cmd/rbac-permissions-check/validate/validate.go
- the action was failing because the github API returns 30 results by default when listing team members, this fix paginates through the responses
=> fix: 🐛 action not getting all team members

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-production/resources/variables.tf
We're using API Gateway to forward requests to our API in Cloud Platform but we used the incorrect URL which meant that we were getting a 404 page when calling our API.
=> Fix Cloud Platform URL used for API Gateway HTTP proxy in production

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-probation-integration-services-prod/resources/scheduled-downtime.tf
to prevent conflicts with existing service accounts in the namespace
=> PI-1016 Set role and rolebinding name for service account

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-development/resources/locals.tf
Use individual API keys so we can better monitor usage statistics. API keys are used in combination with client certificates and IP restrictions.
=> Create an API key for each engineer on the team

namespaces/live.cloud-platform.service.justice.gov.uk/laa-criminal-applications-datastore-staging/resources/api-auth-secrets.tf
This is a first attempt to change from a pull, to a push approach for API secrets. As we can have multiple consumers (for now 2, soon 3), using a `map` and `for_each` can DRY the code and make changes more robust.
Note: this should regenerate existing secrets (change from 20 to 32 chars), that is fine and expected.
=> Refactor secrets generation and injection

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-development/resources/api_gateway.tf
for_each cannot be used with a list of clients on this resource. It will attempt to create multiple secrets with different content but of the same name. A for loop is required to achieve this.
=> Fix multiple kubernetes secret resource

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-pre-production/resources/api_gateway.tf
Use `for` to build up a map, which contains the API Gateway API keys of all the engineers on the team.
=> Fix syntax for kubernetes secret with multiple values

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-production/resources/api_gateway.tf
Use for to build up a map, which contains the API Gateway API keys of all the engineers on the team.
=> Production: Fix syntax for Kubernetes secret with multiple values

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-development/resources/api_gateway.tf
Prevents a race condition by adding an explicit depends_on
=> Add depends_on to force resource execution order

namespaces/live.cloud-platform.service.justice.gov.uk/laa-status-dashboard-development/resources/serviceaccount.tf
Required to create a CI/CD pipeline with GitHub Actions.
=> Create service account for laa-status-dashboard-development

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-development/resources/s3.tf
This makes it consistent with the other environments and allows for automation and scripting.
=> Prefix development to Github trust store

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-development/01-rbac.yaml
This is to allow the DPS Tech team to add and rotate our client credentials for HMPPS Auth.
=> Add DPS Tech to groups allowed to access development

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-pre-production/01-rbac.yaml
This is to allow the DPS Tech team to add and rotate our client credentials for HMPPS Auth.
=> Add DPS Tech to groups allowed to access pre-production

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-production/01-rbac.yaml
This is to allow the DPS Tech team to add and rotate our client credentials for HMPPS Auth.
=> Add DPS Tech to groups allowed to access production

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-dev/resources/elasticache.tf
Upgrade redis type to cache.t4g.micro
Now that we've updated to Redis 7 we can change to a new instance type that should be more cost effective https://user-guide.cloud-platform.service.justice.gov.uk/documentation/deploying-an-app/redis/create.html#table-of-instance-types
=> CAS dev upgrade redis instance

namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-ui-dev/resources/rds.tf
- added `prepare_for_major_upgrade`
- added `db_engine`
- changed `db_engine_version` from 11 -> 14.4 (we are on 11.16 so this is the latest version we can use as per [this documentation](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_UpgradeDBInstance.PostgreSQL.html#USER_UpgradeDBInstance.PostgreSQL.MajorVersion))
- changed `rds_family` from postgres11 to postgres14 
All done as per [the user guide](https://user-guide.cloud-platform.service.justice.gov.uk/documentation/deploying-an-app/relational-databases/upgrade.html#upgrading-to-a-new-major-database-version) - point 5
=> CTSKF-333 - Add upgraded values for PG RDS

namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-ui-dev/resources/rds.tf
- Set `prepare_for_major_upgrade` to false
All done as per [the user guide](https://user-guide.cloud-platform.service.justice.gov.uk/documentation/deploying-an-app/relational-databases/upgrade.html#upgrading-to-a-new-major-database-version) - point 6
=> CTSKF-333 - Set prepare to false

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-test/resources/elasticache.tf
Skip file in place https://github.com/ministryofjustice/cloud-platform-environments/pull/12266
Following the guidance here for jumping straight to redis 7: https://user-guide.cloud-platform.service.justice.gov.uk/documentation/deploying-an-app/redis/upgrade.html#upgrading-a-redis-version
=> CAS test upgraded to Redis 7

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-prod/resources/elasticache.tf
Skip file in place https://github.com/ministryofjustice/cloud-platform-environments/pull/12267
Following the guidance here for jumping straight to redis 7: https://user-guide.cloud-platform.service.justice.gov.uk/documentation/deploying-an-app/redis/upgrade.html#upgrading-a-redis-version
=> CAS prod upgraded to Redis 7

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-prod/resources/elasticache.tf
We tried deploying the redis engine upgrade to 7 at the same time as changing the node type. These need to be in two steps to get through deployment.
We'll move to t4g.small later as a second operation.
=> Fix CAS prod deployment by using compatible elasticache node

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-preprod/resources/elasticache.tf
We tried deploying the redis engine upgrade to 7 at the same time as changing the node type. These need to be in two steps to get through deployment.
We'll move to t4g.micro later as a second operation.
=> Fix CAS preprod deployment by using compatible elasticache node

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-test/resources/elasticache.tf
We tried deploying the redis engine upgrade to 7 at the same time as changing the node type. These need to be in two steps to get through deployment.
We'll move to t4g.micro later as a second operation.
=> Fix CAS test deployment by using compatible elasticache node

namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-prod/07-certificates.yaml
Adds certificates for:
magistrates.judiciary.uk
victimscommissioner.org.uk
publicdefenderservice.org.uk
imb.org.uk
ccrc.gov.uk
=> Add Hale Platform production certificates

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-test/resources/elasticache.tf
The engine update to 7 looks to be complete https://github.com/ministryofjustice/cloud-platform-environments/pull/12509
Now the engine version has been updated to 7 and deployed, we can update our instance to a t4g for efficiency.
=> Change CAS Test Elasticache to t4g.micro

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-preprod/resources/elasticache.tf
This redis 7 engine update looks to be complete https://github.com/ministryofjustice/cloud-platform-environments/pull/12507
Now the engine version has been updated to 7 and deployed, we can update our instance to a t4g for efficiency.
=> Change CAS preprod Elasticache to t4g.micro

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-prod/resources/elasticache.tf
The redis 7 engine update looks to have successfully completed: https://github.com/ministryofjustice/cloud-platform-environments/pull/12508
Now the engine version has been updated to 7 and deployed, we can update our instance to a t4g for efficiency.
=> Change CAS prod Elasticache to t4g.small

namespaces/live.cloud-platform.service.justice.gov.uk/laa-review-criminal-legal-aid-staging/resources/rds.tf
Upgrade to v15 failed as upgrading from v13 -> v15 is too high a jump. Amends [previous change ](https://github.com/ministryofjustice/cloud-platform-environments/pull/12542) to upgrade to v14 instead.
=> Upgrade to postgres v14

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-dev/resources/elasticache.tf
https://user-guide.cloud-platform.service.justice.gov.uk/documentation/other-topics/rotate-tokens-keys.html#aws-rds-db-password
- We are on the latest elasticache cluster module of 6.1.0
=> Rotate CAS dev elasticache auth token

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-test/resources/elasticache.tf
https://user-guide.cloud-platform.service.justice.gov.uk/documentation/other-topics/rotate-tokens-keys.html#aws-rds-db-password
- We are on the latest elasticache cluster module of 6.1.0
=> Rotate CAS test elasticache auth token

namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-ui-uat/resources/rds.tf
- Set `prepare_for_major_upgrade` to false
All done as per [the user guide](https://user-guide.cloud-platform.service.justice.gov.uk/documentation/deploying-an-app/relational-databases/upgrade.html#upgrading-to-a-new-major-database-version) - point 6
=> CTSKF-333 - UAT Set prepare_for_major_upgrade to false

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-prod/resources/elasticache.tf
https://user-guide.cloud-platform.service.justice.gov.uk/documentation/other-topics/rotate-tokens-keys.html#aws-rds-db-password
- We are on the latest elasticache cluster module of 6.1.0
=> Rotate CAS prod elasticache auth token

namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-ui-staging/resources/rds.tf
- added `prepare_for_major_upgrade`
- added `db_engine`
- changed `db_engine_version` from 11 -> 14.4 (we are on 11.16 so this is the latest version we can use as per [this documentation](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_UpgradeDBInstance.PostgreSQL.html#USER_UpgradeDBInstance.PostgreSQL.MajorVersion))
- changed `rds_family` from postgres11 to postgres14 
All done as per [the user guide](https://user-guide.cloud-platform.service.justice.gov.uk/documentation/deploying-an-app/relational-databases/upgrade.html#upgrading-to-a-new-major-database-version) - point 5
=> CTSKF-333 - Staging Update RDS Terraform

namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-ui-staging/resources/rds.tf
- Set `prepare_for_major_upgrade` to false
All done as per [the user guide](https://user-guide.cloud-platform.service.justice.gov.uk/documentation/deploying-an-app/relational-databases/upgrade.html#upgrading-to-a-new-major-database-version) - point 6
=> CTSKF-333 - Staging Set prepare_for_major_upgrade to false

namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-ui-production/resources/rds.tf
- added `prepare_for_major_upgrade`
- added `db_engine`
- changed `db_engine_version` from 11 -> 14.4 (we are on 11.16 so this is the latest version we can use as per [this documentation](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_UpgradeDBInstance.PostgreSQL.html#USER_UpgradeDBInstance.PostgreSQL.MajorVersion))
- changed `rds_family` from postgres11 to postgres14 
All done as per [the user guide](https://user-guide.cloud-platform.service.justice.gov.uk/documentation/deploying-an-app/relational-databases/upgrade.html#upgrading-to-a-new-major-database-version) - point 5
=> CTSKF-333 - Prod Update PG to 14

namespaces/live.cloud-platform.service.justice.gov.uk/laa-assure-hmrc-data-production/resources/pingdom.tf
Change pingdom integration id
Old one was pointing at archived channel #applypivatebeta
and not receiving alerts.
=> laa-assure-hmrc-production: Change pingdom integration id

namespaces/live.cloud-platform.service.justice.gov.uk/token-verification-api-prod/resources/elasticache.tf
Step 1. Move to use default redis 5 param group
=> HAAR-1248: Upgrade token-verification-api-prod to redis 7 - Step 1

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-development/resources/api_gateway.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-development/resources/iam.tf
- Enable access logs for API Gateway. 
- Store log group URL within Kubernetes secret for easy access. _Temporary solution until API Gateway is a supported module_
- Allow API Gateway to perform Cloudwatch actions
=> Enable API Gateway Cloudwatch logging on hmpps-integration-api-development

namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-production/resources/route53.tf
Delegating `rapid.dev.data-platform.service.justice.gov.uk` to analytical-platform-data-engineering-sandbox-a
=> Delegating `rapid.dev.data-platform.service.justice.gov.uk` to analytical-platform-data-engineering-sandbox-a

namespaces/live.cloud-platform.service.justice.gov.uk/laa-estimate-financial-eligibility-for-legal-aid-staging/resources/rds.tf
Temporarily re-enable RDS overnight until we can come up with an elegant way of silencing Pingdom alerts 10pm - 6pm on Staging
=> EL-882: Keep staging RDS instance online overnight

namespaces/live.cloud-platform.service.justice.gov.uk/laa-status-dashboard-development/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-status-dashboard-development/05-servicemonitor.yaml
In order to get application metrics into Prometheus.
=> Add service monitor for laa-status-dashboard-development

namespaces/live.cloud-platform.service.justice.gov.uk/laa-status-dashboard-staging/resources/ecr.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-status-dashboard-staging/resources/elasticache.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-status-dashboard-staging/resources/rds-postgresql.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-status-dashboard-staging/resources/serviceaccount.tf
Adding:
* RDS Postgres
* ECR
* Elasticache
* Service account
Notes:
I have added the `oidc_providers` because I was getting the following [in concourse](https://concourse.cloud-platform.service.justice.gov.uk/builds/21547043#L64527bb1:15:22):
```
Error: Invalid index
on .terraform/modules/ecr_credentials/main.tf line 291, in resource "github_actions_secret" "role_to_assume":
291:   plaintext_value = aws_iam_role.oidc["github"].arn
├────────────────
│ aws_iam_role.oidc is object with no attributes
The given key does not identify an element in this collection value.
```
=> Add resources to laa-status-dashboard-staging

namespaces/live.cloud-platform.service.justice.gov.uk/bold-case-information-dashboard-dev/01-rbac.yaml
Adding the DPS tech team to the BOLD case information dashboard so that the HMPPS Auth team can manage our credentials.
=> Add DPS tech team to BOLD CID

namespaces/live.cloud-platform.service.justice.gov.uk/laa-assure-hmrc-data-staging/certificate.yaml
Remove certificate for old hosted zone
=> laa-asure-hmrc-data-staging: remove certificate for old hosted zone

namespaces/live.cloud-platform.service.justice.gov.uk/laa-assure-hmrc-data-production/certificate.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-assure-hmrc-data-production/resources/route53.tf
Remove unusable hosted zone and certificate
Due to AzureAD authentication redirect URL issues it
is unnecessarily complex to ensure redirecting to the
the correct hosted zone/custom domain, so removing the
superfluous, older one, is simplest.
=> laa-assure-hmrc-data-production: remove unusable hosted zone

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-dev/resources/api_gateway.tf
This should fix the error: `BadRequestException: Access Log format must be single line, new line character is allowed only at end of the format`.
https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/environments-live/jobs/apply-namespace-changes-live/builds/5639
=> Remove newlines from API Gateway CloudWatch logs

namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-dev/resources/rds-instance.tf
=> LASB-1919: Enabled RDS auto start-stop for court data adaptor DEV.

namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-live-dev/resources/service_token_cache.tf
Gone for t4g.medium as this is a live/user facing env and higher traffic than our dev envs, it's live-dev as it's for form owners to publish and test their forms privately.
=> Upgrade redis node type formbuilder-platform-live-dev

namespaces/live.cloud-platform.service.justice.gov.uk/laa-status-dashboard-production/resources/elasticache.tf
Might need to bump it up in the future
=> Use smaller redis instance for laa-status-dashboard-production

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-dev/resources/api_gateway.tf
This will help us debug failing mTLS authentication
=> Enable execution logs for dev API Gateway

namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-test/resources/rds-instance.tf
=> LASB-1919: Enabled RDS auto start-stop in TEST.

namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-uat/resources/rds-instance.tf
=> LASB-1919: Enabled RDS auto start-stop for CDA in UAT

namespaces/live.cloud-platform.service.justice.gov.uk/laa-status-dashboard-production/resources/pingdom.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-status-dashboard-production/resources/versions.tf
Preparing this even if laa-status-dashboard.service.justice.gov.uk hasn't been created yet.
=> Add Pingdom to laa-status-dashboard-production

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-dev/resources/api_gateway.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-dev/resources/s3_truststore.tf
Enable versioning for S3 bucket that holds our truststore.pem for mTLS with API Gateway, and then use latest version.
We realised that API Gateway is using an old version of our truststore.pem and does not update it upon updating the file in S3. Versioning needs to be enabled to do so.
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/api_gateway_domain_name#truststore_uri
=> Add versioning to truststore

namespaces/live.cloud-platform.service.justice.gov.uk/pathfinder-dev/resources/analytical-platform-access.tf
Data Extractor will need to move data into another bucket. Hence the policy changes. 
Reason for change:
A new architecture is being implemented to reduce the number of S3 Buckets being used.
=> Pde 2191 migrate data

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-dev/resources/kubernetes_secrets.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-dev/resources/s3_truststore.tf
This is because Kubernetes secrets that we updated manually that were managed by Terraform were being over-written when the pipeline ran following infrastructure changes. We now store these Kubernetes secrets separately to prevent this issue.
We have also moved our truststore public key (for mutual TLS) out of GitHub and into a Kubernetes secret, to remove the dependency on GitHub.
=> Refactor Kubernetes secrets in dev

namespaces/live.cloud-platform.service.justice.gov.uk/prisoner-content-hub-production/resources/s3-old.tf
The new prod and dev s3 buckets have now been sync'd from staging so are largely in sync with prod.
However we want to start to sync the to the old prod bucket is still the bucket being used, so that they are kept up to date with all the very latest content changes made in the CMS so that we can cut ultimately cut over to the new buckets without loss of data.
=> Allow content hub old prod s3 to sync to new dev and prod s3 buckets.

namespaces/live.cloud-platform.service.justice.gov.uk/jacksapp-dev/resources/elasticsearch.tf, namespaces/live.cloud-platform.service.justice.gov.uk/jacksapp-dev/resources/variables.tf
This cluster will be used to test the elasticsearch api for scripting movement between storage to move the manual step of having to do one at a time from the console
=> feat(Go): Adding ES cluster to dev env

namespaces/live.cloud-platform.service.justice.gov.uk/hmcts-complaints-formbuilder-adapter-staging/resources/rds.tf
Set major upgrade flag and migrate to a t3 instance type as the old type does not support the upgrade to Postgres 14
=> Major upgrade!

namespaces/live.cloud-platform.service.justice.gov.uk/hmcts-complaints-formbuilder-adapter-production/resources/rds.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmcts-complaints-formbuilder-adapter-staging/resources/rds.tf
The prod instance is already on a t3.medium so should support 14.4, which is our max upgrade going from 11.16
=> Upgrade hmcts-adapter-prod to postgres 14.4

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-production/resources/api_gateway.tf
This is because we are renaming our production environment to align with HMPPS naming conventions (specifically, 'prod'). To do so, we're recreating the environment before deleting the old. We must remove the domain name from this environment before we can use it for the new one.
=> Remove custom domain from production environment

namespaces/live.cloud-platform.service.justice.gov.uk/prisoner-content-hub-production/resources/s3-old.tf
See https://github.com/ministryofjustice/cloud-platform-environments/pull/13204 for removal of the s3 bucket in question.
=> 🔥  remove old dev s3 bucket reference in prod bucket policy for content hub. That old dev bucket has been deleted.

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-prod/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-prod/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-prod/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-prod/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-prod/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-prod/resources/ecr.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-prod/resources/kubernetes_secrets.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-prod/resources/locals.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-prod/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-prod/resources/s3_truststore.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-prod/resources/service_account.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-prod/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-prod/resources/versions.tf
This is because we are renaming our environments to align with HMPPS naming conventions (i.e., 'prod' rather than 'production'). To do this we are creating a new namespace and then deleting the old.
=> Create prod environment for HMPPS Integration API

namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-staging/APPLY_PIPELINE_SKIP_THIS_NAMESPACE
Remove APPLY_PIPELINE_SKIP_THIS_NAMESPACE from visit-someone-in-prison-backend-svc-staging namepsace
=> Remove APPLY_PIPELINE_SKIP_THIS_NAMESPACE from namespace

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-dev/resources/locals.tf
Each client we specify as a local gets an API key auto generated. This will be stored in a Kubernetes secret.
=> Create a new API key for MAPPS

namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-dev/resources/claim-criminal-injuries-tempus-queue.tf, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-production/resources/route53.tf
The SSM Parameter is to be overwritten by an MoJ CP team member to avoid putting account IDs in the public repository. As discussed with Jake.
=>  claim-criminal-injuries-dev add tempus queue

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-mercury-submit-dev/resources/elasticache.tf
Error on previous terraform apply saying maintenance window and snapshot window cannot overlap
=> adding explicit redis snapshot window

namespaces/live.cloud-platform.service.justice.gov.uk/ops-pilot-test/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/ops-pilot-test/resources/variables.tf
We've got a new team inbox and renamed Slack channel to match; just updating the contact details to match.
=> Update contact details for ops-pilot-test

namespaces/live.cloud-platform.service.justice.gov.uk/prisoner-content-hub-staging/resources/s3.tf
This is already correct in dev and prod.
=> 🐛  fix CORS origin for prisoner content hub S3 bucket in staging environment.

namespaces/live.cloud-platform.service.justice.gov.uk/prisoner-content-hub-development/resources/s3.tf
This reverts commit 35ff70fc81ab989a9685de5fc9dffcfd2f83e0fd.
Re-enabling versioning did not stop the new log messages being raised.
=> Revert "🔧  test enabling versioning on prisoner content hub dev s3 bucket to see if that accounts for the new log messages occurring on image upload."

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-dev/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-dev/06-certificates.yaml
The user-facing name for this service will primarily be CAS-2 (Community Accommodation Service Tier 2) - although the other tiers have secondary names (`temporary-accommodation` and `approved-premises`) the long-term goal is to bring everything under the CAS banner.
=> rename `supported-accommodation` to `community-accommodation-tier-2`

namespaces/live.cloud-platform.service.justice.gov.uk/abundant-namespace-dev/resources/elasticache.tf
As part of ministryofjustice/cloud-platform#4586.
These are unused.
=> abundant-namespace-dev: remove ElastiCache access keys

namespaces/live.cloud-platform.service.justice.gov.uk/cccd-staging/resources/pingdom.tf
Removes the `sendnotificationwhendown` attribute from `pingdom.tf` so that we receive alerts of downtime sooner.
=> Remove sendnotificationwhendown attribute from CCCD staging pingdom.tf

namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-stag/resources/rds.tf
Terraform wasn't happy about the size of the RDS database being 5gb - increasing to 50gb, any further seems unnecessary as it's a small amount of data being stored.
=> CICA RDS Staging allocation

namespaces/live.cloud-platform.service.justice.gov.uk/cfe-civil-production/04-networkpolicy.yaml
Once the service is cutover we will rely on a stable environment. This should allow all Civil Apply namespaces to call CFE-Civil production using internal routing for speed enhancements
=> CFE-Civil: Add all Civil Apply namespaces to CFE-Civil

namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-reports-prod/resources/dynamodb.tf
Operations Engineering is changing the way we store repository information in reports namespaces. This enables us to perform a more efficient lookup of key values when querying.
=> Change prod hash key to name to meet new structure

namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-reports-dev/resources/dynamodb.tf
Operations Engineering are changing the way we store repository information in the reports namespaces. This enables us to perform a more efficient lookup of key values when querying.
=> Change dev hash key to name to meet new structure

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-interventions-prod/resources/rds-postgres14.tf
We have seen our DB usage hitting 100% and it takes long time to get DB connection. Hence we are changing db instance in production to db.m5.xlarge.
=> Update prod db instance to db.m6g.xlarge

namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-dev/resources/ecr.tf
We are testing moving from long-lived to short-lived credentials. 
Once the new secrets have been generated we can rewrite our git action so it pushes using the new method.
Keeping current secrets in the ecr config  until we have the new method working.
=> Set hale platform dev ecr to generate short lived credentials

namespaces/live.cloud-platform.service.justice.gov.uk/bold-case-information-dashboard-dev/resources/ecr.tf
Remove the long-lived credentials from the ECR module in the Case Information Dashboard
=> Remove long-lived credentials from Case Info Dashboard

namespaces/live.cloud-platform.service.justice.gov.uk/cjs-dashboard-demo/resources/cross-iam-role-sa.tf, namespaces/live.cloud-platform.service.justice.gov.uk/cjs-dashboard-demo/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/cjs-dashboard-demo/resources/versions.tf
The changes made are meant to allow the cjs-dashboard-demo application in CP to access data in an S3 bucket in AP.
I have tried to implement the changes based on work recently done by Yasin Mustafa on another CP application. Link to the thread for Yasin's work here: https://mojdt.slack.com/archives/C57UPMZLY/p1681892544708609
=> cross IAM role to access AP s3 bucket from CP app

namespaces/live.cloud-platform.service.justice.gov.uk/laa-estimate-financial-eligibility-for-legal-aid-production/05-prometheus-custom-rules.yaml
Adding this alert to the repo as per [guidance](https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#advisory-note-1-if-prometheus-gets-re-installed) in case prometheus is ever re-installed
=> EL-941: Add custom prometheus alerts for CCQ production

namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-criminal-legal-aid-staging/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-criminal-legal-aid-staging/05-servicemonitor.yaml
In order to enable prometheus metrics scraping from our staging namespace.
=> Add network policy and service monitor for prometheus

namespaces/live.cloud-platform.service.justice.gov.uk/nettest/resources/serviceaccount.tf
This is to enable deployments via github actions from the modernisation-platform-cp-network-test repository.
=> Add a service account for nettest namespace

namespaces/live.cloud-platform.service.justice.gov.uk/laa-assure-hmrc-data-uat/resources/s3.tf
[laa-assure-hmrc-data-uat] Add `aws_s3_bucket_lifecycle_configuration` to expire all s3 bucket objects after 32 days
The app purges files containing sensitive data 1 month (exactly)
from creation. This is an additional insurance that we are in
compliance with our GDPR requirements.
=> [laa-assure-hmrc-data-uat] Add aws_s3_bucket_lifecycle_configuration to expire all s3 objects

namespaces/live.cloud-platform.service.justice.gov.uk/laa-estimate-financial-eligibility-for-legal-aid-uat/05-prometheus-custom-rules.yaml
The previous query was only firing if there were 2 consecutive non-zero data points.
=> EL-941: Update CCQ uat alert rules

namespaces/live.cloud-platform.service.justice.gov.uk/laa-estimate-financial-eligibility-for-legal-aid-production/05-prometheus-custom-rules.yaml
The previous rule was only firing if we had non-zero values for 2 consecutive data points.
=> EL-941: Update CCQ production alert rules

namespaces/live.cloud-platform.service.justice.gov.uk/laa-estimate-financial-eligibility-for-legal-aid-staging/05-prometheus-custom-rules.yaml
The previous query was only firing if there were 2 consecutive data points
=> EL-941: Update CCQ staging alert rules

namespaces/live.cloud-platform.service.justice.gov.uk/laa-assure-hmrc-data-uat/resources/s3.tf
AP-4065: Amend lifecyle policy to 32 days
Fallback app code that purges sensitive data
after 1 month. 32 days chosen deliberatley to
be one day over longest month to avoid potential
problems with app code attempting to purge keys
that no longer exist.
=> AP-4065: Amend lifecyle policy to 32 days

namespaces/live.cloud-platform.service.justice.gov.uk/laa-assure-hmrc-data-staging/resources/s3.tf
AP-4065: Add lifecycle policy with 32 day expiration
Fallback for app code that purges sensitive data
after 1 month. 32 days chosen deliberately to
be one day over longest month to avoid potential
problems with app code attempting to purge keys
that no longer exist.
=> AP-4065: Add lifecyle policy with 32 expiration

namespaces/live.cloud-platform.service.justice.gov.uk/laa-assure-hmrc-data-production/resources/s3.tf
AP-4065: Add lifecycle policy with 32 day expiration
Fallback for app code that purges sensitive data
after 1 month. 32 days chosen deliberately to
be one day over longest month to avoid potential
problems with app code attempting to purge keys
that no longer exist.
=> AP-4065: Add lifecycle policy with 32 day expiration

namespaces/live.cloud-platform.service.justice.gov.uk/find-unclaimed-court-money-staging/resources/ecr.tf
As per - https://user-guide.cloud-platform.service.justice.gov.uk/documentation/deploying-an-app/container-repositories/deprecating-long-lived-credentials.html#deprecating-long-lived-credentials-for-container-repositories
=> FUM-staging migrate to short lived credentials

namespaces/live.cloud-platform.service.justice.gov.uk/cccd-dev/resources/ecr.tf
https://github.com/ministryofjustice/cloud-platform-environments/pull/14134 enabled short-lived ECR credentials for CCCD, however CircleCI is failing at the `Generate shortlived AWS Keys using CircleCI OIDC token.` stage with the error
```An error occurred (AccessDenied) when calling the AssumeRoleWithWebIdentity operation: Not authorized to perform sts:AssumeRoleWithWebIdentity```
I'm not clear why this is happening but on reviewing the config I noticed that the `github_repositories` attribute is all lower case while in GitHub (and therefore CircleCI) it is in title-case. To try and resolve the failure this corrects the capitalisation.
=> Capitalise CCCD github repo name in ecr.tf

namespaces/live.cloud-platform.service.justice.gov.uk/laa-assure-hmrc-data-uat/resources/ecr.tf
AP-4178: Add ECR lifecycle policy
With the advent of short lived credentials, including
a principle of least privilege, the existing code repo's
script and CI based removal of "old" ECR images will
become unusable. In addition the old approach is discouraged in 
favour of [ECR life cycle policies](https://docs.aws.amazon.com/AmazonECR/latest/userguide/LifecyclePolicies.html#lifecycle_policy_parameters)
reference: [Assure PR](https://github.com/ministryofjustice/laa-assure-hmrc-data/pull/340)
=> AP-4178: Add ECR lifecycle policy

namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-pfg-dash-moj-prod/resources/ecr.tf
Need for vars created in the prod environment to have a prefix of `PROD`
=> Updating ECR secrets/vars prefixes

namespaces/live.cloud-platform.service.justice.gov.uk/family-mediators-api-staging/resources/ecr.tf
Migration to short lived credentials, as per https://user-guide.cloud-platform.service.justice.gov.uk/documentation/deploying-an-app/container-repositories/deprecating-long-lived-credentials.html#deprecating-long-lived-credentials-for-container-repositories
=> Enable oidc provider as Github

namespaces/live.cloud-platform.service.justice.gov.uk/cccd-dev/resources/ecr.tf
Our current approaches to clearing out old ECR images no longer work following the move to short-lived credentials. This adds lifecycle policies to replace them.
=> CCCD: Add ECR lifecycle policies

namespaces/live.cloud-platform.service.justice.gov.uk/contact-moj-production/resources/ecr.tf
Missed this from the guide when adding oidc provider.
=> Add namespace to get credentials in configmap

namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-dev/resources/variables.tf
New git action works with secrets depending on environment so we dont need 'Dev' at end of the name
=> Update Hale Platform Dev github secret names to work with new git action

namespaces/live.cloud-platform.service.justice.gov.uk/laa-estimate-financial-eligibility-for-legal-aid-production/resources/route53.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-estimate-financial-eligibility-for-legal-aid-production/resources/variables.tf
The CCQ service has passed private beta and will be going live on gov.uk, this is to create the DNS for nameservers for use with the new domain.
=> CCQ PROD add route53 terraform file

namespaces/live.cloud-platform.service.justice.gov.uk/laa-estimate-financial-eligibility-for-legal-aid-production/resources/route53.tf
Rename the secret to not use the example prefix and use the teamname instead
=> CCQ PROD rename secret

namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-demo/resources/ecr.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-demo/resources/irsa.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-demo/resources/variables.tf
- Adds lifecycle policy to ecr
- enables the oidc implementation for ecr so we can use short-lived credentials 
- creates irsa - used by s3 
- Rename variables so they can be generic and the same deploy code can be used for each env
- Leave ECR AccessKey variables for now till we are happy finished testing short lived credentials
=> Update Demo Env so it now uses short-lived credentials for ecr and s3

namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-dev/resources/ecr.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-dev/resources/variables.tf
Now uses short lived credentials.
=> Remove Old Hale Platform Dev ECR Access Credentials

namespaces/live.cloud-platform.service.justice.gov.uk/ops-pilot-test/resources/cross-iam-role-sa.tf
Updated the cross-iam-role to have:
```
"glue:GetDatabase",
"glue:GetTable",
"glue:GetPartitions"
```
So that CP app can reference the following Glue Catalog Table: `arn:aws:glue:eu-west-2:*:database/bold_rr_ops_test/mtcars`
=> update perms for cross iam role for athena access

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-events-preprod/resources/outputs-to-ssm-parameters.tf
This is required by a PR coming shortly to make use of these for the activities management service.
=> SAA-803: Adds activities queues to the list of IRSA policies being exported

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-api-dev/resources/s3.tf
If you have the s3:ListBucket permission on the bucket, Amazon S3 will return an HTTP status code 404 (“no such key”) error.
If you don’t have the s3:ListBucket permission, Amazon S3 will return an HTTP status code 403 (“access denied”) error.
Expecting a 404, but getting a 403 and the above suggests it due to missing permission.
=> NN-5273 need list bucket to get the correct error response

namespaces/live.cloud-platform.service.justice.gov.uk/laa-hmrc-interface-uat/resources/ecr.tf
Enable short lived credentials for circleci ECR push and pull
=> AP-4295: Add circleci ECR oidc provider for laa-hmrc-interface-service-api

namespaces/live.cloud-platform.service.justice.gov.uk/hmcts-complaints-formbuilder-adapter-staging/resources/rds.tf
This is because the minor_version_upgrade is set to true and aws managed the upgrades. This is to retrofit the terraform code.
=> Bump db engine version in tf to match the actual version

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-events-dev/resources/hmpps-activities-management.tf
This is for the appointments project so that it can react to the choice selected on the NOMIS cancel on transfer form.
=> SAA-922: Subscribe to appointments-changed offender event in dev

namespaces/live.cloud-platform.service.justice.gov.uk/offender-management-production/resources/rds.tf
The actual DB engine version is 14.7 even though we configured 14.3 - update the TF to match reality and disable minor version upgrades in the future
=> offender-management-production: Upgrade DB engine version to 14.7

namespaces/live.cloud-platform.service.justice.gov.uk/c100-application-staging/resources/rds.tf, namespaces/live.cloud-platform.service.justice.gov.uk/c100-application-staging/resources/variables.tf
aws has upgraded the minor version but the application has also pinned the postgres version causing `apply-live` pipeline failures.
This updates the pin and sets `allow_minor_upgrade_version = "false"`
=> fix: 🐛 rds version for c100 appication

namespaces/live.cloud-platform.service.justice.gov.uk/laa-criminal-applications-datastore-production/01-rbac.yaml
We are assuming this will not break anything, but can't see any other teams doing this.
Is this the correct approach?
We want to limit access to the production namespace so resources can't be easily removed or edited/applied in the CLI with `kubectl`. Still resources are applied via deploy pipeline (service account will have write access).
=> Limit rbac cluster role to view in production namespace

namespaces/live.cloud-platform.service.justice.gov.uk/laa-criminal-applications-datastore-production/01-rbac.yaml
It didn't have the desired effect.
This reverts commit 048f474645866ab9ccbbb61841db544261858a49.
=> Revert "Limit rbac cluster role to view in production namespace (#14448)"

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-probation-integration-services-dev/resources/iam.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-probation-integration-services-dev/resources/serviceaccount.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-probation-integration-services-dev/resources/variables.tf
Trying this out to see if we can use IRSA directly on the CI/CD service account, instead of granting permissions to start pods.
=> PI-1226 Grant IRSA policy to GitHub Actions service account

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-education-and-work-plan-dev/06-certificate.yaml
This PR renames the DNS names for the Education And Work Plan namespace UI and APIs
The previous DNS name for the API was slightly too long in `dev` (and would be even longer as and when we get to `preprod`
Given that our service has been renamed anyway to "Learning and work progress", I've taken the opportunity to rename our DNS names accordingly, as well as dropping the `hmpps-` prefix from the domain names.
The worst case combination for us is the `-api` in `-preprod`. Even with this new name the proposed name for preprod would have been too long!; so for the API I've opted to remove the hyphens; which makes our longest name:
```
learningandworkprogress-api-preprod.hmpps.service.justice.gov.uk
```
(as and when we get to preprod)
=> RR-2 - Renamed certificate dns names

namespaces/live.cloud-platform.service.justice.gov.uk/legal-framework-api-uat/resources/ecr.tf
Add ECR lifecycle policy to legal-framework-api-uat
Remove need for scripted deletion of images using long lived
credentials.
=> AP-4297: Add ECR lifecycle policy to legal-framework-api-uat

namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-production/resources/ecr.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-production/resources/variables.tf
Add new ECR repo with oidc provider and lifecyle policy
To replace the old inconsistently named ECR repo
with consistently named one that implements oidc
for circleci and has a lifecycle policy - to facilitate
migration to IRSA.
THe old ECR repo will be deleted once we have been using
the new for a few days successfully.
=> AP-4293: Add new ECR repo with lifecycle policy

namespaces/live.cloud-platform.service.justice.gov.uk/disclosure-checker-production/05-alerts.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/disclosure-checker-production/secrets.yaml
Add alert manager hooks to Slack. 
As per the steps from https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#create-a-slack-webhook-and-amend-alertmanager
=> Add Disclosure checker AlertManager hooks to Slack

namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-production/resources/ecr.tf
Remove old, unused ECR repo for clamav
[Link to issue](https://dsdmoj.atlassian.net/browse/AP-4321)
We use [hmpps-clamav](http://ghcr.io/ministryofjustice/hmpps-clamav) now and and the old
clamav ECR repos images are not being pulled anywhere and its repo is archived
=> AP-4321: remove old, unused ecr repo for clamav

namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-production/resources/ecr.tf
Reverts ministryofjustice/cloud-platform-environments#14563 and disable deletion_protection. Subsequent PR to remove/destroy the repo should then remove all images.
=> Revert "AP-4321: remove old, unused ecr repo for clamav"

namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-reports-dev/resources/dynamodb.tf
We need to autoscale the write capacity to cope with a large dataset.
=> :zap: Bump autoscale_max_write_capacity to 100

namespaces/live.cloud-platform.service.justice.gov.uk/laa-criminal-applications-datastore-production/resources/api-auth-secrets.tf
Note, this is not a security incident. We are pre-emptively rotating the secrets as we plan to go live with the service in the coming few days, and to ensure our rotation mechanism and services relying on these secrets behave as expected.
=> Rotate secrets to prepare to go live

namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-ui-uat/resources/rds.tf
Making `db_engine_version` match current version of the RDS is to stop apply-live pipeline errors - [apply-live pipeline error here](https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/environments-live/jobs/apply-live/builds/4471#L64ad3dd6:58550)
=> Fix db_engine_version to match what is in place to allow apply-pipeline to run

namespaces/live.cloud-platform.service.justice.gov.uk/laa-estimate-financial-eligibility-for-legal-aid-production/resources/route53.tf
the nameserver list is currently obtained using:
`nameservers = join("\n", aws_route53_zone.eligibility_team_route53_zone.name_servers)`
the output is something like this:
`ns-11.awsdns-11.org\nns-22.awsdns-22.co.uk\nns-33.awsdns-33.com\nns-44.awsdns-44.net`
This PR is to make the nameservers a more readable list with out the `/n`
=> CCQ PROD display nameservers as a list

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-dev/resources/locals.tf
This client is no longer required and will therefore remove the API key, update API Gateway and update our Kubernetes secret for API keys.
=> Remove client for HMPPS Integration API in dev

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-preprod/resources/locals.tf
This client is no longer required and will therefore remove the API key, update API Gateway and update our Kubernetes secret for API keys.
=> Remove client for HMPPS Integration API in pre-prod

namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-criminal-legal-aid-staging/resources/ecr.tf
All our images are tagged one way or another, so in reality, `"tagStatus": "untagged"` was expiring nothing.
Changed to `"tagStatus": "any"` and increased total number of images to keep.
=> Tweak ECR lifecycle policy

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-prod/resources/locals.tf
This client is no longer required and will therefore remove the API key, update API Gateway and update our Kubernetes secret for API keys.
=> Remove client for HMPPS Integration API in prod

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-activities-management-dev/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-activities-management-dev/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-activities-management-dev/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-activities-management-dev/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-activities-management-dev/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-activities-management-dev/05-serviceaccount-circleci.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-activities-management-dev/06-certificate.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-activities-management-dev/resources/elasticache.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-activities-management-dev/resources/irsa.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-activities-management-dev/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-activities-management-dev/resources/rds.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-activities-management-dev/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-activities-management-dev/resources/versions.tf
I am in the process of merging two existing namespaces into one, and renaming this to meeting the naming standards.
`activites-dev` and `activities-api-dev` being merged into `hmpps-activities-management-dev` 
Need both sets active for a period of time whilst moving some of the secrets that are created in other namespaces.
=> SAA-853: Build new alternative namespace for activities services.

namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-staging/resources/ecr.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-staging/resources/irsa.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-staging/resources/variables.tf
- Adds lifecycle policy to ecr
- enables the oidc implementation for ecr so we can use short-lived credentials
- creates irsa - used by s3
- Leave ECR AccessKey variables for now till we are happy finished testing short lived credentials
=> Hale platform staging deployment updates

namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-prod/resources/ecr.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-prod/resources/irsa.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-prod/resources/variables.tf
- Adds lifecycle policy to ecr
- enables the oidc implementation for ecr so we can use short-lived credentials
- creates irsa - used by s3
- Leave ECR AccessKey variables for now till we are happy finished testing short lived credentials
=> Hale platform prod deployment updates

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-events-dev/resources/variables.tf
Typo in new namespace name corrected for domain event topic secret.
Sorry Tom, there was a small typo that I missed in previous PR.
=> SAA-853: Activities DEV namespace typo.

namespaces/live.cloud-platform.service.justice.gov.uk/justice-gov-uk-archiver-dev/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/justice-gov-uk-archiver-dev/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/justice-gov-uk-archiver-dev/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/justice-gov-uk-archiver-dev/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/justice-gov-uk-archiver-dev/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/justice-gov-uk-archiver-dev/resources/ecr.tf, namespaces/live.cloud-platform.service.justice.gov.uk/justice-gov-uk-archiver-dev/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/justice-gov-uk-archiver-dev/resources/s3.tf, namespaces/live.cloud-platform.service.justice.gov.uk/justice-gov-uk-archiver-dev/resources/serviceaccount.tf, namespaces/live.cloud-platform.service.justice.gov.uk/justice-gov-uk-archiver-dev/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/justice-gov-uk-archiver-dev/resources/versions.tf
A new environment to bring in our archive process application for https://www.justice.gov.uk/
An empty Cloudfront template file is included, as this will need to be configured to set up a distribution that can serve the archive from an S3 bucket. This resource is not directly needed to begin the archiving process. Development of this template however is underway.
=> Justice Gov UK Archiver init

namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-staging/resources/variables.tf
Rename variables so they can be generic and the same deploy code can be used for each env
=> Hale platform staging var names

namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-prod/resources/variables.tf
Rename variables so they can be generic and the same deploy code can be used for each env
=> Hale Platform Prod - Rename Variables

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-activities-management-preprod/05-serviceaccount-circleci.yaml
This is related to the conversation here - https://mojdt.slack.com/archives/C57UPMZLY/p1689928407472739
As of K8s v1.24 service accounts do not implicitly create a secret in the namespace - this must now be created explicitly.
I'll get this in and check that the bootstrap process (which configures circle CI deployments into CP, amongst other things) works ok with it.
=> SAA-1014: Activities preprod namespace - explicit creation of secret for service account

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-activities-management-preprod/05-serviceaccount-circleci.yaml
This PR implements the link between a secret holding the service account token and the service account, to replicate the pre V1.24 behaviour which automatically created a secret with the SA token in it.
This is required for the current version of bootstrap to work - though its being looked at, with other potential ways to obtain the circleci-token.
=> SAA-1014: Activities preprod - linking the service account to a token secret (for bootstrap)

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-test/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-test/06-certificates.yaml
We would like to add CAS2 to the `hmpps-community-accommodation-test` namespace.
=> add CAS2 test environment

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-events-prod/resources/hmpps-activities-management.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-events-prod/resources/outputs-to-ssm-parameters.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-events-prod/resources/variables.tf
Will create a subscription and queue to the HMPPS domain event topic and add secrets into the production namespace for activities management.
=> SAA-767 domain events for activities prod

namespaces/live.cloud-platform.service.justice.gov.uk/check-financial-eligibility-uat/resources/ecr.tf
We are about to start decommissioning this service and, following the steps on https://user-guide.cloud-platform.service.justice.gov.uk/documentation/deploying-an-app/cleaning-up.html are turning off deletion protection
=> CFE: set ECR deletion_protection to false

namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-dev/resources/serviceaccount.tf
Provide access to run a autoscaling of our pods as we get the current [error message](https://github.com/ministryofjustice/hale-platform/actions/runs/5626229760/job/15283374004):
forbidden: User "system:serviceaccount:***:cd-serviceaccount" cannot get resource "horizontalpodautoscalers"
=> Add access to allow autoscaling to our pods

namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-criminal-legal-aid-staging/resources/pingdom.tf
This will probe the datastore from Apply service, given datastore is an internal service not reachable from outside (no ingress).
=> Add pingdom check

namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-dev/resources/serviceaccount.tf
Having "autoscaling" in the group API seemed to introduce an issue with the elements in the resource list, specifically secrets.
=> Remove autoscaling label used in API group

namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-criminal-legal-aid-production/resources/pingdom.tf
This will probe the datastore from Apply service, given datastore is an internal service not reachable from outside (no ingress).
=> Add pingdom check (prod namespace)

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-prod/resources/pingdom.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-prod/resources/versions.tf
We follow the CP documentation to create a basic health check for each production service[1].
We try to follow the tagging documentation as best we can[2]
Slack integrations requested here[3]
[1] https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-pingdom-checks.html#create-a-pingdom-check
[2] https://technical-guidance.service.justice.gov.uk/documentation/standards/documenting-infrastructure-owners.html#tags-you-should-use
[3] https://github.com/ministryofjustice/cloud-platform/issues/4665
=> Add CAS production checks for availability with Pingdom

namespaces/live.cloud-platform.service.justice.gov.uk/abundant-namespace-dev/resources/aurora.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-intelligence-test/resources/rds-aurora.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-pin-phone-monitor-dev/resources/rds-aurora.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-pin-phone-monitor-qa/resources/rds-aurora.tf, namespaces/live.cloud-platform.service.justice.gov.uk/manage-intelligence-dev/resources/rds-aurora.tf
Related to [Deprecating long-lived credentials for modules](https://user-guide.cloud-platform.service.justice.gov.uk/documentation/other-topics/deprecating-long-lived-credentials.html) and ministryofjustice/cloud-platform#4546, ministryofjustice/cloud-platform#4372.
The use of RDS Aurora is not documented; though teams who use this (PCMS and IMS) have been made aware of this early removal.
=> rds-aurora: deprecate access keys for non-production namespaces

namespaces/live.cloud-platform.service.justice.gov.uk/laa-not-on-libra-auto-search-application-dev/resources/main.tf
Adds team github slug to default provider so all resources created are visible.
=> Adds team slug to default provider default_tags.

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-prod/resources/pingdom.tf
Pingdom is currently unable to detect the CAS services as they aren’t publicly accessible services.
We think there’s two options:
1. Go via the health-kick service which has existing permission to access the health check pages of our service and is used by other services[1]
2. Add all Pingdom IP addresses into each services helm allowlist [2]
On the one hand we are dependant on health-check service being available, on the other we have to maintain a long list of Pingdom IP addresses which could become out of date. Both can generate false positives. On balance we think the health-kick service is worth a go given it’s used by other services already.
[1] https://github.com/ministryofjustice/cloud-platform-environments/blob/6114e5cc0d24d6afc1f2b62c66c496283a9baf3a/namespaces/live.cloud-platfor …
=> CAS Pingdom checks are made via the health-kick service

namespaces/live.cloud-platform.service.justice.gov.uk/track-a-query-development/resources/s3.tf
- Removes long lived keys
- Removes old live1 domain
- Adds localhost domain so bucket can be used from local environment
=> Add localhost domain for track-a-query-development

namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-demo/resources/serviceaccount.tf
This change allows us to deploy HPA functionality into the namespace.
=> Add HPA autoscaling to Service Account

namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-prod/resources/serviceaccount.tf
This change allows us to deploy HPA functionality into the namespace.
=> Add autoscaling resource to Service Account

namespaces/live.cloud-platform.service.justice.gov.uk/laa-review-criminal-legal-aid-production/resources/pingdom.tf
This will probe the datastore from review service, given datastore is an internal service not reachable from outside (no ingress).
=> Pingdom check for review prod namespace

namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-uat/05-prometheus.yaml
Split out diskspace threshold not reported rule
To more easily tell the difference between threshold
exceeded and not reported in the channel and apply different
timeframe for not reported rule.
=> [laa-apply-for-legalaid-uat] Split out diskspace threshold not reported rule

namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-staging/05-prometheus.yaml
Split out diskspace threshold not reported rule
To more easily tell the difference between threshold
exceeded and not reported in the channel and apply different
timeframe for not reported rule.
=> [laa-apply-for-legalaid-staging] Split out diskspace threshold not reported rule

namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-production/05-prometheus.yaml
Split out diskspace threshold not reported rule
To more easily tell the difference between threshold
exceeded and not reported in the channel and apply different
timeframe for not reported rule.
AND correct severity level for existing rules - which means they may
not have been being reported to the relevant channel.
=> [laa-apply-for-legalaid-production] Split out diskspace threshold not reported rule

namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-prod/resources/irsa.tf
Change Orchestration service to use IRSA
Prior to this PR were only using SNS in VSiP for posting domain events with IRSA, we did not cover listening on hmpps_prison_visits_event queue the orchestration service they are in the same name space (VSiP, orchestration).
THIS SHOULD NOT BE MERGED until we a release Orchestration service released next Tuesday/Wensday.
=> VB-2578 PROD - Orchestration service, Update SQS/SNS queue updates IRSA

namespaces/live.cloud-platform.service.justice.gov.uk/cccd-dev/resources/rds_read_replica.tf
Add a read replica of the dev database in order to allow the data reporting team to make analytics queries and the like.
=> CCCD-DEV Add a read replica of the dev database

namespaces/live.cloud-platform.service.justice.gov.uk/cccd-dev/resources/rds_read_replica.tf
Update the max allocated storage size of the read replica by 10 percent.
This fixes an issue with the read replica deployment that says:
`InvalidParameterCombination: The maximum allocated storage must be increased by at least 10 percent.`
=> CCCD-DEV Update the max allocated storage of the read replica

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-accredited-programmes-dev/resources/elasticache.tf
We've been advised to update Elasticache-Redis to the latest version by the Cloud Platform team and to rotate secrets as part of the CircleCI incident remediation.
This PR does both, following instructions here:
1. https://user-guide.cloud-platform.service.justice.gov.uk/documentation/deploying-an-app/redis/upgrade.html#engine-version-and-parameter-groups
2. https://user-guide.cloud-platform.service.justice.gov.uk/documentation/other-topics/rotate-tokens-keys.html#aws-elasticache-auth-token
We've previously added a skip file in #15257 to tell the apply pipeline to skip this namespace.
=> Update Elasticache-Redis for the Accredited Programmes dev namespace & rotate secrets

namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-staging/resources/rds.tf
* Revert db_engine_version to just `14`
* Downsize instance class to t4g.small
* Remove the prepare_for_major_upgrade flag
=> Civil Apply Staging: Post DB upgrade tidy

namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-production/resources/rds.tf
This is to help with the upgrade to v14 of postgres so we have added the prepare_for_major_upgrade = true flag too
This will be merged by the Civil Apply team out of hours to avoid disruptive downtime
=> Civil Apply Production: Increase instance class size

namespaces/live.cloud-platform.service.justice.gov.uk/legal-framework-api-staging/resources/rds.tf
This was added during the 11 > 14 upgrade and is preventing minor system updates
=> LFA-staging: Remove the postgres version lock

namespaces/live.cloud-platform.service.justice.gov.uk/hosting-data-production/resources/ecr.tf, namespaces/live.cloud-platform.service.justice.gov.uk/ky-first-cp-app-dev/resources/ecr.tf, namespaces/live.cloud-platform.service.justice.gov.uk/ky-first-cp-app-dev/resources/serviceaccount.tf
Both of these namespaces/GitHub repositories already use OpenID Connect, so this removes their access keys.
=> hosting-data-production, ky-first-cp-app-dev: bump cloud-platform-terraform-ecr-credentials to v6.0.0

namespaces/live.cloud-platform.service.justice.gov.uk/legal-framework-api-production/resources/rds.tf
This was added during the 11 > 14 upgrade and is preventing minor system updates
=> LFA-production: Remove the postgres version lock

namespaces/live.cloud-platform.service.justice.gov.uk/use-of-force-prod/resources/analytical-platform-access.tf
The paths incorrectly used a variable name, meaning data was not flowing through as intended. This corrects those paths.
=> correct s3 paths for hmpps-use-of-force-prod

namespaces/live.cloud-platform.service.justice.gov.uk/ops-pilot-test/resources/ecr.tf
In preparation for removing the ops-pilot-test namespace, remove the ECR deletion protection.
=> Remove ECR protection from ops-pilot-test

namespaces/live.cloud-platform.service.justice.gov.uk/bold-case-information-dashboard-dev/resources/ecr.tf
Set the deletion protection flag to false for the bold-case-information-dashboard-dev environment in preparation for deletion.
Preparing to delete this namespace as the data platform team will be taking over our deployment.
=> Remove ECR protection from case info dashboard

namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-bold-case-info-dashboard-dev/resources/variables.tf
Apologies for this error, minor PR to correct Slack name in `.../variables.tf`. This was breaking `apply-live`.
=> Remove # from slack name

namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-production/resources/rds.tf
* Remove `.7` from db_engine_version to prevent version locking 
* change db_instance_class to `db.t4g.small` to allow for future upgrades 
* remove the prepare_for_major_upgrade flag
=> Civil-Apply-Production: conclude postgres 14 upgrade

namespaces/live.cloud-platform.service.justice.gov.uk/cjs-dashboard-development/resources/cross-iam-role-sa.tf, namespaces/live.cloud-platform.service.justice.gov.uk/cjs-dashboard-development/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/cjs-dashboard-development/resources/versions.tf
Adding a cross-iam-role-sa.tf to create a service account, enabling access to a named S3 bucket in AP for the cjs-dashboard-development application.
=> Implement cross-iam-role-sa.tf for cjs-dashboard-development

namespaces/live.cloud-platform.service.justice.gov.uk/laa-cla-backend-staging/resources/ecr.tf
PR to allow laa-cla-backend to use short lived credentials for pushing docker image using circleci. Note that only one ecr module for all namespaces.
[Following these instructions](https://user-guide.cloud-platform.service.justice.gov.uk/documentation/deploying-an-app/container-repositories/deprecating-long-lived-credentials.html#migrating-to-short-lived-credentials-for-circleci)
=> LGA-2576 enable OIDC for circleci

namespaces/live.cloud-platform.service.justice.gov.uk/laa-fee-calculator-ui-dev/resources/ecr.tf
[Following the cloud platform user guide for migrating to short-lived credentials for GithubActions](https://user-guide.cloud-platform.service.justice.gov.uk/documentation/deploying-an-app/container-repositories/deprecating-long-lived-credentials.html#migrating-to-short-lived-credentials-for-github-actions)
- Enable oidc implementation of GitHub Actions via the ECR resource configuration file
- Set a namespace in the ecr resource config
=> laa-fee-calculator-ui-dev Initiate short lived ecr credentials for the DEV Environment

namespaces/live.cloud-platform.service.justice.gov.uk/cjs-dashboard-production/resources/cross-iam-role-sa.tf, namespaces/live.cloud-platform.service.justice.gov.uk/cjs-dashboard-production/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/cjs-dashboard-production/resources/versions.tf
Adding a cross-iam-role-sa.tf to create a service account, enabling access to a named S3 bucket in AP for the cjs-dashboard-production application.
=> Implement cross-iam-role-sa.tf for cjs-dashboard-production

namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-report-service-dev/04-networkpolicy.yaml
Removing -dev suffix for allow-prometheus-scraping network policy.
=> DCES-Report-Service Monitoring Change

namespaces/live.cloud-platform.service.justice.gov.uk/cccd-dev/05-rbac-dart-read-only.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/cccd-dev/06-rbac-role-bind-dart-team.yaml
Add a read only RBAC role for a temporary github team.
this is to test whether we can give a data reporting team pod proxy access to our rds database using kubectl.
This is only temporary whilst i do a proof of concept that we can limit kubectl access to our resources
=> CCCD-DEV Add a new RBAC role for testing purposes

namespaces/live.cloud-platform.service.justice.gov.uk/money-to-prisoners-test/resources/irsa.tf, namespaces/live.cloud-platform.service.justice.gov.uk/money-to-prisoners-test/resources/rds.tf, namespaces/live.cloud-platform.service.justice.gov.uk/money-to-prisoners-test/resources/s3.tf
… in preparation for when the long-lived access key will not be available
=> Stop exporting `money-to-prisoners-test` RDS & S3 access key into k8s secret

namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-production/05-prometheus.yaml
We had shifted v1/bank_statements_controller into the 10 second window as file uploads regularly exceed 2 seconds and we, and users, are fine with it.  This is now being shown in the logs as v1/bank_statements so this updates the rule to prevent false positives in the alerts channel
=> Civil Apply Production: Update long running prometheus rules

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-dpr-fake-dps-service/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-dpr-fake-dps-service/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-dpr-fake-dps-service/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-dpr-fake-dps-service/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-dpr-fake-dps-service/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-dpr-fake-dps-service/05-certificates.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-dpr-fake-dps-service/resources/api-token.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-dpr-fake-dps-service/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-dpr-fake-dps-service/resources/rds-postgresql.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-dpr-fake-dps-service/resources/serviceaccount.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-dpr-fake-dps-service/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-dpr-fake-dps-service/resources/versions.tf
Implements a namespace to support a fake DPS service to be used initially as a PoC, and later for system testing.
=> [DPR-636] Fake DPS Service

namespaces/live.cloud-platform.service.justice.gov.uk/laa-cla-frontend-staging/resources/ecr.tf
Add in required variables so can use configmap for short lived creds
=> LGA-2584 update ecr.tf to allow short lived credentials

namespaces/live.cloud-platform.service.justice.gov.uk/laa-estimate-financial-eligibility-for-legal-aid-production/resources/route53.tf
Have added DNS records to prevent email spoofing of our production domain, following this [guidance](https://www.gov.uk/guidance/protect-domains-that-dont-send-email). Ideally would like a thorough review, as I may have missed something 
I could not create a valid null MX record.
=> EL-1101: prevent e-mail spoofing (CCQ)

namespaces/live.cloud-platform.service.justice.gov.uk/laa-estimate-financial-eligibility-for-legal-aid-production/resources/route53.tf
Updating SPF record - “name” of the SPF record shouldn’t have the protocol “https://” in.
=> EL-1101: Update SPF record

namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-repos/resources/repos.tf, namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-repos/resources/variables.tf
Missed the namespace out, using the var so that it will generate a configmap in formbuilder-repos
=> Add namespace to fb-editor-web ecr module

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-dev/resources/irsa.tf
We have three frontend apps that need access to HMPPS Audit SQS:
* Approved Premises (CAS1) https://github.com/ministryofjustice/hmpps-approved-premises-ui
* CAS2 https://github.com/ministryofjustice/hmpps-community-accommodation-tier-2-ui
* Temporary Accommodation (CAS3) https://github.com/ministryofjustice/hmpps-temporary-accommodation-ui 
This commit adds the configuration for these three apps in dev.
=> add irsa modules for CAS UI applications in dev

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-preprod/resources/irsa.tf
We have three frontend apps that need access to HMPPS Audit SQS:
* Approved Premises (CAS1) https://github.com/ministryofjustice/hmpps-approved-premises-ui
* CAS2 https://github.com/ministryofjustice/hmpps-community-accommodation-tier-2-ui
* Temporary Accommodation (CAS3) https://github.com/ministryofjustice/hmpps-temporary-accommodation-ui
This commit adds the configuration for these three apps in preprod, should match what we've added in dev [1]
[1] https://github.com/ministryofjustice/cloud-platform-environments/pull/15718
=> add irsa modules for CAS UI applications in preprod

namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-repos/resources/repos.tf
`fb-builder` is a custom image that lives in an ECR repository we access using static creds then build our components from that docker context.
Adding these values to this ECR module should generate a configmap I can use to pull a role arn, and use that to pull the build image as described here https://circleci.com/docs/pull-an-image-from-aws-ecr-with-oidc/ - replacing our static ECR credentials used to pull this image.
=> Generate a configmap for fb-builder

namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering/resources/dynamodb-ap-gh-collab-repo.tf, namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering/resources/s3-ap-gh-collab-repo.tf
This isn't actually used. We actually use the IAM user created in another file.
=> :fire: Remove IAM access key id and secret

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-prod/resources/irsa.tf
We have three frontend apps that need access to HMPPS Audit SQS:
* Approved Premises (CAS1) https://github.com/ministryofjustice/hmpps-approved-premises-ui
* CAS2 https://github.com/ministryofjustice/hmpps-community-accommodation-tier-2-ui
* Temporary Accommodation (CAS3) https://github.com/ministryofjustice/hmpps-temporary-accommodation-ui
This commit adds the configuration for these three apps in preprod, should match what we've added in dev [1]
[1] https://github.com/ministryofjustice/cloud-platform-environments/pull/15718
=> add irsa modules for CAS UI applications in prod

namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-dev/resources/irsa.tf
Currently running `aws ecr list-images --repository-name jotw-content-devs/hale-platform-dev-feed-parser-ecr` inside our namespaces' service pod we get a permissions error:
```An error occurred (AccessDeniedException) when calling the ListImages operation: User: arn:aws:sts::754256621582:assumed-role/cloud-platform-irsa-1d5cba8b376d92aa-live/botocore-session-1692802205 is not authorized to perform: ecr:ListImages on resource: arn:aws:ecr:eu-west-2:754256621582:repository/jotw-content-devs/hale-platform-dev-feed-parser-ecr because no identity-based policy allows the ecr:ListImages action```
By adding the IRSA policy to our two ECR modules I'm hoping this gives us access.
=> Provide access to our ECR repositories via the service pod

namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-production/resources/outputs.tf, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-production/resources/route53.tf
We would like to set up redirection for migrated apps from old domain to the new fqdn. As such, we want to bring the old zone under CP management.
=> Bring legacy apps domain under Cloud Platform Management

namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-bold-case-info-dashboard-dev/01-rbac.yaml
In line with [the request here](https://mojdt.slack.com/archives/C02S71KUBED/p1691742113287679?thread_ts=1691667201.530509&cid=C02S71KUBED), adding the HMPPS Auth team to the dev rbac file so they can manage our credentials.
=> Add HMPPS Auth team to rbac

namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-bold-case-info-dashboard-prod/01-rbac.yaml
In line with [the request here](https://mojdt.slack.com/archives/C02S71KUBED/p1691742113287679?thread_ts=1691667201.530509&cid=C02S71KUBED), adding the HMPPS Auth team to the prod rbac file so they can manage our credentials.
=> Add HMPPS Auth to prod rbac

namespaces/live.cloud-platform.service.justice.gov.uk/laa-review-criminal-legal-aid-staging/resources/ecr.tf
Adds github oidc config to `ecr.tf` to enable short lived creds in github actions for crime review staging namespace.
=> Add oidc config for github actions ecr

namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-criminal-legal-aid-staging/resources/ecr.tf
Adds github oidc config to ecr.tf to enable short lived creds in github actions for crime apply staging namespace.
=> Add oidc config for github actions ecr - crime apply staging

namespaces/live.cloud-platform.service.justice.gov.uk/laa-criminal-applications-datastore-staging/resources/ecr.tf
Adds github oidc config to ecr.tf to enable short lived creds in github actions for crime apply datastore staging namespace.
=> Add oidc config for github actions ecr - staging datastore

namespaces/live.cloud-platform.service.justice.gov.uk/cccd-dev-lgfs/resources/irsa.tf
One `role_policy_arn` in our `irsa.tf` was incorrectly described as being for SQS when it is actually for SNS. For clarity, fix the label (and remove the related TODO comment).
=> cccd-dev-lgfs: Rename SQS role_policy_arn to SNS

namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-dev/resources/messaging-queues.tf
=> LASB-2396: Granted readMessage access to the MAAT API IAM Role

namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-repos/resources/repos.tf
We have generated these for some of our repos already and updated the pipelines to migrate away from long lived ECR credentials. This PR should generate the necessary configmaps for the remaining repos, I've put them all in one PR as it is all in the same namespace.
=> Generate configmaps for the ECR repos in formbuilder_repos

namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-prod/resources/brookhouse-route53.tf
Remove the A records for brookhouseinquiry.org.uk so that it deletes all A records pointing to our old load balancer. This then allows us to trigger a new A record pointing to the new CloudPlatform LB.
=> Remove A records pointing to old LB

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-dev/resources/ecr.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-dev/resources/variables.tf
We need to stop using long term credentials and move to using short lived credentials for ecr as notified by cloud platform. Pr raised as per the following [guidance](https://user-guide.cloud-platform.service.justice.gov.uk/documentation/deploying-an-app/container-repositories/deprecating-long-lived-credentials.html#migrating-to-short-lived-credentials-for-circleci).
- Added attributes to ecr to enable short term credentials
=> Updated ecr credentials and added GitHub name variable

namespaces/live.cloud-platform.service.justice.gov.uk/cccd-dev/resources/messaging.tf
Update permissions to allow all actions on SQS in dev
This is so that we can test cross account SQS access with the LAA Landing zone
=> Update SQS permissions for CCCD-DEV

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-preprod/resources/ecr.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-preprod/resources/variables.tf
We need to stop using long term credentials and move to using short lived credentials for ecr as notified by cloud platform. Pr raised as per the following [guidance](https://user-guide.cloud-platform.service.justice.gov.uk/documentation/deploying-an-app/container-repositories/deprecating-long-lived-credentials.html#migrating-to-short-lived-credentials-for-circleci).
- Added attributes to ecr to enable short term credentials
=> Update ECR module to use long-lived credentials in pre-prod

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-preprod/resources/ecr.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-preprod/resources/variables.tf
We need to stop using long term credentials and move to using short lived credentials for ecr as notified by cloud platform. Pr raised as per the following [guidance](https://user-guide.cloud-platform.service.justice.gov.uk/documentation/deploying-an-app/container-repositories/deprecating-long-lived-credentials.html#migrating-to-short-lived-credentials-for-circleci).
- Added attributes to ecr to enable short term credentials
=> Update ECR module to use long-lived credentials in prod

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-staging/resources/redis.tf
We noticed this warning in the logs of one of the Sidekiq pods:
```
WARNING: Your Redis instance will evict Sidekiq data under heavy load.
The 'noeviction' maxmemory policy is recommended (current policy: 'volatile-lru').
See: https://github.com/sidekiq/sidekiq/wiki/Using-Redis#memory
```
This could be the reason that we have had notifications go missing at times, so we have followed the recommendation.
=> MAP-269: Change BaSM API Redis maxmemory-policy to noeviction

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-dev/resources/kubernetes_secrets.tf
We use the Cloud Platform modules for ECR and S3. As long-lived access credentials are being deprecated for them, we need to remove them from our Kubernetes secret.
- Remove IAM access keys for ECR and S3 in our Kubernetes secret in dev.
=> Remove long-lived access credentials in Kubernetes secrets for dev

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-preprod/resources/kubernetes_secrets.tf
We use the Cloud Platform modules for ECR and S3. As long-lived access credentials are being deprecated for them, we need to remove them from our Kubernetes secret.
- Remove IAM access keys for ECR and S3 in our Kubernetes secret in pre-prod.
=> Remove long-lived access credentials in Kubernetes secrets for pre-prod

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-prod/resources/kubernetes_secrets.tf
We use the Cloud Platform modules for ECR and S3. As long-lived access credentials are being deprecated for them, we need to remove them from our Kubernetes secret.
- Remove IAM access keys for ECR and S3 in our Kubernetes secret in prod.
=> Remove long-lived access credentials in Kubernetes secrets for prod

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-uat/resources/redis.tf
We noticed this warning in the logs of one of the Sidekiq pods:
```
WARNING: Your Redis instance will evict Sidekiq data under heavy load.
The 'noeviction' maxmemory policy is recommended (current policy: 'volatile-lru').
See: https://github.com/sidekiq/sidekiq/wiki/Using-Redis#memory
```
This could be the reason that we have had notifications go missing at times, so we have followed the recommendation.
This PR updates UAT.
=> MAP-269: Change BaSM API Redis maxmemory-policy to noeviction (UAT)

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-preprod/resources/redis.tf
We noticed this warning in the logs of one of the Sidekiq pods:
```
WARNING: Your Redis instance will evict Sidekiq data under heavy load.
The 'noeviction' maxmemory policy is recommended (current policy: 'volatile-lru').
See: https://github.com/sidekiq/sidekiq/wiki/Using-Redis#memory
```
This could be the reason that we have had notifications go missing at times, so we have followed the recommendation.
This PR updates preprod.
=> MAP-269: Change BaSM API Redis maxmemory-policy to noeviction (preprod)

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-production/resources/redis.tf
We noticed this warning in the logs of one of the Sidekiq pods:
```
WARNING: Your Redis instance will evict Sidekiq data under heavy load.
The 'noeviction' maxmemory policy is recommended (current policy: 'volatile-lru').
See: https://github.com/sidekiq/sidekiq/wiki/Using-Redis#memory
```
This could be the reason that we have had notifications go missing at times, so we have followed the recommendation.
This PR updates production.
=> MAP-269: Change BaSM API Redis maxmemory-policy to noeviction (prod)

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-proceeding-test/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-proceeding-test/resources/secret.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-proceeding-test/resources/variables.tf
**NOTE: PR includes a team_name change, so will manually need to arrange for the current ECR to be emptied of images in order for it to be deleted and recreated with the new name.**
=> LCAM 878 Added configuration for ccp test client creds in secrets manager

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-proceeding-uat/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-proceeding-uat/resources/secret.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-proceeding-uat/resources/variables.tf
**NOTE: PR includes a team_name change, so will manually need to arrange for the current ECR to be emptied of images in order for it to be deleted and recreated with the new name.**
=> LCAM 878 Added CCP UAT client creds to secret manager

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-proceeding-prod/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-proceeding-prod/resources/secret.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-proceeding-prod/resources/variables.tf
**NOTE: PR includes a team_name change, so will manually need to arrange for the current ECR to be emptied of images in order for it to be deleted and recreated with the new name.**
=> LCAM 878 Added ccp prod client creds to secret manager

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-education-and-work-plan-preprod/resources/serviceaccount-circleci.tf
Add serviceaccount rules to circleci SA; specifically `networkpolicies` and `servicemonitors` as these are missing from the [serviceaccount module](https://github.com/ministryofjustice/cloud-platform-terraform-serviceaccount/blob/main/variables.tf#L20)
=> RR-279 - Add serviceaccount rules to circleci SA

namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-report-service-prod/resources/variables.tf
Reverting back to crime-apps as dces-team will require overhead.
=> DCES-Revert Team Name

namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-dev/resources/irsa.tf
Allow access to an s3 bucket in another aws account so that I can run `aws s3 sync` and transfer the contents of this old bucket to our new CloudPlatform bucket.
=> Add lawcom s3 bucket policy

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-test/resources/irsa.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-test/resources/variables.tf
We have three frontend apps that need access to HMPPS Audit SQS:
Approved Premises (CAS1)
https://github.com/ministryofjustice/hmpps-approved-premises-ui CAS2
https://github.com/ministryofjustice/hmpps-community-accommodation-tier-2-ui Temporary Accommodation (CAS3)
https://github.com/ministryofjustice/hmpps-temporary-accommodation-ui
This commit adds the configuration for these three apps in test.
=> Add irsa config for CAS applications in `test`

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-preprod/resources/rds.tf
We want to be able to run a scheduled job to copy prod data into pre-prod to give us a more realistic pre-prod environment for testing.
This is based off the work done by the interventions team in:
https://github.com/ministryofjustice/hmpps-interventions-service/blob/main/helm_deploy/hmpps-interventions-service/templates/cronjob-prod-to-preprod-refresh.yaml
Once we have the variables injected, we can add the job to our Helm config
=> Inject pre-prod DB credentials into production

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-education-and-work-plan-dev/06-certificate.yaml
Try to fix Education and Work Plan `dev` certificates by using a shorter CN, with a series of longer SANs
This is in relation to this slack conversation: https://mojdt.slack.com/archives/C57UPMZLY/p1694184747281519
We've had discussions in the past about using a short CN with a series of shorter SANs because our service name is long and in one case our primary name would exceed the 64 character limit (`learning-and-work-progress-api-preprod.hmpps.service.justice.gov.uk`).
We worked around this at the time by shortening it to `learningandworkprogress-api-preprod.hmpps.service.justice.gov.uk` (which is exactly 64 characters)
We currently have a problem with `dev`, and whilst its longest CN is below 64 characters (`learningandworkprogress-api-dev.hmpps.service.justice.gov.uk`), trying to use …
=> Try to fix Education and Work Plan dev certificates 

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-education-and-work-plan-preprod/06-certificate.yaml
Fix Education and Work Plan preprod certificates by using a shorter CN, with a series of longer SANs
This PR is the same change we have just made and proved in `dev` via [this PR](https://github.com/ministryofjustice/cloud-platform-environments/pull/16415)
=> Fix Education and Work Plan preprod certificates 

namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-test-production/resources/shared-secrets.tf
This will be used to apply the bucket arn to the service account in the saas-test namespace (saas-test publishes forms to test-dev and test-production from one service account, access will follow in next PR)
=> Add shared secret to formbuilder-platform-test-production

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-education-and-work-plan-prod/06-certificate.yaml
Fix Education and Work Plan prod certificates by using a shorter CN, with a series of longer SANs
This PR is the same change we have just made and proved in dev via [this PR](https://github.com/ministryofjustice/cloud-platform-environments/pull/16415)
=> Fix Education and Work Plan prod certificates

namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-prod/resources/layobservers-route53.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-prod/resources/ppo-route53.tf
Merge all TXT records into one array to avoid duplication and concourse flagging up "already added" notification. Also add correct zone_id for cloudfront.
=> Add correct CloudFront distribution value and TXT array

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-prod/resources/irsa.tf
This adds the RDS policy to the service account used in our service pod, so we can create manual RDS snapshots.
=> Add RDS IRSA Policy to Service Account

namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-prod/resources/publicdefenderservice-route53.tf
Add DAMRC record to Public Defender Service domain to stop being flagged by NCSC.
=> PDS domain add dmarc record

namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-prod/resources/ppj-route53.tf
Remove PPJ A record so that a new A record is created that points to our new hosting stack with the new site on it.
=> Remove PPJ A record to trigger a new A record

namespaces/live.cloud-platform.service.justice.gov.uk/send-legal-mail-to-prisons-dev/APPLY_PIPELINE_SKIP_THIS_NAMESPACE
Remove apply pipeline skip namespace file after upgrading database instance for send-legal-mail-to-prisons-dev namespace.
=> Remove apply pipeline skip namespace - send-legal-mail-to-prisons-dev 

namespaces/live.cloud-platform.service.justice.gov.uk/sqstesting-dev/resources/irsa.tf
Amend service_account_name to use var.namespace to avoid whitespace issue with var.application.
=> LASB-2404 - Amend irsa.tf

namespaces/live.cloud-platform.service.justice.gov.uk/laa-govuk-notify-orchestrator-dev/resources/ecr.tf
Removed the deletion_protection argument from the ECR Module in the laa-govuk-notify-orchestation-dev namespace in preparation to delete and remake the namespace.
=> Removed deletion_protection from laa-govuk-notify-orchestation-dev

namespaces/live.cloud-platform.service.justice.gov.uk/cccd-dev/05-rbac-dart-read-only.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/cccd-dev/06-rbac-role-bind-dart-team.yaml
For the CCCD dev database:
- Add an RBAC role to have read only access to the port-forward-pod
- Bind this role to the DART team / MI reporting team so that they have the ability to use the `port-forward-pod` to connect to the read replica database without having further access privileges to our namespace: This practices the principle of least privilege as they'll only have read access to the pod.
=> CCCD-DEV Add an RBAC role and binding for the DART team

namespaces/live.cloud-platform.service.justice.gov.uk/prisoner-content-hub-development/resources/opensearch.tf
This will enable us to test pointing Drupal at OpenSearch instead of ElasticSearch.
=> LNP-272: 🔍  add opensearch module to prisoner content hub dev environment

namespaces/live.cloud-platform.service.justice.gov.uk/cccd-dev/resources/secrets_manager.tf
This is to hold the rds `read_replica` secret which will contain the cccd-dev's read replica `rds_instance_endpoint` secret key/value
This will then be used to manually create temporary port-forward pods to the read replica database and not the primary database
=> CCCD-DEV Add a secrets manager resource and store the rds_instance_endpoint secret

namespaces/live.cloud-platform.service.justice.gov.uk/cccd-dev/resources/secrets_manager.tf
Fix typo of kubernetes secret name to meet the naming standards
A previous [PR](https://github.com/ministryofjustice/cloud-platform-environments/pull/16727) apply failed https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/environments-live/jobs/apply-namespace-changes-live/builds/9141
> The key to the secrets should only contain '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*') as this is used to create the actual kubernetes resource.
=> CCCD-DEV Fix typo that failed naming conventions validations

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-non-associations-preprod/resources/rds.tf
Created a secret in the `prod` namespace with the `preprod` DB credentials. This will be used to periodically sync the `preprod` database with the `prod` data.
See: `generic-service` helm chart documentation on Postgres database restore cronjob:
https://github.com/ministryofjustice/hmpps-helm-charts/tree/main/charts/generic-service#prison-postgres-database-restore-cronjob
=> NON-263: Secret to sync preprod DB (non-associations)

namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-ap-rshiny-notesbook-dev/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-ap-rshiny-notesbook-dev/resources/ecr.tf, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-ap-rshiny-notesbook-dev/resources/serviceaccount.tf
found out the typo in the repo name which caused the mismatch between namespace's name and repo name 🤦‍♀️ . this PR is the rename the repo name
=> Rename the repo name for ap-rshiny-notesbook app

namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-prod/02-limitrange.yaml
Our production application continuously goes over the default requested amount of both CPU and memory. This makes it difficult to configure our HPA correctly. I've increased both CPU and memory to hopefully cover what is needed.
=> Increase requested compute resource

namespace-resources-cli-template/00-namespace.yaml
This PR ensures that any new environments created include
`pod-security.kubernetes.io/audit: restricted` label.
Will be updated to `enforce` mode following period of PSA audit testing cluster wide.
=> update namespace template with psa audit restricted label

namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-production/05-prometheus.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-staging/05-prometheus.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-uat/05-prometheus.yaml
Remove prom rules using `container_fs_usage_bytes`
This metric is no longer available as of k8s version 1.24,
dockershim to containerd change, and is resulting in daily
or twice daily alerting in the channels for no good reason.
References:
[migrating from dockershim, known issues](https://kubernetes.io/docs/tasks/administer-cluster/migrating-from-dockershim/check-if-dockershim-removal-affects-you/#known-issues)
[Related CP Issue](https://github.com/ministryofjustice/cloud-platform/issues/4672)
=> laa-apply-for-legalaid-namespaces: Remove prom rules using `container_fs_usage_bytes`

namespaces/live.cloud-platform.service.justice.gov.uk/cccd-dev/resources/read_replica.tf
For CCCD Dev
Create rds read replica secret called `read-replica`
Return the `rds-instance-endpoint` so that it can be used to create a port-forward on demand (non-persistent) manually.
=> CCCD-DEV Create rds read-replica k8s secret

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-education-employment-dev/00-namespace.yaml
Add the `farsight-devs` GH team to the `hmpps-education-employment-dev` namespace
=> RR-411 - Add `farsight-devs` to `hmpps-education-employment-dev`

.github/workflows/conftest.yaml, policy/namespace.rego
This PR  enables conftest testing for all namespace rego annotation checks and adds PSA label checks.
GH Action currently set to continue-on-error, this will be disabled once PSA switches from audit to enforce mode.
=> Conftest checks

namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-prod/02-limitrange.yaml
Pods are hitting OOMKILLED with current memory capacity. Looking at Grafana, they seem to spike around 1.5Mi but I have increased the limit to 2000Mi with some buffer room.
=> Increase prod memory limit

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-dev/06-certificates.yaml
The service has been renamed from temporary to transitional. We need to keep the old urls working.
We'll be adding this to all other namespaces.
Is this all that's needed?
=> New CAS 3 dev URL

namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-staging/02-limitrange.yaml
When deploying more than one pod, we are coming close to, or hitting our memory limits and on some pods getting an OOMKILLED message. This results in pods spinning up with half of the files they require. We have tested on prod and setting this new limit fixes the issue.
=> Adjust memory limit to stop OOM error on deploy

namespaces/live.cloud-platform.service.justice.gov.uk/cloud-platform-go-get-module-prod/resources/serviceaccount.tf
This shouldn't deploy any repo level secrets because we are passing in an environment which holds the secrets (this prevents duplicating the secret in two places)
=> test: 💍 sa module

.github/workflows/conftest.yaml
This PR enables our conftest action, so that namespaces with missing required annotations and labels ([see here for rego policies](https://github.com/ministryofjustice/cloud-platform-environments/blob/main/policy/namespace.rego)) will fail this check.
=> switching conftest namespace check to fail on non-passing checks

namespaces/live.cloud-platform.service.justice.gov.uk/cloud-platform-canary-app-eks/resources/application.tf, namespaces/live.cloud-platform.service.justice.gov.uk/cloud-platform-canary-app-eks/resources/values.yaml
- The app has been alerting on high priority for service down
- The pod was exiting with exitCode:137 which lead to investigating towards cpu and memory
- Grafana screenshot showing CPU utlization over limits
=> Increase cpu, memory req and limits for canary-app

namespaces/live.cloud-platform.service.justice.gov.uk/send-legal-mail-to-prisons-preprod/05-serviceaccount-circleci.yaml
Add servicemonitors to circleCI resources (send-legal-mail-to-prisons-preprod) as a fix for failing build - https://app.circleci.com/pipelines/github/ministryofjustice/hmpps-send-legal-mail-staff-ui/101/workflows/22dc3a2b-a726-45cc-a845-c000d2ae21c7/jobs/574
=> Add servicemonitors to circleCI resources - send-legal-mail-to-prisons-preprod

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-test/06-certificates.yaml
The service has been renamed from temporary to transitional. We need to keep the old urls working.
=> New CAS3 test URL

namespaces/live.cloud-platform.service.justice.gov.uk/send-legal-mail-to-prisons-preprod/05-serviceaccount-circleci.yaml
Add secrets to circleCI resources send-legal-mail-to-prisons-preprod as a fix for failing build - https://app.circleci.com/pipelines/github/ministryofjustice/hmpps-send-legal-mail-staff-ui/105/workflows/03c71810-3652-4edf-88d7-fc78f7c6521e/jobs/609
Needs to read secrets from namespace to run smoke tests.
=> Add secrets to circleCI resources send-legal-mail-to-prisons-preprod

namespaces/live.cloud-platform.service.justice.gov.uk/laa-claim-non-standard-magistrate-fee-dev/resources/shared-s3-secret.tf
Creates a secret in the laa-assess-non-standard-magistrate-fee-dev environment to share IRSA policy to access the shared S3 bucket.
=> Share secret with assess non standard mags dev

namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-uat/serviceaccount-circleci.yaml
Add serviceaccount intropection permissions
Allow circleci service account to query serviceaccounts resources
Currently A UAT branch that is attempting to install bitnami/redis
is errororing as follows
```sh
Deploying CIRCLE_SHA1: b24b35edcf6c7d522378eb78b05afc27d9c9d54c under release name: 'apply-ap-4499-remove-redis-namespace'...
Error: UPGRADE FAILED: rendered manifests contain a resource that already exists. Unable to continue with
update: could not get information about the resource: serviceaccounts "apply-ap-4499-remove-redis-namespace" is
forbidden: User "system:serviceaccount:**************************:circleci" cannot get resource "serviceaccounts" in API group "" in
the namespace "**************************"
Exited with code exit status 1
``` …
=> [laa-apply-for-legalaid-uat] Add serviceaccount permissions

namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-uat/serviceaccount-circleci.yaml
Add configmaps permissions
Allow circleci service account to query configmaps resources
Currently A UAT branch that is attempting to install bitnami/redis
is errororing due to lack of permissions
```sh
Deploying CIRCLE_SHA1: b24b35edcf6c7d522378eb78b05afc27d9c9d54c under release name: 'apply-ap-4499-remove-redis-namespace'...
Error: UPGRADE FAILED: rendered manifests contain a resource that already exists. Unable to continue with update: could not get information about the resource: configmaps "apply-ap-4499-remove-redis-namespace-configuration" is forbidden: User "system:serviceaccount:**************************:circleci" cannot get resource "configmaps" in API group "" in the namespace "**************************"
Exited with code exit status 1
```
=> [laa-apply-for-legalaid-uat] Add configmaps permissions

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-offences-api-dev/resources/rds.tf
Steps 1 and 2 from https://user-guide.cloud-platform.service.justice.gov.uk/documentation/deploying-an-app/relational-databases/upgrade.html#upgrading-to-a-new-major-database-version
Step 1: Skip pipeline
Step 2: Change instance type
=> MOP-106 Upgrading DB instance type to t4g 

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-prod/06-certificates.yaml
The service has been renamed from temporary to transitional. We need to keep the old urls working.
=> New CAS3 prod URL

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-preprod/06-certificates.yaml
The service has been renamed from temporary to transitional. We need to keep the old urls working.
=> New CAS3 preprod URL

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-preprod/06-certificates.yaml
The existing domain name is over 64 characters and causing the certificate to error. This follows process used elsewhere such as https://github.com/ministryofjustice/cloud-platform-environments/blob/83728051db55cbe97100ee60e5609e096d14f2b8/namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-probation-integration-services-preprod/05-certificates.yml#L27
and following a conversation here https://mojdt.slack.com/archives/C69NWE339/p1697642282015629
=> add short version of CAS2 preprod domain name

namespaces/live.cloud-platform.service.justice.gov.uk/laa-check-client-qualifies-uat/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-check-client-qualifies-uat/resources/variables.tf
We accidentally broke the pipeline by using a new repo name for our new CCQ UAT namespace.
We haven't yet renamed our existing repo to this new name, so we are setting the repo name back to our existing repo name to fix the pipeline build.
=> Update repo name for new CCQ UAT namespace

namespaces/live.cloud-platform.service.justice.gov.uk/cccd-dev-lgfs/serviceaccount-circleci.yaml
In order to allow our CircleCI service account to update prometheus rules in our app, this gives the account access to `prometheusrules` resources in the `monitoring.coreos.com` API group.
=> Add access to prometheus rules to service account in cccd-dev-lgfs namespace

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-prod/resources/pingdom.tf
We’ve recently redirected from temporary-x to transitional-x so the 301 is preventing the healthy state.
=> Update CAS3 pingdom check url

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-dpr-fake-dps-service/resources/serviceaccount.tf
Bump service account module version in order to fix the following CircleCI failure:
```
Error: rendered manifests contain a resource that already exists. Unable to continue with install: could not get information about the resource: networkpolicies.networking.k8s.io "**************************-ui-dev-monitoring" is forbidden: User "system:serviceaccount:**************************:circleci" cannot get resource "networkpolicies" in API group "networking.k8s.io" in the namespace "**************************"
```
=> [DPR2-122] Service account module version bump

namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-dev/resources/s3.tf
This blocks access to the bucket root dir listing but allows access to subdirectories.
=> Add custom s3 bucket policy

namespaces/live.cloud-platform.service.justice.gov.uk/laa-govuk-notify-orchestrator-staging/04-networkpolicy.yaml
- Adds ingress Network Policy from `laa-cla-backend-staging` and `laa-cla-public-staging`.
=> Added ingress Network Policy to laa-govuk-notify-orchestrator-staging

namespaces/live.cloud-platform.service.justice.gov.uk/laa-govuk-notify-orchestrator-production/04-networkpolicy.yaml
- Adds ingress Network Policy from `laa-cla-backend-production` and `laa-cla-public-production`.
=> Added ingress network policy to laa-govuk-notify-orchestrator-production

namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-ui-dev/prometheus.yaml
Remove DiskSpace-Threshold-Reached alert from laa-court-data-ui-dev
This is because this alert query is no longer supported
=> laa-court-data-ui-dev Remove DiskSpace-Threshold-Reached alert

namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-ui-uat/prometheus.yaml
Remove DiskSpace-Threshold-Reached alert from `laa-court-data-ui-uat`
This is because this alert query is no longer supported
=> Remove DiskSpace-Threshold-Reached alert for CDUI UAT

namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-ui-staging/prometheus.yaml
Remove DiskSpace-Threshold-Reached alert from `laa-court-data-ui-staging`
This is because this alert query is no longer supported
=> Remove DiskSpace-Threshold-Reached alert for CDUI Staging

namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-ui-production/prometheus.yaml
Remove DiskSpace-Threshold-Reached alert from `laa-court-data-ui-production`
This is because this alert query is no longer supported
=> Remove DiskSpace-Threshold-Reached alert for CDUI Production

namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-production/05-prometheus.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-staging/05-prometheus.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-uat/05-prometheus.yaml
This affects multiple namespaces but only the prometheus rules in each
=> CivilApply: Update prometheus rules

namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-production/05-prometheus.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-staging/05-prometheus.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-uat/05-prometheus.yaml
These had the erroneus, count, keyword added to the end of the search query, subsequently they kept increasing!
This should revert the checks to report as expected
=> Civil-Apply: update prometheus rules... again

namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-production/resources/elasticache.tf
bump redis from 6 to 7, reduce node_type size on laa apply for legal aid production
=> bump redis from 6 to 7, reduce node_type size

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-incentives-dev/resources/rds.tf
Stop RDS instance during non-working hours to save money.
See CP user guide:
> [...] temporarily stop your database at 10PM and restart it at 6AM UTC
> (11PM and 7AM BST).
https://user-guide.cloud-platform.service.justice.gov.uk/documentation/deploying-an-app/relational-databases/create.html#non-production
=> INC-1235: Incentives `dev`: Shutdown RDS during non-working hours

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-incentives-preprod/resources/rds.tf
Stop RDS instance during non-working hours to save money.
See CP user guide:
> [...] temporarily stop your database at 10PM and restart it at 6AM UTC
> (11PM and 7AM BST).
https://user-guide.cloud-platform.service.justice.gov.uk/documentation/deploying-an-app/relational-databases/create.html#non-production
=> INC-1235: Incentives `preprod`: Shutdown RDS during non-working hours

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-non-associations-dev/resources/rds.tf
Stop RDS instance during non-working hours to save money.
See CP user guide:
> [...] temporarily stop your database at 10PM and restart it at 6AM UTC
> (11PM and 7AM BST).
https://user-guide.cloud-platform.service.justice.gov.uk/documentation/deploying-an-app/relational-databases/create.html#non-production
=> NON-303: Non-associations `dev`: Shutdown RDS during non-working hours

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-non-associations-preprod/resources/rds.tf
Stop RDS instance during non-working hours to save money.
See CP user guide:
> [...] temporarily stop your database at 10PM and restart it at 6AM UTC
> (11PM and 7AM BST).
https://user-guide.cloud-platform.service.justice.gov.uk/documentation/deploying-an-app/relational-databases/create.html#non-production
=> NON-303: Non-associations `preprod`: Shutdown RDS during non-working hours

namespaces/live.cloud-platform.service.justice.gov.uk/laa-check-client-qualifies-production/resources/variables.tf
The domain removed here also exists in our old namespace `laa-estimate-financial....-production`
deleting from here as it appears to be interfering with A records being created
=> CCQ PROD remove domain duplicated from old NS

namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-prod/resources/irsa.tf
Allow for the permissions to transfer bucket contents from old AWS account to CP.
=> Add bucket permissions to AWS legacy bucket PPO

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-document-management-dev/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-document-management-dev/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-document-management-dev/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-document-management-dev/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-document-management-dev/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-document-management-dev/05-certificate.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-document-management-dev/resources/irsa.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-document-management-dev/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-document-management-dev/resources/rds-postgresql.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-document-management-dev/resources/s3.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-document-management-dev/resources/serviceaccount.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-document-management-dev/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-document-management-dev/resources/versions.tf
Adds a new hmpps-document-management-dev namespace for the HMPPS Document Management API project. This project will prove out an electronic document storage service used initially by the products in the Legacy team. The service is intended to be available across HMPPS as a centralised document management facility and/or templated supporting per service reuse.
Reasons for each module:
- irsa - publish audit events when documents are uploaded/replaced/viewed
- rds-postgres - store document metadata
- s3 - document storage
=> PIC-3407: Add hmpps-document-management-dev namespace

namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-uat/resources/variables.tf
A clean up job has started to fail with
```
Failed to delete release: [configmaps "apply-helm-delete-failures-redis-health" is forbidden: User "system:serviceaccount:***:github-actions" cannot delete resource "configmaps" in API group "" in the namespace "***"
```
So this PR adds the configmaps into the "" resource group that already has delete permissions
=> Civil Apply: Update permissions for github action service account

namespaces/live.cloud-platform.service.justice.gov.uk/help-with-child-arrangements-production/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/help-with-child-arrangements-production/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/help-with-child-arrangements-production/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/help-with-child-arrangements-production/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/help-with-child-arrangements-production/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/help-with-child-arrangements-production/05-certificate.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/help-with-child-arrangements-production/bypass-psp-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/help-with-child-arrangements-production/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/help-with-child-arrangements-production/resources/serviceaccount.tf, namespaces/live.cloud-platform.service.justice.gov.uk/help-with-child-arrangements-production/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/help-with-child-arrangements-production/resources/versions.tf, namespaces/live.cloud-platform.service.justice.gov.uk/track-a-query-qa/resources/versions.tf
This will soon replace an existing service - https://github.com/ministryofjustice/cloud-platform-environments/blob/main/namespaces/live.cloud-platform.service.justice.gov.uk/fj-cait-production
=> Add production namespace for replatforming

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-prisoner-profile-prod/02-limitrange.yaml
This is part one of 2 for the profile where we need to resize the minimum CPU request size for prod profile. there will be another PR to cover the HPA settings, which we will set there.
=> CDPS-401 - Update request default to 100m CPU on the profile

namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-dev/resources/s3.tf
We were able to manually remove `List` from the bucket root so this is no longer needed.
=> Remove bucket policy no longer needed

namespaces/live.cloud-platform.service.justice.gov.uk/mikebell-test/resources/pingdom.tf
Adds the `#cloud-platform-test` channel to the pingdom alert.
=> Add slack channel to pingdom alert

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-micro-frontend-components-prod/02-limitrange.yaml
following on from #17646 and #17647, update memory limits prior to launch of these services.
=> CDPS-514 - update memory limits and defaults

namespaces/live.cloud-platform.service.justice.gov.uk/cloud-platform-reports-prod/resources/dynamodb.tf
Fixes: HOODAW app flapping with errror ```2023-11-08 15:08:17 - Aws::DynamoDB::Errors::ProvisionedThroughputExceededException - The level of configured provisioned throughput for the table was exceeded. Consider increasing your provisioning level with the UpdateTable API.:```
=> Increase the autoscale_max_read_capacity to fix ProvisionedThroughputExceededException

namespaces/live.cloud-platform.service.justice.gov.uk/use-of-force-prod/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/use-of-force-prod/resources/variables.tf
The dps-shared Slack channel is no more. I have updated UoF prod so that it has the correct ownership details and slack channel.
=> MAP-323: Set ownership correctly for UoF prod

namespaces/live.cloud-platform.service.justice.gov.uk/use-of-force-preprod/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/use-of-force-preprod/resources/variables.tf
The dps-shared Slack channel is no more. I have updated UoF preprod so that it has the correct ownership details and slack channel.
=> MAP-323: Set ownership correctly for UoF preprod

namespaces/live.cloud-platform.service.justice.gov.uk/use-of-force-dev/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/use-of-force-dev/resources/variables.tf
The dps-shared Slack channel is no more. I have updated UoF dev so that it has the correct ownership details and slack channel.
=> MAP-323: Set ownership correctly for UoF dev

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-video-link-prod/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-video-link-prod/resources/variables.tf
The dps-shared Slack channel is no more. I have updated BVL prod so that it has the correct ownership details and slack channel.
=> MAP-323: Set ownership correctly for BVL prod

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-video-link-preprod/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-video-link-preprod/resources/variables.tf
The dps-shared Slack channel is no more. I have updated BVL preprod so that it has the correct ownership details and slack channel.
=> MAP-323: Set ownership correctly for BVL preprod

namespaces/live.cloud-platform.service.justice.gov.uk/laa-cla-backend-uat/resources/s3.tf
Adds a lifecycle rule to the `laa-cla-backend-uat` S3 Bucket to expire entries that are over 2 years old.
=> Add lifecycle rule to laa-cla-backend-uat S3 Bucket

namespaces/live.cloud-platform.service.justice.gov.uk/laa-cla-backend-staging/resources/s3.tf
Adds lifecycle rule to the S3 Bucket, removing any extract reports created over 2 years ago.
=> Add Lifecycle Rule to S3 of laa-cla-backend-staging

namespaces/live.cloud-platform.service.justice.gov.uk/laa-cla-backend-training/resources/s3.tf
Adds lifecycle rule to the S3 Bucket, removing any extract reports created over 2 years ago.
=> Add Lifecycle Rule to S3 Bucket of laa-cla-backend-training

namespaces/live.cloud-platform.service.justice.gov.uk/laa-criminal-applications-datastore-production/resources/s3.tf
Adds S3 bucket for production use.
Replicates staging.
Ticket
https://dsdmoj.atlassian.net/browse/CRIMAPP-66
=> [CRIMAP-63] Add s3 to laa-criminal-applications-datastore-production

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-dpr-fake-dps-service/resources/rds-postgresql.tf
Fixes:
- AWS considers 14.7 -> 14.10 to be a major version upgrade.
- 14.10 isn't supported yet.
=> [DPR2-44] RDS 'major' version upgrade fix

namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-production/07-issuer.yaml
Trying to consume our HTTP01 resolver failed, we aren't seeing certificates created, due to
```
Warning   PresentError         challenge/assets-tls-1-3027398620-3333557501   Error presenting challenge: admission webhook "validation.gatekeeper.sh" denied the request: [k8sexternaldnsweight] ...
```
and 
```
$ kubectl --namespace data-platform-production get challenges.acme.cert-manager.io assets-tls-1-3027398620-3333557501 --output yaml
...
status:
presented: false
processing: true
reason: "admission webhook \"validation.gatekeeper.sh\" denied the request: [k8sexternaldnsweight]
\nPlease add valid AWS weight annotation e.g. external-dns.alpha.kubernetes.io/aws-weight:
'100'\n[k8sexternaldnsidentifier] \nPlease add valid external-dns set-identifier
annotation for ingress …
```
=> 🚑 Add `ingressTemplate` to Data Platform's HTTP01 resolver

namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-prod/resources/sifocc-route53.tf
Remove the SIFOCC domain A record so a new one is generated pointing to our current hosted env on CP.
=> Remove SIFOCC domain A record, generate new

namespaces/live.cloud-platform.service.justice.gov.uk/offender-events-dev/resources/book-video-link-sub-queue.tf
BVL needs to access prison events notifications so it can notify courts and prisons if a prisoner transfers with an outstanding BVL appointment
=> MAP-465 create prison events queue for Book Video Link

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-dev/resources/api_gateway.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-dev/resources/kubernetes_secrets.tf
These API key IDs will be used to distinguish between consumers of our API and to authorise endpoints.
=> APIGW key IDs as K8s secrets and proxy to backend

namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-github-runners-poc/resources/github-actions-controller.tf, namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-github-runners-poc/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-github-runners-poc/resources/versions.tf
Why:
This PR connects to https://github.com/ministryofjustice/operations-engineering/issues/3759, please see here for the user story associated.
What:
This PR introduces the GitHub Actions Runner Controller using Helm. The addition is intended to enhance our CI/CD pipeline capabilities by enabling the use of self-hosted runners for GitHub Actions.
Key Points:
- The Helm chart is sourced from the official actions-runner-controller repository.
- The instructions set out [here](https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/quickstart-for-actions-runner-controller) outline required resources deploy the controller on our behalf. 
- Operations Engineering would maintain the controller, but we need don't have the ability …
=> :sparkles: Add GitHub actions local runners controller

namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-github-runners-poc/01-rbac.yaml
This change will allow Operations Engineering staff to make changes to the github runner controller customer resources.
=> :closed_lock_with_key: Add github-runner role and rolebinding

namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-github-runners-poc/resources/github-actions-controller.tf
This commit connects to https://github.com/ministryofjustice/operations-engineering/issues/3759 and relates to the requirement to self-host GitHub actions local runners on the Cloud Platform.
=> :wrench: Add a github action scaleset

namespaces/live.cloud-platform.service.justice.gov.uk/laa-check-client-qualifies-production/resources/route53.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-check-client-qualifies-production/resources/variables.tf
The CCQ service has recently transferred to a new namespace `laa-check-client-qualifies-production`
This PR recreates the route53 hosted zone that is being deleted from the old namespace
There is a [linked PR ](https://github.com/ministryofjustice/cloud-platform-environments/pull/17850)that removes the associated route53 hosted zone from the old namespace `laa-estimate-financial-eligibility-for-legal-aid-production`
There is a support ticket for Cloud Platform Team to transfer the Hosted Zone 'state'
https://github.com/ministryofjustice/cloud-platform/issues/5036
=> CCQ PROD add route53

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-intelligence-preprod/resources/rds-aurora.tf
Setting work_mem to 4MB, to carry out some testing of its effectiveness
=> setting rds postgresql work_mem back to 4Mb for testing

namespaces/live.cloud-platform.service.justice.gov.uk/digital-prison-services-dev/01-rbac.yaml
Some of us have been removed from the `dps-tech` GitHub team which has left us unable to work on DPS. We have been advised to request team-level access be granted to the k8s namespaces. Please see here:
https://mojdt.slack.com/archives/C69NWE339/p1700738995871609
=> chore: Give map-developers team access to DPS, as we have been removed from dps-tech

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-prisoner-cell-allocation-dev/06-certificate.yaml
Use separate certs for CSC UI and API (dev)
=> MAP-16: Use separate certs for CSC UI and API (dev)

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-prisoner-cell-allocation-prod/06-certificate.yaml
Use separate certs for CSC UI and API (preprod)
=> MAP-16: Use separate certs for CSC UI and API (prod)

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-prisoner-cell-allocation-dev/05-serviceaccount-circleci.yaml
Allow CircleCI access to CSC service monitors
[MAP-10]
[MAP-10]: https://dsdmoj.atlassian.net/browse/MAP-10?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: Allow CircleCI access to CSC service monitors

namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-prod/resources/layobservers-route53.tf
Remove old configurations so that new records are regenerated pointing to new stack.
=> Point Lay Observers DNS records to new site

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-prod/resources/pingdom.tf
This seems to have been originally misconfigured and was only surfaced when this fix to the health kick service[1] was made. It appears like a 200 was returned to by health-kick even though the path didn't resolve in a healthy response.
You can test out that this path resolves by visiting the api in dev (which is more easily accessible when on an MoJ device): https://health-kick.prison.service.justice.gov.uk/https/approved-premises-api-dev.hmpps.service.justice.gov.uk/health
[1]  https://github.com/ministryofjustice/health-kick/pull/58
=> Correct CAS API health_check endpoint

namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-uat/serviceaccount-circleci.yaml
Include persistentvolumeclaims so that circle can delete UAT pvcs when a branch is torn down
=> Civil Apply UAT: Update circle ci service account permissions

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-dev/resources/api_gateway.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-dev/resources/kubernetes_secrets.tf
We will use the distinguished name from the client certificate to implement authorisation instead of API key IDs.
This is more flexible as we don't need to keep an internal mapping between key IDs and endpoints.
=> Send mTLS subject distinguished name

namespaces/live.cloud-platform.service.justice.gov.uk/legal-framework-api-uat/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/legal-framework-api-uat/serviceaccount-circleci.yaml
Add privileges for persistentvolumeclaims so that github actions and circleci can delete UAT pvcs when a branch is torn down
=> [legal-framework-api-uat] Add persistentvolumeclaims privilege

namespaces/live.cloud-platform.service.justice.gov.uk/help-with-prison-visits-dev/07-grafandashboard.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/help-with-prison-visits-preprod/07-grafanadashboard.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/help-with-prison-visits-prod/07-grafanadashboard.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/prison-visits-booking-dev/07-grafanadashboard.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/prison-visits-booking-production/05-grafanadashboard.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/prison-visits-booking-staging/05-grafanadashboard.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/send-legal-mail-to-prisons-dev/07-grafanadashboard.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/send-legal-mail-to-prisons-preprod/07-grafanadashboard.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/send-legal-mail-to-prisons-prod/07-grafanadashboard.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-dev/10-grafanadashboard.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-preprod/10-grafanadashboard.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-prod/09-grafanadashboard.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-staging/10-grafanadashboard.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-frontend-svc-dev/09-grafanadashboard.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-frontend-svc-preprod/09-grafanadashboard.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-frontend-svc-prod/09-grafanadashboard.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-frontend-svc-staging/09-grafanadashboard.yaml
Update all Grafana dashboard titles in the visits namespaces 
Uses the 'Visits' prefix followed by our 'known by' abbreviation and environment
=> VB-1874/2 rename grafana dashboards (All visits namespaces)

namespaces/live.cloud-platform.service.justice.gov.uk/prisoner-content-hub-production/10-grafana.yaml
Also raise y-axis limit of CPU use from 10 to 100%.
=> LNP-404: 🧐 rename prisoner content hub grafana elasticsearch dashboard to opensearch.

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-sentence-plan-dev/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-sentence-plan-dev/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-sentence-plan-dev/resources/variables.tf
The sentence plan repos and namespace have been handed over from probabtion-integration to the hmpps-sentence-planning team
=> Changing team responsible for sentence plan dev

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-delius-alfrsco-poc/resources/s3.tf
Alfresco is to use S3 instead of volume persistence
=> NIT-969 Alfresco to use S3 for storing docs

namespaces/live.cloud-platform.service.justice.gov.uk/laa-cla-backend-uat/01-rbac.yaml
This is temporary, for the purpose of developing the integration of CLA with Eligibility Platform
=> LEP-429 Give Eligibility Platform team access CLA UAT environment

namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-saas-test/resources/circleci-service-account.tf, namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-saas-test/resources/variables.tf
We're migrating from old yaml service accounts used by circleci to deploy, trying to add a new service account alongside the old one using the module so I can verify the token it generates will work with our pipelines.
Note: The resource service account I am replacing is not the service account currently in use, it was another experiment! The currently-used service account is untouched in this PR.
=> Move circleci service account to use the sa module

namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-saas-test/resources/circleci-service-account.tf
Using the [existing service account](https://github.com/ministryofjustice/cloud-platform-environments/blob/main/namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-saas-test/05-circleci-service-account.yaml) as s guide for what permissions need to be added
=> Add permissions to new service account module

namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-saas-test/resources/circleci-service-account.tf
The token needs to create cronjobs, but had forgot batch from the api group list, even though cronjob resources were already listed.
=> Need access to modify cronjobs, but missed batch from the api group list

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-dev/resources/api_gateway.tf
Additional safety mechanism to allow a maximum of 5 requests per second on API Gateway. This will be
more than enough for our expected load.
Should prevent accidental DOS from one of our consumers from a runaway script (worst case scenario that hopefully never happens).
=> Set throttle request limit on API GW Development

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-preprod/resources/api_gateway.tf
Additional safety mechanism to allow a maximum of 5 requests per second on API Gateway. This will be more than enough for our expected load.
Should prevent accidental DOS from one of our consumers from a runaway script (worst case scenario that hopefully never happens).
=> Set throttle request limit on API GW Preprod

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-dev/resources/api_gateway.tf
Currently seeing 429 Too many requests errors from very few requests. It doesn't seem that "rate_limit" is restricting requests per second as suggested by the AWS documentation.
Increase this limit and add burst_limit for concurrent requests. Future performance testing may force us to revisit this figure.
=> Increase throttling limit on API Gateway in Dev

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-dev/resources/api_gateway.tf
There is AWS Shield for any major DDOS attacks.
Second level of defense will happen at the NGINX level. The throttle settings at API Gateway level are "best effort" and didn't work quite as expected when testing requests per second.
=> Remove throttling settings from API Gateway in Dev

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-sandbox-admin/resources/rds.tf
As per title. This adds egress to the LAA Landing Zone's Shared Services VPC for access to the DB via workspaces.
=> Adds Egress Sec Group Rule for oracle RDS.

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-sandbox-admin/resources/rds.tf
As per title, this changes the ingress/egress rule to cover access from laa-development's VPC. This is due to laa-shared-services not having any routing connection to Cloud Platform.
=> Switched ingress & egress from/to laa-development

namespaces/live.cloud-platform.service.justice.gov.uk/certificated-bailiffs-prod/resources/route53.tf
Add new DNS zone for the production service of Certificated Bailiffs which is migrating from AWS Tacticalproducts account to Cloud Platform.
This PR duplicates the existing A and CNAME records from the DSD Route53 so we can delegate the NameServers in advance of the migration
=> Certificated Bailiffs production DNS zone and Route53 records

namespaces/live.cloud-platform.service.justice.gov.uk/certificated-bailiffs-prod/05-certificate.yaml
New production cert for certificatedbailiffs.justice.gov.uk in preparation for migration from tacticalproducts AWS account
=> Add certificate for new Certificated Bailiffs production site

namespaces/live.cloud-platform.service.justice.gov.uk/certificated-bailiffs-prod/resources/route53.tf
Remove the A and CNAME records which were pointing to the old service in tacticalproducts AWS
This will make the service live in Cloud Platform
=> Migrate certificatedbailiffs.justice.gov.uk production site

.github/workflows/devsec-scan.yaml, .github/workflows/devsec-scheduled.yaml, .github/workflows/terraform-tools.yml
As we changed the tfsec to changed-files, it closed all the security-alerts. We have to bring it back so it is open and visible to security team.
* Run tfscan for changed files and display the results - currently set to soft-fail set to TRUE. This can be changed.
* Adding scheduled tfscan for full code and upload SARIF file security team.
There is a plan to integrate checkov and scan all possible configs used across this repo.
=> Tfsec improvements

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-dev/resources/api_gateway.tf
Currently we're not getting any logs for API Gateway. Rebuild the log group, and give it a predictable name so it can be documented. Also bump the retention policy to 2 months instead of 2 weeks for debugging older issues.
=> Update API Gateway execution log settings in Dev

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-dev/resources/api_gateway.tf
Suspect this is the cause of the logs not working in API Gateway.
=> Remove unneeded quotes around custom access logging

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-dev/resources/api_gateway.tf
Set data_trace_enabled to true in the aws_api_gateway_method_settings resource. Suspect this resource is overwriting the custom access logs specified in the aws_api_gateway_stage, which disables logging.
=> Enable method settings logs for API Gateway

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-dev/resources/iam.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-dev/resources/s3_truststore.tf
Our CA and client certificates and private keys are stored in K8s secrets. For backup we will also store them in a version enabled, encrypted S3 bucket. An existing IAM user that has access to the API Gateway (for debugging) will also have access to this bucket.
=> Create S3 bucket to backup client certificates Dev

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-sandbox-admin/resources/rds.tf
Adds additional rules for ingress & egress from laa shared services non-prod so we can test the new transit gateway routes without impacting the current acess.
=> Adds ingress/egress for 10.200.0.0/20 on tcp 1521.

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-delius-alfrsco-poc/resources/serviceaccount.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-delius-alfrsco-poc/resources/variables.tf
This is to fix the following errors in github workflows when trying to deploy or get resources:
```
Error from server (Forbidden): replicationcontrollers is forbidden: User "system:serviceaccount:***:cd-serviceaccount" cannot list resource "replicationcontrollers" in API group "" in the namespace "***"
Error from server (Forbidden): daemonsets.apps is forbidden: User "system:serviceaccount:***:cd-serviceaccount" cannot list resource "daemonsets" in API group "apps" in the namespace "***"
Error from server (Forbidden): statefulsets.apps is forbidden: User "system:serviceaccount:***:cd-serviceaccount" cannot list resource "statefulsets" in API group "apps" in the namespace "***"
Error from server (Forbidden): horizontalpodautoscalers.autoscaling is forbidden: User …
```
=> NIT-994 pipeline for installing helm charts

namespaces/live.cloud-platform.service.justice.gov.uk/laa-legal-adviser-api-production/resources/irsa.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-legal-adviser-api-production/resources/rds.tf
* Removes retired Postgres 11 RDS from laa-legal-adviser-api-production
* Removes IRSA Policy which is no longer required
=> Remove retired RDS from laa-legal-adviser-api-production

namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-firebreak-aws-microservice-dev/resources/serviceaccount.tf
Add the missing "s" to allow the default service account to create other service accounts
=> Fix typo in serviceaccounts

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-preprod/resources/locals.tf
This PR is for updating the consumer list for preprod. Including ctrlo will generate an API Gateway API key that can be shared.
- Removed former consumers of preprod
- Added ctrlo to consumer list
=> Create new API key for consumer in Preprod

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-prod/resources/locals.tf
This PR is for updating the consumer list for prod. Including ctrlo will generate an API Gateway API key that can be shared.
- Removed former consumers of prod
- Added ctrlo to consumer list
=> Refresh api keys in prod for current consumers

namespaces/live.cloud-platform.service.justice.gov.uk/laa-cla-backend-staging/resources/rds.tf
Temporarily removes the read replica RDS so it can be re-created and attached to the restored source RDS.
=> Temporarily remove read replica rds

namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-metadata-poc/resources/rds.tf
- In relation to https://github.com/ministryofjustice/operations-engineering/issues/4004
- To enable automatic updates and get the latest minor release of PostgresDB to mitigate CVE-2023-5869
- Added `allow_minor_version_upgrade = "true"` to rds configuration
=> 🆙 Upgrade postgres db to mitigate CVE-2023-5869

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-api-preprod/resources/rds.tf
Ran out of tokens this monday, during a slightly slower run.  Issue faced in prod is the app will still need to work after the migration, so need a far greater amount of tokens to avoid throttling during, or after the migration within a 24 hour window
=> NN-5784 increase tokens in preprod

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-dpr-fake-dps-service/resources/rds-postgresql.tf
The DB is in "Storage-full" state an so we cannot start it. This PR bumps db_max_allocated_storage so we can start it for investigation/troubleshooting of the underlying issue
=> DPR2-311: Increase storage to allow db to restart for troubleshooting.

namespaces/live.cloud-platform.service.justice.gov.uk/send-legal-mail-to-prisons-dev/resources/rds.tf
SLM-338 set prepare_for_major_upgrade to false after updating Send Legal Mail DB version to 14.10 for send-legal-mail-to-prisons-dev namespace.
=> SLM-338 set prepare_for_major_upgrade to false post upgrade to 14.10

namespaces/live.cloud-platform.service.justice.gov.uk/send-legal-mail-to-prisons-dev/resources/rds.tf
SLM-338 update Send Legal Mail DB version to 15.5 for send-legal-mail-to-prisons-dev namespace.
=> SLM-338 update SLM DB version to 15.5 for send-legal-mail-to-prisons-dev namespace.

namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-hello-world-mat-dev/resources/rds-postgresql.tf
https://user-guide.cloud-platform.service.justice.gov.uk/documentation/getting-started/cloud-platform-cli.html#add-an-rds-to-your-namespace
I commented out the read replica as I assume I don't need it to work through the tutorial?
=> Add RDS to tutorial namespace

namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-hello-world-mat-dev/resources/serviceaccount.tf
I'm working my way through this guide:
https://user-guide.cloud-platform.service.justice.gov.uk/documentation/getting-started/cloud-platform-cli.html#add-a-service-account-to-your-namespace
I skipped the github actions part as I don't think I need that right now - I'm just trying to familiarise myself with the platform
=> Add service account

namespaces/live.cloud-platform.service.justice.gov.uk/laa-cla-backend-uat/03-resourcequota.yaml
Because we are hitting the limit now we are running an extra environment, and there are lots of jobs during deployment. Hitting the limit on most deploys now.
=> Increase max pods in CLA-UAT environment

namespaces/live.cloud-platform.service.justice.gov.uk/send-legal-mail-to-prisons-dev/resources/rds.tf
SLM-338 update prepare_for_major_upgrade to false after updating Send Legal Mail DB version to 15.5 for send-legal-mail-to-prisons-dev namespace.
=> SLM-338 update prepare_for_major_upgrade to false after updating  SLM DB version to 15.5

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-prod/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-prod/06-certificates.yaml
We’re now ready to launch into prod so we repeat the steps we took when launching pre-prod[1].
[1] https://github.com/ministryofjustice/cloud-platform-environments/pull/17070
=> Add CAS2 frontend to CAS production namespace

namespaces/live.cloud-platform.service.justice.gov.uk/laa-hmrc-interface-production/resources/rds.tf
=> LAA-HMRC-Interface Production - update RDS minor version

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-dpr-fake-dps-service/resources/rds-postgresql.tf
Allows us to test the effect on the DMS when the replication slot gets too far behind
=> DPR2-311: limit replication slot WAL size to a small value

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-electronic-monitoring-dev/06-certificate.yaml
New dns address: **hmpps-create-electronic-monitoring-order-dev.hmpps.service.justice.gov.uk**
For service: [Create Electronic Monitoring Order](https://github.com/ministryofjustice/hmpps-create-electronic-monitoring-order)
=> Added new dns address to cert for CEMO service

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-dpr-fake-dps-service/resources/rds-postgresql.tf
Increase max_slot_wal_keep_size to give over 2 days grace where the task can be disconnected before DMS task has to be restarted from scratch (at current loads). This will prevent the DB from running out of disk space when the DMS is disconnected for long periods but also gives us a grace period where we can resume it.
=> DPR2-311: Increase max_slot_wal_keep_size

namespaces/live.cloud-platform.service.justice.gov.uk/laa-hmrc-interface-production/resources/rds.tf
Probably shouldn't turn prod off overnight! 🤦‍♂️
=> HMRC Interface Production - Revert enable_rds_auto_start_stop

namespaces/live.cloud-platform.service.justice.gov.uk/laa-assure-hmrc-data-uat/resources/rds-postgresql.tf
=> HMRC Assure UAT - update RDS minor version

namespaces/live.cloud-platform.service.justice.gov.uk/send-legal-mail-to-prisons-preprod/resources/rds.tf
SLM-338 update prepare_for_major_upgrade to false after updating SLM DB version to 14.10 for send-legal-mail-to-prisons-preprod namespace.
=> SLM-338 update prepare_for_major_upgrade to false send-legal-mail-to-prisons-preprod namespace.

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-application-store-dev/resources/rds-postgresql.tf
Bump PG instance to latest minor version to prep for major version
=> laa-crime-application-store-dev - bump to latest minor version

namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-datahub-catalogue-dev/resources/opensearch.tf
Didn't output the open search proxy url to a secret initially so adding in here
=> Add opensearch secret for data platform datahub

namespaces/live.cloud-platform.service.justice.gov.uk/send-legal-mail-to-prisons-preprod/resources/rds.tf
SLM-338 update Send Legal Mail DB version to 15.5 for send-legal-mail-to-prisons-preprod namespace.
=> SLM-338 update SLM DB version to 15.5 for send-legal-mail-to-prisons-preprod

namespaces/live.cloud-platform.service.justice.gov.uk/send-legal-mail-to-prisons-preprod/resources/rds.tf
SLM-338 update prepare_for_major_upgrade to false after updating SLM DB version to 15.5 for send-legal-mail-to-prisons-preprod namespace.
=> SLM-338 update prepare_for_major_upgrade to false - send-legal-mail-to-prisons-preprod namespace.

namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-production/resources/rds.tf
After updating to v14.10 we don't want to lock at this version so removing the minor version to allow future auto minor updates
=> laa-civil-apply-production: remove rds minor version

namespaces/live.cloud-platform.service.justice.gov.uk/laa-assure-hmrc-data-staging/resources/rds-postgresql.tf
After updating to v14.10 we don't want to lock at this version so removing the minor version to allow future auto minor updates, also allow major version updates in line with our other non-production environments
=> laa-hmrc-assure-staging: remove rds minor version

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-person-links-prod/resources/secret.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-person-links-prod/resources/variables.tf
I have created this directly in the production environment. Do I need it in any other environments as well?
I am following https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#create-a-slack-webhook-and-amend-alertmanager
=> CPR-124 add secret for slack webhook

namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-dev/02-limitrange.yaml
Modified memory limit from 1000 to 100 to trigger recently enabled prometheus rules to test notification functionality
=> Hale Platform Dev Prometheus Testing

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-auth-preprod/04-networkpolicy.yaml
The probation integration team would like to switch to internal URLS for hmpps auth for preprod. The internal IPs for the following clients will also need to be added to the allowlist
"CLIENT_ID": "approved-premises-and-delius-integration-1",
"CLIENT_ID": "cas2-and-delius-1",
"CLIENT_ID": "cas3-and-delius-1",
"CLIENT_ID": "create-and-vary-a-licence-and-delius-1",
"CLIENT_ID": "custody-key-dates-and-delius",
"CLIENT_ID": "make-recall-decisions-and-delius-2",
"CLIENT_ID": "manage-offences-and-delius-1",
"CLIENT_ID": "manage-pom-cases-and-delius-1",
"CLIENT_ID": "opd-and-delius-1",
"CLIENT_ID": "pre-sentence-service-delius-client-1",
"CLIENT_ID": "prison-case-notes-to-probation-client-1",
"CLIENT_ID": "prison-custody-status-to-delius-client-1",
"CLIENT_ID": "prison-identifier-and-delius-1", …
=> PI-1733: Added probabtion service to preprod auth namespace

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-education-employment-dev/06-certificate.yaml
Remove the cert for the CIAG UI from the hmpps-education-employment-dev namespace
=> RR-573 - Remove the cert for the CIAG UI from the hmpps-education-employment-dev namespace

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-education-employment-preprod/06-certificate.yaml
Remove the cert for the CIAG UI from the hmpps-education-employment-preprod namespace
=> RR-573 - Remove the cert for the CIAG UI from the hmpps-education-employment-preprod namespace

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-auth-prod/04-networkpolicy.yaml
The probation integration team would like to switch to internal URLS for hmpps auth for prod. The internal IPs for the following clients will also need to be added to the allowlist:
"CLIENT_ID": "approved-premises-and-delius-integration-1",
"CLIENT_ID": "cas2-and-delius-1",
"CLIENT_ID": "cas3-and-delius-1",
"CLIENT_ID": "create-and-vary-a-licence-and-delius-1",
"CLIENT_ID": "custody-key-dates-and-delius-1",
"CLIENT_ID": "make-recall-decisions-and-delius-2",
"CLIENT_ID": "manage-offences-and-delius-1",
"CLIENT_ID": "manage-pom-cases-and-delius-1",
"CLIENT_ID": "opd-and-delius-1",
"CLIENT_ID": "pre-sentence-service-delius-client-1",
"CLIENT_ID": "prison-case-notes-to-probation-client-1",
"CLIENT_ID": "prison-custody-status-to-delius-client-1",
"CLIENT_ID": "prison-identifier-and-delius-1", …
=> PI-1733: Added probation service to prod auth namespace

namespaces/live.cloud-platform.service.justice.gov.uk/laa-fala-staging/resources/s3.tf
Adds a CORS rule to the S3 Bucket of `laa-fala-staging` allowing incoming get requests from additional domains.
=> Add CORS Rule to laa-fala-staging S3 Bucket

namespaces/live.cloud-platform.service.justice.gov.uk/laa-claim-non-standard-magistrate-fee-dev-crm4/resources/rds-postgresql.tf
Following guide note
> Note: If you need to upgrade major versions more than once, e.g. from Postgres 12 to 14, and then 14 to 16, you must turn off prepare_for_major_upgrade (step 6) after each upgrade and then turn it back on (step 5). Otherwise, any upgrade after the first will fail.
=> nscc-dev-crm4:turn off prepare_for_major_upgrade

namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-dev/resources/rds.tf
VB-3380 - update prepare_for_major_upgrade to false after updating VSIP DB version to 14.10 for visit-someone-in-prison-backend-svc-dev namespace.
=> VB-3380 - update prepare_for_major_upgrade to false after updating VSIP DB version to 14.10 for visit-someone-in-prison-backend-svc-dev namespace.

namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-staging/resources/rds.tf
VB-3380 - update prepare_for_major_upgrade to false after updating VSIP DB version to 14.10 for visit-someone-in-prison-backend-svc-staging namespace.
=> VB-3380 - update prepare_for_major_upgrade to false after updating VSIP DB version to 14.10 for visit-someone-in-prison-backend-svc-staging namespace.

namespaces/live.cloud-platform.service.justice.gov.uk/laa-assess-non-standard-magistrate-fee-dev-crm4/resources/rds-postgresql.tf
Cleanup after major postgress upgrade
Unset flags and specify engine version (for completeness).  Will remove SKIP file
in subsequent commit to be safe.
=> assess-dev-crm4: cleanup up after postgres major upgrade

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-activities-management-dev/resources/rds.tf
PostgreSQL minor version upgrade from 14 to 14.10 as part of security CVE-2023-5869
=> SAA-1496 changed postgresql from 14 to 14.10 version

namespaces/live.cloud-platform.service.justice.gov.uk/observability-platform-production/resources/route53.tf
- Creates a Route53 zone for `observability-platform.service.justice.gov.uk`
- Point `observability-platform.service.justice.gov.uk` at GitHub Pages
=> ❇️ Observability Platform Route53

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-prod/resources/pingdom.tf
We copy the other CAS frontend health checks.
The CAS2 health check endpoint can be viewed https://short-term-accommodation-cas-2.hmpps.service.justice.gov.uk/health
[We've requested out Slack integration ID here](https://github.com/ministryofjustice/cloud-platform/issues/5201#issuecomment-1908636973).
=> Add production Pingdom check with Slack alert for CAS2

namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-ui-dev/resources/rds.tf
Upgrade the postgres version to 14.10
This is due to postgres no longer supporting the minor version of 14.7 after march of this year
=> Upgrade postgres minor version to 14.10 for laa-court-data-ui-dev 

namespaces/live.cloud-platform.service.justice.gov.uk/observability-platform-production/resources/route53.tf
- Adds GitHub Pages validation for observability-platform.service.service.justice.gov.uk
=> 🚑 Add GitHub Pages validation

namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-ui-uat/resources/rds.tf
For `laa-court-data-ui-uat`:
1. Update the PostGres version to 14.10 as the minor version 14.7 will soon no longer be supported
=> Upgrade RDS version for laa-court-data-ui-uat 

namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-ui-staging/resources/rds.tf
For `laa-court-data-ui-staging`:
Upgrade the postgres version to 14.10. This is due to PostGres no longer supporting the minor version of 14.7 after march of this year
=> Upgrade postgres minor version to 14.10 for laa-court-data-ui-staging [STAGING] 

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-equinity-historical-data-prod/resources/rds-mssql.tf
Update MSSQL engine used in PROD RDS to -web, was -ex
Also, an additional increase in size now that we are starting the real data migration
=> EMP-3: Update MSSQL engine used in PROD RDS

namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-ui-uat/resources/rds.tf
Upgrade the RDS instance type to t4g for `laa-court-data-ui-uat`
=>  Upgrade rds instance type to t4 for laa-court-data-ui [UAT]

namespaces/live.cloud-platform.service.justice.gov.uk/prisoner-content-hub-staging/02-limitrange.yaml
We had some strange behaviour where bulk updates of content that worked on dev failed subsequently on staging.
This PR is to bring staging up to the spec of dev.
=> LNP-563: 🔧  raise spec of content hub staging to match development.

namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-prod/07-certificates.yaml
Add cym.victimandwitnessinformation.org.uk to handle the Welsh language site to the parent site victimandwitnessinformation.org.uk
=> Add TLS cert for Welsh subdomain - victim and witnesses

namespaces/live.cloud-platform.service.justice.gov.uk/justice-gov-uk-dev/06-certificate.yaml
Use `dev.justice.gov.uk` to target the development application.
=> Add certificate for development

namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-ui-production/resources/rds.tf
Upgrade rds minor version for `laa-court-data-ui-prod`
- Update the postgresql minor version to 14.10 from 14.7
This is to mitigate many CVEs. Also, 14.7 will soon no longer be supported.
=> Upgrade rds minor version for laa-court-data-ui [PROD]

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-dev/resources/rds.tf
The current values are causing issues as they conflict with the same config in `laa-crown-court-remuneration-sandbox-admin`
=> Rename `rds` `snapshot_identifier` and secret name for `laa-crown-court-remuneration-dev`

namespaces/live.cloud-platform.service.justice.gov.uk/money-to-prisoners-test/resources/rds.tf
Previous attempt failed because `prepare_for_major_upgrade` was still true and terraform couldn't successfully apply the changes because of the existence of the parameter group from the PostgreSQL upgrade from `14.x` to `15.x`.
=> MTP-1980: Reset `prepare_for_major_upgrade` flag before upgrading PostgreSQL to 16.1

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-dev/resources/rds.tf
Revert snapshot identifier to try and resolve DB teardown issue
=> Revert snapshot identifier name

namespaces/live.cloud-platform.service.justice.gov.uk/send-legal-mail-to-prisons-prod/resources/rds.tf
SLM-338 - update prepare_for_major_upgrade to false after updating SLM DB version to 14.10 for send-legal-mail-to-prisons-prod namespace.
=> SLM-338 - update prepare_for_major_upgrade to false after updating DB version to 14.10

namespaces/live.cloud-platform.service.justice.gov.uk/send-legal-mail-to-prisons-prod/resources/rds.tf
SLM-338 - set prepare_for_major_upgrade to false after updating DB version to 15.5 for send-legal-mail-to-prisons-prod namespace.
=> SLM-338 - set prepare_for_major_upgrade to false after updating DB version to 15.5 for send-legal-mail-to-prisons-prod namespace.

namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-prod/resources/rds.tf
VB-3380 - set prepare_for_major_upgrade to false after updating DB version to 15.5 for visit-someone-in-prison-backend-svc-prod namespace.
=> VB-3380 - set prepare_for_major_upgrade to false - visit-someone-in-prison-backend-svc-prod namespace.

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-prisoner-download-dev/resources/github_oidc.tf
use the oidc auth to assume the role in GHA, negates the need for token sharing
=> DSOS-2543: add oidc role for offlice file transfer

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-prisoner-download-dev/resources/s3.tf
The referenced bucket is setup with `cloud-platform-terraform-s3-bucket` which enforces encryption as default, so we need to add some encryption permissions to our role.
Also adding a ListBucket permission, as we are using `aws s3 cp` and we think this is required.
=> DSOS-2543: update bucket permissions

namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-saas-test/resources/editor.tf, namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-saas-test/resources/metadata_api.tf
https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_UpgradeDBInstance.PostgreSQL.html#USER_UpgradeDBInstance.PostgreSQL.MajorVersion According to this, we can major upgrade from 12.14 to 15.2 then on to 16+
This PR applies the prepare for major upgrade flag and upgrades to 15.2
=> Upgrade from 12.14 to 15.2

namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-saas-test/resources/editor.tf, namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-saas-test/resources/metadata_api.tf
Going by the email comms regarding upgrading, we were expecting to go from 12.14 to 15.2
When applying the upgrade to 15, we get this failure
According to https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_UpgradeDBInstance.PostgreSQL.html#USER_UpgradeDBInstance.PostgreSQL.MajorVersion 12.17 can target 16.1, but we will need to go to 15.5 and then upgrade the engine from t4g to support 16+
=> Upgrade from 12.17 to 15.5

namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-test-dev/resources/submitter.tf, namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-test-dev/resources/user-datastore.tf
Going from 14.7 to 15.5 
This should satisfy the need to upgrade to latest minor version, as well as giving us longer supported life for the version of Postgres we have.
=> Upgrade platform-test-dev RDS instances

namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-dev/resources/certificates.tf
I've set up two test domains in our dev environment
- https://test1.magistrates.judiciary.uk/
- https://test1.victimscommissioner.org.uk
They both are working and have their TLS certs added the normal default CP way. This tests rolling out existing certs in this looping approach.
=> Add test subdomains and tls cert mapping manifest

namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-test-dev/resources/submitter.tf, namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-test-dev/resources/user-datastore.tf
These RDS instance updates are complete, no longer need this and can revert to default
=> Clean up prepare_for_major_update flags

namespaces/live.cloud-platform.service.justice.gov.uk/legal-framework-api-uat/resources/serviceaccount-circleci.tf
The deleted YAML account had a wider selection of roles so this PR restores the set used on that version
=> LFA-UAT: Extend roles to match previous serviceaccount

namespaces/live.cloud-platform.service.justice.gov.uk/money-to-prisoners-prod/resources/rds.tf
This needs to go back to false before the jump from PostgreSQL `15.5` to `16.1`.
=> MTP-1980: Revert `prepare_for_major_upgrade` before upgrade to `16.1`

namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-saas-live/resources/editor.tf, namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-saas-live/resources/metadata_api.tf
This namespace failed to upgrade to 15.5 as it was on 12.14 not 12.17, according to the [upgrade paths](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_UpgradeDBInstance.PostgreSQL.html#USER_UpgradeDBInstance.PostgreSQL.MajorVersion) I should be able to go to 15.2 then 15.5.
No plans to change engine type at this time as all v15 are supported
=> Upgrade to 15.2

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-education-and-work-plan-dev/resources/rds-postgresql.tf
Upgrade dev RDS instance to 15.5, according to [this guide](https://user-guide.cloud-platform.service.justice.gov.uk/documentation/deploying-an-app/relational-databases/upgrade.html#upgrading-to-a-new-major-database-version).
=> RR-637 - Upgrade RDS to postgres 15.5 - dev

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-education-and-work-plan-dev/resources/rds-postgresql.tf
Now that the RDS instance has been upgraded to 15.5, we need to reset a couple of flags and remove the skip namespace file.
=> RR-637 - Reset dev RDS flags and remove skip namespace file

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-education-and-work-plan-preprod/resources/rds-postgresql.tf
Upgrade pre-prod RDS instance to 15.5, according to [this guide](https://user-guide.cloud-platform.service.justice.gov.uk/documentation/deploying-an-app/relational-databases/upgrade.html#upgrading-to-a-new-major-database-version).
=> RR-638 - Upgrade RDS to postgres 15.5 - pre-prod

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-education-and-work-plan-prod/resources/rds-postgresql.tf
Upgrade production RDS instance to v15.5, as explained in [this guide](https://user-guide.cloud-platform.service.justice.gov.uk/documentation/deploying-an-app/relational-databases/upgrade.html#upgrading-to-a-new-major-database-version).
Once approved, I'll merge this out of hours.
=> RR-639 - Upgrade RDS to postgres 15.5 - prod

namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-prod/resources/justiceinspectorates.tf
Add a new Route53 zone for a new domain coming onto the platform.
=> Add new Route53 zone - justiceinspectorates.gov.uk

.github/workflows/terraform-tools.yml
We're being rate limited when calling tfsec at the moment. Adding a github_token to the action should help fix this (https://github.com/aquasecurity/tfsec-action?tab=readme-ov-file#optional-inputs)
=> Add github token to tfsec

namespaces/live.cloud-platform.service.justice.gov.uk/sjpr-prod/resources/rds-mysql.tf
```Error: updating RDS DB Instance (cloud-platform-47b4127d252f498e): operation error RDS: ModifyDBInstance, https response error StatusCode: 400, RequestID: c2a93fa0-8702-4a84-9c73-e26e96927151, api error InvalidParameterCombination: Cannot upgrade mysql from 8.0.35 to 8.0.33```
Bumping version in terraform to match live state.
=> Bump rds version for sjpr-prod to 8.0.35 to match currently live

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-education-employment-prod/resources/rds-ciag.tf
My previous PR attempted to remove the CIAG API's RDS in prod, but it failed because `deletion_protection` was set to `true`. This PR restores the `rds-ciag.tf` resource, but with `deletion_protection` set to false.
Once this is merged, I will then create another PR to remove the resource entirely.
=> RR-530 - Restore ciag-rds without deletion protection

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-events-dev/resources/hmpps-education-and-work-plan-api.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-events-dev/resources/outputs-to-ssm-parameters.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-events-dev/resources/variables.tf
This PR reverts [this change](https://github.com/ministryofjustice/cloud-platform-environments/pull/21064/files) I made earlier, which caused the following error:
```
FATA[0046] error running terraform on namespace hmpps-domain-events-dev: unable to apply Terraform: exit status 1
Error: deleting IAM Policy (arn:aws:iam::754256621582:policy/cloud-platform/sqs/cloud-platform-sqs-7f8e777ec329): DeleteConflict: Cannot delete a policy attached to entities.
status code: 409, request id: 8f044e96-566e-41ae-81df-98ce18215dc1
```
I'll look into this separately, but in the meantime I'm assuming it might be best to revert that change.
=> RR-641 - Revert changes to education-and-work-plan in domain-events-dev

namespaces/live.cloud-platform.service.justice.gov.uk/laa-claim-non-standard-magistrate-fee-dev/resources/serviceaccount.tf
Repeating for `laa-claim-non-standard-magistrate-fee-dev` what we did recently for `laa-claim-non-standard-magistrate-fee-dev` to aid dynamic per-branch releases
=> CRM457-1061: Update serviceaccount permissions

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-preprod/resources/rds.tf
This PR has 2 commits.
- First to disable the prepare_for_upgrade flag on primary rds and enable for read-replica. This is then applied manually to fix the terraform error  DBParameterGroupAlreadyExists: Parameter group cloud-platform-XXX already exists
- 2nd commit to disable the flag in read replica
=> fix replica upgrade

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-dev/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-dev/resources/variables.tf
We now have a shared inbox rather than the original CAS3 only email that we had at the time of setting up our environments. This should ensure no requests are lost.
=> Update CAS dev support email address

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-prod/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-prod/resources/variables.tf
We now have a shared inbox rather than the original CAS3 only email that we had at the time of setting up our environments. This should ensure no requests are lost.
=> Update CAS prod support email address

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-test/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-test/resources/variables.tf
We now have a shared inbox rather than the original CAS3 only email that we had at the time of setting up our environments. This should ensure no requests are lost.
=> Update CAS test support email address

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-preprod/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-preprod/resources/variables.tf
We now have a shared inbox rather than the original CAS3 only email that we had at the time of setting up our environments. This should ensure no requests are lost.
=> Update CAS preprod support email address

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-electronic-monitoring-dev/resources/emds-s3.tf
Creating a bucket under the hmpps-em dev namespace for the purpose of ingesting unstructured data via the electronic monitoring landing zone. The existing resource is associated with CEMO, a parallel but separate project, and so separating resources is preferable.
=> Electronic monitoring dev resource

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-application-store-dev/resources/serviceaccount.tf
restore 
```
serviceaccount_name  = "circleci"
```
as the last PR store k8 auth from working https://app.circleci.com/pipelines/github/ministryofjustice/laa-crime-application-store/338/workflows/e9ae8460-3f62-478e-a70c-d59effbb8b11/jobs/2100/steps
and this was the only significant difference that could be identified as a potential cause
=> Restore variable removed in last PR

namespaces/live.cloud-platform.service.justice.gov.uk/makeaplea-dev/resources/api-gateway-iam.tf
The prevoius PR failed due to duplicate IAM policy name: https://github.com/ministryofjustice/cloud-platform-environments/pull/21388
=> Make a plea dev: rename iam policy to fix concourse error

namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-find-moj-data-dev/resources/secret.tf
underscores in secret names were causing the terraform apply to fail. This corrects that
=> remove underscores from secret names

namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-find-moj-data-dev/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-find-moj-data-dev/resources/ecr.tf, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-find-moj-data-dev/resources/serviceaccount.tf
We have renamed this back to the original name and created a separate `data-catalogue` repo.
=> Revert rename of find-moj-data repo

namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-live-dev/resources/serviceaccount-formbuilder-submitter-workers-live-dev.tf, namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-live-dev/submitter-workers-service-account.yaml
1. merge this PR in
2. copy the new token to wherever it needs to go '''cloud-platform decode-secret -s formbuilder-submitter-workers-live-dev-migrated-token -n formbuilder-platform-live-dev'''
Feel free to change and amend the newly added serviceaccount terraform in the PR.
[Docs for migration](https://user-guide.cloud-platform.service.justice.gov.uk/documentation/other-topics/moving-service-accounts-to-terraform.html#moving-from-yaml-defined-service-accounts-to-terraform-module)
=> formbuilder-platform-live-dev -- 🤖 migrating sa yaml formbuilder-submitter-workers-live-dev

namespaces/live.cloud-platform.service.justice.gov.uk/contact-moj-production/resources/serviceaccount-circleci.tf
Following on from https://github.com/ministryofjustice/cloud-platform-environments/pull/21567
=> Specify rolebinding name for 2nd service account

namespaces/live.cloud-platform.service.justice.gov.uk/cfe-civil-production/resources/pingdom.tf
updating the URL pingdom uses to check the service is up.
the new status endpoint has a DB check
QUESTION:
We have the APPLY_SKIP_PIPELINE file on the namespace for a DB upgrade. Will that affect this PR ie. will it prevent this change from occurring until after that skip file is removed?
=> CFE Civil PROD update pingdom url

namespaces/live.cloud-platform.service.justice.gov.uk/cfe-civil-production/resources/pingdom.tf
original PR failed on the apply concourse https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/environments-live/jobs/apply-namespace-changes-live/builds/3147
I had incorrectly change the host and not the url
this PR reverts to the correct host and points to the new url
=> CFE Civil PROD update pingdom url correctly

namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-test-production/resources/service_accounts.tf
Using different names to avoid clash, will get renamed later on once the old SA are deleted.
=> Add new TF service accounts

namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-test-production/resources/service_token_cache.tf
Concourse failed as the token name was wrong, using the local variable as a way to ensure this reference is always correct
=> Ensure token names match

namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-services-test-dev/resources/serviceaccount.tf, namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-services-test-dev/resources/variables.tf
This rule appears not to have the permissions listed in the variable default, so try adding them directly
I can see when running get configmaps using the token from the service account this role is bound to that if I target the wrong namespace it says 'role not found' but if I target the correct namespace it says 'permission denied', so I guess the rules weren't applied, hopefully this does work :smile:
=> Add rules to role to allow access to configmaps

namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-saas-test/resources/service-token-cache.tf
The saas-test env holds the editor, which the service token cache in platform-test-dev and platform-test-production need access to
=> Add configmaps access to service-token-cache for editor envs

namespaces/live.cloud-platform.service.justice.gov.uk/laa-fala-staging/resources/s3.tf
- Added `public_read` ACL. 
- Disabled blocking public access.
=> Adjusted access control limits on FALA Staging S3 Bucket

namespaces/live.cloud-platform.service.justice.gov.uk/laa-fala-production/resources/s3.tf
Sets ACL on FALA S3 Bucket to `public-read`.
Disables `enable_allow_block_pub_access`.
=> Enabled public read on laa-fala-production S3 bucket

namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-services-test-production/01-rbac.yaml
This has been replaced by a module derived role binding with only necessary permission
=> Remove cluster admin rolebinding for service-token-cache in test-prod

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-delius-alfresco-dev/resources/irsa.tf
This is required to allow us to sync data between environments for testing
=> NIT-1098 allow access to bucket in lower env

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-events-dev/resources/hmpps-activities-management.tf
The subscription to the Domain event 'alerts updated' in activities management was not quite right.
This PR corrects that mistake.
=> SAA-1629 correcting the prisoner alert event type for activities management, it was incorrect.

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-events-preprod/resources/hmpps-activities-management.tf
Adds subscription to the prisoner alerts updated domain event for the activities management service in preprod.
We already subscribe to this in dev, see PR [here](https://github.com/ministryofjustice/cloud-platform-environments/pull/21954).  We are now in the process of rolling this out to preprod and then prod.  Prod will be done as a separate PR.
=> SAA-1629 adding missing prisoner alert domain event for the activities serivce in preprod.

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-prisoner-cell-allocation-preprod/06-certificate.yaml
Use separate certs for CSC UI and API (preprod)
=> MAP-16: Use separate certs for CSC UI and API (preprod)

namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-saas-test/resources/fb-av-service-account.tf
We've now had old service accounts removed, we will rotate back to this service name to avoid updating downstream references
=> Update name of service account

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-events-prod/resources/hmpps-activities-management.tf
Adds subscription to the prisoner alerts updated domain event for the activities management service in prod.
=> SAA-1629 adding missing prisoner alert domain event for the activities service in prod.

namespaces/live.cloud-platform.service.justice.gov.uk/cfe-civil-uat/resources/ecr.tf
Images are [now tagged by environment](https://github.com/ministryofjustice/cfe-civil/pull/558), and this change changes the lifecycle to reflect that. The idea that lots of builds of one environment does not cause the cleanup of images in use by another environment.
=> LEP-508 Fix expiration of production image

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-events-dev/resources/hmpps-activities-management.tf
This is a transitional PR to replace two events we currently listen to with prisoner search based events instead.
The `prisoner-offender-search.prisoner.released` in particular should be used going forwards as this does not have  induced delay of 45mins for the `prison-offender-events.prisoner.released` which has caused timing issues in production.
```
prison-offender-events.prisoner.received -> prisoner-offender-search.prisoner.received
prison-offender-events.prisoner.released -> prisoner-offender-search.prisoner.released
```
As a first pass we will keep all events so we so not miss any existing events. This may be overkill.
=> SAA-1628 this change introduces two replacement prisoner search events for the prisoner offender events. This is a transitionary change.

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-events-dev/resources/hmpps-activities-management.tf
This removes now redundant events which have been superseded by events added in the transitional PR [here](https://github.com/ministryofjustice/cloud-platform-environments/pull/22130).
=> SAA-1628 this change removes now redundant prisoner offender events which have been replace with prisoner search events.

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-events-prod/resources/hmpps-activities-management.tf
These two events are now redundant.
They have been superseded in previous PR [here](https://github.com/ministryofjustice/cloud-platform-environments/pull/22158).
=> SAA-1628 this change removes now redundant prisoner offender events which have been replaced with prisoner search events.

namespaces/live.cloud-platform.service.justice.gov.uk/intranet-dev/resources/cross-iam-role-sa.tf, namespaces/live.cloud-platform.service.justice.gov.uk/intranet-dev/resources/irsa.tf, namespaces/live.cloud-platform.service.justice.gov.uk/intranet-dev/resources/s3.tf
We intend to sync from a source S3 bucket `intranet2-staging-storage-h1d4c9820k0u`, owned by a different AWS account.
Following the [Migrate from existing buckets guide](https://github.com/ministryofjustice/cloud-platform-terraform-s3-bucket#migrate-from-existing-buckets), I understand that the source bucket must be added to the `user_policy` here.
This PR adds the relevant change to our s3 resource definition.
cc: @EmilyHazlehurst @wilson1000
=> Adds our legacy staging S3 resource to user-policy to allow one-way sync.

namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-prod/resources/rds-pre-sentence-service.tf
Upgrade `pre-sentence-service` RDS minor version to 14.11 to match non-prod instance for database dev/prod parity
for **Prod**
=> pre-sentence-service-prod: Upgrade RDS minor version

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-litigator-fees-dev/resources/rds.tf
LAWS-3733: removed snapshot identifier from RDS
=> LAWS-3733: removed snapshot identifier from RDS

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-education-and-work-plan-dev/resources/irsa.tf
We want to use SQS from our UI, but the IRSA service account name is suffixed with `-api`.  Removing this so it can be used by either.
=> Removed suffix from service account name

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-preprod/resources/rds_postgres.tf
We are currently in the process of creating a Postgres Database to temporarily store hmpps-related events. Once a table is initialised within Postgres, it will be used by both the event notifier and the event handler.
=> Setting up new RDS service for our new Postgres database (PREPROD)

namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-dev/resources/rds.tf
removed rds: from snapshot identifier
=> Hale Dev DR test

namespaces/live.cloud-platform.service.justice.gov.uk/cjse-dev/resources/irsa.tf, namespaces/live.cloud-platform.service.justice.gov.uk/cjse-dev/resources/rds-mssql.tf
- Create read-only replica
- Upgrade the database to SQL server 2022 from SQL server 2019
- Add config maps for both primary and read-only replicas for instance endpoints and addresses
- Add secret for username and password
=> CJS-54 MSSQL RDS read-only replica created

namespaces/live.cloud-platform.service.justice.gov.uk/pathfinder-dev/00-namespace.yaml
Update the team name for the pathfinder namespaces to the "DPS Pathfinder Production Releases" team
=> SI-658-update-pathfinder-team-names

namespaces/live.cloud-platform.service.justice.gov.uk/pathfinder-preprod/00-namespace.yaml
Update the team name for the pathfinder pre-prod namespace to the "DPS Pathfinder Production Releases" team
=> SI-658-update-pathfinder-team-name-preprod

namespaces/live.cloud-platform.service.justice.gov.uk/intranet-dev/resources/acm.tf, namespaces/live.cloud-platform.service.justice.gov.uk/intranet-dev/resources/cloudfront.tf
This PR removes:
- CloudFront aliases.
- Route53 records
- acm certificates.
This is an aim to at least prove that the PEM and access restriction that I added to the CloudFront module is working as intended.
=> intranet-dev - Remove aliases and certs etc. To validate the PEM/restrictions on CloudFront worked.

namespaces/live.cloud-platform.service.justice.gov.uk/intranet-dev/06-certificate.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/intranet-dev/resources/cloudfront.tf, namespaces/live.cloud-platform.service.justice.gov.uk/intranet-dev/resources/route53.tf, namespaces/live.cloud-platform.service.justice.gov.uk/intranet-dev/resources/variables.tf
Created route53 & cert definitions.
This is a step towards having a subdomain for CloudFront CDN. 
We'll pass the name_servers output to operations-engineering.
CC @wilson1000
=> intranet-dev: Add a base domain dev.intranet.justice.gov.uk 

namespaces/live.cloud-platform.service.justice.gov.uk/intranet-dev/resources/route53.tf
Error: deleting Route53 Hosted Zone (Z10272571XL2RC8CGGC7S): HostedZoneNotEmpty: The specified hosted zone contains non-required resource record sets and so cannot be deleted.
status code: 400, request id: a8c568fe-5df1-4417-858e-a8ed509e58b7
=> intranet-dev re-add route53 zone because deleting it was erroring

namespaces/live.cloud-platform.service.justice.gov.uk/cjse-dev/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/cjse-dev/resources/serviceaccount.tf
The following repo is added to the service account and namespace: [moj-cjse-xhibit-webportal-prototype](https://github.com/ministryofjustice/moj-cjse-xhibit-webportal-prototype)
=> CJS-102/CJS-244 Add git repo to namespace and service account

namespaces/live.cloud-platform.service.justice.gov.uk/intranet-dev/resources/cloudfront.tf, namespaces/live.cloud-platform.service.justice.gov.uk/intranet-dev/resources/variables.tf
```
Error: deleting CloudFront PublicKey (K3P2N9XAOU6Q1Y): PublicKeyInUse: The Cloudfront public key is currently associated with either Key Group or a field level encryption profile.
```
=> intranet-dev - use associate flag to disacotiate an old trusted_public_key

namespaces/live.cloud-platform.service.justice.gov.uk/intranet-dev/resources/acm.tf, namespaces/live.cloud-platform.service.justice.gov.uk/intranet-dev/resources/cloudfront.tf, namespaces/live.cloud-platform.service.justice.gov.uk/intranet-dev/resources/route53.tf
To merge **after** Cloud Platform NS are added to DNS for `intranet.justice.gov.uk`.
=> intranet-dev add CloudFront alias with acm and route53 records

namespaces/live.cloud-platform.service.justice.gov.uk/intranet-dev/resources/acm.tf
Brings `aws_acm_certificate_validation` into the same region as `aws_acm_certificate`
=> intranet-dev - Update acm.tf

namespaces/live.cloud-platform.service.justice.gov.uk/intranet-production/resources/route53.tf
@wilson1000 FYI you were right, k8s Ingres will create the necessary A records. Removing cnames here will fix a clash of duplicate entries.
=> intranet-production - remove cname records for dev, demo, staging

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-a-video-link-dev/01-rbac.yaml
This group is required by the HAAR team so they can add the secrets required for HMPPS Auth.
=> BAVL-13 add missing rbac group required by the HAAR team to add auth kube secrets.

namespaces/live.cloud-platform.service.justice.gov.uk/cccd-dev/resources/irsa.tf
disable CCR policies for landing zone until migrated sqs policies have been fully tested and migrated
=> Remove CCR landing zone SQS access policies

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-dev/resources/api_gateway.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-dev/resources/iam.tf
Addressing these errors:
Error: creating API Gateway Integration: NotFoundException: Invalid Method identifier specified
with aws_api_gateway_integration.sqs_integration,
on api_gateway.tf line 159, in resource "aws_api_gateway_integration" "sqs_integration":
159: resource "aws_api_gateway_integration" "sqs_integration" {
Error: putting API Gateway Integration Response: NotFoundException: Invalid Method identifier specified
with aws_api_gateway_integration_response.sqs_integration_response,
on api_gateway.tf line 174, in resource "aws_api_gateway_integration_response" "sqs_integration_response":
174: resource "aws_api_gateway_integration_response" "sqs_integration_response" {
Error: creating IAM Policy (hmpps-integration-api-dev-api-gateway-sqs-policy): MalformedPolicyDocument: Syntax …
=> Addressing errors in CI

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-a-video-link-dev/06-certificate.yaml
Changes needed to match certs with the actual code base helm configs.
`The name of the kubernetes secret where the certificate is stored is used as a value to the helm chart - this is used to configure the ingress.`
UI [here](https://github.com/ministryofjustice/hmpps-book-a-video-link-ui/blob/main/helm_deploy/hmpps-book-a-video-link-ui/values.yaml#L18)
API [here](https://github.com/ministryofjustice/hmpps-book-a-video-link-api/blob/main/helm_deploy/hmpps-book-a-video-link-api/values.yaml#L15)
=> BAVL-13 bring cert secret names in sync with UI/API helm config/locations.

namespaces/live.cloud-platform.service.justice.gov.uk/makeaplea-dev/resources/irsa.tf, namespaces/live.cloud-platform.service.justice.gov.uk/makeaplea-dev/resources/outputs.tf
Celery tasks requires an assume role policy allow irsa role access to the specific sqs queues
=> Attach new assume role policy to the irsa policy 

namespaces/live.cloud-platform.service.justice.gov.uk/manage-soc-cases-dev/resources/serviceaccount-refreshclamav.tf
Updates the refreshclamav service account config for manage-soc-cases/dev only. 
If successful in resolving the issue, will apply to pre-prod, prod, and pathfinder dev / pre-prod / prod.
=> [SI-928] Update ClamAV Refresh job service account - manage-soc-cases/dev

namespaces/live.cloud-platform.service.justice.gov.uk/manage-soc-cases-prod/resources/serviceaccount-refreshclamav.tf
Follows on from: https://github.com/ministryofjustice/cloud-platform-environments/pull/22774
Applies the same fix to `manage-soc-cases` prod
=> [SI-928] Update ClamAV Refresh job service account - soc prod

namespaces/live.cloud-platform.service.justice.gov.uk/pathfinder-preprod/resources/serviceaccount-refreshclamav.tf
Follows on from: https://github.com/ministryofjustice/cloud-platform-environments/pull/22774
Applies the same fix to `pathfinder` preprod
=> [SI-928] Update ClamAV Refresh job service account - pathfinder preprod

namespaces/live.cloud-platform.service.justice.gov.uk/pathfinder-prod/resources/serviceaccount-refreshclamav.tf
Follows on from: https://github.com/ministryofjustice/cloud-platform-environments/pull/22774
Applies the same fix to `pathfinder` prod
=> [SI-928] Update ClamAV Refresh job service account - pathfinder prod

namespaces/live.cloud-platform.service.justice.gov.uk/manage-soc-cases-preprod/resources/serviceaccount-refreshclamav.tf
Follows on from: https://github.com/ministryofjustice/cloud-platform-environments/pull/22774
Applies the same fix to `manage-soc-cases` preprod
=> [SI-928] Update ClamAV Refresh job service account - soc preprod

namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-kpi-dashboard-poc/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-kpi-dashboard-poc/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-kpi-dashboard-poc/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-kpi-dashboard-poc/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-kpi-dashboard-poc/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-kpi-dashboard-poc/resources/irsa.tf, namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-kpi-dashboard-poc/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-kpi-dashboard-poc/resources/rds.tf, namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-kpi-dashboard-poc/resources/serviceaccount.tf, namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-kpi-dashboard-poc/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-kpi-dashboard-poc/resources/versions.tf
- In relation to https://github.com/ministryofjustice/operations-engineering/issues/4420
- To start storing live KPI data 
- Added `operations-engineering-kpi-dashboard-poc` namespace
- Added PostgresDB to store KPI Data
- This namespace is mainly to extend the PoC to prove the capture of live data instead of using locally stubbed data
=> ✨ Add `operations-engineering-kpi-dashboard-poc` namespace

namespaces/live.cloud-platform.service.justice.gov.uk/cloud-platform-label-pods/06-mutating-webhook.yaml
this will label pods all newly created pods with their github teams (pulled from rbac rolebinding) with the following format `<team-a>_<team-b>`
=> feat: 🎸 turn on label pods webhook

namespaces/live.cloud-platform.service.justice.gov.uk/tariq-test/resources/s3.tf, namespaces/live.cloud-platform.service.justice.gov.uk/tariq-test/resources/versions.tf
Test upgrade of S3 using aws 4.00 to 5.00 using the Branch aws-provider-bump in the Repo cloud-platform-terraform-s3-bucket
=> upgrade S3 from hashicorp/aws version 4.00 to 5.00

namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-preprod/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-preprod/resources/variables.tf
- Allow the probation-in-court github team to access preprod aws resources via the aws console
=> Authorise the probation-in-court GitHub team to preprod resources

namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-dev/resources/main.tf
Enable access to aws resources for court probation DEV
=> Add tagging to access aws resources for court-probation-dev

namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-preprod/resources/main.tf
Enable access to aws resources for court probation PREPROD
=> Add tagging to access aws resources for court-probation-preprod

namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-dev/resources/secrets.tf
Add slack-webhook url as an aws secret for court-probation-dev
=> Add slack-webhook as aws secret court-probation-dev

namespaces/live.cloud-platform.service.justice.gov.uk/laa-access-civil-legal-aid-dev/resources/serviceaccount.tf
Re-creates the service account with a github environment argument.
=> Re-create-service-account-in-laa-access-civil-legal-aid-dev

namespaces/live.cloud-platform.service.justice.gov.uk/laa-access-civil-legal-aid-uat/resources/serviceaccount.tf
Removes the service account from laa-access-civil-legal-aid so it can be re-created in a subsequent PR.
=> Remove service account from laa-access-civil-legal-aid-uat

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-dev/resources/pingdom.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-dev/resources/versions.tf
This follows the [How to create pingdom checks](https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-pingdom-checks.html#creating-pingdom-checks)
It adds 2 files in the resources directory of laa-crown-court-remuneration-dev to `versions.tf` and creates a `pingdom.tf` file.
It also adds an integrationids to the pingdom.tf. 
[CCR setup site Pingdom health stats](https://dsdmoj.atlassian.net/browse/CTSKF-756l)
=> Ctskf 756 ccr setup site pingdom health stats

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-dev/resources/pingdom.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-dev/resources/variables.tf
Concourse is [failing](https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/environments-live/jobs/apply-namespace-changes-live/builds/4432) with the error
```
Error: 400 Bad Request: Invalid parameter tags value application_Crown Court Remuneration,businessunit_LAA,component_ping,environment_$environment_development,infrastructuresupport_Crown Court Remuneration,isproduction_false
with pingdom_check.laa-crown-court-remuneration-dev,
on pingdom.tf line 4, in resource "pingdom_check" "laa-crown-court-remuneration-dev"
```
I believe this is being caused by an incorrect tags in `laa-crown-court-remuneration-dev/resources/pingdom.tf`. This corrects the `environment`, `application` and `infrastructure_support` tags.
=> Fix tags in laa-crown-court-remuneration-dev/resources/pingdom.tf

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-dev/resources/variables.tf
An attempt to fix failing build https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/environments-live/jobs/apply-namespace-changes-live/builds/4433:
```
Error: 400 Bad Request: Invalid parameter tags value application_crown-court-remuneration,businessunit_LAA,component_ping,environment_development,infrastructuresupport_laaclairtaskforce@digital.justice.gov.uk,isproduction_false
```
which might be being caused by the uppercase `businessunit`.
=> Lower case CCR dev business_unit

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-dev/resources/s3_truststore.tf
Our events service is failing its initial deployment to dev I believe to Env variables not being set. I have set some dummy values in an effort to see if we can move onto a new error message.
=> Create event service truststore secrets sys int api

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-dev/resources/s3_truststore.tf
We'll need a password for our .p12 certificate stored in a kubernetes secret. We can have a random password created with terraform and take this password and set it as the p12 password.
=> Generate event service password sys int events dev

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-dev/05-prometheus.yaml
This ticket is part of CCRs migration into Cloud Platform - setting up and configuring alerts. [CCR monitor and alerting migration setup Setup slack AlertManager integration](https://dsdmoj.atlassian.net/browse/CTSKF-753)
A support ticket was created to provide a custom alert route [Set up Alert manager Slack integration for CCR dev](https://github.com/ministryofjustice/cloud-platform/issues/5627). When this was completed a custom severity id was provided which has now been added to each alert.
=> Add integration id

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-dev/resources/iam.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-dev/resources/irsa.tf
Our Pods don't have get access to secrets and as a result we need to update our policies
=> Adding policy to retrieve secrets value

namespaces/live.cloud-platform.service.justice.gov.uk/laa-assess-crime-forms-dev/00-namespace.yaml
Add missing  namespace label to namespace config
This missing label relied on by network policy in app-store-dev
This will allow connection to a postgres pod in app store dev
via internal service name from a metabase app instance 
hosted in this namespace, laa-assess-crime-forms-dev.
=> CRM457-1334: Add missing namespace label

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-incident-reporting-dev/00-namespace.yaml
So that we have visibility over potential problems early on.
=> IR-256: `dev`: Send alerts to our dev channel

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-incident-reporting-preprod/00-namespace.yaml
So that we have visibility over potential problems early on.
=> IR-256: `preprod`: Send alerts to our dev channel

namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-dev/00-namespace.yaml
Update the slack alert channel to `probation_in_court_alerts_dev`
=> court-probation-dev: Update slack alert channel

namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-preprod/00-namespace.yaml
Update the slack alert channel to `probation_in_court_alerts_preprod`
=> court-probation-preprod: Update slack alert channel

namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-prod/00-namespace.yaml
Update the slack alert channel to `probation_in_court_alerts_prod`
=> court-probation-prod: Update slack alert channel

namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-prod/08-prometheus-sqs.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-prod/09-prometheus-k8s.yaml
Update the severity label to `probation_in_court_alerts_prod` to link to a new Alertmanager routing.
This is part of a wider feature to split out our alert notifications based off of the environment - sending alerts based off that too.
=> court-probation-prod: Update severity label to alertmanager routing

namespaces/live.cloud-platform.service.justice.gov.uk/parliamentary-questions-development/resources/serviceaccount-github.tf
The serviceaccount, role and rolebinding values clashed with the default values that are being used for the circleCI module
=> Override serviceaccount, role and rolebinding default values

namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-civil/resources/secret.tf
* Added `caab-api-auth-secrets`
* Added `caab-assessment-api-auth-secrets`
* Added `caab-soa-api-auth-secrets`
* Added `caab-ebs-api-auth-secrets`
* Added `caab-ui-secrets`
This is to support app to app authentication between LAA CCMS CAAB services. Related helm chart changes: https://github.com/ministryofjustice/laa-ccms-caab-helm-charts/pull/9
=> Story: [CCLS 2191] Add Auth Secrets for LAA CCMS CAAB Apps

.github/workflows/skip-file-auto-approval.yaml
pull request require a member of the webops team to approve github-action-bot isnt able to approve on behalf of the webops team
=> feat(workflow): change token used to use concourse-bot user to approve skip-file

namespaces/live.cloud-platform.service.justice.gov.uk/c100-application-staging/resources/variables.tf
Bumps RDS version from 14.7 to 14.11 to match automatic upgrade via AWS.
Pipeline should show no terraform changes as this change is already live.
=> chore: bump rds to 14.11 to match live

namespaces/live.cloud-platform.service.justice.gov.uk/laa-cla-backend-production/resources/rds.tf
Allow performance insights to be used on our prod database and small metabase database
=> Add in performance insights to main database and metabase

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-non-associations-preprod/00-namespace.yaml
Send non-associations' `preprod` alerts to our dev Slack channel.
=> NON-318: Send `preprod` alerts to dev Slack channel

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-incentives-dev/00-namespace.yaml
Send Incentives' `dev` alerts to `incentives-dev` Slack channel.
=> INC-1335: Send `dev` alerts to dev Slack channel

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-application-store-dev/04-networkpolicy.yaml
Allow ingress from UAT (laa-crime-application-store-uat) on DEV (laa-crime-application-store-dev)
This is to allow connection of a metabase instance hosted in UAT to postgres pod databases (helm chart created) in DEV
=> CRM457-1487: Allow ingress from UAT on DEV

namespaces/live.cloud-platform.service.justice.gov.uk/laa-cwa-test/resources/main.tf
Added 
```GithubTeam    = var.team_name```
to main.tf file so I can view my secrets in AWS Console and resolve access issues.
=> tag all resources with team name so they are viewable in AWS Console

namespaces/live.cloud-platform.service.justice.gov.uk/tim-development/resources/opensearch-alert.tf
We are using aws provider major version 4 for all other module but we are using aws provider major version 5 for OpenSearch Alert module. 
This testing is to verify if we can create OS alert with aws provider major version 4 to align all module version
=> chore: Test opensearch alert module with downgrade provider

namespaces/live.cloud-platform.service.justice.gov.uk/laa-submit-crime-forms-dev/resources/s3.tf
Hoping to define a metrics filter that filters _all_ objects in the bucket, so that in [Grafana](https://grafana.live.cloud-platform.service.justice.gov.uk/d/AWSS31iWk/aws-s3?orgId=1&var-datasource=P896B4444D3F0DAB8&var-region=default&var-bucket=cloud-platform-5964914c521cc2f2700c40908cdf2e30&var-filterid=) the 'Filtered Requests' graph gets populated.
I know that I haven't included a `filter` block, but the [documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket_metric) states that that block requires me to give criteria to filter by, and I don't want to actually filter anything out. 
Also the docs suggest I should give the bucket `id` in this block, but that attribute doesn't exist so I'm trying `bucket_name` instead.
=> CRM457-1468: Try adding a metric configuration

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-a-video-link-dev/resources/irsa.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-a-video-link-dev/resources/variables.tf
BVLS service was missing the IRSA file responsible for setting up the queue permissions for the service.  As a result the necessary secrets are not showing up in the namespace.
=> BAVL-25 add missing irsa file for setting up queue permissions for the BVLS service.

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-non-associations-dev/resources/rds.tf
Depends on [hmpps-non-associations-api#304](https://github.com/ministryofjustice/hmpps-non-associations-api/pull/304)
=> NON-363: Update RDS terraform module for `hmpps-non-associations-dev`

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-incident-reporting-dev/resources/rds.tf
Depends on [hmpps-incident-reporting-api#127](https://github.com/ministryofjustice/hmpps-incident-reporting-api/pull/127)
=> IR-283: Update RDS terraform module for `hmpps-incident-reporting-dev`

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-non-associations-preprod/resources/rds.tf
Depends on [hmpps-non-associations-api#304](https://github.com/ministryofjustice/hmpps-non-associations-api/pull/304)
=> NON-363: Update RDS terraform module for `hmpps-non-associations-preprod`

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-incident-reporting-preprod/resources/rds.tf
Depends on [hmpps-incident-reporting-api#127](https://github.com/ministryofjustice/hmpps-incident-reporting-api/pull/127)
=> IR-283: Update RDS terraform module for `hmpps-incident-reporting-preprod`

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-non-associations-prod/resources/rds.tf
Depends on [hmpps-non-associations-api#304](https://github.com/ministryofjustice/hmpps-non-associations-api/pull/304)
=> NON-363: Update RDS terraform module for `hmpps-non-associations-prod`

namespaces/live.cloud-platform.service.justice.gov.uk/parliamentary-questions-production/resources/pingdom.tf
The healthcheck endpoint relies on the status of an external service (PQA API). Using /ping will just signal if the web application itself is available or not.
=> Set Pingdom to check /ping endpoint for pq-production

namespaces/live.cloud-platform.service.justice.gov.uk/laa-submit-crime-forms-dev/resources/variables.tf
Add networking policies permission to circle service account [DEV]
need to spin up custom networke policies labels for branch
builder.
Also removing old, no longer required hpa permissions.
=> CRM457-1360: Add networking policies permission to circle service account [DEV]

.github/workflows/malformed-yaml.yml
resolves multi-doc parse and deleted yaml failing: https://github.com/ministryofjustice/github-actions/releases/tag/v18.1.1
=> chore: 🤖 bump malformed-yaml action to latest

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-a-video-link-dev/resources/domain-events-queue-bvls.tf
Adding subscription to a new BLVS domain event to for the BVLS service for processing the cancellation of booking events.
=> BAVL-213 adding subscription to the video booking cancelled domain event for the BVLS service.

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-probation-search-dev/resources/opensearch.tf
to handle additional load required for testing semantic search.
=> PI-2277 Increase OpenSearch cluster size

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-probation-search-dev/resources/opensearch.tf
This is a temporary increase in resources to test semantic search requirements.
=> PI-2277 Switch to compute-optimized OpenSearch instances

namespaces/live.cloud-platform.service.justice.gov.uk/laa-submit-crime-forms-dev/06-prometheus-custom-rules.yaml
Disable dead job alert on on DEV
To avoid noise from DEV branch built deployments
=> Submit DEV: Disable dead job alert

namespaces/live.cloud-platform.service.justice.gov.uk/create-and-vary-a-licence-test2/resources/rds.tf
Bump RDS version to match what's in live. Should be no terraform changes.
=> chore: bump rds version to match live

namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-dev/resources/rds-pre-sentence-service.tf, namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-dev/resources/rds.tf
Update the RDS terraform module version for `court-case-service-dev`
This includes an update to our ca-cert-identifier to `rds-ca-rsa2048-g1` as the previous is soon about to reach EOL.
=> court-case-service-dev Update rds terraform module version

namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-preprod/resources/rds-pre-sentence-service.tf, namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-preprod/resources/rds.tf
Update the RDS terraform module version for `court-case-service-preprod`
This includes an update to our ca-cert-identifier to `rds-ca-rsa2048-g1` as the previous is soon about to reach EOL.
=> Update RDS terraform module to latest for PREPROD

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-litigator-fees-dev/resources/rds.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-dev/resources/rds.tf
These 2 namespaces are using ref=migration for their migration work and we should keep it instead of using 7.0.0.
Concourse error [here](https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/environments-live/jobs/apply-namespace-changes-live/builds/5415.6#L667507c5:8004)
=> fix: Revert RDS module version for LAA namespace

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-dev/cronjob-check-certs-expiry.yaml
PR to create a cronjob which will run at 7am Mon-Fri which will run a script from the hmpps-integration-api repo which checks to see if a certificate is going to expire
=> Create certificate expiry cronjob

namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-prod/resources/rds-pre-sentence-service.tf, namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-prod/resources/rds.tf
Update the RDS terraform module version for `court-case-service-prod`
This includes an update to our ca-cert-identifier to `rds-ca-rsa2048-g1` as the previous is soon about to reach EOL.
=> Update RDS terraform module to latest for PROD 

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-application-store-dev/05-prometheus-custom-rules.yaml
CRM457-1699: Ignore 5xx errors on metabase ingress
Because  they are noisy and unimportant as far as we understand
Note that DEV does not have a metabase instance in any event but this has been added for consistency with UAT and PROD that do.
=> CRM457-1699: Ignore 5xx errors on metabase ingress appstore DEV

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-application-store-uat/05-prometheus-custom-rules.yaml
Ignore 5xx errors on metabase ingress
Because they are noisy and unimportant as far as we understand
=> CRM457-1699: Ignore 5xx errors on metabase ingress appstore UAT

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-complexity-of-need-staging/resources/rds.tf
Standardising naming of secrets/configmap to be the same as in preprod and production namespaces.
Old, existing secret will be deleted once no longer needed.
=> Create CNL staging RDS secret and configmap

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-complexity-of-need-staging/resources/ecr.tf
This reverts commit e53511a9478af87ed472d8a67ef7c8108ee8c43b.
ECR repo is not empty and previous PR can't delete it.
Will raise a separate PR to disable the deletion protection.
=> Revert "Delete unused CNL staging ECR repo (#24148)"

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-complexity-of-need-staging/resources/ecr.tf
This ECR is no longer in use so we can delete it.
A separate PR will be raised to actually delete it after this flag has been applied.
=> Disable CNL staging ECR deletion protection

namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-prod/resources/certificates.tf
Add new TLS cert to support the launch of the new PPO site, an archive site will be setup for legacy content not migrated.
=> Add PPO archive site TLS cert

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-a-video-link-dev/resources/domain-events-queue-bvls.tf
Listen for the prisoner released event in the Book a Video Link Service so we can alter bookings for the released offender should there be any matches.
=> BAVL-235 listen for prison release events in BVLS so can alter video bookings accordingly.

namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-prod/07-certificate.yaml
Include pre-sentence-service in certificates so that it can use TLS e.g. https
=> Court Probation Prod: Include pre-sentence-service in certificates

namespaces/live.cloud-platform.service.justice.gov.uk/peoplefinder-development/APPLY_PIPELINE_SKIP_THIS_NAMESPACE, namespaces/live.cloud-platform.service.justice.gov.uk/peoplefinder-development/resources/rds.tf
Following https://user-guide.cloud-platform.service.justice.gov.uk/documentation/deploying-an-app/relational-databases/upgrade.html#upgrading-to-a-new-major-database-version
=> CDPT-1819: Peoplefinder DB Update from postgres 12 to 16

namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-preprod/07-certificate.yaml
Add wproofreader to TLS certificate list for PreProd
This means it can use https, a secure form of data transfer.
=> Court Probation PreProd: Add wproofreader to TLS certificate list

namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-prod/07-certificate.yaml
Add wproofreader to TLS certificate list for Prod
This means it can use https, a secure form of data transfer.
=> Court Probation Prod: Add wproofreader to TLS certificate list

namespaces/live.cloud-platform.service.justice.gov.uk/parliamentary-questions-staging/resources/rds.tf
Renaming the db_repo in this PR (https://github.com/ministryofjustice/cloud-platform-environments/pull/24359/files) potentially caused the application to fail. Spoke to CP
=> PQ staging use dev repo name

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-dev/resources/rds.tf
* Disables `enable_rds_auto_start_stop` as stopping the database overnight is causing alerts and potential errors in the application when restarting. We may want to re-enable this in future but disabling for now will give us time to investigate properly.
* Disables `performance_insights_enabled` as we are not using this feature and disabling will save money.
=> Adjust CCR dev RDS settings

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-uat/resources/rds.tf
* Disables `enable_rds_auto_start_stop` as disabling the database overnight is causing alerts and potential errors in the application when restarting. We may want to re-enable this in future but disabling for now will give us time to investigate properly.
* Disables `performance_insights_enabled` as we are not using this feature and disabling will save money.
=> Adjust CCR UAT RDS settings

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-staging/resources/rds.tf
* Disables `enable_rds_auto_start_stop` as disabling the database overnight is causing alerts and potential errors in the application when restarting. We may want to re-enable this in future but disabling for now will give us time to investigate properly.
* Disables `performance_insights_enabled` as we are not using this feature and disabling will save money.
=> Adjust CCR staging RDS settings

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-production/resources/rds.tf
* Disables `enable_rds_auto_start_stop` as we do not want to stop the production database overnight.
* Disables `performance_insights_enabled` as we are not using this feature and disabling will save money.
=> Adjust CCR production RDS settings

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-a-video-link-dev/resources/domain-events-queue-bvls.tf
When a prisoner merge event occurs we need to know if this impacts any bookings in the 'book a video link service' and act accordingly.
=> BAVL-250 listen for prisoner merge events in BVLS so can alter video bookings accordingly

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-prison-person-api-preprod/resources/rds-postgresql.tf
Fix `Error: creating RDS DB Instance (cloud-platform-8dd69b293e33c4be): InvalidParameterCombination: The maximum allocated storage must be increased by at least 10 percent.`
https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/environments-live/jobs/apply-live-c/builds/2586#L6675879c:24599
=> chore: Bump RDS storage

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-prison-person-api-preprod/resources/rds-postgresql.tf
Fix `Error: creating RDS DB Instance (cloud-platform-8dd69b293e33c4be): InvalidParameterCombination: The maximum allocated storage must be increased by at least 10 percent.
status code: 400, request id: 0981f485-c3d1-4f1c-809f-791b89edb893`
https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/environments-live/jobs/apply-namespace-changes-live/builds/5740#L6675b81f:24
=> chore: Bump RDS max allocated storage

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-uat/resources/rds.tf
Fix `Error: updating RDS DB Instance (cloud-platform-d076dc502dcc456c): operation error RDS: ModifyDBInstance, https response error StatusCode: 400, RequestID: 41a39ae1-8cb6-43f2-a791-db2a09ea0415, api error InvalidParameterCombination: Cannot upgrade oracle-se2 from 19.0.0.0.ru-2024-01.rur-2024-01.r1 to 19.0.0.0.ru-2023-07.rur-2023-07.r1`
https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/environments-live/jobs/apply-live-d/builds/2624#L6675acf6:26280
RDS minor version was upgrade by AWS in maintenance window.
=> chore: Bump the rds version

namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-dev/02-limitrange.yaml
Dev environment is always crashing as limit range was never updated as the other environments have been.
=> Increase compute power to stop pod crash

namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-dev/resources/service-pod.tf
Add service pod to DEV in order to gain AWS CLI access to SQS queues.
=> court-case-service-dev: Add service pod

namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-preprod/resources/service-pod.tf
Add service pod to PreProd in order to gain AWS CLI access to SQS queues
=> court-case-service-preprod: Add service pod

namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-prod/resources/service-pod.tf
Add service pod to PreProd in order to gain AWS CLI access to SQS queues
=> court-case-service-prod: Add service pod 

namespaces/live.cloud-platform.service.justice.gov.uk/ct-prototype/resources/ecr.tf, namespaces/live.cloud-platform.service.justice.gov.uk/ct-prototype/resources/serviceaccount.tf
The repo has been deleted, so secrets can't be stored there.
NB: This is preparation for the deletion of this namespace
=> Handle non-existence of ct-prototype repo

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-litigator-fees-dev/resources/main.tf
The GithubTeam value in `default_tags` in `main.tf` is set to the team previously responsible for this application. This updates the value to match the team defined in `01-rbac.yaml` (`laa-lz-cp-migration`) so that all relevant developers can access the console for this application.
=> Update github team for CCLF dev console access

namespaces/live.cloud-platform.service.justice.gov.uk/laa-fala-staging/resources/serviceaccount.tf
FALA STG service account is responsible for deleting deployments and needs permission to delete the associated PVC thids PR adds that permission
=> FALA STG service account permissions

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-production/resources/rds.tf
minior version was upgraded in maintenance window. update the terraform file to match the databse version in the aws console
=> chore: Update tf DB engine version to match console version

namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-find-moj-data-dev/resources/route53.tf, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-find-moj-data-dev/resources/variables.tf
This will be used to delegate dev.find-moj-data.justice.service.gov.uk to cloud platform.
=> Create hosted zone for find-moj-data dev namespace

namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-find-moj-data-test/resources/route53.tf, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-find-moj-data-test/resources/variables.tf
This will be used to delegate test.find-moj-data.justice.service.gov.uk to cloud platform.
=> Create hosted zone for find-moj-data test namespace

namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-find-moj-data-preprod/resources/route53.tf, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-find-moj-data-preprod/resources/versions.tf
This will be used to delegate preprod.find-moj-data.justice.service.gov.uk to cloud platform.
=> Create hosted zone for find-moj-data preprod namespace

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-staging/resources/rds.tf
fix `Error: updating RDS DB Instance (cloud-platform-258fabb333470810): operation error RDS: ModifyDBInstance, https response error StatusCode: 400, RequestID: e02443b1-9870-48a3-b140-74a078e016f8, api error InvalidParameterCombination: Cannot upgrade oracle-se2 from 19.0.0.0.ru-2024-01.rur-2024-01.r1 to 19.0.0.0.ru-2023-07.rur-2023-07.r1`
https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/environments-live/jobs/apply-live-d/builds/2719
=> chore: Update tf db version to match console version

namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-prod/resources/rds.tf
We want to keep our booker-api database available 24hrs in production environment.
=> Remove enable_rds_auto_start_stop flag from production db

namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-preprod/resources/rds.tf
Remove enable_rds_auto_start_stop from preprod too similar to PR raised for Prod - https://github.com/ministryofjustice/cloud-platform-environments/pull/24672
=> Remove enable_rds_auto_start_stop from visit-booker-registry preprod

namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-find-moj-data-prod/resources/route53.tf, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-find-moj-data-prod/resources/variables.tf
This will be used to delegate find-moj-data.justice.service.gov.uk to cloud platform.
I'm following this guide https://user-guide.cloud-platform.service.justice.gov.uk/documentation/other-topics/route53-zone.html#add-dns-records-to-a-route53-zone-optional
=> Create hosted zone for find-moj-data prod namespace

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-pin-phone-monitor-qa/resources/rds-aurora.tf
Relates to ministryofjustice/cloud-platform#5893
=> chore: bump RDS Aurora module to 4.0.0 in nonprod

namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-find-a-github-repository-owner-dev/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-find-a-github-repository-owner-dev/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-find-a-github-repository-owner-dev/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-find-a-github-repository-owner-dev/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-find-a-github-repository-owner-dev/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-find-a-github-repository-owner-dev/resources/ecr.tf, namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-find-a-github-repository-owner-dev/resources/irsa.tf, namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-find-a-github-repository-owner-dev/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-find-a-github-repository-owner-dev/resources/rds.tf, namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-find-a-github-repository-owner-dev/resources/serviceaccount.tf, namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-find-a-github-repository-owner-dev/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-find-a-github-repository-owner-dev/resources/versions.tf
- In relation to https://github.com/ministryofjustice/operations-engineering/issues/4620
- To add a new namespace with a database to accommodate the new experimental service
-  Added `operations-engineering-find-a-github-repository-owner-dev` Namespace with an RDS database
- NA
=> ✨ Add `operations-engineering-find-a-github-repository-owner-dev` Namespace

namespaces/live.cloud-platform.service.justice.gov.uk/laa-civil-applications-datastore-uat/resources/ecr.tf
Add `deletion_protection = false` so files can be removed in next PR
=> Civil applications datastore: Prepare for removing namespace

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-production/resources/rds.tf
Fix error in apply pipeline
```
FATA[4433] error running terraform on namespace laa-crown-court-remuneration-production: unable to apply Terraform: exit status 1
Error: updating RDS DB Instance (cloud-platform-74a3ec4664d2ba63): operation error RDS: ModifyDBInstance, https response error StatusCode: 400, RequestID: 48cd53b2-36d8-4f62-98ed-43da0f242b5f, api error InvalidParameterCombination: Cannot upgrade oracle-se2 from 19.0.0.0.ru-2024-04.rur-2024-04.r1 to 19.0.0.0.ru-2024-01.rur-2024-01.r1
```
https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/environments-live/jobs/apply-live-d/builds/2795#L66768a50:24695
=> chore: Update db version in tf to match with console

namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-services-live-production/03-resourcequota.yaml
We saw this env hit limit over the weekend - we have ~60 live deployed forms which can burst up to 10 pods during heavy load.
Bumping to 700 to account for all or almost all of our pods under load + some headroom for further deployed services.
Coincides with an investigation into average utilization being high and possibly preventing pods from scaling back down, this will just give us some breathing room to improve that.
=> Bump up pod limit in live prod env

namespaces/live.cloud-platform.service.justice.gov.uk/rd-hr-smart-knowledge-management-dev/resources/cross-iam-role.tf, namespaces/live.cloud-platform.service.justice.gov.uk/rd-hr-smart-knowledge-management-dev/resources/irsa.tf
Note that the irsa config was already in place, so this just extends it to provide access to the Analytical Platform bucket.
=> Add cross-iam role for AP S3 bucket access

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-template-typescript/01-rbac.yaml
Minor change to request that when the hmpps-template-typescript namespace entry is used as a template, not to remove the two groups that are in the rbac file.
=> add comment to hmpps-template-typescript

namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-datahub-catalogue-prod/05-prometheusrule.yaml
Part of https://github.com/ministryofjustice/data-catalogue/issues/187
The rule for production is copy pasted from preprod, but with the URLs changed for RDS, OpenSearch and the grafana dashboard.
=> Add missing PrometheusRule for datahub prod

namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-find-moj-data-dev/06-certificate.yaml
- The secret needs to align with the app's ingress file according to [guidance](https://user-guide.cloud-platform.service.justice.gov.uk/documentation/other-topics/custom-domain-cert.html#certificate-character-limit)
=> Renamed dev cert secret to align with ingress

namespaces/live.cloud-platform.service.justice.gov.uk/intranet-staging/resources/opensearch.tf
2024/08/07 12:04:14 Running Terraform Apply for namespace: intranet-staging
FATA[1426] error running terraform on namespace intranet-staging: unable to apply Terraform: exit status 1
Error: updating OpenSearch Domain (arn:aws:es:eu-west-xxxxxx): ValidationException: Unrecognized advanced option 'max_clause_count' passed in advancedOptions.
https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/environments-live/jobs/apply-live-d/builds/2904
=> fix: 🐛 tf error

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-events-dev/resources/hmpps-eduation-and-work-plan.tf
`hmpps-education-and-work-plan` - subscribe to `prisoner-offender-search.prisoner.released` and `prisoner-offender-search.prisoner.received` events in dev
Our queues etc were already setup and subscribing to different events (from a previous iteration of our API). The previous events are no longer sent by anything and our kotlin code does not listen to them. But we do now need to listen to `prisoner-offender-search.prisoner.released` and `prisoner-offender-search.prisoner.received` events
=> RR-920 - Subscribe to prisoner-offender events in dev

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-events-preprod/resources/hmpps-education-and-work-plan-api.tf
`hmpps-education-and-work-plan` - subscribe to `prison-offender-events.prisoner.released` and `prison-offender-events.prisoner.received` events in dev
Our queues etc were already setup and subscribing to different events (from a previous iteration of our API). The previous events are no longer sent by anything and our kotlin code does not listen to them. But we do now need to listen to `prison-offender-events.prisoner.released` and `prison-offender-events.prisoner.received` events
=> RR-920 - Subscribe to prison-offender events in preprod

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-events-prod/resources/hmpps-education-and-work-plan-api.tf
`hmpps-education-and-work-plan` - subscribe to `prison-offender-events.prisoner.released` and `prison-offender-events.prisoner.received` events in prod
Our queues etc were already setup and subscribing to different events (from a previous iteration of our API). The previous events are no longer sent by anything and our kotlin code does not listen to them. But we do now need to listen to `prison-offender-events.prisoner.released` and `prison-offender-events.prisoner.received` events
=> Subscribe to prison-offender events in prod

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-litigator-fees-uat/resources/rds.tf
Fix apply pipeline error
```
FATA[4917] error running terraform on namespace laa-crown-court-litigator-fees-uat: unable to apply Terraform: exit status 1
Error: updating RDS DB Instance (cloud-platform-73d0dce4a90613e1): operation error RDS: ModifyDBInstance, https response error StatusCode: 400, RequestID: ee33cc85-8a3c-4309-9f27-80d4cce6aed4, api error InvalidParameterCombination: Cannot upgrade oracle-se2 from 19.0.0.0.ru-2024-04.rur-2024-04.r1 to 19.0.0.0.ru-2024-01.rur-2024-01.r1
```
https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/environments-live/jobs/apply-live-d/builds/2964#L66b9f992:23970
=> chore: Update rds version in tf code to match that in console

namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-datahub-catalogue-prod/resources/rds-postgresql.tf
We don't want our prod backend to shutdown overnight as we'll be running ingestions
=> do not turn of prod rds overnight

namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-kpi-dashboard-poc/resources/ecr.tf
The operations-engineering-kpi-dashboard-poc GitHub repository has had a name change and the OIDC has stopped working. This change corrects this error.
=> :recycle: Change repository name

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-prod/resources/rds.tf
We have had several incidents wherein we have maxed out our database CPU usage, which has then lead to maxing out our connections. This has lead to service incidents in two occasions, which affects the three different services that our API serves.
We believe the root of this cause is some particularly gnarly queries that are eagerly loading in more data than they need. Whilst we are tackling these queries, we would like to increase the instance of our DB considerably whilst we refactor them.
We will look to reduce the size of the instance once this has been done.
=> increase db instance for Community Accommodation Services databases

namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-find-moj-data-dev/resources/pingdom.tf
We've just removed the ingress for the old URLs as we have a service.justice.gov.uk domain now.
=> Find MoJ data (dev): Update URL for pingdom checks

namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-find-moj-data-test/resources/pingdom.tf
We've just removed the ingress for the old URLs as we have a service.justice.gov.uk domain now.
=> Find MoJ data (test): Update URL for pingdom checks

namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-find-moj-data-preprod/resources/pingdom.tf
We've just removed the ingress for the old URLs as we have a service.justice.gov.uk domain now.
=> Find MoJ data (preprod): Update URL for pingdom checks

namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-find-moj-data-prod/resources/pingdom.tf
We've just removed the ingress for the old URLs as we have a service.justice.gov.uk domain now.
=> Find MoJ data (prod): Update URL for pingdom checks

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-contribution-prod/05-prometheus-rules.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-contribution-prod/06-grafana.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-contribution-prod/resources/secret.tf
This PR sets-up alerting for the Crown Court Contribution (CCC) Service in prod to notify Slack for a number of pre-configured alert conditions. It also adds a new Grafana dashboard, as well as setting up the secret to use in AWS Secrets Manager for the Slack webhook URL.
[Link to Story](https://dsdmoj.atlassian.net/browse/LCAM-1436)
=> Add alerts for Crown Court Contribution Service

namespaces/live.cloud-platform.service.justice.gov.uk/intranet-production/resources/rds.tf
fix below error
```
FATA[1508] error running terraform on namespace intranet-production: unable to apply Terraform: exit status 1
Error: updating RDS DB Instance (cloud-platform-283c8dc3f78ede0f): operation error RDS: ModifyDBInstance, https response error StatusCode: 400, RequestID: 6389af51-cf85-4c97-a908-2e7b60ea7ca3, api error InvalidParameterCombination: Cannot upgrade mariadb from 10.11.8 to 10.11.6
with module.rds.aws_db_instance.rds,
on .terraform/modules/rds/main.tf line 144, in resource "aws_db_instance" "rds":
144: resource "aws_db_instance" "rds" {
```
https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/environments-live/jobs/apply-live-d/builds/3049#L66bcda55:7066
=> chore: Update tf rds version to match console version

namespaces/live.cloud-platform.service.justice.gov.uk/justice-gov-uk-production/resources/irsa.tf, namespaces/live.cloud-platform.service.justice.gov.uk/justice-gov-uk-production/resources/rds-tmp.tf
`rds-tmp.tf` is a copy of `rds.tf` except for naming and db_instance_class.
The intention is to use the service pod to restore a snapshot to rds_tmp, then connect to the db to export the database in .sql format.
cc @wilson1000 - I went against using the snapshot property as that required manual intervention from the Cloud Platform team - and this was looks like not too much additional work.
=> justice-gov-uk-production Temp. add a database to restore a snapshot, then export as .sql

namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-services-live-production/02-limitrange.yaml
Our services on these pods sits at around 50% utilisation, and services that feature file uploads sit higher. This means that during regular use they scale up the number of pods quickly and scale down slowly. 
This change will reserve more compute power by default, but should see us scale up deployments less often and use fewer pods and fewer resources overall.
=> Bump live prod pod size

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-education-and-work-plan-dev/01-rbac.yaml
Change the group name from `farsight-devs` to `hmpps-farsight-reduce-re-offend` for the Education & Work Plan `dev` namespace (because that is the GH group that maintains the associated projects)
=> Change group `farsight-devs` to `hmpps-farsight-reduce-re-offend` for the Education & Work Plan `dev` namespace

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-education-and-work-plan-preprod/01-rbac.yaml
Change the group name from `farsight-devs` to `hmpps-farsight-reduce-re-offend` for the Education & Work Plan `preprod` namespace (because that is the GH group that maintains the associated projects)
=> Change group `farsight-devs` to `hmpps-farsight-reduce-re-offend` for the Education & Work Plan `preprod` namespace

namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-test-dev/resources/user-filestore.tf
No changing the prefix/folder name as we have downstream code that expects it.
https://docs.aws.amazon.com/AmazonS3/latest/userguide/lifecycle-expire-general-considerations.html#lifecycle-expire-minimum-storage
based on this, I think there is no cost difference to hold for 30 days over 28 but could prevent an issue we are seeing where files are deleted at 00:00 on retention expiry but records that reference the files are deleted 28 days after creation. This will ensure files are always available and records that reference them will be deleted first.
=> Extend S3 file retention to 30 days

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-templates-dev/01-rbac.yaml
Since the hmpps-templates-dev namespace forms the basis of the namespaces for DPS apps, the support team (hmpps-sre) needs to be kept in the rbac file. This comment will (hopefully) make sure it is retained.
=> doc: comment to keep hmpps-sre

namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-preprod/resources/secrets-manager.tf
Add AWS secret key to contain app insights connection string
This will include the application insights preprod connection string. This is a part of the appinsights migration to major version 3
=> court-case-servcie-preprod : Add AWS secret key to contain app insights connection string

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-application-store-uat/resources/rds-postgresql.tf
App store UAT: revert DB upgrade changes
Previous PRs to upgrade the primary and read replica databases did
not work so reverting the changes to try and start again.
=> App store UAT: revert DB upgrade changes

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-application-store-uat/resources/rds-postgresql.tf
Documentation recommends not setting the minor version of the read replica
=> App store UAT bump primary DB 16.1 to 16.4

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-education-and-work-plan-prod/01-rbac.yaml
Change the group name from `farsight-devs` to `hmpps-farsight-reduce-re-offend` for the Education & Work Plan `prod` namespace (because that is the GH group that maintains the associated projects)
=> Change group `farsight-devs` to `hmpps-farsight-reduce-re-offend` for the Education & Work Plan `prod` namespace

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-means-assessment-test/resources/rds.tf
bump rds versino to fix below error in apply pipeline
```
FATA[3547] error running terraform on namespace laa-crime-means-assessment-test: unable to apply Terraform: exit status 1
Error: updating RDS DB Instance (cloud-platform-600c6af711fc9b17): operation error RDS: ModifyDBInstance, https response error StatusCode: 400, RequestID: 70f3edd6-ebfe-40b2-9cee-2fae05d4f6f8, api error InvalidParameterCombination: Cannot find upgrade path from 14.12 to 14.7.
with module.rds.aws_db_instance.rds,
on .terraform/modules/rds/main.tf line 144, in resource "aws_db_instance" "rds":
144: resource "aws_db_instance" "rds" {
```
https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/environments-live/jobs/apply-live-d/builds/3133#L66bd40fa:24081
=> chore: Update TF RDS version to match AWS

namespaces/live.cloud-platform.service.justice.gov.uk/monitoring/dashboard-nginx-overview.yaml
simplify overview to include panels for (because the thanos queries are so large we need to remove even more panels):
- ~~% success traffic (excluding 404s)~~
- total requests
- breakdown by http codes
- ~~total traffic~~
Tickets to address handling of large thanos queries:
- [scale query component](https://github.com/ministryofjustice/cloud-platform/issues/6085)
- [scale store component](https://github.com/ministryofjustice/cloud-platform/issues/6086)
- [move thanos components to monitoring node group and increase nodes in group](https://github.com/ministryofjustice/cloud-platform/issues/6087)
closes [#5713](https://github.com/ministryofjustice/cloud-platform/issues/5713)
=> ci: 🎡 add a dashboard for cluster traffic overview

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-dev/resources/api_gateway-assume-role-endpoint.tf
Allows clients to use their existing mutual TLS certificate and API key to get a temporary IAM session for accessing their dedicated SQS queue.
=> PI-2447 Add endpoint for temporary SQS credentials
