namespaces/live.cloud-platform.service.justice.gov.uk/laa-cla-backend-production/resources/s3.tf
Removed long-lived credentials from the laa-cla-backend-production's S3 Bucket Terraform file
=> Removed user policy from laa-cla-backend-production S3 Bucket

namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-report-service-dev/resources/main.tf
Adding githubTeam to tags on main.tf
=> DCES-AWS-GithubTeam-Dev

namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-test-dev/resources/service-metadata-bucket.tf
Export bucket arn in a secret to the formbuilder-services-test-dev namespace to generate an IRSA with access
=> Export bucket arn in a secret to formbuilder-services-test-dev

namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-report-service-dev/03-resourcequota.yaml
Increasing pod quota for testing purposes.
=> DCES-Increase-Pod-Quota-Dev

namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-report-service-prod/03-resourcequota.yaml
Increase hard-cap to avoid helm collisions.
=> DCES-Increase-Pod-Hardcap-Prod

namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-report-service-staging/03-resourcequota.yaml
Increase hard-cap to avoid helm collisions.
=> DCES-Increase-Pod-Hardcap-Staging

namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-report-service-uat/03-resourcequota.yaml
Increase hard-cap to avoid helm collisions.
=> DCES-Increase-Pod-Hardcap-UAT

namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-services-test-dev/resources/runner.tf, namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-services-test-dev/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-services-test-dev/resources/versions.tf
Add IRSA module and variable for runner to pick up service metadata S3 bucket policy arn
=> Add IRSA module services-test-dev

namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-production/resources/outputs.tf
Missing outputs to retrieve nameservers.
=> Adding missing outputs.

namespaces/live.cloud-platform.service.justice.gov.uk/cwaapi-poc/resources/ecr.tf
Added ecr.tf generated by CP cli to Add a container repository to namespace
=> Added file generated by cli for ecr repository

namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-production/05-certificates.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-production/06-shutdown-service.yaml
* New service to offer up a new static webpage to tell people their apps have shut down
* A certificate request for the testing domain.
=> Data Platform Migration: Adding testing certificate and a new service to serve a shutdown message.

namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-production/05-certificates.yaml
Requesting a new certificate for the `apps.alpha` domain.
=> Creating a new certificate for apps.alpha domain.

namespaces/live.cloud-platform.service.justice.gov.uk/laa-claim-non-standard-magistrate-fee-dev/resources/circleci-serviceaccount.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-claim-non-standard-magistrate-fee-dev/resources/ecr.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-claim-non-standard-magistrate-fee-dev/resources/variables.tf
- Add service account and variables for CircleCI
- Update ECR to use OIDC for circleci
=> Allow access to deploy from CircleCI

namespaces/live.cloud-platform.service.justice.gov.uk/laa-claim-non-standard-magistrate-fee-prod/resources/circleci-serviceaccount.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-claim-non-standard-magistrate-fee-prod/resources/variables.tf
Adds service account and variable for rules.
=> Add prod circleci service account

namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-live-production/resources/service-metadata-bucket.tf, namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-live-production/resources/shared-secrets.tf, namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-live-production/resources/user-filestore.tf, namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-live-production/resources/variables.tf
In formbuilder-platform-live-dev
- IRSA account for user-filestore with access to buckets
- Cross namespace secrets to share bucket access with runner
-  Shared secret for live editor service account
=> Add live-production S3 IRSA resources

namespaces/live.cloud-platform.service.justice.gov.uk/laa-claim-non-standard-magistrate-fee-dev/resources/circleci-serviceaccount.tf
Add role name to service account
=> Add role name to service account

namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-services-live-production/resources/runner.tf, namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-services-live-production/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-services-live-production/resources/versions.tf
Add resources for formbuilder-services-live-production for irsa access to S3
=> Add resources for formbuilder-services-live-production

namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-prod/resources/ppo-route53.tf
Concorse keeps returning records are already there even though they have been changed. I want to remove this one and then add it back in a separate PR.
=> Remove DNS records completely to allow new configuration

namespaces/live.cloud-platform.service.justice.gov.uk/offender-management-staging/resources/domain-events-subscription.tf
=> offender-management-staging: rename SQS queue names

namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-test-dev/resources/json-output-attachments-s3.tf, namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-test-dev/resources/service-metadata-bucket.tf, namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-test-dev/resources/user-filestore.tf
Remove user policies and exported long lived access key id and secret keys from formbuilder platform test dev S3 buckets
=> Cleanup S3 keys formbuilder-platform-test-dev

namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-dev/resources/irsa.tf
VB-2693 Integrate backend with GOV.UK Notify. Irsa changes
=> VB-2693 Integrate backend with GOV.UK Notify. irsa changes

namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-services-live-dev/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-services-live-dev/resources/versions.tf
There is no terraform backend and hence the pipeline tries to re-create the resources and fails. This PR fixes by adding the backend terraform state
=> Add missing main.tf

namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-staging/resources/irsa.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-staging/resources/variables.tf
We want to be able to run aws cli command on s3 objects between application namepaces and with select external legacy aws accounts
=> Add access to share s3 objects between namespaces

namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-prod/resources/brookhouse-route53.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-prod/resources/publicdefenderservice-route53.tf
* Changing the syntax of this record. Concourse did not like the slashes added. 
* Added new Brookhouse domainkey DNS record
=> Fix syntax on dns record

namespaces/live.cloud-platform.service.justice.gov.uk/offender-management-preprod/resources/domain-events-subscription.tf
=> offender-management-preprod: Add subscription to domain events

namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-prod/resources/irsa.tf
Create new IAM policy too allow for cross s3 bucket transfers out of prod to other namespaces.
=> Hale update IRSA policy s3 access

namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-staging/resources/irsa.tf
Update policy to allow transferring s3 bucket objects between other namespace buckets.
=> Add updated IAM policy for s3 cross bucket access

namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-staging/resources/irsa.tf
IAM generated policies need to have a unique name so I've prefixed with the namespace name.
=> Give policy a unique name with namespace prefix

namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-prod/resources/irsa.tf
This has to be a unique name so I've prefixed it with our namespace.
=> Give s3 bucket policy unique name on prod

namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-dev/resources/irsa.tf
Add a policy to allow s3 object migrations between environment buckets.
=> Add updated s3 bucket policy to dev

namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-demo/resources/irsa.tf
Add a policy to allow s3 object migrations between environment buckets.
=> Update s3 policy on demo namespace

namespaces/live.cloud-platform.service.justice.gov.uk/cfe-civil-uat/resources/ecr.tf
Just a comment update, but explains what the field actually does
=> Updated meaning of "github_repositories" field

namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-preprod/resources/data.tf, namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-preprod/resources/hmpps-prison-visits-event.tf, namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-preprod/resources/hmpps-prison-visits-notification-alerts.tf, namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-preprod/resources/irsa.tf
Added config for preprod env for VSiP, moving config into namespace
=> VB-1536 Proactively manage bookings, Added config for preprod en

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-dev/resources/ecr.tf
Also remove default tags from this module as it leads to duplicated tags.
=> Bump Cloud Platform ECR credentials module

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-preprod/resources/ecr.tf
Also remove default tags from this module as it leads to duplicated tags.
=> Bump Cloud Platform ECR credentials module pre-production

namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-ui-dev/resources/elasticache.tf
Update instance to cache.t4g.micro prior to upgrading to engine 7
=> CTSKF-579 - Update to t4g

namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-ui-dev/resources/elasticache.tf
=> CTKSF-579 - Update to version 7

namespaces/live.cloud-platform.service.justice.gov.uk/cccd-dev/resources/rds.tf, namespaces/live.cloud-platform.service.justice.gov.uk/cccd-dev/resources/read_replica.tf
Add a read replica to CCCD Dev environment to be then used by the MI team.
=> Add read replica to CCCD Dev environment

namespaces/live.cloud-platform.service.justice.gov.uk/send-legal-mail-to-prisons-dev/APPLY_PIPELINE_SKIP_THIS_NAMESPACE
Add apply pipeline skip namespace file before upgrading database inst…ance for send-legal-mail-to-prisons-dev namespace.
=> Add apply pipeline skip namespace file - send-legal-mail-to-prisons-dev DB instance upgrade.

namespaces/live.cloud-platform.service.justice.gov.uk/send-legal-mail-to-prisons-dev/resources/rds.tf
Upgrade db_instance_class to db.t4g.micro and set db_max_allocated_storage to 500. Also set allow_major_version_upgrade to false.
=> Upgrade db_instance for send-legal-mail-to-prisons-dev

namespaces/live.cloud-platform.service.justice.gov.uk/laa-govuk-notifiy-orchestrator-dev/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-govuk-notifiy-orchestrator-dev/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-govuk-notifiy-orchestrator-dev/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-govuk-notifiy-orchestrator-dev/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-govuk-notifiy-orchestrator-dev/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-govuk-notifiy-orchestrator-dev/resources/ecr.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-govuk-notifiy-orchestrator-dev/resources/irsa.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-govuk-notifiy-orchestrator-dev/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-govuk-notifiy-orchestrator-dev/resources/sqs.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-govuk-notifiy-orchestrator-dev/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-govuk-notifiy-orchestrator-dev/resources/versions.tf
Creates the laa-govuk-notify-orchestrator-dev namespace with ECR, FIFO SQS & Dead letter SQS resources.
=> Create namespace laa-govuk-notify-orchestrator-dev

namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-ui-uat/resources/elasticache.tf
Update cache node type prior to DB update
=> Update cache node to t4g CDUI UAT

namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-ui-dev/resources/rds.tf
Update node type before DB Update
=> Update node type for DB to t4g CDUI Dev

namespaces/live.cloud-platform.service.justice.gov.uk/offender-management-staging/prometheus-custom-alerts-moic-staging.yaml
=> offender-management-staging: Alert if domain events DLQ has any messages in it

namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-ui-staging/resources/elasticache.tf
Update cache node type prior to DB update
=> Update node type to t4g CDUI Stg

namespaces/live.cloud-platform.service.justice.gov.uk/send-legal-mail-to-prisons-preprod/resources/rds.tf
Upgrade db_instance_class to db.t4g.micro and set db_max_allocated_storage to 500. Also set allow_major_version_upgrade to false.
=> Upgrade db instance send-legal-mail-to-prisons-preprod

namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-ui-uat/resources/elasticache.tf
=> Update cache version to 7 CDUI UAT

namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-ui-staging/resources/elasticache.tf
Updates the Redis version to the latest available
=> Update cache version to 7 CDUI Stg

namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-ui-production/resources/elasticache.tf
Update cache node type prior to DB update
=> Update node type to t4g CDUI Prod

namespaces/live.cloud-platform.service.justice.gov.uk/offender-management-preprod/prometheus-custom-alerts-moic-preprod.yaml
=> offender-management-preprod: Alert if domain events DLQ has any messages

namespaces/live.cloud-platform.service.justice.gov.uk/offender-management-production/prometheus-custom-alerts-moic-production.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/offender-management-production/resources/domain-events-subscription.tf
=> offender-management-production: Add subscription to domain events

namespaces/live.cloud-platform.service.justice.gov.uk/offender-management-production/resources/irsa.tf
=> offender-management-production: IRSA policy added for SQS queues

namespaces/live.cloud-platform.service.justice.gov.uk/laa-govuk-notifiy-orchestrator-staging/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-govuk-notifiy-orchestrator-staging/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-govuk-notifiy-orchestrator-staging/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-govuk-notifiy-orchestrator-staging/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-govuk-notifiy-orchestrator-staging/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-govuk-notifiy-orchestrator-staging/resources/irsa.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-govuk-notifiy-orchestrator-staging/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-govuk-notifiy-orchestrator-staging/resources/sqs.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-govuk-notifiy-orchestrator-staging/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-govuk-notifiy-orchestrator-staging/resources/versions.tf
Creates the laa-govuk-notify-orchestrator-staging namespace with ECR, FIFO SQS & Dead letter SQS resources.
=> Created namespace laa-govuk-notify-orchestrator-staging

namespaces/live.cloud-platform.service.justice.gov.uk/laa-govuk-notifiy-orchestrator-production/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-govuk-notifiy-orchestrator-production/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-govuk-notifiy-orchestrator-production/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-govuk-notifiy-orchestrator-production/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-govuk-notifiy-orchestrator-production/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-govuk-notifiy-orchestrator-production/resources/irsa.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-govuk-notifiy-orchestrator-production/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-govuk-notifiy-orchestrator-production/resources/sqs.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-govuk-notifiy-orchestrator-production/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-govuk-notifiy-orchestrator-production/resources/versions.tf
Creates the laa-govuk-notify-orchestrator-production namespace with ECR, FIFO SQS & Dead letter SQS resources.
=> Created namespace laa-govuk-notify-orchestration-production

namespaces/live.cloud-platform.service.justice.gov.uk/offender-management-preprod/resources/irsa.tf
=> offender-management-preprod: IRSA policy added for SQS queues

namespaces/live.cloud-platform.service.justice.gov.uk/artefact-library/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/artefact-library/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/artefact-library/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/artefact-library/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/artefact-library/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/artefact-library/resources/basic-auth.tf, namespaces/live.cloud-platform.service.justice.gov.uk/artefact-library/resources/ecr.tf, namespaces/live.cloud-platform.service.justice.gov.uk/artefact-library/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/artefact-library/resources/serviceaccount.tf, namespaces/live.cloud-platform.service.justice.gov.uk/artefact-library/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/artefact-library/resources/versions.tf
Carrying out this pull request as part of the process to publish a prototype to the web.
=> Added artefact-library prototype

namespaces/live.cloud-platform.service.justice.gov.uk/laa-govuk-notify-orchestrator-dev/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-govuk-notify-orchestrator-dev/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-govuk-notify-orchestrator-dev/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-govuk-notify-orchestrator-dev/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-govuk-notify-orchestrator-dev/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-govuk-notify-orchestrator-dev/resources/ecr.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-govuk-notify-orchestrator-dev/resources/irsa.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-govuk-notify-orchestrator-dev/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-govuk-notify-orchestrator-dev/resources/sqs.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-govuk-notify-orchestrator-dev/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-govuk-notify-orchestrator-dev/resources/versions.tf
Creates namespace, laa-govuk-notify-orchestrator-dev with the following resources: 
- ECR, 
- FIFO SQS, 
- FIFO Dead Letter Queue
=> Created namespace laa-govuk-notify-orchestrator-dev

namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-report-service-prod/prometheus-custom-rules-laa-dces-report-service.yaml
Setting severity to custom severity from webhook.
=> DCES-120 - Set Prod Alert custom severity

namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-saas-test/resources/variables.tf
been asked to update instance type from t3 to t4g. Remaining as large instance, can drop if required
=> updated instance type to t4g

namespaces/live.cloud-platform.service.justice.gov.uk/laa-govuk-notify-orchestrator-production/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-govuk-notify-orchestrator-production/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-govuk-notify-orchestrator-production/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-govuk-notify-orchestrator-production/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-govuk-notify-orchestrator-production/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-govuk-notify-orchestrator-production/resources/irsa.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-govuk-notify-orchestrator-production/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-govuk-notify-orchestrator-production/resources/sqs.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-govuk-notify-orchestrator-production/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-govuk-notify-orchestrator-production/resources/versions.tf
Created namespace laa-govuk-notify-orchestrator-production with resources:
- SQS FIFO Queue
- SQS FIFO Dead Letter Queue
=> Created namespace laa-govuk-notify-orchestrator-production

namespaces/live.cloud-platform.service.justice.gov.uk/send-legal-mail-to-prisons-prod/resources/rds.tf
Upgrade db_instance_class to db.t4g.small and set db_max_allocated_storage to 10000. Also set allow_major_version_upgrade to false.
=> Upgrade DB instance - send-legal-mail-to-prisons-prod

namespaces/live.cloud-platform.service.justice.gov.uk/laa-cwa-test/resources/serviceaccount.tf
Amed service account rules to add pods/log
=> laa-cwa-test amend service account rules to include pods/log

namespaces/live.cloud-platform.service.justice.gov.uk/send-legal-mail-to-prisons-dev/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/send-legal-mail-to-prisons-dev/resources/elasticache-staff-ui.tf
Add new project - hmpps-send-legal-mail-staff-ui to existing send-leg…al-mail-to-prisons-dev namespace
=> Add new project - hmpps-send-legal-mail-staff-ui to existing namespace

namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-ap-rshiny-notesbook-dev/resources/serviceaccount.tf
sorry one more typo to be fixed
=> Fix the typo in repo for ap-rshiny-notesbook(again)

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-events-dev/resources/outputs-to-ssm-parameters.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-events-dev/resources/prisoner-offender-search.tf
Reverts ministryofjustice/cloud-platform-environments#16872
=> Revert "SDIT-1114: 🔥 Remove prisoner offender search for hmpps-domain-events-dev"

namespaces/live.cloud-platform.service.justice.gov.uk/offender-events-dev/11-prometheus-sqs-sns.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/offender-events-dev/resources/outputs-to-ssm-parameters.tf, namespaces/live.cloud-platform.service.justice.gov.uk/offender-events-dev/resources/prisoner-offender-search-sub-queue.tf
Reverts ministryofjustice/cloud-platform-environments#16873
=> Revert "SDIT-1114: 🔥 Remove prisoner offender search for offender-events-dev"

namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-prod/resources/icrir-acm.tf
Related to: https://github.com/ministryofjustice/cloud-platform/issues/4827
=> Add ACM to icrir ad DNS delegation is outside CP

.checksum
Reverts ministryofjustice/cloud-platform-environments#16928
=> Revert "revert checksum to fix generate namespace issue"

namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-dev/resources/pushgateway.tf
- Bump pushgateway to v1.4.0
- latest security patches applied tp prom/pushgateway image
=> CICA claim-criminal-injuries-compensation-dev Bump pushgateway to v1.4.0

namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-dev/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-dev/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-dev/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-dev/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-dev/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-dev/05-serviceaccount-circleci.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-dev/06-service-monitor.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-dev/resources/ecr.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-dev/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-dev/resources/pingdom.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-dev/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-dev/resources/versions.tf
=> Initial commit of DCES-DRC-Integration-Dev namespace

namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-uat/resources/pushgateway.tf
- bump pushgateway to v1.4.0
- applies security fixes
=> CICA claim-criminal-injuries-compensation-uat Bump pushgateway to v1.4.0

namespaces/live.cloud-platform.service.justice.gov.uk/laa-check-client-qualifies-staging/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-check-client-qualifies-staging/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-check-client-qualifies-staging/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-check-client-qualifies-staging/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-check-client-qualifies-staging/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-check-client-qualifies-staging/05-prometheus-custom-rules.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-check-client-qualifies-staging/certificate.yml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-check-client-qualifies-staging/resources/elasticache.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-check-client-qualifies-staging/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-check-client-qualifies-staging/resources/pingdom.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-check-client-qualifies-staging/resources/rds.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-check-client-qualifies-staging/resources/serviceaccount.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-check-client-qualifies-staging/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-check-client-qualifies-staging/resources/versions.tf
We are renaming our github repo this will be the new staging namespace for CCQ
=> create new namesapce for CCQ staging

namespaces/live.cloud-platform.service.justice.gov.uk/cloud-platform-go-get-module-prod/resources/serviceaccount.tf
This reverts commit 4fa323563d0968f92755636d9b53af9cd87af188.
=> Revert "Revert "test: 💍 sa module (#17007)" (#17009)"

namespaces/live.cloud-platform.service.justice.gov.uk/send-legal-mail-to-prisons-preprod/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/send-legal-mail-to-prisons-preprod/resources/elasticache-staff-ui.tf
Add new project - hmpps-send-legal-mail-staff-ui to existing namespace - hmpps-send-legal-mail-to-prisons-preprod namespace.
Dev PR for reference - https://github.com/ministryofjustice/cloud-platform-environments/pull/16817
=> Add new project - hmpps-send-legal-mail-staff-ui to existing namespace - preprod

namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-dev/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-dev/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-dev/resources/serviceaccount.tf
Fixing a namespace issue.
Creating serviceaccount.tf as per advice.
=> DCES-142 Dev Setup

namespaces/live.cloud-platform.service.justice.gov.uk/laa-assess-non-standard-magistrate-fee-dev/resources/irsa.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-assess-non-standard-magistrate-fee-dev/resources/variables.tf
- Adds irsa to the assess nsm namepaces
- Pulls secret shared from claim to get arn
- Add missing variables
=> Add irsa to Assess nsm namespace

namespaces/live.cloud-platform.service.justice.gov.uk/laa-claim-non-standard-magistrate-fee-dev/resources/shared-s3-secret.tf
- Adds bucket arn and name for other namespace to access
=> Update shared secret for claim nsm

namespaces/live.cloud-platform.service.justice.gov.uk/laa-check-client-qualifies-uat/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-check-client-qualifies-uat/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-check-client-qualifies-uat/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-check-client-qualifies-uat/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-check-client-qualifies-uat/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-check-client-qualifies-uat/05-prometheus-custom-rules.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-check-client-qualifies-uat/resources/elasticache.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-check-client-qualifies-uat/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-check-client-qualifies-uat/resources/pingdom.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-check-client-qualifies-uat/resources/s3.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-check-client-qualifies-uat/resources/serviceaccount.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-check-client-qualifies-uat/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-check-client-qualifies-uat/resources/versions.tf
We are renaming our Github repo and this will be the new UAT namespace for CCQ
=> Create new namespace for CCQ UAT

namespaces/live.cloud-platform.service.justice.gov.uk/laa-assess-non-standard-magistrate-fee-uat/resources/variables.tf
The RDS config is already in main, need to update application name so that it works 
https://mojdt.slack.com/archives/C57UPMZLY/p1697535694378229
=> Update application name for RDS creation

namespaces/live.cloud-platform.service.justice.gov.uk/laa-govuk-notify-orchestrator-production/resources/ecr.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-govuk-notify-orchestrator-production/resources/serviceaccount-circleci.tf
- Adds an ECR to `laa-govuk-notify-production`.
- Adds a CircleCI service account to the namespace.
=> Add ECR to laa-govuk-notify-orchestrator-production

namespaces/live.cloud-platform.service.justice.gov.uk/laa-govuk-notify-orchestrator-staging/resources/serviceaccount-circleci.tf
Adds a CircleCI service account to `laa-govuk-notify-orchestrator-staging`
=> Add CircleCI service account to laa-govuk-notify-orchestrator-staging

namespaces/live.cloud-platform.service.justice.gov.uk/laa-govuk-notify-orchestrator-production/resources/irsa.tf
Creates a service pod in the `laa-govuk-notify-orchestrator-production` namespace.
=> Create service pod in laa-govuk-notify-orchestrator-production

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-events-dev/resources/hmpps-education-and-work-plan-api.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-events-dev/resources/variables.tf
Setup domain events for CIAG induction
Will emit event to existing queue:  education_and_work_plan_domain_events_queue
=> ESWE-724 - Domain Events

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-events-prod/resources/hmpps-education-and-work-plan-api.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-events-prod/resources/variables.tf
Setup domain events for CIAG induction
Will emit event to existing queue: education_and_work_plan_domain_events_queue
=> ESWE-724 - Domain events - Prod

namespaces/live.cloud-platform.service.justice.gov.uk/send-legal-mail-to-prisons-prod/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/send-legal-mail-to-prisons-prod/05-serviceaccount-circleci.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/send-legal-mail-to-prisons-prod/resources/elasticache-staff-ui.tf
Add new project - hmpps-send-legal-mail-staff-ui to existing send-legal-mail-to-prisons-prod namespace
Includes new redis instance, namespace and circleci service account update.
=> Add new project - hmpps-send-legal-mail-staff-ui to existing send-legal-mail-to-prisons-prod namespace

namespaces/live.cloud-platform.service.justice.gov.uk/laa-check-client-qualifies-staging/00-namespace.yaml
Update repo reference to stop breaking the pipeline
=> CCQ STG update repo reference

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-education-employment-preprod/resources/irsa.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-education-employment-preprod/resources/variables.tf
=> ESWE-724 - IRSA Preprod

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-education-employment-prod/resources/irsa.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-education-employment-prod/resources/variables.tf
=> ESWE-724 - IRSA Prod

namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-uat/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-uat/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-uat/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-uat/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-uat/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-uat/06-service-monitor.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-uat/resources/ecr.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-uat/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-uat/resources/pingdom.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-uat/resources/serviceaccount.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-uat/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-uat/resources/versions.tf
Adding drc-integration uat environment
=> DCES: drc integration uat environment

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-launchpad-auth-dev/resources/rds-postgresql.tf
update db instance class type to small, remove read replica, enable performance insight and auto start stop
=> update db instance class type to small, remove read replica

namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-prod/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-prod/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-prod/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-prod/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-prod/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-prod/06-service-monitor.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-prod/resources/ecr.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-prod/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-prod/resources/pingdom.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-prod/resources/serviceaccount.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-prod/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-prod/resources/versions.tf
Adding prod environment config for laa-dces-drc-integration
=> DCES: drc integration prod environment

namespaces/live.cloud-platform.service.justice.gov.uk/laa-cla-frontend-staging/resources/route53.tf
Creates a DNS Record in cla_frontend for the MyNCSC web check.
=> Created Route53 DNS record for laa-cla-frontend

namespaces/live.cloud-platform.service.justice.gov.uk/abundant-namespace-dev/resources/opensearch.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-intelligence-preprod/resources/opensearch.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-intelligence-test/resources/opensearch.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-prisoner-search-dev/resources/opensearch.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-prisoner-search-preprod/resources/opensearch.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-prisoner-search-prod/resources/opensearch.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-probation-search-dev/resources/opensearch.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-probation-search-preprod/resources/opensearch.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-probation-search-prod/resources/opensearch.tf, namespaces/live.cloud-platform.service.justice.gov.uk/jacksapp-dev/resources/opensearch.tf, namespaces/live.cloud-platform.service.justice.gov.uk/manage-intelligence-dev/resources/opensearch.tf, namespaces/live.cloud-platform.service.justice.gov.uk/peoplefinder-development/resources/opensearch.tf, namespaces/live.cloud-platform.service.justice.gov.uk/peoplefinder-production/resources/opensearch.tf, namespaces/live.cloud-platform.service.justice.gov.uk/peoplefinder-staging/resources/opensearch.tf, namespaces/live.cloud-platform.service.justice.gov.uk/prisoner-content-hub-development/resources/opensearch.tf, namespaces/live.cloud-platform.service.justice.gov.uk/prisoner-content-hub-production/resources/opensearch.tf, namespaces/live.cloud-platform.service.justice.gov.uk/prisoner-content-hub-staging/resources/opensearch.tf
https://github.com/ministryofjustice/cloud-platform-terraform-opensearch/releases/tag/1.4.0
=> chore: 🤖 bump opensearch to fix syntax

namespaces/live.cloud-platform.service.justice.gov.uk/prisoner-offender-search-preprod/resources/es.tf, namespaces/live.cloud-platform.service.justice.gov.uk/prisoner-offender-search-prod/resources/es.tf
https://github.com/ministryofjustice/cloud-platform-terraform-elasticsearch/releases/tag/4.4.0
=> chore: 🤖 bump elastic search to fix syntax

namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-staging/resources/s3.tf
Blocks access to bucket except for specific access to objects/directories.
=> Add new bucket policy

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-prisoner-search-dev/resources/opensearch.tf
Reverts ministryofjustice/cloud-platform-environments#17155
=> Revert "SDIT-723: ✨ Turn on auto tuning for hmpps-prisoner-search-dev"

namespaces/live-2.cloud-platform.service.justice.gov.uk/cloud-platform-canary-app-eks/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/cloud-platform-canary-app-eks/00-namespace.yaml
Related to: [#4872](https://github.com/ministryofjustice/cloud-platform/issues/4872)
=> Update psa label from audit to enforce on cloud-platform-canary-app-eks

namespaces/live-2.cloud-platform.service.justice.gov.uk/cloud-platform-canary-app-eks/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/cloud-platform-canary-app-eks/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-ppud-automation-dev/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-ppud-automation-preprod/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-ppud-automation-prod/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-assess-non-standard-magistrate-fee-prod/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-staging/00-namespace.yaml, policy/namespace.rego
- Update conftest message to enforce
- Update hmpps, laa namespaces label psa audit to enforce
=> revert PSA label from enforce to audit on missed namespaces, update conftest message

namespaces/live.cloud-platform.service.justice.gov.uk/justice-archiver-dev/resources/cloudfront.tf
Creates a secret to be consumed in local application
=> Get the CloudFront distribution domain name

namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-production/resources/secrets.tf, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-production/resources/variables.tf
=> 🤫 Add secrets for create-a-derived-table self-hosted runner

namespaces/live.cloud-platform.service.justice.gov.uk/laa-information-exchange-development/05-promethiusrules.yaml
Added additional prometheus alerts. These will be tested in due course.
=> infox/LAWS-3513 - Adds Prometheus Alerts for Infox Dev.

namespaces/live.cloud-platform.service.justice.gov.uk/laa-information-exchange-development/05-promethiusrules.yaml
Also increased the threshold of the memory usage alert as base memoey usage currently is 87%.
=> Removed namespace up check as this was throwing a false negative.

namespaces/live.cloud-platform.service.justice.gov.uk/laa-govuk-notify-orchestrator-staging/00-namespace.yaml
[LGA-2767](https://dsdmoj.atlassian.net/browse/LGA-2767)
[LGA-2767]: https://dsdmoj.atlassian.net/browse/LGA-2767?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LGA-2767 adding namespace laa-govuk-notify-orchestrator-staging

namespaces/live.cloud-platform.service.justice.gov.uk/laa-govuk-notify-orchestrator-production/00-namespace.yaml
[LGA-2767](https://dsdmoj.atlassian.net/browse/LGA-2767)
[LGA-2767]: https://dsdmoj.atlassian.net/browse/LGA-2767?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LGA-2767 adding namespace laa-govuk-notify-orchestrator-production

namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-prod/resources/lawcom-route53.tf
Remove the A record so a new one is generated and points to new stack
=> Remove A record to generate new one

namespaces/live.cloud-platform.service.justice.gov.uk/laa-govuk-notify-orchestrator-dev/04-networkpolicy.yaml
- Adds ingress Network Policy from `laa-cla-backend-uat`
=> Added ingress network policy to laa-govuk-notify-orchestrator-dev

namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-development/resources/github-actions-serviceaccount.tf
This pull request removes the service account secret injection, something I tried to do in #17338
=> 🔥 Remove secret inject from data-platform-development's GitHub Actions service account

namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-production/resources/github-actions-serviceaccount.tf
We need to create service accounts within our namepsace for IRSA back to Analytical Platform
=> 🛂 Update Data Platform Production's SA rules

namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-prod/resources/justicejobs-route53.tf
Remove A record so a new record is generated pointing to the new stack.
=> Remove JusticeJobs A Record

.checksum, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-application-store-uat/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-application-store-uat/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-application-store-uat/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-application-store-uat/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-application-store-uat/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-application-store-uat/resources/irsa.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-application-store-uat/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-application-store-uat/resources/rds-postgresql.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-application-store-uat/resources/serviceaccount.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-application-store-uat/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-application-store-uat/resources/versions.tf
- Add new namespace
- Add RDS
- Include Service account for CircleCI
- Add IRSA
=> Add UAT env for laa-crime-application-store

.checksum, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-application-store-production/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-application-store-production/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-application-store-production/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-application-store-production/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-application-store-production/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-application-store-production/resources/irsa.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-application-store-production/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-application-store-production/resources/rds-postgresql.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-application-store-production/resources/serviceaccount.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-application-store-production/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-application-store-production/resources/versions.tf
- Add new namespace
- Add RDS
- Include Service account for CircleCI
- Add IRSA
=> Add production env for laa-crime-application-store

namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-staging/resources/elasticache.tf
Bump redis from version 6 to 7 on laa apply staging
=> bump redis from 6 to 7

namespaces/live.cloud-platform.service.justice.gov.uk/laa-govuk-notify-orchestrator-dev/resources/sqs.tf
Adds visibility_timout_seconds queue attribute to laa-govuk-notify-orchestrator-dev
=> Add visibility_timout_seconds queue attribute to laa-govuk-notify-orchestrator-dev

namespaces/live.cloud-platform.service.justice.gov.uk/laa-information-exchange-development/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-information-exchange-development/05-promethiusrules.yaml
As per title. The previous values resulted in "too-hot" alerts.
=> Amends prometheus rules for infox along with new limit ranges.

namespaces/live.cloud-platform.service.justice.gov.uk/laa-govuk-notify-orchestrator-staging/resources/irsa.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-govuk-notify-orchestrator-staging/resources/sqs.tf
- Adds visibility_timeout_seconds SQS Parameter
- Adds service pod
=> Add visibility timeout seconds queue attribute to laa-govuk-notify-orchestrator-staging

namespaces/live.cloud-platform.service.justice.gov.uk/laa-govuk-notify-orchestrator-production/resources/sqs.tf
- Adds visibility_timeout_seconds queue parameter to laa-govuk-notify-orchestrator-production
=> Add visibility_timeout_seconds queue parameter to laa-govuk-notify-orchestrator-production

namespaces/live.cloud-platform.service.justice.gov.uk/laa-information-exchange-development/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-information-exchange-development/05-promethiusrules.yaml
Adds product team access to the namespace. Also minor change to alert labels.
=> Add product team access to the infox dev namespace.

namespaces/live.cloud-platform.service.justice.gov.uk/laa-information-exchange-test/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-information-exchange-test/05-promethiusrules.yaml
As per title. Also adds namespace label for test prometheus alerts.
=> Adds product team access to infox test namespace.

namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-staging/resources/irsa.tf
Update policy to allow transfers from old AWS account PPO site bucket to CP.
=> Update staging environment bucket policy

namespaces/live.cloud-platform.service.justice.gov.uk/cccd-staging/resources/rds.tf
Restore the cccd-staging rds to 4:22am snapshot today 1/11/23
=> Restore cccd-staging rds to earlier snapshot

namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-uat/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-uat/resources/variables.tf
Changing team name to laa-dces-team
=> DCES-188-Changing team name to laa-dces-team

namespaces/live.cloud-platform.service.justice.gov.uk/cccd-api-sandbox/resources/rds.tf
Update the api-sandbox rds to a snapshot made 31/10/2023 at 11pm
=> Restore api-sandbox database snapshot to yesterday

namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-dev/resources/secret.tf
=> DCES-dev-created secret.tf

namespaces/live.cloud-platform.service.justice.gov.uk/create-and-vary-a-licence-api-prod/resources/analytical-platform-access.tf, namespaces/live.cloud-platform.service.justice.gov.uk/create-and-vary-a-licence-api-prod/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/create-and-vary-a-licence-api-prod/resources/versions.tf
Adding the AWS principal permitting export to AP's S3 bucket
=> Add AP export principal to prod

namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-staging/resources/secret.tf
=> DCES-stg-created secret.tf

namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-prod/resources/secret.tf
=> DCES-prod-created secret.tf

namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-uat/resources/secret.tf
created secrets terraform file
=> DCES-uat-created secret.tf

namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-example-dev/resources/ecr.tf, namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-example-dev/resources/serviceaccount.tf
Add github_actions_prefix in ecr module and DEV_ secrets in serviceaccount module
=> update ops-eng-example-dev with dev secrets/vars

namespaces/live.cloud-platform.service.justice.gov.uk/ct-tact-list-dev/resources/irsa-ap-push-to-cp.tf
https://dsdmoj.atlassian.net/jira/software/projects/JCH/issues/JCH-514
=> Add push bucket folder.

namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-prod/resources/ppo-route53.tf
Remove old A record so that a new A record is created that points to the new stack the site is hosted on.
=> Generate new PPO A record

namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-dev/resources/court-case-events-sns-topic.tf
=> CPR-60-topic-update-dev

namespaces/live.cloud-platform.service.justice.gov.uk/mikebell-test/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/mikebell-test/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/mikebell-test/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/mikebell-test/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/mikebell-test/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/mikebell-test/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/mikebell-test/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/mikebell-test/resources/versions.tf
Initial commit of `mikebell-test` namespace as part of onboarding.
=> Create namespace for mikebell-test

namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-prod/resources/court-case-events-sns-topic.tf
=> cpr-60-probation-changes-prod

namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-preprod/resources/court-case-events-sns-topic.tf
=> cpr-60-probation-changes-preprod

namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-prod/resources/court-case-events-sns-topic.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-person-record-prod/resources/cpr-court-case-events-queue.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-person-record-prod/resources/data.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-person-record-prod/resources/irsa.tf
. Added queue subscription for court-case-events topic.
=> CPR-60-prod

namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-preprod/resources/court-case-events-sns-topic.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-person-record-preprod/resources/cpr-court-case-events-queue.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-person-record-preprod/resources/data.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-person-record-preprod/resources/irsa.tf
. Added queue subscription for court-case-events topic.
=> CPR-60-preprod

namespaces/live.cloud-platform.service.justice.gov.uk/mikebell-test/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/mikebell-test/resources/ecr.tf, namespaces/live.cloud-platform.service.justice.gov.uk/mikebell-test/resources/serviceaccount.tf
This PR updates the source code annotation in the namespace and adds in ECR and serviceaccount resources.
=> Update sourcecode url and add ECR and serviceaccount.

namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-preprod/resources/data.tf
. Updated with correct namespace.
=> PIC-3307-preprod

namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-prod/resources/data.tf
. Updated with correct namespace.
=> PIC-3307-prod

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-digital-prison-services-prod/02-limitrange.yaml
follows on from #17635, but for the homepage.
=> CDPS-459 update dps new homepage prod to 100m CPU.

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-micro-frontend-components-prod/02-limitrange.yaml
=> CDPS-460 - update to default request to 100m CPU

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-prisoner-profile-prod/02-limitrange.yaml
to mitigate memory issues, we're upgrading memory request and limits. we are also actively looking at a memory issue, to fix. this is a temporary mitigation (for now)
=> CDPS-513 Double memory limits for hmpps profile

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-digital-prison-services-prod/02-limitrange.yaml
Follows on from #17646 , allows for handling service launch conditions
=> CDPS-512 Double memory for new DPS homepage

namespaces/live.cloud-platform.service.justice.gov.uk/cccd-dev-lgfs/resources/elasticache.tf
=> cccd-dev-lgfs: Update Elasticache Redis to 7.0

namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-prod/resources/icrir-route53.tf
Supporting ICRIR's new email service.
=> ICRIR domain MX record change

namespaces/live.cloud-platform.service.justice.gov.uk/cccd-dev/resources/elasticache.tf
=> cccd-dev: Update Elasticache Redis to 7.0

namespaces/live.cloud-platform.service.justice.gov.uk/mikebell-test/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/mikebell-test/05-servicemonitor.yaml
Adds prometheus monitoring for the mikebell-test applicaiton.
=> Add prometheus monitoring

namespaces/live.cloud-platform.service.justice.gov.uk/cccd-staging/resources/elasticache.tf
=> cccd-staging: Update Elasticache Redis to 7.0

namespaces/live.cloud-platform.service.justice.gov.uk/cccd-api-sandbox/resources/elasticache.tf
=> cccd-api-sandbox: Update Elasticache Redis to 7.0

namespaces/live.cloud-platform.service.justice.gov.uk/mikebell-test/05-servicemonitor.yaml
* cleans up formatting
* adds in missing namespace
* sets port to http and explicit path
=> Potential fix for missing prom metrics

namespaces/live.cloud-platform.service.justice.gov.uk/laa-legal-adviser-api-staging/resources/irsa.tf
Adding required permission needed for RDS snapshot for database migrations 
https://dsdmoj.atlassian.net/browse/LGA-2766
=> LGA-2766 adding irsa policy for rds permissions

namespaces/live.cloud-platform.service.justice.gov.uk/manage-intelligence-dev/resources/rds-aurora.tf
=> set db parameter group family to aurora-postgresql14

namespaces/live.cloud-platform.service.justice.gov.uk/cccd-production/resources/elasticache.tf
=> cccd-production: Update Elasticache Redis to 7.0

.checksum, namespaces/live.cloud-platform.service.justice.gov.uk/cica-copilot-dev/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/cica-copilot-dev/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/cica-copilot-dev/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/cica-copilot-dev/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/cica-copilot-dev/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/cica-copilot-dev/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/cica-copilot-dev/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/cica-copilot-dev/resources/versions.tf
=> Create namespace for cica-copliot-dev

.checksum, namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-api-gateway-uat/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-api-gateway-uat/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-api-gateway-uat/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-api-gateway-uat/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-api-gateway-uat/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-api-gateway-uat/resources/ecr.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-api-gateway-uat/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-api-gateway-uat/resources/serviceaccount.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-api-gateway-uat/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-api-gateway-uat/resources/versions.tf
Creation of UAT namespace for laa-ccms-api-gateway
=> CCMSAPI-12: Create laa-ccms-api-gateway-uat namespace

.checksum, namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-api-gateway-staging/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-api-gateway-staging/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-api-gateway-staging/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-api-gateway-staging/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-api-gateway-staging/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-api-gateway-staging/resources/ecr.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-api-gateway-staging/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-api-gateway-staging/resources/serviceaccount.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-api-gateway-staging/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-api-gateway-staging/resources/versions.tf
Creation of namespace for staging
=> CCMSAPI-12: Create laa-ccms-api-gateway-staging namespace

namespaces/live.cloud-platform.service.justice.gov.uk/laa-legal-adviser-api-staging/resources/rds.tf
- Fixes the minor progres version to 14.7
=> Specify db_engine_version as Postgres 14.7

namespaces/live.cloud-platform.service.justice.gov.uk/laa-legal-adviser-api-staging/resources/rds.tf
Removes the database from `laa-legal-adviser-api-staging` this did not previously pass `Terraform Apply`.
=> Removed database from laa-legal-adviser-api-staging

namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-production/07-issuer.yaml
This adds a HTTP01 Issuer to Data Platform - related to [this](https://mojdt.slack.com/archives/C57UPMZLY/p1699967295124969) thread.
=> :wrench: Add HTTP01 Issuer

namespaces/live.cloud-platform.service.justice.gov.uk/laa-legal-adviser-api-staging/resources/irsa.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-legal-adviser-api-staging/resources/rds.tf
- Removes old Postgres 11 database from `laa-legal-advsier-api-staging`
=> Removed old Postgres 11 database laa-legal-adviser-api-staging

namespaces/live.cloud-platform.service.justice.gov.uk/laa-legal-adviser-api-production/resources/irsa.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-legal-adviser-api-production/resources/rds.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-legal-adviser-api-staging/resources/irsa.tf
- Adds a new Postgres 14 RDS resource to `laa-legal-adviser-api-production`
- Adds a new IRSA Policy arn for this resource
=> Add new Postgres 14 RDS to laa-legal-adviser-api-production

namespaces/live.cloud-platform.service.justice.gov.uk/create-and-vary-a-licence-api-prod/resources/analytical-platform-access.tf
...and also correct service_account_name, which was an artefact mistakenly left over from copy/paste
=> Change bucket name as advised by data engineering

namespaces/live.cloud-platform.service.justice.gov.uk/laa-cla-backend-uat/resources/irsa.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-cla-backend-uat/resources/rds.tf
- Adds Postgres 15 RDS to `laa-cla-backend-uat`
=> Add dashboard RDS to laa-cla-backend-uat

namespaces/live.cloud-platform.service.justice.gov.uk/laa-cla-backend-uat/resources/rds.tf
- Changes the RDS `db_max_allocated_storage` to `db_allocated_storage`
=> Changed db_max_allocated_storage to db_allocated_storage

namespaces/live.cloud-platform.service.justice.gov.uk/help-with-prison-visits-prod/07-grafanadashboard.yaml
=> VB-1874, HWPV - Prod - Grafana ConfigMap

namespaces/live.cloud-platform.service.justice.gov.uk/prison-visits-booking-staging/05-grafanadashboard.yaml
=> VB-1874 - PVB - Staging - grafana ConfigMap

namespaces/live.cloud-platform.service.justice.gov.uk/prison-visits-booking-production/05-grafanadashboard.yaml
=> VB-1874 - PVB - Production - grafana ConfigMap

namespaces/live.cloud-platform.service.justice.gov.uk/prison-visits-booking-dev/07-grafanadashboard.yaml
=> VB-1874 - PVB - Dev - grafana ConfigMap

namespaces/live.cloud-platform.service.justice.gov.uk/send-legal-mail-to-prisons-preprod/07-grafanadashboard.yaml
=> VB-1874 - SLM - preprod - grafana ConfigMap

namespaces/live.cloud-platform.service.justice.gov.uk/send-legal-mail-to-prisons-dev/07-grafanadashboard.yaml
=> VB-1874 - SLM - dev - grafana ConfigMap

namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-staging/10-grafanadashboard.yaml
=> VB-1874 - VSIP Backend - staging - grafana ConfigMap

namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-preprod/10-grafanadashboard.yaml
=> VB-1874 - VSIP Backend - preprod - grafana ConfigMap

namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-dev/10-grafanadashboard.yaml
=> VB-1874 - VSIP Backend - dev - grafana ConfigMap

namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-frontend-svc-dev/09-grafanadashboard.yaml
=> VB-1874, VSIP Frontend - dev - grafana ConfigMap

namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-frontend-svc-staging/09-grafanadashboard.yaml
=> VB-1874, VSIP Frontend - staging - grafana ConfigMap

namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-frontend-svc-prod/09-grafanadashboard.yaml
=> VB-1874, VSIP Frontend - prod - grafana ConfigMap

namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-prod/09-grafanadashboard.yaml
=> VB-1874 - VSIP Backend - prod - grafana ConfigMap

namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-frontend-svc-preprod/09-grafanadashboard.yaml
=> VB-1874, VSIP Frontend - preprod - grafana ConfigMap

namespaces/live.cloud-platform.service.justice.gov.uk/laa-cla-backend-training/resources/irsa.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-cla-backend-training/resources/rds.tf
- Adds Postgres RDS to `laa-cla-backend-training`
=> Add Metabase postgres RDS to laa-cla-backend-training

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-events-dev/resources/book-video-link-sub-queue.tf
needed by BVL
This is a copy of the CVL projects set up with just the app references being changed
=> MAP-465 subscribe to domain events

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-events-dev/resources/book-video-link-sub-queue.tf
needed by BVL
This is a copy of the CVL projects set up with just the app references being changed
=> MAP-465 correct namespace to include hmpps

namespaces/live.cloud-platform.service.justice.gov.uk/send-legal-mail-to-prisons-prod/07-grafanadashboard.yaml
=> VB-1874 - SLM - prod - grafana ConfigMap

namespaces/live.cloud-platform.service.justice.gov.uk/laa-check-client-qualifies-uat/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-check-client-qualifies-uat/resources/variables.tf
We've renamed our GitHub repo, so updating references to it, in this PR.
=> EL-1223: Update to CCQ GitHub repo name - UAT

namespaces/live.cloud-platform.service.justice.gov.uk/laa-check-client-qualifies-staging/00-namespace.yaml
We've renamed our GitHub repo, so updating references to it, in this PR.
=> EL-1223: Update to CCQ GitHub repo name - Staging

namespaces/live.cloud-platform.service.justice.gov.uk/laa-check-client-qualifies-production/00-namespace.yaml
We've renamed our GitHub repo, so updating references to it, in this PR.
=> EL-1223: Update to CCQ GitHub repo name - Production

namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-staging/resources/irsa.tf
Allow us to move contents of legacy s3 into our new s3 bucket.
=> Hale platform Staging add s3 policy

namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-prod/resources/irsa.tf
Allow us to move contents of legacy s3 into our new s3 bucket.
=> Add IMB s3 bucket policy access to legacy bucket

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-interventions-dev/resources/rds-postgres14.tf
Added read replica for dev database for checking if application can be pointed to read replica for read only load.
=> Added read replica for dev database for testing

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-sentence-plan-prototype/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-sentence-plan-prototype/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-sentence-plan-prototype/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-sentence-plan-prototype/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-sentence-plan-prototype/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-sentence-plan-prototype/resources/basic-auth.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-sentence-plan-prototype/resources/ecr.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-sentence-plan-prototype/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-sentence-plan-prototype/resources/serviceaccount.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-sentence-plan-prototype/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-sentence-plan-prototype/resources/versions.tf
Adding thehmpps-sentence-plan-prototype environment
=> Added hmpps-sentence-plan-prototype

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-person-record-dev/resources/court-case-events-topic.tf
. Added court-case-event topic secret
=> CPR-60-dev-fix

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-person-record-preprod/resources/court-case-events-topic.tf
. Added court-case-event topic secret
=> CPR-60-preprod-fix

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-person-record-prod/resources/court-case-events-topic.tf
. Added court-case-event topic secret
=> CPR-60-prod-fix

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-video-link-dev/resources/main.tf
need to access data from AWS console. 
tagged bvl-dev with team name as per [this](https://user-guide.cloud-platform.service.justice.gov.uk/documentation/getting-started/accessing-the-cloud-console.html#tagging-a-module)
=> MAP-465 tag with github team name

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-video-link-dev/resources/main.tf
tag removed as it wasn't producing the desired outcome.
=> MAP-465- remove tag as not correct

namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-saas-test/resources/circleci-service-account.tf, namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-saas-test/resources/fb-av-service-account.tf, namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-saas-test/resources/metadata_api.tf
Update service account names as they conflict with existing old yaml definitions
=> Update service account names in formbuilder-saas-test

namespaces/live.cloud-platform.service.justice.gov.uk/cica-copilot-dev/resources/cognito.tf, namespaces/live.cloud-platform.service.justice.gov.uk/cica-copilot-dev/resources/ecr.tf, namespaces/live.cloud-platform.service.justice.gov.uk/cica-copilot-dev/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/cica-copilot-dev/resources/serviceaccount.tf
Adding ECR, service account, and Cognito to the `cica-copilot-dev` namespace
=> CICA Copilot - add resources

namespaces/live.cloud-platform.service.justice.gov.uk/laa-legal-aid-applications-datastore-uat/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-legal-aid-applications-datastore-uat/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-legal-aid-applications-datastore-uat/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-legal-aid-applications-datastore-uat/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-legal-aid-applications-datastore-uat/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-legal-aid-applications-datastore-uat/resources/ecr.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-legal-aid-applications-datastore-uat/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-legal-aid-applications-datastore-uat/resources/serviceaccount.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-legal-aid-applications-datastore-uat/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-legal-aid-applications-datastore-uat/resources/versions.tf
UAT namespace for Civil Decide Datastore - used to access the data layer
=> AD-399 add decide data store namespace for uat with ecr and service account resources

namespaces/live.cloud-platform.service.justice.gov.uk/laa-legal-aid-applications-datastore-production/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-legal-aid-applications-datastore-production/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-legal-aid-applications-datastore-production/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-legal-aid-applications-datastore-production/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-legal-aid-applications-datastore-production/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-legal-aid-applications-datastore-production/resources/ecr.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-legal-aid-applications-datastore-production/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-legal-aid-applications-datastore-production/resources/serviceaccount.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-legal-aid-applications-datastore-production/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-legal-aid-applications-datastore-production/resources/versions.tf
Production namespace for Civil Decide Datastore - used to access the data layer
=> AD-399 add decide data store namespace for production with ecr and service account resources

namespaces/live.cloud-platform.service.justice.gov.uk/laa-decide-civil-legal-aid-frontend-production/resources/ecr.tf
Add optional prefix as using one repository to push to several namespaces
=> Ad 399 decide frontend actions production

namespaces/live.cloud-platform.service.justice.gov.uk/laa-decide-civil-legal-aid-backend-production/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-decide-civil-legal-aid-backend-production/resources/ecr.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-decide-civil-legal-aid-backend-production/resources/serviceaccount.tf
update repository link and uncomment serviceaccount for github actions
=> AD-399 Fixes for decide production namespace

namespaces/live.cloud-platform.service.justice.gov.uk/laa-decide-civil-legal-aid-backend-staging/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-decide-civil-legal-aid-backend-staging/resources/ecr.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-decide-civil-legal-aid-backend-staging/resources/serviceaccount.tf
remove environment from ecr as does not yet exist in laa-decide-civil-legal-aid-backend
=> AD-399 Update Decide Backend Staging Namespace

namespaces/live.cloud-platform.service.justice.gov.uk/laa-decide-civil-legal-aid-frontend-production/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-decide-civil-legal-aid-frontend-production/resources/ecr.tf
remove environment from ecr as does not yet exist in laa-decide-civil-legal-aid-frontend
=> AD-399 Update Decide Frontend Production Namespace 

namespaces/live.cloud-platform.service.justice.gov.uk/laa-decide-civil-legal-aid-frontend-staging/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-decide-civil-legal-aid-frontend-staging/resources/ecr.tf
remove environment from ecr as does not yet exist in laa-decide-civil-legal-aid-frontend
=> AD-399 Update Decide Frontend Staging Namespace

namespaces/live.cloud-platform.service.justice.gov.uk/laa-decide-civil-legal-aid-ccms-connector-staging/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-decide-civil-legal-aid-ccms-connector-staging/resources/ecr.tf
add optional prefix to allow laa-decide-civil-legal-aid-ccms-connector to push to several namespaces
=> AD-399 Update Decide CCMS connector staging Namespace

namespaces/live.cloud-platform.service.justice.gov.uk/laa-legal-aid-applications-datastore-staging/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-legal-aid-applications-datastore-staging/resources/ecr.tf
add optional prefix to allow laa-legal-aid-applications-datastore to push to several namespaces
=> AD-399 Update laa-legal-aid-applications-datastore staging namespace

namespaces/live.cloud-platform.service.justice.gov.uk/laa-legal-aid-applications-datastore-uat/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-legal-aid-applications-datastore-uat/resources/ecr.tf
add optional prefix to allow laa-legal-aid-applications-datastore to push to several namespaces
=> AD-399 Update laa-legal-aid-applications-datastore uat Namespace

namespaces/live.cloud-platform.service.justice.gov.uk/laa-decide-civil-legal-aid-ccms-connector-production/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-decide-civil-legal-aid-ccms-connector-production/resources/ecr.tf
add optional prefix to allow laa-decide-civil-legal-aid-ccms-connector to push to several namespaces
=> AD-399 Update Decide CCMS connector production Namespace

namespaces/live.cloud-platform.service.justice.gov.uk/laa-legal-aid-applications-datastore-production/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-legal-aid-applications-datastore-production/resources/ecr.tf
add optional prefix to allow laa-legal-aid-applications-datastore to push to several namespaces
=> AD-399 Update laa-legal-aid-applications-datastore production namespace

namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-prod/resources/imb-route53.tf
Remove old CNAME record so that it points to our new stack rather then old one.
=> Point myIMB subdomain to new site

namespaces/live.cloud-platform.service.justice.gov.uk/calculate-release-dates-dev/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/calculate-release-dates-dev/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/calculate-release-dates-dev/resources/variables.tf
Update dev farsight developers to crds team
=> CRD-1684 Update dev farsight developers to crds team

namespaces/live.cloud-platform.service.justice.gov.uk/calculate-release-dates-preprod/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/calculate-release-dates-preprod/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/calculate-release-dates-preprod/resources/variables.tf
Update preprod farsight developers to crds team
=> CRD-1684 Update preprod farsight developers to crds team

namespaces/live.cloud-platform.service.justice.gov.uk/calculate-release-dates-api-prod/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/calculate-release-dates-api-prod/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/calculate-release-dates-api-prod/resources/variables.tf
Update prod api farsight developers to crds team
=> CRD-1684 - Update prod api farsight developers to crds team

namespaces/live.cloud-platform.service.justice.gov.uk/laa-decide-civil-legal-aid-backend-uat/resources/ecr.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-decide-civil-legal-aid-backend-uat/resources/serviceaccount.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-decide-civil-legal-aid-backend-uat/resources/variables.tf
Update to use variables for secrets for deployments rather than github prefixes
=> AD-407-Creating deployment using github actions

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-incident-reporting-dev/resources/sqs.tf
Completes `dev` namespace creation in #18074
=> IR-68: Set SQS queue policy for `dev` HMPPS Incident Reporting Service now that it exists

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-incident-reporting-preprod/resources/sqs.tf
Completes `preprod` namespace creation in #18080
=> IR-68: Set SQS queue policy for `preprod` HMPPS Incident Reporting Service now that it exists

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-incident-reporting-prod/resources/sqs.tf
Completes `prod` namespace creation in #18075
=> IR-68: Set SQS queue policy for `prod` HMPPS Incident Reporting Service now that it exists

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-dev/resources/locals.tf
This will generate an API Gateway API key that can be shared.
=> Create new API key for consumer in Dev

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-delius-alfrsco-poc/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-delius-alfrsco-poc/01-rbac.yaml
Adding members of Zaizi-devs GH team to hmpps-delius-alfrsco-poc ns
=> NIT-969 Zaizi-devs GH team added to hmpps-delius-alfrsco-poc ns

namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-saas-test/resources/circleci-service-account.tf
It's clashing with a test service account but I'd rather rename and clean up after than go in and delete things now.
=> Ensure this service account has a unique name

namespaces/live.cloud-platform.service.justice.gov.uk/laa-check-client-qualifies-staging/resources/rds.tf
=> CCQ STG add metabase

namespaces/live.cloud-platform.service.justice.gov.uk/laa-cla-backend-uat/resources/rds.tf
Add new RDS instance for eligibility integration
=> Add new RDS instance for eligibility integration

namespaces/live.cloud-platform.service.justice.gov.uk/laa-check-client-qualifies-staging/resources/rds.tf
added an RDS in error when I needed to just connect to the existing RDS in this namespace
=> CCQ STG remove rds

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-dev/05-dashboard.yaml
Also update API Gateway panel title in Grafana
=> Fix syntax error HMPPS Integration API Dev Dashboard

namespaces/live.cloud-platform.service.justice.gov.uk/laa-check-client-qualifies-production/resources/rds.tf
add secret for metabase to connect to rds
=> CCQ PROD add secret data

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-subject-access-request-dev/resources/irsa.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-subject-access-request-dev/resources/variables.tf
Add IRSA to access hmpps-audit-dev  for auditing
=> Add IRSA to access hmpps-audit-dev

.checksum, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-candidate-matching-dev/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-candidate-matching-dev/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-candidate-matching-dev/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-candidate-matching-dev/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-candidate-matching-dev/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-candidate-matching-dev/resources/ecr.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-candidate-matching-dev/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-candidate-matching-dev/resources/serviceaccount.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-candidate-matching-dev/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-candidate-matching-dev/resources/versions.tf
Create candidate matching dev namespace
=> ESWE-754 - Candidate Matching DEV

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-sandbox-admin/resources/rds.tf
commented the force ssl parameter
=> Laws 3558 spike feasibility to migrate ccr cclf to cloud platform

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-sandbox-admin/resources/rds.tf
=> assigning security group

.checksum, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-candidate-matching-preprod/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-candidate-matching-preprod/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-candidate-matching-preprod/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-candidate-matching-preprod/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-candidate-matching-preprod/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-candidate-matching-preprod/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-candidate-matching-preprod/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-candidate-matching-preprod/resources/versions.tf
Add Candidate Matching Service - PreProd
=> ESWE-754 Candidate Matching - PreProd

.checksum, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-candidate-matching-prod/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-candidate-matching-prod/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-candidate-matching-prod/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-candidate-matching-prod/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-candidate-matching-prod/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-candidate-matching-prod/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-candidate-matching-prod/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-candidate-matching-prod/resources/versions.tf
=> ESWE-754 - Candidate Matching - Prod

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-candidate-matching-dev/01-rbac.yaml
=> ESWE-755 - Candidate Matching UI Bootstrap (Dev)

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-candidate-matching-preprod/01-rbac.yaml
=> ESWE-755 - Candidate Matching UI Bootstrap (Preprod)

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-candidate-matching-prod/01-rbac.yaml
=> ESWE-755 - Candidate Matching UI Bootstrap (Prod)

namespaces/live.cloud-platform.service.justice.gov.uk/use-of-force-dev/resources/analytical-platform-access.tf, namespaces/live.cloud-platform.service.justice.gov.uk/use-of-force-dev/resources/versions.tf
IRSA role from the existing secret should now be used
=> Removed token resources from use of force dev

namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-firebreak-daap-api/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-firebreak-daap-api/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-firebreak-daap-api/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-firebreak-daap-api/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-firebreak-daap-api/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-firebreak-daap-api/resources/ecr.tf, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-firebreak-daap-api/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-firebreak-daap-api/resources/serviceaccount.tf, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-firebreak-daap-api/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-firebreak-daap-api/resources/versions.tf
- create namespace
- add ecr
- add serviceaccount
=> create dp firebreak daap fastapi namespace

namespaces/live.cloud-platform.service.justice.gov.uk/offender-management-preprod/resources/domain-events-subscription.tf
Ticket: https://dsdmoj.atlassian.net/browse/MO-1389
=> Add MPC domain event filter - preprod

namespaces/live.cloud-platform.service.justice.gov.uk/offender-management-staging/resources/domain-events-subscription.tf
Ticket: https://dsdmoj.atlassian.net/browse/MO-1389
=> Add MPC domain event filter - staging

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-candidate-matching-dev/05-serviceaccount-circleci.yaml
=> ESWE-755 - Candidate Matching- Dev

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-candidate-matching-preprod/resources/serviceaccount-circleci.tf
=> ESWE-755 - Candidate Matching - Preprod

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-candidate-matching-prod/resources/serviceaccount-circleci.tf
=>  ESWE-755 - Candidate Matching - Prod

namespaces/live.cloud-platform.service.justice.gov.uk/offender-management-production/resources/domain-events-subscription.tf
Ticket: https://dsdmoj.atlassian.net/browse/MO-1389
=> Add domain event filter for prod

namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-firebreak-daap-api/resources/elasticache.tf
Adding redis elasticache resource for data platform fastapi PoC
=> Data Platform fastapi PoC - add redis elasticache resource

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-candidate-matching-dev/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-candidate-matching-dev/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-candidate-matching-dev/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-candidate-matching-dev/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-candidate-matching-dev/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-candidate-matching-dev/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-candidate-matching-dev/resources/serviceaccount-circleci.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-candidate-matching-dev/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-candidate-matching-dev/resources/versions.tf
=> ESWE-755 - Candidate Matching - Dev

namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-officehub-cms-app-dev/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-officehub-cms-app-dev/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-officehub-cms-app-dev/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-officehub-cms-app-dev/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-officehub-cms-app-dev/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-officehub-cms-app-dev/resources/ecr.tf, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-officehub-cms-app-dev/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-officehub-cms-app-dev/resources/serviceaccount.tf, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-officehub-cms-app-dev/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-officehub-cms-app-dev/resources/versions.tf
Request to add a namespace for the dev of this AP app. 
@julialawrence any chance you could take a quick look? 
Many thanks!
=> request: dev namespace officehub-cms

namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-officehub-cms-app-prod/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-officehub-cms-app-prod/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-officehub-cms-app-prod/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-officehub-cms-app-prod/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-officehub-cms-app-prod/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-officehub-cms-app-prod/resources/ecr.tf, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-officehub-cms-app-prod/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-officehub-cms-app-prod/resources/serviceaccount.tf, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-officehub-cms-app-prod/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-officehub-cms-app-prod/resources/versions.tf
@julialawrence Same namspace request, for the prod namespace. TIA :)!
=> request: namspace for officehub cms prod

namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-firebreak-daap-api/resources/elasticache.tf, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-firebreak-daap-api/resources/rds-postgresql.tf
swap replication group id for redis url
=> update elasticache cluster output

namespaces/live.cloud-platform.service.justice.gov.uk/prison-visits-booking-dev/05-serviceaccount-circleci.yaml
* Change role to edit
* Add RoleBinding for prometheus alerts
=> Refactor prison-visits-booking-dev sa

namespaces/live.cloud-platform.service.justice.gov.uk/prison-visits-booking-production/serviceaccount-circleci.yaml
* Add RoleBinding for circleci
* Add RoleBinding for prometheus alerts
=> Refactor prison-visits-booking-production sa

namespaces/live.cloud-platform.service.justice.gov.uk/prison-visits-booking-staging/serviceaccount-circleci.yaml
Refactor sa for prison-visits-booking-staging
=> Refactor sa for prison-visits-booking-staging

namespaces/live.cloud-platform.service.justice.gov.uk/hmcts-complaints-formbuilder-adapter-production/resources/serviceaccount.tf
In particular we need horizontalpodautoscalers.
=> Add additional rules to SA

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-candidate-matching-dev/resources/elasticache.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-candidate-matching-dev/resources/variables.tf
=> ESWE-782 - Redis - Dev

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-candidate-matching-preprod/resources/elasticache.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-candidate-matching-preprod/resources/variables.tf
=> ESWE-782 - Redis - Preprod

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-dev/resources/s3_truststore.tf
The application name isn't suitable, use the namespace instead
=> Fix bucket name for HMPPS Integration API Dev

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-dev/resources/s3_truststore.tf
This should be the IAM user ARN, not name
=> Update principal for bucket policy

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-candidate-matching-dev/06-certificate.yaml
=>  ESWE-761 - SSL Certs - Dev

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-candidate-matching-preprod/06-certificate.yaml
=>  ESWE-761 - SSL Certs - Preprod

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-candidate-matching-prod/06-certificate.yaml
=>  ESWE-761 - SSL Certs - Prod 

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-person-record-preprod/resources/cpr-delius-offender-events-queue.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-person-record-preprod/resources/data.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-person-record-preprod/resources/domain-events-topic.tf
. Added delius domain event subscription
. Added domain event topic secret.
=> CPR-63-preprod

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-person-record-prod/resources/cpr-delius-offender-events-queue.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-person-record-prod/resources/data.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-person-record-prod/resources/domain-events-topic.tf
. Added delius domain event subscription
. Added domain event topic secret.
=> CPR-63-prod

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-candidate-matching-dev/resources/rds.tf
=> ESWE-783 - Configure RDS - Dev

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-candidate-matching-preprod/resources/rds.tf
=> ESWE-783 - Configure RDS - Preprod

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-candidate-matching-prod/resources/rds.tf
=> ESWE-783 - Configure RDS - Prod

.checksum, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-equinity-historical-data-uat/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-equinity-historical-data-uat/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-equinity-historical-data-uat/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-equinity-historical-data-uat/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-equinity-historical-data-uat/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-equinity-historical-data-uat/resources/ecr.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-equinity-historical-data-uat/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-equinity-historical-data-uat/resources/serviceaccount.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-equinity-historical-data-uat/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-equinity-historical-data-uat/resources/versions.tf
EMP-67: Create UAT Namespace for Equinity Data Migration propject
=> EMP-67: Create UAT Namespace for Equinity Data Migration propject

namespaces/live.cloud-platform.service.justice.gov.uk/laa-claim-non-standard-magistrate-fee-dev-crm4/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-claim-non-standard-magistrate-fee-dev-crm4/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-claim-non-standard-magistrate-fee-dev-crm4/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-claim-non-standard-magistrate-fee-dev-crm4/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-claim-non-standard-magistrate-fee-dev-crm4/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-claim-non-standard-magistrate-fee-dev-crm4/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-claim-non-standard-magistrate-fee-dev-crm4/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-claim-non-standard-magistrate-fee-dev-crm4/resources/versions.tf
Add namespace laa-claim-non-standard-magistrate-fee-dev-crm4
=> Add namespace laa-claim-non-standard-magistrate-fee-dev-crm4

namespaces/live.cloud-platform.service.justice.gov.uk/laa-assess-non-standard-magistrate-fee-dev-crm4/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-assess-non-standard-magistrate-fee-dev-crm4/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-assess-non-standard-magistrate-fee-dev-crm4/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-assess-non-standard-magistrate-fee-dev-crm4/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-assess-non-standard-magistrate-fee-dev-crm4/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-assess-non-standard-magistrate-fee-dev-crm4/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-assess-non-standard-magistrate-fee-dev-crm4/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-assess-non-standard-magistrate-fee-dev-crm4/resources/versions.tf
Add laa-assess-non-standard-magistrate-fee-dev-crm4 namespace
=> Add laa-assess-non-standard-magistrate-fee-dev-crm4 namespace

namespaces/live.cloud-platform.service.justice.gov.uk/laa-claim-non-standard-magistrate-fee-dev-crm4/resources/serviceaccount.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-claim-non-standard-magistrate-fee-dev-crm4/resources/variables.tf
=> Add serviceaccount

namespaces/live.cloud-platform.service.justice.gov.uk/laa-claim-non-standard-magistrate-fee-dev-crm4/resources/rds-postgresql.tf
Add rds postgresql database resource
=> Add rds postgresql database resource

namespaces/live.cloud-platform.service.justice.gov.uk/laa-claim-non-standard-magistrate-fee-dev-crm4/resources/s3.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-claim-non-standard-magistrate-fee-dev-crm4/resources/shared-s3-secret.tf
=> Add s3 resource

namespaces/live.cloud-platform.service.justice.gov.uk/laa-claim-non-standard-magistrate-fee-dev-crm4/resources/elasticache.tf
=> Add elasticache resource

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-delius-alfrsco-poc/resources/serviceaccount.tf
Organizing cluster secrets for ALF environments
=> NIT-994 pipeline for installing helm charts

namespaces/live.cloud-platform.service.justice.gov.uk/laa-cla-backend-staging/resources/rds.tf
Restore RDS from snapshot `laa-cla-backend-staging`
=> Restore RDS from snapshot laa-cla-backend-staging

namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-firebreak-aws-microservice-dev/resources/serviceaccount.tf
Update the `serviceaccount_rules` to copy the default rules, but add `serviceaccount` so that it can create a service account
=> Add serviceaccount to serviceaccount_rules

namespaces/live.cloud-platform.service.justice.gov.uk/laa-assess-non-standard-magistrate-fee-dev-crm4/resources/elasticache.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-assess-non-standard-magistrate-fee-dev-crm4/resources/rds-postgresql.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-assess-non-standard-magistrate-fee-dev-crm4/resources/serviceaccount.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-assess-non-standard-magistrate-fee-dev-crm4/resources/variables.tf
Provision SA, RDS, ReDiS, IRSA for laa-claim-non-standard-magistrate-fee-dev-crm4
- CRM457-854: Add serviceaccount and rules
- CRM457-854: Add RDS
- CRM457-854: Add elasticache resource
=> CRM457-854: provision resources for laa-claim-non-standard-magistrate-fee-dev-crm4

namespaces/live.cloud-platform.service.justice.gov.uk/laa-assess-non-standard-magistrate-fee-dev-crm4/resources/irsa.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-assess-non-standard-magistrate-fee-dev-crm4/resources/variables.tf
=> CRM457-854: Add IRSA

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-application-store-dev-crm4/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-application-store-dev-crm4/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-application-store-dev-crm4/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-application-store-dev-crm4/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-application-store-dev-crm4/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-application-store-dev-crm4/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-application-store-dev-crm4/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-application-store-dev-crm4/resources/versions.tf
CRM457-854: Add namespace for dev-crm4 environment
=> CRM457-854: Add namespace for dev-crm4 environment

namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-saas-live/resources/circleci-service-account.tf, namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-saas-live/resources/variables.tf
Add module generated service account for circleci deployments to formbuilder-saas-live
=> Add module generated service account

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-prod/resources/s3_truststore.tf
The code adds some infrastructure in production to create a backup bucket for client certificates.
=> Adding certificate back up on prod

namespaces/live.cloud-platform.service.justice.gov.uk/verification-report-pilot/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/verification-report-pilot/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/verification-report-pilot/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/verification-report-pilot/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/verification-report-pilot/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/verification-report-pilot/resources/basic-auth.tf, namespaces/live.cloud-platform.service.justice.gov.uk/verification-report-pilot/resources/ecr.tf, namespaces/live.cloud-platform.service.justice.gov.uk/verification-report-pilot/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/verification-report-pilot/resources/serviceaccount.tf, namespaces/live.cloud-platform.service.justice.gov.uk/verification-report-pilot/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/verification-report-pilot/resources/versions.tf
Trying to set things up for a new prototype. Be kind I'm not a dev 😄
=> Added verification report prototype

namespaces/live.cloud-platform.service.justice.gov.uk/laa-cla-backend-staging/resources/rds.tf
Recreates the read replica RDS, temporarily removed in [this PR](https://github.com/ministryofjustice/cloud-platform-environments/pull/18501)
=> Recreate read replica RDS

namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-prod/resources/pingdom.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-prod/resources/versions.tf
Adding Pingdom for the Hale Platform using Cloud Platform
=> Updated versions.tf and added pingdom.tf for Hale-Platform

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-matching-prototype/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-matching-prototype/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-matching-prototype/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-matching-prototype/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-matching-prototype/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-matching-prototype/resources/basic-auth.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-matching-prototype/resources/ecr.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-matching-prototype/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-matching-prototype/resources/serviceaccount.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-matching-prototype/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-matching-prototype/resources/versions.tf
Create candidate matching prototype
=> Candidate Matching Prototype

namespaces/live.cloud-platform.service.justice.gov.uk/justice-gov-uk-dev/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/justice-gov-uk-dev/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/justice-gov-uk-dev/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/justice-gov-uk-dev/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/justice-gov-uk-dev/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/justice-gov-uk-dev/05-prometheus.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/justice-gov-uk-dev/resources/cloudfront.tf, namespaces/live.cloud-platform.service.justice.gov.uk/justice-gov-uk-dev/resources/ecr.tf, namespaces/live.cloud-platform.service.justice.gov.uk/justice-gov-uk-dev/resources/irsa.tf, namespaces/live.cloud-platform.service.justice.gov.uk/justice-gov-uk-dev/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/justice-gov-uk-dev/resources/rds.tf, namespaces/live.cloud-platform.service.justice.gov.uk/justice-gov-uk-dev/resources/s3.tf, namespaces/live.cloud-platform.service.justice.gov.uk/justice-gov-uk-dev/resources/serviceaccount.tf, namespaces/live.cloud-platform.service.justice.gov.uk/justice-gov-uk-dev/resources/servicepod.tf, namespaces/live.cloud-platform.service.justice.gov.uk/justice-gov-uk-dev/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/justice-gov-uk-dev/resources/versions.tf
This environment is for an application that uses WordPress to deliver a content management system for stakeholders to maintain and manage the justice.gov.uk website.
It creates resources in RDS, S3 and CloudFront.
=> Initial development environment for justice.gov.uk

.checksum, namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-join-github-dev/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-join-github-dev/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-join-github-dev/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-join-github-dev/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-join-github-dev/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-join-github-dev/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-join-github-dev/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-join-github-dev/resources/versions.tf
Connects to https://github.com/ministryofjustice/operations-engineering-landing-page-poc/issues/36
=> :sparkles: Add new development namespace

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-equinity-historical-data-uat/resources/s3.tf
Add S3 bucket for UAT with default values
=> EMP-68: Add S3 bucket for UAT with default values

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-equinity-historical-data-uat/resources/iam.tf
IAM user is created for get file and upload files.
=> IAM User for file upload

namespaces/live.cloud-platform.service.justice.gov.uk/send-legal-mail-to-prisons-dev/resources/rds.tf
SLM-338 update Send Legal Mail DB version to 14.10 for send-legal-mail-to-prisons-dev namespace.
=> SLM-338 update SLM version to 14.10 for send-legal-mail-to-prisons-dev namespace.

namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-datahub-catalogue-dev/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-datahub-catalogue-dev/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-datahub-catalogue-dev/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-datahub-catalogue-dev/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-datahub-catalogue-dev/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-datahub-catalogue-dev/resources/ecr.tf, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-datahub-catalogue-dev/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-datahub-catalogue-dev/resources/serviceaccount.tf, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-datahub-catalogue-dev/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-datahub-catalogue-dev/resources/versions.tf
creating a namespace for the data platform's datahub catalogue
=> namespace for data platform datahub catalogue

.checksum, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-hello-world-mat-dev/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-hello-world-mat-dev/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-hello-world-mat-dev/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-hello-world-mat-dev/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-hello-world-mat-dev/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-hello-world-mat-dev/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-hello-world-mat-dev/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-hello-world-mat-dev/resources/versions.tf
I'm going through the guide at https://user-guide.cloud-platform.service.justice.gov.uk/documentation/getting-started/cloud-platform-cli.html#create-an-environment
=> Create a namespace for going through the tutorial

.checksum, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-equinity-historical-data-staging/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-equinity-historical-data-staging/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-equinity-historical-data-staging/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-equinity-historical-data-staging/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-equinity-historical-data-staging/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-equinity-historical-data-staging/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-equinity-historical-data-staging/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-equinity-historical-data-staging/resources/versions.tf
Added staging namespace following CP CLI Guide
=> EMP-69: Adding staging namespace to project

namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-hello-world-mat-dev/resources/ecr.tf
Following https://user-guide.cloud-platform.service.justice.gov.uk/documentation/getting-started/cloud-platform-cli.html#adding-a-container-repository-to-your-namespace
=> Add ECR repository

namespaces/live.cloud-platform.service.justice.gov.uk/laa-hmrc-interface-uat/resources/rds.tf
=> LAA-HMRC-Interface UAT - update RDS minor version

namespaces/live.cloud-platform.service.justice.gov.uk/laa-hmrc-interface-uat/resources/rds.tf
=> LAA-HMRC-Interface Staging - update RDS minor version

namespaces/live.cloud-platform.service.justice.gov.uk/legal-framework-api-staging/resources/rds.tf
=> Legal Framework Staging - update RDS minor version

namespaces/live.cloud-platform.service.justice.gov.uk/laa-assure-hmrc-data-staging/resources/rds-postgresql.tf
=> HMRC Assure Staging - update RDS minor version

namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-staging/resources/rds.tf
=> LAA Civil Apply Staging - update RDS minor version

namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-production/resources/rds.tf
=> LAA Civil Apply Production - update RDS minor version

namespaces/live.cloud-platform.service.justice.gov.uk/send-legal-mail-to-prisons-preprod/resources/rds.tf
SLM-338 update Send Legal Mail DB version to 14.10 for send-legal-mail-to-prisons-preprod namespace.
=> SLM-338 update SLM version to 14.10 for send-legal-mail-to-prisons-preprod namespace.

namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-datahub-catalogue-dev/resources/opensearch.tf, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-datahub-catalogue-dev/resources/rds-postgresql.tf, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-datahub-catalogue-dev/resources/variables.tf
Adding rds postgres and opensearch resources for data platform datahub app
=> opensearch and rds resources for datahub

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-application-store-dev/resources/rds-postgresql.tf
=> laa-crime-application-store-dev - Upgrade to 16.1

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-education-and-work-plan-dev/06-certificate.yaml
PR to add a new certificate into the `hmpps-education-and-work-plan-dev` namespace
=> RR-573 - Add the cert for the CIAG UI to the hmpps-education-and-work-plan-dev namespace

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-application-store-dev/resources/rds-postgresql.tf
Set `prepare_for_major_upgrade = false` and update read_replica to 16
=> laa-crime-application-store-dev - Update prepare tag and read replica

namespaces/live.cloud-platform.service.justice.gov.uk/legal-framework-api-production/resources/rds.tf
=> Legal Framework Production - update RDS minor version

namespaces/live.cloud-platform.service.justice.gov.uk/laa-assure-hmrc-data-production/resources/rds-postgresql.tf
=> HMRC Assure Production - update RDS minor version

namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-datahub-catalogue-dev/resources/rds-postgresql.tf
To have the rds url available in kube secrets too
=> add postgres rds url to kube secrets

namespaces/live.cloud-platform.service.justice.gov.uk/legal-framework-api-production/resources/rds.tf
=> Update Legal Framework Production RDS

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-activities-management-dev/resources/rds.tf
This PR adds RDS Postgresql parameters required to enable replication.
(it requires a DB reboot for these to take effect).
=> SAA-1444: Add replication parameters to RDS database for Digital Prison Reporting.

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-interventions-prod/resources/rds-postgres14.tf
Read replica for prod database for reporting load.
=> Added read replica for prod database

namespaces/live.cloud-platform.service.justice.gov.uk/digital-prison-services-prod/resources/route53-prison.tf
Updating the Prison API A record to reference the new App GW
=> DSOS-2530: Update route53-prison.tf

namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-dev/05-prometheus.yaml
Added new alert to monitor OOMKilled. 
Trying to verifying our webhook is actually working as it should.
=> Added new prometheus alert

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-education-and-work-plan-preprod/06-certificate.yaml
PR to add a new certificate into the `hmpps-education-and-work-plan-preprod` namespace
=> RR-573 - Add the cert for the CIAG UI to the hmpps-education-and-work-plan-preprod namespace

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-education-and-work-plan-prod/06-certificate.yaml
PR to add a new certificate into the `hmpps-education-and-work-plan-prod` namespace
=> RR-573 - Add the cert for the CIAG UI to the hmpps-education-and-work-plan-prod namespace

namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-prod/resources/omagh-route53.tf
Add zone for domain omagh.independent-inquiry.uk . Will add further records later as we need them.
=> Add Route53 zone for Omagh inquiry

.checksum, namespaces/live.cloud-platform.service.justice.gov.uk/tariq-test/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/tariq-test/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/tariq-test/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/tariq-test/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/tariq-test/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/tariq-test/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/tariq-test/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/tariq-test/resources/versions.tf
=> Create namespace for tariq-test

namespaces/live.cloud-platform.service.justice.gov.uk/laa-means-prototype/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-means-prototype/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-means-prototype/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-means-prototype/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-means-prototype/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-means-prototype/resources/basic-auth.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-means-prototype/resources/ecr.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-means-prototype/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-means-prototype/resources/serviceaccount.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-means-prototype/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-means-prototype/resources/versions.tf
=> add laa-means-prototype

namespaces/live.cloud-platform.service.justice.gov.uk/laa-claim-non-standard-magistrate-fee-dev-crm4/resources/rds-postgresql.tf
=> nscc-dev-crm4: Upgrade postgres 14.7 to 15.5

namespaces/live.cloud-platform.service.justice.gov.uk/laa-fala-production/resources/s3.tf
Adds CORS Rule to S3 Bucket of `laa-fala-production`
=> Add CORS Rule to laa-fala-production S3 Bucket

namespaces/live.cloud-platform.service.justice.gov.uk/tariq-test/resources/ecr.tf, namespaces/live.cloud-platform.service.justice.gov.uk/tariq-test/resources/serviceaccount.tf
Deploying an example application - Create a Cloud Platform container repository and service account
=> added files ecr.tf and serviceaccount.tf to namespace tariq-test

namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-preprod/resources/rds.tf
update VSIP DB version to 14.10 for visit-someone-in-prison-backend-svc-preprod namespace.
=> VSIP - VB-3380 - update VSIP DB version to 14.10 for visit-someone-in-prison-backend-svc-preprod namespace.

namespaces/live.cloud-platform.service.justice.gov.uk/laa-assess-non-standard-magistrate-fee-dev-crm4/resources/rds-postgresql.tf
=> assess-dev-crm4: Bump postgres 14.7 to 14.10

namespaces/live.cloud-platform.service.justice.gov.uk/laa-assess-non-standard-magistrate-fee-dev-crm4/resources/rds-postgresql.tf
=> assess-dev-crm4: Bump postgres 14.10 to 16.1

namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-dev/resources/rds.tf
VSIP - VB-3380 - update VSIP DB version to 15.5 for visit-someone-in-prison-backend-svc-dev namespace.
=> VSIP - VB-3380 - update VSIP DB version to 15.5 for visit-someone-in-prison-backend-svc-dev namespace.

namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-dev/02-limitrange.yaml
Testing has finished, putting limits back to origianal values
=> put limits back to original values

namespaces/live.cloud-platform.service.justice.gov.uk/laa-claim-non-standard-magistrate-fee-dev-crm4/resources/rds-postgresql.tf
=> nscc-dev-crm4: add db minor version

namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-datahub-catalogue-dev/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-datahub-catalogue-dev/01-rbac.yaml
Changing the team to give wider data-platform members access to the namespace
=> change namespace team

namespaces/live.cloud-platform.service.justice.gov.uk/laa-assess-non-standard-magistrate-fee-dev-crm4/resources/rds-postgresql.tf
Add prepare_for_major_upgrade flag to fix upgrade
=> assess-dev-crm4: add flag to fix upgrade

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-application-store-dev-crm4/resources/rds-postgresql.tf
Bump PG to 14.10 prior to major version bump
=> CRM457-923 - Minor PG Version bump

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-application-store-uat/resources/rds-postgresql.tf
=> CRM457-923 - Major PG version bump

namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-datahub-catalogue-dev/resources/rds-postgresql.tf
Installation not working with postgres version 16. Changing to 15 to test
=> change postgres version

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-application-store-uat/resources/rds-postgresql.tf
Set `prepare_for_major_upgrade` to false following upgrade to 16.1
=> CRM457-923 - Set major upgrade flag to false

namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-datahub-catalogue-dev/resources/rds-postgresql.tf
Didn't set variables to allow for previous version change, this does that
=> update variables to allow postgres version change

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-application-store-production/resources/variables.tf
Updated team name and email to match those of other n-scc services
=> CRM457-953 update team and team email in variables

namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-datahub-catalogue-dev/resources/irsa.tf
Adding IRSA to assume role with permissions for datahub app
=> add irsa for datahub

.checksum, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-one-plan-dev/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-one-plan-dev/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-one-plan-dev/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-one-plan-dev/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-one-plan-dev/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-one-plan-dev/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-one-plan-dev/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-one-plan-dev/resources/versions.tf
New namespace for One Plan Development environment.
=> Create namespace for One Plan

namespaces/live.cloud-platform.service.justice.gov.uk/digital-prison-services-prod/resources/route53-prison.tf
update the endpoint IPs, so we can remove the V2 AppGWs
=> DSOS-2529: update for v3 IPs

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-resettlement-passport-preprod/resources/rds-postgresql.tf
=> RP-966 Upgrade resettlement passport preprod RDS database version

namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-datahub-catalogue-dev/resources/secrets.tf
adding secret to hold azure secrets for app auth
=> adding secrets resource to dathub namespace

namespaces/live.cloud-platform.service.justice.gov.uk/offender-case-notes-preprod/resources/rds.tf
remove skip namespace file for offender-case-notes-preprod
=> HAAR-2243: set prepare_for_major_upgrade to false and

.checksum, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-absence-management-dev/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-absence-management-dev/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-absence-management-dev/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-absence-management-dev/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-absence-management-dev/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-absence-management-dev/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-absence-management-dev/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-absence-management-dev/resources/versions.tf
Requesting this sandbox environment for the prototyping of:
- a Lightweight Absence Management service (only backend) to be called from WMT dev to maintain context of Absences (specifically Annual Leave).
=> Alpha Prototyping - Probation Absence Management Service

namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-prod/resources/omagh-route53.tf
New MX records for the omagh.independent-inquiry.uk domain.
=> Add Omagh inquiry domain MX mail records

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-intelligence-prod/resources/rds-aurora.tf
Reverts ministryofjustice/cloud-platform-environments#19002
=> Revert "update rds postgresql to 16.1"

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-activities-management-preprod/resources/rds.tf
Changes: PreProd PostgresSQL upgrade from 14.0 to 14.10
=> SAA-1496 PostgreSQL preprod upgrade from 14.0 to 14.10

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-activities-management-prod/resources/rds.tf
Changes: Upgrade PostgreSQL from 14.0 to 14.10
=> SAA-1496 PostgreSQL PROD upgrade from 14.0 to 14.10

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-interventions-dev/resources/irsa.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-interventions-dev/resources/service-pod.tf
PR for service pod for hmpps-intervention service
=> configuring service pod for hmpps-interventions

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-activities-management-preprod/resources/irsa.tf
=> SAA-1444 RDS Policy for preprod irsa

.checksum, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-dev/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-dev/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-dev/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-dev/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-dev/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-dev/resources/ecr.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-dev/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-dev/resources/serviceaccount.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-dev/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-dev/resources/versions.tf
We are creating a new namespace for CCR dev environment for the migration to cloud platforms. 
[Link to ticket](https://dsdmoj.atlassian.net/browse/CTSKF-666)
=> Laa crown court remuneration dev

namespaces/live.cloud-platform.service.justice.gov.uk/offender-events-preprod/resources/cpr-offender-events-sub-queue.tf
. Added offender events subscription queue for core person record
=> CPR-127-preprod

namespaces/live.cloud-platform.service.justice.gov.uk/offender-events-prod/resources/cpr-offender-events-sub-queue.tf
. Added offender events subscription queue for core person record
=> CPR-127-prod

namespaces/live.cloud-platform.service.justice.gov.uk/laa-check-client-qualifies-production/resources/rds.tf
=> CCQ PROD 2 upgrade db

namespaces/live.cloud-platform.service.justice.gov.uk/offender-events-dev/resources/cpr-offender-events-sub-queue.tf
=> CPR-127-dev

namespaces/live.cloud-platform.service.justice.gov.uk/justice-gov-uk-demo/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/justice-gov-uk-demo/05-prometheus.yaml
=> Fix name/label clashes

namespaces/live.cloud-platform.service.justice.gov.uk/justice-gov-uk-dev/resources/ecr.tf
Add prefix on the development stack
=> Add a prefix to prevent variable name interference

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-dev/resources/rds.tf
This PR is for duplicating the known working RDS terraform file from CCR Sandbox to CCR Dev
=> CTSKF-666 CCR Dev namespace migration - RDS

namespaces/live.cloud-platform.service.justice.gov.uk/justice-gov-uk-dev/resources/route53.tf
This Terraform file creates a DNS zone on CP for the domain: dev.justice.gov.uk
=> Create a DNS zone

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-resettlement-passport-preprod/resources/irsa.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-resettlement-passport-preprod/resources/sqs.tf
Added DLQ and standing queue (pre prod environment)
=> RP2-1003: DLQ and SQS on pre prod

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-intelligence-prod/resources/opensearch.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-prisoner-search-prod/resources/opensearch.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-probation-search-prod/resources/opensearch.tf, namespaces/live.cloud-platform.service.justice.gov.uk/peoplefinder-production/resources/opensearch.tf, namespaces/live.cloud-platform.service.justice.gov.uk/prisoner-content-hub-production/resources/opensearch.tf
https://github.com/ministryofjustice/cloud-platform-terraform-opensearch/releases/tag/1.5.0
Closes: https://github.com/ministryofjustice/cloud-platform/issues/5235
=> Bump opensearch module to 1.5.0 for prod ns

namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-ui-staging/resources/rds.tf
Upgrade the RDS instance type to t4g for `laa-court-data-ui-staging`
=> Upgrade rds instance type to t4 for laa-court-data-ui [Staging]

namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-github-repos-dev/resources/s3.tf, namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-github-repos-prod/resources/s3.tf
State lock tables and secrets created for both dev and prod environments.
=> Added State Lock Tables to Operations Engineering GitHub Repo Namespaces

namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-ui-production/resources/rds.tf
Upgrade the RDS instance type to `t4g.micro` for `laa-court-data-ui-prod`
=> laa-court-data-ui Upgrade RDS instance type [PRODUCTION]

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-equinity-historical-data-uat/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-equinity-historical-data-uat/resources/variables.tf
EMP-73: Change support email to laa-eq-data-migration-team, was laa-crime-apps
=> EMP-73: Change support email to laa-eq-data-migration-team

.checksum, namespaces/live.cloud-platform.service.justice.gov.uk/folarin-test/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/folarin-test/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/folarin-test/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/folarin-test/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/folarin-test/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/folarin-test/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/folarin-test/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/folarin-test/resources/versions.tf
Hi team,
Can I get a review of this PR. It's a test deployments of an hello world app.
=> an hello world app

namespaces/live.cloud-platform.service.justice.gov.uk/send-legal-mail-to-prisons-prod/resources/rds.tf
SLM-338 - update DB version to 15.5 for send-legal-mail-to-prisons-prod namespace.
=> SLM-338 - update DB version to 15.5 for send-legal-mail-to-prisons-prod namespace.

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-equinity-historical-data-staging/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-equinity-historical-data-staging/resources/variables.tf
EMP-71: Change support email to laa-eq-data-migration-team, was laa-crime-apps
=> EMP-71: Change support email to laa-eq-data-migration-team

.checksum, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-data-platform-new-app-runthrough-dev/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-data-platform-new-app-runthrough-dev/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-data-platform-new-app-runthrough-dev/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-data-platform-new-app-runthrough-dev/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-data-platform-new-app-runthrough-dev/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-data-platform-new-app-runthrough-dev/resources/ecr.tf, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-data-platform-new-app-runthrough-dev/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-data-platform-new-app-runthrough-dev/resources/serviceaccount.tf, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-data-platform-new-app-runthrough-dev/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-data-platform-new-app-runthrough-dev/resources/versions.tf
This PR creates the Cloud Platform Namespace, ECR repo, and service accounts required for us to test the new user flow for app registration.
=> Adding a new app to test user flow

namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-data-platform-new-app-runthrough-dev/resources/ecr.tf, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-data-platform-new-app-runthrough-dev/resources/serviceaccount.tf
This PR fixes a bad github URL preventing deployment
=> Fixing bad references to our github repo

namespaces/live.cloud-platform.service.justice.gov.uk/tariq-test/resources/rds-mysql.tf
Adding the RDS module for mysql to namespace tariq-test
=> adding RDS module for mysql engine

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-education-and-work-plan-dev/resources/irsa.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-education-and-work-plan-dev/resources/rds-postgresql.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-education-and-work-plan-dev/resources/variables.tf
- Adds RDS parameters to enable replication (requires DB reboot).
- Adds RDS policy to service account.
- Adds security group for CP MP ingress
=> RR-593: Adds config to enable RDS replication for DPR

namespaces/live.cloud-platform.service.justice.gov.uk/folarin-test/resources/ecr.tf, namespaces/live.cloud-platform.service.justice.gov.uk/folarin-test/resources/serviceaccount.tf
Created a repo in the org's repo. added it to both ecr.tf and serviceaccount.tf
=> Folarin sa fix

namespaces/live.cloud-platform.service.justice.gov.uk/prison-visits-booking-dev/resources/rds.tf
PVB Dev
update database version
also standardise formatting for the rds file
=> VB-3379, PVB Dev, update database version (and fix formatting)

namespaces/live.cloud-platform.service.justice.gov.uk/prison-visits-booking-staging/resources/rds-prison-visits.tf
PVB Staging
update database version
also standardise formatting for the rds file
=> VB-3379, PVB Staging, update databse version (and fix formatting)

namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-test-production/resources/submitter.tf, namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-test-production/resources/user-datastore.tf
- Removed prepare_for_major_upgrade flags as RDS upgrade is complete
- Removed pipeline skip
=> Cleanup formbuilder-platform-test-production

namespaces/live.cloud-platform.service.justice.gov.uk/prison-visits-booking-staging/resources/rds-prison-visits.tf
return `prepare_for_major_upgrade` to false after db upgrade
Prison Visits Booking - Staging
=> VB-3379, PVB - staging, false after db upgrade

namespaces/live.cloud-platform.service.justice.gov.uk/prison-visits-booking-dev/resources/rds.tf
return `prepare_for_major_upgrade` to false after db upgrade
Prison Visits Booking - Dev
=> VB-3379, PVB - Dev, false after db upgrade

namespaces/live.cloud-platform.service.justice.gov.uk/prison-visits-booking-staging/resources/rds-prison-visits.tf
Prision Visits Booking - Staging
Perform second DB Upgrade
=> VB-3379, PVB Staging, second DB upgrade

namespaces/live.cloud-platform.service.justice.gov.uk/prison-visits-booking-staging/resources/rds-prison-visits.tf
Set `prepare_for_major_upgrade` back to false now DB upgrade have completed
Prison Visits Booking staging
=> VB-3379, PVB Staging, remove upgrade flag

namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-data-platform-new-app-runthrough-dev/resources/ecr.tf
Add github env settings to ECR config
=> Add github env settings to ECR config

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-equinity-historical-data-prod/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-equinity-historical-data-prod/resources/variables.tf
EMP-72: Change support email to laa-eq-data-migration-team, was laa-crime-apps
=> EMP-72: Change support email to laa-eq-data-migration-team

namespaces/live.cloud-platform.service.justice.gov.uk/money-to-prisoners-prod/resources/rds.tf
=> MTP-1980: Upgrade MTP `prod` PostgreSQL to `15.5`

namespaces/live.cloud-platform.service.justice.gov.uk/money-to-prisoners-prod/resources/rds.tf
=> MTP-1980: Set `prepare_for_major_upgrade` to `false`

namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-saas-live/resources/editor.tf, namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-saas-live/resources/metadata_api.tf
Upgrades RDS to 15.5 - awaiting scheduled maintenance window as this is a prod environment
=> Upgrade RDS version formbuilder-saas-live

namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-live-production/resources/submitter.tf, namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-live-production/resources/user-datastore.tf
Upgrade RDS version to 15.5 - awaiting scheduled maintenance window
=> Upgrade RDS version formbuilder-platform-live-prod

namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-live-dev/resources/submitter.tf, namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-live-dev/resources/user-datastore.tf
Update RDS version to 15.5 - awaiting scheduled maintenance window
=> Upgrade RDS version formbuilder-platform-live-dev

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-education-and-work-plan-prod/resources/pingdom.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-education-and-work-plan-prod/resources/versions.tf
Pingdom setup for the education and work plan production environment.
=> RR-635: Config Pingdom for education and work plan

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-education-and-work-plan-prod/resources/pingdom.tf
I wrongly assumed API URL took same format as UI URL.
Correcting to, learningandworkprogress-api.hmpps.service.justice.gov.uk
=> RR-635: Correcting API URL

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-education-and-work-plan-dev/resources/rds-postgresql.tf
=> RR-637 - Minor formatting

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-prisoner-to-nomis-update-dev/resources/irsa.tf
=> SDIT-1498 Locations CP to-nomis queues

.checksum, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-hmpps-electronic-monitoring-data-platform-api-dev/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-hmpps-electronic-monitoring-data-platform-api-dev/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-hmpps-electronic-monitoring-data-platform-api-dev/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-hmpps-electronic-monitoring-data-platform-api-dev/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-hmpps-electronic-monitoring-data-platform-api-dev/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-hmpps-electronic-monitoring-data-platform-api-dev/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-hmpps-electronic-monitoring-data-platform-api-dev/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-hmpps-electronic-monitoring-data-platform-api-dev/resources/versions.tf
Create namespace `data-platform-app-hmpps-electronic-monitoring-data-platform-api-dev`.
=> Create namespace for EM data platform API app.

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-person-record-dev/resources/serviceaccount-scheduled-downtime.tf
Following https://github.com/ministryofjustice/hmpps-helm-charts/blob/main/charts/generic-service/README.md#scheduled-downtime
=> CPR-142 create serviceaccount for scheduled downtime

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-person-record-dev/resources/rds.tf
as per https://github.com/ministryofjustice/hmpps-helm-charts/blob/main/charts/generic-service/README.md#scheduled-downtime
=> CPR-142 stop RDS overnight in dev

namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-r53-backup-prod/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-r53-backup-prod/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-r53-backup-prod/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-r53-backup-prod/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-r53-backup-prod/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-r53-backup-prod/resources/gha_oidc.tf, namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-r53-backup-prod/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-r53-backup-prod/resources/s3.tf, namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-r53-backup-prod/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-r53-backup-prod/resources/versions.tf
- Namespace created.
- Role for github runner to assume and interact with state infrastructure.
- S3 and DynamoDB state management infrastructure.
=> operations-engineering-r53-backup-prod namespace and terraform resources for state management

namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-dev/01-rbac.yaml
To allow data creation via SNS/SQS via a service pod, to support end-to-end testing.
=> PI-1906 Grant RBAC access to probation-integration team (dev)

namespaces/live.cloud-platform.service.justice.gov.uk/laa-claim-non-standard-magistrate-fee-uat/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-claim-non-standard-magistrate-fee-uat/resources/serviceaccount.tf
- Update ServiceAccount
- Update Namespace Refs
=> Update UAT Provider App Repo Name

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-application-store-dev/resources/ecr.tf
=> Update Dev Reference to Repo App Store

namespaces/live.cloud-platform.service.justice.gov.uk/laa-claim-non-standard-magistrate-fee-dev-crm4/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-claim-non-standard-magistrate-fee-dev-crm4/resources/serviceaccount.tf
Update Namespace
Update ServiceAccount
=> Update Dev CRM4 Repo Names Provider App

namespaces/live.cloud-platform.service.justice.gov.uk/laa-claim-non-standard-magistrate-fee-prod/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-claim-non-standard-magistrate-fee-prod/resources/serviceaccount.tf
Update ECR
Update ServiceAccount
=> Update Repo Name Production Provider App

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-portfolio-management-dev/resources/rds.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-portfolio-management-dev/resources/versions.tf
POC for investigating the feasibility of moving monitoring config for rds to cloud platform. added the helm release for the generic-prometheus-alerts chart as a terraform’d resource
=> Heat 213 dev

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-portfolio-management-dev/resources/rds.tf
Passing mandatory params for prometheus alerts
=> HEAT-213-hmpps-portfolio-management-dev

namespaces/live.cloud-platform.service.justice.gov.uk/justice-gov-uk-dev/resources/s3.tf
Use custom branch with additional bucket permissions.
Related to issue: https://github.com/ministryofjustice/cloud-platform/issues/5308
cc: @wilson1000-MoJ
=> S3 for justice-gov-uk-dev. 

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-adjustments-prod/resources/elasticache.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-adjustments-prod/resources/rds.tf
Reverts ministryofjustice/cloud-platform-environments#21197
=> ADJUST1-423 adding resources back to prod.

namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-report-service-dev/resources/secret.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-report-service-dev/resources/variables.tf
Adding the secrets to hold the maat details.
=> DCES-185- Add Secrets to Report Dev

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-one-plan-dev/06-certificate.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-one-plan-dev/resources/elasticache.tf
* drop hmpps from cert urls for hmpps-one-plan-dev
=> Add redis cluster for hmpps-one-plan-dev

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-accredited-programmes-dev/resources/audit-queue.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-accredited-programmes-dev/resources/irsa.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-accredited-programmes-dev/resources/variables.tf
https://trello.com/c/uGP2zutK/1360-create-sqs-queue-for-writing-audit-records-in-dev
Write audit messages to sqs queue
=> 1350 - Create sqs queue for writing audit messages in dev

namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-report-service-prod/resources/secret.tf
=> DCES-185 Add AWS Secrets to Report Prod

namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-report-service-uat/resources/secret.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-report-service-uat/resources/variables.tf
=> DCES-185 Add AWS Secrets to Report UAT

namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-prod/resources/certificates.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-prod/resources/newfuturesnetwork-route53.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-prod/resources/pingdom.tf
ALso remove old A records so new a records can be generated
=> Add newfuturesnetwork certs and pingdom

namespaces/live.cloud-platform.service.justice.gov.uk/cfe-civil-staging/resources/rds.tf
Upgrade DB to version with support date after end of March 2024
=> CFE-Civil STG upgrade postgres DB

namespaces/live.cloud-platform.service.justice.gov.uk/cfe-civil-staging/resources/rds.tf
downgrading postgres to 14 so I can upgrade to 14.10 again and run some tests against the service while the change is being applied in the concourse pipeline
=> CFE Civil STG downgrade DB to test:

namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-report-service-staging/resources/secret.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-report-service-staging/resources/variables.tf
Adding AWS secrets to Staging.
=> DCES-185 Add AWS Secrets to Report Staging

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-afer-prototype/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-afer-prototype/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-afer-prototype/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-afer-prototype/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-afer-prototype/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-afer-prototype/resources/basic-auth.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-afer-prototype/resources/ecr.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-afer-prototype/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-afer-prototype/resources/serviceaccount.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-afer-prototype/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-afer-prototype/resources/versions.tf
Creating a new prototype to be published.
=> Added hmpps-afer-prototype prototype

namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-dev/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-dev/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-dev/resources/variables.tf
Cleaning up to reference the dces team.
=> DCES-DRC-Integration-Dev-Team

namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-uat/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-uat/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-uat/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-uat/resources/variables.tf
Cleaning up to reference the dces team.
=> DCES-DRC-Integration-UAT-Team

namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-staging/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-staging/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-staging/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-staging/resources/variables.tf
Cleaning up to reference the dces team.
=> DCES-DRC-Integration-Staging-Team

namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-prod/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-prod/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-prod/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-prod/resources/variables.tf
Cleaning up to reference the dces team.
=> DCES-DRC-Integration-Prod-Team

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-accredited-programmes-prod/resources/irsa.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-accredited-programmes-prod/resources/variables.tf
https://trello.com/c/uGP2zutK/1360-create-sqs-queue-for-writing-audit-records
=> 1360 Create audit queue for accredited-programmes-api prod

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-accredited-programmes-preprod/resources/irsa.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-accredited-programmes-preprod/resources/variables.tf
https://trello.com/c/uGP2zutK/1360-create-sqs-queue-for-writing-audit-records
=> 1360 Create audit queue for accredited-programmes-api preprod

namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-find-moj-data-dev/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-find-moj-data-dev/resources/ecr.tf, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-find-moj-data-dev/resources/serviceaccount.tf
Both have been renamed to data-catalogue
=> Update references to github repos and slack

namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-dev/resources/rds-postgresql.tf
adding Postgres.tf to dces dev
=> dces-postgres-dev

namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-uat/cronjob-cleardown.yaml
Modifed the cica application cleardown cronjob SQL statement
=> Modify cica application cleardown cronjob SQL statement

namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-datahub-catalogue-dev/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-datahub-catalogue-dev/resources/ecr.tf, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-datahub-catalogue-dev/resources/serviceaccount.tf, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-datahub-catalogue-dev/resources/variables.tf
update datahub-catalogue-dev ns references
- dev env in repo
- rename team
=> update datahub-catalogue-dev namespace references

namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-dev/resources/serviceaccount.tf
Prepare a case for sentence uses horizontalpodautoscalers. Following the example from #hmpps-dev channel.
=> PIC-3662 - Add a custom rbac for horizontalpodautoscalers [Dev]

namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-preprod/resources/serviceaccount.tf
Prepare a case for sentence uses horizontalpodautoscalers. Following the example from #hmpps-dev channel.
=> PIC-3662 - Add a custom rbac for horizontalpodautoscalers [PreProd]

namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-prod/resources/serviceaccount.tf
Prepare a case for sentence uses horizontalpodautoscalers. Following the example from #hmpps-dev channel.
=> PIC-3662 - Add a custom rbac for horizontalpodautoscalers [Prod]

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-workload-prod/resources/rds-history.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-workload-prod/resources/rds-live.tf
Reverts ministryofjustice/cloud-platform-environments#21402
=> Revert "Update the version of postgres to 15.5 for hmpps-workload PROD"

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-staff-prod/resources/rds-postgresql.tf
Reverts ministryofjustice/cloud-platform-environments#21415
=> Revert "Update the version of postgres to 15.5 for hmpps-staff PROD"

namespaces/live.cloud-platform.service.justice.gov.uk/workforce-management-prod/resources/rds-allocation.tf
Reverts ministryofjustice/cloud-platform-environments#21417
=> Revert "Update the version of postgres to 15.5 for workforce-management PROD"

namespaces/live.cloud-platform.service.justice.gov.uk/contact-moj-development/resources/rds.tf
Upgrade to PostgreSQL 14 failed because the current version is not allowed to upgrade. Need to do a minor version upgrade first
=> Upgrade contact-moj-development DB to latest minor version

namespaces/live.cloud-platform.service.justice.gov.uk/contact-moj-development/resources/rds.tf
Previous upgrades have failed, so restoring back to the original version
=> Revert contact-moj-development to PostgreSQL 12.11

namespaces/live.cloud-platform.service.justice.gov.uk/contact-moj-production/resources/service-account-github.tf, namespaces/live.cloud-platform.service.justice.gov.uk/contact-moj-production/resources/serviceaccount-circleci.tf
https://github.com/ministryofjustice/cloud-platform-environments/pull/20395 is failing to apply. Adding a role name so a second service account can be added.
=> Allow for 2 service accounts by adding role name

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-one-plan-dev/resources/irsa.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-one-plan-dev/resources/variables.tf
With access to hmpps-audit_queue
=> Add service account to one plan dev

namespaces/live.cloud-platform.service.justice.gov.uk/intranet-staging/00-namespace.yml, namespaces/live.cloud-platform.service.justice.gov.uk/intranet-staging/01-rbac.yml, namespaces/live.cloud-platform.service.justice.gov.uk/intranet-staging/02-limit-range.yml, namespaces/live.cloud-platform.service.justice.gov.uk/intranet-staging/03-resource-quota.yml, namespaces/live.cloud-platform.service.justice.gov.uk/intranet-staging/04-network-policy.yml, namespaces/live.cloud-platform.service.justice.gov.uk/intranet-staging/05-prometheus.yml, namespaces/live.cloud-platform.service.justice.gov.uk/intranet-staging/resources/cloudfront.tf, namespaces/live.cloud-platform.service.justice.gov.uk/intranet-staging/resources/irsa.tf, namespaces/live.cloud-platform.service.justice.gov.uk/intranet-staging/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/intranet-staging/resources/rds.tf, namespaces/live.cloud-platform.service.justice.gov.uk/intranet-staging/resources/s3.tf, namespaces/live.cloud-platform.service.justice.gov.uk/intranet-staging/resources/service-account.tf, namespaces/live.cloud-platform.service.justice.gov.uk/intranet-staging/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/intranet-staging/resources/versions.tf
A new staging environment for: intranet.justice.gov.uk
=> Init new namespace - Intranet Staging

namespaces/live.cloud-platform.service.justice.gov.uk/intranet-production/00-namespace.yml, namespaces/live.cloud-platform.service.justice.gov.uk/intranet-production/01-rbac.yml, namespaces/live.cloud-platform.service.justice.gov.uk/intranet-production/02-limit-range.yml, namespaces/live.cloud-platform.service.justice.gov.uk/intranet-production/03-resource-quota.yml, namespaces/live.cloud-platform.service.justice.gov.uk/intranet-production/04-network-policy.yml, namespaces/live.cloud-platform.service.justice.gov.uk/intranet-production/05-prometheus.yml, namespaces/live.cloud-platform.service.justice.gov.uk/intranet-production/resources/cloudfront.tf, namespaces/live.cloud-platform.service.justice.gov.uk/intranet-production/resources/ecr.tf, namespaces/live.cloud-platform.service.justice.gov.uk/intranet-production/resources/irsa.tf, namespaces/live.cloud-platform.service.justice.gov.uk/intranet-production/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/intranet-production/resources/rds.tf, namespaces/live.cloud-platform.service.justice.gov.uk/intranet-production/resources/s3.tf, namespaces/live.cloud-platform.service.justice.gov.uk/intranet-production/resources/service-account.tf, namespaces/live.cloud-platform.service.justice.gov.uk/intranet-production/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/intranet-production/resources/versions.tf
Creates a new namespace for the MoJ Intranet
=> Init new namespace - Intranet Production

namespaces/live.cloud-platform.service.justice.gov.uk/peoplefinder-production/resources/rds.tf
Apply is erroring, so changing to current version.
=> Change to actual current version of DB - peoplefinder-production

.checksum, namespaces/live.cloud-platform.service.justice.gov.uk/laa-sds-dev/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-sds-dev/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-sds-dev/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-sds-dev/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-sds-dev/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-sds-dev/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-sds-dev/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-sds-dev/resources/versions.tf
This is our starting point for getting our secure document storage solution on to the cloud platform.
=> SDS Dev Environment Setup.

.checksum, namespaces/live.cloud-platform.service.justice.gov.uk/laa-sds-test/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-sds-test/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-sds-test/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-sds-test/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-sds-test/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-sds-test/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-sds-test/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-sds-test/resources/versions.tf
Setting this environment up as our test env
=> SDS Setting up test environment

.checksum, namespaces/live.cloud-platform.service.justice.gov.uk/laa-sds-stg/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-sds-stg/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-sds-stg/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-sds-stg/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-sds-stg/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-sds-stg/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-sds-stg/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-sds-stg/resources/versions.tf
Part of our 4 environment process dev test staging and prodSDS Staging environment
=> SDS Staging environment

namespaces/live.cloud-platform.service.justice.gov.uk/track-a-query-development/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/track-a-query-development/resources/rds.tf
Also re-adds rbac file which was accidentally removed.
=> Upgrade DB track-a-query-development

namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-staging/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-staging/11-certificate.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-staging/resources/rds.tf
=> VB-3433 Setup server - One login user registry staging

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-education-and-work-plan-dev/resources/serviceaccount-circleci.tf
This PR correct the circle sa in `hmpps-education-and-work-plan-dev` so that it uses the tf module, and is consistent with out `preprod` and `prod` environments
=> RR-623 - Correct the circle sa in hmpps-education-and-work-plan-dev

namespaces/live.cloud-platform.service.justice.gov.uk/track-a-query-production/01-rbac.yaml
Appears to have been removed accidentally
=> Re-add rbac file

namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-preprod/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-preprod/11-certificate.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-preprod/resources/rds.tf
new One login user registry preprod preprod service
=> VB-3433 Setup server - One login user registry preprod

namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-live-production/resources/service_accounts.tf
Using different names to avoid clash, will get renamed later on once the old SA are deleted.
=> Add new TF service accounts (live-production)

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-one-plan-prod/06-certificate.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-one-plan-prod/resources/irsa.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-one-plan-prod/resources/variables.tf
* Add service account in hmpps-one-plan-prod with access to hmpps-audit-prod sqs queue
* Fix domain on certificate
=> One plan prod audit queue access

namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-services-test-dev/resources/serviceaccount.tf
reference the service account that needs access
=> Move the role binding to the target namespace

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-one-plan-prod/06-certificate.yaml
=> Fix dns name on cert for one-plan-api-prod ns

namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-dev/resources/rds.tf
name incorrect have change it to 
variable "application" {
description = "Name of Application you are deploying"
default     = "visit-someone-in-prison"
}
=> VB-3433 Setup server - rds application

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-wmt-workload-poc-dev/resources/rds-postgresql.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-wmt-workload-poc-dev/resources/variables.tf
Added RDS Configuration to allow DPS Reporting to run federated queries on the DB.
This is to PoC a custom reporting solution leveraging the DPR Redshift.
=> WMT Alpha - Adding DPS Reporting RDS configuration

namespaces/live.cloud-platform.service.justice.gov.uk/laa-sds-dev/resources/serviceaccount.tf
Creating service account for the dev environment
=> laa-sds Creating service account in dev workspace

namespaces/live.cloud-platform.service.justice.gov.uk/aaf-dev/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/aaf-dev/resources/ecr.tf, namespaces/live.cloud-platform.service.justice.gov.uk/aaf-dev/resources/serviceaccount.tf
=> added ecr and service account

namespaces/live.cloud-platform.service.justice.gov.uk/pathfinder-dev/resources/serviceaccount-refreshclamav.tf
add refresh clamav service account
=> SI-768-add-refresh-clamav-service-account-dev

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-education-employment-dev/resources/rds.tf
Turn off major upgrade version
=> ESWE - Upgrade database, disable major upgrade - dev

namespaces/live.cloud-platform.service.justice.gov.uk/pathfinder-preprod/resources/serviceaccount-refreshclamav.tf
add refresh clamav service account
=> SI-768-add-refresh-clamav-service-account-preprod

namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-data-migration-dev/resources/variables.tf
correcting the application variable
=> laa-dces-dm-correcting-application

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-candidate-matching-dev/resources/rds.tf
=> ESWE - Candidate Matching Database - Dev

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-candidate-matching-preprod/resources/rds.tf
=> ESWE - Candidate Matching Database - PreProd

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-candidate-matching-dev/resources/rds.tf
=> ESWE - Database Upgrade - Dev

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-candidate-matching-preprod/resources/rds.tf
=> ESWE - Database Upgrade - PreProd

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-candidate-matching-prod/resources/rds.tf
=> ESWE - Database Upgrade - Prod

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-education-employment-dev/resources/rds.tf
=> ESWE - Upgrade database - Dev

namespaces/live.cloud-platform.service.justice.gov.uk/pathfinder-prod/resources/serviceaccount-refreshclamav.tf
add refresh clamav service account
=> SI-768-add-refresh-clamav-service-account-prod

namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-live-production/resources/service_accounts.tf
To be merged when we remove/rename the existing accounts so the apply pipeline doesn't clash
=> Update service account names in platform-live-production

namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-datahub-catalogue-test/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-datahub-catalogue-test/resources/ecr.tf, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-datahub-catalogue-test/resources/serviceaccount.tf
Corresponding PR to move the deployment workflow: https://github.com/ministryofjustice/data-catalogue/pull/4
=> Move datahub test to public repo

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-education-employment-preprod/resources/rds.tf
=> ESWE - Database Upgrade Final - PreProd

namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-data-migration-dev/resources/rds-postgresql.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-data-migration-dev/resources/variables.tf
changes to update database name
=> law-dces-data-migration-dev-db-name-change

namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-data-migration-dev/resources/variables.tf
making db name with alpha numeric and underscores only
=> laa-dces-dm-db-name

namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-datahub-catalogue-preprod/resources/irsa.tf
This seems to be conflicting with the terraform for dev
=> Fix datahub preprod build

namespaces/live.cloud-platform.service.justice.gov.uk/manage-soc-cases-dev/resources/serviceaccount-refreshclamav.tf
SI-768-add-refresh-clamav-service-account-soc-dev
=> SI-768-add-refresh-clamav-service-account-soc-dev

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-education-employment-prod/resources/rds.tf
=> ESWE - Database Upgrade to 16.2 - Prod

namespaces/live.cloud-platform.service.justice.gov.uk/manage-soc-cases-prod/resources/serviceaccount-refreshclamav.tf
SI-768-add-refresh-clamav-service-account-soc-prod
=> SI-768-add-refresh-clamav-service-account-soc-prod

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-education-employment-prod/resources/rds.tf
=> ESWE - Database Upgrade Final - Prod

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-temporary-accommodation-services-prototype/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-temporary-accommodation-services-prototype/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-temporary-accommodation-services-prototype/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-temporary-accommodation-services-prototype/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-temporary-accommodation-services-prototype/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-temporary-accommodation-services-prototype/resources/basic-auth.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-temporary-accommodation-services-prototype/resources/ecr.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-temporary-accommodation-services-prototype/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-temporary-accommodation-services-prototype/resources/serviceaccount.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-temporary-accommodation-services-prototype/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-temporary-accommodation-services-prototype/resources/versions.tf
Creating namespace for Community Accommodation Services prototype.
=> Added hmpps-temporary-accomodation-services-prototype prototype

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-equinity-historical-data-prod/resources/rds-mssql-achive.tf
EMP-179: Adding RDS for Archive to PROD namespace
=> EMP-179: Adding RDS for Archive to PROD namespace

namespaces/live.cloud-platform.service.justice.gov.uk/cjse-dev/resources/irsa.tf, namespaces/live.cloud-platform.service.justice.gov.uk/cjse-dev/resources/unprocessed_documents_and_events_sqs.tf
- Created one SQS and one DL Queue
- Created queue secrets containing queue url, id and name
- Created a service pod for connecting with sqs 
- Created a service account / IRSA
=> CJS-56 Create Unprocessed documents and events SQS standard queue

namespaces/live.cloud-platform.service.justice.gov.uk/cjse-dev/resources/unprocessed_documents_and_events_sqs.tf
=> CJS-56 Created Unprocessed documents and events SQS queue

namespaces/live.cloud-platform.service.justice.gov.uk/laa-sds-test/resources/ecr.tf
=> laa-sds test environment prefix for github

namespaces/live.cloud-platform.service.justice.gov.uk/intranet-dev/resources/opensearch.tf
The MoJ Intranet depends on OpenSearch
=> Add OpenSearch module

namespaces/live.cloud-platform.service.justice.gov.uk/intranet-dev/resources/irsa.tf
=> CDPT-1240: Set up service pod

.checksum, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-litigator-fees-dev/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-litigator-fees-dev/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-litigator-fees-dev/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-litigator-fees-dev/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-litigator-fees-dev/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-litigator-fees-dev/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-litigator-fees-dev/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-litigator-fees-dev/resources/versions.tf
Create namespace for Crown Court Litigator Fees Dev
=> Create namespace for Crown Court Litigator Fees Dev

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-jobs-board-prod/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-jobs-board-prod/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-jobs-board-prod/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-jobs-board-prod/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-jobs-board-prod/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-jobs-board-prod/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-jobs-board-prod/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-jobs-board-prod/resources/versions.tf
Create namespace - hmpps-jobs-board-prod
=> ESWE-810 - Jobs Board - Prod

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-jobs-board-dev/01-rbac.yaml
=> ESWE-810 - Jobs Board - Dev

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-jobs-board-preprod/01-rbac.yaml
=> ESWE-810 - Jobs Board - PreProd

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-equinity-historical-data-uat/resources/main.tf
EMP-181: Adding Guthub team to main resources AWS with the intention to add AWS secrets later on
=> EMP-181: Adding Guthub team to main resources AWS

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-equinity-historical-data-uat/resources/secret.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-equinity-historical-data-uat/resources/variables.tf
EMP-181: Adding CP secret using AWS UAT
=> EMP-181: Adding CP secret using AWS UAT

namespaces/live.cloud-platform.service.justice.gov.uk/laa-submit-crime-forms-dev/03-resourcequota.yaml
To 100 to account for branch builder and dependabot PRs
=> Update Provider Dev Pod Limit

namespaces/live.cloud-platform.service.justice.gov.uk/money-to-prisoners-prod/resources/route53.tf
Ref: [mtp-deploy@19086b0](https://github.com/ministryofjustice/money-to-prisoners-deploy/commit/19086b007604a1bb6f2adc07c8ac6b34502fde19)
=> MTP-1994: Add reject DMARC records to all `money-to-prisoners-prod` custom domains

namespaces/live.cloud-platform.service.justice.gov.uk/money-to-prisoners-prod/resources/route53.tf
Stupidly missed in #22077!
Ref [mtp-deploy@43752ff](https://github.com/ministryofjustice/money-to-prisoners-deploy/commit/43752ffbc4d5fbfc219fb3bb919807d771709406)
=> MTP-1994: Add reject DMARC record to `money-to-prisoners-prod` custom domain / zone

namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-dev/resources/variables.tf
Upgrade database to latest minor version to mitigate a CVE https://www.postgresql.org/support/security/CVE-2023-5869/
=> Court Probation Dev - Upgrade database to latest minor version

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-equinity-historical-data-prod/resources/secret.tf
EMP-181: Adding AWS OAuth secrets to AWS Secret Manager PROD
=> EMP-181: Adding AWS OAuth secrets to AWS Secret Manager PROD

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-jobs-board-preprod/resources/elasticache.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-jobs-board-preprod/resources/variables.tf
=> ESWE-810 Jobs Board - PreProd

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-jobs-board-prod/resources/elasticache.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-jobs-board-prod/resources/variables.tf
=> ESWE-810 Jobs Board - Prod

namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-preprod/resources/rds.tf
Upgrade database to latest minor version to mitigate CVE-2023-5869
=> Court Probation PreProd - Upgrade database to latest minor version

namespaces/live.cloud-platform.service.justice.gov.uk/cfe-civil-uat/resources/ecr.tf
As discussed https://mojdt.slack.com/archives/C57UPMZLY/p1711528709380779?thread_ts=1711360332.704029&cid=C57UPMZLY
=> Fix rulePriority to be unique

namespaces/live.cloud-platform.service.justice.gov.uk/laa-fee-calculator-ui-dev/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-fee-calculator-ui-dev/resources/serviceaccount.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-fee-calculator-ui-dev/resources/variables.tf
Some configuration tweaks to point the Fee Calculator UI Dev namespace at the correct environment
=> Configuration tweaks: Fee Calculator UI Dev

namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-prod/resources/variables.tf
This comes with plenty of patches and security fixes. Also, aligns with the db versions of dev and preprod environments making sure we have Dev/preprod/prod parity
=> Court Case Prod - Upgrade database to latest minor version

namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-dev/resources/rds-pre-sentence-service.tf
Upgrade `pre-sentence-service-dev` database to latest minor version to mitigate a CVE https://www.postgresql.org/support/security/CVE-2023-5869/
=> pre-sentence-service-dev: Upgrade RDS minor version

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-user-preferences-dev/resources/rds.tf
Upgrade RDS db to latest minor version
=> hmpps-user-preferences-dev: Upgrade RDS db to latest minor version

namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-preprod/resources/rds-pre-sentence-service.tf
Upgrade database to latest minor version to mitigate a CVE https://www.postgresql.org/support/security/CVE-2023-5869/
for `pre-sentence-service` **PreProd**
=> pre-sentence-service-preprod: Upgrade RDS minor version

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-user-preferences-preprod/resources/rds.tf
Upgrade RDS minor version to `14.11`
=> hmpps-user-preferences-preprod: Upgrade RDS minor version

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-user-preferences-prod/resources/rds.tf
Upgrade RDS minor version for `hmpps-user-preferences` for **Prod**
=> hmpps-user-preferences-prod: Upgrade RDS minor version 

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-litigator-fees-dev/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-litigator-fees-dev/resources/ecr.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-litigator-fees-dev/resources/rds.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-litigator-fees-dev/resources/serviceaccount.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-litigator-fees-dev/resources/variables.tf
=> LAWS-3733: Infra for CCLF Dev

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-equinity-historical-data-prod/resources/iam.tf
EMP: Update S3 user policy to allow check bucker location
=> EMP: Update S3 user policy to allow check bucker location

namespaces/live.cloud-platform.service.justice.gov.uk/laa-fee-calculator-ui-dev/resources/serviceaccount.tf
Add serviceaccount_token_rotated_date variable to serviceaccount teraform template and set date to today to rotate tokens.
=> Rotate laa-fee-calculator-dev serviceaccount tokens

namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-datahub-catalogue-preprod/resources/opensearch.tf
- **increase OS cluster resources and ebs volume size**
- **empty commit**
=> increase OS resources datahub preprod

namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-datahub-catalogue-test/resources/opensearch.tf
- **increase OS cluster resources and ebs volume size**
- **empty commit**
=> increase OS resources datahub test

namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-civil/resources/ecr.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-civil/resources/serviceaccount.tf
Add additional repository to ecr and service account
=> Add assessment api to laa-ccms-civil

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-equinity-historical-data-prod/resources/iam.tf
=> Updated permission for s3

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-dev/resources/rds_postgres.tf
We are currently in the process of creating a Postgres Database to temporarily store hmpps-related events. Once a table is initialised within Postgres, it will be used by both the event notifier and the event handler.
=> Setting up new RDS service for our new Postgres database (DEV).

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-person-record-preprod/resources/cpr-delius-offender-events-queue.tf
. Removed probation case merge/unmerge even types.
. Added prisoner created/updated event type.
=> CPR-57-preprod

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-person-record-dev/resources/cpr-delius-offender-events-queue.tf
. Removed probation case merge/unmerge event types.
. Added prisoner-created/updated event type.
=> CPR-57-dev

namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-dev/resources/rds.tf
We are currently testing our DR process and recording the steps involved in rolling back to a snapshot.
1. Snapshot of Dev RDS has been taken
2. Change has been made to site that would have affected the DB
3. Raising PR now with snapshot showing in rds.tf file
=> RDS DR Test - Hale Dev

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-equinity-historical-data-prod/resources/iam.tf
EMP-198: Add new permission ListObjectsV2 to S3 Bucket in PROD
=> EMP-198: Add new permission ListObjectsV2 to S3 Bucket in PROD

namespaces/live.cloud-platform.service.justice.gov.uk/cjse-dev/resources/irsa.tf, namespaces/live.cloud-platform.service.justice.gov.uk/cjse-dev/resources/rds-mssql.tf
- Bumping up version to 2022
- Removing replica instance
=> CJS-54 Addressing an apply error - DBParameterGroupAlreadyExists

namespaces/live.cloud-platform.service.justice.gov.uk/cjse-dev/resources/rds-mssql.tf
- Changing RDS MSSQL to web edition
- Ensuring the version is 2022
=> CJS-54 Changing RDS MSSQL to webedition

namespaces/live.cloud-platform.service.justice.gov.uk/cica-extraction-dev/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/cica-extraction-dev/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/cica-extraction-dev/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/cica-extraction-dev/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/cica-extraction-dev/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/cica-extraction-dev/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/cica-extraction-dev/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/cica-extraction-dev/resources/versions.tf
Hi,
We are looking to create a name space for the cica case extraction app.
This app would make API calls to Bedrock in MP.
Kindly let m know if you have any questions or clarification.
Thanks
=> Add cica-extraction-dev namespace

namespaces/live.cloud-platform.service.justice.gov.uk/cjse-dev/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/cjse-dev/resources/serviceaccount.tf
The following repos are added to the service account and namespace:
- moj-cjse-xhibit-ingestion-api
- moj-cjse-xhibit-subscription-api
- moj-cjse-xhibit-notification-api
- moj-cjse-xhibit-ingestion-processor
=> CJS-210 Added git repos to namespace and service account

namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-dev/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-dev/11-certificate.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-dev/resources/rds.tf
VSIP - VB-3717 - update RDS DB name, GitHub project and certs from hmpps-one-login-user-registry to hmpps-prison-visit-booker-registry
=> VSIP - VB-3717 - update RDS DB name, GitHub project and certs to hmpps-prison-visit-booker-registry

.checksum, namespaces/live.cloud-platform.service.justice.gov.uk/opg-actor-search-dev/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/opg-actor-search-dev/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/opg-actor-search-dev/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/opg-actor-search-dev/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/opg-actor-search-dev/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/opg-actor-search-dev/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/opg-actor-search-dev/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/opg-actor-search-dev/resources/versions.tf
Creating a environment for a namespace as a step towards deploying a dash app using the new webapp deployment tool
=> Create namespace for new-env-opg-actor-search

namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-staging/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-staging/11-certificate.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-staging/resources/rds.tf
VSIP - VB-3717 - update RDS DB name, GitHub project and certs from hmpps-one-login-user-registry to hmpps-prison-visit-booker-registry - staging env
=> VSIP - VB-3717 - update RDS DB name, GitHub project and certs to hmpps-prison-visit-booker-registry - staging env

namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-preprod/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-preprod/11-certificate.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-preprod/resources/rds.tf
VSIP - VB-3717 - update RDS DB name, GitHub project and certs from hmpps-one-login-user-registry to hmpps-prison-visit-booker-registry - preprod env
=> VSIP - VB-3717 - update RDS DB name, GitHub project and certs to hmpps-prison-visit-booker-registry - preprod env

namespaces/live.cloud-platform.service.justice.gov.uk/calculate-release-dates-api-dev/06-certificate.yaml
add an alternative dns for the alternative CRDS system (to r…un in a different configuration)
=> CRS-1883 Alternative DNS

namespaces/live.cloud-platform.service.justice.gov.uk/calculate-release-dates-dev/06-certificate.yaml
for the alternative CRDS system (to run in a different configuration)
=> CRS-1883 add an alternative dns

namespaces/live.cloud-platform.service.justice.gov.uk/intranet-dev/resources/acm.tf
aws_acm_certificate_validation, increase timeout and add depends_on
=> Draft/WIP: intranet-dev. Add certificates for CloudFront aliases. 

namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-dev/cronjob-cleardown.yaml
Modify cica dev environment application cleardown cronjob SQL statement
=> Modify cica dev environment application cleardown cronjob SQL statement

namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-demo/resources/irsa.tf
Updating the IRSA role for hale-demo with RDS permissions
=> Hale-Demo Updated IRSA role with RDS

namespaces/live.cloud-platform.service.justice.gov.uk/prison-visits-booking-production/resources/rds-prison-visits.tf
PVB Production
First stage database upgrade (will be merging after hours)
12.11 -> 14.4
also changed variable order - to match the two other RDS files in this namespace
=> VB-3379, PVB - Prod - Database upgrade 1

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-prisoner-search-prod/resources/opensearch.tf
=> SDIT-1644 500 errors returned from prisoner search

namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-prod/resources/irsa.tf
Updating the IRSA role for hale-prod with RDS permissions
=> Hale-Prod: Updated IRSA role with RDS

namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-prod/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-prod/11-certificate.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-prod/resources/rds.tf
VSIP - VB-3717 - update RDS DB name, GitHub project and certs from hmpps-one-login-user-registry to hmpps-prison-visit-booker-registry - prod env
=> VSIP - VB-3717 - update RDS DB name, GitHub project and certs hmpps-prison-visit-booker-registry - prod

namespaces/live.cloud-platform.service.justice.gov.uk/prison-visits-booking-production/resources/rds-prison-visits.tf
Set flag `prepare_for_major_upgrade` - true
=> VB-3379, prepare for upgrade - true - PVB Prod

namespaces/live.cloud-platform.service.justice.gov.uk/laa-check-client-qualifies-production/resources/pingdom.tf
Pingdom integration with slack for CCQ/Refer team
=> Add pingdom slack integration #laa-fala-laalaa-alerts-production

.checksum, namespaces/live.cloud-platform.service.justice.gov.uk/mlops-deployment-example/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/mlops-deployment-example/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/mlops-deployment-example/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/mlops-deployment-example/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/mlops-deployment-example/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/mlops-deployment-example/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/mlops-deployment-example/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/mlops-deployment-example/resources/versions.tf
Testing MLOps deployment of a model via Flask
=> Create namespace for my-new-environment-mlops

namespaces/live.cloud-platform.service.justice.gov.uk/mlops-deployment-example/resources/ecr.tf, namespaces/live.cloud-platform.service.justice.gov.uk/mlops-deployment-example/resources/serviceaccount.tf
Adding a service account and ecr to the mlops-deployment-example namespace as per instructions in [AP user guide](https://user-guidance.analytical-platform.service.justice.gov.uk/apps/static-app.html#cloud-platform-environments)
=> adding service account and ecr

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-equinity-historical-data-prod/resources/s3.tf
EMP-198: Simplify bucket policy actions merged into 1 statement
=> EMP-198: Simplify bucket policy actions merged into 1 statement

namespaces/live.cloud-platform.service.justice.gov.uk/intranet-production/resources/route53.tf, namespaces/live.cloud-platform.service.justice.gov.uk/intranet-production/resources/variables.tf
Add draft DNS for review 😄 @EarthlingDavey 
CC @AntonyBishop @kyphutruong
=> intranet-production Intro DNS zone

namespaces/live.cloud-platform.service.justice.gov.uk/prison-visits-booking-production/resources/rds-prison-visits.tf
Prison Visits Booking - Production
Second database upgrade
Will be merged after hours again
=> VB-3379, PVB Production, second DB upgrade

namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-prod/resources/pingdom.tf
Added Hale Dev platform url for monitoring DB
=> Add Hale Pingdom URL

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-equinity-historical-data-prod/resources/s3.tf
EMP-184: reverting change until we know which policy to apply
=> EMP-184: reverting change until we know which policy to apply

namespaces/live.cloud-platform.service.justice.gov.uk/prison-visits-booking-production/resources/rds-prison-visits.tf
Remove pipeline skip file
Set `major_upgrade` back to false
All upgrades completed, this is just the cleanup PR
=> VB-3379, remove pipeline skip file, set major_upgrade to false

namespaces/live.cloud-platform.service.justice.gov.uk/laa-submit-crime-forms-prod/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-submit-crime-forms-prod/04-networkpolicy.yaml
Tickets
[Update network policies so that Provider application talks to datastore via Cloud Platform rather than via an external url](https://dsdmoj.atlassian.net/browse/CRM457-1288)
=> CRM457-1288: Production Provider Network Policy

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-a-video-link-dev/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-a-video-link-dev/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-a-video-link-dev/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-a-video-link-dev/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-a-video-link-dev/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-a-video-link-dev/06-certificate.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-a-video-link-dev/resources/elasticache.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-a-video-link-dev/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-a-video-link-dev/resources/rds-postgresql.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-a-video-link-dev/resources/serviceaccount.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-a-video-link-dev/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-a-video-link-dev/resources/versions.tf
This PR sets up a new development namespace for the re-platforming of the **book a video link** project.
There is another similar (older) namespace for **book a video link**.  However we will be replacing that one in due course.
=> BAVL-10 initial first commit for replatforming of the old book a video link to the new environment.

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-a-video-link-dev/00-namespace.yaml
Small change to the UI github repo name to match up with that of the bootstrap project [here](https://github.com/ministryofjustice/hmpps-project-bootstrap/pull/679)
=> BAVL-10 small change to the UI git repo name to include 'ui' in the name.

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-tier-2-prototype/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-tier-2-prototype/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-tier-2-prototype/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-tier-2-prototype/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-tier-2-prototype/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-tier-2-prototype/resources/basic-auth.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-tier-2-prototype/resources/ecr.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-tier-2-prototype/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-tier-2-prototype/resources/serviceaccount.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-tier-2-prototype/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-tier-2-prototype/resources/versions.tf
Prototype for the Community Accommodation Service Tier-2 prototype (CAS-2), created by dxw and handed over to MoJ colleagues.
=> Added hmpps-community-accommodation-tier-2-prototype prototype

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-dev/resources/irsa.tf
=> CCR dev policy arn update

namespaces/live.cloud-platform.service.justice.gov.uk/laa-sds-dev/resources/dynamodb.tf
We would like to use dynamo db for auditing requests on files
=> Adding dynamo db to dev environment

namespaces/live.cloud-platform.service.justice.gov.uk/offender-events-prod/09-prometheus-sqs-sns.yaml
https://mojdt.slack.com/archives/C06EU2VUHNV/p1713789016768749 
Also removes prison-to-probation-update alert.
=> Add Prometheus alerts for CFO queues

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-person-record-prod/resources/irsa.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-person-record-prod/resources/s3-ndelius-extract.tf
The intention is to create a bucket which is only readable by the IRSA account named person-record-service - i.e. it is not readable by any human user.
=> CPR-276 create machine readable S3 bucket for nDelius extract

namespaces/live.cloud-platform.service.justice.gov.uk/moj-vuln-report/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/moj-vuln-report/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/moj-vuln-report/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/moj-vuln-report/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/moj-vuln-report/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/moj-vuln-report/resources/irsa.tf, namespaces/live.cloud-platform.service.justice.gov.uk/moj-vuln-report/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/moj-vuln-report/resources/s3.tf, namespaces/live.cloud-platform.service.justice.gov.uk/moj-vuln-report/resources/service-pod.tf, namespaces/live.cloud-platform.service.justice.gov.uk/moj-vuln-report/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/moj-vuln-report/resources/versions.tf
incl. service-pod, s3 bucket and irsa
=> feat: 🎸 add new ns for security team vulnerability report

namespaces/live.cloud-platform.service.justice.gov.uk/moj-vuln-report/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/moj-vuln-report/resources/s3.tf
```
ValidationError: 1 validation error detected: Value 'MOJ D&T Cybersecurity' at 'tags.10.member.value' failed to satisfy constraint: Member must satisfy regular expression pattern: [\p{L}\p{Z}\p{N}_.:/=+\-@]*
```
=> fix: 🐛 lifecycle and tag format

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-dev/resources/api_gateway.tf
Error: creating API Gateway Integration: NotFoundException: Invalid Method identifier specified
--> little change in the response resource
--> added a dependency clause
--> added resources to general development resource
=> Addressing errors from CI

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-dev/resources/api_gateway.tf
Error: creating API Gateway Integration: NotFoundException: Invalid Method identifier specified
with aws_api_gateway_integration.sqs_integration,
on api_gateway.tf line 154, in resource "aws_api_gateway_integration" "sqs_integration":
154: resource "aws_api_gateway_integration" "sqs_integration" {
///// Addressing error above by adding a depends_on block for the queue and the method related to the integration
=> Addressing dependency issue raised by CI

namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-prod/resources/certificates.tf
Add new subdomain cert to support new site.
=> Add HMI Prison subdomain TLS cert

namespaces/live.cloud-platform.service.justice.gov.uk/request-personal-information-staging/resources/variables.tf
Change application variable so it is allowable as IRSA service_account_name
=> Fix rpi staging namespace

namespaces/live.cloud-platform.service.justice.gov.uk/monitoring/dashboard-datasource-s3.yaml
relates to ministryofjustice/cloud-platform#5510
=> add grafana s3 cloudwatchw dashboard

.checksum, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-cica-information-extraction-tool-dev/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-cica-information-extraction-tool-dev/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-cica-information-extraction-tool-dev/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-cica-information-extraction-tool-dev/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-cica-information-extraction-tool-dev/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-cica-information-extraction-tool-dev/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-cica-information-extraction-tool-dev/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-cica-information-extraction-tool-dev/resources/versions.tf
Creating namespace for deployment of exploratory app
=> Create namespace for cica-information-extraction-tool-dev

namespaces/live.cloud-platform.service.justice.gov.uk/cloud-platform-label-pods/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/user-roles.yaml
- add specific cluster role (need perms to pull rolebindings)
- point cluster rolebinding to new cluster role
=> chore: 🤖 update rbac and add specific cluster role

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-dev/resources/api_gateway.tf
Removed boolean preventing us from reaching API Gateway
=> Removed boolean preventing us from reaching API Gateway

namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-cica-information-extraction-tool-dev/resources/serviceaccount.tf
Creating service account for namespace
=> Add serviceaccount.tf to data-platform-app-cica-information-extraction-tool-dev

.checksum, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-cica-information-extraction-tool-prod/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-cica-information-extraction-tool-prod/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-cica-information-extraction-tool-prod/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-cica-information-extraction-tool-prod/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-cica-information-extraction-tool-prod/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-cica-information-extraction-tool-prod/resources/ecr.tf, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-cica-information-extraction-tool-prod/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-cica-information-extraction-tool-prod/resources/serviceaccount.tf, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-cica-information-extraction-tool-prod/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-cica-information-extraction-tool-prod/resources/versions.tf
Creating namespace for exploratory app in development
=> Create namespace for cica-information-extraction-tool-prod

namespaces/live.cloud-platform.service.justice.gov.uk/laa-submit-crime-forms-dev/resources/pingdom.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-submit-crime-forms-dev/resources/versions.tf
Add pingdom checks to laa-submit-crime-forms-dev
=> Add pingdom checks to laa-submit-crime-forms-dev

namespaces/live.cloud-platform.service.justice.gov.uk/laa-submit-crime-forms-uat/resources/pingdom.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-submit-crime-forms-uat/resources/versions.tf
Add pingdom to laa-submit-crime-forms--uat
=> Add pingdom to laa-submit-crime-forms-uat

namespaces/live.cloud-platform.service.justice.gov.uk/laa-submit-crime-forms-prod/resources/pingdom.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-submit-crime-forms-prod/resources/versions.tf
Add pingdom to laa-submit-crime-forms-uat
=> Add pingdom to laa-submit-crime-forms-prod

namespaces/live.cloud-platform.service.justice.gov.uk/tariq-test/resources/s3.tf
Setup the S3 bucket resource using existing module to check for deprecation warning messages in the build
=> setup the S3 bucket resource using existing module

namespaces/live.cloud-platform.service.justice.gov.uk/laa-assess-crime-forms-uat/resources/pingdom.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-assess-crime-forms-uat/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-assess-crime-forms-uat/resources/versions.tf
Add pingdom to laa-assess-crime-forms-uat
=> Add pingdom to laa-assess-crime-forms-uat

namespaces/live.cloud-platform.service.justice.gov.uk/laa-assess-crime-forms-dev/resources/pingdom.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-assess-crime-forms-dev/resources/versions.tf
Add pingdom to laa-assess-crime-forms-dev
=> Add pingdom to laa-assess-crime-forms-dev

namespaces/live.cloud-platform.service.justice.gov.uk/laa-assess-crime-forms-prod/resources/pingdom.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-assess-crime-forms-prod/resources/versions.tf
Add pingdom to laa-assess-crime-forms-prod
=> Add pingdom to laa-assess-crime-forms-prod

namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-legislation-drafting-helper-dev/02-limitrange.yaml
Increasing memory allocation to prevent app crashing
=> Modify legislation app limitrange

namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-kpi-dashboard-poc/resources/ecr.tf
- In relation to https://github.com/ministryofjustice/operations-engineering/issues/4420
- To allow deployment of containerised web app
- Added ECR resource to namespace 
- NA
=> ✨ Add ECR to `operations-engineering-kpi-dashboard-poc` namespace

namespaces/live.cloud-platform.service.justice.gov.uk/workforce-management-preprod/resources/rds_refresh.tf
Changes to add secret to enable prod->preprod data refreshes
=> WFP-2171 - rds refresh from prod change

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-delius-alfrsco-poc/resources/rds.tf
- **🔐 Add RDS Identifer to secret**
=> NIT 1243 alfresco backup and restore

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-accredited-programmes-prod/02-limitrange.yaml
=> Accredited Programmes Prod

namespaces/live.cloud-platform.service.justice.gov.uk/makeaplea-prod/resources/irsa.tf, namespaces/live.cloud-platform.service.justice.gov.uk/makeaplea-prod/resources/makeaplea-queue.tf
Remove specific sqs queue permissions from irsa role
=> Remove specific queue permissions for SQS but allow assume role for irsa

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-challenge-support-intervention-plan-prod/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-challenge-support-intervention-plan-prod/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-challenge-support-intervention-plan-prod/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-challenge-support-intervention-plan-prod/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-challenge-support-intervention-plan-prod/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-challenge-support-intervention-plan-prod/06-certificate.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-challenge-support-intervention-plan-prod/resources/domain-events-topic.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-challenge-support-intervention-plan-prod/resources/elasticache.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-challenge-support-intervention-plan-prod/resources/irsa.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-challenge-support-intervention-plan-prod/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-challenge-support-intervention-plan-prod/resources/rds-postgresql.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-challenge-support-intervention-plan-prod/resources/serviceaccount-circleci.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-challenge-support-intervention-plan-prod/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-challenge-support-intervention-plan-prod/resources/versions.tf
Re-creation of HMPPS CSIP namespace with new name (old namespace has been destroyed)
=> Rename hmpps-csip namespace to hmpps-challenge-support-invention-plan (prod)

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-challenge-support-intervention-plan-dev/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-challenge-support-intervention-plan-dev/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-challenge-support-intervention-plan-dev/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-challenge-support-intervention-plan-dev/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-challenge-support-intervention-plan-dev/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-challenge-support-intervention-plan-dev/06-certificate.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-challenge-support-intervention-plan-dev/resources/domain-events-topic.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-challenge-support-intervention-plan-dev/resources/elasticache.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-challenge-support-intervention-plan-dev/resources/irsa.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-challenge-support-intervention-plan-dev/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-challenge-support-intervention-plan-dev/resources/rds-postgresql.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-challenge-support-intervention-plan-dev/resources/serviceaccount-circleci.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-challenge-support-intervention-plan-dev/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-challenge-support-intervention-plan-dev/resources/versions.tf
Re-creation of HMPPS CSIP namespace with new name (old namespace has been destroyed)
=> Rename hmpps-csip namespace to hmpps-challenge-support-intervention-plan (dev)

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-challenge-support-intervention-plan-preprod/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-challenge-support-intervention-plan-preprod/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-challenge-support-intervention-plan-preprod/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-challenge-support-intervention-plan-preprod/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-challenge-support-intervention-plan-preprod/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-challenge-support-intervention-plan-preprod/06-certificate.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-challenge-support-intervention-plan-preprod/resources/domain-events-topic.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-challenge-support-intervention-plan-preprod/resources/elasticache.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-challenge-support-intervention-plan-preprod/resources/irsa.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-challenge-support-intervention-plan-preprod/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-challenge-support-intervention-plan-preprod/resources/rds-postgresql.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-challenge-support-intervention-plan-preprod/resources/serviceaccount-circleci.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-challenge-support-intervention-plan-preprod/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-challenge-support-intervention-plan-preprod/resources/versions.tf
Re-creation of HMPPS CSIP namespace with new name (old namespace has been destroyed)
=> Rename hmpps-csip namespace to hmpps-challenge-support-invention-plan (preprod)

namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-cica-information-extraction-tool-dev/02-limitrange.yaml
Requesting to increase mem and cpu limits for dev version of the app whilst troubleshooting deployment issues
=> Increase mem and cpu limits

namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-preprod/resources/secrets-manager.tf
Add slack-webhook secret for `court-probation-preprod`
=> court-probation-preprod Add slack webhook secret

namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-prod/resources/pingdom.tf
Add Pingdom to crime portal gateway in the PROD environment
=> Add Pingdom to crime portal gateway Prod

namespaces/live.cloud-platform.service.justice.gov.uk/laa-cla-backend-production/resources/rds.tf
Adds a new RDS instance to the `laa-cla-backend-production` namespace.
=> Add Metabase RDS instance to laa-cla-backend-production

namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-prod/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-prod/resources/variables.tf
Allow the probation-in-court github team to access **PROD** aws resources via the aws console
=> Authorise the probation-in-court github team to PROD resources

namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-dev/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-dev/resources/variables.tf
Allow the probation-in-court github team to access **DEV** aws resources via the aws console
=> Authorise the probation-in-court github team to DEV resources

namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-legislation-drafting-helper-dev/02-limitrange.yaml
Increase the memory and cpu to prevent crashing and improve speed
=> Adjust namespace for dev legislation app

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-application-store-dev/resources/variables.tf
Add HPA permissions to service account
=> CRM457-1456: Add HPA permissions to service account (DEV)

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-application-store-uat/resources/variables.tf
CRM457-1456: Add HPA permissions to service account (UAT)
=> CRM457-1456: Add HPA permissions to service account (UAT) 

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-application-store-production/resources/variables.tf
CRM457-1456: Add HPA permissions to service account (PROD)
=> CRM457-1456: Add HPA permissions to service account (PROD)

namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-prod/resources/court-case-events-sns-topic.tf
**environment**: PROD
Update the sns module to the latest cloud platform release in order to resolve a kms permissions issue
=> court-probation-prod Update sns module to latest

namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-preprod/resources/court-case-events-sns-topic.tf
**environment**: PREPROD
Update the sns module to the latest cloud platform release in order to resolve a kms permissions issue
=> court-probation-preprod Update sns module to latest 

namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-dev/resources/court-case-events-sns-topic.tf, namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-dev/resources/main.tf
Remove tagging
This is because i added tagging then upgraded the sns topic when it should have been the other way around.
i plan on creating a new PR to re-add this 🤞🏾
=> court-probation-dev Remove tagging

namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-preprod/resources/court-case-events-sns-topic.tf, namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-preprod/resources/main.tf
Remove tagging
This is because i added tagging then upgraded the sns topic when it should have been the other way around.
i plan on creating a new PR to re-add this 🤞🏾
=> court-probation-preprod Remove tagging

namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-prod/resources/court-case-events-sns-topic.tf, namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-prod/resources/main.tf
Remove tagging
This is because i added tagging then upgraded the sns topic when it should have been the other way around.
i plan on creating a new PR to re-add this 🤞🏾
=> court-probation-prod Remove tagging

namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-prod/resources/main.tf
Add tagging to enable aws resource access for court-probation PROD
=> Add tagging to enable aws resource access for court-probation PROD

namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-prod/resources/secrets-manager.tf
- Add secrets manager resource to court-probation-prod
- Add slack-webhook secret
=> Add slack-webhook as aws secret court-probation-prod

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-dev/resources/rds.tf
CCR: Repoint EDW DB link for CCR Dev
=> CTSKF-768-RDS-Repoint-EDW-DB

namespaces/live.cloud-platform.service.justice.gov.uk/laa-access-civil-legal-aid-uat/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-access-civil-legal-aid-uat/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-access-civil-legal-aid-uat/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-access-civil-legal-aid-uat/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-access-civil-legal-aid-uat/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-access-civil-legal-aid-uat/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-access-civil-legal-aid-uat/resources/serviceaccount.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-access-civil-legal-aid-uat/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-access-civil-legal-aid-uat/resources/versions.tf
Created namespace "laa-access-civil-legal-aid-uat"
=> Create namespace laa-access-civil-legal-aid-uat

namespaces/live.cloud-platform.service.justice.gov.uk/laa-access-civil-legal-aid-staging/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-access-civil-legal-aid-staging/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-access-civil-legal-aid-staging/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-access-civil-legal-aid-staging/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-access-civil-legal-aid-staging/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-access-civil-legal-aid-staging/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-access-civil-legal-aid-staging/resources/serviceaccount.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-access-civil-legal-aid-staging/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-access-civil-legal-aid-staging/resources/versions.tf
Created namespace "laa-access-civil-legal-aid-staging"
=> Create namespace laa-access-civil-legal-aid-staging

namespaces/live.cloud-platform.service.justice.gov.uk/laa-access-civil-legal-aid-dev/resources/serviceaccount.tf
Removed service account from "laa-access-civil-legal-aid-dev" to re-create with subsequent PR.
=> Removed service account from laa-access-civil-legal-aid-dev

namespaces/live.cloud-platform.service.justice.gov.uk/laa-access-civil-legal-aid-production/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-access-civil-legal-aid-production/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-access-civil-legal-aid-production/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-access-civil-legal-aid-production/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-access-civil-legal-aid-production/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-access-civil-legal-aid-production/resources/ecr.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-access-civil-legal-aid-production/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-access-civil-legal-aid-production/resources/serviceaccount.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-access-civil-legal-aid-production/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-access-civil-legal-aid-production/resources/versions.tf
Created namespace "laa-access-civil-legal-aid-production"
=> Create namespace laa-access-civil-legal-aid-production

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-digital-prison-reporting-mi-dev/resources/cross-iam-role-irsa.tf
Ref, https://docs.aws.amazon.com/eks/latest/userguide/associate-service-account-role.html
=> Add oidc_fully_qualified_audiences

namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-dev/resources/variables.tf
Add migrated cica application-service repo to ecr module registry
=> Add migrated cica application-service repo to ecr module registry

namespaces/live.cloud-platform.service.justice.gov.uk/sw-psa-audit-test/01-rbac.yaml
does restricted string trigger guardduty?
=> refactor: 💡 update team rbac

namespaces/live.cloud-platform.service.justice.gov.uk/justice-gov-uk-production/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/justice-gov-uk-production/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/justice-gov-uk-production/resources/ecr.tf, namespaces/live.cloud-platform.service.justice.gov.uk/justice-gov-uk-production/resources/rds.tf, namespaces/live.cloud-platform.service.justice.gov.uk/justice-gov-uk-production/resources/route53.tf, namespaces/live.cloud-platform.service.justice.gov.uk/justice-gov-uk-production/resources/servicepod.tf, namespaces/live.cloud-platform.service.justice.gov.uk/justice-gov-uk-production/resources/variables.tf
- Configure route53 with initial values
- Upgrade module versions
- RDS delete protection enabled
- RDS performance monitoring enabled
- RDS DB memory increased
=> Justice-gov-uk production pre launch

.checksum, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-uat/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-uat/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-uat/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-uat/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-uat/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-uat/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-uat/resources/rds.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-uat/resources/serviceaccount.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-uat/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-uat/resources/versions.tf
Create new non-prod uat namespace for CCR
=> CCR UAT Namespace

namespaces/live.cloud-platform.service.justice.gov.uk/justice-gov-uk-production/resources/route53.tf
Hi @wilson1000 @EmilyHazlehurst , in preparation for later. 
This will need to be deployed at the same time as updating our `ingress.yml`.
=> Remove Squiz A record. DO NOT MERGE
