- namespaces/live.cloud-platform.service.justice.gov.uk/digital-prison-services-prod/resources/route53-prison.tf
Reverts ministryofjustice/cloud-platform-environments#23062
> Revert "SDIT-1751: 🔧 Remove preprod route"

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-data-migration-dev/resources/iam.tf
> laa-dces-dm-s3-dev-stm-path

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-data-migration-dev/resources/serviceaccount.tf
remove service account GitHub action
> laa-dces-dm-dev-del-github-act

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-dev/resources/irsa.tf
amend data module to allow sts assumerole
> Update IRSA to allow IAM assumerole identity

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-dev/resources/irsa.tf
Updates and ameds to IAM resource policy
> Update IRSA and fix build

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-data-migration-dev/resources/s3.tf
> laa-dces-dm-dev-s3-user

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-data-migration-dev/resources/s3.tf
> laa-dces-dm-dev-s3-putObject

- namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-model-metadata-uploader-dev/resources/ecr.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-model-metadata-uploader-dev/resources/serviceaccount.tf
Create ECR and model_metadata namespaces
> create ecr and sa for model_metadata namespace

- namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-dev/resources/variables.tf
Add migrated data-capture-service repo ro ecr module registry
> Add migrated data-capture-service repo ro ecr module registry

- namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-find-moj-data-dev/05-prometheusrule.yaml
Add the yaml detailing prometheus rules to trigger alerts for find-moj-data dev env
> adding prometheus rules for alerting to find-moj-dev

- namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-find-moj-data-dev/resources/pingdom.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-find-moj-data-dev/resources/variables.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-find-moj-data-dev/resources/versions.tf
Adding pingdom, plus updating some out-of-data variables
> Find moj data dev add pingdom

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-application-store-uat/resources/rds-postgresql.tf
Add UAT read replica for use by metabase
> CRM457-1334: Add UAT read replica for use by metabase

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-application-store-uat/resources/rds-postgresql.tf
CRM457-1334: Bump UAT storage autoscaling max
Currently CI is failed to create read replica
> CRM457-1334: Bump UAT storage autoscaling max

- namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-dev/resources/variables.tf
Add migrated cica-web repo ro ecr module registry
> Add migrated cica-web repo ro ecr module registry

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-application-store-production/resources/rds-postgresql.tf
Add PROD read replica for use by metabase
> CRM457-1334: Add PROD read replica for use by metabase

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-dev/resources/s3_truststore.tf
Having issues with certs so updating path to a new cert that has been uploaded
> Update cert path to debug cert

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-fala-production/resources/pingdom.tf
Tag is for creation of a pingdom dashboard across laa production services
> Add pingdom tag

- namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-dev/resources/variables.tf
> Add migrated cica repos ro ecr module registry

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-staff-preprod/resources/irsa.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-staff-preprod/resources/variables.tf
Adding in irsa.tf to preprod
Adding in servicepod to preprod
> WFP-2482-adding irsa and servicepod to preprod

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-hardship-dev/resources/rds-postgresql.tf
```Error: updating RDS DB Instance (cloud-platform-XXXX): operation error RDS: ModifyDBInstance, https response error StatusCode: 400, RequestID: 7d7f4978-0740-448d-a984-5ea63856f230, api error InvalidParameterCombination: Cannot find upgrade path from 14.10 to 14.7.```
> Minor version auto updated fix terraform

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-data-migration-dev/resources/s3.tf
> laa-dces-dm-dev-s3-folderPermissionchange folder access

- namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-stag/resources/service-pod.tf
Service pod for CICA apply staging environment
> Add service pod to staging

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-hardship-uat/resources/rds-postgresql.tf
Fixing auto minor update pipeline error: Cannot find upgrade path from 14.10 to 14.7
> Minor version auto updated, fix terraform

- namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-dev/resources/variables.tf
Rename migrated cica repos for ecr module registry
> Rename migrated cica repos for ecr module registry

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-data-migration-dev/resources/iam.tf
> laa-dces-dm-dev-s3-restrictFoldertesting folder restriction

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-dev/resources/api_gateway.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-dev/resources/event-subscriber-mapps.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-dev/resources/event-subscriber-pnd.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-dev/resources/event-subscriber-test.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-dev/resources/event-topic.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-dev/resources/hmpps-domain-event-subscription.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-dev/resources/iam.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-dev/resources/irsa.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-dev/resources/kubernetes_secrets.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-dev/resources/locals.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-dev/resources/rds_postgres.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-dev/resources/s3_truststore.tf
Updating where the secret policy lives
> Update secrets irsa

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-data-migration-dev/resources/iam.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-data-migration-dev/resources/s3.tf
> laa-dces-dm-dev-s3-deny

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-workload-dev/resources/irsa.tf
service pod for hmpps-workload-dev
> WFP-2162 service pod for hmpps-workload-dev

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-submit-crime-forms-uat/resources/rds-postgresql.tf
Enable deletion protection and auto start and stop
Agreed with NSCC team
> Provider UAT: Enable deletion protection and auto start and stop

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-assess-crime-forms-prod/resources/rds-postgresql.tf
> Assess PROD: Add deletion protection

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-application-store-uat/resources/rds-postgresql.tf
> Appstore UAT: Add deletion protection and auto stop start

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-dev/resources/iam.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-dev/resources/irsa.tf
Moved to having secrets iam instead of secrets module terraform irsa - see slack conversation for more [context](https://mojdt.slack.com/archives/C57UPMZLY/p1716547623559889)
> Switch from secret irsa to iam

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-data-migration-dev/resources/iam.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-data-migration-dev/resources/s3.tf
> laa-dces-dm-dev-s3-deny5

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-application-store-uat/resources/rds-postgresql7.tf
Adds RDS instance for Metabase
> CRM457-UAT-RDS instance for Metabase

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-data-migration-dev/resources/iam.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-data-migration-dev/resources/s3.tf
> laa-dces-dm-dev-s3-deny6

- namespaces/live.cloud-platform.service.justice.gov.uk/core-person-record-prototype/00-namespace.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/core-person-record-prototype/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/core-person-record-prototype/02-limitrange.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/core-person-record-prototype/03-resourcequota.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/core-person-record-prototype/04-networkpolicy.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/core-person-record-prototype/resources/basic-auth.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/core-person-record-prototype/resources/ecr.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/core-person-record-prototype/resources/main.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/core-person-record-prototype/resources/serviceaccount.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/core-person-record-prototype/resources/variables.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/core-person-record-prototype/resources/versions.tf
> Added core-person-record-prototype prototype

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-data-migration-dev/resources/iam.tf
> laa-dces-dm-dev-s3-removeV2

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-sds-test/resources/irsa.tf
Adding cross irsa for migrating buckets to sds
> Adding cross irsa to test environment

- namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-uat/resources/service-pod.tf
Add service pod to uat namespace
> 🧱 CDI-201 UAT service pod

- namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-uat/APPLY_PIPELINE_SKIP_THIS_NAMESPACE
Add skip pipeline file for UAT before RDS version upgrade
> 🙈 Add skip pipeline file before RDS upgrade

- namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-uat/resources/rds.tf
Upgrade minor version from 14.7 to 14.10
> 🗃️ Upgrade RDS UAT minor version

- namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-uat/resources/rds.tf
Change Instance type from t3.small to t4g.small and set max storage.
> 🗃️ Change RDS Instance type CICA UAT

- namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-uat/APPLY_PIPELINE_SKIP_THIS_NAMESPACE
Remove skip namespace file for pipeline
> 🔥 Remove skip file for pipeline

- namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-dns-form-dev/00-namespace.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-dns-form-dev/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-dns-form-dev/02-limitrange.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-dns-form-dev/03-resourcequota.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-dns-form-dev/04-networkpolicy.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-dns-form-dev/resources/ecr.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-dns-form-dev/resources/main.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-dns-form-dev/resources/secret.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-dns-form-dev/resources/serviceaccount.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-dns-form-dev/resources/variables.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-dns-form-dev/resources/versions.tf
- To create infrastructure ready for new app 🥳 
- Added `operations-engineering-dns-form-dev` namespace
- NA
> ✨ Add `operations-engineering-dns-form-dev` namespace

- namespaces/live.cloud-platform.service.justice.gov.uk/check-my-diary-prod/07-certificate.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/check-my-diary-prod/resources/pingdom.tf
> SDIT-1770 Add ingress for cmd-api and csr-api

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-auth-prod/resources/variables.tf
remove -alt from variable domain
> Update hmpps-auth domain name in variables.tf

- namespaces/live.cloud-platform.service.justice.gov.uk/devcontainer-production/00-namespace.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/devcontainer-production/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/devcontainer-production/02-limitrange.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/devcontainer-production/03-resourcequota.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/devcontainer-production/04-networkpolicy.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/devcontainer-production/resources/main.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/devcontainer-production/resources/route53.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/devcontainer-production/resources/variables.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/devcontainer-production/resources/versions.tf
This PR adds a Route53 zone `devcontainer.service.justice.gov.uk` + record `user-guide.devcontainer.service.justice.gov.uk`.
> :wrench: Add devcontainer namespace + DNS

- namespaces/live.cloud-platform.service.justice.gov.uk/make-recall-decision-prod/02-limitrange.yaml
> MRD-Prod-Memory-Increase

- namespaces/live.cloud-platform.service.justice.gov.uk/tim-development/resources/opensearch-alert.tf
This PR is to demonstrate user need to create more than 1 OpenSearch alert rules in their namespace. 
Recall the module to achieve this
> Another os alert rule

- namespaces/live.cloud-platform.service.justice.gov.uk/cccd-staging/resources/messaging.tf
Configuration added to allow security token service role assumability.
> Update CCCD IAM principle array for CCR UAT

- namespaces/live.cloud-platform.service.justice.gov.uk/parliamentary-questions-development/resources/elasticache.tf
Changed to work with latest versions of Redis.
> Remove user from URL

- namespaces/live.cloud-platform.service.justice.gov.uk/parliamentary-questions-staging/resources/serviceaccount-github.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/parliamentary-questions-staging/resources/variables.tf
> Parliamentary questions staging - Switch from CircleCI to GHA

- namespaces/live.cloud-platform.service.justice.gov.uk/parliamentary-questions-staging/resources/elasticache.tf
Changed to work with latest versions of Redis.
> Remove user from Redis URL - PQ Staging

- namespaces/live.cloud-platform.service.justice.gov.uk/parliamentary-questions-production/resources/service-account-github.tf
> Parliamentary questions production - Switch from CircleCI to GHA

- namespaces/live.cloud-platform.service.justice.gov.uk/peoplefinder-development/resources/ecr.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/peoplefinder-development/resources/serviceaccount-github.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/peoplefinder-development/resources/variables.tf
> Peoplefinder development - Switch from CircleCI to GHA

- namespaces/live.cloud-platform.service.justice.gov.uk/parliamentary-questions-production/resources/elasticache.tf
Changed to work with latest versions of Redis.
> Remove user from Redis URL - PQ Production

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-incentives-preprod/00-namespace.yaml
Send Incentives' `preprod` alerts to our dev Slack channel.
> INC-1335: Send `preprod` alerts to dev Slack channel

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-application-store-uat/resources/rds-metabase.tf
Enable auto stop and start fo metabase RDS instance on UAT
As agreed with team
> Enable auto stop and start of metabase RDS instance on UAT

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-uat/resources/rds.tf
Uses `ref=migration` source and `is_migration = true`
> Add CCR uat RDS instance

- namespaces/live.cloud-platform.service.justice.gov.uk/make-recall-decision-prod/resources/service_pod.tf
new service pod for make recall decision prod
> adding service pod to mrd prod

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-digital-prison-reporting-mi-dev/resources/cross-iam-role-irsa.tf
Refactor cross account connectivity in Dev.
> DPR2-751 refactor cross account connectivity in Dev

- namespaces/live.cloud-platform.service.justice.gov.uk/make-recall-decision-dev/resources/irsa.tf
Allowing RDS and ElasticCache policies for IRSA
> adding irsa rds and elastic cache policies

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-digital-prison-reporting-mi-preprod/resources/cross-iam-role-irsa.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-digital-prison-reporting-mi-preprod/resources/variables.tf
Added cross-iam-role-irsa.tf to preprod.
> Dpr2 751 added cross iam role irsa to preprod

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-a-video-link-dev/resources/domain-events-queue-bvls.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-a-video-link-dev/resources/domain-events-topic.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-a-video-link-dev/resources/variables.tf
Setting up initial development AWS queue configuration for the re-platformed book a video link service.
> BAVL-25 initial attempt at queue configuration for the replatformed book a video link service.

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-jobs-board-dev/resources/rds-postgresql.tf
The purpose of this PR is to create a new Dev Postgresql RDS database on the Jobs Portal application.
https://github.com/ministryofjustice/hmpps-jobs-board-api
> ESWE-831 Create new RDS Postgresql Dev database

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-a-video-link-dev/resources/irsa.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-a-video-link-dev/resources/main.tf
Adding the required local queue permissions for the BVLS service in dev.
> BAVL-25 adding queue permissions for the BVLS service.

- namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-dev/resources/rds-temp.tf
We are currently testing the possibility of Creating a new DB with the data from a snapshot for DP purposes so we can recover individual tables should we need to.
> Added new rds tf file for new RDS DB from snapshot

- namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-dev/resources/rds-temp.tf
Updated snapshot identifier for testing a new RDS instance with snapshot data
> Hale-Dev Updated snapshot identifier

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-a-video-link-dev/resources/irsa.tf
Add SQS policy to service account.
> BAVL-25: Add combined sqs policy to service account

- namespaces/live.cloud-platform.service.justice.gov.uk/check-my-diary-preprod/resources/rds.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-test-dev/resources/submitter.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-test-dev/resources/user-datastore.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-test-production/resources/submitter.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-test-production/resources/user-datastore.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-saas-test/resources/editor.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-saas-test/resources/metadata_api.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-jobs-board-dev/resources/rds-postgresql.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-nomis-mapping-service-dev/resources/rds.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-nomis-mapping-service-preprod/resources/rds.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-prisoner-from-nomis-migration-dev/resources/rds.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-prisoner-from-nomis-migration-preprod/resources/rds.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-prisoner-search-dev/resources/rds.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-prisoner-search-preprod/resources/rds.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-restricted-patients-api-dev/resources/rds.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-restricted-patients-api-preprod/resources/rds.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-restricted-patients-api-prod/resources/rds.tf
This PR amends the RDS module to 7.0.0 for namespaces which was already upgraded to 6.1.0
https://mojdt.slack.com/archives/CH6D099DF/p1718712225061249?thread_ts=1718625451.095069&cid=CH6D099DF
> Bump RDS module to 7.0.0

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-submit-crime-forms-uat/resources/secrets.tf
Add slack web hook secret container
> Submit UAT: Add slack webhook secret container

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-submit-crime-forms-prod/resources/secrets.tf
Add slack webhook secret container
> Submit PROD: Add slack webhook secret container

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-incentives-dev/resources/rds.tf
Depends on [hmpps-incentives-api#584](https://github.com/ministryofjustice/hmpps-incentives-api/pull/584)
> INC-1369: Update RDS terraform module for `hmpps-incentives-dev`

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-incentives-preprod/resources/rds.tf
Depends on [hmpps-incentives-api#584](https://github.com/ministryofjustice/hmpps-incentives-api/pull/584)
> INC-1369: Update RDS terraform module for `hmpps-incentives-preprod`

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-incident-reporting-prod/resources/rds.tf
Depends on [hmpps-incident-reporting-api#127](https://github.com/ministryofjustice/hmpps-incident-reporting-api/pull/127)
> IR-283: Update RDS terraform module for `hmpps-incident-reporting-prod`

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-digital-prison-reporting-mi-prod/resources/cross-iam-role-irsa.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-digital-prison-reporting-mi-prod/resources/variables.tf
Added cross-iam-role-irsa.tf to prod.
> DPR2-751 added cross-iam-role-irsa.tf to prod

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-incentives-prod/resources/rds.tf
Depends on [hmpps-incentives-api#584](https://github.com/ministryofjustice/hmpps-incentives-api/pull/584)
> INC-1369: Update RDS terraform module for `hmpps-incentives-prod`

- namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-dev/resources/rds.tf
Update rds module to v7 in vsip-dev
> Update rds module to v7 in vsip-dev

- namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-staging/resources/rds.tf
Update rds module to v7 for visit-scheduler and booker-registry in staging
> Update rds module to v7 for visit-scheduler and booker-registry in staging

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-submit-crime-forms-dev/04-networkpolicy.yaml
> CMR457-1360: Allow scraping of worker pods

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-dev/resources/rds.tf
> DB snapshot made apply to dev namespace

- namespaces/live.cloud-platform.service.justice.gov.uk/monitoring/dashboard-thanos.yaml
Add 2 panels to track:
- thanos compactor backlog
- thanos compactor block backlog
> chore: 🤖 add graf for thanos compactor

- namespaces/live.cloud-platform.service.justice.gov.uk/justice-gov-uk-production/resources/route53.tf
> justice-gov-uk-production - amend CNAME record for GutHub Pages

- namespaces/live.cloud-platform.service.justice.gov.uk/monitoring/dashboard-thanos.yaml
add more useful thanos compactor panels
> chore: 🤖 add more thanos compat panels

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-dev/05-prometheus.yaml
Following migration of dev database from LZ
> Update RDS instance in CCR dev Prometheus rules

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-resettlement-passport-dev/resources/irsa.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-resettlement-passport-dev/resources/sqs.tf
to hmpps-resettlement-passport-dev
> Add offender event queue

- .github/workflows/malformed-yaml.yml
- namespaces/live.cloud-platform.service.justice.gov.uk/sw-psa-audit-test/04-networkpolicy.yaml
update to latest malformed-yaml release with fix for multi doc yaml, plus test a multi doc yaml
> chore: 🤖 bump malformed-yaml action

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-data-migration-dev/resources/s3.tf
> laa-dces-dm-dev-s3-versioning

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-staging/resources/serviceaccount.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-staging/resources/variables.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-uat/resources/serviceaccount.tf
comparison changes to fix pods
> Deploy CCR to staging env

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-application-store-uat/resources/variables.tf
- **Remove hpa and prometheusrules permissions**
- **Add smon and netpol**
> Appstore UAT: Add smon and netpol permissions

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-application-store-dev/resources/variables.tf
Remove hpa and prometheusrules permissions
Add smon and netpol
> Appstore DEV: Add smon and netpol permissions

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-application-store-production/resources/variables.tf
- **Remove hpa and prometheusrules permissions**
- **Add smon and netpol**
> Appstore PROD: Add smon and netpol permissions

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-data-migration-dev/resources/s3.tf
prevent s3 delete for iam user
> laa-dces-dm-dev-s3-preventDelete

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-data-migration-dev/resources/s3.tf
adding principal to deny statement
> laa-dces-dm-dev-s3-preventDelete2

- namespaces/live.cloud-platform.service.justice.gov.uk/prepare-a-case-for-sentence-design-history/00-namespace.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/prepare-a-case-for-sentence-design-history/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/prepare-a-case-for-sentence-design-history/02-limitrange.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/prepare-a-case-for-sentence-design-history/03-resourcequota.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/prepare-a-case-for-sentence-design-history/04-networkpolicy.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/prepare-a-case-for-sentence-design-history/resources/basic-auth.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/prepare-a-case-for-sentence-design-history/resources/ecr.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/prepare-a-case-for-sentence-design-history/resources/main.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/prepare-a-case-for-sentence-design-history/resources/serviceaccount.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/prepare-a-case-for-sentence-design-history/resources/variables.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/prepare-a-case-for-sentence-design-history/resources/versions.tf
This is so that we can host our design history
on cloud platform. Hopefully I have not pasted
the name in twice so it does not exceed the
namespace character limit.
> Adding a new namespace for the design history

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-activities-management-preprod/resources/rds.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-activities-management-preprod/resources/variables.tf
Enables Database sync/replication for the DPR service
> SAA-1479: Enable RDS replication on activities preprod for DPR sync

- .checksum
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-ems-datastore-api-dev/00-namespace.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-ems-datastore-api-dev/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-ems-datastore-api-dev/02-limitrange.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-ems-datastore-api-dev/03-resourcequota.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-ems-datastore-api-dev/04-networkpolicy.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-ems-datastore-api-dev/resources/ecr.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-ems-datastore-api-dev/resources/main.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-ems-datastore-api-dev/resources/serviceaccount.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-ems-datastore-api-dev/resources/variables.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-ems-datastore-api-dev/resources/versions.tf
This is a new environment for an API to access Electronic Monitoring data
> Add new ems api environment

- namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-preprod/resources/rds.tf
Update visit-scheduler and booker-registry to v7 in preprod rds instance
> Update visit-scheduler and booker-registry to v7 in preprod rds instance

- namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-prod/resources/rds.tf
Update visit-scheduler and booker-registry rds module to v7
> Update visit-scheduler and booker-registry rds module to v7

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-submit-crime-forms-dev/06-prometheus-custom-rules.yaml
- **Remove test promrule alert**
- **Add KubePodCrashLooping promrule**
> Submit DEV: Remove test and add podcrashloop promrules

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-dev/resources/s3_truststore.tf
Updating permissions to list s3 objects
> Update permissions to list s3 objects

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-submit-crime-forms-dev/06-prometheus-custom-rules.yaml
- **Move annotations for consistency**
- **Add sidekiq alerts for queuesize and deadjobs**
> Submit DEV: Add sidekiq metrics alerts

- namespaces/live.cloud-platform.service.justice.gov.uk/contact-moj-development/resources/ecr.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/contact-moj-development/resources/serviceaccount-github.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/contact-moj-development/resources/variables.tf
> Contact moj dev - Switch from CircleCI to GHA

- namespaces/live.cloud-platform.service.justice.gov.uk/contact-moj-staging/resources/serviceaccount-github.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/contact-moj-staging/resources/variables.tf
> Contact moj staging - Switch from CircleCI to GHA

- namespaces/live.cloud-platform.service.justice.gov.uk/offender-management-staging/resources/rds.tf
This DB is used across 3 namespaces:
- offender-management-staging
- offender-management-test1
- offender-management-test2
> Upgrade POM cases staging RDS to 7.0.0

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-data-migration-dev/resources/iam.tf
> laa-dces-dm-dev-s3-restrictFolder

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-dev/resources/s3_truststore.tf
revert new s3 permission which is causing build failure
> took away list bucket permission

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-dpr-tools-test/resources/cross-iam-role-irsa.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-dpr-tools-test/resources/variables.tf
Added cross-iam-role-irsa.tf to dpr-tools-test.
> DPR2-936 added cross-iam-role-irsa.tf to dpr-tools-test

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-data-migration-dev/resources/s3.tf
> laa-dces-dm-dev-s3-preventDownload

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-data-migration-dev/resources/s3.tf
> laa-dces-dm-dev-s3-restrictFolderLAA

- namespaces/live.cloud-platform.service.justice.gov.uk/contact-moj-production/resources/ecr.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/contact-moj-production/resources/service-account-github.tf
> Contact moj prod - Switch from CircleCI to GHA

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-data-migration-dev/resources/s3.tf
> laa-dces-dm-dev-s3-restrictFolderLAATryAgain

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-data-migration-dev/resources/iam.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-data-migration-dev/resources/s3.tf
> laa-dces-dm-dev-s3-StAgain

- namespaces/live.cloud-platform.service.justice.gov.uk/track-a-query-staging/resources/serviceaccount-github.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/track-a-query-staging/resources/variables.tf
> CT (Track a query) staging - Switch from CircleCI to GHA

- namespaces/live.cloud-platform.service.justice.gov.uk/track-a-query-qa/resources/serviceaccount-github.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/track-a-query-qa/resources/variables.tf
> CT (Track a query) QA - Switch from CircleCI to GHA

- namespaces/live.cloud-platform.service.justice.gov.uk/track-a-query-production/resources/ecr.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/track-a-query-production/resources/service-account-github.tf
> CT (Track a query) production - Switch from CircleCI to GHA

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-resettlement-passport-preprod/resources/irsa.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-resettlement-passport-preprod/resources/sqs.tf
Add queue listening to domain events for prisoner received/released
> Add queue to hmpps-resettlement-passport-preprod

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-resettlement-passport-prod/resources/irsa.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-resettlement-passport-prod/resources/sqs.tf
Add queue listening to domain events for prisoner received/released
> Add queue to hmpps-resettlement-passport-prod

- .checksum
- namespaces/live.cloud-platform.service.justice.gov.uk/jamesvalidation-dev/00-namespace.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/jamesvalidation-dev/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/jamesvalidation-dev/02-limitrange.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/jamesvalidation-dev/03-resourcequota.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/jamesvalidation-dev/04-networkpolicy.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/jamesvalidation-dev/resources/ecr.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/jamesvalidation-dev/resources/main.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/jamesvalidation-dev/resources/serviceaccount.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/jamesvalidation-dev/resources/variables.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/jamesvalidation-dev/resources/versions.tf
Deploying example application for personal validation
> Implement james-validation sandbox

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-production/00-namespace.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-production/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-production/02-limitrange.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-production/03-resourcequota.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-production/04-networkpolicy.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-production/resources/main.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-production/resources/variables.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-production/resources/versions.tf
Create a Cloud Platform namespace for laa-crown-court-remuneration-production.
> Create a laa-crown-court-remuneration-production namespace

- .checksum
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-production/resources/rds.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-production/resources/serviceaccount.tf
> ccr production create namespace in cloud platform

- namespaces/live.cloud-platform.service.justice.gov.uk/jamesvalidation-dev/00-namespace.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/jamesvalidation-dev/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/jamesvalidation-dev/02-limitrange.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/jamesvalidation-dev/03-resourcequota.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/jamesvalidation-dev/04-networkpolicy.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/jamesvalidation-dev/resources/ecr.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/jamesvalidation-dev/resources/main.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/jamesvalidation-dev/resources/serviceaccount.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/jamesvalidation-dev/resources/variables.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/jamesvalidation-dev/resources/versions.tf
Reverts ministryofjustice/cloud-platform-environments#24041
> Revert "remove jamesvalidation-dev namespace"

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-preprod/resources/api_gateway.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-preprod/resources/api_gateway_mapps_resources.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-preprod/resources/event-subscriber-mapps.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-preprod/resources/event-topic.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-preprod/resources/hmpps-domain-event-subscription.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-preprod/resources/iam.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-preprod/resources/irsa.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-preprod/resources/locals.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-preprod/resources/rds_postgres.tf
> Update API gateway policy

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-probation-search-dev/resources/opensearch.tf
following completion of testing semantic search
> PI-2277 Reduce OpenSearch resources

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-application-store-production/05-prometheus-custom-rules.yaml
- **CRM457-1699: Ignore 5xx errors on metabase ingress**
- **Change low pod count to < 3**
> CRM457-1699: Ignore 5xx errors on metabase ingress appstore PROD

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-nomis-mapping-service-preprod/resources/rds.tf
> SDIT-1852 Casenotes migration

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-staging-file-upload-api-dev/00-namespace.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-staging-file-upload-api-dev/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-staging-file-upload-api-dev/02-limitrange.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-staging-file-upload-api-dev/03-resourcequota.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-staging-file-upload-api-dev/04-networkpolicy.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-staging-file-upload-api-dev/resources/ecr.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-staging-file-upload-api-dev/resources/main.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-staging-file-upload-api-dev/resources/secret.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-staging-file-upload-api-dev/resources/serviceaccount.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-staging-file-upload-api-dev/resources/variables.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-staging-file-upload-api-dev/resources/versions.tf
Create new dev namespace for laa-ccms-staging-file-upload-api
> Create new dev namespace for laa-ccms-staging-file-upload-api

- namespaces/live.cloud-platform.service.justice.gov.uk/contact-moj-development/resources/rds.tf
> Contact MOJ Upgrade to 13.14

- namespaces/live.cloud-platform.service.justice.gov.uk/contact-moj-development/resources/rds.tf
To prepare for next major upgrade
> Turn off major upgrade

- namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-datahub-catalogue-prod/00-namespace.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-datahub-catalogue-prod/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-datahub-catalogue-prod/02-limitrange.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-datahub-catalogue-prod/03-resourcequota.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-datahub-catalogue-prod/04-networkpolicy.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-datahub-catalogue-prod/resources/ecr.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-datahub-catalogue-prod/resources/irsa.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-datahub-catalogue-prod/resources/main.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-datahub-catalogue-prod/resources/opensearch.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-datahub-catalogue-prod/resources/rds-postgresql.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-datahub-catalogue-prod/resources/secrets.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-datahub-catalogue-prod/resources/service-pod.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-datahub-catalogue-prod/resources/serviceaccount.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-datahub-catalogue-prod/resources/variables.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-datahub-catalogue-prod/resources/versions.tf
adding the namespace for prod environment of the Datahub data catalogue backend
> files for datahub prod namespace

- namespaces/live.cloud-platform.service.justice.gov.uk/alpha-cjs-va-dashboard-dev/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/alpha-cjs-va-dashboard-dev/resources/ecr.tf
Creating container repository and amending rbac permissions for alpha-cis-va-dashboard namespace
> Creating container repository and amending rbac permissions

- namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-datahub-catalogue-prod/resources/variables.tf
Just seen there is an `is_production` variable - have set it to the correct value
> correct is_production variable for prod resources

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-production/resources/irsa.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-production/resources/variables.tf
Creates the irsa for assuming IAMs role based on service account, with SQS policy permissions
> Service account creation and SQS policies

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-data-migration-dev/resources/iam.tf
> laa-dces-dm-dev-admin-iam-user

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-data-migration-dev/resources/s3.tf
> laa-dces-dm-dev-admin-s3-policy

- namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-preprod/09-prometheus-alerts.yaml
Add Prometheus alerts for court-case-service / prepare-a-case AWS RDS database
> Court Probation PreProd - Add RDS prometheus alerts 

- namespaces/live.cloud-platform.service.justice.gov.uk/c100-application-staging/resources/rds.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/cccd-staging/resources/rds.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/cfe-civil-staging-mtr/resources/rds.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/cfe-civil-staging/resources/rds.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/contact-moj-staging/resources/rds.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/courtfines-staging/resources/rds-postgresql.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/disclosure-checker-staging/resources/rds.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/evidencelibrary-staging/resources/rds.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/family-mediators-api-staging/resources/rds.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/find-unclaimed-court-money-staging/resources/rds-postgresql.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-staging/resources/rds.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/iac-fees-staging/resources/rds-postgresql.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/intranet-staging/resources/rds.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/justice-gov-uk-staging/resources/rds.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-check-client-qualifies-staging/resources/rds.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-civil-case-api-staging/resources/rds-postgresql.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-cla-backend-staging/resources/rds.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-ui-staging/resources/rds.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-fala-staging/resources/rds.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-legal-adviser-api-staging/resources/rds.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-status-dashboard-staging/resources/rds-postgresql.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/parliamentary-questions-staging/resources/rds.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/peoplefinder-staging/resources/rds.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/prison-visits-booking-staging/resources/rds-prison-visits.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/request-personal-information-staging/resources/rds-postgresql.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/soc-staging/resources/rds.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/track-a-query-staging/resources/rds.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/utiac-staging/resources/rds-postgresql.tf
Relates to ministryofjustice/cloud-platform#5754
> chore: Bump RDS module to 7.0.0 for Staging

- namespaces/live.cloud-platform.service.justice.gov.uk/intranet-staging/06-certificate.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/intranet-staging/resources/acm.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/intranet-staging/resources/cloudfront.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/intranet-staging/resources/cross-iam-role-sa.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/intranet-staging/resources/main.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/intranet-staging/resources/opensearch.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/intranet-staging/resources/route53.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/intranet-staging/resources/variables.tf
Adding:
- Migration pod
- OpenSearch
- Certificate
> Create required staging resources

- namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-uat/resources/rds.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-uat/resources/rds.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-assess-crime-forms-uat/resources/rds-postgresql.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-civil-case-api-uat/resources/rds-postgresql.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-cla-backend-uat/resources/rds.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-uat/resources/rds-instance.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-ui-uat/resources/rds.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-application-store-uat/resources/rds-metabase.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-application-store-uat/resources/rds-postgresql.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-equinity-historical-data-uat/resources/rds-mssql.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-evidence-uat/resources/rds-postgresql.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-hardship-uat/resources/rds-postgresql.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-means-assessment-uat/resources/rds.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-validation-uat/resources/rds-postgresql.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-contribution-uat/resources/rds.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-proceeding-uat/resources/rds.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-submit-crime-forms-uat/resources/rds-postgresql.tf
Relates to ministryofjustice/cloud-platform#5754
> chore: Bump RDS module to 7.0.0 in UAT

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-person-record-prod/resources/cpr-delius-offender-events-queue.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-person-record-prod/resources/data.tf
Reverts ministryofjustice/cloud-platform-environments#24471
> Revert "CPR-388 Use correct sns topic for delius PROD"

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-interventions-dev/resources/rds-postgres14.tf
Change to restore dev database from last Friday's snapshot.
> Ipb 1221 restore dev db

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-events-dev/resources/variables.tf
This namespace is about to be decommissioned.
> Delete reference to test2 namespace

- namespaces/live.cloud-platform.service.justice.gov.uk/alpha-cjs-va-dashboard-dev/resources/cross-iam-role-sa.tf
Hello - Updated the IRSA terraform file to rename service account.
> Create new service account name

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-person-record-dev/resources/cpr-delius-offender-events-queue.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-person-record-dev/resources/data.tf
Reverts ministryofjustice/cloud-platform-environments#24452
> Revert "CPR-388 Subscribe to correct topic DEV"

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-person-record-dev/resources/cpr-delius-offender-events-queue.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-person-record-dev/resources/data.tf
Reverts ministryofjustice/cloud-platform-environments#24532
> CPR-388 Subscribe to correct topic DEV

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-person-record-prod/resources/cpr-delius-offender-events-queue.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-person-record-prod/resources/data.tf
Reverts ministryofjustice/cloud-platform-environments#24479
> CPR-388 Use correct sns topic for delius PROD

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-person-record-preprod/resources/cpr-court-events-queue.tf
We think there are a lot of duplicate messages on the topic this queue subscribes to and hope that content based deduplication will identify them
> CPR-395 create FIFO queue for court events in preprod

- .checksum
- namespaces/live.cloud-platform.service.justice.gov.uk/monitoring-psc-app-dev/00-namespace.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/monitoring-psc-app-dev/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/monitoring-psc-app-dev/02-limitrange.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/monitoring-psc-app-dev/03-resourcequota.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/monitoring-psc-app-dev/04-networkpolicy.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/monitoring-psc-app-dev/resources/main.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/monitoring-psc-app-dev/resources/variables.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/monitoring-psc-app-dev/resources/versions.tf
Creating a new namespace for a dev app
> Create namespace for monitoring-psc-app

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-portfolio-management-prod/resources/serviceaccount.tf
> Add hmpps-github-actions-runner to github repos for hmpps-portfolio-management-prod

- namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-preprod/resources/rds.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-prod/resources/rds.tf
Change our instance class for our db from small to micro for prod environment
> Change the instance class for prison_visit_booker_registry_rds to be small 

- namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-preprod/resources/rds.tf
## What is the aim of this PR?
Change our instance class for our db from small to micro for preprod environment
> Change rds instance from micro to small for preprod database

- .checksum
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-civil-applications-datastore-uat/00-namespace.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-civil-applications-datastore-uat/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-civil-applications-datastore-uat/02-limitrange.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-civil-applications-datastore-uat/03-resourcequota.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-civil-applications-datastore-uat/04-networkpolicy.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-civil-applications-datastore-uat/resources/ecr.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-civil-applications-datastore-uat/resources/main.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-civil-applications-datastore-uat/resources/serviceaccount.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-civil-applications-datastore-uat/resources/variables.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-civil-applications-datastore-uat/resources/versions.tf
Setting up laa-civil-applications-datastore environment on cloudplatform as part of work done by team 5 in the hackathon 2024
> civil applications datastore: setting up environment on cloudplatform

- namespaces/live.cloud-platform.service.justice.gov.uk/rd-hr-smart-knowledge-management-dev/resources/irsa.tf
As explained here: https://github.com/moj-analytical-services/data-engineering-exports/tree/main
> Provide method to get IRSA data for pulling from AP S3 bucket

- namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-find-a-github-repository-owner-dev/resources/ecr.tf
- Fixes https://github.com/ministryofjustice/cloud-platform-environments/pull/24737
- Updated the repository name in the ecr.tf file to point to the correct repository
- NA
> 🔧 Fix Deployment By Adding Correct Repository Name

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-jobs-board-reporting-preprod/00-namespace.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-jobs-board-reporting-preprod/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-jobs-board-reporting-preprod/02-limitrange.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-jobs-board-reporting-preprod/03-resourcequota.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-jobs-board-reporting-preprod/04-networkpolicy.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-jobs-board-reporting-preprod/06-certificate.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-jobs-board-reporting-preprod/resources/elasticache.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-jobs-board-reporting-preprod/resources/main.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-jobs-board-reporting-preprod/resources/rds-postgresql.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-jobs-board-reporting-preprod/resources/serviceaccount-circleci.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-jobs-board-reporting-preprod/resources/variables.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-jobs-board-reporting-preprod/resources/versions.tf
Create Preprod namespace for jobs board reporting.
> Create job board reporting namespace

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-staging-api-preprod/00-namespace.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-staging-api-preprod/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-staging-api-preprod/02-limitrange.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-staging-api-preprod/03-resourcequota.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-staging-api-preprod/04-networkpolicy.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-staging-api-preprod/resources/ecr.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-staging-api-preprod/resources/main.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-staging-api-preprod/resources/secret.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-staging-api-preprod/resources/serviceaccount.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-staging-api-preprod/resources/variables.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-staging-api-preprod/resources/versions.tf
new namespace laa-ccms-staging-api-preprod
> new_env/laa-ccms-staging-api-preprod

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-staging-file-upload-api-preprod/00-namespace.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-staging-file-upload-api-preprod/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-staging-file-upload-api-preprod/02-limitrange.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-staging-file-upload-api-preprod/03-resourcequota.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-staging-file-upload-api-preprod/04-networkpolicy.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-staging-file-upload-api-preprod/resources/ecr.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-staging-file-upload-api-preprod/resources/main.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-staging-file-upload-api-preprod/resources/secret.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-staging-file-upload-api-preprod/resources/serviceaccount.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-staging-file-upload-api-preprod/resources/variables.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-staging-file-upload-api-preprod/resources/versions.tf
new preprod environment for laa-ccms-staging-file-upload-api
> new_env/laa-ccms-staging-file-upload-api-preprod

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-staging-api-uat/00-namespace.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-staging-api-uat/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-staging-api-uat/02-limitrange.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-staging-api-uat/03-resourcequota.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-staging-api-uat/04-networkpolicy.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-staging-api-uat/resources/ecr.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-staging-api-uat/resources/main.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-staging-api-uat/resources/secret.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-staging-api-uat/resources/serviceaccount.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-staging-api-uat/resources/variables.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-staging-api-uat/resources/versions.tf
new namespace laa-ccms-staging-api-uat
> new_env/laa-ccms-staging-api-uat

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-staging-file-upload-api-uat/00-namespace.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-staging-file-upload-api-uat/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-staging-file-upload-api-uat/02-limitrange.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-staging-file-upload-api-uat/03-resourcequota.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-staging-file-upload-api-uat/04-networkpolicy.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-staging-file-upload-api-uat/resources/ecr.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-staging-file-upload-api-uat/resources/main.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-staging-file-upload-api-uat/resources/secret.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-staging-file-upload-api-uat/resources/serviceaccount.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-staging-file-upload-api-uat/resources/variables.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-staging-file-upload-api-uat/resources/versions.tf
new namespace laa-ccms-staging-file-upload-api-uat
> new_env/laa-ccms-staging-file-upload-api-uat

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-pin-phone-monitor-prod/resources/rds-aurora.tf
Relates to [#5894](https://github.com/ministryofjustice/cloud-platform/issues/5894)
> chore: Bump RDS Aurora module to 4.0.0 in prod

- namespaces/live.cloud-platform.service.justice.gov.uk/create-and-vary-a-licence-test2/resources/serviceaccount.tf
Needs to be consistent with service account names in other environments
> Fixing service account name

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-contacts-dev/00-namespace.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-contacts-dev/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-contacts-dev/02-limitrange.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-contacts-dev/03-resourcequota.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-contacts-dev/04-networkpolicy.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-contacts-dev/06-certificate.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-contacts-dev/resources/domain-events-topic.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-contacts-dev/resources/elasticache.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-contacts-dev/resources/irsa.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-contacts-dev/resources/main.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-contacts-dev/resources/rds-postgresql.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-contacts-dev/resources/serviceaccount-circleci.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-contacts-dev/resources/variables.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-contacts-dev/resources/versions.tf
initial commit to create project templates and namespaces for hmpps contacts project
> Add hmpps-contacts-dev namespace

- namespaces/live.cloud-platform.service.justice.gov.uk/abundant-namespace-dev/resources/opensearch.tf
https://github.com/ministryofjustice/cloud-platform-terraform-opensearch/releases/tag/1.5.1
> chore: 🤖 bump opensearch in abdundant ns for new release check

- namespaces/live.cloud-platform.service.justice.gov.uk/cica-extraction-dev/resources/opensearch.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-datahub-catalogue-dev/resources/opensearch.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-datahub-catalogue-preprod/resources/opensearch.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-datahub-catalogue-prod/resources/opensearch.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-datahub-catalogue-test/resources/opensearch.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-delius-alfresco-dev/resources/opensearch.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-delius-alfrsco-poc/resources/opensearch.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-intelligence-preprod/resources/opensearch.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-intelligence-prod/resources/opensearch.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-intelligence-stage/resources/opensearch.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-intelligence-test/resources/opensearch.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-prisoner-profile-casenotes-search-prototype/resources/opensearch.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-prisoner-search-dev/resources/opensearch.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-prisoner-search-preprod/resources/opensearch.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-prisoner-search-prod/resources/opensearch.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-probation-search-preprod/resources/opensearch.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-probation-search-prod/resources/opensearch.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/intranet-demo/resources/opensearch.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/intranet-dev/resources/opensearch.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/intranet-staging/resources/opensearch.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/manage-intelligence-dev/resources/opensearch.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/peoplefinder-development/resources/opensearch.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/peoplefinder-production/resources/opensearch.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/peoplefinder-staging/resources/opensearch.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/prisoner-content-hub-development/resources/opensearch.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/prisoner-content-hub-production/resources/opensearch.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/prisoner-content-hub-staging/resources/opensearch.tf
https://github.com/ministryofjustice/cloud-platform-terraform-opensearch/releases/tag/1.5.1
> chore: 🤖 bump all env opensearch module versions (no-op)

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-data-migration-dev/resources/s3.tf
split s3 user to admin and upload
> laa-dces-dm-dev-split-user

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-ems-cemo-ui-dev/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-ems-cemo-ui-dev/resources/serviceaccount-circleci.tf
Configure hmpps-ems-cemo-ui-dev for SRE team access & deployment using CircleCI.
> Configure hmpps-ems-cemo-ui-dev for SRE team management

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-ems-cemo-ui-prod/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-ems-cemo-ui-prod/resources/serviceaccount-circleci.tf
Configure hmpps-ems-cemo-ui-prod for SRE team access & deployment using CircleCI.
> Configure hmpps-ems-cemo-ui-prod for SRE team management

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-ems-cemo-ui-preprod/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-ems-cemo-ui-preprod/resources/serviceaccount-circleci.tf
Configure hmpps-ems-cemo-ui-preprod for SRE team access & deployment using CircleCI.
> Configure hmpps-ems-cemo-ui-preprod for SRE team management

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-data-migration-dev/resources/s3.tf
deny get object from admin user as a test
> laa-dces-dm-dev-denyGetObject

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-data-migration-dev/resources/s3.tf
updating Upload user permission to restrict getObject
> laa-dces-dm-dev-changeUploadUser

- .checksum
- namespaces/live.cloud-platform.service.justice.gov.uk/llm-webapp-test-dev/00-namespace.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/llm-webapp-test-dev/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/llm-webapp-test-dev/02-limitrange.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/llm-webapp-test-dev/03-resourcequota.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/llm-webapp-test-dev/04-networkpolicy.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/llm-webapp-test-dev/resources/ecr.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/llm-webapp-test-dev/resources/main.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/llm-webapp-test-dev/resources/serviceaccount.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/llm-webapp-test-dev/resources/variables.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/llm-webapp-test-dev/resources/versions.tf
- Followed the guidance https://github.com/ministryofjustice/cloud-platform-environments.git.
- This PR contains all the steps.
> Creating a Cloud Platform dev environment for llm-webapp-test app

- namespaces/live.cloud-platform.service.justice.gov.uk/offender-events-dev/resources/offender_categorisation-sub-queue.tf
Hopefully this is correct, but is something of a guess as to how this process works.
> [SI-1091] Subscribe cat tool to prisoner released events

- namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-find-moj-data-dev/06-certificate.yaml
> Added dev certificate

- namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-prod/resources/certificates.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-prod/resources/iapdc-route53.tf
Please could you send the name server details for this zone once this has been merged. Thank you!
> IAPDC domain and certificates

- namespaces/live.cloud-platform.service.justice.gov.uk/intranet-staging/resources/opensearch.tf
This update attempts to fix an error on the application where the query is carrying too many search clauses.
> Increase number of clauses allowed in query

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-pin-phone-monitor-prod/resources/servicepod.tf
> Add service pod to pcms

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-demo/00-namespace.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-demo/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-demo/02-limitrange.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-demo/03-resourcequota.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-demo/04-networkpolicy.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-demo/06-certificates.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-demo/resources/irsa.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-demo/resources/main.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-demo/resources/rds.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-demo/resources/serviceaccount-circleci.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-demo/resources/servicepod.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-demo/resources/variables.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-demo/resources/versions.tf
Adds a new demo environment for community accomodation services - the purpose of this is to create a stable environment in which to develop a really solid set of testing data that can be used for local testing where large amounts of (non prod) data are required.
> add community accomodation services demo environment

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-events-dev/resources/hmpps-eduation-and-work-plan.tf
This PR corrects the subscription setup earlier in PR #25088 for prisoner events.
In my earlier PR I setup the subscription for `prisoner-offender-search....`, but it should have been `prisoner-offender-events.....`
> RR-920 - Subscribe to prisoner-offender-events

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-events-dev/resources/hmpps-eduation-and-work-plan.tf
This PR corrects my previous PR #25089 by fixing a typo in the message event types!
I originally had it as `prisoner-offender-events.....`, but it should be `prison-offender-events.....`
(prison, not prison**er**)
Third time's a charm! 🙄
> RR-920 - Subscribe to prison-offender-events

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-equinity-historical-data-uat/04-networkpolicy.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-equinity-historical-data-uat/06-service-monitor.yaml
Add Service Monitor and Network Rules for  Prometheus  Scrapping on UAT for Equiniti Historical Data project
> EMP-182: Add prometheus UAT

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-ems-cemo-ui-dev/resources/main.tf
Give github team `hmpps-electronic-monitoring` access to AWS resources in namespace `hmpps-ems-cemo-ui-dev`.
> Update AWS permissions in namespace hmpps-ems-cemo-ui-dev

- namespaces/live.cloud-platform.service.justice.gov.uk/tim-development/resources/oracle_db.tf
Test if we can specify major version but no minor version for Oracle DB
> chore: Test oracle

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-equinity-historical-data-prod/04-networkpolicy.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-equinity-historical-data-prod/06-service-monitor.yaml
EMP-439: Adding ServiceMonitor and NetworkPolicy for Prometheus in PROD
> EMP-439: Adding ServiceMonitor and NetworkPolicy for Prometheus in PROD

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-ems-cemo-ui-dev/06-rbac-haar-client-admin-team.yaml
Grant the client admin team permission to access secrets in namespace hmpps-ems-cemo-ui-dev.
> Give the client admin team permissions in hmpps-ems-cemo-ui-dev

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-ems-cemo-ui-preprod/06-rbac-haar-client-admin-team.yaml
Grant the client admin team permission to access secrets in namespace hmpps-ems-cemo-ui-preprod.
> Give the client admin team permissions in hmpps-ems-cemo-ui-preprod

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-ems-cemo-ui-prod/06-rbac-haar-client-admin-team.yaml
Grant the client admin team permission to access secrets in namespace hmpps-ems-cemo-ui-prod.
> Give the client admin team permissions in hmpps-ems-cemo-ui-prod

- namespaces/live.cloud-platform.service.justice.gov.uk/tim-development/resources/oracle_db.tf
Test if we can specify major version but not minor version for oracle db
> Test Oracle

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-preprod/resources/rds.tf
Following on from [this pr](https://github.com/ministryofjustice/cloud-platform-environments/pull/25172) 
I thought I would draft one for the pre-prod environment as well.
> increase cas preprod db instance type

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-person-record-dev/resources/cpr-nomis-merge-events-queue.tf
edited eventype to prisoner-offender-events.prisoner.merged
> CPR-334 Create nomis merge queue DEV

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-hmrc-interface-uat/resources/rds.tf
> HMRC Interface UAT - update RDS minor version

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-uat/resources/secret.tf
DCES-243: Create mTLS related secrets for DCES-DRC integration project for UAT environment
> DCES-243: Create mTLS related secrets

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-assure-hmrc-data-uat/resources/rds-postgresql.tf
> HMRC Data UAT - update RDS minor version

- namespaces/live.cloud-platform.service.justice.gov.uk/legal-framework-api-staging/resources/rds.tf
> Legal Frameowrk STG - update RDS minor version

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-hmrc-interface-staging/resources/rds.tf
> HMRC Interface STG - update RDS minor version

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-assure-hmrc-data-staging/resources/rds-postgresql.tf
> HMRC Data STG - update RDS minor version

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-staging/resources/rds.tf
> Civil Apply STG - update RDS minor version

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-prisoner-from-nomis-migration-dev/resources/hmpps-prisoner-from-nomis-courtsentencing-sub-queue.tf
> SDIT-1909 case insert dev

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-production/resources/rds.tf
> Civil Apply PROD - update RDS minor version

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-assure-hmrc-data-production/resources/rds-postgresql.tf
> HMRC Data PROD - update RDS minor version

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-hmrc-interface-production/resources/rds.tf
> HMRC Interface PROD - update RDS minor version

- namespaces/live.cloud-platform.service.justice.gov.uk/legal-framework-api-production/resources/rds.tf
> Legal Framework PROD - update RDS minor version

- namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-kpi-dashboard-poc/resources/ecr.tf
- In relation to https://github.com/ministryofjustice/cloud-platform-environments/pull/25330
- To disable ECR Deletion Protection before removing the namespace
- Disabled ECR Deletion Protection
> 🔥 Remove ECR Deletion Protection for `operations-engineering-kpi-dashboard-poc`

- namespaces/live.cloud-platform.service.justice.gov.uk/justice-gov-uk-production/resources/irsa.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/justice-gov-uk-production/resources/rds-tmp.tf
cc @wilson1000 fyi, there is no way to restore from a snapshot after db is created. It has to be done at the time of db provisioning... hence this PR.
I'll get there eventually!
> justice-gov-uk-production. Create temp. db. Use snapshot_identifier property.

- namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-test-dev/resources/user-filestore.tf
I want to interact with the s3 bucket this component uses to help replicate an issue and test possible causes.
This is a test environment
> Add a service pod with the same s3 irsa access as user filestore 

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-submit-crime-forms-uat/resources/rds-postgresql.tf
Do not mergeuntil primary DB upgrade to 16.4
> Upgrade db read replica 16.1 to 16.4 [provider UAT]

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-submit-crime-forms-dev/resources/variables.tf
required for bitnmai postgres helm chart bump
from 11.9.13 to 15+
> Add poddisruptionbudget to policy API group [provider UAT]

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-application-store-uat/resources/rds-postgresql.tf
Also disable auto minor version upgrades
> UAT App Store: Upgrade DB to 16.4

- namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-prod/resources/hmpps-prison-visits-event.tf
Enable prisoner transferred events in production for Visits services
https://dsdmoj.atlassian.net/browse/VB-3590
> VB-3590 - Enable prisoner transferred events in production for Visits services

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-audit-dev/resources/hmpps-contacts.tf
[PRC-9](https://dsdmoj.atlassian.net/browse/PRC-9) : Audit queue integration
[PRC-9]: https://dsdmoj.atlassian.net/browse/PRC-9?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PRC-9 : Audit queue integration

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-application-store-uat/resources/rds-postgresql.tf
undo previous changes that [failed here](https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/environments-live/jobs/apply-namespace-changes-live/builds/6679)
> app store UAT: Revert changes to start fresh

- namespaces/live.cloud-platform.service.justice.gov.uk/tim-development/resources/sns.tf
create non-fifo sns with new testing branch
> chore: Add sns with new branch

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-person-record-preprod/resources/cpr-court-case-events-fifo-topic.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-person-record-prod/resources/cpr-court-case-events-fifo-topic.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/tim-development/resources/sns.tf
- To prevent the deleted branch from blocking apply pipeline
> chore: Bump sns module version

- namespaces/live.cloud-platform.service.justice.gov.uk/sw-psa-audit-test/resources/rds.tf
relates to ministryofjustice/cloud-platform#6068
> chore: 🤖 enable replica

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-fala-production/07-prometheus-custom-rules.yaml
Add Production Prometheus alert to match staging one
> EL-1420 FALA Production Prometheus Alert

- namespaces/live.cloud-platform.service.justice.gov.uk/sw-psa-audit-test/resources/rds.tf
relates to https://github.com/ministryofjustice/cloud-platform/issues/6068
> chore: 🤖 wip

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-uat/resources/rds.tf
> Rename rds module to trigger rebuild of database

- namespaces/live.cloud-platform.service.justice.gov.uk/sw-psa-audit-test/resources/rds.tf
> chore: 🤖 add testing rds for replica upgrade

- namespaces/live.cloud-platform.service.justice.gov.uk/sw-psa-audit-test/resources/rds.tf
> chore: 🤖 updating replica config

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-assess-crime-forms-dev/resources/variables.tf
required by bitnami postgres chart 15+ (pg 16.4+)
> CRM457-1908: Add poddisruptionbudgets to service account privs Assess DEV

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-application-store-dev/resources/variables.tf
Require by bitnami postgres chart 15+ (pg 16.4+)
> CRM457-1908: Add poddisruptionbudgets privs to service account Appstore DEV

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-dev/resources/api_gateway-assume-role-endpoint.tf
> PI-2447 Update role name

- namespaces/live.cloud-platform.service.justice.gov.uk/track-a-query-production/resources/rds.tf
Also added Delete Protection parameter
> Track a Query Production - Upgrade DB instance to medium

- namespaces/live.cloud-platform.service.justice.gov.uk/sw-psa-audit-test/resources/rds.tf
> chore: 🤖 testing replica-first upgrade flow

- namespaces/live.cloud-platform.service.justice.gov.uk/sw-psa-audit-test/resources/rds.tf
> chore: 🤖 test primary rds upgrade post replica

- namespaces/live.cloud-platform.service.justice.gov.uk/aaf-dev/resources/steve-rds.tf
> Test rds no minor version

- namespaces/live.cloud-platform.service.justice.gov.uk/aaf-dev/resources/steve-rds.tf
> chore: 🤖 test replica with no minor version spec

- namespaces/live.cloud-platform.service.justice.gov.uk/aaf-dev/resources/steve-rds.tf
> chore: 🤖 try bumping replica scenario 2

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-data-migration-dev/resources/rds-postgresql.tf
config upadte to stop db shutting down overnight
> dontshutdownovernight

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-uat/resources/secret.tf
These secrets are not necessary for DCES-DRC integration project (UAT environment)
> DCES-243: Remove recently added mTLS related secrets 

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-dev/resources/api_gateway-assume-role-endpoint.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-dev/resources/api_gateway.tf
> PI-2447 Set API Gateway integration method to GET

- namespaces/live.cloud-platform.service.justice.gov.uk/aaf-dev/resources/steve-rds.tf
> chore: 🤖 test bumping minor version primary rds

- namespaces/live.cloud-platform.service.justice.gov.uk/cica-copilot-dev/IAMRole.tf
Change aws region for aws provider
> Change aws region for aws provider

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-submit-crime-forms-prod/resources/rds-postgresql.tf
ticket https://dsdmoj.atlassian.net/browse/CRM457-1907
> CRM457-1907: Upgrade postgres DB 16.1 to 16.4 for Submit PROD

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-assess-crime-forms-prod/resources/rds-postgresql.tf
ticket https://dsdmoj.atlassian.net/browse/CRM457-1907
> CRM457-1907: Upgrade postgres DB 16.1 to 16.4 for Assess PROD

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-submit-crime-forms-prod/resources/rds-postgresql.tf
cloud platform guide says it should not have this version
component.
> CRM457-1907: Remove DB engine version minor component Submit PROD

- namespaces/live.cloud-platform.service.justice.gov.uk/davidconneely-sandbox-dev/00-namespace.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/davidconneely-sandbox-dev/resources/secrets.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/davidconneely-sandbox-dev/resources/variables.tf
- Add secrets to davidconneely-sandbox
- Fixed Slack channel name
- Extend review-after-date as still learning with and using this namespace
- Add missing `eks_cluster_name` variable needed by secrets module
> Add secrets to davidconneely-sandbox

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-staging-api-production/00-namespace.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-staging-api-production/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-staging-api-production/02-limitrange.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-staging-api-production/03-resourcequota.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-staging-api-production/04-networkpolicy.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-staging-api-production/resources/ecr.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-staging-api-production/resources/main.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-staging-api-production/resources/secret.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-staging-api-production/resources/serviceaccount.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-staging-api-production/resources/variables.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-staging-api-production/resources/versions.tf
new_env/laa-ccms-staging-api-production
> new_env/laa-ccms-staging-api-production

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-staging-file-upload-api-production/00-namespace.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-staging-file-upload-api-production/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-staging-file-upload-api-production/02-limitrange.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-staging-file-upload-api-production/03-resourcequota.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-staging-file-upload-api-production/04-networkpolicy.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-staging-file-upload-api-production/resources/ecr.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-staging-file-upload-api-production/resources/main.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-staging-file-upload-api-production/resources/secret.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-staging-file-upload-api-production/resources/serviceaccount.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-staging-file-upload-api-production/resources/variables.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-staging-file-upload-api-production/resources/versions.tf
new_env/laa-ccms-staging-file-upload-api-production
> new_env/laa-ccms-staging-file-upload-api-production

- namespaces/live.cloud-platform.service.justice.gov.uk/cica-copilot-dev/IAMRole.tf
Fix aws region for cloud platform role
> Fix aws region for cloud platform role

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-cwa-deployments-test/00-namespace.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-cwa-deployments-test/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-cwa-deployments-test/02-limitrange.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-cwa-deployments-test/03-resourcequota.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-cwa-deployments-test/04-networkpolicy.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-cwa-deployments-test/resources/ecr.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-cwa-deployments-test/resources/irsa.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-cwa-deployments-test/resources/main.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-cwa-deployments-test/resources/s3.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-cwa-deployments-test/resources/secret.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-cwa-deployments-test/resources/serviceaccount.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-cwa-deployments-test/resources/variables.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-cwa-deployments-test/resources/versions.tf
Add deployment namespace for test env for CWA application
> Add deployment namespace for test env CWA

- namespaces/live.cloud-platform.service.justice.gov.uk/calculate-release-dates-api-prod/resources/rds.tf
Add a new RDS Instance using guides from:
https://github.com/ministryofjustice/cloud-platform-terraform-rds-instance?ref=7.0.0 https://user-guide.cloud-platform.service.justice.gov.uk/documentation/deploying-an-app/relational-databases/upgrade.html#upgrading-to-a-new-major-database-version-upgrade-paths
> RDS Instance with new sizing

- namespaces/live.cloud-platform.service.justice.gov.uk/james-dev/resources/serviceaccount.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/james-dev/resources/versions.tf
Adding james-dev-sa for james-dev namespace
> add james-dev-sa service account for github actions

- namespaces/live.cloud-platform.service.justice.gov.uk/san-dev/06-certificate.yml
> Added eleventy test cert

- .checksum
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-equinity-historical-data-archive/00-namespace.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-equinity-historical-data-archive/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-equinity-historical-data-archive/02-limitrange.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-equinity-historical-data-archive/03-resourcequota.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-equinity-historical-data-archive/04-networkpolicy.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-equinity-historical-data-archive/06-service-monitor.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-equinity-historical-data-archive/resources/main.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-equinity-historical-data-archive/resources/secret.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-equinity-historical-data-archive/resources/serviceaccount.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-equinity-historical-data-archive/resources/variables.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-equinity-historical-data-archive/resources/versions.tf
EMP-469: Add new namespace "Archive" for Equality Historical Data project
> EMP-469: Add new namespace "Archive" for Equality Historical Data project

- namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-preprod/resources/secrets-manager.tf
Update the application insights key name
> court-case-service Update secret key name for PreProd

- namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-preprod/resources/secrets-manager.tf
Reverts ministryofjustice/cloud-platform-environments#25675
> Revert "court-case-service Update secret key name for PreProd"

- namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-preprod/resources/secrets-manager.tf
Delete secret as a workaround for renaming it. (i tried to rename it in a previous PR but the build failed)
> court-case-service-preprod Delete secret 

- namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-preprod/resources/secrets-manager.tf
Add application insights connection string secret for Preprod
> court-case-service-preprod Add application insights secret

- namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-prod/resources/secrets-manager.tf
remove secret that is not being used and is incorrectly named
> court-case-service-PROD Remove incorrectly named secret

- namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-prod/resources/secrets-manager.tf
Add application insights secret
> court-case-service Update secret key name for Prod

- namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-datahub-catalogue-test/resources/rds-postgresql.tf
chore: turning off major upgrade prep vars
> chore: refining RDS variables - DataHub test

- namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-datahub-catalogue-preprod/resources/rds-postgresql.tf
chore: turning off major upgrade prep vars
> chore: refining RDS variables - DataHub preprod

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-application-store-production/resources/rds-postgresql.tf
> CRM457-1907: Bump primary postgres DB 16.1 to 16.4 appstore PROD

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-jobs-board-dev/resources/scheduled-downtime.tf
Schedule database downtime in accordance to MoJ [guidelines](https://github.com/ministryofjustice/hmpps-helm-charts/tree/main/charts/generic-service#scheduled-downtime)
Environment: **DEV**
> Schedule rds downtime

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-jobs-board-preprod/resources/scheduled-downtime.tf
Schedule database downtime in accordance to MoJ [guidelines](https://github.com/ministryofjustice/hmpps-helm-charts/tree/main/charts/generic-service#scheduled-downtime)
Environment: **Pre-prod**
> [ESWE-1055] Schedule rds downtime

- namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-find-moj-data-dev/05-prometheusrule.yaml
1. bump up the threshold for latency alerts
2. replace CPU alert with an autoscaler alert
> Make Find MoJ data dev alerts more forgiving (dev)

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-litigator-fees-dev/resources/rds.tf
* Adds additional CIDR range for non-production workspace: `10.200.0.0/20`
> Add additional LAA LZ IP range to CCLF dev RDS Security Group

- namespaces/live.cloud-platform.service.justice.gov.uk/stability-inspector-dev/00-namespace.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/stability-inspector-dev/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/stability-inspector-dev/02-limitrange.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/stability-inspector-dev/03-resourcequota.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/stability-inspector-dev/04-networkpolicy.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/stability-inspector-dev/resources/ecr.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/stability-inspector-dev/resources/main.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/stability-inspector-dev/resources/push_gateway.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/stability-inspector-dev/resources/service_account.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/stability-inspector-dev/resources/variables.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/stability-inspector-dev/resources/versions.tf
> Initialise Stability Inspector

- namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-find-moj-data-prod/05-prometheusrule.yaml
Replicate the changes already made to dev
- Monitor number of pods
- Raise the threshold for latency alerts
> Tweak find moj data alerts for prod

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-litigator-fees-uat/APPLY_PIPELINE_SKIP_THIS_NAMESPACE
pipeline d is failing due to the instance being stopped
https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/environments-live/jobs/apply-live-d/builds/3309
> chore: 🤖 add skip file

- namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-prod/resources/advance-into-justice-route53.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-prod/resources/certificates.tf
Please could you send Name server details once merged
> Add advance-into-justice domain

- .checksum
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-dummy-drc-dev/00-namespace.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-dummy-drc-dev/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-dummy-drc-dev/02-limitrange.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-dummy-drc-dev/03-resourcequota.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-dummy-drc-dev/04-networkpolicy.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-dummy-drc-dev/resources/ecr.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-dummy-drc-dev/resources/main.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-dummy-drc-dev/resources/serviceaccount.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-dummy-drc-dev/resources/variables.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-dummy-drc-dev/resources/versions.tf
for use with laa-dces-integration project.
> New namespace for the Dummy DRC API application 

- namespaces/live.cloud-platform.service.justice.gov.uk/tst-em-example-app-jkn-dev/00-namespace.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/tst-em-example-app-jkn-dev/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/tst-em-example-app-jkn-dev/02-limitrange.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/tst-em-example-app-jkn-dev/03-resourcequota.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/tst-em-example-app-jkn-dev/04-networkpolicy.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/tst-em-example-app-jkn-dev/resources/ecr.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/tst-em-example-app-jkn-dev/resources/main.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/tst-em-example-app-jkn-dev/resources/serviceaccount.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/tst-em-example-app-jkn-dev/resources/variables.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/tst-em-example-app-jkn-dev/resources/versions.tf
Following the tutorial for the example cloud application
> initial setup of example application

- namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-dev/resources/irsa.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-dev/resources/service-pod.tf
This will be used by court-hearing-event-receiver and crime-portal-gateway
Future PRs will remove these S3 and SNS permissions from the court-case-service IRSA
> PIC-4134 create new IRSA with SNS and S3 permissions

- namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-prod/resources/advance-into-justice-route53.tf
Fix formatting to output more clear with comma
> Change to separate data using comma

- namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-prod/resources/certificates.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-prod/resources/legalaidlearning-route53.tf
Please could you send Name server details once merged
> Hale Platform - add legalaidlearning route 53 and certs

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-production/resources/rds.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-prod/resources/rds.tf
```
operation error RDS: ModifyDBInstance, https response error StatusCode: 400, RequestID: d259833d-ee73-45bf-a078-209e8d55195b, api error InvalidParameterCombination: Cannot upgrade oracle-se2 from 19.0.0.0.ru-2024-07.rur-2024-07.r1 to 19.0.0.0.ru-2024-04.rur-2024-04.r1
```
```
operation error RDS: ModifyDBInstance, https response error StatusCode: 400, RequestID: 9ffc2447-2331-43d8-812d-40bfea1b6ad9, api error InvalidParameterCombination: Cannot upgrade postgres from 15.7 to 15.5
```
> chore: 🤖 fix rds version

- namespaces/live.cloud-platform.service.justice.gov.uk/legal-framework-api-production/resources/secret.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/legal-framework-api-production/resources/variables.tf
Add secret file to legal-framework-api production environment
> AP-5156: Add secret file to production

- namespaces/live.cloud-platform.service.justice.gov.uk/legal-framework-api-staging/resources/secret.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/legal-framework-api-staging/resources/variables.tf
Add secret file to legal-framework-api staging environment
> AP-5156: Add secret file to staging

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-staging/resources/rds.tf
https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/environments-live/jobs/apply-live-d/builds/3323
> chore: 🤖 pin db

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-uat/resources/rds.tf
https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/environments-live/jobs/apply-live-d/builds/3324
> chore: 🤖 fix rds

- namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-live-dev/resources/user-datastore.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-person-record-prod/resources/rds.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-welcome-to-prison-prod/resources/rds.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/licences-dev/resources/rds.tf
> fix: 🐛 pipelines

- namespaces/live.cloud-platform.service.justice.gov.uk/licences-preprod/resources/rds.tf
https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/environments-live/jobs/apply-live-e/builds/3337
> fix: 🐛 rds version

- namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-test-dev/resources/submitter.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/offender-management-production/resources/rds.tf
https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/environments-live/jobs/apply-live-b/builds/3335
https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/environments-live/jobs/apply-live-e/builds/3340
> fix: 🐛 rds minor versions

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-dummy-drc-dev/resources/ecr.tf
Replacing Github Actions with CircleCI
> Added CircleCI config to ecr.tf

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-ems-cemo-ui-dev/resources/hmpps-audit-queue.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-ems-cemo-ui-dev/resources/irsa.tf
In `hmpps-ems-cemo-ui-dev`:
- Configure `irsa.tf`
- Add a missing parameter `sqs_queue_url` to `hmpps-audit-queue.tf`
> Configure IRSA in hmpps-ems-cemo-ui-dev

- namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-saas-test/resources/editor.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/send-legal-mail-to-prisons-dev/resources/rds.tf
https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/environments-live/jobs/apply-live-b/builds/3337
https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/environments-live/jobs/apply-live-e/builds/3341
> Fix pipeline 5

- namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-preprod/resources/rds.tf
https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/environments-live/jobs/apply-live-e/builds/3342
> chore: 🤖 fix tf rds version mismatch

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-preprod/resources/rds.tf
relates to ministryofjustice/cloud-platform#6068
> chore: 🤖 bump preprod read replica

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-production/resources/rds.tf
relates to ministryofjustice/cloud-platform#6068
> chore: 🤖 bump prod secure-move read replica

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-interventions-preprod/resources/rds-postgres14.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-interventions-prod/resources/rds-postgres14.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/peoplefinder-production/resources/rds.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/track-a-query-production/resources/rds.tf
relates to ministryofjustice/cloud-platform#6068
> chore: 🤖 bump remaining replica rds instances

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-delius-alfresco-preprod/resources/amq.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-delius-alfresco-stage/resources/amq.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-delius-alfrsco-poc/resources/amq.tf
relates to ministryofjustice/cloud-platform#6030
> feat: 🎸 add new eks subnets to amq security groups

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-candidate-matching-prod/resources/rds.tf
https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/environments-live/jobs/apply-live-b/builds/3338
> chore: 🤖 fix terraform rds version mismatch

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-dev/resources/iam.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-dev/resources/irsa.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-dev/resources/s3_advantis.tf
Scripts to create a s3 bucket, which will be used to share and upload secure files with a external 3rd party.
The 3rd party will also be able to upload and download files.
The bucket is secured using Kubernetes secrets.
Please review carefully as this is my first terraform script and the bucket needs to be secure.
> chore: created a s3 bucket to share files with 3rd party securely

- namespaces/live.cloud-platform.service.justice.gov.uk/certificated-bailiffs-prod/resources/rds-postgresql.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-saas-live/resources/metadata_api.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-education-employment-prod/resources/rds.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-user-preferences-preprod/resources/rds.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/makeaplea-preprod/resources/rds.tf
Fix for job failures  in apply pipelines:-
https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/environments-live/jobs/apply-live-d/builds/3405
https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/environments-live/jobs/apply-live-c/builds/3408
https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/environments-live/jobs/apply-live-a/builds/3414
https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/environments-live/jobs/apply-live-e/builds/3411
https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/environments-live/jobs/apply-live-b/builds/3405
> rds version changes to fix terraform drift

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-cla-backend-production/resources/rds.tf
Reduced db_instance_class and db_allocated_storage
> laa-cla-backend-production: Reduce RDS instance class

- namespaces/live.cloud-platform.service.justice.gov.uk/abundant-namespace-dev/resources/aurora.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-intelligence-preprod/resources/rds-aurora.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-intelligence-preprod/resources/rds-legacy.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-intelligence-prod/resources/rds-aurora.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-intelligence-prod/resources/rds-legacy.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-intelligence-stage/resources/rds-aurora.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-intelligence-stage/resources/rds-legacy.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-intelligence-test/resources/rds-aurora.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-intelligence-test/resources/rds-legacy-test-gen.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-intelligence-test/resources/rds-legacy.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-pin-phone-monitor-dev/resources/rds-aurora.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-pin-phone-monitor-prod/resources/rds-aurora.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-pin-phone-monitor-qa/resources/rds-aurora.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/manage-intelligence-dev/resources/rds-aurora.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/manage-intelligence-dev/resources/rds-legacy-test-gen.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/manage-intelligence-dev/resources/rds-legacy.tf
[release notes](https://github.com/ministryofjustice/cloud-platform-terraform-rds-aurora/releases/tag/4.2.0)
> chore: 🤖 fix aurora module release for subnets

- namespaces/live.cloud-platform.service.justice.gov.uk/grc-dev/resources/s3.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/grc-dev/resources/variables.tf
> GRC: update dev s3 role access

- namespaces/live.cloud-platform.service.justice.gov.uk/justice-gov-uk-design-system/resources/s3.tf
> CDPT-1854: Create a cloud platform stack to deploy storybook

- namespaces/live.cloud-platform.service.justice.gov.uk/tim-development/resources/rds.tf
> chore: create testing rds

- namespaces/live.cloud-platform.service.justice.gov.uk/tim-development/resources/rds.tf
- testing upgrade to gp3 storage type
> test: upgrade to gp3 storage type

- namespaces/live.cloud-platform.service.justice.gov.uk/certificated-bailiffs-preprod/resources/rds-postgresql.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmcts-complaints-formbuilder-adapter-production/resources/rds.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-interventions-preprod/resources/rds-postgres14.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/iac-fees-prod/resources/rds-postgresql.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/make-recall-decision-prod/resources/postgresql.tf
https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/environments-live/jobs/apply-live-a/builds/3439
NS certificated-bailiffs-preprod
https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/environments-live/jobs/apply-live-d/builds/3430
NS iac-fees-prod
https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/environments-live/jobs/apply-live-e/builds/3436
NS make-recall-decision-prod
https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/environments-live/jobs/apply-live-c/builds/3433
NS hmpps-interventions-preprod
https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/environments-live/jobs/apply-live-b/builds/3431
NS hmcts-complaints-formbuilder-adapter-production
> updated rds engine version to fix terraform drift

- namespaces/live.cloud-platform.service.justice.gov.uk/tim-development/resources/rds.tf
- implement maintenance window for testing rds
> chore: test maintenance window

- namespaces/live.cloud-platform.service.justice.gov.uk/tim-development/resources/rds.tf
- switch to io2 storage type for test rds
> switch to io2 storage type for test rds

- namespaces/live.cloud-platform.service.justice.gov.uk/tim-development/resources/rds.tf
> fix: add db storage size

- namespaces/live.cloud-platform.service.justice.gov.uk/cccd-dev/resources/messaging.tf
to allow access to the new cloud platform CCLF dev environment.
> Update cccd-dev messaging.tf

- namespaces/live.cloud-platform.service.justice.gov.uk/cccd-staging/resources/messaging.tf
to allow access to the new cloud platform CCLF uat environment.
> Update cccd-staging messaging.tf

- namespaces/live.cloud-platform.service.justice.gov.uk/cccd-production/resources/messaging.tf
to allow access to the new cloud platform CCLF production environment.
> Update cccd-production messaging.tf

- namespaces/live.cloud-platform.service.justice.gov.uk/stability-inspector-dev/00-namespace.yaml
Add namespace label according to docs: https://user-guide.cloud-platform.service.justice.gov.uk/documentation/networking/network-policy.html
> stability-inspector-dev Add namespace label

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-litigator-fees-dev/resources/rds.tf
Allows connections from legacy Oracle applications
> Set DB parameters in CCLF dev RDS

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-litigator-fees-uat/resources/rds.tf
Allows connections from legacy Oracle applications
> Set DB parameters in CCLF UAT RDS

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-litigator-fees-staging/resources/rds.tf
Allows connections from legacy Oracle applications
> Set DB parameters in CCLF staging RDS

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-person-record-prod/resources/rds.tf
changed rds instance from t3 to r6gd
> CPR-460-optimized-read

- .checksum
- namespaces/live.cloud-platform.service.justice.gov.uk/c100-application-dev/00-namespace.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/c100-application-dev/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/c100-application-dev/02-limitrange.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/c100-application-dev/03-resourcequota.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/c100-application-dev/04-networkpolicy.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/c100-application-dev/resources/ecr.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/c100-application-dev/resources/irsa.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/c100-application-dev/resources/main.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/c100-application-dev/resources/rds.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/c100-application-dev/resources/redis.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/c100-application-dev/resources/s3.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/c100-application-dev/resources/serviceaccount-circleci.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/c100-application-dev/resources/variables.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/c100-application-dev/resources/versions.tf
We need to have an environment, where we can deploy the code without merging it to master. I was advised to create dev environment. I generate the folder via cloud-platform command and then added other files to replicate what we have in staging.
> Adding development env for C100 application

- namespaces/live.cloud-platform.service.justice.gov.uk/c100-application-dev/resources/ecr.tf
> Updating name for ecr

- namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-dev/resources/irsa.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-dev/resources/service-pod.tf
Keep the irsa module as is.
Rename irsa module court-facing-api-irsa which will be used by other services with less aws resource accesses
> PIC-4134 Rearrange config to reduce change in DEV

- namespaces/live.cloud-platform.service.justice.gov.uk/manage-soc-cases-prod/resources/rds.tf
``` Fix Terraform RDS version drift. Here are the RDS version mismatches: 
```
> Fix: rds version mismatch in manage-soc-cases-prod

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-demo/resources/elasticache.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-demo/resources/variables.tf
This was omitted when the environment was created by mistake
> adds elasticache to CAS demo environment

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-access-civil-legal-aid-dev/05-github-actions-runner.yaml
Creates a self runner for the LAA access civil legal aid dev environment.
> Add runner for access dev

- .checksum
- namespaces/live.cloud-platform.service.justice.gov.uk/pola-production/00-namespace.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/pola-production/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/pola-production/02-limitrange.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/pola-production/03-resourcequota.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/pola-production/04-networkpolicy.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/pola-production/resources/main.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/pola-production/resources/variables.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/pola-production/resources/versions.tf
create prod env for a new digital service
> create POLA Production environment

- .checksum
- namespaces/live.cloud-platform.service.justice.gov.uk/pola-staging/00-namespace.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/pola-staging/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/pola-staging/02-limitrange.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/pola-staging/03-resourcequota.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/pola-staging/04-networkpolicy.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/pola-staging/resources/main.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/pola-staging/resources/variables.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/pola-staging/resources/versions.tf
new staging environment for POLA
> create POLA staging namespace

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-assess-risks-and-needs-integrations-test/00-namespace.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-assess-risks-and-needs-integrations-test/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-assess-risks-and-needs-integrations-test/02-limitrange.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-assess-risks-and-needs-integrations-test/03-resourcequota.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-assess-risks-and-needs-integrations-test/04-networkpolicy.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-assess-risks-and-needs-integrations-test/05-certificates.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-assess-risks-and-needs-integrations-test/06-rbac-haar-client-admin-team.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-assess-risks-and-needs-integrations-test/resources/elasticache.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-assess-risks-and-needs-integrations-test/resources/main.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-assess-risks-and-needs-integrations-test/resources/serviceaccount.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-assess-risks-and-needs-integrations-test/resources/variables.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-assess-risks-and-needs-integrations-test/resources/versions.tf
_Note - this is to replace `hmpps-assess-risks-and-needs-handover-service-test` namespace, which will be removed in a follow-up PR_
Added `hmpps-assess-risks-and-needs-integrations-test` namespace
> Add ARNS Integrations Test namespace

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-assess-risks-and-needs-handover-service-dev/resources/ecr.tf
Pre-PR for https://github.com/ministryofjustice/cloud-platform-environments/pull/26336
> Disable ECR deletion-protection for ARNS Handover Service Dev

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-person-record-prod/resources/rds.tf
updated version from 7.2.0 to 7.3.0
> CPR-460-new-rds-instance-version

- namespaces/live.cloud-platform.service.justice.gov.uk/intranet-production/02-limit-range.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/intranet-production/resources/ecr.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/intranet-production/resources/elasticache.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/intranet-production/resources/opensearch.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/intranet-production/resources/rds.tf
> intranet-production Resize resources & provision Elasticache

- namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-certificate-form/00-namespace.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-certificate-form/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-certificate-form/02-limitrange.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-certificate-form/03-resourcequota.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-certificate-form/04-networkpolicy.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-certificate-form/resources/ecr.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-certificate-form/resources/main.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-certificate-form/resources/serviceaccount.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-certificate-form/resources/variables.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-certificate-form/resources/versions.tf
This PR creates a new namespace for the application operations-engineering-certificate-form.
> Add new namespace: operations-engineering-certificate-form

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-prod/resources/messaging-queues.tf
The following is now redundant so we want to remove the config from prod:
laa_status_update_queue
laa_status_update_queue_policy
laa_status_update_dead_letter_queue
> Remove redundant sqs config from prod

- namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-certificate-form/resources/variables.tf
Autogenerated Terraform used the wrong value for the repository name, this PR is to fix that.
> :recycle: Corrected Default Repository Value

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-staging/resources/main.tf
This is to enable AWS secret management
> Civil Apply Staging: Add github tags to AWS

- namespaces/live.cloud-platform.service.justice.gov.uk/cccd-dev/APPLY_PIPELINE_SKIP_NAMESPACE
https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/environments-live/jobs/apply-live-a/builds/3607
> ci: 🎡 unblock pipeline a with skipfile for `cccd-dev` ns

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-uat/resources/main.tf
Add github team name tags in preparation for adding external secret
> ap-5325: add github team name tags

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-nomis-mapping-service-preprod/resources/rds.tf
Tweak to cut down the database to match prod size
> SDIT-2062 Upgrade prod mapping DB - PREPROD

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-proceeding-dev/resources/secret.tf
Added the following secrets to CCP dev:
- sentry_dsn
- prosecution_concluded_db_username
- email_client_notify_key
> Added secrets to ccp dev

- .checksum
- namespaces/live.cloud-platform.service.justice.gov.uk/kiril-dev/00-namespace.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/kiril-dev/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/kiril-dev/02-limitrange.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/kiril-dev/03-resourcequota.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/kiril-dev/04-networkpolicy.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/kiril-dev/resources/main.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/kiril-dev/resources/variables.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/kiril-dev/resources/versions.tf
learning how to create namespaces in cloud platform
> Created namespace for a test cloud platform project

- namespaces/live.cloud-platform.service.justice.gov.uk/kiril-dev/resources/ecr.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/kiril-dev/resources/serviceaccount.tf
Container repository and service account configuration updates as part of my test application to learn cloud platform
> Updated container repository and service account

- namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-datahub-catalogue-prod/01-rbac.yaml
This should be tied to the data-catalogue github group, not data-platform.
> Update team for RoleBinding (datahub prod)

- namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-datahub-catalogue-test/00-namespace.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-datahub-catalogue-test/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-datahub-catalogue-test/resources/variables.tf
as with https://github.com/ministryofjustice/cloud-platform-environments/pull/26463
> Update team data-platform -> data-catalogue for datahub test

- namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-datahub-catalogue-dev/00-namespace.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-datahub-catalogue-dev/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-datahub-catalogue-dev/resources/variables.tf
as with https://github.com/ministryofjustice/cloud-platform-environments/pull/26463
> update data-platform -> data-catalogue for datahub dev

- namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-datahub-catalogue-preprod/00-namespace.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-datahub-catalogue-preprod/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-datahub-catalogue-preprod/resources/variables.tf
As with the prod namespace https://github.com/ministryofjustice/cloud-platform-environments/pull/26463
> Update team data-platform -> data-catalogue for datahub preprod

- namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-dev/resources/court-cases-queue.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-dev/resources/irsa.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-dev/resources/probation-in-court-cases-queue.tf
JIRA Link : https://dsdmoj.atlassian.net/browse/PIC-4207
> PIC-4207 : Queue creation for dev probation-in-court-cases-queue

- namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-preprod/resources/court-cases-queue.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-preprod/resources/irsa.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-preprod/resources/probation-in-court-cases-queue.tf
JIRA Link : https://dsdmoj.atlassian.net/browse/PIC-4207
> PIC-4207 : Queue creation for pre-prod probation-in-court-cases-queue

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-dev/resources/rds-postgresql.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-dev/resources/variables.tf
Added the RDS entry, and associated variable(s) to the dces-drc-integration-dev environment.
> DCES-477 : Add RDS entry for dces integration DEV

- namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-acronyms-app-dev/00-namespace.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-acronyms-app-dev/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-acronyms-app-dev/02-limitrange.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-acronyms-app-dev/03-resourcequota.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-acronyms-app-dev/04-networkpolicy.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-acronyms-app-dev/resources/ecr.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-acronyms-app-dev/resources/main.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-acronyms-app-dev/resources/serviceaccount.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-acronyms-app-dev/resources/variables.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-acronyms-app-dev/resources/versions.tf
This PR creates a new namespace for the application operations-engineering-acronyms-app-dev.
> Add new namespace: operations-engineering-acronyms-app-dev

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-jobs-board-prod/resources/rds-postgresql.tf
Provision a new [PostgreSQL RDS database instance](https://user-guide.cloud-platform.service.justice.gov.uk/documentation/getting-started/cloud-platform-cli.html#add-an-rds-to-your-namespace) preparation for promoting Jobs Upload to the Production environment.
> ESWE-1054 create database

- namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-acronyms-app-dev/resources/rds-postgresql.tf
Added RDS PostgreSQL to the namespace **operations-engineering-acronyms-app-poc-dev** .
> added postgres rds

- namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-datahub-catalogue-dev/05-prometheusrule.yaml
These alerts are giving us lots of false positives at the moment.
> Silence dev datahub RDS alerts overnight

- namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-prod/resources/court-cases-queue.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-prod/resources/irsa.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-prod/resources/probation-in-court-cases-queue.tf
JIRA Link : https://dsdmoj.atlassian.net/browse/PIC-4207
> PIC-4207 : Queue creation for prod probation-in-court-cases-queue

- namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-acronyms-app-dev/APPLY_PIPELINE_SKIP_THIS_NAMESPACE
https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/environments-live/jobs/apply-live-e/builds/3650
> chore: 🤖 add skip file operations-engineering-acronyms-app-dev

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-proceeding-test/resources/secret.tf
Added the following secrets to CCP Test:
sentry_dsn
prosecution_concluded_db_username
email_client_notify_key
> Add secrets to CCP Test

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-proceeding-uat/resources/secret.tf
Added the following secrets to CCP UAT:
sentry_dsn
prosecution_concluded_db_username
email_client_notify_key
> Add secrets to CCP UAT

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-proceeding-prod/resources/secret.tf
Added the following secrets to CCP Prod:
sentry_dsn
prosecution_concluded_db_username
email_client_notify_key
> Add secrets to CCP prod

- namespaces/live.cloud-platform.service.justice.gov.uk/cfe-civil-cicd-poc-uat/00-namespace.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/cfe-civil-cicd-poc-uat/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/cfe-civil-cicd-poc-uat/02-limitrange.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/cfe-civil-cicd-poc-uat/03-resourcequota.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/cfe-civil-cicd-poc-uat/04-networkpolicy.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/cfe-civil-cicd-poc-uat/05-servicemonitor.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/cfe-civil-cicd-poc-uat/resources/ecr.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/cfe-civil-cicd-poc-uat/resources/irsa.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/cfe-civil-cicd-poc-uat/resources/main.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/cfe-civil-cicd-poc-uat/resources/pingdom.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/cfe-civil-cicd-poc-uat/resources/service-pod.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/cfe-civil-cicd-poc-uat/resources/serviceaccount.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/cfe-civil-cicd-poc-uat/resources/variables.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/cfe-civil-cicd-poc-uat/resources/versions.tf
It is a copy of cfe-civil-uat, but renaming the app from cfe-civil to cfe-civil-cicd-poc, which corresponds to the repo name being https://github.com/ministryofjustice/cfe-civil-cicd-poc
> Create environment cfe-civil-cicd-poc-uat

- namespaces/live.cloud-platform.service.justice.gov.uk/peoplefinder-production/07-grafanadashboard.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/peoplefinder-production/07-graffanadashboard.yaml
> Update peoplefinder-production Grafana dashboard

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-production/resources/rds.tf
RDS terraform file updated to point at new Production snapshot identifier
> CCR - Migration of database

- .checksum
- namespaces/live.cloud-platform.service.justice.gov.uk/cica-copilot-uat/00-namespace.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/cica-copilot-uat/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/cica-copilot-uat/02-limitrange.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/cica-copilot-uat/03-resourcequota.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/cica-copilot-uat/04-networkpolicy.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/cica-copilot-uat/resources/main.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/cica-copilot-uat/resources/variables.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/cica-copilot-uat/resources/versions.tf
New namespce for uat. cica-copilot-uat.
> Create namespace for cica-copilot-uat

- namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-find-moj-data-dev/05-prometheusrule.yaml
Previously: https://github.com/ministryofjustice/cloud-platform-environments/pull/26417
> Ignore garbage latency metric values for Find MoJ data dev

- namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-find-moj-data-preprod/05-prometheusrule.yaml
Previously https://github.com/ministryofjustice/cloud-platform-environments/pull/26417
> Ignore garbage latency metric values in Find MoJ data preprod

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-contacts-prod/00-namespace.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-contacts-prod/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-contacts-prod/02-limitrange.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-contacts-prod/03-resourcequota.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-contacts-prod/04-networkpolicy.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-contacts-prod/06-certificate.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-contacts-prod/resources/domain-events-topic.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-contacts-prod/resources/elasticache.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-contacts-prod/resources/irsa.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-contacts-prod/resources/main.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-contacts-prod/resources/rds-postgresql.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-contacts-prod/resources/serviceaccount-circleci.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-contacts-prod/resources/variables.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-contacts-prod/resources/versions.tf
PRC-157 : Build the PROD environment
> PRC-157 : Build the PROD environment

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-jobs-board-prod/resources/rds-postgresql.tf
Reconfigure RDS DB on prod:
1. disable auto start/stop
2. enable deletion protection
3. revise DB instance type (`db.t4g.small`, was `db.t4g.micro`) 
4. revise DB max. allocated storage (`10000`, was `500`)
> [ESWE-1054] MJMA/CMS Configure RDS production database (postgresql)

- namespaces/live.cloud-platform.service.justice.gov.uk/abundant-namespace-dev/resources/rds-postgresql.tf
- Test RDS bump from `7.2.1` to `7.3.0` in `Abundant namespace`
> chore: Test RDS bump in Abundant namespace

- namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-dev/resources/crime_portal_gateway_s3_bucket.tf
Increase expiry date of s3 bucket to 90 days for DEV
> PIC-4239 Increase S3 Bucket expiry date - DEV

- namespaces/live.cloud-platform.service.justice.gov.uk/james-dev/resources/serviceaccount.tf
Adding team review to github config within serviceaccount.tf
> add team review to github repos

- namespaces/live.cloud-platform.service.justice.gov.uk/abundant-namespace-dev/resources/rds-postgresql-2.tf
- Create new RDS in abundant namespace
- Relates to https://github.com/ministryofjustice/cloud-platform/issues/6270
> chore: Create new RDS in abundant namespace

- namespaces/live.cloud-platform.service.justice.gov.uk/abundant-namespace-dev/resources/rds-postgresql-2.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/abundant-namespace-dev/resources/rds-postgresql.tf
- Bump test RDS to latest release
- Relates to https://github.com/ministryofjustice/cloud-platform/issues/6270
> chore: Bump test RDS to latest release

- namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-preprod/resources/crime_portal_gateway_s3_bucket.tf
Increase expiry date of s3 bucket to 90 days in PreProd
> PIC-4239 Increase S3 Bucket expiry date - PreProd

- .github/workflows/format-code.yml
https://github.com/ministryofjustice/github-actions/releases/tag/v18.2.4
> chore: 🤖 bump code-formatter for terraform binary

- namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-prod/resources/crime_portal_gateway_s3_bucket.tf
Increase expiry date of s3 bucket to 90 days in Prod
> PIC-4239 Increase S3 Bucket expiry date - Prod

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-templates-dev/resources/main.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-templates-dev/resources/serviceaccount-github.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-templates-dev/resources/variables.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-templates-dev/resources/versions.tf
This enables secrets for the github repo for Github Actions workflows
> Template GitHub actions secrets

- namespaces/live.cloud-platform.service.justice.gov.uk/applying-service-standards-dev/00-namespace.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/applying-service-standards-dev/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/applying-service-standards-dev/02-limitrange.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/applying-service-standards-dev/03-resourcequota.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/applying-service-standards-dev/04-networkpolicy.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/applying-service-standards-dev/resources/basic-auth.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/applying-service-standards-dev/resources/main.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/applying-service-standards-dev/resources/serviceaccount.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/applying-service-standards-dev/resources/variables.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/applying-service-standards-dev/resources/versions.tf
The PR creates a development environment for a node application used to host a website the Service Standards assurance team.
> Apply Service Standards - initial commit

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-uat/05-prometheus.yaml
Add prometheus custom rule to detect and alert when a job is added to the list of dead jobs
> AP-5317: Add sidekiq dead job alert [UAT]

- namespaces/live.cloud-platform.service.justice.gov.uk/james-dev/resources/serviceaccount-github.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/james-dev/resources/variables.tf
Some tidying up to ensure the correct environment
> james-dev: change environment to dev + add service account parameters

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-litigator-fees-dev/resources/variables.tf
variables.tf amending application name format to fix job apply.
> Reformatting application name 

- namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-join-github-prod/resources/ecr.tf
Connects to https://github.com/ministryofjustice/operations-engineering/issues/4897
> :fire: Remove deletion_protection to prep for deletion

- namespaces/live.cloud-platform.service.justice.gov.uk/pola-production/resources/ecr.tf
also removes skip file now that the pipeline is fixed
> POLA Production ECR add correct repo name

- namespaces/live.cloud-platform.service.justice.gov.uk/prisoner-content-hub-staging/resources/irsa.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/prisoner-content-hub-staging/resources/rds.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/prisoner-content-hub-staging/resources/service_pod.tf
⬆️  Update RDS TF to 7.2.1 to allow reboots.
🪪  Add ARN for RDS to IRSA.
> LNP-472: 🎉  add service pod to Content Hub staging environment.

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-interventions-dev/resources/rds-postgres14.tf
Bump version of rds module in the interventions dev environment for evaluation
> Bump version of rds module in the interventions dev 

- namespaces/live.cloud-platform.service.justice.gov.uk/prisoner-content-hub-production/resources/irsa.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/prisoner-content-hub-production/resources/rds.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/prisoner-content-hub-production/resources/service_pod.tf
⬆️  Update RDS TF to 7.2.1 to allow reboots.
🪪  Add ARN for RDS to IRSA.
> LNP-472: 🎉  add service pod to Content Hub production environment.

- namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-dns-form-prod/00-namespace.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-dns-form-prod/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-dns-form-prod/02-limitrange.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-dns-form-prod/03-resourcequota.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-dns-form-prod/04-networkpolicy.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-dns-form-prod/resources/ecr.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-dns-form-prod/resources/main.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-dns-form-prod/resources/serviceaccount.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-dns-form-prod/resources/variables.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-dns-form-prod/resources/versions.tf
This namespace will hold the infrastructure required to facilitate dns change in the ministry of justice.
> :sparkles: Add new namespace: operations-engineering-dns-form-prod

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-information-exchange-preproduction/01-rbac.yaml
Add the crimeapps team to rbac for laa-information-exchange-preproduction
> Add the crimeapps team to rbac for laa-information-exchange-preprod

- .checksum
- namespaces/live.cloud-platform.service.justice.gov.uk/rd-entra-test/00-namespace.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/rd-entra-test/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/rd-entra-test/02-limitrange.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/rd-entra-test/03-resourcequota.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/rd-entra-test/04-networkpolicy.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/rd-entra-test/resources/ecr.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/rd-entra-test/resources/main.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/rd-entra-test/resources/serviceaccount.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/rd-entra-test/resources/variables.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/rd-entra-test/resources/versions.tf
Deployment for example application. We need to use it to test integration with EntraID auth.
> example-app-test-entra

- namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-prod/resources/ccrc-route53.tf
Removal of some DNS records that no longer exists as was causing alarms
> Removed unused DNS services 

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-prod/resources/rds-postgresql.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-prod/resources/secret.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-prod/resources/variables.tf
Adding DB and related secrets for Prod Environment
> DCES-Drc-Integration-DB-Update-Prod

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-uat/resources/rds-postgresql.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-uat/resources/secret.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-uat/resources/variables.tf
Adding DB and related secrets for UAT Environment.
> DCES-Drc-Integration-DB-Update-UAT

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-dev/resources/secret.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-dev/resources/variables.tf
Changing db name for naming convention.
> DCES-Drc-Integration-DB-Update-Dev

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-staging/resources/variables.tf
Changing db name for naming convention.
> DCES-Drc-Integration-DB-Update-Staging

- namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-find-moj-data-prod/resources/pingdom.tf
https://github.com/ministryofjustice/cloud-platform/issues/6294
> Updated prod pingdom integration

- namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-datahub-catalogue-prod/resources/secrets.tf
https://github.com/ministryofjustice/find-moj-data/issues/933
> Add slack-alert-webhook secret

- namespaces/live.cloud-platform.service.justice.gov.uk/calculate-journey-variable-payments-preprod/01-rbac.yaml
This is required for when OpenSearch is implemented, to assist with support
> Add hmpps-sre to RBAC for calculate-journey-variable-payments-preprod

- namespaces/live.cloud-platform.service.justice.gov.uk/calculate-journey-variable-payments-prod/01-rbac.yaml
This is required for when OpenSearch is implemented, to assist with support
> Add hmpps-sre to RBAC for calculate-journey-variable-payments-prod

- namespaces/live.cloud-platform.service.justice.gov.uk/create-and-vary-a-licence-api-dev/01-rbac.yaml
> Replace dps-tech in create-and-vary-a-licence-api-dev with hmpps-sre

- namespaces/live.cloud-platform.service.justice.gov.uk/create-and-vary-a-licence-api-preprod/01-rbac.yaml
> Replace dps-tech in create-and-vary-a-licence-api-preprod with hmpps-sre

- namespaces/live.cloud-platform.service.justice.gov.uk/create-and-vary-a-licence-api-prod/01-rbac.yaml
> Replace dps-tech in create-and-vary-a-licence-api-prod with hmpps-sre

- namespaces/live.cloud-platform.service.justice.gov.uk/pola-production/resources/serviceaccount.tf
Service account for POLA production namespace so we can deploy.
> Create serviceaccount.tf for POLA prod

- namespaces/live.cloud-platform.service.justice.gov.uk/pola-staging/resources/serviceaccount.tf
Create service account for POLA staging so we can deploy.
> Create serviceaccount.tf for POLA staging

- namespaces/live.cloud-platform.service.justice.gov.uk/pola-uat/resources/serviceaccount.tf
Create service account for POLA UAT so we can deploy.
> Create serviceaccount.tf for POLA uat

- namespaces/live.cloud-platform.service.justice.gov.uk/check-my-diary-prod/01-rbac.yaml
> Replace dps-tech in check-my-diary-prod with hmpps-sre

- namespaces/live.cloud-platform.service.justice.gov.uk/create-and-vary-a-licence-dev/01-rbac.yaml
> Replace dps-tech in create-and-vary-a-licence-dev with hmpps-sre

- namespaces/live.cloud-platform.service.justice.gov.uk/create-and-vary-a-licence-preprod/01-rbac.yaml
> Replace dps-tech in create-and-vary-a-licence-preprod with hmpps-sre

- namespaces/live.cloud-platform.service.justice.gov.uk/create-and-vary-a-licence-prod/01-rbac.yaml
> Replace dps-tech in create-and-vary-a-licence-prod with hmpps-sre

- namespaces/live.cloud-platform.service.justice.gov.uk/create-and-vary-a-licence-test1/01-rbac.yaml
> Replace dps-tech in create-and-vary-a-licence-test1 with hmpps-sre

- namespaces/live.cloud-platform.service.justice.gov.uk/create-and-vary-a-licence-test2/01-rbac.yaml
> Replace dps-tech in create-and-vary-a-licence-test2 with hmpps-sre

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-complexity-of-need-preprod/01-rbac.yaml
> Replace dps-tech in hmpps-complexity-of-need-preprod with hmpps-sre

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-complexity-of-need-production/01-rbac.yaml
> Replace dps-tech in hmpps-complexity-of-need-production with hmpps-sre

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-complexity-of-need-staging/01-rbac.yaml
> Replace dps-tech in hmpps-complexity-of-need-staging with hmpps-sre

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-contacts-dev/01-rbac.yaml
> Replace dps-tech in hmpps-contacts-dev with hmpps-sre

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-court-cases-release-dates-preprod/01-rbac.yaml
> Replace dps-tech in hmpps-court-cases-release-dates-preprod with hmpps-sre

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-court-cases-release-dates-prod/01-rbac.yaml
> Replace dps-tech in hmpps-court-cases-release-dates-prod with hmpps-sre

- namespaces/live.cloud-platform.service.justice.gov.uk/check-my-diary-preprod/07-rbac-haar-client-admin-team.yaml
> Replace dps-tech in check-my-diary-preprod with hmpps-sre

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-litigator-fees-staging/resources/variables.tf
Replaces spaces with dashes to prevent future errors
> Fix CCLF staging application name

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-litigator-fees-production/resources/variables.tf
Replaces spaces with dashes to prevent future errors
> Fix CCLF production application name

- namespaces/live.cloud-platform.service.justice.gov.uk/calculate-release-dates-api-dev/07-rbac-haar-client-admin-team.yaml
> Replace dps-tech in calculate-release-dates-api-dev with hmpps-sre

- namespaces/live.cloud-platform.service.justice.gov.uk/calculate-journey-variable-payments-prod/07-rbac-haar-client-admin-team.yaml
> Replace dps-tech in calculate-journey-variable-payments-prod with hmpps-sre

- namespaces/live.cloud-platform.service.justice.gov.uk/calculate-journey-variable-payments-preprod/07-rbac-haar-client-admin-team.yaml
> Replace dps-tech in calculate-journey-variable-payments-preprod with hmpps-sre

- namespaces/live.cloud-platform.service.justice.gov.uk/calculate-journey-variable-payments-dev/07-rbac-haar-client-admin-team.yaml
> Replace dps-tech in calculate-journey-variable-payments-dev with hmpps-sre

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-find-and-refer-an-intervention-dev/00-namespace.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-find-and-refer-an-intervention-dev/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-find-and-refer-an-intervention-dev/02-limitrange.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-find-and-refer-an-intervention-dev/03-resourcequota.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-find-and-refer-an-intervention-dev/04-networkpolicy.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-find-and-refer-an-intervention-dev/resources/elasticache.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-find-and-refer-an-intervention-dev/resources/main.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-find-and-refer-an-intervention-dev/resources/rds-postgres14.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-find-and-refer-an-intervention-dev/resources/serviceaccount-circleci.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-find-and-refer-an-intervention-dev/resources/variables.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-find-and-refer-an-intervention-dev/resources/versions.tf
Creating new namespace hmpps-find-and-refer-an-intervention-dev. Once we are happy with this, we will raise PRs for prepared and prod.
> Find and refer an intervention create env

- namespaces/live.cloud-platform.service.justice.gov.uk/calculate-release-dates-api-preprod/07-rbac-haar-client-admin-team.yaml
> Replace dps-tech in calculate-release-dates-api-preprod with hmpps-sre

- namespaces/live.cloud-platform.service.justice.gov.uk/calculate-release-dates-api-prod/07-rbac-haar-client-admin-team.yaml
> Replace dps-tech in calculate-release-dates-api-prod with hmpps-sre

- namespaces/live.cloud-platform.service.justice.gov.uk/calculate-release-dates-dev/07-rbac-haar-client-admin-team.yaml
> Replace dps-tech in calculate-release-dates-dev with hmpps-sre

- namespaces/live.cloud-platform.service.justice.gov.uk/calculate-release-dates-preprod/07-rbac-haar-client-admin-team.yaml
> Replace dps-tech in calculate-release-dates-preprod with hmpps-sre

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-find-and-refer-an-intervention-preprod/00-namespace.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-find-and-refer-an-intervention-preprod/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-find-and-refer-an-intervention-preprod/02-limitrange.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-find-and-refer-an-intervention-preprod/03-resourcequota.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-find-and-refer-an-intervention-preprod/04-networkpolicy.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-find-and-refer-an-intervention-preprod/resources/elasticache.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-find-and-refer-an-intervention-preprod/resources/main.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-find-and-refer-an-intervention-preprod/resources/rds-postgres14.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-find-and-refer-an-intervention-preprod/resources/serviceaccount-circleci.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-find-and-refer-an-intervention-preprod/resources/variables.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-find-and-refer-an-intervention-preprod/resources/versions.tf
creating new namespace hmpps-find-and-refer-an-intervention-preprod
> creating new namespace hmpps-find-and-refer-an-intervention-preprod

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-find-and-refer-an-intervention-prod/00-namespace.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-find-and-refer-an-intervention-prod/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-find-and-refer-an-intervention-prod/02-limitrange.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-find-and-refer-an-intervention-prod/03-resourcequota.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-find-and-refer-an-intervention-prod/04-networkpolicy.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-find-and-refer-an-intervention-prod/resources/elasticache.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-find-and-refer-an-intervention-prod/resources/main.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-find-and-refer-an-intervention-prod/resources/rds-postgres14.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-find-and-refer-an-intervention-prod/resources/serviceaccount-circleci.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-find-and-refer-an-intervention-prod/resources/variables.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-find-and-refer-an-intervention-prod/resources/versions.tf
creating new namespace hmpps-find-and-refer-an-intervention-prod
> creating new namespace hmpps-find-and-refer-an-intervention-prod

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-test/00-namespace.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-test/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-test/02-limitrange.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-test/03-resourcequota.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-test/04-networkpolicy.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-test/06-service-monitor.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-test/07-grafana.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-test/08-certificate.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-test/prometheus-custom-rules-laa-dces-report-service.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-test/resources/cognito.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-test/resources/ecr.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-test/resources/iam.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-test/resources/irsa.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-test/resources/main.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-test/resources/pingdom.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-test/resources/rds-postgresql.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-test/resources/s3_advantis.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-test/resources/s3_private_ca.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-test/resources/secret.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-test/resources/serviceaccount.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-test/resources/variables.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-test/resources/versions.tf
To bring this project in line with the MAAT API project.
> DCES-559: Create a new environment called test (based on Staging)

- namespaces/live.cloud-platform.service.justice.gov.uk/abundant-namespace-dev/resources/service-pod.tf
relates to ministryofjustice/cloud-platform#6157
> chore: 🤖 test service pod module PR for pod names changes

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-assure-hmrc-data-uat/resources/rds-postgresql.tf
Bump rds module from 7.2.0 to 8.0.0 assure UAT
> AP-5423: Bump RDS module from 7.2.0 to 8.0.0 assure UAT

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-hmrc-interface-uat/resources/rds.tf
Bump rds module from 7.2.0 to 8.0.0 HMRC Interface UAT
> AP-5423: Bump RDS module from 7.2.0 to 8.0.0 HMRC Interface UAT

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-prisoner-from-nomis-migration-preprod/resources/hmpps-prisoner-from-nomis-contactperson-sub-queue.tf
> Contact sns subscriptions - preprod

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-prisoner-from-nomis-migration-prod/resources/hmpps-prisoner-from-nomis-contactperson-sub-queue.tf
> Contact sns subscriptions - prod

- namespaces/live.cloud-platform.service.justice.gov.uk/pola-production/resources/main.tf
Add github team name for POLA prod so we can see our aws resources.
> Add github team name for POLA prod

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-court-register-prod/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-court-register-prod/06-rbac-haar-client-admin-team.yaml
> Replace dps-tech in hmpps-court-register-prod with hmpps-sre

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-event-logger-dev/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-event-logger-dev/07-rbac-haar-client-admin-team.yaml
> Replace dps-tech in hmpps-domain-event-logger-dev with hmpps-sre

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-event-logger-preprod/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-event-logger-preprod/07-rbac-haar-client-admin-team.yaml
> Replace dps-tech in hmpps-domain-event-logger-preprod with hmpps-sre

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-event-logger-prod/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-event-logger-prod/07-rbac-haar-client-admin-team.yaml
> Replace dps-tech in hmpps-domain-event-logger-prod with hmpps-sre

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-court-register-preprod/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-court-register-preprod/06-rbac-haar-client-admin-team.yaml
> Replace dps-tech in hmpps-court-register-preprod with hmpps-sre

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-find-and-refer-an-intervention-dev/07-certificate.yaml
Add a certificate to serve UI for find and refer and intervention
Service not present yet so UI only to support initial tests
> Add a certificate for the  find and refer and intervention dev UI

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-hpa-dev/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-hpa-dev/07-rbac-haar-client-admin-team.yaml
> Replace dps-tech in hmpps-hpa-dev with hmpps-sre

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-identify-remand-periods-preprod/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-identify-remand-periods-preprod/08-rbac-haar-client-admin-team.yaml
> Replace dps-tech in hmpps-identify-remand-periods-preprod with hmpps-sre

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-identify-remand-periods-prod/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-identify-remand-periods-prod/08-rbac-haar-client-admin-team.yaml
> Replace dps-tech in hmpps-identify-remand-periods-prod with hmpps-sre

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-identify-remand-periods-dev/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-identify-remand-periods-dev/08-rbac-haar-client-admin-team.yaml
> Replace dps-tech in hmpps-identify-remand-periods-dev with hmpps-sre

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-jobs-board-reporting-prod/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-jobs-board-reporting-prod/07-rbac-haar-client-admin-team.yaml
> Replace dps-tech in hmpps-jobs-board-reporting-prod with hmpps-sre

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-jobs-board-reporting-preprod/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-jobs-board-reporting-preprod/07-rbac-haar-client-admin-team.yaml
> Replace dps-tech in hmpps-jobs-board-reporting-preprod with hmpps-sre

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-jobs-board-reporting-dev/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-jobs-board-reporting-dev/07-rbac-haar-client-admin-team.yaml
> Replace dps-tech in hmpps-jobs-board-reporting-dev with hmpps-sre

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-jobs-board-preprod/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-jobs-board-preprod/07-rbac-haar-client-admin-team.yaml
> Replace dps-tech in hmpps-jobs-board-preprod with hmpps-sre

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-assure-hmrc-data-staging/resources/rds-postgresql.tf
AP-5423: bump rds module from 7.2.0 to 8.0.0
> AP-5423: bump rds module from 7.2.0 to 8.0.0 [Assure staging]

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-users-preprod/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-users-preprod/100-rbac-haar-client-admin-team.yaml
> Replace dps-tech in hmpps-manage-users-preprod with hmpps-sre

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-users-dev/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-users-dev/100-rbac-haar-client-admin-team.yaml
> Replace dps-tech in hmpps-manage-users-dev with hmpps-sre

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-test/resources/secret.tf
> DCES-573: Create a secret to hold values that override those coming from values-xxx.yaml files

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-nomis-prisoner-api-prod/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-nomis-prisoner-api-prod/08-rbac-haar-client-admin-team.yaml
> Replace dps-tech in hmpps-nomis-prisoner-api-prod with hmpps-sre

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-nomis-prisoner-api-preprod/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-nomis-prisoner-api-preprod/08-rbac-haar-client-admin-team.yaml
> Replace dps-tech in hmpps-nomis-prisoner-api-preprod with hmpps-sre

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-nomis-prisoner-api-dev/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-nomis-prisoner-api-dev/08-rbac-haar-client-admin-team.yaml
> Replace dps-tech in hmpps-nomis-prisoner-api-dev with hmpps-sre

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-nomis-mapping-service-prod/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-nomis-mapping-service-prod/07-rbac-haar-client-admin-team.yaml
> Replace dps-tech in hmpps-nomis-mapping-service-prod with hmpps-sre

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-nomis-mapping-service-preprod/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-nomis-mapping-service-preprod/07-rbac-haar-client-admin-team.yaml
> Replace dps-tech in hmpps-nomis-mapping-service-preprod with hmpps-sre

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-nomis-mapping-service-dev/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-nomis-mapping-service-dev/07-rbac-haar-client-admin-team.yaml
> Replace dps-tech in hmpps-nomis-mapping-service-dev with hmpps-sre

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-find-and-refer-an-intervention-dev/07-certificate.yaml
Add new certificate for service / api component for the find-and-refer-an-intervention project
> Add certificate for new service component in dev

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-demo/06-certificates.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-demo/07-rbac-haar-client-admin-team.yaml
These seemed to have been copied across incorrectly.
> Fix demo certificates for CAS environments

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-demo/resources/serviceaccount-github.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-demo/resources/versions.tf
add github.tf to cas demo environment
> add github.tf to cas demo environment

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-test/resources/messaging-queues.tf
Remove prosecution conclude queue delay in test environment
> LCAM-1617-remove delay

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-submit-crime-forms-uat/resources/rds-postgresql.tf
Increase allocated storage to correct minimum amount
> Update Submit Crime Forms UAT RDS Instance Module to 8.0.0

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-pecs-profile-ui-dev/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-pecs-profile-ui-dev/07-rbac-haar-client-admin-team.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-pecs-profile-ui-dev/resources/main.tf
> Replace dps-tech in hmpps-pecs-profile-ui-dev with hmpps-sre

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-pecs-profile-ui-preprod/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-pecs-profile-ui-preprod/07-rbac-haar-client-admin-team.yaml
> Replace dps-tech in hmpps-pecs-profile-ui-preprod with hmpps-sre

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-pecs-profile-ui-prod/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-pecs-profile-ui-prod/07-rbac-haar-client-admin-team.yaml
> Replace dps-tech in hmpps-pecs-profile-ui-prod with hmpps-sre

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-person-links-dev/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-person-links-dev/06-rbac-haar-client-admin-team.yaml
> Replace dps-tech in hmpps-person-links-dev with hmpps-sre

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-person-links-preprod/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-person-links-preprod/06-rbac-haar-client-admin-team.yaml
> Replace dps-tech in hmpps-person-links-preprod with hmpps-sre

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-person-links-prod/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-person-links-prod/06-rbac-haar-client-admin-team.yaml
> Replace dps-tech in hmpps-person-links-prod with hmpps-sre

- namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-demo/resources/rds.tf
Even though this is upgrading from 10.4 -> 10.11 it is a major update. Following this teams lead https://github.com/ministryofjustice/cloud-platform-environments/pull/26924
> Increase MariaDB version and set major db upgrade flag

- namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-demo/resources/rds.tf
Database has been updated. Now return flag back to false.
> Database upgrade - return option back to false

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-find-and-refer-an-intervention-dev/07-certificate.yaml
Rename cert domain from prison -> hmpps to fix health endpoint fail
> fix error in domain within service cert

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-portfolio-management-prod/resources/ssm.tf
renaming the keys so they work better when referred to by modules
> make SSM keys more generic

- namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-dev/07-certificate.yaml
Add court-case-matcher to custom cert in **DEV**
> court-probation-dev: Add court-case-matcher to custom cert

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-test/resources/cognito.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-test/resources/ecr.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-test/resources/secret.tf
And rename a secret to be in line with that in other environments.
> DCES-538 remove unused resources in test environment

- namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-preprod/07-certificate.yaml
Add court-case-matcher to custom cert in **PREPROD**
> court-probation-preprod: Add court-case-matcher to custom cert

- namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-prod/07-certificate.yaml
Add court-case-matcher to custom cert in **PROD**
> court-probation-prod: Add court-case-matcher to custom cert 

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-probation-estate-prod/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-probation-estate-prod/06-rbac-haar-client-admin-team.yaml
> Replace dps-tech in hmpps-probation-estate-prod with hmpps-sre

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-probation-estate-preprod/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-probation-estate-preprod/06-rbac-haar-client-admin-team.yaml
> Replace dps-tech in hmpps-probation-estate-preprod with hmpps-sre

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-probation-estate-dev/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-probation-estate-dev/06-rbac-haar-client-admin-team.yaml
> Replace dps-tech in hmpps-probation-estate-dev with hmpps-sre

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-prisoner-events-prod/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-prisoner-events-prod/08-rbac-haar-client-admin-team.yaml
> Replace dps-tech in hmpps-prisoner-events-prod with hmpps-sre

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-prisoner-events-preprod/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-prisoner-events-preprod/08-rbac-haar-client-admin-team.yaml
> Replace dps-tech in hmpps-prisoner-events-preprod with hmpps-sre

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-assure-hmrc-data-production/resources/rds-postgresql.tf
bump rds modules 7.2.0 to 8.0.0
> AP-5423: bump rds module from 7.2.0 to 8.0.0 [Assure production]

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-prisoner-events-dev/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-prisoner-events-dev/08-rbac-haar-client-admin-team.yaml
> Replace dps-tech in hmpps-prisoner-events-dev with hmpps-sre

- namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-prod/02-limitrange.yaml
Our application is currently using a lot of memory during PDF image processing and we are getting errors as a result. We are increasing the memory usage now to cover that in the short term but looking at ways to make the application more efficient in the medium term so we can reduce our memory usage.
> Adjust memory limits

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-hmrc-interface-production/resources/rds.tf
bump rds module 7.2.0 to 8.0.0
> AP-5423: bump rds module from 7.2.0 to 8.0.0 [HMRC Int production]

- namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-dev/resources/rds.tf
dev env upgrade of booker-registry rds instance to latest v8.0.0
> VB-4865 - Update visits team rds instance to 8.0.0

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-portfolio-management-prod/resources/ssm.tf
> add the dev key back

- namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-dev/02-limitrange.yaml
As the platform has grown we need more compute resources per container.
> Increase compute resource request for better performace

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-dev/02-limitrange.yaml
Changing memory limits on drc-integration-dev
> DCES-588 Update the DRC Integration Memory Limits

- namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-staging/resources/rds.tf
Updates visit-scheduler and booker-registry to 8.0.0
> VB-4865 - Update rds instance on visits team to 8.0.0

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-probation-integration-services-dev/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-probation-integration-services-dev/06-rbac-haar-client-admin-team.yaml
> Replace dps-tech in hmpps-probation-integration-services-dev with hmpps-sre

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-probation-integration-services-preprod/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-probation-integration-services-preprod/06-rbac-haar-client-admin-team.yaml
> Replace dps-tech in hmpps-probation-integration-services-preprod with hmpps-sre

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-probation-integration-services-prod/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-probation-integration-services-prod/06-rbac-haar-client-admin-team.yaml
> Replace dps-tech in hmpps-probation-integration-services-prod with hmpps-sre

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-review-send-recall-dev/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-review-send-recall-dev/07-rbac-haar-client-admin-team.yaml
> Replace dps-tech in hmpps-review-send-recall-dev with hmpps-sre

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-uat/02-limitrange.yaml
Changing memory limits on drc-integration-uat
> DCES-588 Update the DRC Integration Memory Limits - UAT

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-prod/02-limitrange.yaml
Changing memory limits on drc-integration-prod
> DCES-588 Update the DRC Integration Memory Limits - Prod

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-test/02-limitrange.yaml
Changing memory limits on drc-integration-test
> DCES-588 Update the DRC Integration Memory Limits - Test

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-staging/02-limitrange.yaml
Changing memory limits on drc-integration-staging
> DCES-588 Update the DRC Integration Memory Limits - Staging

- namespaces/live.cloud-platform.service.justice.gov.uk/legal-framework-api-production/resources/rds.tf
bump rds module from 7.2.0 to 8.0.0
> AP-5423: bump rds module 7.x to 8.0.0 [LFA production]

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-production/resources/rds.tf
bump rds module from 7.2.0 to 8.0.0
> AP-5423: bump rds module 7.x to 8.0.0 [Civil apply production]

- namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-prod/resources/rds.tf
Even though this is upgrading from 10.4 -> 10.11 it is a major update. Following this teams lead #26924
> Update DB version and set option to true

- namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-preprod/resources/rds.tf
need to skip on this namespace until preprod RDS storage issues can be addressed in the morning
> Visits preprod namespace skip file

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-delius-alfresco-preprod/resources/amq.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-delius-alfresco-preprod/resources/versions.tf
See https://github.com/hashicorp/terraform-provider-aws/issues/38708
> Alf AMQ - tmp remove lifecycle for engine version due to aws bug

- namespaces/live.cloud-platform.service.justice.gov.uk/prison-visits-booking-staging/02-limitrange.yaml
https://dsdmoj.atlassian.net/browse/VB-4773
Increasing memory limit - to stop OOMKILLED for the sidekiq container
> VB-4473, increase PVB Staging sidekiq pod memory limit

- namespaces/live.cloud-platform.service.justice.gov.uk/prison-visits-booking-production/02-limitrange.yaml
https://dsdmoj.atlassian.net/browse/VB-4773
Increasing memory limit - to stop OOMKILLED for the sidekiq container
> VB-4473, increase PVB Production sidekiq pod memory limit

- namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-saas-live/resources/editor.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-saas-live/resources/metadata_api.tf
*Will be merged at arranged time in case of disruption*
> Bump RDS module version in saas-live

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-accredited-programmes-prod/resources/rds-postgresql.tf
Changed the RDS instance class from "db.t4g.micro" to "db.t4g.medium" to enhance performance.
> APG-565 Upgrade RDS instance class for HMPPS Accredited Programmes Prod

- namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-preprod/resources/rds.tf
Its too big and needs downsizing
> Downsize the preprod db for visit-scheduler

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-delius-alfrsco-poc/resources/opensearch.tf
https://github.com/ministryofjustice/cloud-platform-terraform-opensearch/compare/main...georgepstaylor:cloud-platform-terraform-opensearch:patch-1
> chore: 🤖 testing os single instance branch, take 2

- namespaces/live.cloud-platform.service.justice.gov.uk/workforce-management-prod/resources/rds-allocation.tf
> WFP-2803 upgrade rds module - PROD allocations with new config

- namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-datahub-catalogue-preprod/resources/rds-postgresql.tf
https://registry.terraform.io/modules/terraform-aws-modules/security-group/aws/latest?tab=outputs
> Fix output name - this should be the ID

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-legal-adviser-api-production/resources/rds.tf
Increase storage from 5 to 30. minimum is 20 which is what we have staging set at.
> LAALAA PROD increase storage in preparation for upgrade to v8 rds

- namespaces/live.cloud-platform.service.justice.gov.uk/track-a-query-qa/resources/rds.tf
db-instance-identifier: cloud-platform-607522540af5fd87
> Apply DB snapshot on track-a-query-qa

- .checksum
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-get-payments-finance-data-dev/00-namespace.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-get-payments-finance-data-dev/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-get-payments-finance-data-dev/02-limitrange.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-get-payments-finance-data-dev/03-resourcequota.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-get-payments-finance-data-dev/04-networkpolicy.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-get-payments-finance-data-dev/resources/ecr.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-get-payments-finance-data-dev/resources/irsa.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-get-payments-finance-data-dev/resources/main.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-get-payments-finance-data-dev/resources/secret.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-get-payments-finance-data-dev/resources/service_pod.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-get-payments-finance-data-dev/resources/serviceaccount.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-get-payments-finance-data-dev/resources/variables.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-get-payments-finance-data-dev/resources/versions.tf
Create a brand new dev environment for GPDF team and project
> [LPF-468]: Create New Dev Environment in Cloud Platform

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-get-payments-finance-data-uat/resources/ecr.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-get-payments-finance-data-uat/resources/irsa.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-get-payments-finance-data-uat/resources/service_pod.tf
Add ECR and IRSA for UAT environment include the service pod to support diagnostics
> [LPF-154]: Investigate Creating a Second Test Environment

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-get-payments-finance-data-uat/resources/service_pod.tf
This is an update of existing service pods from version 1.1 to version 1.2.0.
> This is an update of existing service pods from version 1.1 to version 1.2.0.

- namespaces/live.cloud-platform.service.justice.gov.uk/offender-management-production/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/offender-management-production/05-rbac-haar-client-admin-team.yaml
> Replace dps-tech in offender-management-production with hmpps-sre

- namespaces/live.cloud-platform.service.justice.gov.uk/prisoner-content-hub-development/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/prisoner-content-hub-development/05-rbac-haar-client-admin-team.yaml
> Replace dps-tech in prisoner-content-hub-development with hmpps-sre

- namespaces/live.cloud-platform.service.justice.gov.uk/prisoner-content-hub-production/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/prisoner-content-hub-production/11-rbac-haar-client-admin-team.yaml
> Replace dps-tech in prisoner-content-hub-production with hmpps-sre

- namespaces/live.cloud-platform.service.justice.gov.uk/prisoner-content-hub-staging/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/prisoner-content-hub-staging/05-rbac-haar-client-admin-team.yaml
> Replace dps-tech in prisoner-content-hub-staging with hmpps-sre

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-dev/resources/main.tf
To enable access to SecretsManager in the console
> Add GithubTeam to default_tags

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-application-tracking-service-test/resources/secret.tf
Add sentry-dsn secret to ats test
> Add sentry-dsn secret to ats test

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-application-tracking-service-uat/resources/secret.tf
Add sentry-dsn secret to ats uat
> Add sentry-dsn secret to ats uat

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-application-tracking-service-prod/resources/secret.tf
Add sentry-dsn secret to ats prod
> Add sentry-dsn secret to ats prod

- namespaces/live.cloud-platform.service.justice.gov.uk/token-verification-api-preprod/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/token-verification-api-preprod/08-rbac-haar-client-admin-team.yaml
> Replace dps-tech in token-verification-api-preprod with hmpps-sre

- namespaces/live.cloud-platform.service.justice.gov.uk/token-verification-api-prod/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/token-verification-api-prod/08-rbac-haar-client-admin-team.yaml
> Replace dps-tech in token-verification-api-prod with hmpps-sre

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-staff-dev/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-staff-dev/06-rbac-haar-client-admin-team.yaml
> Replace dps-tech in hmpps-staff-dev with hmpps-sre

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-staff-preprod/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-staff-preprod/06-rbac-haar-client-admin-team.yaml
> Replace dps-tech in hmpps-staff-preprod with hmpps-sre

- namespaces/live.cloud-platform.service.justice.gov.uk/monitoring-psc-app-dev/resources/ecr.tf
Adding `deletion_protection    = false` to ecr for prep for deletion of app
> prep for deletion ecr psc app

- namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-model-metadata-uploader-dev/resources/ecr.tf
Adding `deletion_protection    = false` to ECR for prep for deletion
> prep for deletion

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-find-and-refer-an-intervention-dev/07-certificate.yaml
Add prefix to common name in a new pair of certificates
> Add certificates with revised common name

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-accredited-programmes-prod/00-namespace.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-accredited-programmes-prod/05-prometheusrules.yaml
- Add new Prometheus alert rules for high CPU, read and write latency, and low free storage space on the RDS database to improve monitoring and responsiveness.
- Include a Slack alert channel in the namespace annotations.
> APG-557 Add new Prometheus rules for RDS alerts PROD

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-criminal-legal-aid-staging/06-prometheus-rds.yaml
Added custom Prometheus rules to monitor the RDS instance on Crime Apply staging.
> CRIMAPP-1448 Prometheus rules for RDS in Crime Apply staging

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-criminal-legal-aid-production/06-prometheus-rds.yaml
Added custom Prometheus rules to monitor the RDS instance on Crime Apply production.
> CRIMAPP-1448 Prometheus rules for RDS in Crime Apply production

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-review-criminal-legal-aid-production/06-prometheus-rds.yaml
Added custom Prometheus rules to monitor the RDS instance on Crime Review production.
> CRIMAPP-1448 Prometheus rules for RDS in Crime Review production

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-production/resources/rds.tf
Update ccr rds.tf to use newly migrated prod database
> CCR prod db migration

- namespaces/live.cloud-platform.service.justice.gov.uk/monitoring/dashboard-datasource-rds.yaml
https://github.com/monitoringartist/grafana-aws-cloudwatch-dashboards/commits/master/aws-rds
> chore: 🤖 update grafana labs RDS datasource dashboard

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-get-payments-finance-data-uat/resources/variables.tf
Update the team name from  `pay-for-legal-aid` to `payforlegalaid`
> [PF-387]: Creating a Second Test Environment (UAT) for pay for legal aid team - update the team name

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-get-payments-finance-data-uat/00-namespace.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-get-payments-finance-data-uat/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-get-payments-finance-data-uat/resources/main.tf
Update the team name from  pay-for-legal-aid to payforlegalaid
> [LPF-387]: Creating a Second Test Environment (UAT) - update team

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-dev/resources/s3_advantis.tf
> laa-dces-data-migration-dev-s3sync

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-get-payments-finance-data-uat/resources/ecr.tf
> [LPF-387]: Creating a Second Test Environment (UAT) - update github enviroment and version of ect

- namespaces/live.cloud-platform.service.justice.gov.uk/monitoring/dashboard-datasource-rds.yaml
relates to ministryofjustice/cloud-platform#6463
> feat: 🎸 add allocated vs free storage pane

- .devcontainer/README.md
- Updates guidance, adding "Open in X" buttons
> 📝 Update Dev Container README

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-dev/resources/s3_advantis.tf
restrict-attachment-folder-access
> laa-dces-drc-integration-restrict-attachment-folder-access

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-dev/resources/s3_advantis.tf
updated principal for deny attachment statement
> laa-drc-integration-updatePrincipalDenyAttachment

- .checksum
- namespaces/live.cloud-platform.service.justice.gov.uk/jwoolcock-dev/00-namespace.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/jwoolcock-dev/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/jwoolcock-dev/02-limitrange.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/jwoolcock-dev/03-resourcequota.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/jwoolcock-dev/04-networkpolicy.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/jwoolcock-dev/resources/ecr.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/jwoolcock-dev/resources/main.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/jwoolcock-dev/resources/serviceaccount.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/jwoolcock-dev/resources/variables.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/jwoolcock-dev/resources/versions.tf
Create a Cloud Platform namespace, container repository, and service account for an example application `jw-cloud-platform-example-application`
Following instructions provided in [deploying-an-example-application](https://user-guide.cloud-platform.service.justice.gov.uk/documentation/deploying-an-app/deploying-an-example-application.html)
> Create namespace to deploy example app

- namespaces/live.cloud-platform.service.justice.gov.uk/cloud-platform-monitoring-alerts/resources/serviceaccount.tf
relates to ministryofjustice/cloud-platform#5207
> feat: 🎸 add serviceaccount for pipeline deploy

- namespaces/live.cloud-platform.service.justice.gov.uk/prison-visits-booking-dev/06-certificates.yaml
Prison Visits Booking - Dev
Create staff service certificate
> VB-4984, PVB Staff Dev - create certificate

- namespaces/live.cloud-platform.service.justice.gov.uk/prison-visits-booking-staging/certificates.yaml
Prison Visits Booking - Staging
Create staff service certificate
(namespace called staging, address will be pre-prod)
> VB-4984, PVB Staff staging, create certificate

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-tier-2-bail-prototypes/00-namespace.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-tier-2-bail-prototypes/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-tier-2-bail-prototypes/02-limitrange.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-tier-2-bail-prototypes/03-resourcequota.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-tier-2-bail-prototypes/04-networkpolicy.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-tier-2-bail-prototypes/resources/basic-auth.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-tier-2-bail-prototypes/resources/ecr.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-tier-2-bail-prototypes/resources/main.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-tier-2-bail-prototypes/resources/serviceaccount.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-tier-2-bail-prototypes/resources/variables.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-tier-2-bail-prototypes/resources/versions.tf
A new environment for hosting our prototypes in the alpha phase of HMPPS Community Accommodation Services tier 2 Bail.
> Adds new prototype environment for HMPPS CAS Bail

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-uat/resources/secret.tf
To allow connection to a Legal Framework API UAT branch from a Civil Apply
UAT branch for testin purposes.
> AP-5377: Create secret for LFA UAT branch pointing [civil apply UAT]

- namespaces/live.cloud-platform.service.justice.gov.uk/prison-visits-booking-dev/06-certificates.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/prison-visits-booking-dev/resources/elasticache.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/prison-visits-booking-dev/resources/main.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/prison-visits-booking-dev/resources/rds.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/prison-visits-booking-dev/resources/route53.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/prison-visits-booking-dev/resources/variables.tf
Add route53 and update supporting files
Prison visits booking - Development environment
> VB-4893, configure route53 PVB Dev

- namespaces/live.cloud-platform.service.justice.gov.uk/prison-visits-booking-dev/06-certificates.yaml
update certificates to make route53 work done in this PR 
https://github.com/ministryofjustice/cloud-platform-environments/pull/28173
> VB-4893, update pvb dev certificates

- namespaces/live.cloud-platform.service.justice.gov.uk/bold-lrs-client-dev/00-namespace.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/bold-lrs-client-dev/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/bold-lrs-client-dev/02-limitrange.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/bold-lrs-client-dev/03-resourcequota.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/bold-lrs-client-dev/04-networkpolicy.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/bold-lrs-client-dev/resources/ecr.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/bold-lrs-client-dev/resources/main.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/bold-lrs-client-dev/resources/serviceaccount.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/bold-lrs-client-dev/resources/variables.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/bold-lrs-client-dev/resources/versions.tf
- Added bold-lrs-client-dev namespace
> added new namespace

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-equinity-historical-data-frontend-dev/resources/secret.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-equinity-historical-data-frontend-dev/resources/variables.tf
- Added secrets manager for laa-crime-equinity-historical-data-frontend-dev application.
> EMP 728: Configure application secrets in AWS Secrets Manager DEV

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-equinity-historical-data-frontend-dev/resources/variables.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-equinity-historical-data-frontend-uat/resources/secret.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-equinity-historical-data-frontend-uat/resources/variables.tf
- Added secrets manager for laa-crime-equinity-historical-data-frontend-uat application.
> EMP 728: Configure application secrets in AWS Secrets Manager UAT

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-equinity-historical-data-frontend-uat/resources/main.tf
- Added GithubTeam tag for laa-crime-equinity-historical-data-frontend-uat application.
> EMP-728: Add GithubTeam tag UAT

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-equinity-historical-data-frontend-archive/resources/main.tf
- Added GithubTeam tag for laa-crime-equinity-historical-data-frontend-archive application.
> EMP-728: Add GithubTeam tag ARCHIVE

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-equinity-historical-data-frontend-prod/resources/main.tf
- Added GithubTeam tag for laa-crime-equinity-historical-data-frontend-prod application.
> EMP-728: Add GithubTeam tag PROD

- namespaces/live.cloud-platform.service.justice.gov.uk/c100-application-dev/resources/redis.tf
relates to ministryofjustice/cloud-platform#6517
> chore: 🤖 bumping redis module for c100-dev namespace

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-incident-reporting-dev/resources/rds.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-incident-reporting-dev/resources/variables.tf
Setup read replica as per IR-639, added parameters for connectivity as per IR-637
> IR-637 & IR-639: Changes to incident reporting dev namespace. 

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-preprod/resources/rds.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-preprod/resources/variables.tf
Here we configure the RDS service for DPR ingestion:
- [Setup Connectivity](https://dsdmoj.atlassian.net/wiki/spaces/DPR/pages/4461494352/Configure+DPS+RDS+Service+for+DPR+Ingestion#Setup-Connectivity)
- [Configure Parameter Groups](https://dsdmoj.atlassian.net/wiki/spaces/DPR/pages/4461494352/Configure+DPS+RDS+Service+for+DPR+Ingestion#Configure-Parameter-Groups)
> BaSM API Preprod: Configure DPS RDS Service for DPR Ingestion

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-preprod/resources/rds.tf
Here we set the DPR security group on the replica, not the primary rds instance.
> MAP-1885 DPR security group should be set on the read replica

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-staging/resources/rds.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-staging/resources/variables.tf
Here we configure the BaSM **DEV** (staging) RDS service for DPR ingestion:
[Setup Connectivity](https://dsdmoj.atlassian.net/wiki/spaces/DPR/pages/4461494352/Configure+DPS+RDS+Service+for+DPR+Ingestion#Setup-Connectivity)
[Configure Parameter Groups](https://dsdmoj.atlassian.net/wiki/spaces/DPR/pages/4461494352/Configure+DPS+RDS+Service+for+DPR+Ingestion#Configure-Parameter-Groups)
> Enable DPR ingression for BaSM dev (staging)  

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-uat/resources/rds.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-uat/resources/variables.tf
Here we configure the BaSM **UAT** RDS service for DPR ingestion:
[Setup Connectivity](https://dsdmoj.atlassian.net/wiki/spaces/DPR/pages/4461494352/Configure+DPS+RDS+Service+for+DPR+Ingestion#Setup-Connectivity)
[Configure Parameter Groups](https://dsdmoj.atlassian.net/wiki/spaces/DPR/pages/4461494352/Configure+DPS+RDS+Service+for+DPR+Ingestion#Configure-Parameter-Groups)
> Enable DPR ingression for BaSM UAT

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-production/resources/rds.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-production/resources/variables.tf
Here we configure the BaSM **PROD** RDS services for DPR ingestion:
[Setup Connectivity](https://dsdmoj.atlassian.net/wiki/spaces/DPR/pages/4461494352/Configure+DPS+RDS+Service+for+DPR+Ingestion#Setup-Connectivity)
[Configure Parameter Groups](https://dsdmoj.atlassian.net/wiki/spaces/DPR/pages/4461494352/Configure+DPS+RDS+Service+for+DPR+Ingestion#Configure-Parameter-Groups)
> Enable DPR ingression for BaSM production

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-person-record-dev/resources/cpr-delius-delete-events-queue.tf
Moving policy document in fact :-)
> CPR-420 add policy document

- namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-certificate-form/resources/ecr.tf
Pre-requisite for removing the namespace.
> Disabled deletion protection for ECR resource

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-dev/resources/s3_malware_protection.tf
> laa-drc-s3-malware-create

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-dev/resources/s3_malware_protection.tf
creating s3_malware_protection.tf
> laa-dces-drc-create-malware-resource

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-jobs-board-integration-preprod/00-namespace.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-jobs-board-integration-preprod/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-jobs-board-integration-preprod/02-limitrange.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-jobs-board-integration-preprod/03-resourcequota.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-jobs-board-integration-preprod/04-networkpolicy.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-jobs-board-integration-preprod/06-certificate.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-jobs-board-integration-preprod/resources/appinsights.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-jobs-board-integration-preprod/resources/main.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-jobs-board-integration-preprod/resources/serviceaccount-github.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-jobs-board-integration-preprod/resources/variables.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-jobs-board-integration-preprod/resources/versions.tf
Bootstrap the `preprod` env for MJMA Jobs Board Integration Service as per this ticket [ESWE-1161](https://dsdmoj.atlassian.net/browse/ESWE-1161)
[ESWE-1161]: https://dsdmoj.atlassian.net/browse/ESWE-1161?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ESWE-1161] Bootstrap the MJMA Jobs Board Integration service (Preprod)

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-jobs-board-integration-prod/00-namespace.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-jobs-board-integration-prod/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-jobs-board-integration-prod/02-limitrange.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-jobs-board-integration-prod/03-resourcequota.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-jobs-board-integration-prod/04-networkpolicy.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-jobs-board-integration-prod/06-certificate.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-jobs-board-integration-prod/resources/appinsights.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-jobs-board-integration-prod/resources/main.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-jobs-board-integration-prod/resources/pingdom.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-jobs-board-integration-prod/resources/serviceaccount-github.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-jobs-board-integration-prod/resources/variables.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-jobs-board-integration-prod/resources/versions.tf
Bootstrap the `prod` env for MJMA Jobs Board Integration Service as per this ticket [ESWE-1161](https://dsdmoj.atlassian.net/browse/ESWE-1161)
[ESWE-1161]: https://dsdmoj.atlassian.net/browse/ESWE-1161?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ESWE-1161] Bootstrap the MJMA Jobs Board Integration service (Prod)

- namespaces/live.cloud-platform.service.justice.gov.uk/offender-categorisation-dev/resources/rds.tf
Upgrading in line with https://user-guide.cloud-platform.service.justice.gov.uk/documentation/deploying-an-app/relational-databases/create.html#table-of-instance-types
> [SI-395] Updates rds source, instance, max alloc

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-audit-dev/resources/hmpps-alerts-ui.tf
Similar to 
https://github.com/ministryofjustice/cloud-platform-environments/pull/27888
and
https://github.com/ministryofjustice/cloud-platform-environments/pull/27911
Adding secret to alerts ns
> feat: add audit queue secret to alerts namespace

- .checksum
- namespaces/live.cloud-platform.service.justice.gov.uk/mip-hmcts-dynatrace-to-xsiam-preprod/00-namespace.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/mip-hmcts-dynatrace-to-xsiam-preprod/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/mip-hmcts-dynatrace-to-xsiam-preprod/02-limitrange.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/mip-hmcts-dynatrace-to-xsiam-preprod/03-resourcequota.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/mip-hmcts-dynatrace-to-xsiam-preprod/04-networkpolicy.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/mip-hmcts-dynatrace-to-xsiam-preprod/resources/main.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/mip-hmcts-dynatrace-to-xsiam-preprod/resources/variables.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/mip-hmcts-dynatrace-to-xsiam-preprod/resources/versions.tf
Namespace for the Send HMCTS Dynatrace logs to XSIAM Preproduction App
> Create namespace for mip-hmcts-dynatrace-to-xsiam-preprod

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-dev/resources/locals.tf
To allow for testing api endpoints (and practise adding new consumers)
> Add bmadley to dev HMPPS Integration API

- namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-dev/resources/court-cases-queue.tf
Subscribe to FIFO SNS Topic in **DEV**
> court-probation-dev: Subscribe to FIFO SNS Topic

- namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-preprod/resources/irsa.tf
Include dead-letter-queue into IRSA permissions
> court-probation-preprod Include dead-letter-queue into IRSA permissions

- namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-prod/resources/irsa.tf
Include dead-letter-queue into IRSA permissions for **PROD**
> court-probation-prod Include dead-letter-queue into IRSA permissions

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-non-associations-preprod/resources/sqs.tf
**DO NOT MERGE** until application changes have been deployed
> NON-367: Listen for booking moved HMPPS domain event

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-mailbox-register-dev/resources/secrets.tf
Destroy is ok as we are not using this secret for real yet.
> Rename manager secret

- .checksum
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-learner-records-microservice-preprod/00-namespace.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-learner-records-microservice-preprod/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-learner-records-microservice-preprod/02-limitrange.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-learner-records-microservice-preprod/03-resourcequota.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-learner-records-microservice-preprod/04-networkpolicy.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-learner-records-microservice-preprod/resources/main.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-learner-records-microservice-preprod/resources/serviceaccount-circleci.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-learner-records-microservice-preprod/resources/variables.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-learner-records-microservice-preprod/resources/versions.tf
Created namespace for pre-prod
> added preprod namespace or hmpps-learner-records-microservice

- namespaces/live.cloud-platform.service.justice.gov.uk/tim-development/resources/ecr.tf
PR to delete ECR with error intentionally for debugging concourse bot not outputting to ask channel.
> chore: Delete ECR with error intentionally for debugging

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-preprod/resources/rds.tf
> Add db_params to BaSM preprod read-replica to support DPR ingestion

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-jobs-board-integration-dev/resources/irsa.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-jobs-board-integration-dev/resources/sqs.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-jobs-board-integration-dev/resources/variables.tf
for Integration events of Jobs Board Integration on dev
* Add SQS queue 
* Add IRSA for access the queue
> [ESWE-1166] add queue for jobs-board integration events on dev

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-jobs-board-integration-dev/resources/rds-postgresql.tf
create database (RDS PostgreSQL) on `dev` for Jobs Board Integration service
> [ESWE-1187] Add DB to jobs-board-integration on `dev`

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-jobs-board-integration-preprod/resources/rds-postgresql.tf
create database for Jobs Board Integration on `preprod` with read-replica off
> [ESWE-1187] Add DB to jobs-board-integration on `preprod`

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-jobs-board-integration-prod/resources/rds-postgresql.tf
Create RDS postgresql db with replica off on `prod` of jobs board integration
> [ESWE-1187] Add DB to jobs-board-integration on `prod`

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-jobs-board-integration-preprod/resources/irsa.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-jobs-board-integration-preprod/resources/sqs.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-jobs-board-integration-preprod/resources/variables.tf
for Jobs Board Integration on `preprod` env.
- add SQS queue
- add IRSA for queue access
> [ESWE-1166] add queue for jobs-board integration events on `preprod`

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-jobs-board-integration-prod/resources/irsa.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-jobs-board-integration-prod/resources/sqs.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-jobs-board-integration-prod/resources/variables.tf
for Jobs Board Integration on `prod` env.
- add SQS queue
- add IRSA for queue access
> [ESWE-1166] add queue for jobs-board integration events on `prod`

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-access-civil-legal-aid-dev/04-networkpolicy.yaml
Allows inbound connections from laa-cla-backend-uat
> Access to CLA Backend ingress

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-access-civil-legal-aid-dev/04-networkpolicy.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-cla-backend-uat/04-networkpolicy.yaml
- Allows inbound connections from `laa-access-civil-legal-aid-dev`
> CLA Backend UAT add inbound ingress connection

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-dev/resources/s3_advantis.tf
added allow statement for guard duty role in s3.tf
> laa-drc-intg-s3-malware-add-s3-permission

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-dev/resources/s3_advantis.tf
> laa-drc-intg-s3-mal-grdduty-principal

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-fala-staging/00-namespace.yaml
- update contacts in fala staging namespace
> EL-1648: Update contacts in FALA staging namespace

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-fala-production/00-namespace.yaml
- update contacts in production namespace
> EL-1648: Update contacts in FALA production namespace

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-legal-adviser-api-staging/00-namespace.yaml
- update contacts in laalaa staging namespace
> EL-1648: Update contacts in LAALAA staging namespace

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-legal-adviser-api-production/00-namespace.yaml
- update contacts in laalaa production namespace
> EL-1648: Update contacts in LAALAA production namespace

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-cla-backend-staging/resources/ecr.tf
Updates CLA backend to allow Access connections
> Access Civil Legal Backend OIDC

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-dev/resources/iam.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-dev/resources/s3_advantis.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-dev/resources/s3_malware_protection.tf
> law-drc-intg-s3-malware-default-role

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-dev/APPLY_PIPELINE_SKIP_THIS_NAMESPACE
> lawa-drc-intg-s3-malware-skip

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-learner-records-api-dev/00-namespace.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-learner-records-api-dev/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-learner-records-api-dev/02-limitrange.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-learner-records-api-dev/03-resourcequota.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-learner-records-api-dev/04-networkpolicy.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-learner-records-api-dev/06-certificate.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-learner-records-api-dev/resources/appinsights.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-learner-records-api-dev/resources/main.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-learner-records-api-dev/resources/serviceaccount-github.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-learner-records-api-dev/resources/variables.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-learner-records-api-dev/resources/versions.tf
added hmpps-learner-records-api-dev namespace
> added hmpps-learner-records-api-dev namespace

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-learner-records-api-dev/06-certificate.yaml
Added env name to certificate dnsNames config.
> updated dnsNames in certificate.yaml config

- namespaces/live.cloud-platform.service.justice.gov.uk/tim-development/resources/guardduty.tf
- This PR create new IAM role with policy to implement S3 GuardDuty Malware Plan.
- IAM reference : https://docs.aws.amazon.com/guardduty/latest/ug/malware-protection-s3-iam-policy-prerequisite.html#attach-iam-policy-s3-malware-protection
- Relates to https://github.com/ministryofjustice/cloud-platform/issues/6641
> chore: Test S3 GuardDuty Malware Plan

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-dev/resources/iam.tf
> laa-drc-intg-malware-reslv-dupRole

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-dev/resources/iam.tf
> laa-dces-drc-intg-malware-add-obj-tag-perm

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-dev/resources/iam.tf
> laa-drc-intg-detector-perms

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-dev/resources/iam.tf
update permissions and variables
> laa-drc-intg-detector-perm-2

- namespaces/live.cloud-platform.service.justice.gov.uk/moj-vuln-report/01-rbac.yaml
- moj soc need access to their namespace
> feat: 🎸 add jd-soc to rbac

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-dev/resources/s3_advantis.tf
create put attachment permission for dm user
> laa-dces-drc-intg-putAttachment

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-electronic-monitoring-for-probation-officers-dev/06-certificate.yaml
URL Update: updating dns name to match url in dev environment
> URL Update: updating dns name to match url in dev environment

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-get-payments-finance-data-dev/resources/serviceaccount.tf
> adding service account rule to get network policy and service monitor

- namespaces/live.cloud-platform.service.justice.gov.uk/calculate-journey-variable-payments-dev/resources/scheduled-downtime.tf
See https://dsdmoj.atlassian.net/browse/MAP-2033
> Add scheduled downtime to dev env for JPC

- namespaces/live.cloud-platform.service.justice.gov.uk/calculate-journey-variable-payments-preprod/resources/scheduled-downtime.tf
See https://dsdmoj.atlassian.net/browse/MAP-2033
> Add scheduled downtime to preprod env for JPC

- namespaces/live.cloud-platform.service.justice.gov.uk/use-of-force-dev/resources/scheduled-downtime.tf
See https://dsdmoj.atlassian.net/browse/MAP-2034
> Add scheduled downtime to dev env for UoF
