- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-incident-reporting-prod/00-namespace.yaml
Send them to `#incident-reporting-service-dev` Instead of sending everything to `#dps_alerts`
> IR-421: Send Incident Reporting `prod` alerts to our dev channel

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-non-associations-prod/00-namespace.yaml
We're in the process of sending all alerts to our dev channel (`#non-associations-dev`) instead of sending everything to `#dps_alerts`.
> Send Non-associations' `prod` alerts to our dev channel

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-dev/resources/api_gateway-assume-role-endpoint.tf
Possible provider bug - setting passthrough_behavior then removing it does not update AWS.
> PI-2447 Set API Gateway pass-through behaviour to WHEN_NO_TEMPLATES

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-assess-crime-forms-prod/resources/rds-postgresql.tf
cloud platform guide says it should not have this version
component.
> CRM457-1907: Remove DB engine version minor component Assess PROD 

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-cwa-deployments-test/resources/ecr.tf
removed github oidc provider due to conflict with variable names
> remove github oidc provider

- namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-prod/resources/secrets-manager.tf
Add AWS secret key to contain app insights connection string
This will include the application insights prod connection string. This is a part of the appinsights migration to major version 3
> court-case-service-prod : Add AWS secret key to contain app insights connection string

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-auth-stage/resources/rds.tf
Temp change  to scale up the `hmpps-auth-stage` rds instance.
We're performance testing a new component and need to scale up the stage DB instance. We will revert the change once our testing is complete.
> increase rds db size to enable performance testsing in staging env

- namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-datahub-catalogue-prod/resources/rds-postgresql.tf
adding deletion protection for prod instance, and turning off major upgrade prep vars
> chore: refining RDS variables - DataHub prod

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-cla-backend-staging/resources/rds.tf
Bumps `cla-backend-staging` RDS Replica to RDS v.7.1.0.
> Bump cla-backend staging replica RDS to 7.1.0

- namespaces/live.cloud-platform.service.justice.gov.uk/monitoring/adapter-config-php-fpm.yaml
Our php-fpm application does not horizontally scale well based on CPU or memory metrics.
Our pods expose custom metrics, that are more suitable for HPA, and they are ingested by prometheus.
One metric in particular `phpfpm_active_processes` looks to be a good metric for pod pressure and an indicator for HPA.
This article explains the process that I'm following
https://aspirin4k.medium.com/scaling-of-php-application-in-kubernetes-based-on-fpm-workers-utilization-15e5c7d8683a
To scale on a custom metric, it looks like we need to add an `adapter-config`.
The added config lets us scale on `phpfpm_active_processes` by exposing the `phpfpm_active_processes_utilization` metric to use in our HPA config.
> Make custom metrics available for HPA.

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-cla-backend-training/resources/rds.tf
Bumps `cla-backend-training` RDS Replica to RDS v.7.1.0.
> Bump cla-backend training replica RDS to 7.1.0

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-preprod/01-rbac.yaml
This is 4 of 5 PRs which adds the SRE team into the Community Accommodation Services (CAS) environments
> adds SRE team to cas preprod environment RBAC (4/5)

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-dev/01-rbac.yaml
This is 1 of 5 PRs which adds the SRE team into the Community Accommodation Services (CAS) environments
> Adds sre team to dev rbac config (1/5)

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-test/01-rbac.yaml
This is 5 of 5 PRs which adds the SRE team into the Community Accommodation Services (CAS) environments
> Adds SRE team to CAS test rbac config (2/5)

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-demo/01-rbac.yaml
This is 3 of 5 PRs which adds the SRE team into the Community Accommodation Services (CAS) environments
> Adds SRE team to CAS demo rbac config (3/5) 

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-prod/01-rbac.yaml
This is 5 of 5 PRs which adds the SRE team into the Community Accommodation Services (CAS) environments
> Adds SRE team to CAS prod rbac config (5/5)

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-litigator-fees-uat/resources/rds.tf
* Fixes incorrect CIDR range for UAT HUB: `10.202.0.0/20` -> `10.206.0.0/20`
* Adds additional CIDR range for production workspace: `10.200.16.0/20`
> Add additional LAA LZ IP range to CCLF UAT RDS Security Group

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-litigator-fees-staging/resources/rds.tf
* Fixes incorrect CIDR range for staging HUB: `10.202.0.0/20` -> `10.204.0.0/20`
* Adds additional CIDR range for production workspace: `10.200.16.0/20`
> Add additional LAA LZ IP range to CCLF staging RDS Security Group

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-litigator-fees-production/resources/rds.tf
* Fixes incorrect CIDR range for production HUB: `10.202.0.0/20` -> `10.205.0.0/20`
* Adds additional CIDR range for production workspace: `10.200.16.0/20`
> Add additional LAA LZ IP range to CCLF production RDS Security Group

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-litigator-fees-staging/resources/rds.tf
fix below error in apply pipeline
```
FATA[4172] error running terraform on namespace laa-crown-court-litigator-fees-staging: unable to apply Terraform: exit status 1
Error: updating RDS DB Instance (cloud-platform-8d4efaf415be74fc): operation error RDS: ModifyDBInstance, https response error StatusCode: 400, RequestID: b815a3fd-3d8a-4dd2-a75f-b76134e5dee9, api error InvalidParameterCombination: Cannot upgrade oracle-se2 from 19.0.0.0.ru-2024-07.rur-2024-07.r1 to 19.0.0.0.ru-2024-01.rur-2024-01.r1
with module.rds-instance.aws_db_instance.rds,
on .terraform/modules/rds-instance/main.tf line 144, in resource "aws_db_instance" "rds":
144: resource "aws_db_instance" "rds" {
subcommand=apply
```
https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/environments-live/jobs/ …
> chore: update rds version to match console

- namespaces/live.cloud-platform.service.justice.gov.uk/.checksum
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-auth/resources/cognito-cma-clients.tf
The MAAT application no longer needs to call the CMA microservice to process mean assessments as this is being handled through the Orchestration microservice now. So I have removed the MAAT clients for each environment from the CMA Cognito user pool.
> LCAM 1114 Remove MAAT Client for Redundant CMA Integration

- namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-live-production/resources/submitter.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-live-production/resources/user-datastore.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-workload-prod/resources/rds-history.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/manage-soc-cases-dev/resources/rds.tf
fix below error
https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/environments-live/jobs/apply-live-b/builds/3333#L66be2760:19667
```
FATA[2036] error running terraform on namespace formbuilder-platform-live-production: unable to apply Terraform: exit status 1
Error: updating RDS DB Instance (cloud-platform-83a92686e95e340d): operation error RDS: ModifyDBInstance, https response error StatusCode: 400, RequestID: 4964ad67-509d-4b9c-b000-cc9cc4d88874, api error InvalidParameterCombination: Cannot upgrade postgres from 15.7 to 15.5
with module.submitter-rds-instance-2.aws_db_instance.rds,
on .terraform/modules/submitter-rds-instance-2/main.tf line 166, in resource "aws_db_instance" "rds":
166: resource "aws_db_instance" "rds" {
Error: updating RDS DB Instance …
```
> chore: fix rds version

- namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-saas-live/resources/editor.tf
fix below error
```
2024/09/12 14:35:13 Running Terraform Apply for namespace: formbuilder-saas-live
FATA[2340] error running terraform on namespace formbuilder-saas-live: unable to apply Terraform: exit status 1
Error: updating RDS DB Instance (cloud-platform-82ad2a679533ec45): operation error RDS: ModifyDBInstance, https response error StatusCode: 400, RequestID: 403460df-abc9-4698-8e8a-a306f27c2837, api error InvalidParameterCombination: Cannot upgrade postgres from 15.7 to 15.5
with module.editor-rds-instance.aws_db_instance.rds,
on .terraform/modules/editor-rds-instance/main.tf line 166, in resource "aws_db_instance" "rds":
166: resource "aws_db_instance" "rds" {
```
https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/environments-live/jobs/apply-live-b/builds …
> fix: update rds version

- namespaces/live.cloud-platform.service.justice.gov.uk/tst-em-example-app-jkn-dev/05-certificate.yaml
This cert will be used by our new UI and API apps in the dev environment.
N.B.: We will be moving to a new namespace once creating these is allowed again later this week. We anticipate this configuration will be ported over at that point.
> Adding cert for use by UI and API apps

- namespaces/live.cloud-platform.service.justice.gov.uk/civil-appeal-case-tracker-dev/resources/rds-postgresql.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/grc-prod/resources/rds.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/iac-fees-staging/resources/rds-postgresql.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/makeaplea-prod/resources/rds.tf
Fix for concourse job failures:-
https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/environments-live/jobs/apply-live-a/builds/3426
NS civil-appeal-case-tracker-dev
https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/environments-live/jobs/apply-live-e/builds/3423
NS makeaplea-prod
https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/environments-live/jobs/apply-live-d/builds/3418
NS iac-fees-staging
https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/environments-live/jobs/apply-live-b/builds/3418
NS grc-prod
> updated rds engine version to fix terraform drift

- namespaces/live.cloud-platform.service.justice.gov.uk/elliotsmith-rnd-dev/resources/serviceaccount.tf
Remove manually-named service account and use the default name. This service account is used by github, so we don't need to pay any attention to it.
Keep the custom name in irsa.tf only, as this is the service account we'll use to talk to AWS from the application running in the Kubernetes namespace.
> Remove repeated service account name

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-maat-orchestration-dev/resources/secret.tf
This PR configures three new secrets for the production Orchestration Service to capture the Sentry DSN and IP address allowlists. Making these secrets available via Secrets Manager is part of refactoring to remove the use of git-crypt from the Orchestration Service.
[Link to Story](https://dsdmoj.atlassian.net/browse/LCAM-1562)
> Configure secrets for the Orchestration Service Dev

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-maat-orchestration-test/resources/secret.tf
This PR configures three new secrets for the production Orchestration Service to capture the Sentry DSN and IP address allowlists. Making these secrets available via Secrets Manager is part of refactoring to remove the use of git-crypt from the Orchestration Service.
[Link to Story](https://dsdmoj.atlassian.net/browse/LCAM-1562)
> Configure secrets for the Orchestration Service Test

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-maat-orchestration-uat/resources/secret.tf
This PR configures three new secrets for the production Orchestration Service to capture the Sentry DSN and IP address allowlists. Making these secrets available via Secrets Manager is part of refactoring to remove the use of git-crypt from the Orchestration Service.
[Link to Story](https://dsdmoj.atlassian.net/browse/LCAM-1562)
> Configure secrets for the Orchestration Service UAT

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-maat-orchestration-prod/resources/secret.tf
This PR configures three new secrets for the production Orchestration Service to capture the Sentry DSN and IP address allowlists. Making these secrets available via Secrets Manager is part of refactoring to remove the use of git-crypt from the Orchestration Service.
[Link to Story](https://dsdmoj.atlassian.net/browse/LCAM-1562)
> Configure secrets for the Orchestration Service Prod

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-maat-orchestration-prod/resources/secret.tf
This PR fixes a typo in the `ingress_external_allowlist_source_range` for the `laa-maat-orchestration-prod` namespace.
> Fix typo in secret name

- namespaces/live.cloud-platform.service.justice.gov.uk/tim-development/resources/rds.tf
- seems minimum storage for io2 is 100 GiB for PostgreSQL
- will delete the rds after testing
> chore: bump test rds storage for io2 storage type

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-litigator-fees-dev/resources/irsa.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-litigator-fees-dev/resources/rds.tf
Updates the RDS instance to use the migrated dev database. 
Renames the RDS module to force a rebuild of the database, and updates references to the module accordingly.
> Update CCLF dev RDS snapshot

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-a-video-link-dev/resources/domain-events-queue-bvls.tf
This changes adds the subscription to a new domain event raised by the whereabouts-api to support the migration of video bookings from old BVLS into the new re-platformed version of BVLS.
> BAVL-41 subcribing to a new video link bookings migration event raised by the whereabouts-api.

- namespaces/live.cloud-platform.service.justice.gov.uk/whereabouts-api-dev/resources/domain-events-topic.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/whereabouts-api-dev/resources/irsa.tf
whereabouts-api needs to publish a new domain event for migration of data to a new service which subscribes to the event.
This change permits whereabouts to raise domain based events (in dev initially).
> BAVL-41 add ability to publish to the domain events topic (primarily for migration domain events to be used by re-platformed BVLS).

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-staging/resources/rds.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-uat/resources/rds.tf
Adding LAA Production VPC CIDR to CCR Staging and UAT RDS so that the windows EC2 instance I created in LAA Production can be used to access the DBs in CP. https://dsdmoj.atlassian.net/browse/TM-517
> TM-517, adding LAA production VPC CIDR to CCR Staging and UAT RDS

- namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-preprod/resources/irsa.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-preprod/resources/service-pod.tf
Rename the irsa modules in **PreProd**. This keeps the irsa module unchanged with a new custom irsa module created.
> PIC-4134 Rename irsa modules in PreProd

- namespaces/live.cloud-platform.service.justice.gov.uk/aaf-dev/resources/rds-postgresql.tf
``` Fix Terraform RDS version drift. Here are the RDS version mismatches: 
downgrade from 16.1 to 16.0
```
> Fix: rds version mismatch in aaf-dev

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-check-client-qualifies-production/resources/rds.tf
``` Fix Terraform RDS version drift. Here are the RDS version mismatches: 
```
> Fix: rds version mismatch in laa-check-client-qualifies-production

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-accredited-programmes-preprod/resources/rds-postgresql.tf
``` Fix Terraform RDS version drift. Here are the RDS version mismatches: 
```
> Fix: rds version mismatch in hmpps-accredited-programmes-preprod

- namespaces/live.cloud-platform.service.justice.gov.uk/manage-soc-cases-preprod/resources/rds.tf
``` Fix Terraform RDS version drift. Here are the RDS version mismatches: 
```
> Fix: rds version mismatch in manage-soc-cases-preprod

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-delius-alfresco-test/resources/rds.tf
``` Fix Terraform RDS version drift. Here are the RDS version mismatches: 
```
> Fix: rds version mismatch in hmpps-delius-alfresco-test

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-check-client-qualifies-staging/resources/rds.tf
``` Fix Terraform RDS version drift. Here are the RDS version mismatches: 
```
> Fix: rds version mismatch in laa-check-client-qualifies-staging

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-accredited-programmes-prod/resources/rds-postgresql.tf
``` Fix Terraform RDS version drift. Here are the RDS version mismatches: 
```
> Fix: rds version mismatch in hmpps-accredited-programmes-prod

- namespaces/live.cloud-platform.service.justice.gov.uk/civil-appeal-case-tracker-prod/resources/rds-postgresql.tf
``` Fix Terraform RDS version drift. Here are the RDS version mismatches: 
```
> Fix: rds version mismatch in civil-appeal-case-tracker-prod

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-a-video-link-preprod/resources/domain-events-queue-bvls.tf
This changes adds the subscription to a new domain event raised by the whereabouts-api in preprod to support the migration of video bookings from old BVLS into the new re-platformed version of BVLS.
> BAVL-41 subcribing to a new video link bookings migration event raised by the whereabouts-api (preprod).

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-interventions-prod/resources/rds-postgres14.tf
``` Fix Terraform RDS version drift. Here are the RDS version mismatches: 
```
> Fix: rds version mismatch in hmpps-interventions-prod

- namespaces/live.cloud-platform.service.justice.gov.uk/whereabouts-api-preprod/resources/domain-events-topic.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/whereabouts-api-preprod/resources/irsa.tf
whereabouts-api needs to publish a new domain event for migration of data to a new service which subscribes to the event.
This change permits whereabouts to raise domain based events in preprod.
> BAVL-41 add ability to publish to the domain events topic in preprod (primarily for migration domain events to be used by re-platformed BVLS).

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-prod/resources/rds-instance.tf
``` Fix Terraform RDS version drift. Here are the RDS version mismatches: 
```
> Fix: rds version mismatch in laa-court-data-adaptor-prod

- namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-prod/resources/rds.tf
``` Fix Terraform RDS version drift. Here are the RDS version mismatches: 
```
> Fix: rds version mismatch in claim-criminal-injuries-compensation-prod

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-preprod/resources/rds.tf
``` Fix Terraform RDS version drift. Here are the RDS version mismatches: 
```
> Fix: rds version mismatch in hmpps-book-secure-move-api-preprod

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-ui-dev/resources/rds.tf
``` Fix Terraform RDS version drift. Here are the RDS version mismatches: 
```
> Fix: rds version mismatch in laa-court-data-ui-dev

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-hmrc-interface-uat/resources/serviceaccount-circleci.tf
Rotate CircleCI service account secrets
This does not seem to have been migrated back in february
and the dd_mm_yyyy secret created 427+ days ago is not being used.
Current CI is using the oldest service account and getting the
```
Use tokens from the TokenRequest API or manually created secret-based tokens instead of auto-generated secret-based tokens.
```
> [HMRC Interface UAT] Rotate CircleCI service account secrets

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-ui-production/resources/rds.tf
``` Fix Terraform RDS version drift. Here are the RDS version mismatches: 
```
> Fix: rds version mismatch in laa-court-data-ui-production

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-launchpad-prod/resources/rds-launchpad-auth-postgresql.tf
``` Fix Terraform RDS version drift. Here are the RDS version mismatches: 
```
> Fix: rds version mismatch in hmpps-launchpad-prod

- namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-stag/resources/rds.tf
``` Fix Terraform RDS version drift. Here are the RDS version mismatches: 
```
> Fix: rds version mismatch in claim-criminal-injuries-compensation-stag

- namespaces/live.cloud-platform.service.justice.gov.uk/pathfinder-dev/resources/rds.tf
``` Fix Terraform RDS version drift. Here are the RDS version mismatches: 
```
> Fix: rds version mismatch in pathfinder-dev

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-complexity-of-need-production/resources/rds.tf
``` Fix Terraform RDS version drift. Here are the RDS version mismatches: 
downgrade from 15.7 to 15.6
```
> Fix: rds version mismatch in hmpps-complexity-of-need-production

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-ui-staging/resources/rds.tf
``` Fix Terraform RDS version drift. Here are the RDS version mismatches: 
```
> Fix: rds version mismatch in laa-court-data-ui-staging

- namespaces/live.cloud-platform.service.justice.gov.uk/pathfinder-preprod/resources/rds.tf
``` Fix Terraform RDS version drift. Here are the RDS version mismatches: 
```
> Fix: rds version mismatch in pathfinder-preprod

- namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-uat/resources/rds.tf
``` Fix Terraform RDS version drift. Here are the RDS version mismatches: 
```
> Fix: rds version mismatch in claim-criminal-injuries-compensation-uat

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-hmrc-interface-staging/resources/serviceaccount-circleci.tf
Rotate CircleCI service account secrets
This does not seem to have been migrated back in february
and the dd_mm_yyyy secret created 427+ days ago is not being used.
Current CI is using the oldest service account and getting the
```
Use tokens from the TokenRequest API or manually created secret-based tokens instead of auto-generated secret-based tokens.
```
> [HMRC Interface Staging] Rotate CircleCI service account secrets 

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-hmrc-interface-production/resources/serviceaccount.tf
Rotate CircleCI service account secrets
This does not seem to have been migrated back in february
and the dd_mm_yyyy secret created 427+ days ago is not being used.
Current CI is using the oldest service account and getting the
```
Use tokens from the TokenRequest API or manually created secret-based tokens instead of auto-generated secret-based tokens.
```
> [HMRC Interface Production] Rotate CircleCI service account secrets

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-assess-risks-and-needs-integrations-dev/00-namespace.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-assess-risks-and-needs-integrations-dev/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-assess-risks-and-needs-integrations-dev/02-limitrange.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-assess-risks-and-needs-integrations-dev/03-resourcequota.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-assess-risks-and-needs-integrations-dev/04-networkpolicy.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-assess-risks-and-needs-integrations-dev/05-certificates.yml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-assess-risks-and-needs-integrations-dev/06-rbac-haar-client-admin-team.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-assess-risks-and-needs-integrations-dev/resources/ecr.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-assess-risks-and-needs-integrations-dev/resources/elasticache.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-assess-risks-and-needs-integrations-dev/resources/main.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-assess-risks-and-needs-integrations-dev/resources/serviceaccount.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-assess-risks-and-needs-integrations-dev/resources/variables.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-assess-risks-and-needs-integrations-dev/resources/versions.tf
Note - This is replacing the `hmpps-assess-risks-and-needs-handover-service-dev` namespace. This will be removed in a follow-up PR
- Added `hmpps-assess-risks-and-needs-integrations-dev` namespace for hosting integration applications in the ARNS space
> Add ARNS Integrations Dev namespace

- namespaces/live.cloud-platform.service.justice.gov.uk/courtfines-dev/resources/rds-postgresql.tf
``` Fix Terraform RDS version drift. Here are the RDS version mismatches: 
```
> Fix: rds version mismatch in courtfines-dev

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-ui-uat/resources/rds.tf
``` Fix Terraform RDS version drift. Here are the RDS version mismatches: 
```
> Fix: rds version mismatch in laa-court-data-ui-uat

- namespaces/live.cloud-platform.service.justice.gov.uk/pathfinder-prod/resources/rds.tf
``` Fix Terraform RDS version drift. Here are the RDS version mismatches: 
```
> Fix: rds version mismatch in pathfinder-prod

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-dev/resources/secret.tf
Add drc-client-auth-tls secret to laa-dces-drc-integration's dev environment.
> Add drc-client-auth-tls secret

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-hardship-prod/resources/rds-postgresql.tf
``` Fix Terraform RDS version drift. Here are the RDS version mismatches: 
```
> Fix: rds version mismatch in laa-crime-hardship-prod

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-staging/resources/rds.tf
``` Fix Terraform RDS version drift. Here are the RDS version mismatches: 
```
> Fix: rds version mismatch in hmpps-book-secure-move-api-staging

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-validation-prod/resources/rds-postgresql.tf
``` Fix Terraform RDS version drift. Here are the RDS version mismatches: 
```
> Fix: rds version mismatch in laa-crime-validation-prod

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-probation-estate-prod/resources/rds.tf
``` Fix Terraform RDS version drift. Here are the RDS version mismatches: 
```
> Fix: rds version mismatch in hmpps-probation-estate-prod

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-probation-integration-services-dev/resources/flipt.tf
``` Fix Terraform RDS version drift. Here are the RDS version mismatches: 
```
> Fix: rds version mismatch in hmpps-probation-integration-services-dev

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-probation-integration-services-preprod/resources/flipt.tf
``` Fix Terraform RDS version drift. Here are the RDS version mismatches: 
```
> Fix: rds version mismatch in hmpps-probation-integration-services-preprod

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-probation-integration-services-prod/resources/flipt.tf
``` Fix Terraform RDS version drift. Here are the RDS version mismatches: 
```
> Fix: rds version mismatch in hmpps-probation-integration-services-prod

- namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-certificate-form/resources/variables.tf
Missing 'a' from autogenerated Terraform template name.
> Correct Template Naming and Removed Skip File

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-resettlement-passport-prod/resources/rds-postgresql.tf
``` Fix Terraform RDS version drift. Here are the RDS version mismatches: 
```
> Fix: rds version mismatch in hmpps-resettlement-passport-prod

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-test/resources/messaging-queues.tf
The following is now redundant so we want to remove the config from test:
laa_status_update_queue
laa_status_update_queue_policy
laa_status_update_dead_letter_queue
> Remove redundant sqs config from test

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-uat/resources/messaging-queues.tf
The following is now redundant so we want to remove the config from uat:
laa_status_update_queue
laa_status_update_queue_policy
laa_status_update_dead_letter_queue
> Remove sqs config from uat

- namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-datahub-catalogue-prod/00-namespace.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-datahub-catalogue-prod/resources/variables.tf
data-platform used to contain data-catalogue + analytical platform teams, and now only contains the analytical platform team.
data-catalogue is the correct set of users who should be managing this one.
> Update the team that owns Datahub

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-production/resources/main.tf
This is to enable AWS secret management
> Civil Apply Production: Add github tags to AWS

- namespaces/live.cloud-platform.service.justice.gov.uk/cccd-dev/resources/irsa.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/cccd-dev/resources/messaging.tf
These relate to the LAA Landing Zone CCLF dev environment which is no longer in use, following migration of the CCLF application to Cloud Platform
> Remove old cccd-dev SQS IAM ARNs

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-litigator-fees-production/resources/rds.tf
Updating DB Engine version because build failed here https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/environments-live/jobs/apply-namespace-changes-live/builds/7637
> updating db_engine_version

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-dev/05-prometheus.yaml
We want to alert when the expected number of connections is exceeded, and therefore the alert threshold needs to be increased to take into account the size of the connection pool.
> CCLF update development rds high database connection threshold

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-production/05-prometheus.yaml
We want to alert when the expected number of connections is exceeded, and therefore the alert threshold needs to be increased to take into account the size of the connection pool.
> CCLF update production rds high database connection threshold

- namespaces/live.cloud-platform.service.justice.gov.uk/courtfines-prod/resources/rds-postgresql.tf
``` Fix Terraform RDS version drift. Here are the RDS version mismatches: 
```
> Fix: rds version mismatch in courtfines-prod

- namespaces/live.cloud-platform.service.justice.gov.uk/courtfines-staging/resources/rds-postgresql.tf
``` Fix Terraform RDS version drift. Here are the RDS version mismatches: 
```
> Fix: rds version mismatch in courtfines-staging

- namespaces/live.cloud-platform.service.justice.gov.uk/create-and-vary-a-licence-api-dev/resources/rds.tf
``` Fix Terraform RDS version drift. Here are the RDS version mismatches: 
downgrade from 15.7 to 15.6
```
> Fix: rds version mismatch in create-and-vary-a-licence-api-dev

- namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-flask-template/resources/ecr.tf
This release is currently in pre-release. It creates the registry as a secret, meaning we don't expose the account number in plain text.
> ⬆️ Bump ECR Module to 7.1.0

- namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-find-moj-data-prod/05-prometheusrule.yaml
We were computing an average by dividing the sum by the count. The count can be zero.
If the sum is 0, the expression returns NaN, and the comparison returns false.
But if the sum is non-zero, it gives +Inf, and we get an alert.
I'm not sure why we would have data points with 0 for the count, and non-zero for the sum, but we are definitely getting +Inf values and unwanted alerts, so I'm explicitly filtering out +Inf (if anyone knows a better way of fixing this, please let me know!)
> Exclude infinities from latency alert expression

- namespaces/live.cloud-platform.service.justice.gov.uk/soc-production/resources/rds.tf
``` Fix Terraform RDS version drift. Here are the RDS version mismatches: 
```
> Fix: rds version mismatch in soc-production

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-breach-notice-prod/resources/rds.tf
``` Fix Terraform RDS version drift. Here are the RDS version mismatches: 
```
> Fix: rds version mismatch in hmpps-breach-notice-prod

- namespaces/live.cloud-platform.service.justice.gov.uk/soc-reporting-dev/resources/rds.tf
``` Fix Terraform RDS version drift. Here are the RDS version mismatches: 
```
> Fix: rds version mismatch in soc-reporting-dev

- namespaces/live.cloud-platform.service.justice.gov.uk/soc-staging/resources/rds.tf
``` Fix Terraform RDS version drift. Here are the RDS version mismatches: 
```
> Fix: rds version mismatch in soc-staging

- namespaces/live.cloud-platform.service.justice.gov.uk/utiac-dev/resources/rds-postgresql.tf
``` Fix Terraform RDS version drift. Here are the RDS version mismatches: 
```
> Fix: rds version mismatch in utiac-dev

- namespaces/live.cloud-platform.service.justice.gov.uk/utiac-prod/resources/rds-postgresql.tf
``` Fix Terraform RDS version drift. Here are the RDS version mismatches: 
```
> Fix: rds version mismatch in utiac-prod

- namespaces/live.cloud-platform.service.justice.gov.uk/utiac-staging/resources/rds-postgresql.tf
``` Fix Terraform RDS version drift. Here are the RDS version mismatches: 
```
> Fix: rds version mismatch in utiac-staging

- namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-staging/resources/rds.tf
``` Fix Terraform RDS version drift. Here are the RDS version mismatches: 
```
> Fix: rds version mismatch in visit-someone-in-prison-backend-svc-staging

- .devcontainer/README.md
- .devcontainer/devcontainer-lock.json
- .devcontainer/devcontainer.json
- .github/workflows/devcontainer.yml
- Updates `ghcr.io/ministryofjustice/devcontainer-feature/aws` to `1.0.0`
- Updates `ghcr.io/ministryofjustice/devcontainer-feature/cloud-platform` to `0.0.5`
- Updates `ghcr.io/ministryofjustice/devcontainer-feature/kubernetes` to `1.0.1`
- Updates `ghcr.io/ministryofjustice/devcontainer-feature/terraform` to `1.1.0`
- Updates `actions/checkout` to `v4.1.2`
> 🍱 Bump Dev Container features

- namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-datahub-catalogue-prod/05-prometheusrule.yaml
These are not useful to us right now.
Previously: https://github.com/ministryofjustice/cloud-platform-environments/pull/26657
> Remove some resource alerts from datahub prod

- namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-datahub-catalogue-dev/05-prometheusrule.yaml
These are not useful to us right now.
Previously: https://github.com/ministryofjustice/cloud-platform-environments/pull/26657
> Remove some resource alerts from datahub dev

- namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-datahub-catalogue-preprod/05-prometheusrule.yaml
These are not useful to us right now
Previously: https://github.com/ministryofjustice/cloud-platform-environments/pull/26657
> Remove some resource alerts from datahub preprod

- namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-find-moj-data-test/05-prometheusrule.yaml
Previously: https://github.com/ministryofjustice/cloud-platform-environments/pull/26417
> Ignore garbage latency metric values in Find MoJ data test

- namespaces/live.cloud-platform.service.justice.gov.uk/cccd-dev-lgfs/resources/secrets_manager.tf
When I created this secret in AWS Secrets Manager I copied the template from another environment without fully understanding all the details. I now realise that the label I gave it is not helpful. I presume that just changing the key will not trigger any changes. Can you please confirm? Thanks.
> Change label on env vars secrets

- namespaces/live.cloud-platform.service.justice.gov.uk/offender-categorisation-prod/resources/main.tf
Updating the GithubTeam in default_tags for offender-categorisation so that we can view performance insights.
> changed GithubTeam in default_tags

- .checksum
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-electronic-monitoring-datastore-preprod/00-namespace.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-electronic-monitoring-datastore-preprod/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-electronic-monitoring-datastore-preprod/02-limitrange.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-electronic-monitoring-datastore-preprod/03-resourcequota.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-electronic-monitoring-datastore-preprod/04-networkpolicy.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-electronic-monitoring-datastore-preprod/05-certificate.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-electronic-monitoring-datastore-preprod/06-rbac-haar-client-admin-team.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-electronic-monitoring-datastore-preprod/resources/ecr.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-electronic-monitoring-datastore-preprod/resources/elasticache.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-electronic-monitoring-datastore-preprod/resources/main.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-electronic-monitoring-datastore-preprod/resources/serviceaccount.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-electronic-monitoring-datastore-preprod/resources/variables.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-electronic-monitoring-datastore-preprod/resources/versions.tf
This is part of a migration:
1. Add a preprod environment (**this** PR)
2. [Prepare existing dev namespace ECR for deletion](https://github.com/ministryofjustice/cloud-platform-environments/pull/26752) (next PR)
3. [Remove existing dev environment which is in an incorrect namespace](https://github.com/ministryofjustice/cloud-platform-environments/pull/26753) (third PR)
4. [Add a dev environment](https://github.com/ministryofjustice/cloud-platform-environments/pull/26754) (fourth PR)
> Adding preprod environment for EM datastore

- namespaces/live.cloud-platform.service.justice.gov.uk/tst-em-example-app-jkn-dev/resources/ecr.tf
This is part of a migration:
1. [Add a preprod environment ](https://github.com/ministryofjustice/cloud-platform-environments/pull/26750)(previous PR)
2. Prepare existing dev namespace ECR for deletion (**this** PR)
3. [Remove existing dev environment which is in an incorrect namespace](https://github.com/ministryofjustice/cloud-platform-environments/pull/26753) (next PR)
4. [Add a dev environment](https://github.com/ministryofjustice/cloud-platform-environments/pull/26754) (fourth PR)
> Enabling ECR deletion for Electronic monitoring datastore temp namespace

- namespaces/live.cloud-platform.service.justice.gov.uk/offender-categorisation-preprod/resources/rds.tf
Following changes made during Cat Tool prod outage (SI-1254) it was flagged (https://mojdt.slack.com/archives/C04JFG3QJE6/p1728319701004019?thread_ts=1728311264.704499&cid=C04JFG3QJE6) that we could upgrade our rds instance to 7.3.0 to take advantage of faster disk resources.
> [SI-1255] Upgrade cat tool pp cloud-platform-terraform-rds-instance to v7.3.1

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-staging/05-prometheus.yaml
> Increase CCR staging prometheus threshold

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-litigator-fees-dev/05-prometheus.yaml
> Increase CCLF dev prometheus threshold

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-litigator-fees-uat/05-prometheus.yaml
> Increase CCLF uat prometheus threshold

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-litigator-fees-staging/05-prometheus.yaml
> Increase CCLF staging prometheus threshold

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-litigator-fees-production/05-prometheus.yaml
> Increase CCLF production prometheus threshold

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-assess-risks-and-needs-integrations-dev/resources/rds.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-assess-risks-and-needs-integrations-test/resources/rds.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-a-video-link-preprod/resources/rds-postgresql.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-a-video-link-prod/resources/rds-postgresql.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-breach-notice-dev/resources/rds.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-breach-notice-preprod/resources/rds.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-breach-notice-prod/resources/rds.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-nomis-mapping-service-dev/resources/rds.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-nomis-mapping-service-preprod/resources/rds.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-nomis-mapping-service-prod/resources/rds.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-person-record-prod/resources/rds.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-dev/resources/rds-postgresql.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-acronyms-app-dev/resources/rds-postgresql.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/rd-ai-nexus-dev/resources/rds-postgresql.tf
- Bump RDS modules from `7.3.0` to `8.0.0`
- Relates to https://github.com/ministryofjustice/cloud-platform/issues/6270
> chore: Bump RDS modules from `7.3.0` to `8.0.0`

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-contacts-preprod/resources/rds-postgresql.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-contacts-prod/resources/rds-postgresql.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-jobs-board-prod/resources/rds-postgresql.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/make-recall-decision-db-analysis/resources/rds-mssql.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/offender-categorisation-preprod/resources/rds.tf
- Bump RDS modules from 7.3.0 to 8.0.0
- Relates to https://github.com/ministryofjustice/cloud-platform/issues/6270
> chore: Bump RDS modules from `7.3.1` to `8.0.0`

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-templates-dev/resources/serviceaccount-github.tf
This splits out the role/rolebinding for the second service account, which was breaking the deployments.
> Hmpps templates - fix service account double rolebinding

- namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-join-github-dev/resources/ecr.tf
This is in preparation to remove the namespace as the application is being sunset.
> :wrench: Set delete_protection to false

- namespaces/live.cloud-platform.service.justice.gov.uk/offender-management-staging/resources/elasticache.tf
Fixes deprecation warning:
```The Redis connection was configured with username "dummyuser", but the provided password was for the default user. This will start failing in redis-rb 5.0.0```
> Update redis auth url staging

- namespaces/live.cloud-platform.service.justice.gov.uk/rd-entra-test/resources/serviceaccount.tf
Commented line in serviceaccount prevented KUBE_* secrets from being created in application repo.
> fix: Uncomment entry in serviceaccount.tf

- namespaces/live.cloud-platform.service.justice.gov.uk/offender-management-preprod/resources/elasticache.tf
Fixes deprecation warning:
```The Redis connection was configured with username "dummyuser", but the provided password was for the default user. This will start failing in redis-rb 5.0.0```
> Update redis auth url preprod

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-litigator-fees-uat/resources/irsa.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-litigator-fees-uat/resources/rds.tf
* Updates RDS snapshot to migrate LZ database to CP
* Renames the RDS module to trigger a database rebuild in order to use the new snapshot
> Migrate CCLF UAT database from LZ to Cloud Platform

- namespaces/live.cloud-platform.service.justice.gov.uk/rd-ai-nexus-dev/resources/rds-postgresql.tf
As we are now using this for demos to potential users, we have discovered that there appears to be a warm up period for the db when accessed from the service for the first time.
To prevent db connection errors on the first few db requests each day, keep the database on permanently.
> Don't switch db off overnight

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-litigator-fees-uat/05-prometheus.yaml
Following the migration of the database from Landing Zone, the id of the RDS instance we want to monitor has changed. This brings the alerts in line with that change.
> Update RDS IDs in CCLF UAT Prometheus rules

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-litigator-fees-uat/resources/variables.tf
Fixes failing build: https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/environments-live/jobs/apply-namespace-changes-live/builds/8094
> Fix CCLF UAT application name

- namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-dns-form-prod/05-certificate.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-dns-form-prod/resources/r53.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-dns-form-prod/resources/variables.tf
This pull request involves setting up DNS and SSL certificate configurations for the `operations-engineering-dns-form-prod` namespace. The changes include defining a new certificate, configuring Route 53 resources, and adding a new variable for the domain.
DNS and SSL certificate configurations:
* [`namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-dns-form-prod/05-certificate.yaml`](diffhunk://#diff-28b5221705b7a8a8dd36c44eb6b95c13ebfd46fc7358274b860a2bbfcd88cfe6R1-R12): Added a new certificate definition for `change-dns.service.justice.gov.uk` using Let's Encrypt.
* [`namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-dns-form-prod/resources/r53.tf`](diffhunk://#diff-2f93ac43cf77353e9bc2ceca71dad31498a1e6fd877b5974a3fc7030c855652fR1-R2 …
> ✨ Add Custom Domain to Change DNS Prod

- namespaces/live.cloud-platform.service.justice.gov.uk/offender-management-production/resources/elasticache.tf
Fixes deprecation warning:
```The Redis connection was configured with username "dummyuser", but the provided password was for the default user. This will start failing in redis-rb 5.0.0```
> Update redis auth url prod

- namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-prod/resources/pingdom.tf
This uses the [health-kick repo](https://github.com/ministryofjustice/health-kick) to proxy any /health checks by pingdom to our internal services.
> PIC-4271 Update pingdom healthkick url in court-probation-prod

- namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-prod/resources/pingdom.tf
Specify the app name in pingdom as it seems to be using the same name for crime-portal-gateway and prepare-a-case
which is "court-case-service"
> court-probation-prod Specify the app name in pingdom

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-find-and-refer-an-intervention-dev/resources/rds-postgres14.tf
``` Fix Terraform RDS version drift. Here are the RDS version mismatches: 
```
> Fix: rds version mismatch in hmpps-find-and-refer-an-intervention-dev

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-probation-integration-services-preprod/resources/common-platform-and-delius-queue.tf
- Update the sqs queue filter policy to receive common-platform hearing messages and not libra messages in preprod
> Update Common-Platform-and-delius-queue filter policy preprod

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-probation-integration-services-dev/resources/common-platform-and-delius-queue.tf
- Update the sqs queue filter policy to receive common-platform hearing messages and not libra messages in dev
> Update Common-Platform-and-delius-queue filter policy dev

- .devcontainer/devcontainer-lock.json
- .devcontainer/devcontainer.json
> [!NOTE]
> Code formatting makes changes to `.devcontainer/devcontainer-lock.json` but this file is automatically generated
- Bumps `ghcr.io/ministryofjustice/devcontainer-feature/aws` to `1.0.1`
- Bumps `ghcr.io/ministryofjustice/devcontainer-feature/cloud-platform` to `1.0.1`
- Bumps `ghcr.io/ministryofjustice/devcontainer-feature/terraform` to `1.2.0`
> 🎡 Bump Dev Container features

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-find-and-refer-an-intervention-prod/resources/rds-postgres14.tf
``` Fix Terraform RDS version drift. Here are the RDS version mismatches: 
```
> Fix: rds version mismatch in hmpps-find-and-refer-an-intervention-prod

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-find-and-refer-an-intervention-preprod/resources/rds-postgres14.tf
``` Fix Terraform RDS version drift. Here are the RDS version mismatches: 
```
> Fix: rds version mismatch in hmpps-find-and-refer-an-intervention-preprod

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-assess-crime-forms-uat/resources/rds-postgresql.tf
Also set the minimum storage value to prevent an error
> Bump RDS version for laa-assess-crime-forms-uat

- .github/workflows/yaml-metadata-change-check.yaml
- cmd/yaml-metadata-change-check/Dockerfile
- cmd/yaml-metadata-change-check/go.mod
- cmd/yaml-metadata-change-check/go.sum
- cmd/yaml-metadata-change-check/main.go
- cmd/yaml-metadata-change-check/utils/github.go
- cmd/yaml-metadata-change-check/utils/struct.go
- cmd/yaml-metadata-change-check/utils/utils.go
This GitHub action will check that `.metadata.name` and `.metadata.namespace` are not changed in a single PR.
We want users to delete the resource first in a PR and then create a second PR that will make the new resource instead. 
Related issue: [#5568](https://github.com/ministryofjustice/cloud-platform/issues/5568)
This has been tested on a fork of `cloud-platform-environments` and has also been tested on this branch.
The test will only trigger on yaml changes in namespaces, and will only fail when it detects a change to either of the metadata fields `name` or `namespace`
> Add yaml metadata check action 

- namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-dev/resources/rds.tf
Even though this is upgrading from 10.4 -> 10.11 apparently it qualifies as a major update. Following this teams lead https://github.com/ministryofjustice/cloud-platform-environments/pull/26924
> Upgrade RDS Maria DB to latest version

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-incident-reporting-dev/resources/rds.tf
This will change the storage type from `gp2` to `gp3`. The module also bumps the default storage size to 20GB (we don't specify this and it was previously
default to 10GB AFAICT).
> Upgrade RDS TF module to v8 for IRS (`dev`)

- namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-staging/resources/rds.tf
Although this is semantically is a minor bump it is considered a major update and option needs to be true.
> Upgrade RDS - bump Maria DB version to latest supported

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-incentives-dev/resources/rds.tf
> Upgrade RDS TF module to v8 for INC (`dev`)

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-non-associations-dev/resources/rds.tf
> Upgrade RDS TF module to v8 for NON (`dev`)

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-incentives-preprod/resources/rds.tf
This will change the storage type from gp2 to gp3. The module also bumps the default storage size to 20GB (we don't specify this and it was previously default to 10GB AFAICT).
> Upgrade RDS TF module to v8 for INC (`preprod`)

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-incident-reporting-preprod/resources/rds.tf
This will change the storage type from gp2 to gp3. The module also bumps the default storage size to 20GB (we don't specify this and it was previously default to 10GB AFAICT).
> Upgrade RDS TF module to v8 for IRS (`preprod`)

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-non-associations-preprod/resources/rds.tf
> Upgrade RDS TF module to v8 for NON (`preprod`)

- namespaces/live.cloud-platform.service.justice.gov.uk/cccd-staging/resources/messaging.tf
These relate to the LAA Landing Zone CCLF UAT environment which is no longer in use.
> Remove old cccd-staging SQS IAM ARNs

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-litigator-fees-production/resources/rds.tf
* Disables enable_rds_auto_start_stop as this interferes with the running of the application
* Disables performance_insights_enabled as we do not currently need this and we can save money by disabling it
* Removes outdated comments
> Minor tweaks to CCLF production RDS config

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-litigator-fees-staging/resources/rds.tf
* Disables enable_rds_auto_start_stop as this interferes with the running of the application
* Disables performance_insights_enabled as we do not currently need this and we can save money by disabling it
* Removes outdated comments
> Minor tweaks to CCLF staging RDS config

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-litigator-fees-uat/resources/rds.tf
* Disables enable_rds_auto_start_stop as this interferes with the running of the application
* Disables performance_insights_enabled as we do not currently need this and we can save money by disabling it
* Removes an outdated comment
> Minor tweaks to CCLF UAT RDS config

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-litigator-fees-dev/resources/rds.tf
* Disables enable_rds_auto_start_stop as this interferes with the running of the application
* Disables performance_insights_enabled as we do not currently need this and we can save money by disabling it
* Removes an outdated comment
> Minor tweaks to CCLF dev RDS config

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-incident-reporting-prod/resources/rds.tf
This will change the storage type from gp2 to gp3. The module also bumps the default storage size to 20GB (we don't specify this and it was previously default to 10GB AFAICT).
> Upgrade RDS TF module to v8 for IRS (`prod`)

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-incentives-prod/resources/rds.tf
> Upgrade RDS TF module to v8 for INC (`prod`)

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-non-associations-prod/resources/rds.tf
> Upgrade RDS TF module to v8 for NON (`prod`)

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-criminal-legal-aid-staging/resources/rds.tf
Updated RDS to 8.0.0 on `laa-apply-for-criminal-legal-aid-staging`.
> CRIMAPP-1404 Update RDS to 8.0.0 on crime apply staging

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-review-criminal-legal-aid-staging/resources/rds.tf
Updated RDS to 8.0.0 on `laa-review-criminal-legal-aid-staging`.
> CRIMAPP-1404 Update RDS to 8.0.0 on crime review staging

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-criminal-applications-datastore-staging/resources/rds.tf
Updated RDS to 8.0.0 on `laa-criminal-applications-datastore-staging`.
> CRIMAPP-1404 Update RDS to 8.0.0 on crime datastore staging

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-a-video-link-dev/resources/domain-events-queue-bvls.tf
Adds listening for a new event to the BVLS service so the appropriate action can be taken if/when the event occurs.
> BAVL-390 listen for the domain event video appointment cancelled in the BVLS service so the appropriate action can be taken.

- namespaces/live.cloud-platform.service.justice.gov.uk/offender-events-dev/resources/offender_categorisation-sub-queue.tf
I need to listen for Offender Released events. I have specified more than this currently, to ensure I see _some_ events (ones I assume are more frequently sent) before narrowing this down.
My aim is to provide the minimal configuration to enable this functionality.
> [SI-1253] Setup SQS queue for offender release events for cat api

- namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-preprod/resources/rds.tf
We replicate prod data into pre-prod and having them as different sizes could result in errors in the future. Aligning them as they are technically the same
> Align pre-prod with prod db

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-a-video-link-preprod/resources/domain-events-queue-bvls.tf
Adds listening for a new event to the preprod BVLS service so the appropriate action can be taken if/when the event occurs.
> BAVL-390 listen for the domain event video appointment cancelled in the preprod BVLS service so the appropriate action can be taken.

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-a-video-link-prod/resources/domain-events-queue-bvls.tf
Adds listening for a new event to the prod BVLS service so the appropriate action can be taken if/when the event occurs.
This change has already been applied to our dev and preprod environments.
> BAVL-390 listen for the domain event video appointment cancelled in the prod BVLS service so the appropriate action can be taken.

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-uat/05-prometheus.yaml
We are seeing regular alerts because the threshold for the Prometheus alert for high RDS read IOPS has been set too low. This increases it to 900 which is slightly higher than what we currently experience but still well below the 3000 IOPS RDS threshold.
> Increase CCR UAT RDS IOPS alert threshold

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-dev/05-prometheus.yaml
We are seeing regular alerts because the threshold for the Prometheus alert for high RDS read IOPS has been set too low (300). A daily batch job regularly results in ~750 IOPS which leads to false alarms and noisy alert channels. 
This change increases the threshold to 900 which is slightly higher than what we currently experience but still well below the 3000 IOPS RDS threshold.
> Increase CCR dev RDS read IOPS alert threshold

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-production/05-prometheus.yaml
We are seeing regular alerts because the threshold for the Prometheus alert for high RDS read IOPS has been set too low (300). A daily batch job regularly results in ~750 IOPS which leads to false alarms and noisy alert channels. 
This change increases the threshold to 900 which is slightly higher than what we currently experience but still well below the 3000 IOPS RDS threshold.
> Increase CCR production RDS read IOPS alert threshold

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-litigator-fees-staging/resources/irsa.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-litigator-fees-staging/resources/rds.tf
* Updates `snapshot_identifier` in `rds.tf` to use final snapshot from the CCLF staging database
* Renames RDS module from `rds-instance-trial` to `rds-instance-migrated` to force recreation of the database, and updates references in `rds.tf` and `irsa.tf`
* deletes unneeded commented config from `irsa.tf`
> Migrate CCLF Staging database from LZ to CP

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-litigator-fees-staging/05-prometheus.yaml
Following the migration of the database from Landing Zone, the id of the RDS instance we want to monitor has changed. This brings the alerts in line with that change.
> Update RDS IDs in CCLF Staging  Prometheus rules

- namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-datahub-catalogue-preprod/resources/rds-postgresql.tf
We want to expose the Datahub catalogue's DB to Quicksight, running in AP on the modernisation platform.
> Add additional security group for modernisation platform ingress

- namespaces/live.cloud-platform.service.justice.gov.uk/monitoring/dashboard-thanos.yaml
Capture the thanos compactor downsample backlog
> ci: 🎡 add thanos compactor downsample graph

- namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-dev/resources/irsa.tf
Should allow the service account to be able to execute against the RDS instances, useful when using the service pod with the service client to run commands such as describe-db-instances, describe-db-snapshots.
This is dev only, but if successful will roll out to pre and prod also.
> Add RDS policies to service client in Visits Dev

- namespaces/live.cloud-platform.service.justice.gov.uk/intranet-production/resources/rds.tf
Having monitored [database metrics](https://grafana.live.cloud-platform.service.justice.gov.uk/d/VR46pmwWk/aws-rds?orgId=1&var-datasource=P896B4444D3F0DAB8&var-region=default&var-dbinstanceidentifier=cloud-platform-283c8dc3f78ede0f&from=now-12h&to=now) this increase in ~~instance size~~ storage is a reaction to high DiskQueueDepth.
@wilson1000
> intranet-production Upgrade increase RDS instance class

- namespaces/live.cloud-platform.service.justice.gov.uk/justice-gov-uk-production/05-prometheus.yaml
This PR:
- Sets the severity level to our assigned string `justice-gov-uk-alerts` for existing alerts.
- Adds various rules related to latency and error rates.
> justice-gov-uk-production Add alerts

- namespaces/live.cloud-platform.service.justice.gov.uk/cfe-civil-staging/resources/rds.tf
I want to downgrade this storage from `small` to `micro`. On all of my other PRs to do this in various STG namesapces have failed e.g
https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/environments-live/jobs/apply-namespace-changes-live/builds/8758
with the same reason:
`RequestID: 287fa6e8-9521-4548-a5bb-8ee57e6d7c05, api error InvalidParameterCombination: The maximum allocated storage must be increased by at least 10 percent.`
This PR is to add a max_allocated_storage value before merging the PR to reduce the instance size and see if that works. Any suggestions you may have are welcome
> CFE Civil STG add a max allocated storage

- namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-preprod/resources/irsa.tf
Remove SNS permissions from irsa service account as it is now in the `court-facing-api` service account
**environment**: PreProd
> PIC-4134 court-probation-preprod: Remove SNS permissions from one of the service accounts

- namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-prod/resources/irsa.tf
Remove SNS permissions from irsa service account as it is now in the `court-facing-api` service account
**environment**: Prod
> PIC-4134 court-probation-prod: Remove SNS permissions from one of the service accounts

- namespaces/live.cloud-platform.service.justice.gov.uk/cfe-civil-staging-mtr/resources/rds.tf
I was trying to downgrade my db instance class (from small to micro) and it failed to apply in concurse:
https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/environments-live/jobs/apply-namespace-changes-live/builds/8758
I have added allocated storage to this PR, however I am not sure if I need to change the class back to `small` first, then merge this PR and the subsequently merge a PR that downgrades to `micro`.
> CFE MTR STG add allocated storage

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-probation-estate-dev/resources/rds.tf
``` Fix Terraform RDS version drift. Here are the RDS version mismatches: 
```
> Fix: rds version mismatch in hmpps-probation-estate-dev

- namespaces/live.cloud-platform.service.justice.gov.uk/make-recall-decision-preprod/resources/postgresql.tf
``` Fix Terraform RDS version drift. Here are the RDS version mismatches: 
downgrade from 13.15 to 13.14
```
> Fix: rds version mismatch in make-recall-decision-preprod

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-jobs-board-reporting-preprod/resources/rds-postgresql.tf
``` Fix Terraform RDS version drift. Here are the RDS version mismatches: 
```
> Fix: rds version mismatch in hmpps-jobs-board-reporting-preprod

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-hardship-dev/resources/rds-postgresql.tf
``` Fix Terraform RDS version drift. Here are the RDS version mismatches: 
```
> Fix: rds version mismatch in laa-crime-hardship-dev

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-candidate-matching-preprod/resources/rds.tf
``` Fix Terraform RDS version drift. Here are the RDS version mismatches: 
```
> Fix: rds version mismatch in hmpps-candidate-matching-preprod

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-hardship-uat/resources/rds-postgresql.tf
``` Fix Terraform RDS version drift. Here are the RDS version mismatches: 
```
> Fix: rds version mismatch in laa-crime-hardship-uat

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-probation-estate-preprod/resources/rds.tf
``` Fix Terraform RDS version drift. Here are the RDS version mismatches: 
```
> Fix: rds version mismatch in hmpps-probation-estate-preprod

- namespaces/live.cloud-platform.service.justice.gov.uk/offender-categorisation-prod/resources/rds.tf
Following changes made during Cat Tool prod outage (SI-1254) it was flagged (https://mojdt.slack.com/archives/C04JFG3QJE6/p1728319701004019?thread_ts=1728311264.704499&cid=C04JFG3QJE6) that we could upgrade our rds instance to 7.3.0 to take advantage of faster disk resources, preprod was then automatically updated from 7.3.1 to 8.0.0 so moving prod to 8.0.0
> [SI-1262] Upgrade cat tool prod cloud-platform-terraform-rds-instance to v8.0.0

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-legal-adviser-api-staging/resources/rds.tf
as suggested here: https://mojdt.slack.com/archives/C57UPMZLY/p1731581806150019?thread_ts=1731579913.865319&cid=C57UPMZLY
reducing to 15 failed with an error saying it had to be minimum of 20.
https://concourse.cloud-platform.service.justice.gov.uk/builds/22700703
So reverted it to 20
> LAALAA STG reduce DB allocated storage

- namespaces/live.cloud-platform.service.justice.gov.uk/rd-ai-nexus-dev/resources/serviceaccount.tf
This sets the environment as "development" for this namespace so that we can segregate deployments in future.
> RND-202 Scope rd-ai-nexus-dev service account to development environment

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-accredited-programmes-preprod/00-namespace.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-accredited-programmes-preprod/05-prometheusrules.yaml
- Introduce multiple Prometheus alerts for resource quotas, pod status, nginx performance, and RDS metrics within the hmpps-accredited-programmes-preprod namespace. 
- Add Slack alert channel metadata to the namespace definition.
> APG-557 Add Prometheus alert rules for preprod namespace

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-review-criminal-legal-aid-staging/06-prometheus-rds.yaml
Added custom Prometheus rules to monitor the RDS instance on Crime Review staging.
> CRIMAPP-1448 Prometheus rules for RDS in Crime Review staging

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-criminal-applications-datastore-production/06-prometheus-rds.yaml
Added custom Prometheus rules to monitor the RDS instance on Crime Datastore production.
> CRIMAPP-1448 Prometheus rules for RDS in Crime Datastore production

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-dev/00-namespace.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-dev/06-certificates.yaml
We would like a dev environment for CAS2 Bail, under the existing CAS namespace because we will be calling the shared API in the future.
> Add CAS2 Bail to CAS env

- namespaces/live.cloud-platform.service.justice.gov.uk/prison-visits-booking-production/certificates.yaml
Remove `prison-visits-staff-cert`
Unusued certificate (also holds incorrect host dnsName)
> remove unusued staff certificate

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-production/resources/pingdom.tf
Adds the `laa_production_environment_dashboard` tag to CCR production pingdom check to add the check to the LAA dashboard.
> Add CCR production pingdom tag

- namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-preprod/resources/irsa.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-preprod/resources/rds.tf
Destroys the preprod scheduler DB so it can be rebuilt as an appropriately (smaller) sized db instance.
see https://dsdmoj.atlassian.net/wiki/spaces/PSCH/pages/5269618719/Database+downsizing
> (Do Not Merge) Destroy preprod visit scheduler RDS and restore terraform apply pipeline

- namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-preprod/resources/irsa.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-preprod/resources/rds.tf
...Freeing up another 16TB of storage allocation
> Destroy redundant copy of visit booker registry preprod RDS

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-ems-cemo-ui-dev/resources/court-case-events-fifo-queue.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-ems-cemo-ui-dev/resources/data.tf
Create on behalf of @Obsiye 
In Development environment
Add FIFO queue and dead-letter-queue to hmpps-ems-cemo-ui-dev.
Add FIFO SNS Topic which communicates with the above FIFO queue.
Add relevant k8s secrets which will be used by the related services.
> Pic 4367 create fifo queue electronic monitoring team

- namespaces/live.cloud-platform.service.justice.gov.uk/monitoring/resources/secret.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/monitoring/resources/variables.tf
Create a secret to store webhook for opensearch alerts to send to low priority alerts.
This relates to the issue [#6311](https://github.com/ministryofjustice/cloud-platform/issues/6311)
> Create secret for opensearch webhook secret

- policy/namespace.rego
The monitoring-alerts service exclusively requires this label, CP environments must use the [correct label](https://github.com/ministryofjustice/cloud-platform-monitoring-alerts?tab=readme-ov-file#how-to-access)
relates to ministryofjustice/cloud-platform#5207
> chore: 🤖 deny monitoring ns access label for user ns

- namespaces/live.cloud-platform.service.justice.gov.uk/monitoring/resources/opensearch-alert.tf
This PR relates to [#6311](https://github.com/ministryofjustice/cloud-platform/issues/6311)
This creates an OpenSearch alert that will look for  the phrase `InsufficientCidrBlocks` which only occurs when there are no IP prefixes left in the subnet. 
When alerting it will post a message in the high-priority-channel slack channel.
> No IP Prefixes OpenSearch alert

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-accredited-programmes-preprod/resources/rds-postgresql.tf
This change introduces a Kubernetes secret to inject pre-prod RDS database credentials into the production namespace. This is needed to enable a refresh job to run on production using pre-prod database credentials.
> APG 361 - Add RDS credentials secret for pre-prod refresh on production

- namespaces/live.cloud-platform.service.justice.gov.uk/prison-visits-booking-dev/resources/route53.tf
Update PVB Dev route53 rule, both services can use the domain `dev.prisonvisits.service.justice.gov.uk`  (as both should be internal, not publicly accessible) 
Staff will use subdomain 'staff.----'
> VB-4893, update PVB DEV, route53 url

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-dev/resources/rds-postgresql.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-dev/resources/versions.tf
Allowing this namespaces' aws provider to bump to latest release to support GuardDuty Malware protection functionality in terraform.
Thread:
https://mojdt.slack.com/archives/C57UPMZLY/p1732635068587109
relates to https://github.com/ministryofjustice/cloud-platform/issues/6517
> chore: 🤖 bump aws provider and rds module

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-preprod/resources/rds.tf
Previously, I [added the DPR Security groups](https://dsdmoj.atlassian.net/wiki/spaces/DPR/pages/4461494352/Configure+DPS+RDS+Service+for+DPR+Ingestion#Setup-Connectivity) to `rds-read-replica` database.
However, the rds-read-replica database is read-only.
When I attempt to add the Postgres User for DPR:
```
CREATE ROLE digital_prison_reporting ...
ERROR:  cannot execute CREATE ROLE in a read-only transaction
```
Here, we add the DPR Security groups to the `rds-instance`
> BaSM API Preprod: Move DPR groups to rds-instance

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-a-video-link-preprod/resources/domain-events-queue-bvls.tf
PREPROD:
Now that the new BVLS service is live and all data from the old service is migrated, we no longer need to subscribe to the migrate data event.
> BAVL-439 remove the migration event in preprod from the new BVLS service now it is live and all data from the old service has been migrated.

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-a-video-link-prod/resources/domain-events-queue-bvls.tf
PROD:
Now that the new BVLS service is live and all data from the old service is migrated, we no longer need to subscribe to the migrate data event.
> BAVL-439 remove the migration event in prod from the new BVLS service now it is live and all data from the old service has been migrated.

- namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-prod/resources/irsa.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-prod/resources/rds.tf
Destroys the old Visits scheduler RDS instance cloud-platform-c6e5432ed45afd19 which has been in a shutdown state since 5th December 19:00 
This has been replaced by cloud-platform-cab7a88fc55abc11
> Destroy the old oversized Visits RDS instance in PROD

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-dpr-fake-dps-service/resources/rds-postgresql.tf
- Upgrades major version of the dpr-fake-dps-service RDS Postgres so we can do some testing with an appropriate Postgres version
- Have already added the skip apply file in a previous PR https://github.com/ministryofjustice/cloud-platform-environments/pull/28383
- This is a testing and dev database
- `aws rds describe-db-engine-versions --engine postgres --engine-version 14.11` reports that 16.2 is a valid upgrade target:
```
{
"Engine": "postgres",
"EngineVersion": "16.2",
"Description": "PostgreSQL 16.2-R3",
"AutoUpgrade": false,
"IsMajorVersionUpgrade": true
}
```
> DPR2-179 upgrade postgres version for dpr-fake-dps-service

- namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-development/resources/s3.tf
Part of the exploration of this spike: ministryofjustice/analytical-platform/issues/6355
Creates a bucket in cloud platform for us to access from AP compute dev
> feat: AP-6355 create sagemaker jumpstart bucket

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-staging/resources/main.tf
Tagging resources to enable AWS access to BaSM Staging.
As per:
https://user-guide.cloud-platform.service.justice.gov.uk/documentation/getting-started/accessing-the-cloud-console.html
> Tag resources to enable BaSM / AWS access - Staging

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-production/resources/main.tf
Tagging resources to enable AWS access to BaSM Production.
As per:
https://user-guide.cloud-platform.service.justice.gov.uk/documentation/getting-started/accessing-the-cloud-console.html
> Tag resources to enable BaSM / AWS access - Production

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-uat/resources/main.tf
Tagging resources to enable AWS access to BaSM UAT.
As per:
https://user-guide.cloud-platform.service.justice.gov.uk/documentation/getting-started/accessing-the-cloud-console.html
> Tag resources to enable BaSM / AWS access - UAT

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-criminal-legal-aid-production/resources/rds.tf
Updated RDS to 8.0.1 on `laa-apply-for-criminal-legal-aid-production`.
> CRIMAPP-1509 Update RDS to 8.0.1 on crime apply production

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-criminal-applications-datastore-production/resources/rds.tf
Updated RDS to 8.0.1 on `laa-criminal-applications-datastore-production`.
> CRIMAPP-1509 Update RDS to 8.0.1 on crime datastore production

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-review-criminal-legal-aid-production/resources/rds.tf
Updated RDS to 8.0.1 on `laa-review-criminal-legal-aid-production`.
> CRIMAPP-1509 Update RDS to 8.0.1 on crime review production

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-adjustments-dev/resources/domain-events-queue-adjustments-prisoner.tf
This enables Adjustment-API to listen to the event and keep in the sync the moving of adjustments in a booking from one prisoner to another.
https://studio.asyncapi.com/?url=https://raw.githubusercontent.com/ministryofjustice/prison-offender-events/main/async-api.yml&readOnly.
This is a backward compatible change.
https://github.com/ministryofjustice/hmpps-adjustments-api/pull/232
> Subscribe to the event - prison-offender-events.prisoner.booking.moved - Dev

- namespaces/live.cloud-platform.service.justice.gov.uk/track-a-query-qa/resources/rds.tf
The automated database backups were thought to run every day, however it seems they are every 2 days. Cloud platform have suggested setting a backup window to see whether this resolves the issue.
> Set backup window time

- namespaces/live.cloud-platform.service.justice.gov.uk/whereabouts-api-dev/resources/irsa.tf
This change removes domain event subscription for legacy BVLS code.
These domain events are now handled by the live re-platformed version of the service.
> BAVL-476 remove SNS subcription to domain events for legacy BVLS. Now handled by re-platformed service.

- namespaces/live.cloud-platform.service.justice.gov.uk/offender-events-dev/resources/whereabouts-sub-queue.tf
This change removes offender event APPOINTMENT_CHANGED subscription for legacy BVLS code in whereabouts-api.
This event is now handled by the live re-platformed version of the service.
> BAVL-476 remove SNS subcription to offender events for legacy BVLS in whereabouts. Now handled by re-platformed service.

- namespaces/live.cloud-platform.service.justice.gov.uk/whereabouts-api-preprod/resources/irsa.tf
This change removes domain event subscription for legacy BVLS code in preprod.
These domain events are now handled by the live re-platformed version of the service.
> BAVL-476 remove SNS subcription to domain events for legacy BVLS in preprod. Now handled by re-platformed service.

- namespaces/live.cloud-platform.service.justice.gov.uk/whereabouts-api-prod/resources/irsa.tf
This queue is no longer used by the underlying BVLS/whereabouts-api code so can be removed.
> BAVL-439 removing unused SQS queue domain events.

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-adjustments-dev/resources/domain-events-queue-adjustments-prisoner.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-adjustments-preprod/resources/domain-events-queue-adjustments-prisoner.tf
This enables Adjustment-API to listen to the event and keep in the sync the moving of adjustments in a booking from one prisoner to another.
https://studio.asyncapi.com/?url=https://raw.githubusercontent.com/ministryofjustice/prison-offender-events/main/async-api.yml&readOnly.
This is a backward compatible change.
https://github.com/ministryofjustice/hmpps-adjustments-api/pull/232
> Subscribe to the event - prison-offender-events.prisoner.booking.moved - Preprod

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-adjustments-prod/resources/domain-events-queue-adjustments-prisoner.tf
This enables Adjustment-API to listen to the event and keep in the sync the moving of adjustments in a booking from one prisoner to another.
https://studio.asyncapi.com/?url=https://raw.githubusercontent.com/ministryofjustice/prison-offender-events/main/async-api.yml&readOnly.
This is a backward compatible change.
https://github.com/ministryofjustice/hmpps-adjustments-api/pull/232
> Subscribe to the event - prison-offender-events.prisoner.booking.moved - Prod

- namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-live-dev/02-limitrange.yaml
We have a platform namespace that consists of a large number of small pods that support data being input to the forms deployed to the public on formbuilder.
We have recently been seeing more restarts on these pods, as we reserve a small number of pods and allow a generous 'burst' threshold, but each pod is small and I believe larger requests are when we see the pod restarts. 
As this limit range applies to all pods in the namespace, I'd like to have them reserve slightly more and burst less, in the hopes of seeing fewer pod restarts and refused connections.
This PR is on our prod sandbox namespace to start, so we can monitor the increased reserve and if it has any effect on pod restarts there, before rolling out to the prod live environment.
> Bump defaultRequest of platform pods

- namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-test-dev/02-limitrange.yaml
This namespace has a number of small pods that experience a lot of horizontal scaling, and now appear to need slightly more default requested compute as they reach target utilisation and lock up/restart more regularly.
> Bump pod default request

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-education-and-work-plan-preprod/resources/rds-postgresql.tf
``` Fix Terraform RDS version drift. Here are the RDS version mismatches: 
```
> Fix: rds version mismatch in hmpps-education-and-work-plan-preprod

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-breach-notice-dev/resources/rds.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-breach-notice-preprod/resources/rds.tf
``` Fix Terraform RDS version drift. Here are the RDS version mismatches: 
```
> Fix: rds version mismatch in hmpps-breach-notice-preprod

- namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-preprod/resources/rds-pre-sentence-service.tf
``` Fix Terraform RDS version drift. Here are the RDS version mismatches: 
downgrade from 14.12 to 14.11
```
> Fix: rds version mismatch in court-probation-preprod

- namespaces/live.cloud-platform.service.justice.gov.uk/workforce-management-preprod/resources/rds-allocation.tf
``` Fix Terraform RDS version drift. Here are the RDS version mismatches: 
```
> Fix: rds version mismatch in workforce-management-preprod

- namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-dev/resources/rds.tf
``` Fix Terraform RDS version drift. Here are the RDS version mismatches: 
```
> Fix: rds version mismatch in visit-someone-in-prison-backend-svc-dev

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-electronic-monitoring-dev/resources/rds.tf
``` Fix Terraform RDS version drift. Here are the RDS version mismatches: 
downgrade from 14.12 to 14.7
```
> Fix: rds version mismatch in hmpps-electronic-monitoring-dev

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-candidate-matching-dev/resources/rds.tf
``` Fix Terraform RDS version drift. Here are the RDS version mismatches: 
```
> Fix: rds version mismatch in hmpps-candidate-matching-dev

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-complexity-of-need-preprod/resources/rds.tf
``` Fix Terraform RDS version drift. Here are the RDS version mismatches: 
downgrade from 15.7 to 15.6
```
> Fix: rds version mismatch in hmpps-complexity-of-need-preprod

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-preprod/resources/rds.tf
Add the security group so that the DPR team can ingest Pre-prod data
> BaSM Pre-prod add security group for DPR

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-dev/resources/locals.tf
I think the old consumer name with dots in was causing problems in our service, so I'm updating to this service name without dots.
> Rename the mapps queue to match new consumer name

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-test/resources/rds.tf
* We need out test database size to match our proeprod/prod database sizes while we run our load tests.
* This will ensure that the results of our loads tests are not skewed due to environment inconsistencies
* Once the load test run in complete we will reduce the size back down
> Temporarily increase CAS RDS instance size (on test env) for load testing

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-get-payments-finance-data-dev/02-limitrange.yaml
Currently memory size is too small for larger reports
> lpf-572: increase memory for pay for legal aid dev pod

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-get-payments-finance-data-uat/02-limitrange.yaml
Currently memory size is too small for larger reports
> lpf-572: increase memory for pay for legal aid uat pod

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-get-payments-finance-data-prod/02-limitrange.yaml
Currently memory size is too small for larger reports
> lpf-572: increase memory for pay for legal aid prod pod

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-sds-dev/resources/irsa.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-sds-dev/resources/s3.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-sds-dev/resources/variables.tf
If this works it will make onboarding alot erasier for new teams as they will only require a name for the bucket.  we will leave it to teams to make sure there name is unique, we cant have generated names as the name for the bucket needs to be added to a configuration mapping an application to a bucket
> adding variable driven buckets.

- namespaces/live.cloud-platform.service.justice.gov.uk/track-a-query-staging/resources/rds.tf
Part of the investigation to resolve the database backup retention issue - https://github.com/ministryofjustice/cloud-platform/issues/6684
> Disable start stop - track-a-query-staging

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-litigator-fees-production/resources/irsa.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-litigator-fees-production/resources/rds.tf
* Updates `snapshot_identifier` in `rds.tf` to use the new snapshot
* Renames the RDS module to `rds-instance-migrated` to force a rebuild of the database, and updates all references to the module
> Update CCLF to use newly migrated production database

- namespaces/live.cloud-platform.service.justice.gov.uk/cccd-production/resources/messaging.tf
These relate to the CCR Landing Zone environment which no longer exists.
> Remove old cccd-production SQS IAM ARNs

- namespaces/live.cloud-platform.service.justice.gov.uk/use-of-force-prod/02-limitrange.yaml
The generic data extractor used by Use of Force is intermittently failing. Pod logs show an OOM error.
Increasing memory to see if this fixes issue
> MAP-2068 increase memories to fix OOM error in generic-data-extractor

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-submit-crime-forms-dev/resources/shared-s3-secret.tf
refs https://github.com/ministryofjustice/cloud-platform-environments/pull/29135
changing shared secret name - using the wrong bucket name/wrong policy for requirements
> [CRM457-1792] swap s3 bucket name

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-criminal-legal-aid-staging/resources/secret.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-criminal-legal-aid-staging/resources/variables.tf
Added the `secrets_manager` module to `laa-apply-for-criminal-legal-aid-staging` for the purpose of migrating from git-crypt to AWS Secrets Manager.
> CRIMAPP-1523 Config AWS Secrets Manager on crime apply staging

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-criminal-legal-aid-staging/resources/main.tf
Added the `GithubTeam` default tag to resources on `laa-apply-for-criminal-legal-aid-staging`.
> Add GithubTeam tag to crime apply staging resources

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-criminal-applications-datastore-staging/resources/secret.tf
Added the `secrets_manager` module to `laa-criminal-applications-datastore-staging` for the purpose of migrating from git-crypt to AWS Secrets Manager.
> CRIMAPP-1523 Config AWS Secrets Manager on crime datastore staging

- namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-gha-runner-dev/resources/ecr.tf
This PR disables ECR deletion protection in advance of namespace removal
> Disable ECR deletion protection for gha-runner-dev

- namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-flask-template/resources/ecr.tf
This PR disables ECR deletion protection in advance of namespace removal
> Disable ECR deletion protection for flask-template

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-templates-dev/resources/versions.tf
This reverts commit 3919424bd4db99a819658d1e89f242e2c82e5925.
Apologies, accidentally committed this to the template namespace rather than the intended namespace
> Revert "Update `integrations/github` version"

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-assess-risks-and-needs-integrations-dev/resources/versions.tf
Update the `integrations/github` version, accidentally updated the template project, which I've reverted in https://github.com/ministryofjustice/cloud-platform-environments/pull/29203
> Update integrations/github version for HMPPS Integrations (Dev) (Attempt #2)

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-delius-alfresco-test/resources/variables.tf
Give permissions for the cd-serviceaccount to get service accounts in the hmpps-delis-alfresco-prod namespace. This is to fix the deployment pipeline.
> Add serviceaccount get permissions for cd sa (prod)

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-organisations-dev/00-namespace.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-organisations-dev/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-organisations-dev/02-limitrange.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-organisations-dev/03-resourcequota.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-organisations-dev/04-networkpolicy.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-organisations-dev/06-certificate.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-organisations-dev/07-rbac-haar-client-admin-team.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-organisations-dev/resources/domain-events-topic.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-organisations-dev/resources/irsa.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-organisations-dev/resources/main.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-organisations-dev/resources/rds-postgresql.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-organisations-dev/resources/serviceaccount-circleci.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-organisations-dev/resources/variables.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-organisations-dev/resources/versions.tf
Create a new DEV namespace and resources for the hmpps-organisations-api service.
> PRC-429: Create a new DEV namespace for organisations

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-criminal-legal-aid-production/resources/main.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-criminal-legal-aid-production/resources/secret.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-criminal-legal-aid-production/resources/variables.tf
Added the `secrets_manager` module to `laa-apply-for-criminal-legal-aid-production` for the purpose of migrating from git-crypt to AWS Secrets Manager.
Added the GithubTeam default tag to resources on `laa-apply-for-criminal-legal-aid-production`.
> CRIMAPP-1523 Config AWS Secrets Manager on crime apply production

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-review-criminal-legal-aid-production/resources/main.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-review-criminal-legal-aid-production/resources/secret.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-review-criminal-legal-aid-production/resources/variables.tf
Added the `secrets_manager` module to `laa-review-criminal-legal-aid-production` for the purpose of migrating from git-crypt to AWS Secrets Manager.
Added the `GithubTeam` default tag to resources on `laa-review-criminal-legal-aid-production`.
> CRIMAPP-1523 Config AWS Secrets Manager on crime review production

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-criminal-applications-datastore-production/resources/secret.tf
Added the `secrets_manager` module to `laa-criminal-applications-datastore-production` for the purpose of migrating from git-crypt to AWS Secrets Manager.
> CRIMAPP-1523 Config AWS Secrets Manager on crime datastore production

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-delius-alfresco-dev/resources/variables.tf
Give permissions for the cd-serviceaccount to get service accounts in the hmpps-delis-alfresco-dev namespace. This is to fix the deployment pipeline.
> Add serviceaccount get permissions for cd sa (dev)

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-delius-alfresco-dev/resources/variables.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-delius-alfresco-preprod/resources/variables.tf
Give permissions for the cd-serviceaccount to get service accounts in the hmpps-delis-alfresco-preprod namespace. This is to fix the deployment pipeline.
> Add serviceaccount get permissions for cd sa (preprod)

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-delius-alfresco-stage/resources/variables.tf
Give permissions for the cd-serviceaccount to get service accounts in the hmpps-delis-alfresco-stage namespace. This is to fix the deployment pipeline.
> Add serviceaccount get permissions for cd sa (stage)

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-find-and-refer-an-intervention-dev/08-github-actions-runner.yaml
Removed the service account name from hmpps-find-and-refer-an-intervention-dev namespace github actions runner in order to try and fix our non-running github actions e2e tests.
> remove service account name from github action runner to try to fix actions issue

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-personal-relationships-preprod/00-namespace.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-personal-relationships-preprod/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-personal-relationships-preprod/02-limitrange.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-personal-relationships-preprod/03-resourcequota.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-personal-relationships-preprod/04-networkpolicy.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-personal-relationships-preprod/06-certificate.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-personal-relationships-preprod/resources/domain-events-topic.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-personal-relationships-preprod/resources/elasticache.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-personal-relationships-preprod/resources/irsa.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-personal-relationships-preprod/resources/main.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-personal-relationships-preprod/resources/rds-postgresql.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-personal-relationships-preprod/resources/serviceaccount-circleci.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-personal-relationships-preprod/resources/variables.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-personal-relationships-preprod/resources/versions.tf
PRC-446 : Create PREPROD environment
> PRC-446 : Create PREPROD environment 

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-litigator-fees-staging/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-litigator-fees-staging/resources/main.tf
Migration of CCLF is complete. laa-clair-taskforce is responsible now.
JIRA ticket - https://dsdmoj.atlassian.net/browse/CTSKF-922
> Change team to team responsible for CCLF staging

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-find-and-refer-an-intervention-dev/08-github-actions-runner.yaml
Update to the memory amount to test a redeployment of the github-actions-runner.
> update memory for deployment test

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-probation-integration/07-dlq-notify.yaml
Integration services are scheduled to start up at 6:30, but occasionally take longer than 30 minutes as the Delius database is still warming up.
See also https://github.com/ministryofjustice/hmpps-probation-integration-services/pull/4617
> PI-2751 Move DLQ notification schedule back 30 minutes

- namespaces/live.cloud-platform.service.justice.gov.uk/cccd-production/resources/main.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/cccd-production/resources/secrets_manager.tf
Creates a new secret by adding `resources/secrets_manager.tf`. Also adds `default_tags` to `resources/main.tf` to enable console access for secrets.
> Add secrets manager config for cccd-production

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-criminal-applications-metabase/resources/main.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-criminal-applications-metabase/resources/secret.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-criminal-applications-metabase/resources/variables.tf
Added the `secrets_manager` module to `laa-criminal-applications-metabase` for the purpose of migrating from git-crypt to AWS Secrets Manager.
Added the GithubTeam default tag to resources on `laa-criminal-applications-metabase`.
> CRIMAPP-1523 Config AWS Secrets Manager on crime metabase

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-education-and-work-plan-preprod/resources/rds-postgresql.tf
PR to add the preprod database secrets to the prod namespace (so that we can use the [database restore job](https://github.com/ministryofjustice/hmpps-helm-charts/blob/main/charts/generic-service/README.md#prison-postgres-database-restore-cronjob) to restore the prod db to preprod)
> RDS-1243 - 🔐 Add preprod database secrets to production

- namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-dev/resources/hmpps-prison-visits-allocation-prisoner-retry-queue.tf
Introduce a new queue for retrying prisoners on an individual basis.
Our main batch job runs on a per-prison basis. This queue is being introduced to allow us to capture failed allocation attempts for individual prisoners, and put them onto a queue for retrying.
without this, we would need to either:
A. retry the whole prison on the main queue.
B. wait until the main batch job re-runs the following day.
https://dsdmoj.atlassian.net/browse/VB-5190
> VB-5190 - Prisoner retry queue [dev]

- namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-staging/resources/hmpps-prison-visits-allocation-prisoner-retry-queue.tf
Introduce a new queue for retrying prisoners on an individual basis.
Our main batch job runs on a per-prison basis. This queue is being introduced to allow us to capture failed allocation attempts for individual prisoners, and put them onto a queue for retrying.
without this, we would need to either:
A. retry the whole prison on the main queue.
B. wait until the main batch job re-runs the following day.
https://dsdmoj.atlassian.net/browse/VB-5190
> VB-5190 - Prisoner retry queue [staging]

- namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-preprod/resources/hmpps-prison-visits-allocation-prisoner-retry-queue.tf
Introduce a new queue for retrying prisoners on an individual basis.
Our main batch job runs on a per-prison basis. This queue is being introduced to allow us to capture failed allocation attempts for individual prisoners, and put them onto a queue for retrying.
without this, we would need to either:
A. retry the whole prison on the main queue.
B. wait until the main batch job re-runs the following day.
https://dsdmoj.atlassian.net/browse/VB-5190
> VB-5190 - Prisoner retry queue [preprod]

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-uat/05-prometheus.yaml
Reduce alert noisiness.
Currently this is a noisy alert because once you get
a significant number of 404s from a scripted probe then
we keep including them in the total for 24 hours. So subsequent
"genuine" 404s are more likely to trip the alert for the next
24 hours, resulting in unimportant alert noise in the slack channel.
This is trying to only alert if 20+ 404s or more are seen in the last 5 minutes
for 1 minute.
> AP-5606: Reduce noise from not founds [Civil Apply UAT]

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-staging/05-prometheus.yaml
AP-5606: Reduce noise from not founds [Civil Apply Staging]
Currently this is a noisy alert because once you get
a significant number of 404s from a scripted probe then
we keep including them in the total for 24 hours. So subsequent
"genuine" 404s are more likely to trip the alert for the next
24 hours, resulting in unimportant alert noise in the slack channel.
This is trying to only alert if 20+ 404s or more are seen in the last
5 minutes for 1 minute.
> AP-5606: Reduce noise from not founds [Civil Apply Staging]

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-production/05-prometheus.yaml
Reduce noise from not founds [Civil Apply production]
Currently this is a noisy alert because once you get
a significant number of 404s from a scripted probe then
we keep including them in the total for 24 hours. So subsequent
"genuine" 404s are more likely to trip the alert for the next
24 hours, resulting in unimportant alert noise in the slack channel.
This is trying to only alert if 20+ 404s or more are seen in the last
5 minutes for 1 minute.
> AP-5606: Reduce noise from not founds [Civil Apply production]

- namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-dev/resources/hmpps-prison-visits-event.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-dev/resources/hmpps-prison-visits-notification-alerts.tf
reduce from default. We don't need the message to exist longer than 1 business day.
> Change message retention config for visits events dlq

- namespaces/live.cloud-platform.service.justice.gov.uk/cica-experian-dev/resources/s3-oidc-role.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/cica-experian-dev/resources/serviceaccount.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/cica-experian-dev/resources/variables.tf
This PR is to create a role that the Circle CI pipeline for https://github.com/ministryofjustice/cica-experian-bank-wizard/ can assume to download from the S3 bucket during build using OIDC.
> Add Role for Circle CI pipeline to access S3 bucket

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-uat/05-prometheus.yaml
AP-5606: increase notfound threshold
Too noisy every 15 due to scripted attacks.
> AP-5606: increase notfound threshold [Civil Apply UAT]

- namespaces/live.cloud-platform.service.justice.gov.uk/offender-categorisation-dev/resources/hmpps-offender-categorisation-api-domain-events-queue.tf
Fix for a copy and paste name error
> offender-categorisation-api setting correct name for queue

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-production/resources/main.tf
Changed namespace to use laa-clair-taskforce instead of laa-claim-for-payment
> Update teamname for CCR production

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-production/resources/main.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-staging/resources/main.tf
Changed namespace to use laa-clair-taskforce instead of laa-claim-for-payment
> Use correct teamname ccr staging

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-production/resources/main.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-uat/resources/main.tf
Changed namespace to use laa-clair-taskforce instead of laa-claim-for-payment
> Use correct teamname ccr uat

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-dev/resources/main.tf
Changed namespace to use laa-clair-taskforce instead of laa-claim-for-payment
> Use correct teamname for CCR dev

- namespaces/live.cloud-platform.service.justice.gov.uk/folarin-rds-namespace/resources/rds-mysql.tf
relates to https://github.com/ministryofjustice/cloud-platform/issues/5401
- adds the **snapshot_identifier**'s value to the rds-mysql manifest
- references step [3](https://user-guide.cloud-platform.service.justice.gov.uk/documentation/other-topics/rds-snapshots.html#3-update-your-current-rds-manifest-file-usually-called-rds-tf-in-the-cloud-platform-environments-repo-to-include-snapshot-identifier-and-raise-the-pr)
> add the snapshot identifier to the rds-msql module

- namespaces/live.cloud-platform.service.justice.gov.uk/folarin-rds-namespace/resources/rds-mysql.tf
- restores the database using an older **snapshot identifier** to restore the RDS database to a state before data was seeded to it
- the restoration comes after data was seeded to the database and a manual snapshot had been taken
- a manual snapshot wasn't taken [here](https://github.com/ministryofjustice/cloud-platform-environments/pull/29768) before the restore attempt, so the data was lost after the database was recreated.
relates to https://github.com/ministryofjustice/cloud-platform/issues/5401
> restore to a state before data was seeded

- namespaces/live.cloud-platform.service.justice.gov.uk/folarin-rds-namespace/resources/rds-mysql.tf
- use the manually-taken snapshot to recreate the database
- attempting to restore by using the final snapshot of the deleted DB will fail because Terraform will (by default) attempt 
to create a final snapshot with the same name for the database that's to be deleted/recreated, hence the conflict.
relates to https://github.com/ministryofjustice/cloud-platform/issues/5401
> Fix snapshotid conflict

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-test/resources/rds.tf
**Background**
* We temporarily scaled up our test db for load testing
* Load testing is now complete
**PR changes** 
* Scale the DB back down (revert previous scale up)
> Revert CAS RDS instance size on test env (as load testing complete)

- namespaces/live.cloud-platform.service.justice.gov.uk/github-community-prod/00-namespace.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/github-community-prod/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/github-community-prod/02-limitrange.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/github-community-prod/03-resourcequota.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/github-community-prod/04-networkpolicy.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/github-community-prod/resources/ecr.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/github-community-prod/resources/irsa.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/github-community-prod/resources/main.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/github-community-prod/resources/rds.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/github-community-prod/resources/serviceaccount.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/github-community-prod/resources/variables.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/github-community-prod/resources/versions.tf
- To provide a namespace for github community projects to be hosted and migrated away from Operations Engineering 
- Added `github-community-prod` Namespace with some required infrastructure for migrating some projects
> ✨ Add `github-community-prod` Namespace

- namespaces/live.cloud-platform.service.justice.gov.uk/github-community-prod/resources/variables.tf
- Fixes https://github.com/ministryofjustice/cloud-platform-environments/pull/29956
- Receives the following error due to the team name being uppercase, and the regex requires all lower case. The team name is being used in the ECR creation:
```
Error: creating ECR Repository (GitHub Community/github-community-prod): 
operation error ECR: CreateRepository, https response error StatusCode: 400, RequestID: 
d6e53279-2078-41eb-8515-d4d86a3c813d, InvalidParameterException: 
Invalid parameter at 'repositoryName' failed to satisfy constraint: 
'must satisfy regular expression '(?:[a-z0-9]+(?:[._-][a-z0-9]+)*/)*[a-z0-9]+(?:[._-][a-z0-9]+)*''
```
- Converted team name to lowercase
> 🔧 Fix Failing Deployment by Making Team Name Lowercase

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-litigator-fees-production/resources/pingdom.tf
Adds the `laa_production_environment_dashboard` tag to CCLF production to add the pingdom check to the LAA dashboard
> Add CCLF production pingdom tag

- namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-prod/resources/hmpps-prison-visits-event.tf
Disable prison-offender-events.prisoner.contact-approved and prison-offender-events.prisoner.contact-unapproved events on prod for reporting.
> Disable visitor events on prod for reporting.

- namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-prod/resources/hmpps-prison-visits-event.tf
Re-enable prison-offender-events.prisoner.contact-approved and prison-offender-events.prisoner.contact-unapproved events on prod for reporting.
> Re-enable events on prod for reporting

- namespaces/live.cloud-platform.service.justice.gov.uk/folarin-dev/resources/rds-postgresql.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/folarin-dev/resources/restored-db.tf
- reference the manual snapshot that's taken  in version 16 in the postgresql manifest
- create a new database instance to restore onto
> add v16 snapshot identifier to the postgresql manifest

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-prod/resources/elasticache.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-prod/resources/hmpps-approved-premises-api.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-prod/resources/hmpps-approved-premises-ui.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-prod/resources/hmpps-community-accommodation-tier-2-ui.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-prod/resources/hmpps-temporary-accommodation-ui.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-prod/resources/versions.tf
Following [this pr](Following this https://github.com/ministryofjustice/cloud-platform-environments/pull/29975, adding this for the test environment) adds hmpps cloud template for the prod environment
> add new hmppt cloud template for each CAS service for prod environment

- namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-dev/resources/cpr-court-cases-queue.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-dev/resources/data.tf
Create a **standard** SQS queue and subscribe it to the CPR SNS topic in **court-probation-dev**
Get CPRs SNS topic arn from `aws_ssm_parameter` resource in order to get the SQS queue to subscribe to it.
> CPR-495 Create Standard SQS queue for CPR events

- namespace-resources-cli-template/resources/prototype/basic-auth.tf
This change relates to issue [#6769](https://github.com/ministryofjustice/cloud-platform/issues/6769)
Removing the ability to set prototype credentials and instead have them set as default values.
This change has been tested in a test namespace and using the cloud-platform cli tool to ensure it works as intended.
> Remove username and password variables and setting strings instead

- .github/workflows/terraform-tools.yml
- bumps tf-tools to ubuntu-latest [#6863](https://github.com/ministryofjustice/cloud-platform/issues/6863)
> ci: bump tf-tools to use ubuntu-latest

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-dev/resources/hmpps-community-accommodation-tier-2-bail-ui.tf
Following the likes of [this pr](https://github.com/ministryofjustice/cloud-platform-environments/pull/29989) I added CAS2v2 (or CAS2 Bail UI) cloud template, as I didn't realise that not doing that would remove all their secrets
> Add cas2v2 dev cloud template

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-activities-management-prod/resources/rds.tf
revert the changes to upgrade prod database to version 16.3. Set the db_engine_version to 14.12 as that is what prod is at.
The prepare_for_major_upgrade was set in a prior PR to the upgrade itself and it failed to apply.
> SAA-2354: revert the changes to upgrade prod database to version 16.3

- namespaces/live.cloud-platform.service.justice.gov.uk/family-mediators-api-production/resources/rds.tf
``` Fix Terraform RDS version drift. Here are the RDS version mismatches: 
```
> Fix: rds version mismatch in family-mediators-api-production

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-production/resources/rds.tf
``` Fix Terraform RDS version drift. Here are the RDS version mismatches: 
```
> Fix: rds version mismatch in hmpps-book-secure-move-api-production

- namespaces/live.cloud-platform.service.justice.gov.uk/parliamentary-questions-production/resources/rds.tf
``` Fix Terraform RDS version drift. Here are the RDS version mismatches: 
```
> Fix: rds version mismatch in parliamentary-questions-production

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-welcome-to-prison-prod/resources/rds.tf
``` Fix Terraform RDS version drift. Here are the RDS version mismatches: 
```
> Fix: rds version mismatch in hmpps-welcome-to-prison-prod

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-candidate-matching-prod/resources/rds.tf
``` Fix Terraform RDS version drift. Here are the RDS version mismatches: 
```
> Fix: rds version mismatch in hmpps-candidate-matching-prod

- namespaces/live.cloud-platform.service.justice.gov.uk/offender-management-production/resources/rds.tf
``` Fix Terraform RDS version drift. Here are the RDS version mismatches: 
```
> Fix: rds version mismatch in offender-management-production

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-activities-management-preprod/resources/rds.tf
referenced from the API, so still required
> SAA-2351: re-add old db secret mapped to new db instance

- namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-preprod/resources/rds.tf
``` Fix Terraform RDS version drift. Here are the RDS version mismatches: 
```
> Fix: rds version mismatch in visit-someone-in-prison-backend-svc-preprod

- namespaces/live.cloud-platform.service.justice.gov.uk/github-community-prod/resources/route53.tf
- To give the github community a production domain name to serve the new Repository Standards project
- Added a hosted zone for `github-community.service.justice.gov.uk`
> ✨ Add Domain Name for GitHub Community

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-education-and-work-plan-prod/resources/rds-postgresql.tf
``` Fix Terraform RDS version drift. Here are the RDS version mismatches: 
```
> Fix: rds version mismatch in hmpps-education-and-work-plan-prod

- namespaces/live.cloud-platform.service.justice.gov.uk/dex-mi-production/resources/rds.tf
``` Fix Terraform RDS version drift. Here are the RDS version mismatches: 
```
> Fix: rds version mismatch in dex-mi-production

- namespaces/live.cloud-platform.service.justice.gov.uk/manage-soc-cases-prod/resources/rds.tf
``` Fix Terraform RDS version drift. Here are the RDS version mismatches: 
```
> Fix: rds version mismatch in manage-soc-cases-prod

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-tier-prod/resources/rds.tf
``` Fix Terraform RDS version drift. Here are the RDS version mismatches: 
```
> Fix: rds version mismatch in hmpps-tier-prod

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-staff-prod/resources/rds-postgresql.tf
``` Fix Terraform RDS version drift. Here are the RDS version mismatches: 
```
> Fix: rds version mismatch in hmpps-staff-prod

- namespaces/live.cloud-platform.service.justice.gov.uk/licences-prod/resources/rds.tf
``` Fix Terraform RDS version drift. Here are the RDS version mismatches: 
```
> Fix: rds version mismatch in licences-prod

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-education-employment-prod/resources/rds.tf
``` Fix Terraform RDS version drift. Here are the RDS version mismatches: 
```
> Fix: rds version mismatch in hmpps-education-employment-prod

- namespaces/live.cloud-platform.service.justice.gov.uk/find-unclaimed-court-money-production/resources/rds-postgresql.tf
``` Fix Terraform RDS version drift. Here are the RDS version mismatches: 
```
> Fix: rds version mismatch in find-unclaimed-court-money-production

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-strengths-based-needs-assessments-dev/resources/rds.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-strengths-based-needs-assessments-dev/resources/versions.tf
Terraform to add the `dblink` extension to the SAN `dev` database.
> Add dblink extension to SAN database

- namespaces/live.cloud-platform.service.justice.gov.uk/certificated-bailiffs-dev/resources/rds-postgresql.tf
``` Fix Terraform RDS version drift. Here are the RDS version mismatches: 
```
> Fix: rds version mismatch in certificated-bailiffs-dev

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-subject-access-request-dev/resources/rds.tf
https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/environments-live/jobs/apply-namespace-changes-live/builds/11125.1
> Fix: rds version mismatch in hmpps-subject-access-request-dev

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-user-preferences-prod/resources/rds.tf
``` Fix Terraform RDS version drift. Here are the RDS version mismatches: 
```
> Fix: rds version mismatch in hmpps-user-preferences-prod

- namespaces/live.cloud-platform.service.justice.gov.uk/calculate-release-dates-api-prod/resources/rds.tf
``` Fix Terraform RDS version drift. Here are the RDS version mismatches: 
```
> Fix: rds version mismatch in calculate-release-dates-api-prod

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-delius-alfrsco-poc/resources/rds.tf
``` Fix Terraform RDS version drift. Here are the RDS version mismatches: 
```
> Fix: rds version mismatch in hmpps-delius-alfrsco-poc

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-user-preferences-preprod/resources/rds.tf
``` Fix Terraform RDS version drift. Here are the RDS version mismatches: 
```
> Fix: rds version mismatch in hmpps-user-preferences-preprod

- namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-test-dev/resources/user-datastore.tf
``` Fix Terraform RDS version drift. Here are the RDS version mismatches: 
```
> Fix: rds version mismatch in formbuilder-platform-test-dev

- namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-test-production/resources/submitter.tf
Fix Terraform RDS version drift. Here are the RDS version mismatches:
> Fix: rds version mismatch in formbuilder-platform-test-production

- namespaces/live.cloud-platform.service.justice.gov.uk/iac-fees-dev/resources/rds-postgresql.tf
``` Fix Terraform RDS version drift. Here are the RDS version mismatches: 
```
> Fix: rds version mismatch in iac-fees-dev

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-interventions-dev/resources/rds-postgres14.tf
``` Fix Terraform RDS version drift. Here are the RDS version mismatches: 
```
> Fix: rds version mismatch in hmpps-interventions-dev

- namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-live-dev/resources/submitter.tf
``` Fix Terraform RDS version drift. Here are the RDS version mismatches: 
```
> Fix: rds version mismatch in formbuilder-platform-live-dev

- namespaces/live.cloud-platform.service.justice.gov.uk/cfe-civil-staging/resources/rds.tf
``` Fix Terraform RDS version drift. Here are the RDS version mismatches: 
```
> Fix: rds version mismatch in cfe-civil-staging

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-workload-prod/resources/rds-live.tf
``` Fix Terraform RDS version drift. Here are the RDS version mismatches: 
```
> Fix: rds version mismatch in hmpps-workload-prod

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-test/resources/hmpps-community-accommodation-tier-2-bail-ui.tf
Following the likes of https://github.com/ministryofjustice/cloud-platform-environments/pull/29989 I've added CAS2v2 (or CAS2 Bail UI) cloud template for the new test env
> Add CAS 2 Bail Test environment config

- namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-saas-live/resources/metadata_api.tf
``` Fix Terraform RDS version drift. Here are the RDS version mismatches: 
```
> Fix: rds version mismatch in formbuilder-saas-live

- namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-live-production/resources/submitter.tf
Fix Terraform RDS version drift. Here are the RDS version mismatches:
> Fix: rds version mismatch in formbuilder-platform-live-production

- namespaces/live.cloud-platform.service.justice.gov.uk/make-recall-decision-prod/resources/postgresql.tf
``` Fix Terraform RDS version drift. Here are the RDS version mismatches: 
downgrade from 13.16 to 13.15
```
> Fix: rds version mismatch in make-recall-decision-prod

- namespaces/live.cloud-platform.service.justice.gov.uk/iac-fees-prod/resources/rds-postgresql.tf
``` Fix Terraform RDS version drift. Here are the RDS version mismatches: 
```
> Fix: rds version mismatch in iac-fees-prod

- namespaces/live.cloud-platform.service.justice.gov.uk/certificated-bailiffs-preprod/resources/rds-postgresql.tf
``` Fix Terraform RDS version drift. Here are the RDS version mismatches: 
```
> Fix: rds version mismatch in certificated-bailiffs-preprod

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-preprod/resources/rds.tf
Pre-Prod: increase db_allocated_storage from 10 to 50 for read_replica module
See related PR (already done) to increase storage for the rds module: https://github.com/ministryofjustice/cloud-platform-environments/pull/30366
> CAS pre-prod database: increase db_allocated_storage from 10 to 50 for rds module

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-person-record-prod/resources/person-match-rds.tf
* Increase to 90GiB allocated mem to support migration, Will revert to auto scaling after migration
> CPR-629 Scale up rds to support migration

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-cwa-test/resources/ecr.tf
Disable namespace association between ECR `laa-cwa-test` and namespaces `laa-cwa-feature-tests`, `laa-cwa`
> chore: disable ecr namespace association

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-templates-dev/06-certificate.yaml
As part of ephemeral deployment testing work
> Add subdomain wildcard for `template-typescript-dev`

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-dev/04-networkpolicy.yaml
I want to enable Prometheus scraping of metrics for laa-crown-court-remuneration-dev
> Enable prometheus scraping for laa ccr dev

- namespaces/live.cloud-platform.service.justice.gov.uk/send-legal-mail-to-prisons-dev/resources/rds.tf
``` Fix Terraform RDS version drift. Here are the RDS version mismatches: 
```
> Fix: rds version mismatch in send-legal-mail-to-prisons-dev

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-user-preferences-dev/resources/rds.tf
``` Fix Terraform RDS version drift. Here are the RDS version mismatches: 
```
> Fix: rds version mismatch in hmpps-user-preferences-dev

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-a-video-link-dev/resources/appinsights.tf
This change is needed on the back of an issue identified [here](https://github.com/ministryofjustice/dps-gradle-spring-boot/blob/main/release-notes/7.x.md#710).
The API change will follow once this has been deployed to DEV.
> BAVL-695 add app insights key to fix app insights warnings in DEV.

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-personal-relationships-dev/resources/rds-postgresql.tf
Increased from db.t4g.micro to db.t4g.small to be able to handle heavy workloads while testing sync and migrate with syscon.
> PRC-570: Increase personal relationships dev DB size

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-dev/06-servicemonitor.yaml
I want a service monitor added for the ccr dev environment to enable Prometheus scraping
> Add ServiceMonitor for ccr dev

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-a-video-link-preprod/resources/appinsights.tf
This change is needed on the back of an issue identified [here](https://github.com/ministryofjustice/dps-gradle-spring-boot/blob/main/release-notes/7.x.md#710).
DEV is already done.
> BAVL-695 add app insights key to fix app insights warnings in PREPROD.

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-a-video-link-prod/resources/appinsights.tf
This change is needed on the back of an issue identified [here](https://github.com/ministryofjustice/dps-gradle-spring-boot/blob/main/release-notes/7.x.md#710).
> BAVL-695 add app insights key to fix app insights warnings in PROD.

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-ui-production/resources/rds.tf
AWS has already auto-upgraded us to 14.13, so we need to bump this to allow other configuration changes to be applied
> Bump RDS version

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-strengths-based-needs-assessments-dev/resources/rds.tf
PR to add a Foreign Data Wrapper to the Assessments database using the information exposed by https://github.com/ministryofjustice/cloud-platform-environments/pull/30468/.
> Add Postgres FDW to the Assessments database

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-dev/resources/irsa.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-dev/resources/hmpps-integration-api.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-dev/resources/hmpps-prison-visits-write-events.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-dev/resources/irsa.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-dev/resources/ssm.tf
The purpose of this PR:
* Add a new queue + dead letter queue to the `visit-someone-in-prison-backend-svc-*` namespaces for visit writes
* We will be listening to this queue in `manage-prison-visits-orchestation` or `visits-scheduler` service
* Allow the HMPPS Integration API to write to this queue
> HMAI-332 - Add visit write queue

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-dev/06-servicemonitor.yaml
The exposed port name of ccr-dev is "http" which is not what is listed in the service monitor.
You can see the name by command `kubectl -n laa-crown-court-remuneration-dev get svc laa-crown-court-remuneration-app -o jsonpath='{range .spec}{"Name: "}{.ports[*].name}{"\nPort: "}{@.ports[*].port}{"\n"}{end}'
`
> CCR dev - Fix port name in service monitor

- namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-dev/01-rbac.yaml
We require a local dev instance of visit-scheduler in order to support our implementation of a queue between hmpps-int-api and the scheduler
> Added millsike github group to visit-scheduler rbac

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-means-assessment-prod/resources/rds.tf
``` Fix Terraform RDS version drift. Here are the RDS version mismatches: 
```
> Fix: rds version mismatch in laa-crime-means-assessment-prod

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-delius-alfresco-dev/resources/rds.tf
``` Fix Terraform RDS version drift. Here are the RDS version mismatches: 
```
> Fix: rds version mismatch in hmpps-delius-alfresco-dev

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-means-assessment-test/resources/rds.tf
``` Fix Terraform RDS version drift. Here are the RDS version mismatches: 
```
> Fix: rds version mismatch in laa-crime-means-assessment-test

- namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-prod/resources/rds.tf
``` Fix Terraform RDS version drift. Here are the RDS version mismatches: 
``` …
> Fix: rds version mismatch in visit-someone-in-prison-backend-svc-prod

- namespaces/live.cloud-platform.service.justice.gov.uk/care-arrangement-plan-dev/resources/elasticache.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/care-arrangement-plan-dev/resources/versions.tf
Adding redis for the Care Arrangement Plan - https://github.com/ministryofjustice/care-arrangement-plan.
Author: @josephsilcock
> care-arrangement-plan-dev Add elasticache

- namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-dev/07-certificate.yaml
Remove this in dev
This is because court-list-splitter has been archived and no longer in use.
> PIC-3705 remove court-list-splitter references in DEV

- namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-prod/07-certificate.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-prod/10-prometheus-k8s-dashboard.yaml
This is because court-list-splitter has been archived and no longer in use.
> PIC-3705 remove court-list-splitter references in Prod

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-ui-production/prometheus.yaml
The query doesn't actually count the number of 404s, and even if it did, most 404s are generated by bots like NCSC Web Check etc, and so this alert doesn't tell us anything helpful and just generates noise
> Remove alert that generates false positives

- namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-reports-dev/resources/ecr.tf
- blocking #30713 
- To enable the deletion of the namespace
- Disabled deletion protection on the ECR Resource
> 🔥 Remove ECR Protection in `operations-engineering-reports-dev`

- namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-reports-dev/resources/ecr.tf
- To enable the deletion of the namespace
- Disabled ECR Deletion protection
> 🔥 Remove ECR Deletion Protection in `operations-engineering-reports-prod`

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-proceeding-test/04-networkpolicy.yaml
- Added network policy to CCP to enable cross namespace integration with functional tests.
> LCAM 1484 Enable Integration Between Functional Tests and CCP

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-test/08-github-actions-runner.yaml
I haven't managed to get my playwright e2e tests running on GH Actions yet.
After chatting to Tom from the ARNS team, he suggested creating a runner - as they did for there project.
This PR copies his: https://github.com/ministryofjustice/cloud-platform-environments/pull/29086
Currently, e2e tests just hang here doing nothing:
> adds self hosted runner for CAS ap UI test env

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-preprod/resources/appinsights.tf
The appinsights secret was missing and deployment is failing. It looks like this file needs to be added for the Github Actions deployments
> Add appinsights to allow CAS2 Bail preprod

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-dev/05-prometheus.yaml
Added an alert so that when there's an increase in the amount of errors scraped over one minute, an alert is raised
> CCR dev - Add alert for new payment_get_errors

- namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-find-a-github-repository-owner-dev/resources/ecr.tf
- In relation to https://github.com/ministryofjustice/github-community/issues/27
- To prepare the removal of the namespace
- Removed ECR deletion protection
> 🔥 Remove ECR Deletion Protection in `operations-engineering-find-a-github-repository-owner-dev`

- namespaces/live.cloud-platform.service.justice.gov.uk/james-dev/02-limitrange.yaml
This will help with github actions runners
> bump limit range to 3GB

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-dev/prometheus-custom-rules-laa-dces-report-service.yaml
Adding more defined alerts for specific responses we want to monitor.
( Some to be later disabled for development environments, this is the template alerts for the service )
Removing alerts that didn't make sense given the final state of the service. ( We no longer have any endpoints, so not worth looking at those )
> DCES Alerting DEV

- namespaces/live.cloud-platform.service.justice.gov.uk/sw-psa-audit-test/resources/ecr.tf
heres a PR with no changes, and no legacy_naming flag set.
EXPECTING: no change anyway, because of lifecycle ignore change
> chore: 🤖 trigger build on no change

- namespaces/live.cloud-platform.service.justice.gov.uk/sw-psa-audit-test/resources/ecr-2.tf
test new changes:
- utilise the legacy_naming flag
should just create another ECR using old team name approach
> chore: 🤖 add another test ecr resource in ns

- namespaces/live.cloud-platform.service.justice.gov.uk/sw-psa-audit-test/resources/ecr-3.tf
ECRs created following branch containing bugfix for team name error should, by default, use naming convention:
```
cloud-platform/var.repo_name
```
> chore: 🤖 add an ecr resource with new cloud-platform naming

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-access-civil-legal-aid-staging/05-certificate.yaml
Adds a TLS certificate to the staging environment of Access Civil Legal Aid
> LAA Access Civil Legal Aid - Add TLS Certificate

- namespaces/live.cloud-platform.service.justice.gov.uk/c100-application-production/resources/variables.tf
- Fix Terraform RDS version drift for namespace: `c100-application-production`
```
module.rds-instance: downgrade from 14.12 to 14.13
```
> Fix: rds version mismatch in c100-application-production

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-staging/resources/rds.tf
- Fix Terraform RDS version drift for namespace: `laa-crown-court-remuneration-staging`
```
module.rds-instance-migrated: downgrade from 19.0.0.0.ru-2024-10.rur-2024-10.r1 to 19.0.0.0.ru-2025-01.rur-2025-01.r1
```
> Fix: rds version mismatch in laa-crown-court-remuneration-staging

- namespaces/live.cloud-platform.service.justice.gov.uk/justice-gov-uk-staging/resources/rds.tf
- Fix Terraform RDS version drift for namespace: `justice-gov-uk-staging`
```
module.rds: downgrade from 10.11.6 to 10.11.8
```
> Fix: rds version mismatch in justice-gov-uk-staging

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-cla-public-staging/06-certificate.yaml
Adds the beta environment to the public dns certificate.
> LAA Check if you can get legal aid DNS certificate Update

- namespaces/live.cloud-platform.service.justice.gov.uk/tim-development/resources/rds.tf
- Fix Terraform RDS version drift for namespace: `tim-development`
```
module.rds_2: downgrade from 16.6 to 16.4
module.rds: downgrade from 16.6 to 16.4
```
> Fix: rds version mismatch in tim-development

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-production/resources/rds.tf
- Fix Terraform RDS version drift for namespace: `laa-crown-court-remuneration-production`
```
module.migrated-rds-instance: downgrade from 19.0.0.0.ru-2024-10.rur-2024-10.r1 to 19.0.0.0.ru-2025-01.rur-2025-01.r1
```
> Fix: rds version mismatch in laa-crown-court-remuneration-production

- namespaces/live.cloud-platform.service.justice.gov.uk/certificated-bailiffs-prod/resources/rds-postgresql.tf
- Fix Terraform RDS version drift for namespace: `certificated-bailiffs-prod`
```
module.rds: downgrade from 14.12 to 14.13
```
> Fix: rds version mismatch in certificated-bailiffs-prod

- namespaces/live.cloud-platform.service.justice.gov.uk/intranet-production/resources/rds.tf
- Fix Terraform RDS version drift for namespace: `intranet-production`
```
module.rds: downgrade from 10.11.9 to 10.11.10
```
> Fix: rds version mismatch in intranet-production

- namespaces/live.cloud-platform.service.justice.gov.uk/create-and-vary-a-licence-api-prod/resources/rds.tf
- Fix Terraform RDS version drift for namespace: `create-and-vary-a-licence-api-prod`
```
module.create_and_vary_a_licence_api_rds: downgrade from 15.7 to 15.8
```
> Fix: rds version mismatch in create-and-vary-a-licence-api-prod

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-litigator-fees-production/resources/rds.tf
- Fix Terraform RDS version drift for namespace: `laa-crown-court-litigator-fees-production`
```
module.rds-instance-migrated: downgrade from 19.0.0.0.ru-2024-07.rur-2024-07.r1 to 19.0.0.0.ru-2025-01.rur-2025-01.r1
```
> Fix: rds version mismatch in laa-crown-court-litigator-fees-production

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-staff-dev/resources/rds-postgresql.tf
- Fix Terraform RDS version drift for namespace: `hmpps-staff-dev`
```
module.rds: downgrade from 15.5 to 15.7
```
> Fix: rds version mismatch in hmpps-staff-dev

- namespaces/live.cloud-platform.service.justice.gov.uk/hmcts-complaints-formbuilder-adapter-staging/resources/rds.tf
- Fix Terraform RDS version drift for namespace: `hmcts-complaints-formbuilder-adapter-staging`
```
module.hmcts-complaints-adapter-rds-instance: downgrade from 14.12 to 14.13
```
> Fix: rds version mismatch in hmcts-complaints-formbuilder-adapter-staging

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-uat/resources/rds.tf
- Fix Terraform RDS version drift for namespace: `laa-crown-court-remuneration-uat`
```
module.rds-instance-migrated: downgrade from 19.0.0.0.ru-2024-10.rur-2024-10.r1 to 19.0.0.0.ru-2025-01.rur-2025-01.r1
```
> Fix: rds version mismatch in laa-crown-court-remuneration-uat

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-electronic-monitoring-preprod/resources/rds.tf
- Fix Terraform RDS version drift for namespace: `hmpps-electronic-monitoring-preprod`
```
module.rds: downgrade from 14.7 to 14.13
```
> Fix: rds version mismatch in hmpps-electronic-monitoring-preprod

- namespaces/live.cloud-platform.service.justice.gov.uk/track-a-query-production/resources/rds.tf
- Fix Terraform RDS version drift for namespace: `track-a-query-production`
```
module.track_a_query_rds: downgrade from 16.3 to 16.4
```
> Fix: rds version mismatch in track-a-query-production

- namespaces/live.cloud-platform.service.justice.gov.uk/licences-dev/resources/rds.tf
- Fix Terraform RDS version drift for namespace: `licences-dev`
```
module.dps_rds: downgrade from 15.7 to 15.8
```
> Fix: rds version mismatch in licences-dev

- namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-dev/resources/rds.tf
- Fix Terraform RDS version drift for namespace: `claim-criminal-injuries-compensation-dev`
```
module.rds: downgrade from 14.12 to 14.13
```
> Fix: rds version mismatch in claim-criminal-injuries-compensation-dev

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-means-assessment-dev/resources/rds.tf
- Fix Terraform RDS version drift for namespace: `laa-crime-means-assessment-dev`
```
module.rds: downgrade from 14.7 to 14.13
```
> Fix: rds version mismatch in laa-crime-means-assessment-dev

- namespaces/live.cloud-platform.service.justice.gov.uk/civil-appeal-case-tracker-dev/resources/rds-postgresql.tf
- Fix Terraform RDS version drift for namespace: `civil-appeal-case-tracker-dev`
```
module.rds: downgrade from 14.12 to 14.13
```
> Fix: rds version mismatch in civil-appeal-case-tracker-dev

- namespaces/live.cloud-platform.service.justice.gov.uk/manage-soc-cases-dev/resources/rds.tf
- Fix Terraform RDS version drift for namespace: `manage-soc-cases-dev`
```
module.dps_rds: downgrade from 15.7 to 15.8
```
> Fix: rds version mismatch in manage-soc-cases-dev

- namespaces/live.cloud-platform.service.justice.gov.uk/create-and-vary-a-licence-test1/resources/rds.tf
- Fix Terraform RDS version drift for namespace: `create-and-vary-a-licence-test1`
```
module.create_and_vary_a_licence_api_rds: downgrade from 15.7 to 15.8
```
> Fix: rds version mismatch in create-and-vary-a-licence-test1

- namespaces/live.cloud-platform.service.justice.gov.uk/workforce-management-prod/resources/rds-allocation.tf
- Fix Terraform RDS version drift for namespace: `workforce-management-prod`
```
module.rds-allocation: downgrade from 15.7 to 15.8
```
> Fix: rds version mismatch in workforce-management-prod

- namespaces/live.cloud-platform.service.justice.gov.uk/send-legal-mail-to-prisons-preprod/resources/rds.tf
- Fix Terraform RDS version drift for namespace: `send-legal-mail-to-prisons-preprod`
```
module.slmtp_api_rds: downgrade from 15.7 to 15.8
```
> Fix: rds version mismatch in send-legal-mail-to-prisons-preprod

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-validation-test/resources/rds-postgresql.tf
- Fix Terraform RDS version drift for namespace: `laa-crime-validation-test`
```
module.rds: downgrade from 14.7 to 14.13
```
> Fix: rds version mismatch in laa-crime-validation-test

- namespaces/live.cloud-platform.service.justice.gov.uk/intranet-staging/resources/rds.tf
- Fix Terraform RDS version drift for namespace: `intranet-staging`
```
module.rds: downgrade from 10.11.6 to 10.11.8
```
> Fix: rds version mismatch in intranet-staging

- namespaces/live.cloud-platform.service.justice.gov.uk/prison-visits-booking-staging/resources/rds-prison-visits.tf
- Fix Terraform RDS version drift for namespace: `prison-visits-booking-staging`
```
module.prison-visits-rds: downgrade from 15.7 to 15.8
```
> Fix: rds version mismatch in prison-visits-booking-staging

- namespaces/live.cloud-platform.service.justice.gov.uk/prison-visits-booking-production/resources/rds-prison-visits.tf
- Fix Terraform RDS version drift for namespace: `prison-visits-booking-production`
```
module.prison-visits-rds: downgrade from 15.7 to 15.8
```
> Fix: rds version mismatch in prison-visits-booking-production

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-litigator-fees-uat/resources/rds.tf
- Fix Terraform RDS version drift for namespace: `laa-crown-court-litigator-fees-uat`
```
module.rds-instance-migrated: downgrade from 19.0.0.0.ru-2024-10.rur-2024-10.r1 to 19.0.0.0.ru-2025-01.rur-2025-01.r1
```
> Fix: rds version mismatch in laa-crown-court-litigator-fees-uat

- namespaces/live.cloud-platform.service.justice.gov.uk/hmcts-complaints-formbuilder-adapter-production/resources/rds.tf
- Fix Terraform RDS version drift for namespace: `hmcts-complaints-formbuilder-adapter-production`
```
module.hmcts-complaints-adapter-rds-instance: downgrade from 14.12 to 14.13
```
> Fix: rds version mismatch in hmcts-complaints-formbuilder-adapter-production

- namespaces/live.cloud-platform.service.justice.gov.uk/grc-prod/resources/rds.tf
- Fix Terraform RDS version drift for namespace: `grc-prod`
```
module.dps_rds: downgrade from 14.12 to 14.13
```
> Fix: rds version mismatch in grc-prod

- namespaces/live.cloud-platform.service.justice.gov.uk/contact-moj-production/resources/rds.tf
- Fix Terraform RDS version drift for namespace: `contact-moj-production`
```
module.contact-moj_rds: downgrade from 16.3 to 16.4
```
> Fix: rds version mismatch in contact-moj-production

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-litigator-fees-staging/resources/rds.tf
- Fix Terraform RDS version drift for namespace: `laa-crown-court-litigator-fees-staging`
```
module.rds-instance-migrated: downgrade from 19.0.0.0.ru-2024-10.rur-2024-10.r1 to 19.0.0.0.ru-2025-01.rur-2025-01.r1
```
> Fix: rds version mismatch in laa-crown-court-litigator-fees-staging

- namespaces/live.cloud-platform.service.justice.gov.uk/create-and-vary-a-licence-api-preprod/resources/rds.tf
- Fix Terraform RDS version drift for namespace: `create-and-vary-a-licence-api-preprod`
```
module.create_and_vary_a_licence_api_rds: downgrade from 15.7 to 15.8
```
> Fix: rds version mismatch in create-and-vary-a-licence-api-preprod

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-a-video-link-dev/resources/domain-events-queue-bvls.tf
Change to subscribe to the appointments changed domain event in dev.
This is so the BVLS API can take the appropriate action for any video bookings affected by the prisoners appointments related to this event.
Associated API PR [here](https://github.com/ministryofjustice/hmpps-book-a-video-link-api/pull/459).
> BAVL-752 subscribe to the appointments changed domain event for the BVLS API to process.

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-accredited-programmes-dev/resources/rds-postgresql.tf
- Allow major version upgrades for RDS instances 
- Upgrade the PostgreSQL version to 16.4. 
- Adjusted the RDS family to match the new version.
> [APG-536] Bump up PostgreSQL to 16.4 in Dev

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-electronic-monitoring-datastore-dev/resources/cross-iam-role-sa.tf
Add an assumable role to hmpps-electronic-monitoring-datastore-dev.
This role allows testing of role based access to restricted data (using test data).
> hmpps-electronic-monitoring-datastore-dev: Update IRSA account roles

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-test/resources/hmpps-approved-premises-ui.tf
The Test environment for CAS1 is fully decoupled from the main pipeline, so no deployment to test can be promoted to preprod or prod.
> CAS1 UI - Allow deployment to test from any branch

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-vcms-notification-poc-dev/resources/rds-mysql.tf
- Fix Terraform RDS version drift for namespace: `hmpps-vcms-notification-poc-dev`
```
module.rds_mysql: downgrade from 8.0.40 to 8.0.35
```
> Fix: rds version mismatch in hmpps-vcms-notification-poc-dev

- namespaces/live.cloud-platform.service.justice.gov.uk/sif-development/resources/rds.tf
- Fix Terraform RDS version drift for namespace: `sif-development`
```
module.rds: downgrade from 14.13 to 14.12
```
> Fix: rds version mismatch in sif-development

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-accredited-programmes-preprod/resources/rds-postgresql.tf
- Updated the RDS configuration to upgrade PostgreSQL from version 14.13 to 16.4.
- Adjusted the RDS family and set the `prepare_for_major_upgrade` to true
> [APG-536] Upgrade PostgreSQL version for Accredited Programmes in Pre-Prod

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-accredited-programmes-preprod/resources/rds-postgresql.tf
- The `prepare_for_major_upgrade` flag was returned to `false` in the RDS configuration
- The `APPLY_PIPELINE_SKIP_THIS_NAMESPACE` file was removed
>  [APG-536] Disable major upgrade preparation flag and remove skip file on pre-prod

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-accredited-programmes-prod/resources/rds-postgresql.tf
- Allow for major RDS version upgrades 
- Update PostgreSQL to version 16.4. 
- Updates the RDS family to match the new PostgreSQL version.
>  [APG-536] Enable major version upgrade for RDS and update PostgreSQL version in Prod

- namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-live-production/02-limitrange.yaml
Upgrade cpu size from 10m to 50m.  This brings the pod size in live with the dev environment.
> Update Form Builder live cpu size

- namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-datahub-catalogue-prod/resources/variables.tf
Removes deletion protection as appears to be required as per the concourse build failure of previous PR - https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/environments-live/jobs/apply-namespace-changes-live/builds/12166
> Change default value of deletion protection for RDS instance to false

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-cwa-feature-tests-test/resources/serviceaccount.tf
Need to inject secrets into the cwa-test-provider-api repo for the laa-cwa-feature-tests-test namespace.
> add cwa-test-provider-api repo to serviceaccount module for laa-cwa-feature-tests-test namespace

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-preprod/resources/hmpps-temporary-accommodation-ui.tf
`preprod`: deploy review from pipeline, only main branch
Follows [similar change done on CAS1](https://github.com/ministryofjustice/cloud-platform-environments/pull/32229)
> Update CAS3 UI env protection rules - preprod

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-prod/resources/hmpps-temporary-accommodation-ui.tf
`prod`: deploy review from pipeline, only main branch
Follows [similar change done on CAS1](https://github.com/ministryofjustice/cloud-platform-environments/pull/32227)
> Update CAS3 UI environment protection rules - prod

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-preprod/resources/hmpps-community-accommodation-tier-2-ui.tf
`preprod`: deploy review from pipeline, only main branch
Follows [similar change done on CAS1](https://github.com/ministryofjustice/cloud-platform-environments/pull/32229)
> Update CAS2 UI env protection rules - preprod

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-dev/resources/hmpps-community-accommodation-tier-2-ui.tf
`development`: auto-deploys from pipeline, only main branch
Follows [similar change done on CAS1](https://github.com/ministryofjustice/cloud-platform-environments/pull/32228)
> Update CAS2 UI environment protection rules - dev

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-dev/resources/locals.tf
This is so it can be re-added to rotate the API Key attached to the bmadley consumer
> Remove bmadley API client

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-dev/resources/s3_truststore.tf
This is to avoid us having to have special cases in the uploadp12 script in Integration API
> Change certificate path so that the path matches other environments

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-electronic-monitoring-datastore-dev/resources/cross-iam-role-sa.tf
Remove superfluous base64 encoding of secrets in `hmpps-electronic-monitoring-datastore-dev`.
> Remove superfluous base64 encoding of some secrets

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-test/resources/hmpps-approved-premises-api.tf
`test`: deploy review from separate 'Deploy to test' workflow, for any branch
Follows [similar change done on CAS1](https://github.com/ministryofjustice/cloud-platform-environments/pull/32230)
> Update CAS API environment protection rules - test

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-dev/resources/hmpps-approved-premises-api.tf
`development`: auto-deploys from pipeline, only main branch
Follows [similar change done on CAS1](https://github.com/ministryofjustice/cloud-platform-environments/pull/32228)
> Update CAS API environment protection rules - dev

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-preprod/resources/hmpps-approved-premises-api.tf
`preprod`: deploy review from pipeline, only main branch
Follows [similar change done on CAS1](https://github.com/ministryofjustice/cloud-platform-environments/pull/32229)
> Update CAS API env protection rules - preprod

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-electronic-monitoring-datastore-dev/resources/cross-iam-role-sa.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-electronic-monitoring-datastore-dev/resources/main.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-electronic-monitoring-datastore-dev/resources/ssm.tf
In namespace `hmpps-electronic-monitoring-datastore-dev`:
- configure SSM for storing role ARNs
- remove a superfluous ARN
- parameterise `tags` for convenient reuse.
> hmpps-electronic-monitoring-datastore-dev: Configure SSM

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-electronic-monitoring-datastore-dev/resources/cross-iam-role-sa.tf
A prior commit removed some hardcoded ARNs from the namespace
`hmpps-electronic-monitoring-datastore-dev`.
This was expected to break aspects of the dev service temporarily until a new feature was implemented to store the ARNs as AWS SSM parameters.
This change prevents that breakage,
and allows continued work on the new feature.
> hmpps-electronic-monitoring-datastore-dev: Temporarily add some test ARNs.

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-events-dev/resources/variables.tf
We will be decommissioning the `offender-management-test` namespace soon. Cleaning up any references found in other namespaces.
> MO-1682 Remove MPC test topic reference

- namespaces/live.cloud-platform.service.justice.gov.uk/offender-management-staging/resources/elasticache.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/offender-management-staging/resources/rds.tf
We will be decommissioning the `offender-management-test namespace` soon. Cleaning up any references found in other namespaces.
> MO-1682 Remove MPC test references

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-electronic-monitoring-datastore-dev/resources/cross-iam-role-sa.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-electronic-monitoring-datastore-dev/resources/iam-policies.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-electronic-monitoring-datastore-dev/resources/kubernetes-secrets.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-electronic-monitoring-datastore-dev/resources/locals.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-electronic-monitoring-datastore-dev/resources/main.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-electronic-monitoring-datastore-dev/resources/ssm.tf
In `hmpps-electronic-monitoring-datastore-dev`:
- Give the service pod SSM parameter permissions
- Refactor the service pod config for ease of maintenance
> hmpps-electronic-monitoring-datastore-dev: Service pod SSM config

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-electronic-monitoring-datastore-dev/resources/iam-policies.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-electronic-monitoring-datastore-dev/resources/kubernetes-secrets.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-electronic-monitoring-datastore-dev/resources/locals.tf
In hmpps-electronic-monitoring-datastore-dev: 
- Remove hardcoded ARNs from the namespace
- Use SSM parameters instead
- Remove some obsolete test content
> hmpps-electronic-monitoring-datastore-dev: Replace hardcoded ARNs with SSM parameters.

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-electronic-monitoring-datastore-preprod/resources/cross-iam-role-sa.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-electronic-monitoring-datastore-preprod/resources/iam-policies.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-electronic-monitoring-datastore-preprod/resources/kubernetes-secrets.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-electronic-monitoring-datastore-preprod/resources/locals.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-electronic-monitoring-datastore-preprod/resources/ssm.tf
- Store ARNs as as SSM parameters.
- Provide these to services in the pod as kubernetes secrets.
- Refactoring.
> hmpps-electronic-monitoring-datastore-preprod: SSM parameterts

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-electronic-monitoring-datastore-preprod/resources/iam-policies.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-electronic-monitoring-datastore-preprod/resources/kubernetes-secrets.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-electronic-monitoring-datastore-preprod/resources/ssm.tf
In `hmpps-electronic-monitoring-datastore-preprod`:
Remove Athena ARN data properties. Use SSM resource values instead.
> hmpps-electronic-monitoring-datastore-preprod: Use SSM resource values in place of data properties.

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-electronic-monitoring-datastore-preprod/resources/iam-policies.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-electronic-monitoring-datastore-preprod/resources/kubernetes-secrets.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-electronic-monitoring-datastore-preprod/resources/ssm.tf
In `hmpps-electronic-monitoring-datastore-preprod`,
reintroduce some data properties that were previously removed.
They were removed as they tried to access AWS SSM parameters that had not yet been created, causing an error.
Now that the SSM parameters have been created the data properties can be reintroduced.
> hmpps-electronic-monitoring-datastore-preprod: Reintroduce ARN data properties.

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-electronic-monitoring-datastore-preprod/00-namespace.yaml
In `hmpps-electronic-monitoring-datastore-preprod`,
correct the `source-code` metadata property in `00-namespace.yaml`.
> hmpps-electronic-monitoring-datastore-preprod: Correct source code reference

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-review-criminal-legal-aid-staging/04-networkpolicy.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-review-criminal-legal-aid-staging/07-prometheus-sidekiq.yaml
This change updates the Prometheus network policy for `laa-review-criminal-legal-aid-staging` by changing the selector to `metrics-target: laa-review-criminal-legal-aid-staging-metrics-target`, which should now select both the web app pods and the new worker pods.
This also adds a couple of Prometheus rules for Sidekiq.
> CRIMAPP-1679 Update network policy in crime review staging

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-electronic-monitoring-datastore-prod/resources/cross-iam-role-sa.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-electronic-monitoring-datastore-prod/resources/iam-policies.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-electronic-monitoring-datastore-prod/resources/kubernetes-secrets.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-electronic-monitoring-datastore-prod/resources/locals.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-electronic-monitoring-datastore-prod/resources/ssm.tf
In `hmpps-electronic-monitoring-datastore-prod`:
- Create SSM parameters for storage of Athena access role ARNs
- Provide these as kubernetes secrets in the namespace
- Refactor the namespace directory for ease of use and maintenance
> hmpps-electronic-monitoring-datastore-prod: Create SSM parameters for Athena access role ARNs

- namespaces/live.cloud-platform.service.justice.gov.uk/sif-staging/resources/rds.tf
- Fix Terraform RDS version drift for namespace: `sif-staging`
```
module.rds: downgrade from 16.4 to 16.3
```
> Fix: rds version mismatch in sif-staging

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-review-criminal-legal-aid-staging/resources/s3.tf
This change adds an S3 bucket resource to `laa-review-criminal-legal-aid-staging`.
> CRIMAPP-1679 Add S3 bucket to crime review staging

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-preprod/resources/api_gateway.tf
Our API Gateway logs contain PII and other Personal data. This seems unideal and we hope that changing `data_trace_enabled` to `false` will resolve this.
> HIA-790 Restrict API Gateway logging in pre-prod

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-prod/resources/api_gateway.tf
Change `data_trace_enabled` to `false` to remove PII from logs
> HIA-790 Restrict API Gateway logging in prod

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-manage-your-civil-cases-production/05-prometheus-custom-rules.yaml
As this service is not yet live, and we only specify 2 pods in production
This is generating unnecessary alerts.
> Temporarily reduce low pod count alert level

- namespaces/live.cloud-platform.service.justice.gov.uk/certificated-bailiffs-dev/resources/apex-rds-oracle.tf
MOJ rds module sets the default db param to "rds.force_ssl" and this is not applicable in Oracle db. Want to have the default set so working around
> RST-7307: Adding a empty db param to avoid the force ssl being made on oracle

- namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-services-live-dev/03-resourcequota.yaml
We are hitting our resource quota of pods in the namespace due to the number of forms in live dev. Bump the limit slightly.
> Increase resource quota

- namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-live-production/02-limitrange.yaml
Increase CPU again after reverting last week. Service cache pod size needs to be bigger.
> Increase CPU for formbuilder-platform-live-production

- .github/workflows/pr-stale.yaml
- Marks PRs as stale after 90 days
- Closes PRs as stale 90 days + 7 days if no response.
- Runs in dry-run only mode so we can test
> ci: add pr stale bot

- namespaces/live.cloud-platform.service.justice.gov.uk/certificated-bailiffs-dev/resources/apex-rds-oracle.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/certificated-bailiffs-dev/resources/apex-s3-role.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/certificated-bailiffs-dev/resources/apex-s3.tf
Creating a S3 bucket where I can put rds dump files that can be picked up by oracle rds integration features and import data pump. Rds files are local so granting put permissions to that bucket only
> RST-7307: apex-rds-migration

- namespaces/live.cloud-platform.service.justice.gov.uk/emma-cloud-test/resources/ecr.tf
This pr is to deletion protection ready to test the deletion of my dev namespace on the slack alerts it is part of issue https://github.com/ministryofjustice/cloud-platform/issues/6929
> add ecr deletion protection as prep to delete my namespace

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-manage-your-civil-cases-production/05-prometheus-custom-rules.yaml
This pull request includes a small update to the Prometheus custom rules configuration for the `laa-manage-your-civil-cases-production` namespace. The change updates the `dashboard_url` annotation to point to a new Grafana dashboard.
> MCC-PROD / Updates grafana dashboard url 

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-manage-your-civil-cases-staging/05-prometheus-custom-rules.yaml
This pull request includes a small update to the Prometheus custom rules configuration for the `laa-manage-your-civil-cases-staging` namespace. The change updates the `dashboard_url` annotation to point to a new Grafana dashboard.
> MCC-STAGING / Updates grafana dashboard url

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-manage-your-civil-cases-uat/05-prometheus-custom-rules.yaml
This pull request includes a small update to the Prometheus custom rules configuration for the `laa-manage-your-civil-cases-uat` namespace. The change updates the `dashboard_url` annotation to point to a new Grafana dashboard.
> MCC-UAT / Updates grafana dashboard url

- .checksum
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-dev/00-namespace.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-dev/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-dev/02-limitrange.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-dev/03-resourcequota.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-dev/04-networkpolicy.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-dev/resources/ecr.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-dev/resources/irsa.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-dev/resources/main.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-dev/resources/secret.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-dev/resources/serviceaccount.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-dev/resources/variables.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-dev/resources/versions.tf
New namespace for all ccms applications being migrated from LZ to CP.
This PR is initially for ccms-pda. Further apps to be added in future PRs.
> Create namespace for laa-ccms-dev

- namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-firebreak-daap-api/resources/ecr.tf
This namespace is no longer needed and a subsequent PR will be raised to delete it.
> `deletion_protection = false` for ECR

- namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-commuter-webapp-familyman-prod/resources/ecr.tf
Preparing to remove an unneeded namespace, following the instructions [here](https://user-guide.cloud-platform.service.justice.gov.uk/documentation/deploying-an-app/cleaning-up.html#preparation)
> Set deletion_protection to false for data-platform-app-commuter-webapp-familyman-prod

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-information-exchange-production/00-namespace.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-information-exchange-production/resources/main.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-information-exchange-production/resources/variables.tf
Update team ownership to `crime-apps-team` from `laa-ops` so that we can migrate the service over from the LAA LZ.
> Update Team Metadata in Information Exchange Production Namespace

- namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-prod/resources/rds-pre-sentence-service.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-prod/resources/variables.tf
- Fix Terraform RDS version drift for namespace: `court-probation-prod`
```
module.court_case_service_rds: downgrade from 14.17 to 14.13
module.pre_sentence_service_rds: downgrade from 14.17 to 14.13
```
> Fix: rds version mismatch in court-probation-prod

- namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-dev/resources/variables.tf
- Fix Terraform RDS version drift for namespace: `court-probation-dev`
```
module.court_case_service_rds: downgrade from 14.17 to 14.13
```
> Fix: rds version mismatch in court-probation-dev

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-delius-alfresco-preprod/resources/rds.tf
- Fix Terraform RDS version drift for namespace: `hmpps-delius-alfresco-preprod`
```
module.rds_alfresco: downgrade from 14.17 to 14.13
```
> Fix: rds version mismatch in hmpps-delius-alfresco-preprod

- namespaces/live.cloud-platform.service.justice.gov.uk/sif-production/resources/rds.tf
- Fix Terraform RDS version drift for namespace: `sif-production`
```
module.rds: downgrade from 14.17 to 14.13
```
> Fix: rds version mismatch in sif-production

- namespaces/live.cloud-platform.service.justice.gov.uk/disclosure-checker-production/resources/rds.tf
- Fix Terraform RDS version drift for namespace: `disclosure-checker-production`
```
module.rds-instance: downgrade from 16.8 to 16.4
```
> Fix: rds version mismatch in disclosure-checker-production

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-interventions-preprod/resources/rds-postgres14.tf
- Fix Terraform RDS version drift for namespace: `hmpps-interventions-preprod`
```
module.hmpps_interventions_postgres14: downgrade from 14.17 to 14.13
```
> Fix: rds version mismatch in hmpps-interventions-preprod

- namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-saas-test/resources/metadata_api.tf
- Fix Terraform RDS version drift for namespace: `formbuilder-saas-test`
```
module.metadata-api-rds-instance: downgrade from 15.12 to 15.8
```
> Fix: rds version mismatch in formbuilder-saas-test

- .github/workflows/pr-stale.yaml
- Allows the bot to override the actions cache and close issues
> fix: require actions write permission for cache

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-electronic-monitoring-data-insights-dev/resources/template-ui.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-electronic-monitoring-data-insights-dev/resources/versions.tf
Deploying the hmpps-electronic-monitoring-data-insights-ui application to the dev environment currently fails due to `AUTH_CODE_CLIENT_ID not found in the secret ` Been told  the typescript hmpps-template is needed in the namespace, to generate the default secrets files.
> EPT-199: added hmpps template ts

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-dev/01-rbac.yaml
This work is to unblock one of our developers in the first instance, who needs access to dev namespace.
> CAS-1681 - Add new dev group to dev rbac. will test with one dev first

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-registers-prod/resources/rds.tf
- Fix Terraform RDS version drift for namespace: `hmpps-registers-prod`
```
module.prisons_rds: downgrade from 16.8 to 16.4
```
> Fix: rds version mismatch in hmpps-registers-prod

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-delius-alfresco-prod/resources/rds.tf
- Fix Terraform RDS version drift for namespace: `hmpps-delius-alfresco-prod`
```
module.rds_alfresco: downgrade from 14.17 to 14.13
```
> Fix: rds version mismatch in hmpps-delius-alfresco-prod

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-preprod/01-rbac.yaml
- Added `hmpps-community-accommodation-live` to preproduction namespace
- cleaned up duplicate SRE entry.
> CAS-1681: Removed dupe RBAC for SRE and added Live CAS group

- namespaces/live.cloud-platform.service.justice.gov.uk/licences-preprod/resources/rds.tf
- Fix Terraform RDS version drift for namespace: `licences-preprod`
```
module.dps_rds: downgrade from 15.12 to 15.8
```
> Fix: rds version mismatch in licences-preprod

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-accredited-programmes-dev/resources/rds-postgresql.tf
- Fix Terraform RDS version drift for namespace: `hmpps-accredited-programmes-dev`
```
module.rds: downgrade from 16.8 to 16.4
```
> Fix: rds version mismatch in hmpps-accredited-programmes-dev

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-landing-page-test/04-networkpolicy.yaml
Allow traffic from Prometheus in the monitoring namespace.
> Update laa-landing-page-test network policy to allow monitoring

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-staging/resources/rds-postgresql.tf
- Fix Terraform RDS version drift for namespace: `laa-dces-drc-integration-staging`
```
module.rds: downgrade from 16.8 to 16.4
```
> Fix: rds version mismatch in laa-dces-drc-integration-staging

- namespaces/live.cloud-platform.service.justice.gov.uk/send-legal-mail-to-prisons-prod/resources/rds.tf
- Fix Terraform RDS version drift for namespace: `send-legal-mail-to-prisons-prod`
```
module.slmtp_api_rds: downgrade from 15.12 to 15.8
```
> Fix: rds version mismatch in send-legal-mail-to-prisons-prod

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-prisoner-location-preprod/resources/s3.tf
hmpps-prisoner-location-preprod
- without the bucket's actual arn in the allowed resources list s3:ListBucket won't work
- s3:PutObject works because it's acting on arn/* i.e. the contents of the bucket
Required to check whether the new file has already been uploaded to make the workflow running the file upload idempotent
It's going to be called at 02:20 a.m. and again at 03:20 a.m. to deal with GMT/BST
Offloc file upload to the source bucket elsewhere runs at 23:20 and 00:20 UTC for the same reason
> allow resource itself for ListObject

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-prisoner-location-prod/resources/s3.tf
hmpps-prisoner-location-prod
- without the bucket's actual arn in the allowed resources list s3:ListBucket won't work
- s3:PutObject works because it's acting on arn/* i.e. the contents of the bucket
Required to check whether the new file has already been uploaded to make the workflow running the file upload idempotent
It's going to be called at 02:20 a.m. and again at 03:20 a.m. to deal with GMT/BST
Offloc file upload to the source bucket elsewhere runs at 23:20 and 00:20 UTC for the same reason
> update allow resource for ListObject

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-person-record-preprod/resources/rds.tf
- Fix Terraform RDS version drift for namespace: `hmpps-person-record-preprod`
```
module.hmpps_person_record_rds: downgrade from 17.4 to 17.1
```
> Fix: rds version mismatch in hmpps-person-record-preprod

- namespaces/live.cloud-platform.service.justice.gov.uk/calculate-release-dates-api-preprod/resources/rds.tf
- Fix Terraform RDS version drift for namespace: `calculate-release-dates-api-preprod`
```
module.calculate_release_dates_api_rds: downgrade from 16.8 to 16.4
```
> Fix: rds version mismatch in calculate-release-dates-api-preprod

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-uat/resources/rds-postgresql.tf
- Fix Terraform RDS version drift for namespace: `laa-dces-drc-integration-uat`
```
module.rds: downgrade from 16.8 to 16.4
```
> Fix: rds version mismatch in laa-dces-drc-integration-uat

- namespaces/live.cloud-platform.service.justice.gov.uk/dex-mi-staging/resources/rds.tf
- Fix Terraform RDS version drift for namespace: `dex-mi-staging`
```
module.dex_mi_staging_rds: downgrade from 16.8 to 16.4
```
> Fix: rds version mismatch in dex-mi-staging

- namespaces/live.cloud-platform.service.justice.gov.uk/calculate-journey-variable-payments-prod/resources/rds.tf
- Fix Terraform RDS version drift for namespace: `calculate-journey-variable-payments-prod`
```
module.rds-instance: downgrade from 16.8 to 16.4
```
> Fix: rds version mismatch in calculate-journey-variable-payments-prod

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-test/resources/rds-postgresql.tf
- Fix Terraform RDS version drift for namespace: `laa-dces-drc-integration-test`
```
module.rds: downgrade from 16.8 to 16.4
```
> Fix: rds version mismatch in laa-dces-drc-integration-test

- namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-services-live-dev/03-resourcequota.yaml
We need a few more pods in live-dev to allow services to scale to the required no of replicas
> Update resource quota for live-dev

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-electronic-monitoring-data-insights-dev/resources/template-ui.tf
Deploying the hmpps-electronic-monitoring-data-insights-ui application to the dev environment currently fails. Been told the typescript hmpps-template is needed in the namespace, to generate the default secrets files.
> EPT-199: brought back  hmpps template

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-benefit-checker-uat/resources/route53.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-benefit-checker-uat/resources/variables.tf
This PR adds a Route53 hosted zone for the UAT environment of Benefit Checker, to enable a certificate to be separately created with a Common Name of less than 64 characters (which is the limit).
Note: the `laa-benefit-checker.service.justice.gov.uk` hostname defined in this PR does not yet exist, so I'm not sure if creating the subdomain defined in this PR will be possible until it does. If this is the case, I will get the PR for the live environment merged in first to create this hostname (https://github.com/ministryofjustice/cloud-platform-environments/pull/33445).
> Add Route53 hosted zone for Benefit Checker UAT

- namespaces/live.cloud-platform.service.justice.gov.uk/civil-appeal-case-tracker-preprod/resources/rds-postgresql.tf
- Fix Terraform RDS version drift for namespace: `civil-appeal-case-tracker-preprod`
```
module.rds: downgrade from 14.17 to 14.13
```
> Fix: rds version mismatch in civil-appeal-case-tracker-preprod

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-check-client-qualifies-production/resources/rds.tf
If applied, this resets the namespace now that DB instance has been upgraded.
> EL-1638: Upgrade Postgres RDS DB on CCQ PROD - Part 4

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-ui-dev/resources/ecr.tf
Keep latest production images indefinitely, others for 60 days
> ACD-302: VCD ECR lifecycle policy

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-production/resources/rds.tf
Reverting this commit as access is no longer needed - https://github.com/ministryofjustice/cloud-platform-environments/commit/1852cb060af6cea0e9bf18b28fc1ed64aea14a34
> [CCR production] Remove rds access, given last week

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-preprod/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-preprod/resources/hmpps-approved-premises-api.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-preprod/resources/hmpps-approved-premises-ui.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-preprod/resources/hmpps-community-accommodation-tier-2-bail-ui.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-preprod/resources/hmpps-community-accommodation-tier-2-ui.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-preprod/resources/hmpps-temporary-accommodation-ui.tf
This environment is now restricted to GH users within `hmpps-community-accommodation-live` team only.
- Deployments.
- K8s access.
> CAS-1681: remove teams no longer allowed to deploy/access to Preprod

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-person-record-prod/resources/rds.tf
- Fix Terraform RDS version drift for namespace: `hmpps-person-record-prod`
```
module.hmpps_person_record_rds: downgrade from 17.4 to 17.1
```
> Fix: rds version mismatch in hmpps-person-record-prod

- namespaces/live.cloud-platform.service.justice.gov.uk/hmcts-mock-api-dev/resources/rds_new.tf
This is a non-prod DB, so 500 seems an appropriate max storage. However, as the instance type was already "small" I don't want to downgrade to micro.
> ACD-499: Upgrade RDS instance type

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-assure-hmrc-data-staging/resources/serviceaccount.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-assure-hmrc-data-staging/resources/variables.tf
Add service account permissions [Assure Staging]
Required for ClamAV PVC and configmaps as well as defaults
> AP-6070: Add service account permissions [Assure Staging]

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-assure-hmrc-data-production/resources/serviceaccount.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-assure-hmrc-data-production/resources/variables.tf
Add service account permissions [Assure Production]
Required for ClamAV PVC and configmaps as well as defaults
> AP-6070: Add explicit serviceaccount permissions [Assure Production]

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-validation-dev/resources/ecr.tf
This PR disables ECR deletion protection for `laa-crime-validation-dev` to enable the namespace and all contained resources to be deleted, as the decision has been made that the service is no longer required.
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-4123)
> Disable ECR deletion protection for laa-crime-validation-dev

- namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-prod/resources/route53-finucane.tf
Txt DNS must be split into 255 chunks. We have two approaches- either put in a special break `\"\"` or I am trying the approach of putting the value over several strings and letting terraform concatenate together.
> Avoid DKIM 255 char limit by setting over several strings

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-test/resources/hmpps-approved-premises-api.tf
The test environment deployment pipeline is completely decoupled from other environments. As such, no deployment to test can be promoted or pushed to any other environments, and it is safe to deploy experimental builds from branches.
> CAS API - Remove deploy branch restriction for test

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-esupervision-dev/resources/variables.tf
Various build components expect the environment name to be 'dev' instead of 'development' so update the name to match.
> Change environment name in dev namespace for esupervision

- namespaces/live.cloud-platform.service.justice.gov.uk/peoplefinder-production/resources/rds.tf
- Fix Terraform RDS version drift for namespace: `peoplefinder-production`
```
module.peoplefinder_rds_replica: downgrade from 16.8 to 16.4
```
> Fix: rds version mismatch in peoplefinder-production

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-test/resources/hmpps-approved-premises-api.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-test/resources/hmpps-approved-premises-ui.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-test/resources/hmpps-community-accommodation-tier-2-ui.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-test/resources/hmpps-temporary-accommodation-ui.tf
A single wildcard does not match branch names that contain slashes [1]. This change ensures that branch names with one slash are a match for the pattern.
[1] https://docs.github.com/en/actions/managing-workflow-runs-and-deployments/managing-deployments/managing-environments-for-deployment#deployment-branches-and-tags
> CAS - Allow branch names that include a slash for deployments to test environment

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-criminal-legal-aid-staging/resources/rds.tf
Turn off `prepare_for_major_upgrade` now that Postgres is upgraded.
> CRIMAPP-1711 Finish Postgres upgrade on Crime Apply staging

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-application-store-production/resources/rds-postgresql.tf
- Fix Terraform RDS version drift for namespace: `laa-crime-application-store-production`
```
module.read_replica: downgrade from 16.8 to 16.4
```
> Fix: rds version mismatch in laa-crime-application-store-production

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-review-criminal-legal-aid-staging/resources/rds.tf
Upgrade RDS Postgres version to 17 for `laa-review-criminal-legal-aid-staging`.
> CRIMAPP-1711 Upgrade Postgres to v17 on Crime Review staging

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-criminal-applications-datastore-staging/resources/rds.tf
Upgrade RDS Postgres version to 17 for `laa-criminal-applications-datastore-staging`.
> CRIMAPP-1711 Upgrade Postgres to v17 on Crime Datastore staging

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-criminal-applications-datastore-staging/resources/rds.tf
Turn off `prepare_for_major_upgrade` now that Postgres is upgraded.
> CRIMAPP-1711 Finish Postgres upgrade on Crime Datastore staging

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-review-criminal-legal-aid-production/resources/rds.tf
Upgrade RDS Postgres version to 16 for `laa-review-criminal-legal-aid-production`.
Upgrade to version 17 to follow.
> CRIMAPP-1711 Upgrade Postgres to v16 on Crime Review production

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-incident-reporting-preprod/resources/github.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-incident-reporting-preprod/resources/variables.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-incident-reporting-preprod/resources/versions.tf
> hmpps-incident-reporting-preprod: Set up for GH Actions

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-esupervision-dev/resources/irsa.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-esupervision-dev/resources/s3.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-esupervision-dev/resources/variables.tf
Define an S3 data bucket with the default access policy for the HMPPS esupervision application. Add an IRSA role to the namespace so the API pod can access the bucket.
> Define S3 bucket and IRSA configuration for esupervision app

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-criminal-legal-aid-production/resources/rds.tf
Turn off `prepare_for_major_upgrade` now that Postgres is upgraded to v16. Upgrade to v17 to follow.
> CRIMAPP-1711 Finish Postgres 16 upgrade on Crime Apply production

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-criminal-applications-datastore-production/resources/rds.tf
Turn off `prepare_for_major_upgrade` now that Postgres is upgraded to v16. Upgrade to v17 to follow.
> CRIMAPP-1711 Finish Postgres 16 upgrade on Crime Datastore production

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-criminal-legal-aid-production/resources/rds.tf
Upgrade RDS Postgres version to 17 for `laa-apply-for-criminal-legal-aid-production`.
> CRIMAPP-1711 Upgrade Postgres to v17 on Crime Apply production

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-criminal-applications-datastore-production/resources/rds.tf
Upgrade RDS Postgres version to 17 for `laa-criminal-applications-datastore-production`.
> CRIMAPP-1711 Upgrade Postgres to v17 on Crime Datastore production

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-review-criminal-legal-aid-production/resources/rds.tf
Turn off `prepare_for_major_upgrade` now that Postgres is upgraded to v17.
> CRIMAPP-1711 Finish Postgres 17 upgrade on Crime Review production

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-esupervision-dev/resources/rds.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-esupervision-dev/resources/variables.tf
Create a postgres 17 instance for the hmpps-esupervision dev namespace. Save the instance state in a secret so it can be accessed by the application.
> Define postgres 17 database for esupervision dev namespace

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-information-exchange-production/resources/secrets.tf
- Created a new secret in AWS Secrets Manager to store the Slack webhook for production alerting.
- This webhook will be used to send Prometheus alert notifications to the appropriate Slack channel.
> Add new Slack webhook secret for infox-prod alerts

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-hardship-test/resources/secret.tf
This PR adds a new secret for the IP allowlist for the test Hardship Service.
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-4143)
> Add IP allowlist secret for test Hardship Service

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-evidence-test/resources/secret.tf
This PR adds a new secret for the IP allowlist for the test Evidence Service.
> Add IP allowlist secret for test Evidence Service

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-evidence-uat/resources/secret.tf
This PR adds a new secret for the IP allowlist for the UAT Evidence Service.
> Add IP allowlist secret for UAT Evidence Service

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-application-tracking-service-uat/resources/secret.tf
This PR adds a new secret for the IP allowlist for the UAT Application Tracking Service.
> Add IP allowlist secret for UAT Application Tracking Service

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-non-associations-dev/resources/application-insights.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-non-associations-dev/resources/github.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-non-associations-dev/resources/variables.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-non-associations-dev/resources/versions.tf
> hmpps-non-associations-dev: Set up for GH Actions

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-non-associations-prod/resources/github.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-non-associations-prod/resources/variables.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-non-associations-prod/resources/versions.tf
> `hmpps-non-associations-prod`: Set up for GH Actions

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-equinity-historical-data-prod/resources/rds-mssql.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/make-recall-decision-db-analysis/resources/rds-mssql.tf
Adding mandatory tags as a part of mandatory tagging work to untagged RDS options groups - [#6972](https://github.com/ministryofjustice/cloud-platform/issues/6972)
Tags copied from existing RDS instances that use the options groups
> Tag untagged resources

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-incentives-preprod/resources/github.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-incentives-preprod/resources/variables.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-incentives-preprod/resources/versions.tf
> `hmpps-incentives-preprod`: Set up for GH Actions

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-review-criminal-legal-aid-production/04-networkpolicy.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-review-criminal-legal-aid-production/07-prometheus-sidekiq.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-review-criminal-legal-aid-production/resources/elasticache.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-review-criminal-legal-aid-production/resources/irsa.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-review-criminal-legal-aid-production/resources/s3.tf
This PR makes the following changes in the `laa-review-criminal-legal-aid-production` namespace:
- Adds an ElastiCache (Redis) cluster
- Adds an S3 bucket
- Adds an IRSA module to allow access to S3
- Updates the network policy for Prometheus to target pods by a new label - `laa-review-criminal-legal-aid-production-metrics-target`
- Adds Prometheus alerts to monitor Sidekiq
> CRIMAPP-1679 Reporting infrastructure for crime review production

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-support-additional-needs-dev/00-namespace.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-support-additional-needs-dev/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-support-additional-needs-dev/resources/variables.tf
PR to change the old group name (`hmpps-farsight-reduce-re-offend`) to the new group name (`hmpps-support-additional-needs-devs`) in respect of the team name and RBAC settings for the Support For Additional Needs dev namespace.
> RR-1598 - Set new group name as used in namespace RBAC

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-litigator-fees-dev/resources/rds.tf
- Fix Terraform RDS version drift for namespace: `laa-crown-court-litigator-fees-dev`
```
module.rds-instance-migrated: downgrade from 19.0.0.0.ru-2025-04.rur-2025-04.r1 to 19.0.0.0.ru-2025-01.rur-2025-01.r1
```
> Fix: rds version mismatch in laa-crown-court-litigator-fees-dev

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-criminal-applications-datastore-staging/04-networkpolicy.yaml
This change updates egress config to the network policy on laa-criminal-applications-datastore-staging.
> [CRIMAPP-1823] Update datastore staging egress network policy

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-information-exchange-preproduction/resources/secrets.tf
Renamed secret from `laa-infox-db_password` to `laa-infox-db-credentials` in `secrets.tf` and updated the description. This will now be used to store all the DB credentials and not just the password.
> Rename DB secret in Infox UAT environment

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-sds-dev/resources/irsa.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-sds-dev/resources/s3.tf
This PR enables S3 object versioning on both buckets in the laa-sds-dev namespace (laa-sds-internal-dev and laa-sds-equiniti-dev). 
It also adds the necessary IAM permissions (s3:ListBucketVersions and s3:DeleteObjectVersion) to support versioned operations.
This work is part of testing and documenting S3 rollback mechanisms for the SDS API.
> Test: Turn on s3 object versioning in the laa-sds-dev namespace to investigate rollback mechanisms

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-benefit-checker-prod/resources/main.tf
This PR adds the missing `GithubTeam` tag for Benefit Checker Prod to the existing Terraform providers set-up for this namespace.
> Add missing GithubTeam tag for Benefit Checker Prod

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-interventions-dev/resources/hmpps-audit-queue.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-interventions-dev/resources/irsa.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-interventions-dev/resources/variables.tf
configure refer and monitor interventions to enable audit in dev so that we can trace call to search for CRN
> configuring audit for hmpps-interventions

- namespaces/live.cloud-platform.service.justice.gov.uk/abundant-namespace-dev/resources/aurora.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/abundant-namespace-dev/resources/opensearch.tf
we have a bunch of 5.1.0 s3 modules to bump as well as 5.2.0 when rolling out 5.3.0. this change will show additional IAM permissions across the board. PR demonstrates this bump is non-destructive
releases:
[5.3.0](https://github.com/ministryofjustice/cloud-platform-terraform-s3-bucket/releases/tag/5.3.0)
[5.2.0](https://github.com/ministryofjustice/cloud-platform-terraform-s3-bucket/releases/tag/5.2.0)
> chore: 🤖 poc s3 release bump and fix aurora drift

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-launchpad-dev/resources/irsa.tf
Updated the key for `sqs_queues` in `irsa.tf` to match the sqs queue name we are attempting to push to (as configured in [hmpps-prisoner-audit-queue.tf](https://github.com/ministryofjustice/cloud-platform-environments/blob/main/namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-launchpad-dev/resources/hmpps-prisoner-audit-queue.tf))
> LNP-1180: Adding prisoner auditing to launchpad ui

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-maat-data-api-prod/resources/secret.tf
This PR adds a new secret to store the Slack webhook for MAAT API prod, which will be used to update the relevant Slack channel with alerts from AlertManager.
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-4275)
> Add new secret to store Slack webhook for MAAT API prod

- namespaces/live.cloud-platform.service.justice.gov.uk/fraud-and-corruption-insights-dev/resources/dynamodb-dev.tf
Adding a second dynamodb resource to the fraud-and-corruption-insights-dev namespace
> Add second dynamodb resource to fci namespace

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-dev/04-networkpolicy.yaml
A second attempt at creating an egress rule based on domain name as the previous version failed with an error. This time the rule is copied form https://docs.tigera.io/calico-cloud/tutorials/applications/egress-controls#use-wildcards-in-domain-names and modified accordingly.
Notable differences;
* Port is explicitly given as 443 (https)
* The domain name is in single quotes instead of double quotes
> Update egress rules

- namespaces/live.cloud-platform.service.justice.gov.uk/user-roles.yaml
This will create a ClusterRole that will allow users to manage Calico network policies.
This will require a RoleBinding in namespaces that want to use it to work.
Tested clusterrole by manually applying the role and blinding it in tom-namespace-dev to a group that contains the dummy user. Tested to ensure the dummy user could only get calico networkpolicies from the namespace and accessing other namespaces calico NPs are forbidden.
> Create clusterrole to enable management of calico network policies

- policy/rolebinding.rego
this PR updates rolebinding conftest check to permit namespaced calico network policy resources
> chore: 🤖 allow calico-network-policy-access role in conftest

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-information-exchange-production/resources/secrets.tf
This PR adds a secret to store the Sentry DSN for InfoX Prod, so that it can be moved out of app configuration. Whilst Sentry DSN values are technically not secret values [according to Sentry](https://sentry.zendesk.com/hc/en-us/articles/26741783759899-My-DSN-key-is-publicly-visible-is-this-a-security-vulnerability), they do allow events to be sent to Sentry without authentication, so ideally should be kept private.
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-4170)
> Add Sentry DSN secret for InfoX Prod

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-maat-data-api-prod/06-grafana.yaml
This PR fixes the MAAT Data API Prod dashboard id to the intended id, as it currently conflicts with the existing MAAT Orchestration Service Prod dashboard id.
> Update MAAT Data API Prod dashboard id

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-esupervision-test/07-ingress.yaml
Add ingress to allow access to the UI application from the internet wtihin the HMPPS esupervision test namespace.
> Add ingress for UI in HMPPS esupervision test namespace

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-landing-page-dev/resources/rds.tf
Testers are working early/late in approach to go live - makes sense to leave this up for now. I have created a ticket to turn this back on post go live.
> Temporarily turn off RDS start/stop

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-data-claims-api-uat/resources/serviceaccount.tf
override default service-account permissions to add persistentvolumeclaims API actions.
> DSTEW-100: override default service-account permissions

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-uat/resources/irsa.tf
There will be strange behaviours as both uat and staging are pointing to the same queues. 
CCR uat is now set to communicate with CCCD dev-lgfs.
> Update irsa for CCR uat

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-single-accommodation-service-prototype/00-namespace.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-single-accommodation-service-prototype/01-rbac.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-single-accommodation-service-prototype/02-limitrange.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-single-accommodation-service-prototype/03-resourcequota.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-single-accommodation-service-prototype/04-networkpolicy.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-single-accommodation-service-prototype/resources/basic-auth.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-single-accommodation-service-prototype/resources/ecr.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-single-accommodation-service-prototype/resources/main.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-single-accommodation-service-prototype/resources/serviceaccount.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-single-accommodation-service-prototype/resources/variables.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-single-accommodation-service-prototype/resources/versions.tf
We need a new k8s namespace for our new prototype repo: 
https://github.com/ministryofjustice/hmpps-single-accommodation-service-prototype
To generate the code changes in this PR, these steps were followed:
https://user-guide.cloud-platform.service.justice.gov.uk/documentation/getting-started/prototype-kit.html#publish-prototypes-on-the-web
> Added hmpps-single-accommodation-service-prototype

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-criminal-applications-datastore-staging/resources/irsa.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-criminal-applications-datastore-staging/resources/sns-application-events.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-criminal-applications-datastore-staging/resources/sqs-application-events.tf
This change adds a new SQS queue to `laa-criminal-applications-datastore-staging`. This queue is linked to the existing dead-letter queue and subscribed to the SNS topic.
> CRIMAPP-1821 Add SQS queue and subscription to Crime Datastore staging

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-esupervision-preprod/07-ingress.yaml
Create ingress which allows access from the internet to the HMPPS esupervision preprod UI.
> Define ingress for HMPPS esupervision preprod environment

- namespaces/live.cloud-platform.service.justice.gov.uk/fraud-and-corruption-insights-prod/resources/irsa.tf
Got an `Error: serviceaccounts "fraud-and-corruption-insights-prod-sa" already exists` error when adding the IRSA from [this PR](https://github.com/ministryofjustice/cloud-platform-environments/pull/35215).
This update attempts to build this properly in the correct service account.
> Update service_account_name in irsa

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-review-criminal-legal-aid-staging/resources/irsa.tf
This change adds the SQS policy ARN for the SQS queue in the `laa-criminal-applications-datastore-staging` namespace, created in that namespace and stored in this one as a secret.
> CRIMAPP-1821 Add SQS role policy from Datastore to Review staging

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-sds-test/resources/irsa.tf
- Fixes a build error caused by a globally named IAM policy (`s3_versioning_policy`) already existing.
- Updates the policy name to include `${var.environment}` to avoid name collisions across environments.
- No functional change to permissions — this is a fix for deployment compatibility.
> Fix naming of IAM policy (laa-sds-test env)

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-sds-stg/resources/irsa.tf
- Fixes a build error caused by a globally named IAM policy (`s3_versioning_policy`) already existing.
- Updates the policy name to include `${var.environment}` to avoid name collisions across environments.
- No functional change to permissions — this is a fix for deployment compatibility.
> Fix naming of IAM policy (laa-sds-stg env)

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-esupervision-test/07-ingress.yaml
Reconfigure the modsecurity WAF to only record suspect requests within the HMPPS test environment. Only suspect requests should be added to the audit log.
> Reconfigure WAF to only record suspect requests in HMPPS test

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-fee-scheme-api-dev/04-networkpolicy.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-fee-scheme-api-dev/05-servicemonitor.yaml
- Added network policy to allow Prometheus scraping
- Added service monitor for actuator
> LFSP-60: Add networkpolicy and servicemonitor (laa-fee-scheme-api-dev)

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-fee-scheme-api-uat/04-networkpolicy.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-fee-scheme-api-uat/05-servicemonitor.yaml
- Added network policy to allow Prometheus scraping
- Added service monitor for actuator
> LFSP-60: Add networkpolicy and servicemonitor (laa-fee-scheme-api-uat)

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-fee-scheme-api-staging/04-networkpolicy.yaml
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-fee-scheme-api-staging/05-servicemonitor.yaml
- Added network policy to allow Prometheus scraping
- Added service monitor for actuator
> LFSP-60: Add networkpolicy and servicemonitor (laa-fee-scheme-api-staging)

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-maat-scheduled-tasks-dev/resources/s3.tf
As per title, allows AP ingestion dev to access the s3 bucket in laa-maat-scheduled-tasks-dev.
> Adds bucket policy for AP ingestion account access.

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-and-deliver-accredited-programmes-prod/01-rbac.yaml
Updated the Role-Based Access Control (RBAC) group for the `manage-and-deliver-accredited-programmes` production namespace
> APG-1235 Update RBAC group for hmpps-manage-and-deliver-accredited-programmes-prod 

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-prod/resources/route53.tf
The CNAME's need to be added in the BC, not in Court Data Adaptor.
> Revert "Adding CNAMEs for Benefit Checker"

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-criminal-applications-datastore-staging/resources/sns-application-events.tf
This change removes the SNS HTTPS subscription from `laa-criminal-applications-datastore-staging`, leaving only the SQS subscription.
> CRIMAPP-1821 Remove SNS HTTPS subscription from Crime Datastore staging

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-person-record-dev/resources/person-match-score-circleci-serviceaccount.tf
Deleted when migrating a project to github actions, but we still have another one which uses circleci
> CPR-769 reinstate dev circleCI serviceaccount

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-maat-scheduled-tasks-dev/resources/cognito.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-maat-scheduled-tasks-dev/resources/variables.tf
The original intention was for these credentials to be for manual testing and use in the functional test suite so renaming to make that clearer.
> LASB 4309 Renamed MAAT Credentials for MAAT Scheduled Tasks Dev

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-maat-scheduled-tasks-test/resources/cognito.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-maat-scheduled-tasks-test/resources/variables.tf
The original intention was for these credentials to be for manual testing and use in the functional test suite so renaming to make that clearer.
> LASB 4309 Renamed MAAT Credentials for MAAT Scheduled Tasks Test

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-maat-scheduled-tasks-prod/resources/cognito.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/laa-maat-scheduled-tasks-prod/resources/variables.tf
The intention was for these credentials to be used for manual testing which will not be done in prod so best to remove unwanted credentials.
> LASB 4309 Remove MAAT Credentials from MAAT Scheduled Tasks Prod

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-data-claims-api-uat/resources/serviceaccount.tf
Put the serviceaccount_name setting back to what it was before the last PR because the pipeline depends on the name.
> Put the serviceaccount_name setting back to what it was 

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-esupervision-dev/resources/cross-iam-role-sa.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-esupervision-dev/resources/irsa.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-esupervision-dev/resources/variables.tf
A role has been defined within an external AWS account (within the modernisation platform) with permissions required for the AWS Rekognition service used within the esupervision application.
Allow the service account permission to assume this role.
> Allow IRSA service account to assume role in external account

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-a-video-link-dev/resources/versions.tf
Update GH actions integration from v5.39.0 to v6.6.0.
> BAVL-1058: Update GH actions integration version

- namespaces/live.cloud-platform.service.justice.gov.uk/cfe-civil-production/resources/main.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/cfe-civil-production/resources/secret.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/cfe-civil-production/resources/variables.tf
Add default tags to allow secret to be viewed by laa-apply-for-legalaid team in console
> ap-6128: add external secret to cfe-civil-production namespace

- namespaces/live.cloud-platform.service.justice.gov.uk/cfe-civil-staging/resources/rds.tf
Change version to v17.6. 
Tidy up config. 
Enable auto start stop. 
Allow minor version upgrades
> AP-6166: Update cfe-civil staging database config

- namespaces/live.cloud-platform.service.justice.gov.uk/cfe-civil-staging/resources/main.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/cfe-civil-staging/resources/secret.tf
Add default tags to allow secret to be viewed by laa-apply-for-legalaid team in console
> ap-6128: add external secret to cfe-civil-staging namespace

- namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-datahub-catalogue-dev/resources/opensearch.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-datahub-catalogue-dev/resources/variables.tf
- Add's variables for key opensearch values
- Upgrades the Opensearch Engine version from 2.9 to 2.19
> Opensearch 2.19 upgrade dc dev

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-delius-alfresco-preprod/resources/athena.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-delius-alfresco-preprod/resources/irsa.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-delius-alfresco-preprod/resources/s3-inventory.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-delius-alfresco-preprod/resources/variables.tf
Config required to generate daily S3 Inventory reports and be able to query them through Athena
> Add S3 Inventory to Alfresco Preprod

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-civil-case-api-uat/04-networkpolicy.yaml
- Adds the `laa-manage-your-civil-cases-production` to CCA's UAT network policy allowed namespaces.
> Add laa-manage-your-civil-cases-production to CCA UAT's network policy

- namespaces/live.cloud-platform.service.justice.gov.uk/nettest/resources/rds-postgresql.tf
Adding an RDS instance to the `nettest` namespace so that I can use it to test network connectivity between MP and CP. This should ensure I have a fixed IP that I can use to test.
> Add rds instance to nettest

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-incident-reporting-dev/resources/rds.tf
This pull request introduces the `hot_standby_feedback` parameter to the RDS configuration in the HMPPS Incident Reporting development environment. This change ensures improved compatibility and responsiveness during high availability failovers in the database setup.
No issues are linked to this pull request.
> IR-1201 Add `hot_standby_feedback` parameter to RDS configuration

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-incident-reporting-prod/resources/rds.tf
This pull request adds the `hot_standby_feedback` parameter to the RDS configuration in the HMPPS Incident Reporting (IR) production environment. This configuration change is aimed at improving compatibility and syncing mechanisms within the database system. 
- **Purpose**: Enhance RDS configuration based on environment needs.
- **Environment**: Production (HMPPS Incident Reporting).
> IR-1201 Add `hot_standby_feedback` parameter to RDS config in HMPPS IR prod

- namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-preprod/resources/rds.tf
After an upgrade to the existing visit scheduler DB, something went wrong and it is currently stuck in an unusable state. We have to leave the DB while aws investigate. For now, to unblock the team, we will create a new rds instance and point the APIs to that, also point the preprod restore job to it as well, to populate with prod data.
> Create new RDS instance for visit scheduler DB on preprod

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-sds-dev/resources/dynamodb.tf
We sometimes encounter `ProvisionedThroughputExceededException` exceptions when carrying out operations that include updates to our dynamodb audit table (e.g. file saves, updates, reads). 
This table does have autoscaling enabled but within default limits of 1 to 10 units. 
This change increases the maximum read and write capacities to 40 units in our dev environment, with goal of seeing if this prevents the `ProvisionedThroughputExceededException` exceptions.
Note information about dynamodb config can be found here: https://github.com/ministryofjustice/cloud-platform-terraform-dynamodb-cluster
> SDS-128 - Increase dynamodb autoscaler limits in LAA-SDS-DEV

- namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-staging/resources/rds.tf
Reset allow_major_version_upgrade and prepare_for_major_upgrade flags to false after upgrading to 16.8 on visit-someone-in-prison-backend-svc-staging namespace.
> Reset flags post upgrade to 16.8 - visit-someone-in-prison-backend-svc-staging namespace

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-fee-scheme-api-staging/04-networkpolicy.yaml
Added network policy to allow access from data claims event service.
> LFSP-157: Add network policy for laa-fee-scheme-api-staging

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-dpr-tools-dev/resources/hmpps-dpr-tools-authoring-api.tf
The "environment" was being set to "developments" as was taking its value from the input variable default value.
Renamed to "dev" since all our project helm confiugation values use "dev".
> DPR2-2138 update environment to "dev" to match project helm values

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-custody-mailbox-register-dev/resources/rds.tf
Avoid overlap with the `enable_rds_auto_start_stop` window.
> Configure MBR dev RDS maintenance window

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-complexity-of-need-preprod/resources/rds.tf
Avoid overlap with the `enable_rds_auto_start_stop` window.
> Configure CNL preprod RDS maintenance window

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-dpr-tools-dev/05-certificates.yaml
Added the ingress host of the authoring API service to the DNS names of the certificate.
> DPR2-2138 added ingress host to dns names

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-intelligence-prod/resources/rds-aurora.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-intelligence-prod/resources/rds-legacy.tf
First step of upgrading existing IMS prod postgres databases to match current deployed engine versions.
> IMS - Step 1 prod DB upgrade tp Postgres 17

- namespaces/live.cloud-platform.service.justice.gov.uk/reuselibrary-dev/resources/main.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/reuselibrary-dev/resources/route53.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/reuselibrary-dev/resources/variables.tf
output zone details via Kubernetes Secret
This PR adds Terraform to create a private/public Route 53 hosted zone for our service domain and a Kubernetes Secret that surfaces the zone ID and nameservers, following the Cloud Platform user guide
> add Route53 hosted zone for dev.reuselibrary.service.justice.gov.uk

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-data-claims-reporting-service-uat/resources/rds-postgresql.tf
This is to allow logical replication from the claims-data database.
> DSTEW-463: Enable pglogical extension on this database 

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-data-claims-reporting-service-uat/resources/security-group.tf
This is so that the name is fixed rather than appended by a random number.
> DSTEW-463: Use name (rather than prefix) in security-group.tf 

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-a-video-link-dev/resources/hmpps-book-a-video-link-github.tf
PR to move the dev book a video link API deployment to use github actions (replacing Circle CI)
> BAVL-1057 move the BVLS API dev deployment over to github actions.

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-emergency-containment-platform/resources/route53.tf
In order to support blue/green deployments to ECP this PR introduces two new records for direct access to blue and green databases.
> Add new route53 records for ECP

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-a-video-link-preprod/resources/hmpps-book-a-video-link-github.tf
PR to move the preprod book a video link API deployment to use github actions (replacing Circle CI)
> BAVL-1057 move the BVLS API preprod deployment over to github actions.

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-audit-preprod/resources/audit-namespaces-secrets.tf
- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-audit-prod/resources/audit-namespaces-secrets.tf
Setting up the preprod namespaces ahead of the audit code being rolled out.
Allows us to control deployment via the feature flag while keeping the helm config consistent across all environments:
```
namespace_secrets:
sqs-hmpps-audit-secret:
AUDIT_SQS_QUEUE_URL: "sqs_queue_url"
AUDIT_SQS_QUEUE_NAME: "sqs_queue_name"
```
Related:
* [preprod](https://github.com/ministryofjustice/cloud-platform-environments/pull/36748)
* [prod](https://github.com/ministryofjustice/cloud-platform-environments/pull/36749)
> ESWE-969: Add audit secrets to MJMA and Jobs Board (preprod)

- namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-prod/resources/hmpps-domain-event-subscription.tf
`prison-offender-events.prisoner.received` is missing on `hmpps-integration-api-prod`
> [ESWE-1468] "Prisoner Received" domain event is missing on `hmpps-integration-api-prod`

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-information-exchange-production/resources/route53.tf
Created a new Route53 CNAME record pointing `infox.apps.live.cloud-platform.service.justice.gov.uk` to `infox.service.justice.gov.uk` to support legacy HMCTS WebLogic clients that cannot validate our custom certificate CN due to SNI/SAN handling issues.
This provides an alternative hostname aligned with the Cloud Platform’s wildcard certificate, while retaining the existing `infox.service.justice.gov.uk` domain for all other consumers.
No application changes required — only DNS and ingress updates.
> Add alternate DNS alias for InfoX production

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-criminal-applications-datastore-staging/resources/rds.tf
Enables Cloudwatch logging for datastore staging rds instance for security auditing purposes as outlined in [docs](https://github.com/ministryofjustice/cloud-platform-terraform-rds-instance/blob/main/README.md#enabling-logging-to-xsiam-cortex)
[Ticket](https://dsdmoj.atlassian.net/browse/CRIMAPP-1958)
> [CRIMAPP-1958] Enable RDS Logging to XSIAM Cortex for datastore staging

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-review-criminal-legal-aid-production/resources/rds.tf
Enables Cloudwatch logging for crime review rds instance for security auditing purposes as outlined in [docs](https://github.com/ministryofjustice/cloud-platform-terraform-rds-instance/blob/main/README.md#enabling-logging-to-xsiam-cortex)
[Ticket](https://dsdmoj.atlassian.net/browse/CRIMAPP-1958)
> [CRIMAPP-1958] Enable RDS Logging to XSIAM Cortex on Crime Review

- namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-criminal-legal-aid-production/resources/rds.tf
Enables Cloudwatch logging for crime apply rds instance for security auditing purposes as outlined in [docs](https://github.com/ministryofjustice/cloud-platform-terraform-rds-instance/blob/main/README.md#enabling-logging-to-xsiam-cortex)
[Ticket](https://dsdmoj.atlassian.net/browse/CRIMAPP-1958)
> [CRIMAPP-1958] Enable RDS Logging to XSIAM Cortex on Crime Apply
