namespaces/live.cloud-platform.service.justice.gov.uk/use-of-force-preprod/resources/scheduled-downtime.tf
See https://dsdmoj.atlassian.net/browse/MAP-2034
=> Add scheduled downtime to preprod env for UoF

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-welcome-to-prison-preprod/resources/scheduled-downtime.tf
https://dsdmoj.atlassian.net/browse/MAP-2035
=> Add scheduled downtime to preprod env for WPIP

namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-dev/resources/iam.tf
=> laa-drc-intg-putObjTagging

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-jobs-board-integration-dev/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-jobs-board-integration-dev/resources/ssm.tf
* output IRSA policy of SQS queue to SSM for another namespace
=> [ESWE-1167] Output IRSA policy to SSM parameter

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-jobs-board-dev/resources/irsa.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-jobs-board-dev/resources/variables.tf
* setup IRSA for SQS queue access (backend to integraiton service)
=> [ESWE-1167] Configure IRSA for queue access

namespaces/live.cloud-platform.service.justice.gov.uk/prison-visits-booking-staging/certificates.yaml
follow dev/production naming for PVB Public Staging (Preprod) environment on certificate
=> VB-4895, add PVB Staging public certificate

namespaces/live.cloud-platform.service.justice.gov.uk/prison-visits-booking-staging/certificates.yaml
Adjust Staff URL to match other environment naming strategy 
Repeat PR as other PR merge main attempt was done incorrectly
=> VB-4895, adjust staff certificate, PVB staging

namespaces/live.cloud-platform.service.justice.gov.uk/prison-visits-booking-staging/resources/route53.tf
Add route53 file to staging (preprod URL) environment for Prison Visits Booking service
=> VB-4895, add preprod route53 file - PVB

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-person-record-dev/resources/person-match-irsa.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-person-record-dev/resources/person-match-rds.tf
added  rds and irsa for person match
=> CPR-541-person-match-dev

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-nomis-prisoner-api-dev/02-limitrange.yaml
This reverts commit f978d843ca4580ea905994562b4092d8959bfd44.
=> Revert "SDIT-2419 Increase initial memory allocation"

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-person-record-dev/resources/person-match-rds.tf
=> CPR-541-person-match-allocation-dev

namespaces/live.cloud-platform.service.justice.gov.uk/track-a-query-qa/resources/rds.tf
The backup_window variable did not resolve the database snapshot retention period issue
=> Remove back window

.checksum, namespaces/live.cloud-platform.service.justice.gov.uk/mip-hmcts-dynatrace-to-xsiam-production/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/mip-hmcts-dynatrace-to-xsiam-production/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/mip-hmcts-dynatrace-to-xsiam-production/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/mip-hmcts-dynatrace-to-xsiam-production/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/mip-hmcts-dynatrace-to-xsiam-production/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/mip-hmcts-dynatrace-to-xsiam-production/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/mip-hmcts-dynatrace-to-xsiam-production/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/mip-hmcts-dynatrace-to-xsiam-production/resources/versions.tf
new file:   namespaces/live.cloud-platform.service.justice.gov.uk/mip-hmcts-dynatrace-to-xsiam-production/00-namespace.yaml
new file:   namespaces/live.cloud-platform.service.justice.gov.uk/mip-hmcts-dynatrace-to-xsiam-production/01-rbac.yaml
new file:   namespaces/live.cloud-platform.service.justice.gov.uk/mip-hmcts-dynatrace-to-xsiam-production/02-limitrange.yaml
new file:   namespaces/live.cloud-platform.service.justice.gov.uk/mip-hmcts-dynatrace-to-xsiam-production/03-resourcequota.yaml
new file:   namespaces/live.cloud-platform.service.justice.gov.uk/mip-hmcts-dynatrace-to-xsiam-production/04-networkpolicy.yaml
new file:   namespaces/live.cloud-platform.service.justice.gov.uk/mip-hmcts-dynatrace-to-xsiam-production/resources/main.tf
new file: …
=> Create namespace for mip-hmcts-dynatrace-to-xsiam-production

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-find-and-refer-an-intervention-preprod/06-certificate.yaml
Add truncated domain primary name to certificate, together with longer secondary
=> Add truncated domain primary name, together with longer secondary

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-preprod/resources/rds.tf
The read-replica on Pre-prod is not needed and by removing it we can save on the resource.
https://dsdmoj.atlassian.net/browse/MAP-2024
=> BaSM Preprod - remove read-replica

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-preprod/resources/irsa.tf
https://dsdmoj.atlassian.net/browse/MAP-2024
=> BaSM Pre-prod - remove `read_replica` from `irsa.tf`

namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-find-moj-data-dev/resources/cross-iam-role-sa.tf
Changing this role to be able to assume another role i've created in the account with the quicksight dashboard. This is because quicksight does not allow resource based permissions
=> Add AssumeRole permissions

.checksum, namespaces/live.cloud-platform.service.justice.gov.uk/emma-cloud-test/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/emma-cloud-test/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/emma-cloud-test/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/emma-cloud-test/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/emma-cloud-test/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/emma-cloud-test/resources/ecr.tf, namespaces/live.cloud-platform.service.justice.gov.uk/emma-cloud-test/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/emma-cloud-test/resources/serviceaccount.tf, namespaces/live.cloud-platform.service.justice.gov.uk/emma-cloud-test/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/emma-cloud-test/resources/versions.tf
create namespace as part of test deployment tutorial
=> creating test namespace

namespaces/live.cloud-platform.service.justice.gov.uk/prison-visits-booking-dev/06-certificates.yaml
Clean up
Remove unused certificate
Dev  environment
=> Cleanup - VB-4893, remove unusued dev certificate

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-learner-records-api-preprod/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-learner-records-api-preprod/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-learner-records-api-preprod/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-learner-records-api-preprod/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-learner-records-api-preprod/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-learner-records-api-preprod/06-certificate.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-learner-records-api-preprod/resources/appinsights.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-learner-records-api-preprod/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-learner-records-api-preprod/resources/serviceaccount-github.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-learner-records-api-preprod/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-learner-records-api-preprod/resources/versions.tf
Created preprod namespace for hmpps-learenr-records-api
=> created preprod namespace

namespaces/live.cloud-platform.service.justice.gov.uk/dave-learning/resources/ecr.tf, namespaces/live.cloud-platform.service.justice.gov.uk/dave-learning/resources/serviceaccount.tf
=> Add ecr and service account

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-portfolio-management-prod/resources/serviceaccount.tf
Also allow merge to main to deploy straight away
=> Move to using hmpps-sre team for portfolio management approvals

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-learner-records-api-uat/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-learner-records-api-uat/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-learner-records-api-uat/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-learner-records-api-uat/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-learner-records-api-uat/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-learner-records-api-uat/06-certificate.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-learner-records-api-uat/resources/appinsights.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-learner-records-api-uat/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-learner-records-api-uat/resources/serviceaccount-github.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-learner-records-api-uat/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-learner-records-api-uat/resources/versions.tf
created uat namespace for hmpps-learner-records-api
=> created uat namespace

namespaces/live.cloud-platform.service.justice.gov.uk/laa-submit-crime-forms-dev/resources/shared-s3-secret.tf
additional namespace for shared secret 
references https://github.com/ministryofjustice/cloud-platform-environments/pull/29042
=> [CRM457-1792] shared secret to second namespace

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-application-store-dev/resources/irsa.tf
adding service account `irsa` for `crime-app-store-dev for s3 shared shared from `crime-submit-forms-dev`
=> [CRM459-1792] app-store-dev irsa

namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-find-moj-data-prod/resources/cross-iam-role-sa.tf
adding role to assume other role with quicksight generate embedded url permissions
=> add quicksight irsa for fmd prod

namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-find-moj-data-preprod/resources/cross-iam-role-sa.tf
adding role to assume other role with quicksight generate embedded url permissions
=> add quicksight irsa for fmd preprod

namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-property-heat-networks-prod/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-property-heat-networks-prod/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-property-heat-networks-prod/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-property-heat-networks-prod/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-property-heat-networks-prod/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-property-heat-networks-prod/resources/ecr.tf, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-property-heat-networks-prod/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-property-heat-networks-prod/resources/serviceaccount.tf, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-property-heat-networks-prod/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-property-heat-networks-prod/resources/versions.tf
=> namespace creation  - prod-property-heat-networks

namespaces/live.cloud-platform.service.justice.gov.uk/ai-website-prod/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/ai-website-prod/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/ai-website-prod/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/ai-website-prod/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/ai-website-prod/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/ai-website-prod/resources/ecr.tf, namespaces/live.cloud-platform.service.justice.gov.uk/ai-website-prod/resources/elasticache.tf, namespaces/live.cloud-platform.service.justice.gov.uk/ai-website-prod/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/ai-website-prod/resources/service-account.tf, namespaces/live.cloud-platform.service.justice.gov.uk/ai-website-prod/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/ai-website-prod/resources/versions.tf
Initial resource set up for ai.justice.gov.uk
=> AI production environment

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-person-record-prod/resources/person-match-rds.tf
Recommended settings from https://user-guide.cloud-platform.service.justice.gov.uk/documentation/deploying-an-app/relational-databases/create.html#choosing-an-appropriate-database-configuration
=> CPR-544 make sure RDS is available in production all the time

namespaces/live.cloud-platform.service.justice.gov.uk/ai-website-dev/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/ai-website-dev/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/ai-website-dev/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/ai-website-dev/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/ai-website-dev/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/ai-website-dev/resources/elasticache.tf, namespaces/live.cloud-platform.service.justice.gov.uk/ai-website-dev/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/ai-website-dev/resources/service-account.tf, namespaces/live.cloud-platform.service.justice.gov.uk/ai-website-dev/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/ai-website-dev/resources/versions.tf
Initialise dev environment for ai.justice.gov.uk
=> AI development environment

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-audit-dev/resources/hmpps-electronic-monitoring-datastore.tf
for em-datastore-dev namespace logging
=> adding secret reference to hmpps-audit-dev 

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-hardship-dev/resources/secret.tf
Add sentry secret to hardship dev
=> Add sentry secret to hardship dev

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-hardship-test/resources/secret.tf
Add sentry secret to hardship test
=> Add sentry secret to hardship test

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-hardship-uat/resources/secret.tf
Add sentry secret to hardship UAT
=> Add sentry secret to hardship UAT

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-hardship-prod/resources/secret.tf
Add sentry secret to hardship prod
=> Add sentry secret to hardship prod

namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-dns-form-dev/resources/ecr.tf
- This PR sets ECR deletion protection to false. This is prep work prior to decommissioning.
- Add `deletion_protection = false` to ecr.tf
=> Update ecr deletion protection argument

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-application-store-dev/resources/irsa.tf
references https://github.com/ministryofjustice/cloud-platform-environments/pull/29134
=> [CRM457-1792] change shared secret name

namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-dev/resources/hmpps-prison-visits-allocation-processing-job-events.tf
Add new queue for SQS messages to trigger visit allocation event job on a prison basis.
=> Add new queue for SQS messages to trigger visit allocation event job

namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-metadata-poc/resources/ecr.tf
This PR updates policy for ECR to be deleted. Namespace to be deleted.
=> Add deletion_protection = false for operations-engineering-metadata-poc ECR

namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-example-dev/resources/ecr.tf
The PR disables ECR deletion protection for namespace that will be removed.
=> add deletion_protection to operations-engineering-example-dev ECR

namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-example-prod/resources/ecr.tf
The PR disables ECR deletion protection for namespace that will be removed.
=> add deletion_protection to operations-engineering-example-prod ECR

namespaces/live.cloud-platform.service.justice.gov.uk/trevors-sandbox/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/trevors-sandbox/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/trevors-sandbox/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/trevors-sandbox/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/trevors-sandbox/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/trevors-sandbox/resources/ecr.tf, namespaces/live.cloud-platform.service.justice.gov.uk/trevors-sandbox/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/trevors-sandbox/resources/serviceaccount.tf, namespaces/live.cloud-platform.service.justice.gov.uk/trevors-sandbox/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/trevors-sandbox/resources/versions.tf
Create a personal sandboxed namespace to try AWS resources such as SQS Queues
=> IMSV2-5932: Add trevorS sandbox namespace

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-sentence-plan-test/01-rbac.yaml
Correcting a namespace value to hmpps-sentence-plan-test.
=> added hmpps-sentence-plan-test namespace

namespaces/live.cloud-platform.service.justice.gov.uk/track-a-query-staging/resources/rds.tf
In reference to this resolved issue
https://github.com/ministryofjustice/cloud-platform/issues/6684
=> Set backup window

namespaces/live.cloud-platform.service.justice.gov.uk/trevors-sandbox/resources/ims-prisoner-locations-queue.tf
=> IMSV2-5932: add sqs resource in trevorS sandbox namespace

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-assess-risks-and-needs-integrations-test/resources/arns-oastub.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-assess-risks-and-needs-integrations-test/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-assess-risks-and-needs-integrations-test/resources/versions.tf
Add OAStub template terraform module for the OAStub app in the HMPPS ARNS Integrations Test environment
=> Add template terraform module for OAStub in HMPPS ARNS Integrations (Test)

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-find-and-refer-an-intervention-dev/08-github-actions-runner.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-sentence-plan-test/06-github-actions-runner.yaml
add new github actions runner to enable playwright tests to run
=> Find and refer github actions runner dev

namespaces/live.cloud-platform.service.justice.gov.uk/trevors-sandbox/resources/serviceaccount.tf
=> IMSV2-5932: add service account resource in trevorS sandbox namespace

namespaces/live.cloud-platform.service.justice.gov.uk/probation-template/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/probation-template/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/probation-template/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/probation-template/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/probation-template/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/probation-template/resources/basic-auth.tf, namespaces/live.cloud-platform.service.justice.gov.uk/probation-template/resources/ecr.tf, namespaces/live.cloud-platform.service.justice.gov.uk/probation-template/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/probation-template/resources/serviceaccount.tf, namespaces/live.cloud-platform.service.justice.gov.uk/probation-template/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/probation-template/resources/versions.tf
New namespace for new design prototype
=> Added probation-template prototype

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-personal-relationships-dev/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-personal-relationships-dev/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-personal-relationships-dev/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-personal-relationships-dev/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-personal-relationships-dev/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-personal-relationships-dev/06-certificate.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-personal-relationships-dev/resources/domain-events-topic.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-personal-relationships-dev/resources/elasticache.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-personal-relationships-dev/resources/irsa.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-personal-relationships-dev/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-personal-relationships-dev/resources/rds-postgresql.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-personal-relationships-dev/resources/serviceaccount-circleci.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-personal-relationships-dev/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-personal-relationships-dev/resources/versions.tf
PRC-446 : Create DEV environments for hmpps-personal-relationships-api
=> PRC-446 : Create DEV environments for hmpps-personal-relationships-api

namespaces/live.cloud-platform.service.justice.gov.uk/laa-submit-crime-forms-prod/resources/shared-s3-secret.tf
share s3 secret to app-store prod
=> [CRM457-1792] share s3 secret to app-store production

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-sentence-plan-test/06-github-actions-runner.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-sentence-plan-test/resources/serviceaccount.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-sentence-plan-test/resources/variables.tf
Additional configuration to add a service account for a GHA runner.
=> Add service account for GHA runner

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-jobs-board-integration-dev/resources/sqs.tf
- Add DLQ
- Fix typo at primary queue's secret
=> [ESWE-1213] Add DLQ on `dev`

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-jobs-board-integration-preprod/resources/sqs.tf
- Add DLQ
- Fix typo at primary queue's secret
=> [ESWE-1213] Add DLQ on `preprod`

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-jobs-board-integration-prod/resources/sqs.tf
- Add DLQ
- Fix typo at primary queue's secret
=> [ESWE-1213] Add DLQ on `prod`

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-litigator-fees-uat/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-litigator-fees-uat/resources/main.tf
Migration of CCLF is complete. laa-clair-taskforce is responsible now.
JIRA ticket - https://dsdmoj.atlassian.net/browse/CTSKF-922
=> Change CCLF UAT team to team responsible for project

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-litigator-fees-dev/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-litigator-fees-dev/resources/main.tf
Migration of CCLF is complete. laa-clair-taskforce is responsible now.
JIRA ticket - https://dsdmoj.atlassian.net/browse/CTSKF-922
=> Change CCLF team to team responsible for dev project

namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-report-service-dev/resources/secret.tf
To hold db connection details for DCES events db.
=> DCES-690: Create a new secret (in dev) 

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-personal-relationships-dev/resources/serviceaccount-circleci.tf
PRC-446 : hmpps personal relationships api - dev
=> PRC-446 : hmpps personal relationships api - dev

namespaces/live.cloud-platform.service.justice.gov.uk/laa-portal/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-portal/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-portal/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-portal/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-portal/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-portal/resources/basic-auth.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-portal/resources/ecr.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-portal/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-portal/resources/serviceaccount.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-portal/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-portal/resources/versions.tf
Adding my laa-prototype so it can be deployed in an live environment
=> deploying prototye for set up

namespaces/live.cloud-platform.service.justice.gov.uk/cccd-production/resources/secrets_manager.tf
This was added in error 🤦 
Also renames the other secret for consistency with other environments.
=> CCCD: Remove unnecessary read-replica secret

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-custody-mailbox-register-dev/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-custody-mailbox-register-dev/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-custody-mailbox-register-dev/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-custody-mailbox-register-dev/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-custody-mailbox-register-dev/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-custody-mailbox-register-dev/06-certificate.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-custody-mailbox-register-dev/resources/appinsights.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-custody-mailbox-register-dev/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-custody-mailbox-register-dev/resources/rds.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-custody-mailbox-register-dev/resources/secrets.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-custody-mailbox-register-dev/resources/ui-elasticache.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-custody-mailbox-register-dev/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-custody-mailbox-register-dev/resources/versions.tf
https://dsdmoj.atlassian.net/browse/MO-1628
This namespace will replace the existing one `hmpps-mailbox-register-dev`, that will be removed once we move the pipeline to deploy to this new one.
=> MO-1628 Create new mailbox register dev namespace

namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-preprod/resources/irsa.tf, namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-preprod/resources/large_court_cases_s3.tf
Add new S3 bucket for PreProd
Create ssm secrets to allow other services to read from the s3 bucket
=> court-probation-preprod Add new S3 bucket for PreProd

namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-dev/resources/irsa.tf
allow read only access to s3 bucket for the services using the irsa (default).
=> court-probation-dev allow read only access to s3 bucket

namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-prod/resources/irsa.tf, namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-prod/resources/large_court_cases_s3.tf
Add new S3 bucket for Prod
Create ssm secrets to allow other services to read from the s3 bucket
=> court-probation-prod Add new S3 bucket for Prod 

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-personal-relationships-preprod/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-personal-relationships-preprod/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-personal-relationships-preprod/06-certificate.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-personal-relationships-preprod/07-rbac-haar-client-admin-team.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-personal-relationships-preprod/resources/domain-events-topic.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-personal-relationships-preprod/resources/versions.tf
PRC-446 : update preprod environment for hmpps-personal-relationships-api
=> PRC-446 : update preprod environment for hmpps-personal-relationships-api

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-personal-relationships-preprod/resources/hmpps-personal-relationships-api.tf
PRC-446  : update-preprod-environment
=> PRC-446  : update-preprod-environment

namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-report-service-prod/resources/secret.tf
To hold db connection details for DCES events db.
=> DCES-690: Create a new secret (in PROD)

namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-report-service-staging/resources/secret.tf
To hold db connection details for DCES events db.
=> DCES-690: Create a new secret (in Staging) 

namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-report-service-uat/resources/secret.tf
to hold db connection details for DCES events db.
=> DCES-690: Create a new secret (in UAT) 

namespaces/live.cloud-platform.service.justice.gov.uk/manage-intelligence-dev/resources/ims-prisoner-details-resources.tf
New queue resources for pushing prisoner movement details
=> IMSV2-5939: create prisoner details queue resources

.github/workflows/annotation-check.yaml
- **feat(workflow): add workflow for annotation check on namespaces**
- **feat(workflow): remove echo step after testing**
- **feat(workflow): update secret ref**
=> annotation check

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-personal-relationships-prod/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-personal-relationships-prod/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-personal-relationships-prod/06-certificate.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-personal-relationships-prod/07-rbac-haar-client-admin-team.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-personal-relationships-prod/resources/domain-events-topic.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-personal-relationships-prod/resources/hmpps-personal-relationships-api.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-personal-relationships-prod/resources/versions.tf
PRC-446 : update prod environment for hmpps-personal-relationships-api
=> PRC-446 : update prod environment for hmpps-personal-relationships-api

.checksum, namespaces/live.cloud-platform.service.justice.gov.uk/analytical-platform-development/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/analytical-platform-development/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/analytical-platform-development/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/analytical-platform-development/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/analytical-platform-development/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/analytical-platform-development/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/analytical-platform-development/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/analytical-platform-development/resources/versions.tf
- Adds Analytical Platform development namespace
=> Add Analytical Platform development namespace

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-organisations-preprod/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-organisations-preprod/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-organisations-preprod/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-organisations-preprod/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-organisations-preprod/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-organisations-preprod/06-certificate.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-organisations-preprod/07-rbac-haar-client-admin-team.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-organisations-preprod/resources/domain-events-topic.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-organisations-preprod/resources/hmpps-organisations-api.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-organisations-preprod/resources/irsa.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-organisations-preprod/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-organisations-preprod/resources/rds-postgresql.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-organisations-preprod/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-organisations-preprod/resources/versions.tf
Adds the preprod namespace for the hmpps-organisations-api.
=> PRC-479: Build preprod environment for organisations api

namespaces/live.cloud-platform.service.justice.gov.uk/manage-intelligence-dev/resources/irsa.tf
Add prisoner queue resources to service account
=> IMSV2-5939: add prisoner details queue resources to service account

.github/workflows/annotation-check.yaml
workflow will check pull requests if it contains a namespace file, if present this will run a script to check annotations for source code and GitHub team name to see if they are valid
=> feat(workflow): Add annotations workflow in to test on namespace files for correct team names and source-code

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-intelligence-prod/resources/ims-prisoner-details-resources.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-intelligence-prod/resources/irsa.tf
add prisoner details resources to IMS prod
=> IMSV2-5939: add prisoner details queue resources to prod

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-portfolio-management-dev/resources/hmpps-service-catalogue.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-portfolio-management-dev/resources/serviceaccount.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-portfolio-management-dev/resources/versions.tf
Custom hmpps module entry for hmpps-service-catalogue
=> add module for hmpps-service-catalogue

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-adjustments-dev/resources/pingdom.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-adjustments-dev/resources/versions.tf
https://dsdmoj.atlassian.net/browse/ADJST-831
Pingdom Integration Id got from
https://github.com/ministryofjustice/cloud-platform/issues/6819
=> ADJST-831 Add Pingdom Adjustment Check for Adjustment and Adjustments API - Dev

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-portfolio-management-prod/resources/hmpps-service-catalogue.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-portfolio-management-prod/resources/serviceaccount.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-portfolio-management-prod/resources/versions.tf
Addition of service catalogue template to production namespace
=> Hmpps portflolio management prod service catalogue

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-adjustments-preprod/resources/pingdom.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-adjustments-preprod/resources/versions.tf
https://dsdmoj.atlassian.net/browse/ADJST-831
Pingdom Integration Id got from
https://github.com/ministryofjustice/cloud-platform/issues/6819
=> ADJST-831 Add Pingdom checks for Adjustment and Adjustment API - Preprod

namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-uat/05-prometheus.yaml
Reduce to 15 not founds in 5 minutes and change message. 
As agreed with team in ticket.
=> AP-5606: Reduce to 15 not founds in 5 minutes and change message [Civil Apply UAT]

namespaces/live.cloud-platform.service.justice.gov.uk/calculate-release-dates-dev/resources/pingdom.tf
https://dsdmoj.atlassian.net/browse/CRS-2278
=> CRS-2278 Change alert channel FE - Dev

namespaces/live.cloud-platform.service.justice.gov.uk/calculate-release-dates-preprod/resources/pingdom.tf
https://dsdmoj.atlassian.net/browse/CRS-2278
=> CRS-2278 Change alert to be sent to the right channel

namespaces/live.cloud-platform.service.justice.gov.uk/calculate-release-dates-api-preprod/resources/pingdom.tf
https://dsdmoj.atlassian.net/browse/CRS-2278
=> CRS-2278 Alert to be sent to the correct channel

namespaces/live.cloud-platform.service.justice.gov.uk/calculate-release-dates-api-dev/resources/pingdom.tf
https://dsdmoj.atlassian.net/browse/CRS-2278
=> CRS-2278 Change alert channel for CRDS API - Pingdom

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-delius-alfresco-prod/resources/migration.tf
Currently referencing wrong KMS key ARN
=> Change KMS key ARN

namespaces/live.cloud-platform.service.justice.gov.uk/make-recall-decision-dev/resources/govnotify-secret.tf
additional secrets for govnotify
=> Consider A Recall (aka make recall decisions) - additional secrets for govnotify

namespaces/live.cloud-platform.service.justice.gov.uk/offender-categorisation-preprod/resources/rds.tf, namespaces/live.cloud-platform.service.justice.gov.uk/offender-categorisation-preprod/resources/variables.tf
Upgrading preprod DB to version 16
=> SI-395 - Upgrade DB to 16 version

namespaces/live.cloud-platform.service.justice.gov.uk/offender-categorisation-dev/resources/rds.tf, namespaces/live.cloud-platform.service.justice.gov.uk/offender-categorisation-dev/resources/variables.tf
This reverts commit 4b9d4e8e0d6f108a902a3495ae3b497d4bb800c0.
=> Revert "SI-395 downgrade to 16.3 compatible version"

namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-staging/05-prometheus.yaml
AP-5606: increase notfound threshold
Every 15 is too noisy due to scripted probing
=> AP-5606: increase notfound threshold [Civil Apply Staging]

namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-production/05-prometheus.yaml
AP-5606: increase notfound threshold
Every 15 was too noisy due to scripted probes
=> AP-5606: increase notfound threshold [Civil Apply Production]

.checksum, namespaces/live.cloud-platform.service.justice.gov.uk/folarin-rds-namespace/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/folarin-rds-namespace/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/folarin-rds-namespace/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/folarin-rds-namespace/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/folarin-rds-namespace/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/folarin-rds-namespace/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/folarin-rds-namespace/resources/rds-mysql.tf, namespaces/live.cloud-platform.service.justice.gov.uk/folarin-rds-namespace/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/folarin-rds-namespace/resources/versions.tf
This PR creates:
1. a test namespace
2. a mysql rds dbase inside the namespace
3. It will serve as a backup dbase for the RDS restoration work in a separate namespace later
=> Rds restore ns0

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-dev/01-rbac.yaml
add `hmpps-integration-api` GH team to RBAC on `hmpps-integration-api-dev`
=> [ESWE-1227] Add `hmpps-integration-api` GH team to RBAC on `dev`

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-preprod/01-rbac.yaml
add `hmpps-integration-api` GH team to RBAC on `hmpps-integration-api-preprod`
=> [ESWE-1227] Add `hmpps-integration-api` GH team to RBAC on `preprod`

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-prod/01-rbac.yaml
add `hmpps-integration-api` GH team to RBAC on `hmpps-integration-api-prod`
=> [ESWE-1227] Add `hmpps-integration-api` GH team to RBAC on `prod`

namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-dev/resources/hmpps-prison-visits-allocation-events.tf, namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-dev/resources/hmpps-prison-visits-allocation-prisoner-retry-queue.tf, namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-dev/resources/hmpps-prison-visits-allocation-processing-job-events.tf
- Change retention settings
- Add dead letter queue for the prisoner-retry queue
=> Update visits-allocation-api queue configs in dev

namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-staging/resources/hmpps-prison-visits-allocation-events.tf, namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-staging/resources/hmpps-prison-visits-allocation-prisoner-retry-queue.tf, namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-staging/resources/hmpps-prison-visits-allocation-processing-job-events.tf
- Change retention settings
- Add dead letter queue for the prisoner-retry queue
=> Update visits-allocation-api queue configs in staging

namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-preprod/resources/hmpps-prison-visits-allocation-events.tf, namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-preprod/resources/hmpps-prison-visits-allocation-prisoner-retry-queue.tf
- Change retention and timeouts for all queues
- Add dlq for prisoner retry queue
=> Update visits-allocation-api qeueue configs in preprd

namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-prod/resources/hmpps-prison-visits-allocation-events.tf, namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-prod/resources/hmpps-prison-visits-allocation-prisoner-retry-queue.tf
Change retention and timeouts for all queues
Add dlq for prisoner retry queue
=> Update visits-allocation-api qeueue configs in prod

namespaces/live.cloud-platform.service.justice.gov.uk/abundant-namespace-dev/resources/rds-postgresql.tf
- this will break the terraform apply but the apply pipeline should raise a pr with a fix
=> fix: 🐛 BREAK: incompatible rds version

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-dev/resources/irsa.tf
Add access to jobs board integration queue on `dev`
=> [ESWE-1227] Add queue access on `dev`

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-preprod/resources/irsa.tf
Add access to jobs board integration queue on `preprod`
=> [ESWE-1227] Add queue access on `preprod`

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-prod/resources/irsa.tf
Add access to jobs board integration queue on `prod`
=> [ESWE-1227] Add queue access on `prod`

namespaces/live.cloud-platform.service.justice.gov.uk/cica-experian-dev/resources/s3-oidc-role.tf
=> 💚 CICA-Experian-fix-role-name

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-uat/resources/rds.tf
For CCR, to resolve failing build
=> Update rds version for uat

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-staging/resources/rds.tf
For CCR, to resolve failing build
=> Update rds version for staging

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-production/resources/rds.tf
For CCR, to resolve failing build
=> Update rds version for prod

namespaces/live.cloud-platform.service.justice.gov.uk/cloud-platform-reports-prod/resources/s3-irsa.tf, namespaces/live.cloud-platform.service.justice.gov.uk/cloud-platform-reports-prod/resources/s3.tf
In order to pull data for erroring namespaces page
relates to ministryofjustice/cloud-platform#6461
=> chore: 🤖 add policy for reading environments reports bucket

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-hdc-prototype/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-hdc-prototype/resources/variables.tf
Reverts ministryofjustice/cloud-platform-environments#29889
=> Revert "Replaced dps-shared team with create-and-vary-a-licence-dev in hmpps-…"

namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-preprod/resources/irsa.tf
Adding access to s3 performance bucket
=> PIC-4482: Adding access to s3 performance bucket

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-proceeding-dev/resources/secret.tf
Added ccp oauth secrets to CCP cev
=> Lasb 3878/add ccp oauth secrets dev

namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-preprod/resources/irsa.tf
Adding list bucket permissions to the s3 performance test bucket
=> PIC_4482: Adding list bucket permissions to the s3 performance test bucket

namespaces/live.cloud-platform.service.justice.gov.uk/folarin-dev/resources/rds-postgresql.tf
- the essence is test if a database engine version can be reverted using a snapshot.
=> create a postgresql dbase

namespaces/live.cloud-platform.service.justice.gov.uk/mikebell-test/resources/dms.tf, namespaces/live.cloud-platform.service.justice.gov.uk/mikebell-test/resources/versions.tf
- Add a dms instance to the mikebell-test namespace to test updates to the module
-
-
=> feat: add test dms instance

namespaces/live.cloud-platform.service.justice.gov.uk/folarin-dev/resources/rds-postgresql.tf
- the goal is to upgrade the database from version 16 to 17
- subsequently restore it to 16 using an already-taken snapshot
Relates to https://github.com/ministryofjustice/cloud-platform/issues/5401#issuecomment-2671167461
=> upgrade to version 17

.checksum, namespaces/live.cloud-platform.service.justice.gov.uk/stg-tech-for-com-example-dev/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/stg-tech-for-com-example-dev/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/stg-tech-for-com-example-dev/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/stg-tech-for-com-example-dev/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/stg-tech-for-com-example-dev/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/stg-tech-for-com-example-dev/resources/ecr.tf, namespaces/live.cloud-platform.service.justice.gov.uk/stg-tech-for-com-example-dev/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/stg-tech-for-com-example-dev/resources/serviceaccount.tf, namespaces/live.cloud-platform.service.justice.gov.uk/stg-tech-for-com-example-dev/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/stg-tech-for-com-example-dev/resources/versions.tf
Add namespace for example app as hosting experiment
=> Stg tech for com example dev

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-adjustments-dev/07-certificate.yaml
https://dsdmoj.atlassian.net/browse/ADJST-404
=> ADJST-404 Cert support for new adjustments dev url

namespaces/live.cloud-platform.service.justice.gov.uk/care-arrangement-plan-prod/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/care-arrangement-plan-prod/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/care-arrangement-plan-prod/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/care-arrangement-plan-prod/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/care-arrangement-plan-prod/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/care-arrangement-plan-prod/resources/ecr.tf, namespaces/live.cloud-platform.service.justice.gov.uk/care-arrangement-plan-prod/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/care-arrangement-plan-prod/resources/service-account.tf, namespaces/live.cloud-platform.service.justice.gov.uk/care-arrangement-plan-prod/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/care-arrangement-plan-prod/resources/versions.tf
=> Initial prod env for Care Arrangement Plan

namespaces/live.cloud-platform.service.justice.gov.uk/folarin-dev/resources/rds-postgresql.tf
- bump the read replica to match the primary database
=> bump read replica version to 17

namespaces/live.cloud-platform.service.justice.gov.uk/github-community-prod/resources/ecr.tf
- To align ECR prefix with environment
- Updated ECR Prefix to `prod`
=> ♻️ Refactor ECR Prefix

namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-dev/07-grafana.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-dev/prometheus-custom-rules-laa-dces-report-service.yaml
Changed some expr: and label values to make the graphs and alerts clearer, more useful.
=> DCES-722: Improve the labels and expressions in grafana monitor charts and prometheus alerts.

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-person-record-dev/resources/court-topic.tf
Store cpr_court_topic_sns_arn sns arn
=> Add AWS SSM secret

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-tier-dev/resources/versions.tf
- Remove github provider which is causing all the other PRs to fail
=> fix: remove github provider

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-tier-dev/resources/versions.tf
Adds github version to `versions.tf`
=> feat: add github provider

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-find-and-refer-an-intervention-prod/06-certificate.yaml
Add certificate definition for Find and Refer's production environment
=> Add certificate file for Find and Refer prod environment

namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-dev/resources/irsa.tf
This is to make sure our irsa module role_policy_arns stay under the threshold (assuming it is 15 arns)
=> CPR-495 Combine SQS policies

namespaces/live.cloud-platform.service.justice.gov.uk/care-arrangement-plan-dev/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/care-arrangement-plan-dev/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/care-arrangement-plan-dev/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/care-arrangement-plan-dev/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/care-arrangement-plan-dev/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/care-arrangement-plan-dev/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/care-arrangement-plan-dev/resources/service-account.tf, namespaces/live.cloud-platform.service.justice.gov.uk/care-arrangement-plan-dev/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/care-arrangement-plan-dev/resources/versions.tf
Create base resources for development stack
=> Init CAP development environment

namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-dev/resources/irsa.tf
Use the sqs_arn in the policy document
=> court-probation-dev update policy document

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-find-and-refer-an-intervention-prod/06-certificate.yaml
Revised certificate without environment suffix for Find And refer prod
=> Revised certificate without environment suffix

opa-auto-approve-policy/README.md
- Update OPA user guide for installing cli tool
=> docs: Update OPA user guide for installing cli tool

.checksum, namespaces/live.cloud-platform.service.justice.gov.uk/laa-cwa-feature-tests-dev/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-cwa-feature-tests-dev/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-cwa-feature-tests-dev/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-cwa-feature-tests-dev/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-cwa-feature-tests-dev/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-cwa-feature-tests-dev/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-cwa-feature-tests-dev/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-cwa-feature-tests-dev/resources/versions.tf
Added new namespace for `laa-cwa-feature-tests-dev`
=> feat: add new namespace

namespaces/live.cloud-platform.service.justice.gov.uk/laa-cwa-feature-tests-dev/resources/ecr.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-cwa-feature-tests-dev/resources/serviceaccount.tf
- Add ECR and SA for `laa-cwa-feature-tests-dev`
=> feat: add sa and ecr

namespaces/live.cloud-platform.service.justice.gov.uk/calculate-release-dates-dev/resources/hmpps-audit-queue.tf, namespaces/live.cloud-platform.service.justice.gov.uk/calculate-release-dates-dev/resources/irsa.tf, namespaces/live.cloud-platform.service.justice.gov.uk/calculate-release-dates-dev/resources/variables.tf
Create resources for crds audit events in development environment.
=> crs-2294-add-audit-resources-dev

namespaces/live.cloud-platform.service.justice.gov.uk/calculate-release-dates-dev/resources/hmpps-audit-queue.tf
Add missing sqs_queue_url secret required for Audit functionality
=> crs-2294-add-sqs-url-for-audit

namespaces/live.cloud-platform.service.justice.gov.uk/calculate-release-dates-preprod/resources/hmpps-audit-queue.tf, namespaces/live.cloud-platform.service.justice.gov.uk/calculate-release-dates-preprod/resources/irsa.tf, namespaces/live.cloud-platform.service.justice.gov.uk/calculate-release-dates-preprod/resources/variables.tf
Add resources to for access to audit service
=> crs-2294-audit-resource-for-preprod

namespaces/live.cloud-platform.service.justice.gov.uk/calculate-release-dates-prod/resources/hmpps-audit-queue.tf, namespaces/live.cloud-platform.service.justice.gov.uk/calculate-release-dates-prod/resources/irsa.tf, namespaces/live.cloud-platform.service.justice.gov.uk/calculate-release-dates-prod/resources/variables.tf
Add resources to for access to audit service
=> crs-2294-audit-resource-for-prod

namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-dev/07-grafana.yaml
Added changes for the contribution scheduler count.
To see how the panel changes will be surface in the proper environment.
=> DCES-728 Grafana Fixes - Contribution Scheduler

namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-dev/07-grafana.yaml
=> DCES-728-Grafana-Fixes

namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-data-migration-dev/resources/iam.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-data-migration-dev/resources/s3.tf
=> laa-dces-data-migration-numero-user

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-activities-management-prod/resources/rds.tf
=> SAA-2354: upgrade prod activities database set prepare for major upgrade to false

namespaces/live.cloud-platform.service.justice.gov.uk/manage-intelligence-dev/resources/irsa.tf, namespaces/live.cloud-platform.service.justice.gov.uk/manage-intelligence-dev/resources/s3-index-batch.tf
IMS - Add S3 resources for batch indexing
=> IMSV2-5932: Add index batch S3 dev resources

namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-dev/prometheus-custom-rules-laa-dces-report-service.yaml
Re-creating prometheus alert rules as advised.
=> DCES-728-Build-Fix

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-activities-management-preprod/resources/irsa.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-activities-management-preprod/resources/rds.tf
This is replaced by the activities_rds instance
=> SAA-2351: remove old database instance in pre-prod. 

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-intelligence-preprod/resources/irsa.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-intelligence-preprod/resources/s3-index-batch.tf
Add S3 bucket support to index batch Q
=> IMSV2-5932: Add index batch S3 preprod resources

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-intelligence-prod/resources/irsa.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-intelligence-prod/resources/s3-index-batch.tf
Add S3 bucket to support index batch Q
=> IMSV2-5932: Add index batch S3 prod resources

.checksum, namespaces/live.cloud-platform.service.justice.gov.uk/laa-smtp-mock-dev/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-smtp-mock-dev/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-smtp-mock-dev/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-smtp-mock-dev/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-smtp-mock-dev/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-smtp-mock-dev/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-smtp-mock-dev/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-smtp-mock-dev/resources/versions.tf
This PR is created for the request of new namespace
=> Create namespace for my-new-environment

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-strengths-based-needs-assessments-dev/resources/rds.tf
Moving the extension into the correct database.
=> Fix the database name for the extension

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-strengths-based-needs-assessments-dev/resources/rds.tf
Remove the `dblink` resource, so it can be re-added it in another PR.
=> Remove and replace dblink resource

namespaces/live.cloud-platform.service.justice.gov.uk/laa-smtp-mock-dev/resources/serviceaccount.tf
This PR is requested for creating the secrets for GitHub Actions
=> updated the github repository for github actions secret

namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-data-migration-dev/resources/iam.tf
=> laa-dces-dm-dev-objTag

namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-prod/resources/certificates.tf
Add hmiprobation and hmiprison certs
=> Hale Platform - justiceinspectorates - certs

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-preprod/resources/rds.tf
Pre-Prod: increase db_allocated_storage from 10 to 50 for rds module.
=> CAS pre-prod database: increase db_allocated_storage from 10 to 50 for rds module

namespaces/live.cloud-platform.service.justice.gov.uk/laa-smtp-mock-dev/resources/ecr.tf
This PR is created for the new container registry
=> new ecr file for container registry

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-jobs-board-preprod/resources/rds-postgresql.tf
=> [ESWE-1262] Remove preprod read replica

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-person-record-prod/resources/person-match-rds.tf
* Finished migration, revert db allocation
=> CPR-629 Remove memory allocation

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-dev/resources/rds.tf
To fix break in build, update the rds version of ccr dev
=> Update rds for ccr dev

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-jobs-board-preprod/resources/rds-postgresql.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-jobs-board-preprod/resources/variables.tf
Confiure param groups for PreProd
=> [ESWE-1260] Confiure param groups for PreProd

.github/workflows/annotation-check.yaml, .github/workflows/conftest-k8s-yaml.yaml, .github/workflows/ecr-deletion-check.yaml, .github/workflows/terraform-tools.yml
- Bumps tj-actions changed files to latest version
=> ci: bump tj-actions changed files to latest release

.github/workflows/terraform-tools.yml
- Bump tj-actions changed files
=> ci: bump tj-action changed-files in tftools

.github/workflows/auto-approve-pr.yaml, .github/workflows/bin-rspec.yml, .github/workflows/check-permissions.yaml, .github/workflows/check-terraform-module-version.yaml, .github/workflows/compare-namespaces.yaml, .github/workflows/devsec-scan.yaml, .github/workflows/format-code.yml, .github/workflows/iam-role-policy-changes-check.yaml, .github/workflows/malformed-yaml.yml, .github/workflows/opa-aap-test.yml, .github/workflows/opa-tests.yml, .github/workflows/po-linter.yaml, .github/workflows/reject-multi-namespace-prs.yml, .github/workflows/run-go-tests.yaml, .github/workflows/skip-file-auto-approval.yaml, .github/workflows/yaml-metadata-change-check.yaml
- Pins most (see [here](https://github.com/ministryofjustice/cloud-platform/issues/6913)) actions to sha commits
=> Pin actions

namespaces/live.cloud-platform.service.justice.gov.uk/laa-cwa-feature-tests-dev/resources/ecr.tf
=> feat: add oidc provider for circleci

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-assess-risks-and-needs-integrations-dev/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-assess-risks-and-needs-integrations-dev/resources/outputs-to-ssm-parameters.tf
I need access to the data from this namespace to use in setting up a Foreign Data Wrapper within an RDS in another namespace.
=> Export database data for use in another namespace

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-sentence-plan-dev/05-certificates.yml
Used for ephemeral deployments
=> Add wildcard subdomain for sentence-plan-dev

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-assess-risks-and-needs-integrations-dev/resources/outputs-to-ssm-parameters.tf
Correct issue with incorrect variables being used.
=> Update exports to use correct values

.checksum, namespaces/live.cloud-platform.service.justice.gov.uk/dedsai-reason-tagging-api-prod/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/dedsai-reason-tagging-api-prod/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/dedsai-reason-tagging-api-prod/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/dedsai-reason-tagging-api-prod/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/dedsai-reason-tagging-api-prod/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/dedsai-reason-tagging-api-prod/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/dedsai-reason-tagging-api-prod/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/dedsai-reason-tagging-api-prod/resources/versions.tf
Adds a production namespace for a new app - https://github.com/ministryofjustice/dedsai-reason-tagging-api/tree/dev
=> Add prod namespace for dedsai-reason-tagging-api

namespaces/live.cloud-platform.service.justice.gov.uk/calculate-release-dates-api-preprod/resources/rds.tf
* Adds sg to RDS to allow data catalogue team access to the RDS instance
=> CRS-2290 Allow data catalogue access to pre-prod RDS

namespaces/live.cloud-platform.service.justice.gov.uk/laa-cwa-feature-tests-dev/resources/irsa.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-cwa-feature-tests-dev/resources/s3.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-cwa-feature-tests-dev/resources/serviceaccount.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-cwa-test/resources/irsa.tf
- Add S3 bucket
- Add S3/K8S IRSA
- Expand and rotate existing SA
=> feat: add irsa, s3 and expand existing sa

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-organisations-preprod/resources/rds-postgresql.tf
An earlier PR was merged 18th March - but concourse did not apply the changes.
This is an attempt to prod it into action.
=> PRC-571: Small change to prompt concourse to apply earlier changes

namespaces/live.cloud-platform.service.justice.gov.uk/legal-framework-api-uat/00-namespace.yaml
Update LAA LFA UAT slack channel from applyprivatebeta to apply-dev
=> Update LAA LFA UAT slack channel

namespaces/live.cloud-platform.service.justice.gov.uk/legal-framework-api-staging/00-namespace.yaml
Update LAA LFA STG slack channel from applyprivatebeta to apply-dev
=> Update LAA LFA STG slack channel

namespaces/live.cloud-platform.service.justice.gov.uk/legal-framework-api-production/00-namespace.yaml
Update LAA LFA PRD slack channel from applyprivatebeta to apply-dev
=> Update LAA LFA PRD slack channel

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-strengths-based-needs-assessments-dev/resources/rds.tf
Had a typo in the fdw_name field.
=> Fix typo in fdw name

.checksum, namespaces/live.cloud-platform.service.justice.gov.uk/dedsai-reason-tagging-api-dev/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/dedsai-reason-tagging-api-dev/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/dedsai-reason-tagging-api-dev/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/dedsai-reason-tagging-api-dev/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/dedsai-reason-tagging-api-dev/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/dedsai-reason-tagging-api-dev/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/dedsai-reason-tagging-api-dev/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/dedsai-reason-tagging-api-dev/resources/versions.tf
Add a dev namespace for a new app - 
https://github.com/ministryofjustice/dedsai-reason-tagging-api/tree/dev
=> Add dev namespace for dedsai-reason-tagging-api

namespaces/live.cloud-platform.service.justice.gov.uk/laa-smtp-mock-dev/04-networkpolicy.yaml
This PR is created for adding the annotations.
=> annotations are added for ingress

namespaces/live.cloud-platform.service.justice.gov.uk/laa-smtp-mock-dev/04-networkpolicy.yaml
This PR is created for adding annotations heading
=> added annotations heading

namespaces/live.cloud-platform.service.justice.gov.uk/laa-cwa-feature-tests-dev/resources/secret.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-cwa-feature-tests-dev/resources/variables.tf
Add test secrets to new namespace
=> add test secrets to the namespace

namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-prod/resources/cpr-court-cases-queue.tf, namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-prod/resources/cpr-large-court-cases-s3-bucket-secret.tf, namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-prod/resources/data.tf, namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-prod/resources/irsa.tf
Create a new standard SQS queue and subcribe to CPR teams SNS topic
Allow our irsa service account access to get objects from CPR teams S3 bucket
**This if for PROD environment**
=> PIC-4543 court-probation-prod create CPR large court cases queue and allow access to S3

namespaces/live.cloud-platform.service.justice.gov.uk/github-community-dev/resources/ecr.tf, namespaces/live.cloud-platform.service.justice.gov.uk/github-community-dev/resources/irsa.tf, namespaces/live.cloud-platform.service.justice.gov.uk/github-community-dev/resources/rds.tf, namespaces/live.cloud-platform.service.justice.gov.uk/github-community-dev/resources/route53.tf, namespaces/live.cloud-platform.service.justice.gov.uk/github-community-dev/resources/serviceaccount.tf, namespaces/live.cloud-platform.service.justice.gov.uk/github-community-dev/resources/variables.tf
add resources for GitHub community dev environment
=> Configure GitHub Community Dev environment

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-strengths-based-needs-assessments-dev/resources/rds.tf
Update user mapping name to match local username.
=> Update user mapping name

namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-dev/resources/variables.tf
=> PIC-4543 update rds to 14.13 in dev

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-dev/06-servicemonitor.yaml
Specify the metrics path in the service monitor for CCR dev
=> Add path for metrics for CCR dev

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-strengths-based-needs-assessments-dev/resources/rds.tf
Map directly to the current DB user.
=> Map directly to DB user

namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-dev/resources/irsa.tf
Noticed a missing comma in the policies, correcting in case this is causing an issue
=> HMAI-332 - Add missing comma

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-custody-mailbox-register-prod/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-custody-mailbox-register-prod/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-custody-mailbox-register-prod/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-custody-mailbox-register-prod/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-custody-mailbox-register-prod/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-custody-mailbox-register-prod/06-certificate.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-custody-mailbox-register-prod/07-rbac-haar-client-admin-team.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-custody-mailbox-register-prod/resources/elasticache.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-custody-mailbox-register-prod/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-custody-mailbox-register-prod/resources/rds.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-custody-mailbox-register-prod/resources/secrets.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-custody-mailbox-register-prod/resources/template-api.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-custody-mailbox-register-prod/resources/template-ui.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-custody-mailbox-register-prod/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-custody-mailbox-register-prod/resources/versions.tf
Ticket: https://dsdmoj.atlassian.net/browse/MO-1659
=> MO-1659 Create new mailbox register prod namespace

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-custody-mailbox-register-preprod/resources/rds.tf
https://dsdmoj.atlassian.net/browse/MO-1663
=> Inject preprod rds creds in prod namespace

namespaces/live.cloud-platform.service.justice.gov.uk/care-arrangement-plan-prod/resources/elasticache.tf
Adding redis for the Care Arrangement Plan prod environment - https://github.com/ministryofjustice/care-arrangement-plan.
Author @josephsilcock
=> care-arrangement-plan-prod Add redis

namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-dev/07-grafana.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-dev/prometheus-custom-rules-laa-dces-report-service.yaml
Revert Grafana expr change.
Namespace addition to alerts test.
Reverting the severity to app.
=> DCES-Alerts

namespaces/live.cloud-platform.service.justice.gov.uk/mikebell-test/resources/rds.tf
- Adds a postgres rds instance for testing
=> feat: add postgres to mikebell-test

.checksum, namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccw-fees-ui-dev/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccw-fees-ui-dev/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccw-fees-ui-dev/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccw-fees-ui-dev/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccw-fees-ui-dev/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccw-fees-ui-dev/resources/ecr.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccw-fees-ui-dev/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccw-fees-ui-dev/resources/serviceaccount.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccw-fees-ui-dev/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccw-fees-ui-dev/resources/versions.tf
- Created a new cloud platform environment for - **laa-ccw-fees-service-ui**
=> BILL-68: Create environment - laa-ccw-fees-service-ui 

namespaces/live.cloud-platform.service.justice.gov.uk/laa-cwa-feature-tests-dev/resources/ecr.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-cwa-feature-tests-dev/resources/serviceaccount.tf
Limit scope of ECR policy and SA for NS `laa-cwa-feature-tests-dev`
=> chore: limit ecr and sa

namespaces/live.cloud-platform.service.justice.gov.uk/mikebell-test/resources/rds.tf
- Adds a secret to output rds credentials to
=> feat: add secret for RDS

namespaces/live.cloud-platform.service.justice.gov.uk/dedsai-intel-sanitise-api-dev/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/dedsai-intel-sanitise-api-dev/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/dedsai-intel-sanitise-api-dev/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/dedsai-intel-sanitise-api-dev/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/dedsai-intel-sanitise-api-dev/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/dedsai-intel-sanitise-api-dev/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/dedsai-intel-sanitise-api-dev/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/dedsai-intel-sanitise-api-dev/resources/versions.tf
Creating dev namespace for the intelligence sanitisation project API
=> Intelligence sanitisation API

.github/workflows/terraform-tools.yml, namespaces/live.cloud-platform.service.justice.gov.uk/emma-cloud-test/00-namespace.yaml
Reverts ministryofjustice/cloud-platform-environments#30735
=> Revert "amending tflint to run on only namespaces with changed files"

namespaces/live.cloud-platform.service.justice.gov.uk/laa-cwa-feature-tests-test/resources/irsa.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-cwa-feature-tests-test/resources/s3.tf
add `s3` and `irsa` to namespace `laa-cwa-feature-tests-test`
=> feat: add s3 and irsa to laa-cwa-feature-tests-test

.checksum, namespaces/live.cloud-platform.service.justice.gov.uk/laa-cwa-feature-tests-uat/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-cwa-feature-tests-uat/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-cwa-feature-tests-uat/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-cwa-feature-tests-uat/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-cwa-feature-tests-uat/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-cwa-feature-tests-uat/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-cwa-feature-tests-uat/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-cwa-feature-tests-uat/resources/versions.tf
add ns `laa-cwa-feature-tests-uat`
=> feat: add ns laa-cwa-feature-tests-uat

cmd/namespace-divergence/divergence.go
relates to ministryofjustice/cloud-platform#6884
=> chore: 🤖 remove kuberhealthy ns refs

namespaces/live.cloud-platform.service.justice.gov.uk/legal-framework-api-staging/resources/rds.tf
Update to 16.4 in accordance with the AWS update guidance
=> LAA Legal Framework Staging: Update postgres 14 > 16.4

namespaces/live.cloud-platform.service.justice.gov.uk/legal-framework-api-staging/resources/rds.tf
Remove the skip file and restore prepare_for_major_upgrade to false
=> LAA Framework Staging: update postgres tidy up

namespaces/live.cloud-platform.service.justice.gov.uk/legal-framework-api-uat/resources/serviceaccount-circleci.tf
This is needed for a new postgres bitnami 17 update
=> LAA Legal Framework UAT: Update CircleCI service account permissions

namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccw-fees-service-dev/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccw-fees-service-dev/resources/rds.tf
- Added RDS PostgreSQL database instance to the LAA CCW Fees Service dev environment.
=> BILL-84: Added RDS PostgreSQL database

namespaces/live.cloud-platform.service.justice.gov.uk/sw-psa-audit-test/resources/ecr.tf, namespaces/live.cloud-platform.service.justice.gov.uk/sw-psa-audit-test/resources/sns.tf, namespaces/live.cloud-platform.service.justice.gov.uk/sw-psa-audit-test/resources/sqs.tf
relates to ministryofjustice/cloud-platform#6115
=> chore: 🤖 add some test resources for team var renaming

namespaces/live.cloud-platform.service.justice.gov.uk/legal-framework-api-production/resources/rds.tf
Update to 16.4 in accordance with the AWS update guidance
=> LAA Legal Framework Production: Update postgres 14 > 16.4

namespaces/live.cloud-platform.service.justice.gov.uk/laa-assure-hmrc-data-uat/resources/rds-postgresql.tf
Upgrade assure UAT RDS instance from 14.13 to 16.4
=> [Assure UAT] Upgrade assure UAT RDS instance from 14.13 to 16.4

namespaces/live.cloud-platform.service.justice.gov.uk/laa-assure-hmrc-data-uat/resources/rds-postgresql.tf
[Assure UAT] disable prepare_for_major_upgrade
=> [Assure UAT] disable prepare_for_major_upgrade

namespaces/live.cloud-platform.service.justice.gov.uk/laa-assure-hmrc-data-uat/resources/rds-postgresql.tf
[Assure UAT] Upgrade RDS instance from 16.4 to 17.4
=> [Assure UAT] Upgrade RDS instance from 16.4 to 17.4

namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-datahub-catalogue-dev/resources/rds-postgresql.tf
- Upgrades postgres minor version to the latest 15 release
- Adds a scheduled maintenance window
=> Upgrade datahub db to 15.12

namespaces/live.cloud-platform.service.justice.gov.uk/laa-assure-hmrc-data-uat/resources/rds-postgresql.tf
[Assure UAT] Remove skip pipeline and disable prepare_for_major_upgrade
Following RDS upgrade 14.13 to 17.4
=> [Assure UAT]: Remove pipeline skip and reset prepare_for_major_upgrade

namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-datahub-catalogue-dev/resources/rds-postgresql.tf, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-datahub-catalogue-dev/resources/variables.tf
- removes pipeline skip file
- applies variables for db params
- removes redundant read replica config
=> Remove pipeline skip file and move db inputs to variables

namespaces/live.cloud-platform.service.justice.gov.uk/laa-assure-hmrc-data-staging/resources/rds-postgresql.tf
Assure staging: bump postgres 14.13 to 16.4
=> [Assure staging] bump postgres 14.13 to 16.4

namespaces/live.cloud-platform.service.justice.gov.uk/laa-assure-hmrc-data-staging/resources/rds-postgresql.tf
Assure staging: remove prepare_for_major_upgrade
=> [Assure staging] Remove prepare_for_major_upgrade

namespaces/live.cloud-platform.service.justice.gov.uk/laa-assure-hmrc-data-staging/resources/rds-postgresql.tf
Assure staging: upgrade postgres 16.4 to 17.4
=> [Assure staging] upgrade postgres 16.4 to 17.4

namespaces/live.cloud-platform.service.justice.gov.uk/laa-assure-hmrc-data-staging/resources/rds-postgresql.tf
Assure staging: remove skip file and turn off prepare_for_major_upgrade
=> [Assure staging] Remove skip file and turn off prepare_for_major_upgrade

namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-datahub-catalogue-preprod/resources/rds-postgresql.tf, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-datahub-catalogue-preprod/resources/variables.tf
- Upgrades db to the v15 latest (15.12)
- Replaces hard codes values with variables
- Adds maintenance and backup windows
- Removes commented out password rotation variable
=> Upgrade to PG 15.12 & refactor RDS module to use variables for configuration parameters a

namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-datahub-catalogue-prod/resources/rds-postgresql.tf, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-datahub-catalogue-prod/resources/variables.tf
- Upgrades db to the v15 latest (15.12)
- Replaces hard coded values with variables
- Adds maintenance and backup windows
- Removes commented out password rotation variable
=> Refactor RDS module to use variables for configuration parameters

namespaces/live.cloud-platform.service.justice.gov.uk/laa-assure-hmrc-data-production/resources/rds-postgresql.tf
Assure production: Bump RDS postgresql 14.13 to 16.4
First step to 17.4
=> [Assure production] Bump RDS postgresql 14.13 to 16.4

namespaces/live.cloud-platform.service.justice.gov.uk/laa-assure-hmrc-data-production/resources/rds-postgresql.tf
Assure production: turn off prepare_for_major_upgrade
=> [Assure production] turn off prepare_for_major_upgrade

namespaces/live.cloud-platform.service.justice.gov.uk/legal-framework-api-production/resources/rds.tf
Remove the skip file and restore prepare_for_major_upgrade to false
=> LAA Framework Production: update postgres tidy up

namespaces/live.cloud-platform.service.justice.gov.uk/laa-assure-hmrc-data-production/resources/rds-postgresql.tf
Assure production: Bump RDS postgresql 16.4 to 17.4
=> [Assure production] Bump RDS postgresql 16.4 to 17.4

namespaces/live.cloud-platform.service.justice.gov.uk/laa-assure-hmrc-data-production/resources/rds-postgresql.tf
Assure production: remove skip file and turn of prepare_for_major_upgrade
=> [Assure production] Remove skip file and turn of prepare_for_major_upgrade

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-dev/resources/irsa.tf
We're having issues setting up HMPPS Audit. This module was missing so hoping this fixes the issue
=> Add IRSA modules for CAS2 Bail dev

namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-prod/resources/brookhouse-route53.tf
* Trim DMARC record as per requested
* Clean-up remove old AWS records
=> Hale platform prod brookhouse dns changes

namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-dev/prometheus-custom-rules-laa-dces-report-service.yaml
Fixes to for and adding firing for.
=> DCES Alerts

namespaces/live.cloud-platform.service.justice.gov.uk/tim-development/resources/guardduty.tf, namespaces/live.cloud-platform.service.justice.gov.uk/tim-development/resources/rds.tf
=> chore: create rds

namespaces/live.cloud-platform.service.justice.gov.uk/tim-development/resources/rds.tf
- intentionally downgrade rds to create error
=> chore: intentionally downgrade rds to create error

.checksum, namespaces/live.cloud-platform.service.justice.gov.uk/dedsai-intel-sanitise-dash-dev/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/dedsai-intel-sanitise-dash-dev/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/dedsai-intel-sanitise-dash-dev/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/dedsai-intel-sanitise-dash-dev/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/dedsai-intel-sanitise-dash-dev/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/dedsai-intel-sanitise-dash-dev/resources/ecr.tf, namespaces/live.cloud-platform.service.justice.gov.uk/dedsai-intel-sanitise-dash-dev/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/dedsai-intel-sanitise-dash-dev/resources/serviceaccount.tf, namespaces/live.cloud-platform.service.justice.gov.uk/dedsai-intel-sanitise-dash-dev/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/dedsai-intel-sanitise-dash-dev/resources/versions.tf
Deploy dash app for the intelligence sanitisation project
=> Intel dash dev

namespaces/live.cloud-platform.service.justice.gov.uk/sw-cp-testing/resources/sqs-2.tf
=> chore: 🤖 add another sqs test (3)

cmd/check-terraform-modules-are-latest/go.mod, cmd/check-terraform-modules-are-latest/go.sum
Reverts ministryofjustice/cloud-platform-environments#30385
=> Revert "Bump golang.org/x/net from 0.23.0 to 0.36.0 in /cmd/check-terraform-modules-are-latest"

namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-prod/resources/pingdom.tf
Add new integration id to point to our new slack alerts channel for PROD
=> PIC-4584 Add new integration id

namespaces/live.cloud-platform.service.justice.gov.uk/laa-access-civil-legal-aid-staging/04-networkpolicy.yaml
Allows Access staging to connect to Backend training.
=> Access Connection to CLA Backend Staging

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-litigator-fees-dev/resources/rds.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-litigator-fees-production/resources/rds.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-litigator-fees-staging/resources/rds.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-litigator-fees-uat/resources/rds.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-dev/resources/rds.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-production/resources/rds.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-staging/resources/rds.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-uat/resources/rds.tf
relates to ministryofjustice/cloud-platform#6464
[release notes](https://github.com/ministryofjustice/cloud-platform-terraform-rds-instance/releases/tag/8.1.0)
=> chore: 🤖 bump oracle migrated rds modules

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-dps-reconciliation-dev/resources/hmpps-domain-topic.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-dps-reconciliation-dev/resources/hmpps-offender-topic.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-dps-reconciliation-dev/resources/irsa.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-dps-reconciliation-dev/resources/rds.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-dps-reconciliation-dev/resources/reconciliation-queue.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-dps-reconciliation-dev/resources/variables.tf
Queue, topics, database and IRSA
=> SDIT-2692 Create reconciliation process between release and receive events and Nomis movements part 2

namespaces/live.cloud-platform.service.justice.gov.uk/analytical-platform-development/resources/rds.tf, namespaces/live.cloud-platform.service.justice.gov.uk/analytical-platform-development/resources/service-accounts.tf
- Adds RDS instance
- Adds Kubernetes service account
=> 🗃️ Add RDS and SA

namespaces/live.cloud-platform.service.justice.gov.uk/cfocats-dev/resources/sns.tf, namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-dev/resources/court-cases-sns-topic.tf, namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-preprod/resources/court-cases-sns-topic.tf, namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-prod/resources/court-cases-sns-topic.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-person-record-dev/resources/court-topic.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-person-record-preprod/resources/court-topic.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-person-record-prod/resources/court-topic.tf
relates to ministryofjustice/cloud-platform#6115
[release](https://github.com/ministryofjustice/cloud-platform-terraform-sns-topic/releases/tag/5.1.1)
=> chore: 🤖 first round of sns topic module bumping

namespaces/live.cloud-platform.service.justice.gov.uk/cccd-dev-lgfs/resources/messaging.tf, namespaces/live.cloud-platform.service.justice.gov.uk/cccd-dev/resources/messaging.tf, namespaces/live.cloud-platform.service.justice.gov.uk/cccd-production/resources/messaging.tf, namespaces/live.cloud-platform.service.justice.gov.uk/cccd-staging/resources/messaging.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-events-dev/resources/hmpps-domain-events-topic.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-events-preprod/resources/hmpps-domain-events-topic.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-events-prod/resources/hmpps-domain-events-topic.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-dev/resources/event-topic.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-preprod/resources/event-topic.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-prod/resources/event-topic.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-criminal-applications-datastore-production/resources/sns-application-events.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-criminal-applications-datastore-staging/resources/sns-application-events.tf, namespaces/live.cloud-platform.service.justice.gov.uk/offender-events-dev/resources/topic.tf, namespaces/live.cloud-platform.service.justice.gov.uk/offender-events-preprod/resources/topic-perf.tf, namespaces/live.cloud-platform.service.justice.gov.uk/offender-events-preprod/resources/topic.tf, namespaces/live.cloud-platform.service.justice.gov.uk/offender-events-prod/resources/topic.tf
relates to ministryofjustice/cloud-platform#6115
closes ministryofjustice/cloud-platform#6115
[release](https://github.com/ministryofjustice/cloud-platform-terraform-sns-topic/releases/tag/5.1.1)
=> chore: 🤖 bump sns topics round two

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-dps-reconciliation-dev/06-certificate.yaml
=> SDIT-2692 Create reconciliation process between release and receive events and Nomis movements part 3

namespaces/live.cloud-platform.service.justice.gov.uk/laa-access-civil-legal-aid-staging/05-certificate.yaml
laa-access-civil-legal-aid-staging - Add tls cert setup
=> laa-access-civil-legal-aid-staging - Add tls cert setup

namespaces/live.cloud-platform.service.justice.gov.uk/laa-access-civil-legal-aid-uat/05-certificate.yaml
laa-access-civil-legal-aid-uat - Add tls cert setup
=> laa-access-civil-legal-aid-uat - Add tls cert setup

.github/workflows/annotation-check.yaml, .github/workflows/conftest-k8s-yaml.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/jacksapp-dev/00-namespace.yaml, policy/clusterrole.rego, policy/clusterrole_test.rego, policy/clusterrolebinding.rego, policy/clusterrolebinding_test.rego, policy/namespace.rego, policy/namespace_test.rego, policy/rolebinding.rego, policy/rolebinding_test.rego, policy/serviceaccount.rego, policy/serviceaccount_test.rego, policy/utils.rego
- **fix(contest): update syntax, to fix erroring opa-tests**
=> (contest) update syntax, to fix erroring opa-tests

policy/clusterrole.rego, policy/clusterrole_test.rego, policy/clusterrolebinding.rego, policy/clusterrolebinding_test.rego, policy/namespace.rego, policy/namespace_test.rego, policy/rolebinding.rego, policy/rolebinding_test.rego, policy/serviceaccount.rego, policy/serviceaccount_test.rego, policy/utils.rego
opa test . -v               
clusterrole_test.rego:
data.main.test_deny_invalid_kind_clusterrole: PASS (618.834µs)
clusterrolebinding_test.rego:
data.main.test_deny_invalid_kind_clusterrolebinding: PASS (163µs)
namespace_test.rego:
data.main.test_deny_empty_business_unit: PASS (546.833µs)
data.main.test_deny_missing_application: PASS (481.5µs)
data.main.test_deny_invalid_busines_unit: PASS (1.026625ms)
data.main.test_not_deny_valid_busines_unit: PASS (408.167µs)
rolebinding_test.rego:
data.main.test_valid_rolebinding: PASS (103.416µs)
data.main.test_invalid_cluster_admin_rolebinding: PASS (114.292µs)
serviceaccount_test.rego:
data.main.test_deny_service_account: PASS (92.75µs)
=> fix(opa): contest policies update

policy/clusterrole.rego, policy/clusterrole_test.rego, policy/clusterrolebinding.rego, policy/clusterrolebinding_test.rego, policy/namespace.rego, policy/namespace_test.rego, policy/rolebinding.rego, policy/rolebinding_test.rego, policy/serviceaccount.rego, policy/serviceaccount_test.rego, policy/utils.rego
revert https://github.com/ministryofjustice/cloud-platform-environments/pull/32042
=> fix: 🐛 revert syntax errors

namespaces/live.cloud-platform.service.justice.gov.uk/laa-access-civil-legal-aid-production/05-certificate.yaml
laa-access-civil-legal-aid-production - Add tls cert setup
=> laa-access-civil-legal-aid-production - Add tls cert setup

.checksum, namespaces/live.cloud-platform.service.justice.gov.uk/fraud-and-corruption-insights-dev/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/fraud-and-corruption-insights-dev/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/fraud-and-corruption-insights-dev/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/fraud-and-corruption-insights-dev/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/fraud-and-corruption-insights-dev/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/fraud-and-corruption-insights-dev/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/fraud-and-corruption-insights-dev/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/fraud-and-corruption-insights-dev/resources/versions.tf
We don't have a team email address at thew moment. We can set one up soon but hopefully the personal email address is okay for now?
=> Create namespace for fraud-and-corruption-insights-dev

namespaces/live.cloud-platform.service.justice.gov.uk/laa-get-payments-finance-data-dev/resources/ecr.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-get-payments-finance-data-dev/resources/variables.tf
fix for: https://github.com/ministryofjustice/cloud-platform-environments/pull/32205
=> [LPF-535]: Integrate acceptance tests into dev pipeline - update ecr name

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-test/resources/hmpps-approved-premises-ui.tf
`test`: deploy review from separate 'Deploy to test' workflow, for any branch
=> Update CAS1 UI environment protection rules - test

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-dev/resources/hmpps-approved-premises-ui.tf
`development`: auto-deploys from pipeline, only main branch
=> Update CAS1 UI environment protection rules - dev

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-preprod/resources/hmpps-approved-premises-ui.tf
`preprod`: deploy review from pipeline, only main branch
=> Update CAS1 UI env protection rules - preprod

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-prod/resources/hmpps-approved-premises-ui.tf
`prod`: deploy review from pipeline, only main branch
=> Update CAS1 UI environment protection rules - prod

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-accredited-programmes-dev/resources/rds-postgresql.tf
- Disable major upgrade preparation for RDS 
- Remove pipeline skip file
=> [APG-536] Disable major upgrade preparation for RDS and remove pipeline skip file - DEV

namespaces/live.cloud-platform.service.justice.gov.uk/sw-cp-testing/resources/ses.tf
relates to ministryofjustice/cloud-platform#7052
=> chore: 🤖 test IAM SES credentials creation for test ses domain

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-adjustments-dev/resources/hmpps-audit-queue.tf
https://dsdmoj.atlassian.net/browse/ADJST-513
=> ADJST-513 - Create the secrets required for Audit queue

opa-auto-approve-policy/ecr/ecr_update.rego, opa-auto-approve-policy/ecr/main.rego
- fix rename ecr note trigger (trigger whenever the repo changes name) @sj-williams will add a user guide to this message
=> test: 💍 update logic for any ecr team name

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-adjustments-dev/resources/irsa.tf
https://dsdmoj.atlassian.net/browse/ADJST-513
=> ADJST-513 - Adding in policies to allow audit service credentials to work

namespaces/live.cloud-platform.service.justice.gov.uk/mikebell-test/resources/github-env.tf
- fixes duplicate module name for github env
=> fix: change module name for prod

namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-datahub-catalogue-prod/resources/rds-postgresql.tf
Restore the DB to the given snapshot
=> Data catalogue db restore

opa-auto-approve-policy/allowlist/main.rego, opa-auto-approve-policy/kubernetes_secret/main.rego, opa-auto-approve-policy/kubernetes_secret/tests/main_test.rego
- k8s secret was not matching noop changes
=> fix: 🐛 noop k8s bug

opa-auto-approve-policy/autoapprove.sh
- Adds the auto approve script to the opa folder
=> feat: add auto approve script to folder

namespaces/live.cloud-platform.service.justice.gov.uk/cfe-civil-production/resources/rds.tf
pipeline is broken due to minor version auto-upgrade
=> CFE PROD update RDS version to match what has been deployed

namespaces/live.cloud-platform.service.justice.gov.uk/cfe-civil-production/resources/rds.tf
broken pipeline doesnt like the size I am using, if t3.small isnt the suggested default is please let me know
=> CFE PROD update instance class

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-adjustments-dev/99-redirect_old_url_ingress.yaml
https://dsdmoj.atlassian.net/browse/ADJST-404
=> ADJST-404 Redirect Old ingress url

namespaces/live.cloud-platform.service.justice.gov.uk/workforce-management-preprod/resources/rds-restore-new.skip
=> delete new db

namespaces/live.cloud-platform.service.justice.gov.uk/dex-mi-production/resources/ses.tf
Create credentials and policy resources so we can use SMTP
=> Create credentials for SMTP in dex-mi-production

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-adjustments-preprod/resources/hmpps-audit-queue.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-adjustments-preprod/resources/irsa.tf
https://dsdmoj.atlassian.net/browse/ADJST-513
=> ADJST-513 Preprod Audit service secrets and sqs policies

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-adjustments-prod/resources/hmpps-audit-queue.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-adjustments-prod/resources/irsa.tf
https://dsdmoj.atlassian.net/browse/ADJST-513
=> ADJST-513 Audit service secrets and SQS policies for Prod environment

namespaces/live.cloud-platform.service.justice.gov.uk/dex-mi-production/resources/ses.tf
Accidentally referenced an incorrect custom domain
=> Fix domain reference in SES policy

namespaces/live.cloud-platform.service.justice.gov.uk/analytical-platform-production/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/analytical-platform-production/resources/iam-policies.tf, namespaces/live.cloud-platform.service.justice.gov.uk/analytical-platform-production/resources/iam-roles.tf, namespaces/live.cloud-platform.service.justice.gov.uk/analytical-platform-production/resources/locals.tf, namespaces/live.cloud-platform.service.justice.gov.uk/analytical-platform-production/resources/rds.tf, namespaces/live.cloud-platform.service.justice.gov.uk/analytical-platform-production/resources/route53.tf, namespaces/live.cloud-platform.service.justice.gov.uk/analytical-platform-production/resources/variables.tf
- Updates our Business Unit to Central Digital
- Adds IAM policy
- Adds IAM role
- Adds RDS instance
- Adds Route53 zone
=> ✨ Analytical Platform Production resources

namespaces/live.cloud-platform.service.justice.gov.uk/analytical-platform-production/resources/serviceacount.tf
=> 🤖 Add AP Prod SA

namespaces/live.cloud-platform.service.justice.gov.uk/analytical-platform-production/05-certificate.yaml
- Add TLS for `observability.analytical-platform.service.justice.gov.uk`
=> 🔒 Add certificate

namespaces/live.cloud-platform.service.justice.gov.uk/cfe-civil-production/resources/rds.tf
i added a read_replica and this made the pipeline go 💥 
https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/environments-live/jobs/apply-namespace-changes-live/builds/12198
this PR reverts those changes to allow me to add the read_replica in a separate PR as suggested here:
https://mojdt.slack.com/archives/C57UPMZLY/p1745347939582249?thread_ts=1745340377.162559&cid=C57UPMZLY
=> CFE RDS revert changes

namespaces/live.cloud-platform.service.justice.gov.uk/laa-manage-your-civil-cases-uat/resources/serviceaccount.tf
as discussed here https://mojdt.slack.com/archives/C57UPMZLY/p1745485946733469?thread_ts=1745444535.900689&cid=C57UPMZLY
this is to create env specific secrets rather than repo specific
=> MCC UAT add GH environment

namespaces/live.cloud-platform.service.justice.gov.uk/laa-manage-your-civil-cases-staging/resources/serviceaccount.tf
as discussed here https://mojdt.slack.com/archives/C57UPMZLY/p1745485946733469?thread_ts=1745444535.900689&cid=C57UPMZLY
this is to create env specific secrets rather than repo specific
=> MCC STG add GH environment

namespaces/live.cloud-platform.service.justice.gov.uk/cloud-platform-containers/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/cloud-platform-containers/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/cloud-platform-containers/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/cloud-platform-containers/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/cloud-platform-containers/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/cloud-platform-containers/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/cloud-platform-containers/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/cloud-platform-containers/resources/versions.tf
- Creates a namespace for `cloud-platform-containers` no k8s resources will be used. only using it to hook into terraform.
=> feat: add cloud-platform-containers namespace

namespaces/live.cloud-platform.service.justice.gov.uk/cloud-platform-containers/resources/ecr_delete_oldsnapshots.tf
- Adds a `delete-oldsnapshots` ecr repo
=> feat: add delete-oldsnapshots ecr

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-electronic-monitoring-crime-matching-dev/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-electronic-monitoring-crime-matching-dev/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-electronic-monitoring-crime-matching-dev/06-certificate.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-electronic-monitoring-crime-matching-dev/resources/hmpps-electronic-monitoring-crime-matching-api.tf
Adding certificate and terraform resource for hmpps-electronic-monitoring-crime-matching-api
=> Crime Matching API Terraform/Certificate

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-dev/05-prometheus.yaml
JIRA ticket - https://dsdmoj.atlassian.net/browse/CTSKF-1101
We want a new prometheus alert to pick up payment post errors from our metrics.
=> CTSKF-1101: Add Prometheus alert for post errors in ccr dev

namespaces/live.cloud-platform.service.justice.gov.uk/tariq-test/resources/rds-postgresql.tf
create postgresSQL 16.7 primary and replica RDS instance as first part of RDS upgrade verify ticket https://github.com/orgs/ministryofjustice/projects/65/views/3?pane=issue&itemId=95977166&issue=ministryofjustice%7Ccloud-platform%7C6759
=> create postgresSQL 16.7 primary and replica RDS instance

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-adjustments-dev/resources/rds.tf
Adjustments Dev DB upgrade to 16 complete.
=> Adjustments Dev upgrade to 16 is complete

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-adjustments-preprod/resources/rds.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-adjustments-preprod/resources/variables.tf
=> ADJST-1104 Upgrade Adjustments Preprod DB to 16

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-adjustments-preprod/resources/rds.tf
=> ADJST-1104 Adjustments DB upgrade to 16 for Preprod complete

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-identify-remand-periods-dev/resources/rds.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-identify-remand-periods-dev/resources/variables.tf
=> ADJST-1104 Identify Remand Dev DB to 16.8

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-identify-remand-periods-dev/resources/rds.tf
=> ADJST-1104 Identify Remand Period Dev DB to 16.8 upgrade complete

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-identify-remand-periods-preprod/resources/rds.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-identify-remand-periods-preprod/resources/variables.tf
=> ADJST-1104 Identify Remand Period Preprod DB upgrade to 16.8

namespaces/live.cloud-platform.service.justice.gov.uk/manage-intelligence-dev/resources/kendra.tf
- Update tagging for Kendra
- relates to https://github.com/ministryofjustice/cloud-platform/issues/6970
=> chore: Update tagging for Kendra

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-identify-remand-periods-preprod/resources/rds.tf
=> ADJST-1104 Identify Remand Period Preprod DB to 16.8 complete

namespaces/live.cloud-platform.service.justice.gov.uk/tariq-test/resources/rds-postgresql.tf
create RDS read replica in NS tariq-test
=> create read replica RDS instance in NS tariq-test

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-adjustments-dev/resources/rds.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-adjustments-dev/resources/variables.tf
=> ADJST-1104 Upgrade Adjustments Dev DB to 17.4

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-adjustments-preprod/resources/rds.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-adjustments-preprod/resources/variables.tf
=> ADJST-1104 Upgrade Adjustments Preprod DB to 17.4

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-adjustments-dev/resources/rds.tf
=> ADJST-1104 Adjustments Dev DB Upgrade to 17.4 Complete

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-adjustments-preprod/resources/rds.tf
=> ADJST-1104 Adjustments Preprod DB Upgrade to 17.4 Complete

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-identify-remand-periods-dev/resources/rds.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-identify-remand-periods-dev/resources/variables.tf
=> ADJST-1104 Identify Remand Periods Dev DB upgrade to 17.4

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-identify-remand-periods-preprod/resources/rds.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-identify-remand-periods-preprod/resources/variables.tf
=> ADJST-1104 Identify Remand Periods Preprod DB upgrade to 17.4

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-identify-remand-periods-dev/resources/rds.tf
=> ADJST-1104 Identify Remand Periods Dev DB upgrade to 17.4 complete

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-identify-remand-periods-preprod/resources/rds.tf
=> ADJST-1104 Identify Remand Periods Preprod DB upgrade to 17.4 complete

namespaces/live.cloud-platform.service.justice.gov.uk/tariq-test/resources/rds-postgresql.tf
Fix read replica build failure with storage increase
https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/environments-live/jobs/apply-namespace-changes-live/builds/12371
=> increase storage to 40

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-electronic-monitoring-datastore-dev/resources/kubernetes-secrets.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-electronic-monitoring-datastore-dev/resources/ssm.tf
Configure kubernetes secrets to dynamically update from SSM parameters.
=> hmpps-electronic-monitoring-datastore-dev: Dynamically update kubernetes secrets

namespaces/live.cloud-platform.service.justice.gov.uk/tariq-test/resources/rds-postgresql.tf
Increase max storage for Read Replica RDS instance
=> increase max storage

namespaces/live.cloud-platform.service.justice.gov.uk/tim-development/resources/sqs.tf
- Update sqs branch to add kms tag
=> chore: add kms tag

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-identify-remand-periods-prod/resources/rds.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-identify-remand-periods-prod/resources/variables.tf
=> ADJST-1104 Identify Remand Period Prod DB to 16.8

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-adjustments-prod/resources/rds.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-adjustments-prod/resources/variables.tf
=> ADJST-1104 Upgrade Adjustments Prod DB to 16.4

namespaces/live-2.cloud-platform.service.justice.gov.uk/monitoring/dashboard-datasource-sqs.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/monitoring/dashboard-datasource-sqs.yaml
[Link to Grafana](https://grafana.live.cloud-platform.service.justice.gov.uk/explore?schemaVersion=1&panes=%7B%22uq2%22:%7B%22datasource%22:%22P896B4444D3F0DAB8%22,%22queries%22:%5B%7B%22alias%22:%22%22,%22application%22:%7B%22filter%22:%22%22%7D,%22dimensions%22:%7B%22QueueName%22:%5B%22probation-integration-prod-prison-case-notes-to-probation-queue%22%5D%7D,%22functions%22:%5B%5D,%22group%22:%7B%22filter%22:%22%22%7D,%22host%22:%7B%22filter%22:%22%22%7D,%22item%22:%7B%22filter%22:%22%22%7D,%22metricName%22:%22NumberOfMessagesDeleted%22,%22mode%22:0,%22namespace%22:%22AWS%2FSQS%22,%22options%22:%7B%22showDisabledItems%22:false%7D,%22period%22:%22%22,%22refId%22:%22A%22,%22region%22:%22default%22,%22metricQueryType%22:0,%22metricEditorMode%22:0,%22statistic%22:%22Average%22,%22datasource%2 …
=> Update SQS dashboard to use Sum for Messages processed

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-identify-remand-periods-prod/resources/rds.tf
=> ADJST-1104 Identify Remand Period Prod DB to 16.8 Complete

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-adjustments-prod/resources/rds.tf
=> ADJST-1104 Upgrade Adjustments Prod DB to 16.4 - Complete

namespaces/live.cloud-platform.service.justice.gov.uk/laa-manage-your-civil-cases-uat/05-prometheus-custom-rules.yaml
Adds prometheus alert for MCC - UAT
=> Adds prometheus alert for MCC - UAT

namespaces/live.cloud-platform.service.justice.gov.uk/laa-manage-your-civil-cases-staging/05-prometheus-custom-rules.yaml
Adds prometheus alert for MCC - Staging
=> Adds prometheus alert for MCC - Staging

namespaces/live.cloud-platform.service.justice.gov.uk/laa-manage-your-civil-cases-production/05-prometheus-custom-rules.yaml
Adds prometheus alert for MCC- Prod
=> Adds prometheus alert for MCC- Prod

namespaces/live.cloud-platform.service.justice.gov.uk/tariq-test/resources/rds-postgresql.tf
RDS minor version upgrade from 16.7 to 16.8
=> minor version upgrade of read replica

namespaces/live.cloud-platform.service.justice.gov.uk/tariq-test/resources/rds-postgresql.tf
Second step of RDS minor upgrade - upgrade of Primary RDS instance from 16.7 to 16.8
=> minor version upgrade of primary instance

namespaces/live.cloud-platform.service.justice.gov.uk/tariq-test/resources/rds-postgresql.tf
Major RDS upgrade of Primary instance from 16.8 to 17.4
=> major version upgrade of primary instance to 17.4

namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-services-live-production/03-resourcequota.yaml
Increase pod limit to ensure service does not fail
=> Formbuilder services live production increase pods limit

namespaces/live.cloud-platform.service.justice.gov.uk/abundant-namespace-dev/resources/sns.tf, namespaces/live.cloud-platform.service.justice.gov.uk/cccd-dev-lgfs/resources/messaging.tf, namespaces/live.cloud-platform.service.justice.gov.uk/cccd-dev/resources/messaging.tf, namespaces/live.cloud-platform.service.justice.gov.uk/cccd-production/resources/messaging.tf, namespaces/live.cloud-platform.service.justice.gov.uk/cccd-staging/resources/messaging.tf, namespaces/live.cloud-platform.service.justice.gov.uk/cfocats-dev/resources/sns.tf, namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-dev/resources/court-cases-sns-topic.tf, namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-preprod/resources/court-cases-sns-topic.tf, namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-prod/resources/court-cases-sns-topic.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-events-dev/resources/hmpps-domain-events-topic.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-events-preprod/resources/hmpps-domain-events-topic.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-events-prod/resources/hmpps-domain-events-topic.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-dev/resources/event-topic.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-preprod/resources/event-topic.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-prod/resources/event-topic.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-person-record-dev/resources/court-topic.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-person-record-preprod/resources/court-topic.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-person-record-prod/resources/court-topic.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-criminal-applications-datastore-production/resources/sns-application-events.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-criminal-applications-datastore-staging/resources/sns-application-events.tf, namespaces/live.cloud-platform.service.justice.gov.uk/offender-events-dev/resources/topic.tf, namespaces/live.cloud-platform.service.justice.gov.uk/offender-events-preprod/resources/topic-perf.tf, namespaces/live.cloud-platform.service.justice.gov.uk/offender-events-preprod/resources/topic.tf, namespaces/live.cloud-platform.service.justice.gov.uk/offender-events-prod/resources/topic.tf, namespaces/live.cloud-platform.service.justice.gov.uk/sw-psa-audit-test/resources/sns.tf, namespaces/live.cloud-platform.service.justice.gov.uk/tim-development/resources/sns.tf
- bump SNS modules to add tagging to KMS resources
- relates to https://github.com/ministryofjustice/cloud-platform/issues/6965
=> chore: bump sns modules

namespaces/live.cloud-platform.service.justice.gov.uk/tariq-test/resources/rds-postgresql.tf
update tf code for read replica upgrade, so code is consistent for primary and read-replica
=> update tf code for read replica upgrade

namespaces/live.cloud-platform.service.justice.gov.uk/tariq-test/resources/rds-postgresql.tf
set prepare for upgrade to false after major upgrade and delete the SKIP file
=> set prepare upgrade to false and remove SKIP file

namespaces/live.cloud-platform.service.justice.gov.uk/migration-link-exchange-build-prod/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/migration-link-exchange-build-prod/resources/cross-namespace-role-sa.tf, namespaces/live.cloud-platform.service.justice.gov.uk/migration-link-exchange-build-prod/resources/service-account.tf, namespaces/live.cloud-platform.service.justice.gov.uk/migration-link-exchange-build-prod/resources/variables.tf
This PR depends on values set in https://github.com/ministryofjustice/cloud-platform-environments/pull/32598
=> migration-link-exchange-build-prod Update env, add GH sa and irsa

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-identify-remand-periods-prod/resources/rds.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-identify-remand-periods-prod/resources/variables.tf
=> ADJST-1104 Identify Remand Periods Prod DB to 17.4

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-adjustments-prod/resources/rds.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-adjustments-prod/resources/variables.tf
=> ADJST-1104 Adjustments Prod DB to 17.4 Upgrade

namespaces/live.cloud-platform.service.justice.gov.uk/laa-check-client-qualifies-uat/resources/serviceaccount.tf
Add networkpolicies.
Attempted fix for postgres bitnami chart deployment
=> el-1637: CCQ UAT Update CircleCI service account resource

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-identify-remand-periods-prod/resources/rds.tf
=> ADJST-1104 Identify Remand Periods Prod DB upgrade to 17 complete

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-adjustments-prod/resources/rds.tf
=> ADJST-1104 Adjustments Prod DB upgrade to 17 complete

namespaces/live.cloud-platform.service.justice.gov.uk/legal-framework-api-staging/resources/scheduled-downtime.tf
Add terraform file for scheduled downtime service account to legal framework api staging environment
=> Add scheduled downtime service account

namespaces/live.cloud-platform.service.justice.gov.uk/folarin-rds-namespace/resources/rds-postgresql.tf
Fixes https://concourse.cloud-platform.service.justice.gov.uk/builds/34102846
=> fix: set an appropriate db_name parameter for the replica

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-electronic-monitoring-crime-matching-dev/resources/cross-iam-role-sa.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-electronic-monitoring-crime-matching-dev/resources/iam-policies.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-electronic-monitoring-crime-matching-dev/resources/kubernetes-secrets.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-electronic-monitoring-crime-matching-dev/resources/ssm.tf
Adding athena/ssm config to allow assuming role for athena communication
=> Crime Matching API - Athena role usage via SSM

namespaces/live.cloud-platform.service.justice.gov.uk/migration-link-exchange-prod/resources/migration-link-exchange-api.tf, namespaces/live.cloud-platform.service.justice.gov.uk/migration-link-exchange-prod/resources/migration-link-exchange-ui.tf, namespaces/live.cloud-platform.service.justice.gov.uk/migration-link-exchange-prod/resources/rds-postgresql.tf, namespaces/live.cloud-platform.service.justice.gov.uk/migration-link-exchange-prod/resources/s3.tf
Hi @Thomas-Geraghty does this look ok to you?
=> `migration-link-exchange-prod` provision resources

namespaces/live.cloud-platform.service.justice.gov.uk/money-to-prisoners-prod/resources/rds.tf
- bump rds to match console version
=> chore: bump rds to match console version

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-personal-relationships-preprod/resources/rds-postgresql.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-personal-relationships-preprod/resources/variables.tf
PRC-612 : DPR access configurations - personal-relationships preprod
=> PRC-612 : DPR access configurations - personal-relationships preprod

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-organisations-prod/resources/rds-postgresql.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-organisations-prod/resources/variables.tf
PRC-612 : DPR access configurations - organisations production
=> PRC-612 : DPR access configurations - organisations production

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-organisations-preprod/resources/rds-postgresql.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-organisations-preprod/resources/variables.tf
PRC-612 : DPR access configurations - organisations preprod
=> PRC-612 : DPR access configurations - organisations preprod

namespaces/live.cloud-platform.service.justice.gov.uk/laa-review-criminal-legal-aid-staging/resources/irsa.tf
This change adds an IRSA module to `laa-review-criminal-legal-aid-staging`.
=> CRIMAPP-1679 Add IRSA to crime review staging

namespaces/live.cloud-platform.service.justice.gov.uk/cdn-production/resources/cloudfront.tf, namespaces/live.cloud-platform.service.justice.gov.uk/cdn-production/resources/iam-policy.tf, namespaces/live.cloud-platform.service.justice.gov.uk/cdn-production/resources/iam-role.tf
- Adds CloudFront distribution
- Adds IAM policy and role for accessing S3
=> ☁️ Add CloudFront and IAM resources

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-api-dev/resources/rds.tf
https://dsdmoj.atlassian.net/browse/NN-6057
Upgrading adjudication db from 15.8 to 16.8
=> postgres upgrade from 15.8 to 16.8

namespaces/live.cloud-platform.service.justice.gov.uk/cdn-production/resources/cloudfront.tf
- Adds secret for CloudFront URL 
=> ☁️ Create Kubernetes secret containing CloudFront data

.github/workflows/opa-tests.yml, policy/clusterrole.rego, policy/clusterrole_test.rego, policy/clusterrolebinding.rego, policy/clusterrolebinding_test.rego, policy/namespace.rego, policy/namespace_test.rego, policy/rolebinding.rego, policy/rolebinding_test.rego, policy/serviceaccount.rego, policy/serviceaccount_test.rego, policy/utils.rego
Both conftest and OPA are running on `> v1` opa engine. These changes should resolve action errors.
=> chore: 🤖 adding rego.v1 import statement for ns checker

.github/workflows/conftest-k8s-yaml.yaml
relates to ministryofjustice/cloud-platform#7167
=> chore: 🤖 pinning conftest to pre v1 breaking change release

.github/workflows/conftest-k8s-yaml.yaml, .github/workflows/opa-tests.yml, namespaces/live.cloud-platform.service.justice.gov.uk/sw-cp-testing/00-namespace.yaml, policy/clusterrole.rego, policy/clusterrole_test.rego, policy/clusterrolebinding.rego, policy/clusterrolebinding_test.rego, policy/namespace.rego, policy/namespace_test.rego, policy/rolebinding.rego, policy/rolebinding_test.rego, policy/serviceaccount.rego, policy/serviceaccount_test.rego, policy/utils.rego
relates to ministryofjustice/cloud-platform#7167
=> chore: 🤖 policy syntax changes, use pre v1 rego in actions

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-api-dev/resources/rds.tf
https://dsdmoj.atlassian.net/browse/NN-6057
=> Updating db from 16.8 to 17.4

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-api-dev/resources/rds.tf
https://dsdmoj.atlassian.net/browse/NN-6057
Removed APPLY_PIPELINE_SKIP_THIS_NAMESPACE and turned off prepare_for_major_upgrade after update to 17.4
=> removed APPLY_PIPELINE_SKIP_THIS_NAMESPACE

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-document-management-dev/resources/serviceaccount-github.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-document-management-dev/resources/versions.tf
https://dsdmoj.atlassian.net/browse/DOC-72
Moving from CircleCI to GHA
=> DOC-74 Create Secrets for GitHubActions - Dev

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-document-management-preprod/resources/serviceaccount-github.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-document-management-preprod/resources/versions.tf
https://dsdmoj.atlassian.net/browse/DOC-72
=> DOC-72 Create secrets for GithubActions - Preprod

namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-prod/resources/rds.tf
VB-5327 - Update DB version to 16.8 on visit_allocation_rds instance on visit-someone-in-prison-backend-svc-prod namespace
=> VB-5327 - Update DB version to 16.8 on visit_allocation_rds - PROD

namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-prod/resources/rds.tf
Update DB version to 17.4 on visit_allocation_rds instance on visit-someone-in-prison-backend-svc-prod namespace
=> VB-5327 - Update DB version to 17.4 - Prod

namespaces/live.cloud-platform.service.justice.gov.uk/certificated-bailiffs-dev/resources/apex-rds-oracle.tf, namespaces/live.cloud-platform.service.justice.gov.uk/certificated-bailiffs-dev/resources/apex-s3.tf
Spinning up a new db instance for oracle apex and increased permissions to delete old data pump files in bucket
=> Rst 7307: spinning new apex oracle db

.checksum, namespaces/live.cloud-platform.service.justice.gov.uk/emma-ns-test/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/emma-ns-test/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/emma-ns-test/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/emma-ns-test/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/emma-ns-test/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/emma-ns-test/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/emma-ns-test/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/emma-ns-test/resources/versions.tf
create test prod namespace to delete for testing slack alert
=> My new namespace

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-test/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-test/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-test/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-test/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-test/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-test/06-certificates.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-test/07-rbac-haar-client-admin-team.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-test/resources/elasticache.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-test/resources/hmpps-manage-adjudications.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-test/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-test/resources/serviceaccount-circleci.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-test/resources/servicepod.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-test/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-test/resources/versions.tf
Add test environment for Adjudications UI
=> NN-6087 - Test Environment for Adjudications UI

namespaces/live.cloud-platform.service.justice.gov.uk/offender-management-staging/resources/rds.tf
Ticket: https://dsdmoj.atlassian.net/browse/MO-1689
Preparation to delete `hmpps-manage-pom-cases-dev` namespace.
=> MO-1689 Delete injected RDS secret

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-api-test/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-api-test/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-api-test/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-api-test/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-api-test/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-api-test/06-rbac-haar-client-admin-team.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-api-test/07-certificate.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-api-test/resources/hmpps-events.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-api-test/resources/hmpps-manage-adjudications-api.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-api-test/resources/irsa.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-api-test/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-api-test/resources/s3.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-api-test/resources/serviceaccount-circleci.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-api-test/resources/sqs.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-api-test/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-api-test/resources/versions.tf
Add test environment for Adjudications API
=> NN-6088 - Test Environment for Adjudications API

namespaces/live.cloud-platform.service.justice.gov.uk/offender-management-preprod/resources/scheduled-downtime.tf
Ticket: https://dsdmoj.atlassian.net/browse/MO-1696
=> MO-1696 Add scheduled downtime SA - MPC preprod

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-custody-mailbox-register-dev/resources/scheduled-downtime.tf
Ticket: https://dsdmoj.atlassian.net/browse/MO-1696
=> MO-1696 Add scheduled downtime SA - MR dev

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-custody-mailbox-register-preprod/resources/scheduled-downtime.tf
Ticket: https://dsdmoj.atlassian.net/browse/MO-1696
=> MO-1696 Add scheduled downtime SA - MR preprod

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-preprod/01-rbac.yaml
=> HEAT-628 - Change GitHub Team - Preprod

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-test/01-rbac.yaml
=> HEAT-628 - Change GitHub Team - Test

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-prod/01-rbac.yaml
=> HEAT-628 - Change GitHub Team - Prod

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-api-preprod/01-rbac.yaml
=> HEAT-628 - Change GitHub Team - API Preprod

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-complexity-of-need-staging/resources/serviceaccount-github.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-complexity-of-need-staging/resources/versions.tf
Ticket: https://dsdmoj.atlassian.net/browse/MO-1693
=> MO-1693 Add github service account to CNL staging

namespaces/live.cloud-platform.service.justice.gov.uk/bold-rr-ops-pilot-prototype/resources/ecr.tf
Remove deletion protection to let us delete the prototype (#33165)
=> Disable deletion protection for BOLD ops prototype

namespaces/live.cloud-platform.service.justice.gov.uk/laa-fee-calculator-ui-dev/resources/ecr.tf
Removes deletion protection on the fee-calculator-ui dev ecr
=> Removes deletion protection on dev

namespaces/live.cloud-platform.service.justice.gov.uk/laa-information-exchange-test/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-information-exchange-test/resources/variables.tf
- Fix reference to old Slack channel that no longer exists.
=> Update Slack Channel in Information Exchange Test Namespace

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-auth/resources/cognito-orchestration-clients.tf
=> LASB-4050-rotate key

.checksum, namespaces/live.cloud-platform.service.justice.gov.uk/laa-benefit-checker-dev/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-benefit-checker-dev/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-benefit-checker-dev/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-benefit-checker-dev/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-benefit-checker-dev/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-benefit-checker-dev/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-benefit-checker-dev/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-benefit-checker-dev/resources/versions.tf
This PR creates the
`laa-benefit-checker-dev` namespace
---
Other PRs for 
- laa-benefit-checker-test
- laa-benefit-checker-uat
- laa-benefit-checker-prod
will follow.
=> Create new laa-benefit-checker-dev namespace

.checksum, namespaces/live.cloud-platform.service.justice.gov.uk/laa-benefit-checker-test/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-benefit-checker-test/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-benefit-checker-test/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-benefit-checker-test/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-benefit-checker-test/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-benefit-checker-test/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-benefit-checker-test/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-benefit-checker-test/resources/versions.tf
Create new `laa-benefit-checker-test` namespace
=> Create new laa-benefit-checker-test namespace

.checksum, namespaces/live.cloud-platform.service.justice.gov.uk/laa-benefit-checker-uat/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-benefit-checker-uat/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-benefit-checker-uat/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-benefit-checker-uat/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-benefit-checker-uat/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-benefit-checker-uat/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-benefit-checker-uat/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-benefit-checker-uat/resources/versions.tf
Create new laa-benefit-checker-uat namespace
=> Create new laa-benefit-checker-uat namespace

.checksum, namespaces/live.cloud-platform.service.justice.gov.uk/laa-benefit-checker-prod/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-benefit-checker-prod/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-benefit-checker-prod/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-benefit-checker-prod/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-benefit-checker-prod/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-benefit-checker-prod/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-benefit-checker-prod/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-benefit-checker-prod/resources/versions.tf
Create new laa-benefit-checker-prod namespace
=> Create new laa-benefit-checker-prod namespace

namespaces/live.cloud-platform.service.justice.gov.uk/laa-information-exchange-development/resources/secrets.tf
=> InfoX - Adding secrets for Client Ids.

.checksum, namespaces/live.cloud-platform.service.justice.gov.uk/laa-cwa-bulk-upload-dev/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-cwa-bulk-upload-dev/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-cwa-bulk-upload-dev/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-cwa-bulk-upload-dev/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-cwa-bulk-upload-dev/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-cwa-bulk-upload-dev/resources/ecr.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-cwa-bulk-upload-dev/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-cwa-bulk-upload-dev/resources/serviceaccount.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-cwa-bulk-upload-dev/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-cwa-bulk-upload-dev/resources/versions.tf
Changes made:
Created a new cloud platform environment for - laa-cwa-bulk-upload-dev
=> Created namespace laa-cwa-bulk-upload-dev

namespaces/live.cloud-platform.service.justice.gov.uk/laa-information-exchange-preproduction/resources/secrets.tf
=> InfoX - Adding secrets for Client Ids - Preprod

namespaces/live.cloud-platform.service.justice.gov.uk/laa-information-exchange-production/resources/secrets.tf
=> InfoX - Adding secrets for Client Ids - Prod

namespaces/live.cloud-platform.service.justice.gov.uk/laa-not-on-libra-auto-search-application-tst/resources/secret.tf
=> NoLASA InfoX Client - Test

namespaces/live.cloud-platform.service.justice.gov.uk/laa-not-on-libra-auto-search-application-preprod/resources/secret.tf
=> NoLASA InfoX Client - PreProd

namespaces/live.cloud-platform.service.justice.gov.uk/laa-not-on-libra-auto-search-application-dev/resources/secret.tf
=> NoLASA InfoX Client - Dev

namespaces/live.cloud-platform.service.justice.gov.uk/laa-not-on-libra-auto-search-application-prd/resources/secret.tf
=> NoLASA InfoX Client - Prod

namespaces/live.cloud-platform.service.justice.gov.uk/laa-information-exchange-test/resources/secrets.tf
=> InfoX - Adding secrets for Client Ids - Test

namespaces/live.cloud-platform.service.justice.gov.uk/lcjbexplorer-dev/resources/ecr.tf
removing deletion protection from lcjb app
=> remove deletion protection

namespaces/live.cloud-platform.service.justice.gov.uk/laa-benefit-checker-uat/resources/ecr.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-benefit-checker-uat/resources/serviceaccount.tf
Add ECR to namespace laa-benefit-checker-uat.
=> Add ECR to laa-benefit-checker-uat

namespaces/live.cloud-platform.service.justice.gov.uk/psr-ai-design-prototype/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/psr-ai-design-prototype/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/psr-ai-design-prototype/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/psr-ai-design-prototype/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/psr-ai-design-prototype/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/psr-ai-design-prototype/resources/basic-auth.tf, namespaces/live.cloud-platform.service.justice.gov.uk/psr-ai-design-prototype/resources/ecr.tf, namespaces/live.cloud-platform.service.justice.gov.uk/psr-ai-design-prototype/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/psr-ai-design-prototype/resources/serviceaccount.tf, namespaces/live.cloud-platform.service.justice.gov.uk/psr-ai-design-prototype/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/psr-ai-design-prototype/resources/versions.tf
Generated via `cloud-platform environment prototype create`
=> Add psr-ai-design-prototype infrastructure

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-find-and-refer-an-intervention-prod/resources/isra.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-find-and-refer-an-intervention-prod/resources/variables.tf
Added audit queue and service account for prod namespace
=> Added audit queue and service account

namespaces/live.cloud-platform.service.justice.gov.uk/cvl-improvements-prototype/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/cvl-improvements-prototype/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/cvl-improvements-prototype/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/cvl-improvements-prototype/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/cvl-improvements-prototype/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/cvl-improvements-prototype/resources/basic-auth.tf, namespaces/live.cloud-platform.service.justice.gov.uk/cvl-improvements-prototype/resources/ecr.tf, namespaces/live.cloud-platform.service.justice.gov.uk/cvl-improvements-prototype/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/cvl-improvements-prototype/resources/serviceaccount.tf, namespaces/live.cloud-platform.service.justice.gov.uk/cvl-improvements-prototype/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/cvl-improvements-prototype/resources/versions.tf
Raising a pull request to set up new prototype link
=> set up cvl improvements 

namespaces/live.cloud-platform.service.justice.gov.uk/cfe-civil-production/00-namespace.yaml
- If applied, this updates the team e-mail
=> EL-2271: Team email CFE Production 

namespaces/live.cloud-platform.service.justice.gov.uk/cfe-civil-uat/00-namespace.yaml
=> EL-2271: Team email CFE UAT

namespaces/live.cloud-platform.service.justice.gov.uk/cfe-civil-staging/00-namespace.yaml
=> EL-2271: Team email CFE Staging

namespaces/live.cloud-platform.service.justice.gov.uk/cfe-civil-staging-mtr/00-namespace.yaml
=> EL-2271: Team email CFE Staging MTR

namespaces/live.cloud-platform.service.justice.gov.uk/laa-check-client-qualifies-production/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-check-client-qualifies-production/resources/variables.tf
=> EL-2271: Team email CCQ Production

namespaces/live.cloud-platform.service.justice.gov.uk/laa-check-client-qualifies-staging/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-check-client-qualifies-staging/resources/variables.tf
=> EL-2271: Team email CCQ Staging

namespaces/live.cloud-platform.service.justice.gov.uk/laa-check-client-qualifies-uat/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-check-client-qualifies-uat/resources/variables.tf
=> EL-2271: Team email CCQ UAT

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-contribution-prod/05-prometheus-rules.yaml
Added prometheus alerts in the laa-crown-court-contribution-prod namespace for:
- Instance-Down
- Quota-Exceeded
- KubePodCrashLooping
=> Add additional prometheus rules to laa-crown-court-contribution-prod

.github/workflows/terraform-tools.yml
scope down the diff to include only PR relevant changes
validate tf files for linting
=> Tflint update

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-sentence-plan-test/06-github-actions-runner.yaml
Needed to change the URL value of the repo to reflect the naming change to remove "poc".
=> updated repo url value to reflect project name change

namespaces/live.cloud-platform.service.justice.gov.uk/laa-assess-crime-forms-dev/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-assess-crime-forms-dev/resources/variables.tf
update email to nscc@digital.gov.uk 
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2593)
=> CRM457-2593 update nscc email

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-applications-adaptor-dev/resources/cognito.tf
Change for rotate secret for dev
=> LSAB-4050-rotate keys

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-applications-adaptor-test/resources/cognito.tf
Change for rotate secret for test
=> LASB-4050-rotate test key

namespaces/live.cloud-platform.service.justice.gov.uk/calculate-release-dates-prototype/resources/secrets.tf, namespaces/live.cloud-platform.service.justice.gov.uk/calculate-release-dates-prototype/resources/variables.tf
Add secret for chatbot API key.
=> crs-2365-add-crds-prototype-secret

.checksum, namespaces/live.cloud-platform.service.justice.gov.uk/laa-cwa-bulk-upload-prod/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-cwa-bulk-upload-prod/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-cwa-bulk-upload-prod/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-cwa-bulk-upload-prod/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-cwa-bulk-upload-prod/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-cwa-bulk-upload-prod/resources/ecr.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-cwa-bulk-upload-prod/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-cwa-bulk-upload-prod/resources/secret.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-cwa-bulk-upload-prod/resources/serviceaccount.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-cwa-bulk-upload-prod/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-cwa-bulk-upload-prod/resources/versions.tf
Created a new cloud platform environment for - laa-cwa-bulk-upload-prod
=> Created namespace laa-cwa-bulk-upload-prod

namespaces/live.cloud-platform.service.justice.gov.uk/abundant-namespace-dev/resources/dynamodb.tf, namespaces/live.cloud-platform.service.justice.gov.uk/cjse-dev/resources/dynamodb.tf, namespaces/live.cloud-platform.service.justice.gov.uk/cloud-platform-reports-prod/resources/dynamodb.tf, namespaces/live.cloud-platform.service.justice.gov.uk/fraud-and-corruption-insights-dev/resources/dynamodb.tf, namespaces/live.cloud-platform.service.justice.gov.uk/fraud-and-corruption-insights-prod/resources/dynamodb.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-mercury-submit-dev/resources/dynamodb.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-mercury-submit-preprod/resources/dynamodb.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-mercury-submit-prod/resources/dynamodb.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-mercury-submit-test/resources/dynamodb.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-sds-dev/resources/dynamodb.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-sds-production/resources/dynamodb.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-sds-stg/resources/dynamodb.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-sds-test/resources/dynamodb.tf
- Bumps dynamodb module for multiple namespaces
- Should only affect tags so doing it in one go
=> chore: bump dynamodb module to 4.1.0

namespaces/live.cloud-platform.service.justice.gov.uk/laa-hmrc-interface-uat/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-hmrc-interface-uat/resources/variables.tf
HMRC Interface: change email address (UAT)
=> HMRC Interface: change email address (UAT)

namespaces/live.cloud-platform.service.justice.gov.uk/laa-hmrc-interface-production/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-hmrc-interface-production/resources/variables.tf
HMRC Interface: change email address (Production)
=> HMRC Interface: change email address (Production)

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-demo/01-rbac.yaml
adds `hmpps-community-accommodation-devs` to demo namespace.
=> CAS-1681: Add Dev github team to demo namespace.

namespaces/live.cloud-platform.service.justice.gov.uk/laa-assure-hmrc-data-uat/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-assure-hmrc-data-uat/resources/variables.tf
Assure: change email address (UAT)
=> Assure: change email address (UAT)

namespaces/live.cloud-platform.service.justice.gov.uk/laa-assure-hmrc-data-staging/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-assure-hmrc-data-staging/resources/variables.tf
Assure: change email address (Staging)
=> Assure: change email address (Staging)

namespaces/live.cloud-platform.service.justice.gov.uk/offender-management-staging/resources/service-pod.tf, namespaces/live.cloud-platform.service.justice.gov.uk/offender-management-staging/resources/serviceaccount-github.tf, namespaces/live.cloud-platform.service.justice.gov.uk/offender-management-staging/resources/versions.tf
Ticket: https://dsdmoj.atlassian.net/browse/MO-1698
Also, removing no longer needed service pod.
=> MO-1698 Add github service account to MPC staging

namespaces/live.cloud-platform.service.justice.gov.uk/offender-management-preprod/resources/serviceaccount-github.tf, namespaces/live.cloud-platform.service.justice.gov.uk/offender-management-preprod/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/offender-management-preprod/resources/versions.tf
Ticket: https://dsdmoj.atlassian.net/browse/MO-1698
=> MO-1698 Add github service account to MPC preprod

namespaces/live.cloud-platform.service.justice.gov.uk/laa-cwa-bulk-upload-dev/resources/serviceaccount.tf
- Added dev github_environments setting for service account resource.
=> Set up dev env service account

namespaces/live.cloud-platform.service.justice.gov.uk/laa-holding-page-production/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-holding-page-production/resources/variables.tf
LAA holding page: change email address (Production)
=> LAA holding page: change email address (Production)

namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-uat/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-uat/resources/s3.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-uat/resources/variables.tf
Civil Apply: change email address (UAT)
=> Civil Apply: change email address (UAT)

namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-staging/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-staging/resources/elasticache.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-staging/resources/rds.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-staging/resources/s3.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-staging/resources/variables.tf
Civil Apply: change email address (Staging)
=> Civil Apply: change email address (Staging)

namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-production/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-production/resources/elasticache.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-production/resources/rds.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-production/resources/route53.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-production/resources/s3.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-production/resources/variables.tf
Civil Apply: change email address (Production)
=> Civil Apply: change email address (Production)

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-dev/resources/hmpps-approved-premises-api.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-dev/resources/hmpps-approved-premises-ui.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-dev/resources/hmpps-community-accommodation-tier-2-bail-ui.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-dev/resources/hmpps-community-accommodation-tier-2-ui.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-dev/resources/hmpps-temporary-accommodation-ui.tf
this is needed to include dev reviewers to dev deployments
=> update to add cas devs group to the github reviewers list

namespaces/live.cloud-platform.service.justice.gov.uk/offender-categorisation-dev/resources/elasticache.tf
Rotate dev elasticache redis token for cat tool dev
=> cat-tool-dev-rotate-redis-token

namespaces/live.cloud-platform.service.justice.gov.uk/laa-data-stewardship-access-dev/resources/ecr.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-data-stewardship-access-dev/resources/serviceaccount.tf
amended tf files for correct github repo
=> added correct github repo

namespaces/live.cloud-platform.service.justice.gov.uk/mbpr-test/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/mbpr-test/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/mbpr-test/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/mbpr-test/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/mbpr-test/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/mbpr-test/resources/cross-iam-role-sa.tf, namespaces/live.cloud-platform.service.justice.gov.uk/mbpr-test/resources/ecr.tf, namespaces/live.cloud-platform.service.justice.gov.uk/mbpr-test/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/mbpr-test/resources/serviceaccount.tf, namespaces/live.cloud-platform.service.justice.gov.uk/mbpr-test/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/mbpr-test/resources/versions.tf
Creates new namespace `mbpr-test`
- adds service account add ecr
- adds cross role iam
=> Add new namespace/mbpr test

namespaces/live.cloud-platform.service.justice.gov.uk/laa-cwa-submissions-api-mpdev/resources/ecr.tf
Dummy change in comment in file ecr.tf
=> Dummy change in comment

namespaces/live.cloud-platform.service.justice.gov.uk/cica-copilot-dev/resources/ecr.tf
Removing deletion protection from the ECR module
=> Add deletion_protection = false to ECR module

namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-production/resources/serviceaccount-circleci.tf
Add permissions for clamav deployment [Civil apply production]
Configmaps and pvcs required for Clamav deployment
=> Add permissions for clamav deployment [Civil apply production]

namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-uat/resources/variables.tf
Add service account permissions to civil apply uat
=> AP-6061: Add service account permissions

namespaces/live.cloud-platform.service.justice.gov.uk/mbpr-dev/resources/ecr.tf, namespaces/live.cloud-platform.service.justice.gov.uk/mbpr-dev/resources/variables.tf
use ecr module to separate secrets and variables
=> separate envs with ecr module

namespaces/live.cloud-platform.service.justice.gov.uk/create-and-vary-a-licence-api-dev/resources/rds.tf
=> CVSL-2942 Update DB version In Dev

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-electronic-monitoring-data-insights-dev/resources/ui-elasticache.tf
=> EPT-199: rename  redis env

namespaces/live.cloud-platform.service.justice.gov.uk/mbpr-prod/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/mbpr-prod/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/mbpr-prod/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/mbpr-prod/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/mbpr-prod/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/mbpr-prod/resources/cross-iam-role-sa.tf, namespaces/live.cloud-platform.service.justice.gov.uk/mbpr-prod/resources/ecr.tf, namespaces/live.cloud-platform.service.justice.gov.uk/mbpr-prod/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/mbpr-prod/resources/serviceaccount.tf, namespaces/live.cloud-platform.service.justice.gov.uk/mbpr-prod/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/mbpr-prod/resources/versions.tf
Added namespace for `mbpr-prod`
- added ecr to use github environment for secret/env-var storage
- added service account to use github environment for secret/env-var storage
- added cross iam role sa
=> add namespace mbpr-prod

namespaces/live.cloud-platform.service.justice.gov.uk/care-arrangement-plan-prod/resources/route53.tf, namespaces/live.cloud-platform.service.justice.gov.uk/care-arrangement-plan-prod/resources/variables.tf
=> Create hosted zone

namespaces/live.cloud-platform.service.justice.gov.uk/mbpr-dev/resources/cross-iam-role-sa.tf
aligning the assume role to a role created on analytical platform (for app data access).
=> update arn for ap assume role

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-challenge-support-intervention-plan-dev/01-rbac.yaml
=> LMS-70 - Add Live support team to CSIP - Dev

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-production/resources/outputs-to-ssm-parameters.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-staging/resources/outputs-to-ssm-parameters.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-education-and-work-plan-dev/resources/ssm.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-education-and-work-plan-preprod/resources/ssm.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-education-and-work-plan-prod/resources/ssm.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-locations-inside-prison-dev/resources/ssm.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-locations-inside-prison-preprod/resources/ssm.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-locations-inside-prison-prod/resources/ssm.tf, namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-dev/resources/ssm.tf, namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-preprod/resources/ssm.tf, namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-prod/resources/ssm.tf, namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-staging/resources/ssm.tf
=> chore: update ssm tag

.checksum, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-esupervision-dev/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-esupervision-dev/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-esupervision-dev/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-esupervision-dev/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-esupervision-dev/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-esupervision-dev/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-esupervision-dev/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-esupervision-dev/resources/versions.tf
Create development namespace for hmpps-esupervision application
=> Create development namespace for hmpps-esupervision application

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-electronic-monitoring-data-insights-dev/07-rbac-haar-client-admin-team.yaml
=> EPT-199: added client admin yaml

namespaces/live.cloud-platform.service.justice.gov.uk/laa-cwa-submissions-api-test/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-cwa-submissions-api-test/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-cwa-submissions-api-test/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-cwa-submissions-api-test/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-cwa-submissions-api-test/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-cwa-submissions-api-test/resources/ecr.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-cwa-submissions-api-test/resources/irsa.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-cwa-submissions-api-test/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-cwa-submissions-api-test/resources/s3.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-cwa-submissions-api-test/resources/serviceaccount.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-cwa-submissions-api-test/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-cwa-submissions-api-test/resources/versions.tf
Setting up CWA Submissions API namespace for test
=> Initial files for test  namespace

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-esupervision-dev/resources/ecr.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-esupervision-dev/resources/serviceaccount.tf
Create container registry and configure secrets in the esupervision API and UI repositories for accessing the cluster.
=> Hmpps esupervision registry

namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-ui-dev/resources/rds.tf
I have checked the [documentation](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_UpgradeDBInstance.PostgreSQL.MajorVersion.html) and 17.4 is an upgrade target for 14.17.
=> ACD-499 (VCD dev): Upgrade DB version

namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-prod/resources/route53-finucane.tf
Changes to DNS records of finucane.independent-inquiry.uk
* Add MX records
* Add DMARC, DKIM and SPF records
=> Hale Platform prod DNS update Finucane site

.github/workflows/pr-stale.yaml
update stale out time to 60 days
=> update staler time to 60 days

namespaces/live.cloud-platform.service.justice.gov.uk/create-and-vary-a-licence-api-preprod/resources/rds.tf
updating minor db version to 5.13
=> CVSL-2942 Update DB version to 5.13 In PreProd

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-and-deliver-accredited-programmes-dev/resources/api.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-and-deliver-accredited-programmes-dev/resources/serviceaccount-github.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-and-deliver-accredited-programmes-dev/resources/serviceaccount.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-and-deliver-accredited-programmes-dev/resources/ui.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-and-deliver-accredited-programmes-dev/resources/versions.tf
- Added API kotlin template module
- Added  UI typescript template module
- Added github service account
=> [APG-960] Add Terraform resources for manage-and-deliver-accredited-programmes (DEV)

.github/workflows/pr-stale.yaml
- Update the stale message to be a bit clearer
=> chore: update stale message

namespaces/live.cloud-platform.service.justice.gov.uk/create-and-vary-a-licence-api-preprod/resources/rds.tf
=> CVSL-2942 Update DB version major 17.5 PreProd tidy up task

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-activities-management-dev/resources/rds.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-interventions-dev/resources/rds-postgres14.tf
- bump rds version to match aws console version
=> chore: bump rds version to match console

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-incident-reporting-dev/resources/application-insights.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-incident-reporting-dev/resources/github.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-incident-reporting-dev/resources/serviceaccounts.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-incident-reporting-dev/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-incident-reporting-dev/resources/versions.tf
=> hmpps-incident-reporting-dev: Set up for GH Actions

.checksum, namespaces/live.cloud-platform.service.justice.gov.uk/stg-tmc-example/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/stg-tmc-example/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/stg-tmc-example/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/stg-tmc-example/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/stg-tmc-example/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/stg-tmc-example/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/stg-tmc-example/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/stg-tmc-example/resources/versions.tf
Running thru the tutorial to create the namespace
=> Adding namepsace stg-tmc-example

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-dps-reconciliation-prod/resources/rds.tf
Clear flag bringing db down overnight
=> SDIT-2692 Create reconciliation process between release and receive events and Nomis movements

namespaces/live.cloud-platform.service.justice.gov.uk/laa-information-exchange-production/05-prometheusrules.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-information-exchange-production/resources/secrets.tf
This PR introduces two key infrastructure changes to improve security and observability:
- Secret Cleanup
- Removed the unused `laa-infox-mtls-certs` secret from the Terraform configuration to reduce unnecessary exposure and align with current usage.
- Production Alerting
- Added a new `prometheusrules.yaml` file to define alerting rules for the production environment.
- Enables proactive monitoring of key metrics and supports early detection of potential issues.
These changes help streamline our infrastructure and improve operational visibility in production.
=> Update Information-Exchange-Production Configuration

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-live-support/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-live-support/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-live-support/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-live-support/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-live-support/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-live-support/06-certificates.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-live-support/07-rbac-haar-client-admin-team.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-live-support/resources/elasticache.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-live-support/resources/hmpps-manage-adjudications.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-live-support/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-live-support/resources/serviceaccount-circleci.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-live-support/resources/servicepod.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-live-support/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-live-support/resources/versions.tf
Add adjudications-live-support namespace
This new environment will be used to deploy a live support version of PreProd code
=> LSM-19 - Create adjudications-live-support-ui namespace

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-evidence-dev/resources/secret.tf
This PR adds a new secret for the IP allowlist for the dev Evidence Service.
=> Add IP allowlist secret for dev Evidence Service

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-dps-reconciliation-prod/resources/reconciliation-queue.tf
Make queue messages short-lived and include merge messages in filter
=> SDIT-2692 Create reconciliation process between release and receive events and Nomis movements prod

namespaces/live.cloud-platform.service.justice.gov.uk/certificated-bailiffs-dev/resources/apex-rds-oracle.tf, namespaces/live.cloud-platform.service.justice.gov.uk/certificated-bailiffs-preprod/resources/apex-rds-oracle.tf
Fixing mandatory tags as a part of mandatory tagging work - https://github.com/ministryofjustice/cloud-platform/issues/6972
Tags changed from having _ in them to - to match mandatory tagging policy
=> Fixing mandatory tag names from _ to -

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-find-and-refer-an-intervention-prod/resources/domain-events-topic.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-find-and-refer-an-intervention-prod/resources/isra.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-find-and-refer-an-intervention-prod/resources/sqs-domain-events.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-find-and-refer-an-intervention-prod/resources/sqs-policy.tf
This PR adds SQS secrets and resources into prod environment for Find and Refer
=> Add SQS resources and secrets for Find and Refer prod

namespaces/live.cloud-platform.service.justice.gov.uk/civil-appeal-case-tracker-preprod/resources/opeansearch.tf
reset query to json generated in OpenSearch Inspect
=> Amend index to live_kubernetes_ingress

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-litigator-fees-dev/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-litigator-fees-dev/05-prometheus.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-litigator-fees-dev/06-servicemonitor.yaml
Porting changes made for alerting to our dev environment.
=> Port cclf dev alerts to dev

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-litigator-fees-staging/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-litigator-fees-staging/05-prometheus.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-litigator-fees-staging/06-servicemonitor.yaml
Porting changes made for alerting to our staging environment.
=> Port cclf dev alerts to staging

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-litigator-fees-uat/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-litigator-fees-uat/05-prometheus.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-litigator-fees-uat/06-servicemonitor.yaml
Porting changes made for alerting to our uat environment.
=> Port cclf dev alerts to uat

.checksum, namespaces/live.cloud-platform.service.justice.gov.uk/decide-beta-dev/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/decide-beta-dev/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/decide-beta-dev/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/decide-beta-dev/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/decide-beta-dev/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/decide-beta-dev/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/decide-beta-dev/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/decide-beta-dev/resources/versions.tf
Creating initial experimental environment for Civil Decide
=> Create namespace for Civil Decide Beta

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-adjustments-dev/resources/hmpps-adjustments-github.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-adjustments-dev/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-adjustments-dev/resources/versions.tf
https://dsdmoj.atlassian.net/browse/ADJST-1260
https://dsdmoj.atlassian.net/browse/ADJST-1261
=> ADJST-1260 and ADJST-1261 Create secrets for Hmpps-adjustments and Hmpps-adjustments-api

namespaces/live.cloud-platform.service.justice.gov.uk/certificated-bailiffs-prod/resources/apex-rds-oracle.tf, namespaces/live.cloud-platform.service.justice.gov.uk/certificated-bailiffs-prod/resources/apex-s3-role.tf
Temporarily removing the database
=> Removing oracle apex database and assosiated roles temporarily

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-adjustments-prod/resources/hmpps-adjustments-github.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-adjustments-prod/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-adjustments-prod/resources/versions.tf
https://dsdmoj.atlassian.net/browse/ADJST-1260
=> Adjst 1260 prod

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-adjustments-preprod/resources/variables.tf
https://dsdmoj.atlassian.net/browse/ADJST-1260
=> ADJST-1260 Migrate to the correct team

namespaces/live.cloud-platform.service.justice.gov.uk/laa-manage-your-civil-cases-production/resources/pingdom.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-manage-your-civil-cases-production/resources/versions.tf
- If applied, this adds a pingdom integration for the MCC Production namespace. 
- It has a placeholder slack Integration ID.
=> EL-2286: MCC Pingdom: Production

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-electronic-monitoring-data-insights-preprod/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-electronic-monitoring-data-insights-preprod/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-electronic-monitoring-data-insights-preprod/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-electronic-monitoring-data-insights-preprod/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-electronic-monitoring-data-insights-preprod/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-electronic-monitoring-data-insights-preprod/06-certificate.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-electronic-monitoring-data-insights-preprod/07-rbac-haar-client-admin-team.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-electronic-monitoring-data-insights-preprod/resources/appinsights.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-electronic-monitoring-data-insights-preprod/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-electronic-monitoring-data-insights-preprod/resources/serviceaccount-github.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-electronic-monitoring-data-insights-preprod/resources/template-api.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-electronic-monitoring-data-insights-preprod/resources/template-ui.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-electronic-monitoring-data-insights-preprod/resources/ui-elasticache.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-electronic-monitoring-data-insights-preprod/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-electronic-monitoring-data-insights-preprod/resources/versions.tf
This is the configuration for the EMDI preprod UI
=> EPT-234: EMDI Preprod env

namespaces/live.cloud-platform.service.justice.gov.uk/laa-fala-staging/resources/ecr.tf
add a prefix to create new secrets
=> FALA STG: Add github action secrets for ECR

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-electronic-monitoring-data-insights-dev/06-certificate.yaml
=> EPT-234: updated certs

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-electronic-monitoring-data-insights-preprod/06-certificate.yaml
preprod api cert config change
=> EPT-234: preprod api cert

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-interventions-prod/resources/hmpps-audit-queue.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-interventions-prod/resources/irsa.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-interventions-prod/resources/variables.tf
PR for configuring audit for Refer and Monitor prod
=> PR for configuring audit for Refer and Monitor prod

namespaces/live.cloud-platform.service.justice.gov.uk/tom-namespace-dev/04-networkpolicy.yaml
Add block egress to namespace for test
=> Add block egress calico network policy

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-interventions-preprod/resources/hmpps-audit-queue.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-interventions-preprod/resources/irsa.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-interventions-preprod/resources/variables.tf
updating environment details for preprod
=> updating environment details for preprod

namespaces/live.cloud-platform.service.justice.gov.uk/laa-manage-a-providers-data-uat/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-manage-a-providers-data-uat/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-manage-a-providers-data-uat/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-manage-a-providers-data-uat/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-manage-a-providers-data-uat/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-manage-a-providers-data-uat/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-manage-a-providers-data-uat/resources/serviceaccount.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-manage-a-providers-data-uat/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-manage-a-providers-data-uat/resources/versions.tf
Creates a uat environment for the Manage a Provider's Data service.
=> MAPD-2 Create UAT Environment

namespaces/live.cloud-platform.service.justice.gov.uk/laa-manage-a-providers-data-production/resources/variables.tf
Removes the apostrophe from application name
=> MAPD-2 Production ECR Fix

namespaces/live.cloud-platform.service.justice.gov.uk/moj-frontend/resources/secrets.tf
Adds a secret for the content security reporting endpoint in sentry
=> add sentry csp reporting endpoint

.checksum, namespaces/live.cloud-platform.service.justice.gov.uk/laa-fee-scheme-api-dev/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-fee-scheme-api-dev/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-fee-scheme-api-dev/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-fee-scheme-api-dev/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-fee-scheme-api-dev/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-fee-scheme-api-dev/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-fee-scheme-api-dev/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-fee-scheme-api-dev/resources/versions.tf
Created namespace folder for LAA-Fee-Scheme (simplified) project and added files for development environment.
=> Namespace created for LAA-Fee Scheme (Simplified version)

namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-dev/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-dev/resources/variables.tf
Changing team from DCES to Crime Apps
=> Drc-Integration Team Change - DEV

namespaces/live.cloud-platform.service.justice.gov.uk/laa-cwa-users-api-test/03-resourcequota.yaml
cwa-users-api-test namespace refresh
=> TA-3329 cwa-users-api-test refresh

.checksum, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-esupervision-test/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-esupervision-test/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-esupervision-test/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-esupervision-test/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-esupervision-test/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-esupervision-test/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-esupervision-test/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-esupervision-test/resources/versions.tf
Create hmpps-esupervision-test namespace. This is a development namespace used to demo the application to internal and external stakeholders.
=> Create test namespace for HMPPS esupervision application

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-prod/00-namespace.yaml
=> LSM-93 - Maintenance alerts UI - Prod

namespaces/live.cloud-platform.service.justice.gov.uk/laa-cwa-users-api-test/03-resourcequota.yaml
Minor change for 2nd refresh after deleting region etc.
=> TA-3329 Minor change for 2nd refresh

namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-test/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-test/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-test/resources/pingdom.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-test/resources/variables.tf
Changing team from DCES to Crime Apps
=> Drc-Integration Team Change - Test

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-esupervision-test/resources/template-kotlin.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-esupervision-test/resources/template-typescript.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-esupervision-test/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-esupervision-test/resources/versions.tf
Configure the node and kotlin projects within the HMPPS esupervision test namespace. Update the environment variable to reflect the environment name used within the helm deployments.
=> Configure the API and UI projects within the test namespace

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-api-live-support/00-namespace.yaml
=> LSM-92 - Maintenance alerts - API - Live Support

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-litigator-fees-dev/resources/cognito.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-litigator-fees-dev/resources/variables.tf
This was originally created for testing, but can now be updated for actual use.
* changes user pool client name to reflect the actual client
* fixes the secret name to match our service
=> Update cclf dev cognito config

namespaces/live.cloud-platform.service.justice.gov.uk/laa-cwa-users-api-stg/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-cwa-users-api-stg/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-cwa-users-api-stg/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-cwa-users-api-stg/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-cwa-users-api-stg/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-cwa-users-api-stg/resources/ecr.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-cwa-users-api-stg/resources/irsa.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-cwa-users-api-stg/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-cwa-users-api-stg/resources/s3.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-cwa-users-api-stg/resources/secret.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-cwa-users-api-stg/resources/serviceaccount.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-cwa-users-api-stg/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-cwa-users-api-stg/resources/versions.tf
TA-3330 Creation of namespace laa-cwa-users-api-stg
=> TA-3330 laa-cwa-users-api-stg namespace

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-esupervision-test/resources/irsa.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-esupervision-test/resources/s3.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-esupervision-test/resources/variables.tf
Add S3 bucket resource and IRSA configuration for the HMPPS esupervision test namespace.
=> Define s3 bucket and IRSA roles for esupervision test namespace

namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-report-service-uat/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-report-service-uat/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-report-service-uat/resources/pingdom.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-report-service-uat/resources/variables.tf
Changing team from DCES to Crime Apps
=> DCES Report Team Change - UAT

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-launchpad-dev/resources/servicepod.tf
Allow us to check the messages we are adding to the prisoner audit queue
=> LNP-1180: Add service pod to launchpad dev

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-dev/04-networkpolicy.yaml
This still isn't working. Removing until I can investigate further.
=> Remove egress blocking

namespaces/live.cloud-platform.service.justice.gov.uk/moj-frontend/resources/secrets.tf
Adds a secret for our ip whitelist
=> add ip list secret

namespaces/live.cloud-platform.service.justice.gov.uk/rajinder-pocs/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/rajinder-pocs/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/rajinder-pocs/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/rajinder-pocs/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/rajinder-pocs/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/rajinder-pocs/resources/ecr.tf, namespaces/live.cloud-platform.service.justice.gov.uk/rajinder-pocs/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/rajinder-pocs/resources/secret.tf, namespaces/live.cloud-platform.service.justice.gov.uk/rajinder-pocs/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/rajinder-pocs/resources/versions.tf
New namespace request for poc , learning and development
=> New namespace request for poc and l and d

namespaces/live.cloud-platform.service.justice.gov.uk/laa-data-stewardship-civil-claims-api-uat/resources/secret.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-data-stewardship-civil-claims-api-uat/resources/variables.tf
[AWS Secret Managerfor laa-data-stewardship-civil-claims-api-uat](https://dsdmoj.atlassian.net/browse/DSTEW-135)
Create Secret name for laa-data-stewardship-civil-claims-api-uat
=> DSTEW-135: Add AWS Secret Manager for laa-data-stewardship-civil-claims-api-uat 

namespaces/live.cloud-platform.service.justice.gov.uk/rajinder-pocs/resources/serviceaccount.tf, namespaces/live.cloud-platform.service.justice.gov.uk/rajinder-pocs/resources/variables.tf
=> Added service account

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-dev/04-networkpolicy.yaml
Allow sending data to Sentry in CCR dev
=> Allow egress to Sentry

namespaces/live.cloud-platform.service.justice.gov.uk/laa-civil-case-api-production/00-namespace.yaml
Add namespace label to Civil Case API production
=> Add namespace label to Civil Case API production

namespaces/live.cloud-platform.service.justice.gov.uk/laa-submit-crime-forms-dev/resources/secrets.tf
Renaming a secret so it has a more intuitive name as it's been repurposed
=> Rename secret for SILAS

namespaces/live.cloud-platform.service.justice.gov.uk/rajinder-pocs/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/rajinder-pocs/resources/secret.tf
Context
https://mojdt.slack.com/archives/C57UPMZLY/p1752754920624149?thread_ts=1752678761.338909&cid=C57UPMZLY
=> Added GithubTeam tag to default tags

namespaces/live.cloud-platform.service.justice.gov.uk/laa-submit-crime-forms-dev/resources/secrets.tf
Need to regenerate mistakenly removed secret
=> Trigger redeployment

namespaces/live.cloud-platform.service.justice.gov.uk/laa-data-claims-api-uat/resources/ecr.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-data-claims-api-uat/resources/rds-postgresql.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-data-claims-api-uat/resources/secret.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-data-claims-api-uat/resources/serviceaccount.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-data-claims-api-uat/resources/variables.tf
Add resources (ecr, rds-psotgres, secrets, sa) to namespace laa-data-claims-api-uat
=> DSTEW-176: Add resources (ecr, rds-psotgres, secrets, sa) 

namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-datahub-catalogue-dev/resources/rds-postgresql.tf, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-datahub-catalogue-dev/resources/variables.tf
Add deletion protection var and sets to false (required ahead of restore)
=> Add deletion protection variable for RDS module

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-staging/resources/cognito.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-staging/resources/variables.tf
This creates a Cognito user pool in ccr-staging environment to add authentication to an API within CCR.
=> configure cognito for ccr-staging

.checksum, namespaces/live.cloud-platform.service.justice.gov.uk/laa-submit-a-bulk-claim-uat/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-submit-a-bulk-claim-uat/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-submit-a-bulk-claim-uat/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-submit-a-bulk-claim-uat/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-submit-a-bulk-claim-uat/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-submit-a-bulk-claim-uat/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-submit-a-bulk-claim-uat/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-submit-a-bulk-claim-uat/resources/versions.tf
Adds a new namespace called `laa-submit-a-bulk-claim-uat`
=> Create namespace for laa-submit-a-bulk-claim-uat

.checksum, namespaces/live.cloud-platform.service.justice.gov.uk/laa-submit-a-bulk-claim-api/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-submit-a-bulk-claim-api/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-submit-a-bulk-claim-api/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-submit-a-bulk-claim-api/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-submit-a-bulk-claim-api/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-submit-a-bulk-claim-api/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-submit-a-bulk-claim-api/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-submit-a-bulk-claim-api/resources/versions.tf
Adds a new namespace called `laa-submit-a-bulk-claim-api-staging`
=> Create namespace for laa-submit-a-bulk-claim-api-staging

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-challenge-support-intervention-plan-dev/00-namespace.yaml
=> LSM-100 - CSIP Alerts - Dev

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-challenge-support-intervention-plan-preprod/00-namespace.yaml
=> LSM-100 - CSIP Alerts - PreProd

namespaces/live.cloud-platform.service.justice.gov.uk/laa-fee-scheme-api-dev/resources/main.tf
Changes made:
Added GitHubTeam tag to `laa-fee-scheme-dev`
=> Add GitHubTeam tag to laa-fee-scheme-dev

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-prod/resources/pingdom.tf
=> LSM-109 - Adjudications UI - Pingdom

.checksum, namespaces/live.cloud-platform.service.justice.gov.uk/laa-fee-scheme-api-uat/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-fee-scheme-api-uat/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-fee-scheme-api-uat/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-fee-scheme-api-uat/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-fee-scheme-api-uat/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-fee-scheme-api-uat/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-fee-scheme-api-uat/resources/rds.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-fee-scheme-api-uat/resources/serviceaccount.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-fee-scheme-api-uat/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-fee-scheme-api-uat/resources/versions.tf
Changes made:
- Created namespace - laa-fee-scheme-api-uat
=> LFSP-44: Create laa-fee-scheme-api-uat namespace

namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-data-migration-dev/resources/iam.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-data-migration-dev/resources/s3.tf
revoking permissions for s3 and iam in dces
=> laa-dces-dm-revoke-privs

.checksum, namespaces/live.cloud-platform.service.justice.gov.uk/laa-fee-scheme-api-staging/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-fee-scheme-api-staging/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-fee-scheme-api-staging/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-fee-scheme-api-staging/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-fee-scheme-api-staging/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-fee-scheme-api-staging/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-fee-scheme-api-staging/resources/rds.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-fee-scheme-api-staging/resources/serviceaccount.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-fee-scheme-api-staging/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-fee-scheme-api-staging/resources/versions.tf
Changes made:
Created namespace - laa-fee-scheme-api-staging
=> LFSP-44: Create laa-fee-scheme-api-staging namespace

namespaces/live.cloud-platform.service.justice.gov.uk/laa-fee-scheme-api-uat/resources/rds.tf
- Upgrade to PostgreSQL version 17.
=> Upgrade to postgres17 for laa-fee-scheme-api-uat

namespaces/live.cloud-platform.service.justice.gov.uk/laa-fee-scheme-api-dev/resources/rds.tf
Changes made:
- Set RDS prepare_for_major_upgrade to false
=> Turn off RDS major version upgrade for laa-fee-scheme-api-dev

.github/workflows/pr-stale.yaml
- Reduced stale time from 60 days to 30 days.
=> chore: reduce stale time to 30 days

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-litigator-fees-uat/resources/irsa.tf
There will be strange behaviours as both uat and staging are pointing to the same queues. 
CCLF uat is now set to communicate with CCCD dev-lgfs.
=> Update irsa for CCLF uat

.checksum, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-esupervision-preprod/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-esupervision-preprod/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-esupervision-preprod/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-esupervision-preprod/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-esupervision-preprod/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-esupervision-preprod/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-esupervision-preprod/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-esupervision-preprod/resources/versions.tf
Define hmpps-esupervision-preprod namespace which will host the preprod environment of the HMPPS esupervision application.
=> Create preprod namespace for HMPPS esupervision application

namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-acronyms-app-dev/resources/ecr.tf
- This PR updates ECR deletion protection to false. This is pre-work required for upcoming decommissioning.
- Added `deletion_protection = false`
=> Update ecr deletion protection

namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-user-management-api-test/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-user-management-api-test/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-user-management-api-test/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-user-management-api-test/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-user-management-api-test/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-user-management-api-test/resources/ecr.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-user-management-api-test/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-user-management-api-test/resources/secret.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-user-management-api-test/resources/serviceaccount.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-user-management-api-test/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-user-management-api-test/resources/versions.tf
Create new test environment for user management api
=> New test environment for user management api

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-esupervision-preprod/resources/github-environment-api.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-esupervision-preprod/resources/github-environment-ui.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-esupervision-preprod/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-esupervision-preprod/resources/versions.tf
Configure the Github preprod environment within the HMPPS esuperivsion preprod namespace.
=> Configure Github environment for API and UI projects in esupervision

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-esupervision-preprod/resources/rds.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-esupervision-preprod/resources/variables.tf
Define postgres instance and store the associated configuration in a secret within the HMPPS esuperivsion preprod environment.
=> Create postgres instance in HMPPS esupervision preprod environment

namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-uat/cronjob-check-supported-versions.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-uat/resources/irsa.tf, namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-uat/resources/s3-oidc-role.tf, namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-uat/resources/s3.tf
Changes:
- Adds a new cronjob
- Adds irsa for cronjob
- Adds s3 bucket (for some reason we have an unused example s3 bucket in our namespaces, so I've replaced this.)
- Adds an assumable role for CircleCi
=> Claim criminal injuries uat versions cronjob

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-esupervision-preprod/resources/irsa.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-esupervision-preprod/resources/variables.tf
Configure a service account in the HMPPS esupervision preprod namespace and configure S3 access.
=> Add service account in HMPPS esupervision preprod

namespaces/live.cloud-platform.service.justice.gov.uk/grc-prod/resources/rds.tf, namespaces/live.cloud-platform.service.justice.gov.uk/grc-prod/resources/secrets-manager.tf
Also, allow automatic minor version upgrades of rds and remove specific minor version
Don't allow automatic major version upgrades
=> Create new external secret for opensearch alerting

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-esupervision-prod/07-ingress.yaml
=> hmpps-supervision-prod: Add ingress configuration

.checksum, namespaces/live.cloud-platform.service.justice.gov.uk/cloud-platform-pingdom-ingress-check-prod/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/cloud-platform-pingdom-ingress-check-prod/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/cloud-platform-pingdom-ingress-check-prod/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/cloud-platform-pingdom-ingress-check-prod/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/cloud-platform-pingdom-ingress-check-prod/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/cloud-platform-pingdom-ingress-check-prod/resources/ecr.tf, namespaces/live.cloud-platform.service.justice.gov.uk/cloud-platform-pingdom-ingress-check-prod/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/cloud-platform-pingdom-ingress-check-prod/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/cloud-platform-pingdom-ingress-check-prod/resources/versions.tf
This is the home for the new pingdom ingress checker service (replacing canary app)
=> feat: 🎸 add new namespace for pingdom ingress checker

namespaces/live.cloud-platform.service.justice.gov.uk/cloud-platform-pingdom-ingress-check-prod/resources/sa.tf
relates to ministryofjustice/cloud-platform#7447
=> feat: 🎸 add serviceaccount for GH deploy action

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-challenge-support-intervention-plan-prod/02-limitrange.yaml
=> LSM-130 - CSIP Limits

namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-prod/resources/justiceinspectorates.tf
- Stakeholder requested lowering TTL for technical support of dns changes.
=> Lower TTL for HMICFRS domain as per requested

namespaces/live.cloud-platform.service.justice.gov.uk/laa-data-claims-event-service-uat/resources/secrets.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-data-claims-event-service-uat/resources/serviceaccount.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-data-claims-event-service-uat/resources/variables.tf
Adds a secret manager and service account to laa-data-claims-event-service-uat namespace
=> Added secrets manager and service account to laa-data-claims-event-service-uat

namespaces/live.cloud-platform.service.justice.gov.uk/laa-data-claims-event-service-prod/resources/secrets.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-data-claims-event-service-prod/resources/serviceaccount.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-data-claims-event-service-prod/resources/variables.tf
Adds a secret manager and service account to laa-data-claims-event-service-production namespace
=> Added secrets manager and service account to laa-data-claims-event-service-production

namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-prod/resources/icrir-route53.tf
Policy requested be removed from stakeholder.
=> DNS ICRIR remove subdomain policy

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-matching-prototype/resources/variables.tf
PR to change password for the prototype app.
Namespace: _hmpps-matching-prototype_
=> ESWE-1385: change prototype password

namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-user-management-api-dev/resources/irsa.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-ccms-user-management-api-dev/resources/modules/sqs/main.tf
=> fix: match queue and dlq types

namespaces/live.cloud-platform.service.justice.gov.uk/laa-landing-page-dev/resources/data.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-landing-page-dev/resources/irsa.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-landing-page-dev/resources/secrets.tf
Adds SQS integration with `laa-ccms-user-management-api-dev`:
- Data lookups for SQS
- IRSA for cross namespace communication and auth
- Secret injection
=> feat: sqs integration with ccms-user-mgmt-api

namespaces/live.cloud-platform.service.justice.gov.uk/stg-track-my-case-service-dev/resources/variables.tf
PR to create a database with custom name
=> PR to create a database with custom name

namespaces/live.cloud-platform.service.justice.gov.uk/laa-landing-page-prd/resources/data.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-landing-page-prd/resources/irsa.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-landing-page-prd/resources/secrets.tf
Integrates with user-mgmt-api-prod sqs queue
=> feat: integrate with user-mgmt-api prod sqs

namespaces/live.cloud-platform.service.justice.gov.uk/laa-get-payments-finance-data-uat/resources/irsa.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-get-payments-finance-data-uat/resources/s3.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-get-payments-finance-data-uat/resources/variables.tf
Having tested the setup on dev namespace worked, am now adding to UAT.
=> LPF-1021 - add template store S3 bucket to UAT

namespaces/live.cloud-platform.service.justice.gov.uk/laa-data-stewardship-payments-dev/resources/ecr.tf
`laa-data-stewardship-payments-dev` ECR deletion protection
=> DSTEW-141: ECR deletion_protection

namespaces/live.cloud-platform.service.justice.gov.uk/laa-maat-scheduled-tasks-prod/resources/irsa.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-maat-scheduled-tasks-prod/resources/s3.tf
This PR creates an S3 bucket for the Scheduled Tasks Service in the prod environment and the appropriate IRSA config for the service account to be able to access this bucket.
=> Create S3 bucket and IRSA config for Scheduled Tasks Service Prod

namespaces/live.cloud-platform.service.justice.gov.uk/laa-maat-scheduled-tasks-prod/resources/secret.tf
Added a secret for a slack webhook.
=> [LASB-4384] Add slack webhook secret for laa-maat-scheduled-tasks-prod

.checksum, namespaces/live.cloud-platform.service.justice.gov.uk/ramya-dev/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/ramya-dev/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/ramya-dev/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/ramya-dev/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/ramya-dev/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/ramya-dev/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/ramya-dev/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/ramya-dev/resources/versions.tf
Creating new namespace ramya-dev
=> creating namespace

namespaces/live.cloud-platform.service.justice.gov.uk/laa-criminal-applications-datastore-production/04-networkpolicy.yaml
This reverts commit 7dd0548422ad5574b58d8ae7d0789ffd3d34f703.
=> Revert "CRIMAPP-1815 remove crime apply access to the datastore"

namespaces/live.cloud-platform.service.justice.gov.uk/laa-data-pact-broker/resources/secret.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-data-pact-broker/resources/variables.tf
Initial configuration of aws secrets
=> DSTEW-335 Initial configuration of AWS secrets

namespaces/live.cloud-platform.service.justice.gov.uk/laa-data-pact-broker/resources/secret.tf
=> DSTEW-335 Consolidate AWS secrets

.checksum, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-emdi-api-dev/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-emdi-api-dev/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-emdi-api-dev/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-emdi-api-dev/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-emdi-api-dev/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-emdi-api-dev/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-emdi-api-dev/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-emdi-api-dev/resources/versions.tf
new namespaces for POCing EMDI functionality
=> Create namespaces for emdi http api

namespaces/live.cloud-platform.service.justice.gov.uk/laa-data-pact-broker/resources/secret.tf
=> DSTEW-335 Reconfigure AWS secrets

namespaces/live.cloud-platform.service.justice.gov.uk/mikebell-test/resources/rds.tf
=> feat: restore db

namespaces/live.cloud-platform.service.justice.gov.uk/laa-data-claims-api-uat/resources/irsa.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-data-claims-api-uat/resources/serviceaccount.tf
Plus other refactoring to reuse existing values rather than creating new ones.
=> Use a single service account (created by IRSA)

namespaces/live.cloud-platform.service.justice.gov.uk/mikebell-test/resources/rds.tf
- Removes skip file
- Adds postgres replica
=> feat: remove skip and add replica

namespaces/live.cloud-platform.service.justice.gov.uk/mikebell-test/resources/irsa.tf, namespaces/live.cloud-platform.service.justice.gov.uk/mikebell-test/resources/rds.tf
=> feat: remove rds

namespaces/live.cloud-platform.service.justice.gov.uk/laa-benefit-checker-prod/06-prometheus-rules.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-benefit-checker-prod/07-grafana.yaml
This PR adds the prometheus configuration and grafana configuration for the benefit checker prod namespace
=> Add grafana and prometheus config to benefit checker prod

namespaces/live.cloud-platform.service.justice.gov.uk/laa-get-payments-finance-data-dev/resources/pingdom.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-get-payments-finance-data-dev/resources/versions.tf
We turned off pingdom for dev for reasons. Turn it back on.
=> Turn Pingdom back on for Dev

namespaces/live.cloud-platform.service.justice.gov.uk/mikebell-test/resources/irsa.tf, namespaces/live.cloud-platform.service.justice.gov.uk/mikebell-test/resources/rds.tf
- Empty commit after removing finalsnapshot
- Re add irsa and rds with read replica
=> Re-enable RDS for mikebell-test

.checksum, namespaces/live.cloud-platform.service.justice.gov.uk/wajid-irsa-test/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/wajid-irsa-test/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/wajid-irsa-test/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/wajid-irsa-test/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/wajid-irsa-test/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/wajid-irsa-test/resources/elasticache.tf, namespaces/live.cloud-platform.service.justice.gov.uk/wajid-irsa-test/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/wajid-irsa-test/resources/rds.tf, namespaces/live.cloud-platform.service.justice.gov.uk/wajid-irsa-test/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/wajid-irsa-test/resources/versions.tf
Env for RDS and Elasticache optional IRSA changes testing.
=> Wajid irsa test

namespaces/live.cloud-platform.service.justice.gov.uk/mikebell-test/resources/rds.tf
- Matches code with current state
=> feat: match code with state

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-launchpad-dev/resources/hmpps-launchpad-auth.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-launchpad-dev/resources/versions.tf
Migrating from circleCI to Github Action
=> hmpps-launchpad-auth Migrate to Github Action

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-esupervision-dev/resources/service_pod.tf
Create a service pod for testing AWS permissions config in the HMPPS esupervision dev namespace.
=> Define service pod in HMPPS esupervision dev namespace

namespaces/live.cloud-platform.service.justice.gov.uk/cfe-civil-staging/resources/rds.tf
Upgrade staging to postgres 17.16
=> AP-6166: Upgrade cfe civil staging to postgres 17.16

namespaces/live.cloud-platform.service.justice.gov.uk/cfe-civil-staging/01-rbac.yaml
=> AP-6161: Add civil apply team to rbac [CFE staging]

namespaces/live.cloud-platform.service.justice.gov.uk/cfe-civil-production/01-rbac.yaml
=> AP-6161: Add civil apply team to rbac [CFE production]

namespaces/live.cloud-platform.service.justice.gov.uk/cfe-civil-production/resources/rds.tf
Set prepare for major upgrade to false for cfe civil production
=> AP-6166: Set prepare for major upgrade to false

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-launchpad-prod/resources/hmpps-launchpad-auth.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-launchpad-prod/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-launchpad-prod/resources/versions.tf
Migrate launchpad-auth-prod to Github
=> Migrate launchpad-auth-prod to Github

namespaces/live.cloud-platform.service.justice.gov.uk/ramya-dev/resources/ecr.tf
Created a ecr as per the documentation in my namespace.
=> creating ecr in name space

namespaces/live.cloud-platform.service.justice.gov.uk/tim-development/resources/rds.tf
=> chore: restore rds

namespaces/live.cloud-platform.service.justice.gov.uk/monitoring/resources/opensearch-alert.tf
Create alert for Error loading seccomp filter - Errno 524
Relating to issue [#7562](https://github.com/ministryofjustice/cloud-platform/issues/7562)
=> Create alert for Error loading seccomp filter - Errno 524

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-proceeding-prod/resources/scheduled-downtime.tf
Add service account in CCP Production to enable automatic scaling of pods
=> LASB-4424|Add service account in CCP Production to enable automatic scaling of pods

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-esupervision-preprod/resources/domain-events-topic.tf, namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-esupervision-preprod/resources/irsa.tf
Adds SNS (publish only) to preprod environment.
=> esupervision: add SNS to preprod env

namespaces/live.cloud-platform.service.justice.gov.uk/laa-data-claims-api-uat/04-networkpolicy.yaml
- Allow ingress from laa-data-claims-event-service-uat -> laa-data-claims-api-uat
- Allow ingress from laa-submit-a-bulk-claim-uat  -> laa-data-claims-api-uat
=> Add network policies - laa-data-claims-api-uat

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-document-management-preprod/resources/rds-postgresql.tf
https://dsdmoj.atlassian.net/browse/DOC-79
=> DOC-79 Create rds postgresql preprod db creds in prod namespace for prod-preprod db copy.

namespaces/live.cloud-platform.service.justice.gov.uk/laa-fee-scheme-api-prod/resources/rds.tf
- Added RDS PostgreSQL resource to laa-fee-scheme-api-prod namespace.
=> LFSP-49: Set up db for laa-fee-scheme-api-prod

namespaces/live.cloud-platform.service.justice.gov.uk/reuselibrary-dev/resources/ecr.tf, namespaces/live.cloud-platform.service.justice.gov.uk/reuselibrary-dev/resources/serviceaccount.tf
Updated the github repository to reuse-library  and removed the environment to correct the build errors
=> Updated the github repository to reuse-library 

namespaces/live.cloud-platform.service.justice.gov.uk/ramya-dev/resources/rds-mysql.tf
adding ads to my namespace Ramya-dev
=> add rds to namespace

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-support-additional-needs-prod/resources/rds-postgresql.tf
Corresponding prod postgres upgrade following: https://github.com/ministryofjustice/cloud-platform-environments/pull/36258
=> RR-1859 Upgrade SAN Prod RDS to postgres 17

namespaces/live.cloud-platform.service.justice.gov.uk/stg-track-my-case-service-dev/01-rbac.yaml
=> Including analytics-hq in to rbac subjects for stg-track-my-case-service-dev;

.checksum, namespaces/live.cloud-platform.service.justice.gov.uk/stg-track-my-case-service-test/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/stg-track-my-case-service-test/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/stg-track-my-case-service-test/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/stg-track-my-case-service-test/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/stg-track-my-case-service-test/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/stg-track-my-case-service-test/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/stg-track-my-case-service-test/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/stg-track-my-case-service-test/resources/versions.tf
stg-track-my-case-service-test namespace added
=> stg-track-my-case-service-test namespace added

namespaces/live.cloud-platform.service.justice.gov.uk/stg-track-my-case-ui-demo/resources/ecr.tf
- deletion_protection    = false
=> Removing stg-track-my-case-ui-demo environment;

namespaces/live.cloud-platform.service.justice.gov.uk/laa-cwa-schedule-uploader-dev/resources/ecr.tf
ECR module added to laa-cwa-schedule-uploader-api
=> Add ecr module to laa-cwa-schedule-uploader-api

.github/workflows/skip-file-auto-approval.yaml
docs:
https://github.com/hmarr/auto-approve-action?tab=readme-ov-file#approving-on-behalf-of-a-different-user
=> chore: 🤖 removing hammer bot token ref for default token use

namespaces/live.cloud-platform.service.justice.gov.uk/laa-cwa-schedule-uploader-prod/resources/variables.tf
Change to variables.tf file addition of ek_cluster_name
=> Change to variables.tf file addition of ek_cluster_name

namespaces/live.cloud-platform.service.justice.gov.uk/laa-cwa-schedule-uploader-prod/resources/secret.tf
secret.tf file added to prod namespace
=> secret.tf file added

namespaces/live.cloud-platform.service.justice.gov.uk/laa-cwa-schedule-uploader-prod/resources/ecr.tf
Addition of ecr.tf file to namespace laa-cwa-schedule-uploader-prod
=> Addition of ecr.tf file

namespaces/live.cloud-platform.service.justice.gov.uk/crime-court-message-processor-service-dev/resources/ecr.tf, namespaces/live.cloud-platform.service.justice.gov.uk/crime-court-message-processor-service-dev/resources/variables.tf
Add GitHub repository name to .tf files.
=> Specify GitHub repo name.

namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-drc-integration-test/resources/rds-postgresql.tf
LASB-4444 - DRC - Dev - Cleanup
=> LASB-4444 - DRC - Test - Cleanup x

namespaces/live.cloud-platform.service.justice.gov.uk/crime-court-message-processor-service-prod/resources/ecr.tf
=> Remove github_action_prefix.

namespaces/live.cloud-platform.service.justice.gov.uk/crime-court-message-processor-service-test/resources/rds-postgresql.tf
Add RDS to the test environment.
=> Add RDS to namespace - test.

namespaces/live.cloud-platform.service.justice.gov.uk/crime-court-message-processor-service-uat/resources/rds-postgresql.tf
Add RDS to the uat environment.
=> Add RDS to namespace - uat.

namespaces/live.cloud-platform.service.justice.gov.uk/laa-amend-a-claim-dev/resources/ecr.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-amend-a-claim-uat/resources/ecr.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-amend-a-claim-uat/resources/serviceaccount.tf
also switching off ecr and serviceaccount in the uat environment until that is ready to enable
=> chore: 🤖 update dev env for laa amend namespace

namespaces/live.cloud-platform.service.justice.gov.uk/crime-court-message-processor-service-dev/resources/serviceaccount.tf
Add service account to dev environment.
=> Add service account to namespace - dev

namespaces/live.cloud-platform.service.justice.gov.uk/crime-court-message-processor-service-test/resources/serviceaccount.tf
Add service account to test environment.
=> Add service account to namespace - test

namespaces/live.cloud-platform.service.justice.gov.uk/crime-court-message-processor-service-uat/resources/serviceaccount.tf
Add service account to uat environment.
=> Add service account to namespace - uat

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-challenge-support-intervention-plan-preprod/resources/rds-postgresql.tf
Add hot_standby_feedback to read-replica parameters
=> LSM-145 - CSIP read-replica parameter change

.checksum, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-llm-gateway-development/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-llm-gateway-development/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-llm-gateway-development/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-llm-gateway-development/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-llm-gateway-development/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-llm-gateway-development/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-llm-gateway-development/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-llm-gateway-development/resources/versions.tf
Resolves https://github.com/ministryofjustice/data-platform/issues/21
- Adds Data Platform LLM Gateway **Development** namespace 
=> 🚅 Data Platform LLM Gateway Development

namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-llm-gateway-development/resources/elasticache.tf, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-llm-gateway-development/resources/irsa.tf, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-llm-gateway-development/resources/rds.tf, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-llm-gateway-development/resources/serviceaccount.tf, namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-llm-gateway-development/resources/variables.tf
Resolves https://github.com/ministryofjustice/data-platform/issues/24
- Creates RDS
- Creates ElastiCache
- Creates IRSA
- Creates CI/CD Service Account
=> ⛅ Create LLM Gateway Cloud Platform Resources

namespaces/live.cloud-platform.service.justice.gov.uk/srikanth-dev/resources/rds-mysql.tf, namespaces/live.cloud-platform.service.justice.gov.uk/srikanth-dev/resources/versions.tf
create mysql to test connectivity and restore procedure.
=> chore: create mysql

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-staging/resources/rds.tf
chore: restoring from snapshot for staging for laa-crown-court-remuneration-staging
=> chore: restoring from snapshot

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-staging/resources/rds.tf
=> chore: changed migration flag to false

namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-llm-gateway-development/resources/route53.tf
- Creates `llm-gateway.development.data-platform.service.justice.gov.uk`
=> 🌐 Add Data Platform LLM Gateway Development Route53

namespaces/live.cloud-platform.service.justice.gov.uk/crime-court-message-processor-service-uat/resources/ecr.tf
Remove ECR deletion protection.
=> Remove ECR deletion protection.

.checksum, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-court-message-processor-dev/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-court-message-processor-dev/01-rbac.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-court-message-processor-dev/02-limitrange.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-court-message-processor-dev/03-resourcequota.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-court-message-processor-dev/04-networkpolicy.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-court-message-processor-dev/resources/main.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-court-message-processor-dev/resources/variables.tf, namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-court-message-processor-dev/resources/versions.tf
Create namespace for CCMP service - dev environment.
=> Create namespace for CCMP - dev.

namespaces/live.cloud-platform.service.justice.gov.uk/laa-data-stewardship-access-resources/resources/ecr.tf
Purpose
This PR removes deletion protection from Data-Stewardship-Access.
♻️ What's changed
Update deletion_protection to set to false
=> Data-Stewardship-Access set flag to remove deletion protection

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-court-message-processor-dev/resources/ecr.tf
Add ECR module to dev environment
=> Create ECR module for dev.

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-court-message-processor-dev/resources/rds-postgresql.tf
=> Add postgresql RDS to dev.

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-court-message-processor-test/resources/rds-postgresql.tf
=> Add porstgresql RDS to test.

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-court-message-processor-uat/resources/rds-postgresql.tf
=> Add porstgresql RDS to uat.

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-court-message-processor-prod/resources/rds-postgresql.tf
=> Add porstgresql RDS to prod.

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-court-message-processor-test/resources/serviceaccount.tf
Add service account to test environment
=> Add service account to test.

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-court-message-processor-prod/resources/serviceaccount.tf
Add service account to prod environment
=> Add service account to prod.

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-court-message-processor-uat/resources/serviceaccount.tf
=> CCMP - Add Github Envs - UAT

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-court-message-processor-test/resources/serviceaccount.tf
=> CCMP - Add Github Envs - Test

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-court-message-processor-dev/resources/serviceaccount.tf
=> CCMP - Add Github Envs - DEV

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-court-message-processor-dev/resources/main.tf
Add team-name to default tags.
=> CCMP - Add Team-Name Tag - Dev 

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-dev/resources/irsa.tf
Grant client queues' access to service account for testing replay-message (`push-messages.sh`) on `dev` env
=> [ESWE-1469] Update IRSA on `hmpps-integration-api-dev`

namespaces/live.cloud-platform.service.justice.gov.uk/offender-management-preprod/resources/rds.tf
It was meant to be on the replica not the primary.
=> Move hot standby db param to replica MPC preprod

namespaces/live.cloud-platform.service.justice.gov.uk/mbpr-prod/00-namespace.yaml, namespaces/live.cloud-platform.service.justice.gov.uk/mbpr-prod/resources/ecr.tf, namespaces/live.cloud-platform.service.justice.gov.uk/mbpr-prod/resources/serviceaccount.tf
Update to use new repo name (same codebase, just a repo name change)
=> update source repo for environment mbpr-prod
