namespaces/live-1.cloud-platform.service.justice.gov.uk/court-probation-prod/10-prometheus-k8s-dashboard.yaml

@jhevans reported an issue whereby the court-probation for prod dashboard had gone missing. This was caused by a failure to load the following configmap into grafana. A change of data.name fixed the issue when applying locally (kubectl edit). This PR reflects that change.

Change data.name in dashboard to avoid conflict

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/court-probation-dev/resources/rds.tf

This PR adds the AWS client ID/secret for RDS so we can configure manual snapshots of RDS databases for court-case-service in court-probation-dev namespace.

court-probation-dev: add RDS client ID/secret to k8s secrets

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/court-probation-preprod/resources/rds.tf

This PR adds the AWS client ID/secret for RDS so we can configure manual snapshots of RDS databases for court-case-service in court-probation-preprod namespace.

Court-probation-preprod: add RDS client ID/secret to k8s secrets

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/court-probation-prod/resources/rds.tf

This PR adds the AWS client ID/secret for RDS so we can configure manual snapshots of RDS databases for court-case-service in court-probation-prod namespace.

court-probation-prod: add RDS client ID/secret to k8s secrets

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/operations-engineering/resources/state-lock-table.tf

This table will be used to lock terraform states for Operations
Engineering projects (initially [this
one](https://github.com/ministryofjustice/github-collaborators).
A later change will add an AWS IAM user with permissions to access both
this dynamodb table, and the S3 bucket (also defined in this folder)
which stores the terraform state files.

Add a DynamoDB table for terraform state locking

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/operations-engineering/resources/terraform-iam-user.tf

This user has access to the S3 bucket in which we
store operations-engineering terraform state
files, and access to the dynamodb table we use for 
the terraform state locks.
The dedicated IAM users created by the S3 and
DynamoDB modules will not be used.

Add IAM user for OpsEng terraform state-locking

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/operations-engineering/resources/terraform-iam-user.tf

The previous PR failed to create this user.
```
Error: Error creating IAM User terraform-user-bbddf46750d979fbbcec4e6bf067d4c4: AccessDenied: User: arn:aws:iam::754256621582:user/cloud-platform/manager-concourse is not authorized to perform: iam:CreateUser on resource: arn:aws:iam::754256621582:user/terraform-user-bbddf46750d979fbbcec4e6bf067d4c4
status code: 403, request id: 0e2e65d7-7271-4bc7-bcfe-e210ad17fbc6
```
However, other IAM users have been created 
successfully.
Looking at others, I can see that they have a 
`path` defined, so this change adds a path to 
this IAM user, to see if that fixes the problem.

Add a path to the opseng terraform IAM user

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/court-probation-prod/resources/pingdom.tf

This PR is to remove `pic` tag from `pingdom.tf` as it's not required.

Removed unnecessary tag

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-pin-phone-monitor-dev/resources/s3.tf

The apply pipeline is failing with this error:
```
Error: Error putting S3 notification configuration: InvalidArgument: Unable to validate the following destination configurations
status code: 400, request id: xxxxxxxxxxxxxxxx, host id: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```
https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/environments-terraform/jobs/apply-live-1/builds/592
I'm commenting out this block to (hopefully) fix the apply pipeline
until the underlying issue can be resolved.

Comment out S3 notification: hmpps-pin-phone-dev

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-pin-phone-monitor-dev/resources/s3.tf

Following this example to create s3 notifications that are pushed to SQS:
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket_notification
Have been encountering this error: "Unable to validate the following destination configurations" which indicates the SQS policy needs to exist that grants S3 permissions to push messages to the queue. I believe there is a dependency on the policy existing before the bucket notification resources.

Change principal of queue policy to s3

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/prisoner-content-hub-development/resources/s3.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/prisoner-content-hub-staging/resources/s3.tf

This PR enables the S3 user in the `prisoner-content-hub-development` namespace to read from the S3 bucket in `prisoner-content-hub-staging`, following the [guidance for migrating S3 buckets](https://github.com/ministryofjustice/cloud-platform-terraform-s3-bucket#migrate-from-existing-buckets).
I've hard-coded the IAM user and bucket ARNs because they're reaching across into different namespaces. If there's a way to reference it in Terraform rather than using absolute values I'd love a push in the right direction. I'll happily update this PR.

Prisoner Content Hub: Add user/bucket policies to allow development S3 user to pull staging S3 content

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/prisoner-content-hub-development/resources/s3.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/prisoner-content-hub-production/resources/s3.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/prisoner-content-hub-staging/resources/s3.tf

Following on from #4045, we've validated those changes enable us to sync data from one S3 bucket to another.
This PR introduces the same change, but for to enable sync from `production` S3 to `staging` and `development`.
The multi-namespace check will complain, but again, this is reaching between namespaces.

Enable staging & development to read-only sync S3 from production

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/prisoner-content-hub-production/09-prometheus.yaml

This PR updates prisoner content hub's yellow/red ElasticSearch alerts to make them consistent with other ES monitoring on Cloud Platform.

Prisoner Content Hub: Bring ElasticSearch Yellow/Red alerts in line with prisoner/probration offender search

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-cla-backend-production/resources/rds.tf

the ratio of iops to max storage should be at-least 0.5. This is to adjust the auto-scaling capability enabled on the module.
More details here: https://github.com/ministryofjustice/cloud-platform-environments/pull/3978

Set max_allocated_storage to 1000

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/prisoner-content-hub-staging/resources/elasticsearch.tf

We believe the yellow cluster alerts we've been receiving for prisoner content hub are caused by momentary dips in available disk space (talked about [here](https://mojdt.slack.com/archives/C57UPMZLY/p1610615299003400)).
This PR hopes to resolve these alarms by increasing the disk from 10Gb to 50Gb. This PR applies the change to staging so we can verify the disk doesn't get rebuilt. Once we're happy, we'll apply the exact same change to production.

Prisoner Content Hub: Increase ElasticSearch disk

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/prisoner-content-hub-production/resources/elasticsearch.tf

This applies the ElasticSearch disk increase to the prisoner content hub production namespace. Follows on from the previous PR testing this in staging https://github.com/ministryofjustice/cloud-platform-environments/pull/4059.
We believe the yellow cluster alerts we've been receiving for prisoner content hub are caused by momentary dips in available disk space (talked about [here](https://mojdt.slack.com/archives/C57UPMZLY/p1610615299003400)).
This PR hopes to resolve these alarms by increasing the disk from 10Gb to 50Gb.

Prisoner Content Hub: Increase ElasticSearch disk (production)

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/offender-events-dev/resources/poll-pusher-sub-queue.tf

This is recommended in AWS documentation. If it's not longer then messages can be automatically removed from the DLQ before the retention period of the main queue ends which is somewhat confusing.

DT-1437 Make DLQ message retention longer than main queue

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/offender-events-dev/resources/prison_to_nhs_update-sub-queue.tf

The prison-to-nhs-update-dev namespace has been deleted, so these
secrets cannot be provisioned anymore. Trying to create them causes the
apply pipeline to fail.

Stop pushing secrets to prison-to-nhs-update-dev

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/court-probation-dev/resources/rds.tf

This is so that we can disable backups temporarily for the purposes of checking our alerts on this. Suggests that setting retention period to 0 has this effect
https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_WorkingWithAutomatedBackups.html

:wrench: change backup retention period to 0 days (temporary)

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/prisoner-content-hub-production/09-prometheus.yaml

This PR increases our ElasticSearch yellow cluster alarm to 6 minute threshold.
Following on from https://mojdt.slack.com/archives/C57UPMZLY/p1610615299003400, we increased the available disk space in #4059 and #4060. However, we're still seeing the same alarms. 
Given the struggle to find a cause, and that they always resolve themselves in exactly 5 minutes, this feels like a good trade-off between getting to the bottom of it and retaining the will to live 🤷‍♂️

Prisoner Content Hub: increase ElasticSearch yellow cluster alarm threshold

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/data-eng-rds-dev/resources/rds.tf

Adds an IAM user to the data-eng-rds-dev namespace. This has permission to write to a data engineering S3 bucket. Makes secrets for that user available through the RDS secret.
This is modelled on the approach in the [pathfinder namespace](https://github.com/ministryofjustice/cloud-platform-environments/blob/main/namespaces/live-1.cloud-platform.service.justice.gov.uk/pathfinder-prod/resources/rds.tf).

Data engineering add iam role

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-saas-test/editor-workers-service-account.yaml

We are building the new formbuilder editor in the test environment.
The editor will be publishing forms into the formbuilder-services-test-* namespaces and it needs a specific service account to provision new pods and applying k8s files.
This PR adds a service account that will be used to provisioning new forms into the formbuilder services namespace as we are starting to build the editor test environment.
Add the permission to this service account to this two namespaces:
- formbuilder-services-test-dev
- formbuilder-services-test-production

Add formbuilder editor workers service account

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-services-test-dev/01-rbac.yaml

The service account was added in this PR: https://github.com/ministryofjustice/cloud-platform-environments/pull/4151
Now we need to add permissions to provision new pods to the formbuilder services test dev environment. This PR address this.

Add permission to editor to publish to services test dev

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-services-test-production/01-rbac.yaml

The service account was added in this PR: https://github.com/ministryofjustice/cloud-platform-environments/pull/4151
Now we need to add permissions to provision new pods to the formbuilder services test production environment. This PR address this.

Add permission to editor to publish to services test

---

namespace-resources-cli-template/resources/main.tf
namespace-resources-cli-template/resources/variables.tf

This ensures that all namespaces created by the
cloud platform CLI will correctly initialise the
github provider.
This is required for the ECR and serviceaccount
modules, so that they can create github actions
secrets containing their credentials.

Set up the github provider in terraform template

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/moj-prototype/00-namespace.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/moj-prototype/01-rbac.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/moj-prototype/02-limitrange.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/moj-prototype/03-resourcequota.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/moj-prototype/04-networkpolicy.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/moj-prototype/resources/ecr.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/moj-prototype/resources/main.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/moj-prototype/resources/serviceaccount.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/moj-prototype/resources/variables.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/moj-prototype/resources/versions.tf

This namespace will be used to develop a Cloud Platform MoJ Prototype
tool. i.e. a way to quickly create prototypes based on the Gov.UK
prototype kit, hosted on the MoJ Cloud Platform.

Create moj-prototype namespace

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/court-probation-preprod/resources/perf_test_data_s3_bucket.tf

This bucket is required to support performance testing in preprod only so there are no corresponding buckets in dev or prod

✨ PIC-1085: Add S3 bucket for cpmg performance test data

---

namespace-resources-cli-template/resources/prototype/basic-auth.tf
namespace-resources-cli-template/resources/prototype/ecr.tf
namespace-resources-cli-template/resources/prototype/github-repo.tf
namespace-resources-cli-template/resources/prototype/serviceaccount.tf

These files will be used by the cli tool when a user runs:
```
cloud-platform environment prototype create
```
These files represent (most of) the difference between a "vanilla"
namespace, and a namespace plus github repository with continuous
deployment of a gov.uk prototype kit site.

Add template files for gov.uk prototype kits

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-repos/resources/repos.tf

We require a separate ECR repo for the workers that will be using
queues when publishing forms.

Form Builder - Add separate editor web and worker ECR repos

---

bin/auto-delete-namespace.rb
lib/cp_env/namespace_deleter.rb
spec/namespace_deleter_spec.rb

We now have resources which require the github
terraform provider. Initialising this provider
requires a "token" and "owner" terraform variable.
This change amends the namespace deleter so that
as well as creating a `main.tf`, it also creates a
`variables.tf` and `versions.tf` file from the
templates in the 
`namespace-resources-cli-template/resources`
directory. 
This ensures that all required terraform variables
are declared when the deleter script runs
`terraform apply`.

Update the namespace deleter script

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-product-page-prod/certificates.yaml

A second domain has been added to the namespace and the certificate
needs adding for the URL - moj-forms.service.justice.gov.uk

Added new URL to certificates.yaml.

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/cloud-platform-demo/00-namespace.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/cloud-platform-demo/01-rbac.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/cloud-platform-demo/02-limitrange.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/cloud-platform-demo/03-resourcequota.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/cloud-platform-demo/04-networkpolicy.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/cloud-platform-demo/resources/basic-auth.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/cloud-platform-demo/resources/ecr.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/cloud-platform-demo/resources/github-repo.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/cloud-platform-demo/resources/main.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/cloud-platform-demo/resources/serviceaccount.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/cloud-platform-demo/resources/variables.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/cloud-platform-demo/resources/versions.tf

This is for an end of sprint demo on 2021-02-05, and should be deleted
after that date, along with the github repository:
https://github.com/ministryofjustice/cloud-platform-demo

Add cloud-platform-demo prototype kit namespace

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/dso-monitoring-prod/resources/serviceaccount.tf

Installing the helm chart for Prometheus Blackbox exporter is failing with this error:
`Error: UPGRADE FAILED: could not get information about the resource: serviceaccounts "blackbox-exporter-prometheus-blackbox-exporter" is forbidden: User "system:serviceaccount:***:cd-serviceaccount" cannot get resource "serviceaccounts" in API group "" in the namespace "***"`
Furthermore, we are deploying servicemonitors to monitor certain endpoints, thus needing servicemonitors permissions
Note that all of this works fine using my credentials

Extend service account permissions

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/dso-monitoring-prod/resources/serviceaccount.tf

Apologies for this, I should've checked the helm chart in a bit more detail.
As far as I can tell, this should be it:
```
agoneygarcia-deniz@L0943 dso-monitoring-prod % helm upgrade --install prometheus-blackbox-exporter prometheus-community/prometheus-blackbox-exporter --set pspEnabled=false --dry-run
Release "prometheus-blackbox-exporter" does not exist. Installing it now.
NAME: prometheus-blackbox-exporter
LAST DEPLOYED: Fri Feb  5 16:13:52 2021
NAMESPACE: dso-monitoring-prod
STATUS: pending-install
REVISION: 1
TEST SUITE: None
HOOKS:
MANIFEST:
---
apiVersion: v1
kind: ServiceAccount
metadata:
name: prometheus-blackbox-exporter
labels:
app.kubernetes.io/name: prometheus-blackbox-exporter
app.kubernetes.io/instance: prometheus-blackbox-exporter
app.kubernetes.io/managed-by: Helm …
```

configmaps permissions were missing too :'(

---

bin/apply
bin/apply-namespace-changes
lib/cp_env/namespace_dir.rb
spec/namespace_dir_spec.rb

For long-running operations, such as upgrading RDS
instances, we have to pause the apply pipeline for
**every** namespace, so that it doesn't alter the
namespace in which the long-running change is 
happening (which has unpredictable effects).
Repeatedly having to pause/unpause the apply 
pipeline is cumbersome, so this change creates a
mechanism by which individual namespaces can be
skipped.
The `CpEnv::NamespaceDir#apply` method is called
by both the `apply` and `apply-namespace-changes`
pipeline jobs, so the class needs a way to know if
the "skip namespaces" feature should be applied or
not.
This change adds an `enable_skip_namespaces` flag
for that purpose, and sets it to `true` in the 
`apply` script, and `false` in the 
`apply-namespace-changes` script.
With `enable_skip_namespaces` …

Enable apply pipeline to skip namespaces

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-production/02-limitrange.yaml

We discovered pods were sitting at the current memory limit pretty much constantly, which we suspect results in some timeouts.

Increase memory for Book a Secure Move production pods

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-domain-events-dev/resources/hmpps-interventions-topic.tf

The new namespace is intended as the shared place for all domain event topics

Move interventions SNS topic to hmpps-domain-events-dev

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-domain-events-dev/resources/hmpps-intervention-events-topic.tf

We're moving SNS topics to `hmpps-domain-events-{env}` namespaces so they are all discoverable in the same place.
This is part 2 of 2: adding the topic to its destination
Part 1 of 2 was #4254, 28b2ba1d340b347be652d2d349ba11e35db1524a
Related to the previous attempt of moving the topic in one go: #4252 and its revert: #4253.

Re-adds the interventions SNS topic to domain-events

---

namespace-resources-cli-template/00-namespace.yaml

depends on https://github.com/ministryofjustice/cloud-platform-cli/pull/70
> Do not merge until the new version of the CLI has been released. Otherwise, people will not be able to create namespaces via the CLI.

Add "ReviewAfter" namespace annotation

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-uat/05-serviceaccount.yaml

Add a pod/exec permission line - this will be used by the bot to issue hardcoded DB instructions
*not* passed through from the bot user
We have an issue with uat pod DB's not initializing correctly, this will allow the bot to respond to
`uat-reset-db ap1234` and issue a `kubectl exec <snip> -- rake db:migrate && rake db:seed` 
command to the pod in question

Update service account

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-pin-phone-monitor-qa/resources/iam.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-pin-phone-monitor-qa/resources/s3.tf

The intention of this low privilege IAM user is that BT will use it to upload files to an MoJ S3 bucket. The ideal would be BT providing their own IAM user for S3 cross-account access. Unfortunately, the BT team don't have the means to create and manage an AWS Account. 
Discussed with AWS account team and agreed on a low privilege user whereby the creds don't rotate automatically as they do now due to the random number generated as part of the user name in the terraform.

Update pins bt s3 upload user

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-domain-events-dev/resources/hmpps-interventions.tf

https://github.com/ministryofjustice/hmpps-interventions-service/pull/98 has switched to the new one, so we no longer need to maintain the fallback name
Cleans up #4284

Remove old secret from interventions

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-uat/05-prometheus.yaml

Update the UAT environment:
- Update the existing long request alert to exclude the statement of case requests because it often takes longer than 2 seconds. This reduces alerts/messages pollution.
- Add a new prometheus alert to alert when the statement of cases request is taking longer than 10 seconds

LAA Apply UAT: seperate prometheus alert for document upload request

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-saas-live/00-namespace.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-saas-live/01-rbac.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-saas-live/02-limitrange.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-saas-live/03-resourcequota.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-saas-live/04-networkpolicy.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-saas-live/05-circleci-service-account.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-saas-live/editor-service-account.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-saas-live/editor-workers-service-account.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-saas-live/metadata-api-service-account.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-saas-live/resources/editor.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-saas-live/resources/main.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-saas-live/resources/metadata_api.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-saas-live/resources/variables.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-saas-live/resources/versions.tf

This creates the required bits and pieces for the Live environment for
the upcoming Editor:
- formbuilder-saas-live namespace
- postgres db for the editor
- postgres db for the metadata api
- service account for the editor
- service account for the editor workers
- service account for the metadata api
- service account for circle ci
- usual network policies and rbac
Leaving out prometheus at this point. Will be added once we start to deploy the apps.

Form Builder - New formbuilder-saas-live namespace

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-services-live-dev/01-rbac.yaml

This adds the necessary permissions for the future Editor worker service account to interact with the formbuilder-services-live-dev namespace

Form Builder - Editor service account permission to formbuilder-services-live-dev

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-services-live-production/01-rbac.yaml

This adds the necessary permissions for the future Editor worker service account to interact with the formbuilder-services-live-production namespace

Form Builder - Editor service account permission to formbuilder-services-live-production

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-staging/05-prometheus.yaml

Update the staging environment:
- Update the existing long request alert to exclude the statement of case requests because it often takes longer than 2 seconds. This reduces alerts/messages pollution.
- Add a new prometheus alert to alert when the statement of cases request is taking longer than 10 seconds
Similar to the UAT change [here](https://github.com/ministryofjustice/cloud-platform-environments/pull/4324)

LAA Apply Staging: seperate prometheus alert for document upload request 

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/poornima-dev/resources/elasticsearch.tf

If unpinned the module will pickup Terraform 0.13 upgrades.

Pin ns_annotation module to 0.0.2

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-interventions-preprod/05-serviceaccount-circleci.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-interventions-preprod/resources/elasticache.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-interventions-preprod/resources/rds.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-interventions-preprod/resources/variables.tf

This gets the pre-prod environment inline with the current development
environment, with the exception of the `hmpps-domain-events` topic.
That change was already promoted to preprod in 3e4291e

IC-926: Apply interventions dev changes to preprod

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/pact-broker-prod/00-namespace.yaml

So that people can find how it's deployed

Point to the github repo that deploys the Pact broker

---

lib/cp_env/terraform.rb
spec/terraform_spec.rb

This change allows us to run Terraform 0.12, 0.13 and 0.14 in the pipeline at the same time.

Terraform plan and  apply to check the contents of versions.tf and select respective binary

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-saas-test/05-circleci-service-account.yaml

The metadata api circleci service account needs to permission to set cronjobs

Form Builder - Cronjob permissions

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-interventions-prod/05-serviceaccount-circleci.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-interventions-prod/resources/elasticache.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-interventions-prod/resources/rds.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-interventions-prod/resources/variables.tf

This gets the prod environment inline with the current pre-prod
environment, with the exception of the `hmpps-domain-events` topic.
That change was already promoted to prod in 2c0b0b619f9cec7469383f580e9ea77b23007ba2
Related: #4369

Apply interventions preprod changes to production

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-saas-test/05-circleci-service-account.yaml

The previous PR added the cronjobs to the wrong api group. The "Batch" API group needs to have the cronjob permissions

Form Builder - Batch cronjob permissions

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-cla-frontend-staging/resources/s3.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-cla-frontend-staging/resources/variable.tf

Intentionally created for public access. I heard there were cron jobs running weekly which turn the access to buckets from public to private. What do we need to do in order to be exempted from this just like how laa-cla-backend is exempted.

LAA CLA Frontend Staging S3 Bucket

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-dev/06-service-account.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-prod/06-service-account.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-stage/06-service-account.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-test/06-service-account.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-uat/06-service-account.yaml

The Crime Apps team would like to create a network policy (https://github.com/ministryofjustice/laa-court-data-adaptor/pull/411) but the circleci user doesn't have permission.
This PR grants circleci user permission to do so.

Grant Circle CI user access to networkpolicies resource

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-dev/06-service-account.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-prod/06-service-account.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-stage/06-service-account.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-test/06-service-account.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-uat/06-service-account.yaml

Grants permission to laa-court-data-adaptor circleci user to `servicemonitors` resource on
the apiGroup `monitoring.coreos.com`.
Fixes error:
```
Error: UPGRADE FAILED: rendered manifests contain a resource that already exists. Unable to continue with update: could not get information about the resource: servicemonitors.monitoring.coreos.com "laa-court-data-adaptor-monitor" is forbidden: User "system:serviceaccount:laa-court-data-adaptor-dev:circleci" cannot get resource "servicemonitors" in API group "monitoring.coreos.com" in the namespace "laa-court-data-adaptor-dev"
```
for all namespaces.

Grant permission to circleci user to servicemonitors resource

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/peoplefinder-demo/resources/rds.tf

Our concourse pipeline fails with the error:
```
Error: Error modifying DB Instance cloud-platform-5dd2bf4aa0e9fe08: InvalidParameterCombination: Cannot upgrade postgres from 12.5 to 12.3
```
https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/environments-terraform/jobs/apply-live-1/builds/83#L60368cf1:20257

Bumping minor RDS version to reflect live

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-saas-live/05-circleci-service-account.yaml

The form builder saas live will setup a cronjob and the service account circleci should have the necessary permissions to do this.
The error that is raising at the moment when deploying to the namespace: ` cannot get resource "cronjobs" in API group "batch" in the namespace "formbuilder-saas-live"`
This PR will solve the build error above.

Add cronjob and jobs permission to formbuilder saas live

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-saas-live/resources/metadata_api.tf

The metadata API app will save all forms metadata and store versioning
for them so let's increase to a high number and monitor (future PR).

Increase metadata api db size in saas live

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/contact-moj-production/resources/rds.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/contact-moj-staging/resources/rds.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/parliamentary-questions-development/resources/rds.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/track-a-query-demo/resources/rds.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/track-a-query-development/resources/rds.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/track-a-query-production/resources/rds-new.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/track-a-query-qa/resources/rds.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/track-a-query-staging/resources/rds.tf

The Terraform module for RDS instances sets the auto minor update to
true as default. This coupled with pinning the minor versions creates a
Terraform error:
```
Error: Error modifying DB Instance cloud-platform-assadasd:
InvalidParameterCombination: Cannot upgrade postgres from 12.5 to 12.3
```
To remedy this, we will have to remove the pinned minor version and give
users the ability to pin in the future. In module 5.13.1 onwards, you
can now set the `auto_minor_version_upgrade` to false and then pin your
version.
https://github.com/ministryofjustice/cloud-platform-terraform-rds-instance/compare/5.13...5.13.1

Remove minor version from RDS

---

lib/cp_env/terraform.rb

The pingdom provider is now available in the registry and hence we no longer need to store it locally in the tools-image. But the terraform init fails with below:
```Error: Failed to install legacy providers required by state
Found unresolvable legacy provider references in state. It looks like these
refer to in-house providers. You can update the resources in state with the
following command:
terraform state replace-provider registry.terraform.io/-/pingdom registry.terraform.io/russellcardullo/pingdom
```
This script checks if the init fails, update the terraform state and retry the terraform init.
This has to be reverted once the pingdom upgrade to 3.1 is completed.

Add tf_state_replace for namespaces which has pingdom  tf 0.13

---

lib/cp_env/terraform.rb

Revert PR "Add tf_state_replace for namespaces which has pingdom  tf 0.13 (#4432)"
This reverts commit f46792b926262297589000c1062859a061d571c0.
This is a one time change and no longer needed.

Revert #4432

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/moj-ds-accessibility-audit/00-namespace.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/moj-ds-accessibility-audit/01-rbac.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/moj-ds-accessibility-audit/02-limitrange.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/moj-ds-accessibility-audit/03-resourcequota.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/moj-ds-accessibility-audit/04-networkpolicy.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/moj-ds-accessibility-audit/resources/basic-auth.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/moj-ds-accessibility-audit/resources/ecr.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/moj-ds-accessibility-audit/resources/github-repo.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/moj-ds-accessibility-audit/resources/main.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/moj-ds-accessibility-audit/resources/serviceaccount.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/moj-ds-accessibility-audit/resources/variables.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/moj-ds-accessibility-audit/resources/versions.tf

The MOJ Design System is going through an accessibility audit. We're creating a demo site for the auditors so that they can test the components in context.
I've put the ownership as OPG and my personal email on it so that we can trace the site back if there are any queries. Since this site isn't for public consumption, I hope that this is acceptable.

Create MOJDS accessibility test site

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-saas-live/07-prometheus.yaml

Fix broken Prometheus rule, causing Prometheus to crashloop
Out of hours change is required, responding to a broken configuration of Prometheus caused by the 'environment|upper' statement in this message. Rather than remove the rule, I changed the message output and confirmed Prometheus validation.
Some work around Prometheus rule validation should following this commit.
The error message seen in config was as follows:
```
level=error ts=2021-03-07T13:49:27.831Z caller=manager.go:946
component="rule manager" msg="loading groups failed"
err="/etc/prometheus/rules/prometheus-prometheus-operator-kube-p-prometheus-rulefiles-0/formbuilder-saas-live-fb-alerting-saas-live.yaml:
group \"formbuilder-saas-rules\", rule 4, \"RDSLowStorage\": annotation
\"message\": template: __alert_RDSLowStorage:1: …
```

Fix broken Prometheus rule, causing Prometheus to crashloop

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/alexhaslehurst-dev/resources/versions.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/davidread-dev/resources/versions.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/dstest/resources/versions.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/jacob-hello-world-dev/resources/versions.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/jason-demo/resources/versions.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/jason-lab/resources/versions.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/mayowa-hello-world-test-dev/resources/versions.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/mogaal-test/resources/versions.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/poornima-dev/resources/elasticsearch.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/poornima-dev/resources/versions.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/poornima-pt-kit/resources/versions.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/poornima-staging/resources/versions.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/rja-sandbox/resources/versions.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/ryanforsyth-dev/resources/versions.tf

This commit informs Terraform to use the 0.14 binary in the
cloud-platform-environments pipeline. The result of this change should
be a clean init and apply.

Bump playground Terraform state to 0.14

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-saas-live/01-rbac.yaml

The service token cache is using the second service account so
we need to add the necessary permission for the service token cache
app to get config maps from the saas live namespace

Add second service account for formbuilder saas live namespace

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-complexity-of-need-staging/certificate.yaml

The Complexity of Need microservice will use the staging hostname:
complexity-of-need-staging.hmpps.service.justice.gov.uk
This commit adds a certificate which can be used by the ingress.

Add a certificate for custom hostname

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/family-mediators-api-production/prometheus.yml

We are going to split the generic prometheus rules we have in the c100-application-production namespace, into their own namespaces.
More PRs will be raised for the other namespaces.

Add prometheus rules to family mediators api namespace

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/disclosure-checker-production/prometheus.yml

We are going to split the generic prometheus rules we have in the c100-application-production namespace, into their own namespaces.
This is the first PR, more will be raised for the other namespaces.

Add prometheus rules to disclosure checker namespace

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/fj-cait-production/prometheus.yml

We are going to split the generic prometheus rules we have in the c100-application-production namespace, into their own namespaces.
More PRs will be raised for the other namespaces.

Add prometheus rules to fj-cait namespace

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/c100-application-production/prometheus.yml

We've split the generic prometheus rules into their own namespaces in PRs #4487, #4488 and #4489.
Now, these rules are updated to only apply to the namespaces related to the C100 service and nothing else.
This is in anticipation to a service hand over to HMCTS.

Make prometheus specific for c100-application namespaces

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-dev/resources/rds.tf

Enables RDS performance insights on the Book a Secure Move dev database

enable performance_insights_enabled

---

bin/delete-namespace.rb

KUBE_CONFIG_PATH is expected when running the script manually inside the tools image. The pipeline already has that.

Add KUBE_CONFIG_PATH env variable

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-interventions-research/05-serviceaccount-circleci.yaml

To address
`
Error from server (Forbidden): error when retrieving current configuration of:
Resource: "batch/v1, Resource=jobs", GroupVersionKind: "batch/v1, Kind=Job"
Name: "clean-and-migrate-user-research-env", Namespace: "hmpps-interventions-research"
from server for: "user_research/reset_env.yaml": jobs.batch "clean-and-migrate-user-research-env" is forbidden: User "system:serviceaccount:***********************:circleci" cannot get resource "jobs" in API group "batch" in the namespace "hmpps-interventions-research"
`

Allow CircleCI to manage Jobs in interventions

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/c100-application-production/prometheus.yml

Related ticket raised here:
https://github.com/ministryofjustice/cloud-platform/issues/2786
This changes the severity so alerts are routed to a different channel. This is part of the service hand over to HMCTS PET team.

Change severity alert route in C100 prometheus rules

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-cla-frontend-staging/05-serviceaccount-circleci.yaml

This amends the service account to put the resources 'developments' and 'ingresses' into more up to date apiGroups for laa-cla-frontend-staging.

laa-cla-frontend-staging service account update

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-saas-test/06-prometheus.yaml

This adds the alerts for RDS storage limits and failed Delayed Jobs for
the formbuilder-saas-test namespace.

Form Builder - Alerting for saas-test namespace

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-saas-test/06-prometheus.yaml

Form Builder - Use correct severity level for test namespace

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-saas-live/07-prometheus.yaml

This adds the alerting necessary for the Live namespace for our Editor app.
Co-authored by: Brendan Butler <brendan.butler@digital.justice.gov.uk>

Form Builder - Add delayed job alerting for saas Live namespace

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-saas-test/06-prometheus.yaml

This adds an alert for any failed cronjobs in the formbuilder-saas-test namespace

Form Builder - Add alert for failed cronjob in saas-test

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-saas-live/07-prometheus.yaml

This adds an alert for any failed cronjobs in the formbuilder-saas-live namespace

Form Builder - Add alert for failed cronjob in saas-live

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-ems-dev/00-namespace.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-ems-dev/resources/route53.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-ems-dev/resources/variables.tf

The original non production domains of acquisitive-crime.(dev|test|preprod).electronic-monitoring.service.justice.gov.uk were too long for AWS ACM, see [AWS ACM Docs](https://docs.aws.amazon.com/acm/latest/APIReference/API_RequestCertificate.html#API_RequestCertificate_RequestParameters)
> DomainName
> 
> Fully qualified domain name (FQDN), such as www.example.com, that you want to secure with an ACM certificate. Use an asterisk (*) to create a wildcard certificate that protects several sites in the same domain. For example, *.example.com protects www.example.com, site.example.com, and images.example.com.
> 
> The first domain name you enter cannot exceed 64 octets, including periods. Each subsequent Subject Alternative Name (SAN), however, can be up to 253 octets in length.
> 
> Type: …

Short Domains for HMPPS EMS AC Non Production Accounts

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-staging/06-ingress.yaml

This is so that we can filter out malicious attacks on our service.
ModSecurity is an open source, cross platform web application firewall (WAF) developed by Trustwave’s SpiderLabs.
I followed the guide here https://user-guide.cloud-platform.service.justice.gov.uk/documentation/other-topics/modsecurity.html#modsecurity-web-application-firewall

Add modsecurity to implement secure firewall on staging for laa-apply

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-staging/06-ingress.yaml

Related to https://github.com/ministryofjustice/cloud-platform-environments/pull/4535
Remove the trailing / on the domain name as requested by cloud platform.

Remove trailing forward slash on application url

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-uat/06-ingress.yaml

Add modsecurity to implement secure firewall on **UAT** environment for laa-apply
This is so that we can filter out malicious attacks on our service.
ModSecurity is an open source, cross platform web application firewall (WAF) developed by Trustwave’s SpiderLabs.
I followed the guide here https://user-guide.cloud-platform.service.justice.gov.uk/documentation/other-topics/modsecurity.html#modsecurity-web-application-firewall

Add modsecurity to our UAT environment on apply for legal aid

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-platform-test-dev/resources/aurora.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-platform-test-dev/resources/variables.tf

Added a custom aurora db module and add a k8s secret for one of our apps: the user datastore.
This will be used as a spike on our test environment so we can test aurora and our application.

Add aurora db to formbuilder platform test dev

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-production/06-ingress.yaml

Add modsecurity to implement secure firewall on **production** environment for laa-apply
This is so that we can filter out malicious attacks on our service.
ModSecurity is an open source, cross platform web application firewall (WAF) developed by Trustwave’s SpiderLabs.
I followed the guide here https://user-guide.cloud-platform.service.justice.gov.uk/documentation/other-topics/modsecurity.html#modsecurity-web-application-firewall****

Add modsecurity ingress firewall for laa apply for legal aid Production

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-ems-prod/resources/route53.tf

As a result of https://github.com/ministryofjustice/cloud-platform-environments/pull/4532 and https://github.com/ministryofjustice/cloud-platform/issues/2798 the EMS design board decided on the following
- mapping.(dev|test|pp).electronic-monitoring.service.justice.gov.uk
- mapping.electronic-monitoring.service.justice.gov.uk

HMPPS EMS Mapping Zone Delegation

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/check-financial-eligibility-uat/05-ingress.yaml

This is to add security and prevent malicious attacks on the service for the UAT environment

Add modsecurity to ingress on check financial eligibility - UAT

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-complexity-of-need-preprod/resources/serviceaccount-circleci.tf

I believe this PR will fix an error that I've encountered whilst trying to get our CircleCI pipeline up and running.
It doesn't seem to be able to deploy to preprod or prod due to missing permissions on the Service Account.
```
User "system:serviceaccount:hmpps-complexity-of-need-preprod:cd-serviceaccount" cannot get resource "configmaps" in API group "" in the namespace "hmpps-complexity-of-need-preprod"
```
See output logs here: https://app.circleci.com/pipelines/github/ministryofjustice/hmpps-complexity-of-need/191/workflows/57ac7eaa-a5e2-487f-8872-2f234dde080f/jobs/750/parallel-runs/0/steps/0-106

Complexity of Need (preprod) | Grant CircleCI access to "configmaps"

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-complexity-of-need-production/resources/serviceaccount-circleci.tf

This PR performs the same change in `production` as #4554 did in `preprod`.
It adds "configmaps" permission to the Service Account used by CircleCI for deployments. We need this to deploy.

Complexity of Need (production) | Grant CircleCI access to "configmaps"

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/cloud-platform-canary-app/02-limitrange.yaml

Following @poornima-krishnasamy's demo, it was recommended that we change this down to 1m to make full use of the hpa.

Change default request limit for canary app

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-uat/06-ingress.yaml

Increase the paranioa level on the modsecurity for laa-apply-for-legal-aid-uat

laa-apply-for-legal-aid-uat : Increase the paranioa level on the modsecurity

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-staging/06-ingress.yaml

Increase the paranioa level on the modsecurity for laa-apply-for-legal-aid-staging

laa-apply-for-legal-aid-staging Increase the paranioa level on the modsecurity 

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-production/06-ingress.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-staging/06-ingress.yaml

Increase the paranioa level on the modsecurity for laa-apply-for-legal-aid-production

laa-apply-for-legal-aid-production: Increase the paranioa level on the modsecurity 

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/check-financial-eligibility-uat/05-ingress.yaml

Increase the paranioa level on the modsecurity for check-financial-eligibility-**uat**

check-financial-eligibility-uat: Increase the paranioa level on the modsecurity

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/check-financial-eligibility-staging/05-ingress.yaml

Increase the paranioa level on the modsecurity for check-financial-eligibility-**staging**

check-financial-eligibility-staging : Increase the paranioa level on the modsecurity

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/check-financial-eligibility-production/05-ingress.yaml

Increase the paranioa level on the modsecurity for check-financial-eligibility-production

check-financial-eligibility-production : Increase the paranioa level on the modsecurity 

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/c100-application-production/prometheus.yml
namespaces/live-1.cloud-platform.service.justice.gov.uk/disclosure-checker-production/prometheus.yml
namespaces/live-1.cloud-platform.service.justice.gov.uk/family-mediators-api-production/prometheus.yml
namespaces/live-1.cloud-platform.service.justice.gov.uk/fj-cait-production/prometheus.yml

Note: this is a multi-namespace PR for simplicity, as I'm doing the same thing in 4 namespaces. Let me know if you prefer 4 separate PRs.
Remove the `IncreasedHTTPErrors` prometheus alert as it is becoming increasingly annoying with all the bots scans and probing lately.
We have other, service-side monitoring alerts with Sentry which are more accurate to detect real issues with "real" users (and not bots), so for the time being we are removing the prometheus one.

Remove http error rate prometheus alert

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/manage-intelligence-dev/resources/batch-queue.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/manage-intelligence-dev/resources/update-queue.tf

This PR creates two AWS SQS queues for the manage-intelligence-dev namespace:
* Create ims_index_update_queue, dead letter queue and k8s secrets.
* Create ims_index_batch_queue, dead letter queue and k8s secrets.

AR-1104: Add two queues which are used for elastic search index rebuilds

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-interventions-dev/resources/analytical-platform-access.tf

Our daily data extraction needs to push files to an S3 bucket that is
currently provisioned and managed by the Analytical Platform
This change adds a policy so that our apps can access those buckets and
pushes the related secrets into the namespace

Add policy to access Analytical Platform S3 bucket

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-interventions-dev/resources/analytical-platform-access.tf

So that the application codebase doesn't need to know how the analytical
platform bucket is configured. It can get all details from the secret
Follows up on #4604

IC-1505: Add AP bucket name to the secret

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-interventions-dev/05-serviceaccount-circleci.yaml

To fix
https://app.circleci.com/pipelines/github/ministryofjustice/hmpps-interventions-service/1742/workflows/36ace87f-7c00-4b63-9fa4-62805b8602ac/jobs/5824
`Error: UPGRADE FAILED: rendered manifests contain a resource that already exists. Unable to continue with update: could not get information about the resource: cronjobs.batch "data-extractor" is forbidden: User "system:serviceaccount:***********************:circleci" cannot get resource "cronjobs" in API group "batch" in the namespace "***********************"`
Effectively copies #4518 to dev env

IC-1505: Add job/cronjob permissions to CircleCI @ hmpps-interventions-dev

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-interventions-dev/resources/reporting-landing-access.tf

Creates a new user and policy to access the reporting landing S3 bucket (for NDMIS ETL).
This follow the same pattern as commit 93310682ef1b7e82a4c112dcf14b6043b05e5a3a for the Analytical Platform landing bucket.
📝 The S3 bucket details are from [this Slack thread](https://mojdt.slack.com/archives/C01H4UPCM43/p1618419546020700?thread_ts=1618399263.010600&cid=C01H4UPCM43)

Add policy to access reporting landing zone S3 bucket

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-dev-lgfs/resources/rds.tf

Add RDS access keys to secret
Required for investigation and testing of
DB snapshotting, upgrade and/or migration.

[cccd-dev-lgfs] Add RDS access keys to secret

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-dev-lgfs/resources/rds.tf

Bump postgres 9.6 --> 13
Test bumping postgres RDS db instance
from 9.6 to 13 (13.2 being the minor version
available at time of writing).

Bump postgres 9.6 --> 13

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-platform-test-dev/03-resourcequota.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-platform-test-dev/resources/user-datastore.tf

1. Increase instance of Postgres database from small to medium
2. Increase pod limit from 50 to 100, to scale sideways for pods.

Formbuilder - Upgrading user datastore to handle more concurrent connections.

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-dev-lgfs/resources/rds.tf

Bump cp rds terraform module 5.14.1 --> 5.15
Grants `rds:DescribeDBEngineVersions` privileges
which are useful for seeing upgrade paths for current
version using, for example:
```
aws rds describe-db-engine-versions \
--engine postgres \
--engine-version 9.6.20 \
--region <> \
--endpoint https://rds.<region>.amazonaws.com \
--output text --query '*[].ValidUpgradeTarget[?IsMajorVersionUpgrade==`true`].{EngineVersion:EngineVersion}'
```

Bump cp rds terraform module 5.14.1 --> 5.15

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-interventions-research/resources/reporting-landing-access.tf

Details from https://mojdt.slack.com/archives/C01H4UPCM43/p1618419546020700?thread_ts=1618399263.010600&cid=C01H4UPCM43
This follow the same pattern as commit 93310682ef1b7e82a4c112dcf14b6043b05e5a3a for the Analytical Platform landing bucket

interventions-research: Add policy to access reporting landing zone S3 bucket

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-interventions-preprod/resources/reporting-landing-access.tf

Details from https://mojdt.slack.com/archives/C01H4UPCM43/p1618419546020700?thread_ts=1618399263.010600&cid=C01H4UPCM43
This follow the same pattern as commit 93310682ef1b7e82a4c112dcf14b6043b05e5a3a for the Analytical Platform landing bucket

interventions-preprod: Add policy to access reporting landing zone S3 bucket

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-interventions-prod/resources/reporting-landing-access.tf

Details from https://mojdt.slack.com/archives/C01H4UPCM43/p1618419546020700?thread_ts=1618399263.010600&cid=C01H4UPCM43
This follow the same pattern as commit 93310682ef1b7e82a4c112dcf14b6043b05e5a3a for the Analytical Platform landing bucket

interventions-prod: Add policy to access reporting landing zone S3 bucket

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-dev-lgfs/resources/rds.tf

Create a new database using old postgres engine version
and restore it from snapshot. Modify the secrets to
use those of the new database.
Questions:
- Do we need to skip the apply pipleine first? separately?
- Are there parameter group considerations?
- With the secrets recreated will I just need to restart the web servers?

Create new database from preupgrade snapshot

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/manage-intelligence-dev/resources/rds-aurora.tf

The RDS Aurora modules doesn't currently support major upgrades so reverting the previous PR to upgrade from v11.8 to v12/4

AR-1240- Revert RDS Aurora version upgrade 

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-platform-live-production/03-resourcequota.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-platform-live-production/resources/user-datastore.tf

The platform needs upgrading to cater for more traffic and ensuring
that service can cope with increased number of concurrent users.

Upgrading the Live Production User Datastore instance and storage.

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-dev-lgfs/resources/rds.tf

Upgrading Postgres for CCCD dev-lgfs environment to version 13.

Upgrade to PG 13 on cccd-dev-lgfs

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-hmrc-interface-uat/resources/rds.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-hmrc-interface-uat/resources/variables.tf

This is to fix the "No stored state was found for the given workspace in the given backend." ,
updated to latest RDS module v5.16 which got a fix for it.

Update laa-hmrc-interface-uat to latest rds module

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-services-live-production/03-resourcequota.yaml

Live services have 2 pods per services, we have reached 84% of pods in
the namespace. Increasing the number of pods will allow new services to be deployed.

Increase the number of pods available within namespace

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-dev/prometheus-custom-alerts-ccic-dev.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-prod/prometheus-custom-alerts-ccic-prod.yaml

Remove the "Node disk space low" alert from out environments. This alert is not useful and since the most recent CP deployment, is erroneously firing multiple times a day.

claim-criminal-injuries removed misfiring alert

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/manage-intelligence-dev/resources/elasticsearch.tf

This is to trigger a restart of the manage-intelligence cluster and will be reduced to 3 again shortly.

AR-1354: Increase elasticsearch nodes from 3 (default) to 4 - in manage-intelligence.

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/parliamentary-questions-staging/02-limitrange.yaml

The Parliamentary Questions app is having problems with pods being reset (OOMKilled) regularly in all environments.  Testing to see if increasing the available memory will stop the resets on Staging.

Increase PQ Staging env memory allocation.

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-interventions-preprod/01-rbac.yaml

The current team has dozens of people who don't _actually_ need access
to pre-prod. This wouldn't worry me, but unfortunately, this environment
will have live data on it

Switch interventions team on pre-prod

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-interventions-prod/01-rbac.yaml

The current team has dozens of people who don't _actually_ need access
to production

Switch interventions team on prod

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/prisoner-content-hub-development/resources/s3.tf

This PR adds a CORS rule to the S3 bucket on the dev environment.  This will allow us to upload files from Drupal directly to S3, and enable the file upload progress bar functionality.

Add CORS rule to S3 dev to allow file upload progress in Drupal

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/prisoner-content-hub-staging/resources/s3.tf

This PR adds a CORS rule to the S3 bucket on the staging environment for prisoner-content-hub. This will allow us to upload files from Drupal directly to S3, and enable the file upload progress bar functionality.
PR for the dev environment has already been merged: https://github.com/ministryofjustice/cloud-platform-environments/pull/4854

Add CORS rule to S3 to allow file upload progress in Drupal - staging

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/mogaal-test/05-hello-world-stack.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/mogaal-test/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/mogaal-test/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/mogaal-test/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/mogaal-test/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/mogaal-test/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/mogaal-test/05-hello-world-stack.yaml

Tested routed policies between live-1 (kops) and live (eks). Target domain is https://mogaal-test.live.cloud-platform.service.justice.gov.uk/ and weight is 50/50

Routing policies

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-interventions-preprod/10-alerts.yaml

They're essentially a copy of  #4913 but routed differently on the preprod environment

Add interventions preprod alerts

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-assess-risks-and-needs-dev/resources/rds.tf

- Add `kubernetes_secret` `hmpps_assess_risks_and_needs_dev_rds_secret` to create secret with new name
- Remove the old secret in a follow-up PR

Add RDS secret to ARN Dev without environment name

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/prisoner-content-hub-production/resources/elasticsearch.tf

As part of debugging ElasticSearch red cluster status issues we think a larger instance type will help (https://mojdt.slack.com/archives/C57UPMZLY/p1623247521299600?thread_ts=1623246302.297800&cid=C57UPMZLY).

Increase prisoner content hub Elasticsearch resources

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-frontend-production/02-limitrange.yaml

The current resourcing is bellow the default Node heap size. This brings it in-line with that and addresses some performance issues.

Increase the CPU and memory available to pods in Book a Secure Move prod

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-cla-frontend-training/resources/s3.tf

Also reorders the two origins to be consistent with how we have it in
the staging namespace

Add scheme to cla-frontend-training cors

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-services-test-dev/03-resourcequota.yaml

This is to enable more forms to run in the test service, the
namespace is currently at just over 85%.
We have a piece of work to manage the services that are not used
to be removed.

Formbuilder Services - Update to the namespace quota from 100 to 150

---

namespaces/live.cloud-platform.service.justice.gov.uk/cloud-platform-reports-dev/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/cloud-platform-reports-dev/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/cloud-platform-reports-dev/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/cloud-platform-reports-dev/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/cloud-platform-reports-dev/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/cloud-platform-reports-dev/resources/dynamodb.tf
namespaces/live.cloud-platform.service.justice.gov.uk/cloud-platform-reports-dev/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/cloud-platform-reports-dev/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/cloud-platform-reports-dev/resources/versions.tf

Overview
---
This PR connects to https://github.com/ministryofjustice/cloud-platform/issues/2857 and relates to the migration of the reports frontend. It just performs a straight copy from the live-1 directory to live in the hopes that we can deploy there and perform a full migration.

Move cloud-platform-reports-dev from live-1 to live cluster

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/court-probation-dev/01-rbac.yaml

Adding DPS-tech so they can run parts of the dps-project-bootstrap process without being in the probation-in-court team

✨ PIC-1494 add DPS-tech to RBAC admin

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-cla-frontend-training/resources/pingdom.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-cla-frontend-training/resources/versions.tf

Requires https://github.com/ministryofjustice/cloud-platform/issues/2953 to be resolved first

Add pingdom resource for laa-cla-frontend-training namespace

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/cloud-platform-migration/resources/ecr.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/cloud-platform-migration/resources/serviceaccount.tf

I was unaware that the `githubRepository` value had to match the namespace. As the namespace name and the repository name are different in this case, the deployment GH action fails. This change should fix that.

Add correct value in github action call

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-workload-dev/05-certificate.yaml

Will this create the certificate and put it into the named secret, or do we have to create the certificate ourselves. If so are there any instructions we can follow please?

WFP-322 add certificate for hmpps-workload-dev

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-test/07-service-monitor.yaml

Point service monitor to metrics endpoint on LAA Court Data Adaptor's `laa-court-data-adaptor-test` namespace.

[LAA Court Data Adaptor - test] Point service monitor to metrics endpoint

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/ppud-replacement-dev/resources/rds.tf

It looks like t2 database instances are not supported by postgresql 13.

Fix the ppud-replacement-dev-rds terraform.

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-dev/08-prometheus-rule.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-prod/08-prometheus-rule.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-stage/08-prometheus-rule.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-test/08-prometheus-rule.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-uat/08-prometheus-rule.yaml

* Add alert rules for new metrics endpoint
* Remove erroneous long request alerts (they were not alerting us about the expected thing)
Must be merged before https://github.com/ministryofjustice/cloud-platform-environments/pull/5069 for zero downtime for alerting.

[LAA Court Data Adaptor] Add alert rules for new metrics endpoint

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-dev/07-service-monitor.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-prod/07-service-monitor.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-stage/07-service-monitor.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-test/07-service-monitor.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-uat/07-service-monitor.yaml

We're creating a new dedicated service for Prometheus to expose data in https://github.com/ministryofjustice/laa-court-data-adaptor/pull/581. The endpoint name is no longer `http` but `metrics`.
Dependent on https://github.com/ministryofjustice/cloud-platform-environments/pull/5078.

[LAA Court Data Adaptor] - Change endpoint name to metrics

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/peoplefinder-development/02-limitrange.yaml

We are having trouble running a report and think that it is related to
running out of RAM, upping the RAM here to test that hypothesis.

Increase memory on peoplefinder dev env

---

namespace-resources-cli-template/resources/variables.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/davidread-dev/resources/ecr.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/davidread-dev/resources/variables.tf

This should inject the ECR creds into Github secrets for my namespace.
It didn't work last time because I didn't have the github_owner variable.
I'm leaving out the github_token variable also mentioned, to see if it
is really necessary.

Enable ECR creds for my namespace

---

namespaces/live.cloud-platform.service.justice.gov.uk/cloud-platform-migration/resources/serviceaccount.tf

This commit connects to https://github.com/ministryofjustice/cloud-platform/issues/2956 and relates to the migration of an application from one cluster (live-1) to another (live).

Add live cluster name to serviceaccount interpolation

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/ppud-replacement-preprod/resources/s3.tf

Reverts ministryofjustice/cloud-platform-environments#5127
This stops the pipeline concourse-user from accessing the bucket and hence the pipeline fails with error 
```
Error: error reading S3 Bucket (cloud-platform-03a24ea5a50651e8e138d4cd7b3e626e): Forbidden: Forbidden
```
This also prevents any the webops team IAM user to checks it from AWS console. 
Need to discuss with @dazoakley about alternative approach.

Revert "Restrict access to the `manage-recalls` S3 bucket to the VPC."

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/ppud-replacement-preprod/resources/s3.tf

Overview
---
Restrict S3 bucket access from Live-1 cluster. This PR connects to a conversation in [slack](https://mojdt.slack.com/archives/C57UPMZLY/p1626337226078500) that requires the s3 bucket access to be restricted to the app only. After deliberation, it was decided this can be achieved with live-1 IP restrictions. We considered VPC restriction to include all clusters, but this was unsuccessful.

Restrict s3 bucket from object access outside of live-1

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/ppud-replacement-prod/resources/s3.tf

This is the prod change of https://github.com/ministryofjustice/cloud-platform-environments/pull/5135
This will restrict object access to applications running within the
live-1 cluster only.
ref PUD-255

Restrict S3 object access to the live-1 cluster

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/ppud-replacement-preprod/resources/rds.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/ppud-replacement-preprod/resources/s3.tf

This sets up an S3 bucket for the data import from Lumen, and a SQL
Server instance to house the transferred database content.
refs PUD-278, PUD-279

Setup an S3 bucket and SQL Server DB to house transferred Lumen data.

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-domain-events-dev/resources/manage-pom-cases.tf

Environment: staging
Grants permission for the Manage POM Cases service (`offender-management-*` namespaces) to publish events to the HMPPS Domain Events SNS topic.

Add Manage POM Cases to HMPPS Domain events

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/money-to-prisoners-prod/resources/rds.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/money-to-prisoners-prod/resources/route53.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/money-to-prisoners-prod/resources/versions.tf

Trial of adding multiple TXT records to a little-used domain. Other changes are cosmetic to appease terraform indentation rules.
Replaces #5168 which was split into this and #5169

Add verification TXT record for Prisoner Money’s sendmoneytoaprisoner.justice.gov.uk domain

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/money-to-prisoners-prod/resources/main.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/money-to-prisoners-prod/resources/route53.tf

Completes #5170 by adding verification TXT records to remaining (and important) domains:
• prisoner-money.service.justice.gov.uk
• send-money-to-prisoner.service.gov.uk

Add verification TXT record for Prisoner Money’s domains

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/prisoner-content-hub-development/resources/s3.tf

For the prisoner-content-hub dev environment.
Relevant Trello card: https://trello.com/c/ZVSfPcz6/225-fix-the-mysterious-missing-file-issue
We have seen unwanted file deletions occurring, and believe that the recent inclusion of this CORS config is the reason why (see https://github.com/ministryofjustice/cloud-platform-environments/pull/4854).
The `DELETE` method via CORS is not required, file deletions should always happen via a server side request.  So this method can be safety removed.

Removing DELETE method from S3 CORS config - dev

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/prisoner-content-hub-staging/resources/s3.tf

For the prisoner-content-hub staging environment.
Relevant Trello card: https://trello.com/c/ZVSfPcz6/225-fix-the-mysterious-missing-file-issue
We have seen unwanted file deletions occurring, and believe that the recent inclusion of this CORS config is the reason why (see https://github.com/ministryofjustice/cloud-platform-environments/pull/4863).
The DELETE method via CORS is not required, file deletions should always happen via a server side request. So this method can be safety removed.

Removing DELETE method from S3 CORS config - staging

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/prisoner-content-hub-production/resources/s3.tf

For the prisoner-content-hub production environment.
Relevant Trello card: https://trello.com/c/ZVSfPcz6/225-fix-the-mysterious-missing-file-issue
We have seen unwanted file deletions occurring, and believe that the recent inclusion of this CORS config is the reason why (seehttps://github.com/ministryofjustice/cloud-platform-environments/pull/4867).
The DELETE method via CORS is not required, file deletions should always happen via a server side request. So this method can be safety removed.

Removing DELETE method from S3 CORS config - production 

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-pin-phone-monitor-dev/resources/rds-aurora.tf

First step in migrating the dev pin phone database to rds aurora to test the migration process prior to performing the same task in production.
A pre-migration snapshot of the dev db has been taken and will be used to create the new rds aurora cluster. The postgres version has been kept at 10.x but will be upgraded post migration to v12.6 in order to take advantage of the partman partitioning extension.
Once complete and new rds aurora instance verified, the old rds postgres db will be removed from this namespace.

PAT-1981 - Migrate rds postgres instance to rds aurora postgres

---

.github/workflows/check-permissions.yaml

This check connects to
https://github.com/ministryofjustice/cloud-platform/issues/2990 and will
mitigate the risk of a member outside a namespace's team having the
ability to amend/delete resources in said namespace.
In summary the action will:
- collect all amended files in a PR.
- if the file path contains a namespace:
check if the PR creator/owner is in the namespaces rbac team
(i.e. github team).
- if not:
write the the PR and fail the check.

Add rbac permissions check GitHub Action

---

.github/workflows/check-permissions.yaml

An example of this error can be found here:
https://github.com/ministryofjustice/cloud-platform-environments/pull/5205/checks?check_run_id=3162240748
and is fixed in the fork defined in this commit.

Use forked version of `get-changed-files` to fix error

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/ppud-replacement-preprod/resources/rds.tf

It wasn't passing over from the module, so this hardcodes it...

Put the PPUD replica database name in the secret

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-dev/resources/rds.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-dev/resources/redis.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-dev/resources/variables.tf

Set a maintenance window for hmpps-book-secure-move-api-dev

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-dev/resources/rds.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-dev/resources/variables.tf

We need to set an explicit backup window to ensure that it doesn't overlap with the maintenance window.
```
executing: cd namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-dev/resources; terraform apply -auto-approve
Command: cd namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-dev/resources; terraform apply -auto-approve failed.
Error: Error modifying DB Instance cloud-platform-4be37a4047a3b230: InvalidParameterValue: The backup window and maintenance window must not overlap.
status code: 400, request id: b436571c-e74b-4e12-aaf2-18a56d4c1b5a
on .terraform/modules/rds-instance/main.tf line 104, in resource "aws_db_instance" "rds":
104: resource "aws_db_instance" "rds" {
```

Set a backup window for hmpps-book-secure-move-api-dev

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-staging/resources/rds.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-staging/resources/redis.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-staging/resources/variables.tf

Set a maintenance window for hmpps-book-secure-move-api-staging

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-frontend-staging/resources/redis.tf

Set a maintenance window for hmpps-book-secure-move-frontend-staging

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-uat/resources/rds.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-uat/resources/redis.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-uat/resources/variables.tf

Set a maintenance window for hmpps-book-secure-move-api-uat

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-frontend-uat/resources/redis.tf

Set a maintenance window for hmpps-book-secure-move-frontend-uat

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-frontend-preprod/resources/redis.tf

Set a maintenance window for hmpps-book-secure-move-frontend-preprod

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-preprod/resources/rds.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-preprod/resources/redis.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-preprod/resources/variables.tf

Set a maintenance window for hmpps-book-secure-move-api-preprod

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-production/resources/rds.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-production/resources/redis.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-production/resources/variables.tf

Set a maintenance window for hmpps-book-secure-move-api-production

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-frontend-production/resources/redis.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-frontend-production/resources/versions.tf

Set a maintenance window for hmpps-book-secure-move-frontend-production

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-uat/resources/redis.tf

This sets a snapshot window for Redis to match the backup window for RDS. Previously we weren't setting this because the parameter wasn't supported by the module, but we've hit an issue where the chosen window by AWS conflicts with our desired maintenance window.

Set snapshot window for hmpps-book-secure-move-api-uat

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-dev/resources/redis.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-preprod/resources/redis.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-production/resources/redis.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-staging/resources/redis.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-frontend-preprod/resources/redis.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-frontend-production/resources/redis.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-frontend-staging/resources/redis.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-frontend-uat/resources/redis.tf

This sets the same snapshot window for all Redis databases for Book a Secure Move. This follows on from https://github.com/ministryofjustice/cloud-platform-environments/pull/5252 where we had an issue that the maintenance window conflicted with the snapshot window, and therefore had to be set explicitly.

Set a consistent snapshot window

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-decide-prototype/resources/github-repo.tf

This protection is currently getting in the way as I'm the only developer working on the repo. It can be reconfigured later as more developers/designers use the repo.

Remove branch protection from laa-decide-prototype

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-dev/resources/messaging-queues.tf

```
Error: Error putting IAM user policy crime-apps-dev-prosecution-concluded-queue: LimitExceeded: Maximum policy size of 2048 bytes exceeded for user cp-sqs-02f5ffc4ea89
```

[LAA Court Data Adaptor] Use one IAM user per SQS queue (dev)

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-cla-backend-training/07-prometheus-k8.yaml

- Creates a PromethusRule as part of following the [creating your own custom alerts guide](https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#create-a-prometheusrule). 
- Rules used are from already set prometheus rules from other repos in namespace repo. Thus these rules are what other people/teams are using.
- Use rules from other repos instead of in favour of what the ticket suggested

Create Prometheus Rules for training namespace

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-cla-backend-production/07-prometheus-k8.yaml

- Creates a PromethusRule as part of following the [creating your own custom alerts guide](https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#create-a-prometheusrule). 
- Rules used are from already set prometheus rules from other repos in namespace repo. Thus these rules are what other people/teams are using.
- Use rules from other repos instead of in favour of what the ticket suggested

Create prometheus rules for production

---

namespaces/live.cloud-platform.service.justice.gov.uk/how-out-of-date-are-we/ingress.yaml

With out external-dns annotation, opa policy will reject ingress

Add external-dns annotation to how-out-of-date-are-we

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-dev/resources/messaging-queues.tf

```
Error: Error putting IAM user policy crime-apps-dev-prosecution-concluded-queue: LimitExceeded: Maximum policy size of 2048 bytes exceeded for user cp-sqs-02f5ffc4ea89
```

[LAA Court Data Adaptor] Use separate IAM user for prosecution_concluded DL queue (dev)

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-uat/resources/messaging-queues.tf

```
Error: Error putting IAM user policy crime-apps-uat-prosecution-concluded-queue: LimitExceeded: Maximum policy size of 2048 bytes exceeded for user cp-sqs-02f5ffc4ea89
```

[LAA Court Data Adaptor] Remove unused SQS queues (UAT)

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-stage/resources/messaging-queues.tf

```
Error: Error putting IAM user policy crime-apps-stage-prosecution-concluded-queue: LimitExceeded: Maximum policy size of 2048 bytes exceeded for user cp-sqs-02f5ffc4ea89
```

[LAA Court Data Adaptor] Remove unused SQS queues (stage)

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-prod/resources/messaging-queues.tf

```
Error: Error putting IAM user policy crime-apps-prod-prosecution-concluded-queue: LimitExceeded: Maximum policy size of 2048 bytes exceeded for user cp-sqs-02f5ffc4ea89
```

[LAA Court Data Adaptor] Remove unused SQS queues (prod)

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-uat/resources/messaging-queues.tf

```
Error: Error putting IAM user policy crime-apps-uat-prosecution-concluded-queue: LimitExceeded: Maximum policy size of 2048 bytes exceeded for user cp-sqs-02f5ffc4ea89
```

[LAA Court Data Adaptor] Use separate IAM user for prosecution_concluded DL queue (UAT)

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/pathfinder-dev/resources/athena-iam.tf

Further changes to athena policy in dev to allow djbc access to data catalogs and run queries against specific database following: https://docs.aws.amazon.com/athena/latest/ug/datacatalogs-example-policies.html

PAT-2045 - Fix Athena policy permissions

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/disclosure-checker-production/prometheus.yml
namespaces/live-1.cloud-platform.service.justice.gov.uk/family-mediators-api-production/prometheus.yml
namespaces/live-1.cloud-platform.service.justice.gov.uk/fj-cait-production/prometheus.yml

We are removing this alert from 3 of our namespaces.
This alert is misleading, and lately has been triggering without apparent reason.

Remove the NamespaceMissing prometheus alert

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/pathfinder-dev/resources/athena-iam.tf

Required to get the database metadata. Any queries against the database are restricted by workgroup. The GetDatabase action returns just the database metadata from the Athena data catalog.

PAT-2045 - restrict athena iam policy to the AWS data catalog. 

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-cla-backend-staging/07-prometheus-k8.yaml

We would get alerts of KubePodCrashLooping due to extrapolation done by the rate function in Prometheus. This would give us results like 1.02 which is > 1 and would trigger the alerts.
The round function will fix this issue and ensure we deal with restarts as integer values.

Add round function to prometheus rules fix rounding errors

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-cla-backend-training/07-prometheus-k8.yaml

We would get alerts of KubePodCrashLooping due to extrapolation done by the rate function in Prometheus. This would give us results like 1.02 which is > 1 and would trigger the alerts.
The round function will fix this issue and ensure we deal with restarts as integer values.

LAA-CLA-BACKEND-TRAINING Add round function to prometheus rules fix rounding errors

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-cla-backend-production/07-prometheus-k8.yaml

We would get alerts of `KubePodCrashLooping` due to extrapolation done by the rate function in Prometheus. This would give us results like 1.02 which is > 1 and would trigger the alerts.
The round function will fix this issue and ensure we deal with restarts as integer values.

LAA-CLA-BACKEND-PRODUCTION Add round function to prometheus rules fix rounding errors

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-stage/resources/messaging-queues.tf

```
Error: Error putting IAM user policy crime-apps-stage-prosecution-concluded-queue: LimitExceeded: Maximum policy size of 2048 bytes exceeded for user cp-sqs-02f5ffc4ea89
```

[LAA Court Data Adaptor] Use separate IAM user for prosecution_concluded DL queue (stage)

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-test/resources/messaging-queues.tf

```
Error: Error putting IAM user policy crime-apps-test-prosecution-concluded-queue: LimitExceeded: Maximum policy size of 2048 bytes exceeded for user cp-sqs-02f5ffc4ea89
```

[LAA Court Data Adaptor] Use separate IAM user for prosecution_concluded DL queue (test)

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-cla-backend-production/07-prometheus-k8.yaml

Previously the round function was being applied too late.
It was being applied after we had checked if the avg no. of restarts is > 1. At this point, the round function basically isn't doing anything since the calculation/> 1 check is already done

LAA-CLA-BACKEND-PRODUCTION Amend query so it rounds before it does the > 1 check

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-cla-backend-staging/07-prometheus-k8.yaml

Previously the round function was being applied too late. 
It was being applied after we had checked if the avg no. of restarts is > 1. At this point, the round function basically isn't doing anything since the calculation/> 1 check is already done

LAA-CLA-BACKEND-STAGING Amend query so it rounds before it does the boolean (>1) check

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-cla-backend-training/07-prometheus-k8.yaml

Previously the round function was being applied too late. 
It was being applied after we had checked if the avg no. of restarts is > 1. At this point, the round function basically isn't doing anything since the calculation/> 1 check is already done

LAA-CLA-BACKEND-TRAINING Amend query so it rounds before the boolean (> 1) check

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-prod/resources/messaging-queues.tf

```
Error: Error putting IAM user policy crime-apps-prod-prosecution-concluded-queue: LimitExceeded: Maximum policy size of 2048 bytes exceeded for user cp-sqs-02f5ffc4ea89
```

[LAA Court Data Adaptor] Use separate IAM user for prosecution_concluded DL queue (prod)

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/workforce-management/resources/github-repo.tf

Thanks, but we don't need branch protection for a prototyping repo

Update github-repo.tf to remove branch protection

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-prod/resources/messaging-queues.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-prod/resources/variables.tf

Increased the visibility timeout for the 3 SQS. This is to avoid message duplications so that consumers don't pick the same message if this is being processed. 
more information on the user story:  https://dsdmoj.atlassian.net/browse/LASB-640

increased visibility timeout to 120 seconds to avoid the message 

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-staging/resources/pingdom.tf

CCCD alerts need to be sent to the channel laa-cccd-alerts in Slack. The
relevant integration ID has been set here:
ministryofjustice/cloud-platform#3136

Integration ID for Pingdom in CCCD (staging)

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-production/resources/pingdom.tf

CCCD alerts need to be sent to the channel laa-cccd-alerts in Slack. The
relevant integration ID has been set here:
ministryofjustice/cloud-platform#3136

Integration ID for Pingdom in CCCD (production)

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/poornima-staging/resources/s3-sqs.tf

This will allow s3 to send notifications to an encrypted sqs queue.
Related to: https://github.com/ministryofjustice/cloud-platform/issues/3128
This fix the pipeline error 
`Error: error putting S3 Bucket Notification Configuration: InvalidArgument: Unable to validate the following destination configurations`

Test sqs module branch allow-s3

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-hmrc-interface-uat/resources/s3.tf

This will not store real PII so does not need encryption at rest
the production environment will require it, see
[this issue](https://github.com/ministryofjustice/cloud-platform/issues/3150)

Add S3 bucket for LAA-HMRC interface UAT

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/poornima-staging/resources/s3-messaging.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/prisoner-content-hub-development/resources/s3.tf

We are currently unable to retrieve object versions.  When using the AWS api, the following error is returned:
```
An error occurred (AccessDenied) when calling the ListObjectVersions operation: Access Denied
```
This PR adds in the policy to allow the operation.  
Relevant slack conversation: https://mojdt.slack.com/archives/C57UPMZLY/p1629801520280700

Prisoner content hub - Add ListBucketVersions permission - dev

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/prisoner-content-hub-staging/resources/s3.tf

This PR adds in the ListBucketVersions permission to the S3 bucket on staging, allowing us to retrieve deleted files.
This has already been merged to dev and tested there, see: https://github.com/ministryofjustice/cloud-platform-environments/pull/5403

Prisoner content hub - Add ListBucketVersions permission - staging

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/prisoner-content-hub-production/resources/s3.tf

This PR adds in the ListBucketVersions permission to the S3 bucket on staging, allowing us to retrieve deleted files.
This has already been merged to dev and tested there, see: https://github.com/ministryofjustice/cloud-platform-environments/pull/5403

Prisoner content hub - Add ListBucketVersions permission - live

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/prisoner-content-hub-staging/resources/s3.tf

This updates staging in the same way as https://github.com/ministryofjustice/cloud-platform-environments/pull/5423 did for development. (See previous PR for further details on why the change is necessary).

Moving the AllowListBucketVersions policy from user to bucket_policy - staging

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/prisoner-content-hub-production/resources/s3.tf

This PR adds the `ListBucketVersions` permission to the production S3 bucket.
This was previously added as user policy.  But was reverted (https://github.com/ministryofjustice/cloud-platform-environments/pull/5420) after we discovered setting `user_policy` in our s3.tf was overriding the one set in [main.tf](https://github.com/ministryofjustice/cloud-platform-terraform-s3-bucket/blob/main/main.tf)
This PR adds back in the permission, but using the `bucket_policy` instead of `user_policy`.  As `bucket_policy` isn't set in main.tf, and is also already being set in this file.  So safe to assume we are not overwriting any permissions set externally with this change.
We have already updated [dev](https://github.com/ministryofjustice/cloud-platform-environments/pull/5423) and …

Adding ListBucketVersions to bucket policy - prisoner content hub - production

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/contact-moj-development/resources/rds.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/cts-prototype-dev-poc/resources/rds.tf

allow_minor_version_upgrade default set to true, the minor version upgrade occurs automatically during the maintenance window.
This is to fix the pipeline failure as a minor version upgrade has already been completed, as a user-specified minor version, the pipeline is trying to downgrade to a specified version.

Remove minor version for postgres RDS module

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/prisoner-content-hub-development/resources/s3.tf

Enabling logging on S3 bucket.
This should fix https://github.com/ministryofjustice/cloud-platform/issues/3126

Prisoner content hub - enable S3 logging - development

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/peoplefinder-development/resources/rds.tf

This solves the error:
```
Error: Error modifying DB Instance cloud-platform-xxxx: InvalidParameterCombination: Cannot upgrade postgres from 12.7 to 12.5
```
As the [minor version variable](https://github.com/ministryofjustice/cloud-platform-terraform-rds-instance/blob/main/main.tf#L127) isn't set this will cause an error if Terraform tries to set it to its declared version in this file. You can't downgrade an RDS instance so this causes the above error.

Fix: Remove minor version declaration

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/prisoner-content-hub-development/resources/s3.tf

Adding additional configuration required to enable logging.
This fixes issue introduced by previous PR: https://github.com/ministryofjustice/cloud-platform-environments/pull/5471

Prisoner content hub - Fix missing S3 config - development

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/prisoner-content-hub-staging/resources/s3.tf

This will allow us to investigate the file deletion issue:
https://trello.com/c/ZVSfPcz6/89-fix-the-mysterious-missing-file-issue
and https://github.com/ministryofjustice/cloud-platform/issues/3126
Note that we should remove this and clear out the logs as soon as it is no longer required.

Prisoner content hub - Enable S3 logging - staging

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/prisoner-content-hub-production/resources/s3.tf

This will allow us to investigate the file deletion issue:
https://trello.com/c/ZVSfPcz6/89-fix-the-mysterious-missing-file-issue
and https://github.com/ministryofjustice/cloud-platform/issues/3126
Note that we should remove this and clear out the logs as soon as it is no longer required.

Prisoner content hub - Enable S3 logging - production

---

.github/workflows/check-ingress-annotation.yml
cmd/check-ingress/Dockerfile
cmd/check-ingress/check-ingress.go
cmd/check-ingress/check-ingress_test.go
cmd/check-ingress/go.mod
cmd/check-ingress/go.sum
pkg/ingress/go.mod
pkg/ingress/ingress.go
pkg/ingress/ingress_test.go

Overview
---
This PR connects https://github.com/ministryofjustice/cloud-platform/issues/3074 and relates to the requirement to check the required ingress annotation the in live-1 cluster.
What's in this PR?
---
This PR contains the following:
- An ingress package that generates a json list of namespaces that doesn't contain an ingress annotation.
- A GitHub Action that will perform the check and comment on a PR if it fails.
- A `cmd` directory and `check-ingress` command that performs the check if live-1 annotation is set. If not, it'll fail.
- A Dockerfile to allow the GitHub Action to pull it execute the ingress check.

Add GitHub Action check for ingress annotation

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/prisoner-content-hub-development/resources/s3.tf

This reverts changes from https://github.com/ministryofjustice/cloud-platform-environments/pull/5473

Prisoner content hub - disable logging - development

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/prisoner-content-hub-staging/resources/s3.tf

This reverts changes from https://github.com/ministryofjustice/cloud-platform-environments/pull/5496

Prisoner content hub - disable logging - staging

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/prisoner-content-hub-production/resources/s3.tf

This reverts changes from https://github.com/ministryofjustice/cloud-platform-environments/pull/5497
Logging is no longer required and should be disabled to avoid taking up unnecessary storage space on S3.

Prisoner content hub - disable logging - production

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-interventions-preprod/resources/rds.tf

Then a cronjob will take both the production and pre-production
credentials and pg_dump/pg_restore
Replaces a custom script in https://github.com/ministryofjustice/hmpps-interventions-ops/commit/4803fcd01bf77748d3659860057d06d2da293409

Inject pre-prod DB credentials for refresh process

---

namespaces/live.cloud-platform.service.justice.gov.uk/user-roles.yaml

This will allow all users to perform `kubectl get ns --all` for example.

Copy default user roles from live-1 to live

---

pkg/namespace/namespace.go
pkg/namespace/namespace_test.go

By calling and passing the hoodaw host name to this function we can
return a listed of all namespaces in a cluster. In fact not just
namespaces, but namespace details and specifics that are outlined in our
https://reports.cloud-platform.service.justice.gov.uk/hosted_services
page.
To call this package you simply:
```go
import
github.com/ministryofjustice/cloud-platform-environments/pkg/namespace
host :=
"https://reports.cloud-platform.service.justice.gov.uk/hosted_services"
allNamespaces, err := namespace.GetAllNamespaces(&host)
```
That will return you the report, to which you can do things like:
```go
for _, namespace := range allNamespaces {
fmt.Println(namespace.TeamName)
}
```

Add `GetAllNamespaces` function to `namespace` package

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/ppud-replacement-dev/resources/pingdom.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/ppud-replacement-preprod/resources/pingdom.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/ppud-replacement-prod/resources/pingdom.tf

NOTE: PROD is currently commented out to stop alert noise - we've not
deployed the application(s) to PROD yet, so the pingdom check is
currently red.

Add (slack) integration ID's for PPUD pingdom checks.

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-services-live-production/03-resourcequota.yaml

MOJ Forms (formbuilder) deploys it's service into live production with 2 replicas.
We have received an alert warning us we have reached 82% of the quota.
Increasing the quota will give us some overhead while we carry out a review of the forms deployed.

Increase the quota of pods in the services-live-prod namespace

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/how-out-of-date-are-we/ingress.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/licences-prod/99-redirect_old_url_ingress.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/maintenance-pages/ingress.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/mogaal-test/05-hello-world-stack.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/monitoring/kibana-dsd-oauth2-proxy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/how-out-of-date-are-we/ingress.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/mogaal-test/05-hello-world-stack.yaml

Now we have OPA policy to block ingress without this annotation.

Update ingress with external-dns annotation

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/ppud-replacement-dev/02-limitrange.yaml

This is due to clamav having issues starting up.

Increase the default CPU/RAM limits in ppud-replacement-dev

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/ppud-replacement-preprod/02-limitrange.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/ppud-replacement-preprod/05-serviceaccount-circleci.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/ppud-replacement-prod/02-limitrange.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/ppud-replacement-prod/05-serviceaccount-circleci.yaml

This pushes the changes made in order to run the clamav helm chart in
the `ppud-replacement-dev` namespace forward to the `preprod` and `prod`
tiers.

Changes needed to run clamav in higher tiers

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/prisoner-content-hub-development/resources/elasticache.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/prisoner-content-hub-development/resources/variables.tf

This PR removes cluster support from elasticache (by removing the `number_cache_clusters` setting, cluster support should then be disabled).
As cluster support is not yet supported by Drupal. See https://www.drupal.org/project/redis/issues/2900947

Prisoner content hub - elasticache remove cluster support - dev

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/prisoner-content-hub-development/resources/elasticache.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/prisoner-content-hub-development/resources/variables.tf

This reverts https://github.com/ministryofjustice/cloud-platform-environments/pull/5708 and explicitly sets number of clusters to 1, to override the setting of 2 from https://github.com/ministryofjustice/cloud-platform-terraform-elasticache-cluster/blob/main/variables.tf and therefore disabling cluster mode.

Prisoner content hub - elasticache set clusters to 1 - dev

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/prisoner-content-hub-development/resources/variables.tf

This fixes issue in build: 
```module.drupal_redis.aws_elasticache_replication_group.ec_redis: Creating...
Error: Error creating ElastiCache Replication Group (cp-66508e899082f511): InvalidParameterCombination: When using automatic failover, there must be at least 2 cache clusters in the replication group.
status code: 400, request id: 014cf333-a243-4dc3-9ae9-61cc2e4175ff
on .terraform/modules/drupal_redis/main.tf line 59, in resource "aws_elasticache_replication_group" "ec_redis":
59: resource "aws_elasticache```

Prisoner content hub - elasticache set cluster back to 2 - dev

---

namespaces/live.cloud-platform.service.justice.gov.uk/manage-my-prison-dev/resources/athena-iam.tf
namespaces/live.cloud-platform.service.justice.gov.uk/manage-my-prison-dev/resources/athena.tf

… mimicking the IAM policy as set in `pathfinder-dev` namespace.
This should give Athena & Glue access to the S3 bucket created in this namespace.

Add an AWS Athena resource for ‘Manage my prison’ `dev` namespace

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/prisoner-content-hub-development/resources/elasticache.tf

This PR switches Redis version from 5 to 4.  This is to avoid an issue reported in the Drupal Redis integration with using version 5 on elasticache:  https://www.drupal.org/project/redis/issues/3151976

Prisoner content hub - elasticache redis downgrade - dev

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/prisoner-content-hub-development/resources/elasticache.tf

Use version 4.0.10 as 4.0.13 is not supported.
See error on build https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/environments-terraform/jobs/apply-namespace-changes-live-1/builds/292
```
Error: Error creating ElastiCache Replication Group (cp-66508e899082f511): InvalidParameterCombination: Cannot find version 4.0.13 for redis
```

Prisoner content hub - elasticache fix redis version number - dev

---

.github/workflows/iam-role-policy-changes-check.yaml

I don't think we need to completely halt a PR that has an IAM change, I think a comment is enough.

Remove the requirement for change

---

namespaces/live.cloud-platform.service.justice.gov.uk/elsa-relevant-search-staging/resources/pingdom.tf

As we are going to kill the `live-1` namespace, we don't need to have 2 pingdom checks with 2 hosts, we only need the `live` one.

Update pingdom host for migrated namespace

---

namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-base-adapter-test/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-base-adapter-test/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-base-adapter-test/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-base-adapter-test/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-base-adapter-test/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-base-adapter-test/circleci-service-account.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-base-adapter-test/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-base-adapter-test/resources/versions.tf

On the MoJ forms team (a.k.a Formbuilder team) we decide to start the migration to the live cluster with a small app called "base adapter". This PR follow [this guide](https://user-guide.cloud-platform.service.justice.gov.uk/documentation/other-topics/migrate-to-live-sa-github-actions.html#migrating-serviceaccount-module-for-github-actions-to-the-quot-live-quot-cluster)

Migrate form builder base adapter to new live cluster

---

namespaces/live.cloud-platform.service.justice.gov.uk/elsa-relevant-search-production/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/elsa-relevant-search-production/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/elsa-relevant-search-production/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/elsa-relevant-search-production/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/elsa-relevant-search-production/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/elsa-relevant-search-production/05-certificate.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/elsa-relevant-search-production/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/elsa-relevant-search-production/resources/pingdom.tf
namespaces/live.cloud-platform.service.justice.gov.uk/elsa-relevant-search-production/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/elsa-relevant-search-production/resources/route53.tf
namespaces/live.cloud-platform.service.justice.gov.uk/elsa-relevant-search-production/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/elsa-relevant-search-production/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/elsa-relevant-search-production/resources/versions.tf

Note: despite this being a "production" namespace, it is not publicly available yet or in use, and is mostly a static website so we are willing to accept any risks.
Staging namespace already migrated and working fine so far.

Migrate elsa-relevant-search-production to live cluster

---

namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-repos/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-repos/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-repos/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-repos/resources/repos.tf
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-repos/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-repos/serviceaccount-circleci.yaml

This migrates the formbuilder-repos namespace which contains all the ECR
repos for the platform and service apps.
Co-authored-by: Tomas Destefi <tomas.destefi@digital.justice.gov.uk>
Co-authored-by: Matt Tei <matt.tei@digital.justice.gov.uk>

Form Builder - Migrate formbuilder-repos namespace

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/offender-events-dev/resources/hmpps-tier-offender-events-sub-queue.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/offender-events-dev/resources/hmpps-tier-sub-queue.tf

The pipeline fails as it couldnot find/create resources between clusters. The secrets has to be copied manually.
Revert this PR back once the `offender-events-dev` namespace is migrated to `live`
@carlov20 FYI

Temporary remove cross reference namespace secrets during migration

---

namespaces/live.cloud-platform.service.justice.gov.uk/disclosure-checker-staging/resources/rds.tf

Trying to migrate to new cluster and bump postgres to a major version might not be the best of the ideas.

Keep RDS same as in live-1

---

.checksum
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-means-assessment-dev/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-means-assessment-dev/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-means-assessment-dev/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-means-assessment-dev/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-means-assessment-dev/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-means-assessment-dev/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-means-assessment-dev/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-means-assessment-dev/resources/versions.tf

This is to create a Dev namespace for the new laa-crime-means-assessment service
New Dev namespace has been created on the live cluster using the Cloud Platform CLI

Add Dev namespace for laa-crime-means-assessment service

---

namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-publisher-test/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-publisher-test/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-publisher-test/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-publisher-test/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-publisher-test/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-publisher-test/circleci-service-account.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-publisher-test/publisher-workers-service-account.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-publisher-test/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-publisher-test/resources/publisher.tf
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-publisher-test/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-publisher-test/resources/versions.tf

This moves the Publisher Test namespace to EKS
Co-authored-by: Tomas Destefi <tomas.destefi@digital.justice.gov.uk>

Form Builder - Migrate Publisher Test namespace

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-api-sandbox/02-limitrange.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-dev-lgfs/02-limitrange.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-dev/02-limitrange.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-production/02-limitrange.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-staging/02-limitrange.yaml

Bump max memory limit 2Gi to 3Gi for all pods
We use a scheduler_daemon and sidekiq worker
that when running a particular query against
a prod-like data scale that can exceed the 2Gi limit.

[CCCD namespaces] Bump max memory limit 2Gi to 3Gi for all pods

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-uat/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-uat/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-uat/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-uat/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-uat/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-uat/05-prometheus.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-uat/05-serviceaccount.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-uat/resources/elasticache.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-uat/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-uat/resources/s3.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-uat/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-uat/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-uat/serviceaccount-admin.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-uat/serviceaccount-circleci.yaml

Migrates the `laa-apply-for-legalaid-uat` to the new live cluster. 
This will trigger warnings about missing ingress annotations which can be ignored. We use this namespace for ephemeral test environments based on github branches. Ingress details are set dynamically by a [script](https://github.com/ministryofjustice/laa-apply-for-legal-aid/blob/main/bin/uat_deploy) in the application repo.

Migrate laa-apply-for-legalaid-uat to live

---

.checksum
namespaces/live.cloud-platform.service.justice.gov.uk/apshinytest-dev/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/apshinytest-dev/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/apshinytest-dev/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/apshinytest-dev/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/apshinytest-dev/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/apshinytest-dev/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/apshinytest-dev/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/apshinytest-dev/resources/versions.tf

Adds a new namespace to allow the AP team to test deploying of RShiny
applications to the cloud platform.

Add a new namespace for AP testing

---

pkg/authenticate/authenticate.go

When using this package inside a non-root container, it will not have permissions to write in the HomeDir /home/. Hence write the kubeconfig under /tmp directory

Update kubeconfig path to write in /tmp 

---

namespaces/live.cloud-platform.service.justice.gov.uk/check-financial-eligibility-uat/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/check-financial-eligibility-uat/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/check-financial-eligibility-uat/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/check-financial-eligibility-uat/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/check-financial-eligibility-uat/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/check-financial-eligibility-uat/resources/ecr.tf
namespaces/live.cloud-platform.service.justice.gov.uk/check-financial-eligibility-uat/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/check-financial-eligibility-uat/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/check-financial-eligibility-uat/serviceaccount-admin.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/check-financial-eligibility-uat/serviceaccount-circleci.yaml

Migrates check-finanicial-ability-uat to the new live cluster.
This will trigger warnings about missing ingress annotations which can be ignored. We use this namespace for ephemeral test environments based on github branches. Ingress details are set dynamically by a [script](https://github.com/ministryofjustice/check-financial-eligibility/blob/main/bin/uat_deploy) in the application repo.

Migrate check-financial-eligibility-uat to live

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-interventions-dev/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-interventions-dev/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-interventions-dev/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-interventions-dev/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-interventions-dev/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-interventions-dev/05-serviceaccount-circleci.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-interventions-dev/resources/analytical-platform-access.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-interventions-dev/resources/elasticache.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-interventions-dev/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-interventions-dev/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-interventions-dev/resources/reporting-landing-access.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-interventions-dev/resources/s3.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-interventions-dev/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-interventions-dev/resources/versions.tf

The cross-account definition changes are in a7fedf15cee3e6c33d8ba8e28fa922753b427126 -- I don't know if these are right, could someone review them in-depth, please?

Migrate hmpps-interventions-dev namespace to live cluster

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-interventions-dev/resources/analytical-platform-access.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-interventions-dev/resources/reporting-landing-access.tf

Fixes
```
Error: error creating IAM Role (to-ap-s3-service-account-live): EntityAlreadyExists: Role with name to-ap-s3-service-account-live already exists.
status code: 409, request id: bb99cccd-860b-4e5e-8f59-2e572863d434
```
Introduced by #6185

Make service account names unique per namespace

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-workload-prod/resources/rds-live.tf

The actual value of the db_allocated_storage has to be set when doing snapshot restore. This is to prevent terraform overriding to default value of 10 which throw error during snapshot restore.

Include actual allocated storage

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-domain-events-dev/resources/hmpps-interventions.tf

We no longer use the `hmpps-interventions-research` environment

Remove interventions-research SNS topic secret

---

namespaces/live.cloud-platform.service.justice.gov.uk/elsa-relevant-search-production/prometheus.yml

This is a fully migrated service. Both staging and production envs are on the `live` cluster now. But the production namespace is not really public, as in nobody is using it yet.
Just using the standard prometheus rules we use already in our services.

Add prometheus rules for elsa-relevant-search

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-interventions-preprod/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-interventions-preprod/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-interventions-preprod/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-interventions-preprod/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-interventions-preprod/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-interventions-preprod/05-serviceaccount-circleci.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-interventions-preprod/10-alerts.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-interventions-preprod/resources/analytical-platform-access.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-interventions-preprod/resources/elasticache.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-interventions-preprod/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-interventions-preprod/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-interventions-preprod/resources/reporting-landing-access.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-interventions-preprod/resources/s3.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-interventions-preprod/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-interventions-preprod/resources/versions.tf

Additional changes:
- IRSA (and some DRY) changes in f2cc317438fc8db9a0eb455cf64faad8a6b6614c
- Temporarily disabling adding DB credentials to the prod namespace for a DB refresh job in 6859d3c2eab025eddb7f2cf0bc88f8d86c34a55d

Migrate hmpps-interventions-preprod over to live

---

namespaces/live.cloud-platform.service.justice.gov.uk/prisoner-content-hub-development/resources/s3.tf

This PR updates the allowed origin on the S3 CORS config with the new domain for the cloud platform environment.
Without this change, users are unable to upload files.

Prisoner content hub - dev - update S3 CORS allowed origin

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-interventions-preprod/10-alerts.yaml

We already have exceptional cases covered by Sentry

Remove 5xx ingress alerts from interventions-preprod

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/help-with-prison-visits-prod/resources/rds.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/polygraph-offender-management/resources/rds.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/ppud-replacement-dev/resources/legacy-ppud-api-rds.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/ppud-replacement-preprod/resources/legacy-ppud-api-rds.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/ppud-replacement-prod/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/help-with-prison-visits-dev/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/help-with-prison-visits-preprod/resources/rds.tf

For sql rds which don’t specify db_parameter as [ ], set them to below
db_parameter = [
{
name         = "rds.force_ssl"
value        = "1"
apply_method = "pending-reboot"
}
]

Upgrade RDS sql to use the latest version

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/offender-events-prod/09-prometheus-sqs-sns.yaml

FYI: @markreesmoj . The prometheusrule seems to be failing because of missing quote in one of the rule.

Fix missing quote on SQS-number-of-messages rule

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-supervisions-prototype/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-supervisions-prototype/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-supervisions-prototype/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-supervisions-prototype/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-supervisions-prototype/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-supervisions-prototype/resources/basic-auth.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-supervisions-prototype/resources/ecr.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-supervisions-prototype/resources/github-repo.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-supervisions-prototype/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-supervisions-prototype/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-supervisions-prototype/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-supervisions-prototype/resources/versions.tf

First attempt at deploying this prototype to the cloud. 
The prototype already exists, it's using v11 of the kit on node 16 and this PR goes with:
https://github.com/ministryofjustice/hmpps-manage-supervisions-prototype/pull/396
I've followed instructions in:
https://user-guide.cloud-platform.service.justice.gov.uk/documentation/getting-started/prototype-kit.html
As the prototype repo exists already, I'm guessing the repo will be otherwise untouched?

Configure hmpps-manage-supervisions-prototype

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-prod/02-limitrange.yaml

Increase CPU request from 10 to 25Mi, and memory request from 100 to 250Mi to get back within bounds.
https://grafana.live-1.cloud-platform.service.justice.gov.uk/d/85a562078cdf77779eaa1add43ccec1e/kubernetes-compute-resources-namespace-pods?orgId=1&refresh=10s&var-datasource=default&var-cluster
=&var-namespace=laa-court-data-adaptor-prod&from=now-24h&to=now

[LAA Court Data Adaptor Prod] Increase CPU/memory request

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-ui-dev/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-ui-dev/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-ui-dev/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-ui-dev/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-ui-dev/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-ui-dev/05-servicemonitor.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-ui-dev/certificate.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-ui-dev/prometheus.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-ui-dev/resources/ecr.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-ui-dev/resources/elasticache.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-ui-dev/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-ui-dev/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-ui-dev/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-ui-dev/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-ui-dev/serviceaccount-circleci.yaml

Create live namespace for laa-court-data-ui-dev following instructions from the [documentation](https://user-guide.cloud-platform.service.justice.gov.uk/documentation/other-topics/migrate-to-live.html#step-3-migrate-your-namespace-environment-to-quot-live-quot)

Create live namespace for laa-court-data-ui-dev

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-ui-uat/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-ui-uat/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-ui-uat/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-ui-uat/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-ui-uat/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-ui-uat/05-servicemonitor.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-ui-uat/certificate.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-ui-uat/prometheus.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-ui-uat/resources/elasticache.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-ui-uat/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-ui-uat/resources/pingdom.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-ui-uat/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-ui-uat/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-ui-uat/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-ui-uat/serviceaccount-circleci.yaml

Create live namespace for laa-court-data-ui-uat following instructions from the [documentation](https://user-guide.cloud-platform.service.justice.gov.uk/documentation/other-topics/migrate-to-live.html#step-3-migrate-your-namespace-environment-to-quot-live-quot)

AAC-391 - Migrate UAT environment

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-ui-staging/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-ui-staging/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-ui-staging/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-ui-staging/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-ui-staging/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-ui-staging/05-servicemonitor.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-ui-staging/certificate.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-ui-staging/prometheus.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-ui-staging/resources/elasticache.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-ui-staging/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-ui-staging/resources/pingdom.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-ui-staging/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-ui-staging/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-ui-staging/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-ui-staging/serviceaccount-circleci.yaml

Create live namespace for laa-court-data-ui-staging following instructions from the [documentation](https://user-guide.cloud-platform.service.justice.gov.uk/documentation/other-topics/migrate-to-live.html#step-3-migrate-your-namespace-environment-to-quot-live-quot)

AAC-392 - Migrate Staging Environment to live

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-monitoring/resources/pingdom.tf

The pingdom monitoring for these two services will be controlled using
our Editor app instead of the cloud platform environments repo.
Therefore we can remove them from here.

Form Builder - Remove Pingdom alerts

---

namespaces/live.cloud-platform.service.justice.gov.uk/monitoring/resources/pingdom.tf

This is to match the host in the monitoring namespace.

Update name of pingdom check

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-interventions-dev/01-rbac.yaml

We've decided to simplify authorizations by creating a dev-only team

Change team ownership for interventions

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-ui-production/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-ui-production/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-ui-production/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-ui-production/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-ui-production/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-ui-production/05-servicemonitor.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-ui-production/certificate.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-ui-production/http_status_codes_grafana_dashboard.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-ui-production/kubernetes_pods_dashboard.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-ui-production/prometheus.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-ui-production/resources/elasticache.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-ui-production/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-ui-production/resources/pingdom.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-ui-production/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-ui-production/resources/route53.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-ui-production/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-ui-production/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-ui-production/serviceaccount-circleci.yaml

Create live namespace for laa-court-data-ui-production following instructions from the [documentation](https://user-guide.cloud-platform.service.justice.gov.uk/documentation/other-topics/migrate-to-live.html#step-3-migrate-your-namespace-environment-to-quot-live-quot)

AAC-393 - Migrate to VCD Production to live namespace

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/peoplefinder-development/resources/elasticsearch.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/peoplefinder-production/resources/elasticsearch.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/peoplefinder-staging/resources/elasticsearch.tf

- Remove cloudwatch log group for development and staging
- Reduce the cloudwatch log retention to 60 days
-
@ymao2, as discussed in Slack with @jasonBirchall , are you happy with the changes?

Remove cloudwatch log group for development and staging

---

namespaces/live.cloud-platform.service.justice.gov.uk/create-and-vary-a-licence-api-preprod/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/create-and-vary-a-licence-api-preprod/06-certificate.yaml

Due the the 64-character limit in certificate CNs this PR adds two DNS names, one short, one long.
It failed to create a certificate previously with only the name `create-and-vary-a-licence-api-preprod.hmpps.service.justice.gov.uk` so also added a second, `create-a-licence-api-preprod.hmpps.service.justice.gov.uk`
Also updated the RBAC to include the group dps-production-releases.

CVSL-331: Add a second, shorter DNS name.

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-preprod/resources/rds.tf

We've been experiencing slowdowns recently related to our database being under-provisioned. We expect that upgrading the instance type will improve the performance of our database. I'm doing the upgrade first in our pre-production environment to gauge exactly what the downtime might be like for production.
We've selected the `db.t3.xlarge` instance type, rather than upgrading one level to `db.t3.large` as we expect our database usage to increase quickly over the next few months.
[Jira Ticket](https://dsdmoj.atlassian.net/browse/P4-3424)

Upgrade BaSM preprod database instance type

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-production/resources/rds.tf

We've been experiencing slowdowns recently related to our database being under-provisioned. We expect that upgrading the instance type will improve the performance of our database.
We've selected the `db.t3.xlarge` instance type, rather than upgrading one level to `db.t3.large` as we expect our database usage to increase quickly over the next few months.
[Jira Ticket](https://dsdmoj.atlassian.net/browse/P4-3424)

Upgrade BaSM production database instance type

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-staging/resources/rds.tf

This environment, although not production, is used frequently for various reasons and we often see timeouts. It's used as part of our end to end tests.
I'm hoping that by upgrading the databases from `t2.small` to `t3.medium` we'll get a small performance increase that should reduce the number of issues we see in the environment.

Upgrade BaSM Staging database

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-uat/resources/rds.tf

This environment, although not production, is used frequently for various reasons and we often see timeouts. It's used by our suppliers to test our API.
I'm hoping that by upgrading the databases from `t2.small` to `t3.medium` we'll get a small performance increase that should reduce the number of issues we see in the environment.

Upgrade BaSM UAT database

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-pin-phone-monitor-dev/resources/rds-aurora.tf

Attempt to upgrade RDS Postgres 12.6 -> v13 failed. Upgrade path for a db.t3 is to 12.7 first and then to v13. Graviton chips can go from 12.4 straight to 13.

PPD - Upgrade Dev RDS postgres DB to v12.7

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-events-dev/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-events-dev/resources/hmpps-pre-sentence-report-queue.tf

Adds a queue that receives events from the domain-events topic, which are then read by the Delius message consumer.

PI-53 Add SQS queue for Pre-Sentence Report events

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-api-dev/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-api-dev/resources/variables.tf

After building our new pipeline its noticed that our service account doesnt have the right permissions for helm upgrades. This PR is to apply the variables as statued in the documentation.

AAC-264 - update permissions for service account

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-pin-phone-monitor-prod/resources/s3.tf

Deferred execution of transcribe job requires a data access role with appropriate S3 permissions: 
https://docs.aws.amazon.com/transcribe/latest/dg/API_JobExecutionSettings.html

PPD - Add transcribe data access role to prod

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-interventions-preprod/resources/rds.tf

Consequence of #6819, but couldn't do it in the same PR
This re-enables adding pre-prod DB credentials for weekly database refresh

interventions-prod: Re-enable injecting pre-prod credentials to prod

---

namespaces/live.cloud-platform.service.justice.gov.uk/pact-broker-prod/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/pact-broker-prod/resources/versions.tf

Missed this from #6834, might explain the apply failure in https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/environments-live/jobs/apply-namespace-changes-live/builds/300
🤷 don't know enough about this, sorry
_Edit_ Thanks @razvan-moj and @jasonBirchall for your help

Add github provider configuration to pact-broker 

---

namespaces/live.cloud-platform.service.justice.gov.uk/pact-broker-prod/resources/main.tf

Final piece to make #6834 work
Entire diff for reference
```diff
diff --git a/namespaces/live.cloud-platform.service.justice.gov.uk/pact-broker-prod/resources/main.tf b/namespaces/live.cloud-platform.service.justice.gov.uk/pact-broker-prod/resources/main.tf
index 0fd2f9470..8c3fa83f6 100644
--- a/namespaces/live.cloud-platform.service.justice.gov.uk/pact-broker-prod/resources/main.tf
+++ b/namespaces/live.cloud-platform.service.justice.gov.uk/pact-broker-prod/resources/main.tf
@@ -16,3 +16,8 @@ provider "aws" {
alias  = "ireland"
region = "eu-west-1"
}
+
+provider "github" {
+  token = var.github_token
+  owner = var.github_owner
+}
diff --git a/namespaces/live.cloud-platform.service.justice.gov.uk/pact-broker-prod/resources/serviceaccount-github.tf …
```

Add missing provider configuration to pact-broker

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-dev/resources/pingdom.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-prod/resources/pingdom.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-uat/resources/pingdom.tf

The host is hard-coded, and points to live-1. Fetching from
variables.tf gets the domain name that is independant from
the cluster name.

Fetch domain to be pinged from variables.tf rather than hardcoded

---

namespaces/live.cloud-platform.service.justice.gov.uk/manage-recalls-dev/resources/manage-recalls-api-rds.tf

We're seeing some performance issues in dev due to data volumes, (that
we would expect in prod down the line), increasing the database RAM to
see the impact it has.

Scale the manage-recalls-dev database to a t3.medium.

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-ems-prod/05-serviceaccount.yaml

I am getting the following error when trying to deploy our Grafana Helm chart
```
helm_release.grafana: Creating...
╷
│ Warning: Helm release "grafana" was created but has a failed status. Use the `helm` command to investigate the error, correct it, then run Terraform again.
│ 
│   with helm_release.grafana,
│   on main.tf line 10, in resource "helm_release" "grafana":
│   10: resource "helm_release" "grafana" {
│ 
╵
╷
│ Error: replicasets.apps is forbidden: User "system:serviceaccount:hmpps-ems-prod:github-actions" cannot list resource "replicasets" in API group "apps" in the namespace "hmpps-ems-prod"
│ 
│   with helm_release.grafana,
│   on main.tf line 10, in resource "helm_release" "grafana":
│   10: resource "helm_release" "grafana" {
│ 
╵
ERRO[0012] 1 error occurred:
* exit status …
```

Add `replicaset` Resource and `list` Verb to `app` apiGroup

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-uat/resources/messaging-queues.tf

Introduce a 120 seconds delay to prosecution_concluded SQS queue messages (UAT).
ref. https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-configure-queue-parameters.html

[LAA Court Data Adaptor UAT] Add delay_seconds to prosecution_concluded SQS queue

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-prod/resources/messaging-queues.tf

Introduce a 120 seconds delay to prosecution_concluded SQS queue messages (UAT).
ref. https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-configure-queue-parameters.html

[LAA Court Data Adaptor Prod] Add delay_seconds to prosecution_concluded SQS queue

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-saas-test/03-resourcequota.yaml

Part of our testing we create testable editors which is the editor app
created from a branch. We are testing many bugs and reached the limit
of the namespace which then broke the deployment pipeline.

Increase pod limit for the namespace

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-dev/resources/messaging-queues.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-dev/resources/versions.tf

Adding a visibility timeout param to the SQS to avoid duplicated messages.

Adding visibility_timeout_seconds param for a SQS.

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-saas-test/05-circleci-service-account.yaml

We need to allow the CircleCI service account permissions to apply
horizontal scaling configuration in the formbuilder-saas-test namespace
in the live-1 cluster.

Allow CircleCI service account HPA permissions live-1

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-interventions-prod/resources/pingdom.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-interventions-prod/resources/versions.tf

We had database connection failed errors and I would have expected a
pingdom alert but we never got any -- it was never setup 😅

Add interventions API healthcheck to pingdom

---

namespaces/live.cloud-platform.service.justice.gov.uk/apply-for-compensation-prototype/resources/ecr.tf
namespaces/live.cloud-platform.service.justice.gov.uk/apply-for-compensation-prototype/resources/serviceaccount.tf

Remove repo names used in module. Github repo used in the ecr and service account module is not within MOJ org,
This cause pipelines to fail as it don't have access to that repo

Update namespace apply-for-compensation-prototype

---

namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-dev/resources/ecr.tf

This adds the terraform config to setup the new ECR repo in AWS
for the hale-platform-dev namespace.

Create ECR for new hale-platform namespace

---

namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-dev/resources/rds.tf

Add the RDS configuration for the hale-plaform. WordPress requires a
MYSQL database to connect to rather than PostgreSQL.

Add MYSQL tf config to hale-platform

---

namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-saas-test/03-resourcequota.yaml

The namespace holds not only the master version of the editor but,
separate editors based on a branch. Each one hase 5 pods. We need
some overhead for testing the EKS migration.

This PR increases the pod quota for the test editor

---

namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-monitoring/resources/pingdom.tf

The CJSM User Research Consent form is no longer required. Remove from Pingdom.

Formbuilder: Remove CJSM User Research Consent form from pingdom

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-ui-uat/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-ui-uat/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-ui-uat/resources/variables.tf

The existing github team that we used seems to have been removed. This PR updates the team and email we use for this service so that details are as up to date as possible

AAC-499 - Update UAT Team information

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-ui-staging/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-ui-staging/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-ui-staging/resources/variables.tf

The existing github team that we used seems to have been removed. This PR updates the team and email we use for this service so that details are as up to date as possible

AAC-499 - Update Staging team information

---

namespaces/live.cloud-platform.service.justice.gov.uk/dso-monitoring-prod/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/dso-monitoring-prod/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/dso-monitoring-prod/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/dso-monitoring-prod/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/dso-monitoring-prod/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/dso-monitoring-prod/05-offender-assessment-api-prometheusrule.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/dso-monitoring-prod/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/dso-monitoring-prod/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/dso-monitoring-prod/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/dso-monitoring-prod/resources/versions.tf

This is for monitoring of the digital studio studio hosting prod cluster. Migrate from live-1 to live as per the instructions in step 3.
Note this has a GHA deployment service account.  We will update the associated pipeline

Migration of dso-monitoring-prod namespace to live cluster

---

namespaces/live.cloud-platform.service.justice.gov.uk/dso-monitoring-prod/05-offender-assessment-api-prometheusrule.yaml

dso-monitoring-prod has been migrated to live environment and prometheus is collecting stats correctly.  This temporary change is to test the slack hook.

DSO-1377: test of DSO studio hosting monitoring live-1 migration

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-ui-uat/prometheus.yaml

Major Prometheus-Exporter bundle update to 2.0.0 (https://github.com/discourse/prometheus_exporter/releases/tag/v2.0.0) gave this instruction:
"rename all http_duration metrics to http_request_duration to match prometheus official naming conventions"
Updated expression for Long-Request alert to use new ruby_http_request_duration_sections instead of ruby_http_duration_secconds to prevent alerts not working

VCD UAT - Update HTTP_DURATION metrics to HTTP_REQUEST_DURATION for Prometheus

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-ui-dev/prometheus.yaml

Major Prometheus-Exporter bundle update to 2.0.0 (https://github.com/discourse/prometheus_exporter/releases/tag/v2.0.0) gave this instruction:
"rename all http_duration metrics to http_request_duration to match prometheus official naming conventions"
Updated expression for Long-Request alert to use new ruby_http_request_duration_sections instead of ruby_http_duration_secconds to prevent alerts not working

VCD Dev - Update HTTP_DURATION metrics to HTTP_REQUEST_DURATION for Prometheus

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-ui-production/prometheus.yaml

Major Prometheus-Exporter bundle update to 2.0.0 (https://github.com/discourse/prometheus_exporter/releases/tag/v2.0.0) gave this instruction:
"rename all http_duration metrics to http_request_duration to match prometheus official naming conventions"
Updated expression for Long-Request alert to use new ruby_http_request_duration_sections instead of ruby_http_duration_secconds to prevent alerts not working

VCD PROD - Update HTTP_DURATION metrics to HTTP_REQUEST_DURATION for Prometheus

---

namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-dev/resources/analytical-platform-access.tf
namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-dev/resources/variables.tf

Renaming the target bucket from being derived from the namespace to being specific to the database as it appears in the Analytics Platform.  This will allow us to accommodate future databases within the namespace, e.g. the PSR service.

PIC-1981 Rename target s3 bucket for data exporter

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-incentives-prod/resources/ap-data.tf

HMPPS Incentives applications in `prod` namespace can already get objects from a particular bucket in Analytical Platform. The bucket policy already has listing permissions, so the IRSA policy also needs to mirror this.

Add IRSA permission to list objects in S3 bucket

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-incentives-dev/resources/s3.tf

We're aiming to use the development namespace in the same way as the production one: namely that IRSA is used to grant access to an S3 bucket rather than using access tokens.
It seems that a bucket IAM policy must include a resource even if it's simply the bucket to which it is attached. Hence the policy must refer to the bucket itself – this causes a circular reference unless the generated bucket ARN is not hard-coded.

Use hard-coded S3 bucket ARN in its attached IAM policy for HMPPS Incentives

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-incentives-dev/resources/s3.tf

… because `s3:ListBucket` is not a valid permission and `s3:GetBucketLocation` is unnecessary

Fix HMPPS Incentives testing S3 bucket policy

---

namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-saas-live/05-circleci-service-account.yaml

This gives the circle service account in formbuilder-saas-live namespace
permissions to set horizontal autoscaling configuration

Form Builder - add HPA permissions to saas-live

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmcts-mock-api-dev/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmcts-mock-api-dev/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmcts-mock-api-dev/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmcts-mock-api-dev/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmcts-mock-api-dev/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmcts-mock-api-dev/06-service-account.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmcts-mock-api-dev/resources/ecr.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmcts-mock-api-dev/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmcts-mock-api-dev/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmcts-mock-api-dev/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmcts-mock-api-dev/resources/versions.tf

Migrate hmcts-mock-api-dev namespace to live cluster.

Migrate hmcts-mock-api-dev to live cluster

---

namespaces/live.cloud-platform.service.justice.gov.uk/monitoring/dashboard-golden-signals.yaml

This is currently part of the `generic-service` helm chart used by a lot
of services, but this is producing a **lot** of dashboards.  This
condenses it all down into one so it can be removed from the helm chart
(and remove noise in the dashboards list)
.

Add a generic "Golden Signals" dashboard

---

namespaces/live.cloud-platform.service.justice.gov.uk/manage-recalls-dev/10-manage-recalls-api-dashboard.yaml

This switches the upstream healthcheck visuals to use a ratio rather than a `min` function so it will expose to us when one of our pods is having issues communicating to an upstream.
The following shows a check that has been having inconsistency issues:

Update the manage-recalls-api dashboard

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/calculate-journey-variable-payments-dev/01-rbac.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/calculate-journey-variable-payments-preprod/01-rbac.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/calculate-journey-variable-payments-prod/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-dev/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-preprod/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-production/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-staging/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-uat/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-frontend-preprod/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-frontend-production/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-frontend-staging/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-frontend-uat/01-rbac.yaml

The Calculate journey variable payments, Book a secure move API and Book a secure move frontend apps all fall under the PECS team. We'd like to consolidate the number of GitHub teams we have by removing superfluous teams. This means changing the access rules to reference the new all-encompassing team.
I've raised this as a single commit rather than having a PR for each namespace to save time.

Update PECS namespaces access rules

---

namespaces/live.cloud-platform.service.justice.gov.uk/manage-recalls-dev/10-manage-recalls-api-dashboard.yaml

This meant that we were only showing the request rate from one pod...

Bugfix: use sum rather than max for request rates

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-incentives-prod/resources/s3.tf

…mirroring other environments which own their bucket, whereas this one is owned by a different AWS account. Having matching secrets will mean apps in different namespaces can work in the same systematic way.

INC-236: Add secret to Incentives prod namespace with S3 bucket details

---

namespaces/live.cloud-platform.service.justice.gov.uk/apply-for-legal-aid-prototype/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/apply-for-legal-aid-prototype/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/apply-for-legal-aid-prototype/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/apply-for-legal-aid-prototype/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/apply-for-legal-aid-prototype/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/apply-for-legal-aid-prototype/resources/basic-auth.tf
namespaces/live.cloud-platform.service.justice.gov.uk/apply-for-legal-aid-prototype/resources/ecr.tf
namespaces/live.cloud-platform.service.justice.gov.uk/apply-for-legal-aid-prototype/resources/github-repo.tf
namespaces/live.cloud-platform.service.justice.gov.uk/apply-for-legal-aid-prototype/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/apply-for-legal-aid-prototype/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/apply-for-legal-aid-prototype/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/apply-for-legal-aid-prototype/resources/versions.tf

This is to set up an environment for the apply prototype on cloud platform, so that we can move away from hosting on Heroku

Set up an environment for the apply prototype 

---

namespaces/live.cloud-platform.service.justice.gov.uk/manage-recalls-dev/10-manage-recalls-api-dashboard.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/monitoring/dashboard-golden-signals.yaml

This adds vertical lines (annotations in grafana terminology) whenever a pod creation event is recorded, and labels the annotation with the pod name.
This is useful for identifying issues related to pod creation or application startup.

Add annotations for "pod creation" events

---

namespaces/live.cloud-platform.service.justice.gov.uk/calculate-journey-variable-payments-dev/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/calculate-journey-variable-payments-preprod/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/calculate-journey-variable-payments-prod/01-rbac.yaml

The Github team name has changed for this project and was missed as part of the migration from the live1-1 to the live cluster.
This is linked to this [Jira](https://dsdmoj.atlassian.net/browse/P4-3398) and this [PR](https://github.com/ministryofjustice/cloud-platform-environments/pull/7410).

The team name responsible for this service changed and was missed as part of the migration from live-1 to the live cluster.

---

namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-monitoring/resources/pingdom.tf

The User Research Form will be deleted, remove alert so we do not get notified.

Formbuilder: Remove pingdom alert

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-interventions-dev/06-service-monitor.yaml

All the necessary services in interventions are now labelled with `app:
hmpps-interventions-service`

Simply service matching for prometheus scraping

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-test/resources/messaging-queues.tf

Increase delay_seconds for prosecution_concluded SQS queue (dev) from 2 to 15 minutes.

[LAA Court Data Adaptor] Increase delay_seconds for prosecution_concluded SQS queue (test)

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-stage/resources/messaging-queues.tf

Increase delay_seconds for prosecution_concluded SQS queue (dev) from 2 to 15 minutes.

[LAA Court Data Adaptor] Increase delay_seconds for prosecution_concluded SQS queue (stage)

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-dev/resources/messaging-queues.tf

Increase delay_seconds for prosecution_concluded SQS queue (dev) from 2 to 15 minutes.

[LAA Court Data Adaptor] Increase delay_seconds for prosecution_concluded SQS queue (dev)

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-staging/05-prometheus.yaml

As we have switched some of the file uploads to a separate controller, this should only alert when a file upload exceeds 10
seconds and exclude it from the default 2 second checks

LAA Apply: Update prometheus alerts on staging

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-prod/resources/messaging-queues.tf

Increase delay_seconds for prosecution_concluded SQS queue (dev) from 2 to 15 minutes.

[LAA Court Data Adaptor] Increase delay_seconds for prosecution_concluded SQS queue (prod)

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-production/05-prometheus.yaml

As we have switched some of the file uploads to a separate controller, this should only alert when a file upload exceeds 10
seconds and exclude it from the default 2 second checks

LAA Apply: Update prometheus alerts

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-staging/05-prometheus.yaml

Remove the admin report alert, this is now an overnight
build and download from S3 so should never exceed the
standard 2-second rule
Include v1/uploaded_evidence_collections in the 10 second
rule and exclude it from 2 seconds

Apply: Update prometheus alerts on staging

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-production/05-prometheus.yaml

Remove the admin report alert, this is now an overnight
build and download from S3 so should never exceed the
standard 2-second rule
Include v1/uploaded_evidence_collections in the 10 second
rule and exclude it from 2 seconds

Apply: Update prometheus alerts on production

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-frontend-production/02-limitrange.yaml

We recently deployed a new release of the frontend and experienced memory limit reached issues, so we're going to increase the memory limit on the frontend in production.
The other environments haven't experienced any memory issues which indicated it's not a memory leak.

Increase memory of Basm frontend in production

---

namespaces/live.cloud-platform.service.justice.gov.uk/monitoring/dashboard-application-alerts.yaml

This dashboard basically spells out what information is used in the
"application" alerts that come from the "generic-alerts" HMPPS helm
chart.

Add a dashboard showing the data used in application alerts

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-api-staging/resources/basic-auth.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-api-staging/resources/variables.tf

After an issue where in the application was returning a 503 because the basic-auth secret was in username/password format and not auth, this is to update the secrets to utilise the correct format and prevent them being overwritten when changes are made.

AAC-557 - Update staging values

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmcts-mock-api-dev/resources/rds.tf

[hmcts-mock-api-dev] Expose AWS creds in Kubernetes secret

---

namespaces/live.cloud-platform.service.justice.gov.uk/interventions-design-history/resources/github-repo.tf

This is needed even if the repository and the deployment files exists already. 
Refer: https://github.com/ministryofjustice/interventions-design-history

Add PROTOTYPE_NAME github action secret for deployment pipeline

---

namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-preprod/resources/rds-pre-sentence-service.tf

auto_minor_version_upgrade is enabled so mention major version. Pipeline fails whenever aws upgrade minor versions

Amend db_engine_version with major version number 

---

namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-dev/resources/rds-pre-sentence-service.tf

auto_minor_version_upgrade is enabled so mention just the major version. Pipeline fails when aws auto upgrades minor versions

Amend db_engine_version with major version number

---

namespaces/live.cloud-platform.service.justice.gov.uk/dso-monitoring-dev/05-certificate.yaml

Certificates weren't being issued, which is most likely due to the ".dev." domain not existing. PR to amend the DNS names.

Amend DSO monitoring certificate DNS names

---

namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-prod/resources/rds-pre-sentence-service.tf

This will fix conflict whenever aws do auto minor upgrades and the pipeline errors because of mismatch in terraform state.

Update db_engine_version with just major version 

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-test/resources/rds.tf

[laa-court-data-adaptor-test] Expose AWS creds in Kubernetes secret

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-dev/resources/rds.tf

[laa-court-data-adaptor-dev] Expose AWS creds in Kubernetes secret

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-stage/resources/rds.tf

[laa-court-data-adaptor-stage] Expose AWS creds in Kubernetes secret

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-uat/resources/rds.tf

[laa-court-data-adaptor-uat] Expose AWS creds in Kubernetes secret

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmcts-mock-api-dev/resources/rds_new.tf

Create new RDS instance, as part of a plan to upgrade the database from Postgres 11 to 14, using the migration method, rather than upgrade in place.

[hmcts-mock-api-dev] Create new RDS instance (t3 small)

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-prod/resources/rds.tf

[laa-court-data-adaptor-prod] Expose AWS creds in Kubernetes secret

---

namespaces/live.cloud-platform.service.justice.gov.uk/ppud-replacement-prod/resources/legacy-ppud-api-rds.tf

It's an optional param and as the user running the apply cannot access
the VPC it's causing failures.

Remove the VPC ID

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-api-production/resources/route53.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-api-production/resources/variables.tf

To enable us to use our own domain name, this PR sets up the Route53 config so that we can proceed to the next step for doing this.

AAC-581 - Add Route53 for production court data api

---

namespaces/live.cloud-platform.service.justice.gov.uk/analytical-platform-poc/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/analytical-platform-poc/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/analytical-platform-poc/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/analytical-platform-poc/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/analytical-platform-poc/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/analytical-platform-poc/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/analytical-platform-poc/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/analytical-platform-poc/resources/versions.tf

I want to see if I can emulate the analytical platform tools api on the Cloud Platform.

feat(analytical-platform): add initial environment with basic cli config

---

namespaces/live.cloud-platform.service.justice.gov.uk/analytical-platform-poc/resources/serviceaccount.tf

0.7.4 is the latest release of this module. I'm not sure why the reports.cloud-platform... didn't pick this up

build(ap-poc): bump the serviceaccount module version to 0.7.4

---

namespaces/live.cloud-platform.service.justice.gov.uk/makerecall-prototype/resources/github-repo.tf

As a design prototype with no mission critical dependancies this security intervention is not required. I'm also the only person editing the HTML and JS on this prototype.

Change required signed commit setting

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-api-dev/05-certificate.yaml

Add certificate to dev namespace for laa-court-data-api-dev after having new dns zone added.

AAC-558 - Add dev cert to laa-court-data-api-dev

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-api-uat/05-certificate.yaml

Add certificate to uat namespace for laa-court-data-api-uat after having new dns zone added.

Add certificate to laa-court-data-api-uat

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-api-staging/05-certificate.yaml

Add certificate to staging namespace for laa-court-data-api-staging after having new dns zone added.

Add cert to laa-court-data-api-staging

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-api-production/05-certificate.yaml

Add certificate to production namespace for laa-court-data-api-production after having new dns zone added.

Add certificate to laa-court-data-api-production

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-incentives-tool/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-incentives-tool/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-incentives-tool/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-incentives-tool/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-incentives-tool/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-incentives-tool/resources/basic-auth.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-incentives-tool/resources/ecr.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-incentives-tool/resources/github-repo.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-incentives-tool/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-incentives-tool/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-incentives-tool/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-incentives-tool/resources/versions.tf

added hmpps-incentives-tool prototype to cloud platform by following the guidance here:
https://user-guide.cloud-platform.service.justice.gov.uk/documentation/getting-started/prototype-kit.html#2-create-your-prototype-kit-site

added hmpps-incentives-tool prototype to cloud platform

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-incentives-tool/resources/github-repo.tf

as suggested in #ask-cloud-platform, to allow prototype container to use
newer version of Node.js base image.

Incentives prototype: Disable override of Dockerfile

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-production/resources/rds.tf

This will allow us to determine which queries might be the slowest and we could look in to improving them.
Based on the instructions here: https://aws.amazon.com/premiumsupport/knowledge-center/rds-postgresql-query-logging/
[Jira Ticket](https://dsdmoj.atlassian.net/browse/P4-3451)

Add slow query logging to Basm production

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-production/resources/rds.tf

Since it's just a repeat of the line below it.

Remove unnecessary comment

---

namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-frontend-svc-dev/06-certificate.yaml

DNS and cert name changes so internat ingress URLs do not exceed character limits

Visit someone in prison -frontend-svc-dev change

---

.github/workflows/conftest-yaml.yml
.github/workflows/opa-tests.yml

Reverts ministryofjustice/cloud-platform-environments#4866
This test the OPA policies for environments repo when users have escalated rolebindings and business-unit other than what we expect.

Add the OPA tests for env repo

---

namespaces/live.cloud-platform.service.justice.gov.uk/mydemoapp-dev/00-namespace.yaml

This special characters broke the HOODAW hosted services and hence removing.
Need investigating on how to detect this before merging

Fix quotes in application annotation

---

namespaces/live.cloud-platform.service.justice.gov.uk/mydemoapp-dev/resources/serviceaccount.tf

Add a service account to namespace as per instructions:
https://user-guide.cloud-platform.service.justice.gov.uk/documentation/getting-started/cloud-platform-cli.html#add-a-service-account-to-your-namespace

Add a service account to namespace

---

namespaces/live.cloud-platform.service.justice.gov.uk/mydemoapp-dev/resources/serviceaccount.tf

Add a serviceaccount_name variable called circleci as per instructions:
https://user-guide.cloud-platform.service.justice.gov.uk/documentation/deploying-an-app/using-circleci-for-continuous-deployment.html#creating-a-service-account-for-circleci

Add a serviceaccount_name variable

---

namespace-resources-cli-template/resources/prototype/templates/cd.yaml
namespace-resources-cli-template/resources/prototype/templates/kubernetes-deploy.tpl

Template files to be fetched by the CLI for prototype deployment
Earlier we maintained these file in the repo: https://github.com/ministryofjustice/cloud-platform-terraform-github-prototype/tree/main/templates. Since, the deployments are branch based, the template will be automatically pulled and updated based on what branch the cli command is executed.

Add deployment manifest and gh action file template for prototype

---

namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-dev/prometheus-custom-alerts-ccic-dev.yaml

A prometheus rule was failing sync. Upon investigation it was caused by this additional closed bracket that has no sibling. This commit runs the file through a yaml linter and removes said bracket, fixing the issue outlined here:
https://mojdt.slack.com/archives/C57UPMZLY/p1654011900012539

Lint and fix broken rule

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-interventions-preprod/05-serviceaccount-circleci.yaml

To make the namespace compatible with
https://github.com/ministryofjustice/hmpps-helm-charts
Similar to #7998

[interventions-preprod] Switching to RoleBinding and enable prometheusrules

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-uat/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-uat/resources/variables.tf

Needs to delete a deployed branch in its own subdomain
with all that that involves
specifically the default serviceaccount_rules were raising this:
```
Error: uninstallation completed with 3 error(s): ...
cannot delete resource "statefulsets" in API group "apps" ...
cannot delete resource "networkpolicies" in API group "networking.k8s.io" ...
cannot delete resource "servicemonitors" in API group "monitoring.coreos.com" ...
```
Ticket [AP-3183](https://dsdmoj.atlassian.net/browse/AP-3183)

Add custom serviceaccount rules for github actions

---

namespaces/live.cloud-platform.service.justice.gov.uk/evidencelibrary-prod/resources/pingdom.tf

https://analytical-evidence-library.service.justice.gov.uk/

evidencelibrary- live site pingdom Url changed.

---

namespaces/live.cloud-platform.service.justice.gov.uk/evidencelibrary-test/resources/certificate.yaml

new domain: https://test.analytical-evidence-library.service.justice.gov.uk/

evidencelibrary-test: new domain cert

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-production/resources/rds.tf

Raising PR on back of advice from Cloud Platform team.
We are trying to create an index on a table with millions of rows in production and so far it hasn't worked.  Hopefully this will give us the boost we need to create it.

Increase prod Basm DB instance size to aid creation of index on tablewith 19 million plus rows.

---

namespaces/live.cloud-platform.service.justice.gov.uk/check-financial-eligibility-uat/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/check-financial-eligibility-uat/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/check-financial-eligibility-uat/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/check-financial-eligibility-uat/resources/versions.tf

Adds all required variables and config
to create a separate serviceaccount that
can be used by github actions to delete
a UAT env deployment.
Should also add necessary vars/config to
automatically generate the secrets that can be used
Related app PR [AP-3184](https://github.com/ministryofjustice/check-financial-eligibility/pull/959)

Add serviceaccount to CFE UAT namespace for github-action

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-hmrc-interface-uat/resources/serviceaccount-github-actions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-hmrc-interface-uat/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-hmrc-interface-uat/resources/versions.tf

Adds all required variables and config
to create a separate serviceaccount that
can be used by github actions to delete
a UAT env deployment.
Also adds necessary vars/config to
automatically generate the secrets that
can be used

Add serviceaccount to HMRC Interface UAT namespace for github-action

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-hmrc-interface-uat/resources/serviceaccount-github-actions.tf

prevent 
```
Error: roles.rbac.authorization.k8s.io "serviceaccount-role" already exists
on .terraform/modules/serviceaccount_github_actions/main.tf line 15, in resource "kubernetes_role" "github_actions_role":
15: resource "kubernetes_role" "github_actions_role" {
```

Amend role name to prevent clash with existing serviceaccount role

---

namespaces/live.cloud-platform.service.justice.gov.uk/calculate-journey-variable-payments-preprod/02-limitrange.yaml

Temporarily increasing the available memory to the payment service whilst buying us time to come up with a longer term solution.

This temporary memory increase to see if we can resolve a production issue in the short term whilst coming up with a longer term solution.

---

namespaces/live.cloud-platform.service.justice.gov.uk/money-to-prisoners-prod/resources/route53.tf

Mailgun has fully been replaced by GOV.UK Notify

Remove unnecessary prisoner money DNS records

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-production/resources/rds.tf

Basm prod write instance is getting low disk space warnings in production.
This change increases the storage allocation on the back of advice from talking to Cloud Platform.

Increasing the prod Basm write instance storage allocation on back of low disk space warnings in the AWS logs and advice from Cloud Platform.

---

namespaces/live.cloud-platform.service.justice.gov.uk/data-eng-uploader-dev/resources/ecr.tf

Have added access to ecr creds to the  analytical-platform-uploader repo to enable automatic deployment of the docker image for the app. Current process is to build and deploy the image from the command line for each significant merge into the repo, which isn't terribly efficient.
Have followed the process outlined in the GitHub Actions section of the cloud platform user guidance [available here](https://user-guide.cloud-platform.service.justice.gov.uk/documentation/getting-started/ecr-setup.html#github-actions)
By way of background, the analytical-platform-uploader allows users to upload data to S3 through a web app, automatically creating the s3 buckets and glue schemas in the case of a new database, which is then more widely accessible through the tools provided on the ap and athena.

adding gh actions secrets

---

.github/workflows/auto-approve-pr.yaml

This PR pins `actions/checkout` to `v3.0.2` in `auto-approve-pr.yaml` rather than `master` to reduce the risk of introducing changes that are not yet released for wider use within the action.

Pin actions/checkout to v3.0.2 in auto-approve-pr.yaml

---

.github/workflows/malformed-yaml.yml

This PR pins `actions/checkout` to `v3.0.2` in `malformed-yaml.yml` rather than `master` to reduce the risk of introducing changes that are not yet released for wider use within the action.

Pin actions/checkout to v3.0.2 in malformed-yaml.yml

---

cmd/check-ingress/README.md
cmd/rbac-permissions-check/README.md
namespaces/live.cloud-platform.service.justice.gov.uk/data-eng-uploader-dev/resources/serviceaccount.tf

Adding the analytical-platform-uploader github repo to the serviceaccount.tf file to add the kube cluster auth info secrets to the aforementioned repo, following the process outlined in the cloud platform guidance [here](https://user-guide.cloud-platform.service.justice.gov.uk/documentation/deploying-an-app/github-actions-continuous-deployment.html#update-the-manifest) to automate deployment.
By way of background, the analytical-platform-uploader app allows users to upload data and automates production of the S3 buckets, glue schemas, etc so that the data can be accessed through athena and other tools available on the ap.

adding the kube cluster auth info to gh repo secrets 

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-criminal-legal-aid-staging/resources/pingdom.tf

HTTPS protocol mistakenly left in host URL due to copy paste error - removed HTTPS protocol to allow apply to happen.

Fix typo bug - remove https protocol from app host url for pingdom

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-probation-webops-poc/resources/serviceaccount.tf

Hello, I am trying to use CircleCI to deploy the multi-container-app and ran intot he following error when helm install:
Error: rendered manifests contain a resource that already exists. Unable to continue with install: could not get information about the resource: statefulsets.apps "multi-container-app-postgresql" is forbidden: User "system:serviceaccount:hmpps-probation-webops-poc:cd-serviceaccount" cannot get resource "statefulsets" in API group "apps" in the namespace "hmpps-probation-webops-poc"
This PR is to add statefulsets to serviceaccount_rules to provide service account with permissions. I cannot confirm if this is all the permissions required, is there a way to check locally first please?

Add serviceaccount_rules

---

namespaces/live.cloud-platform.service.justice.gov.uk/prisoner-content-hub-development/resources/rds.tf

This is to test changes ahead of https://github.com/ministryofjustice/cloud-platform-environments/pull/8282 (but instead we downgrade the instance on dev, as we do not need an xlarge here).

Prisoner content hub - dev - downgrading RDS instance to medium

---

namespaces/live.cloud-platform.service.justice.gov.uk/prisoner-content-hub-production/09-prometheus.yaml

Add prometheus rule to alert when max connections is above 80% of the maximum.
We are often seeing errors in the RDS logs relating to exceeding max_connections.  
Note this is my first Prometheus rule, so hopefully I got this right (I've already tested the expression directly in prometheus).

Prisoner content hub -prod - Add prometheus RDS max connections alert.

---

namespaces/live.cloud-platform.service.justice.gov.uk/prisoner-content-hub-production/resources/rds.tf

This is to increase the resources for RDS to `xlarge`, as we are seeing errors in RDS related to max_connections.  E.g. 
```
2022-07-22 13:11:39 0 [Warning] Aborted connection 0 to db: 'unconnected' user: 'unauthenticated' host: 'connecting host' (Too many connections)
```
The max_connections configuration is tied to the db instance size.
Note we are **not** increasing the dev and staging environments, as these do not require such a large instance and would be an unnecessary cost.
Related Trello card: https://trello.com/c/EjfBYww7/1315-downtime-post-mortem

Prisoner content hub - prod - Upgrade RDS to t3.xlarge

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-interventions-prod/02-limitrange.yaml

Pods are running out of memory, causing outages of the service.

Increase memory for hmpps-interventions-prod

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-probation-webops-poc/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-probation-webops-poc/resources/redis.tf

Work item: https://dsdmoj.atlassian.net/browse/NIT-262
Fixes to param values for correct behaviour with default for RDS and Redis modules.

Apply fixes to webops-poc params for rds and redis dependencies

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-probation-webops-poc/resources/rds.tf

Work item: https://dsdmoj.atlassian.net/browse/NIT-262
Disabling performance insights - missing dependent config but not needed for poc anyway.

disable performance insights for webops-poc mariadb

---

namespaces/live.cloud-platform.service.justice.gov.uk/approved-premises-api-dev/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/approved-premises-api-dev/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/approved-premises-api-dev/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/approved-premises-api-dev/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/approved-premises-api-dev/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/approved-premises-api-dev/05-serviceaccount-circleci.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/approved-premises-api-dev/06-certificate.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/approved-premises-api-dev/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/approved-premises-api-dev/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/approved-premises-api-dev/resources/versions.tf

This follows on from #8331 to create a namespace for the dev version of the Approved Premises API. Again, we're not diverging from defaults much at the mo, so this is just copied from the Kotlin template with any defaults changed.

Create namespace for Approved Premises API Dev

---

namespaces/live.cloud-platform.service.justice.gov.uk/approved-premises-dev/01-rbac.yaml

This was left over from copying from the template repos. We need to give the Approved Premises team access, as well as dps-tech.

Give Approved Premises team namespace access (UI)

---

namespaces/live.cloud-platform.service.justice.gov.uk/money-to-prisoners-test/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/money-to-prisoners-test/resources/rds.tf

…from `t2` to `t4g`, which is cheaper and more performant/energy-efficient. Apparently, cross-architecture migrations are possible (`t4g` is an AWS Graviton2 / ARM type) but this is a test DB so doesn't matter if it is destroyed.

Change prisoner money test DB instance type

---

namespaces/live.cloud-platform.service.justice.gov.uk/money-to-prisoners-test/resources/rds.tf

…because the services uses postgres 10 which is not supported on `t4g` (and we're not prepared to migrate DB versions right now).
C.f #8345

Revert prisoner money test DB to `t2`

---

namespaces/live.cloud-platform.service.justice.gov.uk/approved-premises-api-dev/01-rbac.yaml

This was left over from copying from the template repos. We need to give the Approved Premises team access to the API application, as well as dps-tech.

Give Approved Premises team namespace access (API)

---

namespaces/live.cloud-platform.service.justice.gov.uk/approved-premises-api-dev/resources/rds.tf

This should be everything we need to setup a Postgres instance for the dev instance of Approved Premises API. If I've missed anything please let me know!

Add an RDS for Approved Premises Dev

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-historical-prisoner-application-dev/06-certificate.yaml

This is for hmpps-historical-prisoner-application-dev certificate
using guidence:
https://user-guide.cloud-platform.service.justice.gov.uk/documentation/other-topics/custom-domain-cert.html#certificate-character-limit

Fix 64 char limit issue

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-activity-management-prototype/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-activity-management-prototype/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-activity-management-prototype/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-activity-management-prototype/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-activity-management-prototype/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-activity-management-prototype/resources/basic-auth.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-activity-management-prototype/resources/ecr.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-activity-management-prototype/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-activity-management-prototype/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-activity-management-prototype/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-activity-management-prototype/resources/versions.tf

Creating a namespace for the deployment of the activity management prototype
(Generated using the cloud-platform CLI and a default gov.uk prototype kit)

Create the activity prototype namespace from gov.uk prototype kit template

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-events-dev/resources/iam-sqs-console-role.tf

This has been removed in the Delius account

Remove reference to delius-test-sqs-consumer role

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-events-preprod/resources/iam-sqs-console-role.tf

This has been removed in the Delius account

Remove reference to delius-pre-prod-sqs-consumer role

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-events-prod/resources/iam-sqs-console-role.tf

This has been removed in the Delius account

Remove reference to delius-prod-sqs-consumer role

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-uat/resources/main.tf

Add team tag for Apply team resources
As per [guide](https://user-guide.cloud-platform.service.justice.gov.uk/documentation/getting-started/accessing-the-cloud-console.html#tagging-your-resources)

Add tag for Apply team to uat resources

---

namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-saas-test/formbuilder-av-service-account.yaml

We would like to deploy our fb-av app into the formbuilder-saas-test namespace.
Co-authored-by: Hellema Ibrahim <hellema.ibrahim@digital.justice.gov.uk>

Add serviceaccount to formbuilder-saas-test namespace

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-bot-production/resources/rds.tf

We wanted to switch to db.t4g.small to try the new graviton base image
This has already been applied via the AWS CLI so this should be a
relatively low impact change
This namespace has a SKIP FILE as we are in the progress of updating the Postgres versions

LAA apply-bot: Update RDS instance class

---

namespaces/live.cloud-platform.service.justice.gov.uk/hosting-data-production/resources/rds.tf

This PR is testing the [`create_before_destroy` lifecycle attribute](https://github.com/ministryofjustice/cloud-platform-terraform-rds-instance/commit/79dbf8a47f3962b272100a3336765f79695bacd9) for db_parameter_group as part of the RDS module; which is related to ministryofjustice/cloud-platform#3107.

Test RDS upgrade using lifecycle { create_before_destroy } for db_parameter_group

---

namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-saas-live/formbuilder-av-service-account.yaml

We require this so our editor app can talk to the anti-virus app
Co-authored-by: Brendan Butler <[brendan.butler@digital.justice.gov.uk](mailto:brendan.butler@digital.justice.gov.uk)>
Co-authored-by: Hellema Ibrahim <[hellema.ibrahim@digital.justice.gov.uk](mailto:hellema.ibrahim@digital.justice.gov.uk)>

Add serviceaccount in saas-live namespace

---

namespaces/live.cloud-platform.service.justice.gov.uk/abundant-namespace-dev/resources/elasticsearch.tf
namespaces/live.cloud-platform.service.justice.gov.uk/manage-intelligence-dev/resources/elasticsearch.tf
namespaces/live.cloud-platform.service.justice.gov.uk/peoplefinder-demo/resources/elasticsearch.tf
namespaces/live.cloud-platform.service.justice.gov.uk/peoplefinder-development/resources/elasticsearch.tf
namespaces/live.cloud-platform.service.justice.gov.uk/peoplefinder-production/resources/elasticsearch.tf
namespaces/live.cloud-platform.service.justice.gov.uk/peoplefinder-staging/resources/elasticsearch.tf
namespaces/live.cloud-platform.service.justice.gov.uk/prisoner-content-hub-development/resources/elasticsearch.tf
namespaces/live.cloud-platform.service.justice.gov.uk/prisoner-content-hub-production/resources/elasticsearch.tf
namespaces/live.cloud-platform.service.justice.gov.uk/prisoner-content-hub-staging/resources/elasticsearch.tf
namespaces/live.cloud-platform.service.justice.gov.uk/prisoner-offender-search-dev/resources/es.tf
namespaces/live.cloud-platform.service.justice.gov.uk/prisoner-offender-search-preprod/resources/es.tf
namespaces/live.cloud-platform.service.justice.gov.uk/prisoner-offender-search-prod/resources/es.tf
namespaces/live.cloud-platform.service.justice.gov.uk/probation-offender-search-dev/resources/es.tf
namespaces/live.cloud-platform.service.justice.gov.uk/probation-offender-search-preprod/resources/es.tf
namespaces/live.cloud-platform.service.justice.gov.uk/probation-offender-search-prod/resources/es.tf
namespaces/live.cloud-platform.service.justice.gov.uk/probation-offender-search-staging/resources/es.tf

Bumps [ministryofjustice/cloud-platform-terraform-elasticsearch](https://github.com/ministryofjustice/cloud-platform-terraform-elasticsearch) to 3.9.5.

Bump cloud-platform-terraform-elasticsearch to 3.9.5

---

namespaces/live.cloud-platform.service.justice.gov.uk/prisoner-content-hub-development/resources/rds.tf

This is to facilitate automated database syncing between prod and dev.
The setup is being copied from https://github.com/ministryofjustice/use-of-force/tree/main/database_refresh

Prisoner content hub - Add secret for dev rds instance in the prod namespace.

---

namespaces/live.cloud-platform.service.justice.gov.uk/prisoner-content-hub-development/06-servicemonitor.yml

To allow Apache status data to be scraped by Prometheus. 
See: https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/application-metrics.html#add-service-endpoint-and-servicemonitor
PR for enabling prometheus exporter from the app: https://github.com/ministryofjustice/prisoner-content-hub-backend/pull/436
Note that there is a separate k8ns service that exports the data in the prometheus metric format (it does not come directly from the pods running the app).  This service does not have an ingress entry.  It can only be accessed from within the k8ns network.

Prisoner content hub - dev- Add support for apache prometheus scraping.

---

namespaces/live.cloud-platform.service.justice.gov.uk/offender-management-staging/resources/rds-allocations-api.tf

Remove APPLY_PIPELINE_SKIP_THIS_NAMESPACE
Disallow major version upgrades

offender-management-staging: Clean up after the PG upgrade

---

namespaces/live.cloud-platform.service.justice.gov.uk/approved-premises-prototype/01-rbac.yaml

The team that was specified to access the prototype does not exist. Changed it to the correct team.

Fix Approved Premises Prototype team access

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-production/05-prometheus.yaml

Amend alerting for bank statement upload endpoints
As with others the request can take over 2 seconds so ignore
for those but include for > 10 second alert.

Amend alerting for new file upload endpoints

---

namespaces/live.cloud-platform.service.justice.gov.uk/prisoner-content-hub-production/07-certificates-frontend.yaml

The Studio is a new (fake) prison that has been set up within the studio. When visiting the production domain https://thestudio.content-hub.prisoner.service.justice.gov.uk/ this is not currently served over HTTPS. This record has been added to enable this.

Add dnsName for thestudio development prison

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-events-prod/resources/github.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-events-prod/resources/hmpps-pre-sentence-report-queue.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-events-prod/resources/hmpps-prison-custody-status-to-delius-queue.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-events-prod/resources/hmpps-workforce-allocation-queue.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-events-prod/resources/iam-sqs-console-role.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-events-prod/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-events-prod/resources/prison-to-probation-update.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-events-prod/resources/variables.tf

Also:
* deprecate and remove the subscription for the prison-to-probation-update queue
* tidy up sqs console policy

PI-399 Create queue for prison-custody-status-to-delius service (prod)

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-estimate-financial-eligibility-for-legal-aid-production/resources/ecr.tf

On lines 10 and 85 of the `ecr.tf `I have changed the `repo_name` and  `name` values so that the environment (uat/staging/production) is not part of the ECR name. As this ECR repo will serve all of our environments it makes sense to have the name environment agnostic.

Create ECR for the Estimate Eligibility service

---

namespaces/live.cloud-platform.service.justice.gov.uk/prisoner-content-hub-db-backups/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/prisoner-content-hub-db-backups/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/prisoner-content-hub-db-backups/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/prisoner-content-hub-db-backups/resources/s3.tf
namespaces/live.cloud-platform.service.justice.gov.uk/prisoner-content-hub-db-backups/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/prisoner-content-hub-db-backups/resources/versions.tf

This adds a new namespace `prisoner-content-hub-db-backups`.  This will contain an s3 bucket to store database backups of the `prisoner-content-hub-production` database.  (There will be no other services running in this namespace).
Backups will be created using a cronjob, in `.sql` format.
**Why not use the `prisoner-content-hub-production` namespace?**
The reason for using a separate namespace, is that we want dev and staging to also be able to connect to the s3 bucket, in order to run automated database refresh jobs, syncing the db with production.  
If we placed the s3 bucket in production, we would have to expose the creds for this onto non-prod environments.  Having a separate namespace is much cleaner.
Note that there is no sensitive prisoner data in this application, just content …

Adding new prisoner-content-hub-db-backups namespace.

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-probation-webops-poc/resources/serviceaccount.tf

I would like to run commands using kubectl exec as part of the my CircleCI pipeline, for example:
kubectl -n ${K8S_NAMESPACE} exec -t $POD_NAME -- bash -c "php artisan migrate --force"
But ran into the following error:
Error from server (Forbidden): pods "vcms-artisan-678ddf7455-jk7cc" is forbidden: User "system:serviceaccount:**************************:cd-serviceaccount" cannot create resource "pods/exec" in API group "" in the namespace "**************************"

To allow circleci to execute commands in kube pod

---

namespaces/live.cloud-platform.service.justice.gov.uk/prisoner-content-hub-development/resources/rds.tf

We've been seeing errors like this in production:
```
2022-09-05 11:43:27 59589545 [Warning] Aborted connection 59589545 to db: '*******' user: '*****' host: '*****' (Got an error reading communication packets)
```
The doc from AWS suggest this could be down to a few issues. https://aws.amazon.com/premiumsupport/knowledge-center/rds-mysql-communication-packet-error/
One of which is the max_allowed_packet size (which has a 1MB default).
This PR increases it to 10MB.  From what I have read, this does not increase the initial allocation, so is safe to increase.

Prisoner content hub - dev - increase max_allowed_packets

---

namespaces/live.cloud-platform.service.justice.gov.uk/prisoner-content-hub-development/resources/rds.tf

Reverts ministryofjustice/cloud-platform-environments#8564
This breaks the build as it's below the minimum amount of 16MB.
Upon further investigation, we already have 16MB set in RDS (the default for mysql is 1MB, but it looks like RDS sets it's own value).
Therefore we don't need to increase this value.

Revert "Prisoner content hub - dev - increase max_allowed_packets"

---

namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-services-live-dev/03-resourcequota.yaml

This namespace holds the forms developed by end users and published into the Test environment. Increasing the pod quotas from 160 to 300 as recived a warning alert.

MOJ Forms - Increase pod quota for namespace

---

namespaces/live.cloud-platform.service.justice.gov.uk/activities-dev/05-serviceaccount-circleci.yaml

Minor change to add service monitors to prometheus (missing from template typescript project)

SAA-33: Adding service monitors

---

namespaces/live.cloud-platform.service.justice.gov.uk/manage-soc-cases-prototype/resources/basic-auth.tf
namespaces/live.cloud-platform.service.justice.gov.uk/manage-soc-cases-prototype/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/pathfinder-prototype/resources/basic-auth.tf
namespaces/live.cloud-platform.service.justice.gov.uk/pathfinder-prototype/resources/variables.tf

this ensures that the password set in the kube cluster is in sync with the IaC

[DSE-607] generate random passwords for prototypes

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmcts-mock-api-dev/resources/rds_new.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-complexity-of-need-preprod/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-complexity-of-need-staging/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-dev/resources/rds-instance.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-stage/resources/rds-instance.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-test/resources/rds-instance.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-uat/resources/rds-instance.tf
namespaces/live.cloud-platform.service.justice.gov.uk/offender-management-preprod/resources/rds-allocations-api.tf
namespaces/live.cloud-platform.service.justice.gov.uk/offender-management-staging/resources/rds-allocations-api.tf

This is to remove the pinned minor version
To fix the error:
Error: Error modifying DB Instance xxxxxxxx: InvalidParameterCombination: Cannot upgrade Postgres from 14.x to 14.x

Update RDS engine version non-prod

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-criminal-legal-aid-staging/resources/ecr.tf

ECR lifecycle to keep newest 25 untagged images.
Tagged images (like `staging`) should not be deleted by this policy, only untagged images.

Add ECR lifecycle policy to crime apply service

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-approved-premises-dev/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-approved-premises-dev/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-approved-premises-dev/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-approved-premises-dev/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-approved-premises-dev/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-approved-premises-dev/05-serviceaccount-circleci.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-approved-premises-dev/06-certificates.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-approved-premises-dev/resources/elasticache.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-approved-premises-dev/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-approved-premises-dev/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-approved-premises-dev/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-approved-premises-dev/resources/versions.tf

This adds a new namespace for the approved premises project that has the correct naming convention and also combines the API and UI for ease of use. Once this is created and deployed, the old `approved-premises-dev` and `approved-premises-api-dev` namespaces can be deleted.

Add new `hmpps-approved-premises` namespace

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-temporary-accommodation-prod/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-temporary-accommodation-prod/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-temporary-accommodation-prod/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-temporary-accommodation-prod/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-temporary-accommodation-prod/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-temporary-accommodation-prod/05-serviceaccount-circleci.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-temporary-accommodation-prod/06-certificates.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-temporary-accommodation-prod/resources/elasticache.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-temporary-accommodation-prod/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-temporary-accommodation-prod/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-temporary-accommodation-prod/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-temporary-accommodation-prod/resources/versions.tf

Temporary Accommodation and Approved Premises will share a common codebase, so we want the environment to be closely aligned. This PR gives us the Temporary Accommodation Production equivalent of hmpps-approved-premises-dev
As with #8729, I've err-ed on the side of keeping things consistent with Approved Premises, which has resulted in some arbitrary-seeming changes

Update hmpps-temporary-accommodation-prod namespace to mirror hmpps-approved-premises-dev

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-temporary-accommodation-preprod/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-temporary-accommodation-preprod/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-temporary-accommodation-preprod/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-temporary-accommodation-preprod/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-temporary-accommodation-preprod/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-temporary-accommodation-preprod/05-serviceaccount-circleci.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-temporary-accommodation-preprod/06-certificates.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-temporary-accommodation-preprod/resources/elasticache.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-temporary-accommodation-preprod/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-temporary-accommodation-preprod/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-temporary-accommodation-preprod/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-temporary-accommodation-preprod/resources/versions.tf

Temporary Accommodation and Approved Premises will share a common codebase, so we want the environment to be closely aligned. This PR gives us the Temporary Accommodation Preprod equivalent of hmpps-approved-premises-dev
As with #8729, I've err-ed on the side of keeping things consistent with Approved Premises, which has resulted in some arbitrary-seeming changes

Update hmpps-temporary-accommodation-preprod namespace to mirror hmpps-approved-premises-dev

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-interventions-prod/resources/rds-postgres14.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-interventions-prod/resources/rds.tf

We are running on PostgreSQL 10, which will be end-of-life soon.
This PR creates a new PostgreSQL 14 instance, so we have something to migrate to.

Create new PostgreSQL14 instance on prod

---

namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-repos/resources/repos.tf
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-repos/resources/variables.tf

Adds policy to keep latest 50 images on 1 ecr repo.

Adding life cycle policy to erc

---

namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-repos/resources/repos.tf

This PR adds the lifecyle policy to only keep the latest 50 images on all formbuilder images.

Add ECR lifecycle policy to all formbuilder repos

---

namespaces/live.cloud-platform.service.justice.gov.uk/track-a-query-demo/06-circleci-serviceaccount.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/track-a-query-development/06-circleci-serviceaccount.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/track-a-query-production/06-circleci-serviceaccount.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/track-a-query-qa/06-circleci-serviceaccount.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/track-a-query-staging/06-circleci-serviceaccount.yaml

A change has been made to the application to run data migrations from a Kubernetes Job, but the circleci user does not have permissions to use those resources.

Add permissions for Jobs resources for track-a-query

---

namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-test-production/resources/variables.tf

The Medium instance size is only available with burstable performance which is something we do not require. Just use Large

Form Builder - Use large DB instance size

---

namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-test-dev/resources/submitter.tf
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-test-dev/resources/user-datastore.tf
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-test-dev/resources/variables.tf

Creating a new Graviton RDS instances in the
formbuilder-platform-test-dev namespace for the datastore and the
submitter.

Form Builder - Add new DB in platform test-dev namespace

---

namespaces/live.cloud-platform.service.justice.gov.uk/offender-events-preprod/resources/rds.tf

- SDI-422: 🔧 Skip apply pipeline for offender-events-preprod
- SDI-422: 🔧 Upgrade to postgres 10_21 for offender-events-preprod
- SDI-422: 🔧 Upgrade to postgres 14 for offender-events-preprod

SDI-422: 🔧 Upgrade to postgres 14 for offender-events-preprod

---

namespaces/live.cloud-platform.service.justice.gov.uk/check-my-diary-preprod/resources/rds.tf

- SDI-422: 🔧 Skip apply pipeline for check-my-diary-preprod
- SDI-422: 🔧 Upgrade to postgres 10_21 for check-my-diary-preprod
- SDI-422: 🔧 Upgrade to postgres 14 for check-my-diary-preprod
- SDI-422: 🔧 Set migration instance class for check-my-diary-preprod

SDI-422: 🔧 Set migration instance class for check-my-diary-preprod

---

namespaces/live.cloud-platform.service.justice.gov.uk/offender-events-preprod/resources/rds.tf

- SDI-422: 🔧 Skip apply pipeline for offender-events-preprod
- SDI-422: 🔧 Upgrade to postgres 10_21 for offender-events-preprod
- SDI-422: 🔧 Upgrade to postgres 14 for offender-events-preprod
- SDI-422: 🔧 Set migration instance class for offender-events-preprod

SDI-422: 🔧 Set migration instance class for offender-events-preprod

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-restricted-patients-api-preprod/resources/rds.tf

- SDI-422: 🔧 Skip apply pipeline for hmpps-restricted-patients-api-preprod
- SDI-422: 🔧 Upgrade to postgres 10_21 for hmpps-restricted-patients-api-preprod
- SDI-422: 🔧 Upgrade to postgres 14 for hmpps-restricted-patients-api-preprod
- SDI-422: 🔧 Set migration instance class for hmpps-restricted-patients-api-preprod

SDI-422: 🔧 Set migration instance class for hmpps-restricted-patients-api-preprod

---

namespaces/live.cloud-platform.service.justice.gov.uk/cccd-production/resources/main.tf

The Claim for Payment team requires read-only access to AWS console to support the CCCD service in production.
This adds the necessary config to `resources/main.tf` specifying the GitHub team name.

Add default_tags to cccd-production main.tf

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-cla-backend-staging/resources/rds.tf

Redundant postgres 10 instances removed from the `laa-cla-backend-staging` namespace.

LGA-2157: Postgres 10 RDS instances removed from laa-cla-backend-staging

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-cla-backend-training/resources/rds.tf

Redundant Postgres 10 database instances removed from the `laa-cla-backend-training` environment after migration to a new Postgres 11 instance.

LGA-2158: Redundant postgres 10 instance removed.

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-estimate-financial-eligibility-for-legal-aid-uat/resources/route53-efe.tf

We accidentally allowed Google to index every page on ephemeral UAT branch we've created so far. We need to verify a bunch of UAT subdomains on Google in order to ask them to _un_-index them now.

EL-434: Add TXT records to verify rogue subdomains on Google Search Console

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-dev/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-dev/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-dev/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-dev/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-dev/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-dev/05-serviceaccount-circleci.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-dev/06-certificates.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-dev/resources/elasticache.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-dev/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-dev/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-dev/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-dev/resources/versions.tf

This will eventually replace `hmpps-approved-premises-dev` as we look to replace it with a more generic name that can house both CAS1 and CAS3 services. We imagine that eventually this will also extend to CAS2.
- We don't have a combined Slack channel as we're currently renaming that too to make it generic. We're using the CAS3 channel as a placeholder.
- Given `hmpps-approved-premises-dev` is still in place while we spin this up (to avoid disruption) we imagine there may be a clash on the DNS names used in certificate creation. We've prefixed all three with `cas-` for now which isn't ideal but hopefully after the other has been decommissed we'll be able to reoccupy them and remove this prefix.

Add Community Accommodation dev namespace

---

namespaces/live.cloud-platform.service.justice.gov.uk/cccd-dev-lgfs/resources/elasticache.tf

The latest update to the redis gem in CCCD requires that the username does not appear in `REDIS_URL`. We are testing this first on the dev-lgfs environment before making the same change in other environments.

Remove username from Redis URL string

---

namespaces/live.cloud-platform.service.justice.gov.uk/prison-visits-booking-production/resources/rds-prison-visits.tf

This is to update the engine version to 12.11, which got auto-applied during the maintenance window.
This will also fix the pipeline failure

Update RDS for prison visit

---

namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-prod/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-prod/resources/variables.tf

We use GitActions to deploy to our environments. The standard CloudPlatforms configuration for service accounts creates repository secrets that are not specific to environment. This change should allow for secrets to be generated into a specific GitAction environment (production in this instance).

Create GitHub env secrets prod

---

namespace-resources-cli-template/resources/prototype/github-repo.tf
namespace-resources-cli-template/resources/prototype/templates/kubernetes-deploy.tpl

This PR:
- Update the prototype template to use the v1 ingress controllers
- Remove the github-repo.tf which is no longer used by the Cloud Platform CLI

Update template to switch to v1 ingress controller

---

namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-staging/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-staging/resources/variables.tf

For our GitAction deploy to provide staging specific env vars.

Add service account secrets as environment secrets

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-dev/06-certificates.yaml

This follows up from #9187, and allows us to remove the temporary prefix we put in place while we were developing the `hmpps-community-accommodation-dev` namespace

Remove `cas` prefix from Accommodation domains

---

namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-prod/resources/serviceaccount.tf

We've updated our environment naming in GitAction, this change reflects that.

Update name to match GitHub environment

---

namespaces/live.cloud-platform.service.justice.gov.uk/keyworker-api-preprod/resources/rds.tf

Same as https://github.com/ministryofjustice/cloud-platform-environments/pull/9247

NN-4479: temporarily bump keyworker-api-preprod/rds to db.t3.large

---

namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-staging/resources/ecr.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-staging/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-staging/resources/variables.tf

ECR name is unique to namespace. We need to target a specific environment /namespace when deplpying using GitActions.

Add dedicated ECR variables for staging environment

---

namespaces/live.cloud-platform.service.justice.gov.uk/cccd-dev-lgfs/resources/elasticache.tf

The username is removed from the Redis URL string in a previous commit (#9098) for testing a newer version of the `redis` gem in CCCD. We are not yet ready to update this gem yet so the username needs to be added back in.

Add username to Redis URL string

---

namespaces/live.cloud-platform.service.justice.gov.uk/cjs-dashboard-development/resources/main.tf

This PR adds tags to the AWS resources within `cjs-dashboard-development` so we can view them in the AWS console.

Tag AWS resources with GitHub team name

---

cmd/rbac-permissions-check/get/get.go
cmd/rbac-permissions-check/get/get_test.go

This is to fix rbac failure if the yaml has other documents e.g. serviceaccount.

Fix rbac check for yaml with other documents, add tests

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-preprod/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-preprod/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-preprod/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-preprod/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-preprod/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-preprod/05-serviceaccount-circleci.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-preprod/06-certificates.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-preprod/resources/elasticache.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-preprod/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-preprod/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-preprod/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-preprod/resources/versions.tf

We've copied the configuration of our dev namespace and renamed "dev" to "preprod" in what seems to be the only required change. I eyeballed [the change set of another team](https://github.com/ministryofjustice/cloud-platform-environments/tree/main/namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-education-employment-preprod) (HMPPS Education Employment) and it looks to be confirm no extra service is required at this stage. 
We've also added in the recent support for resource tagging to enable [read-only console access](https://user-guide.cloud-platform.service.justice.gov.uk/documentation/getting-started/accessing-the-cloud-console.html#tagging-all-of-your-namespace-resources) for our upcoming pen test.
If there is any documentation for this that I've missed then please do …

Create preprod namespace for community accommodation

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-victim-case-management-system-dev/resources/rds.tf

Reducing cost by allowing auto stop/start for this VCMS dev DB.

Adding RDS auto start stop for VCMS dev db

---

namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-test-dev/resources/user-datastore.tf

This removes the old DB in formbuilder-platform-test-dev as we are now fully using the new one

Form Builder - Remove old datastore DB in test-dev

---

namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-test-production/resources/user-datastore.tf

This removes the old DB from formbuilder-platform-test-production as we are now fully using the new DB.

Form Builder - remove old datastore DB from test-production

---

namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-live-dev/resources/user-datastore.tf

This removes the old DB from formbuilder-platform-live-dev as we now using the new DB

Form Builder - remove old DB from live-dev

---

namespaces/live.cloud-platform.service.justice.gov.uk/cjs-dashboard-demo/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/cjs-dashboard-demo/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/cjs-dashboard-demo/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/cjs-dashboard-demo/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/cjs-dashboard-demo/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/cjs-dashboard-demo/resources/ecr.tf
namespaces/live.cloud-platform.service.justice.gov.uk/cjs-dashboard-demo/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/cjs-dashboard-demo/resources/s3.tf
namespaces/live.cloud-platform.service.justice.gov.uk/cjs-dashboard-demo/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/cjs-dashboard-demo/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/cjs-dashboard-demo/resources/versions.tf

This PR adds a demo environment `cjs-dashboard-demo` which is based on `cjs-dashboard-development`. The only differences are:
- Name of namespace
- Contact email
- Environment name (`staging` rather than `development`)

Create demo environment for CJS Dashboard

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domestic-abuse-support-officers-dev/resources/rds.tf

The RDS instance in this environment is a dev instance and so we should be using any auto-stop/start feature

Adding rds auto-stop-start for daso dev

---

namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-live-production/resources/user-datastore.tf

Remove the old DB from formbuilder-platform-live-production as we are now fully using the new DB

Form Builder - remove old DB from live-production

---

namespaces/live.cloud-platform.service.justice.gov.uk/cjs-dashboard-demo/resources/ecr.tf
namespaces/live.cloud-platform.service.justice.gov.uk/cjs-dashboard-demo/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/cjs-dashboard-demo/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/cjs-dashboard-demo/resources/variables.tf

Rename secrets used by GitHub Actions to clarify that these are for the demo environment.

Rename GitHub Actions secrets for CJS demo environment

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-interventions-prod/10-alerts.yaml

[Alert on the relative volume of slowness, not fixed count](https://github.com/ministryofjustice/cloud-platform-environments/commit/ea8b95ca4e55489a212244a9a882815bbc35b02a) 
`SlowResponses` will now alert if more than 1% of requests are slow, rather than "at least 10 requests were slow".
This works better in high-traffic scenarios where some requests are inevitably slow.
| Before | After |
|---|---|
|  <img width="1760" alt="image" src="https://user-images.githubusercontent.com/1526295/201092752-48fa7dca-5a8c-4ab2-9afb-61453c82a218.png"> | <img width="1760" alt="image" src="https://user-images.githubusercontent.com/1526295/201092555-3df0a139-97b1-4ac9-8162-4eddc5544fa5.png"> |
[Add an alert for extreme slowness](https://github.com/ministryofjustice/cloud-platform-environments/commit/96234 …

Rework slowness alerts to be relative

---

namespaces/live.cloud-platform.service.justice.gov.uk/prisoner-content-hub-production/resources/s3.tf

Output the S3 bucket name as a k8ns secret, to the staging and development namespaces.
This is to facilitate automated file syncing.  I.e. development and staging will have cronjobs that run `aws s3 sync` to copy files down from prod.
Note that only the bucket name is shared, and not the access key.
See https://github.com/ministryofjustice/prisoner-content-hub-backend/pull/482 for the PR to add the cronjob.

Prisoner content hub production - Output S3 bucket name to dev and staging

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-assessments-prod/08-grafana.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/peoplefinder-development/07-graffanadashboard.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/peoplefinder-staging/07-graffanadashboard.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/prisoner-content-hub-production/10-grafana.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/soc-production/07-soc-production-dashboard.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/ubi-prod/06-fum-production-dashboard.yaml

To make it unique to fix the issue:
dashboards provisioning provider has no database write permissions because of duplicates

Update uid for grafana dashboard

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-events-dev/resources/hmpps-incentives.tf

The `incentives-api` service now uses the newer/more specific `prisoner-offender-search.prisoner.alerts-updated` domain events so as soon as the code to process those newer events is deployed we can unsubscribe from the older events.

INC-958: Unsubscribe from `.prisoner.updated` domain events (DEV)

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-events-preprod/resources/hmpps-incentives.tf

The incentives-api service now uses the newer/more specific `prisoner-offender-search.prisoner.alerts-updated` domain events so as soon as the code to process those newer events is deployed we can unsubscribe from the older events.

INC-958: Unsubscribe from .prisoner.updated domain events (PREPROD)

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-events-prod/resources/hmpps-incentives.tf

The incentives-api service now uses the newer/more specific `prisoner-offender-search.prisoner.alerts-updated` domain events so as soon as the code to process those newer events is deployed we can unsubscribe from the older events.

INC-958: Unsubscribe from .prisoner.updated domain events (PROD)

---

namespaces/live.cloud-platform.service.justice.gov.uk/grc-dev/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/grc-preprod/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/grc-prod/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-prisoner-contacts-preprod/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-prisoner-contacts-prod/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-proceeding-prod/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-proceeding-staging/resources/versions.tf

These are all new namespaces set up in the past couple of days, so bumps their provider to match everyone elses.

Bump new namespaces terraform-aws-provider to ~> 4.27.0

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-pin-phone-monitor-dev/resources/iam.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-pin-phone-monitor-dev/resources/s3.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-pin-phone-monitor-prod/resources/iam.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-pin-phone-monitor-prod/resources/s3.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-pin-phone-monitor-qa/resources/iam.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-pin-phone-monitor-qa/resources/s3.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-probation-webops-poc/resources/s3.tf
namespaces/live.cloud-platform.service.justice.gov.uk/manage-soc-cases-dev/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/manage-soc-cases-preprod/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/manage-soc-cases-prod/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/pathfinder-dev/resources/athena-iam.tf
namespaces/live.cloud-platform.service.justice.gov.uk/pathfinder-dev/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/pathfinder-preprod/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/pathfinder-prod/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/track-a-move-dev/resources/athena-iam.tf
namespaces/live.cloud-platform.service.justice.gov.uk/track-a-move-dev/resources/book-a-secure-move-api-iam.tf
namespaces/live.cloud-platform.service.justice.gov.uk/track-a-move-prod/resources/athena-iam.tf
namespaces/live.cloud-platform.service.justice.gov.uk/track-a-move-prod/resources/book-a-secure-move-api-iam.tf
namespaces/live.cloud-platform.service.justice.gov.uk/track-a-move-uat/resources/athena-iam.tf

This PR replaces interpolation-only strings as deprecated in [Terraform 0.12.14](https://github.com/hashicorp/terraform/releases/tag/v0.12.14):
- Interpolation-only expressions are deprecated: an expression like "${foo}" should be rewritten as just foo.

Remove deprecated interpolation

---

namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-monitoring/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-audit-poc-api-dev/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-audit-poc-api-preprod/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-audit-poc-api-prod/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-external-users-api-dev/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-external-users-api-preprod/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-external-users-api-prod/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-external-users-api-stage/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-prisoner-to-nomis-update-dev/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-prisoner-to-nomis-update-preprod/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-prisoner-to-nomis-update-prod/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-template-kotlin/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-dev/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-prod/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-stage/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-test/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-uat/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-fee-calculator-production/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/maintenance-pages/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/monitoring/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/offender-management-test/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/prison-api-dev/resources/versions.tf

This PR removes unused providers from namespace `required_versions` definitions.

Remove unused providers from required_versions

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-auth-preprod/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-auth-preprod/04-networkpolicy.yaml

As per #9550
This is to enable cross-namespace networking from Make Recall Decisions pre-prod to HMPPS Auth pre-prod in order to help determine where the problem of ECONNABORT-related timeouts to auth is.
Background:
https://mojdt.slack.com/archives/C57UPMZLY/p1669283264160949
https://dsdmoj.atlassian.net/wiki/spaces/MRD/pages/4238213353/Connection+timeouts+on+make-recall-decisions-ui

Timeout investigations

---

namespaces/live.cloud-platform.service.justice.gov.uk/prisoner-content-hub-development/02-limitrange.yaml

Increase memory and cpu limits on development to match production.
We are seeing OOM errors related to a deployment.  We want to ensure the limit range on development matches that of production so we can test the deployment with real world settings.

Prisoner content hub development - increase memory limits

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-test/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-test/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-test/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-test/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-test/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-test/05-serviceaccount-circleci.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-test/06-certificates.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-test/resources/elasticache.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-test/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-test/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-test/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-test/resources/versions.tf

The CAS team need an enviroment that:
- has no real data
- can be stable for fixed periods to enable penetration tests and user research without the risk of deploying new features
We can see that there's a[ convention in the bootstrap](https://github.com/ministryofjustice/dps-project-bootstrap/blob/00708d619dd9bf352e4e98a48c3635d7f9cebba3/scripts/kubectl.sh#L112) for using `dev`, `staging`, `preprod` and `prod`. We'd like to use the name 'test' because we don't intend to use the environment as a staging area. 
There look to be a few existing namespaces with this suffix, though none of these appear in the bootstrap:
- [justicedata-test](https://github.com/ministryofjustice/cloud-platform-environments/tree/main/namespaces/live.cloud-platform.service.justice.gov.uk/justicedata-test)
- …

Create test environment for CAS

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-test/resources/variables.tf

In #9571, we introduced a new namepsace, which is essentially a copy of our dev environment, during the copy over, we forgot to change the tfvar with the name of the namespace, causing the pipeline to fail. This fixes it.

Fix typo in namespace name

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-test/06-certificates.yaml

This is a certificate that we’ll us for our Wiremock instance in our test environment to stub out external services

Add a new certificate

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-maat-test/03-resourcequota.yaml

[Link to Story on Crime Apps Modernisation Board](https://dsdmoj.atlassian.net/browse/LCAM-324)
- Updated config files in the laa-crime-maat-tests namespace to increase the pod limit from 50 to 100.
- A pods is allocated to each functional test and as the number of scenarios grows, the number of allowed pods also needs to increase to support this.

LCAM-324 Increase pods limit from 50 to 100 in the laa-crime-maat-test namespace

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-maat-test/resources/s3.tf

[Link to Story on Crime Apps Modernisation Board](https://dsdmoj.atlassian.net/browse/LCAM-325)
- Removed redundant S3 lifecycle rules
- New S3 lifecycle rule that expires intermediate test reports after 7 days

LCAM-325 New S3 lifecycle rule to expire intermediate tests reports

---

namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-repos/resources/repos.tf

This adds a new ECR repo for a new app in the
formbuilder-base-adapter-test namespace.
Co-authored-by: Hellema Ibrahim <hellema.ibrahim@digital.justice.gov.uk>
Co-authored-by: Steven Leighton <steven.leighton@digital.justice.gov.uk>

Form Builder - Add adapter template ECR repo

---

pkg/ingress/ingress.go
pkg/ingress/ingress_test.go

This PR update the ingress object to use networking/V1 API instead of v1beta1. 
All clusters on CP have upgraded to v1.22 where the v1beta1 Ingress API is deprecated. The reports which uses this package fails after the upgrade. This PR will fix that.

Update ingress package to use networking/v1 instead of v1beta1

---

.github/workflows/terraform-tools.yml

This PR introduces a job to run [tfsec](https://github.com/aquasecurity/tfsec) against this repository, and then upload the SARIF output to allow the users to view issues (if any) in the [Code Scanning](https://github.com/ministryofjustice/cloud-platform-infrastructure/security/code-scanning) view of the Security tab.
The current arguments provided to `tfsec` _exclude_ modules (i.e. any cloud-platform-terraform-*) and some checks. See notes below.
tfsec is currently configured to run with the following flags:
```sh
tfsec
--force-all-dirs # will recursively run tfsec
--no-module-downloads # won't download any modules, as we should fix direct terraform resources first to reduce noise
--soft-fail # doesn't fail the check, to still allow PRs to be merged
-m=HIGH # sets the minimum severity to …
```

Introduce TFSec to cloud-platform-environments

---

.github/workflows/terraform-tools.yml

This PR drops the minimum severity reporting level to `HIGH` for `TFSec`, and downloads all modules to perform that scan.
To reduce noise, this starts to ignore these two errors:
- aws-s3-encryption-customer-key
- aws-sqs-enable-queue-encryption
Once less common 'issues' are resolved, we can start reporting on more common issues.
This change (specifically downloading all modules) does increase the scan time, but shouldn't take too long (~1-3 minutes).

Drop TFSec minimum severity level to HIGH, ignore aws-s3-encryption-customer-key and aws-sqs-enable-queue-encryption

---

namespaces/live.cloud-platform.service.justice.gov.uk/pathfinder-dev/resources/analytical-platform-access.tf

This namespace has an `APPLY_SKIP` file so needs to be done separately.

Remove IRSA SA from pathfinder-dev

---

namespaces/live.cloud-platform.service.justice.gov.uk/check-financial-eligibility-partner-uat/04-networkpolicy.yaml

Enable pods in `laa-estimate-financial-eligibility-for-legal-aid-uat` namespace to make requests across network to pods in `check-financial-eligibility-partner-uat`.

Allow internal routing from CCQ UAT to CFE-Partner UAT

---

bin/apply
bin/apply-namespace-changes
lib/cp_env/namespace_dir.rb
spec/namespace_dir_spec.rb

This PR contains changes to the apply-pipeline and apply-changes-pipeline that will ignore a namespace that contains an empty file called `SECRET_ROTATE_BLOCK`.
The premise behind this change is to present the namespace owner with a PR containing a removal of this file. Once removed, all namespace IAM user credentials will be rotated, and the owner will then have to delete their pods.

Add secret rotation blocking file

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-prod/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-prod/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-prod/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-prod/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-prod/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-prod/05-serviceaccount-circleci.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-prod/06-certificates.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-prod/resources/elasticache.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-prod/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-prod/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-prod/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-prod/resources/versions.tf

Compared to preprod we change these notable values:
```
cloud-platform.justice.gov.uk/is-production: "true" 
cloud-platform.justice.gov.uk/environment-name: "production" 
cloud-platform.justice.gov.uk/slack-alert-channel: "dps_alerts"
```
We use dps_alerts as that seems to be the established pattern. We could put our cas-dev channel in it for production alerts. It doesn't appear that we can add an array so while it would be useful for us to get signals about prd problems, it's probably better that it go to the dps team who manage infrastructure.
Finally, from the hostnames we can finally remove the namespace suffixes from the subdomain eg. prod isn't in 'approved-premises.hmpps.service.justice.gov.uk'

Create CAS production namespace

---

namespaces/live.cloud-platform.service.justice.gov.uk/check-financial-eligibility-partner-production/04-networkpolicy.yaml

Allow the EFE prod namespace in the CFE-P prod network policy

Allow internal routing to production from EFE to CFE-P in production

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-uat/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-uat/resources/elasticache.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-uat/resources/s3.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-uat/resources/variables.tf

The contact email for the Civil Apply team was out of date and no longer existed.
This updates all references to the out-dated email in the `laa-apply-for-legalaid-uat` namespace.

Update `laa-apply-for-legalaid-uat` email

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-staging/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-staging/resources/elasticache.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-staging/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-staging/resources/s3.tf

The contact email for the Civil Apply team was out of date and no longer existed.
This updates all references to the out-dated email in the `laa-apply-for-legalaid-staging` namespace.

Update `laa-apply-for-legalaid-staging` email

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-production/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-production/resources/elasticache.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-production/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-production/resources/route53.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-production/resources/s3.tf

The contact email for the Civil Apply team was out of date and no longer existed.
This updates all references to the out-dated email in the `laa-apply-for-legalaid-production` namespace.

Update `laa-apply-for-legalaid-production` email

---

namespaces/live.cloud-platform.service.justice.gov.uk/legal-framework-api-uat/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/legal-framework-api-uat/resources/variables.tf

The contact email for the Civil Apply team (who maintain the Legal Framework API) was out of date and no longer existed.
This updates all references to the out-dated email in the `legal-framework-api-uat` namespace.

Update `legal-framework-api-uat` email

---

namespaces/live.cloud-platform.service.justice.gov.uk/legal-framework-api-staging/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/legal-framework-api-staging/resources/variables.tf

The contact email for the Civil Apply team (who maintain the Legal Framework API) was out of date and no longer existed.
This updates all references to the out-dated email in the `legal-framework-api-staging` namespace.

Update `legal-framework-api-staging` email

---

namespaces/live.cloud-platform.service.justice.gov.uk/legal-framework-api-production/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/legal-framework-api-production/resources/variables.tf

The contact email for the Civil Apply team (who maintain the Legal Framework API) was out of date and no longer existed.
This updates all references to the out-dated email in the `legal-framework-api-production` namespace.

Update `legal-framework-api-production` email

---

namespaces/live.cloud-platform.service.justice.gov.uk/check-financial-eligibility-uat/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/check-financial-eligibility-uat/resources/variables.tf

The contact email for the Civil Apply team (who maintain the Check Financial Eligibility API) was out of date and no longer existed.
This updates all references to the out-dated email in the `check-financial-eligibility-uat` namespace.

Update `check-financial-eligibility-uat` email

---

namespaces/live.cloud-platform.service.justice.gov.uk/check-financial-eligibility-staging/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/check-financial-eligibility-staging/resources/rds.tf

The contact email for the Civil Apply team (who maintain the Check Financial Eligibility API) was out of date and no longer existed.
This updates all references to the out-dated email in the `check-financial-eligibility-staging` namespace.

Update `check-financial-eligbility-staging` email

---

namespaces/live.cloud-platform.service.justice.gov.uk/check-financial-eligibility-production/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/check-financial-eligibility-production/resources/rds.tf

The contact email for the Civil Apply team (who maintain the Check Financial Eligibility API) was out of date and no longer existed.
This updates all references to the out-dated email in the `check-financial-eligibility-production` namespace.

Update `check-financial-eligibility-production` email

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-hmrc-interface-uat/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-hmrc-interface-uat/resources/variables.tf

The contact email for the Civil Apply team (who maintain the HMRC Interface API) was out of date and no longer existed.
This updates all references to the out-dated email in the `laa-hmrc-interface-uat` namespace.

Update `laa-hmrc-interface-uat` email

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-hmrc-interface-staging/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-hmrc-interface-staging/resources/variables.tf

The contact email for the Civil Apply team (who maintain the HMRC Interface API) was out of date and no longer existed.
This updates all references to the out-dated email in the `laa-hmrc-interface-staging` namespace.

Update `laa-hmrc-interface-staging` email

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-hmrc-interface-production/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-hmrc-interface-production/resources/variables.tf

The contact email for the Civil Apply team (who maintain the HMRC Interface API) was out of date and no longer existed.
This updates all references to the out-dated email in the `laa-hmrc-interface-production` namespace.

Update `laa-hmrc-interface-production` email

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-user-preferences-dev/01-rbac.yaml

This is to allow the dps-bootstrap scripts to be run

🔐 PIC-2679: Grant dps-tech access to hmpps-user-preferences-dev

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-user-preferences-preprod/01-rbac.yaml

This is to allow the dps-bootstrap scripts to be run

🔐 PIC-2679: Grant dps-tech access to hmpps-user-preferences-preprod

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-development/resources/api_gateway.tf

Double timeout to allow the certificate time to validate the route53 record

Add depends_on to certificate validation resource

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-audit-dev/resources/hmpps-community-accommodation.tf

Add audit queue secrets for hmpps-community-accommodation-dev namespace, to allow the service to use the hmpps-audit-service

Add audit queue secrets for hmpps-community-accommodation-dev namespace

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-hmrc-interface-staging/resources/elasticache.tf

[laa-hmrc-interface-staging] Bump redis 4.0.10.0 to 6.2+

---

namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-dev/08-certificate.yaml

Introduce a shorter dns name as suggested on the user guide as the current dnsname is too long.

Introduce a shorter dns name for the orchestration service.

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-development/resources/api_gateway.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-development/resources/variables.tf

- Add an API key for testing purposes and output it to a Kubernetes secret.
- Add usage plan for API Gateway.

Add an API key and usage plan to API Gateway for HMPPS Integration API development

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-pin-phone-monitor-prod/resources/iam.tf

This change will allow BT to perform a controlled rollout of a new limited permission IAM key to the BT kit at each prison.

Add BT access key to allow controlled rotation of IAM key to BT

---

namespaces/live.cloud-platform.service.justice.gov.uk/cjs-dashboard-development/02-limitrange.yaml

This PR increases the default memory request up to 2GB and the upper limit to 3GB. I'll open a corresponding PR for the demo environment after testing.

Increase memory limit for cjs-dashboard-development

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-development/resources/api_gateway.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-development/resources/iam.tf

This is to allow us to call API Gateway via the AWS CLI whilst we
continue to work out what resources we require. We'll reduce these
permissions once we've finalised the infrastructure.

Update api gateway for hmpps integration api development

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-audit-preprod/resources/hmpps-community-accommodation.tf

Add audit queue secrets for hmpps-community-accommodation-preprod namespace, to allow the service to use the hmpps-audit-service

Add audit queue secrets for hmpps-community-accommodation-preprod namespace

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-audit-prod/resources/hmpps-community-accommodation.tf

Add audit queue secrets for hmpps-community-accommodation-prod namespace, to allow the service to use the hmpps-audit-service

Add audit queue secrets for hmpps-community-accommodation-prod namespace

---

namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-dev/08-certificate.yaml

Further shorten dns name to prison-visits-orch-dev.prison.service.justice.gov.uk from prison-visits-orchestration-dev.prison.service.justice.gov.uk as staging and preprod will otherwise go beyond the 64 character limit.

Further shorten dns name for orchestration service - dev

---

namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-staging/08-certificate.yaml

Add a shorter dns name on staging to stick to the 64 character limit for a dns name.

Add a shorter dns name to stick to the 64 character limit - staging

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-staging/resources/elasticache.tf

[laa-apply-for-legalaid-staging] Bump redis 4.0.10.0 to 6.2+

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-hmrc-interface-production/resources/elasticache.tf

[laa-hmrc-interface-production] Bump redis 4.0.10.0 to 6.2+

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-development/resources/api_gateway.tf

We want to serve API requests on the root path "/".

Remove "/development" path from API Gateway URL

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-ui-dev/resources/elasticache.tf

- Bump Elasticache engine_version to `6.x`
- Update parameter_group_name accordingly
##
Environment: Dev

CTSKF-225 - Bump Elasticache cluster to 6.x

---

namespaces/live.cloud-platform.service.justice.gov.uk/cjs-dashboard-production/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/cjs-dashboard-production/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/cjs-dashboard-production/resources/ecr.tf
namespaces/live.cloud-platform.service.justice.gov.uk/cjs-dashboard-production/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/cjs-dashboard-production/resources/variables.tf

Some edits to the existing CJS production placeholder environment:
- Increase memory
- Rename secrets used by GitHub Actions to avoid overlap with demo and dev

Prepare CJS dashboard production environment

---

namespaces/live.cloud-platform.service.justice.gov.uk/cjs-dashboard-production/resources/serviceaccount.tf

Adding a serviceaccount so we can use the Kubernetes secrets in GitHub Actions.
@LauraKnowles, could you merge this once it gets approved? 😄

Add serviceaccount to cjs-dashboard-production

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-audit-dev/resources/visit-someone-in-prison-front-end-staging.tf

The VSiP staging namespace (`visit-someone-in-prison-frontend-svc-staging`) has a manually created `sqs-hmpps-audit-secret` - highlighted when this secret was recently rotated. This change is to manage this secret for the staging environment within code.

VB-1716: Add HMPPS Audit secrets for VSiP staging env

---

namespaces/live.cloud-platform.service.justice.gov.uk/courts-local-scorecard-prod/05-certificate.yaml

Remove the cert from the old site so that we can add this to the new site namespace.

Remove old domain cert

---

namespaces/live.cloud-platform.service.justice.gov.uk/money-to-prisoners-test/resources/rds.tf

Retry of #10073
Depends on #9944
AWS docs have changed and suggest 10.21 can only go up to 14.3 (they used to say 14.4) but haven’t checked against API.

Upgrade `money-to-prisoners` test database – step 2 of 3

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-hmrc-interface-production/resources/rds.tf

Upgrade db_instane_class to db.t3.medium
from db.t2.small.
In preparation for upgrade to Postgres14

Upgrade db_instane_class to db.t3.medium

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-criminal-legal-aid-staging/resources/serviceaccount.tf

Without these, it still fails to apply the resources.

Add missing verbs to service account

---

cmd/check-terraform-modules-are-latest/main.go

When the RawOption (the type of PR diff to fetch) is set to patch the request returns every change. This means the current module is actually set to the initial commit value, therefore failing even when newer commits are pushed. Using "diff" instead of patch allows the diff to contain only the latest change.
for example:
- [patch](https://patch-diff.githubusercontent.com/raw/ministryofjustice/cloud-platform-environments/pull/10294.patch)
- [diff](https://patch-diff.githubusercontent.com/raw/ministryofjustice/cloud-platform-environments/pull/10294.diff)

fix: 🐛 patch -> diff for the the code changes

---

namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-staging/resources/ecr.tf

Uppercase staging env name and re-trigger build so that these secrets are recreated in the GitAction area.

Modify GitAction environment reference

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-incentives-prod/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-incentives-prod/resources/variables.tf

Changed DB instance class to `db.t4g.large`.
Also:
- added deletion protection
- added backup/maintenance window
- added explicit `allow_minor_version_upgrade = true` (this was already the case because of the [TF module default](https://github.com/ministryofjustice/cloud-platform-terraform-rds-instance#input_allow_minor_version_upgrade) for this value)
The [module has `apply_immediately = true `](https://github.com/ministryofjustice/cloud-platform-terraform-rds-instance/blob/64a95b9785d72009ec979a52053cd1400effa8c8/main.tf#L110) which means once this is merged the change will be applied straight away.
The backup/maintenance window are added for other/future automated changes (e.g. minor version upgrades or patching)
The [module configures the database as a …

INC-964: Increase Incentives prod DB instance class

---

namespaces/live.cloud-platform.service.justice.gov.uk/cccd-production/resources/elasticache.tf

**Note:** This is branched off #10573 and that PR should be deployed first so that the redis server is upgraded successfully before a new instance type is used.

Update cccd production redis instance to t4g 

---

cmd/check-terraform-modules-are-latest/README.md
cmd/check-terraform-modules-are-latest/go.mod
cmd/check-terraform-modules-are-latest/main.go
cmd/push-terraform-module-version/Dockerfile
cmd/push-terraform-module-version/README.md
cmd/push-terraform-module-version/go.mod
cmd/push-terraform-module-version/main.go
cmd/push-terraform-module-version/push-terraform-module-version.yaml

Add a GitHub action which should be added to `cloud-platform-terraform-*` repos, so that when a new module version is released we capture that new version in our API too.
The action is simple. It fires a post request that updates the api.

feat: 🎸 push updated terraform module version to api

---

namespaces/live.cloud-platform.service.justice.gov.uk/cccd-dev-lgfs/resources/elasticache.tf

The latest major version of the redis gem requires that the dummy username is not present in the url. CCCD currently has a fix that will strip it out but this fix will be removed once the urls are fixed here.

Remove unnecessary username from redis url

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-hmrc-interface-production/resources/rds.tf

Change laa-hmrc-api-prod db_instance_class to db.t4g.small
from db.t3.medium, following upgrade to Postgres14

Change db_instance_class to db.t4g.small

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-events-dev/resources/hmpps-community-accommodation.tf

The CAS1 (Approved Premises) service needs to emit domain events onto SNS and therefore needs credentials to do so.

Add Domain Events secrets to Community Accommodation dev namespace

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-events-preprod/resources/hmpps-community-accommodation.tf

The CAS1 (Approved Premises) service needs to emit domain events onto SNS and therefore needs credentials to do so.

Add Domain Events secrets to Community Accommodation preprod namespace

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-events-prod/resources/hmpps-community-accommodation.tf

The CAS1 (Approved Premises) service needs to emit domain events onto SNS and therefore needs credentials to do so.

Add Domain Events secrets to Community Accommodation prod namespace

---

namespaces/live.cloud-platform.service.justice.gov.uk/abundant-namespace-dev/resources/elasticsearch.tf
namespaces/live.cloud-platform.service.justice.gov.uk/abundant-namespace-staging/resources/elasticsearch.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-historical-prisoner-dev/resources/es.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-intelligence-test/resources/elasticsearch.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-probation-search-dev/resources/es.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-probation-search-preprod/resources/es.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-probation-search-prod/resources/es.tf
namespaces/live.cloud-platform.service.justice.gov.uk/jakemulley-refactor/resources/elasticsearch.tf
namespaces/live.cloud-platform.service.justice.gov.uk/manage-intelligence-dev/resources/elasticsearch.tf
namespaces/live.cloud-platform.service.justice.gov.uk/peoplefinder-demo/resources/elasticsearch.tf
namespaces/live.cloud-platform.service.justice.gov.uk/peoplefinder-development/resources/elasticsearch.tf
namespaces/live.cloud-platform.service.justice.gov.uk/peoplefinder-production/resources/elasticsearch.tf
namespaces/live.cloud-platform.service.justice.gov.uk/peoplefinder-staging/resources/elasticsearch.tf
namespaces/live.cloud-platform.service.justice.gov.uk/prisoner-content-hub-development/resources/elasticsearch.tf
namespaces/live.cloud-platform.service.justice.gov.uk/prisoner-content-hub-production/resources/elasticsearch.tf
namespaces/live.cloud-platform.service.justice.gov.uk/prisoner-content-hub-staging/resources/elasticsearch.tf
namespaces/live.cloud-platform.service.justice.gov.uk/prisoner-offender-search-dev/resources/es.tf
namespaces/live.cloud-platform.service.justice.gov.uk/prisoner-offender-search-preprod/resources/es.tf
namespaces/live.cloud-platform.service.justice.gov.uk/prisoner-offender-search-prod/resources/es.tf

This release have a fix for domain_name no more than 28 characters long

Update elastic search to use the latest version

---

namespace-resources-cli-template/resources/variables.tf
namespace-resources-cli-template/resources/versions.tf

This PR does a couple of things. It:
- adds an empty `outputs.tf` file to meet the standard Terraform structure
- removes the unused `cluster_state_bucket` variable, as it isn't used by any current namespace
- adds descriptions and value types to variables that were missing them
- pins the GitHub provider to `~> 5.17.0`

Remove unused variables and tidy up the namespace-resources-cli-template

---

namespaces/live.cloud-platform.service.justice.gov.uk/cloud-platform-canary-app-eks/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-event-logger-dev/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-event-logger-preprod/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-event-logger-prod/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/paul-test/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/swestest-dev/resources/versions.tf

This PR bumps 6 namespaces' Terraform AWS provider version to match the mostly-used `~> 4.27.0` version, which is also the default in [`namespace-resources-cli-template`](https://github.com/ministryofjustice/cloud-platform-environments/blob/main/namespace-resources-cli-template/resources/versions.tf#L6).
There are 3 other namespaces that use `~> 4.29.0`, which need some testing to either drop to `~> 4.27.0` to match everyone else, or leave as is.

Bump AWS version to ~> 4.27.0 to match namespace-resources-cli-template

---

namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-dev/resources/s3.tf

We are using a plugin that connects from within the pod to the s3 bucket and requires access to push/pull files. We initially tried using a bucket policy but it looks like we actually needed to switch this to a user level policy which these changes reflect.

Update s3 policy to apply to user not bucket

---

namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-dev/resources/claim-criminal-injuries-application-queue.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-development/resources/api_gateway.tf

Terraform v0.12.4 deprecated interpolation-only expressions, so this PR replaces where it was in use to call the value directly.
See [Terraform v0.12.4 release notes](https://github.com/hashicorp/terraform/releases/tag/v0.12.14) for more details.

Replace deprecated interpolation syntax

---

.github/workflows/terraform-tools.yml

This check is causing some false positives when using a `GitHub` resource, so this turns it off for now whilst we refine it.

Turn off github-actions-no-plain-text-action-secrets check, as needs refining

---

namespace-resources-cli-template/resources/main.tf

This PR adds the `source-code` and `slack-channel` default tags to the namespace/*/resources CLI template. This allows us to start to do a couple of things amongst other stuff:
- identify resources created through cloud-platform-environments by viewing their tags
- automate slack channel alerts for resources based on resource tags
This only affects new namespaces created with the CLI, separate PRs incoming to backport this to previously created namespaces.

Add default_tags for source-code, slack-channel to namespace-resources-cli-template

---

namespaces/live.cloud-platform.service.justice.gov.uk/make-recall-decision-db-analysis/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/make-recall-decision-db-analysis/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/make-recall-decision-db-analysis/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/make-recall-decision-db-analysis/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/make-recall-decision-db-analysis/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/make-recall-decision-db-analysis/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/make-recall-decision-db-analysis/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/make-recall-decision-db-analysis/resources/versions.tf

Created using cloud-platform environment create for spinning up resources to analyse the PPUD database as part of an exploratory phase for make recall decisions.

Create namespace for make-recall-decision-db-analysis

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-temporary-accommodation-prototype/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-temporary-accommodation-prototype/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-temporary-accommodation-prototype/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-temporary-accommodation-prototype/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-temporary-accommodation-prototype/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-temporary-accommodation-prototype/resources/basic-auth.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-temporary-accommodation-prototype/resources/ecr.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-temporary-accommodation-prototype/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-temporary-accommodation-prototype/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-temporary-accommodation-prototype/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-temporary-accommodation-prototype/resources/versions.tf

Namespace created using `cloud-platform environment prototype create`, with manual fixes to `ecr.tf` and `serviceaccount.tf` to address [this failure](https://github.com/ministryofjustice/cloud-platform-environments/actions/runs/4292867850/jobs/7479833879) and [this failure](https://github.com/ministryofjustice/cloud-platform-environments/actions/runs/4292922227/jobs/7479955004).

Add namespace for Temporary Accommodation Prototype

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-assure-hmrc-data-staging/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-assure-hmrc-data-staging/resources/variables.tf

[laa-assure-hmrc-data-staging] Add named serviceaccount secrets
Because we need to deploy to several environments
via GHA this pattern allows secrets to be authomtically created
with an "environment" specific name. Automatic or CP initiated
rotation of these secrets, in the event of a breach, would then
be transparent.

[laa-assure-hmrc-data-staging] Add named serviceaccount secrets

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-assure-hmrc-data-uat/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-assure-hmrc-data-uat/resources/variables.tf

Add serviceaccount with named secrets
Serviceaccount for GHA pipeline
Because we need to deploy to several environments
via GHA this pattern allows secrets to be authomtically created
with an "environment" specific name. Automatic or CP initiated
rotation of these secrets, in the event of a breach, would then
be transparent.

[laa-assure-hmrc-data-uat] Add serviceaccount with named secrets

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-assure-hmrc-data-production/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-assure-hmrc-data-production/resources/variables.tf

Add serviceaccount with named secrets
Serviceaccount for GHA pipeline
Because we need to deploy to several environments
via GHA this pattern allows secrets to be authomtically created
with an "environment" specific name. Automatic or CP initiated
rotation of these secrets, in the event of a breach, would then
be transparent.

[laa-assure-hmrc-data-production] Add serviceaccount with named secrets

---

namespaces/live.cloud-platform.service.justice.gov.uk/offender-events-dev/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/offender-events-dev/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/offender-events-preprod/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/offender-events-preprod/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/offender-events-prod/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/offender-events-prod/resources/versions.tf

The version argument inside provider configuration blocks has been deprecated since Terraform 0.12, so this PR moves the version constraint into the required_provider configuration instead.
[Source - under "UPGRADE NOTES"](https://github.com/hashicorp/terraform/blob/v0.14/CHANGELOG.md)
Note that the provider version for this provider is outdated, and will be updated in a subsequent PR.

Remove deprecated version specification from provider to required_provider

---

namespace-resources-cli-template/resources/versions.tf

Most namespaces utilise the `kubernetes` provider, so this adds it in by default to the `namespace-resources-cli-template`.

namespace-resources-cli-template, versions integrity: set kubernetes as a required provider

---

namespaces/live.cloud-platform.service.justice.gov.uk/cloud-platform-canary-app-eks/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/cloud-platform-metrics/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/cloud-platform-reference-app-github-action/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/cloud-platform-reference-app/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/cloudplatformdiscovery-fs/resources/versions.tf

live, cloud-platform services, versions integrity: set required_providers versions

---

namespaces/live.cloud-platform.service.justice.gov.uk/accessibility-book-club/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/anthony-britton/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/ap-app-poc-bde/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/approved-premises-design-history/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/cccd-api-sandbox/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/cccd-dev-lgfs/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/cjs-dashboard-demo/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/dex-ia-proto/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/eligibility-estimate/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-demo/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-prisoner-education-design-history/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-rap-design-history/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/interventions-design-history/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/isaiah-lakanu/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/jason-design-demo/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/maintenance-pages/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/makerecalldecisions-design-history/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/manage-pom-cases-design-history/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/manage-supervisions-design-history/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/peoplefinder-demo/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/record-a-goose-exercise/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/record-a-goose-sighting/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/rob-sandbox/resources/versions.tf

live, other non-production, versions integrity: set required_providers versions

---

namespaces/live.cloud-platform.service.justice.gov.uk/abundant-namespace-testing-sw/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/dex-ian-dotnet-test/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/evidencelibrary-test/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-publisher-test/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-saas-test/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-test/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-intelligence-test/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/justicedata-test/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-test/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-evidence-test/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-maat-test/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-means-assessment-test/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-contribution-test/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-proceeding-test/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/money-to-prisoners-test/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/nettest/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/paul-test/resources/versions.tf

live, test, versions integrity: set required_providers versions

---

namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-monitoring/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-publisher-live/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-repos/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-saas-live/resources/versions.tf

live, formbuilder services, versions integrity: set required_providers versions

---

namespaces/live.cloud-platform.service.justice.gov.uk/moj-frontend/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/monitoring/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/request-info-from-moj/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/track-a-query-qa/resources/versions.tf

live, unqualified namespaces, versions integrity: set required_providers versions

---

namespaces/live-2.cloud-platform.service.justice.gov.uk/cloud-platform-canary-app-eks/resources/versions.tf
namespaces/live-2.cloud-platform.service.justice.gov.uk/cloud-platform-dev/resources/versions.tf
namespaces/live-2.cloud-platform.service.justice.gov.uk/cloud-platform-go-get-module/resources/versions.tf
namespaces/live-2.cloud-platform.service.justice.gov.uk/cloud-platform-reference-app-dev/resources/versions.tf
namespaces/live-2.cloud-platform.service.justice.gov.uk/cloud-platform-reference-app-github-action-dev/resources/versions.tf
namespaces/live-2.cloud-platform.service.justice.gov.uk/cloud-platform-reports-dev/resources/versions.tf
namespaces/live-2.cloud-platform.service.justice.gov.uk/jacksapp-dev/resources/versions.tf
namespaces/live-2.cloud-platform.service.justice.gov.uk/monitoring/resources/versions.tf
namespaces/live-2.cloud-platform.service.justice.gov.uk/poornima-dev/resources/versions.tf
namespaces/live-2.cloud-platform.service.justice.gov.uk/vijay-beta/resources/versions.tf

This PR does three things:
- removes unused providers for a namespace from `required_providers`
- bumps `hashicorp/aws` from `4.23.0` to `~> 4.27.0` to match `live.`
- adds in missing providers and specified versions
This means these namespaces, when run through Concourse, will use the latest patch in the version constraint that is declared, giving us some some further confidence that they're running the "correct"/declared version of the specific provider. It also means that where previously versions weren't defined, the namespace will not jump to the next major version of a release without explicitly updating it.

live-2, versions integrity: set required_providers versions

---

namespaces/live.cloud-platform.service.justice.gov.uk/cfe-civil-uat/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/check-financial-eligibility-partner-uat/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/check-financial-eligibility-uat/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-uat/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-uat/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-frontend-uat/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-uat/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-cla-backend-uat/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-cla-frontend-uat/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-uat/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-api-uat/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-ui-uat/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-evidence-uat/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-means-assessment-uat/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-contribution-uat/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-proceeding-uat/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-estimate-financial-eligibility-for-legal-aid-uat/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-hmrc-interface-uat/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/legal-framework-api-uat/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/track-a-move-uat/resources/versions.tf

live, uat, versions integrity: set required_providers versions

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domestic-abuse-support-officers-shared/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-incentives-tool/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-pin-phone-monitor-qa/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-prisoner-education/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-probation-integration/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-template-typescript/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-victim-case-management-system-shared/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/manage-a-workforce/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/pfs-education-admin-tool/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/polygraph-offender-management/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/prisoner-content-hub-db-backups/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/workforce-management/resources/versions.tf

live, hmpps services, versions integrity: set required_providers versions

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-cla-backend-training/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-cla-end-to-end-tests/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-cla-frontend-training/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-test-viewer/resources/versions.tf

live, LAA services, versions integrity: set required_providers versions

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-assure-hmrc-data-staging/certificate.yaml

Add TLS certificate for custom staging domain
Friendlier domain name as sub domain of
intended, eventual, production domain assure-hmrc-data.

Add TLS certificate for custom staging domain

---

namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-dev/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-prod/resources/versions.tf

This PR bumps namespaces that use `hashicorp/kubernetes@1.x.x` to its latest minor release, in preparation for upgrading to `hashicorp/kubernetes@2.x.x`.

Bump hashicorp/kubernetes to v1.13.0

---

namespaces/live.cloud-platform.service.justice.gov.uk/ap-auth-proxy-prod/resources/ecr.tf
namespaces/live.cloud-platform.service.justice.gov.uk/grc-prod/resources/ecr.tf
namespaces/live.cloud-platform.service.justice.gov.uk/sjpr-prod/resources/ecr.tf

- grc-prod : Users use the pre-prod secrets so not a issue
- sjpr-prod - Updates the secret  automatically to github action secrets
- ap-auth-proxy-prod. No app deployed in the namespace

Update ecr module from 4.9 - 5.1.0

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-probation-search-preprod/resources/es.tf

Due to errors relating to throughput:
```
Error: error updating Elasticsearch Domain config: LimitExceededException: Throughput must be between 250 and 593
```

PI-832 Reduce volume size to 128GB

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-assure-hmrc-data-production/certificate.yaml

Add TLS certificate for custom domain name in hosted zone
Intended domain name.

[laa-assure-hmrc-data-production] Add TLS certificate for custom domain

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-dev/01-rbac.yaml

We have 8 other namespaces that need this change too - can they be added to this PR or should they be individual PRs?
[P4-4132]

chore: Give github:dps-tech group access to BaSM API dev

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-preprod/01-rbac.yaml

chore: Give github:dps-tech group access to BaSM API preprod

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-production/01-rbac.yaml

chore: Give github:dps-tech group access to BaSM API production

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-staging/01-rbac.yaml

chore: Give github:dps-tech group access to BaSM API staging

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-uat/01-rbac.yaml

chore: Give github:dps-tech group access to BaSM API UAT

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-frontend-preprod/01-rbac.yaml

chore: Give github:dps-tech group access to BaSM frontend preprod

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-frontend-production/01-rbac.yaml

chore: Give github:dps-tech group access to BaSM frontend production

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-frontend-staging/01-rbac.yaml

chore: Give github:dps-tech group access to BaSM frontend staging

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-frontend-uat/01-rbac.yaml

chore: Give github:dps-tech group access to BaSM frontend UAT

---

namespaces/live.cloud-platform.service.justice.gov.uk/prisoner-offender-search-preprod/02-limitrange.yaml

Reverts ministryofjustice/cloud-platform-environments#11263
This is setting the CPU requests for all pods in that namespace to have 1 core which leads to node scaling up.
Informed user to set the request per deployment and not namespace level
@mikehalmamoj FYI

Revert "SDIT-650 Experiment with CPU request to fix slow startup"

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-development/resources/api_gateway.tf
namespaces/live.cloud-platform.service.justice.gov.uk/track-a-move-dev/resources/acm.tf
namespaces/live.cloud-platform.service.justice.gov.uk/track-a-move-prod/resources/acm.tf
namespaces/live.cloud-platform.service.justice.gov.uk/track-a-move-uat/resources/acm.tf

This PR updates `aws_acm_certificate` resources by adding a `lifecycle` block, so in the event of the certificate needing to be recreated, Terraform will create a new certificate before revoking the previous one.

Resolve aws_acm_certificate lifecycle by telling Terraform to create a new certificate before destroying the old one (if necessary)

---

namespaces/live.cloud-platform.service.justice.gov.uk/pathfinder-preprod/resources/cross-iam-role-sa.tf
namespaces/live.cloud-platform.service.justice.gov.uk/pathfinder-prod/resources/cross-iam-role-sa.tf

I compared these with the direct variables (e.g. `variable "is_production"`) and they're the same.

Remove unused pathfinder- variables

---

namespaces/live.cloud-platform.service.justice.gov.uk/calculate-journey-variable-payments-dev/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/calculate-journey-variable-payments-preprod/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/calculate-journey-variable-payments-prod/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-assessments-dev/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-ems-prod/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-dev/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-preprod/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-prod/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-restricted-patients-dev/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-restricted-patients-preprod/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-restricted-patients-prod/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/maintenance-pages/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/prison-services-feedback-and-support-dev/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/prison-services-feedback-and-support-preprod/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/prison-services-feedback-and-support-prod/resources/variables.tf

These namespaces already have an equivalent (`team_name`, `slack_channel`) so this removes the unused, legacy-style dash variables.

Remove legacy-style dash variables: team-name, slack-channel

---

namespaces/live.cloud-platform.service.justice.gov.uk/calculate-journey-variable-payments-dev/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/calculate-journey-variable-payments-preprod/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/calculate-journey-variable-payments-prod/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-assessments-dev/resources/variables.tf

All these namespaces have both `business-unit` and `business_unit` variables, so this removes `business-unit` from them.

Remove legacy-style dash variables from namespaces that already have the new style: business-unit

---

namespaces/live.cloud-platform.service.justice.gov.uk/token-verification-api-preprod/resources/elasticache.tf

Upgraded token-verification-api-preprod elasticache redis from "5.0.6" to V7

HAAR-1248: Upgraded token-verification-api-preprod elasticache redis

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-criminal-applications-datastore-staging/resources/sns-application-events.tf

Follow up to PR #11514.
For SNS subscriptions it seems there is no `maxReceiveCount` attribute.
> (RedrivePolicy): InvalidParameter: Invalid parameter: RedrivePolicy: invalid JSON. Attribute maxReceiveCount is unknown.

Remove maxReceiveCount from redrive policy

---

namespaces/live.cloud-platform.service.justice.gov.uk/legal-framework-api-staging/resources/rds.tf

This temporarily updates the db instance class from `db.t2.small` to `db.t3.small` ahead of an engine version upgrade.
The current db instance class is deprecated and not supported for PostgreSQL 14.
Before we can upgrade to the recommended instance class (db.t4g.small), we need to update to a class that is compatible with v11 (i.e t3).
The size of the database has been temporarily upgraded to `large` to speed up the subsequent database upgrade.

Upgrade `legal-framework-api-staging` db instance class

---

namespaces/live.cloud-platform.service.justice.gov.uk/legal-framework-api-staging/resources/rds.tf

In #11543, we attempted to upgrade to postgres 14, however the [subsequent build failed](https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/environments-live/jobs/apply-namespace-changes-live/builds/4308).
This attempts to resolve the issue by specifying a valid upgrade target version explicitly.

Upgrade `legal-framework-api-staging` to PostgreSQL 14.4

---

namespaces/live.cloud-platform.service.justice.gov.uk/legal-framework-api-production/resources/rds.tf

This temporarily updates the db instance class from `db.t2.small` to `db.t3.small` ahead of an engine version upgrade.
The current db instance class is deprecated and not supported for PostgreSQL 14.
Before we can upgrade to the recommended instance class (db.t4g.small), we need to update to a class that is compatible with v11 (i.e t3).
The size of the database has been temporarily upgraded to `large` to speed up the subsequent database upgrade.

Upgrade `legal-framework-api-production` db instance class

---

namespaces/live.cloud-platform.service.justice.gov.uk/legal-framework-api-production/resources/rds.tf

This updates the database to the newest available target upgrade version for PostgreSQL 14 (i.e 14.4).

Upgrade to `legal-framework-api-production` to PostgreSQL 14

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-accredited-programmes-dev/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-accredited-programmes-dev/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-accredited-programmes-dev/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-accredited-programmes-dev/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-accredited-programmes-dev/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-accredited-programmes-dev/05-serviceaccount-circleci.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-accredited-programmes-dev/06-certificates.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-accredited-programmes-dev/resources/elasticache.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-accredited-programmes-dev/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-accredited-programmes-dev/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-accredited-programmes-dev/resources/versions.tf

Adds namespace for Accredited Programmes dev project, which will consist of a Typescript UI and Kotlin API.
This is my first time setting up a new project on the Cloud Platform, so most of this is new to me and I've taken a lot of this from existing examples. 
Please let me know if I've got the wrong end of the stick on anything here!

Initialise namespace for Accredited Programmes dev

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-accredited-programmes-test/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-accredited-programmes-test/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-accredited-programmes-test/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-accredited-programmes-test/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-accredited-programmes-test/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-accredited-programmes-test/05-serviceaccount-circleci.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-accredited-programmes-test/06-certificates.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-accredited-programmes-test/resources/elasticache.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-accredited-programmes-test/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-accredited-programmes-test/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-accredited-programmes-test/resources/versions.tf

This creates a new namespace for the test environment for the Accredited Programmes project, and is heavily adapted from the dev environment PR #11731.
Again, please let me know if I've missed anything here.

Add namespace for Accredited Programmes Test env

---

namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-staging/resources/s3.tf

Add public access for the website to use for public media assets, docs, images etc.

Add public access for WordPress to s3 bucket

---

namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-staging/resources/s3.tf

WordPress needs public access to the s3 bucket.

Add public assess via ACL

---

namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-demo/resources/s3.tf

WP needs access to a public s3 bucket to serve it's web content from.

Provide public access to s3 bucket so that WP can serve media assets

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-development/resources/api_gateway.tf

Create the certificate and export the contents to a kubernetes secret. This certificate will be sent to the backend API on each request.

API Gateway client certificate to backend API

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-development/resources/api_gateway.tf

This will force the order of the apply to resolve this error:
"Error: Error creating Gateway base path mapping: BadRequestException: Invalid stage identifier specified"

Reference api_gateway_stage to get stage name

---

.github/workflows/compare-namespaces.yaml
cmd/compare-namespace/compare-namespace.go
cmd/compare-namespace/templates/resources/test.tf

- fix(workflow): Comment out workflow for namespace check to forward fix go script
- fix(cmd): fix to stop mismatching with empty namespace blocks

fix(cmd): fix to stop mismatching with empty namespace blocks

---

namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-prod/resources/s3.tf

Allows public access to WordPress for s3 sync. Expectation is that the bucket will always be publicly accessible.

Add public read access ACL - 2 of 2

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-events-dev/resources/hmpps-activities-management.tf

The activities service currently only subscribes to the released event, and this PR adds the following extra events to this:
"prison-offender-events.prisoner.received"
"prison-offender-events.prisoner.merged"
"prison-offender-events.prisoner.cell.move"
"incentives.iep-review.inserted"
"incentives.iep-review.updated"
"incentives.iep-review.deleted"

SAA-511: Add more events to the activities subscription filter.

---

namespaces/live.cloud-platform.service.justice.gov.uk/prisoner-content-hub-development/resources/rds.tf

This is the recommended isolation level for our CMS. See https://www.drupal.org/docs/getting-started/system-requirements/setting-the-mysql-transaction-isolation-level

🗃️  set database isolation level to READ-COMMITTED for prisoner content hub backend in development namespace.

---

namespaces/live.cloud-platform.service.justice.gov.uk/offender-management-staging/resources/elasticache.tf

Required to discared compromised creds which were rotated out

Expose MPC staging redis keys

---

namespaces/live.cloud-platform.service.justice.gov.uk/prisoner-content-hub-staging/resources/rds.tf

As https://github.com/ministryofjustice/cloud-platform-environments/pull/11979 but for staging instead of development.

🗃️  set database isolation level to READ-COMMITTED for prisoner content hub backend in staging namespace.

---

namespaces/live.cloud-platform.service.justice.gov.uk/offender-management-staging/resources/elasticache.tf

I believe that when trying to rotate with engine version 4.0, something got confused and now we cannot access redis even after the version upgrade. Hopefully this new rotation will set the auth token correctly everywhere - the cluster and the k8s secret - making it usable by us again.

offender-management-staging: Rotate redis token again

---

namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-production/resources/route53.tf

This PR adds the records required for PagerDuty to use a custom domain for the status page's frontend and emails

Adding Records for Data Platform PagerDuty Status Page

---

namespaces/live.cloud-platform.service.justice.gov.uk/jakemulley-development/resources/rds.tf

`mysql` and `mariadb` don't support performance insights

jakemulley-development: turn off performance insights for mysql, mariadb

---

namespaces/live.cloud-platform.service.justice.gov.uk/cfe-civil-production/04-networkpolicy.yaml

Allow any CCQ environment to use CFE-Civil Prod (temporarily), in cases if there are temporary issues with CFE-Civil UAT/Staging.
Discussion:
https://mojdt.slack.com/archives/C04TQBBDG2D/p1681381262859979?thread_ts=1681376455.047959&cid=C04TQBBDG2D

Allow any CCQ environments to use CFE-Civil Prod

---

namespaces/live.cloud-platform.service.justice.gov.uk/paul-test/01-rbac.yaml

This is to test non-admin dummy-user permissions for modsec logs

Use test-webops for paul-test namespace

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-production/resources/s3.tf

This is used to do the mutual TLS, and requires a common name that points to the production URL

Add self-signed CA for production

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-hmrc-interface-uat/resources/rds.tf

Enable rds auto start stop for laa-hmrc-interface

enable rds auto start stop for laa-hmrc-interface

---

namespaces/live.cloud-platform.service.justice.gov.uk/abundant-namespace-dev/resources/sns.tf
namespaces/live.cloud-platform.service.justice.gov.uk/cccd-dev-lgfs/resources/messaging.tf
namespaces/live.cloud-platform.service.justice.gov.uk/cccd-dev/resources/messaging.tf
namespaces/live.cloud-platform.service.justice.gov.uk/cccd-production/resources/messaging.tf
namespaces/live.cloud-platform.service.justice.gov.uk/cccd-staging/resources/messaging.tf
namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-dev/resources/court-case-events-sns-topic.tf
namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-preprod/resources/court-case-events-sns-topic.tf
namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-prod/resources/court-case-events-sns-topic.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-events-dev/resources/hmpps-domain-events-topic.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-events-preprod/resources/hmpps-domain-events-topic.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-events-prod/resources/hmpps-domain-events-topic.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-criminal-applications-datastore-staging/resources/sns-application-events.tf
namespaces/live.cloud-platform.service.justice.gov.uk/offender-events-dev/resources/topic.tf
namespaces/live.cloud-platform.service.justice.gov.uk/offender-events-preprod/resources/topic-perf.tf
namespaces/live.cloud-platform.service.justice.gov.uk/offender-events-preprod/resources/topic.tf
namespaces/live.cloud-platform.service.justice.gov.uk/offender-events-prod/resources/topic.tf
namespaces/live.cloud-platform.service.justice.gov.uk/offender-management-staging/resources/sns.tf

sns module now supports provisioning of additional IAM user/keys for shared topics as per:
https://app.zenhub.com/workspaces/cloud-platform-team-5ccb0b8a81f66118c983c189/issues/gh/ministryofjustice/cloud-platform/4383

update sns topics to latest release

---

namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-prod/resources/ccrc-route53.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-prod/resources/imb-route53.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-prod/resources/magistrates-route53.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-prod/resources/publicdefenderservice-route53.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-prod/resources/victimscommissioner-route53.tf

When migrating over to CloudPlatforms we need to have our route53 configuratins setup for our domains that reside on multisite.

Add new route53 configs for multisite domains

---

namespaces/live.cloud-platform.service.justice.gov.uk/prisoner-content-hub-production/resources/rds.tf

As https://github.com/ministryofjustice/cloud-platform-environments/pull/11995 but for production

🗃️  set database isolation level to READ-COMMITTED for prisoner content hub backend for production namespace.

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-estimate-financial-eligibility-for-legal-aid-staging/resources/rds.tf

The CCQ staging environment doesn't need its RDS instance running overnight, so this PR allows it to be switched off to save costs.

CCQ Staging: Switch off RDS at night

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-accommodation-dev/resources/elasticache.tf

The required pipeline skip has been merged https://github.com/ministryofjustice/cloud-platform-environments/pull/12213
We've tested the change locally. Next step is to test this on our dev environment before proceeding to other namespaces.
Following the guidance here for jumping straight to redis 7: https://user-guide.cloud-platform.service.justice.gov.uk/documentation/deploying-an-app/redis/upgrade.html#upgrading-a-redis-version

CAS dev upgraded to Redis 7
