ministryofjustice/cloud-platform-environments

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-complexity-of-need-preprod/certificate.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-complexity-of-need-preprod/resources/rds.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-complexity-of-need-preprod/resources/serviceaccount-circleci.tf

This PR adds resources by the Complexity of Need microservice in the preprod environment:
- PostgreSQL RDS database
- Service Account for CircleCI deployments
- Certificate for custom hostname

Setup resources for Complexity of Need preprod environment

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-domain-events-preprod/resources/hmpps-complexity-of-need.tf

This adds the HMPPS Domain Events SNS topic to the Complexity of Need preprod environment.

Add HMPPS Domain Events SNS to Complexity of Need (preprod)

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-domain-events-prod/resources/hmpps-complexity-of-need.tf

This adds the HMPPS Domain Events SNS topic to the Complexity of Need production environment.

Add HMPPS Domain Events SNS to Complexity of Need (production)

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/check-financial-eligibility-staging/05-ingress.yaml

This bolsters security against unwanted attacks

Add modsecurity to ingress on check financial eligibility - Staging

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/check-financial-eligibility-production/05-ingress.yaml

This acts as a firewall to prevent malicious attacks

Add modsecurity to ingress on check financial eligibility - Production environment

---

.checksum
namespaces/live-1.cloud-platform.service.justice.gov.uk/legal-framework-api-production/00-namespace.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/legal-framework-api-production/01-rbac.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/legal-framework-api-production/02-limitrange.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/legal-framework-api-production/03-resourcequota.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/legal-framework-api-production/04-networkpolicy.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/legal-framework-api-production/resources/main.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/legal-framework-api-production/resources/variables.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/legal-framework-api-production/resources/versions.tf

Create the production environment for legal-framework-api

create the production environment

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-platform-test-dev/resources/aurora.tf

Update replica_count to 0 so the module doesnot create rds instance for serverless

Update replica_count to 0 and add scaling_configuration. Needed for serverless aurora

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/legal-framework-api-staging/resources/rds.tf

create RDS for legal framework staging

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/manage-intelligence-dev/resources/rds-aurora.tf

There should be no changes to the db, this is a minor bump of the module.

Bump the minor version of aurora module

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/legal-framework-api-staging/resources/rds.tf

This change should have no impact on the RDS instance.

Bump minor version of RDS module

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-cla-frontend-staging/resources/ecr.tf

And rename some variables for the existing one for clarity

Add ecr repo for laa-cla-frontend socket server

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/offender-events-preprod/resources/hmpps-tier-offender-events-sub-queue.tf

To be merged once writeback testing in preproduciton has been completed

re-subscribe queue from SNS for writeback testing

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-cla-frontend-staging/resources/route53.tf

- Create route53 resource and add an 'A' record that points to app hosted on template deploy.

LAA CLA Frontend - Create route53 zone

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-interventions-preprod/05-serviceaccount-circleci.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-interventions-preprod/resources/analytical-platform-access.tf

- Adds the recent analytical platform S3 bucket access provision
- Adds jobs and cronjobs permission for CircleCI
Applies changes in #4604, #4607, #4617 to the preprod environment

IC-1505: Bring interventions preprod env in sync with dev

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-interventions-prod/05-serviceaccount-circleci.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-interventions-prod/resources/analytical-platform-access.tf

- Adds the recent analytical platform S3 bucket access provision
- Adds jobs and cronjobs permission for CircleCI
Applies changes in #4604, #4607, #4617 to the research environment

IC-1505: Bring interventions prod env in sync with dev

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-interventions-research/resources/analytical-platform-access.tf

- Adds the recent analytical platform S3 bucket access provision
Applies changes in #4604, #4607 to the research environment (#4617 was already done here by #4518)

IC-1505: Bring interventions research env in sync with dev

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-hmrc-interface-uat/resources/ecr.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-hmrc-interface-uat/resources/rds.tf

Add resources to laa-hmrc-interface-uat

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/offender-events-prod/resources/hmpps-tier-offender-events-sub-queue.tf

Only to be merged once testing is complete

TESTING: resubscribe queue after completion of testing

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-hmrc-interface-uat/resources/serviceaccount-circleci.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-hmrc-interface-uat/resources/serviceaccount.tf

Rename it, for clarity, and extend the permissions

Update the serviceaccount for laa-hmrc-interface-uat

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-cla-frontend-uat/00-namespace.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-cla-frontend-uat/01-rbac.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-cla-frontend-uat/02-limitrange.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-cla-frontend-uat/03-resourcequota.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-cla-frontend-uat/04-networkpolicy.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-cla-frontend-uat/05-serviceaccount-circleci.yaml

- Create UAT namespace for laa-cla-frontend
- Copied folders from laa-cla-frontend-staging directory except from resources
- Changed files accordingly

LAA CLA FRONTEND - Create UAT namespace

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-cla-frontend-training/00-namespace.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-cla-frontend-training/01-rbac.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-cla-frontend-training/02-limitrange.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-cla-frontend-training/03-resourcequota.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-cla-frontend-training/04-networkpolicy.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-cla-frontend-training/05-serviceaccount-circleci.yaml

- Create training namespace laa-cla-frontend
- Copied folders from laa-cla-frontend-staging directory except from resources. 
- Changed files accordingly

LAA CLA FRONTEND - Create training namespace

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-cla-frontend-production/00-namespace.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-cla-frontend-production/01-rbac.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-cla-frontend-production/02-limitrange.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-cla-frontend-production/03-resourcequota.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-cla-frontend-production/04-networkpolicy.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-cla-frontend-production/05-serviceaccount-circleci.yaml

- Create production namespace laa-cla-frontend
- Copied folders from laa-cla-frontend-staging directory except from resources
- Changed files accordingly

LAA CLA FRONTEND - Create production namespace

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-dev/prometheus-custom-alerts-ccic-dev.yaml

This pull request updates the timeframe for Prometheus custom alert in dev.

Adjust time for dev

---

makefile

change to mount main folder with Auth0 creds, kops and config needs to do terraform operations

Change the tools-shell launch config

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-hmrc-interface-uat/resources/serviceaccount-circleci.tf

Add pod/exec permissions to allow removal of UAT databases from RDS

Update laa-hmrc-interface-uat circle ci service account

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-dev/04-networkpolicy.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-dev/prometheus-custom-alerts-ccic-dev.yaml

Adds network policy to allow Prometheus scrape
Updates alert text

Claim criminal injuries dev add cleardown prometheus alert

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-prod/04-networkpolicy.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-prod/prometheus-custom-alerts-ccic-prod.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-prod/resources/main.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-prod/resources/pushgateway.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-prod/resources/variable.tf

Add pushgateway to claim-criminal-injuries-compensation-prod
Add custom alert for data retention
Add network policy to allow Prometheus to scrape gateway

Add push gateway and new alert for unexpected data

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-api-sandbox/resources/rds.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-dev/resources/rds.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-production/resources/rds.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-staging/resources/rds.tf

Happy to separate commits to not break multi-namespace check
unless you are happy to ignore for this PR?
Add access keys to k8s cccd-rds secret for CCCD namespaces
Need access to these for manual snapshot creation
and investigation purposes.

Add access keys to k8s cccd-rds secret for CCCD namespaces

---

.checksum
namespaces/live-1.cloud-platform.service.justice.gov.uk/cloud-platform-reference-app/00-namespace.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/cloud-platform-reference-app/01-rbac.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/cloud-platform-reference-app/02-limitrange.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/cloud-platform-reference-app/03-resourcequota.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/cloud-platform-reference-app/04-networkpolicy.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/cloud-platform-reference-app/resources/main.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/cloud-platform-reference-app/resources/variables.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/cloud-platform-reference-app/resources/versions.tf

This reference app will be used to follow the "create circleci config"
user guide article.

Add namespace for reference app deploy

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/cloud-platform-reference-app/resources/ecr.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/cloud-platform-reference-app/resources/serviceaccount.tf

Add ecr repo for reference app

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-court-data-ui-production/http_status_codes_grafana_dashboard.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-court-data-ui-production/kubernetes_pods_dashboard.yaml

Add grafana dashboards to laa-court-data-ui-production namespace

Add grafana dashboards to laa-court-data-ui-production namespace

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/court-probation-prod/resources/rds.tf

📈 Enable performance insights for court-case-service prod DB

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-court-data-ui-dev/prometheus.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-court-data-ui-production/prometheus.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-court-data-ui-staging/prometheus.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-court-data-ui-uat/prometheus.yaml

Add Prometheus alerts to laa-court-data-ui namespaces

Move Prometheus alerts to cloud platform repo

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/court-probation-prod/09-prometheus-k8s.yaml

If the court-probation-prod prod database has CPU over 90% for 1m

📈 PIC-1170 alert on high RDS CPU usage

---

bin/namespaces-by-creation-date.rb

As requested in
https://mojdt.slack.com/archives/C514ETYJX/p1620126968116700

Add application name to namespace by creation script

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-dev-lgfs/resources/rds.tf

Remove snapshot identifier from cccd-dev-lgfs RDS

[cccd-dev-lgfs] Remove snapshot identifier

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-dev-lgfs/resources/rds.tf

Remove restored DB and attempt restore of 9.6 on 13.1 instance
Testing

Remove restored DB and attempt restore of 9.6 on 13.1 instance

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-interventions-dev/05-serviceaccount-circleci.yaml

Related to https://github.com/ministryofjustice/hmpps-interventions-service/pull/214

Allow CI to change configmaps for interventions

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-tier-prod/06-prometheus-sqs.yaml

direct alerts for hmpps-tier queues into manage-a-workforce_dev slack channel

MAS-415 move alerting for hmpps-tier into hmpps-tier namespace

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/court-probation-dev/resources/court-case-events-sns-topic.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/court-probation-dev/resources/court-case-matcher-queue.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/court-probation-dev/resources/main.tf

A  new SQS queue court-case-matcher-queue, with DLQ. A new SNS topic with the queue subscribed to that topic. Creds and secrets for each

✨ PIC-1346 add SNS topic and queue to subscribe to that topic

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/abundant-namespace-dev/resources/aurora.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-dev-lgfs/resources/rds.tf

Update cccd-dev-lgfs rds to the latest version

Update cccd-dev-lgfs rds to the latest version

---

namespaces/live.cloud-platform.service.justice.gov.uk/vijay-namespace-dev/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/vijay-namespace-dev/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/vijay-namespace-dev/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/vijay-namespace-dev/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/vijay-namespace-dev/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/vijay-namespace-dev/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/vijay-namespace-dev/resources/pushgateway.tf
namespaces/live.cloud-platform.service.justice.gov.uk/vijay-namespace-dev/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/vijay-namespace-dev/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/vijay-namespace-dev/resources/versions.tf

This is to test modules in EKS-live cluster

Add dev namespace in eks-live cluster

---

namespaces/live.cloud-platform.service.justice.gov.uk/vijay-namespace-dev/resources/serviceaccount.tf

This is in the serviceaccount module

Remove github repo list from vijay-namespace-dev

---

namespaces/live.cloud-platform.service.justice.gov.uk/vijay-namespace-dev/resources/serviceaccount.tf

Remove github_repositories to fix the failing pipeline

Remove github_repositories to fix the failing pipeline

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/andrewtulloch-dev/resources/ecr.tf

...working through the hello world example

create ECR for dev/test sandbox

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/justicedata-staging/resources/ecr.tf

Created ECR for justicedata staging

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-domain-events-dev/resources/prison-offender-events.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-domain-events-dev/resources/prison-to-probation-update.tf

prison-to-probation-update can subscribe to those events

prison-offender-events can now push events to HMPPS domain topic

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/court-probation-dev/resources/crime_portal_gateway_s3_bucket.tf

Would like to expire objects in the dev namespace S3 bucket after a couple of days. To test before using larger value of 1 month in prod

✨ PIC-1319 test file expiration in dev s3 bucket

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/abundant-namespace-dev/resources/dynamo_db.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/cloud-platform-reports-dev/resources/dynamodb.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-submit-information-report-dev/resources/dynamodb.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/operations-engineering/resources/dynamodb.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/operations-engineering/resources/state-lock-table.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/prison-to-probation-update-dev/resources/dynamodb.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/prison-to-probation-update-preprod/resources/dynamodb.tf
namespaces/live.cloud-platform.service.justice.gov.uk/vijay-namespace-dev/resources/dynamo_db.tf

This module got a change to use upstream module for dynamodb-autoscaler:
cloudposse/terraform-aws-dynamodb-autoscaler

Update cloud-platform dynamodb to latest version

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-submit-information-report-dev/resources/main.tf

As it is looking for resources in ireland

Update the default region to "eu-west-2"

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/cloud-platform-reports-prod/resources/dynamodb.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/prison-to-probation-update-prod/resources/dynamodb.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/prison-to-probation-update-prod/resources/versions.tf

This module got change to use upstream module for dynamodb-autoscaler:
cloudposse/terraform-aws-dynamodb-autoscaler

Update prod ns dynamodb to latest version

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/abundant-namespace-dev/resources/aurora.tf
namespaces/live.cloud-platform.service.justice.gov.uk/vijay-namespace-dev/resources/aurora.tf

test aurora creation

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/abundant-namespace-dev/resources/aurora.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/manage-intelligence-dev/resources/rds-aurora.tf
namespaces/live.cloud-platform.service.justice.gov.uk/vijay-namespace-dev/resources/aurora.tf

latest-version-rds-aurora ref 1.6

latest-version-rds-aurora

---

namespaces/live.cloud-platform.service.justice.gov.uk/vijay-namespace-dev/resources/sns.tf

Why:
[Test users terraform modules with EKS cluster - sns-topic#2894](https://app.zenhub.com/workspaces/cloud-platform-team-5ccb0b8a81f66118c983c189/issues/ministryofjustice/cloud-platform/2894)

test sns creation

---

namespaces/live.cloud-platform.service.justice.gov.uk/vijay-namespace-dev/resources/sqs.tf

Why:
[Test users terraform modules with EKS cluster - sqs#2895](https://app.zenhub.com/workspaces/cloud-platform-team-5ccb0b8a81f66118c983c189/issues/ministryofjustice/cloud-platform/2895)

test sqs creation

---

namespaces/live.cloud-platform.service.justice.gov.uk/vijay-namespace-dev/resources/amq.tf

Why [Test users terraform modules with EKS cluster - amq-broker#2892](https://app.zenhub.com/workspaces/cloud-platform-team-5ccb0b8a81f66118c983c189/issues/ministryofjustice/cloud-platform/2892)

test amq broker creation

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/check-my-diary-dev/05-serviceaccount-circleci.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/check-my-diary-preprod/05-serviceaccount-circleci.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/check-my-diary-prod/05-serviceaccount-circleci.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-manage-supervisions-dev/05-serviceaccount-circleci.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/manage-hmpps-auth-accounts-dev/05-serviceaccount-circleci.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/manage-hmpps-auth-accounts-preprod/05-serviceaccount-circleci.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/manage-hmpps-auth-accounts-prod/05-serviceaccount-circleci.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/manage-key-workers-dev/05-serviceaccount-circleci.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/manage-key-workers-preprod/05-serviceaccount-circleci.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/manage-key-workers-prod/05-serviceaccount-circleci.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/probation-case-sampler-dev/05-serviceaccount-circleci.yaml

- check-my-diary-dev - update circleci service account, allow prometheusrules
- check-my-diary-preprod - update circleci service account, allow prometheusrules
- check-my-diary-prod - update circleci service account, allow prometheusrules
- hmpps-manage-supervisions-dev - update circleci service account, allow prometheusrules
- manage-hmpps-auth-accounts-dev - update circleci service account, allow prometheusrules
- manage-hmpps-auth-accounts-preprod - update circleci service account, allow prometheusrules
- manage-hmpps-auth-accounts-prod - update circleci service account, allow prometheusrules
- manage-key-workers-dev - update circleci service account, allow prometheusrules
- manage-key-workers-preprod - update circleci service account, allow prometheusrules
- manage-key-workers-prod - …

probation case sampler dev fix service account perms

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-interventions-prod/resources/route53.tf

I mixed up things in my head, the domain in the certificate definition
is the correct one

Use proper intervention domain in Route53 zone

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/sandbox-ppse/resources/sql-server.tf

This is for us to see how SQL Server replication works as we may need to
do this with an off-site database...

Configure a MS SQL Server instance

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/sandbox-ppse/resources/sql-server.tf

Hopefully this might fix the apply...

Switch the rds_family to sqlserver-ee

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/abundant-namespace-dev/resources/rds.tf

Enable stop and start of DB instances
This is related to user request
https://github.com/ministryofjustice/cloud-platform/issues/2923

Test RDS module change

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/justicedata-staging/resources/ecr.tf

Added repo name for github action

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/digital-prison-services-prod/resources/route53-hmpps.tf

Revert "DT-2101 Add TXT record required to claim domain on Maven Central"

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-interventions-prod/10-alerts.yaml

Related: https://github.com/ministryofjustice/cloud-platform/issues/2941

Add initial alerts to interventions production

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/poornima-dev/resources/es.tf
namespaces/live.cloud-platform.service.justice.gov.uk/vijay-namespace-dev/resources/es.tf

This is to test existing module and also create a new one using eks(irsa) updated module

Add existing es module to live-1 cluster, and new module to live cluster

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-interventions-prod/10-alerts.yaml

To route it to the Slack alert created today

Amend interventions prod alert severity

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-interventions-research/10-alerts.yaml

They're essentially a copy of  #4913 but routed differently on the research environment

Add interventions research alerts

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/justicedata-prod/certificate.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/justicedata-prod/resources/route53.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/justicedata-prod/resources/serviceaccount.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/justicedata-prod/resources/variables.tf

Justicedata - added route and cert resource

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-assess-risks-and-needs-dev/resources/rds.tf

- Services now use the new secret, this PR is to remove the old one

Remove old RDS secret in HMPPS Assess Risks and Needs (DEV)

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-hmrc-interface-uat/resources/elasticache.tf

This will be used for caching and temp storage of key-values pairs

Add elasticache to laa-hmrc-interface-uat

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/justicedata-prod/resources/route53.tf

Justicedata - removed the duplicate NS

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-hmrc-interface-uat/resources/elasticache.tf

Add a combined redis_url similar to the instructions in the rds
terraform template

Update laa-hmrc-interface-uat Redis secrets

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/abundant-namespace-dev/resources/elasticsearch.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/manage-intelligence-dev/resources/elasticsearch.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/peoplefinder-demo/resources/elasticsearch.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/peoplefinder-development/resources/elasticsearch.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/peoplefinder-production/resources/elasticsearch.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/peoplefinder-staging/resources/elasticsearch.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/prisoner-content-hub-development/resources/elasticsearch.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/prisoner-content-hub-production/resources/elasticsearch.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/prisoner-content-hub-staging/resources/elasticsearch.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/prisoner-offender-search-dev/resources/es.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/prisoner-offender-search-preprod/resources/es.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/prisoner-offender-search-prod/resources/es.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/probation-offender-search-dev/resources/es.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/probation-offender-search-preprod/resources/es.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/probation-offender-search-prod/resources/es.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/probation-offender-search-staging/resources/es.tf
namespaces/live.cloud-platform.service.justice.gov.uk/vijay-namespace-dev/resources/es.tf

This version has the changes to enable to use of this module for EKS using IRSA

Update ES module to use latest version

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/offender-events-preprod/resources/prison_to_nhs_update-sub-queue.tf

Reverts ministryofjustice/cloud-platform-environments#4090

Revert "Removing sqs used by decommissioned app"

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/offender-events-dev/resources/prison_to_nhs_update-sub-queue.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/offender-events-preprod/resources/prison_to_nhs_update-sub-queue.tf

Bump offendersevents non-prod sqs module to 4.2 latest

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-cla-frontend-production/resources/s3.tf

Also reorders the origins for consistency with staging namespace

Add scheme to cla-frontend-production cors

---

lib/cp_env/terraform.rb
spec/terraform_spec.rb

This will enable live cluster tf_init to use live-1 state.

Update tf_init function to get cluster_state from pipeline var

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-monitoring/resources/pingdom.tf

The CCRC form is going live on Monday and this addition adds the url to pingdom.

Formbuilder - Added the CCRC form to the pingdom list.

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/track-a-query-metabase/00-namespace.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/track-a-query-metabase/01-rbac.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/track-a-query-metabase/02-limitrange.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/track-a-query-metabase/03-resourcequota.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/track-a-query-metabase/04-networkpolicy.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/track-a-query-metabase/resources/main.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/track-a-query-metabase/resources/rds.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/track-a-query-metabase/resources/variables.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/track-a-query-metabase/resources/versions.tf

We plan to introduce a BI tools for reporting for correspondence tools. thank you!

Add a namespace for Metabase BI tool for Correspondence tool team (track-a-query)

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-cla-frontend-staging/resources/pingdom.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-cla-frontend-staging/resources/versions.tf

Requires https://github.com/ministryofjustice/cloud-platform/issues/2953 to be resolved first

Add pingdom resource for laa-cla-frontend-staging namespace

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-cla-frontend-production/resources/pingdom.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-cla-frontend-production/resources/versions.tf

Requires https://github.com/ministryofjustice/cloud-platform/issues/2953 to be resolved first

Add pingdom resource for laa-cla-frontend-production namespace

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/court-probation-dev/05-serviceaccount-circleci.yaml

Attempt to get circleci monitoring prometheus on court-probation-dev

✨ PIC-1494 adding prometheus monitoring

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/digital-prison-services-preprod/00-namespace.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/digital-prison-services-preprod/01-rbac.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/digital-prison-services-preprod/02-limitrange.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/digital-prison-services-preprod/03-resourcequota.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/digital-prison-services-preprod/04-networkpolicy.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/digital-prison-services-preprod/05-serviceaccount-circleci.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/digital-prison-services-preprod/07-certificates.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/digital-prison-services-preprod/resources/elasticache.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/digital-prison-services-preprod/resources/main.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/digital-prison-services-preprod/resources/variables.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/digital-prison-services-preprod/resources/versions.tf

Reverts ministryofjustice/cloud-platform-environments#5031 as was removed in error

Revert "🔥 PIC-1340: Remove digital-prison-services-preprod namespace and contents"

---

.checksum
namespaces/live-1.cloud-platform.service.justice.gov.uk/cloud-platform-migration/00-namespace.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/cloud-platform-migration/01-rbac.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/cloud-platform-migration/02-limitrange.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/cloud-platform-migration/03-resourcequota.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/cloud-platform-migration/04-networkpolicy.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/cloud-platform-migration/resources/main.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/cloud-platform-migration/resources/variables.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/cloud-platform-migration/resources/versions.tf

This will be one of many namespaces that will test the migration from
live-1 to live.

Add cloud-platform migration namespace

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/cloud-platform-migration/resources/ecr.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/cloud-platform-migration/resources/serviceaccount.tf

ECR and serviceaccount will be required to create a GitHub Action for ci/cd

Add ECR and serviceaccount to cloud-platform-migration namespace

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-cla-backend-training/resources/rds.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-cla-backend-training/resources/s3.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-cla-backend-training/resources/versions.tf

This will fix CORS issue and enable our app to access fonts

LAA-CLA-BACKEND-TRAINING - Add custom training URL

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-cla-backend-staging/resources/rds.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-cla-backend-staging/resources/s3.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-cla-backend-staging/resources/versions.tf

This will fix CORS issue and enable our app to access fonts

LAA-CLA-BACKEND-STAGING - Add custom staging URL

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/davidread-dev/resources/ecr.tf

This is to fix the pipeline, it is failing as "helloworld-ruby-app-davidread" git hub repo is not available

Comment out github_repositories in davidread-dev ns

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-pin-phone-monitor-dev/resources/iam.tf

New IAM user to allow selected call data to be processed by AWS transcribe/translate.

PAT-1832 - adds additional IAM user pin phone monitor service

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-monitoring/resources/pingdom.tf

Adding pingdom check for a new service that is on MoJ Forms

Form Builder Money Claim Queries pingdom

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-workload-dev/resources/s3.tf

WFP-324 create s3 bucket for extract

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-dev/08-prometheus-rule.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-prod/08-prometheus-rule.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-stage/08-prometheus-rule.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-test/08-prometheus-rule.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-uat/08-prometheus-rule.yaml

[LAA Court Data Adaptor] - Scope HTTP 404 alerts to /api/* path

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/davidread-dev/resources/main.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/davidread-dev/resources/variables.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/davidread-dev/resources/versions.tf

This is to add missing information related to github var and provider

Updated davidread-dev ecr module

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/create-and-vary-a-licence-dev/00-namespace.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/create-and-vary-a-licence-dev/01-rbac.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/create-and-vary-a-licence-dev/02-limitrange.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/create-and-vary-a-licence-dev/03-resourcequota.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/create-and-vary-a-licence-dev/04-networkpolicy.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/create-and-vary-a-licence-dev/05-serviceaccount-circleci.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/create-and-vary-a-licence-dev/06-certificate.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/create-and-vary-a-licence-dev/resources/elasticache.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/create-and-vary-a-licence-dev/resources/main.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/create-and-vary-a-licence-dev/resources/variables.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/create-and-vary-a-licence-dev/resources/versions.tf

This is the initial creation of a dev namespace that will contain a service for create and vary a licence + a Redis elasticache.

Creating the DEV namespace for a skeleton service for create and vary a licence

---

.checksum
namespaces/live-1.cloud-platform.service.justice.gov.uk/polygraph-offender-management/00-namespace.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/polygraph-offender-management/01-rbac.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/polygraph-offender-management/02-limitrange.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/polygraph-offender-management/03-resourcequota.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/polygraph-offender-management/04-networkpolicy.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/polygraph-offender-management/resources/main.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/polygraph-offender-management/resources/variables.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/polygraph-offender-management/resources/versions.tf

Setting up the namespace for the Polygraph Offender Management System, I'm hoping I am doing this all right.

Initial Commit Polygraph Offender Management System Namespace

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-prod/09-http_status_codes_grafana_dashboard.yaml

[LAA Court Data Adaptor] - Create Grafana dashboard for HTTP status codes

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/create-and-vary-a-licence-api-dev/00-namespace.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/create-and-vary-a-licence-api-dev/01-rbac.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/create-and-vary-a-licence-api-dev/02-limitrange.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/create-and-vary-a-licence-api-dev/03-resourcequota.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/create-and-vary-a-licence-api-dev/04-networkpolicy.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/create-and-vary-a-licence-api-dev/05-serviceaccount-circleci.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/create-and-vary-a-licence-api-dev/06-certificate.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/create-and-vary-a-licence-api-dev/resources/main.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/create-and-vary-a-licence-api-dev/resources/rds.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/create-and-vary-a-licence-api-dev/resources/variables.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/create-and-vary-a-licence-api-dev/resources/versions.tf

Creates a dev namespace + RDS instance for data.

Create the dev namespace for new API service for create-and-vary-a-licence-api-dev

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-dev/08-prometheus-rule.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-prod/08-prometheus-rule.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-stage/08-prometheus-rule.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-test/08-prometheus-rule.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-uat/08-prometheus-rule.yaml

[LAA Court Data Adaptor] - Add Prometheus alerts for Sidekiq queue

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/track-a-query-production/resources/rds.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/track-a-query-production/resources/variables.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/track-a-query-production/resources/versions.tf

This PR is to create a replication of live db for track-a-query-production

Added replica for track-a-query-production live db

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-monitoring/resources/pingdom.tf

Used to monitor the live form is running.
Tidied up the the spacing as the form name was longer.

Added COP Upfront form URL to the pingdom file

---

namespaces/live.cloud-platform.service.justice.gov.uk/paul-test/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/paul-test/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/paul-test/resources/variables.tf

add-paul-test-service-account

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/cloud-platform-canary-app/resources/pingdom.tf

Reduce the alert notification time so the team is informed quicker

Update alert notification time to 3

---

namespaces/live.cloud-platform.service.justice.gov.uk/paul-test/resources/paul-test-iam-cross-account.tf
namespaces/live.cloud-platform.service.justice.gov.uk/paul-test/resources/variables.tf

Paul test iam cross account

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-interventions-dev/resources/s3.tf

i copy pasted this code from elsewhere in this repo. is this everything that is required to get this up and running?
thanks!

add s3 bucket resource to interventions dev environment

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/calculate-release-dates-api-dev/00-namespace.yaml

add the `-dev` suffix to the namespace

Calculate release dates namespace

---

.checksum
namespaces/live-1.cloud-platform.service.justice.gov.uk/evidencelibrary-test/00-namespace.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/evidencelibrary-test/01-rbac.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/evidencelibrary-test/02-limitrange.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/evidencelibrary-test/03-resourcequota.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/evidencelibrary-test/04-networkpolicy.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/evidencelibrary-test/resources/main.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/evidencelibrary-test/resources/variables.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/evidencelibrary-test/resources/versions.tf

To host a frontend ui and backend api.

Added a new namespace for the evidencelibrary test env

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/money-to-prisoners-test/resources/rds.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/money-to-prisoners-test/resources/versions.tf

Indent values so terraform doesn't complain about style

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-fala-staging/resources/s3.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-fala-staging/resources/variable.tf

- Fix CORS issues when trying to access fonts from S3 on staging

LAA-FALA-STAGING Add staging URL to CORS rules

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-fala-production/resources/s3.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-fala-production/resources/variable.tf

- Fix CORS issues when trying to access fonts from S3 on prod

LAA-FALA-PRODUCTION Add production URL to CORS rules

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-fala-staging/resources/s3.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-fala-staging/resources/variable.tf

- Follow up for this PR https://github.com/ministryofjustice/cloud-platform-environments/pull/5184/files
- The above PR did not trigger concourse due to failed yaml test on github
- This commit is to make concourse apply the changes for the above PR by making changes to the relevant files

LAA-FALA STAGING - (Retry) Add staging URL to CORS rules

---

namespaces/live.cloud-platform.service.justice.gov.uk/poornima-dev/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/poornima-dev/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/poornima-dev/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/poornima-dev/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/poornima-dev/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/poornima-dev/certificate.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/poornima-dev/resources/ecr.tf
namespaces/live.cloud-platform.service.justice.gov.uk/poornima-dev/resources/gh-serviceaccount-live.tf
namespaces/live.cloud-platform.service.justice.gov.uk/poornima-dev/resources/gh-serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/poornima-dev/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/poornima-dev/resources/route53.tf
namespaces/live.cloud-platform.service.justice.gov.uk/poornima-dev/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/poornima-dev/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/poornima-dev/serviceaccount-gh-action.yaml

to test the app migration and route53 traffic policy

Copy poornima-dev namespace to live cluster

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-hmrc-interface-uat/resources/serviceaccount-circleci.tf

I am trying to use the `wait` command for pods to start/delete
and it has been implied that this permission will help with that

Update the CircleCI service account

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-reference-data-prod/00-namespace.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-reference-data-prod/01-rbac.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-reference-data-prod/02-limitrange.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-reference-data-prod/03-resourcequota.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-reference-data-prod/04-networkpolicy.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-reference-data-prod/resources/main.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-reference-data-prod/resources/serviceaccount-github.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-reference-data-prod/resources/variables.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-reference-data-prod/resources/versions.tf

Linked to https://github.com/ministryofjustice/hmpps-reference-data

Add reference data namespace

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/ppud-replacement-preprod/resources/rds.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/ppud-replacement-preprod/resources/s3.tf

Enable "native" SQL Server backup/restore from an S3 bucket

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-pin-phone-monitor-dev/resources/rds-aurora.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-pin-phone-monitor-dev/resources/rds.tf

Comment out aurora instance in preparation for migration from snapshot.

PAT-1981 - Update postgres RDS db instance to v12

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-decide-prototype/00-namespace.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-decide-prototype/01-rbac.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-decide-prototype/02-limitrange.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-decide-prototype/03-resourcequota.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-decide-prototype/04-networkpolicy.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-decide-prototype/resources/basic-auth.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-decide-prototype/resources/ecr.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-decide-prototype/resources/github-repo.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-decide-prototype/resources/main.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-decide-prototype/resources/serviceaccount.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-decide-prototype/resources/variables.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-decide-prototype/resources/versions.tf

This is currently hosted in Heroku; we're moving it to cloud platform for improved reliability and security.

Create namespace for LAA Decide prototype

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/education-skills-work-employment-dev/resources/rds-aurora.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/education-skills-work-employment-preprod/resources/rds-aurora.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/education-skills-work-employment-prod/resources/rds-aurora.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/manage-intelligence-dev/resources/rds-aurora.tf
namespaces/live.cloud-platform.service.justice.gov.uk/abundant-namespace-dev/resources/aurora.tf

This is to maintain all modules to use the latest version

Update rds-aurora to use the latest module version.

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-monitoring/resources/pingdom.tf

New form that requires a pingdom check

Form Builder - MoJ User Research Consent pingdom

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-uat/resources/messaging-queues.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-uat/resources/rds.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-uat/resources/versions.tf

Create a dedicated SQS queue for posting prosecution concluded messages to MAAT API.

[LAA Court Data Adaptor] Add prosecution_concluded queue (uat)

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/track-a-move-dev/resources/book-a-secure-move-api-iam.tf

We were too strict with permissions and athena-cli can't grab any data now

Add permissions to BaSM Athena dev

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-test/resources/messaging-queues.tf

```
Error: Error putting IAM user policy crime-apps-test-prosecution-concluded-queue: LimitExceeded: Maximum policy size of 2048 bytes exceeded for user cp-sqs-02f5ffc4ea89
```

[LAA Court Data Adaptor] Remove unused SQS queues (test)

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-dev/resources/messaging-queues.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-dev/resources/variables.tf

[User Story with more info why we are making this change](https://dsdmoj.atlassian.net/browse/LASB-640)

CDA - Updating the SQS visibility timeout to reduce the message duplication

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-interventions-preprod/resources/s3.tf

the code here is copy pasted from dev s3 definition

add s3 bucket resource to interventions preprod environment

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-interventions-research/resources/s3.tf

the code here is copy pasted from dev s3 definition

 add s3 bucket resource to interventions research environment

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-interventions-prod/resources/s3.tf

the code here is copy pasted from dev s3 definition

 add s3 bucket resource to interventions prod environment

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-workload-dev/resources/s3-extract.tf

We need the notifications working to support development

WFP-471 disable encryption as it breaks notifications

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/pathfinder-dev/resources/athena-iam.tf

...on query output bucket
see:
https://aws.amazon.com/premiumsupport/knowledge-center/athena-output-bucket-error/

PAT-2045 - Fix error when querying data due to s3 permission 

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/workforce-management/00-namespace.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/workforce-management/01-rbac.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/workforce-management/02-limitrange.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/workforce-management/03-resourcequota.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/workforce-management/04-networkpolicy.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/workforce-management/resources/basic-auth.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/workforce-management/resources/ecr.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/workforce-management/resources/github-repo.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/workforce-management/resources/main.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/workforce-management/resources/serviceaccount.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/workforce-management/resources/variables.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/workforce-management/resources/versions.tf

Following this guide: https://user-guide.cloud-platform.service.justice.gov.uk/documentation/getting-started/prototype-kit.html#3-raise-a-pr
as part of: https://dsdmoj.atlassian.net/wiki/spaces/DES/pages/3533799489/Create+a+GOV.UK+Prototype+Kit+on+MoJ+Cloud+Platform+Pilot
Feedback on process welcomed!

Workforce management

---

lib/cp_env/terraform.rb
namespaces/live-1.cloud-platform.service.justice.gov.uk/jason-demo/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/cloud-platform-migration/resources/serviceaccount.tf
spec/terraform_spec.rb

used by https://github.com/ministryofjustice/cloud-platform-terraform-serviceaccount/blob/main/variables.tf#L1

export cluster API address

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/poornima-demo/00-namespace.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/poornima-demo/01-rbac.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/poornima-demo/02-limitrange.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/poornima-demo/03-resourcequota.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/poornima-demo/04-networkpolicy.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/poornima-demo/resources/ecr.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/poornima-demo/resources/main.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/poornima-demo/resources/serviceaccount.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/poornima-demo/resources/variables.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/poornima-demo/resources/versions.tf

Related to: https://github.com/ministryofjustice/cloud-platform/issues/3138

Demo namepsace poornima-demo to test migration plan

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-hmrc-interface-staging/00-namespace.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-hmrc-interface-staging/01-rbac.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-hmrc-interface-staging/02-limitrange.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-hmrc-interface-staging/03-resourcequota.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-hmrc-interface-staging/04-networkpolicy.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-hmrc-interface-staging/resources/elasticache.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-hmrc-interface-staging/resources/main.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-hmrc-interface-staging/resources/rds.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-hmrc-interface-staging/resources/serviceaccount-circleci.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-hmrc-interface-staging/resources/variables.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-hmrc-interface-staging/resources/versions.tf

Duplicates UAT, but removes ECR and changes namespace to x-staging

Create LAA-HMRC-Interface staging environment

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/poornima-staging/resources/s3-messaging.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/poornima-staging/resources/variables.tf

Related to: https://github.com/ministryofjustice/cloud-platform/issues/3020

Create resources s3, sns and sqs. This is to test the sns encryption

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/poornima-staging/resources/s3-messaging.tf

This is to test the branch add-test which has the encryption changes to the module

Enable encryption for sns

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/poornima-staging/resources/s3-sqs.tf

Related to: https://github.com/ministryofjustice/cloud-platform/issues/3128

Add s3 bucket and sqs queue to test issue 3128

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/court-probation-dev/resources/court-case-events-sns-topic.tf

Encrypt SNS topic in dev namespace

✨ PIC-1518 encrypt SNS test

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-dev-lgfs/resources/messaging.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-dev/resources/messaging.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-staging/resources/messaging.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/court-probation-dev/resources/court-case-events-sns-topic.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/court-probation-preprod/resources/court-case-events-sns-topic.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-domain-events-dev/resources/hmpps-domain-events-topic.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-domain-events-preprod/resources/hmpps-domain-events-topic.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/offender-events-dev/resources/topic.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/offender-events-preprod/resources/topic-perf.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/offender-events-preprod/resources/topic.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/offender-events-staging/resources/topic.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/poornima-staging/resources/s3-messaging.tf
namespaces/live.cloud-platform.service.justice.gov.uk/abundant-namespace-dev/resources/sns.tf

More details of release: https://github.com/ministryofjustice/cloud-platform-terraform-sns-topic/releases/tag/4.3

Upgrade sns-topic to 4.3 release on all non-prod namespaces

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-production/resources/messaging.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/court-probation-prod/resources/court-case-events-sns-topic.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-domain-events-prod/resources/hmpps-domain-events-topic.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/offender-events-prod/resources/topic.tf

More details of release: https://github.com/ministryofjustice/cloud-platform-terraform-sns-topic/releases/tag/4.3

Upgrade sns-topic to 4.3 release on all prod namespaces

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-production/resources/messaging.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/court-probation-prod/resources/court-case-events-sns-topic.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-domain-events-prod/resources/hmpps-domain-events-topic.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/offender-events-prod/resources/topic.tf

Reverts ministryofjustice/cloud-platform-environments#5410
The namespaces have issues and getting 500. so reverting

Revert "Upgrade sns-topic to 4.3 release on all prod namespaces"

---

namespaces/live.cloud-platform.service.justice.gov.uk/poornima-dev/resources/gh-serviceaccount.tf

This is to test if that changes any of the existing github secrets

Add new serviceaccount

---

namespaces/live.cloud-platform.service.justice.gov.uk/poornima-dev/resources/gh-serviceaccount.tf

This is to fix the error - Duplicate Sa name

Pass new serviceaccount name

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-dev/resources/messaging-queues.tf

Restore queue deleted in https://github.com/ministryofjustice/cloud-platform-environments/pull/5304.

[LAA Court Data Adaptor] Restore laa_status_update queue (dev)

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-ems-prod/resources/rds.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-ems-prod/resources/route53.tf

Delegating zones to EMS tagging accounts

HMPPS EMS Tagging Zone Delegation

---

namespaces/live.cloud-platform.service.justice.gov.uk/poornima-demo/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/poornima-demo/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/poornima-demo/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/poornima-demo/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/poornima-demo/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/poornima-demo/resources/ecr.tf
namespaces/live.cloud-platform.service.justice.gov.uk/poornima-demo/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/poornima-demo/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/poornima-demo/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/poornima-demo/resources/versions.tf

This is to see how the github-actions secrets are updated when moving serviceaccount

Migrate poornima-demo to live cluster

---

.checksum
namespaces/live-1.cloud-platform.service.justice.gov.uk/justicedata-test/00-namespace.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/justicedata-test/01-rbac.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/justicedata-test/02-limitrange.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/justicedata-test/03-resourcequota.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/justicedata-test/04-networkpolicy.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/justicedata-test/resources/main.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/justicedata-test/resources/serviceaccount.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/justicedata-test/resources/variables.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/justicedata-test/resources/versions.tf

added namespace and service account

Added new Justicedata test namespace

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/ppud-replacement-dev/resources/s3.tf

This bucket (and created user) is intended for the legacy PPUD system
(run by Lumen) to be able to push updated (on the PPUD side) documents
into the cloud platform for the `ppud-replacement` team applications to
consume in the new applications designed to replace PPUD.
ref PUD-499

Create an S3 bucket and user for PPUD document transfers

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/ppud-replacement-dev/resources/s3.tf

This will stop concourse getting errors when inspecting the resources.
ref https://mojdt.slack.com/archives/C57UPMZLY/p1630943068084700?thread_ts=1630927342.075000&cid=C57UPMZLY

Update the path of the IAM user.

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/ppud-replacement-dev/resources/s3.tf

ref https://mojdt.slack.com/archives/C57UPMZLY/p1631014126105200?thread_ts=1630927342.075000&cid=C57UPMZLY

Update the Lumen S3 user path

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-fee-calculator-staging/resources/pingdom.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-fee-calculator-staging/resources/versions.tf

Move pingdom alerts from #laa-get-paid-alerts
to #laa-fee-calculator-alerts

[laa-fee-calculator-staging] Change pingdom alerting channel

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-fee-calculator-production/resources/pingdom.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-fee-calculator-production/resources/versions.tf

Move pingdom alerts from #laa-get-paid-alerts
to #laa-fee-calculator-alerts

[laa-fee-calculator-production] Change pingdom alerting channel

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/sm-dev/resources/serviceaccount.tf

Add circleci sa to sm-dev NS

---

namespaces/live.cloud-platform.service.justice.gov.uk/sm-dev/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/sm-dev/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/sm-dev/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/sm-dev/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/sm-dev/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/sm-dev/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/sm-dev/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/sm-dev/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/sm-dev/resources/versions.tf

Create sm-dev NS on live cluster

Create sm-dev NS on live cluster

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/cloud-platform-reference-app-github-action/00-namespace.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/cloud-platform-reference-app-github-action/01-rbac.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/cloud-platform-reference-app-github-action/02-limitrange.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/cloud-platform-reference-app-github-action/03-resourcequota.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/cloud-platform-reference-app-github-action/04-networkpolicy.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/cloud-platform-reference-app-github-action/resources/ecr.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/cloud-platform-reference-app-github-action/resources/main.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/cloud-platform-reference-app-github-action/resources/serviceaccount.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/cloud-platform-reference-app-github-action/resources/variables.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/cloud-platform-reference-app-github-action/resources/versions.tf

This is related to:
https://github.com/ministryofjustice/cloud-platform/issues/3167

Create new ns to test cd using Github Actions

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-audit-poc-api-prod/resources/pingdom.tf

This reverts commit f3110625e65b09785b058de2cbfa1edd1a68fbb3.

Revert "DT-2502 remove pingdom object"

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/maintenance-pages/00-namespace.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/maintenance-pages/01-rbac.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/maintenance-pages/resources/variables.tf

Operations Engineering is taking over ownership of the Maintenance pages app, this updates the namespace contacts and variables.

Update ownership to Operations Engineering team

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/raz-test-one/resources/rds.tf

For https://github.com/ministryofjustice/cloud-platform/issues/3188

DMS test databases

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/manage-intelligence-dev/resources/elasticsearch.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/peoplefinder-demo/resources/elasticsearch.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/peoplefinder-development/resources/elasticsearch.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/peoplefinder-production/resources/elasticsearch.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/peoplefinder-staging/resources/elasticsearch.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/prisoner-content-hub-development/resources/elasticsearch.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/prisoner-content-hub-production/resources/elasticsearch.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/prisoner-content-hub-staging/resources/elasticsearch.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/prisoner-offender-search-dev/resources/es.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/prisoner-offender-search-preprod/resources/es.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/prisoner-offender-search-prod/resources/es.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/probation-offender-search-dev/resources/es.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/probation-offender-search-preprod/resources/es.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/probation-offender-search-prod/resources/es.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/probation-offender-search-staging/resources/es.tf

This module is for live-eks to use Use "aws_eks_cluster", replacing data "terraform_remote_state"

Update es to use the latest module

---

namespaces/live.cloud-platform.service.justice.gov.uk/cloud-platform-reference-app-github-action/resources/serviceaccount.tf

This is for namespace cloud-platform-reference-app-github-action

Remove skip and use new var for live service account

---

namespaces/live.cloud-platform.service.justice.gov.uk/cloud-platform-reference-app-github-action/resources/serviceaccount.tf

This is for namespace cloud-platform-reference-app-github-action

Remove seperate vars for serviceaccount module

---

.checksum
namespaces/live-1.cloud-platform.service.justice.gov.uk/poornima-staging/00-namespace.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/poornima-staging/01-rbac.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/poornima-staging/02-limitrange.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/poornima-staging/03-resourcequota.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/poornima-staging/04-networkpolicy.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/poornima-staging/resources/main.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/poornima-staging/resources/serviceaccount.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/poornima-staging/resources/variables.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/poornima-staging/resources/versions.tf

This also removes the terraform resources which was not removed properly when this namespace was destroyed before

Add poornima-staging for testing

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/poornima-staging/resources/serviceaccount.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/poornima-staging/resources/variables.tf

Test serviceaccount branch to get the kubernetes_cluster from pipeleine in live-1

Test serviceaccount branch to get the kubernetes_cluster from pipeline

---

namespaces/live.cloud-platform.service.justice.gov.uk/manage-my-prison-dev/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/manage-my-prison-dev/05-service-accounts.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/manage-my-prison-dev/06-certificate.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/manage-my-prison-dev/resources/ecr.tf
namespaces/live.cloud-platform.service.justice.gov.uk/manage-my-prison-dev/resources/elasticache.tf
namespaces/live.cloud-platform.service.justice.gov.uk/manage-my-prison-dev/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/manage-my-prison-dev/resources/versions.tf

… so that DPS bootstrap can be used

Give `manage-my-prison-dev` namespace necessary config

---

namespaces/live.cloud-platform.service.justice.gov.uk/abundant-namespace-dev/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/abundant-namespace-dev/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/cloud-platform-migration/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/cloud-platform-migration/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/cloud-platform-reference-app-github-action/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/cloud-platform-reference-app-github-action/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/cloud-platform-reference-app/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/cloud-platform-reference-app/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/cloud-platform-reports-prod/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/cloud-platform-reports-prod/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/paul-test/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/paul-test/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/poornima-demo/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/poornima-dev/resources/gh-serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/poornima-dev/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/sm-dev/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/sm-dev/resources/variables.tf

More details in Release: https://github.com/ministryofjustice/cloud-platform-terraform-serviceaccount/releases/tag/0.6

Upgrade serviceaccount module to 0.6

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/ppud-replacement-dev/resources/s3.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/ppud-replacement-preprod/resources/s3.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/ppud-replacement-prod/resources/s3.tf

These changes add the pre-prod and prod S3 buckets needed for receiving
data from Lumen.

Setup the S3 buckets ppud-replacement needs

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/court-probation-dev/07-certificate.yaml

🔧 Add pre-sentence-service-dev URL to certificate

PIC-1655 Add pre-sentence-service-dev URL to certificate

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/court-probation-preprod/07-certificate.yaml

🔧 Add pre-sentence-service-preprod URL to certificate

PIC-1655 Add pre-sentence-service-preprod URL to certificate 

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/court-probation-prod/07-certificate.yaml

🔧 Add pre-sentence-service URL to certificate

PIC-1655 Add pre-sentence-service URL to certificate 

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/makerecall-prototype/00-namespace.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/makerecall-prototype/01-rbac.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/makerecall-prototype/02-limitrange.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/makerecall-prototype/03-resourcequota.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/makerecall-prototype/04-networkpolicy.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/makerecall-prototype/resources/basic-auth.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/makerecall-prototype/resources/ecr.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/makerecall-prototype/resources/github-repo.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/makerecall-prototype/resources/main.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/makerecall-prototype/resources/serviceaccount.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/makerecall-prototype/resources/variables.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/makerecall-prototype/resources/versions.tf

Setting up new prototype kit environment

setup Making Recall decisions prototype

---

.checksum
namespaces/live-1.cloud-platform.service.justice.gov.uk/dex-ian-dotnet-test/00-namespace.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/dex-ian-dotnet-test/01-rbac.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/dex-ian-dotnet-test/02-limitrange.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/dex-ian-dotnet-test/03-resourcequota.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/dex-ian-dotnet-test/04-networkpolicy.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/dex-ian-dotnet-test/resources/main.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/dex-ian-dotnet-test/resources/variables.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/dex-ian-dotnet-test/resources/versions.tf

This is a dummy app from a tutorial, intended as a learning exercise and proof of concept for moving .Net applications to the Cloud Platform

Added a new namespace to test out .Net Core on Cloud Platform

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/cloud-platform-reference-app-github-action/resources/serviceaccount.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/cloud-platform-reference-app-github-action/resources/variables.tf

This is for namespace cloud-platform-reference-app-github-action
This is also to test SKIP works for "apply-namespace-changes"

Update serviceaccount to latest version

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-monitoring/resources/pingdom.tf

A new form has gone live in formbuilder and needs monitoring.

Add a new production form to pingdom.

---

.checksum
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-hmrc-interface-production/00-namespace.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-hmrc-interface-production/01-rbac.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-hmrc-interface-production/02-limitrange.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-hmrc-interface-production/03-resourcequota.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-hmrc-interface-production/04-networkpolicy.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-hmrc-interface-production/resources/main.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-hmrc-interface-production/resources/variables.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-hmrc-interface-production/resources/versions.tf

Create a production namespace for laa-hmrc-interface-api

hmrc interface production namespace

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-hmrc-interface-production/resources/s3.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-hmrc-interface-production/resources/serviceaccount.tf

add 7 day lifecycle to S3 and serviceaccount rules

add lifecycle to s3 and rules to service_account

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/cloud-platform-migration/resources/serviceaccount.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/cloud-platform-migration/resources/variables.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/cloud-platform-reference-app/resources/serviceaccount.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/cloud-platform-reference-app/resources/variables.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/jason-demo/resources/serviceaccount.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/jason-demo/resources/variables.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-hmrc-interface-production/resources/rds.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-hmrc-interface-production/resources/serviceaccount.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/makerecall-prototype/resources/serviceaccount.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/makerecall-prototype/resources/variables.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/poornima-demo/resources/serviceaccount.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/poornima-demo/resources/variables.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/sm-dev/resources/serviceaccount.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/sm-dev/resources/variables.tf

This it so keep up to date for all the modules in the env repo

Update all modules to use the latest version

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-hmrc-interface-production/resources/s3.tf

we use slightly different s3 variable names for UAT and staging, our circle ci deployment process is made easier by unifying these

update s3 variable names to match UAT and staging

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-ems-prod/resources/route53.tf

Delegating zones to EMS production tagging account

HMPPS EMS Tagging Production Zone Delegation

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/prisoner-content-hub-development/resources/elasticache.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/prisoner-content-hub-development/resources/variables.tf

Add redis elasticache to prisoner content hub dev

prisoner content hub elasticache (dev)

---

namespaces/live.cloud-platform.service.justice.gov.uk/legal-framework-api-uat/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/legal-framework-api-uat/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/legal-framework-api-uat/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/legal-framework-api-uat/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/legal-framework-api-uat/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/legal-framework-api-uat/resources/ecr.tf
namespaces/live.cloud-platform.service.justice.gov.uk/legal-framework-api-uat/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/legal-framework-api-uat/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/legal-framework-api-uat/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/legal-framework-api-uat/serviceaccount-admin.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/legal-framework-api-uat/serviceaccount-circleci.yaml

Migrate legal-framework-api-uat to new live cluster

start to migrate to live cluster

---

.github/workflows/check-ingress-annotation.yml

Reverts ministryofjustice/cloud-platform-environments#5707

Revert "Update check-ingress-annotation.yml"

---

.github/workflows/iam-role-policy-changes-check.yaml

Related to [Create Github Action to identify PRs that contain IAM Role and Policy changes#3015](https://github.com/ministryofjustice/cloud-platform/issues/3015)

Iam policy check

---

.checksum
namespaces/live.cloud-platform.service.justice.gov.uk/bucket-data-uploader-dev/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/bucket-data-uploader-dev/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/bucket-data-uploader-dev/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/bucket-data-uploader-dev/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/bucket-data-uploader-dev/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/bucket-data-uploader-dev/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/bucket-data-uploader-dev/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/bucket-data-uploader-dev/resources/versions.tf

Create namespace for data engineering s3 upload development

Create namespace for data engineering s3 upload development

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-hmrc-interface-uat/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-hmrc-interface-uat/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-hmrc-interface-uat/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-hmrc-interface-uat/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-hmrc-interface-uat/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-hmrc-interface-uat/resources/ecr.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-hmrc-interface-uat/resources/elasticache.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-hmrc-interface-uat/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-hmrc-interface-uat/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-hmrc-interface-uat/resources/s3.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-hmrc-interface-uat/resources/serviceaccount-circleci.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-hmrc-interface-uat/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-hmrc-interface-uat/resources/versions.tf

Migrate `laa-hmrc-interface-uat` to live

Migrate laa-hmrc-interface-uat to live

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/offender-events-dev/resources/poll-pusher-sub-queue.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/offender-events-dev/resources/prison_to_nhs_update-sub-queue.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/offender-events-dev/resources/prison_to_probation_update-sub-queue.tf

Reverts ministryofjustice/cloud-platform-environments#5974

Revert "DT-2796: 🐛 Temporarily remove cross namespace references during migra…"

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/offender-events-dev/resources/poll-pusher-sub-queue.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/offender-events-dev/resources/prison_to_nhs_update-sub-queue.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/offender-events-dev/resources/prison_to_probation_update-sub-queue.tf

Reverts ministryofjustice/cloud-platform-environments#5983

Revert "Revert "DT-2796: 🐛 Temporarily remove cross namespace references during migra…""

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-means-assessment-dev/resources/ecr.tf

Added ECR to laa-crime-means-assessment-dev namespace

Added ecr to laa-crime-means-assessment-dev namespace

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-interventions-dev/resources/reporting-landing-access.tf

interventions-ndmis-bucket-name

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-interventions-dev/resources/reporting-landing-access.tf

Remove trailing commar which may be causing issues.

remove trailing commar

---

namespaces/live.cloud-platform.service.justice.gov.uk/manage-intelligence-dev/08-certificate.yaml

in the mangage-intelligence namespace

AR-1430 - re-create submit-report certificate 

---

namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-test-dev/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-test-dev/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-test-dev/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-test-dev/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-test-dev/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-test-dev/av-service-account.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-test-dev/circleci-service-account.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-test-dev/pdf-generator-service-account.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-test-dev/resources/json-output-attachments-s3.tf
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-test-dev/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-test-dev/resources/service_token_cache.tf
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-test-dev/resources/submitter.tf
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-test-dev/resources/user-datastore.tf
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-test-dev/resources/user-filestore.tf
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-test-dev/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-test-dev/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-test-dev/service-token-cache-service-account.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-test-dev/submitter-workers-service-account.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-test-dev/user-datastore-service-account.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-test-dev/user-filestore-service-account.yaml

Starting to migrate the formbuilder platform (test-dev first) to the new cluster.

Migrate formbuilder platform test dev to the new cluster

---

namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-test-production/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-test-production/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-test-production/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-test-production/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-test-production/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-test-production/av-service-account.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-test-production/circleci-service-account.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-test-production/pdf-generator-service-account.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-test-production/resources/json-output-attachments-s3.tf
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-test-production/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-test-production/resources/service_token_cache.tf
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-test-production/resources/submitter.tf
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-test-production/resources/user-datastore.tf
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-test-production/resources/user-filestore.tf
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-test-production/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-test-production/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-test-production/service-token-cache-service-account.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-test-production/submitter-workers-service-account.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-test-production/user-datastore-service-account.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-test-production/user-filestore-service-account.yaml

Migrating form builder platform test production to the new cluster. Don't be mistaken by the name of this namespace, is a test environment and not a "production" one. 😓

Migrate formbuilder platform test production to the new cluster

---

namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-saas-test/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-saas-test/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-saas-test/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-saas-test/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-saas-test/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-saas-test/05-circleci-service-account.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-saas-test/06-prometheus.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-saas-test/editor-service-account.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-saas-test/editor-workers-service-account.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-saas-test/metadata-api-service-account.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-saas-test/resources/editor.tf
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-saas-test/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-saas-test/resources/metadata_api.tf
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-saas-test/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-saas-test/resources/versions.tf

Adding the formbuilder-saas-test namespace in the EKS cluter

Form Builder - Create formbuilder-saas-test namespace in EKS

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/ppud-replacement-dev/resources/bandiera.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/ppud-replacement-dev/resources/main.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/ppud-replacement-dev/resources/rds.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/ppud-replacement-dev/resources/versions.tf

This also moves all of the bandiera config into a separate file.

Create a basic-auth secret for the bandiera app

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmcts-complaints-formbuilder-adapter-staging/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmcts-complaints-formbuilder-adapter-staging/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmcts-complaints-formbuilder-adapter-staging/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmcts-complaints-formbuilder-adapter-staging/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmcts-complaints-formbuilder-adapter-staging/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmcts-complaints-formbuilder-adapter-staging/05-service-accounts.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmcts-complaints-formbuilder-adapter-staging/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmcts-complaints-formbuilder-adapter-staging/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmcts-complaints-formbuilder-adapter-staging/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmcts-complaints-formbuilder-adapter-staging/resources/versions.tf

Migrating Formbuilder HMCTS Adapter Staging to new namespace

Migrate Formbuilder HMCTS Adapter Staging to EKS

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/offender-events-preprod/resources/offender_categorisation-sub-queue.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/offender-events-preprod/resources/pathfinder-sub-queue.tf

Temporarily remove event queue secrets

PAT-2103 Migrate pathfinder to live cluster

---

namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-product-page-staging/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-product-page-staging/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-product-page-staging/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-product-page-staging/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-product-page-staging/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-product-page-staging/formbuilder-product-page-staging-service-account.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-product-page-staging/resources/ecr.tf
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-product-page-staging/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-product-page-staging/resources/versions.tf

Add Formbuilder product page staging namespace for EKS

Add Formbuilder product page staging namespace for EKS

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-interventions-research/resources/reporting-landing-access.tf

Similar to #6028 but for the research environment

Expand reporting S3 bucket secret with bucket name

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/disclosure-checker-production/resources/pingdom.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/disclosure-checker-production/resources/rds.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/disclosure-checker-production/resources/route53.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/disclosure-checker-production/resources/variables.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/disclosure-checker-production/resources/versions.tf

Renamed a few variables to be consistent with staging.

Add pingdom check to disclosure-checker-production

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/fj-cait-production/resources/pingdom.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/fj-cait-production/resources/route53.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/fj-cait-production/resources/variables.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/fj-cait-production/resources/versions.tf

Renamed a few variables to be consistent with staging.

Add pingdom check to fj-cait-production

---

namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-monitoring/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-monitoring/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-monitoring/circleci-service-account.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-monitoring/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-monitoring/resources/pingdom.tf
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-monitoring/resources/versions.tf

This creates the monitoring namespace and service account in the new EKS cluster

Form Builder - Migrate monitoring namespace

---

namespaces/live.cloud-platform.service.justice.gov.uk/licences-dev/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/licences-dev/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/licences-dev/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/licences-dev/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/licences-dev/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/licences-dev/05-serviceaccount-circleci.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/licences-dev/07-certificates.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/licences-dev/resources/elasticache.tf
namespaces/live.cloud-platform.service.justice.gov.uk/licences-dev/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/licences-dev/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/licences-dev/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/licences-dev/resources/versions.tf

DCS-1333: migrate licences-dev to live

DCS-1333: migrate licences-dev to live

---

namespaces/live.cloud-platform.service.justice.gov.uk/use-of-force-dev/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/use-of-force-dev/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/use-of-force-dev/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/use-of-force-dev/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/use-of-force-dev/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/use-of-force-dev/05-serviceaccount-circleci.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/use-of-force-dev/07-certificate.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/use-of-force-dev/resources/elasticache.tf
namespaces/live.cloud-platform.service.justice.gov.uk/use-of-force-dev/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/use-of-force-dev/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/use-of-force-dev/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/use-of-force-dev/resources/versions.tf

DCS-1333: migrate use-of-force-dev to live

DCS-1333: migrate use-of-force-dev to live

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-video-link-dev/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-video-link-dev/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-video-link-dev/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-video-link-dev/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-video-link-dev/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-video-link-dev/05-serviceaccount-circleci.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-video-link-dev/06-certificate.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-video-link-dev/resources/elasticache.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-video-link-dev/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-video-link-dev/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-video-link-dev/resources/versions.tf

DCS-1333: migrate hmpps-book-video-link-dev to live

DCS-1333: migrate hmpps-book-video-link-dev to live

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-welcome-to-prison-dev/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-welcome-to-prison-dev/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-welcome-to-prison-dev/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-welcome-to-prison-dev/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-welcome-to-prison-dev/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-welcome-to-prison-dev/05-serviceaccount-circleci.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-welcome-to-prison-dev/06-certificate.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-welcome-to-prison-dev/resources/elasticache.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-welcome-to-prison-dev/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-welcome-to-prison-dev/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-welcome-to-prison-dev/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-welcome-to-prison-dev/resources/versions.tf

DCS-1333: migrate hmpps-welcome-to-prison-dev to live

DCS-1333: migrate hmpps-welcome-to-prison-dev to live

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-means-assessment-dev/05-serviceaccount-circleci.yaml

Added a new role and binding to the existing circleci service account to resolves errors such as 'replicasets.apps is forbidden: User "system:serviceaccount:******************************:circleci" cannot list resource "replicasets" in API group "apps" in the namespace'

Added new role and binding to existing circleci service account

---

.checksum
namespaces/live.cloud-platform.service.justice.gov.uk/dex-alistair-testapp/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/dex-alistair-testapp/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/dex-alistair-testapp/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/dex-alistair-testapp/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/dex-alistair-testapp/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/dex-alistair-testapp/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/dex-alistair-testapp/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/dex-alistair-testapp/resources/versions.tf

init commit

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-means-assessment-dev/05-serviceaccount-circleci.yaml

Fixed api version

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-means-assessment-dev/05-serviceaccount-circleci.yaml

Added replicasets to apps group in role

Added replicasets to apps group

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/manage-recalls-dev/00-namespace.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/manage-recalls-dev/01-rbac.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/manage-recalls-dev/02-limitrange.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/manage-recalls-dev/03-resourcequota.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/manage-recalls-dev/04-networkpolicy.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/manage-recalls-dev/05-serviceaccount-circleci.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/manage-recalls-dev/certificate.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/manage-recalls-dev/resources/elasticache.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/manage-recalls-dev/resources/main.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/manage-recalls-dev/resources/pingdom.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/manage-recalls-dev/resources/rds.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/manage-recalls-dev/resources/s3.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/manage-recalls-dev/resources/variables.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/manage-recalls-dev/resources/versions.tf

Create the `manage-recalls-dev` namespace and resources

---

.checksum
namespaces/live.cloud-platform.service.justice.gov.uk/dex-alistair-helloworld/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/dex-alistair-helloworld/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/dex-alistair-helloworld/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/dex-alistair-helloworld/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/dex-alistair-helloworld/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/dex-alistair-helloworld/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/dex-alistair-helloworld/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/dex-alistair-helloworld/resources/versions.tf

initial - new namespace dex-alistair-helloworld

init new namespace

---

namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-dev/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-dev/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-dev/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-dev/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-dev/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-dev/certdcsdev.yml
namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-dev/certwsdev.yml
namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-dev/prometheus-custom-alerts-ccic-dev.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-dev/resources/ecr.tf
namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-dev/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-dev/resources/pingdom.tf
namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-dev/resources/pushgateway.tf
namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-dev/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-dev/resources/s3.tf
namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-dev/resources/variable.tf
namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-dev/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-dev/serviceaccount.yml

Migration of our dev namespace.

migration of claim-criminal-injuries-compensation-dev namespace

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/manage-recalls-preprod/00-namespace.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/manage-recalls-preprod/01-rbac.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/manage-recalls-preprod/02-limitrange.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/manage-recalls-preprod/03-resourcequota.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/manage-recalls-preprod/04-networkpolicy.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/manage-recalls-preprod/05-serviceaccount-circleci.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/manage-recalls-preprod/certificate.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/manage-recalls-preprod/resources/elasticache.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/manage-recalls-preprod/resources/main.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/manage-recalls-preprod/resources/pingdom.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/manage-recalls-preprod/resources/rds.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/manage-recalls-preprod/resources/s3.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/manage-recalls-preprod/resources/variables.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/manage-recalls-preprod/resources/versions.tf

Create the `manage-recalls-preprod` namespace and resources.

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/manage-recalls-prod/00-namespace.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/manage-recalls-prod/01-rbac.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/manage-recalls-prod/02-limitrange.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/manage-recalls-prod/03-resourcequota.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/manage-recalls-prod/04-networkpolicy.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/manage-recalls-prod/05-serviceaccount-circleci.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/manage-recalls-prod/certificate.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/manage-recalls-prod/resources/elasticache.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/manage-recalls-prod/resources/main.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/manage-recalls-prod/resources/pingdom.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/manage-recalls-prod/resources/rds.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/manage-recalls-prod/resources/s3.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/manage-recalls-prod/resources/variables.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/manage-recalls-prod/resources/versions.tf

Create the `manage-recalls-prod` namespace and resources.

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/court-probation-dev/resources/rds-pre-sentence-service.tf

Upgrades rds-pre-sentence-service from Postgres 11 to 13.3

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/court-probation-dev/resources/rds-pre-sentence-service.tf

PIC-1935 pre-sentence service dev postgres

---

namespaces/live.cloud-platform.service.justice.gov.uk/manage-soc-cases-preprod/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/manage-soc-cases-preprod/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/manage-soc-cases-preprod/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/manage-soc-cases-preprod/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/manage-soc-cases-preprod/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/manage-soc-cases-preprod/05-serviceaccount-circleci.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/manage-soc-cases-preprod/06-certificate.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/manage-soc-cases-preprod/07-certificate.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/manage-soc-cases-preprod/resources/elasticache.tf
namespaces/live.cloud-platform.service.justice.gov.uk/manage-soc-cases-preprod/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/manage-soc-cases-preprod/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/manage-soc-cases-preprod/resources/s3.tf
namespaces/live.cloud-platform.service.justice.gov.uk/manage-soc-cases-preprod/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/manage-soc-cases-preprod/resources/versions.tf

DCS-1333: migrate manage-soc-cases-preprod to live

♻️DCS-1333: migrate manage-soc-cases-preprod to live

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/court-probation-preprod/resources/rds-pre-sentence-service.tf

Upgrades rds-pre-sentence-service in pre prod from Postgres 11 to 13.3

PIC-1935 pre-sentence-service preprod postgres upgrade

---

namespaces/live.cloud-platform.service.justice.gov.uk/legal-framework-api-staging/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/legal-framework-api-staging/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/legal-framework-api-staging/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/legal-framework-api-staging/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/legal-framework-api-staging/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/legal-framework-api-staging/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/legal-framework-api-staging/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/legal-framework-api-staging/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/legal-framework-api-staging/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/legal-framework-api-staging/serviceaccount-admin.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/legal-framework-api-staging/serviceaccount-circleci.yaml

This mornings PR was mainly empty due to a git commit issue!

EKS: Migrate legal framework staging environment

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/court-probation-prod/resources/rds-pre-sentence-service.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/court-probation-prod/resources/rds.tf

Upgrade pre-sentence-service to Postgres 13.3
Ensure other rds instance is not affected

PIC-1935 Upgrade Postgres PR2

---

.checksum
namespaces/live.cloud-platform.service.justice.gov.uk/evidencelibrary-prod/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/evidencelibrary-prod/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/evidencelibrary-prod/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/evidencelibrary-prod/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/evidencelibrary-prod/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/evidencelibrary-prod/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/evidencelibrary-prod/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/evidencelibrary-prod/resources/versions.tf

Added to live folder. Not planning to go live in the next 1 month!

Evidencelibrary: new namespace for prod env

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/track-a-move-dev/resources/book-a-secure-move-api-iam.tf

This should solve an issue we have with fetching new athena data in our GPS Data report.

Add glue:BatchCreatePartition to dev BaSM Athena

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/track-a-move-prod/resources/book-a-secure-move-api-iam.tf

This should solve an issue we have with fetching new athena data in our GPS Data report.

Add glue:BatchCreatePartition to prod BaSM Athena

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-fee-calculator-dev/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-fee-calculator-dev/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-fee-calculator-dev/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-fee-calculator-dev/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-fee-calculator-dev/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-fee-calculator-dev/certficate.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-fee-calculator-dev/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-fee-calculator-dev/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-fee-calculator-dev/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-fee-calculator-dev/serviceaccount-circleci.yaml

Create laa-fee-calculator-dev namespace in "live"

Create laa-fee-calculator-dev namespace in "live"

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/court-probation-dev/resources/rds-pre-sentence-service.tf

No longer allow major version upgrade

PIC-1935 Upgrade Postgres - (Dev)

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/court-probation-prod/resources/rds-pre-sentence-service.tf

No longer allow major version upgrade

PIC-1935 Upgrade Postgres - (Prod) 

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/contact-moj-production/resources/ecr.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/parliamentary-questions-development/resources/ecr.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/peoplefinder-production/resources/ecr.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/track-a-query-production/resources/ecr.tf

This is to use the latest version, to fix inspector2 permissions issue

Update ECR for correspondence and pq-team teams

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-fee-calculator-staging/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-fee-calculator-staging/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-fee-calculator-staging/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-fee-calculator-staging/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-fee-calculator-staging/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-fee-calculator-staging/certficate.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-fee-calculator-staging/resources/ecr.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-fee-calculator-staging/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-fee-calculator-staging/resources/pingdom.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-fee-calculator-staging/resources/route53.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-fee-calculator-staging/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-fee-calculator-staging/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-fee-calculator-staging/serviceaccount-circleci.yaml

Prepare migration of laa-fee-calculator-staging namespace to "live" cluster

Create laa-fee-calculator-staging namespace in "live" cluster

---

namespaces/live.cloud-platform.service.justice.gov.uk/use-of-force-preprod/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/use-of-force-preprod/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/use-of-force-preprod/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/use-of-force-preprod/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/use-of-force-preprod/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/use-of-force-preprod/05-serviceaccount-circleci.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/use-of-force-preprod/07-certificate.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/use-of-force-preprod/resources/elasticache.tf
namespaces/live.cloud-platform.service.justice.gov.uk/use-of-force-preprod/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/use-of-force-preprod/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/use-of-force-preprod/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/use-of-force-preprod/resources/versions.tf

DCS-1360: migrate use-of-force-preprod to live

DCS-1360: migrate use-of-force-preprod to live

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-fee-calculator-production/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-fee-calculator-production/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-fee-calculator-production/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-fee-calculator-production/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-fee-calculator-production/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-fee-calculator-production/certificate.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-fee-calculator-production/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-fee-calculator-production/resources/pingdom.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-fee-calculator-production/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-fee-calculator-production/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-fee-calculator-production/serviceaccount-circleci.yaml

Prep for migration of laa-fee-calculator-production to "live" cluster

create laa-fee-calculator-production namespace in live

---

namespaces/live.cloud-platform.service.justice.gov.uk/use-of-force-prod/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/use-of-force-prod/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/use-of-force-prod/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/use-of-force-prod/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/use-of-force-prod/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/use-of-force-prod/05-serviceaccount-circleci.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/use-of-force-prod/07-certificate.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/use-of-force-prod/resources/elasticache.tf
namespaces/live.cloud-platform.service.justice.gov.uk/use-of-force-prod/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/use-of-force-prod/resources/pingdom.tf
namespaces/live.cloud-platform.service.justice.gov.uk/use-of-force-prod/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/use-of-force-prod/resources/route53.tf
namespaces/live.cloud-platform.service.justice.gov.uk/use-of-force-prod/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/use-of-force-prod/resources/versions.tf

DCS-1360: migrate use-of-force-prod to live

DCS-1360: migrate use-of-force-prod to live

---

namespaces/live.cloud-platform.service.justice.gov.uk/evidencelibrary-prod/resources/pingdom.tf
namespaces/live.cloud-platform.service.justice.gov.uk/evidencelibrary-prod/resources/versions.tf

added a couple of pingdom_check resources for prod environment.

evidencelibrary-prod: add pingdom checks

---

namespaces/live.cloud-platform.service.justice.gov.uk/check-financial-eligibility-staging/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/check-financial-eligibility-staging/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/check-financial-eligibility-staging/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/check-financial-eligibility-staging/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/check-financial-eligibility-staging/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/check-financial-eligibility-staging/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/check-financial-eligibility-staging/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/check-financial-eligibility-staging/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/check-financial-eligibility-staging/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/check-financial-eligibility-staging/serviceaccount-admin.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/check-financial-eligibility-staging/serviceaccount-circleci.yaml

create live version of CFE staging

create live version of cfe staging using cloud-platform tool

---

namespaces/live.cloud-platform.service.justice.gov.uk/cccd-dev-lgfs/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/cccd-dev-lgfs/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/cccd-dev-lgfs/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/cccd-dev-lgfs/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/cccd-dev-lgfs/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/cccd-dev-lgfs/certificate.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/cccd-dev-lgfs/resources/elasticache.tf
namespaces/live.cloud-platform.service.justice.gov.uk/cccd-dev-lgfs/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/cccd-dev-lgfs/resources/messaging.tf
namespaces/live.cloud-platform.service.justice.gov.uk/cccd-dev-lgfs/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/cccd-dev-lgfs/resources/s3.tf
namespaces/live.cloud-platform.service.justice.gov.uk/cccd-dev-lgfs/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/cccd-dev-lgfs/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/cccd-dev-lgfs/serviceaccount-circleci.yaml

Create cccd-dev-lgfs namespace in "live"
First namespace migration for CCCD

create cccd-dev-lgfs namespace in live

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/peoplefinder-staging/resources/elasticsearch.tf

https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/environments-terraform/jobs/apply-namespace-changes-live-1/builds/896

Fix duplicate cloudwatch log group elasticsearch.tf

---

namespaces/live.cloud-platform.service.justice.gov.uk/check-financial-eligibility-production/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/check-financial-eligibility-production/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/check-financial-eligibility-production/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/check-financial-eligibility-production/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/check-financial-eligibility-production/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/check-financial-eligibility-production/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/check-financial-eligibility-production/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/check-financial-eligibility-production/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/check-financial-eligibility-production/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/check-financial-eligibility-production/serviceaccount-admin.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/check-financial-eligibility-production/serviceaccount-circleci.yaml

create a new live cluster namespace for CFE prod

create new napespace cfe EKS

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-welcome-to-prison-preprod/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-welcome-to-prison-preprod/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-welcome-to-prison-preprod/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-welcome-to-prison-preprod/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-welcome-to-prison-preprod/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-welcome-to-prison-preprod/05-serviceaccount-circleci.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-welcome-to-prison-preprod/06-certificate.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-welcome-to-prison-preprod/resources/elasticache.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-welcome-to-prison-preprod/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-welcome-to-prison-preprod/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-welcome-to-prison-preprod/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-welcome-to-prison-preprod/resources/versions.tf

🤖 DCS-1383: Migrate hmpps-welcome-to-prison-preprod to live

🤖 DCS-1383: Migrate hmpps-welcome-to-prison-preprod to live

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-welcome-to-prison-prod/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-welcome-to-prison-prod/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-welcome-to-prison-prod/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-welcome-to-prison-prod/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-welcome-to-prison-prod/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-welcome-to-prison-prod/05-serviceaccount-circleci.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-welcome-to-prison-prod/06-certificate.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-welcome-to-prison-prod/resources/elasticache.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-welcome-to-prison-prod/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-welcome-to-prison-prod/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-welcome-to-prison-prod/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-welcome-to-prison-prod/resources/versions.tf

🤖 DCS-1383: Migrate hmpps-welcome-to-prison-prod to live

🤖 DCS-1383: Migrate hmpps-welcome-to-prison-prod to live

---

namespaces/live.cloud-platform.service.justice.gov.uk/licences-preprod/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/licences-preprod/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/licences-preprod/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/licences-preprod/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/licences-preprod/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/licences-preprod/05-serviceaccount-circleci.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/licences-preprod/07-certificates.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/licences-preprod/resources/elasticache.tf
namespaces/live.cloud-platform.service.justice.gov.uk/licences-preprod/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/licences-preprod/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/licences-preprod/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/licences-preprod/resources/versions.tf

🤖 DCS-1383: Migrate licences-preprod to live

🤖 DCS-1383: Migrate licences-preprod to live

---

namespaces/live.cloud-platform.service.justice.gov.uk/licences-prod/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/licences-prod/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/licences-prod/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/licences-prod/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/licences-prod/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/licences-prod/05-serviceaccount-circleci.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/licences-prod/07-certificates.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/licences-prod/08-certificates-old-hostname.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/licences-prod/99-redirect_old_url_ingress.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/licences-prod/resources/elasticache.tf
namespaces/live.cloud-platform.service.justice.gov.uk/licences-prod/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/licences-prod/resources/pingdom.tf
namespaces/live.cloud-platform.service.justice.gov.uk/licences-prod/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/licences-prod/resources/route53.tf
namespaces/live.cloud-platform.service.justice.gov.uk/licences-prod/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/licences-prod/resources/versions.tf

🤖 DCS-1383: Migrate licences-prod to live

🤖 DCS-1383: Migrate licences-prod to live

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-video-link-prod/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-video-link-prod/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-video-link-prod/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-video-link-prod/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-video-link-prod/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-video-link-prod/05-serviceaccount-circleci.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-video-link-prod/06-certificate.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-video-link-prod/resources/elasticache.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-video-link-prod/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-video-link-prod/resources/pingdom.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-video-link-prod/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-video-link-prod/resources/versions.tf

🤖 DCS-1383: Migrate hmpps-book-video-link-prod to live

🤖 DCS-1383: Migrate hmpps-book-video-link-prod to live

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-video-link-preprod/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-video-link-preprod/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-video-link-preprod/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-video-link-preprod/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-video-link-preprod/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-video-link-preprod/05-serviceaccount-circleci.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-video-link-preprod/06-certificate.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-video-link-preprod/resources/elasticache.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-video-link-preprod/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-video-link-preprod/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-video-link-preprod/resources/versions.tf

🤖 DCS-1383: Migrate hmpps-book-video-link-preprod to live

🤖 DCS-1383: Migrate hmpps-book-video-link-preprod to live

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-cla-frontend-production/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-cla-frontend-production/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-cla-frontend-production/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-cla-frontend-production/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-cla-frontend-production/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-cla-frontend-production/05-serviceaccount-circleci.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-cla-frontend-production/06-certificate.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-cla-frontend-production/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-cla-frontend-production/resources/pingdom.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-cla-frontend-production/resources/s3.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-cla-frontend-production/resources/variable.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-cla-frontend-production/resources/versions.tf

laa cla frontend production migration

laa-cla-frontend-production migration.

---

namespaces/live.cloud-platform.service.justice.gov.uk/cccd-dev/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/cccd-dev/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/cccd-dev/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/cccd-dev/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/cccd-dev/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/cccd-dev/certificate.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/cccd-dev/resources/ecr.tf
namespaces/live.cloud-platform.service.justice.gov.uk/cccd-dev/resources/elasticache.tf
namespaces/live.cloud-platform.service.justice.gov.uk/cccd-dev/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/cccd-dev/resources/messaging.tf
namespaces/live.cloud-platform.service.justice.gov.uk/cccd-dev/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/cccd-dev/resources/route53.tf
namespaces/live.cloud-platform.service.justice.gov.uk/cccd-dev/resources/s3.tf
namespaces/live.cloud-platform.service.justice.gov.uk/cccd-dev/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/cccd-dev/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/cccd-dev/serviceaccount-circleci.yaml

create cccd-staging namespace in live

create cccd-dev namespace in live

---

namespaces/live.cloud-platform.service.justice.gov.uk/cccd-staging/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/cccd-staging/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/cccd-staging/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/cccd-staging/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/cccd-staging/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/cccd-staging/certificate.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/cccd-staging/resources/elasticache.tf
namespaces/live.cloud-platform.service.justice.gov.uk/cccd-staging/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/cccd-staging/resources/messaging.tf
namespaces/live.cloud-platform.service.justice.gov.uk/cccd-staging/resources/pingdom.tf
namespaces/live.cloud-platform.service.justice.gov.uk/cccd-staging/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/cccd-staging/resources/s3.tf
namespaces/live.cloud-platform.service.justice.gov.uk/cccd-staging/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/cccd-staging/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/cccd-staging/serviceaccount-circleci.yaml

create cccd-staging namespace in live cluster

create cccd-staging namespace in live

---

namespaces/live.cloud-platform.service.justice.gov.uk/cccd-api-sandbox/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/cccd-api-sandbox/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/cccd-api-sandbox/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/cccd-api-sandbox/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/cccd-api-sandbox/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/cccd-api-sandbox/certificate.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/cccd-api-sandbox/resources/elasticache.tf
namespaces/live.cloud-platform.service.justice.gov.uk/cccd-api-sandbox/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/cccd-api-sandbox/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/cccd-api-sandbox/resources/s3.tf
namespaces/live.cloud-platform.service.justice.gov.uk/cccd-api-sandbox/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/cccd-api-sandbox/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/cccd-api-sandbox/serviceaccount-circleci.yaml

Create cccd-ai-sandbox namespace in live

create cccd-ai-sandbox namespace in live

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-incentives-prod/resources/pingdom.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-incentives-prod/resources/versions.tf

Part of ticket: https://trello.com/c/w2bGwZHv

Incentives API/UI `prod` pingdom resources

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-cla-backend-production/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-cla-backend-production/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-cla-backend-production/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-cla-backend-production/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-cla-backend-production/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-cla-backend-production/05-serviceaccount-circleci.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-cla-backend-production/06-certificate.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-cla-backend-production/07-prometheus-k8.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-cla-backend-production/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-cla-backend-production/resources/pingdom.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-cla-backend-production/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-cla-backend-production/resources/route53.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-cla-backend-production/resources/s3.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-cla-backend-production/resources/sqs.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-cla-backend-production/resources/variable.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-cla-backend-production/resources/versions.tf

Migrate laa-cla-backend-production namespace to live cluster

Migrate laa-cla-backend-production namespace to live cluster

---

namespaces/live.cloud-platform.service.justice.gov.uk/cccd-production/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/cccd-production/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/cccd-production/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/cccd-production/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/cccd-production/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/cccd-production/certificate.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/cccd-production/resources/elasticache.tf
namespaces/live.cloud-platform.service.justice.gov.uk/cccd-production/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/cccd-production/resources/messaging.tf
namespaces/live.cloud-platform.service.justice.gov.uk/cccd-production/resources/pingdom.tf
namespaces/live.cloud-platform.service.justice.gov.uk/cccd-production/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/cccd-production/resources/route53.tf
namespaces/live.cloud-platform.service.justice.gov.uk/cccd-production/resources/s3.tf
namespaces/live.cloud-platform.service.justice.gov.uk/cccd-production/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/cccd-production/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/cccd-production/serviceaccount-circleci.yaml

Create cccd-production namespace in live

create cccd-production namespace in live

---

namespaces/live.cloud-platform.service.justice.gov.uk/check-my-diary-prod/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/check-my-diary-prod/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/check-my-diary-prod/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/check-my-diary-prod/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/check-my-diary-prod/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/check-my-diary-prod/05-serviceaccount-circleci.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/check-my-diary-prod/07-certificate.yml
namespaces/live.cloud-platform.service.justice.gov.uk/check-my-diary-prod/08-prometheus.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/check-my-diary-prod/resources/ecr.tf
namespaces/live.cloud-platform.service.justice.gov.uk/check-my-diary-prod/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/check-my-diary-prod/resources/pingdom.tf
namespaces/live.cloud-platform.service.justice.gov.uk/check-my-diary-prod/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/check-my-diary-prod/resources/route53.tf
namespaces/live.cloud-platform.service.justice.gov.uk/check-my-diary-prod/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/check-my-diary-prod/resources/versions.tf

🤖 PAT-2128: Migrate check-my-diary-prod to live

🤖 PAT-2128: Migrate check-my-diary-prod to live

---

namespaces/live.cloud-platform.service.justice.gov.uk/pathfinder-prod/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/pathfinder-prod/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/pathfinder-prod/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/pathfinder-prod/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/pathfinder-prod/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/pathfinder-prod/05-serviceaccount-circleci.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/pathfinder-prod/06-certificate.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/pathfinder-prod/07-certificate.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/pathfinder-prod/resources/elasticache.tf
namespaces/live.cloud-platform.service.justice.gov.uk/pathfinder-prod/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/pathfinder-prod/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/pathfinder-prod/resources/route53.tf
namespaces/live.cloud-platform.service.justice.gov.uk/pathfinder-prod/resources/s3.tf
namespaces/live.cloud-platform.service.justice.gov.uk/pathfinder-prod/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/pathfinder-prod/resources/versions.tf

🤖 PAT-2128: Migrate pathfinder-prod to live

🤖 PAT-2128: Migrate pathfinder-prod to live

---

namespaces/live.cloud-platform.service.justice.gov.uk/manage-soc-cases-prod/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/manage-soc-cases-prod/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/manage-soc-cases-prod/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/manage-soc-cases-prod/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/manage-soc-cases-prod/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/manage-soc-cases-prod/05-serviceaccount-circleci.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/manage-soc-cases-prod/06-certificate.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/manage-soc-cases-prod/07-certificate.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/manage-soc-cases-prod/resources/elasticache.tf
namespaces/live.cloud-platform.service.justice.gov.uk/manage-soc-cases-prod/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/manage-soc-cases-prod/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/manage-soc-cases-prod/resources/s3.tf
namespaces/live.cloud-platform.service.justice.gov.uk/manage-soc-cases-prod/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/manage-soc-cases-prod/resources/versions.tf

🤖 PAT-2128: Migrate manage-soc-cases-prod to live

🤖 PAT-2128: Migrate manage-soc-cases-prod to live

---

namespaces/live.cloud-platform.service.justice.gov.uk/offender-categorisation-prod/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/offender-categorisation-prod/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/offender-categorisation-prod/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/offender-categorisation-prod/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/offender-categorisation-prod/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/offender-categorisation-prod/05-serviceaccount-circleci.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/offender-categorisation-prod/07-rbac-nart-team.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/offender-categorisation-prod/08-certificates.yml
namespaces/live.cloud-platform.service.justice.gov.uk/offender-categorisation-prod/resources/elasticache.tf
namespaces/live.cloud-platform.service.justice.gov.uk/offender-categorisation-prod/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/offender-categorisation-prod/resources/messaging.tf
namespaces/live.cloud-platform.service.justice.gov.uk/offender-categorisation-prod/resources/pingdom.tf
namespaces/live.cloud-platform.service.justice.gov.uk/offender-categorisation-prod/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/offender-categorisation-prod/resources/route53.tf
namespaces/live.cloud-platform.service.justice.gov.uk/offender-categorisation-prod/resources/s3.tf
namespaces/live.cloud-platform.service.justice.gov.uk/offender-categorisation-prod/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/offender-categorisation-prod/resources/versions.tf

🤖 PAT-2128: Migrate offender-categorisation-prod to live

🤖 PAT-2128: Migrate offender-categorisation-prod to live

---

namespaces/live.cloud-platform.service.justice.gov.uk/contact-moj-staging/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/contact-moj-staging/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/contact-moj-staging/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/contact-moj-staging/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/contact-moj-staging/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/contact-moj-staging/05-certificate.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/contact-moj-staging/06-servicemonitor.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/contact-moj-staging/08-service-account-circleci.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/contact-moj-staging/resources/elasticache.tf
namespaces/live.cloud-platform.service.justice.gov.uk/contact-moj-staging/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/contact-moj-staging/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/contact-moj-staging/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/contact-moj-staging/resources/versions.tf

Migrate contact-moj staging live1 to live

contact-moj-staging migrate live1 to live

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-dev/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-dev/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-dev/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-dev/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-dev/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-dev/05-certificate.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-dev/06-service-account.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-dev/07-service-monitor.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-dev/08-prometheus-rule.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-dev/resources/cp_local_queue.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-dev/resources/ecr.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-dev/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-dev/resources/messaging-queues.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-dev/resources/pingdom.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-dev/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-dev/resources/redis.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-dev/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-dev/resources/versions.tf

Migrate laa-court-data-adaptor-dev namespace env to 'live' cluster

Migrate laa-court-data-adaptor-dev namespace env to 'live' cluster

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-legal-adviser-api-production/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-legal-adviser-api-production/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-legal-adviser-api-production/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-legal-adviser-api-production/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-legal-adviser-api-production/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-legal-adviser-api-production/05-serviceaccount-circleci.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-legal-adviser-api-production/resources/elasticache.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-legal-adviser-api-production/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-legal-adviser-api-production/resources/pingdom.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-legal-adviser-api-production/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-legal-adviser-api-production/resources/s3.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-legal-adviser-api-production/resources/variable.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-legal-adviser-api-production/resources/versions.tf

Migrate laa-legal-adviser-api-production to new live cluster

Migrate laa-legal-adviser-api-production to new live cluster

---

.checksum
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-api-dev/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-api-dev/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-api-dev/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-api-dev/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-api-dev/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-api-dev/resources/ecr.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-api-dev/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-api-dev/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-api-dev/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-api-dev/resources/versions.tf

- Created a new namespace as per [this guide](https://user-guide.cloud-platform.service.justice.gov.uk/documentation/getting-started/env-create.html#introduction)
- Created a new ECR repo as per [this guide](https://user-guide.cloud-platform.service.justice.gov.uk/documentation/getting-started/ecr-setup.html#creating-the-registry)
- Create a new service account as per [this guide](https://user-guide.cloud-platform.service.justice.gov.uk/documentation/getting-started/ecr-setup.html#creating-the-registry)

AAC-268 - New namespace for laa-court-data-api-dev

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-users-prod/99-redirect_old_url_ingress.yaml

https://dsdmoj.atlassian.net/browse/HAAR-10

HAAR-10: 🔧 update ingress

---

pkg/authenticate/authenticate.go
pkg/authenticate/authenticate_test.go

This is to create a new function switchContextFromS3Bucket that takes the bucket name, a config file, a region and the context of a cluster and set the current context.

Auth switch in authenticate package

---

namespaces/live.cloud-platform.service.justice.gov.uk/soc-reporting-dev/resources/ecr.tf
namespaces/live.cloud-platform.service.justice.gov.uk/soc-reporting-dev/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/soc-reporting-dev/resources/variables.tf

added service account for both soc entry and soc reporting and modified ecr.tf to enable git actions

Soc dev GitHub actions

---

namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-prod/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-prod/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-prod/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-prod/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-prod/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-prod/certdcsprod.yml
namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-prod/certwsprod.yml
namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-prod/prometheus-custom-alerts-ccic-prod.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-prod/resources/ecr.tf
namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-prod/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-prod/resources/pingdom.tf
namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-prod/resources/pushgateway.tf
namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-prod/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-prod/resources/route53.tf
namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-prod/resources/s3.tf
namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-prod/resources/variable.tf
namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-prod/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-prod/serviceaccount.yml

Claim-criminal-injuries-compensation-prod migration

Prod environment migration

---

namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-uat/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-uat/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-uat/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-uat/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-uat/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-uat/certdcsuat.yml
namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-uat/certwsuat.yml
namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-uat/resources/ecr.tf
namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-uat/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-uat/resources/pingdom.tf
namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-uat/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-uat/resources/s3.tf
namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-uat/resources/variable.tf
namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-uat/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-uat/serviceaccount.yml

Claim-criminal-injuries-compensation-uat migration

Uat environment migration

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-services-live-production/03-resourcequota.yaml

This namespace holds the live forms in production. We have recieved an alert
that we are nearing the quota. We have recently added more replicas to cope
with demand. This PR will increase the hard limit from 150 to 250.

Increase the the quota of pods

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-fala-production/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-fala-production/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-fala-production/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-fala-production/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-fala-production/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-fala-production/05-serviceaccount-circleci.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-fala-production/06-certificate.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-fala-production/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-fala-production/resources/route53.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-fala-production/resources/s3.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-fala-production/resources/variable.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-fala-production/resources/versions.tf

Migrate laa-fala-production to new live cluster

Migrate laa-fala-production to new live cluster

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-events-prod/resources/hmpps-interventions.tf

Consequence of #6819, but couldn't do it in the same PR

interventions-prod: Re-enable domain event topic secret injection

---

namespaces/live.cloud-platform.service.justice.gov.uk/pact-broker-prod/resources/serviceaccount-github.tf
namespaces/live.cloud-platform.service.justice.gov.uk/pact-broker-prod/resources/variables.tf

Add github credentials to hmpps-pact-broker

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-uat/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-uat/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-uat/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-uat/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-uat/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-uat/05-certificate.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-uat/06-service-account.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-uat/07-service-monitor.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-uat/08-prometheus-rule.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-uat/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-uat/resources/messaging-queues.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-uat/resources/pingdom.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-uat/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-uat/resources/redis.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-uat/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-uat/resources/versions.tf

Migrate laa-court-data-adaptor-uat to live cluster

Migrate laa-court-data-adaptor-uat to live cluster

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-test/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-test/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-test/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-test/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-test/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-test/05-certificate.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-test/06-service-account.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-test/07-service-monitor.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-test/08-prometheus-rule.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-test/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-test/resources/messaging-queues.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-test/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-test/resources/redis.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-test/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-test/resources/versions.tf

Migrate laa-court-data-adaptor-test to live cluster

Migrate laa-court-data-adaptor-test to live cluster

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-stage/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-stage/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-stage/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-stage/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-stage/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-stage/05-certificate.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-stage/06-service-account.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-stage/07-service-monitor.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-stage/08-prometheus-rule.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-stage/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-stage/resources/messaging-queues.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-stage/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-stage/resources/redis.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-stage/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-stage/resources/versions.tf

Migrate laa-court-data-adaptor-stage  namespace to live cluster.

Migrate laa-court-data-adaptor-stage to live cluster

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-prod/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-prod/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-prod/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-prod/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-prod/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-prod/05-certificate.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-prod/06-service-account.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-prod/07-service-monitor.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-prod/08-prometheus-rule.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-prod/09-http_status_codes_grafana_dashboard.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-prod/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-prod/resources/messaging-queues.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-prod/resources/pingdom.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-prod/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-prod/resources/redis.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-prod/resources/route53.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-prod/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-prod/resources/versions.tf

Migrate laa-court-data-adaptor-prod to live cluster with `cloud-platform environment migrate`.

Migrate laa-court-data-adaptor-prod to live cluster

---

pkg/authenticate/authenticate.go

This will enable to set the path as input supplied at function call

Update SwitchContextFromS3Bucket for config path

---

pkg/authenticate/authenticate.go
pkg/authenticate/authenticate_test.go

To provide kubeConfigPath actual input supplied at function call

Update auth KubeConfigFromS3Bucket

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-interventions-prototype/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-interventions-prototype/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-interventions-prototype/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-interventions-prototype/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-interventions-prototype/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-interventions-prototype/resources/basic-auth.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-interventions-prototype/resources/ecr.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-interventions-prototype/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-interventions-prototype/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-interventions-prototype/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-interventions-prototype/resources/versions.tf

To publish prototype from an existing GitHub repo.

Create hmpps-interventions-prototype namespace

---

.checksum
namespaces/live.cloud-platform.service.justice.gov.uk/nettest/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/nettest/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/nettest/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/nettest/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/nettest/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/nettest/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/nettest/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/nettest/resources/versions.tf

This app will be used to test networking connectivity between the Cloud Platform and the Modernisation Platform.

Create a Cloud Platform environment for the network test app

---

namespaces/live.cloud-platform.service.justice.gov.uk/contact-moj-development/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/contact-moj-development/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/contact-moj-development/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/contact-moj-development/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/contact-moj-development/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/contact-moj-development/05-certificate.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/contact-moj-development/08-service-account-circleci.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/contact-moj-development/resources/elasticache.tf
namespaces/live.cloud-platform.service.justice.gov.uk/contact-moj-development/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/contact-moj-development/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/contact-moj-development/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/contact-moj-development/resources/versions.tf

Reverts ministryofjustice/cloud-platform-environments#6976

Revert "contact-moj-development remove migrated namespaces"

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-ems-prod/resources/route53.tf

Add CNAME record so HMPPS EMS can use a custom Auth0 domain to close https://github.com/ministryofjustice/cloud-platform-environments/pull/6999

Add Auth0 custom domain CNAME record

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-ems-prod/05-serviceaccount.yaml

Helm is getting stuck in `pending-install`, and I think this is the solution
Related to https://github.com/helm/helm/issues/7139

Add `update` verb to HMPPS EMS Prod GitHub Service Account

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-fee-calculator-dev/serviceaccount-circleci.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-fee-calculator-production/serviceaccount-circleci.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-fee-calculator-staging/serviceaccount-circleci.yaml

Enable watch and list of deployments
So we can "wait" for successfull deply or fail.

Add laa fee calculator circle serviceaccount privs

---

namespaces/live.cloud-platform.service.justice.gov.uk/digital-prison-services-prod/resources/route53-hmpps.tf

https://dsdmoj.atlassian.net/browse/HAAR-71

HAAR-71: drop route53 record for hmpps-auth-stage

---

namespace-resources-cli-template/resources/prototype/github-repo.tf

This is to create files to files to build docker image and
CD workflow in prototype github repo
Related to:
https://github.com/ministryofjustice/cloud-platform/issues/3457

Update git-hub repo prototype

---

namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-av-mirror/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-av-mirror/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-av-mirror/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-av-mirror/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-av-mirror/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-av-mirror/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-av-mirror/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-av-mirror/resources/versions.tf

Part of the improvements being made to MOJ Forms platform is
the virus checking for uploaded documents.
We use CLamAv and will be adding more scanning services
and they will all get the latest definitions from this service.

New namespace for test running a clamav mirror

---

namespaces/live.cloud-platform.service.justice.gov.uk/offender-events-prod/09-prometheus-sqs-sns.yaml

Related to: https://mojdt.slack.com/archives/C8PF51AT0/p1644417689032659

Comment hmpps-cfo-dms-alerts as this channel doesnot exists

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-ems-prod/resources/serviceaccount.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-ems-prod/resources/variables.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-ems-prod/resources/versions.tf

As per my conversation with CP, I am creating a service account using the Terraform module. This will eventually replace the one I created https://github.com/ministryofjustice/cloud-platform-environments/blob/main/namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-ems-prod/05-serviceaccount.yaml
This will close https://github.com/ministryofjustice/hmpps-ems-platform/issues/144

Create Service Account for GitHub Actions

---

namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-services-live-dev/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-services-live-dev/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-services-live-dev/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-services-live-dev/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-services-live-dev/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-services-live-dev/certificate.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-services-live-dev/circleci-service-account.yaml

formbuilder-services-live-dev namespace in live cluster

Add formbuilder-services-live-dev to Live

---

namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-services-live-production/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-services-live-production/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-services-live-production/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-services-live-production/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-services-live-production/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-services-live-production/certificate.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-services-live-production/circleci-service-account.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-services-live-production/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-services-live-production/resources/route53.tf
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-services-live-production/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-services-live-production/resources/versions.tf

formbuilder-services-live-production namespace in live cluster

Add formbuilder-services-live-production to Live

---

namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-product-page-prod/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-product-page-prod/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-product-page-prod/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-product-page-prod/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-product-page-prod/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-product-page-prod/certificates.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-product-page-prod/formbuilder-product-page-prod-service-account.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-product-page-prod/resources/ecr.tf
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-product-page-prod/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-product-page-prod/resources/route53.tf
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-product-page-prod/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-product-page-prod/resources/versions.tf

formbuilder-product-page-prod namespace in live cluster

Add formbuilder-product-page-prod namespace to live

---

namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-saas-live/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-saas-live/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-saas-live/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-saas-live/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-saas-live/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-saas-live/05-circleci-service-account.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-saas-live/06-certificates.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-saas-live/07-prometheus.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-saas-live/editor-service-account.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-saas-live/editor-workers-service-account.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-saas-live/metadata-api-service-account.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-saas-live/resources/editor.tf
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-saas-live/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-saas-live/resources/metadata_api.tf
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-saas-live/resources/route53.tf
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-saas-live/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-saas-live/resources/versions.tf

formbuilder-saas-live namespace in live cluster

Add formbuilder-saas-live to Live

---

namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-publisher-live/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-publisher-live/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-publisher-live/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-publisher-live/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-publisher-live/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-publisher-live/circleci-service-account.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-publisher-live/publisher-workers-service-account.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-publisher-live/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-publisher-live/resources/publisher.tf
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-publisher-live/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-publisher-live/resources/versions.tf

formbuilder-publisher-live namespace in live cluster

Add formbuilder-publisher-live namespace to Live

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmcts-complaints-formbuilder-adapter-production/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmcts-complaints-formbuilder-adapter-production/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmcts-complaints-formbuilder-adapter-production/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmcts-complaints-formbuilder-adapter-production/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmcts-complaints-formbuilder-adapter-production/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmcts-complaints-formbuilder-adapter-production/05-service-accounts.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmcts-complaints-formbuilder-adapter-production/resources/ecr.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmcts-complaints-formbuilder-adapter-production/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmcts-complaints-formbuilder-adapter-production/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmcts-complaints-formbuilder-adapter-production/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmcts-complaints-formbuilder-adapter-production/resources/versions.tf

hmcts-complaints-formbuilder-adapter-production namespace in live cluster

Add hmcts-adapter-production namespace to Live

---

namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-live-dev/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-live-dev/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-live-dev/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-live-dev/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-live-dev/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-live-dev/av-service-account.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-live-dev/circleci-service-account.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-live-dev/pdf-generator-service-account.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-live-dev/resources/json-output-attachments-s3.tf
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-live-dev/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-live-dev/resources/service_token_cache.tf
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-live-dev/resources/submitter.tf
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-live-dev/resources/user-datastore.tf
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-live-dev/resources/user-filestore.tf
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-live-dev/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-live-dev/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-live-dev/service-token-cache-service-account.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-live-dev/submitter-workers-service-account.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-live-dev/user-datastore-service-account.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-live-dev/user-filestore-service-account.yaml

Add the formbuilder-platform-live-dev namespace to the Live EKS cluster

Create formbuilder-platform-live-dev namespace in Live

---

namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-live-production/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-live-production/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-live-production/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-live-production/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-live-production/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-live-production/av-service-account.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-live-production/circleci-service-account.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-live-production/pdf-generator-service-account.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-live-production/resources/json-output-attachments-s3.tf
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-live-production/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-live-production/resources/service_token_cache.tf
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-live-production/resources/submitter.tf
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-live-production/resources/user-datastore.tf
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-live-production/resources/user-filestore.tf
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-live-production/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-live-production/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-live-production/service-token-cache-service-account-2.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-live-production/service-token-cache-service-account.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-live-production/submitter-workers-service-account.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-live-production/user-datastore-service-account.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-live-production/user-filestore-service-account.yaml

formbuilder-platform-live-production namespace in live cluster

Create formbuilder-platform-live-production namespace in Live

---

namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-services-test-dev/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-services-test-dev/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-services-test-dev/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-services-test-dev/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-services-test-dev/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-services-test-dev/certificate.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-services-test-dev/circleci-service-account.yaml

Adding formbuilder-services-test-dev in Live cluster

Create formbuilder-services-test-dev namespace in Live

---

namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-services-test-production/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-services-test-production/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-services-test-production/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-services-test-production/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-services-test-production/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-services-test-production/certificate.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-services-test-production/circleci-service-account.yaml

Adding the formbuilder-services-test-production namespace in the Live
cluster

Create formbuilder-services-test-production in Live

---

namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-dev/resources/s3.tf

This will be used to store the WordPress persistent assets
such as files and multimedia.

Add s3 bucket to hale-platform-dev namespace

---

namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-av-mirror/resources/ecr.tf
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-av-mirror/resources/versions.tf

Followed instructions in the user guide and also enabled github
action secrets

Added ECR repository to the namespace

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-ui-dev/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-ui-dev/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-ui-dev/resources/variables.tf

The existing github team that we used seems to have been removed. This PR updates the team and email we use for this service so that details are as up to date as possible

AAC-499 - VCD Dev team update

---

namespaces/live.cloud-platform.service.justice.gov.uk/manage-recalls-dev/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/manage-recalls-preprod/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/manage-recalls-prod/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/ppud-replacement-dev/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/ppud-replacement-preprod/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/ppud-replacement-prod/00-namespace.yaml

These are needed for configuring network policies

Add labels to the manage-recalls and ppud-replacement namespaces

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-backstage-dev/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-backstage-dev/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-backstage-dev/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-backstage-dev/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-backstage-dev/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-backstage-dev/05-serviceaccount-circleci.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-backstage-dev/06-certificate.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-backstage-dev/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-backstage-dev/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-backstage-dev/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-backstage-dev/resources/versions.tf

- run `cloud-platform environment migrate` to generate migration

Migrate hmpps-backstage-dev to Live Namespace

---

namespaces/live.cloud-platform.service.justice.gov.uk/dso-monitoring-prod/05-offender-assessment-api-prometheusrule.yaml

Reverts ministryofjustice/cloud-platform-environments#7190 - testing was successful

Revert "DSO-1377: test of DSO studio hosting monitoring live-1 migration"

---

namespaces/live.cloud-platform.service.justice.gov.uk/send-legal-mail-to-prisons-dev/05-serviceaccount-circleci.yaml

This reverts commit 0403e0c4574da7d12b563381eb7786661c79af45.

Revert "SLM-135 Remove all role bindings so we can change one of them"

---

namespaces/live.cloud-platform.service.justice.gov.uk/send-legal-mail-to-prisons-dev/05-serviceaccount-circleci.yaml

This doesn't work in the pipeline so was applied manually - changing to match the manual change

SLM-135 Bind to admin ClusterRole

---

namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-dev/resources/analytical-platform-access.tf

S3 bucket for probation in court sending data to the analytical platform

PIC-1981 S3 bucket for analytical platform

---

namespaces/live.cloud-platform.service.justice.gov.uk/offender-events-prod/09-prometheus-sqs-sns.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/offender-events-prod/11-prometheus.yaml

to probation-integration-notifications channel

PI-73 Move Prometheus alerts for probation-offender-search SQS queue

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-ems-prod/resources/route53.tf

Resolves https://github.com/ministryofjustice/hmpps-ems-platform/issues/116

Add HMPPS EMS Mapping Training Zone Delegation

---

namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-preprod/resources/analytical-platform-access.tf
namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-prod/resources/analytical-platform-access.tf

PIC-1981 S3 buckets for probation in court sending data to the analytic platform

S3 buckets for probation in court sending data to analytic platform

---

namespaces/live.cloud-platform.service.justice.gov.uk/c100-application-metabase/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/c100-application-metabase/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/c100-application-metabase/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/c100-application-metabase/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/c100-application-metabase/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/c100-application-metabase/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/c100-application-metabase/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/c100-application-metabase/resources/versions.tf

Helping out #hmcts-sustaining-team with some parts of the migration as they are under pressure.

Migrate C100 metabase namespace to live cluster

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-incentives-dev/resources/ap-data.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-incentives-dev/resources/s3.tf

This change mirrors #7321 in testing environment

Add IRSA permission to list objects in dev S3 bucket

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-incentives-dev/resources/s3.tf

…by using terraform for the policy document so that validation is easier, plus I'm pretty sure the policy resource was previously incorrect

Fix HMPPS Incentives testing S3 bucket policy

---

namespaces/live.cloud-platform.service.justice.gov.uk/cccd-dev/resources/ecr.tf
namespaces/live.cloud-platform.service.justice.gov.uk/cccd-dev/resources/temp_ecr.tf

Temporay credentials for use by ITHC security team to scan images
of CCCD

Create temporary IAM creds for ITHC

---

namespaces/live.cloud-platform.service.justice.gov.uk/cccd-dev/resources/ecr.tf

Amend repo name for ECR credentials

---

namespaces/live.cloud-platform.service.justice.gov.uk/cccd-dev/resources/ecr.tf
namespaces/live.cloud-platform.service.justice.gov.uk/cccd-dev/resources/temp_ecr.tf

Correct ecr repo name

---

namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-monitoring/resources/pingdom.tf

Correct URL is live not live-1

Form Builder - update publisher pingdom URL

---

namespaces/live.cloud-platform.service.justice.gov.uk/create-and-vary-a-licence-prod/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/create-and-vary-a-licence-prod/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/create-and-vary-a-licence-prod/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/create-and-vary-a-licence-prod/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/create-and-vary-a-licence-prod/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/create-and-vary-a-licence-prod/05-serviceaccount-circleci.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/create-and-vary-a-licence-prod/06-certificate.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/create-and-vary-a-licence-prod/resources/elasticache.tf
namespaces/live.cloud-platform.service.justice.gov.uk/create-and-vary-a-licence-prod/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/create-and-vary-a-licence-prod/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/create-and-vary-a-licence-prod/resources/versions.tf

Create and vary a licence - create production namespace for the UI service.

CVSL-370: Create the UI service production namespace and resources.

---

namespaces/live.cloud-platform.service.justice.gov.uk/create-and-vary-a-licence-api-prod/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/create-and-vary-a-licence-api-prod/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/create-and-vary-a-licence-api-prod/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/create-and-vary-a-licence-api-prod/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/create-and-vary-a-licence-api-prod/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/create-and-vary-a-licence-api-prod/05-serviceaccount-circleci.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/create-and-vary-a-licence-api-prod/06-certificate.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/create-and-vary-a-licence-api-prod/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/create-and-vary-a-licence-api-prod/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/create-and-vary-a-licence-api-prod/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/create-and-vary-a-licence-api-prod/resources/versions.tf

Create and vary a licence - create production namespace for the API service.

CVSL-371: Create the API service production namespace and resources

---

namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-preprod/resources/analytical-platform-access.tf
namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-preprod/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-prod/resources/analytical-platform-access.tf
namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-prod/resources/variables.tf

Update S3 permissions to match refactored Analytic Platform pipeline database names

PIC-1981 Update S3 permissions to match refactored AP pipeline names

---

namespaces/live.cloud-platform.service.justice.gov.uk/cloudopsbot-prod/resources/rds-postgresql.tf

add PostgreSQL RDS for CloudOps Bot

:card_file_box: add PostgreSQL RDS for CloudOps Bot

---

namespaces/live.cloud-platform.service.justice.gov.uk/c100-application-staging/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/c100-application-staging/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/c100-application-staging/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/c100-application-staging/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/c100-application-staging/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/c100-application-staging/resources/ecr.tf
namespaces/live.cloud-platform.service.justice.gov.uk/c100-application-staging/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/c100-application-staging/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/c100-application-staging/resources/redis.tf
namespaces/live.cloud-platform.service.justice.gov.uk/c100-application-staging/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/c100-application-staging/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/c100-application-staging/serviceaccount-circleci.yaml

hmcts-sustaining-team c100 staging namespace migration to live.

Migrate C100 staging namespace to live cluster

---

namespaces/live.cloud-platform.service.justice.gov.uk/manage-recalls-dev/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/manage-recalls-dev/10-manage-recalls-api-dashboard.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/manage-recalls-preprod/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/manage-recalls-prod/04-networkpolicy.yaml

This moves config out of our helm charts into here to make them a little simpler to maintain.

Migrate manage recalls resources

---

namespaces/live.cloud-platform.service.justice.gov.uk/c100-application-production/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/c100-application-production/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/c100-application-production/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/c100-application-production/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/c100-application-production/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/c100-application-production/certificate.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/c100-application-production/prometheus.yml
namespaces/live.cloud-platform.service.justice.gov.uk/c100-application-production/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/c100-application-production/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/c100-application-production/resources/redis.tf
namespaces/live.cloud-platform.service.justice.gov.uk/c100-application-production/resources/route53.tf
namespaces/live.cloud-platform.service.justice.gov.uk/c100-application-production/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/c100-application-production/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/c100-application-production/serviceaccount-circleci.yaml

Migrate C100-application-production namespace to live cluster

Migrate C100 production namespace to live cluster

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-cla-backend-uat/resources/rds.tf

Create postgres 10 rds instance and export connection details as `database-10` K8 secret

LGA-2052 - Create postgres 10 rds instance and export connection details as database-10 K8 secret

---

namespaces/live.cloud-platform.service.justice.gov.uk/offender-events-prod/resources/offender_case_notes-sub-queue.tf

https://dsdmoj.atlassian.net/browse/HAAR-228

HAAR-228: create queue secrets in live namespace

---

namespaces/live.cloud-platform.service.justice.gov.uk/offender-events-prod/resources/topic.tf

https://dsdmoj.atlassian.net/browse/HAAR-228

HAAR-228: create topic secrets in live namespace

---

namespaces/live.cloud-platform.service.justice.gov.uk/offender-events-prod/resources/topic.tf

https://dsdmoj.atlassian.net/browse/HAAR-228

HAAR-228: rename topic secret

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-incentives-prod/resources/ap-data.tf

… since data scientists and engineers are putting files in multiple root folders

Grant HMPPS Incentives production applications read access to the root of bucket in Analytical Platform

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/data-eng-rds-dev/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/data-eng-rds-dev/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/data-eng-rds-dev/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/data-eng-rds-dev/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/data-eng-rds-dev/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/data-eng-rds-dev/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/data-eng-rds-dev/resources/ecr.tf
namespaces/live.cloud-platform.service.justice.gov.uk/data-eng-rds-dev/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/data-eng-rds-dev/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/data-eng-rds-dev/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/data-eng-rds-dev/resources/versions.tf

Hi, 
this is a PR as part of the migration to live from live-1
Any questions let me know - I can't currently modify the ingress file due to permissions issues, so this probably shouldn't be progressed until I can.

Migrating data-eng-rds-dev

---

namespaces/live.cloud-platform.service.justice.gov.uk/request-info-from-moj/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/request-info-from-moj/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/request-info-from-moj/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/request-info-from-moj/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/request-info-from-moj/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/request-info-from-moj/resources/basic-auth.tf
namespaces/live.cloud-platform.service.justice.gov.uk/request-info-from-moj/resources/ecr.tf
namespaces/live.cloud-platform.service.justice.gov.uk/request-info-from-moj/resources/github-repo.tf
namespaces/live.cloud-platform.service.justice.gov.uk/request-info-from-moj/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/request-info-from-moj/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/request-info-from-moj/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/request-info-from-moj/resources/versions.tf

This namespace is related to the prototype
https://github.com/ministryofjustice/cloud-platform/issues/3575

Migrate request-info-from-moj to "live"

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-means-assessment-dev/05-serviceaccount-circleci.yaml

Added monitoring api group and updated networking api group for CircleCI Role

Updated CircleCI role so that servicemonitor etc can be deployed

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-interventions-dev/06-service-monitor.yaml

The other side of
- https://github.com/ministryofjustice/hmpps-interventions-service/pull/843

Add prometheus service monitor for interventions-dev

---

namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-monitoring/resources/pingdom.tf

This form has been superseeded by another one

Form Builder - Remove usingmojforms pingdom

---

namespaces/live.cloud-platform.service.justice.gov.uk/manage-recalls-dev/10-manage-recalls-api-dashboard.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/manage-recalls-dev/10-manage-recalls-ui-dashboard.yaml

Looks like the JSON name needs to be unique...

Fix the MaR dashboards from overwriting each other

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-view-court-data-prototype/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-view-court-data-prototype/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-view-court-data-prototype/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-view-court-data-prototype/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-view-court-data-prototype/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-view-court-data-prototype/resources/basic-auth.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-view-court-data-prototype/resources/ecr.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-view-court-data-prototype/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-view-court-data-prototype/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-view-court-data-prototype/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-view-court-data-prototype/resources/versions.tf

Following the guidance here: https://user-guide.cloud-platform.service.justice.gov.uk/documentation/getting-started/prototype-kit.html#publish-prototypes-on-the-web

Add 'laa-view-court-data-prototype' namespace

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-prisoner-from-nomis-migration-dev/06-certificate.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-prisoner-from-nomis-migration-dev/resources/elasticache.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-prisoner-from-nomis-migration-dev/resources/variables.tf

Add cert & elastic cache for new service hmpps-prisoner-from-nomis-migration-dev

---

namespaces/live.cloud-platform.service.justice.gov.uk/jacksapp-dev/resources/ecr.tf

Adding a ecr resource following user guide "Creating an ECR repository"
to allow my to continue with "Step 3 - Create an Amazon ECR" of "Deploying a ‘Hello World’
application to the Cloud Platform"

feat: adding ecr resource

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-uat/05-prometheus.yaml

Update 10 second rule to include v1/statement_of_cases
Update 2 second rule to exclude it

Apply: Update UAT prometheus rules

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-production/05-prometheus.yaml

Update 10 second rule to include v1/statement_of_cases
Update 2 second rule to exclude it

Apply: Update Production prometheus rules

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-prisoner-education-design-history/resources/ecr.tf

Reverts ministryofjustice/cloud-platform-environments#7494

Revert "ESWE-270: Create ECR repository"

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-events-preprod/resources/curious-update.tf

Enable queue by de-mangling filter criteria

Enable Curious SQS queue in HMPPS Domain Events - preprod environment

---

namespaces/live.cloud-platform.service.justice.gov.uk/offender-events-preprod/resources/rds.tf

https://dsdmoj.atlassian.net/browse/HAAR-228

HAAR-228: create preprod secret in prod namespace which is used by db-refresh-job

---

namespaces/live.cloud-platform.service.justice.gov.uk/offender-categorisation-dev/01-rbac.yaml

PAT-2158 - update manage cat rbac github teams

---

namespaces/live.cloud-platform.service.justice.gov.uk/manage-pom-cases-prototype/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/manage-pom-cases-prototype/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/manage-pom-cases-prototype/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/manage-pom-cases-prototype/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/manage-pom-cases-prototype/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/manage-pom-cases-prototype/resources/basic-auth.tf
namespaces/live.cloud-platform.service.justice.gov.uk/manage-pom-cases-prototype/resources/ecr.tf
namespaces/live.cloud-platform.service.justice.gov.uk/manage-pom-cases-prototype/resources/github-repo.tf
namespaces/live.cloud-platform.service.justice.gov.uk/manage-pom-cases-prototype/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/manage-pom-cases-prototype/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/manage-pom-cases-prototype/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/manage-pom-cases-prototype/resources/versions.tf

Moving our prototype from Heroku to Cloud Platform.

Manage POM cases prototype

---

.checksum
namespaces/live.cloud-platform.service.justice.gov.uk/courts-local-scorecard-prod/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/courts-local-scorecard-prod/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/courts-local-scorecard-prod/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/courts-local-scorecard-prod/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/courts-local-scorecard-prod/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/courts-local-scorecard-prod/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/courts-local-scorecard-prod/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/courts-local-scorecard-prod/resources/versions.tf

Creates prod environment for the cjs-scorecard application

Add prod env for cjs-scorecard

---

namespaces/live.cloud-platform.service.justice.gov.uk/courts-local-scorecard-prod/resources/serviceaccount.tf

Needed to run Github workflows.

Add service account to courts-local-scorecard-prod

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-moic-prototype/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-moic-prototype/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-moic-prototype/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-moic-prototype/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-moic-prototype/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-moic-prototype/resources/basic-auth.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-moic-prototype/resources/ecr.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-moic-prototype/resources/github-repo.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-moic-prototype/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-moic-prototype/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-moic-prototype/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-moic-prototype/resources/versions.tf

Moving prototype from heroku to cloud platform

hmpps-moic-prototype

---

namespaces/live.cloud-platform.service.justice.gov.uk/courts-local-scorecard-prod/resources/route53.tf
namespaces/live.cloud-platform.service.justice.gov.uk/courts-local-scorecard-prod/resources/variables.tf

Add route53 config for new hosted zone for custom prod custom domain

Add route53.tf for custom prod domain name for courts-local-scorecard

---

namespaces/live.cloud-platform.service.justice.gov.uk/monitoring/dashboard-golden-signals.yaml

Added request timings and some pod diagnostic graphs

Update the golden signals dashboard

---

namespaces/live.cloud-platform.service.justice.gov.uk/monitoring/dashboard-golden-signals.yaml

More updates to the golden signals dashboard

---

namespaces/live.cloud-platform.service.justice.gov.uk/jacksapp-dev/resources/serviceaccount.tf

adding a service account to allow actions to run deployments to
namespace

feat: adding service account

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-events-prod/resources/curious-update.tf

De-mangle filter to allow messages to flow to Curious SQS

De-mangle Curious SQS filter for HMPPS-DOMAIN-EVENTS 

---

.checksum
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-api-uat/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-api-uat/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-api-uat/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-api-uat/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-api-uat/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-api-uat/resources/basic-auth.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-api-uat/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-api-uat/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-api-uat/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-api-uat/resources/versions.tf

As apart of deploying our new application we need to create the different environments for our application for testing. This PR is for creating our UAT environment with:
- Base namespace
- Service Account for CircleCI
- Basic Auth Secret

AAC-557 - Add new namespace for CDAPI

---

.checksum
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-api-staging/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-api-staging/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-api-staging/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-api-staging/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-api-staging/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-api-staging/resources/basic-auth.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-api-staging/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-api-staging/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-api-staging/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-api-staging/resources/versions.tf

As apart of deploying our new application we need to create the different environments for our application for testing. This PR is for creating our UAT environment with:
- Base namespace
- Service Account for CircleCI
- Basic Auth Secret

AAC-557 - Add CDAPI Staging namespace

---

namespaces/live.cloud-platform.service.justice.gov.uk/interventions-design-history/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/interventions-design-history/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/interventions-design-history/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/interventions-design-history/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/interventions-design-history/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/interventions-design-history/resources/basic-auth.tf
namespaces/live.cloud-platform.service.justice.gov.uk/interventions-design-history/resources/ecr.tf
namespaces/live.cloud-platform.service.justice.gov.uk/interventions-design-history/resources/github-repo.tf
namespaces/live.cloud-platform.service.justice.gov.uk/interventions-design-history/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/interventions-design-history/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/interventions-design-history/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/interventions-design-history/resources/versions.tf

Closed old PR for this. This new one creates the correct files!

Creating new Interventions design history

---

namespaces/live.cloud-platform.service.justice.gov.uk/jacksapp-dev/resources/route53.tf

creating a custom route 53 zone for namespace to allow custom record to
be added for application url

feat: adding new route53 zone

---

namespaces/live.cloud-platform.service.justice.gov.uk/jacksapp-dev/05-certificate.yaml

Adding a certifiacte to allow url to use new route 53 record for the
services.gov.uk

feat: Add Certificate for route53 record

---

.checksum
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-api-production/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-api-production/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-api-production/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-api-production/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-api-production/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-api-production/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-api-production/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-api-production/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-api-production/resources/versions.tf

As apart of deploying our new application we need to create the different environments for our application for testing. This PR is for creating our Production environment with:
- Base namespace
- Service Account for CircleCI

AAC-557 - Add CDA Production namespace

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-means-assessment-test/resources/rds.tf

New RDS creation for the laa-crime-means-assessment-test namespace.

Creation of new RDS resource

---

namespaces/live.cloud-platform.service.justice.gov.uk/manage-recalls-dev/10-manage-recalls-ui-dashboard.yaml

Add some pie charts showing the size of files uploaded to the MaR service

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-means-assessment-test/resources/rds.tf

Removed RDS name configuration as an RDS with this name already exists.

Fixed duplicate RDS creation

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-means-assessment-dev/05-serviceaccount-circleci.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-means-assessment-test/05-serviceaccount-circleci.yaml

Fixed missing service account creation for laa crime means assessment namespaces

Fix service account creation for means assessment namespaces

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-dev/resources/rds-instance.tf

[laa-court-data-adaptor-dev] Create Postgres 14.2 RDS instance for migration

---

.checksum
namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-dev/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-dev/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-dev/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-dev/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-dev/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-dev/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-dev/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-dev/resources/versions.tf

New namespace for VSiP back end services - dev environment.

VB-636_new_VSIP_backend_namespace

---

namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-av-mirror/05-circleci-service-account.yaml

Application will  deploy using circleci.

Added service account for circleci

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-test/resources/rds-instance.tf

[laa-court-data-adaptor-test] Create Postgres 14.2 RDS instance for migration

---

namespaces/live.cloud-platform.service.justice.gov.uk/ppud-replacement-prod/resources/legacy-ppud-api-rds.tf

One last try... This will make sure the SG is created in the same VPC as
the database - fingers crossed this will appease things.

Ensure the security group is created in the correct VPC

---

namespaces/live.cloud-platform.service.justice.gov.uk/analytical-platform-poc/resources/ecr.tf
namespaces/live.cloud-platform.service.justice.gov.uk/analytical-platform-poc/resources/serviceaccount.tf

This will allow GH actions to deploy to the poc namespace.

Add ECR repository and github action service account

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-stage/resources/rds-instance.tf

[laa-court-data-adaptor-stage]  Create Postgres 14.2 RDS instance for migration

---

namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-dev/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-dev/05-serviceaccount-circleci.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-dev/06-certificate.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-dev/07-certificate.yaml

dps-tech added to RBAC 
CircleCI service account added
Certificates for two microservices added

Visit Someone in Prison Namespace

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-events-dev/resources/book-a-prison-visit-api.tf

Add Book-a prison-visit-api project as provider

HMPPS Domain Events dev namespace

---

README.md

Reverts changes to README.md made in #7742.

Revert README.md changes

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-uat/resources/rds-instance.tf

[laa-court-data-adaptor-uat] Create Postgres 14.2 RDS instance for migration

---

namespace-resources-cli-template/resources/prototype/basic-auth.tf
namespace-resources-cli-template/resources/prototype/variables.tf

Reverts ministryofjustice/cloud-platform-environments#7624

Revert "Update basic-auth.tf"

---

namespaces/live.cloud-platform.service.justice.gov.uk/monitoring/dashboard-nodes.yaml

The labels dont exists in eks.

Update nodes dashboard to list all eks nodes without grouping.

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-staging/resources/rds.tf

This new version includes permissions for accessing database logs.

Upgrade Basm staging RDS module

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-incentives-preprod/05-serviceaccount-circleci.yaml

INC-501: Grant CircleCI permission to modify monitoring resources in `hmpps-incentives-preprod`

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-incentives-prod/05-serviceaccount-circleci.yaml

INC-501: Grant CircleCI permission to modify monitoring resources in `hmpps-incentives-prod`

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-events-dev/resources/visit-someone-in-prison-backend-svc.tf

Added new resource for posting events from visit-someone-in-prison-backend-svc-dev namespace

HMPPS Domain Events Dev

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-events-preprod/resources/pre-sentence-service-topic.tf

Add event topic for pre-sentence-service preprod

PIC-1653 - HMPPS Domain Event topic preprod

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-prod/resources/rds-instance.tf

[laa-court-data-adaptor-prod] Create Postgres 14.2 RDS instance for migration

---

.checksum
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-means-assessment-staging/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-means-assessment-staging/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-means-assessment-staging/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-means-assessment-staging/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-means-assessment-staging/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-means-assessment-staging/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-means-assessment-staging/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-means-assessment-staging/resources/versions.tf

https://dsdmoj.atlassian.net/browse/LASB-976

LASB-975| added new namespace for laa-crime-means-assessment staging

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-uat/05-prometheus.yaml

Add rules for 429 and 403 responses

LAA-Apply: Update prometheus rules for UAT

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-uat/05-prometheus.yaml

Remove the for values completely

LAA-Apply: Update UAT Prometheus rules

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-production/05-prometheus.yaml

Add new alerts for 403 and 429

LAA-Apply: Update Production Prometheus rules

---

namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-frontend-svc-preprod/06-certificate.yaml

revise dns entry including changing subdomein to "prison"

visit-someone-in-prison-frontend-svc-preprod namespace

---

namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-frontend-svc-dev/06-certificate.yaml

Revise DNS entry & correponding certificate

visit-someone-in-prison-frontend-svc-dev

---

namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-dev/06-certificate.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-dev/07-certificate.yaml

Revise cert spec to match subdomain 'prison"

visit-someone-in-prison-backend-svc-dev

---

namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-preprod/06-certificate.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-preprod/07-certificate.yaml

cert name to reference prison subdomain

visit-someone-in-prison-backend-svc-preprod

---

namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-prod/06-certificate.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-prod/07-certificate.yaml

cert spec to match subdomain "prison"

visit-someone-in-prison-backend-svc

---

.checksum
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-means-assessment-prod/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-means-assessment-prod/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-means-assessment-prod/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-means-assessment-prod/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-means-assessment-prod/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-means-assessment-prod/05-serviceaccount-circleci.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-means-assessment-prod/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-means-assessment-prod/resources/pingdom.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-means-assessment-prod/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-means-assessment-prod/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-means-assessment-prod/resources/versions.tf

This is to create a new prod namespace for the laa-crime-means-assessment service.
Namespace has been created on the live cluster using the Cloud Platform CLI.

Prod namespace for laa-crime-means-assessment application

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-events-prod/resources/pre-sentence-service-topic.tf

Add event topic for pre-sentence-service prod

PIC-1653 - HMPPS Domain Event topic prod

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-licenses-prototype/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-licenses-prototype/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-licenses-prototype/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-licenses-prototype/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-licenses-prototype/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-licenses-prototype/resources/basic-auth.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-licenses-prototype/resources/ecr.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-licenses-prototype/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-licenses-prototype/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-licenses-prototype/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-licenses-prototype/resources/versions.tf

Moving hmpps licenses prototype from heroku to cloud platform.

Hmpps licenses prototype

---

namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-monitoring/resources/pingdom.tf

[Trello](https://trello.com/c/KVv331D5/2567-add-pingdom-for-new-hmcts-forms)
Add pingdom to two forms that are live

Formbuilder: Add two forms to pingdom

---

.checksum
namespaces/live.cloud-platform.service.justice.gov.uk/chapsdotnet-dev/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/chapsdotnet-dev/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/chapsdotnet-dev/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/chapsdotnet-dev/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/chapsdotnet-dev/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/chapsdotnet-dev/resources/ecr.tf
namespaces/live.cloud-platform.service.justice.gov.uk/chapsdotnet-dev/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/chapsdotnet-dev/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/chapsdotnet-dev/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/chapsdotnet-dev/resources/versions.tf

PR to fix variable.tf file error message.

Chaps dot net

---

namespaces/live.cloud-platform.service.justice.gov.uk/cloud-platform-canary-app-eks/resources/application.tf
namespaces/live.cloud-platform.service.justice.gov.uk/cloud-platform-canary-app-eks/resources/values.yaml

Update the canary app to latest version and use the new ingress controller using the new IngressClassName field

Add new IngressClass field and update app version

---

namespaces/live.cloud-platform.service.justice.gov.uk/cloud-platform-canary-app-eks/resources/values.yaml

New Canary Release 

---

namespaces/live.cloud-platform.service.justice.gov.uk/chaps-dev/resources/serviceaccount.tf

Added requirement to pickup certificates

Added certificate requirement in serviceaccount.tf

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-uat/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-uat/resources/variables.tf

Create a separate service account for github actions to
use.

[laa-apply-for-legalaid-uat] Add serviceacount for github-actions

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-uat/resources/serviceaccount.tf

Commented out github_repositories to debug the failure

Updated laa-apply-for-legalaid-uat

---

namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-dev/prometheus-custom-alerts-ccic-dev.yaml

Update to Prometheus alert rules

Criminal-injuries-dev prometheus update

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-cla-backend-uat/resources/rds.tf

This database is no longer required because the upgrade to 10 has been successful

Remove redundant postgres9.6 database

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-uat/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-uat/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-uat/resources/versions.tf

Added missing provider block to fix the issue

This is to fix the github secrets added to repo

---

namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-dev/prometheus-custom-alerts-ccic-dev.yaml

Update prometheus alerts

---

namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-dev/prometheus-custom-alerts-ccic-dev.yaml

Add namespace to Prometheus alerts

Bug: Add namespaces to prometheus alerts

---

namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-dev/prometheus-custom-alerts-ccic-dev.yaml

Update prometheus rules

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-interventions-prod/05-serviceaccount-circleci.yaml

To make the namespace compatible with
https://github.com/ministryofjustice/hmpps-helm-charts
Similar to #7998 and #8000.

[interventions-prod] Switching to RoleBinding and enable prometheusrules

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-cla-backend-production/resources/rds.tf

Remove postgres9.6 database server
Remove postgres9.6 database replication server

Remove redundant laa-cla-backend-production postgres9.6 database

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-interventions-dev/resources/rds-onboarding.tf

Using latest postgres and instance class

Provision provider onboarding database

---

namespaces/live.cloud-platform.service.justice.gov.uk/courts-local-scorecard-dev/05-certificate.yaml

Creating certs ref. for custom domain `dev.` subs

Certs for custom dev domains

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-uat/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-uat/resources/variables.tf

In particular this adds the team name

Add all expected variables and providers

---

namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-prod/prometheus-custom-alerts-ccic-prod.yaml

Updating Prometheus alerts for prod.

Claim-criminal-injuries-comp-prod update prometheus rules

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-pin-phone-monitor-prod/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-pin-phone-monitor-qa/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/manage-soc-cases-preprod/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/manage-soc-cases-prod/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/offender-categorisation-preprod/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/offender-categorisation-prod/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/pathfinder-preprod/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/pathfinder-prod/01-rbac.yaml

Add Secure Estate Digital Team (SED) to RBAC for
- PF
- SOC
- CAT
- PCMS

[DSE 290] Add SED Team to RBAC for PF / SOC / CAT / PCMS

---

namespaces/live.cloud-platform.service.justice.gov.uk/evidencelibrary-test/APPLY_PIPELINE_SKIP_THIS_NAMESPACE

evidencelibrary-test: remove skip file.

---

namespaces/live.cloud-platform.service.justice.gov.uk/helloworldsw-dev/resources/ecr.tf
namespaces/live.cloud-platform.service.justice.gov.uk/helloworldsw-dev/resources/serviceaccount.tf

for Helm CD user guide tutorial

Add github actions secrets

---

namespaces/live.cloud-platform.service.justice.gov.uk/evidencelibrary-prod/resources/route53.tf
namespaces/live.cloud-platform.service.justice.gov.uk/evidencelibrary-prod/resources/variables.tf

Added route53 with required domain name.

evidencelibrary-prod: new domain

---

namespaces/live.cloud-platform.service.justice.gov.uk/evidencelibrary-prod/certificate.yaml

evidencelibrary-prod: added domain cert file

---

.checksum
namespaces/live.cloud-platform.service.justice.gov.uk/whilesp-sandbox/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/whilesp-sandbox/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/whilesp-sandbox/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/whilesp-sandbox/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/whilesp-sandbox/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/whilesp-sandbox/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/whilesp-sandbox/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/whilesp-sandbox/resources/versions.tf

running through the cloud platform tutorial

whilesp helloworld dev initial

---

namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-saas-live/07-prometheus.yaml

Just to make it a little easier to eyeball.

Form Builder - Update Failed Delayed Job message

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-interventions-preprod/resources/rds-onboarding.tf

Using latest postgres and instance class
Similar to #8005

[interventions-preprod] Provision provider onboarding database

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-users-dev/99-redirect_old_url_ingress.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-users-preprod/99-redirect_old_url_ingress.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-users-prod/99-redirect_old_url_ingress.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/how-out-of-date-are-we/ingress.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/licences-prod/99-redirect_old_url_ingress.yaml

This is related to:
https://github.com/ministryofjustice/cloud-platform/issues/3650
Also, move how-out-of-date-are-we to new ingress controller

Update ingress to v1 from v1beta1

---

.checksum
namespaces/live.cloud-platform.service.justice.gov.uk/hello-world-tapa-dev/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hello-world-tapa-dev/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hello-world-tapa-dev/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hello-world-tapa-dev/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hello-world-tapa-dev/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hello-world-tapa-dev/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hello-world-tapa-dev/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hello-world-tapa-dev/resources/versions.tf

Created as part of following the "Hello World" example.
https://user-guide.cloud-platform.service.justice.gov.uk/documentation/deploying-an-app/helloworld-app-deploy.html#deploying-a-39-hello-world-39-application-to-the-cloud-platform

initial hello-world-tapa commit

---

namespaces/live.cloud-platform.service.justice.gov.uk/dso-monitoring-dev/resources/cross-acct-prometheus-sa.tf

- Adding prometheus irsa for ec2 discovery.
- Commit changes made by code formatters
- Typo.
- Unique names for irsa module and output.
- Fixing role name reference and secret output.

DSO: fix irsa prometheus role policy."

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-interventions-prod/10-alerts.yaml

Alert if slow responses rate spikes up

---

namespaces/live.cloud-platform.service.justice.gov.uk/calculate-journey-variable-payments-prod/02-limitrange.yaml

Reverts ministryofjustice/cloud-platform-environments#8085

Revert "This temporary memory increase to see if we can resolve a production issue in the short term whilst coming up with a longer term solution."

---

namespaces/live.cloud-platform.service.justice.gov.uk/dso-monitoring-prod/06-certificate.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/dso-monitoring-prod/resources/cross-acct-alertmanager-sa.tf
namespaces/live.cloud-platform.service.justice.gov.uk/dso-monitoring-prod/resources/cross-acct-grafana-sa.tf
namespaces/live.cloud-platform.service.justice.gov.uk/dso-monitoring-prod/resources/cross-acct-prometheus-sa.tf
namespaces/live.cloud-platform.service.justice.gov.uk/dso-monitoring-prod/resources/variables.tf

- DSO - Adding alertmanager irsa definition.
- Adding irsa and certificate resources to dso-monitoring-prod

dso monitoring prod resources

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-production/05-prometheus.yaml

Amend the runbook to point to the confluence page
Update the rule to match the description (403, not 429)

Apply prod: Update prometheus rules

---

.checksum
namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-criminal-legal-aid-dev/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-criminal-legal-aid-dev/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-criminal-legal-aid-dev/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-criminal-legal-aid-dev/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-criminal-legal-aid-dev/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-criminal-legal-aid-dev/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-criminal-legal-aid-dev/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-criminal-legal-aid-dev/resources/versions.tf

Just basic setup after following the cli wizard thanks :)

Add LAA Apply for Criminal Legal Aid dev environment

---

.checksum
namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-criminal-legal-aid-staging/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-criminal-legal-aid-staging/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-criminal-legal-aid-staging/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-criminal-legal-aid-staging/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-criminal-legal-aid-staging/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-criminal-legal-aid-staging/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-criminal-legal-aid-staging/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-criminal-legal-aid-staging/resources/versions.tf

Just basic setup after following the cli wizard thanks :)

Add LAA Apply for Criminal Legal Aid staging environment

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-pin-phone-monitor-dev/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-pin-phone-monitor-prod/01-rbac.yaml

Add role at the bottom of the RBAC file, as GitHub action RBAC check expect role binding with subjects to the top of the file

Update hmpps-pin-phone-monitor-dev rbac file

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-criminal-legal-aid-staging/resources/rds.tf

To the namespace `laa-apply-for-criminal-legal-aid-staging`.

Add RDS instance to staging namespace

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-probation-webops-poc/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-probation-webops-poc/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-probation-webops-poc/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-probation-webops-poc/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-probation-webops-poc/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-probation-webops-poc/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-probation-webops-poc/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-probation-webops-poc/resources/versions.tf

Work item: https://dsdmoj.atlassian.net/browse/NIT-221
Following CP docs to create a namespace for our team which we plan to use for sandboxing.

nit-221-create-hmpps-probation-webops-sandbox-namespace

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-events-preprod/resources/hmpps-incentives.tf

https://dsdmoj.atlassian.net/browse/INC-479

INC-479: create queue in preprod for incentives api to subscribe to prisoner domain events

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-events-prod/resources/hmpps-incentives.tf

https://dsdmoj.atlassian.net/browse/INC-479

INC-479: create queue in prod for incentives api to subscribe to prisoner domain events

---

namespaces/live.cloud-platform.service.justice.gov.uk/helloworldsw-dev/resources/rds.tf

For prometheus app metrics guide runthrough

Add rds resource

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-means-assessment-dev/resources/messaging-queues.tf

Editing the secret name to regenerate the keys

Edit to regenerate the AWS keys

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-criminal-legal-aid-staging/resources/pingdom.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-criminal-legal-aid-staging/resources/versions.tf

Adds pingdom + slack integration to LAA Apply for Criminal Legal Aid Application

Add integration id for slack

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-licenses-prototype/resources/variables.tf

Change the user name and password for hmpps-licenses-prototype

username and password change for CVL prototype

---

.checksum
namespaces/live.cloud-platform.service.justice.gov.uk/data-eng-uploader-prod/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/data-eng-uploader-prod/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/data-eng-uploader-prod/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/data-eng-uploader-prod/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/data-eng-uploader-prod/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/data-eng-uploader-prod/resources/ecr.tf
namespaces/live.cloud-platform.service.justice.gov.uk/data-eng-uploader-prod/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/data-eng-uploader-prod/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/data-eng-uploader-prod/resources/versions.tf

Create namespace for analytical platform uploader production

Create namespace for AP Uploader production

---

namespaces/live.cloud-platform.service.justice.gov.uk/cloud-platform-canary-app-eks/resources/application.tf
namespaces/live.cloud-platform.service.justice.gov.uk/cloud-platform-canary-app-eks/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/cloud-platform-canary-app-eks/resources/pingdom.tf
namespaces/live.cloud-platform.service.justice.gov.uk/cloud-platform-canary-app-eks/resources/values.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/cloud-platform-canary-app-eks/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/cloud-platform-canary-app-eks/resources/versions.tf

Closes https://github.com/ministryofjustice/cloud-platform/issues/3958

Pingdom checks for the ingress IP addresses

---

namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-dev/prometheus-custom-alerts-ccic-dev.yaml

Claim-criminal-injuries-comepnsation-dev Add new prometheus rule

claim-criminal-injuries-comepnsation-dev Add new prometheus rule

---

namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-dev/prometheus-custom-alerts-ccic-dev.yaml

claim-criminal-injuries-compensation-dev Update prometheus rule

claim-criminal-injuries-compensation-dev Update prometheus rule

---

namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-prod/prometheus-custom-alerts-ccic-prod.yaml

claim-criminal-injuries-compensation-prod Add new prometheus rule

claim-criminal-injuries-compensation-prod Add new prometheus rule

---

namespaces/live.cloud-platform.service.justice.gov.uk/approved-premises-dev/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/approved-premises-dev/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/approved-premises-dev/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/approved-premises-dev/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/approved-premises-dev/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/approved-premises-dev/05-serviceaccount-circleci.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/approved-premises-dev/06-certificate.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/approved-premises-dev/resources/elasticache.tf
namespaces/live.cloud-platform.service.justice.gov.uk/approved-premises-dev/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/approved-premises-dev/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/approved-premises-dev/resources/versions.tf

This is my first time setting everything up for a project, but I think I've followed all the instructions in Confluence correctly. It's a fairly new project, so we're not (yet) diverting from anything that the template Typescript / Kotlin projects need. Please tell me if there's anything incorrect/missing! 👍

Initialize namespace for the Approved Premises service

---

namespaces/live.cloud-platform.service.justice.gov.uk/money-to-prisoners-prod/resources/rds.tf

MTP-1920: Increase size of production DB for prisoner money

---

namespaces/live.cloud-platform.service.justice.gov.uk/approved-premises-api-dev/resources/rds.tf

This allows us to load the URL as an environment variable for Spring

Add jdbc prefix to postgres url

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-pin-phone-monitor-dev/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/manage-soc-cases-dev/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/manage-soc-cases-prototype/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/offender-categorisation-dev/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/pathfinder-dev/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/pathfinder-prototype/resources/main.tf

**secure-estate-digital-team**
- hmpps-pin-phone-monitor-dev
- manage-soc-cases-dev
- offender-categorisation-dev
- pathfinder-dev
**secure-estate-digital-prototypes**
- manage-soc-cases-prototype
- pathfinder-prototype

[DSE-579] AWS - Add GH Teams to Dev Services and Prototypes

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-pin-phone-monitor-dev/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/manage-soc-cases-dev/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/manage-soc-cases-prototype/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/offender-categorisation-dev/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/pathfinder-dev/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/pathfinder-prototype/resources/main.tf

Reverts ministryofjustice/cloud-platform-environments#8357; breaks apply pipeline

Revert "[DSE-579] AWS - Add GH Teams to Dev Services and Prototypes"

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-pin-phone-monitor-dev/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/manage-soc-cases-dev/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/manage-soc-cases-prototype/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/offender-categorisation-dev/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/pathfinder-dev/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/pathfinder-prototype/resources/main.tf

Reverts ministryofjustice/cloud-platform-environments#8364

Revert "Revert "[DSE-579] AWS - Add GH Teams to Dev Services and Prototypes""

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-bot-production/resources/rds.tf

The service has had a skipfile created and it is acknolwedged that this
appraoch will cause a time of unavailibility, it's being done to see
what impact this will have on the services and to document for
other services the team maintain

LAA Apply Bot: Update RDS from 11 to 14

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-bot-production/resources/rds.tf

Add the allow_major_version_upgrade flag

LAA Apply-bot: Update the v14 update

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-bot-production/resources/rds.tf

Updating 11 > 14 failed, reduce the target to 13

LAA apply-bot: reduce postgres to 13

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-bot-production/resources/rds.tf

This namespace has a skip file

LAA Apply-bot: Upgrade RDS to 14

---

namespaces/live.cloud-platform.service.justice.gov.uk/data-eng-uploader-preprod/resources/serviceaccount.tf

This PR will update the service account secrets in the preprod github environment.

Add github environment name preprod

---

.checksum
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-dpr-poc-dev/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-dpr-poc-dev/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-dpr-poc-dev/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-dpr-poc-dev/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-dpr-poc-dev/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-dpr-poc-dev/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-dpr-poc-dev/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-dpr-poc-dev/resources/versions.tf

POC Namespace for Digital Prison Reporting:
- federation of NOMIS and DPR DBs
- reporting functionality
Jira Ticket https://dsdmoj.atlassian.net/browse/DPR-47

Added hmpps-dpr-poc-dev namespace for Digital Prisoner Reporting

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-dpr-poc-dev/00-namespace.yaml

Changed namespace repo to templated github repo hmpps-digital-prison-reporting-poc

Changed repo to moj templated repo hmpps-digital-prison-reporting-poc

---

.checksum
namespaces/live.cloud-platform.service.justice.gov.uk/jakemulley-development/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/jakemulley-development/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/jakemulley-development/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/jakemulley-development/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/jakemulley-development/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/jakemulley-development/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/jakemulley-development/resources/rds-mssql.tf
namespaces/live.cloud-platform.service.justice.gov.uk/jakemulley-development/resources/rds-mysql.tf
namespaces/live.cloud-platform.service.justice.gov.uk/jakemulley-development/resources/rds-postgresql.tf
namespaces/live.cloud-platform.service.justice.gov.uk/jakemulley-development/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/jakemulley-development/resources/versions.tf

This PR creates a new development namespace and 3x development databases (Postgres, MySQL, MSSQL) to test various RDS upgrade and downgrade paths.

Add development environment for jakemulley

---

namespaces/live.cloud-platform.service.justice.gov.uk/offender-management-staging/resources/rds-allocations-api.tf

psql bumped to 10.21
instance class bumped to db.t3.small which is compatible with psql v14
major version upgrade enabled

offender-management-staging: preparing for upgrade to 14

---

namespaces/live.cloud-platform.service.justice.gov.uk/parliamentary-questions-development/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/parliamentary-questions-development/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/parliamentary-questions-development/resources/versions.tf

This is for namespace "parliamentary-questions-development"

Add git provider for pq-development

---

namespaces/live.cloud-platform.service.justice.gov.uk/offender-management-preprod/resources/rds-allocations-api.tf

* Change instance class to one supported by 14.3
* Minor version upgrade to one that supports being upgraded to 14.3
* Allow major version upgrades
On-demand pricing changes from $0.206/hour to $0.211/hour.
MO-1133

offender-management-preprod: Prepare for PSQL upgrade to v14

---

namespaces/live.cloud-platform.service.justice.gov.uk/offender-management-preprod/resources/rds-allocations-api.tf

offender-management-preprod: Upgrade PG to 14.3

---

namespaces/live.cloud-platform.service.justice.gov.uk/offender-management-preprod/resources/rds-allocations-api.tf

Remove skip pipeline file
Disable major version upgrades

offender-management-preprod: RDS upgrade cleanup

---

namespaces/live.cloud-platform.service.justice.gov.uk/offender-management-production/resources/rds-allocations-api.tf

* Change instance class to one supported by 14.3
* Minor version upgraded to 10.21, as it supports being upgraded to 14.3
* Allow major version upgrades
On-demand pricing changes from $0.206/hour to $0.211/hour
MO-1133

offender-management-production: Prepare for PSQL upgrade to v14

---

namespaces/live.cloud-platform.service.justice.gov.uk/offender-management-production/resources/rds-allocations-api.tf

offender-management-production: Upgrade PG to 14.3

---

namespaces/live.cloud-platform.service.justice.gov.uk/offender-management-production/resources/rds-allocations-api.tf

Remove skip pipeline file
Disable major version upgrades
MO-1133

offender-management-production: RDS upgrade cleanup

---

README.md
namespaces/live.cloud-platform.service.justice.gov.uk/approved-premises-prototype/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/approved-premises-prototype/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/approved-premises-prototype/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/approved-premises-prototype/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/approved-premises-prototype/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/approved-premises-prototype/resources/basic-auth.tf
namespaces/live.cloud-platform.service.justice.gov.uk/approved-premises-prototype/resources/ecr.tf
namespaces/live.cloud-platform.service.justice.gov.uk/approved-premises-prototype/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/approved-premises-prototype/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/approved-premises-prototype/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/approved-premises-prototype/resources/versions.tf

We have a prototype built using the GOV.UK prototyping kit. We would like to deploy this using Cloud Platform.

Approved premises prototype

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-complexity-of-need-staging/resources/rds.tf

hmpps-complexity-of-need-staging: Prepare for PG14 upgrade

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-complexity-of-need-preprod/resources/rds.tf

hmpps-complexity-of-need-preprod: Prepare for PG14 upgrade

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-complexity-of-need-staging/resources/rds.tf

hmpps-complexity-of-need-staging: upgrade to PG14

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-complexity-of-need-preprod/resources/rds.tf

hmpps-complexity-of-need-preprod: upgrade to PG14

---

namespaces/live.cloud-platform.service.justice.gov.uk/abundant-namespace-dev/resources/elasticsearch.tf
namespaces/live.cloud-platform.service.justice.gov.uk/manage-intelligence-dev/resources/elasticsearch.tf
namespaces/live.cloud-platform.service.justice.gov.uk/peoplefinder-demo/resources/elasticsearch.tf
namespaces/live.cloud-platform.service.justice.gov.uk/peoplefinder-development/resources/elasticsearch.tf
namespaces/live.cloud-platform.service.justice.gov.uk/peoplefinder-production/resources/elasticsearch.tf
namespaces/live.cloud-platform.service.justice.gov.uk/peoplefinder-staging/resources/elasticsearch.tf
namespaces/live.cloud-platform.service.justice.gov.uk/prisoner-content-hub-development/resources/elasticsearch.tf
namespaces/live.cloud-platform.service.justice.gov.uk/prisoner-content-hub-production/resources/elasticsearch.tf
namespaces/live.cloud-platform.service.justice.gov.uk/prisoner-content-hub-staging/resources/elasticsearch.tf
namespaces/live.cloud-platform.service.justice.gov.uk/prisoner-offender-search-dev/resources/es.tf
namespaces/live.cloud-platform.service.justice.gov.uk/prisoner-offender-search-preprod/resources/es.tf
namespaces/live.cloud-platform.service.justice.gov.uk/prisoner-offender-search-prod/resources/es.tf
namespaces/live.cloud-platform.service.justice.gov.uk/probation-offender-search-dev/resources/es.tf
namespaces/live.cloud-platform.service.justice.gov.uk/probation-offender-search-preprod/resources/es.tf
namespaces/live.cloud-platform.service.justice.gov.uk/probation-offender-search-prod/resources/es.tf
namespaces/live.cloud-platform.service.justice.gov.uk/probation-offender-search-staging/resources/es.tf

https://github.com/ministryofjustice/cloud-platform-terraform-elasticsearch/pull/29

upgrade ES module

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-complexity-of-need-production/resources/rds.tf

Remove skip file & disallow major version upgrades
MO-1133

hmpps-complexity-of-need-production: Finalize DB upgrade

---

namespaces/live.cloud-platform.service.justice.gov.uk/data-eng-uploader-prod/resources/ecr.tf
namespaces/live.cloud-platform.service.justice.gov.uk/data-eng-uploader-prod/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/data-eng-uploader-prod/resources/variables.tf

This PR will add a service account in our prod namespace. It will also create github actions ECR and KUBE secrets.

Create serviceaccount for prod

---

namespaces/live.cloud-platform.service.justice.gov.uk/approved-premises-prototype/resources/ecr.tf
namespaces/live.cloud-platform.service.justice.gov.uk/approved-premises-prototype/resources/variables.tf

We had some names and teams set incorrectly, and the ecr config didn't have a repo set, which meant we couldn't deploy.

Fix Approved Premises config

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-events-dev/resources/github.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-events-dev/resources/hmpps-pre-sentence-report-queue.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-events-dev/resources/hmpps-prison-custody-status-to-delius-queue.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-events-dev/resources/hmpps-workforce-allocation-queue.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-events-dev/resources/iam-sqs-console-role.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-events-dev/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-events-dev/resources/prison-to-probation-update.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-events-dev/resources/variables.tf

Also deprecate and remove the subscription for the prison-to-probation-update queue.

PI-399 Create queue for prison-custody-status-to-delius service (dev)

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-victim-case-management-system-dev/resources/rds.tf

to make space for one restored from a snapshot

NIT-307 temporarily delete VCMS dev database

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-events-preprod/resources/github.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-events-preprod/resources/hmpps-pre-sentence-report-queue.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-events-preprod/resources/hmpps-prison-custody-status-to-delius-queue.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-events-preprod/resources/hmpps-workforce-allocation-queue.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-events-preprod/resources/iam-sqs-console-role.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-events-preprod/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-events-preprod/resources/prison-to-probation-update.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-events-preprod/resources/variables.tf

Also:
* deprecate and remove the subscription for the prison-to-probation-update queue
* tidy up sqs console policy

PI-399 Create queue for prison-custody-status-to-delius service (preprod)

---

.checksum
namespaces/live.cloud-platform.service.justice.gov.uk/laa-estimate-financial-eligibility-for-legal-aid-staging/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-estimate-financial-eligibility-for-legal-aid-staging/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-estimate-financial-eligibility-for-legal-aid-staging/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-estimate-financial-eligibility-for-legal-aid-staging/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-estimate-financial-eligibility-for-legal-aid-staging/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-estimate-financial-eligibility-for-legal-aid-staging/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-estimate-financial-eligibility-for-legal-aid-staging/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-estimate-financial-eligibility-for-legal-aid-staging/resources/versions.tf

This adds the first namespace for the new Estimate financial eligibility for Legal Aid service

Add first namespace for Estimate financial eligibility for Legal Aid

---

.checksum
namespaces/live.cloud-platform.service.justice.gov.uk/laa-estimate-financial-eligibility-for-legal-aid-uat/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-estimate-financial-eligibility-for-legal-aid-uat/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-estimate-financial-eligibility-for-legal-aid-uat/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-estimate-financial-eligibility-for-legal-aid-uat/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-estimate-financial-eligibility-for-legal-aid-uat/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-estimate-financial-eligibility-for-legal-aid-uat/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-estimate-financial-eligibility-for-legal-aid-uat/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-estimate-financial-eligibility-for-legal-aid-uat/resources/versions.tf

Create UAT environment for eligibility calculator application

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-estimate-financial-eligibility-for-legal-aid-production/resources/serviceaccount.tf

create a service account for production namespace

Create PRODUCTION service account for estimate eligibility

---

namespaces/live.cloud-platform.service.justice.gov.uk/swestest-dev/resources/elasticsearch.tf

Testing index state management via terraform

test: add es cluster

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-estimate-financial-eligibility-for-legal-aid-uat/resources/serviceaccount.tf

Add permissions to a circleci service account

add permissions for CircleCI service account

---

namespaces/live.cloud-platform.service.justice.gov.uk/paul-test/resources/elasticsearch.tf

Why:
[Figure out a way to create Index State Management policies using terraform#4068](https://app.zenhub.com/workspaces/cloud-platform-team-5ccb0b8a81f66118c983c189/issues/ministryofjustice/cloud-platform/4068)
introduce cold storage Index State Management policies using terraform

introduce-cold-storage

---

namespaces/live.cloud-platform.service.justice.gov.uk/offender-events-prod/resources/pic-probation-offender-events-sub-queue.tf

. Added offender event subscription queue for pic prod env.

PIC-2379-prod

---

namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-preprod/resources/rds.tf

This is to remove pinned minor version

User engine version as "13"

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-prod/resources/rds-instance.tf

This is to fix the error
Error: Error modifying DB Instance cloud-platform-xxxxx: InvalidParameterCombination: Cannot upgrade postgres from 14.3 to 14.2

Update rds to applied version

---

namespaces/live.cloud-platform.service.justice.gov.uk/categorisation-prototype/resources/basic-auth.tf
namespaces/live.cloud-platform.service.justice.gov.uk/categorisation-prototype/resources/variables.tf

this ensures that the password set in the kube cluster is in sync with the IaC

CAT-1155 generate random password for categorisation-prototype

---

.checksum
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-temporary-accommodation-preprod/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-temporary-accommodation-preprod/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-temporary-accommodation-preprod/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-temporary-accommodation-preprod/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-temporary-accommodation-preprod/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-temporary-accommodation-preprod/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-temporary-accommodation-preprod/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-temporary-accommodation-preprod/resources/versions.tf

This is for the CAS3 Temporary Accommodation project. The use of the https://github.com/ministryofjustice/approved-premises-ui git repo is intentional, as we will be sharing a codebase with this project

Create namespace for hmpps-temporary-accommodation-preprod

---

.checksum
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-temporary-accommodation-prod/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-temporary-accommodation-prod/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-temporary-accommodation-prod/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-temporary-accommodation-prod/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-temporary-accommodation-prod/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-temporary-accommodation-prod/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-temporary-accommodation-prod/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-temporary-accommodation-prod/resources/versions.tf

This is for the CAS3 Temporary Accommodation project. The use of the https://github.com/ministryofjustice/approved-premises-ui git repo is intentional, as we will be sharing a codebase with this project

Create namespace for hmpps-temporary-accommodation-prod

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-approved-premises-dev/06-certificates.yaml

Fixed a couple of typo / copy paste errors

Fix Certificate secret and DNS names

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-temporary-accommodation-dev/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-temporary-accommodation-dev/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-temporary-accommodation-dev/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-temporary-accommodation-dev/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-temporary-accommodation-dev/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-temporary-accommodation-dev/05-serviceaccount-circleci.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-temporary-accommodation-dev/06-certificates.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-temporary-accommodation-dev/resources/elasticache.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-temporary-accommodation-dev/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-temporary-accommodation-dev/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-temporary-accommodation-dev/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-temporary-accommodation-dev/resources/versions.tf

Temporary Accommodation and Approved Premises will share a common codebase. This PR aligns the two namespaces

Update hmpps-temporary-accommodation-dev namespace to mirror hmpps-approved-premises-dev

---

namespaces/live-2.cloud-platform.service.justice.gov.uk/cloud-platform-dev/00-namespace.yaml
namespaces/live-2.cloud-platform.service.justice.gov.uk/cloud-platform-dev/01-rbac.yaml
namespaces/live-2.cloud-platform.service.justice.gov.uk/cloud-platform-dev/02-limitrange.yaml
namespaces/live-2.cloud-platform.service.justice.gov.uk/cloud-platform-dev/03-resourcequota.yaml
namespaces/live-2.cloud-platform.service.justice.gov.uk/cloud-platform-dev/04-networkpolicy.yaml
namespaces/live-2.cloud-platform.service.justice.gov.uk/cloud-platform-dev/resources/ecr.tf
namespaces/live-2.cloud-platform.service.justice.gov.uk/cloud-platform-dev/resources/main.tf
namespaces/live-2.cloud-platform.service.justice.gov.uk/cloud-platform-dev/resources/serviceaccount.tf
namespaces/live-2.cloud-platform.service.justice.gov.uk/cloud-platform-dev/resources/variables.tf
namespaces/live-2.cloud-platform.service.justice.gov.uk/cloud-platform-dev/resources/versions.tf

Create new namespace in live-2

Create new namespace in live-2

---

namespaces/live-2.cloud-platform.service.justice.gov.uk/cloud-platform-dev/resources/variables.tf

Using vpc_name now to provider it to the modules to get vpc info

Remove cluster_name var

---

namespaces/live-2.cloud-platform.service.justice.gov.uk/cloud-platform-canary-app-eks/00-namespace.yaml
namespaces/live-2.cloud-platform.service.justice.gov.uk/cloud-platform-canary-app-eks/01-rbac.yaml
namespaces/live-2.cloud-platform.service.justice.gov.uk/cloud-platform-canary-app-eks/02-limitrange.yaml
namespaces/live-2.cloud-platform.service.justice.gov.uk/cloud-platform-canary-app-eks/03-resourcequota.yaml
namespaces/live-2.cloud-platform.service.justice.gov.uk/cloud-platform-canary-app-eks/04-networkpolicy.yaml
namespaces/live-2.cloud-platform.service.justice.gov.uk/cloud-platform-canary-app-eks/resources/application.tf
namespaces/live-2.cloud-platform.service.justice.gov.uk/cloud-platform-canary-app-eks/resources/main.tf
namespaces/live-2.cloud-platform.service.justice.gov.uk/cloud-platform-canary-app-eks/resources/pingdom.tf
namespaces/live-2.cloud-platform.service.justice.gov.uk/cloud-platform-canary-app-eks/resources/psp.tf
namespaces/live-2.cloud-platform.service.justice.gov.uk/cloud-platform-canary-app-eks/resources/values.yaml
namespaces/live-2.cloud-platform.service.justice.gov.uk/cloud-platform-canary-app-eks/resources/variables.tf
namespaces/live-2.cloud-platform.service.justice.gov.uk/cloud-platform-canary-app-eks/resources/versions.tf
namespaces/live-2.cloud-platform.service.justice.gov.uk/monitoring/dashboard-cluster-status.yaml
namespaces/live-2.cloud-platform.service.justice.gov.uk/monitoring/dashboard-datasource-rds.yaml
namespaces/live-2.cloud-platform.service.justice.gov.uk/monitoring/dashboard-datasource-redis.yaml
namespaces/live-2.cloud-platform.service.justice.gov.uk/monitoring/dashboard-datasource-sns.yaml
namespaces/live-2.cloud-platform.service.justice.gov.uk/monitoring/dashboard-datasource-sqs.yaml
namespaces/live-2.cloud-platform.service.justice.gov.uk/monitoring/dashboard-nginx-ingress.yaml
namespaces/live-2.cloud-platform.service.justice.gov.uk/monitoring/dashboard-nodes.yaml
namespaces/live-2.cloud-platform.service.justice.gov.uk/monitoring/dashboard-pods-per-node.yaml
namespaces/live-2.cloud-platform.service.justice.gov.uk/monitoring/dashboard-postgresql-exporter.yaml
namespaces/live-2.cloud-platform.service.justice.gov.uk/monitoring/dashboard-provisioning.yaml
namespaces/live-2.cloud-platform.service.justice.gov.uk/monitoring/dashboard-traffic.yaml
namespaces/live-2.cloud-platform.service.justice.gov.uk/monitoring/dashboard-velero.yaml
namespaces/live-2.cloud-platform.service.justice.gov.uk/monitoring/resources/main.tf
namespaces/live-2.cloud-platform.service.justice.gov.uk/monitoring/resources/pingdom.tf
namespaces/live-2.cloud-platform.service.justice.gov.uk/monitoring/resources/variables.tf
namespaces/live-2.cloud-platform.service.justice.gov.uk/monitoring/resources/versions.tf

This is related to:
https://github.com/ministryofjustice/cloud-platform/issues/4107

Pingdom live 2

---

.checksum
namespaces/live.cloud-platform.service.justice.gov.uk/laa-review-criminal-legal-aid-staging/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-review-criminal-legal-aid-staging/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-review-criminal-legal-aid-staging/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-review-criminal-legal-aid-staging/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-review-criminal-legal-aid-staging/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-review-criminal-legal-aid-staging/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-review-criminal-legal-aid-staging/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-review-criminal-legal-aid-staging/resources/versions.tf

Initial setup for new staging environment for LAA Crime Review application.

Create LAA Crime Review Staging namespace

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-events-dev/resources/wmt-worker.tf

Added queue for WMT worker for WFP-1388 work.

WFP-1388 added queue for wmt-worker

---

namespaces/dev-alpha.cloud-platform.service.justice.gov.uk/cloud-platform-dev/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-dev/resources/s3.tf
namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-prod/resources/s3.tf
namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-uat/resources/s3.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-approved-premises-dev/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-pin-phone-monitor-dev/resources/rds-aurora.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-pin-phone-monitor-prod/resources/rds-aurora.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-pin-phone-monitor-qa/resources/rds-aurora.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-temporary-accommodation-dev/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-temporary-accommodation-preprod/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-temporary-accommodation-prod/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-workload-preprod/resources/dms-impact-testing.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-prod/resources/rds-instance.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-means-assessment-staging/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/manage-intelligence-dev/resources/rds-aurora.tf
namespaces/live.cloud-platform.service.justice.gov.uk/ppud-replacement-dev/resources/legacy-ppud-api-dms.tf
namespaces/live.cloud-platform.service.justice.gov.uk/ppud-replacement-prod/resources/legacy-ppud-api-rds.tf

This is to the vpc info to use in the DMS module and aurora module
Also updated some RDS modules to latest version

Update modules to use the vpc_name

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-review-criminal-legal-aid-staging/resources/ecr.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-review-criminal-legal-aid-staging/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-review-criminal-legal-aid-staging/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-review-criminal-legal-aid-staging/resources/variables.tf

In addition to a service account to enable github workflows.

Create RDS and ECR resources for LAA crime review

---

.checksum
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-proceeding-dev/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-proceeding-dev/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-proceeding-dev/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-proceeding-dev/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-proceeding-dev/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-proceeding-dev/05-serviceaccount-circleci.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-proceeding-dev/resources/ecr.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-proceeding-dev/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-proceeding-dev/resources/pingdom.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-proceeding-dev/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-proceeding-dev/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-proceeding-dev/resources/versions.tf

Dev namespace for laa-crown-court-proceeding

LCAM-173-dev-namespace-laa-crown-court-proceeding

---

namespaces/live.cloud-platform.service.justice.gov.uk/monitoring/dashboard-golden-signals.yaml

https://dsdmoj.atlassian.net/browse/HEAT-14

HEAT-14: fix Golden Signals Grafana dashboard

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-events-dev/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-events-dev/resources/hmpps-activities-management.tf

Sets up a queue and dead letter queue for the HMPPS Activities management service.  Also subscribes to the HMPPS domain events topic.

SAA-84 initial draft queue config for hmpps activities management.

---

namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-repos/resources/repos.tf

This adds the ECR repo for the MoJ Forms maintenance page

MoJ Forms maintenance page ECR repo

---

.checksum
namespaces/live-2.cloud-platform.service.justice.gov.uk/poornima-dev/00-namespace.yaml
namespaces/live-2.cloud-platform.service.justice.gov.uk/poornima-dev/01-rbac.yaml
namespaces/live-2.cloud-platform.service.justice.gov.uk/poornima-dev/02-limitrange.yaml
namespaces/live-2.cloud-platform.service.justice.gov.uk/poornima-dev/03-resourcequota.yaml
namespaces/live-2.cloud-platform.service.justice.gov.uk/poornima-dev/04-networkpolicy.yaml
namespaces/live-2.cloud-platform.service.justice.gov.uk/poornima-dev/resources/main.tf
namespaces/live-2.cloud-platform.service.justice.gov.uk/poornima-dev/resources/variables.tf
namespaces/live-2.cloud-platform.service.justice.gov.uk/poornima-dev/resources/versions.tf

This is to test PRs merging to live-2 cluster

Add test namespace to live-2

---

namespaces/live.cloud-platform.service.justice.gov.uk/housing-disrepair-oss-staging/resources/ecr.tf

Bit of guesswork for the values for the GitHub repos and environments here...

Add ECR with lifecycle rules

---

.checksum
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domestic-abuse-support-officers-shared/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domestic-abuse-support-officers-shared/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domestic-abuse-support-officers-shared/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domestic-abuse-support-officers-shared/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domestic-abuse-support-officers-shared/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domestic-abuse-support-officers-shared/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domestic-abuse-support-officers-shared/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domestic-abuse-support-officers-shared/resources/versions.tf

Team work item: https://dsdmoj.atlassian.net/browse/NIT-366

Add new daso shared namespace

---

namespaces/live.cloud-platform.service.justice.gov.uk/prison-visits-booking-staging/resources/rds-prison-visits.tf

This is for prison-visits-booking-staging ns

Remove pinned version for RDS

---

.checksum
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domestic-abuse-support-officers-dev/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domestic-abuse-support-officers-dev/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domestic-abuse-support-officers-dev/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domestic-abuse-support-officers-dev/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domestic-abuse-support-officers-dev/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domestic-abuse-support-officers-dev/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domestic-abuse-support-officers-dev/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domestic-abuse-support-officers-dev/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domestic-abuse-support-officers-dev/resources/versions.tf

Team work item: https://dsdmoj.atlassian.net/browse/NIT-366

Add DASO dev environment

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domestic-abuse-support-officers-dev/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domestic-abuse-support-officers-dev/resources/redis.tf

Team work item: https://dsdmoj.atlassian.net/browse/NIT-366
Adding DB and cache to the DASO dev environment.

Add daso dev rds and redis

---

namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-dev/resources/serviceaccount.tf

Setup SA so that our GitAction can deploy into the k8s cluster.

Create Service Account and point to GitHub repo

---

namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-staging/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-staging/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-staging/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-staging/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-staging/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-staging/05-serviceaccount-circleci.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-staging/06-certificate.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-staging/07-certificate.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-staging/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-staging/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-staging/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-staging/resources/versions.tf

Visit someone in prison - new namespace for staging environment

Backend svc Staging Namespace

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-hmrc-interface-production/resources/rds.tf

We are aware this will cause downtime, and plan to merge out of hours.

Upgrade laa-hmrc-interface-prod rds instance to postgres 11

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domestic-abuse-support-officers-shared/resources/ecr.tf

Work item: https://dsdmoj.atlassian.net/browse/NIT-366
New repo to hold Artisan images that can be used in the pipeline for managing the app.

Adding Artisan repo for daso dev

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-workload-dev/resources/reductions-completed-sqs.tf

added a queue to publish to reductions completed for hmpps workload.

WFP-1427 added a queue to publish to reductions completed

---

namespaces/live.cloud-platform.service.justice.gov.uk/offender-events-dev/resources/rds.tf

- SDI-422: 🔧 Set migration instance class for offender-events-dev
- SDI-422: 🔧 Upgrade to postgres 10_21 for offender-events-dev

SDI-422: 🔧 Upgrade to postgres 10_21 for offender-events-dev

---

namespaces/live.cloud-platform.service.justice.gov.uk/offender-events-dev/resources/rds.tf

- SDI-422: 🔧 Set migration instance class for offender-events-dev
- SDI-422: 🔧 Upgrade to postgres 10_21 for offender-events-dev
- SDI-422: 🔧 Upgrade to postgres 14 for offender-events-dev

SDI-422: 🔧 Upgrade to postgres 14 for offender-events-dev

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-workload-preprod/resources/extract-placed-sqs.tf

extract publish e…vent to preprod

WFP-1425-pre-prod - added a queue to listen to NART preprod

---

namespaces/live.cloud-platform.service.justice.gov.uk/check-my-diary-dev/resources/rds.tf

- SDI-422: 🔧 Skip apply pipeline for check-my-diary-dev
- SDI-422: 🔧 Upgrade to postgres 10_21 for check-my-diary-dev

SDI-422: 🔧 Upgrade to postgres 10_21 for check-my-diary-dev

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-restricted-patients-api-dev/resources/rds.tf

- SDI-422: 🔧 Skip apply pipeline for hmpps-restricted-patients-api-dev
- SDI-422: 🔧 Upgrade to postgres 10_21 for hmpps-restricted-patients-api-dev

SDI-422: 🔧 Upgrade to postgres 10_21 for hmpps-restricted-patients-api-dev

---

namespaces/live.cloud-platform.service.justice.gov.uk/check-my-diary-dev/resources/rds.tf

- SDI-422: 🔧 Skip apply pipeline for check-my-diary-dev
- SDI-422: 🔧 Upgrade to postgres 10_21 for check-my-diary-dev
- SDI-422: 🔧 Upgrade to postgres 14 for check-my-diary-dev

SDI-422: 🔧 Upgrade to postgres 14 for check-my-diary-dev

---

namespaces/live.cloud-platform.service.justice.gov.uk/legal-framework-api-staging/resources/rds.tf

Bump LFA staging namespace from 10.21 to 11.16

legal-framework-api-staging bump postgres10 to 11

---

namespaces/live.cloud-platform.service.justice.gov.uk/check-my-diary-preprod/resources/rds.tf

- SDI-422: 🔧 Skip apply pipeline for check-my-diary-preprod
- SDI-422: 🔧 Upgrade to postgres 10_21 for check-my-diary-preprod

SDI-422: 🔧 Upgrade to postgres 10_21 for check-my-diary-preprod

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-restricted-patients-api-preprod/resources/rds.tf

- SDI-422: 🔧 Skip apply pipeline for hmpps-restricted-patients-api-preprod
- SDI-422: 🔧 Upgrade to postgres 10_21 for hmpps-restricted-patients-api-preprod

SDI-422: 🔧 Upgrade to postgres 10_21 for hmpps-restricted-patients-api-preprod

---

namespaces/live.cloud-platform.service.justice.gov.uk/offender-events-preprod/resources/rds.tf

- SDI-422: 🔧 Skip apply pipeline for offender-events-preprod
- SDI-422: 🔧 Upgrade to postgres 10_21 for offender-events-preprod

SDI-422: 🔧 Upgrade to postgres 10_21 for offender-events-preprod

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-restricted-patients-api-preprod/resources/rds.tf

- SDI-422: 🔧 Skip apply pipeline for hmpps-restricted-patients-api-preprod
- SDI-422: 🔧 Upgrade to postgres 10_21 for hmpps-restricted-patients-api-preprod
- SDI-422: 🔧 Upgrade to postgres 14 for hmpps-restricted-patients-api-preprod

SDI-422: 🔧 Upgrade to postgres 14 for hmpps-restricted-patients-api-preprod

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-education-employment-preprod/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-education-employment-preprod/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-education-employment-preprod/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-education-employment-preprod/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-education-employment-preprod/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-education-employment-preprod/05-serviceaccount-circleci.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-education-employment-preprod/06-certificate.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-education-employment-preprod/resources/elasticache.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-education-employment-preprod/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-education-employment-preprod/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-education-employment-preprod/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-education-employment-preprod/resources/versions.tf

🔧 Create new namespace for hmpps-education-employment-preprod

ESWE-445: PreProd namespace for HMPPS Education & Employment services

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-education-employment-prod/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-education-employment-prod/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-education-employment-prod/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-education-employment-prod/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-education-employment-prod/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-education-employment-prod/05-serviceaccount-circleci.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-education-employment-prod/06-certificate.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-education-employment-prod/resources/elasticache.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-education-employment-prod/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-education-employment-prod/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-education-employment-prod/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-education-employment-prod/resources/versions.tf

🔧 Create new namespace for hmpps-education-employment-prod

ESWE-446: Prod namespace for HMPPS Education & Employment services

---

namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-test-production/resources/submitter.tf

Adding new graviton RDS instance in formbuilder-platform-test-production namespace.

Form Builder - Add new submitter DB to test-production

---

namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-dev/resources/serviceaccount.tf

* Added rules in particularly to fix an error with deploying pvcs but will help with other permissions as well.

Add Service Account rules

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-api-dev/resources/rds.tf

NN-4479: upgrade hmpps-manage-adjudications-api-dev/rds to db.t3.small

---

namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-live-dev/resources/submitter.tf
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-live-dev/resources/user-datastore.tf
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-live-dev/resources/variables.tf

Adding the new RDS Graviton instances in the
formbuilder-platform-live-dev namespace

Form Builder - New RDS instances in platform live dev namespace

---

namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-live-production/resources/submitter.tf
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-live-production/resources/user-datastore.tf
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-live-production/resources/variables.tf

Adding the new RDS Graviton instances in the
formbuilder-platform-live-production namespace
xlarge instance sizes

Form Builder - New RDS instances in platform live production namespace

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-api-dev/resources/rds.tf

NN-4479: upgrade hmpps-manage-adjudications-api-dev/rds to postgres14

---

namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-publisher-test/resources/publisher.tf

Adding secret access key and access key id credentials to the Publisher RDS secret

Form Builder - Add aws credentials to RDS secret

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-api-dev/resources/rds.tf

NN-4479: disable major upgrades for hmpps-manage-adjudications-api-dev/rds

---

namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-publisher-live/resources/publisher.tf

Adding secret access key and access key id credentials to the Publisher Live RDS secret

Form Builder - Publisher Live AWS credentials to RDS secret

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-estimate-financial-eligibility-for-legal-aid-uat/resources/route53-efe.tf

...from EFE UAT Route53 config.

Remove erroneous whitespace

---

namespaces/live.cloud-platform.service.justice.gov.uk/ap-app-poc-bde/resources/ecr.tf

adding ecr to namespace for the helloworld example

add ecr to namespace

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-incentives-dev/resources/elasticache.tf

…to a newer/cheaper/faster instance.
See also #9054

Upgrade redis node type in incentives `dev` environment

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-api-preprod/resources/rds.tf

Same as https://github.com/ministryofjustice/cloud-platform-environments/pull/8986

NN-4479: set params which are currently configured for hmpps-manage-adjudications-api-preprod/rds

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-api-preprod/resources/rds.tf

NN-4479: temporarily bump hmpps-manage-adjudications-api-preprod/rds to db.t3.large

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-api-dev/resources/rds.tf

NN-4479: upgrade hmpps-manage-adjudications-api-dev/rds to db.t4g.small

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-api-preprod/resources/rds.tf

NN-4479: post upgrade changes for hmpps-manage-adjudications-api-preprod/rds

---

namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-dev/07-certificate.yaml

🔧 Add pre-sentence-service-wproofreader-dev to cert

Update certificate for wproofreader service - dev

---

namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-preprod/07-certificate.yaml

🔧 Add pre-sentence-service-wproofreader-preprod to cert

Update certificate for wproofreader service - preprod

---

namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-prod/07-certificate.yaml

🔧 Add pre-sentence-service-wproofreader to cert

Update certificate for wproofreader service - prod

---

namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-test-dev/resources/service-metadata-bucket.tf

Adding bucket to formbuilder-platform-test-dev namespace

Form Builder - Add S3 bucket for service metadata

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-workload-preprod/resources/rds-live.tf

Update db_allocated_storage to fit the snapshot size

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-estimate-financial-eligibility-for-legal-aid-uat/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-estimate-financial-eligibility-for-legal-aid-uat/resources/variables.tf

create new secrets for github actions

add github actions secrets to service account for estimate eligibility UAT

---

namespaces/live.cloud-platform.service.justice.gov.uk/prisoner-offender-search-dev/resources/es.tf

UPgrade ES dev for prisoner-search

SDI-436 Elastic Search CPU issue

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-criminal-applications-datastore-staging/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-criminal-applications-datastore-staging/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-criminal-applications-datastore-staging/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-criminal-applications-datastore-staging/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-criminal-applications-datastore-staging/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-criminal-applications-datastore-staging/resources/ecr.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-criminal-applications-datastore-staging/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-criminal-applications-datastore-staging/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-criminal-applications-datastore-staging/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-criminal-applications-datastore-staging/resources/versions.tf

Scaffolding of a new staging namespace for a new service.
Adding the ECR as well.

Add laa-criminal-applications-datastore namespace

---

namespaces/live.cloud-platform.service.justice.gov.uk/prisoner-offender-search-preprod/resources/es.tf

Increase ES instance_type size

Sdi 436 elastic search cpu issue preprod

---

namespaces/live.cloud-platform.service.justice.gov.uk/ap-app-poc-bde/resources/ecr.tf

Hi we are working on a POC  and need to  set up git secrets so we can test our pipeline to release to CP

ap-poc add repo for secrets

---

namespaces/live.cloud-platform.service.justice.gov.uk/ap-app-poc-bde/resources/ecr.tf

previous PR used incorrect parameter ths is to correct it

ap-poc use correct parameter

---

namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-staging/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-staging/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-staging/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-staging/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-staging/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-staging/resources/ecr.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-staging/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-staging/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-staging/resources/s3.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-staging/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-staging/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-staging/resources/versions.tf

Create the staging environment for our application hale-platform. This can then be integrated into our GitAction deployment. Todo, create the other two environments after this, demo and prod.

Create hale-platform staging environment

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-template-kotlin/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-template-kotlin/resources/variables.tf

https://dsdmoj.atlassian.net/browse/HEAT-16

HEAT-16: add GithubTeam to hmpps-template-kotlin

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-template-typescript/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-template-typescript/resources/variables.tf

https://dsdmoj.atlassian.net/browse/HEAT-16

HEAT-16: add GithubTeam to hmpps-template-typescript

---

namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-demo/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-demo/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-demo/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-demo/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-demo/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-demo/resources/ecr.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-demo/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-demo/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-demo/resources/s3.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-demo/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-demo/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-demo/resources/versions.tf

Setup a demo environment for showcasing new features to stakeholders.

Create demo environment for Hale Platform

---

namespaces/live.cloud-platform.service.justice.gov.uk/abundant-namespace-dev/resources/dynamodb.tf

Testing this PR:
https://github.com/ministryofjustice/cloud-platform-terraform-dynamodb-cluster/pull/20

test: IAM policy module PR for dynamodb ListTables

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-dev/resources/rds.tf

This need to be added while upgrading the RDS

Add rds_family to the replica

---

namespaces/live.cloud-platform.service.justice.gov.uk/intranet-archive-dev/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/intranet-archive-dev/resources/s3.tf

Add an S3 resource to environment

Intranet archive/add s3 resource

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-staging/resources/rds.tf

This is for namespace "hmpps-book-secure-move-api-staging"

Add rds engine version for readreplica

---

namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-demo/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-demo/resources/variables.tf

Specific to the demonstration environment.

Create specific GitAction environment variables

---

namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-dev/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-dev/resources/variables.tf

Create the variables to setup the development environment for deploying via GitActions.

Add dev specific GitAction env vars

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-events-dev/resources/hmpps-incentives.tf

https://dsdmoj.atlassian.net/browse/INC-766

INC-766: update hmpps_incentives_subscription filter for dev hmpps-domain-events-topic

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-events-preprod/resources/hmpps-incentives.tf

https://dsdmoj.atlassian.net/browse/INC-766

INC-766: update hmpps_incentives_subscription filter for preprod hmpps-domain-events-topic

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-nomis-mapping-service-dev/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-nomis-mapping-service-dev/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-nomis-mapping-service-dev/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-nomis-mapping-service-dev/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-nomis-mapping-service-dev/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-nomis-mapping-service-dev/05-serviceaccount-circleci.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-nomis-mapping-service-dev/06-certificate.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-nomis-mapping-service-dev/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-nomis-mapping-service-dev/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-nomis-mapping-service-dev/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-nomis-mapping-service-dev/resources/versions.tf

for the hmpps-nomis-visits-mapping service

SDI-396 Change domain name and namespace

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-events-preprod/resources/hmpps-incentives.tf

https://dsdmoj.atlassian.net/browse/INC-766

INC-766: correct event name for preprod hmpps_incentives_subscription

---

.checksum
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-rehabilitation-ancilliary-jitbit-dev/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-rehabilitation-ancilliary-jitbit-dev/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-rehabilitation-ancilliary-jitbit-dev/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-rehabilitation-ancilliary-jitbit-dev/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-rehabilitation-ancilliary-jitbit-dev/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-rehabilitation-ancilliary-jitbit-dev/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-rehabilitation-ancilliary-jitbit-dev/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-rehabilitation-ancilliary-jitbit-dev/resources/versions.tf

Work item: https://dsdmoj.atlassian.net/browse/NIT-427
Dev environment to test out some possibilities to host jitbit in CP.

Add new hmpps cr jitbit dev env

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-cla-backend-production/resources/rds.tf

LGA-2159: Remove Postgres 10 RDS instance.

---

namespaces/live.cloud-platform.service.justice.gov.uk/offender-events-prod/resources/whereabouts-sub-queue.tf

Keeping as draft as this change is currently blocked. More details in DCS-1869 ticket.

DCS-1869: ✨Add APPOINTMENT_CHANGED to whereabouts-sub-queue prod

---

namespaces/live.cloud-platform.service.justice.gov.uk/keyworker-api-dev/resources/rds.tf

Same as https://github.com/ministryofjustice/cloud-platform-environments/pull/8986

NN-4479: set params which are currently configured for keyworker-api-dev/rds

---

namespaces/live.cloud-platform.service.justice.gov.uk/keyworker-api-dev/resources/rds.tf

NN-4479: temporarily bump keyworker-api-dev/rds to db.t3.large

---

.checksum
namespaces/live.cloud-platform.service.justice.gov.uk/check-financial-eligibility-partner-uat/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/check-financial-eligibility-partner-uat/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/check-financial-eligibility-partner-uat/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/check-financial-eligibility-partner-uat/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/check-financial-eligibility-partner-uat/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/check-financial-eligibility-partner-uat/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/check-financial-eligibility-partner-uat/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/check-financial-eligibility-partner-uat/resources/versions.tf

Create uat namespace for CFE fork

---

namespaces/live.cloud-platform.service.justice.gov.uk/keyworker-api-dev/resources/rds.tf

NN-4479: upgrade keyworker-api-dev/rds to postgres14

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-rehabilitation-ancilliary-jitbit-dev/resources/ecr.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-rehabilitation-ancilliary-jitbit-dev/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-rehabilitation-ancilliary-jitbit-dev/resources/s3.tf

Work item: https://dsdmoj.atlassian.net/browse/NIT-427
Adding S3, RDS and ECR to jitbit dev

Add hmpps cr jitbit dev aws backing services

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-rehabilitation-ancilliary-jitbit-dev/resources/rds.tf

Work item: https://dsdmoj.atlassian.net/browse/NIT-432

Correct db param for hmpps cr jitbit dev

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-rehabilitation-ancilliary-jitbit-dev/resources/rds.tf

Work item: https://dsdmoj.atlassian.net/browse/NIT-427

Add license module to hmpps jit rds dev

---

namespaces/live.cloud-platform.service.justice.gov.uk/whereabouts-api-dev/resources/rds.tf

Same as https://github.com/ministryofjustice/cloud-platform-environments/pull/8986

NN-4479: set params which are currently configured for whereabouts-api-dev/rds

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-rehabilitation-ancilliary-jitbit-dev/resources/rds.tf

Work item: https://dsdmoj.atlassian.net/browse/NIT-427
Re-working the setup of the mssql rds for jitbit dev to ensure valid combination of engine edition, instance class and storage allocation.

Re-configure mssql rds for hmpps-jitbit-dev

---

namespaces/live.cloud-platform.service.justice.gov.uk/whereabouts-api-dev/resources/rds.tf

NN-4479: temporarily bump whereabouts-api-dev/rds to db.t3.large

---

namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-test-production/resources/service-metadata-bucket.tf

This creates a new bucket in the formbuilder-platform-test-production namespace

Formbuilder - Add S3 bucket to platform-test-production

---

namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-live-dev/resources/service-metadata-bucket.tf

This adds an S3 bucket to the formbuilder-platform-live-dev namespace

Formbuilder - Add S3 bucket to platform-live-dev

---

namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-live-production/resources/service-metadata-bucket.tf

This adds an S3 bucket to the formbuilder-platform-live-production namespace

Formbuilder - Add S3 bucket to platform-live-production

---

namespaces/live.cloud-platform.service.justice.gov.uk/make-recall-decision-dev/07-certificates.yaml

Removed old mrd functional tests config.

mrd-383_removed-old-mrd-functional-tests:

---

namespaces/live.cloud-platform.service.justice.gov.uk/whereabouts-api-dev/resources/rds.tf

NN-4479: upgrade whereabouts-api-dev/rds to postgres14

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-events-prod/resources/hmpps-incentives.tf

https://dsdmoj.atlassian.net/browse/INC-766

INC-766: update hmpps_incentives_subscription filter for prod hmpps-domain-events-topic

---

namespaces/live.cloud-platform.service.justice.gov.uk/whereabouts-api-preprod/resources/rds.tf

NN-4479: upgrade whereabouts-api-preprod/rds to postgres14

---

namespaces/live.cloud-platform.service.justice.gov.uk/check-financial-eligibility-partner-production/resources/serviceaccount.tf

add service account using cloud-platform cli tool

Add service account to CFEPartner prod

---

namespaces/live.cloud-platform.service.justice.gov.uk/keyworker-api-preprod/resources/rds.tf

NN-4479: upgrade keyworker-api-preprod-preprod/rds to postgres14

---

namespaces/live.cloud-platform.service.justice.gov.uk/keyworker-api-preprod/resources/rds.tf

NN-4479: post upgrade changes for keyworker-api-dev/preprod

---

namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-staging/resources/ecr.tf

Create secrets in staging Git Actions environment rather than global repository secrets.

Target specific GitHub environment

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-incentives-dev/resources/main.tf

https://dsdmoj.atlassian.net/browse/INC-932

INC-932: add GithubTeam to hmpps-incentives-dev

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-events-dev/resources/hmpps-incentives.tf

Changes in alerts trigger an update of the next review date.

INC-901: Subscribe to POS' `prisoner.updated` events (DEV)

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-events-preprod/resources/hmpps-incentives.tf

Changes in alerts trigger an update of the next review date.

INC-901: Subscribe to POS' prisoner.updated events (PREPROD)

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-incentives-preprod/resources/main.tf

https://dsdmoj.atlassian.net/browse/INC-932

INC-932: add GithubTeam to hmpps-incentives-preprod

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-incentives-prod/resources/main.tf

https://dsdmoj.atlassian.net/browse/INC-932

INC-932: add GithubTeam to hmpps-incentives-prod

---

namespaces/live.cloud-platform.service.justice.gov.uk/cdpt-redirect-service-dev/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/cdpt-redirect-service-dev/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/cdpt-redirect-service-dev/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/cdpt-redirect-service-dev/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/cdpt-redirect-service-dev/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/cdpt-redirect-service-dev/resources/ecr.tf
namespaces/live.cloud-platform.service.justice.gov.uk/cdpt-redirect-service-dev/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/cdpt-redirect-service-dev/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/cdpt-redirect-service-dev/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/cdpt-redirect-service-dev/resources/versions.tf

A Central Digital Product Team application to implement and test a universal redirect service.

CDPT URL Redirect Service (dev)

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-estimate-financial-eligibility-for-legal-aid-production/resources/pingdom.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-estimate-financial-eligibility-for-legal-aid-production/resources/versions.tf

Add initial Pingdom configuration (Slack integration IDs to follow) for EFE production environment

Initial Pingdom integration for LAA EFE Production

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-events-prod/resources/make-recall-decision-api.tf

mrd-285_hmpps-domain-event-config-for-mrd-api-prod: config on prod for hmpps-domain-events-topic.

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-events-preprod/resources/make-recall-decision-api.tf

mrd-285_hmpps-domain-event-config-for-mrd-api-preprod: config on preprod for hmpps-domain-events-topic.

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-events-dev/resources/make-recall-decision-api.tf

mrd-285_hmpps-domain-event-config-for-mrd-api-dev: config on dev for hmpps-domain-events-topic.

---

namespaces/live.cloud-platform.service.justice.gov.uk/intranet-archive-dev/resources/s3.tf

Adjust s3 policy

---

namespaces/live.cloud-platform.service.justice.gov.uk/disclosure-checker-staging/resources/rds.tf

Make details available to then be used when upgrading DB.

Expose Disclosure Checker Staging RDS access key and secret

---

namespaces/live.cloud-platform.service.justice.gov.uk/disclosure-checker-production/resources/rds.tf

Make details available to then be used when upgrading DB.

Expose Disclosure Checker Production RDS access key and secret

---

namespaces/live.cloud-platform.service.justice.gov.uk/disclosure-checker-staging/resources/rds.tf

- Remove skip file
- Disallow major version upgrade

Disclosure Checker Staging - DB upgrade clean up

---

namespaces/live.cloud-platform.service.justice.gov.uk/family-mediators-api-staging/resources/rds.tf

- Expose AWS keys
- Upgrade to latest minor version
- Upgrade instance class to supported type
- Add skip file

Prepare family-mediators-staging for DB upgrade

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-criminal-applications-datastore-staging/resources/dynamodb.tf

On the back of this convo:
https://mojdt.slack.com/archives/C57UPMZLY/p1669803605427189
Removed the skip file so pipeline can apply the changes.

Bump dynamodb module and declare GSI
