namespaces/non-production.k8s.integration.dsd.io/analytics-hq-dev/analytics-hq-dev-admin-role.yaml
namespaces/non-production.k8s.integration.dsd.io/cccd-dev/cccd-dev-admin-role.yaml
namespaces/non-production.k8s.integration.dsd.io/formbuilder-services-dev/formbuilder-services-dev-admin-role.yaml
namespaces/non-production.k8s.integration.dsd.io/laa-fee-calculator-dev/laa-fee-calculator-dev-admin-role.yaml
namespaces/non-production.k8s.integration.dsd.io/mps-dev/mps-dev-admin-role.yaml
namespaces/non-production.k8s.integration.dsd.io/pvbpublic-dev/pvbpublic-dev-admin-role.yaml

This PR adds additional `ClusterRole` and `ClusterRoleBinding` resources for users' team accounts, to grant them permissions to list namespaces, and to use the authorization API to check their own permission level (e.g. with `kubectl auth can-i list namespaces`).
These changes will add a new `ClusterRole` resource for each user namespace, which grants `list` on `namespaces`. As this role is at the cluster scope, and does not refer to any specific namespaces, groups or teams, it would be better to create a single role once, and bind it to each user group; however we don't currently have a defined method for creating cluster-level resources as part of cluster creation, so creating an individual role for each namespace seems simpler for now.
**To test these changes:**
Copy an existing …

Grant users permissions to list namespaces and check their own permissions

---

namespaces/cloud-platform-test-1.k8s.integration.dsd.io/monitoring/namespace.yaml

connects to https://waffle.io/ministryofjustice/cloud-platform/cards/5b226c477357e5001de038f5
New namespace for the Prometheus. Will just contain the namespace for now.

Add new namespace:monitoring on Test-1 cluster

---

namespaces/cloud-platform-test-1.k8s.integration.dsd.io/laa-fee-calculator-dev/namespace.yaml
namespaces/cloud-platform-test-1.k8s.integration.dsd.io/laa-fee-calculator-dev/serviceaccount-circleci.yaml

connects to #138
**WHAT**
- laa-fee-calculator-dev namespace 
- CircleCI Service Account for laa-fee-calculator-dev pipeline
**WHY**
Testing the laa-fee-calculator app in the test-1 cluster before promoting to live later this week. The namespace creates an environment for the app and the Service Account authenticates CircleCI with the test-1 cluster. CircleCI has access to all resources and verbs named below in the 'role' section of the Service Account.

Add laa-fee-calculator-dev namespace and serviceaccount for CircleCI

---

whichNamespace.sh

This change breaks the `build-environments` pipeline until https://github.com/ministryofjustice/cloud-platform-concourse/pull/14 is merged.

kubeconfig should be managed by the pipeline or user

---

bin/apply
namespaces/cloud-platform-test-1.k8s.integration.dsd.io/platforms-dev/resources/main.tf

Connects to https://github.com/ministryofjustice/cloud-platform/issues/74
Backend configuration is done in the `apply` script to avoid a lot of boilerplate for users and to restrict control.

Terraform backend configuration for environment resources

---

namespaces/cloud-platform-test-1.k8s.integration.dsd.io/user-roles.yaml
namespaces/non-production.k8s.integration.dsd.io/user-roles.yaml

Connects to https://github.com/ministryofjustice/cloud-platform/issues/95
The user permissions are created on the cluster scope and apply to all users. They don't need to be declared in each namespace.
The pipeline already supports global resources.

Global user RBAC manifests.

---

namespaces/cloud-platform-live-0.k8s.integration.dsd.io/digicop-development-test/00-namespace.yml
namespaces/cloud-platform-live-0.k8s.integration.dsd.io/digicop-development/digicop-development-admin-role.yaml
namespaces/cloud-platform-live-0.k8s.integration.dsd.io/digicop-test/00-namespace.yml
namespaces/cloud-platform-live-0.k8s.integration.dsd.io/digicop-test/digicop-test-admin-role.yaml

- Rename digicop-development-test --> digicop-test
- Remove opg-webops word wrongly placed in the yaml

Fix erronious team name.

---

namespaces/cloud-platform-live-0.k8s.integration.dsd.io/laa-apply-for-legalaid-production/resources/ecr.tf

New ECR repository for `laa-apply-for-legalaid-provider-frontend` docker images.

laa-apply-for-legalaid-provider-frontend ECR repo

---

bin/apply

When `terraform init` is invoked the second time it does not know what to do with the existing state file from the previous invocation.
Reference: https://concourse.apps.cloud-platform-live-0.k8s.integration.dsd.io/teams/main/pipelines/build-environments/jobs/apply/builds/1371

Terraform state files are created under resources/

---

namespace-resources/00-namespace.yaml
namespace-resources/01-rbac.yaml
namespace-resources/02-limitrange.yaml
namespace-resources/03-resourcequota.yaml

WHAT
Created a new folder with mandatory files that are required to create a new ns including new files for limitrange and resourcequota
WHY
limitrange and resourcequota are required so we can have better sizing and node utilisation.
The values are based on live-0 node sizes of c4 2xl. These will need to be adjusted when using on lower spec clusters

add ns resource folder with ns creation files

---

namespaces/cloud-platform-live-0.k8s.integration.dsd.io/logging/README.md
namespaces/cloud-platform-live-0.k8s.integration.dsd.io/logging/elasticsearch-curator.yaml
namespaces/cloud-platform-test-1.k8s.integration.dsd.io/logging/README.md
namespaces/cloud-platform-test-1.k8s.integration.dsd.io/logging/elasticsearch-curator.yaml

ministryofjustice/cloud-platform#287
**WHAT**
- A elasticsearch-curator.yaml that contains a ConfigMap and CronJob Kubernetes resource. The ConfigMap contains a python script provided by [AWS](https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/curator.html) that creates AWS credentials in `aws-platforms-integration` and deletes logs in the configured Elasticsearch cluster that are older than a month.
- The CronJob is responsible for scheduling the script to run once a day at 1am. Scheduling and log rotation is configurable in the elasticsearch-curator.yaml. 
- The elasticsearch-curator yaml has been added to the kubernetes live-0 and test-1 clusters and configured differently to delete logs from their specific elasticsearch cluster. 
- A section on …

Add Elasticsearch-Curator to `test-1` and `live-0` to rotate logs

---

namespaces/cloud-platform-live-0.k8s.integration.dsd.io/logging/elasticsearch-curator.yaml

connects to ministryofjustice/cloud-platform#287
**WHAT**
- Add elasticsearch-curator back to live-0 with exception handling
- Configure test-1 elasticsearch curator with exception handling
**WHY**
- The script fails if there aren't any logs for the curator to delete. An exception has been added to print `("index_list object is empty")` if this occurs. As most logs are not 30 days old, it is expected that this may happen for a while.

Add elasticsearch-curator to live-0 and configure test-1

---

namespaces/cloud-platform-live-0.k8s.integration.dsd.io/formbuilder-platform-dev/00-namespace.yaml
namespaces/cloud-platform-live-0.k8s.integration.dsd.io/formbuilder-platform-dev/formbuilder-platform-dev-admin-role.yaml
namespaces/cloud-platform-live-0.k8s.integration.dsd.io/formbuilder-platform-dev/publisher-workers-service-account.yaml
namespaces/cloud-platform-live-0.k8s.integration.dsd.io/formbuilder-platform-staging/00-namespace.yaml
namespaces/cloud-platform-live-0.k8s.integration.dsd.io/formbuilder-platform-staging/formbuilder-platform-staging-admin-role.yaml
namespaces/cloud-platform-live-0.k8s.integration.dsd.io/formbuilder-platform-staging/publisher-workers-service-account.yaml
namespaces/cloud-platform-live-0.k8s.integration.dsd.io/formbuilder-services-dev/00-namespace.yaml
namespaces/cloud-platform-live-0.k8s.integration.dsd.io/formbuilder-services-dev/formbuilder-services-dev-admin-role.yaml
namespaces/cloud-platform-live-0.k8s.integration.dsd.io/formbuilder-services-staging/00-namespace.yaml
namespaces/cloud-platform-live-0.k8s.integration.dsd.io/formbuilder-services-staging/formbuilder-services-staging-admin-role.yaml
namespaces/non-production.k8s.integration.dsd.io/formbuilder-platform-dev/publisher-workers-service-account.yaml
namespaces/non-production.k8s.integration.dsd.io/formbuilder-platform-staging/publisher-workers-service-account.yaml
namespaces/non-production.k8s.integration.dsd.io/formbuilder-services-dev/formbuilder-services-dev-admin-role.yaml
namespaces/non-production.k8s.integration.dsd.io/formbuilder-services-staging/formbuilder-services-staging-admin-role.yaml

We need the formbuilder-publisher app workers (which will be running as a distinct service account in the formbuilder-platform-(env) namespaces) to be able to perform k8s operations in the formbuilder-services-(env) namespaces
This PR adds:
- a distinct service account
- a RoleBinding to grant admin access to the service account
...for the dev and staging environments

add RoleBinding for FB Publisher app service account

---

namespaces/cloud-platform-live-0.k8s.integration.dsd.io/monitoring/storageClass.yaml
namespaces/cloud-platform-test-1.k8s.integration.dsd.io/monitoring/storageClass.yaml

***What***
StorageClass which defines which cloud provider we will be provisioning our volumes from and the Retain policy. This class will be used anytime you want to add an Volume to your deployment.
***Why***
In order to create PersistentVolumes for Prometheus, we needed to define a StorageClass which will be used in the VolumeClaims Template. The VolumeClaims will use this class to understand what type of Volume to provision, in this case. AWS EBS

storageClass.yaml for test-1 / live-0 cluster

---

namespaces/cloud-platform-test-1.k8s.integration.dsd.io/ingress-controllers/00-namespace.yaml
namespaces/cloud-platform-test-1.k8s.integration.dsd.io/limit-env/networkpolicy.yaml

Add test network policy to allow only ingress controllers access to limit-env namespace 
Added label name: ingress-controllers to ingress-controllers namespace

Add network policy for limit-env and add label for ingress controllers

---

namespaces/cloud-platform-live-0.k8s.integration.dsd.io/formbuilder-platform-dev/resources/main.tf

At the moment this is just an RDS instance, but there will be more once this is running (Elasticache Redis, Cloudfront distro, etc)

Add bare-minimum AWS resources for fb-publisher in dev

---

namespaces/cloud-platform-live-0.k8s.integration.dsd.io/logging/kube-fluentd-es-config.yaml
namespaces/cloud-platform-live-0.k8s.integration.dsd.io/logging/kube-fluentd-es.yaml
namespaces/cloud-platform-test-1.k8s.integration.dsd.io/logging/kube-fluentd-es-config.yaml
namespaces/cloud-platform-test-1.k8s.integration.dsd.io/logging/kube-fluentd-es.yaml

Currently fluentd is configured to connect to elasticsearch on port 80, http. We need to change that to a secured connection.

SSL connection for fluentd - live-0 / test-1

---

namespaces/cloud-platform-test-1.k8s.integration.dsd.io/logging/kube-fluentd-es-config.yaml
namespaces/cloud-platform-test-1.k8s.integration.dsd.io/logging/kube-fluentd-es.yaml

Connects to https://github.com/ministryofjustice/cloud-platform/issues/309
- `fluentd` will now tail the kubernetes audit logs
- the audit logs are sent to a dedicated ES cluster
- `fluentd` now decorates all logs with `kubernetes_cluster` since multiple kubernetes clusters can send logs to same ES cluster (eg. both `live-0` and `live-1` will send logs to the `live` ES)
Configuration for the audit logs will be part of a separate PR.

Kubernetes audit log parsing

---

docs/networkpolicy.md
namespace-resources/04-networkpolicy.yaml
namespaces/cloud-platform-live-0.k8s.integration.dsd.io/ingress-controllers/00-namespace.yaml

New default network policy created 
Network policy prohibits all traffic from one namespace to another except for ingress-controllers namespaces to all other namespaces
Added label to ingress controller NS - component=ingress-controllers
networkpolicy.md file created

Add new default Network Policy yaml file to resources folder

---

namespaces/cloud-platform-test-1.k8s.integration.dsd.io/logging/kube-fluentd-es.yaml
namespaces/cloud-platform-test-1.k8s.integration.dsd.io/priorityclasses.yaml

Starting with kubernetes 1.11.1, the default system-critical- PriorityClasses are reserved for use in kube-system only. This prevents fluentd from being deployed in the logging namespace. The two new PriorityClasses introduced by this PR are equivalent to the defaults and use the maximum priority available to custom classes.
Reference:
- https://kubernetes.io/docs/setup/release/notes/#urgent-upgrade-notes
- https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.11.md#action-required-1
Documentation on `PriorityClasses`:
- https://kubernetes.io/docs/tasks/administer-cluster/guaranteed-scheduling-critical-addon-pods/#marking-pod-as-critical-when-priorites-are-enabled
- https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/#priorityclass

Custom PriorityClasses for critical components.

---

namespaces/cloud-platform-live-0.k8s.integration.dsd.io/reference-app/00-namespace.yaml
namespaces/cloud-platform-live-0.k8s.integration.dsd.io/reference-app/01-rbac.yaml
namespaces/cloud-platform-live-0.k8s.integration.dsd.io/reference-app/02-limitrange.yaml
namespaces/cloud-platform-live-0.k8s.integration.dsd.io/reference-app/03-resourcequota.yaml

**WHAT**
- Added namespace.yaml to create my namespace on live-0.
- Added RBAC to permission my namespace.
- Added Limitrange and resource quota as per requirements.
**WHY**
Our documentation for new users requires us to reference this namespace on live-0. This will assist new users in, `namespace creation`, `application deployment` and `circle ci`.

Add reference-app namespace to the cloud-platform-live-0 cluster

---

namespaces/cloud-platform-live-0.k8s.integration.dsd.io/formbuilder-services-dev/formbuilder-services-dev-admin-role.yaml
namespaces/cloud-platform-live-0.k8s.integration.dsd.io/formbuilder-services-staging/formbuilder-services-staging-admin-role.yaml

The previous syntax did not work - the serviceaccount was not added to the RoleBinding, although the group was. This version works on local minikube, so hopefully will work on cloud-platform-live-0

Fix cross-namespace service account reference in rolebindings

---

namespaces/cloud-platform-live-0.k8s.integration.dsd.io/formbuilder-services-dev/formbuilder-services-dev-admin-role.yaml
namespaces/cloud-platform-live-0.k8s.integration.dsd.io/formbuilder-services-staging/formbuilder-services-staging-admin-role.yaml

We want the publisher workers in each of our -dev and -staging environments to be able to deploy to the services namespaces in each of -dev and -staging.
This adds RoleBinding subjects to achieve that

add -dev & -staging SAs to each group

---

namespaces/cloud-platform-test-1.k8s.integration.dsd.io/concourse-main/04-networkpolicy.yaml
namespaces/cloud-platform-test-1.k8s.integration.dsd.io/concourse/04-networkpolicy.yaml
namespaces/cloud-platform-test-1.k8s.integration.dsd.io/limit-env/04-networkpolicy.yaml
namespaces/cloud-platform-test-1.k8s.integration.dsd.io/logging/04-networkpolicy.yaml
namespaces/cloud-platform-test-1.k8s.integration.dsd.io/monitoring/04-networkpolicy.yaml
namespaces/cloud-platform-test-1.k8s.integration.dsd.io/platforms-dev/04-networkpolicy.yaml

the allow-ingress-controllers policy alone blocks traffic between pods in the same namespace

FIX allow inter-pod traffic

---

namespace-resources/04-networkpolicy.yaml

connects to https://github.com/ministryofjustice/cloud-platform/issues/342
**WHAT**
- This commit amends the 'template' network resource, adding a required default network policy. 
**WHY** 
- Before we start the process of applying this policy to live namespaces I wanted to correct the template network policy.

Amend default network policy

---

README.md

**WHAT**
--
- This PR simply removes any reference to the old namespace.py file that was used in previous iterations of the environment creation pipeline. 
**WHY**
--
- So we aren't referencing something that no longer exists.

Change README to remove reference to namespace.py

---

namespaces/cloud-platform-live-0.k8s.integration.dsd.io/logging/03-resourcequota.yaml

connects to closed ticket ministryofjustice/cloud-platform#287
**WHAT**
- Increase logging namespace resourcequota from 6000m to 12000m.
**WHY**
The elasticsearch-curator pods start everyday at 1am. Once the job is complete, the pods stay with a status of `completed`. Kubernetes by default will only keep 3 successful pods and 1 failed pod at a time. The namespace is also shared with fluentd who uses all 6 pods. After a discussion with @alkar , it was discussed to either limit elasticsearch-curator to use less than 1 CPU or to double the CPU limit. After research, limiting a cronjob's CPU did not seem configurable.

Increase logging namespace resourcequota

---

namespaces/cloud-platform-live-0.k8s.integration.dsd.io/concourse-main/04-networkpolicy.yaml
namespaces/cloud-platform-live-0.k8s.integration.dsd.io/concourse/04-networkpolicy.yaml
namespaces/cloud-platform-live-0.k8s.integration.dsd.io/digicop-development/04-networkpolicy.yaml
namespaces/cloud-platform-live-0.k8s.integration.dsd.io/formbuilder-platform-dev/04-networkpolicy.yaml
namespaces/cloud-platform-live-0.k8s.integration.dsd.io/formbuilder-platform-staging/04-networkpolicy.yaml
namespaces/cloud-platform-live-0.k8s.integration.dsd.io/formbuilder-services-dev/04-networkpolicy.yaml
namespaces/cloud-platform-live-0.k8s.integration.dsd.io/formbuilder-services-staging/04-networkpolicy.yaml
namespaces/cloud-platform-live-0.k8s.integration.dsd.io/kath-sample-dev/04-networkpolicy.yaml
namespaces/cloud-platform-live-0.k8s.integration.dsd.io/laa-apply-for-legalaid-production/04-networkpolicy.yaml
namespaces/cloud-platform-live-0.k8s.integration.dsd.io/laa-apply-for-legalaid-staging/04-networkpolicy.yaml
namespaces/cloud-platform-live-0.k8s.integration.dsd.io/laa-fee-calculator-production/04-networkpolicy.yaml
namespaces/cloud-platform-live-0.k8s.integration.dsd.io/laa-fee-calculator-staging/04-networkpolicy.yaml
namespaces/cloud-platform-live-0.k8s.integration.dsd.io/toby-myapp-dev/04-networkpolicy.yaml

connected to https://github.com/ministryofjustice/cloud-platform/issues/342
**WHAT**
- Apply default network policy to remaining namespaces in the Cloud Platform. When merged to master the network policy will be applied to the following namespaces:
**concourse-***
**digicop-***
**formbuilder-***
**kath-sample-dev**
**laa-apply-***
**laa-fee-calc***
**toby-myapp-dev**
**WHY**
- This will deny ingress traffic from anything but the ingress controllers. This has been performed on over half the namespaces currently in live-0. 
- This is the final piece of work required in: https://github.com/ministryofjustice/cloud-platform/issues/342
**NOTES**
- Testing has been completed in test-1 and is active in over half the namespaces on live-0. The default network policy will not be applied to …

Add network policy manifest to remaining namespaces

---

namespaces/cloud-platform-live-0.k8s.integration.dsd.io/formbuilder-platform-dev/resources/main.tf
namespaces/cloud-platform-live-0.k8s.integration.dsd.io/formbuilder-platform-staging/resources/main.tf

Pinned tf database resources to particular version, so that when we change the rds terraform module does not break existing resources. Pinned to V1.0 of rds terraform module.

Pinned rds to v1.0 terraform module.

---

namespaces/cloud-platform-live-0.k8s.integration.dsd.io/laa-cla-public-staging/05-serviceaccount-circleci.yaml

Creates a `ServiceAccount` role for CircleCI in the `laa-cla-public-staging` namespace.
We need this as part of https://github.com/ministryofjustice/cla_public/pull/751 to be able to deploy `cla_public` from CircleCI.

Create ServiceAccount role for CircleCI

---

bin/apply

When applying terraform for user-requested resouces, the variables `clouster_name` and `cluster_state_bucket` are now provided at runtime. This allows us to use `terraform_remote_state` in order to retrieve outputs from the cluster terraform state.
Connects to https://github.com/ministryofjustice/cloud-platform/issues/362

Introduces additional variables for terraform.

---

namespaces/cloud-platform-live-0.k8s.integration.dsd.io/concourse/04-networkpolicy.yaml
namespaces/cloud-platform-live-0.k8s.integration.dsd.io/concourse/monitoring.yaml
namespaces/cloud-platform-live-0.k8s.integration.dsd.io/monitoring/00-namespace.yaml
namespaces/cloud-platform-test-1.k8s.integration.dsd.io/monitoring/00-namespace.yaml

Metrics are already enabled. The `ServiceMonitor` and `NetworkPolicy` introduced by this PR allow prometheus to discover and scrape the metrics.

Enables concourse metrics scraping by prometheus

---

namespace-resources/02-limitrange.yaml
namespace-resources/03-resourcequota.yaml
namespace-resources/04-networkpolicy.yaml

I have added the namespace name as part of the metadata for each of the
default policies for namespaces. We need to do this to limit the
resources to that particular namespace, rather than scope them globally.

Add namespace to each policy

---

namespaces/cloud-platform-test-1.k8s.integration.dsd.io/platforms-dev/resources/main.tf

The S3 bucket module no longer accepts `bucket_identifier`. These kinds of issues should be resolved as we pin modules to specific refs.

Remove deprecated attribute.

---

namespaces/cloud-platform-live-0.k8s.integration.dsd.io/support-labelling-webhook-dev/00-namespace.yaml
namespaces/cloud-platform-live-0.k8s.integration.dsd.io/support-labelling-webhook-dev/01-rbac.yaml
namespaces/cloud-platform-live-0.k8s.integration.dsd.io/support-labelling-webhook-dev/02-limitrange.yaml
namespaces/cloud-platform-live-0.k8s.integration.dsd.io/support-labelling-webhook-dev/03-resourcequota.yaml
namespaces/cloud-platform-live-0.k8s.integration.dsd.io/support-labelling-webhook-dev/04-networkpolicy.yaml

The [support labelling webhook](https://github.com/ministryofjustice/cloud-platform-support-labelling-webhook) currently runs on Heroku. We are investigating running it on Kubernetes instead. 
This namespace is to try deploying the app on the cluster and seeing how well it works.

Add env for support labelling webhook

---

namespaces/cloud-platform-live-0.k8s.integration.dsd.io/monitoring/dsd-kibana.yaml

**What**
This will move http://elasticsearch.dsd.io/_plugin/kibana/app/kibana behind https://dsd-kibana.apps.cloud-platform-live-0.k8s.integration.dsd.io/_plugin/kibana/app/kibana, adding authentication and HTTPS
**Why**
https://github.com/ministryofjustice/cloud-platform/issues/352

authenticate DSD Kibana

---

namespaces/cloud-platform-test-1.k8s.integration.dsd.io/restricted-psp.yaml
namespaces/cloud-platform-test-1.k8s.integration.dsd.io/unrestricted-psp.yaml

connects to: https://github.com/ministryofjustice/cloud-platform/issues/203
**WHAT**
---
- First draft of the default restricted pod security policy document. This includes restrictions to:
**privileged: false** - ensures the pod cannot access any devices on the host.
**AllowPrivilegeEscalation** - Setting it to false ensures that no child process of a container can gain more privileges than its parent.
**volumes** - this allows core volumes to be used and is the recommended minimum set by Kubernetes in their docs. 
**HostPID: false** - Controls whether the pod containers can share the host process ID namespace. Note that when paired with ptrace this can be used to escalate privileges outside of the container (ptrace is forbidden by default).
**HostIPC: false** - Controls whether the pod …

Add restricted and unrestricted pod security policy to test-1 cluster

---

namespaces/cloud-platform-live-0.k8s.integration.dsd.io/support-labelling-webhook-dev/resources/main.tf

To deploy the support labelling webhook to Kubernetes I'll need an ECR
repo (that's what the docs tell me!). I've added the terraform here to
add that repo.

Add ECR for support labelling webhook

---

namespaces/cloud-platform-live-0.k8s.integration.dsd.io/jenny-myapp-dev/01-rbac.yaml

I've put this in `01-rbac.yaml` to keep all access-related config together, rather than creating a separate file for it as the docs suggest.

Set up Tiller in jenny-myapp-dev namespace

---

namespaces/cloud-platform-live-0.k8s.integration.dsd.io/laa-cla-public-production/00-namespace.yaml
namespaces/cloud-platform-live-0.k8s.integration.dsd.io/laa-cla-public-production/01-rbac.yaml
namespaces/cloud-platform-live-0.k8s.integration.dsd.io/laa-cla-public-production/02-limitrange.yaml
namespaces/cloud-platform-live-0.k8s.integration.dsd.io/laa-cla-public-production/03-resourcequota.yaml
namespaces/cloud-platform-live-0.k8s.integration.dsd.io/laa-cla-public-production/04-networkpolicy.yaml
namespaces/cloud-platform-live-0.k8s.integration.dsd.io/laa-cla-public-production/05-serviceaccount-circleci.yaml
namespaces/cloud-platform-live-0.k8s.integration.dsd.io/laa-cla-public-staging/00-namespace.yaml

This pull request creates a new namespace called `laa-cla-public-production`. It is a duplicate of `laa-cla-public-staging`.
I've also added the tags to both namespaces.

Laa cla public production

---

namespaces/cloud-platform-live-0.k8s.integration.dsd.io/monitoring/03-resourcequota.yaml

**Why**
```
6m          6m           1         prometheus-operator-d75587d6.1556679b4e14bff3         ReplicaSet               Warning   FailedCreate   replicaset-controller   Error creating: pods "prometheus-operator-d75587d6-w2tz8" is forbidden: exceeded quota: namespace-quota, requested: limits.cpu=1, used: limits.cpu=5426m, limited: limits.cpu=6
bash-3.2$ kubectl --context live-0 -n monitoring get deployments
NAME                                  DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
dsd-kibana                            1         0         0            0           7d
grafana-oauth2-proxy                  1         1         1            1           28d
kibana-proxy                          1         0         0            0           31d
kube-prometheus-exporter-kube-state …
```

raise monitoring ns limits

---

namespaces/cloud-platform-live-0.k8s.integration.dsd.io/monitoring/grafana-oauth2.yaml
namespaces/cloud-platform-live-0.k8s.integration.dsd.io/monitoring/oidc-proxy.yaml
namespaces/cloud-platform-test-1.k8s.integration.dsd.io/monitoring/grafana-oauth2.yaml
namespaces/cloud-platform-test-1.k8s.integration.dsd.io/monitoring/oidc-proxy.yaml

WHAT
Remove the webops team filter for AM, Prom and Grafana 
WHY 
In order to allow users to get useful metrics for the applications

Open up Prometheus, Alertmanager and Grafana to the org

---

namespaces/cloud-platform-live-0.k8s.integration.dsd.io/formbuilder-platform-dev/02-limitrange.yaml
namespaces/cloud-platform-live-0.k8s.integration.dsd.io/formbuilder-platform-staging/02-limitrange.yaml

..to stop pods failing to create due to hitting max _total_ limit setting

Lower default limits on formbuilder-platform-(dev|staging)

---

namespaces/cloud-platform-live-0.k8s.integration.dsd.io/ingress-controllers/04-networkpolicy.yaml
namespaces/cloud-platform-live-0.k8s.integration.dsd.io/kube-system/04-networkpolicy.yaml
namespaces/cloud-platform-test-1.k8s.integration.dsd.io/ingress-controllers/04-networkpolicy.yaml
namespaces/cloud-platform-test-1.k8s.integration.dsd.io/kube-system/04-networkpolicy.yaml

connects to https://github.com/ministryofjustice/cloud-platform/issues/371
**WHAT**
An `allow all` network policy that enables a blank network policy to be applied to the `kube-system` and `ingress-controllers` namespaces on both live-0 and test-1.
**WHY**
It has been decided that we will open these namespaces to all ingress traffic.

Add open network policy to kube-system and ingress-controllers namespace

---

namespaces/cloud-platform-live-0.k8s.integration.dsd.io/formbuilder-platform-dev/resources/submitter.tf
namespaces/cloud-platform-live-0.k8s.integration.dsd.io/formbuilder-platform-dev/submitter-workers-service-account.yml
namespaces/cloud-platform-live-0.k8s.integration.dsd.io/formbuilder-platform-staging/resources/submitter.tf
namespaces/cloud-platform-live-0.k8s.integration.dsd.io/formbuilder-platform-staging/submitter-service-account.yml

We're deploying a new FormBuilder component (fb-submitter) which needs an RDS instance, Elasticache Redis and a ServiceAccount
This PR adds the above

add RDS, Elasticache and ServiceAccount for fb-submitter

---

namespaces/cloud-platform-test-1.k8s.integration.dsd.io/monitoring/grafana-dashboard-aggregator.yaml
namespaces/cloud-platform-test-1.k8s.integration.dsd.io/monitoring/helm/kube-prometheus/values.yaml

This service aggregates user-created dashboards discovered in ConfigMaps into a single ConfigMap in the monitoring namespace that grafana has been configured to use as a source.
Connects to https://github.com/ministryofjustice/cloud-platform/issues/445

Introduce grafana-dashboard-aggregator

---

namespaces/cloud-platform-test-1.k8s.integration.dsd.io/monitoring/helm/kube-prometheus/values.yaml
namespaces/cloud-platform-test-1.k8s.integration.dsd.io/monitoring/helm/prometheus-operator/values.yaml

Also, upgrade all kube-prometheus components (only the operator is strictly required to enable `PrometheusRules`).

test-1: consume PrometheusRules from any namespace

---

namespaces/cloud-platform-live-0.k8s.integration.dsd.io/monitoring/grafana-dashboard-aggregator.yaml
namespaces/cloud-platform-test-1.k8s.integration.dsd.io/monitoring/grafana-dashboard-aggregator.yaml

Even with VIEWERS_CAN_EDIT enabled, users cannot add panels to a dashboard. This commit adds sample panels that users can then edit and copy to create their dashboards.

Add sample panels to blank dashboard

---

namespaces/cloud-platform-live-0.k8s.integration.dsd.io/support-labelling-webhook-production/00-namespace.yaml
namespaces/cloud-platform-live-0.k8s.integration.dsd.io/support-labelling-webhook-production/01-rbac.yaml
namespaces/cloud-platform-live-0.k8s.integration.dsd.io/support-labelling-webhook-production/02-limitrange.yaml
namespaces/cloud-platform-live-0.k8s.integration.dsd.io/support-labelling-webhook-production/03-resourcequota.yaml
namespaces/cloud-platform-live-0.k8s.integration.dsd.io/support-labelling-webhook-production/04-networkpolicy.yaml

The support labelling webhook currently only has a dev site (which is
essentially the live version of the webhook). This creates a prod
namespace so that in the future no one gets confused and deletes the dev
one.

Create namespace for prod version of support app

---

namespaces/cloud-platform-live-0.k8s.integration.dsd.io/steve-test-dev/00-namespace.yaml
namespaces/cloud-platform-live-0.k8s.integration.dsd.io/steve-test-dev/01-rbac.yaml
namespaces/cloud-platform-live-0.k8s.integration.dsd.io/steve-test-dev/02-limitrange.yaml
namespaces/cloud-platform-live-0.k8s.integration.dsd.io/steve-test-dev/03-resourcequota.yaml
namespaces/cloud-platform-live-0.k8s.integration.dsd.io/steve-test-dev/04-networkpolicy.yaml

This is a new namespace just to enable me to test the usage and features of the cloud platform with a dummy application.
Note the repo for the application is not prepared for Docker/Kubernetes yet.

Add Steve Lorek's test application (dev) to live cluster

---

namespaces/cloud-platform-live-0.k8s.integration.dsd.io/formbuilder-services-dev/03-resourcequota.yaml

NB. limits.memory is set to 64Gi but appears to have no effect

Increase formbuilder-services-dev requests.memory quota to 16Gi

---

namespace-resources/01-rbac.yaml
namespaces/cloud-platform-live-0.k8s.integration.dsd.io/cica-development/01-rbac.yaml

Github team names appear in lowercase in the OIDC claim. Fix for cica-development and enforce through the template.

Fix incorrect RBAC group

---

namespaces/cloud-platform-live-0.k8s.integration.dsd.io/laa-apply-for-legalaid-uat/03-resourcequota.yaml

Deployments are still failing after the previous resource increase. The limit still appears to be set to 6 uat deployments. This change should increase the number of deployments we can make simultaneously.

Add more resources to fix failing deployments

---

namespaces/cloud-platform-live-0.k8s.integration.dsd.io/pq-dev/resources/variables.tf

It is used by CircleCI as a github team name.

Update team name.

---

namespaces/cloud-platform-live-0.k8s.integration.dsd.io/formbuilder-services-dev/02-limitrange.yaml
namespaces/cloud-platform-live-0.k8s.integration.dsd.io/formbuilder-services-dev/03-resourcequota.yaml
namespaces/cloud-platform-live-0.k8s.integration.dsd.io/formbuilder-services-production/02-limitrange.yaml
namespaces/cloud-platform-live-0.k8s.integration.dsd.io/formbuilder-services-production/03-resourcequota.yaml
namespaces/cloud-platform-live-0.k8s.integration.dsd.io/formbuilder-services-staging/02-limitrange.yaml
namespaces/cloud-platform-live-0.k8s.integration.dsd.io/formbuilder-services-staging/03-resourcequota.yaml

To provide:
* Dev - 100 forms
* Staging/Production - 50 forms
Using the following limit ranges
* cpu - request: 10m, limit: 150m
* memory: - request: 128Mi, limit: 300Mi

Adjust formbuilder environment quotas

---

namespaces/cloud-platform-live-0.k8s.integration.dsd.io/laa-apply-for-legalaid-production/resources/rds.tf
namespaces/cloud-platform-live-0.k8s.integration.dsd.io/laa-apply-for-legalaid-staging/resources/rds.tf

Add /resources/rds.tf to staging and production namespaces to create RDS databases for the service.

Add rds to laa apply for legalaid staging and production

---

namespaces/cloud-platform-live-0.k8s.integration.dsd.io/offender-management-production/serviceaccount-circleci.yaml
namespaces/cloud-platform-live-0.k8s.integration.dsd.io/offender-management-staging/serviceaccount-circleci.yaml

circleci needs to be able to create ServiceMonitors

offender-management: extend circleci SA access

---

namespaces/cloud-platform-live-0.k8s.integration.dsd.io/offender-management-production/02-limitrange.yaml
namespaces/cloud-platform-live-0.k8s.integration.dsd.io/offender-management-production/03-resourcequota.yaml
namespaces/cloud-platform-live-0.k8s.integration.dsd.io/offender-management-staging/02-limitrange.yaml
namespaces/cloud-platform-live-0.k8s.integration.dsd.io/offender-management-staging/03-resourcequota.yaml

We have been experiencing an issue on staging where when we are trying
to deploy new code only 2 out of the 3 pods are successfully updated,
and means that we currently have to manually delete the 3rd pod to get
everything working properly.  Therefore we need to increase our
resource limit to avoid this issue moving forward.

Increase resource limit for OMIC prod & staging

---

namespaces/cloud-platform-live-0.k8s.integration.dsd.io/c100-application-staging/resources/rds_instance.tf
namespaces/cloud-platform-live-0.k8s.integration.dsd.io/c100-application-staging/resources/redis.tf
namespaces/cloud-platform-live-0.k8s.integration.dsd.io/formbuilder-platform-dev/resources/publisher.tf
namespaces/cloud-platform-live-0.k8s.integration.dsd.io/formbuilder-platform-dev/resources/submitter.tf
namespaces/cloud-platform-live-0.k8s.integration.dsd.io/formbuilder-platform-dev/resources/user-datastore.tf
namespaces/cloud-platform-live-0.k8s.integration.dsd.io/formbuilder-platform-test-dev/resources/variables.tf

This allows us to run the latest terraform version (0.11.11)
See https://github.com/ministryofjustice/cloud-platform-terraform-rds-instance/pull/9/commits/4ef00b926bc0e5c651201fbca249356b674d8391

Upgrade cloud-platform-terraform module versions

---

namespaces/cloud-platform-live-0.k8s.integration.dsd.io/offender-management-production/resources/main.tf
namespaces/cloud-platform-live-0.k8s.integration.dsd.io/offender-management-production/resources/rds-allocations-api.tf
namespaces/cloud-platform-live-0.k8s.integration.dsd.io/offender-management-staging/resources/ecr-allocation-manager.tf
namespaces/cloud-platform-live-0.k8s.integration.dsd.io/offender-management-staging/resources/main.tf

This means that these are clearly defined once per namespace, rather than
being in files for other specific resources.
[As suggested](https://github.com/ministryofjustice/cloud-platform-environments/pull/340#issuecomment-454874137) by @razvan-moj

Move backend and AWS region to main.tf for 2 namespaces

---

namespaces/cloud-platform-live-0.k8s.integration.dsd.io/monitoring/grafana-dashboard-aggregator.yaml

Previously, it was struggling to complete requests and getting killed ofter. This chang makes it more responsive and
allows it to complete the aggregation.

Adjust resources on grafana-dashboard-aggregator

---

namespaces/cloud-platform-live-0.k8s.integration.dsd.io/adrian-sample-app-dev/resources/ecr.tf

I'm testing the instructions for setting up an app in advance of
running a practical with the LAA developers.

Add ECR repository for adrian-sample-app-dev

---

namespaces/cloud-platform-live-0.k8s.integration.dsd.io/monitoring/dashboard-nginx-ingress.yaml
namespaces/cloud-platform-live-0.k8s.integration.dsd.io/monitoring/dashboard-nodes.yaml
namespaces/cloud-platform-live-0.k8s.integration.dsd.io/monitoring/dashboard-traffic.yaml

The new dashboards are:
* nginx-ingress requests
* nginx-ingress traffic per ingress
* kubernetes nodes (based on the one provided by kube-prometheus)
Dashboard are already present in grafana

Add new grafana dashboards

---

namespaces/cloud-platform-live-0.k8s.integration.dsd.io/laa-cla-public-production/05-serviceaccount-circleci.yaml
namespaces/cloud-platform-live-0.k8s.integration.dsd.io/laa-cla-public-staging/05-serviceaccount-circleci.yaml

This is required so that circleci is able to push up configmaps for the grafana dashboards

Add configmaps access to circleci role for laa-cla-public namespaces

---

namespaces/cloud-platform-live-0.k8s.integration.dsd.io/cccd-dev/01-rbac.yaml

Replace github prefix on team name
This was accidentally deleted when the team name was replaced

Update CCCD namespace

---

namespaces/cloud-platform-live-0.k8s.integration.dsd.io/laa-cla-public-production/02-limitrange.yaml

Our monitoring identified that our maximum memory usage for these pods was 126MiB since Christmas Eve 2018.
Similarly, our highest CPU spike was 59 millicpu.
We propose to scale memory down to 512Mi and CPU down to 250m. This will give us 24 pods to scale up, if necessary.

LGA-288: Reduce default cla-public production limits

---

namespaces/cloud-platform-live-0.k8s.integration.dsd.io/offender-management-production/resources/rds-allocations-api.tf
namespaces/cloud-platform-live-0.k8s.integration.dsd.io/offender-management-staging/resources/rds-allocations-api.tf

- This PR creates new 'POSTGRES...' env vars that point to AWS Relation Database service. Using 'POSTGRES...' will bring about greater consistency across the Offender Management Allocation API application.
- Once connection to the database via the new env vars is made, then a follow up PR will be raised to remove unused database env vars.

Create new 'POSTGRES...' env vars that point to AWS Relation Database

---

docs/running-the-pipeline-locally.md

This will come in handy in case we experience issues with Concourse again.

Add instructions on running the pipeline locally

---

namespaces/cloud-platform-live-0.k8s.integration.dsd.io/laa-great-ideas-staging/resources/main.tf

We only need one ECR repo, and the namespace can access the existing
repo without the secret.

Remove ECR and secret

---

namespaces/cloud-platform-live-0.k8s.integration.dsd.io/logging/elasticsearch-curator.yaml

Instead of building on the curator library, we can just use the command line tool. It should make this a bit easier to
understand and modify in the future.

Revisit elasticsearch-curator

---

namespaces/cloud-platform-live-0.k8s.integration.dsd.io/laa-fala-production/05-serviceaccount-circleci.yaml
namespaces/cloud-platform-live-0.k8s.integration.dsd.io/laa-fala-staging/05-serviceaccount-circleci.yaml

This is required so that circleci is able to push up configmaps for the grafana dashboards

Add configmaps access to circleci role for laa-fala namespaces

---

namespaces/cloud-platform-live-0.k8s.integration.dsd.io/monitoring/03-resourcequota.yaml

This brings limits and requests to the same level. We need to increase the requests so that we can allocate more
memory to prometheus, however, we do not really have a lot of burstable pods in this namespace so it makes sense to just
equalise the two values.

Increase ResourceQuota requests for monitoring

---

namespaces/cloud-platform-live-0.k8s.integration.dsd.io/laa-apply-for-legalaid-production/resources/rds.tf
namespaces/cloud-platform-live-0.k8s.integration.dsd.io/laa-apply-for-legalaid-staging/resources/rds.tf

This is currently at 10.6 but the manifest shows 10.5. This commit will align both together and allow the pipeline to complete successfully. Please see build logs for more information: https://concourse.apps.cloud-platform-live-0.k8s.integration.dsd.io/teams/main/pipelines/build-environments/jobs/apply/builds/20598

Align actual RDS version with manifest

---

namespaces/cloud-platform-live-0.k8s.integration.dsd.io/laa-great-ideas-staging/resources/main.tf
namespaces/cloud-platform-live-0.k8s.integration.dsd.io/laa-great-ideas-uat/resources/main.tf

This is currently at 10.6 but the manifest shows 10.5. This commit will align both together and allow the pipeline to complete successfully. Please see build logs for more information: https://concourse.apps.cloud-platform-live-0.k8s.integration.dsd.io/teams/main/pipelines/build-environments/jobs/apply/builds/20698

Align manifest with RDS version

---

namespaces/cloud-platform-live-0.k8s.integration.dsd.io/offender-management-production/resources/rds-allocations-api.tf

To match the RDS version in live we have removed the minor version pin. This will follow the module best practice.

Remove RDS minor version

---

namespaces/cloud-platform-live-0.k8s.integration.dsd.io/dummy-app-dev/resources/ecr.tf

Renamed ECR to avoid conflict, from dummy-app to dummy-app-mourad

 Renamed ECR to avoid conflict

---

namespaces/cloud-platform-live-0.k8s.integration.dsd.io/dummy-app-dev/01-rbac.yaml

I followed the documentation and added account and rolebinding to the dummy-app-dev namespace. 
This should allow me to deploy to this namespace with Helm.

Added service account and rolebinding to the dummy-app-dev namespace

---

bin/plan

Exported branch and master Shas while running plan pipeline, this change is to pick those Shas and use it in the git diff so it can check all the commits in the PR raised.

fix to use shas instead of using branch while doing git diff

---

namespaces/cloud-platform-live-0.k8s.integration.dsd.io/offender-management-production/resources/elasticache.cf
namespaces/cloud-platform-live-0.k8s.integration.dsd.io/offender-management-production/resources/variables.tf
namespaces/cloud-platform-live-0.k8s.integration.dsd.io/offender-management-staging/resources/elasticache.tf
namespaces/cloud-platform-live-0.k8s.integration.dsd.io/offender-management-staging/resources/variables.tf

Adds elasticache to both the staging and production environment for the offender-management-allocation service.

Create Elasticache instance for offender-management

---

namespaces/cloud-platform-live-0.k8s.integration.dsd.io/logging/elasticsearch-curator.yaml

This changes the age filter to use the date from the index name, which produces the expected result.
See the documentation for more detail: https://www.elastic.co/guide/en/elasticsearch/client/curator/current/filtertype_age.html

Change elasticsearch-curator filters

---

namespaces/cloud-platform-live-0.k8s.integration.dsd.io/prison-visits-booking-staging/serviceaccount-circleci.yaml

CircleCI is not allowed to deploy Kubernetes cronjobs and is sad 😭 
Let CircleCi deploy cronjobs
```
"./deploy/staging/cronjob.yaml": cronjobs.batch "delete-load-test-data" is forbidden: User "system:serviceaccount:prison-visits-booking-staging:circleci" cannot get cronjobs.batch in the namespace "prison-visits-booking-staging"
```

Prison Visits Booking Allow CircleCI to deploy Kubernetes cron jobs

---

namespaces/cloud-platform-live-0.k8s.integration.dsd.io/ingress-controllers/02-limitrange.yaml
namespaces/cloud-platform-live-0.k8s.integration.dsd.io/ingress-controllers/03-resourcequota.yaml

**Why**
https://grafana.apps.cloud-platform-live-0.k8s.integration.dsd.io/d/6581e46e4e5c7ba40a07646395ef7b23/k8s-compute-resources-pod?refresh=10s&orgId=1&var-datasource=Prometheus&var-namespace=ingress-controllers shows high res usage for both RAM&CPU

increase ingress limits

---

namespaces/cloud-platform-live-0.k8s.integration.dsd.io/kube-ops/deployment.yaml

This PR is to bump up the kube-ops image version from v0.8.1 to v0.10

Bump up the image version from v0.8.1 to v0.10

---

namespaces/cloud-platform-live-0.k8s.integration.dsd.io/money-to-prisoners-prod/05-service-account.yaml
namespaces/cloud-platform-live-0.k8s.integration.dsd.io/money-to-prisoners-prod/README.md
namespaces/cloud-platform-live-0.k8s.integration.dsd.io/money-to-prisoners-test/05-service-account.yaml

the idea is to allow pods to use the k8s api to determine what other pods/replicas exists

Add pod-internal service accounts for money-to-prisoners

---

namespaces/cloud-platform-live-0.k8s.integration.dsd.io/offender-management-production/serviceaccount-circleci.yaml
namespaces/cloud-platform-live-0.k8s.integration.dsd.io/offender-management-staging/serviceaccount-circleci.yaml

Allow CircleCI to deploy config maps for Offender Manager Staging & Production

CircleCi Permissions - config maps

---

namespaces/cloud-platform-live-0.k8s.integration.dsd.io/cccd-staging/resources/rds.tf

Using the cloud-platform-multi-container-demo-app configuration referenced  [here](https://github.com/ministryofjustice/cloud-platform-multi-container-demo-app/blob/5956b7588fba07bcbaabfeca12a453fe8198c056/kubernetes_deploy/rails-app-deployment.yaml#L22) and defined [here](https://github.com/ministryofjustice/cloud-platform-environments/blob/master/namespaces/cloud-platform-live-0.k8s.integration.dsd.io/davids-dummy-dev/resources/multicontainer-demo-app-rds.tf#L36)

Add compiled postgres url to cccd-staging

---

namespaces/cloud-platform-live-0.k8s.integration.dsd.io/authorized-keys-provider/provider.yaml
namespaces/cloud-platform-live-0.k8s.integration.dsd.io/authorized-keys-provider/resources/s3.tf

Although the Pod generally does not use a lot of resources (see requests), it will need to spike when it starts up and
installs a number of dependencies (see limits).

Update resource definitions for authorized-keys-provider

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/fj-cait-production/00-namespace.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/fj-cait-production/01-rbac.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/fj-cait-production/02-limitrange.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/fj-cait-production/03-resourcequota.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/fj-cait-production/04-networkpolicy.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/fj-cait-production/serviceaccount-circleci.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/fj-cait-staging/00-namespace.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/fj-cait-staging/01-rbac.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/fj-cait-staging/02-limitrange.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/fj-cait-staging/03-resourcequota.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/fj-cait-staging/04-networkpolicy.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/fj-cait-staging/resources/ecr.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/fj-cait-staging/resources/main.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/fj-cait-staging/resources/variables.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/fj-cait-staging/serviceaccount-circleci.yaml

Basically copy/paste from what we already had on `live-0`, but changing the `aws_region` to be `eu-west-2`.
This service doesn't have a database, so the only resource needed is the ECR repo (created once, on staging namespace).
If there is anything else required, please let us know.

Add CAIT namespaces to live-1 cluster

---

namespaces/cloud-platform-live-0.k8s.integration.dsd.io/laa-apply-for-legalaid-uat/03-resourcequota.yaml

Each PR our team create boots its own UAT env and so we are struggling to stay within the quota at the moment

Increase limits.memory quota for laa-apply-for-legalaid-uat

---

namespaces/cloud-platform-live-0.k8s.integration.dsd.io/vv-myapp-dev/00-namespace.yaml

This PR is to correct annotations in environments repo, updated business-unit for vv-myapp-dev to cloud-platform-test as all application monitoring for CP team is based on using the cloud_platform_justice_gov_uk_business_unit="cloud-platform" annotation.

Updated business-unit for vv-myapp-dev

---

bin/check-inconsistent-state

Since we removed the cluster loop, the continue statement is invalid. See the plan & apply scripts for another example.

Fix wrong continue statement in the check script

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/family-mediators-api-production/00-namespace.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/family-mediators-api-production/01-rbac.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/family-mediators-api-production/02-limitrange.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/family-mediators-api-production/03-resourcequota.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/family-mediators-api-production/04-networkpolicy.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/family-mediators-api-production/resources/main.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/family-mediators-api-production/resources/rds.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/family-mediators-api-production/resources/variables.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/family-mediators-api-production/serviceaccount-circleci.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/family-mediators-api-staging/00-namespace.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/family-mediators-api-staging/01-rbac.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/family-mediators-api-staging/02-limitrange.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/family-mediators-api-staging/03-resourcequota.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/family-mediators-api-staging/04-networkpolicy.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/family-mediators-api-staging/resources/ecr.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/family-mediators-api-staging/resources/main.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/family-mediators-api-staging/resources/rds.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/family-mediators-api-staging/resources/variables.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/family-mediators-api-staging/serviceaccount-circleci.yaml

Only AWS resources are ECR and RDS, both now on `eu-west-2` zone.
Using latest versions of the terraform modules.

Add Family Mediators API namespaces to live-1 cluster

---

namespace-resources/main.tf
namespace-resources/variables.tf

This PR when merged will make changes to the `namespace-resources` Terraform so that the environment generation files are now inserted into the `live-1.cloud-platform.service.justice.gov.uk` dir.

Switched env creation dir to live-1 and removed cluster var

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/monitoring/kibana-oauth2-proxy.yaml

**Why**
We don't want the main monitoring/login page address to change when we switch clusters

shorter kibana ingress

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-dev/resources/ecr.tf

We are trying to standardise tour internal naming convention and these had diverged

Update the ecr credentials for cccd-dev

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/david-helloworld-demo-dev/resources/rds.tf

This will be the datastore for a demo deployment of the multi-
container demo application, as per the walkthrough in the user
guide.

Add an RDS instance for multi-container-demo app.

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/david-helloworld-demo-dev/resources/rds.tf

Instead of the RDS kubernetes secret providing the individual
DB name, username, password etc. Export a 'url' value containing
the complete string that the application can use to connect to the
database.

Export complete DB URL from RDS module

---

namespaces/cloud-platform-live-0.k8s.integration.dsd.io/formbuilder-platform-test-dev/01-rbac.yaml

- the service account already has access to out service namespace which we use to fetch info.
- we want to do the same but for platform namespace too

formbuilder. add service account to role

---

namespaces/cloud-platform-live-0.k8s.integration.dsd.io/monitoring/resources/main.tf
namespaces/cloud-platform-live-0.k8s.integration.dsd.io/monitoring/resources/pingdom.tf

**Overview**
At the moment the `monitoring` namespace doesn't have a Terraform backend. This means the state is stored locally, causing duplicate results of newly created resources. 
This PR adds a `main.tf` to the `monitoring` namespace and moves the pingdom provider from `pingdom.tf` to `main.tf`

Pingdom Terraform state backend

---

namespaces/cloud-platform-live-0.k8s.integration.dsd.io/laa-legal-adviser-api-staging/resources/ecr.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-legal-adviser-api-staging/resources/ecr.tf

This ecr.tf is just a copy of the one that's in the staging namespace on live-0
I know it won't need to go in more than one namespace dir in the end, but I thought it best to add it to this dir as we're going to be cleaning the live-0 one up soon, but apologies if I've misunderstood.

Add ecr to new laa-legal-adviser-api namespace

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-platform-test-dev/resources/user-filestore.tf

previously using 2.0 which defaults to eu-west-1
now using 3.0 which defaults to eu-west-2
on a sidenote it looks like my previous commit broke the pipeline
```
* module.user-filestore-s3-bucket.aws_s3_bucket.bucket: configuration for module.user-filestore-s3-bucket.provider.aws.destination is not present; a provider configuration block is required for all operations
````
I'm hoping this will fix it?

add formbuilder bucket

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/umar-dev/resources/ecr.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/umar-dev/resources/rds.tf

Didn't realise these were meant to be GitHub team names! Fixed!

Fix the team names

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/rds-test/resources/main.tf

**WHY**
This will increase the size of the RDS storage, and test the apply_immediately variable.

increased rds storage size

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/live0-to-live1/00-namespace.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/live0-to-live1/01-rbac.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/live0-to-live1/02-limitrange.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/live0-to-live1/03-resourcequota.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/live0-to-live1/04-networkpolicy.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/live0-to-live1/05-serviceaccount-circleci.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/live0-to-live1/resources/ecr.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/live0-to-live1/resources/elasticache.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/live0-to-live1/resources/main.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/live0-to-live1/resources/rds-live0.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/live0-to-live1/resources/s3.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/live0-to-live1/resources/variables.tf

This is to test migration from live0 to live1 #779
Updated modules to use the latest version.

Migration of namespace: live0_to_live1 in to live1 cluster

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/rds-test/resources/main.tf

**WHY**
To increase the RDS storage size after the 6-hour wait limitation.

increase rds storage size

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-services-integration-dev/certificate.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-services-integration-staging/certificate.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-services-live-dev/certificate.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-services-live-staging/certificate.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-services-test-dev/certificate.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-services-test-staging/certificate.yaml

we were planning on having one wildcard certificate for multiple (three) namespaces. however ingresses in different namespaces could not access the shared certificate. instead we have decided to give each of the 9 environments there own wildcard certificate.

formbuilder: add wildcard certs, one for each env

---

.github/slack.workflow

This change will enable us to remove standard and noisy github integration with slack, and replace it with targeted information about the actions.

Enable GH action on PRs

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-get-access-service-improvement/00-namespace.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-get-access-service-improvement/01-rbac.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-get-access-service-improvement/02-limitrange.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-get-access-service-improvement/03-resourcequota.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-get-access-service-improvement/04-networkpolicy.yaml

We plan to use this namespace to store team-related artefacts (mainly secrets) and helper applications used for day-to-day development and support.
cc @ministryofjustice/laa-get-access-service-improvement

Add LAA Service Improvement team namespace

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/money-to-prisoners-prod/02-limitrange.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/money-to-prisoners-prod/04-networkpolicy.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/money-to-prisoners-prod/05-service-account.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/money-to-prisoners-prod/resources/ecr.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/money-to-prisoners-prod/resources/main.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/money-to-prisoners-test/02-limitrange.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/money-to-prisoners-test/04-networkpolicy.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/money-to-prisoners-test/05-service-account.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/money-to-prisoners-test/resources/main.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/money-to-prisoners-test/resources/rds.tf

and disable ECR lifecycle policy
c.f. [Issue 839](https://github.com/ministryofjustice/cloud-platform/issues/839)

Update money-to-prisoners namespaces with latest terraform resource versions

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/rds-test/resources/main.tf

The current pipeline breaks if no manifest files are left in the directory.
Related to #734 
See https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/build-environments/jobs/apply-live-1/builds/2180

Remove rds-test resources

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/prison-visits-booking-staging/resources/rds-prison-visits.tf

Following a discussion with CP we are going to upgrade Postgres 9.6 on
staging and experiment/test both migrating the data from the current db
& upgrading the version as Postgres 9.4 stops being supported early next
year.

Upgrade PVB RDS Postgres to 9.6

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/logging/elasticsearch-curator.yaml

**Overview**
This PR will (when merged) create a cronjob on live-1 that will cleanup elasticsearch indices in live-1 older than 30 days.

Add elasticsearch-curator cronjob to live-1

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-legal-adviser-api-staging/resources/rds.tf

Given that they're within an `rds` secret, these data keys make more sense to us when consuming them during our deployment

Rename keys in laalaa rds secret data

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-legal-adviser-api-staging/resources/rds.tf

Apologies. Think I need the postgis protocol, so that `dj-database-url` correctly sets the database engine type when we configure the app

Change laalaa database url to use postgis://

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/logging/elasticsearch-curator.yaml

When `curator_cli` has nothing to delete, it exits with an error and so the second invocation fails to run.

Update elasticsearch-curator command

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/c100-application-metabase/00-namespace.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/c100-application-metabase/01-rbac.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/c100-application-metabase/02-limitrange.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/c100-application-metabase/03-resourcequota.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/c100-application-metabase/04-networkpolicy.yaml

This namespace doesn't require any AWS resources (rds, s3, etc.) and also it doesn't require for now CircleCI.

Namespace definition for C100 metabase

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-dev/01-rbac.yaml

This is not used yet, we still use basic k8s
When we need Helm/Tiller this can be re-added

Remove tiller from cccd-dev

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/monitoring/kibana-audit-oauth2-proxy.yaml

Currently, there's no easy way to access it.
Depends on https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/272

Define an oauth2 proxy for the live-1 audit kibana

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/court-probation-dev/00-namespace.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/court-probation-dev/01-rbac.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/court-probation-dev/02-limitrange.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/court-probation-dev/03-resourcequota.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/court-probation-dev/04-networkpolicy.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/court-probation-dev/resources/ecr.tf

copy from live0 with a couple of minor changes
- improve ecr repo names and use 3.3 of module
- Increase resources limit due to our image processing service require a lot of memory/cpu

Migrate court probation to live1

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-staging/resources/rds.tf

The environment name was left in the metadata name by mistake

Update cccd-staging rds name

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-get-access-service-improvement/01-rbac.yaml

The @ministryofjustice/laa-get-access-data-and-reporting team has been created recently and the resources in this namespace will be shared between these two teams.
The intention of this pull request is to assign the admin role to both of these GitHub teams.

Expand namespace to another Get Access team

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/parliamentary-questions-development/resources/rds.tf

Updated db name to match the requirement for parliamentary-questions-dev namespace
As the pipeline is failing to create the RDS

Updated db name to match the requirement for parliamentary-questions

---

.github/main.workflow

Unfortunately github does not detect workflows with different than default names.

Rename workflow to main.workflow

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-staging/resources/messaging.tf

This allows the queue and topic to be created before allowing
the topic to post to the queue
This could not be done in a single step as terraform
did not like setting a variable while creating it.
See https://www.terraform.io/docs/providers/aws/r/sqs_queue_policy.html

CCCD Staging: Split SQS policy into separate step

---

bin/plan

The first 'attribute line' after a resource begins with `^[[0m` (a control character) so we need to account for that as well.
Connects to https://github.com/ministryofjustice/cloud-platform/issues/1004

Refine terraform plan censoring regex

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-api-sandbox/resources/main.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-api-sandbox/resources/rds.tf

To add postgres DB and Use latest ref and current (i.e. production) cccd db engine version.

Add rds instance terraform for cccd-api-sandbox

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-api-sandbox/resources/rds.tf

This is to enable using postgres
db_engine_version 9.6 in line with
current production db

Switch to use rds ref 4.3

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-api-sandbox/02-limitrange.yaml

The terraform template defaults were insufficient
and resulted in the unicorn server performing
SIGKILL, restarting the pod, when performing
even mundane tasks on the box - like `rake db:version`.

Increase default cpu and memory for cccd-api-sandbox

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-platform-test-dev/circleci-service-account.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-platform-test-production/circleci-service-account.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-platform-test-staging/circleci-service-account.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-repos/serviceaccount-circleci.yaml

This allows CircleCI to push docker images to our ECR and deploy those images to kubernetes to our test environments

Formbuilder circleci deployment

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/pecs-move-platform-backend-staging/resources/ecr.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/pecs-move-platform-backend-staging/resources/main.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/pecs-move-platform-backend-staging/resources/rds.tf

It was brought to my attention that terraform plan was failing on the removal of the `pecs-move-platform-backend-staging`. Adding the commits in this PR will fix this and allow plan (and subsequently merge to master) to complete successfully.

Fixing broken Terraform plan 

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-staging/resources/main.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-staging/resources/variables.tf

This was causing the pipeline to wait forever for input, since it
couldn't resolve the variables at runtime.

Replace variables w. hard-coded values in main.tf

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/disclosure-checker-staging/resources/ecr.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/disclosure-checker-staging/resources/main.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/disclosure-checker-staging/resources/rds.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/disclosure-checker-staging/resources/variables.tf

* Bump the RDS and ECR modules to the latest versions.
* Using the new providers mechanism.
* Force SSL in RDS module.
Note: ECR module bumped only to 3.3 and not 3.4 because latest version doesn't work until the providers mechanism is in place.

Bump disclosure checker module versions

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-repos/resources/repos.tf

this docker image is used to build form builder components
this is used by our continuous integration tools

add ECR for form builder fb-builder

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/logging/monitoring.yaml

This is now managed by the helm chart, see https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/309

Remove fluentd-es ServiceMonitor

---

namespaces/cloud-platform-live-0.k8s.integration.dsd.io/laa-fee-calculator-production/00-namespace.yaml
namespaces/cloud-platform-live-0.k8s.integration.dsd.io/laa-fee-calculator-staging/00-namespace.yaml

Due to the pending migration from live-0 > live-1 these two environments
need to remain, together, in the live-1 environment until the application
has been prepared for migration

Update fee-calculator labels

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-services-live-production/resources/main.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-services-live-production/resources/route53.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-services-live-production/resources/variables.tf

- I've reworked the missing route53 modules for form builder
- I've moved the namespaces so it seems more logical and closer to the certificates
- It's not tested so want a second pair of eyes

rework form builder route53 terraforms

---

namespaces/cloud-platform-live-0.k8s.integration.dsd.io/laa-apply-for-legalaid-production/00-namespace.yaml
namespaces/cloud-platform-live-0.k8s.integration.dsd.io/laa-apply-for-legalaid-staging/00-namespace.yaml
namespaces/cloud-platform-live-0.k8s.integration.dsd.io/laa-apply-for-legalaid-uat/00-namespace.yaml

Marking our namespaces as `production` in order to give us more time to migrate them to `live-1`

Flag laa-apply-for-legalaid namespaces as production

---

namespaces/cloud-platform-live-0.k8s.integration.dsd.io/laa-cla-public-staging/00-namespace.yaml
namespaces/cloud-platform-live-0.k8s.integration.dsd.io/laa-fala-staging/00-namespace.yaml

To protect them when non-production environments are removed from live-0
The production namespaces for both are already marked as `in-production`

Mark cla-public and fala staging namespaces as is-production

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/c100-application-production/resources/rds.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/c100-application-staging/resources/rds.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/disclosure-checker-staging/resources/rds.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/family-mediators-api-production/resources/main.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/family-mediators-api-production/resources/rds.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/family-mediators-api-production/resources/variables.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/family-mediators-api-staging/resources/main.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/family-mediators-api-staging/resources/rds.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/family-mediators-api-staging/resources/variables.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/fj-cait-staging/resources/main.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/fj-cait-staging/resources/variables.tf

Happy to use the defaults for `db_engine_version` and  `rds_family`, so we are not specifying these.
Cleanup of some remaining unused `var.aws_region`.

Bump RDS module version

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/prison-visits-booking-production/02-limitrange.yaml

The limitrange values in production are causing PVB to hit quota
limits for their deployments. Their pods use far less resources
than they request, so this commit reduces the limitrange values
in their production namespace, to avoid this problem.
For more details:
https://mojdt.slack.com/archives/C57UPMZLY/p1563370094059800

Set pvb prod ns limitrange to pvb staging values

---

namespace-resources/02-limitrange.yaml

Averaged across the whole cluster, containers use
8m CPU, and 128Mi Memory. 
The defaultRequest values are the resources the
scheduler will *reserve* for every container in a 
pod. If these values are much higher than what
containers will actually use, the cluster will run
out of capacity much sooner than it should.
NB: This commit only changes the *request* value,
not the limits on how much resource a container
is actually allowed to consume.

Reduce default request values for new namespaces

---

namespace-resources/03-resourcequota.yaml

Change #1012 reduced the resources that will be
reserved for every container in a namespace.
Having reduced those values, we should be able to
reduce the overall resources that will be reserved
for the namespaces as a whole.
This commit reduces those values by half, which is
a conservative change.
Looking at our actual usage, out of 114 namespaces
in live-1, 103 are using less than 2Gi of memory,
and 107 are using less than 100m of CPU.
NB: This only puts a limit on the resources the
cluster will reserve for a namespace. It does not
prevent the namespace from *consuming* more than
this.
Relates to #1012
Relates to https://github.com/ministryofjustice/cloud-platform/issues/1094
Closes https://github.com/ministryofjustice/cloud-platform/issues/1093

Halve the requests limits for new namespaces

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-frontend-production/certificate.yaml

For the frontend server we are using hostname `bookasecuremove.service.justice.gov.uk`

Add certificate for hmpps-book-secure-move-frontend-production

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-production/certificate.yaml

For the backend API server we are using hostname `api.bookasecuremove.service.justice.gov.uk`

Add certificate for hmpps-book-secure-move-api-production

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-fee-calculator-production/00-namespace.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-fee-calculator-production/01-rbac.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-fee-calculator-production/02-limitrange.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-fee-calculator-production/03-resourcequota.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-fee-calculator-production/04-networkpolicy.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-fee-calculator-production/certificate.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-fee-calculator-production/resources/main.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-fee-calculator-production/resources/variables.tf

Setup the laa fee calculator production API's resources
We are going to run this production app in tandem
with currently used live-0 production app while we
rewire consumers. On the face of it only two components
make use of this API:
- https://github.com/ministryofjustice/Claim-for-Crown-Court-Defence
- https://github.com/ministryofjustice/laa-fee-calculator-client
...and the app (former) uses the client gem (latter).
We also need to determine other users of the current API
by reviewing logs on the live-0 production instances.

Add laa-fee-calculator-production namespace, resources and certificate

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/prison-visits-booking-production/02-limitrange.yaml

This change was made because PVB were unable to increase the number
of replicas for their staff app. deployment from 3 to 5. By making
this change, we believe enough reserved capacity was freed up to
allow the extra pods to run. So, this commit makes the change
permanent.

Decrease default limits for CPU and memory

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/logging/02-limitrange.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/logging/03-resourcequota.yaml

Due to a recent node scale out the daemonset for fluentd was failing due to resource limitations. This change will allow us to deploy the daemonset successfully.

Change logging resourcequota and limit range

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-production/resources/route53.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-staging/resources/route53.tf

Add a route53.tf file to set up a domain name for the production environment under the ```.service.justice.gov.uk``` domain.
The preferred names are:
production  ```apply-for-legal-aid.service.justice.gov.uk```
staging ```staging.apply-for-legal-aid.service.justice.gov.uk```
Would it be better to set the route53.tf on production and have a subdomain for staging?

Add route53.tf file for apply for legal aid 

---

bin/namespace-reporter.rb

PR #1038 removes the 'limits' values from new
namespaces, so reporting on them is only likely to
confuse people.
This change still gathers the information on
'hard' limits, but it doesn't output those values.

Remove the 'hard limits' from reporter output

---

namespace-resources/02-limitrange.yaml
namespace-resources/03-resourcequota.yaml

This PR removes the 'limits' on namespace resource quotas, because they don't
do anything useful.
It also reduces the request limits values for namespaces, and the requests and
limits values which will apply to new containers, if users do not specify values
in their deployments.

Reduce default resource quota and limit range values for new namespaces

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-platform-integration-dev/resources/main.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-platform-integration-dev/resources/user-datastore.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-platform-integration-production/resources/main.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-platform-integration-production/resources/user-datastore.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-platform-integration-staging/resources/main.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-platform-integration-staging/resources/user-datastore.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-platform-live-dev/resources/main.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-platform-live-dev/resources/user-datastore.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-platform-live-production/resources/main.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-platform-live-production/resources/user-datastore.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-platform-live-staging/resources/main.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-platform-live-staging/resources/user-datastore.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-platform-test-production/resources/main.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-platform-test-production/resources/user-datastore.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-platform-test-staging/resources/main.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-platform-test-staging/resources/user-datastore.tf

- this is similar to https://github.com/ministryofjustice/cloud-platform-environments/pull/1045 except for different application hence different rds instances

formbuilder force_ssl on datastore rds instances

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/prison-visits-booking-production/03-resourcequota.yaml

These request limit values are based on amount of resources their
production namespace uses.
Also, remove the 'hard' limits from the namespace resourcequota, because they're not useful.

Reduce request.limits resourcequota for PVB prod.

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/prison-visits-booking-staging/03-resourcequota.yaml

They have some cron jobs, so they need some
'headroom' in their CPU and memory resource quotas

Increase resource request limits for PVB staging

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/prison-visits-booking-production/03-resourcequota.yaml

They need more 'headroom' to allow cron jobs to be scheduled

Increase PVB prod request.limits memory to 16GB

---

namespace-resources/03-resourcequota.yaml

Based on PVB prod namespace resizing, it's hard to predict in
advance how much memory a namespace will need, especially for
short-lived jobs.
This change should give developers more room to play with, although
they will still need to increase this limit for production namespaces

Allocate 5Gi memory request.limits to namespaces

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-staging/resources/pingdom.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-staging/resources/variables.tf

Add pingdom resource to CCCD staging
To get failed ping response alerts in #laa-get-paid-alerts
channel

Add pingdom resource to CCCD staging

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/offender-management-preprod/03-resourcequota.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/offender-management-production/03-resourcequota.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/offender-management-staging/03-resourcequota.yaml

Currently staging and preprod have much lower values than production, so
this PR set them all to the same - at the same time, it removes the hard
limits.

Update the resource quotas for MOIC

---

bin/namespace-reporter.rb
makefile

* Treat the supplied name as a pattern (e.g. get output for all the prison-visits namespaces at once)
* Add a `-o json` option for JSON output
* Handle memory values in the format 99999Ki
* Handle namespaces where the limits are not set (e.g. 'default')
* Update the usage tips at the top of the file
Note: This is a breaking change, in the sense that `./bin/namespace-reporter.rb foo` will not
work anymore. Now, it has to be `./bin/namespace-reporter.rb -n foo`

This PR adds several improvements to the namespace reporter script

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-publisher-test/resources/main.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-publisher-test/resources/publisher.tf

- I am aware rds module 4.5 and postgres 10.10 are available but have to chosen these numbers so we can have parity across the many moving form builder parts
- these changes affect non-production environments

formbuilder upgrade non-prod postgres 10.6 => 10.9

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-staging/certificate.yaml

Need to create a certificate for new domain ```apply-for-legal-aid.service.justice.gov.uk```
however this is on staging as we require ```staging.apply-for-legal-aid.service.justice.gov.uk``` as a subdomain.
Not sure if this is the correct way, i.e should I be creating one certificate under ```apply-for-legal-aid.service.justice.gov.uk``` and this would also cover any subdomains?

Add certificate for domain name

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-staging/certificate.yaml

The namespace was provided was incorrect
laa-apply-for-legal-aid-staging -> laa-apply-for-legalaid-staging
i.e. remove extraneous dash in 'legal-aid'

Correct the namespace name in certificate file

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-dev/resources/messaging.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-staging/resources/messaging.tf

For runtime resolution of URLs by consuming
apps.
3 apps consume these queues. They currently (in TD "world")
do so by querying the SQS url via its name and,
transparently, against the relevant AWS credentials.
By fixing the name we render the apps more resilient to
possible changes to the random underlying URLs.

Add names to all of CCCDs SQS queues

---

namespace-resources/02-limitrange.yaml

Containers can require a lot more resources when 
they start up than they do during normal operation
e.g. CCCD's containers use about 4m CPU most of
the time, but spike to nearly 1000m during startup
If the CPU limit is set too low in the limit range
the container can be throttled during startup.
This can make the startup process take so long
that the container fails its readiness probe, and
the cluster kills it and starts a new one, which
results in a crashloop.
This commit allows containers to spike to 1000m
CPU, and also increases the memory limit to 1Gi,
to avoid this problem.

Increase default container CPU & memory limits

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-dev/resources/messaging.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-staging/resources/messaging.tf

Remove redunant environment name repetition in names
The SQS terraform template enforces
prefixing of queue names with team
name and environment.
Given this, the queues names will have
to change from those currently used in
TD incarnations regardless. This, therefore,
just removes redudant environment name
repetition.

Rename all cccd SQS queues

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/offender-management-preprod/prometheus-custom-alerts-moic-preprod.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/offender-management-production/prometheus-custom-alerts-moic-production.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/offender-management-staging/prometheus-custom-alerts-moic-staging.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/prison-visits-booking-production/prometheus-custom-alerts-pvb-production.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/prison-visits-booking-staging/prometheus-custom-alerts-pvb-staging.yaml

The KubePodNotReady alert is not working as intended and is causing a
huge amount of noise in our alerts channels for PVB & MOIC so we are
going to remove it.

Remove custom Prometheus alert from PVB & MOIC

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-fee-calculator-production/02-limitrange.yaml

They are seeing sentry issues with failing health checks, and I
can see 'Readiness probe failed' kubernetes events.
I believe the container is sometimes being starved of CPU,
probably at launch time, causing startup to take too long, and
the readiness probe to fail.
This change allows the container to burst CPU usage much higher,
which should avoid this problem.

Increase the default resource limits for fee-calc

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-fee-calculator-staging/02-limitrange.yaml

Increase laa-fee-calculator-staging default resource limits
Inline with [laa-fee-calculator-production changes](https://github.com/ministryofjustice/cloud-platform-environments/pull/1118/files) for
the sake of parity.

Increase laa-fee-calculator-staging default resource limits

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/offender-categorisation-dev/resources/messaging.tf

Removed resource aws_sqs_queue_policy to fix pipeline
pipeline failing with reason:
` Error updating SQS attributes: AWS.SimpleQueueService.NonExistentQueue: The specified queue does not exist for this wsdl version.`

Removed resource aws_sqs_queue_policy to fix pipeline

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/family-mediators-api-production/resources/route53.tf

- Added Route53 zone in family-mediator-api-production.
The zone had been created manually. 
A manual import is needed before merging this.

add route53 for family mediator

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/c100-application-production/resources/route53.tf

- Added new route53 zones in c100-application-production.
- The two zones had been created manually, this PR configures it in the code.
A terraform import has to be ran before this can be merged.

add route53 zone for c100, long and short

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/offender-management-production/resources/route53.tf

- Add route53 zone for moic.service.justice.gov.uk
- The zone exists already, but was created manually. This change brings it into the code .
A terraform import is needed before we can merge this.

Route53 moic

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/money-to-prisoners-prod/resources/main.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/money-to-prisoners-prod/resources/route53.tf

- Add route53 zone definition for prisoner-money.service.justice.gov.uk.
- This zone already exist and had been created manually. This change make it manageable through code.
- Add default terraform provider, on top of `aws.london`
A terraform import will be required, before this is merged.

add route53 for prisoner-money

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-production/00-namespace.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-production/01-rbac.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-production/02-limitrange.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-production/03-resourcequota.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-production/04-networkpolicy.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-production/resources/main.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-production/resources/variables.tf

Add cccd-production namespace
migration to live-1. This namespace is
initially to be used for testing RDS and
s3 migration.

Add cccd-production namespace

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-production/02-limitrange.yaml

Reduce cccd-production cpuRequest limitrange
receiving the following with current settings:
```
Warning   FailedCreate        ReplicaSet   Error creating: pods "claim-for-crown-court-defence-845ff6bd95-j28ln" is forbidden: exceeded quota: namespace-quota, requested: requests.cpu=125m, used: requests.cpu=250m, limited: requests.cpu=300m
```
These changes bring cccd-production
inline with cccd-staging namespace
but will need reviewing inline with
current (template-deploy) production
version of CCCD.

Reduce cccd-production cpuRequest limitrange

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-production/resources/messaging.tf

do not merge til SNS queue and IAM user
applied.
Reverts "Remove SQS from message.tf"
This reverts commit c4990fa4ddd7307e0b1472209842035834880d3e.
This commit was previously applied because the
SNS IAM user needs to be created first before
before used as the SQS user.

Add cccd-production SQS resource

---

makefile

This makefile target uses the cloud platform tools
image, so the user does not need to install 
terraform, although they do need to have a 
`moj-cp` AWS profile configured, and docker
installed.
This change, once merged, will be used as the
basis for a rewrite of the user guide article on
creating a new namespace.

Enable creating namespace with `make namespace`

---

makefile

This means there is no longer a requirement for the user to have
the AWS cli installed and configured, and no need to authenticate
to ECR in order to run `make namespace`

Update makefile to use dockerhub tools image

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmcts-complaints-formbuilder-adapter-staging/00-namespace.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmcts-complaints-formbuilder-adapter-staging/01-rbac.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmcts-complaints-formbuilder-adapter-staging/02-limitrange.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmcts-complaints-formbuilder-adapter-staging/03-resourcequota.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmcts-complaints-formbuilder-adapter-staging/04-networkpolicy.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmcts-complaints-formbuilder-adapter-staging/resources/main.tf

See `production` namespace PR here: https://github.com/ministryofjustice/cloud-platform-environments/pull/1171
Formbuilder team are building an integration to connect an HMCTS form (built with Formbuilder) to the HMCTS Optics CMS system. This form is for handling complaints about courts.
This "adapter" is going to sit off the Formbuilder infrastructure and receive a JSON payload from Formbuilder. It will take this JSON payload and connect to the HMCTS Optics CMS system (3rd party).
This PR is for the staging namespace for this application.

HMCTS Formbuilder Adapter staging namespace

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmcts-complaints-formbuilder-adapter-production/00-namespace.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmcts-complaints-formbuilder-adapter-production/01-rbac.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmcts-complaints-formbuilder-adapter-production/02-limitrange.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmcts-complaints-formbuilder-adapter-production/03-resourcequota.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmcts-complaints-formbuilder-adapter-production/04-networkpolicy.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmcts-complaints-formbuilder-adapter-production/resources/main.tf

See `staging` namespace PR here: https://github.com/ministryofjustice/cloud-platform-environments/pull/1170
Formbuilder team are building an integration to connect an HMCTS form (built with Formbuilder) to the HMCTS Optics CMS system. This form is for handling complaints about courts.
This "adapter" is going to sit off the Formbuilder infrastructure and receive a JSON payload from Formbuilder. It will take this JSON payload and connect to the HMCTS Optics CMS system (3rd party).
This PR is for the staging namespace for this application.

HMCTS Formbuilder Adapter production namespace

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-production/02-limitrange.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-staging/02-limitrange.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-uat/02-limitrange.yaml

Runtime CPU usage of each of the Apply-for-legal-aid containers stays
under 10m. So allocating 100m for each was an overkill.
We increased the memory allocation per container as some of our
containers use between 256Mi and 900Mi, while others use less than
100Mi.
We normalized the container CPU and Memory allocation for the three
environments/namespaces: UAT, Staging and Production so we have the
same resources everywhere.

Reduce "Apply for legal aid" containers CPU allocation

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-production/resources/pingdom.tf

previous host was a copy and paste
error from cccd-staging - that host does not
exist for production.

Amend pingdom host

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/namespace-usage-report/00-namespace.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/namespace-usage-report/01-rbac.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/namespace-usage-report/02-limitrange.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/namespace-usage-report/03-resourcequota.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/namespace-usage-report/04-networkpolicy.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/namespace-usage-report/resources/main.tf

This namespace will host a single pod, with a container running
the sinatra application that displays information about namespace
utilisation.

Create a namespace for the namespace usage report

---

bin/namespace-reporter.rb

This JSON file will be used in the namespace usage report web
application. I expect it will only be updated hourly, or something
like that, so it's important for users to know when the data
they're looking at was generated.

Add a "last updated" value to the namespace report

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-legal-adviser-api-staging/resources/elasticache.tf

A quick follow-up to #1182: the secret postfix is unnecessary as we already have "staging" in the namespace.

Remove environment postfix from the secret

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-production/03-resourcequota.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-staging/03-resourcequota.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-uat/03-resourcequota.yaml

Runtime CPU usage of each of the Apply-for-legal-aid namespaces stays
well under 100m (usually below 20m).
So allocating 4000m to 20000m for each namespace was an overkill.
The memory currently used by namespace is bellow 3Gi, so setting an
scheduled allocation of 6Gi gives us space for even a replica of all the
containers in the namespace.
We normalized the namespace CPU and Memory allocation for the three
environments/namespaces: UAT, Staging and Production so we have the
same resources everywhere.
The limits.cpu and limits.memory are not used anymore in the defaults
and we removed them to align our configurations with Cloud Platform
current defaults/standards.

Reduce "Apply for legal aid" namespaces CPU allocation

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-production/03-resourcequota.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-staging/03-resourcequota.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-uat/03-resourcequota.yaml

Reverts ministryofjustice/cloud-platform-environments#1168
We were actually allocating more CPU per pod than the Namespace Allocation we set up, so started getting alerts like: 
"Alert: Namespace laa-apply-for-legalaid-production is using 170% of its requests.cpu "
Reverting the reduction, will adjust accordingly and re-open the PR.

Revert "Reduce "Apply for legal aid" namespaces CPU allocation"

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/namespace-usage-report/deployment.yaml

This version includes this fix:
https://github.com/ministryofjustice/cloud-platform-namespace-usage-report/commit/29a46515976cc155c82380809364174d961eb0e6

Bump the namespace report image from 1.0 to 1.1

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-staging/resources/main.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-staging/resources/rds.tf

Postgres 10.6 --> 9.6.
Also:
- update the terraform template
- specify instance class to match production
This downgrade of the rds instance is in line with both
live-1 cccd-production and cccd-api-sandbox, as well as
all current CCCD Template deploy environment. The downgrade
is to remove potential unknowns from any migration of the
current production databases (TD).
Can be upgraded after migration to live-1.

Downgrade cccd-staging rds instance to postgres 9.6

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/monitoring/02-limitrange.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/monitoring/03-resourcequota.yaml

* Reduce limitrange requests from 125m/250Mi to
10m/100Mi
This change will not have any effect, because all
the pods in the monitoring namespace seem to have
sensible resource values set via the helm chart, 
so these defaults won't be used. But, this change
is worth making in case we add any pods to the
namespace in future, without specifying limits.
* Remove the 'hard limit' on the namespace
* Reduce the request limit from 10000m/24Gi to
500m/12Gi
These changes bring the namespace closer into line
with our defaults for all namespaces, and better
reflect what the monitoring namespace actually
uses.

Reduce resources reserved for monitoring namespace

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/monitoring/03-resourcequota.yaml

The total of all pod cpu requests is 2150, so a limit for the
namespace of 500 is much too low.

Increase monitoring namespace request CPU limit

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-dev/resources/main.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-dev/resources/rds.tf

Postgres 10.6 --> 9.6
Also:
- update the terraform template
- specify instance class to be small
This downgrade of the rds instance is in line with both
live-1 cccd-production, cccd-api-sandbox and cccd-staging
as well as all current CCCD Template deploy environments.
The downgrade is to remove potential unknowns from any
migration of the current production databases (TD).
Can be upgraded after migration to live-1.

Downgrade cccd-dev rds instance to postgres 9.6

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-dev/resources/redis.tf

previously had forgotten to jsonencode the value
resulting in apply pipeline error.
```
Error: Error running plan: 1 error occurred:
* kubernetes_secret.cccd_elasticache_redis: data (member_clusters): '' expected type 'string', got unconvertible type '[]interface {}'
```

Add member clusters output to cccd-dev redis cluster

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/cts-prototype-dev-poc/resources/redis.tf

Enable redis cluster for use with Track a Query (Correspondence Tool Staff)

Track A Query - add elasticache

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-api-sandbox/resources/elasticache.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-api-sandbox/resources/main.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-api-sandbox/resources/variables.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-dev/resources/elasticache.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-production/resources/elasticache.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-production/resources/rds.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-production/resources/variables.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-staging/resources/elasticache.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-staging/resources/rds.tf

amend cccd-dev terraform file name inline with conventions
add elastiche to api-sandbox, staging and production.
Redis used for queuing email jobs and caching calls
to internal API.
TD elasticache uses an old node size of cache.m1.small in
production which most closely maps to cache.t2.small for
[current standard nodes](https://aws.amazon.com/elasticache/pricing/)

Add elasticache to all cccd namespaces

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/track-a-query-dev/resources/rds.tf

To fix a broken reference to a namespace that doesn't exist.

Fix namespace in track-a-query-dev namespace

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/cts-prototype-dev-poc/resources/s3.tf

Correspondence Tool Staff requires an S3 bucket to operate

Track a Query - Add simple S3 bucket to terraform config

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/kube-system/00-namespace.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/opa/00-namespace.yaml

Related to: https://github.com/ministryofjustice/cloud-platform/issues/1028
Why: OPA policy to block Pods which has tolerations stopped OPA to make decisions because the OPA pod were also blocked from creating which created a loop. Hence, Ignore OPA and kube-system from OPA policy decisions.
Ref: https://www.openpolicyagent.org/docs/latest/kubernetes-debugging/#ensure-the-webhook-is-configured-for-the-proper-namespaces

Annotate OPA and kube-system namespace so OPA ignore decisions

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/kube-system/00-namespace.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/logging/00-namespace.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/monitoring/00-namespace.yaml

What:
Annotate monitoring and logging namespaces with cloud-platform.justice.gov.uk/can-tolerate-master-taints
Why: so when the OPA policy for pod toleration is applied, these namespaces are allowed to schedule pods on master node
Related to: https://github.com/ministryofjustice/cloud-platform/issues/1028

Annotate monitoring and logging ns to have workloads in master node

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/money-to-prisoners-test/06-service-account-circleci.yaml

This is because if you want to "patch deployments" you need "get" as well.

Add get verb to MTP Test for circleci service account

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/cts-prototype-dev-poc/resources/redis.tf

Redis URL in module output should have the `redis://` protocol in the URL for use in the consuming application.

Track a Query - Add protocol to Redis URL

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmcts-complaints-formbuilder-adapter-production/01-rbac.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmcts-complaints-formbuilder-adapter-staging/01-rbac.yaml

We only use `helm template` so don't need Tiller running on the server.

Remove Tiller Service Accounts

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/logging/03-resourcequota.yaml

The logging namespace uses less than 3000m CPU. This change
reduces the amount of CPU requested (i.e. reserved) from 6000m
to 3000m

Reduce logging namespace CPU request to 3000m

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/offender-management-production/certificate.yaml

This was previously being done in the code repo and as a result was
infrequently applied.  Moving here for safe keeping.

Add certificate for offender-management-production

---

bin/apply

This change has no functional effect, but it makes
it easier to grab the part of the command you need
when doing a manual apply on a namespace, without
including the dangerous `auto-approve` flag

Move `auto-approve` flag to the end of the command

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/opa/02-limitrange.yaml

* CPU: 40m -> 4m
* memory: 200Mi -> 50Mi
This is much closer to what the pods use in live-1

Reduce OPA limitrange default requests

---

bin/certificates.rb

Output a list of all TLS secrets in the cluster, for which there is no
matching (i.e. with the same name) certificate object in the same namespace.
replaces https://github.com/ministryofjustice/cloud-platform/pull/1237

Add "missing certificates" script

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-platform-integration-dev/resources/json-output-attachments-s3.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-platform-integration-production/resources/json-output-attachments-s3.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-platform-integration-staging/resources/json-output-attachments-s3.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-platform-live-dev/resources/json-output-attachments-s3.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-platform-live-production/resources/json-output-attachments-s3.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-platform-live-staging/resources/json-output-attachments-s3.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-platform-test-dev/resources/json-output-attachments-s3.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-platform-test-production/resources/json-output-attachments-s3.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-platform-test-staging/resources/json-output-attachments-s3.tf

In order to support attachments for the HMCTS API integration, we need new
buckets with a shorter lifecycle policy.
Files will be encrypted with a different key than the existing bucket.
This key will then be passed on to our adapter to fetch and decrypt these files
on request from the Optics API.  We will use pre-signed URL's to fetch the
objects.

Additional User Filestore S3 buckets for each environment

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/cts-prototype-dev-poc/resources/elasticache.tf

Changes the `redis.tf` filename to `elasticache.tf` with appropriate URL change to use `rediss://`

Track-a-Query Use Redis encrypted URL

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/c100-application-production/03-resourcequota.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/c100-application-staging/03-resourcequota.yaml

- Removing hard.limit of the c100 namespaces. 
- Bumping hard.request.memory to 12Gi

Removing namespace hard-limit

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/monitoring/02-limitrange.yaml

**Why**
`level=warn ts=2019-09-25T10:08:55.109237842Z caller=scrape.go:835 component="scrape manager" scrape_pool=monitoring/prometheus-operator-node-exporter/0 target=http://172.20.93.216:9100/metrics msg="append failed" err="write to WAL: log samples: write /prometheus/wal/00013884: cannot allocate memory"`
After increasing the limit, Prometheus operator pod stabilized at around 1000m CPU / 9000 Mi RAM

more resources for Prometheus operator

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/concourse/02-limitrange.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/concourse/03-resourcequota.yaml

**Why**
`top pod` and speed of pipeline shows a slowdown

more CPU for Concourse

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-platform-pentest-dev/resources/main.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-platform-pentest-production/resources/main.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-platform-pentest-staging/resources/main.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-publisher-pentest/resources/main.tf

These namespaces have all had their AWS resources
deleted, and been removed from the cluster.
This commit removes leftover main.tf files which
are no longer required, and the directories
themselves.

Remove leftover main.tf files from fb pentest ns

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/logging/00-namespace.yaml

What:
Synching labels and annotations for logging namespace with infrastructure repo
Why:
The namespace creation is moved to infrastructure repo but when the pipeline run for live-1, it overwrites the labels and annotations creating conflicts whenever doing terraform plan on live-1.

Removing conflicts for logging namespace

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/parliamentary-questions-development/02-limitrange.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/parliamentary-questions-development/03-resourcequota.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/parliamentary-questions-production/02-limitrange.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/parliamentary-questions-production/03-resourcequota.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/parliamentary-questions-staging/02-limitrange.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/parliamentary-questions-staging/03-resourcequota.yaml

This commit adjusts PQ namespaces' resource requests and limits
* removes the namespace hard limits
* reduces namespace request limits
* increases default container hard limits
* reduces default container request limits
Nick Preddy of the PQ team has given the green light for this change to go ahead.

Resize pq namespaces

---

bin/namespace-details.rb

This script outputs the overall namespace resource requests and usage,
and print out details of how much each running container is requesting
and using.
This will be used to generate reports to send to responsible parties
whose namespace resources need adjusting.

Add a script to report namespace usage down to container-level

---

bin/namespace-details.rb

This is not needed for normal operation, and removing the require
means the script doesn't need any custom libraries in order to run.

Remove pry-byebug

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/concourse/03-resourcequota.yaml

Now that the pod resources requested by concourse have been
adjusted, we cna reduce the overall namespace resource requests
related to
https://github.com/ministryofjustice/cloud-platform-concourse/pull/103

Reduce concourse namespace resourcequota

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/money-to-prisoners-prod/resources/route53.tf

this is a bit of an experiment. i'm hoping that knowing the name servers for these new zones will allow us to check that things were correctly copied from the DSD account and will work properly once delegated instead to the CP account.
is the kubernetes secret used for anything special within cloud platform? is it ok to add/change keys here?

Save Route53 zone name servers into kubernetes secret

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/logging/elasticsearch-curator.yaml

**Why**
fails if the test ES cluster doesn't have any entries

curator ignore empty test

---

bin/namespace-details.rb

filter was introduced in ruby 2.6
find_all is a synonym, and works with earlier versions, so this
change makes it possible for people to run this script without
requiring them to install a later version of ruby.

namespace-details.rb: 'find_all' not 'filter'

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/cica-oas-basic-testing/03-resourcequota.yaml

* CPU to 250m
* Memory to 5000Mi
Memory is our default for new namespaces, 250m is double what the
total pods in the namespace are currently requesting

Reduce cica-oas-basic-testing resources

---

bin/namespace-details.rb

This makes it easier to see when the namespace request limit for
CPU and memory can be safely adjusted, without impact.

Add namespace total requested CPU & memory

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-prod/03-resourcequota.yaml

This brings the namespace into line with the dev namespace.
Although this is "prod", the service is not actually running yet.

claim-criminal-injuries-compensation-prod requests

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-dev/03-resourcequota.yaml

* CPU to 600m (double total requests)
* memory to 5000Mi (default for new namespaces)

Reduce claim-criminal-injuries-compensation-dev

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/pecs-move-platform-backend-staging/03-resourcequota.yaml

* CPU to 750m (double current total requests)
* Memory to 5000Mi (default for new namespaces)

Reduce pecs-move-platform-backend-staging requests

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-platform-test-dev/03-resourcequota.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-platform-test-production/03-resourcequota.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-platform-test-staging/03-resourcequota.yaml

Temporary uplift of namespace cpu resources so we can reduce resources for the pods.

Fb platform dev namespaces increase resources

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-dev/resources/s3.tf

The `aws s3 sync` command requires `s3:CopyObject` permissions
at least.
This must be applied here and on the dev bucket's bucket policy
inline with this change.
example output without this action permitted
```
copy failed: s3://adp-dev-documents/reports/management_information_20191008040001.csv to s3://cloud-platform-9266f53d509c18e49891086e2f27d82c/reports/management_information_20191008040001.csv An error occurred (AccessDenied) when calling the CopyObject operation: Access Denied
```

Enable sync between template deploy s3 dev and cccd-dev s3

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/court-probation-dev/03-resourcequota.yaml

* CPU: 6000m to 300m (double current total requested)
* memory: 12Gi to 5Gi (default for new namespaces)

court-probation-dev resource requests

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/dps-welcome-dev/02-limitrange.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/dps-welcome-prod/02-limitrange.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/nomis-reports-dev/02-limitrange.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/offender-case-notes-dev/02-limitrange.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/offender-case-notes-preprod/02-limitrange.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/offender-case-notes-prod/02-limitrange.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/offender-categorisation-dev/02-limitrange.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/offender-categorisation-preprod/02-limitrange.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/offender-categorisation-prod/02-limitrange.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/offender-events-dev/02-limitrange.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/use-of-force-dev/02-limitrange.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/use-of-force-preprod/02-limitrange.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/use-of-force-prod/02-limitrange.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/whereabouts-api-dev/02-limitrange.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/whereabouts-api-preprod/02-limitrange.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/whereabouts-api-prod/02-limitrange.yaml

HMPPS namespaces were created when our default
for defaultRequest.cpu was 180m
This is excessive because the containers in these
namespaces generally use around 1m CPU (this is
the case for most namespaces in the cluster) and 
it reduces the CPU available for other workloads.
Once this change is merged, and after the pods
running with the current 180m CPU request have
been cycled, subsequent PRs will reduce the
overall request size for the namespaces, which
will free up these resources.

Reduce CPU default request to 10m for HMPPS

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-api-sandbox/resources/s3.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-production/resources/s3.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-staging/resources/s3.tf

Add s3 IAM user-policies to cccd-staging, api-sandbox
and production.
Enable live-1 (destination) s3 sync with
template-deploy (source) s3 bucket.
The Bucket policy of the source will
restrict permissions to ListBucket and
GetObject, which are the minimum required
for sync to work.

Add cccd s3 user-policies necessary for TD sync

---

.github/workflows/delete-branch-after-merge.yml
bin/delete-branch-after-merge.rb

Merging a PR will trigger the workflow, which will
find the branch the PR relates to, and delete it.
If the user has already deleted the branch, this
workflow will show an error, but nothing terrible
will happen.
It's not strictly necessary to use the tools image
for this. A lighter-weight ruby image would work,
but we'll need the tools image for some workflows,
so it seems simpler to just use it everywhere, 
even if that makes workflows run a little slower
than they could.

Add a github actions workflow deleting branches

---

bin/delete-branch-after-merge.rb

If the user deletes their branch when merging, then the branch
will be missing when this script tries to delete it. This will
raise an error, making it look like something was wrong.
This change swallows the relevant error, so that the action will
complete successfully.
This might sometimes swallow other errors that we would prefer to
see, so the rescue block dumps the error to stdout, so that it's
visible to anyone who views the action log via the github web UI.

Catch errors if branch already deleted

---

bin/delete-branch-after-merge.rb

This should have gone in as part of the last PR.
If the branch delete fails, it might be useful to
see the details of the error, in case it's not
because the user deleted the branch before the
action could do so.

Output the exception, if branch delete fails

---

.github/workflows/malformed-yaml.yml

PRs like this one, containing malformed YAML, are hard to spot
by eye:
https://github.com/ministryofjustice/cloud-platform-environments/pull/1353
This commit adds a workflow which will attempt to parse every YAML file
included in a given PR. If any fail to parse, the action marks the PR as
bad and lists the failing files.

Add github action to reject bad YAML

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/whereabouts-api-dev/03-resourcequota.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/whereabouts-api-preprod/03-resourcequota.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/whereabouts-api-prod/03-resourcequota.yaml

The whereabouts API namespaces are requesting less than 200m CPU
(the total of all requests for all pods in the namespaces), but
the namespaces have a request limit of 3000m.
This change reduces the CPU request limit of each namespace to
300m, which will free up 8100m of CPU in the cluster which is
currently not being used.
I have run this change past Matt Whittaker, who is happy for us to go ahead with it.

Reduce CPU request limits for whereabouts API

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/disclosure-checker-production/03-resourcequota.yaml

The disclosure-checker-production namespace is using 270m CPU and
1200Mi of memory.
This change reduces the CPU request limit from 3000m to 600m, and
the memory request limit from 6000Mi to 5000Mi.
This brings the production namespace into line with the staging
namespace, and frees up 2400m of CPU which is not currently
being used.
I've run this past Jesus Laiz, who is happy for us to go ahead.

Reduce resourcequota for disclosure-checker-prod

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/use-of-force-dev/03-resourcequota.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/use-of-force-preprod/03-resourcequota.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/use-of-force-prod/03-resourcequota.yaml

The use-of-force-(dev|preprod|prod) namespaces request 3000m CPU
each. The total CPU requested by all pods in those namespaces is
190m each.
This change reduces the CPU requested for each namespace from
3000m to 300m, freeing up 8100m of unused CPU.

Reduce use of force namespaces CPU requests

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/fj-cait-production/03-resourcequota.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/fj-cait-staging/03-resourcequota.yaml

The fj-cait-(production|staging) namespaces are requesting 3000m
CPU and 6000Mi of memory.
The total requests for all pods in those namespaces is 50m CPU and
600Mi of memory.
This change reduces the requests for those namespaces to 100m CPU
and 1000Mi of memory.
This change should have no impact at all on the service. It does
not limit the resources available to the namespace, it just
changes the information provided to the scheduler in order to
help it decide where to schedule these namespaces' workloads.
This frees up 5800m CPU and 10Gi of memory which were not being
used, making them available to the cluster.

Reduce fj-cait resource requests

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-publisher-integration/02-limitrange.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-publisher-live/02-limitrange.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-publisher-live/03-resourcequota.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-publisher-test/02-limitrange.yaml

The publisher services use more memory.
formbuilder.publisher.test / integration / live
spec.limits.default.memory from 300Mi to 1000Mi
spec.limits.defaultRequest.cpu from 100m to 10m
spec.limits.defaultRequest.memory from 128Mi to 250Mi
spec.hard.limits removed from production-live.

changed resources for all formbuilder-publisher namespaces.

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-publisher-integration/03-resourcequota.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-publisher-live/03-resourcequota.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-publisher-test/03-resourcequota.yaml

formbuilder-publisher-test / integration / live
spec.hard.requests.cpu from 4000m to 300m
spec.hard.requests.memory 8Gi to 2000Mi

Change requested resources in the Namespaces.

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-legal-adviser-api-production/03-resourcequota.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-legal-adviser-api-staging/03-resourcequota.yaml

The max total of all pods' CPU requests in these two namespaces is 375m
(this will drop to 30m when the pods are restarted, and the new
limitrange values take effect). However, the namespaces request 3000m of
CPU each.
This change reduces the cpu requested by each namespace to 500m, freeing
up 5500m of unused CPU capacity.

Reduce CPU requests for legal adviser namespaces

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-services-live-dev/03-resourcequota.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-services-live-production/03-resourcequota.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-services-live-staging/03-resourcequota.yaml

Removed hard.limits from:
- formbuilder-services-live-dev
- formbuilder-services-live-staging
- formbuilder-services-live-production

Removed hard.limits from namespaces.

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-services-integration-dev/03-resourcequota.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-services-integration-production/03-resourcequota.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-services-integration-staging/03-resourcequota.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-services-live-dev/03-resourcequota.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-services-live-production/03-resourcequota.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-services-live-staging/03-resourcequota.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-services-test-dev/03-resourcequota.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-services-test-production/03-resourcequota.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-services-test-staging/03-resourcequota.yaml

Made the spec.hard.requests standard across all names spaces (except live.dev). The Service namespaces hold the running forms and therefore need larger overhead due to the form having elevated default resources for live forms (and testing).

spec.hard.requests adjusted for all service namespaces

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/offender-management-preprod/03-resourcequota.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/offender-management-production/03-resourcequota.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/offender-management-staging/03-resourcequota.yaml

The total of all the CPU requests for all pods in these namespaces is
800m in production, 600m in staging and 90m in preprod.  This will drop
to 90m in all 3 namespaces once all pods are restarted.
This change reduces the namespaces' CPU requests from 3000m to 1000m,
freeing up 4000m of unused CPU capacity. Although 1000m is much more
than should be required, I want all the namespaces to have the same
resourcequota, so that they all behave consistently wrt. scheduling
pods.
We can make a subsequent change to reduce the resourcequota further,
after all pods have been cycled and more resource can be reclaimed.

Reduce CPU requests for offender-management

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/c100-application-metabase/03-resourcequota.yaml

The total of all the CPU requests for all pods in these namespaces is
20m. Memory requests total is 500Mi.
This change reduces the overall namespace requests from 3000m CPU
to 100m, and from 6Gi of memory to 2Gi.

Reduce c100-application-metabase resource requests

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/offender-categorisation-dev/03-resourcequota.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/offender-categorisation-preprod/03-resourcequota.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/offender-categorisation-prod/03-resourcequota.yaml

The total of all the CPU requests for all pods in these namespaces is
400m. This will drop to 60m once all pods are restarted, because some
pods are still running with the old limitrange CPU requests value of
180m rather than 10m.
This change reduces the namespaces' CPU requests from 3000m to 600m,
freeing up 7200m of unused CPU capacity.
We can make a subsequent change to reduce the resourcequota further,
after all pods have been cycled and more resource can be reclaimed.

Reduce offender-categorisation ns CPU requests

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-production/03-resourcequota.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-staging/03-resourcequota.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-frontend-production/03-resourcequota.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-frontend-staging/03-resourcequota.yaml

@digitalronin pointed out that we're requesting 3 full CPUs for each service, but we're only using 0.04, so this PR frees up the remaining resource for other purposes.

Reduce resource quotes for book-a-secure-move

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-production/01-rbac.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-staging/01-rbac.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-frontend-production/01-rbac.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-frontend-staging/01-rbac.yaml

This updates the Book a Secure Move service to use RBAC on the `book-a-secure-move` team rather than `pecs` for consistency.
I'll delete the `pecs` team shortly.

Update book-a-secure-move Github team owners

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-production/resources/variables.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-staging/resources/variables.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-frontend-production/resources/variables.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-frontend-staging/resources/variables.tf

Following our previous PRs our CI started failing. This PR brings the ECR team name in line with the GitHub team specified in RBAC.

Book a secure move – rename team for ECR registry to match GH team

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/track-a-query-demo/resources/s3.tf

Access to existing S3 bucket in Template Deploy to allow sync operation with Cloud Platform deployed S3 Bucket

Track a Query - add demo S3 bucket access to Template Deploy

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/track-a-query-production/resources/s3.tf

Allow access to Template Deploy based S3 bucket for sync operations

Track a Query - add production S3 settings to access Template Deploy

---

namespace-resources/03-resourcequota.yaml

We don't set hard limits for CPU and memory anymore. This leaves
us open to a risk that a namespace could spawn unlimited pods,
eventually crashing a worker node.
This change sets a default limit on the number of pods which can
be scheduled into a namespace, which should reduce this risk.

Limit new namespaces to 50 pods

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/offender-events-dev/resources/messaging.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/offender-events-preprod/resources/messaging.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/offender-events-prod/resources/messaging.tf

How's best to the get the secret into another namespace?  I've raised this PR to hopefully cope the secret from the offender-events-x namespace into the offender-case-notes-x namespace - not sure if it will work or if there is a better way?

DT-326: Add offender events topic secret to case notes namespace

---

bin/apply

This commit depends on https://github.com/ministryofjustice/cloud-platform-concourse/pull/112, which makes the table name available as
an environment variable.
It also depends on https://github.com/ministryofjustice/cloud-platform-concourse/pull/111, which created the dynamodb table.
AFAICT, if the table is missing, or the env var.
is not available, the pipeline would still run
successfully, but would simply not lock the 
terraform states. I might be wrong about this, but
that's what seemed to be happening while I was
figuring this out.

Use dynamodb table to lock environments tf states

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-legal-adviser-api-production/resources/elasticache.tf

Production version of https://github.com/ministryofjustice/cloud-platform-environments/pull/1182

Add Amazon ElastiCache for Redis for laa-legal-adviser-api-production namespace

---

makefile

This will enable users to interact with the 
cluster, without having to install kubectl
locally

Add a `make tools-shell` command in env. repo

---

makefile

This enables users to use the tools shell to deploy kubernetes
manifest files from any directory on their local machine.
It requires setting APPDIR before running `make tools-shell`
This is a bit clunky, but if people don't have kubectl installed,
it's the easiest way I could think of to use the tools image for
everything.

Mount $APPDIR into the tools shell

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/prison-visits-booking-staging/03-resourcequota.yaml

The PVB team had a problem deploying an update in their staging
namespace. We traced this to container memory requests hitting the
namespace memory request limit, which was set lower than the
production namespace.
This change makes the resourcequota values consistent between
staging and production, which should avoid this issue in future.
On a related note, their deployments specify quite high memory
request values for some of their containers. These should probably
be reduced to avoid these kinds of issues.

Set pvb staging resourcequota to production values

---

bin/plan

depends on
https://github.com/ministryofjustice/cloud-platform-concourse/pull/114
This commit makes the `plan` pipeline use terraform state locking in
the same way as the build pipeline does.
This isn't strictly necessary, but it prevents the plan stage from
happening if the build pipeline is in the middle of applying, to the
same terraform state file.

Lock terraform state during `terraform plan`

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-get-access-service-improvement/03-resourcequota.yaml

* reduce CPU request from 3000m to 10m
* reduce memory request from 6000Mi to 500Mi
* set limit on number of pods to 50
This namespace has been completely empty since May 2019.

Change namespace resourcequota

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/c100-application-production/03-resourcequota.yaml

Jesus has tested deployment into the staging namespace, with the
new quota values, and everything seems to be fine. So this change
brings the production namespace into line with staging.

Change c100-app prod ns. requests to match staging

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/c100-application-production/prometheus.yml

We had this in the deploy repo.
Adding the file to the environments repo so that rules can be deployed and re-created via the pipeline in case of cluster failure (essentially like we do with certificates).

Add prometheus rules to namespace

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-production/resources/route53.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-production/resources/variables.tf

This is to be used to have GDS nameserver
authorities point to - and enable control over
cutover from template-deploy to live-1 servers.

Add DNS hosted zone for cccd-production

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-production/resources/route53.tf

copies of existing template-deploy DNS records
In preparation for having GDS delegate control
for production service.gov.uk domain.

Add cccd production DNS records

---

namespace-resources/03-resourcequota.yaml

related to
https://github.com/ministryofjustice/cloud-platform/issues/1357
If we are going to remove CPU & memory request limits for all
namespaces in the near future, it makes sense to remove those
limits for any new namespaces. The change ensures that new
namespaces only have pod count limits applied, by default.

Remove new namespace CPU & memory request limits

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/track-a-query-production/resources/route53.tf

When creating route53 records with terraform should not be the full name. 
Instead an A record's name should only be the prefix to be addedd to zone name (if any) 
`track-a-query.service.gov.uk.` ->  `.`
`staging.track-a-query.service.gov.uk.` -> `staging`

Track a query r53 records

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/logging/03-resourcequota.yaml

This change removes the cpu and memory request limits from the
logging namespace, and replaces them with a limit of 100 on the
number of pods the namespace may launch.
There are currently 29 pods in the logging namespace, so this
change allows for temporary spikes, e.g. if we were to launch
a full set of new pods before deleting the old ones.

Replace logging request limits with pods: 100

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/authorized-keys-provider/03-resourcequota.yaml

The authorized-keys-provider is running a single container.
This change removes the cpu and memory request limits on the
namespace, and replaces them with a limit of 5 on the number of
pods the namespace may run concurrently.

Replace authorized-keys-provider request limits

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/track-a-query-development/05-certificate.yaml

Use the correct development environment host name - change from `development` to `dev` to match existing dev environment url.

Track a Query - alter development host name for certificate

---

bin/namespace-reporter.rb

We are planning to use pod count limits as the only way namespaces are
restricted. To support this, we will have a page showing a chart of the
number of pods allowed vs. used in each namespace. This change enables that
feature to be built.

Include pods count (limit & used) in the report

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/namespace-usage-report/deployment.yaml

This change uses the latest version of the namespace reporter,
which will display the "pods used vs. pods allowed" page.
depends on #1513

Update the namespace reporter image version

---

bin/apply

The build pipeline pulls a copy of the environments repo at the
start of each run, but it's possible that changes get merged
and applied by the `build-namespace-changes` pipeline after that.
This can cause the following issue:
* Namespace N is in state 1
* `build` pipeline starts, and gets environments repo code showing N in
state 1
* User merges a PR putting N into state 2
* `build-namespace-changes` pipeline puts N into state 2
* build pipeline applies its copy of N source code, and puts N into
state 1
* The next run of the `build` pipeline puts N into state 2
So, the namespace states go N1 -> N2 -> N1 -> N2
This is always confusing, and could cause major issues (e.g. if
the transition from N2 -> N1 causes an RDS instance to be destroyed
and recreated).
This change should fix this issue …

Add a `git pull` before applying every namespace

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-uat/03-resourcequota.yaml

Multiple testers are working in parallel releases under the namespace, and the team is being throttled by the Namespace Quota limits.
Adjusting the quotas to the usage needs.

Adjust 'apply for legal aid' UAT resource quotas

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/c100-application-production/resources/redis.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/c100-application-staging/resources/redis.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-platform-live-dev/resources/service_token_cache.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-platform-live-dev/resources/submitter.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-platform-live-production/resources/service_token_cache.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-platform-live-production/resources/submitter.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-platform-live-staging/resources/service_token_cache.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-platform-live-staging/resources/submitter.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-platform-test-dev/resources/service_token_cache.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-platform-test-dev/resources/submitter.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-platform-test-production/resources/service_token_cache.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-platform-test-production/resources/submitter.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-platform-test-staging/resources/service_token_cache.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-platform-test-staging/resources/submitter.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-publisher-live/resources/publisher.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-publisher-test/resources/publisher.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-frontend-production/resources/redis.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-frontend-staging/resources/redis.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/offender-management-staging/resources/elasticache.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/prison-visits-booking-staging/resources/elasticache.tf

This is the pre-requisite before we work on upgrading tfv0.12
This is related to https://github.com/ministryofjustice/cloud-platform/issues/1363.
The latest elasticache-cluster version have provider and "apply_immediately = true" changes.

Update elasticache-cluster modules to use latest ver

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-legal-adviser-api-staging/resources/variable.tf

- replaced spaces with hyphens in a variable.tf file. 
It seems both variables and uppercases letter are forbidden in the Pingdom resource.

removed spaces from variable.tf in laa api staging

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-api-sandbox/resources/s3.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-dev/resources/s3.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-staging/resources/s3.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-production/resources/s3.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-staging/resources/s3.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-uat/resources/s3.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-legal-adviser-api-production/resources/s3.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-legal-adviser-api-staging/resources/s3.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/offender-categorisation-dev/resources/s3.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/offender-categorisation-preprod/resources/s3.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/offender-categorisation-prod/resources/s3.tf

This is Pre-requisites  for terraform upgrade v0.12
This is related to https://github.com/ministryofjustice/cloud-platform/issues/1363
s3 module v3.0 to v3.3 contains, below changes, which are not effected as the modules i updated are not using these changes.
provider changes 
s3 lifecycle object
user_policy
aws-s3-region tag is removed in v3.2, so we can see a change in this for modules updated from v3.0.

Updated s3 modules to use the latest version

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-dev/serviceaccount-circleci.yaml

Attempt to enable circleci to apply updates to cccd cronjobs,. Currently kubectl apply -f kubernetes_deploy/cron_jobs/archive_stale.yaml but this is failing with in config.yml but this is failing with 'cronjobs.batch "cccd-archive-stale" is forbidden: User "system:serviceaccount:********:circleci" cannot get resource "cronjobs" in API group "batch" in the namespace "********".

Attempt to enable circleci to apply updates to cccd cronjobs

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-api-sandbox/serviceaccount-circleci.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-production/serviceaccount-circleci.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-staging/serviceaccount-circleci.yaml

Add the ability for circleci to update cccd cronjobs in live1 to other cccd namespaces. See also https://github.com/ministryofjustice/cloud-platform-environments/pull/1548.

Add the ability for circleci to update cronjobs to other cccd namespaces

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/track-a-query-staging/resources/s3.tf

Track a Query uses Dropzone in the browser to allow users to upload documents directly into S3. This module amendment will set the appropriate CORS rules for both the cloud platform generated URL and the actual staging.track-a-query domain

Track a Query - Add S3 CORS rules for staging bucket

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-dev/resources/rds.tf

Use latest RDS module version and specify false for `force_ssl`
In line with CP request for upgrading
to terraform v0.12.4

Upgrade cccd-dev's rds terraform module

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-production/certificate.yaml

This is the domain for current (live/template-deploy)
production environment that will need to be the
ingress after cutover.

Add cccd-production certificate for cutover

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/track-a-query-production/resources/route53.tf

Removes DNS A Record in route53 settings for Cloud Platform track a query
This will ensure demo.track-a-query.service.justice.gov.uk is served from cloud platform

Track a Query - remove demo DNS A record

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-api-sandbox/resources/rds.tf

Update to latest CP rds module version
and explcitly set force_ssl false (default
of true for this module would break current
app).
In addition update the rds config inline with other
cccd namespace terraform modules - to use variables
and specify rds engine, storage, class size and family.
Note: not sure what current instance class size it is at
the moment so using what is close to current TD equivalent of `db.m3.medium` --> `db.t3.medium`. Could probably use
default of `db.t2.small` though - happy to change.

Upgrade cccd-api-sandbox rds terraform

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/authorized-keys-provider/resources/s3.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-api-sandbox/resources/s3.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-dev/resources/s3.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-production/resources/s3.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-staging/resources/s3.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/cts-prototype-dev-poc/resources/s3.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-platform-live-dev/resources/json-output-attachments-s3.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-platform-live-dev/resources/user-filestore.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-platform-live-production/resources/json-output-attachments-s3.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-platform-live-production/resources/user-filestore.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-platform-live-staging/resources/json-output-attachments-s3.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-platform-live-staging/resources/user-filestore.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-platform-test-dev/resources/json-output-attachments-s3.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-platform-test-dev/resources/user-filestore.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-platform-test-production/resources/json-output-attachments-s3.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-platform-test-production/resources/user-filestore.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-platform-test-staging/resources/json-output-attachments-s3.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-platform-test-staging/resources/user-filestore.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-production/resources/s3.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-staging/resources/s3.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-uat/resources/s3.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-fala-production/resources/s3.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-fala-staging/resources/s3.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-legal-adviser-api-production/resources/s3.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-legal-adviser-api-staging/resources/s3.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/offender-categorisation-dev/resources/s3.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/offender-categorisation-preprod/resources/s3.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/offender-categorisation-prod/resources/s3.tf

This is prerequisite to upgrade to terraform v0.12
Updated s3 modules to v3.4, this change shouldn't have any effect as v3.3 to v3.4 contains CORS changes, which will only effect when cors_rule is used.

Update s3 modules to use the latest version 3.4

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-staging/resources/rds.tf

Latest rds module version and
explicit setting for force_ssl of
false because default is true and this
would break connectivity at the moment.

Upgrade cccd-staging rds terraform

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-production/resources/rds.tf

Use latest CP rds terraform module but
explictly apply force_ssl false. Default
module force_ssl of true would break current
app.

Upgrade cccd-production rds terraform module

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-dev/resources/messaging.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-production/resources/messaging.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-staging/resources/messaging.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/offender-categorisation-dev/resources/messaging.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/offender-categorisation-preprod/resources/messaging.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/offender-categorisation-prod/resources/messaging.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/offender-events-dev/resources/messaging.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/offender-events-dev/resources/poll-pusher-sub-queue.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/offender-events-preprod/resources/messaging.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/offender-events-preprod/resources/poll-pusher-sub-queue.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/offender-events-prod/resources/messaging.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/offender-events-prod/resources/poll-pusher-sub-queue.tf

Latest module v3.5 contains encryption option.
Modules moved from v3.2(who don't have encryption enabled) will have encrypt_sqs_kms  = "false".
Modules moved from v3.4 (which are already using encryption) will have encrypt_sqs_kms  = "true"

Update sqs module to use the latest version3.5

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/track-a-query-production/resources/route53.tf

Remove the Cloud Platform production DNS entry that points the live domain to old site on template deploy

Track a Query switch production url to Cloud Platform!

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-production/resources/route53.tf

POST MIGRATION only.
To ensure future traffic is directed to
live-1 cccd-production load balancer

remove cccd-production A record pointing to TD load balancer

---

.github/workflows/bin-rspec.yml

This action will run all the rspec tests in the bin/spec
directory whenever a PR is raised, or code is pushed to the
master branch.
Developed and tested in this repo:
https://github.com/digitalronin/github-actions-rspec
The only visible output of this action is to put a green tick or
a red cross against the PR, so it may be desirable in future to
add alerting via Slack, or some other, more 'pro-active' result.
closes https://github.com/ministryofjustice/cloud-platform/issues/1436

Add a github action to run bin/spec tests

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-preprod/resources/s3.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-production/resources/s3.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-staging/resources/s3.tf

This PR adds S3 buckets to our Book A Secure Move API application and stores the secrets so our app can extract them later.
Looking at existing implementations, it doesn't _appear_ to be necessary to add IAM policies as we're just using the generated credentials in our API container.

Adds S3 buckets to Book A Secure Move API environments

---

bin/pipeline.rb
bin/spec/pipeline_spec.rb
bin/spec/spec_helper.rb
bin/spec/terraform_spec.rb

This change is designed to make it easier to alter the
pipeline scripts to accomodate both terraform 12 and
terraform 11 source code.

Refactor bin/pipeline.rb; extract Terraform class

---

bin/pipeline.rb
bin/spec/pipeline_spec.rb
bin/spec/terraform_spec.rb

This change will make the plan, build and apply-namespace changes pipelines
work with source code written for both versions of terraform that we care about
(0.11.14 and 0.12.13).
The existence of a `versions.tf` file is used as a test for terraform 0.12 code
and, if found, will cause the pipeline to run `terraform12` instead of
`terraform` (see the `terraform_executable` method in the `Terraform` class).
terraform12 was added to the tools image by this PR
https://github.com/ministryofjustice/cloud-platform-tools-image/pull/44
Terraform 0.12 requires that any variable passed on the command-line to `plan`
and `apply` is actually used in the relevant source code. We have no way to
know this in advance, so this change depends on
https://github.com/ministryofjustice/cloud-platform-concourse/pul …

Enable our concourse pipelines to work with terraform 0.12 code

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/pathfinder-dev/resources/rds.tf

As v4.7 got issue using path from team-name.
Need to fix the module to upgrade to the latest version.
For now reverting to old version4.5

Revert pathfinder-dev rds version

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/track-a-query-development/05-certificate.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/track-a-query-development/resources/s3.tf

Prefer `development.track-a-query.service.gov.uk` rather than the current `dev.`

Track a Query - Replace dev.track-a-query.service.gov.uk URL

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/check-financial-eligibility-staging/resources/main.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/check-financial-eligibility-staging/resources/rds.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/correspondence-staff-staging/resources/rds.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-legal-adviser-api-staging/resources/rds.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/nomis-api-access-staging/resources/rds.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/prison-visits-booking-staging/resources/rds-prison-visits.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/sentence-planning-preprod/resources/rds.tf

Updated RDS to latest v4.8 from v4.2
This is for all the non-production namespaces
This is pre-requisite to get env repo upgraded to tf0.12

Update RDS to latest v4.8 from v4.2

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/becca-test-app-dev/resources/rds.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-api-sandbox/resources/rds.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-staging/resources/rds.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/cts-prototype-dev-poc/resources/rds.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-platform-live-dev/resources/submitter.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-platform-live-dev/resources/user-datastore.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-platform-test-dev/resources/user-datastore.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-publisher-test/resources/publisher.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmcts-complaints-formbuilder-adapter-staging/resources/rds.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmcts-mock-api-dev/resources/rds.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/keyworker-api-dev/resources/rds.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/keyworker-api-preprod/resources/rds.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-staging/resources/rds.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-dev/resources/rds.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/money-to-prisoners-test/resources/rds.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/parliamentary-questions-development/resources/rds.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/parliamentary-questions-staging/resources/rds.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/probation-core-services-tooling/resources/sonarqube-db.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/track-a-query-demo/resources/rds.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/track-a-query-development/resources/rds.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/track-a-query-qa/resources/rds.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/track-a-query-staging/resources/rds.tf

Update RDS to latest v4.8 from v4.6 and 4.7
This is for all the non-production namespaces
This is pre-requisite to get env repo upgraded to tf0.12

Update rds to latest version 4.8 from 4.6 and 4.7

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-preprod/resources/rds.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-production/resources/rds.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-staging/resources/rds.tf

This PR adds the AWS client ID/secret for RDS so we can inspect snapshots for Book A Secure Move.
It also updates to the latest version of the RDS module.

Book A Secure Move – adds RDS client ID/secret to k8s secrets

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/c100-application-production/resources/rds.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-production/resources/rds.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-prod/resources/rds.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/disclosure-checker-production/resources/rds.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/family-mediators-api-production/resources/rds.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-platform-live-production/resources/submitter.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-platform-live-production/resources/user-datastore.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-platform-test-production/resources/submitter.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-platform-test-production/resources/user-datastore.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-publisher-live/resources/publisher.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmcts-complaints-formbuilder-adapter-production/resources/rds.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/keyworker-api-prod/resources/rds.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-production/resources/rds.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/licences-prod/resources/rds.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/money-to-prisoners-prod/resources/rds.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/offender-case-notes-prod/resources/rds.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/offender-categorisation-prod/resources/rds.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/offender-events-prod/resources/rds.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/pathfinder-prod/resources/rds.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/track-a-query-production/resources/rds.tf

Update RDS to latest v4.8 from v4.5, 4.6 and 4.7
This is for all the production namespaces
This is pre-requisite to get env repo upgraded to tf0.12

Update RDS to latest v4.8 from v4.5, 4.6 and 4.7

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/cp-terraform-module-testing/resources/amq.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/cp-terraform-module-testing/resources/dynamo.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/cp-terraform-module-testing/resources/ecr.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/cp-terraform-module-testing/resources/elasticache.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/cp-terraform-module-testing/resources/elasticsearch.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/cp-terraform-module-testing/resources/main.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/cp-terraform-module-testing/resources/rds.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/cp-terraform-module-testing/resources/s3.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/cp-terraform-module-testing/resources/sns.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/cp-terraform-module-testing/resources/sqs.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/cp-terraform-module-testing/resources/versions.tf

Related to: https://github.com/ministryofjustice/cloud-platform/issues/1460.
Upgrading terraform module to 0.12.13 on testing namespace `cp-terraform-module-testing` to test how pipeline works with both tf 11 and tf12.

Upgrade all modules to terraform 12

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/monitoring/02-limitrange.yaml

Increasing LimitRange from 16Gi to 24Gi for Prometheus.
This is due to seeing Prometheus gradually using more memory over the past month.
We are adding more metrics into Prometheus including a number of new metrics from CloudWatch.
Will continue to closely monitor usage over the next few weeks

Increase LimitRange to 24Gi for Prometheus

---

bin/pipeline.rb
bin/spec/terraform_spec.rb

Now that we have upgraded everything we care about
to terraform 0.12, we don't need branching logic
to run two different versions.
This depends on a change to the concourse pipeline to use
a version of the tools image where the `terraform` command
executes the terraform 0.12 binary.
depends on https://github.com/ministryofjustice/cloud-platform-tools-image/pull/46

Remove multi-version code from the pipeline

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/parliamentary-questions-production/resources/main.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/parliamentary-questions-production/resources/route53.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/parliamentary-questions-production/resources/variables.tf

This PR creates a Route53 hosted zone in the Cloud Platform.
Once created, a secret will be populated  with `zone_id` and `name_servers`, in the relevant namespace.

PQ Route53 Hosted Zone

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-production/resources/pingdom.tf

Have changed ingress to remove default live-1
cluster ingress. Pingdom therefore indicating
it is down as a result.
http://pingdom.service.dsd.io/5404882

Amend pingdom host inline with ingress changes

---

Gemfile

The tools image doesn't install development gems, so we need to
put any gems which are not already installed on the tools image
into a group, so that ruby doesn't try to load them, and complain
when they're missing.

Put development gems into :development group

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/licences-preprod/07-certificates.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/licences-preprod/resources/rds.tf

Create a certificate and a password for new 'probation_teams' schema/role in db shared with licences-preprod

DCS-266 Deploy probation-teams service to preprod. 

---

Gemfile
Gemfile.lock
bin/deleted-namespaces.rb
lib/cp_env/pipeline.rb
spec/pipeline_spec.rb

This script is designed to be executed by a concourse pipeline, whenever a
commit to the environments repo is merged to master. It will send a notification
to #cloud-platform if there are any namespaces which should be deleted. The
notification includes a link to the runbook for 'manually' deleting a namespace
and its AWS resources, using the deleter script.
This is a temporary manual step until we are confident that the only
namespaces which are being flagged for deletion are the right ones.
Subsequent commits will alter this script to delete the namespaces by
itself, and merely notify us that this has happened.

Add a script to notify us about deleted namespaces

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/pathfinder-preprod/resources/s3.tf

This module got a fix for the error 
Error: Error creating IAM User s3-bucket-user-840fd3f2f8b97cc72167c4818098f121: ValidationError: The specified value for path is invalid. It must begin and end with / and contain only alphanumeric characters and/or / characters.

Updated s3 module to v4.1 for pathfinder-preprod

---

bin/delete-namespace.rb
lib/cp_env/namespace_deleter.rb

Previously, the code this was based upon had to 
work on both live-0 and live-1, which are in 
different AWS accounts, so in one cluster we
needed two different sets of AWS credentials.
Now that we only have to worry about live-1, we
can be sure that the same AWS credentials that
give us access to the terraform state files will
also give us access to the kubeconfig file's S3
bucket. So, we can reduce complexity by only
using a single set of AWS credentials.

Re-use AWS creds for terraform & getting kube conf

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-cla-public-staging/resources/ecr.tf

Bad copy-paste job.
We haven't started using it yet, so it's fine if this causes a deletion and recreation of the ecr repo.

Fix ecr secret name in laa-cla-public

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-cla-public-production/06-certificate.yaml

To allow us to set up the production ingress exactly like it will be but using `live1.checklegalaid.service.gov.uk` instead of `checklegalaid.service.gov.uk` so we have as few moving parts as possible when we're getting ready to switch.

Add temporary testing domain to cla-public prod cert

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/parliamentary-questions-development/resources/rds.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/parliamentary-questions-staging/resources/rds.tf

This reverts commit 3bea1fd318cf298bc3566dc1b2896b269822f2d6.
AWS does not allow hyphens in RDS database names (they are allowed
in *instance* names, but not in database names).

Revert "Amend RDS database name"

---

bin/delete_manually_created_pods.rb
lib/cp_env.rb
lib/cp_env/executor.rb
lib/cp_env/manually_created_pod_deleter.rb
lib/cp_env/pipeline.rb
spec/manually_created_pod_deleter_spec.rb

This script will delete any pods which are:
* not part of a ReplicaSet
* and not in kube-system
* and have been running for more than 2 days
Such pods prevent the node-recycler from draining a node to
replace it.
Developers need to run manual pods for tasks such as port-forwarding
to a database, but there's no good reason for such a pod to still be
running after 48 hours. If pods should always be running, they should
be part of a deployment (and hence a ReplicaSet).
NB: This PR adds the script. A subsequent PR will
create a concourse pipeline to execute it daily.

Add script to delete manually-created pods

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-test/00-namespace.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-test/01-rbac.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-test/02-limitrange.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-test/03-resourcequota.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-test/04-networkpolicy.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-test/resources/main.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-test/resources/versions.tf

Creates a test environment / namespace for the `laa-court-data-adaptor` application:
https://github.com/ministryofjustice/laa-court-data-adaptor

Add laa-court-data-adaptor test namespace

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-uat/00-namespace.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-uat/01-rbac.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-uat/02-limitrange.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-uat/03-resourcequota.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-uat/04-networkpolicy.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-uat/resources/main.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-uat/resources/versions.tf

Creates a user acceptance testing environment/namespace for the laa-court-data-adaptor application:
https://github.com/ministryofjustice/laa-court-data-adaptor

Add laa-court-data-adaptor uat namespace

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-stage/00-namespace.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-stage/01-rbac.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-stage/02-limitrange.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-stage/03-resourcequota.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-stage/04-networkpolicy.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-stage/resources/main.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-stage/resources/versions.tf

Creates a user acceptance staging environment/namespace for the laa-court-data-adaptor application:
https://github.com/ministryofjustice/laa-court-data-adaptor

Add laa-court-data-adaptor staging namespace

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-prod/00-namespace.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-prod/01-rbac.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-prod/02-limitrange.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-prod/03-resourcequota.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-prod/04-networkpolicy.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-prod/resources/main.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-prod/resources/versions.tf

Creates a user acceptance production environment/namespace for the laa-court-data-adaptor application:
https://github.com/ministryofjustice/laa-court-data-adaptor

Add laa-court-data-adaptor production namespace

---

spec/fixtures/make-gitops-namespace-test-dev/resources/gitops.tf

Current integration tests fail with the message:
```
Diff:
@@ -1,5 +1,5 @@
module "concourse-gitops" {
-  source                        = "github.com/ministryofjustice/cloud-platform-terraform-gitops"
+  source                        = "github.com/ministryofjustice/cloud-platform-terraform-gitops?ref=tf12"
source_code_url               = "https://foo.bar.baz"
github_team                   = "webops"
namespace                     = "make-gitops-namespace-test-dev"
```
The template module now only references the source from master.

Correct gitops module spec fixtures

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/jason-lab/resources/jason-lab-rds.tf

Adding a new RDS to keep the change pipeline busy long enough to test the concurrency.

add RDS to jason-lab, for testing purposes

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/poornima-dev/resources/rds.tf

Adding a new RDS to keep the change pipeline busy long enough to test the concurrency.

add RDS to poornima-dev, for testing purposes

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-court-data-ui-dev/resources/route53.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-court-data-ui-dev/resources/variables.tf

add hosted zone for laa-court-data-ui environments
to allow custom DNS records.

Add internal (`.justice.`) hosted domain for service

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/dstest/resources/rds.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/dstest/resources/variables.tf

The purpose of this change is to test the delete protection
features for production databases, hence the value of
"is-production" is set to true for the terraform resources.
Later PRs will attempt to delete the RDS instance.
NB: This PR uses a branch of the RDS module repo.

Add a 'production' database to dstest namespace

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/cloud-platform-bots/00-namespace.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/cloud-platform-bots/01-rbac.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/cloud-platform-bots/02-limitrange.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/cloud-platform-bots/03-resourcequota.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/cloud-platform-bots/04-networkpolicy.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/cloud-platform-bots/resources/main.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/cloud-platform-bots/resources/versions.tf

Can be used for any other bots from Cloud Platform team that needs deploying in live-1.

Add new namespace to deploy slack answer bot

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/peoplefinder-demo/resources/s3.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/peoplefinder-staging/resources/s3.tf

I couldn't see the pictures that I synced, I'm hoping it's because of the slash. Sorry to keep doing this!

poeplefinder remove slash from url

---

.gitignore
gitops-namespace-resources/05-deployrole.yaml
gitops-namespace-resources/gitops-resources/deploy-serviceaccount.yaml
lib/cp_env/gitops_gpg_keypair.rb
lib/cp_env/namespace_dir.rb
namespaces/live-1.cloud-platform.service.justice.gov.uk/namespace-usage-report/05-deployrole.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/namespace-usage-report/gitops-resources/deploy-serviceaccount.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/namespace-usage-report/resources/gitops.tf

Overview
---
This PR allows the apply script to execute gitops actions on the EKS manager cluster. To enable this we had to re-work how the gitops pipeline would authenticate to both live and manager clusters and store secrets in live-1 in the application namespace not concourse. 
This PR also contains changes to the live-1 environment `namespace-usage-report` as this will be the first app using gitops.

Gitops pipeline on manager cluster

---

bin/create-gitops-namespace-files.rb
gitops-namespace-resources/resources/gitops.tf
spec/fixtures/make-gitops-namespace-test-dev/00-namespace.yaml
spec/fixtures/make-gitops-namespace-test-dev/05-deployrole.yaml
spec/fixtures/make-gitops-namespace-test-dev/gitops-resources/deploy-serviceaccount.yaml
spec/fixtures/make-gitops-namespace-test-dev/resources/gitops.tf
spec/make_gitops_namespace_spec.rb
spec/namespace_dir_spec.rb

Overview
---
Due to the work carried out in https://github.com/ministryofjustice/cloud-platform-environments/pull/1886 the gitops tests are now failing. This PR excludes the failing tests from running, which will be fixed at a later date.

Fix failing gitops tests

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-dev/resources/cp_test_queue.tf

Updated policy to queue to allow receive message on aws legacy.

Add policy to allow aws legacy to recieve message

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/monitoring/kibana-oauth2-proxy.yaml

This is a temporary thing. When our issue is resolved, we will reinstate the ingress.

re-install kibana, but without the public ingress rule

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/logging/elasticsearch-curator.yaml

The Curator Job was removed in order to prevent any more logs to be deleted, while an incident was being investigated.

Bring back curator cronjob

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-repos/resources/repos.tf

The "fb-submit-product" were using the "fb-pdf-generator" credentials.
The purpose of this PR is to populate kubernetes secrets with correct ecr credentials.

Rename formbuilder submit product ecr credentials

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/monitoring/dashboard-datasource-elasticsearch.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/monitoring/dashboard-datasource-rds.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/monitoring/dashboard-datasource-redis.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/monitoring/dashboard-datasource-sqs.yaml

After this PR (https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/577) is applied in Infrastructure, datasource dashboards can be applied
->   Added cloudwatch datasource dashboard for Redis
https://grafana.com/grafana/dashboards/969
->   Added cloudwatch datasource dashboard for rds
https://grafana.com/grafana/dashboards/707
->    Added cloudwatch datasource dashboard for ES
https://grafana.com/grafana/dashboards/11655
->    Added cloudwatch datasource dashboard for sqs
https://grafana.com/grafana/dashboards/584

Grafana datasource dashboard

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/poornima-staging/resources/rds-mysql.tf

Before merging, the db instance id has to be renamed in order for the db instance to be created in the same db instance id. And hence, the security group, kms key and other parameters matches.

Restoring RDS from older snapshot. 

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/monitoring/dashboard-postgresql-exporter.yaml

Fixed Invalid value: "PostgreSQL exporter metrics" by removed spaces

Fix dashboard-postgresql-exporter-metrics

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/money-to-prisoners-prod/00-namespace.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/money-to-prisoners-test/00-namespace.yaml

…with namespace-specific name prefixes in the form `[namespace]-iam-role-[application-specific]`.
This is to trial cross-account S3 bucket access.

Allow pods in "Prisoner money" namespaces to assume IAM roles

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/peoplefinder-production/resources/route53.tf

Do not merge until maintenance window on Thursday 20th February a.m.
Hoping that this will mean that ingress takes over and peoplefinder.service.gov.uk goes to the CP production site instead of TD.

Remove production alias to template deploy

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/learning-cloud-deployments-dev/03-resourcequota.yaml

This change frees up some CPU and memory in the
cluster which is being unnecessarily 'ring-fenced'
by a sandbox namespace.
In general, we don't want to set request limits
in namespaces - this one must have slipped through
the PR review process.

Remove request limits from dev. namespace

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/disclosure-checker-production/resources/variables.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/disclosure-checker-staging/resources/variables.tf

Now the name of the service has been decided, this makes it more explicit in the `application` variable.
Staging and production environments.

Change application variable to be more explicit

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/c100-application-production/prometheus.yml

We've started getting these quite frequently on deploys (didn't happen before) but in reality they are not quite useful as we have other alerts setup for containers and replicas mismatch.

Remove unneeded alert

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-monitoring/resources/main.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-monitoring/resources/pingdom.tf

This PR adds the pingdom check to the main apps running on formbuilder-services-* namespace.
Within the formbuilder app called fb-publisher, every time a new user create a form and publish the form, we provision 2 more new pods into formbuilder-services-* namespace, with every pod being a single tenant app.
So we decided to go for the route of using Cloud Platform pingdom integration but then it means every time an user publish a new form we need to add here the form. The solution is good for now but will be revised the moment we have more forms than we currently have at the moment.

Add pingdom check to form builder

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-monitoring/resources/pingdom.tf

#1984 and #1997 added the pingdom integration but didn't made public to appear on http://pingdom.service.dsd.io/
Add the flag so it can appear on the link above

Add formbuilder pingdom to public report

---

lib/cp_env/pipeline.rb

This will run kubectl apply --server-dry-run, in plan pipeline.
This is related to `https://github.com/ministryofjustice/cloud-platform/issues/1402`
Tests:
Positive: `https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/plan-environments/jobs/plan-live-1/builds/206#L5e58d7e8:73:85`
Negative: `https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/plan-environments/jobs/plan-live-1/builds/207#L5e58d7f7:74:86`

Update pipeline.rb to add dryrun_kubernetes_files

---

lib/cp_env/pipeline.rb

This is because --server-dry-run is failing on new namespace creation.
error: namespaces not found

Update dryrun_kubernetes_files in pipeline.rb

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-dev/resources/rds.tf

This change has already been `terraform applied`
so the pipeline should do nothing.

Update RDS module from 5.0 to 5.3

---

bin/update-rds-module-version.rb

This script takes a namespace name and:
* Updates terraform source to use RDS 5.3
* Terraform apply
* Gracefully replace all namespace pods
* Raise a PR with the terraform source changes
We need to run the terraform apply ourselves, so that we can immediately
replace the namespace pods so that they pick up the new database credentials.
In theory, we could just rotate the DB credentials and wait for pods to be
replaced naturally, but that increases the risk of application downtime, since
any pod that tries to refresh its database connection will fail because its
credentials are no longer valid.
Also, if this script is executed, and then the build pipeline runs, it will
just revert this change, so we need to get the code into the github repo before
that happens.
So, the process to use this …

Add script to update RDS modules to 5.3

---

bin/namespace-rds-report.rb

The CSV is created by scanning the
namespaces/live-1.cloud-platform.service.justice.gov.uk/ folder, and
analysing the terraform source files.
Outputs a CSV of
* namespace name
* production? "true" / "false"
* RDS name (i.e. name of the terraform RDS instance resource)
* Version number of the CP RDS module

Add a script to output a CSV of RDS info

---

bin/update-rds-module-version.rb

...instead of also sleeping after deleting the last pod in a namespace,
which is unnecessary

Only sleep *between* pod deletions

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/monitoring/kibana-dsd-oauth2-proxy.yaml

This is the proxy for "elasticseach-public-prod" in dsd account.
We used to maintain this in live-0, as live-0 is decommissioned now, created this in live-1.

Add kibana-dsd-proxy-oauth2-proxy

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-staging/resources/rds.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-staging/resources/variables.tf

I think this is now the right plan for reading my staging database from dev - create a new secret in the 'dev' namespace that refers to the read-only database resource in the 'staging' universe.

move read-only secret into k8s 'dev' namespace where it can be picked up

---

bin/find-process-containers.rb

This script iterates over every container running
in the cluster, and looks for a named process
(e.g. 'python'). If it finds the process running,
it outputs the pod and container name.
The original use for this was to identify 
namespaces which might be running django 
applications, but it should work more generally.

Add a script to find specific processes in cluster

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-cla-backend-staging/05-serviceaccount-circleci.yaml

`deployment` seems to have moved to `apps` now, and I think Helm set my new Deployment template up to use that api version. I could change it back to the extensions beta version, but seems more sensible (give none of this is live yet) to go ahead with it in apps and change the service account permissions accordingly

Support deployments now being in apps group

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/kube-system/00-namespace.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/monitoring/04-networkpolicy.yaml

This PR will add a new label to the kube-system namespace and a network policy in the monitoring namespace for it to allow kube-system pods access. 
This is required to get the prometheus rules webhook working within the prometheus-operator.

Add Kube-sysem label and monitoring network policy

---

bin/find-process-containers.rb

Previously, the script would print out every namespace name, including
those with no containers running the relevant process. This change makes
the script 'quieter', only outputting positive results.

Only output namespaces with matching processes

---

makefile

Sometimes we need to be able to run terraform code from inside the same VPC
as the cluster (e.g. code which manipulates an RDS database).
To make this easier, this makefile target launches a temporary tools-image
inside the cluster,  mapping useful environment variables into it.

Add make target for tools shell in the cluster

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/pathfinder-dev/resources/rds.tf

The purpose of this IAM user is to allow a future pod running in the pathfinder namespace to create an RDS to S3 snapshot export. In dev the export will be to an s3 pathfinder reporting bucket configured in the dev namespace. In production the bucket will exist in the MOJ Analytical environment. The MOJ AP will grant permission to this IAM user to put snapshots into their S3 staging bucket.
We decided not to use an assumed role like the prisoner money team do because in theory any other namespace could assume that role and export data from the DB. A specific pathfinder IAM user will contain who can perform the export task and where to.
If the reviewer could check the syntax of creating the iam user and exposing the creds to kubernetes that would be appreciated.
See: …

PAT-708 - add Pathfinder IAM user with rds to s3 export permissions.

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/pathfinder-dev/resources/rds.tf

During testing it turns out we need snapshot access as its the snapshots that are extracted to s3.
Could the reviewer check the policy is correctly setup? I'm not sure if the account id and region are being pulled through correctly. I used the rds template as an example.

PAT-708 - Add snapshot arn to resources

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-staging/resources/rds.tf

It appears that a DB snapshot has its own credentials, not those of the DB that it originally cloned.

use snapshot entity DB credentials rather than staging ones

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-preprod/resources/rds.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-production/resources/rds.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-production/resources/variables.tf

This reverts commit e4f9e4fbc24e143197a6b5966fb348e58be0efd8.
Revert this change, as it was horribly broken - it didn't correctly use the DB snapshot.

Revert "RDS snapshot, from production -> preprod for db repair testing"

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-production/resources/rds.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-production/resources/variables.tf

This is the definitive version of the secure move database snapshot work - but for a production snapshot mounted on preprod

put RDS snapshot on preprod to aid DB repair testing

---

lib/cp_env/manually_created_pod_deleter.rb
spec/manually_created_pod_deleter_spec.rb

Currently, the pipeline to delete manually-created pods runs every 24h,
but the script only deletes such pods when they are more than 48h old.
This change reduces to 24h the age at which a manually-created pod
becomes eligible for deletion.
We recently changed the node recycler to run every 8 hours, 7 days/week,
instead of once/day, Monday to Friday.
This change means the node recycler will spend less time "stuck" waiting
for manually-created pods to be cleared away.
Another option, in future, might be to enable the node recycler to
delete such pods by itself.

Delete manually created pods after 24 hours

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/how-out-of-date-are-we/deployment.yaml

depends on #2203
This version adds a page showing the status of namespaces' terraform
module versions, and has some changes to the API endpoints.

Use how-out-of-date-are-we docker image v. 1.2

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/pathfinder-dev/resources/rds.tf

Now that the role has a random string in its name the arn needs to be exported so that it can be injected into the pod that will run the export script. Also create db snapshot permission required in order to create a temporary snapshot used by the rds to s3 export script.

Further work on RDS to S3 Export IAM policy 

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/pathfinder-dev/resources/rds.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/pathfinder-dev/resources/s3.tf

Rename of S3 bucket to match intended usage. Also having to use eu-west-1 for rds export features only available in Ireland region at the moment and to match up with AP s3 bucket

PAT 730 tidy up bucket names

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-dev/resources/messaging.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-production/resources/messaging.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-staging/resources/messaging.tf

Module version 4.1 is the latest release.
This change brings these namespaces into line with
our policy of always using the latest version of
our terraform modules in all namespaces.
According to `terraform plan`, this change will 
have no effect on their namespace.

Update CCCD namespaces to sns-topic module v4.1

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/offender-events-dev/resources/topic.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/offender-events-preprod/resources/topic.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/offender-events-prod/resources/topic.tf

Module version 4.1 is the latest release.
This change brings these namespaces into line with
our policy of always using the latest version of
our terraform modules in all namespaces.
According to terraform plan, this change will
have no effect on their namespace.

Update offender-events ns to sns-topic module v4.1

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-apply-bot-production/00-namespace.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-apply-bot-production/01-rbac.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-apply-bot-production/02-limitrange.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-apply-bot-production/03-resourcequota.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-apply-bot-production/04-networkpolicy.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-apply-bot-production/resources/main.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-apply-bot-production/resources/versions.tf

This is to deploy an in-development slack bot
so it will require minimal specs and no non-prod
namespaces, it's not envisaged to be business
critical

Add laa-apply-bot-production namespace

---

lib/cp_env.rb
lib/cp_env/executor.rb
lib/cp_env/logger.rb
lib/cp_env/pipeline.rb
lib/cp_env/terraform.rb
spec/logger_spec.rb
spec/pipeline_spec.rb
spec/terraform_spec.rb

This class acts as a single "choke point" for all
command output, so we can locate all of our log
filtering logic there, instead of having to
duplicate it in the Terraform class.
fixes ministryofjustice/cloud-platform#1776

Add a logger class for the concourse pipelines

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-production/resources/rds.tf

This instance is no longer required.
It was breaking the build pipeline with this error:
```
Error: error deleting Database Instance
"cloud-platform-a23ffc9abc15d8ba": DBSnapshotAlreadyExists: Cannot
create the snapshot because a snapshot with the identifier
cloud-platform-a23ffc9abc15d8ba-finalsnapshot already exists.
```
I have manually deleted the snapshot and run `terraform apply` to remove
the RDS instance. So this commit brings the code in the repository into
line with the state of AWS and the cluster.

Remove the rds-snapshot RDS instance

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-staging/resources/rds.tf

This instance is no longer required.
It was breaking the build pipeline with this error:
```
Error: error deleting Database Instance "cloud-platform-2f8c3c1ceaf0a05d": DBSnapshotAlreadyExists: Cannot create the snapshot because a snapshot with the identifier cloud-platform-2f8c3c1ceaf0a05d-finalsnapshot already exists.
status code: 400, request id: 810dcddc-71e8-454f-96b0-2afc4c6b426b
```

Remove rds-snapshot RDS instance

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/interventions-catalogue-service-dev/resources/topic.tf

When I approved the PR that added this topic, I didn't notice that they
were using an older version of the SNS module.
I've checked using terraform plan, and this change applies without
terraform doing anything to their SNS topic.

Update SNS module to version 4.1

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/dstest/resources/redis5.tf

AWS seems to be picky about the value of parameter_group_name
This value works, but the previous `default.redis5.0.6` fails with
```
Error creating Elasticache Replication Group: CacheParameterGroupNotFound: CacheParameterGroup not found: default.redis5.0.6
```

Correct the parameter_group_name

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-platform-live-production/02-limitrange.yaml

We are expecting an increase in traffic across the form builder platform. Also according to Grafana the memory limit for the platform pods operate very close to the limit.
Allocate an additional 200MB for now. We will monitor and increase if required.
https://trello.com/c/3Wrgd4To/458-iterate-on-pa-efile-form-second-iteration

Increase Form Builder platform continer resource memory

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-dev-lgfs/resources/messaging.tf

The previous PR which attempted to create these
AWS resources was failing because of some 
leftover AWS resources created by a failed
terraform apply on 2020-04-17.
I have delete these manually, and this code now
applies cleanly.

Create remaining messaging infra. for LGFS env.

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/contact-moj-production/resources/route53.tf

Note that I'm adding Route53 for a new domain, the new domain is:
contact-moj.service.justice.gov.uk
I'm planning to use Ingress for these as well:
development.contact-moj.service.justice.gov.uk
staging.contact-moj.service.justice.gov.uk
The domain needs setting up. There is a ticket here for that:
https://github.com/ministryofjustice/cloud-platform/issues/1825

Contact MOJ Prod Add Route 53

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/how-out-of-date-are-we/deployment.yaml

This version displays helm release data for both the live-1 and manager
clusters.

Use version 2.0 of the HOODAW image

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/crime-portal-mirror-gateway-dev/05-serviceaccount-circleci.yaml

Creates a circle ci service account. I have read the page here https://user-guide.cloud-platform.service.justice.gov.uk/documentation/deploying-an-app/use-circleci-to-upgrade-app.html#requirements but that links to K8S web page rather than terraform. 
Please let me know what else I need to do or what else I need to read thanks

pic-412 added circleci service account

---

bin/rotate-rds-password.rb

supersedes #2035
This script will:
* taint the random_password.password of the RDS instance
* terraform apply to replace the password and kubernetes secret
* gracefully cycle all the namespace pods

Add a script to rotate RDS credentials

---

lib/cp_env/namespace_dir.rb

This is due to the context name changing in the kubeconfig file

Change the MANAGER_CLUSTER context name

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/pathfinder-dev/resources/s3.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/pathfinder-dev/resources/variables.tf

Pathfinder has an S3 bucket to hold documents uploaded and associated with its cases. When a document is deleted by a service user, it is moved to a DELETED/ prefix where a lifecycle policy is set, with a filter, to expire them after x number of days. The Pathfinder service needs to set the expiry days based on configuration so that it can be different in different environments, and when running locally for development. This PR sets a user_policy on the Pathfinder document bucket to allow the life cycle policy to be set and viewed via AWS CLI (for support reasons) and programatically by the service to match-up with its configured expiry time.
Affects - only the Pathfinder document s3 bucket permissions.

PAT-818  - Allow Pathfinder service to set/view bucket lifecycle policy

---

bin/delete_unused_dns_records.rb

This script will be used in a concourse pipeline to regularly prune the
main live-1 hosted zone.

Add a script to delete surplus DNS A & TXT records

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-monitoring/resources/pingdom.tf

The Apply to be a Financial Deputy form is going live today. This just
adds the pingdom check for when it is published.

Form Builder pingdom for Apply Financial Deputy Form

---

bin/delete_unused_dns_records.rb

It will be useful to have the list of records the script tried to delete
in the concourse job logs. So, we can always log the records, and just
do nothing else if the "-l" or "--list" flag was supplied.

Always log affected DNS records

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/offender-management-production/serviceaccount-circleci.yaml

I've updated the CircleCI service account permissions to allow it to deploy Certificate resources. This follows a recent change to the MOJ Cloud Platform.

Update CircleCI service account permissions

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/logging/02-limitrange.yaml

The fluentd pod on the main master keeps getting OOM killed. So, even
though all the other fluentd pods consume 70m or less, this PR doubles
the memory limit for pods in the logging namespace to 1000m

Increase memory limit for logging containers to 1G

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/logging/02-limitrange.yaml

The previous memory limit increase seems to have helped accidentally,
but I was looking at the wrong column of figures, and what the pod
really wants is more CPU. Hence this change.

Increase the CPU limit for logging containers

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-cla-public-production/05-serviceaccount-circleci.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-cla-public-staging/05-serviceaccount-circleci.yaml

Adds 'deployments' in 'apps' and 'ingresses' in 'networking.k8s.io' for
new setup.
Keeps the old permissions (in apiGroup 'extensions') around for now,
until our Helm deploy has fully replaced our existing k8s one and the
existing objects are no longer needed.

Add laa-cla-public permissions in new apiGroups

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-cla-backend-staging/resources/redis.tf

I've spoken with the developer, and they're happy to stick with redis 5

Use default redis version (5)

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-cla-backend-staging/resources/s3.tf

Users could read but not write to this bucket. The policy change has been tested locally and this performs as expected.

Amend S3 policy to allow user write access

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/prison-data-compliance-preprod/resources/iam.tf

The Analytical platform team have created a role which has a trust relationship with this user, therefore enabling this user to assume it.  The role allows the user to execute Athena queries and gives access to a limited and required set of S3 buckets.

GDPR-123 Assuming Analytical Platform Athena role

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/crime-portal-mirror-gateway-dev/05-certificates.yml

To fix the DNS name to dev.crime-portal-mirror-gateway.service.justice.gov.uk for certificates.yml

Update to DNS name in certificates.yml

---

spec/spec_helper.rb

This helper method is supposed to check that one directory
matches another, in terms of the names of the files in each directory.
But, the ordering of files returned by `Dir[]` is not guaranteed, so
sometimes the check fails because, e.g.
```
[a, b, c] != [b, a, c]
```
This change sorts each list before comparing, which should prevent these
kinds of false failures.

Sort lists of files before comparing

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-dev/resources/messaging.tf

New covid-19 related "hardship" claim types to be filtered onto relevant queues.

Amend cccd-dev SNS filter policy to allow new claim types

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-production/resources/messaging.tf

Amend cccd-production SNS filtering for litigator hardship claims
Activates "data injection" of litigator hardship claims (only)
from CCCD into CCLF.
This is a new claim type that has only recently been added
to handle covid-19 impact on provider cash flow.

Amend cccd-production SNS filtering for litigator hardship claims

---

bin/find-deprecated-objects.rb

This script will output a CSV report listing all objects which
use API versions deprecated in kubernetes 1.16
It also lists *all* tiller pods (not just those which are too old)
fixes https://github.com/ministryofjustice/cloud-platform/issues/1942

Add script to find deprecated kubernetes objects

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-dev/resources/pingdom.tf

Add `resources/pingdom.tf` to enable pingdom checks for the `laa-court-data-adaptor-dev`.

Add Pingdom check to laa-court-data-adaptor-dev

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-dev/resources/pingdom.tf

The owner tag in pingdom.tf is failing validation because of a @. This removes the tag.

Remove owner tag

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/probation-prod/00-namespace.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/probation-prod/01-rbac.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/probation-prod/02-limitrange.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/probation-prod/03-resourcequota.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/probation-prod/04-networkpolicy.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/probation-prod/resources/main.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/probation-prod/resources/route53.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/probation-prod/resources/versions.tf

This PR creates the standalone namespace `probation-prod`.
This NS is used to create the Route53 zone `probation.service.justice.gov.uk`, which is needed for subdomains.

Probation zone

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/prisoner-content-hub-production/resources/elasticsearch.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/prisoner-content-hub-production/resources/variables.tf

We need to add elasticsearch to support the migration of the content hub into cloud platform.
This PR: 
- fixes the team name to ensure it is dash separated and works with the elasticsearch module
- Added elasticsearch module

Add elasticsearch to Prisoner content hub

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-platform-pentest-dev/00-namespace.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-platform-pentest-dev/01-rbac.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-platform-pentest-dev/02-limitrange.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-platform-pentest-dev/03-resourcequota.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-platform-pentest-dev/04-networkpolicy.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-platform-pentest-dev/av-service-account.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-platform-pentest-dev/circleci-service-account.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-platform-pentest-dev/pdf-generator-service-account.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-platform-pentest-dev/resources/json-output-attachments-s3.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-platform-pentest-dev/resources/main.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-platform-pentest-dev/resources/service_token_cache.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-platform-pentest-dev/resources/submitter.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-platform-pentest-dev/resources/user-datastore.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-platform-pentest-dev/resources/user-filestore.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-platform-pentest-dev/resources/variables.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-platform-pentest-dev/resources/versions.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-platform-pentest-dev/service-token-cache-service-account.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-platform-pentest-dev/submitter-workers-service-account.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-platform-pentest-dev/user-datastore-service-account.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-platform-pentest-dev/user-filestore-service-account.yaml

Form Builder is going to have penetration testing done on their platform and services. This adds the dev namespace for that purpose.
https://trello.com/c/wV1szkzk/592-set-up-pentest-environment
Co-authored-by Matt Tei <matt.tei@digital.justice.gov.uk>
Co-authored-by Tomas Destefi <tomas.destefi@digital.justice.gov.uk>

Add Form Builder pentest dev platform environment

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/prisoner-content-hub-production/resources/rds.tf

This PR adds an RDS resource for the `prisoner-content-hub-production` namespace.
It can't be merged until the custom_parameters change that's being tested in master is released. I've assumed that'll be `5.4` but that needs checking!

Add MariaDB RDS module

---

makefile
namespaces/live-1.cloud-platform.service.justice.gov.uk/authorized-keys-provider/provider.yaml

This version pins the gov.uk concourse provider to v5.8.0, which should
fix a problem where the apply pipeline breaks for 'gitops' namespaces.

Use tools image 1.18

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-dev/06-serviceaccount-circleci.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-preprod/06-serviceaccount-circleci.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-production/serviceaccount-circleci.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-staging/serviceaccount-circleci.yaml

Allow book-a-secure-move's CircleCI service accounts to manage jobs and cronjobs.

Book a secure move circleci permissions

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/poornima-dev/resources/rds.tf

To test RDS module related to: https://github.com/ministryofjustice/cloud-platform/issues/1859

Test read replica

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-services-pentest-production/00-namespace.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-services-pentest-production/01-rbac.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-services-pentest-production/02-limitrange.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-services-pentest-production/03-resourcequota.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-services-pentest-production/04-networkpolicy.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-services-pentest-production/certificate.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-services-pentest-production/circleci-service-account.yaml

This adds the Form Builder services namespace production required for the penetration testing.
https://trello.com/c/wV1szkzk/592-set-up-pentest-environment

Add Form Builder services namespace in production for pen test

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-publisher-pentest/00-namespace.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-publisher-pentest/01-rbac.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-publisher-pentest/02-limitrange.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-publisher-pentest/03-resourcequota.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-publisher-pentest/04-networkpolicy.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-publisher-pentest/circleci-service-account.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-publisher-pentest/publisher-workers-service-account.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-publisher-pentest/resources/main.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-publisher-pentest/resources/publisher.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-publisher-pentest/resources/variables.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-publisher-pentest/resources/versions.tf

This adds the Form Builder publisher namespace required for the penetration testing.
https://trello.com/c/wV1szkzk/592-set-up-pentest-environment

Add Form Builder publisher namespace for pentest

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/prison-visits-booking-staging/resources/ecr-prison-visits-tests.tf

The PVB team are moving the integration and smoke tests from Jenkins to Circle:CI, but the tests need to run inside the K8S cluster. This repo is where we store the images for those tests

Add ECR repo for prison-visits-integration-tests

---

bin/auto-delete-namespace.rb

concourse pipleline "destroy-deleted-namespaces" run this script to detect
deleted namespaces and delete all AWS resources belonging to the deleted
namespace, and will then delete the namespace itself from the live-1 cluster.

Add auto-delete-namespace

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-repos/resources/repos.tf

We are adding a new app to some of our environments and need to have an
ECR repo for this.
https://trello.com/c/32QuD95Z/699-deploy-base-adapter-in-pentest-environment
Co-authored-by Tomas Destefi <tomas.destifi@digital.justice.gov.uk>
Co-authored-by Matt Tei <matt.tei@digital.justice.gov.uk>

Add Form Builder ECR base adapter repository

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/prepare-a-case-prod/07-certificates.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/prepare-a-case-prod/resources/route53.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/prepare-a-case-prod/resources/variables.tf

Changes domain to to prepareacase-probation.service.justice.gov.uk
Updated certificate.yaml to support change
Signed-off-by: Paul Massey <paul.massey@digital.justice.gov.uk>

prepare-a-case route53 and certificate change

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-dev/06-serviceaccount-circleci.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-preprod/06-serviceaccount-circleci.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-production/serviceaccount-circleci.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-staging/serviceaccount-circleci.yaml

Hi, 
adding some more  permission to our CircleCI service account so that it can pull logs.
Useful to inspect the outcome of one-off jobs, such as migrations.

Allow CircleCI to fetch pods logs

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-base-adapter-test/circleci-service-account.yaml

Add CircleCI as service account for formbuilder base adapter in test environment.

Add CircleCI service account to form builder adapter base test

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/offender-events-dev/resources/manage-soc-cases-sub-queue.tf

* Creates queues for manage-soc-cases
* Subscribes this service to the same topics/filters as Pathfinder
* Exports secrets to the manage-soc-cases-dev namespace

PAT-938: Adding queues and subscriptions for service manage-soc-cases

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/money-to-prisoners-prod/05-service-accounts.yaml

…to allow access to deployments in both legacy "extensions" and new "apps" api groups.
#2551 already did this for the test namespace

Update RBAC role for prisoner money pod service account in production namespace

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/money-to-prisoners-prod/resources/rds.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/money-to-prisoners-test/resources/rds.tf

… removing `apply_method` parameter which did nothing since it only applied to `force_ssl` which is on by default (and therefore already applied to all instances)

Update RDS module for Prisoner Money namespaces

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/manage-soc-cases-dev/resources/route53.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/manage-soc-cases-dev/resources/variables.tf

As this service is only present in dev (until it undergoes pen test & DPIA process), the dev instance requires a DNS entry for ingress.

PAT-998: Add DNS record for manage-soc-cases-dev

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-services-pentest-dev/01-rbac.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-services-pentest-production/01-rbac.yaml

The "formbuilder-publisher-pentest" namespace was not having access to "formbuilder-services-pentest-dev" and "formbuilder-services-pentest-production" namespace.
We are suspecting that this will solve the problem.
Co-authored-by: Matt Tei <matt.tei@digital.justice.gov.uk>

Fix formbuilder publisher service accounts for pentest namespace

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-services-pentest-dev/certificate.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-services-pentest-production/certificate.yaml

The pentest environments had the wrong DNS names
Co-authored-by Tomas Destefi <tomas.destifi@digital.justice.gov.uk>
Co-authored-by Matt Tei <matt.tei@digital.justice.gov.uk>

Update formbuilder pentest cert DNS Names

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/peoplefinder-demo/resources/rds.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/peoplefinder-development/resources/rds.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/peoplefinder-production/resources/rds.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/peoplefinder-staging/resources/rds.tf

- Remove apply_method = "pending-reboot" as this affects only if the force_ssl state changes. Part of db_parameter variable now.
- Update to latest version

Update rds module for peoplefinder namespaces

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/offender-events-preprod/resources/cfo-sub-queue-perf.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/offender-events-preprod/resources/cfo-sub-queue.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/offender-events-preprod/resources/topic-perf.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/offender-events-prod/resources/cfo-sub-queue.tf

1. Add preprod/prod queues for CFO
2. Create secondary versions for these queues that can be attached to Delius Perf environment (rather than creating a whole new namespace that will have nothing in except secrets for a couple of queues)

CFO queues for preprod/prod and perf queue/topic just for CFO

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/how-out-of-date-are-we/deployment.yaml

There are no changes to the web application, but this keeps the version
numbers in sync between this namespace and the concourse pipeline.

Use HOODAW docker image v2.9

---

bin/create-gitops-namespace-files.rb

The 'namespace_questions.rb' file was renamed to 'namespace_creation.rb'
but I forgot to change it here.

Bugfix: Requiring a file that doesn't exist

---

gitops-namespace-resources/00-namespace.yaml
namespace-resources/00-namespace.yaml
spec/fixtures/make-gitops-namespace-answers.yaml
spec/fixtures/make-gitops-namespace-test-dev/00-namespace.yaml
spec/fixtures/make-namespace-answers.yaml
spec/fixtures/make-namespace-test-dev/00-namespace.yaml

it should be "slack-channel" throughout, not
"slack_channel" for the key but "slack-channel" as
the value.
Also, I forgot we had rspec tests for this, so
I've slapped myself on the wrist.

Bugfix: interpolate slack channel correctly

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-api-sandbox/serviceaccount-circleci.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-dev-lgfs/serviceaccount-circleci.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-dev/serviceaccount-circleci.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-production/serviceaccount-circleci.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-staging/serviceaccount-circleci.yaml

`networking.k8s.io` has replaced `extensions` for ingress
config.
get this error via circleci deployment  - which i believe is because this apiGroup is not availble to it?!
```
Error from server (Forbidden): error when retrieving current configuration of:
Resource: "networking.k8s.io/v1beta1, Resource=ingresses", GroupVersionKind: "networking.k8s.io/v1beta1, Kind=Ingress"
Name: "cccd-app-ingress", Namespace: "********"
Object: &{map["metadata":map["name":"cccd-app-ingress" "namespace":"********" "annotations":map["kubectl.kubernetes.io/last-applied-configuration":""]] "spec":map["rules":[map["host":"dev.claim-crown-court-defence.service.justice.gov.uk" "http":map["paths":[map["backend":map["serviceName":"cccd-app-service" "servicePort":'P'] "path":"/"]]]]] …
```

Add permission to service account for new ingress api

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-court-data-ui-dev/serviceaccount-circleci.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-court-data-ui-production/serviceaccount-circleci.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-court-data-ui-staging/serviceaccount-circleci.yaml

Add networking.k8s.io to serviceaccount apiGroups - applying ingress is failing in CircleCI with Error from server (Forbidden): error when retrieving current configuration of:
Resource: "networking.k8s.io/v1beta1, Resource=ingresses", GroupVersionKind: "networking.k8s.io/v1beta1, Kind=Ingress"

Add networking.k8s.io to serviceaccount apiGroup

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/crime-portal-mirror-gateway-dev/04-networkpolicy.yaml

This network policy is allowing traffic from court-probation-dev to crime-portal-mirror-gateway-dev.

add network policy to accept traffic from court-probation-dev

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/prison-visits-booking-staging/serviceaccount-circleci.yaml

We need to be able to track job progress when running remove interation tests via circle.
This PR adds the permission I think we need in order for that to be allowed via circle

Prison Visis Staging Add pods/log resource access to circle service account

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/prison-visits-booking-staging/serviceaccount-circleci.yaml

Prison-visits-booking still can't wait for its integration tests on circle:ci. 
This is a second attempt to add the permission to make this possible - it adds a 'watch' verb (?!?) permission which I'm hoping will fix the problem

2nd attempt at giving circle permission to wait for integration test job

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/offender-search-dev/09-certificates.yml

I was getting "CSR doesn't contain a SAN short enough to fit in CN" error with the old name which was 67 characters

shorten DNS name to be within 63 characters

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/crime-portal-mirror-gateway-dev/04-networkpolicy.yaml

This change should allow all traffic from the namespace labelled `court-probation-dev` to flow to the `crime-portal-mirror-gateway-dev` namespace

modify the namespaceSelector label 

---

bin/find-deprecated-objects.rb

* Stop searching for Ingresses with kubectl
All ingresses show up as using the deprecated APIs
Some of the time this might be valid, but a lot of
the time it's not, and there's no easy way to tell
which is which. So this change simply stops
searching for Ingresses in this way, to avoid a
lot of false alerts.
* Only report kubectl objects when the api version
matches the one in the last-applied-configuration
This should avoid false alerts about helm 
deployments which *have* been updated, but the
object still shows up as using the old API
(because kubernetes sees the update as a noop, 
since the old API is still valid).

Update the find-deprecated-objects script

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/c100-application-dev/serviceaccount-circleci.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/c100-application-production/serviceaccount-circleci.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/c100-application-staging/serviceaccount-circleci.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/disclosure-checker-production/serviceaccount-circleci.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/disclosure-checker-staging/serviceaccount-circleci.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/family-mediators-api-production/serviceaccount-circleci.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/family-mediators-api-staging/serviceaccount-circleci.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/fj-cait-production/serviceaccount-circleci.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/fj-cait-staging/serviceaccount-circleci.yaml

To ensure everything continues to work after the Kubernetes 1.16 upgrade.

Update ServiceAccount apiGroups permissions

---

lib/cp_env/namespace_deleter.rb

The namespace deleter fetches an "empty" `main.tf` file from github. Now
that we have changed the default branch of the environments repo to
"main", the URL to fetch that file was incorrect. This PR fixes that.

Update namespace deleter wrt. "master" -> "main"

---

lib/cp_env/namespace_deleter.rb
spec/namespace_deleter_spec.rb
spec/pipeline_spec.rb

The namespace deleter will not delete a production namespace, but the
concourse pipeline still shows as successful, so we don't get a slack alert
to go and clean up the namespace manually.
This change fixes that.
fixes https://github.com/ministryofjustice/cloud-platform/issues/2047

Raise an error when we can't delete a namespace

---

.github/workflows/bin-rspec.yml
spec/fixtures/make-gitops-namespace-test-dev/resources/gitops.tf
spec/pipeline_spec.rb

This workflow was only monitoring the "master" branch, so after the
switch to "main" the rspec tests have not been running.

Run the rpec tests on PRs

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/prisoner-content-hub-staging/00-namespace.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/prisoner-content-hub-staging/01-rbac.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/prisoner-content-hub-staging/02-limitrange.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/prisoner-content-hub-staging/03-resourcequota.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/prisoner-content-hub-staging/04-networkpolicy.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/prisoner-content-hub-staging/05-serviceaccount-circleci.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/prisoner-content-hub-staging/resources/elasticsearch.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/prisoner-content-hub-staging/resources/main.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/prisoner-content-hub-staging/resources/rds.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/prisoner-content-hub-staging/resources/s3.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/prisoner-content-hub-staging/resources/variables.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/prisoner-content-hub-staging/resources/versions.tf

This PR copies [prisoner-content-hub-production](https://github.com/ministryofjustice/cloud-platform-environments/tree/main/namespaces/live-1.cloud-platform.service.justice.gov.uk/prisoner-content-hub-production) to create a staging namespace.
Differences to `production`:
- `is-production` is `false`
- names containing `production` updated to `staging`
This is the partner to #2725, which does the same thing for development.

Create staging environment for Prisoner Content Hub

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/prisoner-content-hub-development/00-namespace.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/prisoner-content-hub-development/01-rbac.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/prisoner-content-hub-development/02-limitrange.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/prisoner-content-hub-development/03-resourcequota.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/prisoner-content-hub-development/04-networkpolicy.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/prisoner-content-hub-development/05-serviceaccount-circleci.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/prisoner-content-hub-development/resources/elasticsearch.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/prisoner-content-hub-development/resources/main.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/prisoner-content-hub-development/resources/rds.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/prisoner-content-hub-development/resources/s3.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/prisoner-content-hub-development/resources/variables.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/prisoner-content-hub-development/resources/versions.tf

This PR copies [prisoner-content-hub-production](https://github.com/ministryofjustice/cloud-platform-environments/tree/main/namespaces/live-1.cloud-platform.service.justice.gov.uk/prisoner-content-hub-production) to create a development namespace.
Differences to `production`:
- `is-production` is `false`
- names containing `production` updated to `development `
This is the partner to #2724, which does the same thing for `staging`.

Create development environment for Prisoner Content Hub

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-legal-adviser-api-staging/05-serviceaccount-circleci.yaml

Keep existing permissions until we no longer have any of those objects
around and can clean up

Add service account perms for new api resources

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/prisoner-content-hub-development/00-namespace.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/prisoner-content-hub-development/01-rbac.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/prisoner-content-hub-development/02-limitrange.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/prisoner-content-hub-development/03-resourcequota.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/prisoner-content-hub-development/04-networkpolicy.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/prisoner-content-hub-development/05-serviceaccount-circleci.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/prisoner-content-hub-development/resources/elasticsearch.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/prisoner-content-hub-development/resources/main.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/prisoner-content-hub-development/resources/rds.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/prisoner-content-hub-development/resources/s3.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/prisoner-content-hub-development/resources/variables.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/prisoner-content-hub-development/resources/versions.tf

Another attempt to get Prisoner Content Hub's dev namespace working. 
This PR contains the "fixed" version from before, with London as the primary region. Hopefully applying it cleanly now the previous incarnation has been reverted/destroyed will work...

Prisoner content hub development namespace

---

.github/workflows/bin-rspec.yml

The vast majority of the commits and PRs to this repo are to
sub-directories of `namespaces/` For these changes, there is no point
running the specs because they're not relevant.
Github action execution minutes are a limited resource, so we don't want
to waste them. Running unnecessary checks also means we have to wait
longer before we can approve a PR.
This change restricts this github action to only run when *relevant*
changes are proposed/made.

Only run the specs when relevant files are changed

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-cla-backend-production/resources/rds.tf

This fixes the replica creating with default rds values instead of source rds instance.

Update replica to have similar settings as source db

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/prisoner-content-hub-development/resources/rds.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/prisoner-content-hub-development/resources/s3.tf

The prisoner-content-hub-development namespace is using outdated
versions of our s3 & rds modules.
I've done a manual `terraform plan` with these changes, and there were
no changes reported to either the S3 bucket or the RDS instance.
There were some apparent changes planned to IAM policies, but those seem
to be a red herring - i.e. changes with no semantic impact.

Use latest S3 & RDS modules

---

namespace-resources-cli-template/00-namespace.yaml
namespace-resources-cli-template/01-rbac.yaml
namespace-resources-cli-template/02-limitrange.yaml
namespace-resources-cli-template/03-resourcequota.yaml
namespace-resources-cli-template/04-networkpolicy.yaml
namespace-resources-cli-template/resources/main.tf
namespace-resources-cli-template/resources/variables.tf
namespace-resources-cli-template/resources/versions.tf

These template files are used by the [cloud-platform-cli ](https://github.com/ministryofjustice/cloud-platform-moj-cp) to create namespace for end users of cloud platform
Related to: https://github.com/ministryofjustice/cloud-platform/issues/1961

Template files referenced when creating namespace using cloud-platform CLI

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/prisoner-content-hub-production/00-namespace.yaml

We recently renamed our repository from `digital-hub` to [`prisoner-content-hub` ](https://github.com/ministryofjustice/prisoner-content-hub). 
This PR updates the `prisoner-content-hub-production` namespace to use the new repo name.

Update Prisoner Content Hub repo name

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-dev-lgfs/certificate.yaml

Extend certificate to cover additional dnsname for cccd-dev-lgfs
Repurposing of environment for spike work related
to Civil legal aid review (CLAR) - to enable tester/users to 
access site at subdomain `dev-clar`.

Add dns name for cccd-dev-lgfs ingress

---

.github/workflows/reject-multi-namespace-prs.yml

This PR enables a new github action, which prevent PRs from spanning multiple namespaces.

New GH action to reject multi-namespace PR

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/how-out-of-date-are-we/deployment.yaml

related to
https://github.com/ministryofjustice/cloud-platform-how-out-of-date-are-we/pull/36
part of
https://github.com/ministryofjustice/cloud-platform/issues/1928

Update HOODAW web app. to version 2.11

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-dev/serviceaccount.yml

Hi, I'm updating our manifest files for k8s 1.16 compatibility. Our current service accounts contain no Roles / RoleBindings. These are currently located in separate files: [Role](https://github.com/CriminalInjuriesCompensationAuthority/data-capture-service/blob/master/kube_deploy/Dev/cirole.yml) and [RoleBinding](https://github.com/CriminalInjuriesCompensationAuthority/data-capture-service/blob/master/kube_deploy/Dev/cirolebind.yml). I wasn't involved in configuring CircleCI so I'm not sure how these have been applied in the past.
This PR adds these to our service account and includes the additional "apps" and "networking.k8s.io" as per the [upgrade instructions](https://user-guide.cloud-platform.service.justice.gov.uk/documentation/other-topics/apiversion-changes-k8s-1-16.html).
Is it …

Add Role/RoleBinding to cica dev service account

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/prison-visits-booking-staging/serviceaccount-circleci.yaml

Namespace: `prison-visits-booking-staging`

PVB staging: Grant CircleCI access to new Kube 1.16 APIs

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/prison-visits-booking-production/serviceaccount-circleci.yaml

Namespace: `prison-visits-booking-production`

PVB production: Grant CircleCI access to new Kube 1.16 APIs

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/offender-management-staging/serviceaccount-circleci.yaml

Namespace: `offender-management-staging`

MOIC staging: Grant CircleCI access to new Kube 1.16 APIs

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/offender-management-preprod/serviceaccount-circleci.yaml

Namespace: `offender-management-preprod`

MOIC preprod: Grant CircleCI access to new Kube 1.16 APIs

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/offender-management-production/serviceaccount-circleci.yaml

Namespace: `offender-management-production`

MOIC production: Grant CircleCI access to new Kube 1.16 APIs

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/prisoner-content-hub-production/resources/route53.tf

The `prisoner.service.justice.gov.uk` domain is managed in Azure by a separate team.
We would like to sit the Prisoner Content Hub under `content-hub.prisoner.service.justice.gov.uk`, and shift management into Cloud Platform/route53.
This PR creates the Route53 zone for `content-hub.prisoner.service.justice.gov.uk`. Once it's been created, we'll need to set up delegation on the upstream name servers.

Add route53 zone for Prisoner Content Hub

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/prisoner-content-hub-production/06-certificates-cms.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/prisoner-content-hub-production/07-certificates-frontend.yaml

We created a Route53 zone in #2821.
This PR adds two certificates, one for the CMS application and another for the Node frontend.
The frontend certificate has multiple hostnames (one for each prison we support).

Add certificates for prisoner content hub CMS and frontend

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/how-out-of-date-are-we/deployment.yaml

blocked by
https://github.com/ministryofjustice/cloud-platform-how-out-of-date-are-we/pull/40
This version exposes JSON endpoints for all the report pages.

Use HOODAW web app. image 2.14

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/mogaal-test/04-networkpolicy.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/mogaal-test/resources/ingress.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/mogaal-test/resources/main.tf

- New network policy which accepts all traffic to ingress controller pods (nginx)
- Added the ingress controller terraform module

New network policy and ingress controller module

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/mogaal-test/00-namespace.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/mogaal-test/04-networkpolicy.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/mogaal-test/resources/ingress.tf

- Reverting network policies (not needed the custom one anymore)
- Not need to create LB within the team's namespace
- Testing the latest nginx ingress module

Refactor ingress implementation

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-cla-backend-production/resources/rds.tf

This should give us 750 Base Performance (IOPS) according to https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_Storage.html

Increase production database size to get better base performance iops

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-cla-backend-production/resources/rds.tf

Due to slow performing queries in the laa-cla-backend app we had to increase the spec of the RDS instance. The work to optimize these queries will be done after the migration process.

Increase RDS instance spec due to slow queries

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/authorized-keys-provider/provider.yaml

Why:
Ticket [KubeDeploymentReplicaMismatch#2119](https://app.zenhub.com/workspaces/cloud-platform-team-5ccb0b8a81f66118c983c189/issues/ministryofjustice/cloud-platform/2119)
Temporarily set replica's to zero - to silence this alert - whilst work being carried out re authorized-keys-provider

silence alert until authorized-keys-provider procedure modified

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-product-page-staging/00-namespace.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-product-page-staging/formbuilder-product-page-staging-service-account.yaml

We are attempting to setup up Github Actions for one of our repos in staging. This service account will be used by Github Actions to access secrets and to apply changes etc.
Also fix typo
Co-authored-by: Matt Tei <matt.tei@digital.justice.gov.uk>

Add Form Builder github actions service account for product page

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-cla-backend-production/resources/rds.tf

Preliminary tests with 3 concurrent users seem to have significant decrease of site response times. Restoring current database specs to carry out further testing

Restore usage of db.m4.4xlarge instance size

---

namespace-resources-cli-template/05-serviceaccount.yaml

This file will be used by the `cloud-platform-cli` tool and links to
issue https://github.com/ministryofjustice/cloud-platform/issues/2059.

Add template serviceaccount file to cli templates

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-monitoring/resources/pingdom.tf

New form is going live for reporting security incidents. This adds the pingdom check for the live form.
https://trello.com/c/U9pnDhSS/569-plan-delivery-of-security-incident-form-with-stakeholders

Add report security incident pingdom check

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-product-page-prod/formbuilder-product-page-prod-service-account.yaml

This just adds the service account for the production namespace of the form builder product page

Add Form Builder product page production Service Account

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/pathfinder-prod/02-limitrange.yaml

Increase memory limit in PROD namespace.
This has already been applied successfully (and fixed the issue) in the DEV namespace.

PAT-1167: Pathfinder increase default memory limit - PROD namespace

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/pathfinder-preprod/02-limitrange.yaml

Already applied in DEV & PROD - this increases the memory limits for Pathfinder in PREPROD.

PAT-1167: Increase Pathfinder default memory limit in PREPROD namespace

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/manage-soc-cases-dev/02-limitrange.yaml

The same issue as affected Pathfinder also affects Manage SOC cases - but this only has a DEV namespace.
Increases default memory limit from 1Gb to 2Gb to cater for increased demand of the clamav pods.

PAT-1168: Increase default memory limit to 2Gb for manage-soc-cases - DEV namespace

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/prisoner-content-hub-production/resources/pingdom.tf

The email address may be the cause of the build failure in https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/environments-terraform/jobs/apply-namespace-changes-live-1/builds/284\#L5f2aeb61:135. This swaps it out for a dns-compliant team name.
While this isn't ideal (because `pfs` isn't that meaningful and doesn't have an email address), in the context of the other tags you could _probably_ end up in the right place. It also looks like other teams have taken this approach.

Swaps out email address for team name in Pingdom resource.

---

namespace-resources-cli-template/resources/variables.tf

Also, add a comment marking the hyphenated versions as deprecated.

Add snake_case versions of hyphenated variables

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/david-test/resources/variables.tf

This change alters the david-test namespace so that the resources/variables.tf
matches the latest template code, used by the cloud platform cli.

Use latest variables.tf

---

lib/cp_env/namespace_deleter.rb

The namespace deleter script fetches an empty main.tf file from our
environments repo, but the previous version was deleted by #2922
This change points to the new location of an empty main.tf file.

Update path to empty main.tf file

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-apply-bot-production/00-namespace.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-production/00-namespace.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-staging/00-namespace.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-uat/00-namespace.yaml

Apparently `apply-dev` is the right slack channel to use if we need to
contact the team which owns these namespaces.
https://mojdt.slack.com/archives/C57UPMZLY/p1597761057454200

Add slack channel annotation to laa namespaces

---

lib/cp_env/completed_job_deleter.rb

To remove completed cronjobs, if "ttlSecondsAfterFinished" is not set.

Updated CompletedJobDeleter

---

lib/cp_env/completed_job_deleter.rb

It's possible that a job gets deleted between the script determining the
list of jobs to delete, and actually deleting that specific job. In that
case, without a `rescue` clause, the whole script terminates.
This change adds a rescue inside the loop, so that even if one job fails
to be deleted successfully, the script carries on and tries to delete
all the following jobs.
Example of error:
```
executing: kubectl -n laa-apply-for-legalaid-staging delete job apply-for-legal-aid-metrics-1598255400
Command: kubectl -n laa-apply-for-legalaid-staging delete job apply-for-legal-aid-metrics-1598255400 failed.
Error from server (NotFound): jobs.batch "apply-for-legal-aid-metrics-1598255400" not found
Traceback (most recent call last):
5: from ./bin/delete_completed_jobs.rb:38:in `<main>'
4: from …
```

Add rescue block in delete completed jobs loop

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/mogaal-test/resources/ingress.tf

I want to link to this in the user comms, so it needs to be in the correct state for people to copy/paste into their own namespaces.

Update mogaal-test ingress to module v. 0.0.3

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/check-my-diary-dev/resources/ingress.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/check-my-diary-preprod/resources/ingress.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/court-probation-dev/resources/ingress.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/court-probation-preprod/resources/ingress.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/manage-hmpps-auth-accounts-dev/resources/ingress.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/manage-hmpps-auth-accounts-preprod/resources/ingress.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/manage-soc-cases-dev/resources/ingress.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/manage-soc-cases-preprod/resources/ingress.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/oasys-keycloak-development/resources/ingress.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/offender-case-notes-dev/resources/ingress.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/pathfinder-dev/resources/ingress.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/prisoner-content-hub-development/resources/ingress.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/prisoner-content-hub-staging/resources/ingress.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/sentence-planning-development/resources/ingress.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/sentence-planning-preprod/resources/ingress.tf

This PR will create a separate AWS load-balancer
and ingress controller for each namespace, so that
the teams can add the ingress class annotation to
their ingress definitions to start routing traffic
through the new ingresses.
As soon as all of these namespaces have migrated
their traffic, we will disable mod-security on the
default ingress, which should reduce the problems
we are seeing where the ingress pods are running
out of shared memory.
Related to ministryofjustice/cloud-platform#2224

Ingress controllers for non-prod mod-sec namespaces

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/dstest/resources/ingress.tf

I will add a helloworld deployment, service and ingress definition so
that I can link to it as an example for the changes users will have to
make to their own ingress definitions, in our user comms relating to the
switch to dedicated ingress controllers.

Add a dedicated ingress controller to dstest ns

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/offender-events-prod/resources/manage-soc-cases-sub-queue.tf

Creating the production queues that are needed prior to deploying the production manage-soc-cases service.
This will subscribe 3 queues to the offender events topic and to listen and filter on events of interest. 
Interesting events will be placed on specific queues, from where the service will read and process them.

PAT-1065 Manage SOC cases - create production queues and SNS subscription with filters

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/dstest/certificate.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/dstest/deployment.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/dstest/ingress.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/dstest/service.yaml

This commit adds files to the `dstest` namespace folder so that I can
link to these files in the user comms about changing to dedicated
ingress controllers per namespace.
related to
https://github.com/ministryofjustice/cloud-platform/issues/2224

Add a working "hello world" web application

---

namespace-resources-cli-template/resources/ingress.tf

This will allow a later change to the cloud platform CLI, to create a
dedicated ingress controller with each new namespace.
related to
https://github.com/ministryofjustice/cloud-platform/issues/2224

Add a template ingress.tf file

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-dev/resources/ingress.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-preprod/resources/ingress.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-staging/resources/ingress.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-uat/resources/ingress.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-frontend-preprod/resources/ingress.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-frontend-staging/resources/ingress.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-frontend-uat/resources/ingress.tf

This change adds an ingress.tf file to all the
non-production "book a secure move" namespaces.
A later PR will do the same for production
namespaces, after the team have validated this
change.

Add ingress.tf to non-prod book-secure-move ns

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-dev/00-namespace.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-preprod/00-namespace.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-production/00-namespace.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-staging/00-namespace.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-uat/00-namespace.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-frontend-preprod/00-namespace.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-frontend-production/00-namespace.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-frontend-staging/00-namespace.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-frontend-uat/00-namespace.yaml

According to Miguel Afonso, #hmpps_dev is the best
channel to use if we need to contact this team.

Add slack channel to all book-secure-move ns

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/offender-events-dev/resources/manage-soc-cases-sub-queue.tf

Old name:  manage_soc_cases_probation_offender_events_queue_dl
New name: manage_soc_cases_probation_offender_events_dlq 
Necessary to be consistent across all environments because the original exceeds an AWS resource limit (80 chars) when the name is combined with team-name and env-name in preprod.  It is already created in preprod and prod with the shorter name.

PAT-1216: Rename the queue manage_soc_cases_probation_offender_events

---

.github/workflows/auto-approve-pr.yaml

This PR connects to https://github.com/ministryofjustice/cloud-platform/issues/1931 and relates to the eventual auto-approval of a PR that is deemed sufficiently standard.
The action will trigger upon pull request, checkout the users branch, create a hash of the users newly created namespace and then add a comment on its suitability. More information on its design can be found
here:
https://github.com/ministryofjustice/cloud-platform-directory-hash/#solution
When the team are comfortable with this solution we can remove the comment section in this action and uncomment the auto-approval.
To see a live demo of this action working, please see the checks in this PR.

Add GitHub Action to comment on PR if sufficient

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/check-my-diary-dev/resources/ingress.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/check-my-diary-preprod/resources/ingress.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/court-probation-dev/resources/ingress.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/court-probation-preprod/resources/ingress.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-dev/resources/ingress.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-preprod/resources/ingress.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-staging/resources/ingress.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-uat/resources/ingress.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-frontend-preprod/resources/ingress.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-frontend-staging/resources/ingress.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-frontend-uat/resources/ingress.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/manage-hmpps-auth-accounts-dev/resources/ingress.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/manage-hmpps-auth-accounts-preprod/resources/ingress.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/manage-soc-cases-dev/resources/ingress.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/manage-soc-cases-preprod/resources/ingress.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/manage-soc-cases-prod/resources/ingress.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/mogaal-test/resources/ingress.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/oasys-keycloak-development/resources/ingress.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/offender-case-notes-dev/resources/ingress.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/pathfinder-dev/resources/ingress.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/prisoner-content-hub-development/resources/ingress.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/prisoner-content-hub-staging/resources/ingress.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/sentence-planning-development/resources/ingress.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/sentence-planning-preprod/resources/ingress.tf

This is the version which enables teams to use the
`*.apps.live-1.cloud-platform.service.justice.gov.uk` wildcard certificate from
the `ingress-controllers` namespace (by not adding a `certificate.yaml` to their
namespace, and not specifying a `secretName` in their ingress definition).

Use v0.0.7 of the ingress-controller module

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-production/02-limitrange.yaml

We are about to go live and are reviewing production settings.

Increase pod max memory to 1024Mb

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/manage-soc-cases-dev/resources/ingress.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/manage-soc-cases-dev/resources/variables.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/manage-soc-cases-preprod/resources/ingress.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/manage-soc-cases-preprod/resources/variables.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/manage-soc-cases-prod/resources/ingress.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/manage-soc-cases-prod/resources/variables.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/pathfinder-dev/resources/ingress.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/pathfinder-dev/resources/variables.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/pathfinder-preprod/resources/ingress.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/pathfinder-preprod/resources/variables.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/pathfinder-prod/resources/ingress.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/pathfinder-prod/resources/variables.tf

* Adds ingress controllers to pathfinder-dev, -preprod and -prod namespaces.
* Small changes to manage-soc-cases - to make it consistent with others
* Removed some unused variables
* Set is_production = var.is-production in all ingress definitions

PAT 1230 - ingress controllers for pathfinder namespaces + small changes to manage-soc-cases for consistency

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-repos/serviceaccount-circleci.yaml

On CircleCI, when we try to run the command `kubectl get secrets -n formbuilder-repos` we are receiving the error message on our builds: Error from server (Forbidden): secrets is forbidden: User "********..." cannot list resource "secrets" in API group "" in the namespace "formbuilder-repos".
So this PR adds the list permission that will make us able list the secret names from formbuilder repos.

Form builder repos: Add list permission to circle service account

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/check-my-diary-prod/resources/ingress.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/check-my-diary-prod/resources/variables.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/court-probation-prod/resources/ingress.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/court-probation-prod/resources/variables.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/manage-hmpps-auth-accounts-prod/resources/ingress.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/manage-hmpps-auth-accounts-prod/resources/variables.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/oasys-keycloak-prod/resources/ingress.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/oasys-keycloak-prod/resources/variables.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/prisoner-content-hub-production/resources/ingress.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/prisoner-content-hub-production/resources/variables.tf

DO NOT MERGE BEFORE CHECKING PLAN OUTPUT
This pr adds dedicated ingress controllers to all
the production namespaces which are currently
using mod-security
It also ensures that all these namespaces have a
"namespace" and "is_production" variable, with the
appropriate values.
related to https://github.com/ministryofjustice/cloud-platform-environments/pull/2966

Add ingress controllers for prod mod-sec ns

---

namespace-resources-cli-template/resources/ingress.tf

We don't need to do any template interpolation here - we can just use the existing terraform variable to supply the namespace at plan/apply time.

Use var.namespace in ingress.tf

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-repos/resources/repos.tf

We have some inconsistencies with naming conventions across our platform. We predominantly use the plural 'workers'.
To try an address this we need a new ECR repo with the correct name. We will remove the old repo once we have transitioned to using the new one.

New Form Builder Submitter ECR repo

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-repos/resources/repos.tf

We no longer need the formbuilder-submitter-worker repo as we now use the pluralised version of that: formbuilder-submitter-workers.

Remove old form builder submitter repo

---

lib/cp_env/sonar_qube_scanner.rb

We only need to scan the latest version of the code, so we can used `--depth 1` to avoid checking out the full history of every repo we scan.

Add `--depth 1` to speed up sonarqube scanning

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/manage-key-workers-prod/resources/ingress.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/offender-categorisation-prod/resources/ingress.tf

offender-categorisation-prod
manage-key-workers-prod
This is because we don't have AWS limit for NLB.
We will add this back once AWS increase then limit

Remove teams NLB

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/digital-prison-services-prod/resources/ingress.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/keyworker-api-prod/resources/ingress.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/prison-data-compliance-prod/resources/ingress.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/whereabouts-api-prod/resources/ingress.tf

This version got a fix to remove validation web hooks, which caused issue creating ingress when there is a issue with one of validationwebhooks
This 3 prod namespaces still using the default ingress-class
digital-prison-services-prod
keyworker-api-prod
whereabouts-api-prod
prison-data-compliance-prod namesapce, spoke to Jon Brighton, he is happy for the change to apply

Updated prod namespaces to use the latest nginx version

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/whereabouts-api-dev/resources/ingress.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/whereabouts-api-preprod/resources/ingress.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/whereabouts-api-prod/resources/ingress.tf

We hit the limit of AWS NLB, we can add back once we get the limit increase
Pipeline failing with below reason
Command: cd namespaces/live-1.cloud-platform.service.justice.gov.uk/whereabouts-api-prod/resources; terraform apply -auto-approve failed.
Error: timed out waiting for the condition
But actual issue from the events.
Error syncing load balancer: failed to ensure load balancer: error creating load balancer: "TooManyLoadBalancers: The maximum number of load balancers has been reached.
Spoke to Nevelina Aleksandrova , she is happy for them to be added back once we got the limit increase

Remove ingress_controller in whereabouts-api-*

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/check-my-diary-prod/resources/ingress.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/court-probation-prod/resources/ingress.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/davidread-dev/resources/ingress.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/digital-prison-services-prod/resources/ingress.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/keyworker-api-prod/resources/ingress.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/manage-key-workers-dev/resources/ingress.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/manage-key-workers-preprod/resources/ingress.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/mogaal-test/resources/ingress.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/oasys-keycloak-development/resources/ingress.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/oasys-keycloak-prod/resources/ingress.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/prisoner-content-hub-production/resources/ingress.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/sentence-planning-development/resources/ingress.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/sentence-planning-preprod/resources/ingress.tf

If users created a dedicated ingress controller, but not using it yet, this PR will delete it.
(to reduce the number of NLBs, which is a limited, shared resource)
Also Remove ingress controller for users not using it and enabled mod-security, as for ingresses where people need mod-security, we will create a pool of ingress controllers, and distribute ingresses so that no one ingress controller is handling more than N ingresses.

Remove nlb non usage

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-staging/resources/rds_temp.tf

We are currently experiencing errors on our staging RDS instance around disk space: 
`PG::DiskFull: ERROR: could not write block 114692 of temporary file: No space left on device`
We have raised an issue to investigate this with AWS, however we would like to unblock our staging environment by pointing to a new RDS temp instance in the meantime.

Create new temp RDS for staging Book a secure move

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/monitoring/dashboard-pods-per-node.yaml

We have had a few alerts of "TooManyPods" on node recently. 
We have made a few changes to cleaning up completed pods.
This is a quick clean dashboard to show how many pods per node are running at any time, also showing the max pod count for info

Add Dashboard to show pods per node

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/how-out-of-date-are-we/deployment.yaml

This adds the namespace costs page, as per:
https://github.com/ministryofjustice/cloud-platform-how-out-of-date-are-we/pull/46

Use HOODAW v2.19

---

lib/cp_env/sonar_qube_scanner.rb

Prior to this change, only single, github repo. URLs would be considered
for sonarqube scanning. However, some namespaces have multiple
repositories they would like to be scanned (e.g. #3109), so this change
will allow comma-separated lists of github repo. URLs in the source-code
annotation.

Allow comma-sep. lists of URLs in "source-code"

---

lib/cp_env/sonar_qube_scanner.rb

Although using `--depth 1` makes the git checkout faster, it also means that sonarqube cannot supply any `git blame` information. You can see this in the logs:
```
WARN: Shallow clone detected, no blame information will be provided...
```
Since this job takes a long time to run anyway, adding a bit more time in order to have more information in the final reports seems like a worthwhile trade-off.

Remove `--depth 1` from `git clone` command

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/how-out-of-date-are-we/resources/dynamodb.tf

Although plan was fine with the previous `dynamodb.tf` file, when
applied it resulted in this error:
```
Error: error creating DynamoDB Table: ValidationException: Invalid
KeySchema: Some index key attribute have no definition
status code: 400, request id: XXX...
```
Removing the `range_key` line allowed `terraform apply ` to succeed.
NB: I have already applied this manually, so this PR is just to keep the
code in sync with the terraform state.

Fix dynamodb definition

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/case-notes-to-probation-prod/resources/ingress.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/prison-estate-prod/resources/ingress.tf

This is to get the ingress controller to use the upgraded version
Following this process to Zero-downtime Ingress Controller Upgrade
https://runbooks.cloud-platform.service.justice.gov.uk/zero-downtime-ingress-upgrade.html#zero-downtime-ingress-controller-upgrade

Upgrade ingress-controller for prison-estate-prod and case-notes-to-probation-prod

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-staging/02-limitrange.yaml

this increases the memory limit from 500mb to 1gb, as we are having some memory issues on our staging system

Increase BaSM staging memory limit on pods

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-monitoring/resources/pingdom.tf

This adds a Pingdom check for the Form Builder publisher in production

Add Form Builder Publisher pingdom check

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-cla-backend-production/resources/route53.tf

The Ingress should populate this record when it sees it is not set
PR should be merged as close as possible to the migration completion

Remove A record from fox admin zone

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-cla-backend-production/resources/rds.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-cla-backend-staging/resources/rds.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-cla-backend-training/resources/rds.tf

Since we created the staging and production databases, the default value
of force_ssl has been changed to true, but with an apply_method that is
incompatible with our db engine. Therefore we need to respecify it. This
was stopping the db being created in our training namespace, but we
should specify it in the other two namespaces to avoid confusion
Hopefully I can get an exception to the single-namespace check here

Set force_ssl: true  on cla_backend_rds instances

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-repos/resources/repos.tf

We have now migrated to using the new ECR repos so these can be deleted.
https://trello.com/c/TuaqBFCp/944-adjust-hmcts-complaints-adapter-deployment

Form Builder - Remove old HMCTS adapter repo

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/offender-events-prod/09-prometheus-sqs-sns.yaml

Normally we'd be looking at 9-5 but we are going a little early to prove to ourselves that this approach actually works - we hope to still get some alerts between 4am and 9am.

DT-1143 Ignore probation offender event alerts at uninteresting times

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/calculate-journey-variable-payments-dev/resources/s3.tf

The apply pipeline is complaining about a  malformed policy.
https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/environments-terraform/jobs/apply-live-1/builds/1191
I'm commenting this out to fix the pipeline.

Comment out the S3 bucket resource

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/manage-intelligence-dev/07-certificate.yaml

An API service will share the same namespace as the manage-intelligence service.
This creates a certificate file and DNS entry for the API.

AR-301: Add certificate and DNS entry for manage-intelligence-api-dev

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-dev-lgfs/serviceaccount-circleci.yaml

Add configmaps access for cccd-dev-lgfs circleci service account
Want to use configmaps as part of deploy to avoid
repetition between app and worker pods

Add configmaps access for cccd-dev-lgfs circleci service account

---

makefile
namespaces/live-1.cloud-platform.service.justice.gov.uk/cloud-platform-bots/00-namespace.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-monitoring/00-namespace.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/kube-system/00-namespace.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/prison-api-certificates/00-namespace.yaml
policy/namespace.rego

This change adds a `policy` directory to hold
rego files defining rules all namespaces should
comply with, and a makefile target that tests all
the yaml files in the repo against all of the
policies in that directory.
Initially, this only covers required annotations
and labels for Namespace definitions.
Later changes should add more rules for more
objects, and a github action to apply our policies
to any PRs raised.

Start adding Rego policies for namespaces

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-api-sandbox/serviceaccount-circleci.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-dev/serviceaccount-circleci.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-production/serviceaccount-circleci.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-staging/serviceaccount-circleci.yaml

Grant configmap resource access to all cccd circleci service accounts
To enable sharing of common config between app
and worker pods

Grant configmap resource access to all cccd circleci service accounts

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/prisoner-content-hub-production/resources/pingdom.tf

As far as I'm aware this should add the relevant check to each endpoint using health-kick to return the results.
We also have a previous integration id for #pfs_dev.

Add Pingdom to prisoner-content-hub-production

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/monitoring/kibana-audit-oauth2-proxy.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/monitoring/kibana-dsd-oauth2-proxy.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/monitoring/kibana-oauth2-proxy.yaml

This is needed so we always have proxy running when terminating/draining nodes.

Add 2 replicas to proxy template.

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/dstest/resources/rds.tf

This is just for use while I work on adding Namespace tags to AWS resources. I'll delete it when that work is finished (for RDS instances).

Add an RDS to the dstest namespace

---

namespace-resources-cli-template/resources/variables.tf

This change removes the hyphenated (`foo-bar` vs. `foo_bar`) versions of terraform variables in the namespace template.
This probably means that, for new namespaces, we will encounter problems where our modules are expecting hyphenated variables. Spotting these failures in new namespaces is probably the least disruptive way to ensure that we do actually get around to fixing our modules, as per the [ADR]
[ADR]: https://github.com/ministryofjustice/cloud-platform/blob/main/architecture-decision-record/017-Variable-Naming.md#variable-names-in-yaml--terraform-files-are-in-snake-case

Remove hyphenated variables

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-uat/05-prometheus.yaml

Prometheus rules for the `apply-for-legalaid-uat` namepsace are currently held in our team repo (https://github.com/ministryofjustice/laa-apply-for-legal-aid). 
This change moves them to the `cloud-platform-environments` repo. They will be removed from the other repo separately.

Move apply-for-legalaid-uat prometheus rules

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-staging/05-prometheus.yaml

Prometheus rules for the apply-for-legalaid-staging namepsace are currently held in our team repo (https://github.com/ministryofjustice/laa-apply-for-legal-aid).
This change moves them to the cloud-platform-environments repo. They will be removed from the other repo separately.

Add apply-for-legalaid-staging Prometheus rules

---

makefile

The previous command tested all `*.yaml` files against our rego
policies, but skipped `*.yml` files. This change fixes that.

Apply rego policies to *.yml files, too

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/c100-application-metabase/00-namespace.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/c100-application-production/00-namespace.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/c100-application-staging/00-namespace.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/disclosure-checker-production/00-namespace.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/disclosure-checker-staging/00-namespace.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/family-mediators-api-production/00-namespace.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/family-mediators-api-staging/00-namespace.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/fj-cait-production/00-namespace.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/fj-cait-staging/00-namespace.yaml

As per conversation in:
https://mojdt.slack.com/archives/C57UPMZLY/p1601638362184400
This PR reassign the business-unit to "HQ" and updates some other outdated or incorrect annotations. Also add the missing `team-name` annotation to all namespaces.
We are aware our team name (from github) is the old one and should be updated too, but that will have to wait as it involves changing a lot more files and re-authenticate to the cluster.

Update annotations in all UCPD namespaces

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/c100-application-production/prometheus.yml

As per conversation in:
https://mojdt.slack.com/archives/C57UPMZLY/p1601638362184400
The business-unit annotation has been changed to be `HQ` so we need to use a different one to filter and select only our team services.
Changed this to be annotation:
`cloud-platform.justice.gov.uk/team-name: "family-justice"`

Update UCPD prometheus rules

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-production/http_status_codes_grafana_dashboard.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-production/nginx-errors_grafana_dashboard.yaml

Code for grafana dashboards for `apply-for-legal-aid` are currently held in
our team repo (https://github.com/ministryofjustice/laa-apply-for-legal-aid).
This change moves them to the `cloud-platform-environments` repo. They
will be removed from the other repo separately.

Move grafana dashboards to cloud platform repo

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/maintenance-pages/certificate.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/maintenance-pages/ingress.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/maintenance-pages/resources/route53.tf

The formula that worked : 
- One route53 zone per domain ( it seems we can't skip a parent when delegating) + 1:1 delegation
- No wildcard cert for domain whose parent we don't control. ( *.decisions)
- One broken or unresolvable domain prevents the whole cert from being  validated, that domain was skipped.

Upadted ingresses, certs and R53 zones for maintenance pages

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-dev-lgfs/serviceaccount-circleci.yaml

Attempting to watch a rollout during deploy but receiving this
error:
```
Waiting for deployment "claim-for-crown-court-defence" rollout to finish: 2 old replicas are pending termination...
Error from server (Forbidden): unknown (get deployments.apps)
```
Hoping this resolves it?!

Enable watch verb on cccd-dev-lgfs 

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-api-sandbox/serviceaccount-circleci.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-dev/serviceaccount-circleci.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-production/serviceaccount-circleci.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/cccd-staging/serviceaccount-circleci.yaml

Add watch and list verb privileges for all cccd namespace circleci serviceaccounts
To enable watching a deployment rollout and fail with timeout 
if pods not replaced.

Add watch and list verb privileges for all cccd ns serviceaccounts

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-court-data-ui-dev/serviceaccount-circleci.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-court-data-ui-production/serviceaccount-circleci.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-court-data-ui-staging/serviceaccount-circleci.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-court-data-ui-uat/serviceaccount-circleci.yaml

Add watch and list verb privileges for all VCD namespace circleci serviceaccounts
To enable watching a deployment rollout and fail with timeout
if pods not replaced.

Add watch and list verb privileges for all VCD namespace circleci serviceaccounts

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-pin-phone-monitor-dev/resources/iam.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-pin-phone-monitor-dev/resources/s3.tf

The intention here is to demonstrate that we can separate the permissions of our application (which should only be able to get and delete objects from S3) from the permissions of another IAM user which can only put objects to the bucket.

🔧 PPD-47: Adding separate IAM user for uploading to S3

---

namespace-resources-cli-template/05-serviceaccount.yaml

see #3424 
Adding this permission should allow users/pipelines to continually monitor status as they deploy their services.

Add "watch" permission to serviceaccount template

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-platform-live-dev/resources/submitter.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-platform-live-dev/resources/user-datastore.tf

These RDS instances have "auto minor upgrade" enabled. This causes
problems when the minor version of the AWS instances is greater than the
minor version specified in the code.
If "auto minor upgrade" is enabled, we shouldn't specify the minor
version in the terraform code.
I've done a manual `terraform plan` with these changes, and it reports no changes to the RDS instances.

Remove minor version number from RDS instances

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/pathfinder-dev/resources/rds.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/pathfinder-preprod/resources/rds.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/pathfinder-prod/resources/rds.tf

This avoids conflicts with "auto upgrade minor"

Remove minor version from pathfinder RDS instances

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/licences-dev/resources/main.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/licences-preprod/resources/main.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/licences-prod/resources/main.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/offender-categorisation-dev/resources/main.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/offender-categorisation-preprod/resources/main.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/offender-categorisation-prod/resources/main.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/offender-events-dev/resources/main.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/offender-events-preprod/resources/main.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/offender-events-prod/resources/main.tf

Hashicorp upgraded the random provider from 2.30
to 3.0.0 today. This change seems to remove the
`b64` function (there are no release notes, so we
can't confirm this, but stuff breaks).
This PR pins the random provider version to 2.3+
so that namespaces in which the `b64` function is
used continue to plan/apply correctly.

Pin the version of the "random" provider

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-saas-test/00-namespace.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-saas-test/01-rbac.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-saas-test/02-limitrange.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-saas-test/03-resourcequota.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-saas-test/04-networkpolicy.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-saas-test/resources/main.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-saas-test/resources/metadata_api.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-saas-test/resources/variables.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-saas-test/resources/versions.tf

We are creating a new Metadata API application that will be backed by a postgres database.
At the same time we need to create a new namespace `formbuilder-saas-test` which the api will live in along with some future apps.
https://trello.com/c/6s5j3gj7/972-cloud-platform-configuration-for-the-db

Create formbuilder-saas namespace and Metadata API DB

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/prison-to-nhs-update-dev/resources/main.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/prison-to-nhs-update-preprod/resources/main.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/prison-to-nhs-update-prod/resources/main.tf

The apply pipeline is breaking because `.b64` is no longer a valid
function. This fixes that.

Pin "random" provider to 2.3+

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-platform-live-production/01-rbac.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-platform-live-production/service-token-cache-service-account-2.yaml

Unfortunately we need to rotate the token used by the old service account for the service-token-cache app. The way the app utilises it makes it not possible to simply delete and let K8S regenerate it as that would mean potential downtime for some users.
We need to create another service account from scratch and move to use the token generated for that before deleting the old service account.
https://trello.com/c/LfLkccvb/963-redact-kubernetes-token-in-service-token-cache

Create new Form Builder service token cache service account

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-services-live-production/01-rbac.yaml

We need the service account to have permissions to interact with the `formbuilder-services-live-production`.

Add Form Builder service account permissions

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/peoplefinder-development/resources/elasticsearch.tf

This version adds the "namespace" tag to AWS resources.
This is an initial test, in a single non-prod namespace. If this doesn't
cause any problems, I'll raise other PRs for all the other instances of
this module in the environments repo.

Use ES module v3.2

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-cla-backend-production/resources/rds.tf

The replica RDS instance does not have a value for "namespace", so its
costs are not being allocated correctly.

Add namespace tag to replica database

---

bin/rds-instances-by-namespace.rb

This makes it easier to figure out which namespace a given RDS belongs
to, if the "namespace" tag is missing.

Add a script to list all namespaces and DB names

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-saas-test/05-circleci-service-account.yaml

The Service Account used by Circle needs to have some additional permissions in order to work correctly.
https://trello.com/c/16na1z6k/979-deployment-pipeline-configuration

Give Form Builder Metadata API service account more permissions

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-saas-test/05-circleci-service-account.yaml

The core API group is in fact the one that requires the permission to get resources for configmaps.
We also need to add the ability to get servicemonitors for the monitoring.coreos.com API group.

Update Form Builder Metadata API service account permissions

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/dstest/resources/rds.tf

Creating this RDS instance failed with:
```
Error: Error modifying DB Parameter Group: InvalidParameterCombination: cannot use immediate apply method for static parameter
```
I think allowing major version upgrade here might fix this, since that's the only significant difference I can see between this RDS instance and [this one](https://github.com/ministryofjustice/cloud-platform-environments/blob/main/namespaces/live-1.cloud-platform.service.justice.gov.uk/track-a-query-staging/resources/rds.tf)

Allow major version upgrade

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/dstest/resources/rds.tf

This RDS is still not building correctly.
This is another difference between this RDS and other 9.5 RDS instances that have already been built.

Disable performance insights

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/kube-system/00-namespace.yaml

We need to annotation to be set to cloud-platform till we change all monitoring alarms to use a different annotation

Change annotation back to CP till we ready to change

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/monitoring/00-namespace.yaml

Change annotation back to CP till we ready to change alarms as alarms are still using the cp annotation

Change annotation to CP till monitoring alarms changed

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/check-financial-eligibility-uat/05-ingress.yaml

Add configuration to ingress to turn server-tokens off in order to resolve a security issue that reveals the server and version e.g. nginx/v1... This is after curl-ing the url
curl https://.... which returns a http response with the server info in it.

Add configuration to ingress to turn server-tokens off

---

.github/workflows/auto-approve-pr.yaml

An issue has caused a failure to pull down a Dockerfile. This has been rectified in a fork of the project. Will temporarily move there.

Fix broken GitHub Action

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/how-out-of-date-are-we/resources/dynamodb.tf

The application isn't working right now, and the pod logs show this
error:
```
2020-10-23 11:24:36 -
Aws::DynamoDB::Errors::ProvisionedThroughputExceededException - The
level of configured provisioned throughput for the table was exceeded.
Consider increasing your provisioning level with the UpdateTable API.:
```
Enabling the dynamodb autoscaler should fix this.

Enable dynamodb autoscaler for HOODAW

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/check-financial-eligibility-uat/05-ingress.yaml

~~Fix issue with namespaces/live-1.cloud-platform.service.justice.gov.uk/check-financial-eligibility-uat/05-ingress.yaml
after merging [pr](https://github.com/ministryofjustice/cloud-platform-environments/pull/3645#issue-506905524)~~
~~The error was:
The Ingress "nginx-configuration" is invalid: spec: Invalid value: []networking.IngressRule(nil): either `backend` or `rules` must be specified~~
EDIT:
Remove this file namespaces/live-1.cloud-platform.service.justice.gov.uk/check-financial-eligibility-uat/05-ingress.yaml
The attempt to update the config in the ingress controller here was in the wrong repo , it should have been updated in this repo  ministryofjustice/cloud-platform-terraform-ingress-controller

Update ingress.yaml to include rules

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/dstest/resources/rds.tf

I've already done this, so this change brings the code into alignment
with the RDS instance.

Update dstest RDS to postgres9.6

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/dstest/resources/rds.tf

This uses a branch of the RDS module which adds more permissions to the
IAM user which is created with the RDS instance. This should allow teams
to manage their own DB engine upgrades, which is what I'll test once
this RDS is created.

Add a postgres9.5 RDS to dstest namespace

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/dstest/resources/rds.tf

Disable performance insights for postgres9.5 DB

---

bin/rds-instances-by-namespace.rb

This is useful when we need to tell teams to upgrade their database
versions, as AWS end-of-lifes older ones.

Output DB engine & version for each rds instance

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-saas-test/01-rbac.yaml

The formbuilder service token cache app needs permission to see the config maps from formbuilder-saas-* namespaces.

 Add service token cache permission to formbuilder saas

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-uat/serviceaccount-circleci.yaml

This will allow the circleci serviceaccount to deploy to the application
to the UAT environment. As discussed with @willc-work

Add permissions to circleci serviceaccount

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-production/resources/pingdom.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-frontend-production/resources/pingdom.tf

Adds the pingdom integration ID to Book a Secure Move API and frontend production environments.

Add Pager Duty integration to Book a Secure Move production

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-saas-test/06-prometheus.yaml

Creating the Prometheus rules for the formbuilder saas test namespace.
Co-authored-by: Brendan Butler brendan.butler@digital.justice.gov.uk

Add prometheus rules for formbuilder saas test namespace

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-production/00-namespace.yaml

Add the runbook urls for laa-apply-for-legalaid production environment

Add runbook urls to laa-apply-for-legalaid

---

.checksum
namespaces/live-1.cloud-platform.service.justice.gov.uk/operations-engineering/00-namespace.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/operations-engineering/01-rbac.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/operations-engineering/02-limitrange.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/operations-engineering/03-resourcequota.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/operations-engineering/04-networkpolicy.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/operations-engineering/resources/main.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/operations-engineering/resources/s3.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/operations-engineering/resources/variables.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/operations-engineering/resources/versions.tf

This S3 bucket will be used to store terraform
statefiles relating to operations-engineering
projects.

Add namespace & s3 bucket for OpsEng

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/check-financial-eligibility-uat/serviceaccount-circleci.yaml

deployments are failing because serviceaccount doesnt have permission to update resources, added in permission

add update to resources verbs uat cfe

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-uat/serviceaccount-circleci.yaml

remove tiller service account no longer needed due to helm3 upgrade

Apply UAT networkpolicies is in wrong resources

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/check-financial-eligibility-uat/01-rbac.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/check-financial-eligibility-uat/serviceaccount-circleci.yaml

While upgrading to helm3 I removed the circleci service account instead of the tiller serviceaccount. This PR is to reinstate the circle serviceaccount and remove the tiller serviceaccount from `rbac.yaml`
Question: Do we need the circle serviceaccount to be reinstated? The deployments all work without this serviceaccount and I assume having an unused serviceaccount is probably a security risk. If it is required why are deployments working without it?

CFE UAT add serviceaccount back in

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-uat/serviceaccount-circleci.yaml

Prometheus reporting appears broken at present, possibly because the serviceaccount doesn't have `prometheusrules` as an available resource.

Apply Staging - add prometheusrules to resources

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/prison-visits-booking-production/resources/route53.tf

There is a route53 hosted zone which has an A record for a production service:
```
http://staff.prisonvisits.service.justice.gov.uk/
```
...but it's not being managed in terraform.
This change adds a terraform resource for the zone. A manual `terraform
import` will import the existing AWS route53 hosted zone into the
terraform state.

Add a route53 zone for prisonvisits.service.just..

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-interventions-dev/00-namespace.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-interventions-dev/01-rbac.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-interventions-dev/02-limitrange.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-interventions-dev/03-resourcequota.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-interventions-dev/04-networkpolicy.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-interventions-dev/resources/main.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-interventions-dev/resources/variables.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-interventions-dev/resources/versions.tf

Intervention teams are moving into the beta phase, so we need namespaces
to deploy the applications.
The namespace is "empty" as we will be adding modules later.
Split from #3795.

Create intervention dev namespace

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-interventions-preprod/00-namespace.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-interventions-preprod/01-rbac.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-interventions-preprod/02-limitrange.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-interventions-preprod/03-resourcequota.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-interventions-preprod/04-networkpolicy.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-interventions-preprod/resources/main.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-interventions-preprod/resources/variables.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-interventions-preprod/resources/versions.tf

Intervention teams are moving into the beta phase, so we need namespaces
to deploy the applications.
The namespace is "empty" as we will be adding modules later.
Split from #3795.

Create intervention preprod namespace

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-interventions-prod/00-namespace.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-interventions-prod/01-rbac.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-interventions-prod/02-limitrange.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-interventions-prod/03-resourcequota.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-interventions-prod/04-networkpolicy.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-interventions-prod/resources/main.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-interventions-prod/resources/variables.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-interventions-prod/resources/versions.tf

Intervention teams are moving into the beta phase, so we need namespaces
to deploy the applications.
The namespace is "empty" as we will be adding modules later.
Split from #3795.

Create intervention prod namespace

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/maintenance-pages/deployment.yaml

Why:
https://github.com/ministryofjustice/cloud-platform-maintenance-pages/pull/7

add new maintenance page release

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-preprod/resources/rds.tf

Increases Book A Secure Move rds size to 20gb, in order to apply a production snapshot to pre-prod.

increase BASM pre-prod rds db size

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-interventions-dev/05-serviceaccount-circleci.yaml

We are getting
`Error: UPGRADE FAILED: replicasets.apps is forbidden: User "system:serviceaccount:***********************:circleci" cannot list resource "replicasets" in API group "apps" in the namespace "***********************"`
during deployment -- this change allows this.
🙋 Additionally, the name of the file now mentions `circleci`, a convention we noticed in other folders.

Allow replicasets to be managed by CircleCI in interventions-dev

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-interventions-dev/05-serviceaccount-circleci.yaml

Addressing deployment error on CircleCI:
`Error: UPGRADE FAILED: update: failed to update: secrets
"sh.helm.release.v1.hmpps-interventions-service.v4" is forbidden: User
"system:serviceaccount:***********************:circleci" cannot update
resource "secrets" in API group "" in the namespace
"***********************"`

Allow updating secrets for default API group in interventions-dev

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/court-probation-preprod/05-serviceaccount-circleci.yaml

This should resolve the following error returned by Helm:
```
Error: replicasets.apps is forbidden: User "system:serviceaccount:***********************:circleci" cannot list resource "replicasets" in API group "apps" in the namespace "***********************"
```

Grant Helm 3 replicaset permissions in court-probation-preprod

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/court-probation-preprod/05-serviceaccount-circleci.yaml

Fix for:
```
Error: replicasets.apps is forbidden: User "system:serviceaccount:***********************:circleci" cannot list resource "replicasets" in API group "apps" in the namespace "***********************"
```

Fix permission granted to wrong apiGroup

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-monitoring/resources/pingdom.tf

The form was used for user testing and now needs to be unpublished,
hence the reason to remove from pingdom

Remove form from pingdom

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/pact-broker-prod/00-namespace.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/pact-broker-prod/01-rbac.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/pact-broker-prod/02-limitrange.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/pact-broker-prod/03-resourcequota.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/pact-broker-prod/04-networkpolicy.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/pact-broker-prod/resources/main.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/pact-broker-prod/resources/rds.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/pact-broker-prod/resources/variables.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/pact-broker-prod/resources/versions.tf

The https://github.com/pact-foundation/pact_broker itself is a Ruby application that requires a database. We have configured this as PostgreSQL.

Create pact broker namespace

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/how-out-of-date-are-we/deployment.yaml

This version includes the namespace usage report.
depends on https://github.com/ministryofjustice/cloud-platform-how-out-of-date-are-we/pull/61 (plus creating a new release)

Use HOODAW image 2.30

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/c100-application-metabase/01-rbac.yaml

This reverts commit 1a632650ce8848b5bd0afa7d59f0f558955d0c30.
It turns out the necessary changes to run the container as non-root will be part of the next major version (v0.38) and not included in the current latest version (v0.37.3)
As we don't know when the version will be released we need to rollback the rbac so we can get metabase working again in the meantime 😞

Revert "Remove privileged rules from metabase rbac"

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/manage-intelligence-dev/resources/s3.tf

S3 bucket to store help and guidance content for the HMPPS manage intelligence service.

Add s3 storage bucket for managing manage-intelligence

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-interventions-dev/resources/rds.tf

This was breaking the apply pipeline
```
Error: Error creating DB Instance: InvalidParameterCombination: The Parameter Group cloud-platform-c6fbb5a155375227 with DBParameterGroupFamily postgres11 cannot be used for this instance. Please use a Parameter Group with DBParameterGroupFamily postgres10
status code: 400, request id: 0a906f02-7216-4ff1-92e8-672af89baa60
```
So, I'm commenting it out until the team can apply a fix.

Comment hmpps-interventions-dev RDS definition

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-interventions-dev/resources/rds.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-interventions-dev/resources/variables.tf

this is to address the following error when applying terraform
```
Error: Error creating DB Instance: InvalidParameterCombination: The Parameter Group cloud-platform-c6fbb5a155375227 with DBParameterGroupFamily postgres11 cannot be used for this instance. Please use a Parameter Group with DBParameterGroupFamily postgres10
status code: 400, request id: 385d9afe-9161-42cc-94b3-520212767027
```

set hmpps-interventions-dev rds_family to 'postgres10' to fix deployment

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/manage-intelligence-dev/06-certificate.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/manage-intelligence-dev/07-certificate.yaml

Due to issues with DXC proxies, changing the certificates for the dev instance of the node app and api

Change certs to use prison.service.justice.gov.uk

---

bin/post_namespace_usage_data.sh

Occasionally (about 1 time in 10), we get this error in the concourse
pipeline job that posts namespace usage data to HOODAW:
```
curl: (92) HTTP/2 stream 0 was not closed cleanly: PROTOCOL_ERROR (err
1)
```
e.g.
https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/hoodaw/jobs/hoodaw-namespace-usage/builds/52
This PR is an attempt to fix that.
I think the underlying problem is that *something* in the chain between
the script's invocation of `curl` and the HOODAW web application is not
handling http/2 correctly wrt. large POST requests.
I've checked the curl version on the tools image, and it seems up to
date. I suspect a tweak to increase the post buffer size of the ingress
controller might be a better solution to this intermittent problem, but
TBH it just doesn't …

Force HTTP1.1, posting namespace usage to HOODAW

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-uat/05-serviceaccount.yaml

This, currently, only needs to rad the ingresses data from the UAT
namespace. so hopefully this set of permissions is restricted/
permissive enough!

Add serviceaccount for laa-apply-slack-bot

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-apply-bot-production/service-account-github-actions.yaml

It needs access to decode the ECR secrets to
prevent them being stored outside of the
cluster

Update ServiceAccount permissions

---

.checksum
namespaces/live-1.cloud-platform.service.justice.gov.uk/cloud-platform-canary-app/00-namespace.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/cloud-platform-canary-app/01-rbac.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/cloud-platform-canary-app/02-limitrange.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/cloud-platform-canary-app/03-resourcequota.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/cloud-platform-canary-app/04-networkpolicy.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/cloud-platform-canary-app/resources/main.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/cloud-platform-canary-app/resources/variables.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/cloud-platform-canary-app/resources/versions.tf

This namespace will act as a canary in the cluster, when it and a number
of other applications fail it will indicate a larger problem. It will be
monitored using blackbox tools such as Pingdom and alert the Cloud
Platform team if it fails.

Add canary application for cluster monitoring

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/cloud-platform-canary-app/resources/application.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/cloud-platform-canary-app/resources/main.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/cloud-platform-canary-app/resources/pingdom.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/cloud-platform-canary-app/resources/psp.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/cloud-platform-canary-app/resources/values.yaml

Overview
---
This PR connects to https://github.com/ministryofjustice/cloud-platform/issues/2380 and relates to the creation of a canary application in the cluster. This application uses the helpful [podinfo](https://github.com/stefanprodan/podinfo) container that sends metrics to Prometheus, structured logging and graceful shutdowns. 
Clusterrolebinding
---
As the container runs as root, I'm required to bind all serviceaccounts in the `cloud-platform-canary-app` namespace to the privileged pod security policy. 
Pingdom
---
The purpose of creating this deployment is to monitor using blackbox tooling such as Pingdom. This PR also contains a Terraform resource that creates a check that will send a trigger alarm to the #low-priority-alarms channel.

Add podinfo Helm Terraform resource and Pingdom check

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/cloud-platform-canary-app/resources/values.yaml

This will fail to /healthz endpoint when the pod fails to receive
traffic.

Add custom http errors annotation

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/track-a-move-prod/resources/acm.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/track-a-move-prod/resources/apigw.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/track-a-move-prod/resources/firehose.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/track-a-move-prod/resources/route53.tf

https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/environments-terraform/jobs/apply-live-1/builds/266
The error is:
```
Command: cd namespaces/live-1.cloud-platform.service.justice.gov.uk/track-a-move-prod/resources; terraform apply -auto-approve failed.
Error: error creating Kinesis Firehose Delivery Stream: ResourceInUseException: Firehose geoamey under accountId 754256621582 already exists
Error: Error describing created certificate: Expected certificate to be issued but was in state PENDING_VALIDATION
Error: error creating Kinesis Firehose Delivery Stream: ResourceInUseException: Firehose serco under accountId 754256621582 already exists
```
I think the prod environment resources need different names from the existing dev
resources.
In order to restore the …

Comment out resources to unbreak apply pipeline

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-cla-backend-production/resources/rds.tf

The iops needs more testing. 
Concourse throws error
`Invalid iops to max storage (GB) ratio for engine name postgres and storage type io1: 0.3000`

Revert laa-cla-backend-production RDS to 5.11

---

.checksum
namespaces/live-1.cloud-platform.service.justice.gov.uk/cloud-platform-reports-dev/00-namespace.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/cloud-platform-reports-dev/01-rbac.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/cloud-platform-reports-dev/02-limitrange.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/cloud-platform-reports-dev/03-resourcequota.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/cloud-platform-reports-dev/04-networkpolicy.yaml
namespaces/live-1.cloud-platform.service.justice.gov.uk/cloud-platform-reports-dev/resources/main.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/cloud-platform-reports-dev/resources/variables.tf
namespaces/live-1.cloud-platform.service.justice.gov.uk/cloud-platform-reports-dev/resources/versions.tf

I'm planning to rename "how out of date are we" to
"cloud platform reports", and create a helm chart
to deploy the app.
This namespace is where I'm planning to deploy a
dev instance of it.

Add `cloud-platform-reports-dev` namespace

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/manage-intelligence-dev/resources/elasticsearch.tf

As per recommendation from cloud-platform team, attempting to use a branch of the elasticsearch terraform module to add encryption support to our dev cluster. The expectation is that the cluster will be rebuilt which is fine for the dev instance.

Upgrade to v7.9 and add encryption to cluster.

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/cloud-platform-canary-app/resources/main.tf

Terraform requires an auth block so it knows where to look for a
kubeconfig file. This PR adds that block into the canary app namespace.

Add Helm authentication in canary application

---

namespaces/live-1.cloud-platform.service.justice.gov.uk/formbuilder-repos/resources/repos.tf

Carrying on from [this PR](https://github.com/ministryofjustice/cloud-platform-environments/pull/3990)
We also no longer require this ECR repo.
https://trello.com/c/hcr5vlD5/1132-remove-unused-namespace-and-document-the-other-namespaces-we-have

Form Builder - Remove old submit product ECR repo
