namespaces/live.cloud-platform.service.justice.gov.uk/family-mediators-api-production/resources/rds.tf

Initial changes needed to upgrade DB

Skip file and AWS keys exposed for Family Mediators Production

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-dpr-poc-dev/resources/ecr.tf

Create an ECR Repository for Digital Prisons Reporting Proof-of-Concept FE Application

DPR-73 Digital Prison Reporting Proof of Concept DEV

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-api-prod/resources/rds.tf

NN-4479: temporarily bump hmpps-manage-adjudications-api-prod/rds to db.t3.large

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-api-prod/resources/rds.tf

NN-4479: post upgrade changes for hmpps-manage-adjudications-api-prod/rds

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-criminal-applications-datastore-harness/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-criminal-applications-datastore-harness/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-criminal-applications-datastore-harness/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-criminal-applications-datastore-harness/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-criminal-applications-datastore-harness/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-criminal-applications-datastore-harness/resources/dynamodb.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-criminal-applications-datastore-harness/resources/ecr.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-criminal-applications-datastore-harness/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-criminal-applications-datastore-harness/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-criminal-applications-datastore-harness/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-criminal-applications-datastore-harness/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-criminal-applications-datastore-harness/resources/versions.tf

A new environment namespace for an existing service.

Create new datastore harness namespace

---

namespaces/live-2.cloud-platform.service.justice.gov.uk/poornima-dev/resources/dynamodb.tf

This PR is for testing purpose. When the workaround is acheived, this will be deleted and the actual dynamobdb will be created as part of concourse

Add dynamodb for testing the pipeline

---

namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-test-dev/resources/submitter.tf

Removing the old submitter DB in formbuilder-platform-test-dev

Form Builder - Remove old submitter DB test-dev

---

namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-test-production/resources/submitter.tf

Removing the old DB in formbuilder-platform-test-production

Form Builder - remove old submitter DB test-production

---

namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-live-dev/resources/submitter.tf

Removes the old submitter DB in formbuilder-platform-live-dev

Form Builder - remove old submitter DB live-dev

---

namespaces/live.cloud-platform.service.justice.gov.uk/check-financial-eligibility-partner-staging/00-namespace.yaml

Added a network policy but forgot tp update the labels in 00_namesapce.yml

add label and update namespace info for internal routing

---

namespaces/live.cloud-platform.service.justice.gov.uk/family-mediators-api-production/resources/rds.tf

Required before upgrading Postgres

Change db instance class for family mediators production

---

namespaces/live.cloud-platform.service.justice.gov.uk/disclosure-checker-production/resources/rds.tf

Required before Postgres upgrade

Change db instance class for disclosure tracker production

---

namespaces/live-2.cloud-platform.service.justice.gov.uk/jacksapp-dev/resources/ecr.tf

- feat: Add dev env to live-2 for training purpose
- fix(variable): Remove cluster_name var
- fix: Remove cluster_name var
- fix(ecr): change ecr name

change ecr name

---

namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-preprod/resources/rds.tf

Update storage for court-probation-preprod

Update storage for court-probation-preprod

---

.checksum
namespaces/live.cloud-platform.service.justice.gov.uk/incident-management-dev/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/incident-management-dev/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/incident-management-dev/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/incident-management-dev/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/incident-management-dev/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/incident-management-dev/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/incident-management-dev/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/incident-management-dev/resources/versions.tf

Using OPG repo, which in turn is based on the Monzo, incident.io repo.

Adding development environment to test incident management app

---

namespaces/live.cloud-platform.service.justice.gov.uk/offender-events-preprod/resources/prisoner-offender-events-sub-queue.tf

SDI-450 Removal of the /events endpoint from prison-api

---

namespaces/live.cloud-platform.service.justice.gov.uk/calculate-release-dates-api-prod/resources/pingdom.tf
namespaces/live.cloud-platform.service.justice.gov.uk/calculate-release-dates-api-prod/resources/versions.tf

Re-committed changes to this file to bypass merge conflict in already approved PR https://github.com/ministryofjustice/cloud-platform-environments/pull/9516

Crs 1114 - Committed same changes in a new branch to avoid merge conflict

---

namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-dev/resources/ecr.tf
namespaces/live.cloud-platform.service.justice.gov.uk/incident-management-dev/resources/ecr.tf
namespaces/live.cloud-platform.service.justice.gov.uk/incident-management-dev/resources/variables.tf

NOTE, default settings for now, as this is PoC.

Adding an ecr to the incident-management-dev namespace

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-historical-prisoner-dev/resources/es.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-probation-search-dev/resources/es.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-probation-search-preprod/resources/es.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-probation-search-prod/resources/es.tf
namespaces/live.cloud-platform.service.justice.gov.uk/manage-intelligence-dev/resources/elasticsearch.tf
namespaces/live.cloud-platform.service.justice.gov.uk/peoplefinder-demo/resources/elasticsearch.tf
namespaces/live.cloud-platform.service.justice.gov.uk/peoplefinder-development/resources/elasticsearch.tf
namespaces/live.cloud-platform.service.justice.gov.uk/peoplefinder-production/resources/elasticsearch.tf
namespaces/live.cloud-platform.service.justice.gov.uk/peoplefinder-staging/resources/elasticsearch.tf
namespaces/live.cloud-platform.service.justice.gov.uk/prisoner-content-hub-development/resources/elasticsearch.tf
namespaces/live.cloud-platform.service.justice.gov.uk/prisoner-content-hub-production/resources/elasticsearch.tf
namespaces/live.cloud-platform.service.justice.gov.uk/prisoner-content-hub-staging/resources/elasticsearch.tf
namespaces/live.cloud-platform.service.justice.gov.uk/prisoner-offender-search-dev/resources/es.tf
namespaces/live.cloud-platform.service.justice.gov.uk/prisoner-offender-search-preprod/resources/es.tf
namespaces/live.cloud-platform.service.justice.gov.uk/prisoner-offender-search-prod/resources/es.tf

This PR will remove override_main_response_version set as default to false

Update es module to latest

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-estimate-financial-eligibility-for-legal-aid-uat/resources/serviceaccount.tf

Follows on from https://github.com/ministryofjustice/cloud-platform-environments/pull/9536

Serviceaccount permissions - try plural to see if that gets it working

---

namespaces/live.cloud-platform.service.justice.gov.uk/check-financial-eligibility-partner-uat/resources/serviceaccount.tf

Set four actions secrets in ministryofjustice/check-financial-eligibility-partner

Add some Github actions secrets to CFE-P repo

---

namespaces/live.cloud-platform.service.justice.gov.uk/check-financial-eligibility-partner-uat/resources/serviceaccount.tf

The service account now handles grafana

add configmaps to serviceaccount

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-cla-backend-staging/04-networkpolicy.yaml

- Adding cla public to cla back namespace.

LGA-2267 adding in laa cla public staging to cla backend namespace

---

.checksum
namespaces/live.cloud-platform.service.justice.gov.uk/laa-status-dashboard-development/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-status-dashboard-development/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-status-dashboard-development/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-status-dashboard-development/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-status-dashboard-development/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-status-dashboard-development/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-status-dashboard-development/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-status-dashboard-development/resources/versions.tf

Add laa-status-dashboard-development namespace

---

namespaces/live.cloud-platform.service.justice.gov.uk/offender-events-dev/11-prometheus-sqs-sns.yaml

https://dsdmoj.atlassian.net/browse/HEAT-46

HEAT-46: add link to Grafana dashboard for Offender Events Dev SQS & SNS alerts

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-status-dashboard-development/resources/ecr.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-status-dashboard-development/resources/elasticache.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-status-dashboard-development/resources/rds-postgresql.tf

Adding ECR, RDS Postgres (via CLI) and Elasticache (manually).

Add resources to laa-status-dashboard-development

---

namespaces/live.cloud-platform.service.justice.gov.uk/offender-events-prod/09-prometheus-sqs-sns.yaml

https://dsdmoj.atlassian.net/browse/HEAT-46

HEAT-46: add link to Grafana dashboard for Offender Events Prod SQS & SNS alerts

---

namespaces/live.cloud-platform.service.justice.gov.uk/calculate-release-dates-api-dev/resources/pingdom.tf
namespaces/live.cloud-platform.service.justice.gov.uk/calculate-release-dates-api-dev/resources/versions.tf

Add a new uptime check for the development api and report it to farsight-alerts

New Pingdom Check

---

namespaces/live.cloud-platform.service.justice.gov.uk/calculate-release-dates-api-preprod/resources/pingdom.tf
namespaces/live.cloud-platform.service.justice.gov.uk/calculate-release-dates-api-preprod/resources/versions.tf

and report it to farsight-alerts

Add a new uptime check for the preprod api 

---

namespaces/live.cloud-platform.service.justice.gov.uk/calculate-release-dates-preprod/resources/pingdom.tf
namespaces/live.cloud-platform.service.justice.gov.uk/calculate-release-dates-preprod/resources/versions.tf

For the Preprod Frontend Service

Add new Pingdom Alert

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-probation-integration-services-preprod/05-certificates.yml

This is by including shorter dnsname

Fix cert for prison-case-notes-to-probation

---

.github/workflows/po-linter.yaml

Removing detail summary on success as the result will be blank if passed, this is only needed for failed test to show error

feat(workflow): Update po-linter action to separate success and failed pr comments

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-interventions-prototype/01-rbac.yaml

So that we can help debug deployment and operational problems
@emmalouisehidalgolaw could you please approve as the original owner needs to approve such additions
https://dsdmoj.atlassian.net/browse/IPB-123

Allow developer access to prototype namespace

---

namespaces/live.cloud-platform.service.justice.gov.uk/track-a-query-production/resources/ecr.tf

Reverts ministryofjustice/cloud-platform-environments#9662

Revert "track-a-query-production Update team on ECR resource"

---

namespaces/live.cloud-platform.service.justice.gov.uk/check-financial-eligibility-partner-staging/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-development/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-probation-estate-dev/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-probation-estate-preprod/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-api-dev/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-api-staging/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-api-uat/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-estimate-financial-eligibility-for-legal-aid-staging/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-hmrc-interface-staging/resources/serviceaccount-circleci.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-hmrc-interface-uat/resources/serviceaccount-circleci.tf

Reverts ministryofjustice/cloud-platform-environments#9688.

Revert "Destroy service account for non-production environments" - recreate service accounts for non-production environments

---

namespaces/live.cloud-platform.service.justice.gov.uk/check-financial-eligibility-partner-production/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-production/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-probation-estate-prod/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-api-production/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-estimate-financial-eligibility-for-legal-aid-production/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-hmrc-interface-production/resources/serviceaccount.tf

Reverts ministryofjustice/cloud-platform-environments#9689

Revert "Destroy service account for production environments" - recreate service accounts in production environments

---

namespaces/live.cloud-platform.service.justice.gov.uk/approved-premises-design-history/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/cjs-dashboard-demo/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/evidencelibrary-test/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-demo/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-rap-design-history/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/interventions-design-history/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/jason-design-demo/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/justicedata-test/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-maat-test/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/makerecalldecisions-design-history/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/manage-pom-cases-design-history/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/manage-supervisions-design-history/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/rob-sandbox/resources/serviceaccount.tf

Reverts ministryofjustice/cloud-platform-environments#9694

Revert "Destroy service account for test, demo, sandbox, history environments" - add service account back in

---

namespaces/live.cloud-platform.service.justice.gov.uk/chaps-staging/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/disclosure-checker-staging/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/family-mediators-api-staging/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/fj-cait-staging/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-staging/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/justicedata-staging/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-criminal-legal-aid-staging/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-criminal-applications-datastore-staging/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-review-criminal-legal-aid-staging/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/soc-staging/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/ubi-staging/resources/serviceaccount.tf

Reverts ministryofjustice/cloud-platform-environments#9696

Revert "Destroy service account for staging environments" - add service accounts back to staging

---

namespaces/live.cloud-platform.service.justice.gov.uk/check-financial-eligibility-partner-uat/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/check-financial-eligibility-uat/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-uat/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-estimate-financial-eligibility-for-legal-aid-uat/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/legal-framework-api-uat/resources/serviceaccount.tf

Reverts ministryofjustice/cloud-platform-environments#9699

Revert "Destroy service account for uat environments" - recreate service accounts

---

namespaces/live.cloud-platform.service.justice.gov.uk/data-eng-uploader-preprod/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-complexity-of-need-preprod/resources/serviceaccount-circleci.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-probation-integration-services-preprod/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-workload-preprod/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/workforce-management-preprod/resources/serviceaccount.tf

Reverts ministryofjustice/cloud-platform-environments#9701

Revert "Destroy service account for pre-production environments" - recreate service accounts for pre-prod

---

namespaces/live.cloud-platform.service.justice.gov.uk/analytical-platform-poc/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/cloud-platform-reference-app-github-action/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/cloud-platform-reference-app/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/cloudplatformdiscovery-fs/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/eligibility-estimate/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-incentives-tool/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-prisoner-education/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-probation-webops-poc/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-criminal-applications-datastore-harness/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-test-viewer/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/maintenance-pages/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/manage-a-workforce/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/moj-frontend/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/pfs-education-admin-tool/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/record-a-goose-sighting/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/request-info-from-moj/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/workforce-management/resources/serviceaccount.tf

Reverts ministryofjustice/cloud-platform-environments#9703

Revert "Destroy service account for unqualified environments" - recreate service accounts

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-test-viewer/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/maintenance-pages/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/manage-a-workforce/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/moj-frontend/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/pfs-education-admin-tool/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/record-a-goose-sighting/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/request-info-from-moj/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/workforce-management/resources/variables.tf

Reverts ministryofjustice/cloud-platform-environments#9705

Revert "Force change on missed namespaces"

---

namespaces/live.cloud-platform.service.justice.gov.uk/chaps-production/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/cloud-platform-reports-prod/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/contact-moj-production/resources/service-account-github.tf
namespaces/live.cloud-platform.service.justice.gov.uk/courts-local-scorecard-prod/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/data-eng-uploader-prod/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/disclosure-checker-production/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/dso-monitoring-prod/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/evidencelibrary-prod/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/family-mediators-api-production/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/fj-cait-production/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-prod/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-complexity-of-need-production/resources/serviceaccount-circleci.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-ems-prod/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-probation-integration-services-prod/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-reference-data-prod/resources/serviceaccount-github.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-workload-prod/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hosting-data-api-production/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hosting-data-production/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/justicedata-prod/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/makeaplea-prod/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/pact-broker-prod/resources/serviceaccount-github.tf
namespaces/live.cloud-platform.service.justice.gov.uk/parliamentary-questions-production/resources/service-account-github.tf
namespaces/live.cloud-platform.service.justice.gov.uk/peoplefinder-production/resources/service-account-github.tf
namespaces/live.cloud-platform.service.justice.gov.uk/soc-production/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/track-a-query-production/resources/service-account-github.tf
namespaces/live.cloud-platform.service.justice.gov.uk/ubi-prod/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/workforce-management-prod/resources/serviceaccount.tf

Reverts ministryofjustice/cloud-platform-environments#9707

Revert "Destroy service account for production environments" - recreate service accounts for production environments

---

.checksum
namespaces/live.cloud-platform.service.justice.gov.uk/techdebt-dev/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/techdebt-dev/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/techdebt-dev/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/techdebt-dev/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/techdebt-dev/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/techdebt-dev/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/techdebt-dev/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/techdebt-dev/resources/versions.tf

* create new namespace request techdebt team

Create namespace for techdebt

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-historical-prisoner-dev/resources/es.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-probation-search-dev/resources/es.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-probation-search-preprod/resources/es.tf
namespaces/live.cloud-platform.service.justice.gov.uk/manage-intelligence-dev/resources/elasticsearch.tf
namespaces/live.cloud-platform.service.justice.gov.uk/peoplefinder-demo/resources/elasticsearch.tf
namespaces/live.cloud-platform.service.justice.gov.uk/peoplefinder-development/resources/elasticsearch.tf
namespaces/live.cloud-platform.service.justice.gov.uk/peoplefinder-staging/resources/elasticsearch.tf
namespaces/live.cloud-platform.service.justice.gov.uk/prisoner-content-hub-development/resources/elasticsearch.tf
namespaces/live.cloud-platform.service.justice.gov.uk/prisoner-content-hub-staging/resources/elasticsearch.tf
namespaces/live.cloud-platform.service.justice.gov.uk/prisoner-offender-search-dev/resources/es.tf
namespaces/live.cloud-platform.service.justice.gov.uk/prisoner-offender-search-preprod/resources/es.tf

Reverts ministryofjustice/cloud-platform-environments#9718

Revert "Remove ES SA from non-production environments" - recreate ES SA for non-production environments

---

namespaces/live.cloud-platform.service.justice.gov.uk/pathfinder-dev/resources/analytical-platform-access.tf

Reverts ministryofjustice/cloud-platform-environments#9738

Revert "Remove IRSA SA from pathfinder-dev" - recreate pathfinder-dev IRSA serviceaccount

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-probation-search-prod/resources/es.tf
namespaces/live.cloud-platform.service.justice.gov.uk/peoplefinder-production/resources/elasticsearch.tf
namespaces/live.cloud-platform.service.justice.gov.uk/prisoner-content-hub-production/resources/elasticsearch.tf
namespaces/live.cloud-platform.service.justice.gov.uk/prisoner-offender-search-prod/resources/es.tf

Reverts ministryofjustice/cloud-platform-environments#9721

Revert "Remove ES SA from production environments" - recreate ES SA tokens for production

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-prisoner-education-design-history/resources/github-repo.tf

Design history module is not supported any more

This module is not available

---

namespaces/live.cloud-platform.service.justice.gov.uk/prisoner-offender-search-dev/resources/es.tf

Reverts ministryofjustice/cloud-platform-environments#9713

Revert "SDI-514 Improve security of ElasticSearch"

---

namespaces/live.cloud-platform.service.justice.gov.uk/offender-management-staging/resources/ecr-allocation-manager.tf
namespaces/live.cloud-platform.service.justice.gov.uk/offender-management-staging/resources/elasticache.tf
namespaces/live.cloud-platform.service.justice.gov.uk/offender-management-staging/resources/rds-allocations-api.tf

This allows sharing of the same data sources between environments

Create secrets in offender-management-test2 NS that use -staging data

---

namespaces/live.cloud-platform.service.justice.gov.uk/ap-gold-scorecard-form-prod/resources/cross-iam-role-sa.tf

in this change:
- update service account IAM role permissions to allow read access to Athena
- create IAM user that will be used to allow access to S3 buckets in the analytical platform data aws account

modify IAM permissions and add user for athena

---

namespaces/live.cloud-platform.service.justice.gov.uk/abundant-namespace-testing-sw/resources/rds.tf

This is to recreate RDS secrets for testing kubernetes resource updated field

switch back to rds module release tag

---

namespaces/live-2.cloud-platform.service.justice.gov.uk/poornima-dev/resources/variables.tf

To see if PR resource can add any comments

Test apply namespace PR

---

namespaces/live-2.cloud-platform.service.justice.gov.uk/poornima-dev/resources/variables.tf

This is by adding Merge resource

Test apply namespace attempt2

---

namespaces/live-2.cloud-platform.service.justice.gov.uk/poornima-dev/resources/variables.tf

Test comments using concourse

---

namespaces/live-2.cloud-platform.service.justice.gov.uk/poornima-dev/resources/variables.tf

Reverts ministryofjustice/cloud-platform-environments#9857

Revert "Update variables.tf to test the merged-pr-resource"

---

namespaces/live.cloud-platform.service.justice.gov.uk/money-to-prisoners-prod/05-service-accounts.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/money-to-prisoners-prod/resources/ecr.tf

Grant cross-namespace access to service account for use in GitHub Actions for prisoner money

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-development/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-development/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-development/resources/variables.tf

An additional team was manually created and will be removed. Use the correct team name that was automatically created.

Update Github team name for HMPPS Integration API

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-user-preferences-prod/01-rbac.yaml

This is to allow the dps-bootstrap scripts to be run

🔐 PIC-2679: Grant dps-tech access to hmpps-user-preferences-prod

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-education-employment-dev/06-certificate.yaml

ESWE-474 Change DNS Name - DEV

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-education-employment-preprod/06-certificate.yaml

ESWE-474 Change DNS Name - PREPROD

---

namespaces/live.cloud-platform.service.justice.gov.uk/techdebt-dev/resources/ecr.tf

* PR request to create ECR repository for names Techdept

ecr request for techdebt-dev

---

.checksum
namespaces/live-2.cloud-platform.service.justice.gov.uk/cloud-platform-go-get-module/00-namespace.yaml
namespaces/live-2.cloud-platform.service.justice.gov.uk/cloud-platform-go-get-module/01-rbac.yaml
namespaces/live-2.cloud-platform.service.justice.gov.uk/cloud-platform-go-get-module/02-limitrange.yaml
namespaces/live-2.cloud-platform.service.justice.gov.uk/cloud-platform-go-get-module/03-resourcequota.yaml
namespaces/live-2.cloud-platform.service.justice.gov.uk/cloud-platform-go-get-module/04-networkpolicy.yaml
namespaces/live-2.cloud-platform.service.justice.gov.uk/cloud-platform-go-get-module/resources/main.tf
namespaces/live-2.cloud-platform.service.justice.gov.uk/cloud-platform-go-get-module/resources/variables.tf
namespaces/live-2.cloud-platform.service.justice.gov.uk/cloud-platform-go-get-module/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/cloud-platform-go-get-module/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/cloud-platform-go-get-module/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/cloud-platform-go-get-module/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/cloud-platform-go-get-module/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/cloud-platform-go-get-module/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/cloud-platform-go-get-module/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/cloud-platform-go-get-module/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/cloud-platform-go-get-module/resources/versions.tf

This PR creates a new namespace used for a development idea.
https://github.com/ministryofjustice/cloud-platform-go-get-module

Add new namespace: cloud-platform-go-get-module

---

namespaces/live.cloud-platform.service.justice.gov.uk/offender-events-dev/resources/topic.tf

See [Slack thread](https://mojdt.slack.com/archives/C04HL1GJC3V/p1674139329138029)

Adding secret management for prison-data-compliance-dev

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-events-dev/resources/hmpps-domain-events-topic.tf

This will create new key for existing user

Add new user for hmpps-domain-events-dev

---

namespaces/live.cloud-platform.service.justice.gov.uk/offender-events-prod/resources/topic.tf

See [Slack thread](https://mojdt.slack.com/archives/C04HL1GJC3V/p1674139329138029)

Adding secret management for prison-data-compliance-prod

---

namespaces/live.cloud-platform.service.justice.gov.uk/offender-events-preprod/resources/topic.tf

See [Slack thread](https://mojdt.slack.com/archives/C04HL1GJC3V/p1674139329138029)

Adding secret management for prison-data-compliance-preprod

---

namespaces/live.cloud-platform.service.justice.gov.uk/ap-judicial-reviews-app-prod/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/ap-judicial-reviews-app-prod/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/ap-judicial-reviews-app-prod/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/ap-judicial-reviews-app-prod/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/ap-judicial-reviews-app-prod/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/ap-judicial-reviews-app-prod/resources/cross-iam-role-sa.tf
namespaces/live.cloud-platform.service.justice.gov.uk/ap-judicial-reviews-app-prod/resources/ecr.tf
namespaces/live.cloud-platform.service.justice.gov.uk/ap-judicial-reviews-app-prod/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/ap-judicial-reviews-app-prod/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/ap-judicial-reviews-app-prod/resources/versions.tf

Adding namespace and requested resources (ECR, IRSA) for Judicial reviews app migration

Anpl 1395/add test app namespace

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-development/resources/api_gateway.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-development/resources/ecr.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-development/resources/locals.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-development/resources/main.tf

- Extract a `default_tags` local.
- Remove unnecessary comments in ECR file.

Refactor: Extract default tags for HMPPS Integration API development

---

namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-staging/08-certificate.yaml

Add certificate for new VSIP service (hmpps-manage-prison-visits-orchestration) for staging env.

Add certificate for new VSIP service - staging

---

namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-preprod/08-certificate.yaml

Add certificate for new VSIP service (hmpps-manage-prison-visits-orchestration) for preprod env.

Add certificate for new VSIP service - preprod

---

namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-prod/08-certificate.yaml

Add certificate for new VSIP service (hmpps-manage-prison-visits-orchestration) for production env.

Add certificate for new VSIP service - production env

---

.checksum
namespaces/live.cloud-platform.service.justice.gov.uk/sjpr-prod/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/sjpr-prod/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/sjpr-prod/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/sjpr-prod/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/sjpr-prod/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/sjpr-prod/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/sjpr-prod/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/sjpr-prod/resources/versions.tf

Corrected the team, and the cloning method. Otherwise the same information

adding sjpr, take 2

---

namespaces/live.cloud-platform.service.justice.gov.uk/offender-events-dev/resources/topic.tf

Follows suggestion done with https://github.com/ministryofjustice/cloud-platform-environments/pull/10289
See [Slack thread](https://mojdt.slack.com/archives/C69NWE339/p1674222931465879?thread_ts=1674216124.498369&cid=C69NWE339)

Add new user for offender-events-dev

---

namespaces/live.cloud-platform.service.justice.gov.uk/sjpr-prod/resources/serviceaccount.tf

Signed-off-by: Amit Kohli <data@amitkohli.com>

adding service account

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-uat/resources/elasticache.tf

[laa-apply-for-legalaid-uat] Bump redis 4.0.10.0 to 6.2+

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-uat/resources/elasticache.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-hmrc-interface-uat/resources/elasticache.tf

Change redis `node_type` to `cache.t4g.medium`

[laa-hmrc-interface-uat] change redis node type

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-uat/resources/elasticache.tf

Change redis node_type to cache.t4g.medium

[laa-apply-for-legalaid-uat] change redis node type

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-development/resources/api_gateway.tf

- Remove unnecessary "/" API Gateway resource.
- Add request parameters to enable forwarding of requests to our API.

Fix API Gateway forwarding requests to HMPPS Integration API

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-hmrc-interface-staging/resources/elasticache.tf

Change redis `node_type` to `cache.t4g.medium`

[laa-hmrc-interface-staging] Change redis `node_type` to `cache.t4g.medium`

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-production/resources/elasticache.tf

[laa-apply-for-legalaid-production] Bump redis 4.0.10.0 to 6.2+

---

namespaces/live.cloud-platform.service.justice.gov.uk/offender-events-preprod/resources/topic.tf

Same as https://github.com/ministryofjustice/cloud-platform-environments/pull/10338

Add new user for offender-events-preprod

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-production/resources/elasticache.tf

Change redis node_type to cache.t4g.medium

[laa-apply-for-legalaid-production] change redis node type

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-hmrc-interface-production/resources/elasticache.tf

Change redis node_type to cache.t4g.medium

[laa-hmrc-interface-production] change redis node_type

---

namespaces/live.cloud-platform.service.justice.gov.uk/offender-events-prod/resources/topic.tf

Same as https://github.com/ministryofjustice/cloud-platform-environments/pull/10338

Add new user for offender-events-prod

---

namespaces/live.cloud-platform.service.justice.gov.uk/offender-events-preprod/resources/topic.tf

This reverts commit cfc0f91a9752c5da8b7b2b3e0a7898184e6b55be.

Revert "Add new user for offender-events-preprod"

---

namespaces/live.cloud-platform.service.justice.gov.uk/offender-events-prod/resources/topic.tf

This reverts commit 52a7afb7c1efbbc477e00ef3276d71883a5c17bc.

Revert "Add new user for offender-events-prod"

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-visit-someone-in-prison-prototype/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-visit-someone-in-prison-prototype/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-visit-someone-in-prison-prototype/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-visit-someone-in-prison-prototype/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-visit-someone-in-prison-prototype/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-visit-someone-in-prison-prototype/resources/basic-auth.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-visit-someone-in-prison-prototype/resources/ecr.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-visit-someone-in-prison-prototype/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-visit-someone-in-prison-prototype/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-visit-someone-in-prison-prototype/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-visit-someone-in-prison-prototype/resources/versions.tf

Add namespace for new prototype - following instructions in https://user-guide.cloud-platform.service.justice.gov.uk/documentation/getting-started/prototype-kit.html

VB-1715: Add namespace for hmpps-visit-someone-in-prison-prototype

---

namespaces/live.cloud-platform.service.justice.gov.uk/cjs-dashboard-development/02-limitrange.yaml

Increase max cpu for cjs-dashbaord-development

---

namespaces/live.cloud-platform.service.justice.gov.uk/cjs-dashboard-production/02-limitrange.yaml

Update CPU and memory limits to match development.

Update limits on cjs-dashboard-production

---

namespaces/live.cloud-platform.service.justice.gov.uk/cjs-dashboard-demo/02-limitrange.yaml

Update values to match development.

Update CPU and memory limits on cjs-dashboard-demo

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-events-dev/resources/gdx-data-share-subscription.tf

Prisoner received data share with GDX event platform.  

---

namespaces/live.cloud-platform.service.justice.gov.uk/cjs-dashboard-production/05-certificate.yaml

Add in the new cert for this namespace

Set DNS to new domain

---

namespaces/live.cloud-platform.service.justice.gov.uk/cccd-dev-lgfs/resources/elasticache.tf

Starting to test Redis 6 on a dev environment for CCCD.

Update Redis server to version 6

---

namespaces/live.cloud-platform.service.justice.gov.uk/pathfinder-dev/resources/s3.tf

Remove athena resource, reporting s3 bucket

remove_athena_reporting_s3_bucket_from_pathfinder_dev_force

---

namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-publisher-test/resources/publisher.tf

Add value for rds_family and db_instance_class, update postgres version to 12
Note - also added more whitespace for formatting

Update Postgres version

---

namespaces/live.cloud-platform.service.justice.gov.uk/ap-app-poc-bde/resources/serviceaccount.tf

Change to add service account to namespace

add service account to repo

---

namespaces/live.cloud-platform.service.justice.gov.uk/grc-preprod/resources/main.tf

https://tools.hmcts.net/jira/browse/RST-5088

Add tag for pet team to staging

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-criminal-legal-aid-staging/resources/serviceaccount.tf

This hopefully will cope when applying through github actions some new resources we have in our namespace.

Add additional service account rules

---

namespaces/live.cloud-platform.service.justice.gov.uk/cccd-production/resources/elasticache.tf

**Note:** To be deployed out of hours and after the following PR have already been merged:
* #10570 
* #10571
* #10572

Update Redis server to version 6 in production environment

---

namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-demo/resources/ecr.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-demo/resources/variables.tf

We want these to be generated in our GitActions.

Hale platform add vars demo

---

namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-prod/resources/ecr.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-prod/resources/variables.tf

Add these new secrets to the GitAction environment area.

Create new ECR secrets in GitActions

---

namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-dev/resources/ecr.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-dev/resources/variables.tf

Add ECR secrets to GitActions.

Add ECR secrets to GitActions dev environment

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-incentives-dev/resources/elasticache.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-incentives-dev/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-incentives-dev/resources/variables.tf

…upgrading terraform modules and exporting more outputs in k8s secrets

Rotate `dev` RDS & Elasticache Redis passwords

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-incentives-preprod/resources/elasticache.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-incentives-preprod/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-incentives-preprod/resources/variables.tf

…upgrading terraform modules and exporting more outputs in k8s secrets

Rotate `preprod` RDS & Elasticache Redis passwords

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-hmrc-interface-production/resources/rds.tf

Upgrade laa-hmrc-interface prod to postgres14

Upgrade laa-hmrc-interface prod to postgres14

---

namespaces/live.cloud-platform.service.justice.gov.uk/record-a-goose-exercise/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/record-a-goose-exercise/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/record-a-goose-exercise/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/record-a-goose-exercise/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/record-a-goose-exercise/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/record-a-goose-exercise/resources/ecr.tf
namespaces/live.cloud-platform.service.justice.gov.uk/record-a-goose-exercise/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/record-a-goose-exercise/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/record-a-goose-exercise/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/record-a-goose-exercise/resources/versions.tf

Used by the accessibility team for training within and outwith MOJ

Add "Record a Goose Sighting" exercise site

---

namespaces/live.cloud-platform.service.justice.gov.uk/offender-events-dev/resources/hmpps-prisoner-from-nomis-iep-sub-queue.tf
namespaces/live.cloud-platform.service.justice.gov.uk/offender-events-dev/resources/hmpps-prisoner-from-nomis-sentencing-sub-queue.tf
namespaces/live.cloud-platform.service.justice.gov.uk/offender-events-dev/resources/hmpps-prisoner-from-nomis-visits-sub-queue.tf

* New subscription for sentencing migration 
* Initial step to move subscription onto 2 queues without a breaking change

SDI-554 New offender event subscription

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-criminal-legal-aid-staging/resources/api-auth-secret.tf

This may not work until previous PR #10687 is applied.

Copy secret to another namespace

---

.checksum
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-contribution-dev/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-contribution-dev/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-contribution-dev/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-contribution-dev/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-contribution-dev/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-contribution-dev/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-contribution-dev/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-contribution-dev/resources/versions.tf

LCAM-418|added dev namespace for laa-crown-court-contribution

---

.checksum
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-contribution-test/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-contribution-test/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-contribution-test/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-contribution-test/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-contribution-test/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-contribution-test/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-contribution-test/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-contribution-test/resources/versions.tf

LCAM-418|added test namespace for laa-crown-court-contribution

---

.checksum
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-contribution-uat/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-contribution-uat/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-contribution-uat/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-contribution-uat/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-contribution-uat/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-contribution-uat/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-contribution-uat/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-contribution-uat/resources/versions.tf

LCAM-418|added uat namespace for laa-crown-court-contribution

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-contribution-dev/05-serviceaccount-circleci.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-contribution-dev/resources/ecr.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-contribution-dev/resources/pingdom.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-contribution-dev/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-contribution-dev/resources/versions.tf

LCAM-418|added rds, ecr, pingdom and service account

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-contribution-dev/resources/pingdom.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-contribution-test/05-serviceaccount-circleci.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-contribution-test/resources/pingdom.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-contribution-test/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-contribution-test/resources/versions.tf

Lcam 418  configure resources contribution test

---

namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-dev/resources/s3.tf

Allow WP to push/pull files to public s3 bucket from within pod.

Allow push/pull files to s3 bucket

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-contribution-staging/05-serviceaccount-circleci.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-contribution-staging/resources/pingdom.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-contribution-staging/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-contribution-staging/resources/versions.tf

LCAM-418|added rds, pingdom and service account-staging

---

namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-dev/resources/s3.tf

Add required Principal field to policy

---

namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-prod/09-prometheus-k8s.yaml

and  on pre-sentence-service-wproofreader ingress 5xx

🔈 PIC-2741: Add alerting on pre-sentence-service RDS cpu usage

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-contribution-uat/05-serviceaccount-circleci.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-contribution-uat/resources/pingdom.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-contribution-uat/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-contribution-uat/resources/versions.tf

LCAM-418|added rds, pingdom and service account- uat

---

namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-frontend-svc-dev/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-frontend-svc-dev/08-certificate.yaml

VB-1817 Dev Create server for Public VSiP UI

VB-1817 Create server for Public VSiP UI

---

.checksum
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-ap-shiny-cp-deployment-dev/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-ap-shiny-cp-deployment-dev/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-ap-shiny-cp-deployment-dev/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-ap-shiny-cp-deployment-dev/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-ap-shiny-cp-deployment-dev/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-ap-shiny-cp-deployment-dev/resources/ecr.tf
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-ap-shiny-cp-deployment-dev/resources/irsa.tf
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-ap-shiny-cp-deployment-dev/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-ap-shiny-cp-deployment-dev/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-ap-shiny-cp-deployment-dev/resources/versions.tf

Testing AP app migration automation for ap-shiny-cp-deployment-dev
Namespace: data-platform-app-ap-shiny-cp-deployment-dev

Test AP app migration automation - ap-shiny-cp-deployment-dev

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-dev/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-dev/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-dev/resources/variables.tf

NN-4655: add GithubTeam to hmpps-manage-adjudications-dev

---

.checksum
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-ap-shiny-cp-deployment-prod/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-ap-shiny-cp-deployment-prod/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-ap-shiny-cp-deployment-prod/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-ap-shiny-cp-deployment-prod/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-ap-shiny-cp-deployment-prod/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-ap-shiny-cp-deployment-prod/resources/ecr.tf
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-ap-shiny-cp-deployment-prod/resources/irsa.tf
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-ap-shiny-cp-deployment-prod/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-ap-shiny-cp-deployment-prod/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-ap-shiny-cp-deployment-prod/resources/versions.tf

Testing AP app migration automation for ap-shiny-cp-deployment-prod
Namespace: data-platform-app-ap-shiny-cp-deployment-prod

Test AP app migration automation - ap-shiny-cp-deployment-prod

---

namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-ap-shiny-cp-deployment-dev/resources/irsa.tf

Note: also created github env in target repo

add resource arn to irsa

---

namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-frontend-svc-preprod/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-frontend-svc-preprod/08-certificate.yaml

Create preprod server for Public VSiP UI

VB-1817 Create preprod server for Public VSiP UI

---

namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-dev/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-dev/09-certificate.yaml

Create dev server for Notifications & Alerts service

VB-1826 Create server for Notifications & Alerts service

---

namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-frontend-svc-prod/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-frontend-svc-prod/08-certificate.yaml

Create prod server for Public VSiP UI

VB-1817 Create prod server for Public VSiP UI

---

cmd/check-terraform-modules-are-latest/go.mod
cmd/check-terraform-modules-are-latest/go.sum

https://github.com/ministryofjustice/cloud-platform-environments/security/dependabot/18
https://github.com/ministryofjustice/cloud-platform-environments/security/dependabot/14

fix: 🐛 bump vulnerable deps

---

namespaces/live.cloud-platform.service.justice.gov.uk/keyworker-api-dev/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/keyworker-api-dev/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/keyworker-api-dev/resources/variables.tf

NN-4655: add GithubTeam to keyworker-api-dev

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-api-dev/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-api-dev/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-api-dev/resources/variables.tf

NN-4655: add GithubTeam to hmpps-manage-adjudications-api-dev

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-api-preprod/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-api-preprod/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-api-preprod/resources/variables.tf

NN-4655: add GithubTeam to hmpps-manage-adjudications-api-preprod

---

namespaces/live.cloud-platform.service.justice.gov.uk/keyworker-api-preprod/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/keyworker-api-preprod/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/keyworker-api-preprod/resources/variables.tf

NN-4655: add GithubTeam to keyworker-api-preprod

---

namespaces/live.cloud-platform.service.justice.gov.uk/whereabouts-api-dev/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/whereabouts-api-dev/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/whereabouts-api-dev/resources/variables.tf

NN-4655: add GithubTeam to whereabouts-api-dev

---

namespaces/live.cloud-platform.service.justice.gov.uk/whereabouts-api-preprod/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/whereabouts-api-preprod/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/whereabouts-api-preprod/resources/variables.tf

NN-4655: add GithubTeam to whereabouts-api-preprod

---

namespaces/live.cloud-platform.service.justice.gov.uk/manage-key-workers-dev/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/manage-key-workers-dev/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/manage-key-workers-dev/resources/variables.tf

NN-4655: add GithubTeam to manage-key-workers-dev

---

namespaces/live.cloud-platform.service.justice.gov.uk/manage-key-workers-preprod/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/manage-key-workers-preprod/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/manage-key-workers-preprod/resources/variables.tf

NN-4655: add GithubTeam to manage-key-workers-preprod

---

namespaces/live.cloud-platform.service.justice.gov.uk/prison-services-feedback-and-support-preprod/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/prison-services-feedback-and-support-preprod/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/prison-services-feedback-and-support-preprod/resources/variables.tf

NN-4655: add GithubTeam to prison-services-feedback-and-support-preprod

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-restricted-patients-dev/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-restricted-patients-dev/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-restricted-patients-dev/resources/variables.tf

NN-4655: add GithubTeam to hmpps-restricted-patients-dev

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-restricted-patients-preprod/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-restricted-patients-preprod/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-restricted-patients-preprod/resources/variables.tf

NN-4655: add GithubTeam to hmpps-restricted-patients-preprod

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-restricted-patients-api-dev/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-restricted-patients-api-dev/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-restricted-patients-api-dev/resources/variables.tf

NN-4655: add GithubTeam to hmpps-restricted-patients-api-dev

---

namespaces/live.cloud-platform.service.justice.gov.uk/prison-services-feedback-and-support-prod/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/prison-services-feedback-and-support-prod/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/prison-services-feedback-and-support-prod/resources/variables.tf

NN-4655: add GithubTeam to prison-services-feedback-and-support-prod

---

namespaces/live.cloud-platform.service.justice.gov.uk/manage-key-workers-prod/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/manage-key-workers-prod/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/manage-key-workers-prod/resources/variables.tf

NN-4655: add GithubTeam to manage-key-workers-prod

---

namespaces/live.cloud-platform.service.justice.gov.uk/digital-prison-services-prod/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/digital-prison-services-prod/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/digital-prison-services-prod/resources/variables.tf

NN-4655: add GithubTeam to digital-prison-services-prod

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-restricted-patients-prod/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-restricted-patients-prod/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-restricted-patients-prod/resources/variables.tf

NN-4655: add GithubTeam to hmpps-restricted-patients-prod

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-prod/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-prod/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-prod/resources/variables.tf

NN-4655: add GithubTeam to hmpps-manage-adjudications-prod

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-api-prod/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-api-prod/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-api-prod/resources/variables.tf

NN-4655: add GithubTeam to hmpps-manage-adjudications-api-prod

---

namespaces/live.cloud-platform.service.justice.gov.uk/offender-events-dev/11-prometheus-sqs-sns.yaml

SDI-636 Queue alerts going to wrong slack channel

---

namespaces/live.cloud-platform.service.justice.gov.uk/cfe-civil-uat/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/cfe-civil-uat/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/cfe-civil-uat/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/cfe-civil-uat/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/cfe-civil-uat/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/cfe-civil-uat/resources/ecr.tf
namespaces/live.cloud-platform.service.justice.gov.uk/cfe-civil-uat/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/cfe-civil-uat/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/cfe-civil-uat/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/cfe-civil-uat/resources/versions.tf

A UAT environment for the new 'CFE Civil' repo.

EL-691: Add CFE Civil UAT environment

---

namespaces/live.cloud-platform.service.justice.gov.uk/cfe-civil-uat/resources/ecr.tf

EL-691: Fix invalid ECR name

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-criminal-applications-datastore-staging/resources/sns-application-events.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-criminal-applications-datastore-staging/resources/sqs-applications-for-maat.tf

Mainly we want to trigger apply again, this is just moving code from one file to another, without introducing changes.

Reorganise some code

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-estimate-financial-eligibility-for-legal-aid-staging/resources/rds.tf

Borrowing config from check-financial-eligibility-partner-staging

EL-716: Add RDS to efe staging

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-estimate-financial-eligibility-for-legal-aid-production/resources/rds.tf

Borrowing config from check-financial-eligibility-partner-production

EL-716: Add RDS to efe production

---

namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-prod/09-prometheus-k8s.yaml

This is related to promethues alerts

Fix alert for court-probation-prod

---

namespaces/live.cloud-platform.service.justice.gov.uk/make-recall-decision-db-analysis/resources/rds-mssql.tf

Created with cloud-platform environment rds create

Adds RDS (SQL Server)

---

.checksum
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-production/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-production/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-production/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-production/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-production/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-production/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-production/resources/route53.tf
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-production/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-production/resources/versions.tf

Adding Data Platform Production namespace and creating Route 53 zone with technical documentation record

Add Data Platform Production

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-assure-hmrc-data-uat/resources/ecr.tf

Add ecr for laa-assure-hmrc-data application

Add ecr for laa-assure-hmrc-data application

---

.checksum
namespaces/live.cloud-platform.service.justice.gov.uk/laa-assure-hmrc-data-staging/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-assure-hmrc-data-staging/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-assure-hmrc-data-staging/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-assure-hmrc-data-staging/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-assure-hmrc-data-staging/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-assure-hmrc-data-staging/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-assure-hmrc-data-staging/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-assure-hmrc-data-staging/resources/versions.tf

Add laa-assure-hmrc-data-staging namespace

Add laa-assure-hmrc-data-staging namespace

---

.checksum
namespaces/live.cloud-platform.service.justice.gov.uk/laa-assure-hmrc-data-production/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-assure-hmrc-data-production/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-assure-hmrc-data-production/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-assure-hmrc-data-production/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-assure-hmrc-data-production/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-assure-hmrc-data-production/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-assure-hmrc-data-production/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-assure-hmrc-data-production/resources/versions.tf

Add laa-assure-hmrc-data-production namespace

Add laa-assure-hmrc-data-production namespace

---

namespaces/live.cloud-platform.service.justice.gov.uk/keyworker-api-prod/resources/rds.tf

NN-4479: post upgrade changes for keyworker-api-prod/rds

---

namespaces/live.cloud-platform.service.justice.gov.uk/money-to-prisoners-prod/resources/rds.tf

…and forbid postgres major & minor upgrades

Update `money-to-prisoners` prod database instance type

---

namespaces/live.cloud-platform.service.justice.gov.uk/whereabouts-api-prod/resources/rds.tf

NN-4479: post upgrade changes for whereabouts-api-prod/rds

---

namespaces/live.cloud-platform.service.justice.gov.uk/whereabouts-api-prod/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/whereabouts-api-prod/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/whereabouts-api-prod/resources/variables.tf

NN-4655: add GithubTeam to whereabouts-api-prod

---

namespaces/live.cloud-platform.service.justice.gov.uk/keyworker-api-prod/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/keyworker-api-prod/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/keyworker-api-prod/resources/variables.tf

NN-4655: add GithubTeam to keyworker-api-prod

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-restricted-patients-api-prod/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-restricted-patients-api-prod/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-restricted-patients-api-prod/resources/variables.tf

NN-4655: add GithubTeam to hmpps-restricted-patients-api-prod

---

namespaces/live.cloud-platform.service.justice.gov.uk/find-unclaimed-court-money-dev/resources/ecr.tf
namespaces/live.cloud-platform.service.justice.gov.uk/find-unclaimed-court-money-dev/resources/rds-postgresql.tf
namespaces/live.cloud-platform.service.justice.gov.uk/find-unclaimed-court-money-dev/resources/serviceaccount.tf

- Removes references to Github environments for github actions use as that is not set up yet.
- Adds RDS

Remove Github namespace & add RDS

---

namespaces/live.cloud-platform.service.justice.gov.uk/offender-events-prod/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/offender-events-prod/resources/variables.tf

Reverts ministryofjustice/cloud-platform-environments#11040

Revert "SDI-642: ✨ Add github team to access AWS console for offender-events-prod"

---

namespaces/live.cloud-platform.service.justice.gov.uk/offender-events-preprod/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/offender-events-preprod/resources/variables.tf

Reverts ministryofjustice/cloud-platform-environments#11039

Revert "SDI-642: ✨ Add github team to access AWS console for offender-events-preprod"

---

namespaces/live.cloud-platform.service.justice.gov.uk/offender-events-dev/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/offender-events-dev/resources/variables.tf

Reverts ministryofjustice/cloud-platform-environments#11038

Revert "SDI-642: ✨ Add github team to access AWS console for offender-events-dev"

---

namespaces/live.cloud-platform.service.justice.gov.uk/prisoner-offender-search-prod/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/prisoner-offender-search-prod/resources/variables.tf

Reverts ministryofjustice/cloud-platform-environments#11043

Revert "SDI-642: ✨ Add github team to access AWS console for prisoner-offender-search-prod"

---

namespaces/live.cloud-platform.service.justice.gov.uk/prisoner-offender-search-preprod/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/prisoner-offender-search-preprod/resources/variables.tf

Reverts ministryofjustice/cloud-platform-environments#11042

Revert "SDI-642: ✨ Add github team to access AWS console for prisoner-offender-search-preprod"

---

namespaces/live.cloud-platform.service.justice.gov.uk/prisoner-offender-search-dev/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/prisoner-offender-search-dev/resources/variables.tf

Reverts ministryofjustice/cloud-platform-environments#11041

Revert "SDI-642: ✨ Add github team to access AWS console for prisoner-offender-search-dev"

---

namespaces/live.cloud-platform.service.justice.gov.uk/mrd-proto/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/mrd-proto/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/mrd-proto/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/mrd-proto/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/mrd-proto/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/mrd-proto/resources/basic-auth.tf
namespaces/live.cloud-platform.service.justice.gov.uk/mrd-proto/resources/ecr.tf
namespaces/live.cloud-platform.service.justice.gov.uk/mrd-proto/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/mrd-proto/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/mrd-proto/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/mrd-proto/resources/versions.tf

This is a new proto for the second phase of the this project Public Beta

New design prototype for the make recall decisions team

---

namespaces/live.cloud-platform.service.justice.gov.uk/sjpr-prod/resources/variables.tf

our team now has a team email!

changing email

---

namespaces/live.cloud-platform.service.justice.gov.uk/grc-prod/05-certificate-apply-gender.yaml

apply-gender-recognition-certificate.service.gov.uk

Add new certificate for the migrated service

---

namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-frontend-svc-dev/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-frontend-svc-dev/07-certificate.yaml

removed VSiP name from url and repo and added visits

Update internal admin repo and url

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-assure-hmrc-data-staging/resources/rds-postgresql.tf

- Generate rds postgresql for laa-assure-hmrc-data-staging
- Update terraform version
- Remove read-replica config
- Removed unused terraform var

laa-assure-hmrc-data-staging - add rds

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-assure-hmrc-data-staging/resources/serviceaccount.tf

Add service account for gthb action workflow

laa-assure-hmrc-data - add service account for GHA

---

.checksum
namespaces/live.cloud-platform.service.justice.gov.uk/judicial-reviews-app/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/judicial-reviews-app/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/judicial-reviews-app/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/judicial-reviews-app/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/judicial-reviews-app/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/judicial-reviews-app/resources/ecr.tf
namespaces/live.cloud-platform.service.justice.gov.uk/judicial-reviews-app/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/judicial-reviews-app/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/judicial-reviews-app/resources/versions.tf

Create namespace for judicial-reviews application migrating from AP to CP

Anpl 1438 cp

---

namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-frontend-svc-preprod/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-frontend-svc-preprod/07-certificate.yaml

Change of name for project from vsip and visits (Repo/certs/dns)

Update internal admin repo and url for pre prod

---

namespaces/live.cloud-platform.service.justice.gov.uk/judicial-reviews-app/resources/serviceaccount.tf

Add service account  to judicial-reviews-app namespace

add service account to namespace

---

namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-frontend-svc-prod/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-frontend-svc-prod/07-certificate.yaml

Update internal admin repo and dns for prod, old cert needs to be deleted

Update internal admin repo and url for prod

---

namespaces/live.cloud-platform.service.justice.gov.uk/create-and-vary-a-licence-api-dev/resources/analytical-platform-access.tf
namespaces/live.cloud-platform.service.justice.gov.uk/create-and-vary-a-licence-api-dev/resources/variables.tf

Following instructions here 
[https://dsdmoj.atlassian.net/wiki/spaces/PPDE/pages/3297050829/Steps+to+set+up+daily+transfers+to+the+analytical+platform](url) 
to get our data flowing out to AP. Let me know if anything looks awry!

Cvl add analytical platform principal

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-events-dev/resources/hmpps-domain-events-topic.tf

INC-1119: fix name

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-events-dev/resources/hmpps-domain-events-topic.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-incentives-dev/resources/hmpps-events.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-incentives-dev/resources/sqs.tf

INC-1119: configure HMPPS Domain Events queue in hmpps-incentives-dev namespace

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-assure-hmrc-data-production/resources/route53.tf

[laa-assure-hmrc-data-production] Add route53 hosted zone

---

namespaces/live.cloud-platform.service.justice.gov.uk/find-unclaimed-court-money-dev/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/find-unclaimed-court-money-production/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/find-unclaimed-court-money-staging/resources/serviceaccount.tf

Add env vars for each environment configured in the repo

Add environment specific service account details

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-probation-search-preprod/resources/es.tf

for compatibility with non-graviton master nodes

PI-832 Switch back to m5 instances

---

.checksum
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-development/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-development/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-development/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-development/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-development/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-development/resources/github-actions-serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-development/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-development/resources/simulated-data-producer-rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-development/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-development/resources/versions.tf

Closes ministryofjustice/data-platform#172
Closes ministryofjustice/data-platform#173

Add Data Platform development namespace

---

namespaces/live.cloud-platform.service.justice.gov.uk/offender-management-staging/resources/elasticache.tf
namespaces/live.cloud-platform.service.justice.gov.uk/offender-management-staging/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/offender-management-staging/resources/rds-allocations-api.tf
namespaces/live.cloud-platform.service.justice.gov.uk/offender-management-staging/resources/sns.tf
namespaces/live.cloud-platform.service.justice.gov.uk/offender-management-staging/resources/sqs.tf
namespaces/live.cloud-platform.service.justice.gov.uk/offender-management-staging/resources/variables.tf

* SNS topic for publishing events.
* An SQS subscription to that for testing.

offender-management-staging: Add SNS events topic and SQS subscription

---

namespaces/live.cloud-platform.service.justice.gov.uk/ap-auth-proxy-prod/resources/ecr.tf
namespaces/live.cloud-platform.service.justice.gov.uk/ap-auth-proxy-prod/resources/variables.tf

This PR is to store the ecr credential  for ns: ap-auth-proxy-prod to github repo for github actions

ANPL-1418 Adding ecr credential to github (ap-auth-proxy-prod)

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-events-preprod/resources/hmpps-prisoner-nomis-update.tf

update cloud-platform-terraform-sqs version

SDI-639 Create a 'create-appointment' handler

---

namespaces/live.cloud-platform.service.justice.gov.uk/judicial-reviews-app/resources/serviceaccount.tf

Adding permissions for the service account.

judicial-reviews-app: add sa permissions

---

namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-prod/resources/haletest1-route53.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-prod/resources/haletest2-route53.tf

We want to test how the hale platform routes multipule domains via CP route53.

Add two test domains for the hale platform

---

namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-development/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-development/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-development/resources/variables.tf

data-platform-core-infra -> data-platform-cloud-platform-development

Update Data Platform Development to use new GitHub team

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-education-employment-prod/resources/elasticache.tf

Upgrade Redis
Upgrade module version
Add business-unit

ESWE-531 - Upgrade Redis - Prod

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-estimate-financial-eligibility-for-legal-aid-uat/03-resourcequota.yaml

As discussed with CP here: https://mojdt.slack.com/archives/C57UPMZLY/p1678120353097919

EL-788 Increase pods limit for CCQ UAT environment

---

namespaces/live.cloud-platform.service.justice.gov.uk/check-financial-eligibility-partner-uat/03-resourcequota.yaml

As discussed with CP here: https://mojdt.slack.com/archives/C57UPMZLY/p1678120353097919

LEP-40 Increase pods limit for CFE-P UAT environment

---

namespaces/live.cloud-platform.service.justice.gov.uk/cfe-civil-uat/03-resourcequota.yaml

As discussed with CP here: https://mojdt.slack.com/archives/C57UPMZLY/p1678120353097919

LEP-41 Increase pods limit for CFE-Civil UAT environment

---

namespaces/live.cloud-platform.service.justice.gov.uk/token-verification-api-dev/resources/elasticache.tf

Upgraded token-verification-api elasticache redis from "5.0.6" to V7

HAAR-1248: Upgraded token-verification-api elasticache redis

---

namespaces/live.cloud-platform.service.justice.gov.uk/cloud-platform-bots/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-base-adapter-test/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-monitoring/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-product-page-staging/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-product-portfolio-prod/resources/variables.tf

These namespaces don't have `variables.tf` files, so this adds them.

Add missing variables to namespaces

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-rehabilitation-ancilliary-jitbit-dev/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-rehabilitation-ancilliary-jitbit-dev/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-rehabilitation-ancilliary-jitbit-dev/resources/s3.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-rehabilitation-ancilliary-jitbit-dev/resources/variables.tf

2 main changes
- Change the team name used to authorise users into the namespace
- Add a new bucket to hold the app artefacts from the vendor

New hmpps jitbit bucket and team name change

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-events-preprod/resources/hmpps-prison-visits-event.tf

Setting up Queue with no subscription for our preprod environment because we have not implement the code to consume these events yet

VB-1929 Set up a queue in Cloud platform environments SQS for preprod

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-rehabilitation-ancilliary-jitbit-dev/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-community-rehabilitation-ancilliary-jitbit-dev/resources/serviceaccount.tf

Addition of required GH team to rbac and addition of service account for github actions

HMPPS Jitbit - fix RBAC and add service account

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-events-preprod/resources/hmpps-domain-events-topic.tf

INC-1119:  use AWS SSM to store hmpps-domain-events-preprod topic ARN

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-events-prod/resources/hmpps-domain-events-topic.tf

INC-1119:  use AWS SSM to store hmpps-domain-events-prod topic ARN

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-incentives-preprod/resources/hmpps-events.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-incentives-preprod/resources/sqs.tf

Same as https://github.com/ministryofjustice/cloud-platform-environments/pull/11141

INC-1119: configure HMPPS Domain Events queue in hmpps-incentives-preprod namespace

---

namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-dev/resources/s3.tf

We want to have access to view bucket items for the website

Enable ACL to bucket

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-incentives-preprod/resources/variables.tf

INC-1119: rename environment variable to preprod

---

.checksum
namespaces/live.cloud-platform.service.justice.gov.uk/philpayne-sandbox/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/philpayne-sandbox/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/philpayne-sandbox/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/philpayne-sandbox/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/philpayne-sandbox/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/philpayne-sandbox/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/philpayne-sandbox/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/philpayne-sandbox/resources/versions.tf

For learning and understanding CP better.

Create namespace for philpayne-sandbox

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-incentives-dev/resources/elasticache.tf

Change instance class & redis version in 1 go; worked last time, I think

Upgrade redis for `hmpps-incentives-dev`

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-incentives-prod/resources/elasticache.tf

Cf. #11609 which worked with minimal downtime but took ~25min (this should be faster as the instance type is not changing)

Upgrade redis for `hmpps-incentives-prod`

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-intelligence-test/resources/rds-aurora.tf
namespaces/live.cloud-platform.service.justice.gov.uk/manage-intelligence-dev/resources/rds-aurora.tf

Setting RDS instance_type to db.t4g.medium

updated RDS instance_type for IMS test and dev

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-criminal-legal-aid-staging/resources/rds.tf

Skip file was added in previous PR #11632.

Upgrade RDS to major version

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-criminal-legal-aid-staging/resources/rds.tf

Follow up to PRs #11632 and #11633.

Remove skip file and tweak RDS config

---

namespaces/live.cloud-platform.service.justice.gov.uk/bold-rr-ops-pilot-prototype/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/bold-rr-ops-pilot-prototype/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/bold-rr-ops-pilot-prototype/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/bold-rr-ops-pilot-prototype/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/bold-rr-ops-pilot-prototype/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/bold-rr-ops-pilot-prototype/resources/basic-auth.tf
namespaces/live.cloud-platform.service.justice.gov.uk/bold-rr-ops-pilot-prototype/resources/ecr.tf
namespaces/live.cloud-platform.service.justice.gov.uk/bold-rr-ops-pilot-prototype/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/bold-rr-ops-pilot-prototype/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/bold-rr-ops-pilot-prototype/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/bold-rr-ops-pilot-prototype/resources/versions.tf

Adding our mock-up design of the prototype to the cloud platform for sharing with stakeholders

Add BOLD RR operational pilot prototype

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-estimate-financial-eligibility-for-legal-aid-staging/resources/elasticache.tf

There is an issue with staging deploys it appears to be credential related, this PR rotates the credentials to see if that fixes the issue

CCQ STG rotate auth for staging

---

.checksum
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-gold-scorecard-form-prod/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-gold-scorecard-form-prod/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-gold-scorecard-form-prod/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-gold-scorecard-form-prod/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-gold-scorecard-form-prod/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-gold-scorecard-form-prod/resources/ecr.tf
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-gold-scorecard-form-prod/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-gold-scorecard-form-prod/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-gold-scorecard-form-prod/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-gold-scorecard-form-prod/resources/versions.tf

Testing AP app migration automation for gold-scorecard-form-prod
Namespace: data-platform-app-gold-scorecard-form-prod

Test AP app migration automation - gold-scorecard-form-prod

---

namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-gold-scorecard-form-prod/resources/ecr.tf

correct github_repositories name

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-events-dev/resources/hmpps-prisoner-nomis-update.tf

SDIT-383 Create a 'create-appointment' handler

---

namespaces/live.cloud-platform.service.justice.gov.uk/cfe-civil-staging/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/cfe-civil-staging/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/cfe-civil-staging/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/cfe-civil-staging/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/cfe-civil-staging/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/cfe-civil-staging/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/cfe-civil-staging/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/cfe-civil-staging/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/cfe-civil-staging/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/cfe-civil-staging/resources/versions.tf

Create staging environment (with RDS) for CFE Civil

LEP-39 Create CFE Civil Staging

---

namespaces/live.cloud-platform.service.justice.gov.uk/contact-moj-development/resources/elasticache.tf

Rotating auth token didn't work. Hoping this will enable it to work.

Add data output for contact-moj-development elasticache

---

namespaces/live.cloud-platform.service.justice.gov.uk/contact-moj-development/resources/elasticache.tf

Auth is not working after an upgrade so rotating to see if that fixes it.

Rotate auth token for contact-moj-development redis

---

namespaces/live.cloud-platform.service.justice.gov.uk/cfe-civil-uat/resources/pingdom.tf
namespaces/live.cloud-platform.service.justice.gov.uk/cfe-civil-uat/resources/versions.tf

LEP-44 Add Pingdom check to CFE Civil UAT

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-incentives-prod/resources/hmpps-events.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-incentives-prod/resources/sqs.tf

Same as https://github.com/ministryofjustice/cloud-platform-environments/pull/11141

INC-1119: configure HMPPS Domain Events queue in hmpps-incentives-prod namespace

---

namespaces/live.cloud-platform.service.justice.gov.uk/check-financial-eligibility-partner-uat/00-namespace.yaml

Ticket: [LEP-7](https://dsdmoj.atlassian.net/jira/software/c/projects/LEP/boards/1143?modal=detail&selectedIssue=LEP-7)
Updated ownership details
[LEP-7]: https://dsdmoj.atlassian.net/browse/LEP-7?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LEP-7 Update ownership details

---

namespaces/live.cloud-platform.service.justice.gov.uk/check-financial-eligibility-partner-staging/00-namespace.yaml

Ticket: [LEP-7](https://dsdmoj.atlassian.net/jira/software/c/projects/LEP/boards/1143?modal=detail&selectedIssue=LEP-7)
Updated ownership details
[LEP-7]: https://dsdmoj.atlassian.net/browse/LEP-7?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LEP-7 changed ownership details

---

namespaces/live.cloud-platform.service.justice.gov.uk/manage-soc-cases-dev/golden_signals_grafana_dashboard-api.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/manage-soc-cases-dev/golden_signals_grafana_dashboard-ui.yaml

Golden Signals - Grafana Dashboard

[DSE-1042] Manage SOC Cases DEV- UI/API

---

namespaces/live.cloud-platform.service.justice.gov.uk/manage-soc-cases-preprod/golden_signals_grafana_dashboard-api.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/manage-soc-cases-preprod/golden_signals_grafana_dashboard-ui.yaml

Golden Signals - Grafana Dashboard

[DSE-1042] Manage SOC Cases PREPROD- UI/API

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-apply-integration-adapter-prototype/resources/api_gateway.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-apply-integration-adapter-prototype/resources/cognito.tf

Added account_recovery_setting for cognate user pool and tagged the resources

Lasb 1819 terraform spike for apigw cognito

---

namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-hmpps-hr-dashboard-dev/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-hmpps-hr-dashboard-dev/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-hmpps-hr-dashboard-dev/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-hmpps-hr-dashboard-dev/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-hmpps-hr-dashboard-dev/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-hmpps-hr-dashboard-dev/resources/ecr.tf
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-hmpps-hr-dashboard-dev/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-hmpps-hr-dashboard-dev/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-hmpps-hr-dashboard-dev/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-hmpps-hr-dashboard-dev/resources/versions.tf

Testing AP app migration automation for hmpps-hr-dashboard-dev
Namespace: data-platform-app-hmpps-hr-dashboard-dev

AP app migration TEST - first batch: hmpps-hr-dashboard-dev

---

namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-ltc-capabilites-app-prod/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-ltc-capabilites-app-prod/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-ltc-capabilites-app-prod/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-ltc-capabilites-app-prod/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-ltc-capabilites-app-prod/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-ltc-capabilites-app-prod/resources/ecr.tf
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-ltc-capabilites-app-prod/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-ltc-capabilites-app-prod/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-ltc-capabilites-app-prod/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-ltc-capabilites-app-prod/resources/versions.tf

Testing AP app migration automation for ltc-capabilites-app-prod
Namespace: data-platform-app-ltc-capabilites-app-prod

AP app migration TEST - first batch: ltc-capabilites-app-prod

---

namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-ltc-capabilites-app-dev/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-ltc-capabilites-app-dev/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-ltc-capabilites-app-dev/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-ltc-capabilites-app-dev/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-ltc-capabilites-app-dev/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-ltc-capabilites-app-dev/resources/ecr.tf
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-ltc-capabilites-app-dev/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-ltc-capabilites-app-dev/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-ltc-capabilites-app-dev/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-ltc-capabilites-app-dev/resources/versions.tf

Testing AP app migration automation for ltc-capabilites-app-dev
Namespace: data-platform-app-ltc-capabilites-app-dev

AP app migration TEST - first batch: ltc-capabilites-app-dev

---

namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-mlp-app-prod/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-mlp-app-prod/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-mlp-app-prod/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-mlp-app-prod/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-mlp-app-prod/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-mlp-app-prod/resources/ecr.tf
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-mlp-app-prod/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-mlp-app-prod/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-mlp-app-prod/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-mlp-app-prod/resources/versions.tf

Testing AP app migration automation for mlp-app-prod
Namespace: data-platform-app-mlp-app-prod

AP app migration TEST - first batch: mlp-app-prod

---

namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-moj-officehub-locator-webapp-dev/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-moj-officehub-locator-webapp-dev/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-moj-officehub-locator-webapp-dev/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-moj-officehub-locator-webapp-dev/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-moj-officehub-locator-webapp-dev/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-moj-officehub-locator-webapp-dev/resources/ecr.tf
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-moj-officehub-locator-webapp-dev/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-moj-officehub-locator-webapp-dev/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-moj-officehub-locator-webapp-dev/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-moj-officehub-locator-webapp-dev/resources/versions.tf

Testing AP app migration automation for moj-officehub-locator-webapp-dev
Namespace: data-platform-app-moj-officehub-locator-webapp-dev

AP app migration TEST - first batch: moj-officehub-locator-webapp-dev

---

namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-moj-officehub-locator-webapp-prod/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-moj-officehub-locator-webapp-prod/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-moj-officehub-locator-webapp-prod/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-moj-officehub-locator-webapp-prod/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-moj-officehub-locator-webapp-prod/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-moj-officehub-locator-webapp-prod/resources/ecr.tf
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-moj-officehub-locator-webapp-prod/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-moj-officehub-locator-webapp-prod/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-moj-officehub-locator-webapp-prod/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-moj-officehub-locator-webapp-prod/resources/versions.tf

Testing AP app migration automation for moj-officehub-locator-webapp-prod
Namespace: data-platform-app-moj-officehub-locator-webapp-prod

AP app migration TEST - first batch: moj-officehub-locator-webapp-prod

---

namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-pfg-dash-moj-dev/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-pfg-dash-moj-dev/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-pfg-dash-moj-dev/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-pfg-dash-moj-dev/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-pfg-dash-moj-dev/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-pfg-dash-moj-dev/resources/ecr.tf
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-pfg-dash-moj-dev/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-pfg-dash-moj-dev/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-pfg-dash-moj-dev/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-pfg-dash-moj-dev/resources/versions.tf

Testing AP app migration automation for pfg-dash-moj-dev
Namespace: data-platform-app-pfg-dash-moj-dev

AP app migration TEST - first batch: pfg-dash-moj-dev

---

namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-pfg-dash-moj-prod/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-pfg-dash-moj-prod/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-pfg-dash-moj-prod/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-pfg-dash-moj-prod/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-pfg-dash-moj-prod/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-pfg-dash-moj-prod/resources/ecr.tf
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-pfg-dash-moj-prod/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-pfg-dash-moj-prod/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-pfg-dash-moj-prod/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-pfg-dash-moj-prod/resources/versions.tf

Testing AP app migration automation for pfg-dash-moj-prod
Namespace: data-platform-app-pfg-dash-moj-prod

AP app migration TEST - first batch: pfg-dash-moj-prod

---

namespaces/live.cloud-platform.service.justice.gov.uk/cfe-civil-uat/resources/pingdom.tf

Ticket [LEP-44](https://dsdmoj.atlassian.net/jira/software/c/projects/LEP/boards/1143?modal=detail&selectedIssue=LEP-44)
Added pingdom/slack integration id.
[LEP-44]: https://dsdmoj.atlassian.net/browse/LEP-44?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Lep 44 cfe civil pingdom

---

namespaces/live.cloud-platform.service.justice.gov.uk/manage-soc-cases-dev/golden_signals_grafana_dashboard-api.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/manage-soc-cases-dev/golden_signals_grafana_dashboard-ui.yaml

```
creationTimestamp:
resourceVersion:
selfLink:
uid:
```

[DSE-1042] Update golden_signals_grafana_dashboard-X.yaml

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-cla-backend-staging/04-networkpolicy.yaml

This is a test to see if our networkpolicy are working correctly.

Network policy testing - 1

---

namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-demo/resources/s3.tf

Add access to public bucket via ACL

Make bucket public, set ACL to public

---

namespaces/live.cloud-platform.service.justice.gov.uk/licences-prod/resources/rds.tf

will manually upgrade the DB size before merging this PR as I believe there are issues increasing the size
Need to do this out of hours so this is in preparation for that

Upgrade licences postgres version

---

namespaces/live.cloud-platform.service.justice.gov.uk/cfe-civil-staging/serviceaccount-circleci.yaml

We need a service account specifically for circle. This adds it for cfe-civil-staging

LEP-39 Add circle service account for CFE Civil Staging

---

namespaces/live.cloud-platform.service.justice.gov.uk/cfe-civil-staging/resources/pingdom.tf
namespaces/live.cloud-platform.service.justice.gov.uk/cfe-civil-staging/resources/versions.tf

Ticket: [LEP-72 ](https://dsdmoj.atlassian.net/jira/software/c/projects/LEP/boards/1143?modal=detail&selectedIssue=LEP-72)
Added pingdom support for CFE-CIVIL-Staging

LEP-72 added pingdom support

---

namespaces/live.cloud-platform.service.justice.gov.uk/cfe-civil-staging/resources/pingdom.tf

Ticket [PET-72](https://dsdmoj.atlassian.net/jira/software/c/projects/LEP/boards/1143?modal=detail&selectedIssue=LEP-72) 
Hostname corrected

PET-72 correction to hostname

---

namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-prod/resources/s3.tf

Add access to our s3 bucket for the WordPress site.

Add public bucket access s3 var - step 1 of 2

---

namespaces/live.cloud-platform.service.justice.gov.uk/track-a-query-qa/resources/elasticache.tf

Rotate elasticache auth token - track-a-query-qa

---

namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-judicial-wm2-dev/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-judicial-wm2-dev/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-judicial-wm2-dev/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-judicial-wm2-dev/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-judicial-wm2-dev/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-judicial-wm2-dev/resources/ecr.tf
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-judicial-wm2-dev/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-judicial-wm2-dev/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-judicial-wm2-dev/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-judicial-wm2-dev/resources/versions.tf

Testing AP app migration automation for judicial-wm2-dev
Namespace: data-platform-app-judicial-wm2-dev

AP app migration TEST - first batch: judicial-wm2-dev

---

namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-judicial-reviews-app-prod/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-judicial-reviews-app-prod/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-judicial-reviews-app-prod/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-judicial-reviews-app-prod/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-judicial-reviews-app-prod/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-judicial-reviews-app-prod/resources/ecr.tf
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-judicial-reviews-app-prod/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-judicial-reviews-app-prod/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-judicial-reviews-app-prod/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-judicial-reviews-app-prod/resources/versions.tf

Testing AP app migration automation for judicial-reviews-app-prod
Namespace: data-platform-app-judicial-reviews-app-prod

AP app migration TEST - first batch: judicial-reviews-app-prod

---

namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-judicial-reviews-app-dev/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-judicial-reviews-app-dev/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-judicial-reviews-app-dev/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-judicial-reviews-app-dev/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-judicial-reviews-app-dev/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-judicial-reviews-app-dev/resources/ecr.tf
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-judicial-reviews-app-dev/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-judicial-reviews-app-dev/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-judicial-reviews-app-dev/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-judicial-reviews-app-dev/resources/versions.tf

Testing AP app migration automation for judicial-reviews-app-dev
Namespace: data-platform-app-judicial-reviews-app-dev

AP app migration TEST - first batch: judicial-reviews-app-dev

---

namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-judicial-wm2-prod/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-judicial-wm2-prod/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-judicial-wm2-prod/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-judicial-wm2-prod/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-judicial-wm2-prod/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-judicial-wm2-prod/resources/ecr.tf
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-judicial-wm2-prod/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-judicial-wm2-prod/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-judicial-wm2-prod/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-judicial-wm2-prod/resources/versions.tf

Testing AP app migration automation for judicial-wm2-prod
Namespace: data-platform-app-judicial-wm2-prod

AP app migration TEST - first batch: judicial-wm2-prod

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-users-prod/resources/elasticache.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-users-prod/resources/variables.tf

HAAR-1248: Update hmpps-manage-users-prod to redis 7 - Step 1

---

namespaces/live.cloud-platform.service.justice.gov.uk/offender-management-staging/resources/elasticache.tf

In response to CircleCI breach

offender-management-staging: Rotate elasticacahe secrets

---

namespaces/live.cloud-platform.service.justice.gov.uk/check-financial-eligibility-partner-production/00-namespace.yaml

Ticket: [LEP-7](https://dsdmoj.atlassian.net/jira/software/c/projects/LEP/boards/1143?modal=detail&selectedIssue=LEP-7)
Email address corrected
[LEP-7]: https://dsdmoj.atlassian.net/browse/LEP-7?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LEP-7 Updated email address of owner

---

namespaces/live.cloud-platform.service.justice.gov.uk/jakemulley-development/resources/rds.tf

Reverts ministryofjustice/cloud-platform-environments#12063.
Trying to replicate a downgrade issue from small to micro.

Revert "jakemulley-development: bump RDS instance class for Postgres, MySQL, MariaDB"

---

namespaces/live.cloud-platform.service.justice.gov.uk/offender-events-dev/11-prometheus-sqs-sns.yaml

To fix: PrometheusOperatorReconcileErrors. https://mojdt.slack.com/archives/C8QR5FQRX/p1681298186489989

Fix prometheus rule - unterminated quoted string

---

cmd/compare-namespace/compare-namespace.go

- feat(go): handle listfiles error
- fix(cmd): Add error handling for when the directory is being deleted to stop check failing

fix(cmd): Add error handling for when the directory is being deleted to stop check failing

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-interventions-preprod/resources/rds-postgres14.tf

Increased database allocated storage to 20

Increased database allocated storage

---

.checksum
namespaces/live.cloud-platform.service.justice.gov.uk/laa-fee-calculator-ui-dev/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-fee-calculator-ui-dev/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-fee-calculator-ui-dev/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-fee-calculator-ui-dev/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-fee-calculator-ui-dev/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-fee-calculator-ui-dev/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-fee-calculator-ui-dev/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-fee-calculator-ui-dev/resources/versions.tf

A new dev environment for the user interface for Fee Calculator.

Dev environment for Fee Calculator UI

---

namespaces/live.cloud-platform.service.justice.gov.uk/jakemulley-development/resources/rds.tf

This is to test a instance type drop from originally a `db.t4g.medium` to a `db.t4g.micro`.

jakemulley-development: add Postgres database

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-production/resources/api_gateway.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-production/resources/ecr.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-production/resources/iam.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-production/resources/locals.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-production/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-production/resources/s3.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-production/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-production/resources/versions.tf

API gateway is required for client authentication

Add missing resources to production environment

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-assessments-dev/resources/elasticache.tf

- Upgrade elasticache
- Cycle auth token

Upgrade Elasticache in hmpps-assessments-dev

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-audit-dev/resources/rds.tf

HAAR-1359: Upgrade Postgres DB from V 14 to V 15 for 'hmpps-audit-dev' service

HAAR-1359: Upgrade Postgres DB from V 14 to V 15

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-assessments-preprod/resources/elasticache.tf

- Upgrade elasticache
- Cycle auth token

Upgrade elasticache in hmpps-assessments-preprod

---

namespaces/live.cloud-platform.service.justice.gov.uk/offender-management-staging/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/offender-management-staging/resources/variables.tf

offender-management-staging: Update MPC staging email

---

namespaces/live.cloud-platform.service.justice.gov.uk/offender-management-preprod/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/offender-management-preprod/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/offender-management-preprod/resources/variables.tf

offender-management-preprod: Update email/slack

---

namespaces/live.cloud-platform.service.justice.gov.uk/offender-management-test/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/offender-management-test/resources/variables.tf

offender-management-test: Update email/slack

---

namespaces/live.cloud-platform.service.justice.gov.uk/offender-management-test2/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/offender-management-test2/resources/variables.tf

offender-management-test2: Update email/slack

---

namespaces/live.cloud-platform.service.justice.gov.uk/offender-management-production/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/offender-management-production/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/offender-management-production/resources/variables.tf

offender-management-production: Update email/slack

---

namespaces/live.cloud-platform.service.justice.gov.uk/offender-management-preprod/resources/elasticache.tf
namespaces/live.cloud-platform.service.justice.gov.uk/offender-management-preprod/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/offender-management-preprod/resources/variables.tf

I hope I can do both together
MO-1259
MO-1260

mpc-preprod: Shrink RDS instance type and upgrade Redis

---

namespaces/live.cloud-platform.service.justice.gov.uk/offender-management-staging/resources/elasticache.tf
namespaces/live.cloud-platform.service.justice.gov.uk/offender-management-staging/resources/rds.tf

offender-management-staging: Tweak Redis/RDS instance types and versions

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-pre-production/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-pre-production/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-pre-production/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-pre-production/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-pre-production/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-pre-production/resources/api_gateway.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-pre-production/resources/ecr.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-pre-production/resources/iam.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-pre-production/resources/locals.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-pre-production/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-pre-production/resources/s3.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-pre-production/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-pre-production/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-pre-production/resources/versions.tf

We've used our production namespace as a template to create this and renamed all references of production to pre-production.

Create pre-production environment for hmpps-integration-api

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-audit-preprod/resources/rds.tf

Upgrade Postgres DB from V 14 to V 15(hmpps-audit-preprod)

HAAR-1359: Upgrade Postgres DB from V 14 to V 15(hmpps-audit-preprod)

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-mercury-submit-dev/07-serviceaccount-circleci.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-mercury-submit-dev/resources/variables.tf

Circleci service account had been missed from the config

added circleci service account

---

namespaces/live.cloud-platform.service.justice.gov.uk/offender-management-production/resources/elasticache.tf
namespaces/live.cloud-platform.service.justice.gov.uk/offender-management-production/resources/route53.tf
namespaces/live.cloud-platform.service.justice.gov.uk/offender-management-production/resources/variables.tf

offender-management-production: Redis changes

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-education-employment-dev/resources/rds.tf

Change instance type
Configure maximum allocated storage
Enable auto stop

ESWE-572 - Update RDS config - DEV

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-education-employment-preprod/resources/rds.tf

Change instance type
Configure maximum allocated storage
Enable auto stop

ESWE-572 - Update RDS config - PREPROD

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-education-employment-prod/resources/rds.tf

Change instance type
Configure maximum allocated storage
Add delete protection

ESWE-572 - Update RDS config - PROD

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-development/resources/api_gateway.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-development/resources/locals.tf

These resources were refactored to use for_each instead of count. Also allows creating multiple clients.

Update development to match pre-production and production

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-pre-production/resources/locals.tf

This will be used for testing purposes

Assign API Gateway API key to each enigneer

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-criminal-applications-datastore-production/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-criminal-applications-datastore-production/resources/sns-application-events.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-criminal-applications-datastore-production/resources/sqs-application-events-dlq.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-criminal-applications-datastore-production/resources/versions.tf

CRIMRE-282 Add namespace resources

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-sentence-plan-dev/05-certificates.yml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-sentence-plan-dev/resources/elasticache.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-sentence-plan-dev/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-sentence-plan-dev/resources/rds-postgresql.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-sentence-plan-dev/resources/variables.tf

Also updates the team name and sets the GitHubTeam tag for AWS Console access.

PI-987 Create ElastiCache and cert for hmpps-sentence-plan-ui

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-education-employment-preprod/resources/rds-ciag.tf

New rds instance for ciag-careers-induction-api

ESWE-560 - New RDS instance for ciag-careers-induction-api - PREPROD

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-education-employment-prod/resources/rds-ciag.tf

New rds instance for ciag-careers-induction-api

ESWE-560 - New RDS instance for ciag-careers-induction-api - PROD

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-review-criminal-legal-aid-production/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-review-criminal-legal-aid-production/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-review-criminal-legal-aid-production/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-review-criminal-legal-aid-production/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-review-criminal-legal-aid-production/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-review-criminal-legal-aid-production/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-review-criminal-legal-aid-production/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-review-criminal-legal-aid-production/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-review-criminal-legal-aid-production/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-review-criminal-legal-aid-production/resources/versions.tf

Also adding the RDS resource at the same time, not sure if it is best to do it separately?

CRIMRE-280 Create crime review production namespace

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-criminal-legal-aid-production/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-criminal-legal-aid-production/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-criminal-legal-aid-production/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-criminal-legal-aid-production/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-criminal-legal-aid-production/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-criminal-legal-aid-production/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-criminal-legal-aid-production/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-criminal-legal-aid-production/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-criminal-legal-aid-production/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-criminal-legal-aid-production/resources/versions.tf

Also adding the RDS resource at the same time.

CRIMAP-325 Create crime apply production namespace

---

namespaces/live.cloud-platform.service.justice.gov.uk/prisoner-content-hub-development/resources/s3-old.tf
namespaces/live.cloud-platform.service.justice.gov.uk/prisoner-content-hub-development/resources/s3.tf

The prod s3 bucket for content hub is in the wrong AWS region.
We need to create a new bucket in London, sync all the contents over, then repoint the application.
This PR creates a second bucket in dev, so that we can test the process.

✨ Add test s3 bucket switch for content hub in dev

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-review-criminal-legal-aid-staging/resources/rds.tf

Following earlier upgrade to v14

Upgrade rds to postgres 15

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-review-criminal-legal-aid-staging/resources/rds.tf

Following successful rds major version upgrade

Set prepare attribute to false and remove skip file

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-registers-prod/resources/rds.tf

Upgrade Postgres DB from V 14 to V 15(prisons-registers prod)

HAAR-1382: Upgrade Postgres DB from V 14 to V 15(prisons-registers prod)

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-audit-prod/resources/rds.tf

*****DO NOT MERGE ** **
Production changes to audit api service.

HAAR-1366: Upgrade Postgres DB from V 14 to V 15(hmpps-audit-prod)

---

namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-prod/resources/imb-route53.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-prod/resources/publicdefenderservice-route53.tf

Route53 dns records added to:
- publicdefenderservice.org.uk
- imb.org.uk

Hale platform dns migration

---

namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-prod/resources/ccrc-route53.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-prod/resources/magistrates-route53.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-prod/resources/victimscommissioner-route53.tf

Add domain records for
ccrc.gov.uk
magistrates.judiciary.uk
victimscommissioner.org.uk

Hale platform cp migration domain records

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-assure-hmrc-data-production/certificate.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-assure-hmrc-data-production/resources/route53.tf

Add check_clients_details_using_hmrc_data domain name

Add new domain name to laa-assure-hmrc-data-production

---

namespaces/live.cloud-platform.service.justice.gov.uk/prison-visits-booking-production/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/prison-visits-booking-production/resources/rds-prison-visits.tf

https://dsdmoj.atlassian.net/browse/VB-2196

VB-2196: enable RDS performance insights for prison-visits-booking-production

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-assure-hmrc-data-production/resources/pingdom.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-assure-hmrc-data-production/resources/versions.tf

[laa-assure-hmrc-data-production] Add pingdom checks

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-assure-hmrc-data-staging/resources/pingdom.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-assure-hmrc-data-staging/resources/versions.tf

Add pingdom checks to laa-assure-hmrc-data-staging namespace

laa-assure-hmrc-data-staging - Add pingdom checks

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-nomis-mapping-service-prod/resources/rds.tf

- SDIT-759: 🔧 Upgrade to postgres 15 for hmpps-nomis-mapping-service-prod
- SDIT-759: 🔧 Turn off preparing to upgrade after upgrade to postgres 15 for hmpps-nomis-mapping-service-prod

 SDIT-759: 🔧 Turn off preparing to upgrade after upgrade to postgres 15 for hmpps-nomis-mapping-service-prod

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-prisoner-from-nomis-migration-prod/resources/rds.tf

- SDIT-759: 🔧 Upgrade to postgres 15 for hmpps-prisoner-from-nomis-migration-prod
- SDIT-759: 🔧 Turn off preparing to upgrade after upgrade to postgres 15 for hmpps-prisoner-from-nomis-migration-prod

 SDIT-759: 🔧 Turn off preparing to upgrade after upgrade to postgres 15 for hmpps-prisoner-from-nomis-migration-prod

---

namespaces/live.cloud-platform.service.justice.gov.uk/prisoner-offender-search-prod/resources/rds.tf

- SDIT-759: 🔧 Upgrade to postgres 15 for prisoner-offender-search-prod
- SDIT-759: 🔧 Turn off preparing to upgrade after upgrade to postgres 15 for prisoner-offender-search-prod

SDIT-759: 🔧 Turn off preparing to upgrade after upgrade to postgres 15 for prisoner-offender-search-prod

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-hmrc-interface-production/resources/pingdom.tf

Slack channel change #applyprivatebeta to #laa-civil-apply

Slack channel change #applyprivatebeta to #laa-civil-apply

---

namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-people-data-self-serve-prod/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-people-data-self-serve-prod/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-people-data-self-serve-prod/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-people-data-self-serve-prod/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-people-data-self-serve-prod/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-people-data-self-serve-prod/resources/ecr.tf
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-people-data-self-serve-prod/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-people-data-self-serve-prod/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-people-data-self-serve-prod/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-people-data-self-serve-prod/resources/versions.tf

Testing AP app migration automation for people-data-self-serve-prod
Namespace: data-platform-app-people-data-self-serve-prod

AP app migration TEST - first batch: people-data-self-serve-prod

---

namespaces/live.cloud-platform.service.justice.gov.uk/check-my-diary-prod/resources/rds.tf

- SDIT-759: 🔧 Upgrade to postgres 15 for check-my-diary-prod
- SDIT-759: 🔧 Turn off preparing to upgrade after upgrade to postgres 15 for check-my-diary-prod

 SDIT-759: 🔧 Turn off preparing to upgrade after upgrade to postgres 15 for check-my-diary-prod

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-restricted-patients-api-prod/resources/rds.tf

- SDIT-759: 🔧 Upgrade to postgres 15 for hmpps-restricted-patients-api-prod
- SDIT-759: 🔧 Turn off preparing to upgrade after upgrade to postgres 15 for hmpps-restricted-patients-api-prod

 SDIT-759: 🔧 Turn off preparing to upgrade after upgrade to postgres 15 for hmpps-restricted-patients-api-prod

---

namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-people-data-self-serve-dev/01-rbac.yaml

Needed so AP team can check deployment status of this app

add AP team to people-data-self-serve dev rbac

---

namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-people-data-self-serve-prod/01-rbac.yaml

Needed so AP team can check deployment status of this app

add AP team to people-data-self-serve prod rbac

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-mercury-submit-dev/resources/update-queue.tf

Reverts ministryofjustice/cloud-platform-environments#12747

Revert "update to secret names"

---

namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-regime-dashboard-dev/resources/ecr.tf

Bumping the ECR module version to try out OIDC integration

Bump ECR version and pass oidc provider var.

---

.checksum
namespaces/live.cloud-platform.service.justice.gov.uk/ct-tact-list-dev/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/ct-tact-list-dev/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/ct-tact-list-dev/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/ct-tact-list-dev/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/ct-tact-list-dev/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/ct-tact-list-dev/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/ct-tact-list-dev/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/ct-tact-list-dev/resources/versions.tf

Proof-of-concept to display data tables from the Analytical Platform in the CP, ticket https://dsdmoj.atlassian.net/browse/JCH-421

New namespace for CT TACT List.

---

namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-judicial-reviews-app-dev/resources/ecr.tf

Bump ECR module version and add OIDC

Bump ECR module and add OIDC provider

---

namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-judicial-wm2-dev/resources/ecr.tf

Update ECR module version and add OIDC

Update ECR module version and add OIDC

---

namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-judicial-reviews-app-prod/resources/ecr.tf

Bump ECR module version and add OIDC

Bump ECR module version and add OIDC

---

namespaces/live.cloud-platform.service.justice.gov.uk/ct-tact-list-dev/resources/ecr.tf
namespaces/live.cloud-platform.service.justice.gov.uk/ct-tact-list-dev/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/ct-tact-list-dev/resources/rds-mysql.tf
namespaces/live.cloud-platform.service.justice.gov.uk/ct-tact-list-dev/resources/s3.tf
namespaces/live.cloud-platform.service.justice.gov.uk/ct-tact-list-dev/resources/serviceaccount.tf

Ticket: https://dsdmoj.atlassian.net/browse/JCH-421

Add AWS resources to TACT List

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-interventions-prod/resources/rds-postgres14.tf

Increased database allocated storage for prod

Increased database allocated storage for prod

---

namespaces/live.cloud-platform.service.justice.gov.uk/calculate-journey-variable-payments-dev/resources/rds.tf

Enable RDS overnight shutdown and upgrade to t4g

P4-4142 P4-4160 JPC Dev - t4g and overnight shutdown

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-dev/resources/rds.tf

Enable RDS overnight shutdown and upgrade to t4g instance type for BaSM dev environment

P4-4142 P4-4160 BaSM Dev - t4g and overnight shutdown

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-preprod/resources/rds.tf

Enable RDS overnight shutdown and upgrade to t4g

P4-4142 P4-4160 BaSM Preprod - t4g and overnight shutdown

---

.checksum
namespaces/live.cloud-platform.service.justice.gov.uk/bold-case-information-dashboard-dev/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/bold-case-information-dashboard-dev/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/bold-case-information-dashboard-dev/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/bold-case-information-dashboard-dev/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/bold-case-information-dashboard-dev/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/bold-case-information-dashboard-dev/resources/ecr.tf
namespaces/live.cloud-platform.service.justice.gov.uk/bold-case-information-dashboard-dev/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/bold-case-information-dashboard-dev/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/bold-case-information-dashboard-dev/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/bold-case-information-dashboard-dev/resources/versions.tf

Adding a new dev environment for the BOLD Case Information Dashboard.

Add new BOLD CID dev environment

---

namespaces/live.cloud-platform.service.justice.gov.uk/calculate-release-dates-api-dev/resources/analytical-platform-access.tf

Update bucket locations to new migrated locations

Update bucket locations for data puts

---

namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-test-dev/resources/service_token_cache.tf

- version upgrade to to 6.2.6
- use newer t3 node type

Upgrade formbuilder-platform-test-dev redis

---

namespaces/live.cloud-platform.service.justice.gov.uk/check-financial-eligibility-staging/resources/rds.tf

change instance class to db.t3.large

change instance class to db.t3.large on CFE staging

---

namespaces/live.cloud-platform.service.justice.gov.uk/check-financial-eligibility-staging/resources/rds.tf

upgrade postgres from v11 to v14

upgrade postgres from v11 to v14 for CFE staging

---

namespaces/live.cloud-platform.service.justice.gov.uk/check-financial-eligibility-staging/resources/rds.tf

Unable to upgrade directly from v11.16 to v14.6 so specify v14.4

specify v14.4 as cannot upgrade to newer version on CFE Staging

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-cla-backend-uat/resources/rds.tf

Investigating bumping our Postgresql version from 11 to 14 on our uat environment for [LGA-2408](https://dsdmoj.atlassian.net/browse/LGA-2408)
[LGA-2408]: https://dsdmoj.atlassian.net/browse/LGA-2408?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LGA-2408 Added in postgres 11 replica and postgres 14 modules

---

namespaces/live.cloud-platform.service.justice.gov.uk/check-financial-eligibility-staging/resources/rds.tf

change class to db.t4g.small for CFE staging

---

namespaces/live.cloud-platform.service.justice.gov.uk/prisoner-content-hub-production/resources/s3.tf

This was originally part of https://github.com/ministryofjustice/cloud-platform-environments/pull/12926 but failed the .github/workflows/reject-multi-namespace-prs.yml / reject-multi-namespace-prs check, so has been cherry picked to it's own branch and PR.

🔒  Add permissions to user policy for new content hub prod s3 bucket to facilitate staging -> new prod sync.

---

namespaces/live.cloud-platform.service.justice.gov.uk/check-financial-eligibility-staging/resources/rds.tf

set prepare_for_major_upgrade to `false`

set prepare_for_major_upgrade to false in CFE staging

---

namespaces/live.cloud-platform.service.justice.gov.uk/check-financial-eligibility-production/resources/rds.tf

set instance class to db.t3.large and max allocated storage to 500

set instance class to db.t3.large and max allocated storage to 500 on CFE production

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-offences-api-preprod/resources/cross-iam-role-sa.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-offences-api-preprod/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-offences-api-preprod/resources/versions.tf

the config is based on the dev environment - where it has been fully tested

MOP-62 Add cross-iam-role terraform module to enable integration with s3 buckets in analytical platform (ho_codes data)

---

namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-autotest-dev/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-autotest-dev/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-autotest-dev/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-autotest-dev/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-autotest-dev/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-autotest-dev/05-serviceaccount-circleci.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-autotest-dev/06-certificate.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-autotest-dev/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-autotest-dev/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-autotest-dev/resources/versions.tf

add namespace for automated testing facility
dev environment

Visit Someone in Prison Service

---

namespaces/live.cloud-platform.service.justice.gov.uk/check-financial-eligibility-production/resources/rds.tf

upgrade from postgres v11 to v14

upgrade from postgres v11 to v14 for CFE production

---

namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-autotest-staging/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-autotest-staging/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-autotest-staging/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-autotest-staging/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-autotest-staging/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-autotest-staging/05-serviceaccount-circleci.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-autotest-staging/06-certificate.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-autotest-staging/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-autotest-staging/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-autotest-staging/resources/versions.tf

new namespace for automated test facility
stage environment

Visit Someone in Prison

---

namespaces/live.cloud-platform.service.justice.gov.uk/manage-soc-cases-dev/resources/rds.tf

Update SOC dev RDS DB to postgres 12.14 and db.t4g.micro

Update SOC dev RDS DB to postgres 12.14 and db.t4g.micro

---

namespaces/live.cloud-platform.service.justice.gov.uk/manage-soc-cases-dev/resources/rds.tf

Update SOC dev to db.t3.micro

---

namespaces/live.cloud-platform.service.justice.gov.uk/check-financial-eligibility-production/resources/rds.tf

change instance class to db.t4g.small

change instance class to db.t4g.small on CFE production

---

namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-development/resources/cross-account-data-product-role.tf
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-development/resources/variables.tf

https://github.com/ministryofjustice/data-platform/issues/429
Adding permissions to assume roles in other AP/DP accounts.

Adding additional permissions to the cross-account role

---

namespaces/live.cloud-platform.service.justice.gov.uk/prisoner-content-hub-development/resources/s3.tf

This is the dev namespace corresponding PR to https://github.com/ministryofjustice/cloud-platform-environments/pull/13146

Update user policy for new content hub dev s3 bucket to be synced from new prod bucket.

---

namespaces/live.cloud-platform.service.justice.gov.uk/check-financial-eligibility-production/resources/rds.tf

set prepare_for_major_upgrade to false

set prepare_for_major_upgrade to false on CFE production

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmcts-complaints-formbuilder-adapter-staging/resources/rds.tf

Upgrade to the instance type to follow

Upgrade formbuilder HMCTS adapter staging postgres to version 14

---

namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-publisher-test/resources/publisher.tf

Upgrade to instance type to follow

Upgrade fb-publisher-test redis version to 7

---

namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-publisher-test/resources/publisher.tf

Use t4g.micro instead of default instance type

Upgrade redis node type fb-publisher-test

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-preprod/resources/api_gateway.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-preprod/resources/iam.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-preprod/resources/kubernetes_secrets.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-preprod/resources/s3_truststore.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-preprod/resources/versions.tf

In #13155 we created our preprod environment. Following the creation of our truststore certificates, we have added API Gateway. This completes our preprod environment.

Add API Gateway to Preprod

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-workload-preprod/resources/dms-impact-testing.tf

Update DMS module version to latest version - 2.4.2

Update DMS module version to 2.4.2

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-education-employment-dev/06-certificate.yaml

Add certificates for CIAG services - DEV

ESWE-601 - CIAG Certificates - Dev

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-education-employment-preprod/06-certificate.yaml

Add certificates for CIAG services - PREPROD

ESWE-601 - CIAG Certificates - PreProd

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-education-employment-prod/06-certificate.yaml

Add certificates for CIAG services - PROD

ESWE-601 - CIAG Certificates - Prod

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-prod/resources/api_gateway.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-prod/resources/iam.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-prod/resources/kubernetes_secrets.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-prod/resources/s3_truststore.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-integration-api-prod/resources/versions.tf

This is the final infrastructure step for recreating/renaming our "production" environment to "prod", related to #13206.
We'll be deleting our "production" namespace once we're sure "prod" is working.

Add API Gateway to prod namespace for HMPPS Integration API

---

namespaces/live.cloud-platform.service.justice.gov.uk/jacksapp-dev/resources/elasticsearch.tf

- feat(TF): Add cold storage to elastic search instance
- fix(TF): enable warm storage

fix(TF): enable warm storage

---

namespaces/live.cloud-platform.service.justice.gov.uk/jacksapp-dev/resources/elasticsearch.tf

- fix(TF): Module master node added
- fix(TF): add correct instance type
- fix(TF): Change instance type

elasticsearch api testing

---

namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-staging/resources/rds.tf

Upgrade db_instance_class to db.t4g.micro and set db_max_allocated_storage to 500 based on https://github.com/ministryofjustice/cloud-platform-environments/pull/13234.

Upgrade db_instance_class to db.t4g.micro

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmcts-complaints-formbuilder-adapter-production/resources/rds.tf

Please do not merge, we will advertise a small downtime to our users then merge at agreed time

Upgrade postgres node to t4g

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-api-dev/01-rbac.yaml

https://dsdmoj.atlassian.net/browse/NN-5136

NN-5136: add hmpps-adjudications team to hmpps-manage-adjudications-api-dev

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-dev/01-rbac.yaml

https://dsdmoj.atlassian.net/browse/NN-5136

NN-5136: add hmpps-adjudications team to hmpps-manage-adjudications-dev

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-auth-dev/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/token-verification-api-dev/00-namespace.yaml

enable cross-namespace traffic routing between client services and auth

HAAR-1392: enabling hmpps-audit, token-verification-api in AUTH 

---

namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-dev/resources/rds.tf

Upgrade db_instance_class to db.t4g.micro and set db_max_allocated_storage to 500.

Upgrade db_instance_class to db.t4g.micro - visit-someone-in-prison-backend-svc-dev

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-frontend-uat/resources/redis.tf

Added auth_token_rotated_date, no change to other lines bar aligning =

P4-4179 BaSM Front End UAT Rotate creds, remove skip file

---

namespaces/live.cloud-platform.service.justice.gov.uk/activities-api-preprod/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/activities-api-preprod/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/activities-api-preprod/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/activities-api-preprod/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/activities-api-preprod/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/activities-api-preprod/05-serviceaccount-circleci.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/activities-api-preprod/06-certificate.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/activities-api-preprod/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/activities-api-preprod/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/activities-api-preprod/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/activities-api-preprod/resources/versions.tf

* Preprod namespace for API
* RDS instance & secrets
*  Certificate
* RBAC

SAA-609 Create preprod environment for Activities (API)

---

namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-dev/APPLY_PIPELINE_SKIP_THIS_NAMESPACE

remove APPLY_PIPELINE_SKIP_THIS_NAMESPACE post DB instance update

remove skip apply pipleline post DB instance update

---

namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-preprod/APPLY_PIPELINE_SKIP_THIS_NAMESPACE

Add pipeline skip namespace file before upgrading database instance -…

Add pipeline skip namespace file before upgrading database instance

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-audit-dev/resources/hmpps-audit-queue.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-audit-dev/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-audit-dev/resources/outputs-to-ssm-parameters.tf

https://dsdmoj.atlassian.net/browse/HEAT-68

HEAT-68: configure IRSA SSM params for hmpps-audit-dev

---

namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-preprod/resources/rds.tf

Upgrade db_instance_class to db.t4g.micro and set db_max_allocated_storage to 500.

Upgrade db_instance_class to db.t4g.micro - visit-someone-in-prison-backend-svc-preprod

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-incentives-dev/resources/irsa.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-incentives-dev/resources/sqs.tf

INC-1263: configure IRSA for incentives-dev

---

namespaces/live.cloud-platform.service.justice.gov.uk/contact-moj-development/resources/elasticache.tf
namespaces/live.cloud-platform.service.justice.gov.uk/contact-moj-development/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/contact-moj-development/resources/variables.tf

CDPT-662 Enable RDS auto stop start on contact-moj-development

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-audit-dev/resources/hmpps-incentives.tf

INC-1263: tidy up no longer used secret data for sqs-hmpps-audit-secret - incentives-dev

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-audit-preprod/resources/hmpps-audit-queue.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-audit-preprod/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-audit-preprod/resources/outputs-to-ssm-parameters.tf

https://dsdmoj.atlassian.net/browse/HEAT-68

HEAT-68: configure IRSA SSM params for hmpps-audit-preprod

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-incentives-preprod/resources/irsa.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-incentives-preprod/resources/sqs.tf

INC-1263: configure IRSA for incentives-preprod

---

namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-dev/resources/claim-criminal-injuries-tempus-queue.tf

The apply of #12852 failed, I suspect due to this trailing comma

CICA Tempus Queue Fix

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-applications-adaptor-prototype/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-applications-adaptor-prototype/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-applications-adaptor-prototype/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-applications-adaptor-prototype/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-applications-adaptor-prototype/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-applications-adaptor-prototype/resources/api_gateway.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-applications-adaptor-prototype/resources/cognito.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-applications-adaptor-prototype/resources/iam.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-applications-adaptor-prototype/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-applications-adaptor-prototype/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-applications-adaptor-prototype/resources/versions.tf

LASB-1918: Added the laa-crime-application-adaptor-prototype namespace

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-audit-prod/resources/hmpps-audit-queue.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-audit-prod/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-audit-prod/resources/outputs-to-ssm-parameters.tf

https://dsdmoj.atlassian.net/browse/HEAT-68

HEAT-68: configure IRSA SSM params for hmpps-audit-prod

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-incentives-preprod/resources/sqs.tf

INC-1263: tidy up no longer used secret data for prisoner-event-queue - preprod

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-audit-preprod/resources/hmpps-incentives.tf

INC-1263: tidy up no longer used secret data for sqs-hmpps-audit-secret - incentives-preprod

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-incentives-prod/resources/irsa.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-incentives-prod/resources/sqs.tf

INC-1263: configure IRSA for incentives-prod

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-incentives-prod/resources/sqs.tf

INC-1263: tidy up no longer used secret data for prisoner-event-queue - prod

---

namespaces/live.cloud-platform.service.justice.gov.uk/bold-rr-ops-pilot-prototype/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/bold-rr-ops-pilot-prototype/resources/variables.tf

The prototype is owned by the BOLD CID team, and we've got new contact details (a new Slack channel).

Update contact info for BOLD RR prototype

---

namespaces/live.cloud-platform.service.justice.gov.uk/bold-case-information-dashboard-dev/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/bold-case-information-dashboard-dev/resources/variables.tf

Just updating the contact info to use the new shared mailbox and slack channel for the BOLD Case Information Dashboard team.

Update contact info for BOLD CID team

---

.checksum
namespaces/live.cloud-platform.service.justice.gov.uk/digital-prison-reporting-mi-dev/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/digital-prison-reporting-mi-dev/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/digital-prison-reporting-mi-dev/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/digital-prison-reporting-mi-dev/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/digital-prison-reporting-mi-dev/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/digital-prison-reporting-mi-dev/resources/digital-prison-reporting-mi-ecr.tf
namespaces/live.cloud-platform.service.justice.gov.uk/digital-prison-reporting-mi-dev/resources/digital-prison-reporting-mi-ui-ecr.tf
namespaces/live.cloud-platform.service.justice.gov.uk/digital-prison-reporting-mi-dev/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/digital-prison-reporting-mi-dev/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/digital-prison-reporting-mi-dev/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/digital-prison-reporting-mi-dev/resources/versions.tf

- Added Digital Prison Reporting MI Dev environment
- Added ECR repos for api and UI
- Added service account for CircleCI integration

[DPR-440] Added Digital Prison Reporting MI Dev environment, ECR repos, and service account

---

namespaces/live.cloud-platform.service.justice.gov.uk/parliamentary-questions-development/resources/rds.tf

Also removes `allow_major_version_upgrade`

Enable rds auto stop/start on parliamentary-questions-development

---

namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-dev/resources/claim-criminal-injuries-tempus-queue.tf

terraform apply for Tempus Queue (#13327) is still failing, attempting another couple of changes to try and resolve the policy resource issue.

Fix Tempus Queue

---

namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-prod/resources/rds.tf

Upgrade db_instance_class to db.t4g.small and add db_max_allocated_storage with value 10000 for visit-someone-in-prison-backend-svc-prod .

Upgrade visit-someone-in-prison-backend-svc-prod database instance

---

namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-dev/resources/claim-criminal-injuries-tempus-queue.tf

Switch to SourceArn instead of PrincipalArn

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-frontend-production/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-frontend-production/resources/redis.tf

Update namespace owner
Add value to redis secret
Skip apply pipeline

P4-4181 BaSM Front End production

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-production/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-production/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-production/resources/redis.tf

Update namespace owner
Add value to redis secret
Skip apply pipeline

P4-4186 BaSM API production

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-electronic-monitoring-documentation-dev/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-electronic-monitoring-documentation-dev/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-electronic-monitoring-documentation-dev/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-electronic-monitoring-documentation-dev/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-electronic-monitoring-documentation-dev/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-electronic-monitoring-documentation-dev/05-serviceaccount-circleci.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-electronic-monitoring-documentation-dev/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-electronic-monitoring-documentation-dev/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-electronic-monitoring-documentation-dev/resources/versions.tf

Creating environment for documentation for Electronic monitoring service.

Adding environment for hmpps-electronic-monitoring-documentation-dev

---

namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-dev/resources/claim-criminal-injuries-tempus-queue.tf

Add tempus queue back in now SSM parameter resource is in

Claim criminal injuries tempus queue

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-incentives-prod/resources/sqs.tf

INC-1263: correct secret for prisoner-event-queue - prod

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-accredited-programmes-dev/resources/rds-postgresql.tf

Add a Postgres RDS instance to the `hmpps-accredited-programmes-dev` namespace.
* Turned off overnight
* No read replica
* db.t4g.micro instance class

DXW Accredited Programmes team. Card 417. 

---

namespaces/live.cloud-platform.service.justice.gov.uk/track-a-move-dev/resources/book-a-secure-move-api-iam.tf

BaSM dev namespace has been decommissioned

track-a-move dev put iam secret in basm staging secrets

---

namespaces/live.cloud-platform.service.justice.gov.uk/makeaplea-dev/resources/rds.tf

Upgrade the postgres version from 11 to 12.9

Postgres Version Upgrade for Make a Plea Dev

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-digital-prison-reporting-mi-dev/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-digital-prison-reporting-mi-dev/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-digital-prison-reporting-mi-dev/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-digital-prison-reporting-mi-dev/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-digital-prison-reporting-mi-dev/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-digital-prison-reporting-mi-dev/resources/elasticache.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-digital-prison-reporting-mi-dev/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-digital-prison-reporting-mi-dev/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-digital-prison-reporting-mi-dev/resources/ui-session-secret.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-digital-prison-reporting-mi-dev/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-digital-prison-reporting-mi-dev/resources/versions.tf

Deletion of digital-prison-reporting-mi to follow.

[DPR-383] Add hmpps- prefixed namespace

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-electronic-monitoring-dev/05-serviceaccount-circleci.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-electronic-monitoring-dev/06-certificate.yaml

add resources to enable typescript ui project

add resources to enable typescript ui project

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-electronic-monitoring-dev/06-certificate.yaml

removed hmpps from domain name following advice

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-api-dev/resources/irsa.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-api-dev/resources/variables.tf

NN-5154: configure IRSA for hmpps-manage-adjudications-api-dev

---

namespaces/live.cloud-platform.service.justice.gov.uk/keyworker-api-dev/resources/irsa.tf
namespaces/live.cloud-platform.service.justice.gov.uk/keyworker-api-dev/resources/variables.tf

NN-5154: configure IRSA for keyworker-api-dev

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-api-preprod/resources/irsa.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-api-preprod/resources/variables.tf

NN-5154: configure IRSA for hmpps-manage-adjudications-api-preprod

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-api-prod/resources/irsa.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-api-prod/resources/variables.tf

NN-5154: configure IRSA for hmpps-manage-adjudications-api-prod

---

namespaces/live.cloud-platform.service.justice.gov.uk/keyworker-api-preprod/resources/irsa.tf
namespaces/live.cloud-platform.service.justice.gov.uk/keyworker-api-preprod/resources/variables.tf

NN-5154: configure IRSA for keyworker-api-preprod

---

namespaces/live.cloud-platform.service.justice.gov.uk/keyworker-api-prod/resources/irsa.tf
namespaces/live.cloud-platform.service.justice.gov.uk/keyworker-api-prod/resources/variables.tf

NN-5154: configure IRSA for keyworker-api-prod

---

namespaces/live.cloud-platform.service.justice.gov.uk/ap-auth-proxy-prod/resources/ecr.tf

https://dsdmoj.atlassian.net/browse/ANPL-1618
Adding OIDC provider var to ECR declaration to enable OIDC.

Enabling OIDC auth for auth-proxy ECR.

---

namespaces/live.cloud-platform.service.justice.gov.uk/whereabouts-api-prod/resources/irsa.tf
namespaces/live.cloud-platform.service.justice.gov.uk/whereabouts-api-prod/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/whereabouts-api-prod/resources/variables.tf

NN-5154: configure IRSA for whereabouts-api-prod

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-api-prod/resources/sqs.tf

NN-5154: tidy up no longer used secret data for prisoner-event-queue - prod

---

namespaces/live.cloud-platform.service.justice.gov.uk/use-of-force-preprod/resources/analytical-platform-access.tf

Following dev migration of extractor target buckets, this will migrate preprod

PDE-2210 moved use of force AP buckets

---

namespaces/live.cloud-platform.service.justice.gov.uk/use-of-force-dev/resources/analytical-platform-access.tf
namespaces/live.cloud-platform.service.justice.gov.uk/use-of-force-preprod/resources/analytical-platform-access.tf

* the extractor data wasn't flowing to the new architecture in dev or preprod because the directory path to write to was incorrect. I am correcting this.

Correcting extractor target directory.

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-electronic-monitoring-dev/resources/elasticache.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-electronic-monitoring-dev/resources/variables.tf

unsure if I need to edit values

Added basic elasticache file from template typescript ui repo

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-education-and-work-plan-prototype/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-education-and-work-plan-prototype/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-education-and-work-plan-prototype/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-education-and-work-plan-prototype/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-education-and-work-plan-prototype/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-education-and-work-plan-prototype/resources/basic-auth.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-education-and-work-plan-prototype/resources/ecr.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-education-and-work-plan-prototype/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-education-and-work-plan-prototype/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-education-and-work-plan-prototype/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-education-and-work-plan-prototype/resources/versions.tf

Added Cloud Platform env for HMPPS Education And Work Plan prototype

Added hmpps-education-and-work-plan-prototype

---

namespaces/live.cloud-platform.service.justice.gov.uk/manage-soc-cases-dev/resources/rds.tf

Dev SOC revert prepare for major upgrade to false

Dev SOC revert prepare for major upgrade to false

---

namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-dev/resources/irsa.tf
namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-dev/resources/variables.tf

Adding Update SQS/SNS queue updates to use IRSA this is for VSiP Dev

VB-1929 Set up a queue in Cloud platform environments SQS for dev VSiP

---

namespaces/live.cloud-platform.service.justice.gov.uk/prison-to-probation-update-preprod/resources/dynamodb.tf
namespaces/live.cloud-platform.service.justice.gov.uk/prison-to-probation-update-preprod/resources/irsa.tf
namespaces/live.cloud-platform.service.justice.gov.uk/prison-to-probation-update-preprod/resources/variables.tf

- prison-to-probation-update-preprod: update to latest irsa module
- prison-to-probation-update-preprod: update to latest irsa module

prison-to-probation-update-preprod: update to latest irsa module

---

namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-autotest-staging/resources/irsa.tf
namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-autotest-staging/resources/variables.tf

Adding Update SQS/SNS queue updates to use IRSA this is for VSiP staging

VB-2329 Staging - VSiP service Migrate to using IRSA CPS

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-electronic-monitoring-preprod/00-namespace.yaml

Comparison project is hmpps-external-users-api-preprod

Amended namespace file to match comparison project naming

---

namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-preprod/resources/irsa.tf
namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-preprod/resources/variables.tf

Adding Update SQS/SNS queue updates to use IRSA this is for VSiP preprod

VB-2329 PreProd - VSiP service Migrate to using IRSA CPS

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-auth/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-auth/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-auth/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-auth/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-auth/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-auth/resources/cognito.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-auth/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-auth/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-auth/resources/versions.tf

This namespace will be used to configure AWS Cognito for all of our services.

New namespace for authenticating laa-crime services

---

namespaces/live.cloud-platform.service.justice.gov.uk/whereabouts-api-dev/resources/irsa.tf
namespaces/live.cloud-platform.service.justice.gov.uk/whereabouts-api-dev/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/whereabouts-api-dev/resources/route53.tf
namespaces/live.cloud-platform.service.justice.gov.uk/whereabouts-api-dev/resources/variables.tf

HEAT-74: whereabouts-api-dev: update to use latest irsa module

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-api-prod/resources/ap-data.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-api-prod/resources/s3.tf

https://dsdmoj.atlassian.net/browse/NN-5194

NN-5194: provide IAM account which can access AP S3 bucket

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-incentives-dev/resources/irsa.tf

HEAT-74: incentives-dev: update to use latest irsa module

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-api-dev/resources/irsa.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-api-dev/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-api-dev/resources/sqs.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-api-dev/resources/variables.tf

HEAT-74: adjudications-dev: update to use latest irsa module

---

namespaces/live.cloud-platform.service.justice.gov.uk/whereabouts-api-preprod/resources/irsa.tf
namespaces/live.cloud-platform.service.justice.gov.uk/whereabouts-api-preprod/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/whereabouts-api-preprod/resources/route53.tf
namespaces/live.cloud-platform.service.justice.gov.uk/whereabouts-api-preprod/resources/variables.tf

HEAT-74: whereabouts-api-preprod: update to use latest irsa module

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-api-preprod/resources/irsa.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-api-preprod/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-api-preprod/resources/sqs.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-api-preprod/resources/variables.tf

HEAT-74: adjudications-preprod: update to use latest irsa module

---

namespaces/live.cloud-platform.service.justice.gov.uk/whereabouts-api-prod/resources/irsa.tf
namespaces/live.cloud-platform.service.justice.gov.uk/whereabouts-api-prod/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/whereabouts-api-prod/resources/route53.tf
namespaces/live.cloud-platform.service.justice.gov.uk/whereabouts-api-prod/resources/variables.tf

HEAT-74: whereabouts-api-prod: update to use latest irsa module

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-api-prod/resources/irsa.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-api-prod/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-api-prod/resources/sqs.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-api-prod/resources/variables.tf

HEAT-74: adjudications-prod: update to use latest irsa module

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-api-prod/resources/ap-data.tf

https://dsdmoj.atlassian.net/browse/NN-5194
I renamed the variable with https://github.com/ministryofjustice/cloud-platform-environments/pull/13806 and forgot to update https://github.com/ministryofjustice/cloud-platform-environments/pull/13669 😬

NN-5194: fix pipeline

---

namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-preprod/resources/irsa.tf

VB-2329 PreProd - VSiP service Migrate to using IRSA CPS, Found out I had left the Dev arn details have changed to preprod

VB-2329 PreProd - VSiP service Migrate to using IRSA CPS,

---

namespaces/live.cloud-platform.service.justice.gov.uk/whereabouts-api-dev/resources/irsa.tf

HEAT-74-whereabouts-api-dev: Removing old instance of irsa module

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-incentives-dev/resources/irsa.tf

HEAT-74-incentives-dev: Removing old instance of irsa module

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-api-dev/resources/irsa.tf

HEAT-74-adjudications-dev: Removing old instance of irsa module

---

namespaces/live.cloud-platform.service.justice.gov.uk/whereabouts-api-preprod/resources/irsa.tf

HEAT-74-whereabouts-api-preprod: Removing old instance of irsa module

---

namespaces/live.cloud-platform.service.justice.gov.uk/whereabouts-api-prod/resources/irsa.tf

HEAT-74-whereabouts-api-prod: Removing old instance of irsa module

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-incentives-prod/resources/irsa.tf

HEAT-74-incentives-prod: Removing old instance of irsa module

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-api-prod/resources/irsa.tf

HEAT-74-adjudications-prod: Removing old instance of irsa module

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-incentives-preprod/resources/irsa.tf

HEAT-74-incentives-preprod: Removing old instance of irsa module

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-api-preprod/resources/irsa.tf

HEAT-74-adjudications-preprod: Removing old instance of irsa module

---

namespaces/live.cloud-platform.service.justice.gov.uk/pathfinder-preprod/resources/analytical-platform-access.tf

part of the migration of extractor data to new s3 architecture

change to destination bucket

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-non-associations-preprod/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-non-associations-preprod/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-non-associations-preprod/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-non-associations-preprod/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-non-associations-preprod/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-non-associations-preprod/05-serviceaccount-circleci.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-non-associations-preprod/06-certificate.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-non-associations-preprod/resources/elasticache.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-non-associations-preprod/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-non-associations-preprod/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-non-associations-preprod/resources/scheduled-downtime.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-non-associations-preprod/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-non-associations-preprod/resources/versions.tf

Mostly copied from `non-associations-dev` but tweaked a few things, like namespace references, DNS names, etc...

NON-10: `hmpps-non-associations-preprod` namespace/resources

---

namespaces/live.cloud-platform.service.justice.gov.uk/pathfinder-preprod/resources/analytical-platform-access.tf

correction to the bucket used in this #13836

correct bucket for this env migration

---

namespaces/live.cloud-platform.service.justice.gov.uk/ops-pilot-test/resources/cross-iam-role-sa.tf

Added Get perms for bucket, changed bucket name for use with data-engineeeing-exports and refactored names

added get perms and recfactor

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-assess-risks-and-needs-preprod/resources/analytical-platform-access.tf

part of the migration of extractor data to new s3 architecture

updating destination bucket to align with new architecture

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-non-associations-prod/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-non-associations-prod/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-non-associations-prod/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-non-associations-prod/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-non-associations-prod/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-non-associations-prod/05-serviceaccount-circleci.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-non-associations-prod/06-certificate.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-non-associations-prod/resources/elasticache.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-non-associations-prod/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-non-associations-prod/resources/pingdom.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-non-associations-prod/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-non-associations-prod/resources/scheduled-downtime.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-non-associations-prod/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-non-associations-prod/resources/versions.tf

Mostly copied from `preprod` with tweaks to stuff like namespace names, `is-production=true`, ElastiCache/Redis instance size, DNS names, pingdom, limit range, etc...
CC: @neilmendum

NON-10: `hmpps-non-associations-prod` namespace/resources

---

namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-prod/resources/irsa.tf
namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-prod/resources/variables.tf

Prod - VSiP service Migrate to using IRSA CPS
Please make sure the following is correct for production : 
```
data "aws_ssm_parameter" "irsa_policy_arns_sns" {
name = "/hmpps-domain-events-prod/sns/cloud-platform-Digital-Prison-Services-97e6567cf80881a8a52290ff2c269b08/irsa-policy-arn"
}
```

VB-2329 Prod - VSiP service Migrate to using IRSA CPS

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-interventions-preprod/resources/rds-postgres14.tf

Upgrading pre-prod db instance to test it out before upgrading prod db instance.

Update pre-prod db instance to db.m6g.xlarge

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-restricted-patients-api-preprod/resources/rds.tf

SDIT-887: 🔧 Remove IAM access keys for hmpps-restricted-patients-api-preprod

---

namespaces/live.cloud-platform.service.justice.gov.uk/makeaplea-dev/resources/rds.tf

Change postgres version of mgw from 12.9 to 12.11

Change postgres version in makeaplea-dev

---

namespaces/live.cloud-platform.service.justice.gov.uk/offender-events-dev/resources/prisoner-offender-events-sub-queue.tf

SDIT-887: 🐛 Fix reference to irsa_policy_arn

SDIT-887: 🐛 Fix reference to irsa_policy_arn

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-interventions-preprod/resources/rds-postgres14.tf

Reverting back the db instance class on pre-prod

Reverting back the db instance class on pre-prod

---

namespaces/live.cloud-platform.service.justice.gov.uk/mpc-prototype/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/mpc-prototype/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/mpc-prototype/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/mpc-prototype/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/mpc-prototype/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/mpc-prototype/resources/basic-auth.tf
namespaces/live.cloud-platform.service.justice.gov.uk/mpc-prototype/resources/ecr.tf
namespaces/live.cloud-platform.service.justice.gov.uk/mpc-prototype/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/mpc-prototype/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/mpc-prototype/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/mpc-prototype/resources/versions.tf

Would like to publish a new prototype please

Added new prototype for mpc

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-cvl-prototype/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-cvl-prototype/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-cvl-prototype/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-cvl-prototype/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-cvl-prototype/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-cvl-prototype/resources/basic-auth.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-cvl-prototype/resources/ecr.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-cvl-prototype/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-cvl-prototype/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-cvl-prototype/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-cvl-prototype/resources/versions.tf

Could I please add a new prototype for Create and vary a licence? Thank zou

Added hmpps-cvl-prototype

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-claim-non-standard-magistrate-fee-dev/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-claim-non-standard-magistrate-fee-dev/resources/ecr.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-claim-non-standard-magistrate-fee-dev/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-claim-non-standard-magistrate-fee-dev/resources/variables.tf

Update variables so that email/slack are up to date and reachable.

NSM - Clean up dev variables

---

namespaces/live.cloud-platform.service.justice.gov.uk/ops-pilot-test/resources/ecr.tf

Update the resources file to remove the long-lived credentials from ECR

Remove long-lived credentials

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-video-link-dev/resources/elasticache.tf

MAP-32 add skip file and secrets

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-claim-non-standard-magistrate-fee-uat/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-claim-non-standard-magistrate-fee-uat/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-claim-non-standard-magistrate-fee-uat/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-claim-non-standard-magistrate-fee-uat/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-claim-non-standard-magistrate-fee-uat/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-claim-non-standard-magistrate-fee-uat/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-claim-non-standard-magistrate-fee-uat/resources/rds-postgresql.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-claim-non-standard-magistrate-fee-uat/resources/s3.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-claim-non-standard-magistrate-fee-uat/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-claim-non-standard-magistrate-fee-uat/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-claim-non-standard-magistrate-fee-uat/resources/versions.tf

Creates a new environment for CRM7 team as UAT.

Add environment for CRM7 UAT

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-template-typescript/resources/elasticache.tf

https://dsdmoj.atlassian.net/browse/

Remove long-lived credentials from HMPPS TypeScript Template

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-video-link-preprod/resources/elasticache.tf

Map 32 bvl preprod update redis 1

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-video-link-preprod/resources/elasticache.tf

MAP-32 update node type

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-probation-integration-services-dev/resources/irsa.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-probation-integration-services-dev/resources/person-search-index-from-delius-contact-queue.tf

```
LimitExceeded: Cannot exceed quota for PoliciesPerRole: 15
```

PI-1178 Fix for policy quota limit

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-claim-non-standard-magistrate-fee-prod/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-claim-non-standard-magistrate-fee-prod/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-claim-non-standard-magistrate-fee-prod/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-claim-non-standard-magistrate-fee-prod/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-claim-non-standard-magistrate-fee-prod/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-claim-non-standard-magistrate-fee-prod/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-claim-non-standard-magistrate-fee-prod/resources/rds-postgresql.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-claim-non-standard-magistrate-fee-prod/resources/s3.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-claim-non-standard-magistrate-fee-prod/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-claim-non-standard-magistrate-fee-prod/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-claim-non-standard-magistrate-fee-prod/resources/versions.tf

Creates a production namespace for the CRM7 team for the backend app

Create new namespace for CRM7 prod

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-probation-integration-services-dev/resources/iam.tf

PI-1178 Grant permissions to perform DLQ redrive (dev)

---

namespaces/live.cloud-platform.service.justice.gov.uk/find-unclaimed-court-money-dev/resources/ecr.tf

As per instruction from Senior Dev

Remove github actions prefix

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-video-link-prod/resources/elasticache.tf

Map 32 BVL prod update redis 2

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-estimate-financial-eligibility-for-legal-aid-production/resources/ecr.tf

Enable short-lived ECR credentials for CCQ

EL-965: Enable short-lived credentials for CCQ on Circle

---

namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-prod/07-certificates.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-prod/resources/imb-route53.tf

* Add IMB certificate
* Remove reference to old load balancer to trigger new LB generation.

Hale platform IMB domain switch

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-education-and-work-plan-dev/resources/elasticache-ui.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-education-and-work-plan-dev/resources/variables.tf

Add Redis to hmpps-education-and-work-plan-dev.

Add Redis to education-and-work-plan-dev

---

namespaces/live.cloud-platform.service.justice.gov.uk/use-of-force-dev/resources/elasticache.tf

MAP-38-add skip file and secrets update redis engine

---

namespaces/live.cloud-platform.service.justice.gov.uk/use-of-force-dev/resources/elasticache.tf

Map 38 uof dev update redis 2

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-education-employment-preprod/06-certificate.yaml

Renamed certificates to fix too long name
Updated dnsNames after changing service ingress URLs

ESWE-649 - Certificates - PREPROD

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-education-employment-prod/06-certificate.yaml

Renamed certificates to fix too long name
Updated dnsNames after changing service ingress URLs

ESWE-649 - Certificates - PROD

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-estimate-financial-eligibility-for-legal-aid-production/resources/ecr.tf

Update the CCQ ECR lifecycle policy to accommodate changes to how ECR images are tagged.

EL-965: Adjust CCQ ECR lifecycle

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-api-dev/resources/s3.tf

note: removed secret key and id, as we should attempt use irsa

s3 bucket for dev

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-assure-hmrc-data-staging/resources/irsa.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-assure-hmrc-data-staging/resources/variables.tf

Add IRSA policy
To assist with move short lived credentials on cloud platform

Add IRSA policy

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-interventions-dev/resources/rds-postgres14.tf

Updated dev db instance class to t4g

Updated dev db instance class to t4g

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-api-dev/resources/s3.tf

can ignore the two previous commits, due to being on main
Policy is on the irsa role

NN-5269 no bucket policy

---

namespaces/live.cloud-platform.service.justice.gov.uk/pact-broker-prod/resources/rds-postgres14.tf

Updated pact db instance class to t4g

Updated pact db instance class to t4g

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-education-employment-dev/06-certificate.yaml

ESWE-649 - Certificates DEV

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-education-employment-preprod/06-certificate.yaml

ESWE-649 - Certificates PREPROD

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-education-employment-prod/06-certificate.yaml

ESWE-649 - Certificates PROD

---

namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-gold-scorecard-form-dev/resources/secrets.tf
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-gold-scorecard-form-dev/resources/variables.tf

adding secrets to an application to enable alerts for Prometheus rules

Secret manager gold scorecard

---

namespaces/live.cloud-platform.service.justice.gov.uk/activities-api-dev/resources/irsa.tf
namespaces/live.cloud-platform.service.justice.gov.uk/activities-api-dev/resources/variables.tf

Adds IAM role service account (IRSA) for the activities-api-dev namespace.

SAA-803: Activities IRSA dev

---

namespaces/live.cloud-platform.service.justice.gov.uk/parliamentary-questions-development/resources/ecr.tf
namespaces/live.cloud-platform.service.justice.gov.uk/parliamentary-questions-production/resources/ecr.tf

CDPT-763: PQ: Migrate to circleci short-lived credentials

---

namespaces/live.cloud-platform.service.justice.gov.uk/digital-prison-reporting-mi-prototype/resources/sg.tf

Update SG Name - fix to NAME

---

namespaces/live.cloud-platform.service.justice.gov.uk/legal-framework-api-uat/resources/ecr.tf

Enable short lived credentials for circleci ECR push and pull

AP-4298: Add circleci ECR oidc provider for Legal-framework-api

---

namespaces/live.cloud-platform.service.justice.gov.uk/check-financial-eligibility-staging/resources/rds.tf

see https://github.com/ministryofjustice/cloud-platform-environments/pull/14441

fix: 🐛 update db version pin

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-probation-integration-services-preprod/resources/github-actions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-probation-integration-services-preprod/resources/iam.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-probation-integration-services-preprod/resources/irsa.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-probation-integration-services-preprod/resources/variables.tf

```
LimitExceeded: Cannot exceed quota for PolicySize: 6144
```
https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/environments-live/jobs/apply-namespace-changes-live/builds/7052.1

PI-1226 Separate IAM policies to avoid LimitExceeded error (preprod)

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-proceeding-dev/resources/ecr.tf

Changes made for short lived credentials for circleci

LCAM-636-short-lived-credential-circleci

---

namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-uat/resources/rds.tf

terraform is failing attempting to downgrade rds version

fix: 🐛 rds pinned version

---

.checksum
namespaces/live.cloud-platform.service.justice.gov.uk/cloud-platform-service-pod/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/cloud-platform-service-pod/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/cloud-platform-service-pod/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/cloud-platform-service-pod/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/cloud-platform-service-pod/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/cloud-platform-service-pod/resources/ecr.tf
namespaces/live.cloud-platform.service.justice.gov.uk/cloud-platform-service-pod/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/cloud-platform-service-pod/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/cloud-platform-service-pod/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/cloud-platform-service-pod/resources/versions.tf

This namespace is for the ECR repository and service account that the "service pod" image will be pushed to.

cloud-platform-service-pod: add new environment for supporting resources for service pod

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-probation-integration-services-dev/resources/github-actions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-probation-integration-services-dev/resources/variables.tf

This reverts commit 391f236f4b14548dcdc4d2621ac4d60f2466d7e2.

Revert "PI-1226 Grant IRSA policy to GitHub Actions service account (#14460)

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-hmrc-interface-uat/resources/ecr.tf

Update description in ecr.tf

---

namespaces/live.cloud-platform.service.justice.gov.uk/use-of-force-preprod/resources/elasticache.tf

MAP-38 add skip file, secrets and update redis engine

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-api-preprod/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-api-preprod/07-certificate.yaml

https://dsdmoj.atlassian.net/browse/NN-5137

NN-5137: configure adjudications-insights-api PreProd

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-api-prod/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-adjudications-api-prod/07-certificate.yaml

https://dsdmoj.atlassian.net/browse/NN-5137

NN-5137: configure adjudications-insights-api Prod

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-events-dev/resources/create-and-vary-a-licence-sub-queue.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-events-dev/resources/create-and-vary-a-licence-test1-sub-queue.tf
namespaces/live.cloud-platform.service.justice.gov.uk/offender-events-dev/resources/create-and-vary-a-licence-sub-queue.tf
namespaces/live.cloud-platform.service.justice.gov.uk/offender-events-dev/resources/create-and-vary-a-licence-test1-sub-queue.tf

Making an alteration to #14309 to use a domain event rather than a several prison events for updates to offender details

Changing CVL dev environment to use domain event

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-education-employment-prod/resources/pingdom.tf

Add Pingdom for CIAG Induction

ESWE-656 - CIAG Pingdom

---

namespaces/live.cloud-platform.service.justice.gov.uk/contact-moj-production/09-alerts.yaml

https://github.com/ministryofjustice/cloud-platform/issues/4641

cdpt 780 contact-moj production add alert and update the severity value

---

namespaces/live.cloud-platform.service.justice.gov.uk/peoplefinder-production/10-alerts.yaml

https://github.com/ministryofjustice/cloud-platform/issues/4642

cdpt 780 peoplefinder production update the severity value

---

namespaces/live.cloud-platform.service.justice.gov.uk/disclosure-checker-production/05-alerts.yaml

https://github.com/ministryofjustice/cloud-platform/issues/4637

cdpt 780 disclosure-checker production update the severity value

---

namespaces/live.cloud-platform.service.justice.gov.uk/parliamentary-questions-production/07-alerts.yaml

https://github.com/ministryofjustice/cloud-platform/issues/4640

cdpt 780 pq tracker production update the severity value

---

namespaces/live.cloud-platform.service.justice.gov.uk/family-mediators-api-production/05-alerts.yaml

https://github.com/ministryofjustice/cloud-platform/issues/4643

cdpt 780 family-mediators-api production update the severity value

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-estimate-financial-eligibility-for-legal-aid-production/certificate.yaml

Add a certificate for a custom `.service.gov.uk `domain name for staging and production domain names

CCQ PROD add certificate 

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-estimate-financial-eligibility-for-legal-aid-production/certificate.yaml

CCQ PROD remove staging subdomain cert

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-preprod/resources/rds.tf

aws auto bumped version, now terraform can't downgrade

chore: 🤖 bump minor db version

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-production/resources/ecr.tf

In preparation for deleting this repo

Disable deletion protection ecr-repo-applyforlegalaid-service

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-production/resources/ecr.tf

images now being pushed to repo named in ecr_credentials

Remove repo ecr-repo-applyforlegalaid-service

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-estimate-financial-eligibility-for-legal-aid-staging/resources/pingdom.tf

We now have 2 staging URLs and we want separate pingdom checks for each until we retire the old URL, but both should be integrated with the same Slack channel.

EL-1013: Add Pingdom check for new CCQ Staging URL

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-estimate-financial-eligibility-for-legal-aid-production/resources/pingdom.tf

We now have 2 production URLs and we want separate pingdom checks for each until we retire the old URL, but both should be integrated with the same Slack channel.

EL-1013: Add Pingdom check for new CCQ Production URL

---

namespaces/live.cloud-platform.service.justice.gov.uk/peoplefinder-production/resources/ecr.tf
namespaces/live.cloud-platform.service.justice.gov.uk/peoplefinder-production/resources/elasticsearch.tf
namespaces/live.cloud-platform.service.justice.gov.uk/peoplefinder-production/resources/irsa.tf
namespaces/live.cloud-platform.service.justice.gov.uk/peoplefinder-production/resources/pingdom.tf
namespaces/live.cloud-platform.service.justice.gov.uk/peoplefinder-production/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/peoplefinder-production/resources/route53.tf
namespaces/live.cloud-platform.service.justice.gov.uk/peoplefinder-production/resources/s3.tf
namespaces/live.cloud-platform.service.justice.gov.uk/peoplefinder-production/resources/service-account-github.tf
namespaces/live.cloud-platform.service.justice.gov.uk/peoplefinder-production/resources/variables.tf

Also uses variables where possible across all resources

Add IRSA config for peoplefinder-production

---

namespaces/live.cloud-platform.service.justice.gov.uk/justice-gov-uk-archiver-dev/resources/ecr.tf

This PR fixes a small typo in the ECR module.

Correct a typo in ECR module

---

namespaces/live.cloud-platform.service.justice.gov.uk/use-of-force-prod/resources/elasticache.tf

upgrading to redis 7
NOT to be merged until 20/7/23

MAP-167 add skip file, secrets and update redis engine

---

namespaces/live.cloud-platform.service.justice.gov.uk/keyworker-api-preprod/resources/rds.tf

Postgres database upgrade from 14 to 15.

NN-5295 keyworker api preprod db upgrade from 14 to 15

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-activities-management-preprod/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-activities-management-preprod/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-activities-management-preprod/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-activities-management-preprod/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-activities-management-preprod/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-activities-management-preprod/05-serviceaccount-circleci.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-activities-management-preprod/06-certificate.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-activities-management-preprod/resources/elasticache.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-activities-management-preprod/resources/irsa.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-activities-management-preprod/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-activities-management-preprod/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-activities-management-preprod/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-activities-management-preprod/resources/versions.tf

Creates a new PREPROD namespace which will host the combine API and UI activities services + resources + secrets.

SAA-1014: New namespace for activities management services in preprod

---

namespace-resources-cli-template/resources/prototype/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/pre-sentence-service-prototype/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/pre-sentence-service-prototype/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/pre-sentence-service-prototype/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/pre-sentence-service-prototype/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/pre-sentence-service-prototype/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/pre-sentence-service-prototype/resources/basic-auth.tf
namespaces/live.cloud-platform.service.justice.gov.uk/pre-sentence-service-prototype/resources/ecr.tf
namespaces/live.cloud-platform.service.justice.gov.uk/pre-sentence-service-prototype/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/pre-sentence-service-prototype/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/pre-sentence-service-prototype/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/pre-sentence-service-prototype/resources/versions.tf

We need a new prototype so that we can test with users

Set up namespace for pre-sentence-service

---

.checksum
namespaces/live.cloud-platform.service.justice.gov.uk/laa-not-on-libra-auto-search-application-dev/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-not-on-libra-auto-search-application-dev/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-not-on-libra-auto-search-application-dev/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-not-on-libra-auto-search-application-dev/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-not-on-libra-auto-search-application-dev/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-not-on-libra-auto-search-application-dev/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-not-on-libra-auto-search-application-dev/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-not-on-libra-auto-search-application-dev/resources/versions.tf

Initial scratch environment for the migration of the above LAA application from the LAA LZ to Cloud Platform.

laa-not-on-libra-auto-search-application-dev 

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-activities-management-prod/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-activities-management-prod/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-activities-management-prod/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-activities-management-prod/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-activities-management-prod/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-activities-management-prod/05-serviceaccount-circleci.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-activities-management-prod/06-certificate.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-activities-management-prod/resources/elasticache.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-activities-management-prod/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-activities-management-prod/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-activities-management-prod/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-activities-management-prod/resources/versions.tf

Creates production namespace and resources for activities management services.

SAA-767 activities management production namespace

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-audit-prod/resources/hmpps-activities-management.tf

This creates a secret to reference the HMPPS audit queue for activities management.

SAA0767 audit queue for activities prod

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-not-on-libra-auto-search-application-dev/resources/ecr.tf

ECR resource for laa-not-on-libra-auto-search-application-dev

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-not-on-libra-auto-search-application-dev/resources/ecr.tf

Added necessary namespace reference for the configmap creation.

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-events-preprod/resources/hmpps-prison-visits-event.tf

SUBSCRIBE to queue, this was disabled in the pass because we were not ready to use the messages

VB-2573 PREPROD - Orchestration service, SUBSCRIBE to queue.

---

namespaces/live.cloud-platform.service.justice.gov.uk/offender-management-staging/resources/domain-events-subscription.tf

offender-management-staging: add domain events subscription

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-production/resources/s3-ap-exports.tf

Adding terraform to create user with AP s3 permissions.

Book A Secure Move Prod AP Exports

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-staging/resources/s3-ap-exports.tf

Adding terraform to create user with AP s3 permissions.

Book A Secure Move Staging AP Exports

---

namespaces/live.cloud-platform.service.justice.gov.uk/c100-application-production/resources/redis.tf

DO NOT MERGE UNLESS YOU MEAN TO MERGE TO PRODUCTION

PRODUCTION Update redis.tf to 7.0

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-claim-non-standard-magistrate-fee-dev/resources/ecr.tf

Updating the ECR module in an attempt to move our project from long lived credentials to short lived credentials.

Add OIDC Provider to ECR module

---

namespaces/live.cloud-platform.service.justice.gov.uk/ap-firebreak-superset/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/ap-firebreak-superset/resources/secret.tf
namespaces/live.cloud-platform.service.justice.gov.uk/ap-firebreak-superset/resources/variables.tf

adding secret manager and secrets

Tag resources in aws

---

namespaces/live.cloud-platform.service.justice.gov.uk/ap-firebreak-superset/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/ap-firebreak-superset/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/ap-firebreak-superset/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/ap-firebreak-superset/resources/variables.tf

fixes issues caused by incorrect team_name in values
also fixes depricated github team membership references

fixes to namespace

---

namespaces/live.cloud-platform.service.justice.gov.uk/prisoner-content-hub-development/resources/cloudfront.tf
namespaces/live.cloud-platform.service.justice.gov.uk/prisoner-content-hub-development/resources/s3-cf.tf

This PR adds a new empty S3 bucket with Cloudfront for the dev environment of Prisoner Content Hub.

Cloudfront poc content hub

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-claim-non-standard-magistrate-fee-dev/resources/ecr.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-claim-non-standard-magistrate-fee-dev/resources/irsa.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-claim-non-standard-magistrate-fee-dev/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-claim-non-standard-magistrate-fee-dev/resources/variables.tf

- Adds the IRSA for the S3 module
- Clean up variables to be used

CRM457-345 - Add irsa for S3

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-claim-non-standard-magistrate-fee-uat/resources/irsa.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-claim-non-standard-magistrate-fee-uat/resources/variables.tf

- Adds the IRSA for the S3 module
- Add variables to be used

CRM457-345 - Short lived credentials

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-claim-non-standard-magistrate-fee-prod/resources/irsa.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-claim-non-standard-magistrate-fee-prod/resources/variables.tf

- Adds the IRSA for the S3 module
- Add variables to be used

CRM457-345 - Update to short lived S3 creds

---

namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-dev/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-prod/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-stag/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/cloud-platform-canary-app-eks/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-preprod/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-hpa-preprod/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-intelligence-test/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/manage-intelligence-dev/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/track-a-move-dev/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/track-a-move-prod/resources/versions.tf
namespaces/live.cloud-platform.service.justice.gov.uk/track-a-move-uat/resources/versions.tf

…icorp/random and lagging aws/kubernetes providers

chore: bump cyrilgdn/postgresql, hashicorp/helm, hashicorp/http, hashicorp/random and lagging aws/kubernetes providers

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-cwa-test/resources/serviceaccount.tf

Created service account for cwa namespace

laa-cwa-test-sa | add service account for cwa

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-staging/resources/rds.tf

Step 1 of moving to t4g.small, and v14 this is
supposed to speed up the migration from 11>14

Civil Apply Staging: Increase db_instance

---

.checksum
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-application-store-dev/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-application-store-dev/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-application-store-dev/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-application-store-dev/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-application-store-dev/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-application-store-dev/resources/ecr.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-application-store-dev/resources/irsa.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-application-store-dev/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-application-store-dev/resources/rds-postgresql.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-application-store-dev/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-application-store-dev/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crime-application-store-dev/resources/versions.tf

- Creates a new environment using the cloud-platform cli
- Adds ECR using the cloud-platform cli
- Adds RDS using the cloud-platform cli
- Creates IRSA for short live creds from the start

CRM457-372 - Create new environment for Application Store

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-staging/resources/rds.tf

Update engine to postgres v14 and change the instance_type to t4g.small

Civil Apply Staging: Update Database version and instance_type

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-cwa-test/resources/irsa.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-cwa-test/resources/s3.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-cwa-test/resources/variables.tf

Add irsa and S3 account for cwa test

laa-cwa-test| add irsa s3 account

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-staging/resources/rds.tf

This should allow an upgrade with a following PR removing the specific version and reverting to just `14`

Civil Apply Staging: set specific engine version

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-supervisions-prototype/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-supervisions-prototype/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-supervisions-prototype/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-supervisions-prototype/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-supervisions-prototype/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-supervisions-prototype/resources/basic-auth.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-supervisions-prototype/resources/ecr.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-supervisions-prototype/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-supervisions-prototype/resources/serviceaccount.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-supervisions-prototype/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-supervisions-prototype/resources/versions.tf

This reverts commit 9e2c7eb91e483f97ae45469405d97da4f64c8e4a, reversing changes made to 6aa4371db22c91b7c4af8ed4f3eb91f4471c1d30.

Revert "Merge pull request #14347 from ministryofjustice/ab_PI-1183"

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-apply-for-legalaid-production/resources/rds.tf

This is the next step on moving to generic postgres `14`

Civil-Apply-Production: Update postres to 14.7

---

namespaces/live.cloud-platform.service.justice.gov.uk/offender-management-staging/resources/irsa.tf
namespaces/live.cloud-platform.service.justice.gov.uk/offender-management-staging/resources/variables.tf

offender-management-staging: Set up IRSA, add domain event SQS policies

---

namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-reports-dev/resources/ecr.tf
namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-reports-dev/resources/irsa.tf
namespaces/live.cloud-platform.service.justice.gov.uk/operations-engineering-reports-dev/resources/variables.tf

- :wrench: Add IRSA file for short-lived dynamo credentials
- :green_heart: Use short-lived credentials in ECR configuration

Add short-lived credentials for DynamoDB

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-report-service-dev/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-report-service-dev/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-report-service-dev/06-service-monitor.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-report-service-dev/prometheus-custom-rules-laa-dces-report-service.yaml

Add prometheus hooks to laa-dces-report-service-dev

Add Prometheus to DCES laa-dces-report-service-dev

---

namespaces/live.cloud-platform.service.justice.gov.uk/offender-management-staging/resources/irsa.tf

offender-management-staging: Add IRSA policy for domain events SNS

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-cla-backend-staging/resources/ecr.tf

Added in required namespace name to ecr.tf

LGA-2576 enable OIDC for circleci part 2

---

namespaces/live.cloud-platform.service.justice.gov.uk/offender-management-test/resources/irsa.tf
namespaces/live.cloud-platform.service.justice.gov.uk/offender-management-test/resources/variables.tf

offender-management-test: Add IRSA support

---

.checksum
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-interventions-dev-two/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-interventions-dev-two/01-rbac.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-interventions-dev-two/02-limitrange.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-interventions-dev-two/03-resourcequota.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-interventions-dev-two/04-networkpolicy.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-interventions-dev-two/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-interventions-dev-two/resources/variables.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-interventions-dev-two/resources/versions.tf

Setup new dev namespace for branched development in hmpps-interventions

Create namespace for hmpps-interventions-dev-two

---

namespaces/live.cloud-platform.service.justice.gov.uk/legal-framework-api-staging/04-networkpolicy.yaml

Allow internal routing from from CFE Civil namespaces

LFA-staging: Update NetworkPolicy

---

namespaces/live.cloud-platform.service.justice.gov.uk/legal-framework-api-production/04-networkpolicy.yaml

Allow internal routing from from Civil Apply production and CFE Civil staging and production namespaces

LFA-production: Update NetworkPolicy

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-interventions-dev-two/01-rbac.yaml

Change rbac definition file to be consistent with existing env hmpps-interventions-dev

make rbac config consistent with dev

---

namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-dev/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-dev/resources/rds.tf

and add github team slug to tags

Vsip enable db performance insights dev

---

.github/workflows/po-linter.yaml
.pint.hcl

Configuration Documentation:
https://cloudflare.github.io/pint/configuration.html#parser

feat(Workflow): Move to the cloudflare po linter

---

namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-staging/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/visit-someone-in-prison-backend-svc-staging/resources/rds.tf

also enable auto DB start stop outside business hours

enable RDS performance insights on staging database

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-welcome-to-prison-dev/resources/elasticache.tf

MAP-254 add skip file, secrets and update redis engine

---

namespaces/live.cloud-platform.service.justice.gov.uk/offender-management-preprod/resources/irsa.tf
namespaces/live.cloud-platform.service.justice.gov.uk/offender-management-preprod/resources/variables.tf

offender-management-preprod: Add IRSA support

---

namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-saas-live/resources/metadata_api.tf
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-saas-live/resources/variables.tf

The instance was defaulting to a t2

Set the db instance class to non-default value

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-report-service-uat/prometheus-custom-rules-laa-dces-report-service.yaml

Fix prometheus rule expression. And point to new dashboards.

DCES-UAT-Fix

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-report-service-dev/prometheus-custom-rules-laa-dces-report-service.yaml

Change dashboard url to new dashboard.

DCES-Dev-Fix

---

namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-repos/resources/ecr.tf
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-repos/resources/variables.tf

Migrating to short-lived credentials for CircleCI

Formbuilder: Add ECR credentials

---

namespaces/live.cloud-platform.service.justice.gov.uk/money-to-prisoners-prod/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/money-to-prisoners-prod/resources/s3.tf

… in preparation for when the long-lived access key will not be available

Stop exporting `money-to-prisoners-prod` RDS & S3 access key into k8s secret

---

namespaces/live.cloud-platform.service.justice.gov.uk/grc-dev/resources/rds-postgresql-11.tf

Practice run for db version reversion incase it is needed during prod db upgrade

Rst 5388 dev revert db version practice run

---

namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-uat/resources/ssm.tf

CICA - Add Account ID to param store

---

namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-uat/resources/claim-criminal-injuries-tempus-queue.tf
namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-uat/resources/iam.tf
namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-uat/resources/pushgateway.tf
namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-uat/resources/variables.tf

We are aware that Long Term credentials are being deprecated and need replacing and we're creating further dependencies on them here, but we're looking to get into UAT on Monday and then will be looking to move to service accounts as per the guidance.

CICA - Bring UAT in line with Staging

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-report-service-dev/07-grafana.yaml

DCES Grafana Update

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-welcome-to-prison-prod/resources/elasticache.tf

I'm assuming the rotated_date needs to be date the upgrade is done rather than today.

Map 249 wpip prod update redis 2

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-legal-adviser-api-production/resources/irsa.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-legal-adviser-api-production/resources/sqs.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-legal-adviser-api-production/resources/variables.tf

- Adding irsa config
- Adding sqs resource

Adding irsa config for laa-legal-adviser-api-producion namespace

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-claim-non-standard-magistrate-fee-dev/resources/elasticache.tf

Adds basic Redis pre-production to the laa-claim-non-standard-magistrates-fee-dev environment

Add redis to CRM dev environment

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-report-service-dev/07-grafana.yaml

Change email graph expression.

DCES-Grafana-Email-Modification

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-report-service-dev/07-grafana.yaml

DCES-Grafana-Changes

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-legal-adviser-api-staging/resources/ecr.tf

Hi,
Just removing the long lived credentials for LAA Legal Advisor API

LGA-2586 Updating LAALAA namespace

---

namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-dev/resources/servicepod.tf

Add service pod to namespace to allow running AWS commands on resources used.

Add Service Pod to namespace

---

namespaces/live.cloud-platform.service.justice.gov.uk/make-recall-decision-dev/resources/irsa.tf
namespaces/live.cloud-platform.service.justice.gov.uk/make-recall-decision-dev/resources/variables.tf

IRSA migration for Consider a Recall (Make Recall Decisions)

mrd-1670_migrate-to-irsa-make-recall-decisions-dev

---

namespaces/live.cloud-platform.service.justice.gov.uk/cloud-platform-metrics/resources/secret.tf
namespaces/live.cloud-platform.service.justice.gov.uk/cloud-platform-reports-prod/resources/secret.tf
namespaces/live.cloud-platform.service.justice.gov.uk/sm-dev/resources/secrets.tf

this recreates empty secrets, tokens to be repopulated post merge

bump cp-metrics and reports secrets

---

namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-demo/resources/ecr-feed-parser.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-demo/resources/irsa.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-demo/resources/servicepod.tf

* Add a service pod to run commands on AWS resources
* Add permissions to IRSA to allow aws commands to be run against ECR

Hale platform add service pod

---

namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-staging/resources/ecr-feed-parser.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-staging/resources/irsa.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hale-platform-staging/resources/servicepod.tf

Add a service pod to run commands on AWS resources
Add permissions to IRSA to allow aws commands to be run against ECR
Increase ECR module version to 6.1

Hale platform service pod staging

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-report-service-dev/03-resourcequota.yaml

DCES-107 - Single Application

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-report-service-prod/03-resourcequota.yaml

DCES-107-Single-Pod-Prod

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-report-service-staging/03-resourcequota.yaml

DCES-107-Single-Pod-Staging

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-dces-report-service-dev/07-grafana.yaml

Adding grafana chart to display MAAT API call outcomes.

DCES-103 - Update Grafana chart

---

namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-stag/resources/iam.tf
namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-stag/resources/irsa.tf
namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-stag/resources/variables.tf

Cdi 60 add irsa to staging

---

namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-dev/resources/iam.tf
namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-dev/resources/irsa.tf
namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-dev/resources/variables.tf

Add IRSA for Dev

---

namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-uat/resources/iam.tf
namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-uat/resources/irsa.tf
namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-uat/resources/variables.tf

Add IRSA Module to CICA UAT namespace.

Add IRSA to UAT

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-interventions-dev-two/resources/serviceaccount.tf

Add details of affected repositories

Add pointers to the project repos in serviceaccount.tf

---

namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-environ-surveillance-hub-dev/resources/ecr.tf

remove unneeded namespace pre-reqs (dp-esh-dev)

---

namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-legal-aid-tools-dev/resources/ecr.tf

remove unneeded namespace pre-reqs (dp-lat-dev)

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-assess-non-standard-magistrate-fee-dev/resources/rds-postgresql.tf

To use for deployment pipeline

Add url secret to postgres

---

namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-environ-surveillance-hub-prod/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-environ-surveillance-hub-prod/resources/ecr.tf

remove ecr protection
unset prod flag

remove unneeded namespace pre-reqs (dp-esh-prod)

---

namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-legal-aid-tools-prod/00-namespace.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-legal-aid-tools-prod/resources/ecr.tf

remove ecr protection
unset prod flag

remove unneeded namespace pre-reqs (dp-lat-prod)

---

namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-prod/resources/ssm.tf

As per the other three environments. Will need updating manually in parameter store - appreciate Secrets Manager has been introduced since first implementing this method however given timescales of go-live would prefer to stick with this approach given account IDs won't change and this is the final environment.

[CICA] - Add Prod Account ID

---

namespaces/live.cloud-platform.service.justice.gov.uk/peoplefinder-development/resources/opensearch.tf

Also changes output name for secret

peoplefinder-dev remove skip file

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-launchpad-auth-dev/01-rbac.yaml

adding kind, name, apiGroup in rbac file under subjects for hmpps launchpad auth dev

adding kind, name, apiGroup in rbac file under subjects 

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-criminal-applications-datastore-staging/resources/irsa.tf

Fix irsa service account name format for datastore staging namespace

Fix irsa service account name format

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-court-data-adaptor-dev/resources/messaging-queues.tf

This reverts commit 3429b94f1ff0cbc19d968b96695ba8a93e946fea.

LASB-2396: Limit SQS access to IAM Role from Landing Zone

---

namespaces/live.cloud-platform.service.justice.gov.uk/cccd-dev/resources/messaging.tf

Adds policy for the receive queue so that we can send back messages from Landing Zone

CTSKF-574 - Add policy for receive queue

---

namespaces/live.cloud-platform.service.justice.gov.uk/cccd-dev/resources/messaging.tf

Fixes resource within the policy

CTSKF-574 - Fix Resource Policy

---

namespaces/live.cloud-platform.service.justice.gov.uk/cccd-dev/resources/messaging.tf

Update to use the right resource name

CTSKF-574 - Use correct queue resource

---

namespaces/live.cloud-platform.service.justice.gov.uk/cccd-staging/resources/messaging.tf

Updates UAT policies to use tested dev policies

CTSKF-574 - Update UAT policies

---

namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-prod/prometheus-sqs-alerts.yaml
namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-prod/resources/claim-criminal-injuries-application-queue.tf
namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-prod/resources/claim-criminal-injuries-notify-queue.tf
namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-prod/resources/claim-criminal-injuries-tempus-queue.tf
namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-prod/resources/iam.tf
namespaces/live.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-prod/resources/irsa.tf

This includes adding the Tempus SQS queue as well as the required clean-up around IRSA migration.

[CICA] - CICA Prod Infra Updates

---

namespaces/live.cloud-platform.service.justice.gov.uk/cccd-production/resources/messaging.tf

Adds policies for queues to allow for access from landing zone

CTSKF-574 - Add policies for SQS for prod env

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-education-and-work-plan-preprod/05-serviceaccount-circleci.yaml

Add service account config for CircleCI, as detailed here: https://kubernetes.io/docs/concepts/configuration/secret/#service-account-token-secrets

RR-279 - Add circleci-token config

---

namespaces/live.cloud-platform.service.justice.gov.uk/prisoner-content-hub-production/resources/s3.tf

🔧 Use new staging cloud bucket ID for content sync.

---

namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-test-dev/resources/service-metadata-bucket.tf
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-test-dev/resources/user-filestore.tf
namespaces/live.cloud-platform.service.justice.gov.uk/formbuilder-platform-test-dev/resources/variables.tf

Replace s3 user policies with irsa definitions in formbuilder-platform-test-dev

Migrating to IRSA S3 access

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-proceeding-staging/resources/main.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-proceeding-staging/resources/secret.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-proceeding-staging/resources/variables.tf

**NOTE: PR includes a team_name change, so will manually need to arrange for the current ECR to be emptied of images in order for it to be deleted and recreated with the new name.**

LCAM 878 Added CCP staging client creds to secret manager

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-events-prod/resources/curious-update.tf
namespaces/live.cloud-platform.service.justice.gov.uk/laa-cla-backend-staging/resources/s3.tf

Removed long-lived credentials from the laa-cla-backend-staging's S3 Bucket Terraform file

laa-cla-backend-staging Removed user policy from S3 buckets

---

namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-production/resources/route53.tf

- Remove rAPId zone delegation
- Remove PagerDuty status page records

🔥 Clean up Data Platform Route53 records

---

namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-complexity-of-need-preprod/resources/irsa.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-complexity-of-need-preprod/resources/rds.tf
namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-complexity-of-need-preprod/resources/variables.tf

Try to standardize variables.tf between environments as well

hmpps-complexity-of-need-preprod: Add IRSA support

---

namespaces/live.cloud-platform.service.justice.gov.uk/laa-cla-backend-training/resources/s3.tf

Removed long-lived credentials from the laa-cla-backend-training's S3 Bucket Terraform file

Removed user policy from laa-cla-backend-training S3 Bucket
